NAME = 'FreStapfer1889: Le Nouveau Testament traduction de Stapfer - 1889'
BOOK = 'Colossians'

CHAPTERS = {
    1: {
        1: 'Paul, apôtre de Jésus-Christ, par la volonté de Dieu, et, le frère Timothée',
        2: 'aux frères en Christ, fidèles et croyants, qui sont à Colosses. Grâce et paix vous soient accordées par Dieu notre Père.',
        3: 'Nous rendons sans cesse des actions de grâces pour vous au Dieu et Père de notre Seigneur Jésus-Christ dans nos prières;',
        4: "car on nous a raconté votre foi en Jésus-Christ et l'amour que vous éprouvez pour tous les fidèles,",
        5: 'votre espérance enfin qui sera récompensée dans le ciel. On vous a parlé autrefois de ces choses quand on vous a annoncé la vérité évangélique.',
        6: "L'Évangile est au milieu de vous, comme, du reste, dans le monde entier. Il y porte des fruits, il y gagne du terrain comme il l'a fait chez vous depuis le jour où vous avez appris à connaître la vérité, c'est-à-dire la grâce de Dieu.",
        7: "C'est Épaphras, notre bien-aimé compagnon de service, qui vous a instruits; ce fidèle ministre du Christ auprès de nous",
        8: "nous a fait connaître les sentiments d'amour que l'Esprit vous inspire.",
        9: "Et alors nous, depuis le jour où nous avons appris tout cela, nous ne cessons de prier pour vous; nous demandons à Dieu que vous appreniez à connaître tout à fait sa volonté, avec cette entière sagesse et cette intelligence que donne l'Esprit.",
        10: "Vous vivrez ainsi d'une manière digne du Seigneur, vous le satisferez entièrement. Vous porterez toute espèce de bons fruits, vous ferez des progrès dans la connaissance de Dieu.",
        11: 'Vous serez admirablement fortifiés par sa glorieuse puissance; vous serez remplis de patience, de persévérance, de joie.',
        12: "Vous rendrez des actions de grâces à notre Père qui vous a mis à même d'avoir un jour votre part de l'héritage des fidèles dans la lumière,",
        13: 'qui nous a arrachés au pouvoir des ténèbres, qui nous a transportés dans le Royaume de son Fils bien-aimé;',
        14: 'car par lui nous sommes rachetés, délivrés de nos péchés.',
        15: 'Il est une image du Dieu invisible, il est né le premier de tous les êtres créés;',
        16: "c'est en lui, en effet, que tout a été créé, tout ce qui est dans le ciel, tout ce qui est sur la terre, ce qui est visible et ce qui est invisible, les trônes, les seigneuries, les autorités, les puissances, tout a été créé par lui et pour lui.",
        17: 'Il est avant toutes choses et toutes choses subsistent en lui.',
        18: "Il est la tête du corps, c'est-à-dire le chef de l'Église; il est le principe; il est le premier-né d'entre les morts, afin d'être partout à la première place.",
        19: "En effet, c'est en lui que Dieu a voulu que sa plénitude entière résidât;",
        20: "c'est par lui qu'il a voulu tout réconcilier avec lui-même, et ce qui est sur la terre et ce qui est dans le ciel; par lui il a rétabli la paix au moyen du sang versé sur la croix.",
        21: "Autrefois vous lui étiez étrangers, vous étiez ses ennemis par vos pensées et vos mauvaises oeuvres; aujourd'hui le Christ vous a réconciliés",
        22: 'par la mort de son corps, de sa chair, pour vous faire comparaître devant lui, saints, sans tache et sans reproche;',
        23: "si du moins vous restez attachés à la foi, fermes, inébranlables, sans vous écarter de l'espérance apportée par l'Évangile que vous avez entendu, Évangile prêché à toute créature sous le ciel, et dont moi, Paul, je suis devenu le ministre.",
        24: "Je suis maintenant dans la joie en souffrant pour vous; et ce, qui manquait encore aux souffrances du Christ, je le complète moi-même pour le bien de son corps, je veux dire de l'Église",
        25: "dont je suis devenu le ministre. C'est Dieu qui m'a confié cette charge; je dois vous annoncer le plein accomplissement de la parole de Dieu,",
        26: "le mystère caché de tout temps et à tous les peuples, mais qu'il a aujourd'hui révélé à ses fidèles.",
        27: "Dieu a voulu leur faire connaître toute la glorieuse richesse de ce mystère à l'égard des païens, c'est-à-dire: Christ en vous, l'espérance de la gloire!",
        28: 'Nous le prêchons; nous exhortons, nous instruisons chaque homme avec une entière sagesse, pour présenter à Dieu chaque homme devenu parfait en Christ.',
        29: "C'est à cela que je travaille, pour cela que je lutte, grâce à sa force qui agit puissamment en moi.",
    },
    2: {
        1: 'Je tiens à ce que vous sachiez toute la grandeur de ce combat que je livre pour vous, pour les Laodicéens, pour tous ceux qui ne me connaissent pas de vue,',
        2: "j'y tiens pour réconforter leurs coeurs, pour que l'amour les unisse, pour qu'ils aient une intelligence riche et complète, qu'ils connaissent le mystère de Dieu, de Christ,",
        3: 'où sont «... cachés tous les trésors» de la sagesse et de la science.',
        4: 'Je vous dis cela pour que personne ne vous trompe par de spécieux raisonnements.',
        5: 'Si je suis absent de corps, je suis cependant avec vous en esprit, heureux de voir votre bon ordre et la fermeté de votre foi en Christ.',
        6: 'Comme vous avez appris à connaître le Christ, Jésus, le Seigneur, vivez ainsi en lui,',
        7: "greffés, édifiés sur lui, affermis dans la foi, telle qu'on vous l'a enseignée, et montrez beaucoup de reconnaissance.",
        8: "Faites attention à celui qui voudrait vous accaparer avec de la philosophie, trompeuse illusion, enseignement purement humain, tout élémentaire et mondain, qui n'est pas selon Christ.",
        9: "Car c'est en lui que réside réellement toute la plénitude de la divinité.",
        10: 'Et vous, vous êtes remplis de lui, le chef de toute autorité et de tout pouvoir.',
        11: 'En lui aussi vous avez été circoncis; je ne parle pas de la circoncision que font les hommes, mais de celle du Christ, du dépouillement de votre corps charnel.',
        12: "Vous avez été ensevelis avec lui au moyen du baptême, où vous êtes aussi ressuscités avec lui, par la foi en la puissance de Dieu qui l'a ressuscité d'entre les morts.",
        13: 'Vous étiez morts par vos péchés, et par votre incirconcision charnelle, et il vous a fait revivre avec lui; il nous a pardonné tous nos péchés,',
        14: "il a effacé l'acte qui était contre nous, dont les clauses nous étaient contraires, il l'a mis de côté en le clouant sur la croix,",
        15: "il a dépouillé les autorités et les puissances, il les a victorieusement données en spectacle, il a triomphé d'elles par le Christ!",
        16: 'Que personne ne vienne donc vous critiquer pour un mets, une boisson, un jour de fête, de nouvelle lune ou pour des sabbats,',
        17: "tout cela n'est que l'ombre de ce qui devait venir; la réalité est en Christ.",
        18: "Ne vous laissez pas enlever votre prix par ceux qui font les humbles, rendent un culte aux anges, spéculent sur des rêveries, que leurs idées charnelles remplissent d'un vain orgueil,",
        19: "et qui ne s'attachent pas au chef, dont le corps entier pourvu de nerfs et de muscles, et soutenu par eux, prend le développement que Dieu lui donne.",
        20: 'Si vous êtes morts avec Christ aux enseignements élémentaires et mondains, pourquoi, comme si vous viviez encore dans le monde, vous faites-vous des règlements:',
        21: "«Ne touche pas ceci, ne goûte pas cela; n'approche pas de ceci; tout cela te souillera, si tu en fais usage.»",
        22: '«Ce sont les hommes qui enseignent et commandent ces choses.»',
        23: "Elles ont sans doute un certain air de sagesse, c'est un culte volontaire, plein d'humilité et de dureté pour le corps, mais elles n'ont aucune valeur et ne servent qu'à satisfaire les sens.",
    },
    3: {
        1: 'Si vous êtes ressuscités avec le Christ, recherchez les choses, qui sont en haut, où le Christ est «Assis à la droite de Dieu;»',
        2: 'pensez aux choses qui sont en haut et non à celles qui sont sur la terre,',
        3: 'car vous êtes morts et votre vie est cachée avec le Christ en Dieu;',
        4: 'et quand, un jour, le Christ qui est votre vie aura paru, vous, vous apparaîtrez avec lui dans la gloire.',
        5: "Mortifiez donc vos membres, ceux qui sont de la terre, la débauche, l'impureté, la luxure, les passions coupables et l'avarice (elle est une idolâtrie).",
        6: 'Voilà ce qui attire la colère de Dieu,',
        7: 'et voilà ce que, vous aussi, vous avez fait autrefois; oui, vous avez vécu dans ces désordres.',
        8: "Mais aujourd'hui vous devez vous défaire de tout ce qui est colère, emportement, méchanceté, médisance; ne prononcez plus de mots inconvenants;",
        9: "ne vous dites pas de mensonge l'un à l'autre; débarrassez-vous du vieil homme et de ses oeuvres,",
        10: "et revêtez-vous du nouvel homme, qui se renouvelle à l'image de son Créateur",
        11: "et arrive à comprendre l'état où il n'y a ni Grec ni Juif, ni circoncis ni incirconcis, ni étranger ni barbare, ni esclave ni homme libre, mais où Christ est tout et en tous.",
        12: "Vous, les élus de Dieu, les fidèles, les bien-aimés, montrez des coeurs pleins de pitié, de bonté, d'humilité, de douceur, de patience.",
        13: "Supportez-vous les uns les autres; pardonnez-vous mutuellement quand l'un de vous a à se plaindre de son prochain; faites comme, le Seigneur qui vous a pardonné.",
        14: "Par-dessus tout, montrez de l'amour; c'est lui qui réunit toutes les perfections.",
        15: "Que dans vos coeurs règne la paix du Christ; vous y avez été appelés pour ne former qu'un seul et même corps. Soyez reconnaissants.",
        16: 'Que la parole du Christ demeure en vous dans toute sa richesse. Instruisez-vous, avertissez-vous les uns les autres avec une grande sagesse. Que des psaumes, des hymnes, des chants spirituels montent à Dieu de vos coeurs reconnaissants.',
        17: 'Quoi que vous fassiez, que vous parliez, que vous agissiez, faites tout au nom du Seigneur Jésus, en rendant grâces par lui à Dieu le Père.',
        18: 'Vous, femmes, soyez soumises à vos maris, comme il convient quand on est au Seigneur.',
        19: 'Vous, maris, aimez vos femmes et ne vous irritez pas contre elles.',
        20: 'Vous, enfants, obéissez en tout à vos parents, car cela est agréable au Seigneur.',
        21: "Vous, pères, ne tourmentez pas vos enfants, de peur qu'ils ne se découragent.",
        22: "Vous, esclaves, obéissez en tout à ceux qui sont vos maîtres sur la terre; ne les servez pas seulement quand ils vous voient, comme si vous n'aviez à plaire qu'à des hommes; mais servez-les en toute simplicité de coeur et en craignant le Seigneur.",
        23: "Dans tout ce que vous faites, travaillez de toute votre âme, comme s'il s'agissait du Seigneur et non des hommes.",
        24: "Vous savez que vous recevrez du Seigneur en récompense l'héritage céleste. Soyez les esclaves de Christ le Seigneur.",
        25: "Celui qui aura fait le mal sera puni pour ce mal; il n'y aura point d'acception de personnes.",
    },
    4: {
        1: 'Vous, maîtres, fournissez à vos esclaves ce qui est juste, équitable; vous savez que vous avez, vous aussi, un maître au ciel.',
        2: 'Dans vos prières montrez de la persévérance, de la vigilance, de la reconnaissance.',
        3: "En même temps, priez pour nous, que Dieu nous ouvre une porte, que nous parlions, que nous prêchions le mystère du Christ. C'est pour lui que je porte la chaîne;",
        4: "demandez que je le fasse connaître comme je dois l'annoncer.",
        5: 'Conduisez-vous avec prudence envers ceux du dehors, et profitez bien des moments opportuns.',
        6: 'Que vos paroles soient toujours aimables, pleines de saveur, de manière à savoir répondre à chacun comme il faut.',
        7: "Vous apprendrez tout ce qui me concerne personnellement par Tychique, mon bien-aimé frère, mon aide fidèle, mon collègue dans l'oeuvre du Seigneur.",
        8: "Je vous l'envoie tout exprès pour cela, pour que vous sachiez où en sont nos affaires, et qu'il console vos coeurs.",
        9: "Avec lui est notre fidèle et bien-aimé frère, Onésime, l'un de vos compatriotes. Ils vous informeront de tout ce qui se passe ici.",
        10: "Vous avez les salutations d'Aristarque, mon compagnon de prison, et celles de Marc, le cousin de Barnabas (vous avez reçu des avis à son sujet; quand il viendra vous voir, faites-lui bon accueil),",
        11: 'celles de Jésus dit Justus. Ce sont les seuls circoncis qui aient travaillé avec moi pour le Royaume de Dieu; ils ont été pour moi une véritable force.',
        12: "Vous avez aussi les salutations de votre compatriote Épaphras; c'est un serviteur de Jésus-Christ; il lutte sans cesse pour vous dans ses prières, pour que vous persistiez dans votre parfaite et entière soumission à toute la volonté de Dieu.",
        13: "Je lui rends le témoignage qu'il est plein de sollicitude pour vous ainsi que pour les frères de Laodicée et de Hiérapolis.",
        14: 'Vous avez les salutations de mon bien-aimé Luc, le médecin, et celles de Démas.',
        15: "Nous saluons nos frères de Laodicée ainsi que Nymphas et l'Église qui s'assemble dans leur maison.",
        16: "Quand vous aurez lu cette lettre, ayez soin qu'elle soit lue aussi de l'Église de Laodicée et lisez à votre tour celle qu'on vous enverra de Laodicée.",
        17: 'Dites à Archippe: Prends garde de bien remplir le ministère que tu as reçu de la part du Seigneur.',
        18: "Je vous salue en écrivant moi-même: Paul. N'oubliez pas que je suis en prison. La grâce soit avec vous.",
    },
}
