NAME = 'PorNVA: Bíblia Nova Versão de Acesso Livre'
BOOK = 'Colossians'

CHAPTERS = {
    1: {
        1: 'Paulo, apóstolo de Jesus Cristo, de acordo com a vontade de Deus, e Timóteo, nosso irmão,',
        2: 'para os santos e fiéis irmãos em Cristo que estão em Colossos. Graça a vós, e paz da parte de Deus nosso Pai.',
        3: 'Damos graças a Deus, Pai do nosso Senhor Jesus Cristo, e sempre oramos por vós.',
        4: 'Nós ouvimos da vossa fé em Cristo Jesus e do amor que tendes para com todos os santos de Deus,',
        5: 'por causa da esperança reservada para vós nos céus. Vós primeiro ouvistes sobre esta esperança na Palavra da verdade, o Evangelho,',
        6: 'que chegou a vós. E que também está produzindo fruto e crescendo em todo o mundo, tal como também em vós, desde o dia que o ouvistes e conhecestes a graça de Deus na verdade.',
        7: 'Este é o Evangelho que aprendestes com Epafras, nosso amado conservo e companheiro, o qual é um fiel ministro de Cristo, em nosso favor.',
        8: 'Ele nos relatou do vosso amor no Espírito.',
        9: 'Por esta razão, também nós, desde o dia em que o ouvimos, não cessamos de orar e suplicar para que sejais cheios do conhecimento da sua vontade, em toda sabedoria e entendimento espiritual.',
        10: 'Nós oramos para que andeis dignamente no Senhor, para o seu inteiro agrado, frutificando em toda boa obra e crescendo no conhecimento de Deus.',
        11: 'Oramos para que sejais fortalecidos com todo o poder, segundo a força da sua glória, em toda perseverança e paciência.',
        12: 'Oramos para que deis graças ao Pai com alegria, que vos capacitou para receber uma parte da herança dos santos na luz.',
        13: 'Ele nos resgatou do poder das trevas e nos transportou para o Reino do Seu Filho amado.',
        14: 'Em quem temos redenção, isto é, o perdão dos pecados.',
        15: 'Ele é a imagem do Deus invisível, o primogênito de toda criação.',
        16: 'Pois, Nele, todas as coisas foram criadas, quer nos céus e sobre a terra, as visíveis e as invisíveis; quer tronos ou domínios, ou governos ou autoridades, todas as coisas foram criadas por Ele e para Ele.',
        17: 'Ele é antes de todas as coisas, e todas as coisas Nele subsistem.',
        18: 'Ele é a cabeça do corpo, que é a igreja. Ele é o princípio, o primogênito dentre os mortos; assim, Ele tem o primeiro lugar em todas as coisas.',
        19: 'Porquanto, agradou a Deus que toda Sua plenitude, Nele, habitasse,',
        20: 'e que havendo feito a paz pelo sangue da sua cruz, por meio dele, reconciliasse consigo mesmo todas as coisas, quer sobre a terra, quer nos céus.',
        21: 'E vós também, outrora, éreis estranhos a Deus e Seus inimigos em vossas mentes e por vossas más obras.',
        22: 'Mas, agora, vos reconciliou no corpo da sua carne, mediante a Sua morte, para vos apresentar santos, inculpáveis e irrepreensíveis perante Ele,',
        23: 'se continuardes na fé, alicerçados e firmes, não sendo removidos da esperança do Evangelho que ouvistes, que foi proclamado em toda a criação debaixo dos céus. O Evangelho do qual eu, Paulo, me tornei ministro.',
        24: 'Agora, me alegro em meus sofrimentos por vós, e completo, na minha carne, o que está faltando das aflições de Cristo a favor do Seu corpo, que é a igreja.',
        25: 'Esta é a igreja da qual sou ministro, segundo a responsabilidade que recebi de Deus, que me foi confiada em favor de vós, para cumprir a Palavra de Deus.',
        26: 'Este é o mistério oculto desde os séculos e gerações, mas agora foi manisfestado aos seus santos,',
        27: 'para quem Deus quis fazer conhecidas as riquezas da Sua glória do mistério entre os gentios, isto é, Cristo em vós, a esperança da glória.',
        28: 'Este é o Cristo que nós proclamamos. Nós admoestamos a todos, os ensinando em toda sabedoria; para que possamos apresentá-los completos em Cristo.',
        29: 'Por isso, eu me esforço e luto, de acordo com a Sua força que opera em mim com poder.',
    },
    2: {
        1: 'Quero que saibais quão grande é a luta que tenho enfrentado por vós, pelos de Laodiceia e por todos quantos não me conhecem pessoalmente,',
        2: 'para que vossos corações sejam encorajados pela comunhão, em amor, e pelas riquezas da plenitude do entendimento e conhecimento do mistério de Deus, que é Cristo.',
        3: 'Nele estão escondidos todos os tesouros da sabedoria e do entendimento.',
        4: 'Digo-vos isso para que nenhum de vós seja iludido com palavras persuasivas.',
        5: 'E, apesar de eu não estar convosco em carne, embora esteja em espírito, alegro-me em ver a ordem e a firmeza da vossa fé em Cristo.',
        6: 'Assim como recebestes Cristo, o Senhor, andai Nele',
        7: 'e Nele estai firmemente plantados e edificados; estabelecidos na fé, tal como fostes instruídos, e abundantes em ações de graças.',
        8: 'Cuidai para que ninguém vos escravize com filosofias e vãs sutilezas, de acordo com a tradição dos homens, conforme os rudimentos do mundo, e não segundo Cristo;',
        9: 'porque Nele habita, corporalmente, toda a plenitude da natureza de Deus.',
        10: 'E Nele, que é o Cabeça de todo poder e autoridade, fostes levados à plenitude.',
        11: 'Por meio Dele, fostes também circuncidados, não com a circuncisão feita por mãos humanas na remoção do corpo carnal, mas por meio da circuncisão de Cristo.',
        12: 'Vós fostes sepultados com Ele no batismo e Nele fostes ressuscitados pela fé no poder de Deus, que O ressuscitou dentre os mortos.',
        13: 'Quando estáveis mortos nas vossas transgressões e na incircuncisão da vossa carne, deu-vos vida, juntamente com Ele, perdoando todos os nossos delitos;',
        14: 'Ele cancelou todos os escritos de débito contra nós em Seus mandamentos. Ele removeu tudo isso, cravando-os na cruz.',
        15: 'Ele desarmou os governos e as autoridades, e os expôs em público, vencendo-os na cruz.',
        16: 'Portanto, ninguém vos julgue pelo comer ou beber, ou por causa do dia de festa ou da lua nova ou pelos sábados.',
        17: 'Tudo isso é uma sombra das coisas futuras, mas a realidade é Cristo.',
        18: 'Que ninguém vos desqualifique, fingindo humildade e adoração dos anjos. Tais pessoas baseiam-se em visões, inchadas pela arrogância de sua mente carnal,',
        19: 'e não se apoiam na Cabeça. É da cabeça que todo o corpo, através de suas junções e ligamentos, é mantido coeso, recebe sustento e cresce com o crescimento dado por Deus.',
        20: 'Visto que morrestes juntamente com Cristo para os elementos do mundo, por que viveis como submissos às crenças deste mundo, tais como:',
        21: '"Não pegues, não proves, não toques"?',
        22: 'Todos esses preceitos e ensinamentos humanos estão fadados ao desaparecimento pelo uso.',
        23: 'Essas regras têm uma aparência de sabedoria, com falsa devoção, falsa humildade e severidade para com o corpo; mas não têm qualquer valor no combate aos desejos da carne.',
    },
    3: {
        1: 'Se então Deus vos ressuscitou com Cristo, procurai as coisas que são do alto, onde Cristo está assentado à direita de Deus.',
        2: 'Pensai nas coisas que são do alto, não nas que são terrenas,',
        3: 'porque já morrestes e vossa vida está escondida com Cristo em Deus.',
        4: 'Quando Cristo, que é vossa vida, for revelado, então, vós também sereis revelados com Ele em glória.',
        5: 'Portanto, mortificai os desejos pecaminosos da natureza terrena: imoralidade sexual, impureza, paixões, maus desejos e a ganância, que é idolatria.',
        6: 'É por causa dessas coisas que a ira de Deus vem sobre os filhos da desobediência.',
        7: 'E foi nestas coisas que uma vez andastes no passado, quando vivíeis nelas.',
        8: 'Mas agora deveis vos despir de todas estas coisas: ira, raiva, más intenções, insultos e palavras obscenas dos vossos lábios.',
        9: 'Não mintais uns aos outros, porque já vos despistes do velho homem e suas práticas,',
        10: 'e vos revestistes do novo homem, o qual é renovado para o pleno conhecimento, segundo a imagem Daquele que o criou.',
        11: 'Sendo assim, não há grego nem judeu, circuncisão ou incircuncisão, nem bárbaro nem cita, nem escravo nem livre, mas Cristo é tudo e está em todos.',
        12: 'Portanto, revesti-vos pois, como eleitos de Deus, santos e amados, de profundos sentimentos de misericórdia, bondade, humildade, mansidão e paciência.',
        13: 'Suportai-vos uns aos outros, sede graciosos uns para com os outros. Se alguém tem algo contra outrem, perdoai da mesma forma que o Senhor vos perdoou.',
        14: 'Sobre todas estas coisas, está o amor, que é o vínculo da perfeição.',
        15: 'Que a paz de Cristo governe os vossos corações. Foi nesta paz que vós fostes chamados em um só corpo; e sede agradecidos.',
        16: 'Que a palavra de Cristo habite em vós ricamente. Com toda sabedoria, ensinai e admoestai-vos uns aos outros com salmos, hinos e cânticos espirituais. Cantai com gratidão a Deus em vossos corações.',
        17: 'Qualquer coisa que façais em palavras ou ações, fazei tudo em nome do Senhor Jesus, dando graças a Deus Pai por meio Dele.',
        18: 'Esposas, sede submissas aos vossos maridos, como convém no Senhor.',
        19: 'Maridos, amai vossas esposas e não as trateis com amargura.',
        20: 'Filhos, obedecei aos vossos pais em todas as coisas, porque isso é agradável ao Senhor.',
        21: 'Pais, não irriteis os vossos filhos, para que eles não sejam desencorajados.',
        22: 'Escravos, obedecei aos vossos senhores em todas as coisas, não somente quando eles estão olhando para os bajular, mas com um coração sincero, que teme ao Senhor.',
        23: 'O que quer que façais, fazei-o de todo coração como para o Senhor e não para homens.',
        24: 'Sabendo que recebereis do Senhor a recompensa da vossa herança. É ao Senhor Jesus a quem servis.',
        25: 'Pois qualquer um que praticar injustiça receberá a penalidade pela injustiça que fez, e não há parcialidade.',
    },
    4: {
        1: 'Senhores, dai aos escravos o que é correto e justo, sabendo que também tendes um Senhor no céu.',
        2: 'Continuai firmes em oração, vigiando com ação de graças.',
        3: 'Orai, ao mesmo tempo, também por nós, para que Deus nos abra a porta da Palavra, a fim de falarmos do mistério de Cristo, pelo qual estou preso;',
        4: 'e orai para que eu possa falar claramente, que é como devo fazer.',
        5: 'Andai com sabedoria diante daqueles que são de fora; usai o tempo sabiamente.',
        6: 'Sejam vossas palavras sempre agradáveis, temperadas com sal, para que saibais como deveis responder a cada um.',
        7: 'Tíquico vos fará conhecer todas as coisas a meu respeito. Ele é um irmão amado, um ministro fiel, e um cooperador no serviço do Senhor.',
        8: 'Eu o enviei especificamente para que vós possais saber sobre nossa situação e, também, que ele possa consolar vossos corações,',
        9: 'junto com Onésimo, irmão amado e fiel. Eles vos farão conhecer tudo o que está sendo feito aqui.',
        10: 'Aristarco, meu companheiro de prisão, vos cumprimenta, bem como Marcos, primo de Barnabé (de quem recebestes instruções; se ele vier a vós, recebei-o),',
        11: 'e Jesus, que é também chamado de Justo. Apenas estes da circuncisão são meus cooperadores de trabalho pelo Reino de Deus. Eles têm sido um consolo para mim.',
        12: 'Epafras, servo de Cristo Jesus e vosso conterrâneo, vos cumprimenta, sempre lutando por vós em oração, para que vos torneis completos, cheios de toda vontade de Deus.',
        13: 'Pois sou testemunha de que ele trabalha duro por vós, pelos de Laodiceia e pelos de Hierápolis.',
        14: 'Lucas, o médico amado, e Demas, vos cumprimentam.',
        15: 'Cumprimentai os irmãos de Laodiceia, e Ninfa e a igreja que está em sua casa.',
        16: 'Quando esta carta for lida perante vós, que também seja lida na igreja dos laodicenses, e certificai de ler, também, a carta de Laodiceia.',
        17: 'Dizei a Arquipo: "Atenta para o ministério que tens recebido no Senhor, para que o completes".',
        18: 'Estas saudações são de meu próprio punho, Paulo. Lembrai das minhas algemas. A graça seja convosco.',
    },
}
