NAME = 'VulgSistine: Vulgata Sistina'
BOOK = 'Proverbs'

CHAPTERS = {
    1: {
        1: 'Parabolae Salomonis, filii David, regis Israel.',
        2: 'Ad sciendam sapientiam, et disciplinam:',
        3: 'ad intelligenda verba prudentiae: et suscipiendam eruditionem doctrinae, iustitiam, et iudicium, et aequitatem:',
        4: 'ut detur parvulis astutia, adolescenti scientia, et intellectus.',
        5: 'Audiens sapiens, sapientior erit: et intelligens, gubernacula possidebit.',
        6: 'Animadvertet parabolam, et interpretationem, verba sapientum, et aenigmata eorum.',
        7: 'Timor Domini principium sapientiae. Sapientiam, atque doctrinam stulti despiciunt.',
        8: 'Audi, fili mi, disciplinam patris tui, et ne dimittas legem matris tuae:',
        9: 'ut addatur gratia capiti tuo, et torques collo tuo.',
        10: 'Fili mi, si te lactaverint peccatores, ne acquiescas eis.',
        11: 'Si dixerint: Veni nobiscum, insidiemur sanguini, abscondamus tendiculas contra insontem frustra:',
        12: 'deglutiamus eum sicut infernus viventem, et integrum quasi descendentem in lacum.',
        13: 'Omnem pretiosam substantiam reperiemus, implebimus domos nostras spoliis.',
        14: 'Sortem mitte nobiscum, marsupium unum sit omnium nostrum.',
        15: 'Fili mi, ne ambules cum eis, prohibe pedem tuum a semitis eorum.',
        16: 'Pedes enim illorum ad malum currunt, et festinant ut effundant sanguinem.',
        17: 'Frustra autem iacitur rete ante oculos pennatorum.',
        18: 'Ipsi quoque contra sanguinem suum insidiantur, et moliuntur fraudes contra animas suas.',
        19: 'Sic semitae omnis avari, animas possidentium rapiunt.',
        20: 'Sapientia foris praedicat, in plateis dat vocem suam:',
        21: 'in capite turbarum clamitat, in foribus portarum urbis profert verba sua, dicens:',
        22: 'Usquequo parvuli diligitis infantiam, et stulti ea, quae sibi sunt noxia, cupient, et imprudentes odibunt scientiam?',
        23: 'Convertimini ad correptionem meam: en proferam vobis spiritum meum, et ostendam vobis verba mea.',
        24: 'Quia vocavi, et renuistis: extendi manum meam, et non fuit qui aspiceret.',
        25: 'Despexistis omne consilium meum, et increpationes meas neglexistis.',
        26: 'Ego quoque in interitu vestro ridebo, et subsannabo, cum vobis id, quod timebatis, advenerit.',
        27: 'Cum irruerit repentina calamitas, et interitus quasi tempestas ingruerit: quando venerit super vos tribulatio, et angustia:',
        28: 'Tunc invocabunt me, et non exaudiam: mane consurgent, et non invenient me:',
        29: 'eo quod exosam habuerint disciplinam, et timorem Domini non susceperint,',
        30: 'nec acquieverint consilio meo, et detraxerint universae correptioni meae.',
        31: 'Comedent igitur fructus viae suae, suisque consiliis saturabuntur.',
        32: 'Aversio parvulorum interficiet eos, et prosperitas stultorum perdet illos.',
        33: 'Qui autem me audierit, absque terrore requiescet, et abundantia perfruetur, timore malorum sublato.',
    },
    2: {
        1: 'Fili mi, si susceperis sermones meos, et mandata mea absconderis penes te,',
        2: 'ut audiat sapientiam auris tua: inclina cor tuum ad cognoscendam prudentiam.',
        3: 'Si enim sapientiam invocaveris, et inclinaveris cor tuum prudentiae:',
        4: 'si quaesieris eam quasi pecuniam, et sicut thesauros effoderis illam:',
        5: 'tunc intelliges timorem Domini, et scientiam Dei invenies:',
        6: 'quia Dominus dat sapientiam: et ex ore eius prudentia, et scientia.',
        7: 'Custodiet rectorum salutem, et proteget gradientes simpliciter,',
        8: 'servans semitas iustitiae, et vias sanctorum custodiens.',
        9: 'Tunc intelliges iustitiam, et iudicium, et aequitatem, et omnem semitam bonam.',
        10: 'Si intraverit sapientia cor tuum, et scientia animae tuae placuerit:',
        11: 'consilium custodiet te, et prudentia servabit te,',
        12: 'ut eruaris a via mala, et ab homine, qui perversa loquitur:',
        13: 'qui relinquunt iter rectum, et ambulant per vias tenebrosas:',
        14: 'qui laetantur cum malefecerint, et exultant in rebus pessimis:',
        15: 'quorum viae perversae sunt, et infames gressus eorum.',
        16: 'Ut eruaris a muliere aliena, et ab extranea, quae mollit sermones suos,',
        17: 'et relinquit ducem pubertatis suae,',
        18: 'et pacti Dei sui oblita est. inclinata est enim ad mortem domus eius, et ad inferos semitae ipsius.',
        19: 'omnes, qui ingrediuntur ad eam, non revertentur, nec apprehendent semitas vitae.',
        20: 'Ut ambules in via bona: et calles iustorum custodias.',
        21: 'Qui enim recti sunt, habitabunt in terra, et simplices permanebunt in ea.',
        22: 'Impii vero de terra perdentur: et qui inique agunt, auferentur ex ea.',
    },
    3: {
        1: 'Fili mi, ne obliviscaris legis meae, et praecepta mea cor tuum custodiat.',
        2: 'longitudinem enim dierum, et annos vitae, et pacem apponent tibi.',
        3: 'Misericordia, et veritas te non deserant, circumda eas gutturi tuo, et describe in tabulis cordis tui:',
        4: 'et invenies gratiam, et disciplinam bonam coram Deo et hominibus.',
        5: 'Habe fiduciam in Domino ex toto corde tuo, et ne innitaris prudentiae tuae.',
        6: 'In omnibus viis tuis cogita illum, et ipse diriget gressus tuos.',
        7: 'Ne sis sapiens apud temetipsum: time Deum, et recede a malo:',
        8: 'sanitas quippe erit umbilico tuo, et irrigatio ossium tuorum.',
        9: 'Honora Dominum de tua substantia, et de primitiis omnium frugum tuarum da pauperibus:',
        10: 'et implebuntur horrea tua saturitate, et vino torcularia tua redundabunt.',
        11: 'Disciplinam Domini, fili mi, ne abiicias: nec deficias cum ab eo corriperis:',
        12: 'quem enim diligit Dominus, corripit: et quasi pater in filio complacet sibi.',
        13: 'Beatus homo, qui invenit sapientiam, et qui affluit prudentia:',
        14: 'melior est acquisitio eius negotiatione auri, et argenti primi et purissimi fructus eius:',
        15: 'pretiosior est cunctis opibus: et omnia, quae desiderantur, huic non valent comparari.',
        16: 'Longitudo dierum in dextera eius, et in sinistra illius divitiae, et gloria.',
        17: 'Viae eius viae pulchrae, et omnes semitae illius pacificae.',
        18: 'Lignum vitae est his, qui apprehenderint eam: et qui tenuerit eam, beatus.',
        19: 'Dominus sapientia fundavit terram, stabilivit caelos prudentia.',
        20: 'Sapientia illius eruperunt abyssi, et nubes rore concrescunt.',
        21: 'Fili mi, ne effluant haec ab oculis tuis: Custodi legem atque consilium:',
        22: 'et erit vita animae tuae, et gratia faucibus tuis.',
        23: 'tunc ambulabis fiducialiter in via tua, et pes tuus non impinget:',
        24: 'si dormieris, non timebis: quiesces, et suavis erit somnus tuus.',
        25: 'ne paveas repentino terrore, et irruentes tibi potentias impiorum.',
        26: 'Dominus enim erit in latere tuo, et custodiet pedem tuum ne capiaris.',
        27: 'Noli prohibere benefacere eum, qui potest: si vales, et ipse benefac:',
        28: 'Ne dicas amico tuo: Vade, et revertere: cras dabo tibi: cum statim possis dare.',
        29: 'Ne moliaris amico tuo malum, cum ille in te habeat fiduciam.',
        30: 'Ne contendas adversus hominem frustra, cum ipse tibi nihil mali fecerit.',
        31: 'Ne aemuleris hominem iniustum, nec imiteris vias eius:',
        32: 'quia abominatio Domini est omnis illusor, et cum simplicibus sermocinatio eius.',
        33: 'Egestas a Domino in domo impii: habitacula autem iustorum benedicentur.',
        34: 'Ipse deludet illusores, et mansuetis dabit gratiam.',
        35: 'Gloriam sapientes possidebunt: stultorum exaltatio, ignominia.',
    },
    4: {
        1: 'Audite filii disciplinam patris, et attendite ut sciatis prudentiam.',
        2: 'Donum bonum tribuam vobis, legem meam ne derelinquatis.',
        3: 'Nam et ego filius fui patris mei, tenellus, et unigenitus coram matre mea:',
        4: 'et docebat me, atque dicebat: Suscipiat verba mea cor tuum, custodi praecepta mea, et vives.',
        5: 'Posside sapientiam, posside prudentiam: ne obliviscaris, neque declines a verbis oris mei.',
        6: 'Ne dimittas eam, et custodiet te: dilige eam, et conservabit te.',
        7: 'Principium sapientiae, posside sapientiam, et in omni possessione tua acquire prudentiam:',
        8: 'arripe illam, et exaltabit te: glorificaberis ab ea, cum eam fueris amplexatus.',
        9: 'dabit capiti tuo augmenta gratiarum, et corona inclyta proteget te.',
        10: 'Audi fili mi, et suscipe verba mea, ut multiplicentur tibi anni vitae.',
        11: 'Viam sapientiae monstrabo tibi, ducam te per semitas aequitatis:',
        12: 'quas cum ingressus fueris, non arctabuntur gressus tui, et currens non habebis offendiculum.',
        13: 'Tene disciplinam, ne dimittas eam: custodi illam, quia ipsa est via tua.',
        14: 'Ne delecteris in semitis impiorum, nec tibi placeat malorum via.',
        15: 'Fuge ab ea, nec transeas per illam: declina, et desere eam.',
        16: 'non enim dormiunt nisi malefecerint: et non capitur somnus ab eis nisi supplantaverint.',
        17: 'comedunt panem impietatis, et vinum iniquitatis bibunt.',
        18: 'Iustorum autem semita quasi lux splendens, procedit et crescit usque ad perfectam diem.',
        19: 'Via impiorum tenebrosa: nesciunt ubi corruant.',
        20: 'Fili mi, ausculta sermones meos, et ad eloquia mea inclina aurem tuam.',
        21: 'ne recedant ab oculis tuis, custodi ea in medio cordis tui:',
        22: 'vita enim sunt invenientibus ea, et universae carni sanitas.',
        23: 'Omni custodia serva cor tuum, quia ex ipso vita procedit.',
        24: 'Remove a te os pravum, et detrahentia labia sint procul a te.',
        25: 'Oculi tui recta videant, et palpebrae tuae praecedant gressus tuos.',
        26: 'Dirige semitam pedibus tuis, et omnes viae tuae stabilientur.',
        27: 'Ne declines ad dexteram, neque ad sinistram: averte pedem tuum a malo. vias enim, quae a dextris sunt, novit Dominus: perversae vero sunt quae a sinistris sunt. Ipse autem rectos faciet cursus tuos, itinera autem tua in pace producet.',
    },
    5: {
        1: 'Fili mi, attende ad sapientiam meam, et prudentiae meae inclina aurem tuam,',
        2: 'ut custodias cogitationes, et disciplinam labia tua conservent. Ne attendas fallaciae mulieris.',
        3: 'favus enim distillans labia meretricis, et nitidius oleo guttur eius.',
        4: 'novissima autem illius amara quasi absinthium, et acuta quasi gladius biceps.',
        5: 'Pedes eius descendunt in mortem, et ad inferos gressus illius penetrant.',
        6: 'Per semitam vitae non ambulant, vagi sunt gressus eius, et investigabiles.',
        7: 'Nunc ergo fili mi audi me, et ne recedas a verbis oris mei.',
        8: 'Longe fac ab ea viam tuam, et ne appropinques foribus domus eius.',
        9: 'Ne des alienis honorem tuum, et annos tuos crudeli.',
        10: 'ne forte implentur extranei viribus tuis, et labores tui sint in domo aliena,',
        11: 'et gemas in novissimis, quando consumpseris carnes tuas et corpus tuum, et dicas:',
        12: 'Cur detestatus sum disciplinam, et increpationibus non acquievit cor meum,',
        13: 'nec audivi vocem docentium me, et magistris non inclinavi aurem meam?',
        14: 'Pene fui in omni malo, in medio ecclesiae et synagogae.',
        15: 'Bibe aquam de cisterna tua, et fluenta putei tui:',
        16: 'Deriventur fontes tui foras, et in plateis aquas tuas divide.',
        17: 'Habeto eas solus, nec sint alieni participes tui.',
        18: 'Sit vena tua benedicta, et laetare cum muliere adolescentiae tuae:',
        19: 'cerva charissima, et gratissimus hinnulus. ubera eius inebrient te in omni tempore, in amore eius delectare iugiter.',
        20: 'Quare seduceris fili mi ab aliena, et foveris in sinu alterius?',
        21: 'Respicit Dominus vias hominis, et omnes gressus eius considerat.',
        22: 'Iniquitates suas capiunt impium, et funibus peccatorum suorum constringitur.',
        23: 'Ipse morietur, quia non habuit disciplinam, et in multitudine stultitiae suae decipietur.',
    },
    6: {
        1: 'Fili mi, si spoponderis pro amico tuo, defixisti apud extraneum manum tuam,',
        2: 'illaqueatus es verbis oris tui, et captus propriis sermonibus.',
        3: 'Fac ergo quod dico fili mi, et temetipsum libera: quia incidisti in manum proximi tui. Discurre, festina, suscita amicum tuum:',
        4: 'ne dederis somnum oculis tuis, nec dormitent palpebrae tuae.',
        5: 'Eruere quasi damula de manu, et quasi avis de manu aucupis.',
        6: 'Vade ad formicam o piger, et considera vias eius, et disce sapientiam:',
        7: 'quae cum non habeat ducem, nec praeceptorem, nec principem,',
        8: 'parat in aestate cibum sibi, et congregat in messe quod comedat.',
        9: 'Usquequo piger dormies? quando consurges e somno tuo?',
        10: 'Paululum dormies, paululum dormitabis, paululum conseres manus ut dormias:',
        11: 'et veniet tibi quasi viator, egestas, et pauperies quasi vir armatus. Si vero impiger fueris, veniet ut fons messis tua, et egestas longe fugiet a te.',
        12: 'Homo apostata, vir inutilis, graditur ore perverso,',
        13: 'annuit oculis, terit pede, digito loquitur,',
        14: 'pravo corde machinatur malum, et omni tempore iurgia seminat.',
        15: 'huic extemplo veniet perditio sua, et subito conteretur, nec habebit ultra medicinam.',
        16: 'Sex sunt, quae odit Dominus, et septimum detestatur anima eius:',
        17: 'Oculos sublimes, linguam mendacem, manus effundentes innoxium sanguinem,',
        18: 'cor machinans cogitationes pessimas, pedes veloces ad currendum in malum,',
        19: 'proferentem mendacia testem fallacem, et eum, qui seminat inter fratres discordias.',
        20: 'Conserva fili mi praecepta patris tui, et ne dimittas legem matris tuae.',
        21: 'Liga ea in corde tuo iugiter, et circumda gutturi tuo.',
        22: 'Cum ambulaveris, gradiantur tecum: cum dormieris, custodiant te, et evigilans loquere cum eis.',
        23: 'quia mandatum lucerna est, et lex lux, et via vitae increpatio disciplinae:',
        24: 'ut custodiant te a muliere mala, et a blanda lingua extraneae.',
        25: 'Non concupiscat pulchritudinem eius cor tuum, nec capiaris nutibus illius:',
        26: 'pretium enim scorti vix est unius panis: mulier autem viri pretiosam animam capit.',
        27: 'Numquid potest homo abscondere ignem in sinu suo, ut vestimenta illius non ardeant?',
        28: 'aut ambulare super prunas, ut non comburantur plantae eius?',
        29: 'sic qui ingreditur ad mulierem proximi sui, non erit mundus cum tetigerit eam.',
        30: 'Non grandis est culpa, cum quis furatus fuerit: ut esurientem impleat animam:',
        31: 'deprehensus tamen reddet septuplum, et omnem substantiam domus suae tradet.',
        32: 'Qui autem adulter est, propter cordis inopiam perdet animam suam:',
        33: 'turpitudinem et ignominiam congregat sibi, et opprobrium illius non delebitur.',
        34: 'quia zelus et furor viri non parcet in die vindictae,',
        35: 'nec acquiescet cuiusquam precibus, nec suscipiet pro redemptione dona plurima.',
    },
    7: {
        1: 'Fili mi, custodi sermones meos, et praecepta mea reconde tibi. Fili',
        2: 'serva mandata mea, et vives: et legem meam quasi pupillam oculi tui:',
        3: 'liga eam in digitis tuis, scribe illam in tabulis cordis tui.',
        4: 'Dic sapientiae, soror mea es: et prudentiam voca amicam tuam,',
        5: 'ut custodiant te a muliere extranea, et ab aliena, quae verba sua dulcia facit.',
        6: 'De fenestra enim domus meae per cancellos prospexi,',
        7: 'et video parvulos, considero vecordem iuvenem,',
        8: 'qui transit per plateam iuxta angulum, et prope viam domus illius, graditur',
        9: 'in obscuro, advesperascente die, in noctis tenebris, et caligine.',
        10: 'Et ecce occurrit illi mulier ornatu meretricio, praeparata ad decipiendas animas: garrula, et vaga,',
        11: 'quietis impatiens, nec valens in domo consistere pedibus suis,',
        12: 'nunc foris, nunc in plateis, nunc iuxta angulos insidians.',
        13: 'Apprehensumque deosculatur iuvenem, et procaci vultu blanditur, dicens:',
        14: 'Victimas pro salute vovi, hodie reddidi vota mea.',
        15: 'idcirco egressa sum in occursum tuum, desiderans te videre, et reperi.',
        16: 'Intexui funibus lectulum meum, stravi tapetibus pictis ex Aegypto.',
        17: 'aspersi cubile meum myrrha, et aloe, et cinnamomo.',
        18: 'Veni, inebriemur uberibus, et fruamur cupitis amplexibus, donec illucescat dies.',
        19: 'non est enim vir in domo sua, abiit via longissima.',
        20: 'sacculum pecuniae secum tulit: in die plenae lunae reversurus est in domum suam.',
        21: 'Irretivit eum multis sermonibus, et blanditiis labiorum protraxit illum.',
        22: 'Statim eam sequitur quasi bos ductus ad victimam, et quasi agnus lasciviens, et ignorans quod ad vincula stultus trahatur,',
        23: 'donec transfigat sagitta iecur eius: velut si avis festinet ad laqueum, et nescit quod de periculo animae illius agitur.',
        24: 'Nunc ergo fili mi, audi me, et attende verbis oris mei.',
        25: 'Ne abstrahatur in viis illius mens tua: neque decipiaris semitis eius.',
        26: 'multos enim vulneratos deiecit, et fortissimi quique interfecti sunt ab ea.',
        27: 'Viae inferi domus eius, penetrantes in interiora mortis.',
    },
    8: {
        1: 'Numquid non sapientia clamitat, et prudentia dat vocem suam?',
        2: 'In summis, excelsisque verticibus supra viam, in mediis semitis stans,',
        3: 'iuxta portas civitatis in ipsis foribus loquitur, dicens:',
        4: 'O viri, ad vos clamito, et vox mea ad filios hominum.',
        5: 'Intelligite parvuli astutiam, et insipientes animadvertite.',
        6: 'Audite, quoniam de rebus magnis locutura sum: et aperientur labia mea, ut recta praedicent.',
        7: 'Veritatem meditabitur guttur meum, et labia mea detestabuntur impium.',
        8: 'Iusti sunt omnes sermones mei, non est in eis pravum quid, neque perversum.',
        9: 'recti sunt intelligentibus, et aequi invenientibus scientiam.',
        10: 'Accipite disciplinam meam, et non pecuniam: doctrinam magis, quam aurum eligite.',
        11: 'Melior est enim sapientia cunctis opibus pretiosissimis: et omne desiderabile ei non potest comparari.',
        12: 'Ego sapientia habito in consilio, et eruditis intersum cogitationibus.',
        13: 'Timor Domini odit malum: arrogantiam, et superbiam, et viam pravam, et os bilingue detestor.',
        14: 'Meum est consilium, et aequitas, mea est prudentia, mea est fortitudo.',
        15: 'Per me reges regnant, et legum conditores iusta decernunt:',
        16: 'Per me principes imperant, et potentes decernunt iustitiam.',
        17: 'Ego diligentes me diligo: et qui mane vigilant ad me, invenient me.',
        18: 'Mecum sunt divitiae, et gloria, opes superbae, et iustitia.',
        19: 'Melior est enim fructus meus auro, et lapide pretioso, et genimina me argento electo.',
        20: 'In viis iustitiae ambulo, in medio semitarum iudicii,',
        21: 'ut ditem diligentes me, et thesauros eorum repleam.',
        22: 'Dominus possedit me in initio viarum suarum, antequam quidquam faceret a principio.',
        23: 'Ab aeterno ordinata sum, et ex antiquis antequam terra fieret.',
        24: 'Nondum erant abyssi, et ego iam concepta eram: necdum fontes aquarum eruperant:',
        25: 'necdum montes gravi mole constiterant: ante colles ego parturiebar:',
        26: 'adhuc terram non fecerat, et flumina, et cardines orbis terrae.',
        27: 'Quando praeparabat caelos, aderam: quando certa lege, et gyro vallabat abyssos:',
        28: 'quando aethera firmabat sursum, et librabat fontes aquarum:',
        29: 'quando circumdabat mari terminum suum, et legem ponebat aquis, ne transirent fines suos: quando appendebat fundamenta terrae:',
        30: 'Cum eo eram cuncta componens: et delectabar per singulos dies, ludens coram eo omni tempore;',
        31: 'ludens in orbe terrarum: et deliciae meae esse, cum filiis hominum.',
        32: 'Nunc ergo filii audite me: Beati, qui custodiunt vias meas.',
        33: 'Audite disciplinam, et estote sapientes, et nolite abiicere eam.',
        34: 'Beatus homo qui audit me, et qui vigilat ad fores meas quotidie, et observat ad postes ostii mei.',
        35: 'Qui me invenerit, inveniet vitam, et hauriet salutem a Domino:',
        36: 'qui autem in me peccaverit, laedet animam suam. Omnes, qui me oderunt, diligunt mortem.',
    },
    9: {
        1: 'Sapientia aedificavit sibi domum, excidit columnas septem.',
        2: 'Immolavit victimas suas, miscuit vinum, et proposuit mensam suam.',
        3: 'Misit ancillas suas ut vocarent ad arcem, et ad moenia civitatis:',
        4: 'Siquis est parvulus, veniat ad me. Et insipientibus locuta est:',
        5: 'Venite, comedite panem meum, et bibite vinum quod miscui vobis.',
        6: 'Relinquite infantiam, et vivite, et ambulate per vias prudentiae.',
        7: 'Qui erudit derisorem, ipse iniuriam sibi facit: et qui arguit impium, sibi maculam generat.',
        8: 'Noli arguere derisorem, ne oderit te. Argue sapientem, et diliget te.',
        9: 'Da sapienti occasionem, et addetur ei sapientia. Doce iustum, et festinabit accipere.',
        10: 'Principium sapientiae timor Domini: et scientia sanctorum, prudentia.',
        11: 'Per me enim multiplicabuntur dies tui, et addentur tibi anni vitae.',
        12: 'Si sapiens fueris, tibimetipsi eris: si autem illusor, solus portabis malum.',
        13: 'Mulier stulta et clamosa, plenaque illecebris, et nihil omnino sciens,',
        14: 'sedit in foribus domus suae super sellam in excelso urbis loco,',
        15: 'ut vocaret transeuntes per viam, et pergentes itinere suo:',
        16: 'Qui est parvulus, declinet ad me. Et vecordi locuta est:',
        17: 'Aquae furtivae dulciores sunt, et panis absconditus suavior.',
        18: 'Et ignoravit quod ibi sint gigantes, et in profundis inferni convivae eius.',
    },
    10: {
        1: 'Filius sapiens laetificat patrem: filius vero stultus moestitia est matris suae.',
        2: 'Nil proderunt thesauri impietatis: iustitia vero liberabit a morte.',
        3: 'Non affliget Dominus fame animam iusti, et insidias impiorum subvertet.',
        4: 'Egestatem operata est manus remissa: manus autem fortium divitias parat. Qui nititur mendaciis, hic pascit ventos: idem autem ipse sequitur aves volantes.',
        5: 'Qui congregat in messe, filius sapiens est: qui autem stertit aestate, filius confusionis.',
        6: 'Benedictio Domini super caput iusti: os autem impiorum operit iniquitas.',
        7: 'Memoria iusti cum laudibus: et nomen impiorum putrescet.',
        8: 'Sapiens corde praecepta suscipit: stultus caeditur labiis.',
        9: 'Qui ambulat simpliciter, ambulat confidenter: qui autem depravat vias suas, manifestus erit.',
        10: 'Qui annuit oculo, dabit dolorem: et stultus labiis verberabitur.',
        11: 'Vena vitae, os iusti: et os impiorum operit iniquitatem.',
        12: 'Odium suscitat rixas: et universa delicta operit charitas.',
        13: 'In labiis sapientis invenitur sapientia: et virga in dorso eius qui indiget corde.',
        14: 'Sapientes abscondunt scientiam: os autem stulti confusioni proximum est.',
        15: 'Substantia divitis, urbs fortitudinis eius: pavor pauperum, egestas eorum.',
        16: 'Opus iusti ad vitam: fructus autem impii ad peccatum.',
        17: 'Via vitae, custodienti disciplinam: qui autem increpationes relinquit, errat.',
        18: 'Abscondunt odium labia mendacia: qui profert contumeliam, insipiens est.',
        19: 'In multiloquio non deerit peccatum: qui autem moderatur labia sua prudentissimus est.',
        20: 'Argentum electum, lingua iusti: cor autem impiorum pro nihilo.',
        21: 'Labia iusti erudiunt plurimos: qui autem indocti sunt, in cordis egestate morientur.',
        22: 'Benedictio Domini divites facit, nec sociabitur eis afflictio.',
        23: 'Quasi per risum stultus operatur scelus: sapientia autem est viro prudentia.',
        24: 'Quod timet impius, veniet super eum: desiderium suum iustus dabitur.',
        25: 'Quasi tempestas transiens non erit impius: iustus autem quasi fundamentum sempiternum.',
        26: 'Sicut acetum dentibus, et fumus oculis, sic piger his, qui miserunt eum.',
        27: 'Timor Domini apponet dies: et anni impiorum breviabuntur.',
        28: 'Expectatio iustorum laetitia: spes autem impiorum peribit.',
        29: 'Fortitudo simplicis via Domini: et pavor his, qui operantur malum.',
        30: 'Iustus in aeternum non commovebitur: impii autem non habitabunt super terram.',
        31: 'Os iusti parturiet sapientiam: lingua pravorum peribit.',
        32: 'Labia iusti considerant placita: et os impiorum perversa.',
    },
    11: {
        1: 'Statera dolosa, abominatio est apud Deum: et pondus aequum, voluntas eius.',
        2: 'Ubi fuerit superbia, ibi erit et contumelia: ubi autem est humilitas, ibi et sapientia.',
        3: 'Simplicitas iustorum diriget eos: et supplantatio perversorum vastabit illos.',
        4: 'Non proderunt divitiae in die ultionis: iustitia autem liberabit a morte.',
        5: 'Iustitia simplicis diriget viam eius: et in impietate sua corruet impius.',
        6: 'Iustitia rectorum liberabit eos: et in insidiis suis capientur iniqui.',
        7: 'Mortuo homine impio, nulla erit ultra spes: et expectatio solicitorum peribit.',
        8: 'Iustus de angustia liberatus est: et tradetur impius pro eo.',
        9: 'Simulator ore decipit amicum suum: iusti autem liberabuntur scientia.',
        10: 'In bonis iustorum exultabit civitas: et in perditione impiorum erit laudatio.',
        11: 'Benedictione iustorum exaltabitur civitas: et ore impiorum subvertetur.',
        12: 'Qui despicit amicum suum, indigens corde est: vir autem prudens tacebit.',
        13: 'Qui ambulat fraudulenter, revelat arcana: qui autem fidelis est, celat amici commissum.',
        14: 'Ubi non est gubernator, populus corruet: salus autem, ubi multa consilia.',
        15: 'Affligetur malo, qui fidem facit pro extraneo: qui autem cavet laqueos, securus erit.',
        16: 'Mulier gratiosa inveniet gloriam: et robusti habebunt divitias.',
        17: 'Benefacit animae suae vir misericors: qui autem crudelis est, etiam propinquos abiicit.',
        18: 'Impius facit opus instabile: seminanti autem iustitiam merces fidelis.',
        19: 'Clementia praeparat vitam: et sectatio malorum mortem.',
        20: 'Abominabile Domino cor pravum: et voluntas eius in iis, qui simpliciter ambulant.',
        21: 'Manus in manu non erit innocens malus: semen autem iustorum salvabitur.',
        22: 'Circulus aureus in naribus suis, mulier pulchra et fatua.',
        23: 'Desiderium iustorum omne bonum est: praestolatio impiorum furor.',
        24: 'Alii dividunt propria, et ditiores fiunt: alii rapiunt non sua, et semper in egestate sunt.',
        25: 'Anima, quae benedicit, impinguabitur: et qui inebriat, ipse quoque inebriabitur.',
        26: 'Qui abscondit frumenta, maledicetur in populis: benedictio autem super caput vendentium.',
        27: 'Bene consurgit diluculo qui quaerit bona: qui autem investigator malorum est, opprimetur ab eis.',
        28: 'Qui confidit in divitiis suis, corruet: iusti autem quasi virens folium germinabunt.',
        29: 'Qui conturbat domum suam, possidebit ventos: et qui stultus est, serviet sapienti.',
        30: 'Fructus iusti lignum vitae: et qui suscipit animas, sapiens est.',
        31: 'Si iustus in terra recipit, quanto magis impius et peccator?',
    },
    12: {
        1: 'Qui diligit disciplinam, diligit scientiam: qui autem odit increpationes, insipiens est.',
        2: 'Qui bonus est, hauriet gratiam a Domino: qui autem confidit in cogitationibus suis, impie agit,',
        3: 'Non roborabitur homo ex impietate: et radix iustorum non commovebitur.',
        4: 'Mulier diligens, corona est viro suo: et putredo in ossibus eius, quae confusione res dignas gerit.',
        5: 'Cogitationes iustorum iudicia: et consilia impiorum fraudulenta:',
        6: 'Verba impiorum insidiantur sanguini: os iustorum liberabit eos.',
        7: 'Verte impios, et non erunt: domus autem iustorum permanebit.',
        8: 'Doctrina sua noscitur vir: qui autem vanus et excors est, patebit contemptui.',
        9: 'Melior est pauper et sufficiens sibi, quam gloriosus et indigens pane.',
        10: 'Novit iustus iumentorum suorum animas: viscera autem impiorum crudelia.',
        11: 'Qui operatur terram suam, satiabitur panibus: qui autem sectatur otium, stultissimus est. Qui suavis est in vini morationibus, in suis munitionibus relinquit contumeliam.',
        12: 'Desiderium impii monumentum est pessimorum: radix autem iustorum proficiet.',
        13: 'Propter peccata labiorum ruina proximat malo: effugiet autem iustus de angustia.',
        14: 'De fructu oris sui unusquisque replebitur bonis, et iuxta opera manuum suarum retribuetur ei.',
        15: 'Via stulti recta in oculis eius: qui autem sapiens est, audit consilia.',
        16: 'Fatuus statim indicat iram suam: qui autem dissimulat iniuriam, callidus est.',
        17: 'Qui quod novit loquitur, iudex iustitiae est: qui autem mentitur, testis est fraudulentus.',
        18: 'Est qui promittit, et quasi gladio pungitur conscientiae: lingua autem sapientium sanitas est.',
        19: 'Labium veritatis firmum erit in perpetuum: qui autem testis est repentinus, concinnat linguam mendacii.',
        20: 'Dolus in corde cogitantium mala: qui autem pacis ineunt consilia, sequitur eos gaudium.',
        21: 'Non contristabit iustum quidquid ei acciderit: impii autem replebuntur malo.',
        22: 'Abominatio est Domino labia mendacia: qui autem fideliter agunt, placent ei.',
        23: 'Homo versatus celat scientiam: et cor insipientium provocat stultitiam.',
        24: 'Manus fortium dominabitur: quae autem remissa est, tributis serviet.',
        25: 'Moeror in corde viri humiliabit illum, et sermone bono laetificabitur.',
        26: 'Qui negligit damnum propter amicum, iustus est: iter autem impiorum decipiet eos.',
        27: 'Non inveniet fraudulentus lucrum: et substantia hominis erit auri pretium.',
        28: 'In semita iustitiae, vita: iter autem devium ducit ad mortem.',
    },
    13: {
        1: 'Filius sapiens, doctrina patris: qui autem illusor est, non audit cum arguitur.',
        2: 'De fructu oris sui homo satiabitur bonis: anima autem praevaricatorum iniqua.',
        3: 'Qui custodit os suum, custodit animam suam: qui autem inconsideratus est ad loquendum, sentiet mala.',
        4: 'Vult et non vult piger: anima autem operantium impinguabitur.',
        5: 'Verbum mendax iustus detestabitur: impius autem confundit, et confundetur.',
        6: 'Iustitia custodit innocentis viam: impietas autem peccatorem supplantat.',
        7: 'Est quasi dives cum nihil habeat: et est quasi pauper, cum in multis divitiis sit.',
        8: 'Redemptio animae viri, divitiae suae: qui autem pauper est, increpationem non sustinet.',
        9: 'Lux iustorum laetificat: lucerna autem impiorum extinguetur.',
        10: 'Inter superbos semper iurgia sunt: qui autem agunt omnia cum consilio, reguntur sapientia.',
        11: 'Substantia festinata minuetur: quae autem paulatim colligitur manu, multiplicabitur.',
        12: 'Spes, quae differtur, affligit animam: lignum vitae desiderium veniens.',
        13: 'Qui detrahit alicui rei, ipse se in futurum obligat: qui autem timet praeceptum, in pace versabitur. Animae dolosae errant in peccatis: iusti autem misericordes sunt, et miserantur.',
        14: 'Lex sapientis fons vitae, ut declinet a ruina mortis.',
        15: 'Doctrina bona dabit gratiam: in itinere contemptorum vorago.',
        16: 'Astutus omnia agit cum consilio: qui autem fatuus est, aperit stultitiam.',
        17: 'Nuncius impii cadet in malum: legatus autem fidelis, sanitas.',
        18: 'Egestas, et ignominia ei, qui deserit disciplinam: qui autem acquiescit arguenti, glorificabitur.',
        19: 'Desiderium si compleatur, delectat animam: detestantur stulti eos, qui fugiunt mala.',
        20: 'Qui cum sapientibus graditur, sapiens erit: amicus stultorum similis efficietur.',
        21: 'Peccatores persequitur malum: et iustis retribuentur bona.',
        22: 'Bonus reliquit heredes filios, et nepotes: et custoditur iusto substantia peccatoris.',
        23: 'Multi cibi in novalibus patrum: et aliis congregantur absque iudicio.',
        24: 'Qui parcit virgae, odit filium suum: qui autem diligit illum, instanter erudit.',
        25: 'Iustus comedit, et replet animam suam: venter autem impiorum insaturabilis.',
    },
    14: {
        1: 'Sapiens mulier aedificat domum suam: insipiens extructam quoque manibus destruet.',
        2: 'Ambulans recto itinere, et timens Deum, despicitur ab eo, qui infami graditur via.',
        3: 'In ore stulti virga superbiae: labia autem sapientium custodiunt eos.',
        4: 'Ubi non sunt boves, praesepe vacuum est: ubi autem plurimae segetes, ibi manifesta est fortitudo bovis.',
        5: 'Testis fidelis non mentietur: profert autem mendacium dolosus testis.',
        6: 'Quaerit derisor sapientiam, et non invenit: doctrina prudentium facilis.',
        7: 'Vade contra virum stultum, et nescit labia prudentiae.',
        8: 'Sapientia callidi est intelligere viam suam: et imprudentia stultorum errans.',
        9: 'Stultis illudet peccatum, et inter iustos morabitur gratia.',
        10: 'Cor quod novit amaritudinem animae suae, in gaudio eius non miscebitur extraneus.',
        11: 'Domus impiorum delebitur: tabernacula vero iustorum germinabunt.',
        12: 'Est via, quae videtur homini iusta: novissima autem eius deducunt ad mortem.',
        13: 'Risus dolore miscebitur, et extrema gaudii luctus occupat.',
        14: 'Viis suis replebitur stultus, et super eum erit vir bonus.',
        15: 'Innocens credit omni verbo: astutus considerat gressus suos. Filio doloso nihil erit boni: servo autem sapienti prosperi erunt actus, et dirigetur via eius.',
        16: 'Sapiens timet, et declinat a malo: stultus transilit, et confidit.',
        17: 'Impatiens operabitur stultitiam: et vir versutus odiosus est.',
        18: 'Possidebunt parvuli stultitiam, et expectabunt astuti scientiam.',
        19: 'Iacebunt mali ante bonos: et impii ante portas iustorum.',
        20: 'Etiam proximo suo pauper odiosus erit: amici vero divitum multi.',
        21: 'Qui despicit proximum suum, peccat: qui autem miseretur pauperis, beatus erit. Qui credit in Domino, misericordiam diligit.',
        22: 'Errant qui operantur malum: misericordia et veritas praeparant bona.',
        23: 'In omni opere bono erit abundantia: ubi autem verba sunt plurima, ibi frequenter egestas.',
        24: 'Corona sapientium, divitiae eorum: fatuitas stultorum, imprudentia.',
        25: 'Liberat animas testis fidelis: et profert mendacia versipellis.',
        26: 'In timore Domini fiducia fortitudinis, et filiis eius erit spes.',
        27: 'Timor Domini fons vitae, ut declinet a ruina mortis.',
        28: 'In multitudine populi dignitas regis: et in paucitate plebis ignominia principis.',
        29: 'Qui patiens est, multa gubernatur prudentia: qui autem impatiens est, exaltat stultitiam suam.',
        30: 'Vita carnium, sanitas cordis: putredo ossium, invidia.',
        31: 'Qui calumniatur egentem, exprobrat factori eius: honorat autem eum, qui miseretur pauperis.',
        32: 'In malitia sua expelletur impius: sperat autem iustus in morte sua.',
        33: 'In corde prudentis requiescit sapientia, et indoctos quosque erudiet.',
        34: 'Iustitia elevat gentem: miseros autem facit populos peccatum.',
        35: 'Acceptus est regi minister intelligens: iracundiam eius inutilis sustinebit.',
    },
    15: {
        1: 'Responsio mollis frangit iram: sermo durus suscitat furorem.',
        2: 'Lingua sapientium ornat scientiam: os fatuorum ebullit stultitiam.',
        3: 'In omni loco oculi Domini contemplantur bonos et malos.',
        4: 'Lingua placabilis, lignum vitae: quae autem immoderata est, conteret spiritum.',
        5: 'Stultus irridet disciplinam patris sui: qui autem custodit increpationes, astutior fiet. In abundanti iustitia virtus maxima est: cogitationes autem impiorum eradicabuntur.',
        6: 'Domus iusti plurima fortitudo: et in fructibus impii conturbatio.',
        7: 'Labia sapientium disseminabunt scientiam: cor stultorum dissimile erit.',
        8: 'Victimae impiorum abominabiles Domino: vota iustorum placabilia:',
        9: 'Abominatio est Domino via impii: qui sequitur iustitiam, diligitur ab eo.',
        10: 'Doctrina mala deserentium viam vitae: qui increpationes odit, morietur.',
        11: 'Infernus, et perditio coram Domino: quanto magis corda filiorum hominum?',
        12: 'Non amat pestilens eum, qui se corripit: nec ad sapientes graditur.',
        13: 'Cor gaudens exhilarat faciem: in moerore animi deiicitur spiritus.',
        14: 'Cor sapientis quaerit doctrinam: et os stultorum pascitur imperitia.',
        15: 'Omnes dies pauperis, mali: secura mens quasi iuge convivium.',
        16: 'Melius est parum cum timore Domini, quam thesauri magni et insatiabiles.',
        17: 'Melius est vocari ad olera cum charitate: quam ad vitulum saginatum cum odio.',
        18: 'Vir iracundus provocat rixas: qui patiens est, mitigat suscitatas.',
        19: 'Iter pigrorum quasi sepes spinarum: via iustorum absque offendiculo.',
        20: 'Filius sapiens laetificat patrem: et stultus homo despicit matrem suam.',
        21: 'Stultitia gaudium stulto: et vir prudens dirigit gressus suos.',
        22: 'Dissipantur cogitationes ubi non est consilium: ubi vero sunt plures consiliarii, confirmantur.',
        23: 'Laetatur homo in sententia oris sui: et sermo opportunus est optimus.',
        24: 'Semita vitae super eruditum, ut declinet de inferno novissimo.',
        25: 'Domum superborum demolietur Dominus: et firmos faciet terminos viduae.',
        26: 'Abominatio Domini cogitationes malae: et purus sermo pulcherrimus firmabitur ab eo.',
        27: 'Conturbat domum suam qui sectatur avaritiam: qui autem odit munera, vivet. Per misericordiam et fidem purgantur peccata: per timorem autem Domini declinat omnis a malo.',
        28: 'Mens iusti meditatur obedientiam: os impiorum redundat malis.',
        29: 'Longe est Dominus ab impiis: et orationes iustorum exaudiet.',
        30: 'Lux oculorum laetificat animam: fama bona impinguat ossa.',
        31: 'Auris, quae audit increpationes vitae, in medio sapientium commorabitur.',
        32: 'Qui abiicit disciplinam, despicit animam suam: qui autem acquiescit increpationibus, possessor est cordis.',
        33: 'Timor Domini, disciplina sapientiae: et gloriam praecedit humilitas.',
    },
    16: {
        1: 'Hominis est animam praeparare: et Domini gubernare linguam.',
        2: 'Omnes viae hominis patent oculis eius: spirituum ponderator est Dominus.',
        3: 'Revela Domino opera tua, et dirigentur cogitationes tuae.',
        4: 'Universa propter semetipsum operatus est Dominus: impium quoque ad diem malum.',
        5: 'Abominatio Domini est omnis arrogans: etiamsi manus ad manum fuerit, non est innocens. Initium viae bonae, facere iustitiam: accepta est autem apud Deum magis, quam immolare hostias.',
        6: 'Misericordia et veritate redimitur iniquitas: et in timore Domini declinatur a malo.',
        7: 'Cum placuerint Domino viae hominis, inimicos quoque eius convertet ad pacem.',
        8: 'Melius est parum cum iustitia, quam multi fructus cum iniquitate.',
        9: 'Cor hominis disponit viam suam: sed Domini est dirigere gressus eius.',
        10: 'Divinatio in labiis regis, in iudicio non errabit os eius.',
        11: 'Pondus et statera iudicia Domini sunt: et opera eius omnes lapides sacculi.',
        12: 'Abominabiles regi qui agunt impie: quoniam iustitia firmatur solium.',
        13: 'Voluntas regum labia iusta: qui recta loquitur, diligetur:',
        14: 'Indignatio regis, nuncii mortis: et vir sapiens placabit eam.',
        15: 'In hilaritate vultus regis, vita: et clementia eius quasi imber serotinus.',
        16: 'Posside sapientiam, quia auro melior est: et acquire prudentiam, quia pretiosior est argento.',
        17: 'Semita iustorum declinat mala: custos animae suae servat viam suam.',
        18: 'Contritionem praecedit superbia: et ante ruinam exaltatur spiritus.',
        19: 'Melius est humiliari cum mitibus, quam dividere spolia cum superbis.',
        20: 'Eruditus in verbo reperiet bona: et qui sperat in Domino, beatus est.',
        21: 'Qui sapiens est corde, appellabitur prudens: et qui dulcis eloquio, maiora reperiet.',
        22: 'Fons vitae eruditio possidentis: doctrina stultorum fatuitas.',
        23: 'Cor sapientis erudiet os eius: et labiis eius addet gratiam.',
        24: 'Favus mellis, composita verba: dulcedo animae, sanitas ossium.',
        25: 'Est via quae videtur homini recta: et novissima eius ducunt ad mortem.',
        26: 'Anima laborantis laborat sibi, quia compulit eum os suum:',
        27: 'Vir impius fodit malum, et in labiis eius ignis ardescit.',
        28: 'Homo perversus suscitat lites: et verbosus separat principes.',
        29: 'Vir iniquus lactat amicum suum: et ducit eum per viam non bonam.',
        30: 'Qui attonitis oculis cogitat prava, mordens labia sua perficit malum.',
        31: 'Corona dignitatis senectus, quae in viis iustitiae reperietur.',
        32: 'Melior est patiens viro forti: et qui dominatur animo suo, expugnatore urbium.',
        33: 'Sortes mittuntur in sinum, sed a Domino temperantur.',
    },
    17: {
        1: 'Melior est buccella sicca cum gaudio, quam domus plena victimis cum iurgio.',
        2: 'Servus sapiens dominabitur filiis stultis, et inter fratres hereditatem dividet.',
        3: 'Sicut igne probatur argentum, et aurum camino: ita corda probat Dominus.',
        4: 'Malus obedit linguae iniquae: et fallax obtemperat labiis mendacibus.',
        5: 'Qui despicit pauperem, exprobrat factori eius: et qui ruina laetatur alterius, non erit impunitus.',
        6: 'Corona senum filii filiorum: et gloria filiorum patres eorum.',
        7: 'Non decent stultum verba composita: nec principem labium mentiens.',
        8: 'Gemma gratissima, expectatio praestolantis: quocumque se vertit, prudenter intelligit.',
        9: 'Qui celat delictum, quaerit amicitias: qui altero sermone repetit, separat foederatos.',
        10: 'Plus proficit correptio apud prudentem, quam centum plagae apud stultum.',
        11: 'Semper iurgia quaerit malus: angelus autem crudelis mittetur contra eum.',
        12: 'Expedit magis ursae occurrere raptis foetibus, quam fatuo confidenti in stultitia sua.',
        13: 'Qui reddit mala pro bonis, non recedet malum de domo eius.',
        14: 'Qui dimittit aquam, caput est iurgiorum: et antequam patiatur contumeliam, iudicium deserit.',
        15: 'Qui iustificat impium, et qui condemnat iustum, abominabilis est uterque apud Deum.',
        16: 'Quid prodest stulto habere divitias, cum sapientiam emere non possit? Qui altum facit domum suam, quaerit ruinam: et qui evitat discere, incidet in mala.',
        17: 'Omni tempore diligit qui amicus est: et frater in angustiis comprobatur.',
        18: 'Stultus homo plaudet manibus cum spoponderit pro amico suo.',
        19: 'Qui meditatur discordias, diligit rixas: et qui exaltat os suum, quaerit ruinam.',
        20: 'Qui perversi cordis est, non inveniet bonum: et qui vertit linguam, incidet in malum.',
        21: 'Natus est stultus in ignominiam suam: sed nec pater in fatuo laetabitur.',
        22: 'Animus gaudens aetatem floridam facit: spiritus tristis exiccat ossa.',
        23: 'Munera de sinu impius accipit, ut pervertat semitas iudicii.',
        24: 'In facie prudentis lucet sapientia: oculi stultorum in finibus terrae.',
        25: 'Ira patris, filius stultus: et dolor matris quae genuit eum.',
        26: 'Non est bonum, damnum inferre iusto: nec percutere principem, qui recta iudicat.',
        27: 'Qui moderatur sermones suos, doctus et prudens est: et pretiosi spiritus vir eruditus.',
        28: 'Stultus quoque si tacuerit, sapiens reputabitur: et si compresserit labia sua, intelligens.',
    },
    18: {
        1: 'Occasiones quaerit qui vult recedere ab amico: omni tempore erit exprobrabilis.',
        2: 'Non recipit stultus verba prudentiae: nisi ea dixeris quae versantur in corde eius.',
        3: 'Impius, cum in profundum venerit peccatorum, contemnit: sed sequitur eum ignominia et opprobrium.',
        4: 'Aqua profunda verba ex ore viri: et torrens redundans fons sapientiae.',
        5: 'Accipere personam impii in iudicio non est bonum, ut declines a veritate iudicii.',
        6: 'Labia stulti miscent se rixis: et os eius iurgia provocat.',
        7: 'Os stulti contritio eius: et labia ipsius, ruina animae eius.',
        8: 'Verba bilinguis, quasi simplicia: et ipsa perveniunt usque ad interiora ventris. Pigrum deiicit timor: animae autem effeminatorum esurient.',
        9: 'Qui mollis et dissolutus est in opere suo, frater est sua opera dissipantis.',
        10: 'Turris fortissima, nomen Domini: ad ipsam currit iustus, et exaltabitur.',
        11: 'Substantia divitis urbs roboris eius, et quasi murus validus circumdans eum.',
        12: 'Antequam conteratur, exaltatur cor hominis: et antequam glorificetur, humiliatur.',
        13: 'Qui prius respondet quam audiat, stultum se esse demonstrat, et confusione dignum.',
        14: 'Spiritus viri sustentat imbecillitatem suam: spiritum vero ad irascendum facilem quis poterit sustinere?',
        15: 'Cor prudens possidebit scientiam: et auris sapientium quaerit doctrinam.',
        16: 'Donum hominis dilatat viam eius, et ante principes spatium ei facit.',
        17: 'Iustus, prior est accusator sui: venit amicus eius, et investigabit eum.',
        18: 'Contradictiones comprimit sors, et inter potentes quoque diiudicat.',
        19: 'Frater, qui adiuvatur a fratre, quasi civitas firma: et iudicia quasi vectes urbium.',
        20: 'De fructu oris viri replebitur venter eius: et genimina labiorum ipsius saturabunt eum.',
        21: 'Mors, et vita in manu linguae: qui diligunt eam, comedent fructus eius.',
        22: 'Qui invenit mulierem bonam, invenit bonum: et hauriet iucunditatem a Domino. Qui expellit mulierem bonam, expellit bonum: qui autem tenet adulteram, stultus est et insipiens.',
        23: 'Cum obsecrationibus loquitur pauper: et dives effabitur rigide.',
        24: 'Vir amicabilis ad societatem, magis amicus erit, quam frater.',
    },
    19: {
        1: 'Melior est pauper, qui ambulat in simplicitate sua, quam dives torquens labia sua, et insipiens.',
        2: 'Ubi non est scientia animae, non est bonum: et qui festinus est pedibus, offendet.',
        3: 'Stultitia hominis supplantat gressus eius: et contra Deum fervet animo suo.',
        4: 'Divitiae addunt amicos plurimos: a paupere autem et hi, quos habuit, separantur.',
        5: 'Testis falsus non erit impunitus: et qui mendacia loquitur, non effugiet.',
        6: 'Multi colunt personam potentis, et amici sunt dona tribuentis.',
        7: 'Fratres hominis pauperis oderunt eum: insuper et amici procul recesserunt ab eo. Qui tantum verba sectatur, nihil habebit:',
        8: 'qui autem possessor est mentis, diligit animam suam, et custos prudentiae inveniet bona.',
        9: 'Falsus testis non erit impunitus: et qui loquitur mendacia, peribit.',
        10: 'Non decent stultum deliciae: nec servum dominari principibus.',
        11: 'Doctrina viri per patientiam noscitur: et gloria eius est iniqua praetergredi.',
        12: 'Sicut fremitus leonis, ita et regis ira: et sicut ros super herbam, ita et hilaritas eius.',
        13: 'Dolor patris, filius stultus: et tecta iugiter perstillantia, litigiosa mulier.',
        14: 'Domus, et divitiae dantur a parentibus: a Domino autem proprie uxor prudens.',
        15: 'Pigredo immittit soporem, et anima dissoluta esuriet.',
        16: 'Qui custodit mandatum, custodit animam suam: qui autem negligit viam suam, mortificabitur.',
        17: 'Foeneratur Domino qui miseretur pauperis: et vicissitudinem suam reddet ei.',
        18: 'Erudi filium tuum, ne desperes: ad interfectionem autem eius ne ponas animam tuam.',
        19: 'Qui impatiens est, sustinebit damnum: et cum rapuerit, aliud apponet.',
        20: 'Audi consilium, et suscipe disciplinam, ut sis sapiens in novissimis tuis.',
        21: 'Multae cogitationes in corde viri: voluntas autem Domini permanebit.',
        22: 'Homo indigens misericors est: et melior est pauper quam vir mendax.',
        23: 'Timor Domini ad vitam: et in plenitudine commorabitur, absque visitatione pessimi.',
        24: 'Abscondit piger manum suam sub ascella, nec ad os suum applicat eam.',
        25: 'Pestilente flagellato stultus sapientior erit: si autem corripueris sapientem, intelliget disciplinam.',
        26: 'Qui affligit patrem, et fugit matrem, ignominiosus est et infelix.',
        27: 'Non cesses fili audire doctrinam, nec ignores sermones scientiae.',
        28: 'Testis iniquus deridet iudicium: et os impiorum devorat iniquitatem.',
        29: 'Parata sunt derisoribus iudicia: et mallei percutientes stultorum corporibus.',
    },
    20: {
        1: 'Luxuriosa res, vinum, et tumultuosa ebrietas: quicumque his delectatur, non erit sapiens.',
        2: 'Sicut rugitus leonis, ita et terror regis: qui provocat eum, peccat in animam suam.',
        3: 'Honor est homini, qui separat se a contentionibus: omnes autem stulti miscentur contumeliis.',
        4: 'Propter frigus piger arare noluit: mendicabit ergo aestate, et non dabitur illi.',
        5: 'Sicut aqua profunda, sic consilium in corde viri: sed homo sapiens exhauriet illud.',
        6: 'Multi homines misericordes vocantur: virum autem fidelem quis inveniet?',
        7: 'Iustus, qui ambulat in simplicitate sua, beatos post se filios derelinquet.',
        8: 'Rex, qui sedet in solio iudicii, dissipat omne malum intuitu suo.',
        9: 'Quis potest dicere: Mundum est cor meum, purus sum a peccato?',
        10: 'Pondus et pondus, mensura et mensura: utrumque abominabile est apud Deum.',
        11: 'Ex studiis suis intelligitur puer, si munda et recta sint opera eius.',
        12: 'Aurem audientem, et oculum videntem, Dominus fecit utrumque.',
        13: 'Noli diligere somnum, ne te egestas opprimat: aperi oculos tuos, et saturare panibus.',
        14: 'Malum est, malum est, dicit omnis emptor: et cum recesserit, tunc gloriabitur.',
        15: 'Est aurum, et multitudo gemmarum: vas autem pretiosum labia scientiae.',
        16: 'Tolle vestimentum eius, qui fideiussor extitit alieni, et pro extraneis aufer pignus ab eo.',
        17: 'Suavis est homini panis mendacii: et postea implebitur os eius calculo.',
        18: 'Cogitationes consiliis roborantur: et gubernaculis tractanda sunt bella.',
        19: 'Ei, qui revelat mysteria, et ambulat fraudulenter, et dilatat labia sua, ne commiscearis.',
        20: 'Qui maledicit patri suo, et matri, extinguetur lucerna eius in mediis tenebris.',
        21: 'Hereditas, ad quam festinatur in principio, in novissimo benedictione carebit.',
        22: 'Ne dicas: Reddam malum: expecta Dominum, et liberabit te.',
        23: 'Abominatio est apud Dominum pondus et pondus: statera dolosa non est bona.',
        24: 'A Domino diriguntur gressus viri: quis autem hominum intelligere potest viam suam?',
        25: 'Ruina est homini devotare sanctos, et post vota retractare.',
        26: 'Dissipat impios rex sapiens, et incurvat super eos fornicem.',
        27: 'Lucerna Domini spiraculum hominis, quae investigat omnia secreta ventris.',
        28: 'Misericordia, et veritas custodiunt regem, et roboratur clementia thronus eius.',
        29: 'Exultatio iuvenum, fortitudo eorum: et dignitas senum canities.',
        30: 'Livor vulneris absterget mala: et plagae in secretioribus ventris.',
    },
    21: {
        1: 'Sicut divisiones aquarum, ita cor regis in manu Domini: quocumque voluerit, inclinabit illud.',
        2: 'Omnis via viri recta sibi videtur: appendit autem corda Dominus.',
        3: 'Facere misericordiam et iudicium, magis placet Domino quam victimae.',
        4: 'Exaltatio oculorum est dilatatio cordis: lucerna impiorum peccatum.',
        5: 'Cogitationes robusti semper in abundantia: omnis autem piger semper in egestate est.',
        6: 'Qui congregat thesauros lingua mendacii, vanus et excors est, et impingetur ad laqueos mortis.',
        7: 'Rapinae impiorum detrahent eos, quia noluerunt facere iudicium.',
        8: 'Perversa via viri, aliena est: qui autem mundus est, rectum opus eius.',
        9: 'Melius est sedere in angulo domatis, quam cum muliere litigiosa, et in domo communi.',
        10: 'Anima impii desiderat malum, non miserebitur proximo suo.',
        11: 'Mulctato pestilente sapientior erit parvulus: et si sectetur sapientem, sumet scientiam.',
        12: 'Excogitat iustus de domo impii, ut detrahat impios a malo.',
        13: 'Qui obturat aurem suam ad clamorem pauperis, et ipse clamabit, et non exaudietur.',
        14: 'Munus absconditum extinguit iras: et donum in sinu indignationem maximam.',
        15: 'Gaudium iusto est facere iudicium: et pavor operantibus iniquitatem.',
        16: 'Vir, qui erraverit a via doctrinae, in coetu gigantum commorabitur.',
        17: 'Qui diligit epulas, in egestate erit: qui amat vinum, et pinguia, non ditabitur.',
        18: 'Pro iusto dabitur impius: et pro rectis iniquus.',
        19: 'Melius est habitare in terra deserta, quam cum muliere rixosa et iracunda.',
        20: 'Thesaurus desiderabilis, et oleum in habitaculo iusti: et imprudens homo dissipabit illud.',
        21: 'Qui sequitur iustitiam et misericordiam, inveniet vitam, et gloriam.',
        22: 'Civitatem fortium ascendit sapiens, detraxitque robur fiduciae eius.',
        23: 'Qui custodit os suum, et linguam suam, custodit ab angustiis animam suam.',
        24: 'Superbus et arrogans vocatur indoctus, qui in ira operatur superbiam.',
        25: 'Desideria occidunt pigrum: noluerunt enim quidquam manus eius operari:',
        26: 'tota die concupiscit et desiderat: qui autem iustus est, tribuet, et non cessabit.',
        27: 'Hostiae impiorum abominabiles, quae offeruntur ex scelere.',
        28: 'Testis mendax peribit: vir obediens loquetur victoriam.',
        29: 'Vir impius procaciter obfirmat vultum suum: qui autem rectus est, corrigit viam suam.',
        30: 'Non est sapientia, non est prudentia, non est consilium contra Dominum.',
        31: 'Equus paratur ad diem belli: Dominus autem salutem tribuit.',
    },
    22: {
        1: 'Melius est nomen bonum, quam divitiae multae: super argentum et aurum, gratia bona.',
        2: 'Dives, et pauper obviaverunt sibi: utriusque operator est Dominus.',
        3: 'Callidus videt malum, et abscondit se: innocens pertransiit, et afflictus est damno.',
        4: 'Finis modestiae timor Domini, divitiae et gloria et vita.',
        5: 'Arma et gladii in via perversi: custos autem animae suae longe recedit ab eis.',
        6: 'Proverbium est: Adolescens iuxta viam suam, etiam cum senuerit, non recedet ab ea.',
        7: 'Dives pauperibus imperat: et qui accipit mutuum, servus est foenerantis.',
        8: 'Qui seminat iniquitatem, metet mala, et virga irae suae consummabitur.',
        9: 'Qui pronus est ad misericordiam, benedicetur: de panibus enim suis dedit pauperi. Victoriam et honorem acquiret qui dat munera: animam autem aufert accipientium.',
        10: 'Eiice derisorem, et exibit cum eo iurgium, cessabuntque causae et contumeliae.',
        11: 'Qui diligit cordis munditiam, propter gratiam labiorum suorum habebit amicum regem.',
        12: 'Oculi Domini custodiunt scientiam: et supplantantur verba iniqui.',
        13: 'Dicit piger: Leo est foris, in medio platearum occidendus sum.',
        14: 'Fovea profunda, os alienae: cui iratus est Dominus, incidet in eam.',
        15: 'Stultitia colligata est in corde pueri, et virga disciplinae fugabit eam.',
        16: 'Qui calumniatur pauperem, ut augeat divitias suas, dabit ipse ditiori, et egebit.',
        17: 'Fili mi! Inclina aurem tuam, et audi verba sapientium: appone autem cor ad doctrinam meam.',
        18: 'quae pulchra erit tibi, cum servaveris eam in ventre tuo, et redundabit in labiis tuis:',
        19: 'Ut sit in Domino fiducia tua, unde et ostendi eam tibi hodie.',
        20: 'Ecce descripsi eam tibi tripliciter, in cogitationibus et scientia:',
        21: 'ut ostenderem tibi firmitatem, et eloquia veritatis, respondere ex his illis, qui miserunt te.',
        22: 'Non facias violentiam pauperi, quia pauper est: neque conteras egenum in porta:',
        23: 'quia iudicabit Dominus causam eius, et configet eos, qui confixerunt animam eius.',
        24: 'Noli esse amicus homini iracundo, neque ambules cum viro furioso:',
        25: 'ne forte discas semitas eius, et sumas scandalum animae tuae.',
        26: 'Noli esse cum his, qui defigunt manus suas, et qui vades se offerunt pro debitis:',
        27: 'si enim non habes unde restituas, quid causae est ut tollat operimentum de cubili tuo?',
        28: 'Ne transgrediaris terminos antiquos, quos posuerunt patres tui.',
        29: 'Vidisti virum velocem in opere suo? coram regibus stabit, nec erit ante ignobiles.',
    },
    23: {
        1: 'Quando sederis ut comedas cum principe, diligenter attende quae apposita sunt ante faciem tuam:',
        2: 'et statue cultrum in gutture tuo, si tamen habes in potestate animam tuam,',
        3: 'ne desideres de cibis eius, in quo est panis mendacii.',
        4: 'Noli laborare ut diteris: sed prudentiae tuae pone modum.',
        5: 'Ne erigas oculos tuos ad opes, quas non potes habere: quia facient sibi pennas quasi aquilae, et volabunt in caelum.',
        6: 'Ne comedas cum homine invido, et ne desideres cibos eius:',
        7: 'quoniam in similitudinem arioli, et coniectoris, aestimat quod ignorat. Comede et bibe, dicet tibi: et mens eius non est tecum.',
        8: 'Cibos, quos comederas, evomes: et perdes pulchros sermones tuos.',
        9: 'In auribus insipientium ne loquaris: qui despicient doctrinam eloquii tui.',
        10: 'Ne attingas parvulorum terminos: et agrum pupillorum ne introeas:',
        11: 'Propinquus enim illorum fortis est: et ipse iudicabit contra te causam illorum.',
        12: 'Ingrediatur ad doctrinam cor tuum: et aures tuae ad verba scientiae.',
        13: 'Noli subtrahere a puero disciplinam: si enim percusseris eum virga, non morietur.',
        14: 'Tu virga percuties eum: et animam eius de inferno liberabis.',
        15: 'Fili mi, si sapiens fuerit animus tuus, gaudebit tecum cor meum:',
        16: 'et exultabunt renes mei, cum locuta fuerint recta labia tua.',
        17: 'Non aemuletur cor tuum peccatores: sed in timore Domini esto tota die:',
        18: 'quia habebis spem in novissimo, et praestolatio tua non auferetur.',
        19: 'Audi fili mi, et esto sapiens: et dirige in via animum tuum.',
        20: 'Noli esse in conviviis potatorum, nec in comessationibus eorum, qui carnes ad vescendum conferunt:',
        21: 'quia vacantes potibus, et dantes symbola consumentur, et vestietur pannis dormitatio.',
        22: 'Audi patrem tuum, qui genuit te: et ne contemnas cum senuerit mater tua.',
        23: 'Veritatem eme, et noli vendere sapientiam, et doctrinam, et intelligentiam.',
        24: 'Exultat gaudio pater iusti: qui sapientem genuit, laetabitur in eo.',
        25: 'Gaudeat pater tuus, et mater tua, et exultet quae genuit te.',
        26: 'Praebe fili mi cor tuum mihi: et oculi tui vias meas custodiant.',
        27: 'Fovea enim profunda est meretrix: et puteus angustus, aliena.',
        28: 'Insidiatur in via quasi latro, et quos incautos viderit, interficiet.',
        29: 'Cui vae? cuius patri vae? cui rixae? cui foveae? cui sine causa vulnera? cui suffusio oculorum?',
        30: 'Nonne his, qui commorantur in vino, et student calicibus epotandis?',
        31: 'Ne intuearis vinum quando flavescit, cum splenduerit in vitro color eius: ingreditur blande,',
        32: 'sed in novissimo mordebit ut coluber, et sicut regulus venena diffundet.',
        33: 'Oculi tui videbunt extraneas, et cor tuum loquetur perversa.',
        34: 'Et eris sicut dormiens in medio mari, et quasi sopitus gubernator, amisso clavo:',
        35: 'et dices: Verberaverunt me, sed non dolui: traxerunt me, et ego non sensi: quando evigilabo, et rursus vina reperiam?',
    },
    24: {
        1: 'Ne aemuleris viros malos, nec desideres esse cum eis:',
        2: 'quia rapinas meditatur mens eorum, et fraudes labia eorum loquuntur.',
        3: 'Sapientia aedificabitur domus, et prudentia roborabitur.',
        4: 'In doctrina replebuntur cellaria, universa substantia pretiosa et pulcherrima.',
        5: 'Vir sapiens, fortis est: et vir doctus, robustus et validus.',
        6: 'Quia cum dispositione initur bellum: et erit salus ubi multa consilia sunt.',
        7: 'Excelsa stulto sapientia, in porta non aperiet os suum.',
        8: 'Qui cogitat mala facere, stultus vocabitur.',
        9: 'Cogitatio stulti peccatum est: et abominatio hominum detractor.',
        10: 'Si desperaveris lapsus in die angustiae: imminuetur fortitudo tua.',
        11: 'Erue eos, qui ducuntur ad mortem: et qui trahuntur ad interitum liberare ne cesses.',
        12: 'Si dixeris: Vires non suppetunt: qui inspector est cordis, ipse intelligit, et servatorem animae tuae nihil fallit, reddetque homini iuxta opera sua.',
        13: 'Comede, fili mi, mel, quia bonum est, et favum dulcissimum gutturi tuo:',
        14: 'Sic et doctrina sapientiae animae tuae: quam cum inveneris, habebis in novissimis spem, et spes tua non peribit.',
        15: 'Ne insidieris, et quaeras impietatem in domo iusti, neque vastes requiem eius.',
        16: 'Septies enim in die cadit iustus, et resurgit: impii autem corruent in malum.',
        17: 'Cum ceciderit inimicus tuus, ne gaudeas, et in ruina eius ne exultet cor tuum:',
        18: 'ne forte videat Dominus, et displiceat ei, et auferat ab eo iram suam.',
        19: 'Ne contendas cum pessimis, nec aemuleris impios:',
        20: 'quoniam non habent futurorum spem mali, et lucerna impiorum extinguetur.',
        21: 'Time Dominum, fili mi, et regem: et cum detractoribus non commiscearis:',
        22: 'quoniam repente consurget perditio eorum: et ruinam utriusque quis novit?',
        23: 'Haec quoque sapientibus dico: Cognoscere personam in iudicio non est bonum.',
        24: 'Qui dicunt impio: Iustus es: maledicent eis populi, et detestabuntur eos tribus.',
        25: 'Qui arguunt eum, laudabuntur: et super ipsos veniet benedictio.',
        26: 'Labia deosculabitur, qui recta verba respondet.',
        27: 'Praepara foris opus tuum, et diligenter exerce agrum tuum: et postea aedifices domum tuam.',
        28: 'Ne sis testis frustra contra proximum tuum: nec lactes quemquam labiis tuis.',
        29: 'Ne dicas: Quomodo fecit mihi, sic faciam ei: reddam unicuique secundum opus suum.',
        30: 'Per agrum hominis pigri transivi, et per vineam viri stulti:',
        31: 'et ecce totum repleverant urticae, et operuerant superficiem eius spinae, et maceria lapidum destructa erat.',
        32: 'Quod cum vidissem, posui in corde meo, et exemplo didici disciplinam.',
        33: 'Usquequo piger dormies? usquequo de somno consurgens? Parum, inquam, dormies, modicum dormitabis, pauxillum manus conseres, ut quiescas:',
        34: 'et veniet tibi quasi cursor egestas, et mendicitas quasi vir armatus.',
    },
    25: {
        1: 'Hae quoque parabolae Salomonis, quas transtulerunt viri Ezechiae regis Iuda.',
        2: 'Gloria Dei est celare verbum, et gloria regum investigare sermonem.',
        3: 'Caelum sursum, et terra deorsum, et cor regum inscrutabile.',
        4: 'Aufer rubiginem de argento, et egredietur vas purissimum:',
        5: 'Aufer impietatem de vultu regis, et firmabitur iustitia thronus eius.',
        6: 'Ne gloriosus appareas coram rege, et in loco magnorum ne steteris.',
        7: 'Melius est enim ut dicatur tibi: Ascende huc; quam ut humilieris coram principe.',
        8: 'Quae viderunt oculi tui, ne proferas in iurgio cito: ne postea emendare non possis, cum dehonestaveris amicum tuum.',
        9: 'Causam tuam tracta cum amico tuo, et secretum extraneo ne reveles:',
        10: 'ne forte insultet tibi cum audierit, et exprobrare non cesset. Gratia et amicitia liberant: quas tibi serva, ne exprobrabilis fias.',
        11: 'Mala aurea in lectis argenteis, qui loquitur verbum in tempore suo.',
        12: 'Inauris aurea, et margaritum fulgens, qui arguit sapientem, et aurem obedientem.',
        13: 'Sicut frigus nivis in die messis, ita legatus fidelis ei, qui misit eum, animam ipsius requiescere facit.',
        14: 'Nubes, et ventus, et pluviae non sequentes, vir gloriosus, et promissa non complens.',
        15: 'Patientia lenietur princeps, et lingua mollis confringet duritiam.',
        16: 'Mel invenisti, comede quod sufficit tibi, ne forte satiatus evomas illud.',
        17: 'Subtrahe pedem tuum de domo proximi tui, nequando satiatus oderit te.',
        18: 'Iaculum, et gladius, et sagitta acuta, homo qui loquitur contra proximum suum falsum testimonium.',
        19: 'Dens putridus, et pes lassus, qui sperat super infideli in die angustiae,',
        20: 'et amittit pallium in die frigoris. Acetum in nitro, qui cantat carmina cordi pessimo. Sicut tinea vestimento, et vermis ligno: ita tristitia viri nocet cordi.',
        21: 'Si esurierit inimicus tuus, ciba illum: si sitierit, da ei aquam bibere:',
        22: 'prunas enim congregabis super caput eius, et Dominus reddet tibi.',
        23: 'Ventus aquilo dissipat pluvias, et facies tristis linguam detrahentem.',
        25: 'Aqua frigida animae sitienti, et nuncius bonus de terra longinqua.',
        26: 'Fons turbatus pede, et vena corrupta, iustus cadens coram impio.',
        27: 'Sicut qui mel multum comedit, non est ei bonum: sic qui scrutator est maiestatis, opprimetur a gloria.',
        28: 'Sicut urbs patens et absque murorum ambitu, ita vir, qui non potest in loquendo cohibere spiritum suum.',
    },
    26: {
        1: 'Quomodo nix in aestate, et pluviae in messe: sic indecens est stulto gloria.',
        2: 'Sicut avis ad alta transvolans, et passer quo libet vadens: sic maledictum frustra prolatum in quempiam superveniet.',
        3: 'Flagellum equo, et camus asino, et virga in dorso imprudentium.',
        4: 'Ne respondeas stulto iuxta stultitiam suam, ne efficiaris ei similis.',
        5: 'Responde stulto iuxta stultitiam suam, ne sibi sapiens esse videatur.',
        6: 'Claudus pedibus, et iniquitatem bibens, qui mittit verba per nuncium stultum.',
        7: 'Quomodo pulchras frustra habet claudus tibias: sic indecens est in ore stultorum parabola.',
        8: 'Sicut qui mittit lapidem in acervum Mercurii: ita qui tribuit insipienti honorem.',
        9: 'Quomodo si spina nascatur in manu temulenti: sic parabola in ore stultorum.',
        10: 'Iudicium determinat causas: et qui imponit stulto silentium, iras mitigat.',
        11: 'Sicut canis, qui revertitur ad vomitum suum, sic imprudens, qui iterat stultitiam suam.',
        12: 'Vidisti hominem sapientem sibi videri? magis illo spem habebit insipiens.',
        13: 'Dicit piger: Leo est in via, et leaena in itineribus:',
        14: 'sicut ostium vertitur in cardine suo, ita piger in lectulo suo.',
        15: 'Abscondit piger manum sub ascella sua, et laborat si ad os suum eam converterit.',
        16: 'Sapientior sibi piger videtur septem viris loquentibus sententias.',
        17: 'Sicut qui apprehendit auribus canem, sic qui transit impatiens, et commiscetur rixae alterius.',
        18: 'Sicut noxius est qui mittit sagittas, et lanceas in mortem:',
        19: 'ita vir, fraudulenter nocet amico suo: et cum fuerit deprehensus, dicit: Ludens feci.',
        20: 'Cum defecerint ligna, extinguetur ignis: et susurrone subtracto, iurgia conquiescunt.',
        21: 'Sicut carbones ad prunas, et ligna ad ignem, sic homo iracundus suscitat rixas.',
        22: 'Verba susurronis quasi simplicia, et ipsa perveniunt ad intima ventris.',
        23: 'Quomodo si argento sordido ornare velis vas fictile, sic labia tumentia cum pessimo corde sociata.',
        24: 'Labiis suis intelligitur inimicus, cum in corde tractaverit dolos.',
        25: 'Quando submiserit vocem suam, ne credideris ei: quoniam septem nequitiae sunt in corde illius.',
        26: 'Qui operit odium fraudulenter, revelabitur malitia eius in consilio.',
        27: 'Qui fodit foveam, incidet in eam: et qui volvit lapidem, revertetur ad eum.',
        28: 'Lingua fallax non amat veritatem: et os lubricum operatur ruinas.',
    },
    27: {
        1: 'Ne glorieris in crastinum, ignorans quid superventura pariat dies.',
        2: 'Laudet te alienus, et non os tuum: extraneus, et non labia tua.',
        3: 'Grave est saxum, et onerosa arena: sed ira stulti utroque gravior.',
        4: 'Ira non habet misericordiam, nec erumpens furor: et impetum concitati spiritus ferre quis poterit?',
        5: 'Melior est manifesta correptio, quam amor absconditus.',
        6: 'Meliora sunt vulnera diligentis, quam fraudulenta oscula odientis',
        7: 'Anima saturata calcabit favum: et anima esuriens etiam amarum pro dulci sumet.',
        8: 'Sicut avis transmigrans de nido suo, sic vir qui derelinquit locum suum.',
        9: 'Unguento et variis odoribus delectatur cor: et bonis amici consiliis anima dulcoratur.',
        10: 'Amicum tuum, et amicum patris tui ne dimiseris: et domum fratris tui ne ingrediaris in die afflictionis tuae. Melior est vicinus iuxta, quam frater procul.',
        11: 'Stude sapientiae fili mi, et laetifica cor meum, ut possim exprobranti respondere sermonem.',
        12: 'Astutus videns malum, absconditus est: parvuli transeuntes sustinuerunt dispendia.',
        13: 'Tolle vestimentum eius, qui spopondit pro extraneo: et pro alienis, aufer ei pignus.',
        14: 'Qui benedicit proximo suo voce grandi, de nocte consurgens maledicenti similis erit.',
        15: 'Tecta perstillantia in die frigoris, et litigiosa mulier comparantur:',
        16: 'qui retinet eam, quasi qui ventum teneat, et oleum dexterae suae evacuabit.',
        17: 'Ferrum ferro exacuitur, et homo exacuit faciem amici sui.',
        18: 'Qui servat ficum, comedet fructus eius: et qui custos est domini sui, glorificabitur.',
        19: 'Quomodo in aquis resplendent vultus prospicientium, sic corda hominum manifesta sunt prudentibus.',
        20: 'Infernus et perditio numquam implentur: similiter et oculi hominum insatiabiles:',
        21: 'Quomodo probatur in conflatorio argentum, et in fornace aurum: sic probatur homo ore laudantis. Cor iniqui inquirit mala, cor autem rectum inquirit scientiam.',
        22: 'Si contuderis stultum in pila quasi ptisanas feriente desuper pilo, non auferetur ab eo stultitia eius.',
        23: 'Diligenter agnosce vultum pecoris tui, tuosque greges considera:',
        24: 'Non enim habebis iugiter potestatem: sed corona tribuetur in generatione et generationem.',
        25: 'Aperta sunt prata, et apparuerunt herbae virentes, et collecta sunt foena de montibus.',
        26: 'Agni ad vestimentum tuum: et hoedi, agri pretium.',
        27: 'Sufficiat tibi lac caprarum in cibos tuos, et in necessaria domus tuae: et ad victum ancillis tuis.',
    },
    28: {
        1: 'Fugit impius, nemine persequente: iustus autem quasi leo confidens, absque terrore erit.',
        2: 'Propter peccata terrae multi principes eius: et propter hominis sapientiam, et horum scientiam quae dicuntur, vita ducis longior erit.',
        3: 'Vir pauper calumnians pauperes, similis est imbri vehementi, in quo paratur fames.',
        4: 'Qui derelinquunt legem, laudant impium: qui custodiunt, succenduntur contra eum.',
        5: 'Viri mali non cogitant iudicium: qui autem inquirunt Dominum, animadvertunt omnia.',
        6: 'Melior est pauper ambulans in simplicitate sua, quam dives in pravis itineribus.',
        7: 'Qui custodit legem, filius sapiens est: qui autem comessatores pascit, confundit patrem suum.',
        8: 'Qui coacervat divitias usuris et foenore liberali, in pauperes congregat eas.',
        9: 'Qui declinat aures suas ne audiat legem, oratio eius erit execrabilis.',
        10: 'Qui decipit iustos in via mala, in interitu suo corruet: et simplices possidebunt bona eius.',
        11: 'Sapiens sibi videtur vir dives: pauper autem prudens scrutabitur eum.',
        12: 'In exultatione iustorum multa gloria est: regnantibus impiis ruinae hominum.',
        13: 'Qui abscondit scelera sua, non dirigetur: qui autem confessus fuerit, et reliquerit ea, misericordiam consequetur.',
        14: 'Beatus homo, qui semper est pavidus: qui vero mentis est durae, corruet in malum.',
        15: 'Leo rugiens, et ursus esuriens, princeps impius super populum pauperem.',
        16: 'Dux indigens prudentia, multos opprimet per calumniam: qui autem odit avaritiam, longi fient dies eius.',
        17: 'Hominem, qui calumniatur animae sanguinem, si usque ad lacum fugerit, nemo sustinet.',
        18: 'Qui ambulat simpliciter, salvus erit: qui perversis graditur viis, concidet semel.',
        19: 'Qui operatur terram suam, satiabitur panibus: qui autem sectatur otium, replebitur egestate.',
        20: 'Vir fidelis multum laudabitur: qui autem festinat ditari, non erit innocens.',
        21: 'Qui cognoscit in iudicio faciem, non benefacit: iste et pro buccella panis deserit veritatem.',
        22: 'Vir, qui festinat ditari, et aliis invidet, ignorat quod egestas superveniet ei.',
        23: 'Qui corripit hominem, gratiam postea inveniet apud eum magis quam ille, qui per linguae blandimenta decipit.',
        24: 'Qui subtrahit aliquid a patre suo, et a matre: et dicit hoc non esse peccatum, particeps homicidae est.',
        25: 'Qui se iactat, et dilatat, iurgia concitat: qui vero sperat in Domino, sanabitur.',
        26: 'Qui confidit in corde suo, stultus est: qui autem graditur sapienter, ipse laudabitur.',
        27: 'Qui dat pauperi, non indigebit: qui despicit deprecantem, sustinebit penuriam.',
        28: 'Cum surrexerint impii, abscondentur homines: cum illi perierint, multiplicabuntur iusti.',
    },
    29: {
        1: 'Viro, qui corripientem dura cervice contemnit, repentinus ei superveniet interitus: et eum sanitas non sequetur.',
        2: 'In multiplicatione iustorum laetabitur vulgus: cum impii sumpserint principatum, gemet populus.',
        3: 'Vir, qui amat sapientiam, laetificat patrem suum: qui autem nutrit scorta, perdet substantiam.',
        4: 'Rex iustus erigit terram, vir avarus destruet eam.',
        5: 'Homo, qui blandis, fictisque sermonibus loquitur amico suo, rete expandit gressibus eius.',
        6: 'Peccantem virum iniquum involvet laqueus: et iustus laudabit atque gaudebit.',
        7: 'Novit iustus causam pauperum: impius ignorat scientiam.',
        8: 'Homines pestilentes dissipant civitatem: sapientes vero avertunt furorem.',
        9: 'Vir sapiens, si cum stulto contenderit, sive irascatur, sive rideat, non inveniet requiem.',
        10: 'Viri sanguinum oderunt simplicem: iusti autem quaerunt animam eius.',
        11: 'Totum spiritum suum profert stultus: sapiens differt, et reservat in posterum.',
        12: 'Princeps, qui libenter audit verba mendacii, omnes ministros habet impios.',
        13: 'Pauper, et creditor obviaverunt sibi: utriusque illuminator est Dominus.',
        14: 'Rex, qui iudicat in veritate pauperes, thronus eius in aeternum firmabitur.',
        15: 'Virga atque correptio tribuit sapientiam: puer autem, qui dimittitur voluntati suae, confundit matrem suam.',
        16: 'In multiplicatione impiorum multiplicabuntur scelera: et iusti ruinas eorum videbunt.',
        17: 'Erudi filium tuum, et refrigerabit te, et dabit delicias animae tuae.',
        18: 'Cum prophetia defecerit, dissipabitur populus: qui vero custodit legem, beatus est.',
        19: 'Servus verbis non potest erudiri: quia quod dicis intelligit, et respondere contemnit.',
        20: 'Vidisti hominem velocem ad loquendum? stultitia magis speranda est, quam illius correptio.',
        21: 'Qui delicate a pueritia nutrit servum suum, postea sentiet eum contumacem.',
        22: 'Vir iracundus provocat rixas: et qui ad indignandum facilis est, erit ad peccandum proclivior.',
        23: 'Superbum sequitur humilitas: et humilem spiritu suscipiet gloria.',
        24: 'Qui cum fure participat, odit animam suam: adiurantem audit, et non indicat.',
        25: 'Qui timet hominem, cito corruet: qui sperat in Domino, sublevabitur.',
        26: 'Multi requirunt faciem principis: et iudicium a Domino egreditur singulorum.',
        27: 'Abominantur iusti virum impium: et abominantur impii eos, qui in recta sunt via. Verbum custodiens filius, extra perditionem erit.',
    },
    30: {
        1: 'Verba Congregantis filii Vomentis. Visio, quam locutus est vir, cum quo est Deus, et qui Deo secum morante confortatus, ait:',
        2: 'Stultissimus sum virorum, et sapientia hominum non est mecum.',
        3: 'Non didici sapientiam, et non novi scientiam sanctorum.',
        4: 'Quis ascendit in caelum atque descendit? quis continuit spiritum in manibus suis? quis colligavit aquas quasi in vestimento? quis suscitavit omnes terminos terrae? quod nomen est eius, et quod nomen filii eius, si nosti?',
        5: 'Omnis sermo Dei ignitus, clypeus est sperantibus in se:',
        6: 'ne addas quidquam verbis illius, et arguaris inveniarisque mendax.',
        7: 'Duo rogavi te, ne deneges mihi antequam moriar.',
        8: 'Vanitatem, et verba mendacia longe fac a me. Mendicitatem, et divitias ne dederis mihi: tribue tantum victui meo necessaria:',
        9: 'ne forte satiatus illiciar ad negandum, et dicam: Quis est Dominus? aut egestate compulsus furer, et periurem nomen Dei mei.',
        10: 'Ne accuses servum ad Dominum suum, ne forte maledicat tibi, et corruas.',
        11: 'Generatio, quae patri suo maledicit, et quae matri suae non benedicit.',
        12: 'Generatio, quae sibi munda videtur, et tamen non est lota a sordibus suis.',
        13: 'Generatio, cuius excelsi sunt oculi, et palpebrae eius in alta surrectae.',
        14: 'Generatio, quae pro dentibus gladios habet, et commandit molaribus suis, ut comedat inopes de terra, et pauperes ex hominibus.',
        15: 'Sanguisugae duae sunt filiae, dicentes: Affer, Affer. Tria sunt insaturabilia, et quartum, quod numquam dicit: Sufficit.',
        16: 'Infernus, et os vulvae, et terra, quae non satiatur aqua: ignis vero numquam dicit: Sufficit.',
        17: 'Oculum, qui subsannat patrem, et qui despicit partum matris suae, effodiant corvi de torrentibus, et comedant eum filii aquilae.',
        18: 'Tria sunt difficilia mihi, et quartum penitus ignoro:',
        19: 'Viam aquilae in caelo, viam colubri super petram, viam navis in medio mari, et viam viri in adolescentia.',
        20: 'Talis est et via mulieris adulterae, quae comedit, et tergens os suum dicit: Non sum operata malum.',
        21: 'Per tria movetur terra, et quartum non potest sustinere:',
        22: 'Per servum cum regnaverit: per stultum cum saturatus fuerit cibo:',
        23: 'per odiosam mulierem cum in matrimonio fuerit assumpta: et per ancillam cum fuerit heres dominae suae.',
        24: 'Quattuor sunt minima terrae, et ipsa sunt sapientiora sapientibus.',
        25: 'Formicae, populus infirmus, qui praeparat in messe cibum sibi:',
        26: 'lepusculus, plebs invalida, qui collocat in petra cubile suum:',
        27: 'regem locusta non habet, et egreditur universa per turmas suas:',
        28: 'stellio manibus nititur, et moratur in aedibus regis.',
        29: 'Tria sunt, quae bene gradiuntur, et quartum, quod incedit feliciter:',
        30: 'Leo fortissimus bestiarum, ad nullius pavebit occursum:',
        31: 'gallus succinctus lumbos: et aries: et rex, cui non est, qui resistat ei.',
        32: 'Est qui stultus apparuit postquam elevatus est in sublime: si enim intellexisset, ori suo imposuisset manum.',
        33: 'Qui autem fortiter premit ubera ad eliciendum lac, exprimit butyrum: et qui vehementer emungit, elicit sanguinem: et qui provocat iras, producit discordias.',
    },
    31: {
        1: 'Verba Lamuelis regis. Visio, qua erudivit eum mater sua.',
        2: 'Quid dilecte mi, quid dilecte uteri mei, quid dilecte votorum meorum?',
        3: 'Ne dederis mulieribus substantiam tuam, et divitias tuas ad delendos reges.',
        4: 'Noli regibus, o Lamuel, noli regibus dare vinum: quia nullum secretum est ubi regnat ebrietas.',
        5: 'et ne forte bibant, et obliviscantur iudiciorum, et mutent causam filiorum pauperis.',
        6: 'Date siceram moerentibus, et vinum his, qui amaro sunt animo:',
        7: 'ut bibant, et obliviscantur egestatis suae, et doloris sui non recordentur amplius.',
        8: 'Aperi os tuum muto, et causis omnium filiorum qui pertranseunt:',
        9: 'aperi os tuum, decerne quod iustum est, et iudica inopem et pauperem.',
        10: 'Mulierem fortem quis inveniet? procul, et de ultimis finibus pretium eius.',
        11: 'Confidit in ea cor viri sui, et spoliis non indigebit.',
        12: 'Reddet ei bonum, et non malum, omnibus diebus vitae suae.',
        13: 'Quaesivit lanam et linum, et operata est consilia manuum suarum.',
        14: 'Facta est quasi navis institoris, de longe portans panem suum.',
        15: 'Et de nocte surrexit, deditque praedam domesticis suis, et cibaria ancillis suis.',
        16: 'Consideravit agrum, et emit eum: de fructu manuum suarum plantavit vineam.',
        17: 'Accinxit fortitudine lumbos suos, et roboravit brachium suum.',
        18: 'Gustavit, et vidit quia bona est negotiatio eius: non extinguetur in nocte lucerna eius.',
        19: 'Manum suam misit ad fortia, et digiti eius apprehenderunt fusum.',
        20: 'Manum suam aperuit inopi, et palmas suas extendit ad pauperem.',
        21: 'Non timebit domui suae a frigoribus nivis: omnes enim domestici eius vestiti sunt duplicibus.',
        22: 'Stragulatam vestem fecit sibi: byssus, et purpura indumentum eius.',
        23: 'Nobilis in portis vir eius, quando sederit cum senatoribus terrae.',
        24: 'Sindonem fecit, et vendidit, et cingulum tradidit Chananaeo.',
        25: 'Fortitudo et decor indumentum eius, et ridebit in die novissimo.',
        26: 'Os suum aperuit sapientiae, et lex clementiae in lingua eius.',
        27: 'Consideravit semitas domus suae, et panem otiosa non comedit.',
        28: 'Surrexerunt filii eius, et beatissimam praedicaverunt: vir eius, et laudavit eam.',
        29: 'Multae filiae congregaverunt sibi divitias: tu supergressa es universas.',
        30: 'Fallax gratia, et vana est pulchritudo: mulier timens Dominum ipsa laudabitur.',
        31: 'Date ei de fructu manuum suarum: et laudent eam in portis opera eius.',
    },
}
