NAME = 'FinBiblia: Finnish Biblia (1776)'
BOOK = 'Tobit'

CHAPTERS = {
    1: {
        1: 'Oli yksi mies, nimeltä Tobia, Naphtalin suvusta, yhdestä ylimmäisen Galilean kaupungista, ylempänä Asseria, tien vieressä vasemmalla kädellä merta kohden.',
        2: 'Se myös vangiksi vietiin Salmanasserin, Assyrian kuninkaan aikana. Ja vaikka hän niin muukalaisten seassa vankina oli, ei hän kuitenkaan Jumalan sanasta luopunut.',
        3: 'Ja kaikki mitä hänellä oli, jakoi hän veljillensä ja tuttavillensa, jotka hänen kanssansa vankina olivat.',
        4: 'Ja ehkä hän nuorin mies oli Naphtalin suvusta, ei kuitenkaan hän itsiänsä lapsellisesti käyttänyt.',
        5: 'Ja kuin muutoin jokainen palveli kultaisia vasikoita, jotka Jerobeam, Israelin kuningas, oli tehdä antanut, vältti hän sitä kauhistusta,',
        6: 'Ja piti itsensä templiin ja Jerusalemin jumalanpalvelukseen, ja palveli siellä Herraa, ja rukoili Israelin Jumalaa, antoi myös esikoisensa ja kymmenyksensä aivan uskollisesti,',
        7: 'Niin että hän aina kolmantena vuotena muukalaisille, leskille ja orvoille heidän kymmenyksensä antoi.',
        8: 'Ne hän piti nuoruudestansa, Herran lain jälkeen.',
        9: 'Kuin hän nyt mieheksi kasvanut oli, otti hän vaimon Naphtalin suvusta, Hannan nimeltä, ja siitti pojan, jonka hän myös Tobiaksi nimitti,',
        10: 'Ja opetti hänen nuoruudesta Jumalan sanassa, Jumalaa pelkäämään ja syntiä välttämään.',
        11: 'Ja kuin hän kaiken sukunsa, vaimonsa ja poikansa kanssa vietiin pois vankein seassa, Niniven kaupunkiin,',
        12: 'Ja jokainen söi pakanain uhrista ja ruasta, vältti hän sitä ja ei saastuttanut itsiänsä senkaltaisella rualla.',
        13: 'Ja että hän koko sydämestänsä Herraa pelkäsi, antoi Jumala hänelle armon Salmanasserin, Assyrian kuninkaan edessä,',
        14: 'Että hän antoi hänelle luvan käydäksensä, kuhunka hän tahtoi, ja toimittaa, mitä hänellä tekemistä oli.',
        15: 'Niin hän meni kaikkein tykö, jotka vankina olivat, ja lohdutti heitä Jumalan sanalla,',
        16: 'Ja tuli Median kaupunkiin Ragekseen, ja hänen myötänsä oli kymmenen leiviskää hopiaa, jotka kuningas hänelle antanut oli.',
        17: 'Ja kuin hän muiden Israelilaisten seassa näki yhden suvustansa, nimeltä Gabelin, joka sangen köyhä oli, antoi hän hänelle sen rahan, ja otti kirjoituksen häneltä',
        18: 'Sitoo pitkän ajan perästä, Salmanasserin kuoleman jälkeen, kuin hänen poikansa Sennaherib hänen jälkeensä hallitsi, joka Israelin lasten vihamies oli,',
        19: 'Kävi Tobia joka päivä kaikkein Israelilaisten tykönä, ja lohdutti heitä, ja jakoi itsekullekin hyvyydestänsä voimansa jälkeen.',
        20: 'Isoovaisia hän ruokki, alastomia hän vaatetti, tapetuita ja kuolleita hän hautasi.',
        21: 'Mutta kuningas Sennaherib oli paennut Juudeasta, kuin Jumala hänen lyönyt oli, hänen pilkkaamisensa tähden. Kun hän nyt palasi, oli hän kiukuissansa ja antoi tappaa paljo Israelin lapsia; niiden ruumiit toimitti Tobia hautaan.',
        22: 'Mutta koska kuningas sen tietää sai, käski hän hänen tapettaa, ja otti häneltä kaiken hänen tavaransa. Vaan Tobia pakeni vaimonsa ja poikansa kanssa, ja piti itsensä salaa hyväin ystäväinsä tykönä. Vaan viiden päivän perästä viidettäkymmentä tapettiin kuningas omilta pojiltansa. Ja Tobia tuli jälleen kotiansa, ja kaikki hänen tavaransa annettiin hänelle jälleen.',
    },
    2: {
        1: 'Senjälkeen, Herran juhlapäivänä, kuin Tobia huoneessansa kuuluisan vieraspidon valmistanut oli,',
        2: 'Sanoi hän pojallensa: mene ja kutsu ne jumaliset meidän suvustamme meidän kanssamme rualle.',
        3: 'Ja kuin hän palasi, sanoi hän isällensä Tobialle: yksi Israelilainen on kuolleena kadulla.',
        4: 'Niin nousi Tobia kohta pöydästä, ennenkuin hän söi, ja meni kuolleen ruumiin tykö, ja otti sen, ja kantoi salaa huoneesensa, että hän sen salaa hautais yöllä.',
        5: 'Ja kuin hän ruumiin salaa kätkenyt oli, söi hän leipäänsä murheessansa.',
        6: 'Ja ajatteli sitä sanaa: jonka Herra Amos prophetan kautta puhunut oli: teidän juhlapäivänne pitää murhepäiväksi tuleman.',
        7: 'Ja meni yöllä ja hautasi kuolleen.',
        8: 'Mutta hänen ystävänsä nuhtelivat häntä ja sanoivat: äsken käski kuningas sinun tapettaa sen asian tähden, ja sinä olet tuskin siitä päässyt, ja kuitenkin hautaat kuolleita.',
        9: 'Mutta Tobia pelkäsi Jumalaa enemmän kuin kuningasta, ja kantoi salaisesti kokoon ne tapetut, ja piti salaa huoneessansa, ja yöllä hän hautasi heidät.',
        10: 'Mutta se tapahtui yhtenä päivänä, kuin hän kotia tuli kuolleita hautaamasta, ja oli väsyksissä, ja nojasi seinukselle, ja nukkui,',
        11: 'Putosi pääskysen pesästä palava sonta hänen silmiinsä, josta hän tuli sokiaksi.',
        12: 'Mutta senkaltaisen vaivan antoi Jumala tulla hänen päällensä, että jälkeentulevaiset oppisivat kärsimään, niinkuin pyhästä Jobista.',
        13: 'Ja että hän aina nuoruudestansa Jumalaa peljännyt ja hänen käskynsä pitänyt oli, ei hän vihastunut eikä napissut Jumalaa vastaan, että hän oli antanut hänen sokiaksi tulla;',
        14: 'Vaan pysyi lujana Jumalan pelvossa ja kiitti Jumalaa kaiken elinaikansa. Ja niinkuin kuninkaat pyhää Jobia nauroivat, niin myös Tobiaa nauroivat hänen ystävänsä, Ja sanoivat: kussa nyt sinun uskallukses on, jonka tähden sinä almujas jakanut ja niin paljo kuolleita haudannut olet? Ja Tobia nuhteli heitä ja sanoi: älkäät sanoko niin; Sillä me olemme pyhäin lapset, ja odotamme elämää, jonka Jumala antaa niille, jotka uskossa vahvana ja lujana pysyvät hänen edessänsä. Mutta Hanna, hänen emäntäinsä, teki viriästi työtä käsillänsä, ja ruokki hänen kehräämisellä. Mutta se tapahtui, että hän nuoren vuohen toi kotia, Ja kuin hänen miehensä Tobia kuuli sen määkyvän, sanoi hän: katsokaat ettei se varastettu ole, antakaat häntä isännällensä jälleen; sillä ei meidän sovi syödä varastetusta kalusta, eikä siihen ryhtyä. Siitä puheesta vihastui hänen emäntänsä, vastasi ja sanoi: tästä nähdään, että sinun uskallukses ei ole mitään, ja sinun almus ovat hukkuneet. Senkaltaisilla ja muilla sanoilla soimasi hän hänelle hänen viheliäisyyttänsä.',
    },
    3: {
        1: 'Silloin huokasi Tobia raskaasti ja rupesi itkemään ja rukoilemaan la sanoi:',
        2: 'Herra, sinä olet hurskas, ja kaikki sinun työs ovat oikiat, ja sula hyvyys ja uskollisuus!',
        3: 'Ja nyt minun Herrani, ole minulle armollinen, ja älä kosta minun syntiäni, älä muistele minun eli minun isäni pahoja tekoja;',
        4: 'Sillä ettemme sinun käskyjäs pitäneet, niin me myös olemme annetut meidän vihollisillemme, että he meitä ryöstävät, vankina pitävät ja tappavat, ja olemme häväistykseksi, nauruksi ja pilkaksi tulleet muukalaisille, kuhunkas meidät hajoittanut olet.',
        5: 'Ja nyt, Herra! hirmuiset ovat sinun tuomios, ettemme sinun käskyjäs pitäneet ole, emmekä oikein sinun edessäs vaeltaneet.',
        6: 'Ah Herra, osoita minulle armo, ja korjaa minun henkeni rauhassa; sillä minä tahtoisin paljoa paremmin kuolla kuin elää.',
        7: 'Ja se tapahtui sinä päivänä, että Saara Raguelin tytär, Mediläisten kaupungista Rageksesta, myös pahoin häväistiin ja soimattiin isänsä piialta.',
        8: 'Hän oli annettu seitsemälle miehelle toinen toisensa jälkeen, ja paha henki, Asmodi nimeltä, oli heidät kaikki tappanut, kohta kuin he vuoteesen tulivat hänen tykönsä.',
        9: 'Sentähden soimasi häntä hänen isänsä piika ja sanoi:',
        10: 'Jumala tehköön, ettemme ikänä sinusta näkisi poikaa eli tytärtä maan päällä, sinä miestes murhaaja!',
        11: 'Tahdotkos minunkin tappaa, niinkuin sinä ne seitsemän miestä tappanut olet?',
        12: 'Niiden sanain tähden meni hän kammioon huoneen päälle, ja ei syönyt eikä juonut kolmena päivänä, ja ei lakannut rukoilemasta ja itkemästä, ja rukoili Jumalaa, että hän hänen siitä häväistyksestä vapahtais.',
        13: 'Sitte kolmantena päivänä, kuin hän rukouksensa päättänyt oli, kiitti hän Jumalaa ja sanoi:',
        14: 'Kiitetty olkoon sinun nimes, Herra, meidän isäimme Jumala! Sillä koska sinä vihastut, osoitat sinä armon ja hyvyyden, ja ahdistuksessa sinä synnit anteeksi annat niille, jotka sinua avuksensa huutavat.',
        15: 'Sinun puolees, minun Herrani, käännän minä kasvoni; sinun tykös minä nostan silmäni,',
        16: 'Ja rukoilen sinua, ettäs minun pelastaisit tästä raskaasta häväistyksestä, eli minun täältä korjaisit.',
        17: 'Sinä tiedät, Herra, etten minä miestä himoinnut ole, ja olen minun sieluni puhtaana pitänyt kaikista pahoista himoista, enkä ole koskaan häpeemättömäin ja rivoin joukossa ollut. Miestä ottamaan olen minä mielistynyt sinun pelvossas ja en hempeydestä. Taikka en ole minä heidän, elikkä ei he minun vertaiseni olleet, ja sinä olet minua mitämaks säästänyt toiselle miehelle; Sillä sinun neuvos ei ole ihmisen voimassa. Mutta sen minä kyllä todeksi tiedän: joka Jumalaa palvelee, se kiusauksen jälkeen lohdutetaan, ja murheesta pelastetaan, ja kurituksen jälkeen löytää armon. Sillä et sinä mielisty meidän kadotukseemme; sillä pahan ilman perästä annat sinä auringon paistaa, ja parun ja itkun perästä täytät sinä meidät ilolla. Sinun nimelles, Israelin Jumala, olkoon ijankaikkinen kiitos ja ylistys! Sillä hetkellä kuultiin heidän molempain rukouksensa Herralta taivaassa. Ja Pyhä Raphael, Herran enkeli, lähetettiin heitä molempia auttamaan, että heidän rukouksensa yhtä haavaa tuotiin Herran eteen.',
    },
    4: {
        1: 'Kuin Tobia luuli rukouksensa kuulluksi, että hänen kuoleman piti, kutsui hän poikansa tykönsä, ja sanoi hänelle:',
        2: 'Minun poikani, kuule minun sanani, ja pidä ne lujasti sinun sydämessäs!',
        3: 'Kuin Jumala minun sieluni korjaa, niin hautaa minun ruumiini, ja kunnioita sinun äitiäsi kaikkena elinaikanas.',
        4: 'Muista, mitä vaaraa hän kärsi, kuin hän sinun sydämensä alla kantoi.',
        5: 'Ja kuin hän kuolee niin hautaa häntä minun viereeni.',
        6: 'Ja kaikkena sinun elinaikanas pidä Jumala silmäis edessä ja sydämessäs, ja karta, ettet mihinkään syntiin mielisty ja Jumalan käskyä vastaan tee.',
        7: 'Sinun tavarastas auta köyhiä, ja älä käännä itsiäs pois köyhästä, niin Jumala taas armollisesti katsoo sinun päälles.',
        8: 'Kussas taidat, niin auta tarvitsevaa.',
        9: 'Jos sinulla paljo on, niin anna runsaasti: jos sinulla vähä, niin anna vähästä hyvällä mielellä.',
        10: 'Sillä sinä kokoot sinulles hyvän palkan tuskassa;',
        11: 'Sillä almu pelastaa kaikesta synnistä ja kuolemasta, ja ei hylkää hädässä.',
        12: 'Almu on hyvä lohdutus korkeimman Jumalan edessä.',
        13: 'Karta, poikani, kaikkinaista huoruutta, ja paitsi omaa vaimoas älä keneenkään muuhun suostut.',
        14: 'Älä anna ylpeyden hallita ei sydämessäs eli sanoissas; sillä se on kaiken kadotuksen alku.',
        15: 'Joka sinun työtäs tekee, anna hänelle kohta hänen palkkansa, ja älä pidä keltäkään ansaittua palkkaansa.',
        16: 'Jota et tahdo keneltäkään sinulles tehtää, katso, ettet sitä myös toiselle tee.',
        17: 'Jaa leipäs isoovaiselle, ja peitä alastomia vaatteillas.',
        18: 'Anna almua leivästäs ja viinastas jumalisten hautaamisissa, ja älä syö elikkä juo syntisten kanssa.',
        19: 'Kysy aina neuvoa viisailta.',
        20: 'Ja kiitä aina Jumalaa, ja rukoile, että hän sinun hallitsis, ja ettäs kaikissa töissäs seuraisit hänen sanaansa.',
        21: 'Sinun pitää myös tietämän, poikani, että minä kymmenen leiviskää hopiaa, läsnäollessas, lainasin Gabelille Rageksen kaupungissa Mediassa, ja hänen kirjoituksensa on minulla. Sen tähden ajattele, kuinka hänen tykönsä tulisit ja anoisit rahan, ja antaisit jälleen hänen kirjoituksensa. Älä murehdi, poikani! Me olemme tosin köyhät, mutta me saamme paljo hyvää, jos me Jumalaa pelkäämme, vältämme syntiä ja teemme hyvää.',
    },
    5: {
        1: 'Silloin vastasi nuori Tobia isäänsä ja sanoi: kaikki, mitäs minulle sanonut olet, minun isäni, tahdon minä tehdä.',
        2: 'Mutta kuinka minun tätä rahaa anoman pitää, en minä tiedä: ei hän minua tunne, enkä minä häntä. Mitä minun pitää merkiksi viemän; että hän minun uskois? En tiedä minä myös tietä sinne.',
        3: 'Niin vastasi häntä hänen isänsä, ja sanoi: hänen kirjoituksensa on minulla; koskas sen hänelle näytät, niin hän kohta sinulle antaa rahan.',
        4: 'Mene nyt ja etsi sinulles uskollinen kumppani, joka palkan edestä sinun kanssas menis, ettäs sen rahan minun eläissäni jälleen saisit.',
        5: 'Niin meni nuori Tobia ulos, Ja löysi kauniin nuorukaisen seisomasta, joka oli itsensä vyöttänyt ja valmistanut vaeltamaan,',
        6: 'Ja ei tietänyt, että se Jumalan enkeli oli, tervehti häntä ja sanoi: kustas olet, hyvä nuorukainen?',
        7: 'Ja hän sanoi: minä olen Israelin lapsista.',
        8: 'Tobia sanoi hänelle: tiedätkös tien Median maalle? Hän vastasi: tiedän kyllä, ja olen usein sitä vaeltanut, ja olen majaa ollut meidän veljemme Gabelln tykönä, joka asuu Rageksessa Mediassa, joka on Ekbatanan vuorella.',
        9: 'Ja Tobia sanoi hänelle: odotas vähä aikaa, siihenasti että minä sen isälleni sanon.',
        10: 'Ja Tobia meni ja sanoi sen isällensä; ja isä ihmetteli, ja rukoili, että se nuorukainen tulis sisälle.',
        11: 'Ja hän meni sisälle vanhan tykö, ja tervehti häntä, ja sanoi: Jumala antakoon sinulle iloa!',
        12: 'Ja Tobia sanoi hänelle: mikä ilo minulla oleman pitäis, jonka pimeydessä istuman pitää, ja taivaan valkeutta en nähdä taida?',
        13: 'Ja nuorukainen sanoi hänelle: ole kärsivällinen; Jumala sinua pian auttaa.',
        14: 'Ja Tobia sanoi hänelle: tahdotkos minun poikani johdattaa Ragekseen Mediaan Gabelin tykö? niin minä annan sinulle sinun palkkas, kuin palajat.',
        15: 'Ja enkeli sanoi hänelle: minä tahdon hänen sinne viedä, ja jälleen sinun tykös tänne tuoda.',
        16: 'Ja Tobia sanoi hänelle: minä rukoilen sinua: sano minulle: mistä suvusta ja kenenkä sukukunnasta sinä olet?',
        17: 'Ja enkeli Raphael sanoi: ole ääneti! eikö siinä kyllä ole, että sinulla on sanansaattaja; mitä sinun tarvitsee tietää, kusta minä olen?',
        18: 'Kuitenkin ettäs sitä vähemmin pelkäisit, niin minä sanon sinulle: minä olen Atsaria, suuren Ananian poika.',
        19: 'Ja Tobia sanoi: sinä olet hyvästä suvusta. Minä rukoilen sinua, ettet vihastuisi, että minä sinun sukuas kysynyt olen.',
        20: 'Ja enkeli sanoi: minä tahdon sinun poikas terveenä sinne ja jälleen tänne saattaa.',
        21: 'Tobia vastasi: niin menkäät matkaan, Jumala olkoon teidän kanssanne tiellä, ja hänen enkelinsä johdattakoon teitä!',
        22: 'Silloin valmisti Tobia itsensä ja kaikki, mitä hän kanssansa ottaa tahtoi, ja siunasi isänsä ja ja äitinsä, ja meni matkaansa kumppaninensa. Ja hänen äitinsä rupesi itkemään ja sanoi: meidän vanhuuden lohdutuksen olet sinä ottanut ja lähettänyt pois. Minä soisin, ettei se raha ikänä olisi ollut, jonka tähden sinä hänen olet lähettänyt pois. Me olisimme tyytyneet meidän köyhyytemme; se olis suuri rikkaus, että meidän poikamme tykönämme olis. Ja Tobia sanoi: älä itke! meidän poikamme menee raittiina ja palajaa terveenä, ja sinun silmäs pitää näkemän hänen. Sillä minä uskon, että Jumalan hyvä enkeli johdattaa hänen, ja kaikki hyvin toimittaa, mitä hänellä toimittamista on, niin että hän ilolla jälleen meidän tykömme palajaa. Niin hänen äitinsä vaikeni ja tyytyi siihen.',
    },
    6: {
        1: 'Ja Tobia meni matkaansa, ja koira juoksi hänen kanssansa, ja ensimäisen päivän matkana tulivat he Tygriksen virran tykö.',
        2: 'Ja hän meni pesemään jalkojansa; ja katso, suuri kala hyppäsi sieltä, ja tahtoi niellä hänen,',
        3: 'Jota Tobia hämmästyi, ja huusi täydellä äänellä ja sanoi: Herra, hän tahtoo minun syödä.',
        4: 'Ja enkeli sanoi hänelle: tartu hänen kiduksiinsa, ja vedä häntä ylös. Ja hän veti hänen maalle, niin hän pyrisi hänen jalkainsa edessä.',
        5: 'Silloin sanoi enkeli: halkaise kala kahtia: sydän, maksa ja sappi pidä itselles; sillä ne ovat sangen hyvät voiteeksi.',
        6: 'Ja monikahdat kappaleet kalasta he paistoivat ja ottivat kanssansa matkalle: ne muut he suolasivat evääksi matkalle, siihenasti että he tulisivat Rageksen Mediaan.',
        7: 'Niin Tobia kysyi enkeliltä Ja sanoi hänelle: minä rukoilen sinua, Atsaria veljeni. ettäs sanoisit minulle, mitä voiteita niistä kappaleista tehdä taidetaan, jotka minun käskit tähdellä pitää?',
        8: 'Niin enkeli sanoi: koska kappaleen sydäntä ja maksaa panet tulisten hiilten päälle, niin se savu karkottaa kaikkinaiset kyöpelit miehen ja vaimon tyköä, niin ettei he enää vahingoittaa taida.',
        9: 'Ja kalan maksa on hyvä silmiä voidella, että kalvo pois kuluu.',
        10: 'Ja Tobia sanoi: kuhunka me poikkeemme? Ja enkeli vastasi ja sanoi:',
        11: 'Tässä on yksi mies, Raguel nimeltä, sinun lankos sinun suvustas, hänellä on ainoastaan yksi tytär, Saara nimeltä, ja ei yhtään muuta lasta.',
        12: 'Sinulle ovat kaikki hänen tavaransa aiotut, ja sinä otat hänen tyttärensä.',
        13: 'Ano siis häntä hänen isältänsä niin hän antaa hänen sinulle emännäksi.',
        14: 'Niin sanoi Tobia: minä olen kuullut, että hän jo ennen seitsemälle miehelle annettu on, ne kaikki ovat kuolleet; päälliseksi sanotaan, että paha henki on heidät tappanut. 3: 7, etc.',
        15: 'Sentähden pelkään minä, ettei minun myös niin kävisi, niin kuolisivat minun vanhempani murheisiinsa, että minä ainoa poika olen.',
        16: 'Silloin sanoi enkeli Raphael: kuule, minä sanon sinulle, keiden päälle perkeleellä valta on:',
        17: 'Nimittäin niiden päälle, jotka katsovat Jumalan ylön, ja vaivoin haureuden tähden vaimoja ottavat, niinkuin järjettömät eläimet.',
        18: 'Mutta sinä, kuin morsiames kanssa kammioon tulet, pitää sinun kolme päivää pitämän sinus pois hänestä, ja hänen kanssansa rukoileman. Ja sinä yönä, kuin panet kalan sydämen ja maksan tulisten hiilten päälle, niin perkele tulee karkotetuksi. Toisena yönä pitää sinun hänen tykönsä menemän puhtaudessa, niinkuin pyhät patriarkat. Kolmantena yönä sinä saat! siunauksen, että terveet lapset teistä syntyvät. Mutta kuin kolmas yö kulunut on, niin sinun pitää neitseen tykö Jumalan pelvossa menemän enempi hedelmän himosta, kuin pahasta halusta, että sinä ja sinun lapses siunauksen saisitte, joka Abrahamin siemenelle luvattu on.',
    },
    7: {
        1: 'Ja he menivät Raguelin tykö, Ja Raguel otti vastaan heidät ilolla,',
        2: 'Ja katsoi Tobian päälle, Ja sanoi Ednalle emännällensä: kuinka tämä nuori mies on meidän lankomme muotoinen!',
        3: 'Ja kuin hän sen puhunut oli, sanoi hän: kusta te olette, minun veljeni? He sanoivat: me olemme Naphtalin suvusta niistä vangeista, jotka Ninivessä ovat.',
        4: 'Raguel sanoi heille: tunnetteko minun veljeni Tobian? Ja he sanoivat: me tunnemme hänen hyvin',
        5: 'Ja kuin hän nyt paljon hyvää puhui Tobiasta, sanoi enkeli Raguelille: Tobia, jonkas perään kysyt, on tämän nuoren miehen isä.',
        6: 'Ja Raguel nojasi hänen puoleensa, itki, rupesi hänen kaulaansa, ja suuta antoi hänen,',
        7: 'Ja sanoi: hyvästi siunattu ole sinä, minun rakas poikani; sillä sinä olet juuri jalon miehen poika.',
        8: 'Ja Edna hänen emäntänsä, ja Saara hänen tyttärensä rupesivat myös itkemään.',
        9: 'Sitte käski Raguel tappaa lampaan ja valmistaa ruokaa. Ja kuin he heitä rukoilivat pöydän tykö istumaan,',
        10: 'Sanoi Tobia: en minä tänäpänä syö enkä juo, ellet sinä myöten anna minulle minun rukoustani, ja lupaa minulle Saaraa, sinun tytärtäs.',
        11: 'Kuin Raguel sen kuuli, peljästyi hän, muistain, mitä niille seitsemälle miehelle tapahtunut oli, joille hän ennen tyttärensä antanut oli, ja pelkäsi, että tälle myös niin tapahtuman piti.',
        12: 'Ja kuin ei hän vastata tahtonut, sanoi enkeli hänelle: älä pelkää hänelle antaa piikaa: sinun tyttäres on hänelle aiottu vaimoksi; sillä hän pelkää Jumalaa, sentähden ei pitänyt yksikään muu sinun tytärtäs saaman.',
        13: 'Silloin sanoi Raguel: en minä epäile, ettei Jumala minun katkeroita kyyneleitäni ja rukouksiani kuullut ole,',
        14: 'Ja uskon, että hän sitä varten on teidän antanut minun tyköni tulla, että minun tyttäreni tämän sais hänen suvustansa, Moseksen lain jälkeen; ja älä nyt mitään epäile, minä annan hänen sinulle.',
        15: 'Ja otti tyttärensä käden ja löi Tobian käteen, ja sanoi: Abrahamin Jumala, Isakin Jumala, Jakobin Jumala olkoon teidän kanssanne, ja auttakoon teitä yhteen, ja antakoon siunauksensa runsaasti teille!',
        16: 'Ja he ottivat kirjan ja kirjoittivat avioliiton, Ja kiittivät Jumalaa ja pitivät vieraspitoa. Ja Raguel kutsui tykönsä emäntänsä Ednan, ja käski hänen toisen kammion valmistaa. Ja he veivät sinne tyttärensä Saaran, ja hän itki. Ja hän sanoi hänelle: ole hyvässä turvassa, minun tyttäreni: taivaan Herra antakoon sinulle ilon siitä murheesta, jonka sinä kärsinyt olet!',
    },
    8: {
        1: 'Ja ehtoollisen jälkeen veivät he nuoren Tobian neitseen tykö kammioon.',
        2: 'Ja Tobia muisti enkelin sanat, ja otti säkistänsä kappaleen sydäntä ja maksaa, ja pani ne tuo tulisille hiilille.',
        3: 'Ja enkeli Raphael otti sen hengen vangiksi, ja sitoi hänen kauvas Egyptin korpeen.',
        4: 'Sitte neuvoi Tobia neitsyttä ja sanoi: Saara, nouse, ja rukoilkaamme Jumalaa tänäpänä ja huomenna; sillä nämät kolme yötä me rukoilkaamme, ja senjälkeen olkaamme yhdessä niinkuin avioväki.',
        5: 'Sillä me olemme pyhäin lapset: ei meidän sovi sitä säätyä niin alkaa kuin pakanat, jotka Jumalan katsovat ylön.',
        6: 'Ja he nousivat ylös, ja rukoilivat ynnä hartaasti, että Jumala heitä varjelis.',
        7: 'Ja Tobia rukoili ja sanoi: Herra minun Jumalani, sinä meidän isäimme Jumala, sinua kiittäkään taivaat, maa, meri, kaikki vedet ja lähteet, ja kaikki luontokappaleet, kuin niissä ovat.',
        8: 'Sinä olet tehnyt Adamin maan tomusta ja olet hänelle antanut Hevan apulaiseksi.',
        9: "Ja nyt, Herra! sinä tiedät, etten minä pahasta himosta tätä minun sisartani vaimokseni ottanut ole, vaan että minä lapsia siittäisin, jonka kautta sinun pyhä' nimes iankaikkisesti kiitettäisiin ja ylistettäisiin.",
        10: 'Ja Saara sanoi: Herra, armahda meidän päällemme, että me molemmin terveinä mahtaisimme vanhuutemme saavuttaa.',
        11: 'Puoliyöstä huusi Raguel palveliansa, ja meni hänen kanssansa hautaa tekemään.',
        12: 'Sillä hän sanoi: mitämaks hänelle on niin tapahtunut, kuin muillekin seitsemälle, jotka hänen kihlanneet olivat.',
        13: 'Ja kuin he haudan tehneet olivat, tuli Raguel emäntänsä tykö ja sanoi:',
        14: 'Lähetä piika, ja anna katsoa, jos hänkin kuollut on, että me hänen ennen päivää hautaisimme.',
        15: 'Ja piika meni kammioon, ja löysi heidät molemmat terveinä ja raittiina makaavan toinen toisensa tykönä.',
        16: 'Ja hän toi heille hyvän sanoman. Ja Raguel emäntinensä kiittivät Jumalaa ja sanoivat:',
        17: 'Me kiitämme sinua, Herra Israelin Jumala, ettei se tapahtunut, jota me pelkäsimme; sillä sinä olet laupiutes meille näyttänyt, ja olet meidän vihollisemme, joka meidän pahaa teki, ajanut pois.',
        18: 'Sinä olet armahtanut näitä kahta ainoaa lasta. Ja nyt, Herra, anna heidän aina sinua kiittää senkaltaisen armon edestä, ja sinulle aina kiitosta uhrata, että muut ihmiset heissä tuntisivat, että sinä olet ainoa Jumala kaikessa maailmassa.',
        19: 'Ja Raguel käski kohta täyttää haudan ennenkuin päivä tulis.',
        20: 'Ja käski emäntänsä taas valmistaa vieraspidon, ja toimittaa heille kaikkinaiset tarpeet tielle',
        21: 'Ja hän antoi tappaa kaksi lihavaa härkää, ja neljä lammasta, ja kutsui kaikki lähimmäisensä ja ystävänsä vieraiksi Ja Raguel neuvoi ja rukoili suuresti Tobiaa viipymään tykönänsä kaksi viikkoa. Ja kaikesta tavarastansa antoi hän puolen Tobialle, ja teki kirjoituksen, että hänen kuolemansa jälkeen toinen puoli myös Tobian olis.',
    },
    9: {
        1: 'Silloin kutsui Tobia enkelin tykönsä, sillä hän luuli hänen ihmiseksi, ja sanoi hänelle: Atsaria, veljeni, minä rukoilen sinua, kuule minun sanani.',
        2: 'Vaikka minä itseni sinulle omaksi orjakses antaisin, niin ei kuitenkaan se mitään olisi sinun hyväin tekois suhteen.',
        3: 'Kuitenkin rukoilen minä, ota tämä palvelia ja kamelit, ja mene Gabelin tykö Rageksen Mediassa, ja anna hänelle tämä kirjoitus, ja ota häneltä se raha, ja rukoile häntä minun häihini tulemaan.',
        4: 'Sillä sinä tiedät, minun isäni lukee hetket ja päivät, ja jos minä päivänkin enempi viivyn, niin hänen sielunsa tulee murheelliseksi.',
        5: 'Ja sinä tiedät, kuinka hartaasti Raguel minua rukoillut on, etten minä häneltä kieltää taida.',
        6: 'Silloin otti enkeli Raphael Raguelin palvelian ja kaksi kamelia, ja meni Ragekseen ja löysi Gabelin, ja antoi hänelle kirjoituksen ja sai rahan häneltä, Ja ilmoitti hänelle kaikki, mitä tapahtunut oli Tobian pojalle, ja kutsui häntä häihin. Ja kuin he tulivat Raguelin huoneesen, löysivät he Tobian pöydän tykönä, ja katso, hän nousi hänen tähtensä ja antoivat suuta toinen toisensa. Ja Gabel itki, ja kiitti Jumalaa, ja sanoi: Israelin Jumala siunatkoon sinua; sillä sinä olet kunniallisen, hurskaan ja jumalisen miehen poika, joka vaivaisille paljo hyvää tehnyt on. Siunattu olkoon sinun vaimos ja sinun vanhempas. Ja Jumala antakoon teidän nähdä teidän lapsenne ja lastenne lapset kolmanteen ja neljänteen polveen, ja siunattu olkoon sinun siemenes Israelin Jumalalta, joka hallitsee ja vallitsee ijankaikkiseen! Ja kuin he kaikki amen! sanoneet olivat, istuivat he pöydän tykö, vaan he aterioitsivat ja iloitsivat Jumalan pelvossa.',
    },
    10: {
        1: 'Kuin nuori Tobia häittensä tähden kauvan oli poissa, rupesi vanha Tobia, hänen isänsä, murehtimaan ja sanoi: miksi minun poikani niin kauvan poissa on, ja mikä häntä viivyttää?',
        2: 'Mitämaks Gabel on kuollut, ja ei kenkään tahdo hänelle rahaa maksaa.',
        3: 'Ja tulivat sangen murheellisiksi, Tobia ja Hanna hänen emäntänsä, ja itkivät molemmin, ettei heidän poikansa määrätyllä ajalla kotia tullut.',
        4: 'Ja hänen äitinsä itki niin ettei hän tahtonut itsiänsä lohduttaa antaa, ja sanoi: voi minun poikani! voi minun poikani! miksi me olemme päästäneet sinun vaeltamaan? meidän ainoan ilomme meidän ainoan lohdutuksemme vanhuudessamme, meidän sydämemme ja meidän perillisemme.',
        5: 'Meillä olisi kyllä tavaraa ollut, jos emme sinua olisi päästäneet pois.',
        6: 'Ja Tobia sanoi hänelle: ole ääneti ja hyvässä turvassa! ei meidän pojallamme Jumalan avulla hätää ole, hänellä on uskollinen kumppani kanssansa.',
        7: 'Vaan ei hän tahtonut itsiänsä antaa lohduttaa, ja juoksi joka päivä ulos ja katsoi joka kujalle kusta hänen tuleman piti, jos hän, jossakussa hänen näkis.',
        8: 'Mutta Raguel sanoi vävyllensä Tobialle: pysy meidän tykönämme, minä tahdon sanan lähettää Tobialle sinun isälles, ja hänen tietää antaa, ettäs terveenä olet.',
        9: 'Ja Tobia sanoi: minä tiedän että minun isäni ja äitini parhaallansa lukevat jokaisen päivän ja hetken, ja ovat minun tähteni kovin murheissansa.',
        10: 'Ja kuin Raguel monilla sanoilla rukoili Tobiaa, ja ei hän millään muotoa sitä tehdä tahtonut, antoi hän hänelle Saaran, ja antoi hänelle puolen kaikesta tavarastansa, palvelioista, piioista, karjasta, kameleista ja härjistä ja paljon rahaa, ja antoi hänen terveenä ja iloisena tyköänsä mennä pois, ja sanoi:',
        11: 'Herran pyhä enkeli olkoon sinun kanssas tiellä, ja saattakoon sinun terveenä kotia jälleen, ettäs löytäisit vanhempas terveenä; ja Jumala antakoon minun silmäni nähdä teidän lapsenne ennen kuin minä kuolen!',
        12: 'Ja vanhemmat ottivat tyttärensä, ja suuta antoivat hänen, ja päästivät hänen tyköänsä,',
        13: 'Ja neuvoivat häntä, että hän pitäis miehensä vanhemmat kunniassa, niinkuin omat vanhempansa, rakastais miestänsä, hallitsis visusti perheen, pitäis itsensä kunniallisesti.',
    },
    11: {
        1: 'Ja tiellä, kuin he tulivat Haraniin, joka on puolivälissä Ninivetä, ensimmäisenä päivänä toistakymmentä,',
        2: 'Sanoi enkeli: veljeni Tobia, sinä tiedät, mihinkä tilaan sinä jätit isäs;',
        3: 'Jos sinun tahtos on, niin käykäämme edellä, ja antakaamme sinun emäntäs väen ja karjan kanssa jäljestä tulla.',
        4: 'Ja kuin se Tobialle kelpasi, sanoi Raphael: ota myötäs kalan sappea, sillä se on tarpeellinen. Niin Tobias otti tykönsä kalan sappea, ja he menivät niin edellä.',
        5: 'Mutta Hanna istui joka päivä tien vieressä mäellä, niin että hän sai katsoa kauvas ympärillensä.',
        6: 'Ja kuin hän siinä paikassa katseli, näki hän poikansa kaukaa ja tunsi kohta hänen, ja juoksi ilmoittamaan miehellensä, ja sanoi: katso, sinun poikas tulee!',
        7: 'Ja Raphael sanoi Tobialle: kohta kuin sinä huoneesen tulet, niin rnkoile ja huuda Herran tykö, ja kiitä häntä, ja mene sitte isäs tykö, ja anna hänelle suuta.',
        8: 'Ja voitele kohta hänen silmänsä kalan sapella, joka sinulla on, niin hänen silmänsä kohta aukenevat, ja sinun isäs taas näkee ja suuresti iloitsee.',
        9: 'Niin juoksi koira edellä, jonka he kanssansa ottaneet olivat, ja liehakoitsi hännällänsä, hyppeli ja oli iloinen.',
        10: 'Ja hänen sokia isänsä nousi äkisti, ja kiiruhti niin kovin, että hän loukkasi itsensä; niin hän kutsui palvelian tykönsä, joka häntä talutti kädestä kohtaamaan poikaansa.',
        11: 'Sitä teki myös äiti, ja he suuta antoivat hänelle, ja itkivät molemmin ilosta.',
        12: 'Ja kuin he rukoilleet olivat ja kiittäneet Jumalaa, istuivat he kaikki maahan.',
        13: 'Silloin otti Tobia kalan sappea, ja voiteli isänsä silmät.',
        14: 'Ja hän kärsi sitä puolen hetkeä, ja kaihi läksi hänen silmistänsä, niinkuin munan kalvo!',
        15: 'Ja Tobia otti sen ja repäisi pois hänen silmistänsä, ja hän sai kohta näkönsä jälleen.',
        16: 'Ja he kiittivät Jumalaa, hän ja hänen emäntänsä, ja kaikki jotka sen tietää saivat.',
        17: 'Ja Tobia sanoi: minä kiitän sinua Herra, Israelin Jumala, ettäs minua kuritit, ja autit minua jälleen, niin että minä rakkaan poikani saan nähdä jälleen.',
        18: 'Ja seitsemän päivän perästä tuli Saara, hänen poikansa vaimo, kaiken perheensä, karjansa ja kameleinsa kanssa, ja toi paljo rahaa kanssansa, niin myös sen rahan, jonka hän Gabelilta saanut oli. Ja Tobia jutteli vanhemmillensa, kuinka paljon hyvää Jumala hänelle tehnyt oli, sen kumppanin kautta, Joka hänen kanssansa vaeltanut oli. Akior ja Nabat, Tobian langot, tulivat hänen tykönsä ja toivottivat hänelle onnea, ja iloitsivat hänen kanssansa kaikesta siitä hyvästä, jonka Herra hänelle antanut oli. Ja he söivät yhdessä seitsemän päivää, ja olivat iloiset',
    },
    12: {
        1: 'Sitte kutsui Tobia poikansa tykönsä, ja sanoi: mitä me annamme sille pyhälle miehelle, joka sinun kanssas vaeltanut on?',
        2: 'Ja Tobia vastasi isäänsä: kuinka me taidamme maksaa hänelle ne hyvät työt, Jotka hän minulle tehnyt on?',
        3: 'Hän on minun terveenä vienyt pois, ja tuonut kotia jälleen: hän toi sen rahan Gabelilta itse, ja autti minua tälle emännälle, niin hän myös ajoi pois pahan hengen, ja teki hänen vanhempansa iloisiksi. Jopa hän autti minua itse, kuin minun suuri kala niellä tahtoi, ja antoi sinulle näkös jälleen, ja on tehnyt meille sangen paljon hyvää.',
        4: 'Kuinka siis me taidamme maksaa hänelle senkaltaiset hyvät työt? Mutta minä rukoilen sinua, isäni, taritse hänelle puoli kaikesta siitä tavarasta, jonka me myötämme tuoneet olemme, että hän ne ottais.',
        5: 'Ja molemmat sekä isä että poika kutsuivat hänen erinänsä, ja rukoilivat häntä ottamaan puolen kaikesta siitä tavarasta, jonka he myötänsä tuoneet olivat. Ja minä olen Raphael, yksi niistä seitsemästä enkelistä, jotka seisomme Herran edessä.',
        6: 'Ja hän sanoi heille salaisesti: kiittäkäät te ja kunnioittakaat taivaan Jumalaa jokaisen edessä, että hän teille senkaltaisen armon näyttänyt on.',
        7: 'Kuningasten ja päämiesten neuvoa ja salaisuutta pitää salattaman; mutta Jumalan töitä pitää korkiasti ylistettämän ja julistettaman.',
        8: 'Senkaltainen rukous paastolla ja almuilla on parempi kuin kultaa koota tavaraksi.',
        9: 'Sillä almut vapahtavat kuolemasta, pyyhkivät pois synnit, ja pitävät elämässä.',
        10: 'Mutta jumalattomat saattavat itsensä pois hengeltänsä.',
        11: 'Niin minä nyt ilmoitan teille totuuden, ja en salaa teiltä sitä salaista käskyä.',
        12: 'Kuin sinä niin katkerasti itkit ja rukoilit, ja nousit rualta, ja hautasit kuolleita, kätkit ruumiit salaa huoneeses, ja hautasit ne yöllä, silloin minä kannoin sinun rukoukses Herran eteen.',
        13: 'Ja ettäs Jumalalle kelpasit, niin sen piti niin oleman; ilman kiusausta ei sinun pitänyt oleman, ettäs olisit koetelluksi tullut.',
        14: 'Ja Jumala on minun lähettänyt parantamaan sinua, ja ajamaan pois sitä pahaa henkeä, joka Saaran sinun poikas emännän tykönä oli.',
        16: 'Ja kuin he sen kuulivat, hämmästyivät he, vapisivat ja lankesivat maahan kasvoillensa.',
        17: 'Ja. enkeli sanoi heille: Olkaat hyvässä turvassa, ja älkäät peljätkö.',
        18: 'Sillä se kuin minä teidän tykönänne ollut olen, sen on Jumala niin tahtonut; kiittäkäät ja kunnioittakaat häntä.',
        19: 'Minä olin syövinäni ja juovinani teidän kanssanne, mutta minä nautitsen näkymätöintä ruokaa, jota ei yksikään ihminen nähdä taida.',
        20: 'Ja nyt on aika, että minä menen taas hänen tykönsä, joka minun on lähettänyt; kunnioittakaat te Jumalaa ja ilmoittakaat hänen ihmeitänsä!',
        21: 'Ja kuin hän sen sanonut oli, katosi hän heidän silmäinsä edestä, ja ei he häntä enää nähneet.',
        22: 'Ja he lankesivat maahan kolmeksi hetkeksi, ja kunnioittivat Jumalaa; sitte nousivat he ja sanelivat niitä, ja ilmoittivat hänen suuria ihmeitänsä.',
    },
    13: {
        1: 'Mutta Tobia avasi suunsa, kiitti Jumalaa ja sanoi: Herra, sinä olet suuri ja väkevä Jumala, ja sinun valtakuntas pysyy ijankaikkiseen.',
        2: 'Sinä kuritat, ja lohdutat jälleen; sinä taidat sysätä helvettiin, ja taas ottaa sieltä ulos; sinun kättäs ei taida kenkään välttää.',
        3: 'Te Israelin lapset, kiittäkäät Herraa, ja ylistäkäät häntä pakanain edessä.',
        4: 'Sillä sen tähden on hän teidät hajoittanut pakanain sekaan, jotka ei häntä tunne, ilmoittamaan hänen ihmeitänsä, ja että pakanat ymmärtäisivät, ettei kenkään ole kaikkivaltias Jumala, vaan hän ainoastaan.',
        5: 'Hän on kurittanut meitä meidän synteimme tähden, ja laupiudestansa hän meitä jälleen auttaa.',
        6: 'Katsokaat, mitä hän meidän kanssamme tehnyt on, ja kiittäkäät häntä pelvolla ja vavistuksella; kiittäkäät häntä hänen töissänsä, ylistäkäät häntä, joka ijankaikkisesti hallitsee.',
        7: 'Ja minä myös tahdon kiittää häntä tässä maassa, jossa me vankina olemme; sillä hän on näyttänyt ihmeensä syntiselle kansalle.',
        8: 'Sentähden palatkaat, te syntiset, ja tehkäät vanhurskantta Jumalan edessä, ja uskokaat, että hän teille laupiutensa osoittaa.',
        9: 'Ja minä tahdon nyt sydämestäni iloita Jumalassa.',
        10: 'Kiittäkäät Herraa, te hänen valittunsa, pitäkäät ilopäiviä, ja kiittäkäät häntä.',
        11: 'Jerusalem, sinä Jumalan kaupunki! Jumala kurittaa sinua sinun töittes tähden, mutta hän taas armahtaa sinua.',
        12: 'Kiitä Herraa hänen lahjainsa edessä, ja ylistä ijankaikkista Jumalaa, että hän taas rakentais sinun majas ja tois jälleen kaikki sinun vankis, niin ettäs iloitsisit ijankaikkisesti.',
        13: 'Sinun pitää paistaman niinkuin kirkas valkeus, ja kaikissa maailman äärissä pitää sinua kunnioitettaman.',
        14: 'Kaukaiselta maalta pitää sinun tykös tultaman, ja lahjoja kannettaman.',
        15: 'Sinussa pitää rukoiltaman Herraa, ja sinua pitää pyhäksi kutsuttaman. Herran suurta nimeä pitää sinussa avuksihuudettaman.',
        16: 'Kirotut pitää kaikki oleman, jotka katsovat sinua ylön; kadotetuksi pitää tuleman kaikki, jotka sinua pilkkaavat; siunatut pitää oleman kaikki, jotka sinua rakentavat.',
        17: 'Mutta sinun pitää iloitseman sinun lapsistas; sillä he tulevat kaikki siunatuksi, ja pitää koottaman Herran tykö. Autuaat ovat ne, jotka sinua rakastavat, ja jotka sinulle onnea toivottavat. Minun sieluni kiittäkään Herraa; sillä Herra meidän Jumalamme lunastaa Jerusalemin kaupungin kaikista murheistansa. Autuas minäkin olen, jos jääneet minun suvustani saavat nähdä Jerusalemin kunniassansa. Jerusalemin portit pitää saphirista ja smaragdista rakennetut oleman, ja kaikki hänen muurinsa kalliista kivistä joka puolelta. Valkiasta ja puhtaasta marmorista pitää kaikki hänen katunsa lasketut oleman, ja joka kadulla pitää veisattaman Halleluja! Kiitetty olkoon Jumala, joka hänen on korottanut, ja hänen valtakuntansa pysyköön ijankaikkisesti hänen päällänsä, amen.',
    },
    14: {
        1: 'Kuin nämät olivat tapahtuneet, ja Tobia oli näkönsä saanut jälleen, eli hän vielä sitte kaksiviidettäkymmentä ajastaikaa, ja näki lapsensa lapset.',
        2: 'Ja kuin hän sadan ja kahden ajastajan vanhana oli, haudattiin hän Ninivessä kunniallisesti.',
        3: 'Sillä kuin hän kuudenkuudettakymmentä ajastajan vanha oli, tuli hän sokiaksi, ja kuudentenakymmenentenä vuonna sai hän näkönsä jälleen.',
        4: 'Ja sen muun ikänsä kulutti hän ilolla ja menestyi Jumalan pelvossa, ja kuoli hyvässä rauhassa.',
        5: 'Mutta ennen kuolemaansa kutsui hän poikansa Tobian eteensä, ja seitsemän nuorta poikaista, hänen poikansa lasta, ja sanoi heille:',
        6: 'Ninive pitää pian hävitettämän, sillä ei Herran sana puutu; mutta Mediassa pitää vielä sitte kauvan rauhan oleman, ja meidän veljemme, jotka Israelin maalta hajoitetut ovat, pitää tuleman jälleen.',
        7: 'Ja meidän maamme, joka nyt kylmillä on, pitää joka paikassa asutuksi tuleman. Ja Jumalan huone, joka poltettu on, pitää rakennettaman jälleen, ja kaikki, jotka Jumalaa pelkäävät, sinne tuleman jälleen.',
        8: 'Ja pakanat pitää myös hylkäämän epäjumalansa, ja tuleman Jerusalemiin ja siellä asuman.',
        9: 'Ja kaikki pakanat ja kuninkaat pitää siellä iloitseman, ja palveleman Israelin Jumalaa.',
        10: 'Niin kuulkaat nyt, minun poikani, teidän isäänne: palvelkaat Herraa totuudessa, ja olkaat vaat hänessä, ja turvatkaat häneen täydellisesti.',
        11: 'Tehkäät, mitä hän käskenyt on, ja opettakaat se teidän lapsillenne, että he myös almua antaisivat, että he aina Jumalaa pelkäisivät ja luottaisivat hänen päällensä kaikesta sydämestänsä.',
        12: 'Ja, rakkaat lapset, kuulkaat minua, ja älkäät pysykö tässä Ninivessä, vaan kuin te äitinne haudanneet olette minun tyköni minun hautaani, niin nouskaat menemään täältä pois.',
        13: 'Sillä minä näen, että Niniven synti lopettaa hänen.',
        14: 'Ja kohta äitinsä kuoleman jälkeen meni Tobia Ninivestä, emäntänsä, lastensa ja lasten lastensa kanssa Mediaan appensa ja emäntänsä sukuin tykö, ja löysi heidät terveinä hyvässä voimassansa, ja hän holhosi heitä.',
        15: 'Ja kuin he kuolivat, painoi hän myös heidän silmänsä kiinni, ja sai niin kaiken perinnön ja Raguelin tavaran, ja eli hamaan viidenteen polveen, ja näki lapsensa ja lastensa lapset. Ja kuin hän yhdeksänkymmenen ja yhdeksän vuotinen oli, jotka hän Jumalan pelvossa ilolla elänyt oli, hautasivat hänen sukunsa hänen. Ja kaikki hänen sukunsa elivät jumalisesti ja kunniallisesti, niin että he sekä Jumalalle että ihmisille ja kaikille, jotka maakunnassa asuivat, otolliset olivat.',
    },
}
