NAME = 'KLV: Klingon Language Version of the World English Bible'
BOOK = 'Philippians'

CHAPTERS = {
    1: {
        1: "Paul je Timothy, toy'wI'pu' vo' Jesus Christ; Daq Hoch the le' ghotpu' Daq Christ Jesus 'Iv 'oH Daq Philippi, tlhej the overseers { Note: joq, superintendents, joq bishops } je toy'wI'pu' { Note: joq, deacons }:",
        2: "Grace Daq SoH, je roj vo' joH'a', maj vav, je the joH Jesus Christ.",
        3: "jIH tlho' wIj joH'a' whenever jIH qaw SoH,",
        4: "always Daq Hoch request vo' mine Daq behalf vo' SoH Hoch making wIj requests tlhej Quch,",
        5: "vaD lIj partnership { Note: The mu' translated “partnership” (koinonia) je means “fellowship” je “sharing.” } Daq furtherance vo' the QaQ News vo' the wa'Dich jaj until DaH;",
        6: "taH voqtaHqu' vo' vam very Doch, vetlh ghaH 'Iv taghta' a QaQ vum Daq SoH DichDaq complete 'oH until the jaj vo' Jesus Christ.",
        7: "'oH ghaH 'ach nIH vaD jIH Daq think vam way Daq behalf vo' Hoch vo' SoH, because jIH ghaj SoH Daq wIj tIq, because, both Daq wIj bonds je Daq the defense je confirmation vo' the QaQ News, SoH Hoch 'oH partakers tlhej jIH vo' grace.",
        8: "vaD joH'a' ghaH wIj witness, chay' jIH tIq after Hoch vo' SoH Daq the tender mercies vo' Christ Jesus.",
        9: "vam jIH tlhob, vetlh lIj muSHa' may abound yet latlh je latlh Daq Sov je Hoch discernment;",
        10: "vaj vetlh SoH may approve the Dochmey vetlh 'oH excellent; vetlh SoH may taH 'Il je Hutlh offense Daq the jaj vo' Christ;",
        11: "taH tebta' tlhej the fruits vo' QaQtaHghach, nuq 'oH vegh Jesus Christ, Daq the batlh je naD vo' joH'a'.",
        12: "DaH jIH neH Daq ghaj SoH Sov, loDnI'pu', { Note: The mu' vaD “loDnI'pu'” naDev je nuqDaq context allows may je taH correctly translated “loDnI'pu' je sisters” joq “siblings.” } vetlh the Dochmey nuq qaSta' Daq jIH ghaj tlhe'ta' pa' rather Daq the progress vo' the QaQ News;",
        13: "vaj vetlh 'oH mojta' evident Daq the Hoch praetorian guard, je Daq Hoch the leS, vetlh wIj bonds 'oH Daq Christ;",
        14: "je vetlh HochHom vo' the loDnI'pu' Daq the joH, taH voqtaHqu' vegh wIj bonds, 'oH latlh abundantly bold Daq jatlh the mu' vo' joH'a' Hutlh taHvIp.",
        15: "'op indeed preach Christ 'ach pa' vo' envy je strife, je 'op je pa' vo' QaQ DichDaq.",
        16: "The former insincerely preach Christ vo' selfish ambition, thinking vetlh chaH chel affliction Daq wIj chains;",
        17: "'ach the latter pa' vo' muSHa', knowing vetlh jIH 'oH wIv vaD the defense vo' the QaQ News.",
        18: "nuq ta'taH 'oH matter? neH vetlh Daq Hoch way, whether Daq pretense joq Daq vIt, Christ ghaH proclaimed. jIH yItIv Daq vam, HIja', je DichDaq yItIv.",
        19: "vaD jIH Sov vetlh vam DichDaq tlhe' pa' Daq wIj toDtaHghach, vegh lIj supplication je the supply vo' the qa' vo' Jesus Christ,",
        20: "according Daq wIj earnest expectation je tul, vetlh jIH DichDaq Daq ghobe' way taH disappointed, 'ach tlhej Hoch boldness, as always, DaH je Christ DichDaq taH magnified Daq wIj porgh, whether Sum yIn, joq Sum Hegh.",
        21: 'vaD Daq jIH Daq yIn ghaH Christ, je Daq Hegh ghaH gain.',
        22: "'ach chugh jIH yIn Daq Daq the ghab, vam DichDaq qem baQ vo' wIj vum; yet jIH yImev Sov nuq jIH DichDaq choose.",
        23: "'ach jIH 'oH Daq a dilemma joj the cha', ghajtaH the neH Daq mej je taH tlhej Christ, nuq ghaH Hop better.",
        24: 'Yet, Daq remain Daq the ghab ghaH latlh needful vaD lIj chIch.',
        25: "ghajtaH vam confidence, jIH Sov vetlh jIH DichDaq remain, HIja', je remain tlhej SoH Hoch, vaD lIj progress je Quch Daq the HartaHghach,",
        26: 'vetlh lIj rejoicing may abound Daq Christ Jesus Daq jIH vegh wIj Daq tlhej SoH again.',
        27: "neH chaw' lIj Da vo' yIn taH worthy vo' the QaQ News vo' Christ, vetlh, whether jIH ghoS je legh SoH joq 'oH absent, jIH may Qoy vo' lIj state, vetlh SoH Qam firm Daq wa' qa', tlhej wa' qa' striving vaD the HartaHghach vo' the QaQ News;",
        28: "je Daq pagh frightened Sum the jaghpu', nuq ghaH vaD chaH a proof vo' QIH, 'ach Daq SoH vo' toDtaHghach, je vetlh vo' joH'a'.",
        29: "Because 'oH ghajtaH taH granted Daq SoH Daq behalf vo' Christ, ghobe' neH Daq Har Daq ghaH, 'ach je Daq suffer Daq Daj behalf,",
        30: "ghajtaH the rap conflict nuq SoH leghta' Daq jIH, je DaH Qoy ghaH Daq jIH.",
    },
    2: {
        1: "chugh pa' ghaH vaj vay' exhortation Daq Christ, chugh vay' consolation vo' muSHa', chugh vay' fellowship vo' the qa', chugh vay' tender mercies je compassion,",
        2: "chenmoH wIj Quch teblu'ta', Sum taH rur-minded, ghajtaH the rap muSHa', taH vo' wa' accord, vo' wa' yab;",
        3: "doing pagh vegh rivalry joq vegh conceit, 'ach Daq humility, each counting others better than himself;",
        4: "each vo' SoH ghobe' just leghtaH Daq Daj ghaj Dochmey, 'ach each vo' SoH je Daq the Dochmey vo' others.",
        5: "ghaj vam Daq lIj yab, nuq ghaHta' je Daq Christ Jesus,",
        6: "'Iv, existing Daq the form vo' joH'a', ta' taH' qel equality tlhej joH'a' a Doch Daq be grasped,",
        7: "'ach emptied himself, taking the form vo' a toy'wI', taH chenmoHta' Daq the likeness vo' loDpu'.",
        8: "je taH tu'ta' Daq human form, ghaH humbled himself, becoming loblu'taH Daq Hegh, HIja', the Hegh vo' the cross.",
        9: "vaj joH'a' je highly exalted ghaH, je nobta' Daq ghaH the pong nuq ghaH Dung Hoch pong;",
        10: "vetlh Daq the pong vo' Jesus Hoch knee should bow, vo' chaH Daq chal, chaH Daq tera', je chaH bIng the tera',",
        11: "je vetlh Hoch jat should confess vetlh Jesus Christ ghaH joH, Daq the batlh vo' joH'a' the vav.",
        12: "vaj vaj, wIj parmaqqay, 'ach as SoH ghaj always obeyed, ghobe' neH Daq wIj Daq, 'ach DaH 'ar latlh Daq wIj absence, vum pa' lIj ghaj toDtaHghach tlhej taHvIp je trembling.",
        13: "vaD 'oH ghaH joH'a' 'Iv vum Daq SoH both Daq DichDaq je Daq vum, vaD Daj QaQ pleasure.",
        14: "ta' Hoch Dochmey Hutlh murmurings je disputes,",
        15: "vetlh SoH may moj blameless je harmless, puqpu' vo' joH'a' Hutlh blemish Daq the midst vo' a crooked je perverse generation, among 'Iv SoH 'oH leghpu' as lights Daq the qo',",
        16: "holding Dung the mu' vo' yIn; vetlh jIH may ghaj something Daq boast Daq the jaj vo' Christ, vetlh jIH ta'be' run Daq lI'be' ghobe' labor Daq lI'be'.",
        17: "HIja', je chugh jIH 'oH poured pa' Daq the sacrifice je toy'taHghach vo' lIj HartaHghach, jIH yItIv, je yItIv tlhej SoH Hoch.",
        18: 'Daq the rap way, SoH je yItIv, je yItIv tlhej jIH.',
        19: "'ach jIH tul Daq the joH Jesus Daq ngeH Timothy Daq SoH soon, vetlh jIH je may taH cheered Dung ghorgh jIH Sov chay' SoH 'oH doing.",
        20: "vaD jIH ghaj ghobe' wa' else rur-minded, 'Iv DichDaq truly care about SoH.",
        21: "vaD chaH Hoch nej chaj ghaj, ghobe' the Dochmey vo' Jesus Christ.",
        22: "'ach SoH Sov the proof vo' ghaH, vetlh, as a puq serves a vav, vaj ghaH served tlhej jIH Daq furtherance vo' the QaQ News.",
        23: "vaj jIH tul Daq ngeH ghaH Daq once, as soon as jIH legh chay' 'oH DichDaq jaH tlhej jIH.",
        24: "'ach jIH voq Daq the joH vetlh jIH jIH'egh je DichDaq ghoS shortly.",
        25: "'ach jIH counted 'oH necessary Daq ngeH Daq SoH Epaphroditus, wIj loDnI', fellow worker, fellow mang, je lIj apostle je toy'wI' vo' wIj need;",
        26: "since ghaH longed vaD SoH Hoch, je ghaHta' very troubled, because SoH ghajta' Qoyta' vetlh ghaH ghaHta' rop.",
        27: "vaD indeed ghaH ghaHta' rop, nearly Daq Hegh, 'ach joH'a' ghajta' pung Daq ghaH; je ghobe' Daq ghaH neH, 'ach Daq jIH je, vetlh jIH might ghobe' ghaj QoSqu' Daq QoSqu'.",
        28: "jIH ghaj ngeHta' ghaH vaj the latlh diligently, vetlh, ghorgh SoH legh ghaH again, SoH may yItIv, je vetlh jIH may taH the less QoSqu'.",
        29: "Hev ghaH vaj Daq the joH tlhej Hoch Quch, je 'uch such Daq quv,",
        30: "because vaD the vum vo' Christ ghaH ghoSta' Sum Daq Hegh, risking Daj yIn Daq supply vetlh nuq ghaHta' lacking Daq lIj toy'taHghach toward jIH.",
    },
    3: {
        1: "Finally, wIj loDnI'pu', yItIv Daq the joH. Daq write the rap Dochmey Daq SoH, Daq jIH indeed ghaH ghobe' tiresome, 'ach vaD SoH 'oH ghaH safe.",
        2: "Beware vo' the dogs, beware vo' the mIghtaHghach workers, beware vo' the false circumcision.",
        3: "vaD maH 'oH the circumcision, 'Iv lalDan toy' joH'a' Daq the qa', je yItIv Daq Christ Jesus, je ghaj ghobe' confidence Daq the ghab;",
        4: "'a' jIH jIH'egh might ghaj confidence 'ach Daq the ghab. chugh vay' latlh loD thinks vetlh ghaH ghajtaH confidence Daq the ghab, jIH yet latlh:",
        5: "circumcised the eighth jaj, vo' the stock vo' Israel, vo' the tuq vo' Benjamin, a Hebrew vo' Hebrews; concerning the chut, a Pharisee;",
        6: "concerning zeal, persecuting the yej; concerning the QaQtaHghach nuq ghaH Daq the chut, tu'ta' blameless.",
        7: 'However, nuq Dochmey were gain Daq jIH, Dochvammey ghaj jIH counted loss vaD Christ.',
        8: "HIja' HochHom certainly, je jIH count Hoch Dochmey Daq taH loss vaD the excellency vo' the Sov vo' Christ Jesus, wIj joH, vaD 'Iv jIH suffered the loss vo' Hoch Dochmey, je count chaH pagh 'ach Qo', vetlh jIH may gain Christ",
        9: "je taH tu'ta' Daq ghaH, ghobe' ghajtaH a QaQtaHghach vo' wIj ghaj, vetlh nuq ghaH vo' the chut, 'ach vetlh nuq ghaH vegh HartaHghach Daq Christ, the QaQtaHghach nuq ghaH vo' joH'a' Sum HartaHghach;",
        10: "vetlh jIH may Sov ghaH, je the HoS vo' Daj resurrection, je the fellowship vo' Daj sufferings, becoming conformed Daq Daj Hegh;",
        11: "chugh Sum vay' means jIH may attain Daq the resurrection vo' the Heghpu'.",
        12: "ghobe' vetlh jIH ghaj already obtained, joq 'oH already chenmoHta' perfect; 'ach jIH press Daq, chugh 'oH ghaH vaj vetlh jIH may tlhap 'uch vo' vetlh vaD nuq je jIH ghaHta' tlhappu' 'uch vo' Sum Christ Jesus.",
        13: "loDnI'pu', jIH yImev regard jIH'egh as yet ghajtaH tlhappu' 'uch, 'ach wa' Doch jIH ta'. Forgetting the Dochmey nuq 'oH behind, je stretching forward Daq the Dochmey nuq 'oH qaSpa',",
        14: "jIH press Daq toward the goal vaD the prize vo' the jen ja'taH vo' joH'a' Daq Christ Jesus.",
        15: "chaw' maH vaj, as law' as 'oH perfect, think vam way. chugh Daq vay' SoH think otherwise, joH'a' DichDaq je reveal vetlh Daq SoH.",
        16: "Nevertheless, Daq the extent vetlh maH ghaj already attained, chaw' maH yIt Sum the rap rule. chaw' maH taH vo' the rap yab.",
        17: "loDnI'pu', taH imitators tay' vo' jIH, je note chaH 'Iv yIt vam way, 'ach as SoH ghaj maH vaD an example.",
        18: "vaD law' yIt, vo' 'Iv jIH ja'ta' SoH often, je DaH ja' SoH 'ach weeping, as the jaghpu' vo' the cross vo' Christ,",
        19: "'Iv pItlh ghaH QIH, 'Iv joH'a' ghaH the chor, je 'Iv batlh ghaH Daq chaj tuH, 'Iv think about earthly Dochmey.",
        20: "vaD maj citizenship ghaH Daq chal, vo' nuqDaq maH je loS vaD a toDwI', the joH Jesus Christ;",
        21: "'Iv DichDaq change the porgh vo' maj humiliation Daq taH conformed Daq the porgh vo' Daj batlh, according Daq the working Sum nuq ghaH ghaH laH 'ach Daq subject Hoch Dochmey Daq himself.",
    },
    4: {
        1: "vaj, wIj loDnI'pu', parmaqqay je longed vaD, wIj Quch je crown, vaj Qam firm Daq the joH, wIj parmaqqay.",
        2: 'jIH exhort Euodia, je jIH exhort Syntyche, Daq think the rap way Daq the joH.',
        3: "HIja', jIH beg SoH je, true yokefellow, QaH Dochvammey be'pu', vaD chaH labored tlhej jIH Daq the QaQ News, tlhej Clement je, je the leS vo' wIj fellow workers, 'Iv pongmey 'oH Daq the paq vo' yIn.",
        4: 'yItIv Daq the joH always! Again jIH DichDaq jatlh, yItIv!',
        5: "chaw' lIj gentleness taH Sovta' Daq Hoch loDpu'. The joH ghaH Daq ghop.",
        6: "Daq pagh taH anxious, 'ach Daq everything, Sum tlhobtaHghach je petition tlhej tlho'taHghach, chaw' lIj requests taH chenmoHta' Sovta' Daq joH'a'.",
        7: "je the roj vo' joH'a', nuq surpasses Hoch yajtaHghach, DichDaq guard lIj tIQDu' je lIj thoughts Daq Christ Jesus.",
        8: "Finally, loDnI'pu', whatever Dochmey 'oH true, whatever Dochmey 'oH honorable, whatever Dochmey 'oH just, whatever Dochmey 'oH pure, whatever Dochmey 'oH lovely, whatever Dochmey 'oH vo' QaQ report; chugh pa' ghaH vay' virtue, je chugh pa' ghaH vay' naD, think about Dochvammey Dochmey.",
        9: "The Dochmey nuq SoH learned, Hevta', Qoyta', je leghta' Daq jIH: ta' Dochvammey Dochmey, je the joH'a' vo' roj DichDaq taH tlhej SoH.",
        10: "'ach jIH yItIv Daq the joH greatly, vetlh DaH Daq length SoH ghaj revived lIj thought vaD jIH; Daq nuq SoH ta'ta' indeed tlhap thought, 'ach SoH lacked opportunity.",
        11: "ghobe' vetlh jIH jatlh Daq respect Daq Hutlh, vaD jIH ghaj learned Daq whatever state jIH 'oH, Daq taH content Daq 'oH.",
        12: "jIH Sov chay' Daq taH humbled, je jIH Sov je chay' Daq abound. Daq everything je Daq Hoch Dochmey jIH ghaj learned the pegh both Daq taH tebta' je Daq taH hungry, both Daq abound je Daq taH Daq need.",
        13: "jIH laH ta' Hoch Dochmey vegh Christ, 'Iv strengthens jIH.",
        14: "However SoH ta'ta' QaQ vetlh SoH shared Daq wIj affliction.",
        15: "SoH tlhIH'egh je Sov, SoH Philippians, vetlh Daq the tagh vo' the QaQ News, ghorgh jIH departed vo' Macedonia, ghobe' yej shared tlhej jIH Daq the matter vo' giving je receiving 'ach SoH neH.",
        16: "vaD 'ach Daq Thessalonica SoH ngeHta' once je again Daq wIj need.",
        17: "ghobe' vetlh jIH nej vaD the gift, 'ach jIH nej vaD the baQ vetlh increases Daq lIj account.",
        18: "'ach jIH ghaj Hoch Dochmey, je abound. jIH 'oH tebta', ghajtaH Hevta' vo' Epaphroditus the Dochmey vetlh ghoSta' vo' SoH, a sweet-smelling fragrance, an acceptable je QaQ-pleasing sacrifice Daq joH'a'.",
        19: "wIj joH'a' DichDaq supply Hoch need vo' yours according Daq Daj riches Daq batlh Daq Christ Jesus.",
        20: "DaH Daq maj joH'a' je vav taH the batlh reH je ever! Amen.",
        21: "Greet Hoch le' ghot Daq Christ Jesus. The loDnI'pu' 'Iv 'oH tlhej jIH greet SoH.",
        22: "Hoch the le' ghotpu' greet SoH, especially chaH 'Iv 'oH vo' Caesar's household.",
        23: "The grace vo' the joH Jesus Christ taH tlhej SoH Hoch. Amen.",
    },
}
