NAME = 'GerOffBiSt: Offene Bibel - Studienfassung'
BOOK = 'Daniel'

CHAPTERS = {
    2: {
        4: 'Da (und) sprachen die Chaldäer (Wahrsager, Sterndeuter) zum König [auf] Aramäisch: „Ewig lebe der König! Erzähle (sage) deinen Sklaven (Dienern, Knechten) den Traum, dann (und) werden wir [seine] Bedeutung (Deutung) erzählen (erklären).“',
        5: 'Der König antwortete {und sagte zu} den Chaldäern (Wahrsagern, Sterndeutern): „Mein Wort ist unwiderruflich: Wenn ihr mir den Traum und seine Bedeutung (Deutung) nicht mitteilen könnt (mitteilt), werdet ihr zu Körperteilen (Gliedern) gemacht und eure Häuser in Müllhaufen (Latrinen; Trümmerhaufen) verwandelt werden!',
        6: 'Aber (und) wenn ihr den Traum und seine Bedeutung (Deutung) erklären könnt, werdet ihr von mir Geschenke, {und} Belohnungen (Geschenke, Kostbarkeiten) und große Ehre empfangen. Darum (nur wenn) erklärt mir den Traum und seine Bedeutung (Deutung)!“',
        7: 'Sie antworteten noch einmal (ein zweites Mal) {und sagten}: „Der König möge seinen Sklaven (Dienern, Knechten) den Traum sagen, danach (und) werden wir die Bedeutung (Deutung) erklären!“',
        8: 'Der König antwortete {und sagte}: „ [Jetzt] weiß ich ganz sicher, dass ihr [versucht] Zeit [zu] kaufen, weil [ihr] seht (gesehen habt), dass mein Wort unwiderruflich ist:',
        9: '{dass} Wenn ihr mir den Traum nicht mitteilt, gibt es [nur] ein Urteil (Beschluss, Strafe, Gesetz) [über] euch: {und} Ihr habt euch abgesprochen (verschworen, entschlossen), falsche und verlogene (verdorbene) Worte (Sache) vor mir zu sprechen (mir zu sagen), bis die Zeit sich ändert (ändern wird). Deshalb (Wenn) sagt mir den Traum, dann (und) werde ich wissen, dass ihr mir seine Bedeutung (Deutung) erklären könnt!“',
        10: 'Die Chaldäer (Wahrsager, Sterndeuter) antworteten {vor} dem König {und sagten}: „Es gibt keinen Menschen auf dem trockenen Land (der Erde), der erklären könnte, was der König verlangt (sagt)! Entsprechend (Deshalb) hat noch kein großer und mächtiger (herrschender) König (großer König oder (und) Herrscher) eine solche Tat von einem Wahrsager, Beschwörer oder Chaldäer (Wahrsager, Sterndeuter) verlangt (gefordert, erbeten).',
        11: 'Was der König fordert, [ist uns] zu schwierig (schwierig; unmöglich, zu hoch), und es gibt niemand anderen, der {vor} dem König [das Geforderte] mitteilen (erklären) könnte außer Göttern (Gott), deren Wohnung nicht beim Fleisch ist!“',
        12: 'Darüber wurde (war) der König wütend und sehr zornig und gebot, alle Weisen Babels umzubringen.',
        13: 'Bald (und) erging das [entsprechende] Gesetz und die Weisen sollten hingerichtet (getötet) werden. Auch (und) Daniel und seine Freunde (Gefährten) suchte man, um [sie] hinzurichten (zu töten).',
        14: 'Da übermittelte Daniel einen Rat und Vorschlag (einen verständigen Rat) an Arioch, den Obersten der Leibgarde (Scharfrichter) des Königs, der unterwegs (aufgebrochen, sich aufgemacht, losgegangen) war, um die Weisen Babels hinzurichten (zu töten).',
        15: 'Er fragte (antwortete) {und sagte zu} Arioch: „Du Mächtiger (Bevollmächtigter; mächtigster [Mann]) des Königs (Arioch, den Bevollmächtigten des Königs), warum [dieses] strenge (übereilte, dringliche) Gesetz von seiten des Königs (warum ist das Gesetz … [so] streng)?“Da klärte (informierte über, berichtete von, weihte ein in) Arioch Daniel [über] die Angelegenheit (Sache) auf,',
        16: 'und Daniel trat ein und erbat vom König, dass er ihm eine Audienz (Frist) gewähre, dann (und) werde [er] dem König die Bedeutung (Deutung) erklären.',
        17: 'Daraufhin (sofort) begab sich Daniel zu seinem Haus (nach Hause) und klärte (informierte über, berichtete von, weihte ein in) seine Freunde (Gefährten) Hananja, Mischaël und Asarja [über] die Angelegenheit (Sache) auf.',
        18: '{und} Er [bat sie], angesichts dieser unlösbaren Aufgabe (dieses Geheimnisses) vor dem Gott des Himmels um Erbarmen zu bitten, damit (sodass) man Daniel und seine Freunde (Gefährten) nicht mit den übrigen Weisen Babels umbrächte.',
        19: 'Da wurde (dem) Daniel in einer nächtlichen Erscheinung das Geheimnis offenbart. Da lobte Daniel den Gott des Himmels.',
        20: 'Daniel hob an und sagte: Der Name Gottes soll gelobt sein von Ewigkeit zu Ewigkeit, denn die Weisheit und die Stärke – sein sind sie.',
        21: 'Denn er ändert die Jahre und die Fristen, er setzt Könige ab und setzt Könige ein, er gibt den Weisen die Weisheit und den Verstand denen, die Verstand kennen.',
        22: 'Er offenbart die Tiefen und die verborgenen Dinge; er weiß, was im Dunkeln (geschieht), und das Licht wohnt bei ihm.',
        23: 'Dich, Gott meiner Väter, lobe und preise ich, denn die Weisheit und die Stärke hast du mir gegeben, und nun hast du mich wissen lassen, was wir von dir erbeten haben; denn du hast uns die Sache des Königs wissen lassen.',
        24: 'Deshalb ging Daniel hinein zu Arjoch, den der König beauftragt hatte, die Weisen Babels umzubringen; er ging hinein und so sprach er zu ihm: Bringe die Weisen Babels nicht um! Führe mich hinein vor den König und ich werde dem König die Deutung kundtun!',
        25: 'Daraufhin führte Arjoch Daniel eilends für den König und sprach zu ihm so: Ich habe einen Mann gefunden von den Söhnen der Gefangenschaft Judas, der dem König die Deutung mitteilen wird/kann/will.',
        26: 'Der König hob an und sagte zu Daniel, dessen Name Beltschazar ist: Du vermagst, mich den Traum wissen zu lassen, den ich gesehen habe, und seine Deutung?',
        27: 'Daniel antwortete (vor) dem König und sagte: Das Geheimnis, das der König verlangt, können Weise, Wahrsager, Magier, Zeichendeuter dem König nicht kundtun.',
        28: 'Aber es gibt einen Gott im Himmel, der Geheimnisse offenbart, und er ließ den König Nebukadnezar wissen, was am Ende der Tage geschehen wird. Dein Traum und die Erscheinungen deines Kopfes auf deinem Lager waren dies:',
        29: 'Dir, König, stiegen auf deinem Lager deine Gedanken auf, was nach diesem geschehen werde, und der, der die Geheimnisse offenbart, hat dich wissen lassen, was geschehen wird.',
        30: 'Aber mir wurde dieses Geheimnis nicht offenbart durch die Weisheit, die in mir vor (mehr als in) allen Lebewesen ist, sondern damit sie/man den König die Deutung wissen lasse (n) und du die Gedanken deines Herzens verstehst.',
        31: 'Du, König, hast gesehen, und siehe, ein großes Bild. Jenes Bild war groß und sein Glanz war außerordentlich. Es stand vor dir und sein Aussehen war fürchterlich.',
        32: 'Das Bild (von diesem Bild gilt): sein Kopf war aus gutem/reinem Gold, seine Brust und seine Arme aus Silber, sein Bauch und seine Hüfte aus Bronze;',
        33: 'seine Schenkel (waren) aus Eisen, seine Füße teils aus Eisen und teils aus Ton.',
        34: 'Du hast gesehen, bis sich ein Stein nicht durch Hände löste und das Bild an seinen Füßen aus dem Eisen und dem Ton traf und sie zermalmte.',
        35: 'Dann wurden zugleich zermalmt das Eisen, der Ton, die Bronze, das Silber und das Gold und wurden wie Spreu von den Tennen des Sommers und der Wind verwehte sie und keine Spur von ihnen wurde (mehr) gefunden. Und der Stein, der das Bild traf, wurde zu einem großen Berg und erfüllte die ganze Erde.',
        36: 'Dies war der Traum. Auch seine Deutung werden/wollen wir vor dem König sagen.',
        37: 'Du, König, bist der König der Könige, dem der Gott des Himmels das Königtum, die Kraft und die Stärke und die Ehre gegeben hat,',
        38: 'und in allem (überall), wo die Söhne des Menschen wohnen, hat er das Tier (die Tiere) des Feldes und die Vögel des Himmels in deine Hand gegeben, und hat dich als Herrscher über sie alle eingesetzt. Du bist der Kopf aus Gold.',
        39: 'Und nach dir wird ein anderes Königreich aufstehen, geringer als du, und ein anderes drittes Königreich aus Bronze, das über die ganze Erde herrschen wird.',
        40: 'Und ein viertes Königreich wird hart sein wie Eisen, weil Eisen alles zermalmt und zerschmettert, und wie das Eisen, das zertrümmert, wird es diese alle zermalmen und zertrümmern.',
        41: 'Und dass du die Füße und die Zehen teils aus Töpferton und teils aus Eisen gesehen hast, (das) wird ein geteiltes Königreich sein. Und von der Härte des Eisens wird (etwas) in ihm sein, weil du das Eisen mit Ton aus Lehm gemischt gesehen hast.',
        42: 'Und die Zehen der Füße waren teils aus Eisen und teils aus Ton: Zum Teil wird das Königreich mächtig sein und zum Teil wird es zerbrechlich sein.',
        43: 'Dass du das Eisen mit Ton aus Lehm gemischt gesehen hast: Sie werden vermischt sein im Samen des Menschen und/aber sie werden nicht untereinander haften so wie das Eisen sich nicht vermischen lässt mit dem Ton.',
        44: 'Und in den Tagen dieser Könige wird der Gott des Himmels ein Königreich errichten, das in Ewigkeit nicht zugrunde gehen wird, und das Königreich wird nicht einem anderen Volk überlassen werden. Es wird alle jene Königreiche zermalmen und (ihnen) ein Ende machen. Und es (selbst) wird bestehen in Ewigkeit.',
        45: 'Weil du gesehen hast, dass sich von dem Berg nicht durch Hände ein Stein gelöst und das Eisen, die Bronze, den Ton, das Silber und das Gold zermalmt hat: Ein großer Gott hat den König wissen lassen, was danach geschehen wird; und der Traum ist sicher und seine Deutung zuverlässig.',
        46: 'Da fiel der König Nebukadnezar auf sein Angesicht und huldigte Daniel und befahl, ihm ein Opfer und ein Rauchopfer darzubringen.',
        47: 'Der König antwortete (dem) Daniel und sagte: Von Wahrheit (Wahrhaftig) ist euer Gott Gott von Göttern und Herr von Königen und einer, der Geheimnisse offenbart, denn du konntest dieses Geheimnis offenbaren.',
        48: 'Da verlieh der König (dem) Daniel einen hohen Rang und gab ihm viele große Geschenke und setzte ihn als Herrscher ein über die ganze Provinz Babel und zum obersten Statthalter über alle Weisen Babels.',
        49: 'Und Daniel bat den König (von dem König), und er (dass er…) beauftragte mit der Verwaltung der Provinz Babel Schadrach, Meschach und Abed-Nego. Und Daniel war (blieb) im Tor (am Hof) des Königs.',
    },
    3: {
        1: 'Nebukadnezar, der König, machte ein Bild aus Gold. Seine Höhe (war) sechzig Ellen. Seine Breite (war) sechs Ellen. Er errichtete es in der Ebene Dura, in der Provinz Babel.',
        2: 'Und Nebukadnezar, der König, sandte hin um die Satrapen, die Statthalter und die Verwalter, die Ratgeber, die Schatzmeister, die Richter, die Polizeiobersten und alle Befehlshaber der Provinzen zu versammeln, damit sie zur Einweihung des Bildes kämen, das der König Nebukadnezar errichtet hatte.',
        3: 'Da versammelten sich die Satrapen, die Statthalter und die Verwalter, die Ratgeber, die Schatzmeister, die Richter, die Polizeiobersten und alle Befehlshaber der Provinzen zur Einweihung des Bildes, das der König Nebukadnezar errichtet hatte, und sie standen vor dem Bild, das Nebukadnezar errichtet hatte.',
        4: 'Und der Herold rief mit Stärke (laut): Euch, den Völkern, den Nationen und den Sprachgruppen, befehlen sie (befiehlt man/wird befohlen):',
        5: 'Zu der Zeit, zu der ihr den Klang des Horns, der Pfeife, einer Zither, der Harfe, einer Laute, einer Sackpfeife und/oder jeder Art Instrument hören werdet, sollt ihr niederfallen und das Bild aus Gold anbeten, das der König Nebukadnezar errichtet hat.',
        6: 'Und wer nicht niederfallen und anbeten wird, der wird/soll in diesem Augenblick in den brennenden Feuerofen geworfen werden.',
        7: 'Deshalb, zu der Zeit, als alle Völker den Klang des Horns, der Pfeife, einer Zither, der Harfe, einer Laute und/oder jeder Art Instrument hörten, fielen alle Völker, Nationen und Sprachgruppen nieder (und) beteten das Bild aus Gold an, das der König Nebukadnezar errichtet hatte.',
        8: 'Deshalb näherten sich zu der Zeit Männer, Sterndeuter, und sie verklagten die Juden.',
        9: 'Sie hoben an und sagten zu dem König Nebukadnezar: König, lebe ewig!',
        10: 'Du, König, hast Befehl gegeben, dass jeder Mensch, der den Klang des Horns, der Pfeife, einer Zither, der Harfe, einer Laute, einer Sackpfeife und/oder jeder Art Instrument hören wird, niederfallen und das Bild aus Gold anbeten soll.',
        11: 'Und wer nicht niederfallen und anbeten wird, der soll in den brennenden Feuerofen geworfen werden.',
        12: 'Es gibt jüdische Männer, die du beauftragt hast mit der Verwaltung der Provinz Babel, Schadrach, Meschach und Abed-Nego; diese Männer haben dir, König, keine Beachtung geschenkt; deinen Göttern dienen sie nicht und vor dem Bild aus Gold, das du errichtet hast, beten sie nicht an.',
        13: 'Da befahl Nebukadnezar in Zorn und Wut, Schadrach, Meschach und Abed-Nego herzubringen. Da wurden diese Männer hergebracht vor den König.',
        14: 'Nebukadnezar hob an und sagte zu ihnen: Ist es wahr, Schadrach, Meschach und Abed-Nego, dass ihr meinen Göttern nicht dient und vor dem Bild aus Gold, das ich errichtet habe, nicht anbetet?',
        15: 'Nun, wenn ihr bereit seid zu der Zeit, zu der ihr den Klang des Horns, der Pfeife, einer Zither, der Harfe, einer Laute und einer Sackpfeife und/oder jeder Art Instrument hören werdet, niederzufallen und das Bild anzubeten, das ich gemacht habe… Aber wenn ihr nicht anbeten werdet, werdet ihr in dem Augenblick in den brennenden Feuerofen geworfen werden. Und wer ist ein Gott, der euch aus meiner Hand retten wird?',
        16: 'Schadrach, Meschach und Abed-Nego antworteten und sagten zu dem König: Nebukadnezar, wir haben es nicht nötig, dir auf dieses Wort zu antworten.',
        17: 'Wenn unser Gott, dem wir dienen, uns retten kann, wird er uns aus dem brennenden Feuerofen und aus deiner Hand, König, retten.',
        18: 'Und wenn nicht, dann sollst du wissen, König, dass wir nicht deinen Göttern dienen und nicht vor dem Bild aus Gold, das du errichtet hast, anbeten werden.',
        19: 'Da wurde Nebukadnezar erfüllt mit Zorn und der Ausdruck seines Gesichts veränderte sich wegen/gegenüber Schadrach, Meschach und Abed-Nego. Er hob an und befahl, den Ofen zu heizen auf ein Siebenfaches von dem, was gewöhnlich war ihn zu heizen.',
        20: 'Und Männern, starken Männern/Kriegern in seinem Heer, befahl er, Schadrach, Meschach und Abed-Nego zu binden, um (sie) in den brennenden Feuerofen zu werfen.',
        21: 'Da wurden diese Männer mit ihren Mänteln, ihren Hosen und ihren Mützen und ihren (sonstigen) Kleidern gebunden und in den brennenden Feuerofen geworfen.',
        22: 'Deshalb, weil die Sache des Königs streng und der Ofen außerordentlich geheizt war, tötete jene Männer, die Schadrach, Meschach und Abed-Nego hinaufbrachten, die Flamme des Feuers.',
        23: 'Und jene drei Männer, Schadrach, Meschach und Abed-Nego, fielen gebunden in den brennenden Feuerofen.',
        24: 'Da erschrak der König Nebukadnezar und stand in Eile auf; er hob an und sagte zu seinen Räten: Haben wir nicht drei Männer gebunden in das Feuer geworfen? Sie antworteten und sagten zu dem König: Sicher, König!',
        25: 'Er antwortete und sagte: Siehe, ich sehe vier Männer frei im Feuer umhergehen und keine Verletzung ist an ihnen und das Aussehen des Vierten ist ähnlich einem Sohn der Götter.',
        26: 'Da trat Nebukadnezar hinzu an die Öffnung des brennenden Feuerofens. Er hob an und sagte: Schadrach, Meschach und Abed-Nego, Diener des höchsten Gottes, geht heraus und kommt! Da gingen Schadrach, Meschach und Abed-Nego heraus aus dem Feuer.',
        27: 'Und es versammelten sich die Satrapen, die Statthalter und die Verwalter und die Räte des Königs; sie sahen jene Männer an, über deren Leib das Feuer keine Macht hatte, und das Haar ihres Kopfes war nicht versengt worden und ihre Mäntel waren unverändert und an sie war kein Geruch von Feuer gekommen.',
        28: 'Und Nebukadnezar hob an und sagte: Gepriesen sei der Gott Schadrachs, Meschachs und Abed-Negos, der seinen Boten geschickt und seine Knechte gerettet hat, die sich auf ihn verlassen und das Wort des Königs übertreten haben und ihre Leiber gegeben haben, dass sie nicht irgendeinem (=keinem) Gott dienten und ihn anbeteten außer ihren Gott.',
        29: 'Und von mir ist ein Befehl ergangen an jedes Volk, jede Nation und Sprachengruppe, dass, wer etwas Verächtliches sagen wird über den Gott Schadrachs, Meschachs und Abed-Negos, in Stücke gemacht werden soll und sein Haus soll einem Trümmerhaufen gleichgemacht werden, weil es keinen anderen Gott gibt, der retten kann wie dieser.',
        30: 'Daraufhin ließ der König es Schadrach, Meschach und Abed-Nego gut ergehen in der Provinz Babel (= der König beförderte…). Der König Nebukadnezar an alle Völker und Nationen und Sprachengruppen, die auf der ganzen Erde wohnen: Euer Friede soll groß werden! Die Zeichen und Wunder, die der höchste Gott an mir getan hat, gefiel/gefällt es mir kundzutun. Groß wie was (=wie groß) sind seine Zeichen und mächtig wie was (=wie mächtig) seine Wunder!? Sein Königreich ist ein ewiges Königreich und seine Herrschaft (ist/bleibt) von Generation zu Generation.',
    },
    4: {
        1: 'Ich, Nebukadnezar, war ruhig in meinem Haus und glücklich in meinem Palast.',
        2: 'Ich sah einen Traum und er wird mich erschrecken (erschreckte mich) und Gedanken auf meinem Lager und die Erscheinungen meines Kopfes werden mich erschrecken (erschreckten mich).',
    },
    12: {
        1: 'Und in dieser Zeit wird Michael stehen, der große Führer, der einsteht über die Söhne deines Volkes. Und es wurde eine Zeit der Not, die [noch] nie geschah, vom Sein des Volkes bis zu dieser Zeit. Aber zu jener Zeit wird dein Volk gerettet werden, alle die gefunden werden, geschrieben in dem Buch.',
        2: 'Und viele im Staub der Erde Schlafende werden aufwachen, diese zum ewigen Leben und diese zu ewiger Schmach, zu Abscheu.',
        3: 'Und die Weisen werden scheinen wie der Glanz der festen Himmelswölbung und die vielen Gerechten wie die Sterne für immer und ewig (für Ewigkeit und immer).',
        4: 'Und du, Daniel, halte die Worte geheim und versiegle das Buch bis zur Zeit des Endes. Viele werden nachforschen (umhergehen) und das Wissen wird groß sein.',
        5: 'Und ich, Daniel, sah zwei andere, die standen. Der eine hier am Ufer des Flusses, und der andere hier am Ufer des Flusses.',
        6: 'Und er sagte zu dem Mann, bekleidet in {den} Leinen, der oberhalb von den Wassern des Stromes war: Bis wann ist das Ende der Wunder?',
        7: 'Und ich hörte den Mann, bekleidet in {den} Leinen, der oberhalb von den Wassern des Stromes war. Und es erhob sich seine rechte Hand und seine linke zu den Himmeln und schwor auf das ewige Leben, dass es eine verabredete Zeit und verabredete Zeiten und eine halbe sein soll. Und wenn die Zerstreuung [der Hand] des heiligen Volkes beendet ist, wird dies alles vollendet werden.',
        8: 'Und ich hörte, und ich verstand nicht. Und ich sagte: Herr, was wird der Ausgang von diesem sein?',
        9: 'Und er sagte: Geh, Daniel, denn die Worte sind verschlossen und versiegelt bis zum Ende der Zeit.',
        10: 'Und viele werden sich reinigen und werden gereinigt und werden geläutert. Und die Gottlosen werden freveln und alle Gottlosen werden nicht verstehen und die Verständnisvollen werden verstehen.',
        11: 'Und von der Zeit, [seit] das tägliche Opfer abgeschafft und die Abscheu der Verwüstung aufgestellt wurde, sind es eintausendzweihundertneunzig Tage.',
        12: 'Wohl dem, der wartet und gelangt zu den tausenddreihundertfünfunddreißig Tagen!',
        13: 'Und du, geh zum Ende und ruhe und stehe auf, zu deinem Los am Ende der Tage.',
    },
}
