NAME = 'GerOffBiSt: Offene Bibel - Studienfassung'
BOOK = 'Jeremiah'

CHAPTERS = {
    1: {
        1: 'Worte Jeremias, Sohn des Hilkija, von den Priestern in Anatot im Land Benjamin.',
        2: 'An (zu) ihn erging (geschah) das „Wort JHWH s“in den Tagen Joschijas, Sohn Amons, König von Juda, im 13. Jahr seiner Regentschaft.',
        3: 'Und es geschah [weiter] in den Tagen Jojakims, Sohn Joschijas, König von Juda, bis zum Ende des 11. Jahres [der Regentschaft] Zidkijas, Sohn Joschijas, König von Juda; bis in die Verbannung gebracht wurde Jerusalem im 5. Monat.',
        4: 'Und [es] erging (geschah) das „Wort JHWH s“an (zu) mich {folgendermaßen}:',
        5: 'Bevor ich dich formte im Bauch [der Mutter], kannte ich dich, und bevor du herauskamst aus dem Schoß, habe ich dich geweiht; Prophet für die Völker ließ ich dich werden.',
        6: 'Aber ich sagte: Ach, Herr JHWH! Sieh, nicht habe ich gelernt zu reden. Denn ein Jugendlicher [bin] ich.',
        7: "Aber sprach JHWH zu mir: Sprich nicht: 'Ein Jugendlicher [bin] ich', denn zu allen, zu denen ich dich schicken werde, wirst du gehen und alles, was ich dir befehlen werde, wirst du reden.",
        8: 'Fürchte dich nicht vor ihnen. Denn bei dir [bin] ich, [um] dich zu retten. Spruch JHWH s',
        9: 'Und JHWH streckte seine Hand aus und berührte meinen Mund. Und sprach JHWH zu mir: „Sieh, ich habe gelegt mein Wort in deinen Mund.',
        10: 'Werde gewahr: Ich habe dir anvertraut an diesem Tag Völker und Königreiche: auszureißen und abzubrechen und auszurotten und einzureißen und zu bauen und zu pflanzen.“',
        11: 'Und es erging (geschah) das „Wort JHWH s“an (zu) mich {folgendermaßen}: Was siehst du, Jeremia? Da (und) antwortete ich: Einen Zweig des Mandelbaums sehe ich.',
        12: 'Da (und) sprach JHWH zu mir: Du hast gut gesehen! Denn wachend [bin] ich über mein Wort, es zu tun.',
        13: 'Und es erging (geschah) das „Wort JHWH s“an (zu) mich ein zweites Mal {folgendermaßen}: Was siehst du? Da (und) antwortete ich: Einen Topf, angefacht, sehe ich, und seine Oberfläche [neigt sich?] nach Norden.',
        14: 'Da (und) sprach JHWH zu mir: Von Norden wird entfesselt das Unheil über alle Bewohner des Landes.',
        15: 'Denn sieh mich: ein Rufender bin ich alle Sippen, Königreiche des Nordens, Spruch JHWH s, und sie werden kommen und jeder seinen Thron in der Öffnung der Tore Jerusalems aufstellen und auf alle ihre Mauern ringsum und an alle Städte Judas.',
        16: 'Und ich werde sprechen meinen Rechtsentscheid über sie wegen all ihrer Bosheit, „von der gilt“: sie haben mich verlassen und räucherten auf anderen Göttern und beteten an die Werke ihrer Hände.',
        17: 'Und du gürte deine Hüften und steh auf und rede zu ihnen alles, „von dem gilt“: ich habe [es] dir geboten. Erschrick nicht vor ihnen, damit nicht ich dich erschrecke vor ihnen!',
        18: 'Und sieh, ich habe dich heute gemacht zur Festungsstadt und zum eisernen Pfeiler und zur ehernen Mauer für das ganze Land, für die Könige Judas, für seine Fürsten, für seine Priester und für das „Volk des Landes“.',
        19: 'Und sie werden kämpfen gegen dich und dich nicht übermögen. Denn mit dir [bin] ich, Spruch JHWH s, um dich zu retten.',
    },
    2: {
        1: 'Und es erging (geschah) „Wort JHWH s“(das Wort JHWH s) an mich (zu mir) {folgendermaßen}:',
        2: 'Geh und rufe in die Ohren Jerusalems {folgendermaßen}: So spricht JHWH: ich erinnere mich (gedenke) an dich, an die Liebe (Treue, Verbundenheit) deiner Jugendzeit, die Liebe deines Brautstandes, dein Gehen hinter mir [her] in der Wüste, im Land, wo nicht gesät [wird].',
        3: 'Heiliges (Heiligtum) [war] Israel für JHWH, Erstling seines Ertrages. Alle ihn Essenden (Fressenden) werden sich verschulden, Unheil wird über sie kommen. Spruch (spricht) JHWH s.',
        4: 'Hört „Wort JHWH s“(das Wort JHWH s), Haus Jakob und alle Sippen (Familien) des Hauses Israel.',
        5: 'So spricht JHWH: Was fanden eure Väter an mir [für] Unrecht, dass sie sich fernhielten von mir und gingen hinter den Nichtsen (Nichtigkeit, Hauch; Götzen) [her] und wurden [selbst] nichtig?',
        6: 'Und fragten (sprachen) nicht: Wo [ist] JHWH?, der uns heraufbrachte aus dem Land Ägypten, der uns führte in der Wüste, im Land der Steppe (Wüste) und des Abgrunds (Fanggrube), im Land der Trockenheit und des Todesschattens, im Land nicht durchzieht es jemand (ein Mensch) und nicht wohnt ein Mensch dort.',
        7: 'Und ich brachte euch ins Land des Fruchtgartens, um zu essen seine Früchte (Ertrag) und seine Güter (Bestes). (Und =) Aber ihr kamt und verunreinigtet (entweihtet) mein Land, und mein Erbe machtet ihr zu Abscheulichem.',
        8: 'Die Priester (sagten =) fragten nicht: Wo [ist] JHWH? (Und =) Als Handhabende (Gebrauchende) die Torah (Gesetz) verstehen (kennen) sie mich nicht, und die Hirten sind von mir abgefallen. Und die Propheten prophezeien dem Baal und hinter Nichtsnutzen gehen sie (laufen sie her).',
        9: 'Darum: Weiter will (werde) ich rechten (einen Rechtsstreit führen) mit euch, Spruch (spricht) JHWH s, und mit den Kindern eurer Kinder will (werde) ich rechten (einen Rechtsstreit führen).',
        10: 'Denn geht hinüber zu den Inseln der Kittäer (Zyprioten) und seht, und nach Kedar und gebt (sehr =) genau acht und seht, siehe!, geschah [je] Solches?',
        11: 'Hat [je] ein Volk Götter (Gott) geändert (vertauscht)? Dabei (und) [sind] sie keine Götter (Gott)! (Und =) Aber mein Volk vertauscht seine Herrlichkeit (Ansehen, Ehre, Pracht) mit (nicht nützen =) Nichtsnutzen.',
        12: 'Entsetze dich Himmel darüber! {Und} Empfinde Schauder, trockne (sehr =) völlig aus! Spruch (spricht) JHWH s.',
        13: 'Denn zwei (zweifach) Übel (Böses) tut mein Volk: Mich verlassen sie, [die] Quelle lebendigen Wassers, um sich [eigene] Brunnen auszuhauen - Brunnen, die rissig werden, so dass sie das Wasser nicht halten können.',
        14: 'Ist Israel ein Knecht (Sklave)? Oder [ist] er ein (im Haus =) unfrei (?) Geborener? Warum wurde er [zum] Plündergut?',
        15: 'Gegen ihn brüllen junge Löwen, erheben ihre Stimmen und machten sein Land zu [etwas] Schauerlichem (Entsetzlichem); seine Städte wurden verbrannt, [sind] ohne Bewohner.',
        16: 'Auch (die Söhne Nophs =) die Bewohner Nophs und Tachpanches werden dir den Scheitel [kahl] (weiden=) fressen.',
        17: 'Hast du dies nicht dir selbst (getan =) zu verdanken, als du verließest JHWH, deinen Gott, zu der Zeit, als er dich führte auf dem Weg?',
        18: 'Und nun! Was [willst] du mit dem Weg [nach] Ägypten? [Willst du] (Fluss-wasser =) Nilwasser trinken? Und was [willst] du mit dem Weg [nach] Assyrien? [Willst du] (Strom=) Euphratwasser trinken?',
        19: 'Ich züchtige dich [wegen] deiner Bosheit und [wegen] deiner Abtrünnigkeit weise ich dich zurecht. (Und) du sollst spüren und sehen, dass es schlecht (schädlich, unglückbringend) und bitter [ist], dass du JHWH, deinen Gott, verlassen hast und (mein Schrecken =) Ehrfurcht vor mir nicht bei dir ist, Spruch des Herrn JHWH der Heerscharen (Zebaot).',
        20: 'Denn (von Ewigkeiten her =) schon immer habe ich dein Joch zerbrochen und deine Fesseln zerrissen, aber du sprichst: Ich will nicht dienen! Sondern auf jedem hohen Hügel und unter jedem grünen Baum legst du dich hin und treibst Hurerei.',
        21: 'Ich aber pflanzte dich [als] edle Traube, [als] völlig zuverlässige Pflanzung. Aber wie hast du dich mir [gegenüber] verändert? [Zu] wilden (aus der Art geschlagenen) Weinranken eines fremden Weinstocks.',
        22: 'Denn [selbst] wenn du dich reinigst (abwäscht) mit Natron und dir viel Laugensalz verschaffst, Deine Vergehen (Sünden) sind ein Schmutzfleck vor mir, Ausspruch des Herrn JHWH s.',
        23: 'Wie sprichst du: „Ich habe mich nicht verunreinigt, hinter den Baalen bin ich nicht [her] gelaufen“? Sieh deinen Weg im Tal [an]! Erkenne, was du getan hast! Eine schnelle junge Kamelstute läuft hin und her [auf] ihrem Weg',
        24: 'Ein [e] Wildesel [in], gewöhnt [an] die Wüste, im Verlangen ihrer Seele schnappt sie nach Luft. Ihre Brunst: wer drängt sie zurück (besänftigt sie)? Alle, die sie suchen werden nicht müde; in ihrem Monat werden sie sie finden.',
        25: 'Halte deinen Fuß ab von Barfüßigkeit und deine Kehle vom Durst! Aber du sprachst: Es ist vergeblich, nein! Denn ich liebe die Fremden und (hinter ihnen will ich hergehen =) ihnen will ich nachlaufen.',
        26: 'Wie Schande (Scham) eines Diebes, wenn er erwischt wird, so soll sich das Haus Israel schämen: Ihr, Könige, Beamte (Befehlshaber, Edle, Vornehme, Vorsteher, Oberste) und Priester und Propheten.',
        27: 'Sie sprechen zum Holz: Du bist mein Vater! und zum Stein: Du hast uns geboren! {Denn} sie wenden mir den Rücken zu und nicht das Gesicht aber zur Zeit des Unheils sprechen sie: Erhebe dich doch und rette uns!',
        28: 'Wo [sind] deine Götter, die du für dich (dir) gemacht hast? Sie sollen aufstehen, wenn sie dir helfen (dich retten) in der Zeit deines Unheils (Not, Unglück, Übel); denn wie die Zahl deiner Städte sind deine Götter, Juda.',
        29: 'Warum streitet (prozessiert) ihr mit mir? Ihr alle seid abgefallen von mir, Spruch JHWH s.',
        30: 'Vergeblich schlug ich die Söhne, die Warnung nahmen sie nicht an. Das Schwert fraß eure Propheten, wie ein verderbender (tötender) Löwe.',
        31: 'Du Generation (Geschlecht, Gemeinschaft), sieh das Wort JHWH s. War ich eine Wüste für Israel, oder ein Land der Finsternis? Warum hat mein Volk gesagt: Wir schweifen umher, wir kommen nicht mehr zu dir?',
        32: 'Vergisst eine Jungfrau ihren Schmuck, eine Braut ihren Gürtel? Aber mein Volk hat mich vergessen Tage ohne Zahl.',
        33: 'Wie gut führst du (deinen Gang =) es aus, eine Liebschaft zu suchen! Darum auch hast du an Böses (Unheil, Verbrechen) (deine Wege =) dein Leben gewöhnt (eingeübt):',
        34: 'Sogar an deinem Gewandsaum wird das Blut armer, schuldloser Leute gefunden, die du nicht beim Einbruch ertappt hast, denn all diesem waren sie entgegen (= haben sie widerstanden).',
        35: 'Aber du sagst: so rein bin ich, sein Zorn hat sich ja von mir abgewandt! - Siehe, ich rechte (führe einen Prozess) mit dir, weil du gesagt hast: ich habe nichts Böses getan (mich nicht verfehlt, nicht gesündigt).',
        36: 'Wie sehr (weit?) gehst du weg, zu ändern deinen Weg? Auch von Ägypten wirst du enttäuscht (oder: auch Ägyptens wirst du dich schämen), wie du enttäuscht wirst von Assur (oder: wie du dich Assurs schämen wirst).',
        37: 'Auch von dort wirst du ausziehen (herauskommen), {und} deine Hände auf deinem Kopf, denn abgelehnt hat JHWH dein Vertrauen (Sicherheit), und du wirst kein Glück haben mit ihnen.',
    },
    3: {
        1: '[Gott] spricht: Wenn ein Mann seine Frau fortschickt (entlässt), und sie geht weg von ihm und gehört einem anderen Mann, kann sie [dann] noch zu ihm zurückkehren? Würde [dann] nicht jenes Land völlig (gewiss) entweiht? Und du gingst fremd (buhltest, triebst Hurerei) mit vielen (zahlreichen) Fremden und willst zurückkehren zu mir? Spruch JHWH s.',
        2: 'Hebe deine Augen auf (Blicke hin) zu den Hügeln und sieh: wo hast du dich nicht schänden lassen (bist du nicht geschändet worden)? Auf den Wegen hast du für sie gesessen, wie ein Beduine (Araber) in der Wüste. Und du hast entweiht das Land (die Erde) durch deine Unzucht und durch dein Böses (= das Böse, das du getan hast).',
        3: '[Daher, deshalb] wurden versagt (entzogen) die Regen, und der Spätregen fiel nicht. [Aber] die Stirn einer Frau, die hurt hast du, die sich weigert, sich zu schämen.',
        4: 'Rufst du nicht von jetzt an zu mir „mein Vater!, Freund meiner Jugend (Jugendfreund) [bist] du!“?',
        5: '„Er wird [doch] nicht für ewig zürnen oder bewahren (aufbewahren, im Gedächtnis behalten, nachtragen) für immer?“Sieh du hast geredet und getan das Böse und du brachtest es fertig (vermochtest, konntest es).',
        6: '(Und) Da sprach JHWH zu mir in den Tagen des Königs Josia: hast du gesehen, was das abtrünnige Israel tut? Wie es auf auf jeden hohen Hügel steigt und unter jedem grünen Baum {dort} fremdgeht (Unzucht treibt, hurt)?',
        7: '[Da] sagte (dachte) ich: Nachdem es das alles getan hat, wird es zu mir zurückkehren. Aber es kehrte nicht [wieder] zurück. [Das] sah [seine] treulose Schwester Juda.',
        8: '[Da] sah es, dass, weil das abtrünnige Israel fremdging (die Ehe brach), ich es wegschickte und ihm den Scheidebrief gab. Aber das treulose Juda, seine Schwester, fürchtete sich nicht, sondern auch es ging hin und ging fremd (trieb Unzucht).',
        9: 'Und {es geschah} durch sein leichtfertiges Fremdgehen (Huren, Unzucht) wurde entweiht das Land (die Erde), und es ging fremd (hurte, trieb Unzucht) mit Stein und Holz.',
        10: 'Trotzdem kehrte nicht zu mir um seine treulose Schwester Juda mit ihrem ganzen Herzen, außer zum Schein, Spruch JHWH s.',
        11: 'Da sprach JHWH zu mir: als gerecht erweist sich die Seele des abtrünnigen Israels (das abtrünnige Israel) gegenüber dem (im Vergleich zum) treulosen Juda.',
        12: 'Geh und rufe diese Worte nach Norden {und sprich}: „Kehr zurück, abtrünniges Israel!“Spruch JHWH s. Ich lasse nicht fallen mein Antlitz gegen euch (Ich schaue euch nicht mehr ungnädig an), denn ich bin gnädig (gütig). Spruch JHWH s. Ich grolle nicht für immer (ewig).',
        13: 'Nur (jedoch) erkenne deine Schuld (Sünde, Vergehen), denn gegen JHWH, deinen Gott, hast du dich aufgelehnt, da du deine Wege zerstreut hast (herumgeschweift bist) mit den Fremden unter jedem grünen Baum und auf meine Stimme habt ihr nicht gehört. Spruch JHWH s.',
        14: 'Kehrt um, meine abtrünnigen Kinder! Spruch JHWH s. Denn ich habe euch zu Besitz genommen (bin euer Herr) und ich nehme (hole) euch, einen aus einer Stadt und zwei aus einer Familie (Sippe), und ich bringe euch [zum] Zion.',
        15: 'Und ich gebe euch Hirten nach meinem Herzen, und sie weiden euch [mit] Erkenntnis und Verstand.',
        16: 'Und es wird geschehen, wenn ihr zahlreich werdet und fruchtbar sein werdet im Lande (auf Erden) in jenen Tagen, Spruch JHWH s, werden sie nicht mehr sprechen von der Lade des Bundes JHWHs und sie wird [ihnen] nicht aufs Herz (in den Sinn) kommen, und sie werden ihrer nicht gedenken, und sie werden [sie] nicht vermissen (suchen) und keine [neue] mehr anfertigen (machen).',
        17: 'Zu dieser Zeit werden sie Jerusalem nennen „Thron JHWH s“, und alle Völker werden sich in ihr sammeln, beim Namen JHWH s in Jerusalem. Und sie werden nicht mehr wandeln (leben) nach der Verstocktheit (Starrsinn) ihres bösen Herzens.',
        18: 'In jenen Tagen wird das Haus Juda zum Haus Israel gehen, und sie werden zusammen (miteinander) kommen vom Land im Norden (Nordland) zum Land, das ich ihren Vätern zum Besitz (Erbe) gab.',
        19: 'Aber (Und) ich dachte (sprach): Wie will ich dich machen zu (herausstellen unter den) Kindern!, und dir kostbares (begehrenswertes) Land geben, herrlichsten Erbbesitz [unter den] Völkern. Darum meinte ich, „mein Vater“würdet ihr mich nennen, und von {hinter} mir würdet ihr euch nicht kehren.',
        20: 'Aber (fürwahr, gewiss) [wie] eine Frau treulos ist von ihrem Geliebten, so seid ihr treulos zu mir, Haus Israel. Spruch JHWH s.',
        21: 'Man hört Lärm (Geräusch, Stimme, Laut) auf kahlem Hügel: Weinen, Flehen der Kinder Israels. Denn verkehrt haben sie ihren Weg, vergessen JHWH, ihren Gott.',
        22: '„Kehrt um, meine abtrünnigen Kinder, ich will euch von eurer Abtrünnigkeit heilen. Da sind wir, wir kommen zu dir, denn du bist JHWH, unser Gott.“',
        23: 'Fürwahr (gewiss, aber), Lüge (Trug, Täuschung) [kommt] von den Hügeln, Getöse [von] den Bergen. Gewiss (fürwahr, aber) bei JHWH, unserem Gott, [ist] Rettung [für] Israel.',
        24: 'Aber (Und) „der Schändliche“fraß den Erwerb (Gewinn) unserer Väter, von unserer Jugend [an], ihr Kleinvieh und ihre Rinder, ihre Söhne und ihre Töchter.',
        25: 'Wir legen uns hin in unserer Schande, wir decken uns zu mit unserer Schmach, denn an JHWH, unserem Gott, haben wir uns versündigt, wir und unsere Väter, von unserer Jugend an bis zu diesem Tag, und nicht haben wir gehört auf die Stimme JHWHs, unseres Gottes.',
    },
    4: {
        1: 'Wenn du umkehrst, Israel, Spruch JHWH s, wirst du zu mir zurückkehren. Und wenn du beseitigen wirst deine Abscheulichkeit vor mir, dann wirst du nicht schwanken (ziellos sein). (vgl. Genesis 4,14)',
        2: 'Und schwörst du: [So wahr] JHWH lebt! in Treue, in Recht und in Gerechtigkeit, dann werden Völker sich in ihm glücklich preisen, und in ihm sich rühmen.',
        3: 'Denn so spricht JHWH zu den Leuten Judas und zu Jerusalem: macht euch Neubruch urbar und sät nicht auf Dornen.',
        4: 'Lasst euch beschneiden für JHWH und beseitigt die Vorhäute eures Herzens, Leute Judas und Einwohner Jerusalems, dass nicht komme wie Feuer mein Zorn, und er brennt, und keiner löscht wegen der Schlechtigkeit eurer Taten.',
    },
    7: {
        1: 'Das Wort, das an Jeremia von JHWH geschah:',
        2: 'Stell dich in das Tor des Hauses JHWH s und rufe dort dieses Wort und sage: Hört das Wort JHWHs, ganz Juda, die ihr kommt durch diese Tore, um JHWH anzubeten.',
        3: 'So spricht JHWH, Herr der Heerschaaren, Gott Israel: Macht gut eure Wege und eure Taten, dann werde ich euch wohnen lassen an diesem Ort.',
        4: 'Verlasst euch nicht auf Worte der Lüge, wenn sie sagen: Der Tempel JHWH s, der Tempel JHWHs, der Tempel JHWHs ist dieser.',
    },
    8: {
        4: 'Sprich zu ihnen, so hat JHWH gesprochen: Fällt man und steht nicht wieder auf? Oder wendet sich einer ab und kehrt nicht wieder zurück?',
        5: 'Warum hat sich dieses Volk Jerusalems abgewendet in beharrlicher Abkehr? Sie halten fest an der Täuschung (Trug) und weigern sich, umzukehren.',
        6: 'Ich horche hin und höre: Sie sprechen nicht recht, nicht einer bereut seine Bosheit und sagt: „Was habe ich getan!“Alle rennen noch weiter fort, (sie kehren sich ab in ihrem Rennen) wie ein Pferd (Hengst) galoppiert (strömt) in die Schlacht.',
        7: 'Auch der Storch (Kranich) am Himmel kennt seine festgesetzten Zeiten (kennt die Zeit der Rückkehr), Taube, Schwalbe und Kranich hören auf die Zeit ihres Kommens aber mein Volk kennt nicht die Rechtsordnung (Recht,Rechtsbestimmung) JHWH s.',
        9: '... Siehe, das Wort JHWH s haben sie verschmäht (verworfen), aber welche Weisheit haben sie?',
    },
    10: {
        11: 'Folgendes solltet (könnt, dürft) ihr zu ihnen sagen: „Die Götter, die den Himmel und die Erde nicht gemacht haben, werden (sollen, müssen) verschwinden (vergehen) von der Erde und von unter diesem Himmel!“',
    },
    20: {
        7: 'Du hast mich, JHWH, überredet und ich ließ mich überreden. Du bist mir zu stark geworden und hast gesiegt. Ich bin zum Gespött geworden den ganzen Tag; jeder [ist] mir ein Spötter.',
        8: 'Denn sooft ich rede, muss ich schreien, „Gewalttat“und „Bedrohung“muss ich rufen. Ja, das Wort JHWH s wurde mir zu Hohn und Spott den ganzen Tag.',
        9: 'Und ich habe [mir] gesagt: Ich will nicht an ihn denken und nicht mehr in seinem Namen reden; aber es wurde in meinem Herzen wie brennendes Feuer, verschlossen in meinen Knochen. Und ich habe mich vergeblich abgemüht es auszuhalten, aber ich konnte nicht!',
        10: 'Denn ich habe die Verleumdung von vielen gehört: „Schrecken ringsherum!“, „Zeigt ihn an!“und „Lasst uns ihn anzeigen!“Alle meine Freunde erwarten meinen Untergang: „Vielleicht lässt er sich verleiten, damit wir ihn besiegen und unsere Rache nehmen an ihm.“',
        11: 'Aber JHWH [ist] bei mir wie ein starker Held, deshalb werden meine Verfolger straucheln und nicht siegen! Sie werden sich sehr schämen, denn sie sind nicht einsichtig; eine ewige Schande - sie wird nicht vergessen werden.',
        12: 'Und [du], JHWH der Heerscharen (Zebaot), der du den Gerechten prüfst und siehst Nieren und Herz: Lass mich sehen deine Rache an ihnen! Denn dir habe ich anvertraut meinen Streit.',
        13: 'Singt JHWH, lobt JHWH, denn er hat die Seele des Unglücklichen gerettet aus der Hand der Übeltäter!',
    },
    23: {
        5: 'Siehe: Tage kommen – Spruch JHWH s. Ich werde für David einen gerechten Sproß wachsen (aufgehen) lassen. Er wird als König regieren (herrschen) und Einsicht haben. Er wird Recht tun und Gerechtigkeit im Land (auf der Erde).',
        6: 'In seinen Tagen (zu seiner Zeit) wird Juda geholfen werden und Israel wohnt in Sicherheit.',
        7: 'Daher siehe: Tage kommen – Spruch JHWH s. Sie werden nicht mehr sagen: So wahr JHWH lebt, der die Söhne Israels (Israeliten) aus dem Land Ägypten heraufgeführt hat.',
        8: 'Sondern: So wahr JHWH lebt, der heraufgeführt hat, und der gebracht hat die Nachkommenschaft des Hauses Israel aus dem Land des Nordens und aus allen Ländern, wohin ich sie versprengt (fortgetrieben) habe. Sie werden zu ihrem Ackerland (Landbesitz) zurückkehren.',
    },
    29: {
        4: 'So spricht JHWH der Heerscharen (Zebaot), der Gott Israels zu allen Weggeführten, die ich von Jerusalem [nach] Babel in Verbannung geführt habe:',
        5: '„Baut Häuser und wohnt [darin] und pflanzt Gärten und esst ihre Früchte!',
        6: 'Nehmt [euch] Frauen und zeugt Söhne und Töchter, und nehmt für eure Söhne Frauen und gebt Männern eure Töchter – sodass (und) sie Söhne und Töchter gebären werden und werdet dort groß und nicht weniger!',
        7: 'Und sucht der Stadt Wohlergehen, [in] die ich euch in Verbannung geführt habe und betet für sie zu JHWH: Denn in ihrem Frieden wird für euch Frieden sein!“',
        8: 'Fürwahr, so spricht JHWH der Heerscharen (Zebaot), der Gott Israels: „Und [es] sollen euch nicht eure Propheten täuschen, die in eurer Mitte sind und eure Wahrsager und ihr [sollt] (werdet) nicht [auf die] hören, die euch zum Träumen verleiten!',
        9: 'Denn in Lüge reden sie prophetisch zu euch in meinem Namen – ich habe sie nicht gesandt“, Ausspruch JHWH s.',
        10: 'Fürwahr, so spricht JHWH: „Wenn (denn) für Babel siebzig Jahre gänzlich erfüllt sind, werde ich mich eurer annehmen und […] (ich) mein gutes Wort über euch erfüllen um euch zu diesem Ort zurückzubringen!',
        11: 'Denn ich kenne die Pläne, die ich über euch dachte“, Ausspruch JHWH s. „Heilsgedanken und nicht […] (für) Böses um […] (für) euch Zukunft und Hoffnung zu geben!',
        12: 'Wenn (und) ihr mich anruft und ihr geht, [dass] (und) ihr zu mir betet: Und ich werde euch erhören!',
        13: 'Wenn (und) ihr mich sucht […] (und) werdet ihr [mich] finden, denn [wenn] ihr mich suchen werdet mit eurem ganzen Herzen, [so] (und) werde ich mich finden lassen',
        14: 'von euch“, Ausspruch JHWH s. „Und ich werde eure Gefangenschaft wenden und ich werde euch sammeln aus allen Völkern und aus allen Orten von wo ich euch vertrieben habe“, Ausspruch JHWH s. „Und ich werde euch zurückbringen an (nach) den Ort, […] (der) von dort [aus] ich euch in Verbannung geführt habe.“',
    },
}
