NAME = 'GerOffBiSt: Offene Bibel - Studienfassung'
BOOK = 'Philippians'

CHAPTERS = {
    1: {
        1: 'Paulus und Timotheus, Sklaven Christi Jesu, allen Heiligen in Christus Jesus, die in Philippi sind, mit den Bischöfen (urspr.: Aufseher) und Diakonen (urspr.: Diener, Helfer),',
        2: 'Gnade [sei] mit euch und Friede von Gott, unserem Vater, und [vom] Herrn Jesus Christus.',
        3: 'Ich danke meinem Gott (bei aller Erinnerung an euch =) so oft ich euer gedenke',
        4: 'immer (stets) in jedem meiner Gebete (jeder Bitte) für euch alle, wobei ich mit Freude (n) das Gebet (tue =) verrichte,',
        5: 'wegen (für) eurer Gemeinschaft für das (am) Evangelium vom ersten Tag bis jetzt,',
        6: 'überzeugt davon (gewiss darin), dass der, der bei euch begonnen hat (den Anfang machte) [das] gute Werk, [es] zu Ende bringen (beendigen, vollenden) wird bis zum Tage Christi Jesu.',
        7: 'So ist es (für mich =) in meinen Augen recht (richtig, billig), dies über euch alle zu denken, weil ich euch im Herzen habe, in meinem Gefängnis und auch in der Verteidigung und Befestigung (festen Begründung) des Evangeliums; ihr seid alle Teilhaber (Genossen) meiner Gnade.',
        8: 'Denn Gott ist mein Zeuge, wie ich mich nach euch allen sehne in der Liebe (Zuneigung) Christi Jesu.',
        9: 'Und dies erbitte (bitte) ich, damit eure Liebe mehr und mehr wachse in der Erkenntnis und in aller Erfahrung',
        10: 'damit ihr das, worauf es ankommt (das Wesentliche), prüft, damit ihr lauter und tadellos seid für den (am) Tag Christi,',
        11: 'erfüllt von der Frucht der Gerechtigkeit, die durch Jesus Christus [geschaffen ist] zu Ehre und Lob Gottes.',
        12: 'Wissen lassen will ich euch aber, Geschwister, dass meine Angelegenheiten eher zur Förderung des Evangeliums ausgeschlagen sind',
        13: 'weil nämlich (sodass) meine Gefangenschaft durch Christus bekannt wurde im ganzen Prätorium und bei allen übrigen',
        14: 'und die meisten der Geschwister im Herrn, weil sie durch meine Gefangenschaft überzeugt waren, hatten in stärkerem Maße (stärker) den Mut (wagten), furchtlos das Wort zu predigen (verkündigen).',
        15: 'Einige (Manche) {zwar} verkündigen Christus auch durch Neid und Streit (Hader), einige (manche) {aber} auch durch guten Willen.',
        16: 'Die einen aus Liebe, weil sie wissen, dass ich zur Verteidigung des Evangeliums bestimmt (eingesetzt) bin,',
        17: 'die anderen verkündigen Christus aus Selbstsucht (Eigennutz), nicht lauter (unlauter), weil sie meinen (denken) [mir] in meiner Gefangenschaft Trübsal (Kummer) zu bereiten.',
        18: 'Was denn? Außer dass auf jede Weise, sei es unter einem Vorwand, sei es in Wahrheit, Christus verkündigt wird, und darüber freue ich mich. Aber ich werde mich auch freuen,',
        19: 'denn ich weiß, dass mir dies zur Rettung (Heil, Erlösung) ausschlagen wird durch eure Bitten und [durch] Unterstützung des Geistes Jesu Christi,',
        20: 'gemäß (entsprechend) meiner sehnsüchtigen Erwartung und Hoffnung, dass ich in keiner Weise (in nichts) beschämt (zuschanden) werde, sondern frei (offen, in aller Öffentlichkeit), wie immer, so auch jetzt Christus durch meinen Leib verherrlicht wird, sei es durchs Leben, sei es durch den Tod.',
        21: 'Denn für mich [ist] zu leben Christus, und zu sterben Gewinn.',
        22: 'Wenn es aber das Leben im Fleisch [ist], [ist, bedeutet] dies für mich Frucht der Arbeit (= Arbeitsertrag), und was ich vorziehe, weiß ich nicht.',
        23: 'Von beiden [Seiten] aber werde ich angefochten (gequält), ich habe Verlangen, aufzubrechen (abzuscheiden) und mit Christus zu sein, [wie] viel besser {nämlich} [wäre das]!',
        24: 'Aber das Bleiben im Fleisch ist nötiger euretwegen.',
        25: 'Und dies weiß ich gewiss, dass ich bleibe und bleiben werde bei euch allen zu eurer Förderung und [zur] Freude des Glaubens,',
        26: 'damit das, was zu eurem Ruhm gesagt wird (wörtl.: das Loblied), in Christus Jesus im Überfluss vorhanden ist durch mich, (durch meine Anwesenheit wiederum bei euch =) dadurch, dass ich wiederum zu euch komme.',
        27: 'Nur (bloß) führt euer Leben würdig des Evangeliums Christi, damit ich, ob ich komme und euch sehe, oder abwesend von euch höre, {dass} ihr in einem Glauben steht, einmütig zusammen für den Glauben des Evangeliums streitet',
        28: 'und euch nicht einschüchtern lasst in nichts (in keiner Hinsicht) von den Widersachern, was ihnen ein Anzeichen (Beweis) des Verderbens, euch aber der Rettung ist, und das von Gott.',
        29: 'Denn euch wurde geschenkt das für Christus nicht allein an ihn Glauben, sondern auch das für ihn Leiden.',
        30: 'Ihr habt den selben Kampf zu bestehen, wie ihr ihn an mir seht und nun von mir hört.',
    },
    2: {
        1: 'Wenn nun Trost (Ermahnung, Zuspruch) in Christus etwas gilt, {wenn} Zuspruch (Erleichterung) der Liebe {etwas gilt}, {wenn} Gemeinschaft des Geistes (Geistgemeinschaft) {etwas gilt}, {wenn} Erbarmen {etwas gilt},',
        2: 'dann macht meine Freude [dadurch] vollkommen, dass ihr (dasselbe denkt =) einmütig seid, die selbe Liebe besitzt, einträchtig, auf das Eine bedacht seid,',
        3: 'niemals streitsüchtig (rechthaberisch), niemals ruhmbegierig (eingebildet), sondern zieht einander dadurch vor (stellt einer den anderen über sich selbst), dass ihr euch an Demut übertrefft,',
        4: 'und seht jeder nicht auf das Seine, sondern vor allem {alle} auf das der anderen.',
        5: 'Hegt diese Gesinnung untereinander, die ihr auch (in Christus Jesus =) als Glieder Christi [hegen müsst],',
        6: 'Der, obwohl er in Gestalt Gottes war nicht als Geschenk des Zufalls (Glücksfund; Beute) sah er an das Gleichsein mit Gott,',
        7: 'sondern entblößte (entleerte, beraubte) sich selbst, indem er die Gestalt eines Knechtes (Sklaven) annahm, und (sich in Gestalt der Menschen befand =) menschenähnlich war und seinem Aussehen nach als Mensch erschien.',
        8: 'Er erniedrigte sich selbst und wurde gehorsam bis zum Tod, und zwar zum (Tod des Kreuzes =) Kreuzestod.',
        9: 'Deshalb hat ihn auch Gott hoch erhoben und ihm aus Gnade den Namen geschenkt, der über alle Namen ist,',
        10: 'damit (in dem Namen Jesu =) beim Erklingen des Namens Jesu jedes Knie sich beuge der Himmlischen (himmlischen Wesen) und der Irdischen (irdischen Wesen) und Unterirdischen (unterirdischen Wesen),',
        11: 'und jede Zunge wird anerkennen (bekennen), dass Herr [ist] Jesus Christus zur Ehre Gottes des Vaters.',
        12: 'Daher (also) erarbeitet euch, meine Lieben (Geliebten), eure Rettung (euer Heil) mit Furcht und Zittern, wie ihr mir immer (jederzeit) gehorcht habt, nicht wie [etwas, das] allein bei meiner Anwesenheit [geschehen würde], sondern jetzt noch viel mehr bei meiner Abwesenheit.',
        13: 'Denn Gott ist es, der in euch bewirkt sowohl das Wollen als auch das wirksam Sein (das sich Betätigen) über den guten Willen hinaus.',
        14: 'Alles tut ohne Murren und Bedenken (Zweifel),',
        15: 'damit ihr untadelig und unverdorben seid, Gottes untadelige Kinder inmitten einer krummen (verkehrten) und verdorbenen (verkehrten) Zeit (Generation, Geschlecht), in der ihr scheint (leuchtet) wie Sterne (Gestirne) am Himmel (Weltraum),',
        16: 'die das Wort des Lebens festhalten, zu meinem Ruhm für den Tag des Christus (= des Messias), dass ich nicht vergebens (umsonst, erfolglos) gelaufen bin noch mich vergebens (umsonst, erfolglos) gemüht habe.',
        17: 'Aber wenn ich auch geopfert werde beim Opfer und Opferdienst eures Glaubens, freue ich mich und freue mich mit euch allen.',
        18: 'In gleicher Weise freut auch ihr euch und freut euch mit mir!',
        19: 'Ich hoffe aber im Herrn Jesus, Timotheus bald zu euch zu schicken, damit auch ich guten Mutes werde, wenn ich eure Lage erfahre.',
        20: 'Denn ich habe keinen, der derart [mit euch] solidarisch wäre, dass er aufrichtig besorgt um eure Lage ist.',
        21: 'Denn alle verfolgen ihre Angelegenheiten (ihre Sache), nicht die Jesu Christi.',
        22: 'Ihr wisst aber, dass er etwas taugt (wörtl.: ihr kennt ihn als erprobt), denn wie ein Kind dem Vater, [so] hat er mit mir dem Evangelium gedient.',
        23: 'Diesen nun hoffe ich, zu euch zu schicken, sofort, sowie ich meine Lage überblicken kann.',
        24: 'Ich vertraue aber im Herrn darauf (baue darauf), dass ich auch selbst bald kommen werde.',
        25: 'Ich habe es aber für notwendig angesehen, Epaphroditus, meinen Bruder, Mitarbeiter und Mitstreiter, {aber} euren Boten und der, dessen Dienst meinen Mangel behob, zu euch zu schicken,',
        26: 'da er nach euch allen Sehnsucht hatte und in Unruhe darüber war, dass ihr gehört hattet, er sei krank.',
        27: '{Und} er war auch krank, dem Tode nah. Aber Gott erbarmte sich seiner, nicht nur seiner allein, sondern auch meiner, damit ich nicht Kummer über Kummer hätte.',
        28: 'Besonders eilig habe ich ihn nun geschickt, damit, wenn ihr ihn seht, ihr wieder froh seid und auch ich sorgenfrei bin.',
        29: 'Nehmt ihn nun auf im Herrn mit aller Freude und haltet Leute wie ihn (wörtl.: solche) in Ehren,',
        30: "weil er um des Werkes Christi willen dem Tode nahegekommen war und sein Leben auf's Spiel gesetzt hat, um eure Abwesenheit im Dienst für mich zu vertreten.",
    },
    3: {
        1: 'Weiterhin, meine Geschwister, freut euch im Herrn. Euch das selbe zu schreiben ist mir {zwar} nicht langweilig, euch aber [gibt es größere] Gewissheit.',
        2: 'Hütet euch (nehmt euch in acht, seht euch vor) vor den Hunden, hütet euch vor den schlechten Arbeitern, hütet euch vor der Zerschneidung!',
        3: 'Denn wir sind die Beschneidung, die wir im Geist (oder: durch den Geist) Gott dienen und uns in Christus Jesus rühmen und nicht auf das Fleisch vertrauen,',
        4: "obwohl ich Zuversicht habe auch auf das Fleisch. Wenn ein anderer meint, er könne auf's Fleisch vertrauen, ich um so mehr!",
        5: 'Am achten Tag beschnitten, aus dem Volk Israel, Stamm Benjamin, Hebräer von (Hebräern =) hebräischen Eltern, was [meine Stellung zum] Gesetz betrifft (dem Gesetz nach) Pharisäer,',
        6: 'was meinen Eifer betrifft (dem Eifer nach) Verfolger der Gemeinde, was die Gerechtigkeit, die im Gesetz gewährt wird, betrifft (der Gerechtigkeit … nach), tadellos (untadelig).',
        7: 'Aber das, was für mich Gewinn war, das sah ich um Christi willen als Verlust (Nachteil) an.',
        8: 'Aber noch vielmehr sehe ich auch [jetzt] alles Verlust (Nachteil) an wegen der alles übertreffenden [Größe der] Erkenntnis Christi Jesu, meines Herrn, um dessentwillen ich mich um das alles bringen ließ, und halte es für Dreck (Abfall, Unrat, Mist, Kot), damit ich Christus gewönne',
        9: 'und in ihm gefunden werde, damit ich nicht meine Gerechtigkeit aus dem Gesetz habe, sondern die durch den Glauben an Christus, die Gerechtigkeit von Gott auf Grund des Glaubens,',
        10: 'damit ich ihn kennen lerne (kenne, erkenne) und die Macht seiner Auferstehung und die Gemeinschaft seiner Leiden, seinem Tod gleichgestaltet,',
        11: 'ob ich vielleicht irgendwie die Auferstehung von den Toten erlange (erreiche).',
        12: 'Nicht, dass ich [Christus] schon (geistig oder seelisch) erfasst (in mich aufgenommen) hätte oder schon vollendet wäre; ich eile (renne) aber, ob ich [ihn] auch ergreife, weil ich {auch} ergriffen wurde von Christus Jesus.',
        13: 'Geschwister, ich sehe mich selbst nicht an, [ihn] ergriffen zu haben. Eins aber [tue ich]: was hinten liegt {zwar} vergesse (vernachlässige) ich, nach dem aber, was vor mir liegt, strecke ich mich aus.',
        14: 'Ich laufe nach dem Ziel um den Kampfpreis der Berufung von oben durch Gott in Christus Jesus.',
        15: 'Soweit wir nun Eingeweihte [sind], lasst uns darauf bedacht sein (das im Sinn haben). Und wenn ihr etwas anderes wollt (im Sinn habt), wird Gott euch auch das offenbaren.',
        16: 'Nur, was wir erreicht haben: lasst uns an das selbe halten.',
        17: 'Ahmt mit mir zusammen [Christus] nach, Geschwister und blickt auf die, die so (wandeln =) handeln (leben), wie ihr uns als Vorbild habt.',
        18: 'Denn viele (wandeln =) leben, von denen ich euch oft gesprochen habe, nun aber spreche ich mit Tränen über die Feinde des Kreuzes Christi,',
        19: 'deren Ziel Verderben [ist], deren Gott der Bauch [ist] und deren Ehre (Ruhm) (in ihrer Schande =) in dem, was ihnen Schande macht, [besteht], die auf irdische Dinge bedacht sind.',
        20: 'Denn unser Gemeinwesen (Staat) befindet sich im Himmel, von wo wir auch als Retter erwarten den Herrn Jesus Christus,',
        21: 'der umgestalten (verwandeln) wird unseren Niedrigkeitsleib gleichgestaltet seinem Herrlichkeitsleib auf Grund der wirksamen Kraft, die ihn befähigt, sich ihm alles zu unterwerfen.',
    },
    4: {
        1: 'Daher (Deshalb, Also), meine geliebten und herbeigesehnten Geschwister, meine Freude und Schmuck, auf solche Weise steht fest im Herrn, Geliebte.',
        2: 'Euodia bitte ich und Syntyche {bitte ich}, einnmütig zu sein (dasselbe zu denken) im Herrn.',
        3: 'Ja, ich bitte auch dich, rechter („waschechter“) Gefährte (Genosse), steh ihnen bei (hilf ihnen), die mit mir zusammen im Evangelium gekämpft haben mit Clemens und meinen übrigen Mitarbeitern, deren Namen im Buch des Lebens [sind, stehen].',
        4: 'Freut euch immer (stets) im Herrn! Aufs neue (Nochmals, Wiederum) werde ich sagen: freut euch!',
        5: 'Eure Güte lasst alle Menschen erfahren. Der Herr [ist] nahe!',
        6: 'Um nichts sorgt euch, sondern in jedem Gebet und [jeder] Bitte sollen eure Anliegen (Bitten) mit Danksagung Gott kundgetan (zur Kenntnis gebracht) werden.',
        7: 'Und der Friede Gottes, der alle Vernunft übertrifft, bewahre (beschütze, behüte) eure Herzen und Gedanken in Christus Jesus.',
        8: 'Im übrigen (Außerdem, Weiterhin, Endlich), Geschwister, was wahr ist, was ehrbar (ehrwürdig), was gerecht, was rein, was angenehm (beliebt, wohlgefällig), was wohltuend (glückverheißend, löblich, anziehend, ansprechend), ob irgendeiner Tugend [hat] und ob irgendeiner Lob [verdient], das bedenkt.',
        9: 'Und was ihr bei mir gelernt und [von mir] übernommen und gehört und gesehen habt, das tut. Und der Gott des Friedens sei mit euch.',
        10: 'Ich freute mich aber sehr im Herrn, weil (dass) ihr endlich einmal aufgeblüht seid, was eure Fürsorge für mich betrifft, denn ihr dachtet [an mich], fandet aber keine Gelegenheit.',
        11: 'Nicht, dass ich bedürftig wäre, ich habe nämlich gelernt, wo (= bei wem) ich bin, genügsam zu sein.',
        12: 'Ich bin einerseits imstande (ich verstehe), mich zu kasteien, andererseits {bin ich imstande}, es mir gut gehen zu lassen (Überfluss zu haben). Ich bin durchaus (in allem, in jeder Beziehung) und in jeder Hinsicht (in allen Stücken) eingeweiht, sowohl satt sein (satt werden), als auch hungern, sowohl Überfluss haben wie Mangel leiden.',
        13: 'Alles vermag ich durch den, der mich stark macht.',
        14: 'Jedoch (indessen) habt ihr gut gehandelt, dass ihr an meiner Bedrängnis Anteil genommen habt.',
        15: 'Aber auch ihr Philipper wisst, dass am Beginn des Evangeliums, als ich von Mazedonien loszog (auszog), mir keine Gemeinde Anteil gewährte in Abrechnung des Gebens und Nehmens (der Ausgaben und Einnahmen) als ihr allein,',
        16: 'weil ihr mir auch nach Thessaloniki (ein- bis zweimal =) ein paarmal eine Zusendung machtet, um meinem Mangel abzuhelfen.',
        17: 'Nicht, dass ich die (Gabe =) Zinsen suche, sondern ich wünsche (die Frucht in ihrer reichlichen Fülle =) den Profit, zu euren Gunsten verrechnet (auf euer Konto gebucht).',
        18: 'Ich habe aber alles empfangen und lebe im Überfluss. Mir sind die Hände gefüllt, nachdem ich von Epaphroditus eure Gabe empfangen habe, ein wohlriechender Opferduft, ein angenehmes Opfer, wohlgefällig dem Herrn.',
        19: 'Mein Gott aber fülle all euren Mangel (Bedarf, Not) aus entsprechend seines Reichtums in der Herrlichkeit in Christus Jesus.',
        20: 'Unserem Gott und Vater aber sei Ehre bis in die fernste Ewigkeit. Amen.',
        21: 'Grüßt jeden Heiligen in Christus Jesus. Es grüßen euch die Geschwister, die bei mir sind.',
        22: 'Es grüßen euch alle Heiligen, am meisten aber die Kaisersklaven.',
        23: 'Die Gnade des Herrn Jesus Christus [sei] mit eurem Geist.',
    },
}
