NAME = 'SloKJV: Slovenian translation of Holy Bible King James Version (1769)'
BOOK = 'Malachi'

CHAPTERS = {
    1: {
        1: 'Breme Gospodove besede Izraelu, po Malahiju.',
        2: '»Ljubil sem vas,« govori Gospod. Vendar pravite: »V čem si nas ljubil?« » Mar ni bil Ezav Jakobov brat?« govori Gospod, »vendar sem ljubil Jakoba,',
        3: 'Ezava pa sovražil ter opustošil njegove gore in njegovo dediščino za zmaje divjine.«',
        4: 'Kakor govori Edóm: »Obubožani smo, toda vrnili se bomo in pozidali zapuščene kraje,« tako govori Gospod nad bojevniki: »Gradili bodo, toda jaz bom rušil. Imenovali jih bodo: ›Meja zlobnosti‹ in ›Ljudstvo, zoper katero ima Gospod ogorčenje na veke.‹«',
        5: 'Vaše oči bodo videle in rekli boste: » Gospod bo poveličan prek Izraelove meje.«',
        6: '»Sin časti svojega očeta in služabnik svojega gospodarja. Če sem jaz potem oče, kje je moja čast? In če sem jaz gospodar, kje je moj strah?« govori Gospod nad bojevniki, »vam, oh duhovniki, ki prezirate moje ime. Vi pa pravite: ›V čem smo prezirali tvoje ime?‹',
        7: 'Na mojem oltarju ste darovali oskrunjen kruh, vi pa pravite: ›V čem smo te oskrunili?‹ V tem, da pravite: › Gospodova miza je zaničevanja vredna.‹',
        8: 'In če darujete slepo za žrtev, mar ni to zlo? In če darujete hromo in bolno, mar ni to zlo? Daruj to sedaj svojemu voditelju; ali bo zadovoljen s teboj, ali sprejme tvojo osebo?« govori Gospod nad bojevniki.',
        9: '»In sedaj vas prosim, rotite Boga, da nam bo milostljiv. To je bilo z vašimi sredstvi. Mar bo cenil vaše osebe?« govori Gospod nad bojevniki.',
        10: '§ »Kdo je tam, celo med vami, da bi zaman zaprl vrata? Niti na mojem oltarju ognja ne netite zaman. Nobenega zadovoljstva nimam z vami,« govori Gospod nad bojevniki, »niti ne bom sprejel daritve iz vaše roke.',
        11: 'Kajti od sončnega vzhoda, celo do zahajanja istega bo moje ime veliko med pogani in na vsakem kraju bo mojemu imenu darovano kadilo in čista daritev, kajti moje ime bo veliko med pogani,« govori Gospod nad bojevniki.',
        12: '»Toda vi ste to oskrunili v tem, ko pravite: › Gospodova miza je oskrunjena; in njen sad, celó njegova jed, je zaničevanja vredna.‹',
        13: 'Pravite tudi: ›Glej, kakšna težava je to!‹ In vi ste nad tem vihali nos,« govori Gospod nad bojevniki, »in privedli to, kar je bilo raztrgano in hromo in bolno. Tako daritev ste privedli. Mar naj bi to sprejel iz vaše roke?« govori Gospod.',
        14: 'Toda preklet bodi slepar, ki ima v svojem tropu samca, pa prisega in žrtvuje Gospodu pokvarjeno stvar, kajti jaz sem velik Kralj,« govori Gospod nad bojevniki, »in moje ime je grozno med pogani.«',
    },
    2: {
        1: '»In sedaj, oh vi duhovniki, ta zapoved je za vas.',
        2: 'Če ne boste poslušali in če si tega ne boste položili k srcu, da izročite slavo mojemu imenu,« govori Gospod nad bojevniki, »bom nad vas poslal celo prekletstvo in bom preklel vaše blagoslove. Da, že sem jih preklel, ker si tega niste vzeli k srcu.',
        3: 'Glejte, pokvaril bom vaše seme in razmazal gnoj na vaše obraze, celó gnoj vaših slovesnih praznikov in nekdo vas bo odvedel z njim.',
        4: 'In vedeli boste, da sem to zapoved poslal k vam, da bi bila moja zaveza lahko z Levijem,« govori Gospod nad bojevniki.',
        5: '»Moja zaveza z njim je bila o življenju in miru in dal sem mu jih za strah, s katerim se me je bal in je bil prestrašen pred mojim imenom.',
        6: 'Postava resnice je bila v njegovih ustih in krivičnosti ni bilo najti na njegovih ustnicah. Z menoj je hodil v miru in nepristranskosti in mnoge je odvrnil proč od krivičnosti.',
        7: 'Kajti duhovnikove ustnice naj bi ohranile spoznanje in pri njegovih ustih naj bi iskali postavo, kajti on je poslanec od Gospoda nad bojevniki.',
        8: 'Toda odšli ste iz poti, mnogim ste povzročili, da se spotaknejo ob postavi, pokvarili ste Lévijevo zavezo,« govori Gospod nad bojevniki.',
        9: '»Zato sem vas tudi naredil zaničevanja vredne in vas ponižal pred vsem ljudstvom, glede na to, da se niste držali mojih poti, temveč ste bili delni v postavi.«',
        10: 'Mar nimamo vsi istega očeta? Mar nas ni ustvaril en Bog? Zakaj zahrbtno postopamo vsak človek zoper svojega brata z oskrunitvijo zaveze naših očetov?',
        11: 'Juda je postopal zahrbtno in ogabnost je zagrešena v Izraelu in v Jeruzalemu, kajti Juda je oskrunil svetost Gospoda, ki ga je ljubil in poročil hčer tujega boga.',
        12: 'Gospod bo iztrebil človeka, ki to počne, gospodarja in učenca, iz Jakobovih šotorov in tistega, ki daruje daritev Gospodu nad bojevniki.',
        13: 'In to ste ponovno storili, pokrivajoč Gospodov oltar s solzami, z jokanjem in z vzklikanjem, do take mere, da se ni več oziral na daritev ali to z dobro voljo sprejemal iz vaše roke.',
        14: 'Vendar pravite: ›Zakaj?‹ Ker je bil Gospod priča med teboj in ženo tvoje mladosti, proti kateri si zahrbtno ravnal, čeprav je ona tvoja družabnica in žena tvoje zaveze.',
        15: 'Mar ni on naredil eno? Vendar je imel preostanek duha. In zakaj eno? Da bi lahko iskal bogaboječe seme. Zato pazite na svojega duha in naj nihče ne postopa zahrbtno zoper ženo svoje mladosti.',
        16: 'Kajti Gospod, Izraelov Bog, pravi, da sovraži ločitev, kajti nekdo zakriva nasilje s svojo obleko,‹ govori Gospod nad bojevniki. ›Zato pazite na svojega duha, da ne ravnate zahrbtno.',
        17: 'S svojimi besedami ste izmučili Gospoda. Vendar pravite: ›V čem smo ga izmučili?‹ Ko pravite: ›Vsak, kdor počenja zlo, je dober v Gospodovih očeh in on se razveseljuje v njih‹ ali: ›Kje je Bog sodbe?‹«',
    },
    3: {
        1: '»Glejte, poslal bom svojega poslanca in pripravil bo pot pred menoj in Gospod, ki ga iščete, bo nenadoma prišel k svojemu templju, celo poslanec zaveze, v katerem se razveseljujete. Glejte, prišel bo,« govori Gospod nad bojevniki.',
        2: 'Toda kdo lahko prenese dan njegovega prihoda? In kdo bo obstal, ko se pojavi? Kajti podoben je prečiščevalčevemu ognju in podoben pralčevemu milu.',
        3: 'Sédel bo kakor prečiščevalec in čistilec srebra in očistil bo Lévijeve sinove in jih presejal kakor zlato in srebro, da bodo lahko Gospodu darovali daritev v pravičnosti.',
        4: 'Potem bo daritev Juda in Jeruzalema prijetna Gospodu, kakor v dneh iz davnine in kakor v prejšnjih letih.',
        5: 'In prišel bom bliže k vam, da sodim in bom hitra priča zoper čarodeje in zoper zakonolomce in zoper krivoprisežnike in zoper tiste, ki zatirajo najemnika pri njegovih plačilih, vdovo in osirotelega in ki odvračajo tujca pred njegovo pravico, mene pa se ne bojijo,« govori Gospod nad bojevniki.',
        6: '»Kajti jaz sem Gospod, jaz se ne spreminjam; zatorej vi, Jakobovi sinovi, niste uničeni.',
        7: 'Celo od dni svojih očetov ste odstopali od mojih odredb in se jih niste držali. Vrnite se k meni in jaz se bom vrnil k vam,« govori Gospod nad bojevniki. »Toda rekli ste: ›V čem se bomo vrnili?‹',
        8: 'Ali bo človek oropal Boga? Vendar ste me oropali. Toda vi pravite: ›V čem smo te oropali?‹ V desetinah in daritvah.',
        9: 'Prekleti ste s prekletstvom, kajti oropali ste me, celó ves ta narod.',
        10: 'Prinesite vse desetine v skladišče, da bo lahko hrana v moji hiši in preizkusite me sedaj s tem,« govori Gospod nad bojevniki, »če vam ne bom odprl oken neba in vam izlil blagoslova, tako da ne bo dovolj prostora, da bi ga sprejeli.«',
        11: 'Zaradi vas bom oštel požiralca in ne bo uničil sadov vaše zemlje niti vaša trta na polju svojega sadu ne bo odvrgla pred časom,« govori Gospod nad bojevniki.',
        12: '»In vsi narodi vas bodo klicali blagoslovljeni, kajti vi boste krasna dežela,« govori Gospod nad bojevniki.',
        13: '»Vaše besede so bile arogantne zoper mene,« govori Gospod. »Vendar pravite: ›Kaj smo tako zelo govorili zoper tebe?‹',
        14: 'Rekli ste: ›Prazno je služiti Bogu in kakšna korist je to, da smo se držali njegove odredbe in da smo žalujoč hodili pred Gospodom nad bojevniki?',
        15: 'In sedaj ponosnega imenujemo srečen. Da, tisti, ki počnejo zlobnost, so povzdignjeni; da, tisti, ki skušajo Boga, so celo osvobojeni.‹«',
        16: 'Potem so tisti, ki so se bali Gospoda, pogosto govorili drug drugemu. Gospod je prisluhnil in to slišal in knjiga spominov je bila napisana pred njim za tiste, ki so se bali Gospoda in tiste, ki mislijo na njegovo ime.',
        17: '»Oni bodo moji,« govori Gospod nad bojevniki, »na tisti dan, ko bom pripravil svoje dragocenosti; in jim prizanesel, kakor mož prizanese svojemu lastnemu sinu, ki mu služi.',
        18: 'Potem se boste vrnili in razločevali med pravičnim in zlobnim, med tistim, ki služi Bogu in tistim, ki mu ne služi.«',
    },
    4: {
        1: '»Kajti glejte, prihaja dan, ki bo gorel kakor peč in vsi ponosni, da in vsi, ki počno zlobno, bodo strnišče. In dan, ki prihaja, jih bo požgal,« govori Gospod nad bojevniki, »da jim ne preostane niti korenina niti mladika.',
        2: 'Toda vam, ki se bojite mojega imena, bo vzšlo Sonce pravičnosti, z ozdravljenjem v njegovih perutih, in šli boste naprej in rastli kakor teleta iz hleva.',
        3: 'Pomendrali boste zlobne, kajti oni bodo pepel pod podplati vaših stopal, na dan, ko bom to storil,« govori Gospod nad bojevniki.',
        4: '»Spominjajte se postave Mojzesa, mojega služabnika, ki sem mu jo zapovedal na Horebu, z zakoni in sodbami za ves Izrael.',
        5: 'Glejte, poslal vam bom Elija, preroka, pred prihodom velikega in groznega dneva Gospodovega.',
        6: 'Obrnil bo srca očetov k otrokom in srca otrok k njihovim očetom, da ne pridem in udarim zemlje s prekletstvom.«',
    },
}
