NAME = 'SloKJV: Slovenian translation of Holy Bible King James Version (1769)'
BOOK = 'Mark'

CHAPTERS = {
    1: {
        1: 'Začetek evangelija Jezusa Kristusa, Božjega Sina,',
        2: 'kakor je zapisano v prerokih: »Glej, pošiljam svojega poslanca pred tvojim obličjem, ki bo pripravil tvojo pot pred teboj.',
        3: 'Glas nekoga, ki kliče v divjini: ›Pripravite Gospodovo pot, izravnajte njegove steze.‹«',
        4: 'Janez je krščeval v divjini in oznanjal krst kesanja v odpuščanje grehov.',
        5: 'In k njemu je prišla vsa judejska dežela in tisti iz Jeruzalema in vsi so bili po njem krščeni v reki Jordan ter priznavali svoje grehe.',
        6: 'In Janez je bil odet s kameljo dlako in s pasom iz usnja okoli svojih ledij; in jedel je kobilice in divji med,',
        7: 'in oznanjal, rekoč: »Za menoj prihaja nekdo, močnejši kakor jaz, čigar čevljev jermena nisem vreden, da bi se sklonil in ju odvezal.',
        8: 'Zares sem vas krstil z vodo, toda on vas bo krstil s Svetim Duhom.«',
        9: 'In pripetilo se je v tistih dneh, da je prišel Jezus iz Nazareta v Galileji in je bil po Janezu krščen v Jordanu.',
        10: 'In nemudoma, ko se je vzpenjal iz vode, je zagledal odprta nebesa in Duha, podobnega golobici, spuščati se nadenj,',
        11: 'in prišel je glas z neba, rekoč: »Ti si moj ljubljeni Sin, s katerim sem zelo zadovoljen.«',
        12: 'In Duh ga je takoj gnal v divjino.',
        13: 'In tam, v divjini, je bil štirideset dni skušan od Satana in bil je z divjimi živalmi in angeli so mu stregli.',
        14: 'Potem ko je bil torej Janez vtaknjen v ječo, je Jezus prišel v Galilejo in oznanjal evangelij Božjega kraljestva',
        15: '§ ter govoril: »Čas je dopolnjen in Božje kraljestvo se je približalo. Pokesajte se in verjemite evangeliju.«',
        16: 'Ko je torej hodil ob Galilejskem morju, je zagledal Simona in njegovega brata Andreja metati mrežo v morje, kajti bila sta ribiča.',
        17: 'Jezus jima je rekel: »Pridita za menoj in storil vama bom, da postaneta ribiča ljudi.«',
        18: 'In nemudoma sta zapustila svoje mreže ter mu sledila.',
        19: 'In ko je odšel malce naprej od tam, je zagledal Jakoba, Zebedejevega sina in njegovega brata Janeza, ki sta bila prav tako na ladji in popravljala svoje mreže.',
        20: 'In nemudoma ju je poklical; in zapustila sta svojega očeta Zebedeja z najetimi služabniki na ladji ter odšla za njim.',
        21: 'In odšli so v Kafarnáum in nemudoma, na šabatni dan, je vstopil v sinagogo ter učil.',
        22: 'In nad njegovim naukom so bili osupli, kajti učil jih je kakor nekdo, ki ima oblast in ne kakor pisarji.',
        23: 'In v njihovi sinagogi je bil človek z nečistim duhom, in ta je zakričal,',
        24: 'rekoč: »Daj nam mir; kaj imamo opraviti s teboj, ti, Jezus Nazarečan? Ali si prišel, da nas uničiš? Vem, kdo si, Sveti od Boga.«',
        25: 'In Jezus ga je oštel, rekoč: »Umolkni in pojdi iz njega.«',
        26: 'In ko ga je nečisti duh trgal in zavpil z močnim glasom, je prišel iz njega.',
        27: 'In vsi so bili osupli, tako zelo, da so se med seboj spraševali, rekoč: »Kakšna beseda je to? Kakšen novi nauk je to? Kajti z oblastjo ukazuje celó nečistim duhovom in oni ga ubogajo.«',
        28: 'In njegov slôves se je takoj razširil po vsem celotnem področju okoli Galileje.',
        29: 'In ko so prišli iz sinagoge, so z Jakobom in Janezom nemudoma vstopili v Simonovo in Andrejevo hišo.',
        30: 'Toda Simonova tašča je ležala bolna zaradi vročice in takoj so mu povedali o njej.',
        31: 'In prišel je ter jo prijel za roko in jo dvignil; in vročica jo je takoj zapustila in jim je stregla.',
        32: 'In zvečer, ko je sonce zašlo, so k njemu privedli vse tiste, ki so bili bolni in tiste, ki so bili obsedeni s hudiči.',
        33: 'In vse mesto je bilo skupaj zbrano pri vratih.',
        34: 'In ozdravil je mnoge, ki so bili bolni zaradi različnih bolezni in izgnal mnogo hudičev; hudičem pa ni dovolil govoriti, ker so ga poznali.',
        35: 'In zjutraj, ko je vstal veliko pred dnevom, je odšel ven ter se odpravil na samoten kraj in tam molil.',
        36: 'Simon in tisti, ki so bili z njim, pa so sledili za njim.',
        37: 'In ko so ga našli, so mu rekli: »Vsi ljudje te iščejo.«',
        38: 'Rekel jim je: »Pojdimo v naslednja mesta, da bom lahko tudi tam oznanjal, kajti zato sem prišel.«',
        39: 'In po vsej celotni Galileji je oznanjal v njihovih sinagogah ter izganjal hudiče.',
        40: 'In k njemu je prišel gobavec, ga rotil in pokleknil navzdol k njemu ter mu rekel: »Če hočeš, me moreš narediti čistega.«',
        41: 'In Jezus, prevzet s sočutjem, je iztegnil svojo roko in se ga dotaknil in mu reče: »Hočem; bodi čist.«',
        42: '§ In brž, ko je izgovoril, je gobavost takoj odšla od njega in bil je očiščen.',
        43: '§ In strogo mu je zabičal ter ga nemudoma poslal proč,',
        44: 'ter mu rekel: »Glej, da nikomur nič ne poveš, temveč pojdi svojo pot, pokaži se duhovniku in daruj za svoje očiščenje te stvari, ki jih je Mojzes zapovedal, njim v pričevanje.«',
        45: 'Toda ta je odšel ven in začel to zelo naznanjati in besedo na široko razglašati, tako da Jezus ni mogel več javno vstopiti v mesto, temveč je bil zunaj na zapuščenih krajih, in k njemu so prihajali iz vsake četrti.',
    },
    2: {
        1: 'Po nekaj dneh je ponovno vstopil v Kafarnáum, in razglasilo se je, da je v hiši.',
        2: 'In nemudoma so bili zbrani mnogi, toliko, da tam ni bilo več prostora, da jih sprejme, ne, niti pred vrati ne; in oznanjal jim je besedo.',
        3: 'In prišli so k njemu in prinesli nekoga, bolnega zaradi paralize, ki je bil prenašan od štirih.',
        4: 'Ko pa zaradi gneče niso mogli priti bliže k njemu, so odkrili streho, kjer je bil. In ko so jo predrli, so spustili posteljo, na kateri je ležal bolni zaradi paralize.',
        5: 'Ko je Jezus videl njihovo vero, je rekel bolnemu zaradi paralize: »Sin, tvoji grehi so ti odpuščeni.«',
        6: 'Toda bili so nekateri izmed pisarjev, ki so tam sedeli ter v svojih srcih razmišljali:',
        7: '»Zakaj ta človek govori takšna bogokletja? Kdo lahko odpušča grehe razen Boga samega?«',
        8: 'In takoj, ko je Jezus v svojem duhu zaznal, da so v sebi tako modrovali, jim je rekel: »Zakaj v svojih srcih razmišljate te besede?',
        9: 'Ali je bolnemu zaradi paralize lažje reči: ›Tvoji grehi so ti odpuščeni‹ ali reči: ›Vstani in vzemi svojo posteljo ter hôdi?‹',
        10: 'Toda da boste lahko vedeli, da ima Sin človekov na zemlji oblast odpuščati grehe, (reče bolnemu zaradi paralize)',
        11: 'pravim ti: ›Vstani in vzemi svojo posteljo ter pojdi svojo pot v svojo hišo.‹«',
        12: 'In ta je takoj vstal, vzel posteljo ter pred njimi vsemi odšel, tako da so bili vsi osupli in slavili Boga, rekoč: »Nikoli tega nismo videli na tak način.«',
        13: 'In ponovno je odšel naprej ob morski obali, in vsa množica je krenila k njemu in jih je učil.',
        14: 'In ko je hodil mimo, je zagledal Levija, Alfejevega sina, ki je sedel pri kraju plačevanja davkov ter mu rekel: »Sledi mi.« In ta je vstal ter mu sledil.',
        15: 'In pripetilo se je, ko je Jezus v njegovi hiši sedel pri obedu, da je tudi mnogo davkarjev in grešnikov sedelo skupaj z Jezusom in njegovimi učenci, kajti bilo jih je mnogo in so mu sledili.',
        16: 'In ko so ga pisarji in farizeji videli jesti z davkarji in grešniki, so njegovim učencem rekli: »Kako to, da jé in pije z davkarji in grešniki?«',
        17: '§ Ko je Jezus to slišal, jim reče: »Tisti, ki so zdravi, nimajo nobene potrebe po zdravniku, temveč tisti, ki so bolni; nisem prišel klicat pravičnih, temveč grešnike h kesanju.«',
        18: 'Janezovi učenci in učenci farizejev so se postili; in prišli so ter mu rekli: »Zakaj se Janezovi učenci in učenci farizejev postijo, tvoji učenci pa se ne postijo?«',
        19: 'Jezus jim je rekel: »Ali se lahko otroci svatovske sobe postijo, dokler je z njimi ženin? Kolikor dolgo imajo s seboj ženina, se ne morejo postiti.',
        20: 'Toda prišli bodo dnevi, ko bo ženin vzet proč od njih in tedaj, v tistih dneh, se bodo postili.',
        21: 'Tudi nihče ne prišije koščka novega oblačila na staro obleko; sicer bo nov košček, ki jo je zapolnil, odvzel iz stare in nastane hujša raztrganina.',
        22: 'In novega vina nihče ne vliva v stare mehove, sicer novo vino mehove razžene, vino pa se izlije in mehovi bodo poškodovani; temveč mora biti novo vino vlito v nove mehove.«',
        23: 'In pripetilo se je, da je na šabatni dan šel skozi žitna polja; in njegovi učenci so med hojo začeli smukati žitno klasje.',
        24: 'Farizeji so mu rekli: »Glej, zakaj delajo na šabatni dan to, kar ni zakonito?«',
        25: 'Rekel jim je: »Ali niste nikoli brali, kaj je storil David, ko je imel potrebo in je bil lačen on in tisti, ki so bili z njim?',
        26: 'Kako je v dneh vélikega duhovnika Abjatárja odšel v Božjo hišo in jedel hlebe navzočnosti, kar ni zakonito jesti [nikomur] razen duhovnikom in je dal tudi tem, ki so bili z njim?«',
        27: 'In rekel jim je: »Šabat je bila narejena zaradi človeka, ne pa človek zaradi šabate,',
        28: 'zato je Sin človekov Gospod tudi [čez] šabat.«',
    },
    3: {
        1: 'Ponovno je vstopil v sinagogo; in tam je bil človek, ki je imel izsušeno roko.',
        2: 'In opazovali so ga, ali ga bo ozdravil na šabatni dan; da bi ga lahko obtožili.',
        3: 'In človeku, ki je imel izsušeno roko, reče: »Stopi naprej.«',
        4: 'In jim reče: »Ali je na šabatne dneve zakonito delati dobro ali delati zlo? Rešiti življenje ali ubiti?« Toda molčali so.',
        5: '§ Ko je z jezo pogledal na te naokoli, užaloščen zaradi trdote njihovih src, reče človeku: »Iztegni svojo roko.« In iztegnil jo je; in njegova roka je bila v celoti ozdravljena, tako kot druga.',
        6: 'In farizeji so odšli ter se s herodovci nemudoma posvetovali zoper njega, kako bi ga lahko pokončali.',
        7: 'Toda Jezus se je s svojimi učenci umaknil k morju, in sledila mu je velika množica iz Galileje in iz Judeje',
        8: 'in iz Jeruzalema in iz Idumeje in iz onstran Jordana; in tisti okoli Tira in Sidóna, velika množica je prišla k njemu, ko so slišali, kakšna velika dela je storil.',
        9: 'In svojim učencem je rekel, da naj ga zaradi množice pričakuje majhna ladja, da ne bi pritiskali nanj.',
        10: 'Kajti mnoge je ozdravil; tako da so pritiskali nanj, da bi se ga dotaknili, kateri so imeli nadloge.',
        11: 'In kadar so ga zagledali nečisti duhovi, so pred njim padali dol in vpili, rekoč: »Ti si Božji Sin.«',
        12: 'In strogo jim je zapovedoval, da naj ga ne razglašajo.',
        13: 'In povzpne se na goro ter pokliče k sebi katere je hotel, in prišli so k njemu.',
        14: 'In določil jih je dvanajst, da bi bili z njim in da bi jih lahko poslal naprej oznanjat',
        15: '§ ter bi imeli oblast, da ozdravljajo bolezni ter da izganjajo hudiče.',
        16: '§ In Simonu je dal vzdevek Peter;',
        17: 'in Jakoba, Zebedejevega sina in Janeza, Jakobovega brata; in dal jima je vzdevek Boanergés, to je: ›Sinova groma,‹',
        18: 'in Andreja in Filipa in Bartolomeja in Mateja in Tomaža in Jakoba, Alfejevega sina in Tadeja in Simona Kananeja',
        19: 'in Juda Iškarijota, ki ga je tudi izdal, in odšli so v hišo.',
        20: 'In množica ponovno pride skupaj, tako da so komaj jedli kruh.',
        21: 'In ko so njegovi prijatelji slišali o tem, so odšli ven, da ga primejo, kajti rekli so: »Brez pameti je.«',
        22: 'In pisarji, ki so prišli dol iz Jeruzalema, so rekli: »Bélcebuba ima in s princem hudičev izganja hudiče.«',
        23: 'In poklical jih je k sebi ter jim govoril v prispodobah: »Kako lahko Satan izžene Satana?',
        24: 'In če se kraljestvo razdvoji zoper sebe, takšno kraljestvo ne more obstati.',
        25: 'In če se hiša razdvoji zoper sebe, takšna hiša ne more obstati.',
        26: 'In če se Satan dvigne zoper samega sebe in se razdvoji, ne more obstati, temveč ima konec.',
        27: 'Nihče ne more vstopiti v hišo močnega in opleniti njegove dobrine, razen če ne bo najprej zvezal močnega; in tedaj bo oplenil njegovo hišo.',
        28: 'Resnično, povem vam: ›Vsi grehi bodo človeškim sinovom oproščeni in bogokletja, s katerimi bodo kakorkoli preklinjali,',
        29: 'toda kdor bo preklinjal zoper Svetega Duha, nima nikoli odpuščanja, temveč je v nevarnosti večnega prekletstva,‹«',
        30: 'kajti govorili so: »Nečistega duha ima.«',
        31: 'Tja so potem prišli njegovi bratje, njegova mati in stoječ zunaj, so poslali k njemu, [da] ga pokličejo.',
        32: 'In okoli njega je sedela množica in rekli so mu: »Glej, tvoja mati in tvoji bratje so zunaj [in] te iščejo.«',
        33: 'In odgovoril jim je, rekoč: »Kdo je moja mati ali moji bratje?«',
        34: 'Pogledal je naokoli na te, ki so sedeli okoli njega ter rekel: »Glejte, moja mati in moji bratje!',
        35: 'Kajti kdorkoli bo izvrševal Božjo voljo, ta isti je moj brat in moja sestra in mati.«',
    },
    4: {
        1: 'In ponovno je začel učiti ob morski obali, in tam se je k njemu zbrala velika množica, tako da je vstopil na ladjo in [na njej] sedel na morju; celotna množica pa je bila ob morju na kopnem.',
        2: 'In s prispodobami jih je učil mnoge stvari in jim s svojim naukom govoril:',
        3: '»Prisluhnite: ›Glejte, sejalec je odšel sejat,',
        4: 'in pripetilo se je, medtem ko je sejal, da je nekaj padlo poleg poti in prišla je perjad neba in to pozobala.',
        5: 'In nekaj je padlo na kamnita tla, kjer ni imelo dovolj zemlje; in je takoj pognalo, ker ni imelo nobene globine zemlje,',
        6: 'toda ko je sonce vzšlo, je bilo ožgano; in ker ni imelo korenine, se je posušilo.',
        7: 'In nekaj je padlo med trnje in trnje je zraslo in ga zadušilo in ni obrodilo sadu.',
        8: 'Drugo pa je padlo na dobro zemljo in rodilo sad, ki je pognal in se povečeval; in obrodilo, nekatero trideseterno in nekatero šestdeseterno in nekatero stoterno.‹«',
        9: 'In rekel jim je: »Kdor ima ušesa, da slišijo, naj posluša.«',
        10: 'Ko je bil sam, so ga ti, ki so bili z dvanajsterimi okoli njega, vprašali o prispodobi.',
        11: 'Rekel jim je: »Vam je dano, da poznate skrivnost Božjega kraljestva, toda tem, ki so zunaj, so vse te stvari prikazane v prispodobah,',
        12: 'da bi z gledanjem lahko videli, pa ne zaznali; in s poslušanjem lahko slišali, pa ne razumeli; da se ne bi kadarkoli spreobrnili in bi jim bili njihovi grehi odpuščeni.«',
        13: 'In rekel jim je: »Ali ne razumete te prispodobe? In kako boste potem razumeli vse prispodobe?',
        14: 'Sejalec seje besedo.',
        15: '§ In ti so tisti ob poti, kjer je bila posejana beseda, toda ko so jo slišali, takoj pride Satan in vzame besedo, ki je bila posejana v njihova srca.',
        16: 'In ti so prav tako tisti, ki so posejani na kamnita tla; ko so slišali besedo, jo takoj z veseljem sprejmejo,',
        17: 'v sebi pa nimajo korenine in tako zdržijo le nekaj časa. Kasneje, ko zaradi besede nastaneta stiska ali preganjanje, pa so takoj pohujšani.',
        18: 'In ti so tisti, ki so posejani med trnje; tisti, ki slišijo besedo,',
        19: 'in skrbi tega sveta, zapeljivost bogastev in poželenja po drugih stvareh vstopijo, zadušijo besedo in ta postane brezplodna.',
        20: 'In ti so tisti, ki so posejani na dobra tla; takšni, ki slišijo besedo in jo sprejmejo ter obrodijo sad, nekateri trideseternega, nekateri šestdeseternega in nekateri stoternega.«',
        21: 'In rekel jim je: »Ali se sveča prinese, da se postavi pod mernik ali pod posteljo? In ali se ne postavi na svečnik?',
        22: 'Kajti nič ni skrito, kar ne bo jasno pokazano; niti nič ni bilo obdržano tajno, razen da bi postalo znano.',
        23: 'Če ima katerikoli človek ušesa, da slišijo, naj posluša.«',
        24: 'Rekel jim je: »Pazite, kaj poslušate; s kakršno mero merite, tako vam bo odmerjeno; in vam, ki slišite, vam bo dano več.',
        25: 'Kajti kdor ima, njemu bo dano; kdor pa nima, bo od njega vzeto celó to, kar ima.«',
        26: 'In rekel je: »Božje kraljestvo je takšno, kot če bi človek v zemljo vrgel seme,',
        27: 'in bi spal in vstajal ponoči ter podnevi in seme bi pognalo in raslo, da sam ne ve kako.',
        28: 'Kajti zemlja sama od sebe prinaša sad; najprej bilko, potem klas in nató polno žita v klasu.',
        29: 'Toda ko sad obrodi, takoj pošlje srp, kajti prišla je žetev.«',
        30: 'In rekel je: »S čim naj primerjamo Božje kraljestvo? Ali s kakšno primerjavo naj ga primerjamo?',
        31: 'Podobno je zrnu gorčičnega semena, ki je, ko je posejano v zemljo, manjše od vseh semen, ki so v zemlji;',
        32: 'toda ko je posejano, zraste in postane večje od vseh zelišč in poganja ven velike mladike, tako da lahko pod njegovo senco prenočuje perjad neba.«',
        33: 'In z mnogimi takšnimi prispodobami jim je govoril besedo, kakor so jo bili zmožni slišati.',
        34: 'Toda brez prispodobe jim ni govoril. Ko pa so bili sami, je svojim učencem pojasnil vse besede.',
        35: 'In istega dne, ko je prišel večer, jim reče: »Prepeljimo se na drugo stran.«',
        36: 'Ko so množico odpustili, so ga vzeli na ladjo, tako kakor je bil. Z njim pa so bile tam tudi druge majhne ladje.',
        37: 'In vzdignil se je velik vetroven vihar in valovi so udarjali v ladjo, tako, da je bila v kratkem polna.',
        38: 'On pa je bil na zadnjem delu ladje, speč na blazini in zbudili so ga ter mu rekli: »Učitelj, te ne skrbi, da ginemo?«',
        39: 'In vstal je, zapretil vetru in rekel morju: »Mir, bodi mirno.« In veter je ponehal in bil je velik mir.',
        40: 'In rekel jim je: »Zakaj ste tako boječi? Kako to, da nimate vere?«',
        41: 'In silno so se ga bali in drug drugemu govorili: »Kakšne vrste človek je to, da ga ubogata celó veter in morje?«',
    },
    5: {
        1: 'In prišli so preko, na drugo stran morja, v deželo Géračanov.',
        2: 'In ko je prišel z ladje, ga je takoj srečal tisti iz grobnic, človek z nečistim duhom,',
        3: 'ki je imel svoje prebivališče med grobnicami; in noben človek ga ni mogel zvezati, ne, niti z verigami ne,',
        4: 'zato ker je bil pogosto zvezan z okovi in verigami, pa je verige potrgal narazen in okove razbil na koščke; niti ga noben človek ni mogel obvladati.',
        5: 'In vedno, ponoči in podnevi, je bil po gorah ter v grobnicah in kričal ter samega sebe rezal s kamni.',
        6: 'Toda ko je od daleč zagledal Jezusa, je stekel in ga oboževal',
        7: 'in z močnim glasom zakričal ter rekel: »Kaj imam opraviti s teboj, Jezus, ti Sin najvišjega Boga? Zaklinjam te pri Bogu, da me ne mučiš.«',
        8: 'Kajti rekel mu je: »Pridi ven iz človeka, ti nečisti duh.«',
        9: 'In vprašal ga je: »Kakšno je tvoje ime?« On pa je odgovoril, rekoč: »Moje ime je Legija, ker nas je veliko.«',
        10: 'In zelo ga je rotil, da jih ne bi poslal proč, ven iz dežele.',
        11: 'Tam je bila torej, blizu gorá, velika čreda svinj, ki so se pasle.',
        12: 'In vsi hudiči so ga rotili, rekoč: »Pošlji nas v svinje, da bomo lahko vstopili vanje.«',
        13: 'Jezus jim je nemudoma dal dovoljenje. In nečisti duhovi so odšli ven ter vstopili v svinje, in čreda je silovito stekla navzdol po strmini v morje (bilo jih je okoli dva tisoč) in so se zadušile v morju.',
        14: 'In tisti, ki so pasli svinje, so pobegnili in to povedali v mestu in na deželi. In ti so odšli, da vidijo, kaj je bilo to, kar se je zgodilo.',
        15: 'In prišli so k Jezusu ter zagledali tega, ki je bil obseden s hudičem in imel legijo, kako je sedel oblečen in pri zdravi pameti; in bili so prestrašeni.',
        16: 'Tisti, ki so to videli, so jim povedali, kako se je pripetilo temu, ki je bil obseden s hudičem in tudi glede svinj.',
        17: 'In začeli so ga prositi, naj odide iz njihovih krajev.',
        18: 'Ko je prišel na ladjo, ga je ta, ki je bil obseden s hudičem, prosil, da bi bil lahko z njim.',
        19: 'Vendar mu Jezus ni dovolil, temveč mu reče: »Pojdi domov k svojim prijateljem in jim povej, kako velike stvari je Gospod storil zate in je imel sočutje do tebe.«',
        20: 'In ta je odšel ter v Deseteromestju začel razglašati, kako velike stvari je Jezus storil zanj, in vsi ljudje so se čudili.',
        21: 'Ko je Jezus z ladjo ponovno prešel na drugo stran, se je k njemu zbralo mnogo ljudi; bil pa je blizu morja.',
        22: 'In glej, prihajal je eden izmed predstojnikov sinagoge, Jaír po imenu; in ko ga je ta zagledal, je padel k njegovim stopalom',
        23: 'in ga silno rotil, rekoč: »Moja majhna hčerka leži na točki smrti. Prosim te, pridi in nanjo položi svoje roke, da bo lahko ozdravljena in da bo živela.«',
        24: 'In Jezus je odšel z njim in sledilo mu je veliko ljudi ter pritiskalo nanj.',
        25: 'In neka ženska, ki je imela dvanajst let težavo s krvjo',
        26: 'in je od mnogih zdravnikov pretrpela mnoge stvari in porabila vse, kar je imela, pa se ni nič izboljšalo, temveč raje postalo huje,',
        27: 'je, ko je slišala o Jezusu, prišla v gnečo za njim in se dotaknila njegove obleke.',
        28: 'Kajti rekla je: »Če se lahko samo dotaknem njegovih oblek, bom zdrava.«',
        29: 'In studenec njene krvi je bil nemudoma posušen; in v svojem telesu je začutila, da je bila ozdravljena od te nadloge.',
        30: 'Jezus pa je v sebi takoj vedel, da je iz njega odšla moč, se v gneči obrnil in rekel: »Kdo se je dotaknil mojih oblačil?«',
        31: 'Njegovi učenci pa so mu rekli: »Množico vidiš, ki pritiska nate, pa praviš: ›Kdo se me je dotaknil?‹«',
        32: 'Pogledal je naokoli, da bi videl tisto, ki je storila to stvar.',
        33: 'Toda ženska, prestrašena in trepetajoča, ker je vedela, kaj se je v njej zgodilo, je pristopila in padla dol pred njim ter mu povedala vso resnico.',
        34: 'In rekel ji je: »Hči, tvoja vera te je naredila zdravo; pojdi v miru in bodi ozdravljena od svoje nadloge.«',
        35: 'Medtem ko je še govoril, je od hiše predstojnika sinagoge prišel nekdo, ki je rekel: »Tvoja hči je mrtva, zakaj še vedno vznemirjaš Učitelja?«',
        36: 'Brž ko je Jezus slišal besedo, ki je bila izgovorjena, reče predstojniku sinagoge: »Ne boj se, samo veruj.«',
        37: 'In nobenemu človeku ni dovolil, da mu sledi, razen Petru in Jakobu in Janezu, Jakobovemu bratu.',
        38: 'In pride v hišo predstojnika sinagoge in vidi hrup ter te, ki so jokali in silno tarnali.',
        39: 'In ko je vstopil, jim reče: »Zakaj delate ta trušč in jok? Gospodična ni mrtva, temveč spi.«',
        40: 'In smejali so se mu do norčevanja. Toda ko jih je vse postavil ven, vzame očeta in mater od gospodične in te, ki so bili z njim in vstopi tja, kjer je ležala gospodična.',
        41: 'In gospodično je prijel za roko ter ji rekel: »Talíta kumi,« kar je prevedeno: »Gospodična,« rečem ti, »vstani.«',
        42: 'In gospodična je nemudoma vstala ter hodila, kajti bila je stara dvanajst let. Oni pa so bili osupli z veliko osuplostjo.',
        43: 'In strogo jim je naročil, naj noben človek ne izve za to; in velel je, da naj ji bo nekaj dano za jesti.',
    },
    6: {
        1: 'In od tam je odšel ven ter prišel v svojo lastno deželo, in njegovi učenci so mu sledili.',
        2: 'In ko je prišel šabatni dan, je začel učiti v sinagogi, in mnogi, ki so ga poslušali, so bili osupli, rekoč: »Od kod ima ta človek te besede? In kakšna je ta modrost, ki mu je dana, da so po njegovih rokah storjena celó takšna mogočna dela?',
        3: 'Ali ni to tesar, Marijin sin, brat Jakoba in Jozéja in od Juda in Simona? In ali niso njegove sestre tukaj z nami?« In pohujševali so se nad njim.',
        4: 'Toda Jezus jim je rekel: »Prerok ni brez spoštovanja, razen v svoji lastni deželi in med svojim lastnim rodom in v svoji lastni hiši.«',
        5: 'In tam ni mogel storiti nobenega mogočnega dela, razen da je svoje roke položil na nekaj bolnih ljudi in jih ozdravil.',
        6: 'In čudil se je zaradi njihove nevere. In odšel je naokoli po vaseh ter učil.',
        7: 'In k sebi je poklical dvanajstere ter jih začel pošiljati po dva in dva, in dal jim je oblast nad nečistimi duhovi',
        8: 'in jim zapovedal, da naj na svojo pot ne jemljejo ničesar razen zgolj palice; ne malhe, ne kruha, ne denarja v svoji mošnji,',
        9: 'temveč naj bodo obuti v sandale in naj ne oblečejo dveh plaščev.',
        10: 'In rekel jim je: »V kateremkoli kraju vstopite v hišo, tam ostanite, dokler ne odidete iz tega kraja.',
        11: '§ Kdorkoli pa vas ne bo sprejel niti vas ne bo poslušal, ko odidete od tam, otresite prah pod vašimi stopali v pričevanje proti njim. Resnično, povem vam: ›Bolj znosno bo za Sódomo in Gomóro na dan sodbe, kakor za to mesto.‹«',
        12: 'In odšli so ven ter oznanjali, da naj bi se ljudje pokesali.',
        13: 'In izgnali so mnogo hudičev in z oljem mazilili mnoge, ki so bili bolni in jih ozdravili.',
        14: 'In kralj Herod je slišal o njem; (kajti njegovo ime je bilo razglašeno povsod) in rekel: »Da je bil Janez Krstnik obujen od mrtvih in zato se v njem kažejo mogočna dela.«',
        15: 'Drugi so rekli: »Da je Elija.« Drugi pa so rekli: »Da je prerok ali kakor eden izmed prerokov.«',
        16: 'Toda ko je Herod slišal o tem, je rekel: »To je Janez, ki sem ga obglavil. Obujen je od mrtvih.«',
        17: 'Kajti sam Herod je poslal in zgrabil Janeza ter ga zvezal v ječi zaradi Herodiade, žene svojega brata Filipa, ker se je z njo poročil.',
        18: 'Kajti Janez je rekel Herodu: »Zate ni zakonito, da imaš ženo svojega brata.«',
        19: 'Zato je imela Herodiada proti njemu spor in bi ga ubila, toda ni mogla,',
        20: '§ kajti Herod se je bal Janeza, ker je vedel, da je bil pravičen človek in svet in ga je spoštoval; in ko ga je poslušal, je storil mnoge stvari, poslušal pa ga je rade volje.',
        21: 'Ko pa je prišel primeren dan, da je Herod na svoj rojstni dan pripravil večerjo svojim velikašem, visokim stotnikom in upravnikom posestev Galileje,',
        22: 'in ko je vstopila hči od že omenjene Herodiade in plesala ter ugajala Herodu in tem, ki so sedeli z njim, je kralj rekel gospodični: »Prosi me, karkoli si želiš in ti bom to dal.«',
        23: 'In prisegel ji je: »Karkoli me boš prosila, ti bom to dal, do polovice svojega kraljestva.«',
        24: 'In odšla je in rekla svoji materi: »Kaj naj prosim?« Ta pa je rekla: »Glavo Janeza Krstnika.«',
        25: 'In nemudoma je z naglico vstopila h kralju ter prosila, rekoč: »Hočem, da mi v kratkem na velikem pladnju izročiš glavo Janeza Krstnika.«',
        26: 'In kralj je bil silno žalosten, vendar je zaradi svoje prisege in zaradi teh, ki so sedeli z njim, ni hotel zavrniti.',
        27: 'In kralj je takoj poslal rablja ter ukazal, da se prinese njegova glava; in ta je odšel ter ga v ječi obglavil',
        28: 'in na velikem pladnju prinesel njegovo glavo ter jo dal gospodični, gospodična pa jo je dala svoji materi.',
        29: 'Ko so njegovi učenci slišali o tem, so prišli in vzeli njegovo truplo in ga položili v grobnico.',
        30: 'In apostoli so se skupaj zbrali k Jezusu ter mu povedali vse stvari, tako kaj so delali, kakor kaj so učili.',
        31: 'In rekel jim je: »Pridite sami, ločeno, na zapuščen kraj in nekaj časa počijte,« kajti tam so bili mnogi, ki so prihajali in odhajali in niso imeli nobenega prostega časa, niti toliko, da bi jedli.',
        32: 'In skrivoma so z ladjo odpluli na zapuščen kraj.',
        33: 'Množica pa jih je videla odhajati in mnogi so ga poznali in iz vseh mest so peš tekli tja ter jih prehiteli in skupaj prišli k njemu.',
        34: 'Ko pa je Jezus prišel ven, je zagledal mnogo ljudi in bil prevzet s sočutjem do njih, ker so bili kakor ovce, ki nimajo pastirja, in začel jih je učiti mnogo stvari.',
        35: 'Ko pa je dan davno minil, so k njemu prišli njegovi učenci in rekli: »To je zapuščen kraj in sedaj je čas davno potekel;',
        36: 'pošlji jih proč, da lahko gredo naokoli po deželi in v vasi in si kupijo kruha zase, kajti nič nimajo za jesti.«',
        37: 'Odgovoril je in jim rekel: »Dajte jim vi jesti.« Oni pa so mu rekli: »Ali naj gremo in kupimo za dvesto denarjev kruha ter jim damo jesti?«',
        38: 'Reče jim: »Koliko hlebov imate? Pojdite in poglejte.« In ko so vedeli, so rekli: »Pet in dve ribi.«',
        39: 'In ukazal jim je, naj se vsi po skupinah posedejo na zeleno travo.',
        40: 'In posedli so se v vrstah, po sto in po petdeset.',
        41: 'Ko je vzel pet hlebov in dve ribi, je pogledal gor v nebo in blagoslovil in razlomil hlebe in jih dal svojim učencem, da jih postavijo prednje; in dve ribi je razdelil med njih vse.',
        42: 'In vsi so jedli in bili nasičeni.',
        43: 'In pobrali so dvanajst polnih košar odlomkov in od rib.',
        44: 'Teh pa, ki so jedli od hlebov, je bilo okoli pet tisoč mož.',
        45: 'In svoje učence je nemudoma primoral, da gredo v ladjo in da gredo naprej, na drugo stran, v Betsajdo, medtem ko je on odpustil množico.',
        46: 'In ko jih je odpustil, je odšel na goro molit.',
        47: 'Ko pa je prišel večer, je bila ladja na sredi morja, on sam pa na kopnem.',
        48: 'In videl jih je garati v veslanju, kajti veter jim je bil nasproten. In okoli četrte nočne straže je prihajal k njim, hodil je po morju in bi šel mimo njih.',
        49: 'Toda ko so ga videli hoditi po morju, so domnevali, da je bil to duh in so zakričali,',
        50: 'kajti vsi so ga videli in so bili zaskrbljeni. On pa je z njimi takoj spregovoril in jim reče: »Bodite dobre volje; jaz sem, ne bojte se.«',
        51: 'In vzpel se je k njim na ladjo in veter je ponehal in v sebi so bili zelo osupli, prekomerno in so se čudili.',
        52: 'Kajti niso še preudarili čudeža s hlebi, ker je bilo njihovo srce zakrknjeno.',
        53: 'Ko pa so se prepeljali, so prišli v deželo Genezaret in se približali obali.',
        54: 'In ko so prišli z ladje, so ga nemudoma spoznali',
        55: 'in tekli naokoli prek celotnega področja in začeli s seboj nositi v posteljah te, ki so bili bolni, kjer so slišali, da se je nahajal.',
        56: '§ In kamorkoli je vstopil, v vasi ali mesta ali deželo, so na ulice polagali bolne in ga rotili, da bi se lahko dotaknili vsaj roba njegove obleke. In tako veliko, kot se ga je dotaknilo, so bili ozdravljeni.',
    },
    7: {
        1: 'Potem so prišli skupaj k njemu farizeji in nekateri izmed pisarjev, ki so prišli iz Jeruzalema.',
        2: 'In ko so videli nekatere izmed njegovih učencev jesti kruh z omadeževanimi, to se pravi z neumitimi rokami, so našli krivdo.',
        3: 'Kajti farizeji in vsi Judje ne jedo, razen če si svojih rok pogosto ne umivajo, ker se držijo izročila starešin.',
        4: 'In ko pridejo iz trga, ne jedo, razen če se ne umijejo. In mnogo drugih stvari je, ki so jih sprejeli, da se jih drže, kot umivanje čaš in vrčev, bakrenih posod in miz.',
        5: 'Potem so ga farizeji in pisarji vprašali: »Zakaj tvoji učenci ne živijo glede na izročilo starešin, temveč jedo kruh z neumitimi rokami?«',
        6: 'Odgovoril je in jim rekel: »Dobro je Izaija prerokoval o vas hinavcih, kakor je pisano: ›Ti ljudje me spoštujejo s svojimi ustnicami, toda njihovo srce je daleč od mene.‹',
        7: 'Čeprav me zaman obožujejo, ker za nauke učijo človeške zapovedi.',
        8: 'Ker se z odlaganjem Božje zapovedi na stran držite človeških izročil, kakor je umivanje čaš in vrčev in počnete še mnoge druge takšne stvari.«',
        9: 'In rekel jim je: »Prav dobro zavračate Božjo zapoved, da bi lahko obdržali svoje lastno izročilo.',
        10: 'Kajti Mojzes je rekel: ›Spoštuj svojega očeta in svojo mater,‹ in: ›Kdorkoli preklinja očeta ali mater, naj življenje konča s smrtjo,‹',
        11: 'toda vi pravite: ›Če bo človek rekel svojemu očetu ali materi: ›To je korbán, to se pravi dar, po čemerkoli bi lahko imel korist od mene,‹ bo prost.‹',
        12: 'In mu nič več ne dovolite, da bi za svojega očeta ali svojo mater karkoli storil.',
        13: 'S svojim izročilom, ki ste ga izročili, delate Božjo besedo brez učinka in počnete mnogo takšnih podobnih stvari.«',
        14: 'In ko je k sebi poklical vso množico, jim je rekel: »Vsak izmed vas naj mi prisluhne in razume:',
        15: '›Nič ni zunaj človeka, kar bi ga z vstopanjem vanj lahko omadeževalo, toda besede, ki pridejo iz njega, te so tiste, ki omadežujejo človeka.‹',
        16: 'Če ima katerikoli človek ušesa, da slišijo, naj posluša.«',
        17: 'Ko je od množice vstopil v hišo, so ga njegovi učenci vprašali glede prispodobe.',
        18: 'In reče jim: »Ali ste tudi vi tako brez razumevanja? Ali ne zaznate, da ga katerakoli stvar, ki od zunaj vstopa v človeka, ta ne more omadeževati,',
        19: 'ker ta ne vstopa v njegovo srce, temveč v trebuh in gre ven v zunanje stranišče, očiščujoč vso hrano?«',
        20: 'In rekel je: »To, kar prihaja iz človeka, to omadežuje človeka.',
        21: 'Kajti od znotraj, iz človekovega srca, izvirajo zle misli, zakonolomstva, prešuštva, umori,',
        22: 'tatvine, pohlepnost, zlobnost, prevara, pohotnost, hudoben pogled, bogokletje, ponos, nespametnost;',
        23: 'vse te zle stvari prihajajo od znotraj in omadežujejo človeka.«',
        24: 'In vstal je od tam ter odšel v meje Tira in Sidóna in vstopil v hišo in hotel, da tega ne bi izvedel noben človek, toda ni mogel ostati skrit.',
        25: 'Kajti neka ženska, katere mlada hči je imela nečistega duha, je slišala o njem in prišla ter padla k njegovim stopalom.',
        26: 'Ženska je bila Grkinja, Sirofeničanka po rodu, in rotila ga je, da bi iz njene hčere izgnal hudiča.',
        27: 'Toda Jezus ji je rekel: »Naj bodo najprej nasičeni otroci, kajti ni primerno vzeti kruha otrokom in ga vreči psom.«',
        28: 'Ona pa je odgovorila in mu rekla: »Da, Gospod, vendar psi pod mizo jedo od otroških drobtin.«',
        29: 'In rekel ji je: »Zaradi tega govora pojdi svojo pot; hudič je izšel iz tvoje hčere.«',
        30: 'In ko je prišla k svoji hiši, je spoznala, da je hudič izšel in svojo hčer [našla] ležečo na postelji.',
        31: 'In spet, ko je odšel iz tirskih in sidónskih pokrajin, je prišel h Galilejskemu morju, skozi sredo krajev Deseteromestja.',
        32: 'In k njemu prinesejo nekoga, ki je bil gluh in je imel motnjo v svojem govoru in rotili so ga, naj nanj položi svojo roko.',
        33: 'In vzel ga je proč od množice in svoja prsta položil v njegova ušesa in pljunil ter se dotaknil njegovega jezika',
        34: 'in zroč k nebu, je vzdihnil ter mu rekel: »Efatá!« to je: »Odpri se.«',
        35: 'In njegova ušesa so se nemudoma odprla in vez njegovega jezika se je sprostila in je jasno govoril.',
        36: 'In naročil jim je, da naj ne povedo nobenemu človeku, toda bolj, kot jim je naročal, toliko bolj na veliko so to razglašali,',
        37: 'in bili so preko mere osupli, rekoč: »Vse stvari je storil dobro; tako gluhim daje slišati, kakor nemim govoriti.«',
    },
    8: {
        1: 'V tistih dneh, [ko] je bila množica zelo velika in ni imela nič za jesti, je Jezus poklical k sebi svoje učence in jim rekel:',
        2: '»Sočutje imam do množice, ker so z menoj sedaj že tri dni, pa nimajo ničesar za jesti,',
        3: 'in če jih pošljem proč k njihovim lastnim hišam tešče, bodo med potjo oslabeli, kajti številni izmed njih so prišli od daleč.«',
        4: 'In njegovi učenci so mu odgovorili: »Od kod lahko človek, tukaj v divjini, te ljudi nasiti s kruhom?«',
        5: 'In vprašal jih je: »Koliko hlebov imate?« In rekli so: »Sedem.«',
        6: 'In zapovedal je množici, da se usede na tla, in vzel je sedem hlebov ter se zahvalil in prelomil ter dal svojim učencem, da jih postavijo prednje in oni so jih postavili pred množico.',
        7: 'In imeli so nekaj majhnih rib, in blagoslovil je ter velel, da jih prav tako postavijo pred njih.',
        8: 'Tako so jedli in bili nasičeni; in od odlomkov hrane, ki je ostala, so pobrali sedem košar.',
        9: 'In teh, ki so jedli, je bilo okoli štiri tisoč; in poslal jih je proč.',
        10: 'In s svojimi učenci je nemudoma vstopil na ladjo ter prišel v dalmanútske kraje.',
        11: 'In prišli so farizeji, ter se začeli pričkati z njim in ga skušali in od njega iskali znamenje z neba.',
        12: 'In v svojem duhu je globoko vzdihnil in rekel: »Zakaj ta rod išče znamenje? Resnično, povem vam: ›Temu rodu ne bo dano nobeno znamenje.‹«',
        13: 'In zapustil jih je ter vstopil na ladjo in ponovno odplul na drugo stran.',
        14: 'Učenci so torej pozabili vzeti kruh niti s seboj na ladji niso imeli več kakor en hleb.',
        15: 'In naročil jim je, rekoč: »Pazite, varujte se farizejskega kvasa in Herodovega kvasa.«',
        16: 'In med seboj so razpravljali, rekoč: » To je zato, ker nimamo kruha.«',
        17: 'Ko je Jezus to spoznal, jim reče: »Zakaj razmišljate, ker nimate kruha? Še niste zaznali niti razumeli? Ali imate svoje srce še vedno zakrknjeno?',
        18: 'Imate oči, pa ne vidite? Imate ušesa, pa ne slišite? In ali se ne spominjate?',
        19: 'Ko sem prelomil pet hlebov med pet tisoč, koliko košar, polnih odlomkov, ste pobrali?« Rekli so mu: »Dvanajst.«',
        20: '»In ko sedem med štiri tisoč, koliko košar, polnih odlomkov, ste pobrali?« In rekli so: »Sedem.«',
        21: 'In rekel jim je: »Kako to, da ne razumete?«',
        22: 'In pride v Betsajdo, in k njemu privedejo slepega moža in rotili so ga, da se ga dotakne.',
        23: 'In z roko je prijel slepega moža in ga odvedel iz mesta in ko je pljunil na njegove oči in svoji roki položil nanj, ga je vprašal, ali karkoli vidi.',
        24: 'In ta je pogledal gor ter rekel: »Vidim ljudi kakor drevesa, hodijo.«',
        25: 'Nató je svoje roke ponovno položil na njegove oči in ga pripravil, da pogleda gor, in bil je ozdravljen in razločno videl vsakega človeka.',
        26: '§ In poslal ga je proč k njegovi hiši, rekoč: »Niti ne pojdi v mesto niti tega ne povej nikomur v mestu.«',
        27: 'In Jezus je odšel ven ter njegovi učenci, v mesta Cezareje Filipove. Med potjo pa je svoje učence vprašal, rekoč jim: »Kdo ljudje pravijo, da sem jaz?«',
        28: 'Odgovorili so: »Janez Krstnik,« toda nekateri pravijo »Elija,« drugi pa: »Eden izmed prerokov.«',
        29: 'In reče jim: »Toda kdo vi pravite, da sem jaz?« In Peter odgovori ter mu reče: »Ti si Kristus.«',
        30: 'In naročil jim je, da naj nobenemu človeku ne povedo o njem.',
        31: 'In začel jih je učiti, da mora Sin človekov pretrpeti mnoge stvari in biti zavrnjen od starešin in od visokih duhovnikov in pisarjev in biti ubit ter po treh dneh ponovno vstati.',
        32: 'In ta govor je govoril javno. Peter pa ga je prijel in ga začel oštevati.',
        33: 'Toda ko se je obrnil okoli in pogledal na svoje učence, je Petra oštel, rekoč: »Spravi se za menoj, Satan, kajti ne posvečaš se stvarem, ki so Božje, temveč stvarem, ki so od ljudi.«',
        34: 'In ko je k sebi poklical množico, skupaj s svojimi učenci, jim je rekel: »Kdorkoli hoče priti za menoj, naj se odpove samemu sebi in vzame svoj križ in mi sledi.',
        35: 'Kajti kdorkoli hoče rešiti svoje življenje, ga bo izgubil, toda kdorkoli bo izgubil svoje življenje zaradi mene in evangelija, ta isti ga bo rešil.',
        36: '§ Kajti kaj bo koristilo človeku, če bo pridobil ves svet, izgubil pa svojo lastno dušo?',
        37: '§ Ali kaj bo dal človek v zamenjavo za svojo dušo?',
        38: 'Kdorkoli se bo torej v tem zakonolomnem in grešnem rodu sramoval mene in mojih besed, tega se bo sramoval tudi Sin človekov, ko pride v slavi svojega Očeta s svetimi angeli.«',
    },
    9: {
        1: 'In rekel jim je: »Resnično, povem vam: ›Da bo nekaj od teh, ki stojijo tukaj, ki ne bodo okusili smrti, dokler ne bodo videli Božjega kraljestva priti z močjo.‹«',
        2: 'In po šestih dneh Jezus vzame s seboj Petra in Jakoba in Janeza in jih posebej vodi na visoko goro; in pred njimi je bil preobražen.',
        3: 'In njegova oblačila so postala sijoča, silno bela kakor sneg, tako kot jih noben belivec na zemlji ne more pobeliti.',
        4: 'In prikazal se jim je Elija z Mojzesom; in onadva sta se pogovarjala z Jezusom.',
        5: '§ In Peter je odgovoril ter Jezusu rekel: »Učitelj, dobro je za nas, da smo tukaj; in naredimo tri šotore, enega zate in enega za Mojzesa in enega za Elija.«',
        6: 'Kajti ni vedel, kaj bi rekel, ker so bili boleče prestrašeni.',
        7: 'In tam je bil oblak, ki jih je obsenčil in iz oblaka je prišel glas, rekoč: »Ta je moj ljubljeni Sin, njega poslušajte.«',
        8: 'Nenadoma pa, ko so pogledali naokoli, niso videli nobenega človeka več, razen samo Jezusa, ki je bil z njimi.',
        9: 'In ko so prišli dol z gore, jim je naročil, naj nobenemu človeku ne povedo, kakšne stvari so videli, dokler ne bo Sin človekov vstal od mrtvih.',
        10: 'In ta govor so zadržali med njimi samimi in drug drugega spraševali, kaj naj bi pomenilo vstati od mrtvih.',
        11: 'In vprašali so ga, rekoč: »Zakaj pravijo pisarji, da mora najprej priti Elija?«',
        12: 'Odgovoril je in jim rekel: »Elija resnično prihaja prvi in obnavlja vse stvari in kako je pisano o Sinu človekovemu, da mora trpeti mnoge stvari ter biti zaničevan.',
        13: 'Toda povem vam: ›Da je Elija zares prišel in storili so mu, karkoli so si zahoteli, kakor je pisano o njem.‹«',
        14: 'In ko je prišel k svojim učencem, je okoli njih zagledal veliko množico in pisarje pričkati se z njimi.',
        15: 'In nemudoma, ko so ga zagledali, je bila vsa množica silno osupla ter stekla k njemu, da ga pozdravijo.',
        16: 'In pisarje je vprašal: »Kaj se pričkate z njimi?«',
        17: 'Nekdo iz množice pa je odgovoril in rekel: »Učitelj, k tebi sem privedel svojega sina, ki ima nemega duha,',
        18: 'in kjerkoli ga zgrabi, ga trga in se peni in škripa s svojimi zobmi in hira; in rekel sem tvojim učencem, da naj ga izženejo ven, pa niso mogli.«',
        19: 'Odgovarja mu in reče: »Oh neverni rod, kako dolgo bom z vami? Doklej vas bom trpel? Pripeljite ga k meni.«',
        20: 'In pripeljali so ga k njemu; in ko ga je zagledal, ga je duh nemudoma trgal, in padel je na tla ter se penast valjal.',
        21: 'In njegovega očeta je vprašal: »Kako dolgo je že, odkar je ta prišel vanj?« In odgovoril je: »Od otroštva.',
        22: 'In da ga pokonča, ga je pogosto vrgel v ogenj in v vode, toda če lahko karkoli storiš, imej sočutje do nas in nam pomagaj.«',
        23: 'Jezus mu je rekel: »Če lahko veruješ, so vse stvari mogoče tistemu, ki veruje.«',
        24: 'In otrokov oče je nemudoma zavpil in s solzami rekel: »Gospod, verujem, pomagaj moji neveri.«',
        25: 'Ko je Jezus videl, da je množica tekla skupaj, je oštel nečistega duha, rekoč mu: » Ti, nemi in gluhi duh, ukazujem ti, pridi iz njega in ne vstopi več vanj.«',
        26: 'In duh je zavpil ter ga hudo zgrabil in prišel iz njega; in bil je kakor nekdo, [ki je] mrtev, tako da so mnogi rekli: »Mrtev je.«',
        27: 'Toda Jezus ga je prijel za roko in ga dvignil in ta je vstal.',
        28: 'Ko pa je prišel v hišo, so ga njegovi učenci na samem vprašali: »Zakaj ga mi nismo mogli izgnati ven?«',
        29: '§ In rekel jim je: »Ta vrsta ne pride ven z ničimer, razen z molitvijo in postom.«',
        30: 'In odšli so od tam ter šli skozi Galilejo, in ni želel, da bi katerikoli človek to izvedel.',
        31: 'Kajti svoje učence je učil in jim govoril: »Sin človekov je izročen v človeške roke, in ubili ga bodo. In potem, ko bo umorjen, bo tretji dan vstal.«',
        32: 'Tega govora pa niso razumeli in bali so se ga vprašati.',
        33: 'In prišel je v Kafarnáum. In ko so bili v hiši, jih je vprašal: »Kaj je bilo to, da ste se po poti prerekali med seboj?«',
        34: 'Vendar so molčali, kajti med potjo so se med seboj prerekali, kdo naj bi bil največji.',
        35: 'In usedel se je, poklical dvanajstere in jim spregovoril: »Če želi katerikoli človek biti prvi, ta isti naj bo zadnji izmed vseh in služabnik vsem.«',
        36: 'In vzel je otroka ter ga posadil v sredo mednje, in ko ga je vzel v svoje naročje, jim je rekel:',
        37: '»Kdorkoli bo sprejel enega od takšnih otrok v mojem imenu, sprejema mene; in kdorkoli bo sprejel mene, ne sprejema mene, temveč tistega, ki me je poslal.«',
        38: 'In Janez mu je odgovoril, rekoč: »Učitelj, videli smo nekoga v tvojem imenu izganjati hudiče, pa nam ta ne sledi, in smo mu prepovedali, ker nam ne sledi.«',
        39: 'Vendar je Jezus rekel: »Ne prepovejte mu, kajti nobenega človeka ni, ki bi v mojem imenu storil čudež, da bi lahko brž hudobno govoril o meni.',
        40: 'Kajti kdor ni proti nam, je na naši strani.',
        41: 'Kajti kdorkoli vam bo za pitje ponudil čašo vode v mojem imenu, ker pripadate Kristusu, resnično vam povem, ne bo izgubil svoje nagrade.',
        42: 'In kdorkoli bo pohujšal enega od teh malčkov, ki verujejo vame, je bolje zanj, da bi bil okoli njegovega vratu obešen mlinski kamen in bi bil vržen v morje.',
        43: 'In če te tvoja roka pohujšuje, jo odsekaj proč; bolje je zate, da vstopiš v življenje pohabljen, kakor imeti dve roki in iti v pekel, v ogenj, ki ne bo nikoli pogašen,',
        44: 'kjer njihov črv ne umre in ogenj ni pogašen.',
        45: 'In če te tvoje stopalo pohujšuje, ga odsekaj proč; bolje je zate, da vstopiš v življenje šepav, kakor imeti dve stopali in biti vržen v pekel, v ogenj, ki ne bo nikoli pogašen,',
        46: '§ kjer njihov črv ne umre in ogenj ni pogašen.',
        47: 'In če te tvoje oko pohujšuje, ga iztakni ven; bolje je zate, da vstopiš v Božje kraljestvo z enim očesom, kakor biti z dvema očesoma vržen v peklenski ogenj,',
        48: '§ kjer njihov črv ne umre in ogenj ni pogašen.',
        49: 'Kajti vsakdo bo osoljen z ognjem in vsaka žrtev bo osoljena s soljo.',
        50: 'Sol je dobra, toda če je sol izgubila svojo slanost, s čim jo boste začinili? Imejte sol v sebi in imejte mir drug z drugim.«',
    },
    10: {
        1: 'In vzdignil se je od tam ter po drugi strani Jordana prihajal v judejske kraje; in množica je ponovno krenila k njemu, in kakor je bil navajen, jih je ponovno učil.',
        2: 'In k njemu so prišli farizeji ter ga vprašali: »Ali je možu zakonito odsloviti svojo ženo?« ker so ga skušali.',
        3: 'In odgovoril jim je ter rekel: »Kaj vam je zapovedal Mojzes?«',
        4: 'Rekli so: »Mojzes je dopustil napisati ločitveni list in [jo] odsloviti.«',
        5: 'Jezus pa je odgovoril in jim rekel: »Zaradi trdote vašega srca vam je napisal ta predpis.',
        6: 'Toda od začetka stvarstva ju je Bog ustvaril moškega in žensko.',
        7: 'Zaradi tega razloga bo mož zapustil svojega očeta in mater ter se trdno pridružil k svoji ženi',
        8: 'in ta dva bosta eno meso. Tako potem nista nič več dva, temveč eno meso.',
        9: 'Kar je torej Bog združil skupaj, naj človek ne loči narazen.«',
        10: 'In v hiši so ga njegovi učenci ponovno vprašali o isti zadevi.',
        11: 'Rekel jim je: »Kdorkoli bo odslovil svojo ženo in poročil drugo, proti njej zagreši zakonolomstvo.',
        12: 'In če bo ženska odslovila svojega soproga in bo poročena k drugemu, zagreši zakonolomstvo.«',
        13: 'In k njemu so prinašali mlajše otroke, da bi se jih dotaknil; njegovi učenci pa so ošteli te, ki so jih prinašali.',
        14: 'Vendar ko je Jezus to videl, je bil zelo nezadovoljen in jim rekel: »Dovolite majhnim otrokom, da pridejo k meni in ne prepovejte jim, kajti takšnih je Božje kraljestvo.',
        15: 'Resnično, povem vam: ›Kdorkoli Božjega kraljestva ne bo sprejel kakor majhen otrok, ne bo vstopil vanj.‹«',
        16: 'In dvignil jih je v svoje naročje, nanje položil svoji roki in jih blagoslovil.',
        17: 'In ko je odšel naprej po poti, je nekdo pritekel in pokleknil k njemu ter ga prosil: »Dobri Učitelj, kaj naj storim, da bom lahko podedoval večno življenje?«',
        18: 'Jezus mu je rekel: »Čemu me kličeš dober? Nihče ni dober razen enega, to je Boga.',
        19: 'Zapovedi poznaš: ›Ne zagreši zakonolomstva,‹ ›Ne ubijaj,‹ ›Ne kradi,‹ ›Ne pričaj po krivem,‹ ›Ne goljufaj,‹ ›Spoštuj svojega očeta in mater.‹«',
        20: 'Odgovoril je in mu rekel: »Učitelj, vse to sem obeleževal od svoje mladosti.«',
        21: 'Potem ga je Jezus pogledal, ga ljubil, ter mu rekel: »Ena stvar ti manjka, pojdi svojo pot, prodaj karkoli imaš in daj revnim in imel boš zaklad v nebesih in pridi, vzemi križ ter hodi za menoj.«',
        22: 'In ob tej besedi je bil žalosten ter užaloščen odšel proč, kajti imel je veliko posesti.',
        23: 'Jezus pa je pogledal naokoli in rekel svojim učencem: »Kako težko bodo tisti, ki imajo bogastva, vstopili v Božje kraljestvo!«',
        24: 'In učenci so bili ob njegovih besedah osupli. Vendar Jezus ponovno odgovarja in jim reče: »Otroci, kako težko je tem, ki zaupajo v bogastva, vstopiti v Božje kraljestvo!',
        25: 'Lažje je za kamelo, da gre skozi šivankino uho, kakor bogatašu vstopiti v Božje kraljestvo.«',
        26: 'In bili so prekomerno osupli ter med seboj govorili: »Kdo je potem lahko rešen?«',
        27: 'In Jezus, ko pogleda nanje, reče: »Pri ljudeh je to nemogoče, toda ne z Bogom, kajti z Bogom so vse stvari mogoče.«',
        28: 'Potem mu je Peter začel govoriti: »Glej, vse smo zapustili in ti sledili.«',
        29: 'Jezus pa je odgovoril in rekel: »Resnično, povem vam: ›Nikogar ni, ki je zapustil hišo ali brate ali sestre ali očeta ali mater ali ženo ali otroke ali zemljišča zaradi mene in evangelija,',
        30: 'toda prejel bo stokratno, sedaj, v tem času, hiš in bratov in sester in mater in otrok in zemljišč s preganjanji; in večno življenje v svetu, ki pride.',
        31: 'Toda mnogi, ki so prvi, bodo zadnji, in zadnji prvi.‹«',
        32: 'In bili so na poti, ki gre gor v Jeruzalem in Jezus je šel pred njimi in bili so osupli in medtem ko so ga spremljali, so bili prestrašeni. In ponovno je vzel dvanajstere ter jim začel pripovedovati, kakšne stvari naj bi se mu pripetile,',
        33: 'rekoč: »Glejte, mi gremo gor v Jeruzalem in Sin človekov bo izročen visokim duhovnikom in pisarjem in oni ga bodo obsodili na smrt ter ga izročili poganom',
        34: 'in zasmehovali ga bodo in ga bičali in pljuvali nanj ter ga umorili, toda tretji dan bo ponovno vstal.«',
        35: 'In Jakob in Janez, Zebedejeva sinova, sta prišla k njemu, rekoč: »Učitelj, midva hočeva, da nama storiš, karkoli bova prosila.«',
        36: 'In rekel jima je: »Kaj hočeta, da bi vama storil?«',
        37: 'Rekla sta mu: »Usliši naju, da bova lahko sedela v tvoji slavi, eden na tvoji desnici, drugi pa na tvoji levici.«',
        38: 'Toda Jezus jima je rekel: »Vidva ne vesta, česa prosita. Ali moreta piti iz čaše, iz katere jaz pijem? In biti krščena s krstom, s katerim sem jaz krščen?«',
        39: 'In odgovorila sta mu: »Moreva.« Jezus pa jima je rekel: »Vidva bosta zares pila iz čaše, iz katere jaz pijem; in s krstom, s katerim sem jaz krščen, bosta tudi vidva krščena,',
        40: 'toda sedeti na moji desnici in na moji levici, ni moje, da dam, temveč bo dano tistim, ki jim je to pripravljeno.«',
        41: 'In ko so deseteri to slišali, so postali zelo nezadovoljni z Jakobom in Janezom.',
        42: 'Toda Jezus jih je poklical k sebi in jim reče: »Vi veste, da tisti, ki se štejejo, da vladajo nad pogani, izvajajo gospostvo nad njimi, in njihovi velikaši izvajajo oblast nad njimi.',
        43: 'Toda med vami naj ne bo tako, temveč kdorkoli hoče biti med vami velik, naj bo vaš sluga;',
        44: 'in kdorkoli izmed vas hoče biti glavni, naj bo sluga vsem.',
        45: 'Kajti celo Sin človekov ni prišel, da bi mu služili, temveč, da služi in da svoje življenje daruje v odkupnino za mnoge.«',
        46: 'In prišli so v Jeriho, in ko je s svojimi učenci in velikim številom ljudi odšel iz Jerihe, je slepi Bartimáj, Timájev sin, sedel ob glavni cesti in beračil.',
        47: 'In ko je slišal, da je bil to Jezus Nazarečan, je začel vzklikati ter govoriti: »Jezus, ti Davidov Sin, usmili se me.«',
        48: 'In mnogi so ga opozarjali, naj molči, toda še veliko glasneje je vpil: » Ti, Davidov Sin, usmili se me.«',
        49: 'Jezus je obstal in velel, naj ga pokličejo. In poklicali so slepega moža ter mu rekli: »Bodi dobro potolažen, vstani, kliče te.«',
        50: 'In ta, ko je odvrgel svojo obleko proč, je vstal in prišel k Jezusu.',
        51: 'In Jezus je odgovoril ter mu rekel: »Kaj hočeš, da naj ti storim?« Slepi mož mu je rekel: »Gospod, da bi lahko prejel svoj vid.«',
        52: 'In Jezus mu je rekel: »Pojdi svojo pot; tvoja vera te je naredila zdravega.« In takoj je prejel svoj vid ter sledil Jezusu po poti.',
    },
    11: {
        1: 'In ko so prišli blizu Jeruzalema, k Bétfagi in Betaniji, ob Oljski gori, pošlje naprej dva izmed svojih učencev',
        2: 'in jima reče: »Pojdita svojo pot v vas pred vama in brž ko bosta vstopila vanjo, bosta našla privezano žrebe, na katerem človek nikoli ni sedel; odvežita ga in ga pripeljita.',
        3: 'Če pa bi vama katerikoli človek rekel: ›Čemu to počneta?‹ recita, da ima Gospod potrebo po njem; in on ga bo nemudoma poslal sèm.«',
        4: 'In odšla sta svojo pot ter našla zunaj pri vratih privezano žrebe, na kraju, kjer sta se srečali dve poti in sta ga odvezala.',
        5: 'Nekateri izmed tistih, ki so stali tam, pa so jima rekli: »Kaj počneta, da odvezujeta žrebe?«',
        6: 'In rekla sta jim torej kot je naročil Jezus in pustili so ju oditi.',
        7: 'In žrebe sta privedla k Jezusu in svoje obleke vrgla nanj in on je sédel nanj.',
        8: 'In mnogi so svoje obleke razgrnili na pot, drugi pa so z dreves odsekali mladike ter z njimi nastlali pot.',
        9: 'In tisti, ki so šli spredaj in tisti, ki so sledili, so vzklikali, rekoč: »›Hozana;‹ blagoslovljen je ta, ki prihaja v imenu Gospodovem;',
        10: 'blagoslovljeno bodi kraljestvo našega očeta Davida, ki prihaja v imenu Gospodovem: ›Hozana na višavah.‹«',
        11: 'In Jezus je vstopil v Jeruzalem in v tempelj. In ko se je razgledal naokoli po vseh stvareh in je torej prihajal večer, je z dvanajsterimi odšel ven v Betanijo.',
        12: 'In naslednji dan, ko so prišli iz Betanije, je bil lačen.',
        13: 'In ko je daleč stran zagledal figovo drevo, ki je imelo listje, je prišel, če bi morda lahko karkoli našel na njem. In ko je prišel k njemu, ni našel nič razen listov, kajti ni bil še čas za fige.',
        14: 'In Jezus je odgovoril ter mu rekel: »Nihče naj od tebe odslej nikoli več ne jé sadu.« In njegovi učenci so to slišali.',
        15: 'In prišli so v Jeruzalem in Jezus je odšel v tempelj ter začel izganjati te, ki so v templju prodajali in kupovali, menjalcem denarja pa je prevrnil mize in sedeže teh, ki so prodajali golobice',
        16: 'in ni dovolil, da bi katerikoli človek skozi tempelj nosil kakršnokoli posodo.',
        17: 'In učil jih je, rekoč: »Ali ni pisano: ›Moja hiša se bo od vseh narodov imenovala hiša molitve?‹ Vi pa ste jo naredili za brlog razbojnikov.«',
        18: 'Pisarji in visoki duhovniki pa so to slišali ter iskali, kako bi ga lahko pokončali, kajti bali so se ga, ker je bila vsa množica osupla nad njegovim naukom.',
        19: 'In ko je prišel večer, je odšel iz mesta.',
        20: 'In zjutraj, ko so šli mimo, so videli figovo drevo posušeno iz korenin.',
        21: 'Peter pa se spomni in mu reče: »Učitelj, glej, figovo drevo, ki si ga preklel, je ovenelo.«',
        22: 'In Jezus jim odgovarja, rekoč: »Imejte vero v Boga.',
        23: 'Kajti resnično, povem vam: ›Da kdorkoli bo rekel tej gori: ›Prestavi se in bodi vržena v morje‹ in v svojem srcu ne bo dvomil, temveč bo veroval, da se te besede, ki jih reče, pripetijo, bo imel, karkoli reče.‹',
        24: 'Zatorej vam pravim: ›Katerekoli stvari si želite, ko molite, verujte, da jih prejemate in imeli jih boste.',
        25: 'In ko vstanete k molitvi, odpustite, če imate kaj proti komu, da vam tudi vaš Oče, ki je v nebesih, lahko odpusti vaše prekrške.',
        26: '§ Toda če vi ne odpustite, tudi vaš Oče, ki je v nebesih, ne bo odpustil vaših prekrškov.‹«',
        27: 'In ponovno so prišli v Jeruzalem in ko je hodil po templju, so prišli k njemu visoki duhovniki in pisarji in starešine',
        28: 'ter mu rekli: »S kakšno oblastjo delaš te stvari? In kdo ti je dal to oblast, da delaš te stvari?«',
        29: 'Jezus je odgovoril in jim rekel: »Tudi jaz vas bom vprašal neko vprašanje in odgovorite mi in povedal vam bom, s kakšno oblastjo delam te stvari.',
        30: 'Janezov krst, ali je bil ta iz nebes ali od ljudi? Odgovorite mi.«',
        31: 'In med seboj so razpravljali, rekoč: »Če bomo rekli: ›Iz nebes,‹ bo rekel: ›Zakaj mu potem niste verovali?‹',
        32: 'Toda če bomo rekli: ›Od ljudi,‹ so se bali ljudstva, kajti vsi ljudje so šteli Janeza, da je bil zares prerok.«',
        33: 'In odgovorili so ter rekli Jezusu: »Ne moremo povedati.« Jezus pa jim odgovarja, rekoč: »Niti vam jaz ne povem, s kakšno oblastjo delam te stvari.«',
    },
    12: {
        1: 'In začel jim je govoriti s prispodobami. » Neki človek je zasadil vinograd in okoli njega postavil ograjo ter izkopal prostor za vinsko kad in zgradil stolp ter to prepustil poljedelcem in odšel v daljno deželo.',
        2: 'In ob primernem času je k poljedelcem poslal služabnika, da bi od poljedelcev lahko prejel sad od vinograda.',
        3: 'Oni pa so ga zgrabili in ga pretepli ter ga odgnali praznega.',
        4: 'In ponovno je poslal k njim drugega služabnika; in nanj so metali kamne in ga ranili na glavi ter ga spodili nespodobno obravnavanega.',
        5: 'In ponovno je poslal drugega; in so ga ubili in mnoge druge; nekatere so pretepli, druge pa ubili.',
        6: 'Imel je torej še enega sina, svojega srčno ljubljenega, tudi njega je zadnjega poslal k njim, rekoč: ›Mojega sina bodo spoštovali.‹',
        7: 'Toda tisti poljedelci so med seboj govorili: ›Ta je dedič; pridite, ubijmo ga in dediščina bo naša.‹',
        8: 'In vzeli so ga in ga ubili ter ga vrgli iz vinograda.',
        9: 'Kaj naj torej stori gospodar vinograda? Prišel bo in uničil poljedelce in vinograd dal drugim.',
        10: 'In ali niste brali tega pisma: »Kamen, ki so ga graditelji zavrnili, je postal glava vogalu;',
        11: 'to je bilo Gospodovo delo in to je čudovito v naših očeh?‹«',
        12: 'In prizadevali so si, da ga primejo, toda bali so se množice, kajti vedeli so, da je prispodobo govoril zoper njih; in pustili so ga ter odšli svojo pot.',
        13: 'In k njemu so poslali nekatere izmed farizejev in herodovcev, da ga ujamejo v njegovih besedah.',
        14: 'In ko so prišli, mu rečejo: »Učitelj, vemo, da si pošten in se ne oziraš na človeka, kajti ne oziraš se na zunanjost ljudi, temveč v resnici učiš Božjo pot: ›Ali je zakonito dajati cesarju davek ali ne?',
        15: 'Ali naj dajemo ali naj ne dajemo?‹« Ker pa je vedel za njihovo hinavščino, jim je rekel: »Kaj me skušate? Prinesite mi kovanec, da ga lahko pogledam.«',
        16: 'In prinesli so ga. On pa jim reče: »Čigava je ta podoba in napis?« In rekli so mu: »Cesarjeva.«',
        17: 'Jezus jim je odgovoril, rekoč: »Povrnite cesarju stvari, ki so cesarjeve, Bogu pa stvari, ki so Božje.« In so se mu čudili.',
        18: 'Potem so k njemu prišli saduceji, ki pravijo, da ni vstajenja; in vprašali so ga, rekoč:',
        19: '»Učitelj, Mojzes nam je zapisal: ›Če komu umre brat in za seboj zapusti svojo ženo, pa ne zapusti otrok, da naj njegov brat vzame njegovo ženo in svojemu bratu obudi seme.‹',
        20: 'Bilo je torej sedem bratov; in prvi je vzel ženo in umirajoč ni zapustil semena.',
        21: 'In vzel jo je drugi ter umrl [in] niti on ni zapustil semena in tretji prav tako.',
        22: 'In sedem jo je imelo, pa niso zapustili semena. Zadnja od vseh je umrla tudi ženska.',
        23: 'Ob vstajenju torej, ko bodo vstali, čigava žena bo od teh? Kajti sedem jo je imelo za ženo.«',
        24: 'Jezus jim je odgovoril, rekoč: »Ali se ne motite zato, ker ne poznate [ne] pisem niti Božje moči?',
        25: 'Kajti ko bodo vstali od mrtvih, se ne bodo niti poročali niti ne bodo dane v zakon; temveč so kakor angeli, ki so v nebesih.',
        26: 'In glede mrtvih, da bodo obujeni; kaj niste brali v Mojzesovi knjigi, kako mu je Bog govoril v grmu, rekoč: ›Jaz sem Bog Abrahamov in Bog Izakov in Bog Jakobov?‹',
        27: 'On ni Bog mrtvih, temveč Bog živih. Torej delate veliko napako.«',
        28: 'In prišel je eden izmed pisarjev in jih slišal skupaj razmišljati in ker je dojel, da jim je dobro odgovoril, ga je vprašal: »Katera je prva izmed vseh zapovedi?«',
        29: 'Jezus mu je odgovoril: »Prva izmed vseh zapovedi je: ›Poslušaj, oh Izrael: ›Gospod, naš Bog, je edini Gospod.',
        30: '§ In ljubil boš Gospoda, svojega Boga, z vsem svojim srcem in z vso svojo dušo in z vsem svojim mišljenjem in z vso svojo močjo;‹‹ to je prva zapoved.',
        31: 'Druga pa je podobna, namreč ta: ›Ljubi svojega bližnjega kakor samega sebe.‹ Nobena druga zapoved ni večja kakor ti [dve].«',
        32: 'In pisar mu je rekel: »Dobro, Učitelj, povedal si resnico, kajti samo en Bog je; in ni drugega razen njega.',
        33: '§ In ljubiti njega z vsem srcem in z vsem razumevanjem in z vso dušo in z vso močjo in ljubiti svojega bližnjega kakor samega sebe, je več kakor vse žgalne daritve in žrtvovanja.«',
        34: 'Ko je Jezus videl, da je razumno odgovoril, mu je rekel: »Nisi daleč od Božjega kraljestva.« In nató se mu nihče ni drznil zastaviti kakršnegakoli vprašanja.',
        35: 'In Jezus je, medtem ko je učil v templju, odgovoril in rekel: »Kako pravijo pisarji, da je Kristus Davidov Sin?',
        36: 'Kajti sam David je po Svetem Duhu rekel: › Gospod je rekel mojemu Gospodu: ›Sédi na mojo desnico, dokler ne naredim tvojih sovražnikov za tvojo pručko.‹‹',
        37: 'David mu torej sam reče Gospod in od kod je on potem njegov sin?« In preprosto ljudstvo ga je rade volje poslušalo.',
        38: 'In v svojem nauku jim je rekel: »Pazite se pisarjev, ki radi hodijo v dolgih oblačilih in imajo radi pozdrave na trgih',
        39: 'in vodilne sedeže v sinagogah in najpomembnejša mesta na praznovanjih,',
        40: 'ki vdovam požirajo hiše in za pretvezo delajo dolge molitve; ti bodo prejeli večjo obsodbo.«',
        41: 'In Jezus je sedel nasproti zakladnici in gledal, kako množica meče denar v zakladnico; in mnogi, ki so bili bogati, so veliko vrgli vanjo.',
        42: 'Prišla pa je neka siromašna vdova in vanjo vrgla dva kovanca, kar je en novčič.',
        43: 'K sebi je poklical svoje učence in jim reče: »Resnično, povem vam: ›Da je ta siromašna vdova vrgla vanjo več kakor vsi, ki so metali v zakladnico,',
        44: 'kajti vsi ti so metali od svojega obilja, toda ona je od svojega siromaštva vrgla vanjo vse, kar je imela, celó ves svoj dohodek.‹«',
    },
    13: {
        1: 'In ko je odšel iz templja, mu eden izmed njegovih učencev reče: »Učitelj, glej kakšne vrste kamnov in kakšne zgradbe so tukaj!«',
        2: 'In Jezus mu odgovori ter reče: »Te velike stavbe gledaš? Tam ne bo ostal en kamen na drugem, ki ne bi bil zrušen.«',
        3: 'In ko je sedèl na Oljski gori, nasproti templju, so ga Peter in Jakob in Janez ter Andrej na samem vprašali:',
        4: '»Povej nam, kdaj bodo te stvari? In kakšno bo znamenje, ko se bodo vse te besede dopolnile?«',
        5: 'In Jezus jim je odgovoril ter začel govoriti: »Pazite, da vas katerikoli človek ne prevara,',
        6: 'kajti mnogi bodo prišli v mojem imenu, rekoč: ›Jaz sem Kristus ‹ in bodo mnoge prevarali.',
        7: 'Ko pa boste slišali o vojnah in govorice o vojnah, ne bodite zaskrbljeni, kajti takšne stvari brezpogojno bodo, toda ne bo še konec.',
        8: 'Kajti narod se bo dvignil proti narodu in kraljestvo proti kraljestvu in potresi bodo na raznih krajih in lakote bodo ter nevšečnosti; te so začetek bridkosti.',
        9: 'Toda pazite se, kajti izročali vas bodo sodiščem in v sinagogah boste pretepeni in zaradi mene boste privedeni pred vladarje in kralje, v pričevanje proti njim.',
        10: 'Najprej pa se mora evangelij razglasiti med vsemi narodi.',
        11: 'Toda ko vas bodo vodili in izročali, ne premišljujte vnaprej kaj boste govorili niti ne delajte naklepov, temveč karkoli vam bo v tej uri dano, to govorite, kajti to niste vi, ki govorite, temveč Sveti Duh.',
        12: 'Brat bo torej brata izdajal v smrt in oče sina; in otroci bodo vstajali zoper svoje starše ter jim povzročali, da bodo usmrčeni.',
        13: 'In zaradi mojega imena boste osovraženi od vseh ljudi, toda kdor bo vztrajal do konca, ta isti bo rešen.',
        14: '§ Toda ko boste videli ogabnost opustošenja, o kateri govori prerok Daniel, stati, kjer ne bi smela, (naj tisti, ki bere, razume) takrat naj tisti, ki so v Judeji, bežijo v gore;',
        15: 'in naj tisti, ki je na hišni strehi, ne gre dol v hišo niti ne vstopi vanjo, da iz svoje hiše karkoli vzame;',
        16: 'in naj se tisti, ki je na polju, ne obrne ponovno nazaj, da vzame svojo obleko.',
        17: 'Toda gorje tem, ki so z otrokom in tem, ki v tistih dneh dojijo!',
        18: 'In molíte, da vaš pobeg ne bo pozimi.',
        19: 'Kajti v teh dneh bo stiska, kakršne ni bilo od začetka stvarstva, ki ga je Bog ustvaril, do tega časa niti je ne bo.',
        20: 'In razen če Gospod ne bi skrajšal teh dni, ne bi bilo rešeno nobeno meso, toda zaradi izvoljenih, ki jih je izbral, je dneve skrajšal.',
        21: "In če vam katerikoli človek tedaj reče: ›Glej! Tukaj je Kristus' ali: ›Glej, tam je,‹ mu ne verjemite.",
        22: 'Kajti vstali bodo lažni Kristusi in lažni preroki in prikazovali bodo znamenja in čudeže, da zapeljejo, če bi bilo mogoče, celó izvoljene.',
        23: 'Toda pazite se, glejte, napovedal sem vam vse stvari.',
        24: 'Toda v tistih dneh, po tisti stiski, bo sonce otemnelo in luna ne bo dajala svoje svetlobe',
        25: 'in zvezde neba bodo padale in moči, ki so na nebu, se bodo tresle.',
        26: 'In tedaj bodo videli Sina človekovega prihajati na oblakih z veliko močjo in slavo.',
        27: 'In potem bo poslal svoje angele in bo zbral skupaj svoje izvoljene iz štirih vetrov, od skrajnega dela zemlje do skrajnega dela neba.',
        28: 'Naučite se torej prispodobe o figovem drevesu: ›Kadar je njegova veja še mlada in poganja liste, veste, da je poletje blizu.‹',
        29: 'Tudi vi na podoben način, ko boste videli, da se te stvari dogajajo, védite, da je to blizu, celó pri vratih.',
        30: 'Resnično, povem vam, da ta rod ne bo prešel, dokler se vse te stvari ne zgodijo.',
        31: 'Nebo in zemlja bosta minila, toda moje besede ne bodo minile.',
        32: 'Toda za tisti dan in tisto uro ne ve nihče, niti angeli ne vedo, ki so na nebu, niti ne Sin, temveč Oče.',
        33: '§ Pazite se, bedite in molíte, kajti ne veste, kdaj je čas.',
        34: 'Kajti Sin človekov je kakor človek, ki je šel na dolgo pot, ki je zapustil svojo hišo in svojim služabnikom dal oblast in vsakemu človeku svoje delo, vratarju pa je naročil, naj bedi.',
        35: 'Čujte torej, kajti ne veste, kdaj prihaja hišni gospodar, zvečer ali opolnoči ali ob petelinjem petju ali zjutraj,',
        36: 'da vas ob nenadnem prihodu ne najde spečih.',
        37: 'In kar pravim vam, pravim vsem: ›Čujte.‹«',
    },
    14: {
        1: 'Dva dni kasneje je bil praznik pashe in nekvašenega kruha. In visoki duhovniki in pisarji so si prizadevali, kako bi ga lahko s prebrisanostjo prijeli in ga usmrtili.',
        2: 'Vendar so rekli: »Ne na prazničen dan, da ne bi bilo vstaje med ljudmi.«',
        3: 'In ko je bil v Betaniji, v hiši Simona gobavca, medtem ko je sedel pri obedu, je prišla ženska, ki je imela alabastrno škatlo zelo dragocenega mazila iz narde; in strla škatlo ter jo izlila na njegovo glavo.',
        4: 'In tam so bili nekateri, ki so imeli v sebi ogorčenje in rekli: »Čemu je bila narejena ta potrata mazila?',
        5: 'Kajti lahko bi bilo prodano za več kakor tristo denarjev in dano revnim.« In godrnjali so zoper njo.',
        6: 'Jezus pa je rekel: »Pustite jo pri miru. Zakaj jo nadlegujete? Na meni je storila dobro delo.',
        7: 'Kajti uboge imate vedno med seboj in kadarkoli želite, jim lahko storite dobro, toda mene nimate vedno.',
        8: 'Naredila je, kar je lahko; prišla je vnaprej, da moje telo mazili za pokop.',
        9: 'Resnično, povem vam: ›Kjerkoli se bo ta evangelij oznanjal po vsem svetu, se bo tudi to, kar je ona storila, govorilo njej v spomin.‹«',
        10: 'Juda Iškarijot, eden izmed dvanajsterih, pa je odšel k visokim duhovnikom, da bi jim ga izdal.',
        11: 'Ko so oni to slišali, so bili veseli in so mu obljubili, da mu dajo denar. In iskal je, kako bi ga lahko ob priložnosti izdal.',
        12: 'In prvi dan nekvašenega kruha, ko so zaklali pashalno jagnje, so mu njegovi učenci rekli: »Kam hočeš, da gremo in pripravimo, da boš lahko jedel pashalno jagnje?«',
        13: 'In pošlje dva izmed svojih učencev ter jima reče: »Pojdita v mesto in tam vaju bo srečal mož, ki nese lončen vrč vode. Sledita mu.',
        14: 'In kjerkoli bo vstopil, recita hišnemu očetu: ›Učitelj pravi: ›Kje je soba za goste, kjer bom s svojimi učenci jedel pashalno jagnje?‹‹',
        15: 'In pokazal vama bo veliko zgornjo sobo, opremljeno in pripravljeno; tam pripravita za nas.«',
        16: 'In njegova učenca sta odšla naprej ter prišla v mesto in našla, kakor jima je rekel; in pripravila sta pashalno jagnje.',
        17: 'In zvečer je prišel z dvanajsterimi.',
        18: 'In ko so se usedli ter jedli, je Jezus rekel: »Resnično, povem vam: ›Eden izmed vas, ki jé z menoj, me bo izdal.‹«',
        19: '§ Postajali pa so žalostni in mu drug za drugim govorili: ›Ali sem jaz?‹ in drugi je rekel: ›Ali sem jaz?‹',
        20: 'Odgovoril je in jim rekel: »Eden izmed dvanajsterih je, ki z menoj pomaka v skledo.',
        21: 'Sin človekov zares gre, kakor je pisano o njem, toda gorje tistemu človeku, po katerem je bil Sin človekov izdan! Dobro bi bilo za tega človeka, če se nikoli ne bi rodil.«',
        22: '§ In ko so pojedli, je Jezus vzel kruh in blagoslovil in ga razlomil in jim dal ter rekel: »Vzemite, jejte, to je moje telo.«',
        23: 'In vzel je čašo in ko se je zahvalil, jim jo je dal in vsi so pili iz nje.',
        24: '§ In rekel jim je: »To je moja kri nove zaveze, ki se preliva za mnoge.',
        25: 'Resnično, povem vam: ›Nič več ne bom pil od sadu vinske trte do tistega dne, ko bom pil novega v Božjem kraljestvu.‹«',
        26: 'In ko so odpeli hvalnico, so odšli ven na Oljsko goro.',
        27: '§ In Jezus jim reče: »Vsi se boste to noč pohujšali zaradi mene, kajti pisano je: ›Udaril bom pastirja in ovce se bodo razkropile.‹',
        28: 'Toda potem, ko bom obujen, bom pred vami šel v Galilejo.«',
        29: 'Toda Peter mu je rekel: »Četudi se bodo vsi pohujšali, se vendarle jaz ne bom.«',
        30: 'Jezus pa mu reče: »Resnično, povem ti: ›Da me boš ta dan, celó v tej noči, preden petelin dvakrat zapoje, trikrat zatajil.‹«',
        31: 'Toda on je še bolj silovito govoril: »Če naj bi umrl s teboj, te na noben način ne bom zatajil.« Prav tako so govorili tudi vsi drugi.',
        32: 'In prišli so na kraj, ki je bil imenovan Getsemani. In svojim učencem reče: »Sedíte tukaj, dokler bom molil.«',
        33: 'In s seboj vzame Petra in Jakoba in Janeza in postajal je boleče prepaden in zelo potrt',
        34: 'in jim reče: »Moja duša je silno žalostna do smrti. Zadržujte se tukaj in bedite.«',
        35: 'In odšel je malce naprej ter padel na tla in molil, če bi bilo mogoče, da gre ta ura mimo njega.',
        36: 'In rekel je: »Aba, Oče, tebi so vse stvari mogoče. To čašo odvzemi od mene, vendar ne kar jaz hočem, temveč kar ti hočeš.«',
        37: 'In pride ter jih najde speče in reče Petru: »Simon, spiš? Nisi mogel eno uro bedeti?',
        38: 'Bedite in molíte, da ne bi vstopili v skušnjavo. Duh je resnično voljan, toda meso je šibko.«',
        39: 'In ponovno je odšel proč ter molil in govoril iste besede.',
        40: 'In ko se je vrnil, jih je ponovno našel speče (kajti njihove oči so bile težke) niti niso vedeli, kaj naj mu odgovorijo.',
        41: 'In pride tretjič ter jim reče: »Spite torej in vzemite si svoj počitek; dovolj je, ura je prišla; glejte, Sin človekov je izdan v roke grešnikov.',
        42: 'Vstanite, pojdimo; glejte, tisti, ki me izdaja, je blizu.«',
        43: 'Medtem pa, ko je še govoril, takoj pride Juda, eden izmed dvanajsterih in z njim velika množica z meči in palicami od vélikih duhovnikov in pisarjev in starešin.',
        44: 'In tisti, ki ga je izdal, jim je dal znak, rekoč: »Kogarkoli bom poljubil, ta isti je on; primite ga in ga varno odvedite proč.«',
        45: '§ In brž, ko je prišel, je nemudoma šel k njemu in reče: »Učitelj, učitelj;« in ga poljubil.',
        46: 'Oni pa so svoje roke položili nanj ter ga prijeli.',
        47: 'Eden izmed tistih, ki je stal poleg, pa je izvlekel meč in udaril služabnika vélikega duhovnika ter mu odsekal uho.',
        48: 'In Jezus je odgovoril ter jim rekel: »Ali ste prišli ven, da me primete kakor zoper tatu, z meči in s palicami?',
        49: 'Dnevno sem bil z vami v templju in poučeval, pa me niste prijeli, toda pisma morajo biti izpolnjena.«',
        50: 'In vsi so ga zapustili ter pobegnili.',
        51: 'Sledil pa mu je nek mladenič, ki je imel okoli svojega nagega telesa ogrnjeno laneno oblačilo; in mladeniča so zgrabili,',
        52: 'ta pa je pustil laneno oblačilo in nag pobegnil od njih.',
        53: 'In Jezusa so odvedli k vélikemu duhovniku; in z njim so bili zbrani vsi visoki duhovniki in starešine in pisarji.',
        54: 'In Peter mu je sledil od daleč, celó v palačo vélikega duhovnika; in sedèl je s služabniki ter se grel pri ognju.',
        55: 'In visoki duhovniki in ves véliki zbor so iskali pričevanje zoper Jezusa, da ga usmrté, pa niso našli nobenega.',
        56: 'Kajti mnogo jih je krivo pričalo proti njemu, toda njihova pričevanja se niso ujemala.',
        57: 'In tam so vstali nekateri in krivo pričali proti njemu, rekoč:',
        58: '»Slišali smo ga reči: ›Uničil bom ta tempelj, ki je narejen z rokami in v treh dneh bom zgradil novega, narejenega brez rok.‹«',
        59: 'Toda niti tako se njihova pričevanja niso ujemala.',
        60: 'Véliki duhovnik pa je vstal, [stopil] v sredo in vprašal Jezusa, rekoč: »Nič ne odgovarjaš? Kaj je to, kar ti pričajo zoper tebe?«',
        61: 'Vendar je ohranil svoj mir in ni nič odgovoril. Véliki duhovnik ga je ponovno vprašal in mu rekel: »Ali si ti Kristus, Sin Blagoslovljenega?«',
        62: 'In Jezus je rekel: »Jaz sem, in videli boste Sina človekovega sedeti na desnici moči in prihajati na oblakih neba.«',
        63: 'Tedaj je véliki duhovnik raztrgal svoja oblačila in reče: »Kaj nam je treba nadaljnjih prič?',
        64: 'Slišali ste bogokletje, kaj mislite?« In vsi so ga obsodili, da je kriv smrti.',
        65: 'Nekateri pa so začeli pljuvati nanj in zakrivati njegov obraz ter ga klofutati in mu govoriti: »Prerokuj.« Služabniki pa so ga udarjali z dlanmi svojih rok.',
        66: 'In ko je bil Peter spodaj v palači, pride ena izmed služabnic vélikega duhovnika.',
        67: 'In ko je videla Petra, kako se greje, ga je pogledala in rekla: »In tudi ti si bil z Jezusom Nazarečanom.«',
        68: 'Vendar je zanikal, rekoč: »Ne vem niti ne razumem kaj praviš.« In odšel je ven v preddverje, petelin pa je zakikirikal.',
        69: 'In služkinja ga je ponovno videla in začela govoriti tem, ki so stali poleg: »Ta je eden izmed njih.«',
        70: '§ On pa je ponovno zanikal. In malce kasneje so tisti, ki so stali poleg, ponovno rekli Petru: »Zagotovo si eden izmed njih, kajti Galilejec si in tvoje narečje se ujema k temu.«',
        71: 'Vendar je začel preklinjati in prisegati, rekoč: »Ne poznam tega človeka, o katerem govorite.«',
        72: 'In petelin je drugič zapel. Peter pa se je spomnil besede, ki mu jo je rekel Jezus: »Preden bo petelin dvakrat zapel, me boš trikrat zatajil.« Ko pa je o tem premišljeval, je zajokal.',
    },
    15: {
        1: 'In takoj zjutraj so imeli visoki duhovniki posvet s starešinami in pisarji ter celotnim vélikim zborom in zvezali Jezusa in ga odvedli proč ter ga izročili Pilatu.',
        2: 'In Pilat ga je vprašal: »Ali si ti Kralj Judov?« In odgovoril je ter mu rekel: »Ti praviš to.«',
        3: 'In visoki duhovniki so ga obtožili mnogih stvari. Toda nič ni odgovoril.',
        4: 'In Pilat ga je ponovno vprašal, rekoč: »Nič ne odgovarjaš? Glej, koliko stvari pričujejo zoper tebe.«',
        5: 'Vendar Jezus še vedno ni nič odgovoril, tako da se je Pilat čudil.',
        6: 'Torej na ta praznik jim je izpustil enega jetnika, kateregakoli so želeli.',
        7: 'Tam pa je bil nekdo, imenovan Baraba, ki je ležal zvezan s temi, ki so z njim storili upor in ki je v uporu zagrešil umor.',
        8: 'In množica je na glas kričala in začela zahtevati, da stori, kakor jim je vedno storil.',
        9: 'Toda Pilat jim je odgovoril, rekoč: »Hočete, da vam izpustim Kralja Judov?«',
        10: 'Kajti vedel je, da so mu ga visoki duhovniki izročili iz zavisti.',
        11: 'Toda visoki duhovniki so napeljali množico, da naj jim raje izpusti Baraba.',
        12: 'Pilat pa je odgovoril in jim ponovno rekel: »Kaj potem hočete, da naj storim tistemu, ki ga imenujete Kralj Judov?«',
        13: 'In ponovno so zavpili: »Križaj ga.«',
        14: 'Potem jim je Pilat rekel: »Zakaj, kakšno zlo je storil?« Oni pa so še bolj silno vpili: »Križaj ga.«',
        15: 'In tako jim je Pilat, voljan ustreči množici, izpustil Baraba in ko je prebičal Jezusa, ga je izročil, da bi bil križan.',
        16: 'In vojaki so ga odvedli proč v dvorano, imenovano Praetorium in sklicali vso četo.',
        17: 'In oblekli so ga s škrlatom in spletli krono iz trnja ter jo nadeli na njegovo glavo',
        18: 'in ga začeli pozdravljati: »Pozdravljen, Kralj Judov!«',
        19: 'In s trstom so ga udarjali po glavi in pljuvali nanj in ko so upogibali svoja kolena, so ga oboževali.',
        20: 'In ko so ga zasmehovali, so z njega sneli škrlat in nanj nadeli njegova lastna oblačila ter ga odvedli ven, da ga križajo.',
        21: 'Prisilili pa so nekega Simona Cirenca, Aleksandrovega in Rufovega očeta, ki je šel mimo in prihajal iz dežele, da nese njegov križ.',
        22: 'In privedli so ga na kraj Golgota, kar je prevedeno: ›Kraj lobanje.‹',
        23: 'In dali so mu za piti vina, pomešanega z miro, toda ni ga sprejel.',
        24: 'In ko so ga križali, so razdelili njegove obleke in zanje metali žreb, kaj naj bi vsak mož vzel.',
        25: 'In bila je tretja ura, oni pa so ga križali.',
        26: 'In napis njegove obtožbe je bil napisan nad njim: KRALJ JUDOV.',
        27: 'In z njim so križali dva tatova; enega na njegovi desni roki, drugega pa na njegovi levi.',
        28: '§ In pismo je bilo izpolnjeno, ki pravi: »In bil je prištet skupaj s prestopniki.«',
        29: 'Tisti pa, ki so hodili mimo, so se mu posmehovali in zmajevali s svojimi glavami ter govorili: »Ah, ti, ki uničiš tempelj in ga v treh dneh zgradiš,',
        30: 'reši samega sebe in pridi dol s križa.«',
        31: 'Podobno so ga zasmehovali tudi visoki duhovniki in s pisarji med seboj govorili: »Druge je rešil; sebe ne more rešiti.',
        32: 'Naj se Kristus, Izraelov Kralj, torej spusti s križa, da bomo lahko videli in verovali.« Ta dva, ki sta bila križana z njim, pa sta ga zasramovala.',
        33: 'In ko je prišla šesta ura, je bila tema čez vso deželo do devete ure.',
        34: 'Ob deveti uri pa je Jezus z močnim glasom zavpil, rekoč: »Eloí, Eloí, lemá sabahtáni?« kar je prevedeno: »Moj Bog, moj Bog, zakaj si me zapustil?«',
        35: 'Nekateri izmed teh, ki so stali poleg, pa so, ko so to slišali, rekli: »Glejte, Elija kliče.«',
        36: 'In nekdo je stekel ter celotno gobo napojil s kisom in jo nataknil na trst in mu dal piti, rekoč: »Pustite pri miru; poglejmo, ali bo prišel Elija, da ga sname dol.«',
        37: 'In Jezus je z močnim glasom zavpil in izročil duha.',
        38: 'In tempeljsko zagrinjalo se je raztrgalo na dvoje od vrha do tal.',
        39: 'Ko je stotnik, ki je stal poleg, njemu nasproti, videl, da je tako zavpil in izročil duha, je rekel: »Resnično, ta človek je bil Božji Sin.«',
        40: 'Tam so bile tudi ženske, ki so gledale od daleč; med katerimi je bila Marija Magdalena in Marija, mater Jakoba mlajšega in od Jozéja in Salóma',
        41: '(ki so mu, ko je bil v Galileji, tudi sledile in mu služile) in mnoge druge ženske, ki so z njim prišle gor v Jeruzalem.',
        42: 'In sedaj, ko je prišel večer, ker je bila priprava, to je dan pred šabat,',
        43: 'je Jožef iz Arimateje, častitljiv svetovalec, ki je prav tako pričakoval Božje kraljestvo, prišel in pogumno stopil k Pilatu ter prosil za Jezusovo telo.',
        44: 'In Pilat se je začudil, da je bil že mrtev; in ko je k sebi poklical stotnika, ga je vprašal ali je bil že nekaj časa mrtev.',
        45: 'In ko je od stotnika to izvedel, je telo poklonil Jožefu.',
        46: 'In ta je kupil tanko laneno platno in ga snel ter zavil v laneno platno in ga položil v mavzolej, ki je bil izklesan iz skale in k vratom mavzoleja zavalil kamen.',
        47: 'Marija Magdalena in Marija, Jozéjeva mati, pa sta opazovali, kam je bil položen.',
    },
    16: {
        1: 'Ko je šabat minil, so Marija Magdalena in Marija, Jakobova mati in Salóma kupile prijetne dišave, da bi lahko prišle ter ga pomazilile.',
        2: 'In zelo zgodaj zjutraj, prvega dne v tednu, so ob sončnem vzhodu prišle k mavzoleju.',
        3: 'In med seboj so govorile: »Kdo nam bo odvalil kamen proč izpred vrat mavzoleja?«',
        4: 'Ko pa so pogledale, so videle, da je bil kamen odvaljen proč, kajti bil je zelo velik.',
        5: 'In vstopajoč v mavzolej, so zagledale mladeniča, ki je sedel na desni strani, oblečenega v dolgo belo obleko; in bile so zgrožene.',
        6: 'On pa jim reče: »Ne bodite zgrožene. Ve iščete Jezusa Nazarečana, ki je bil križan. Obujen je, ni ga tukaj. Poglejte prostor, kamor so ga položili.',
        7: 'Toda pojdite svojo pot, povejte njegovim učencem in Petru, da gre pred vami v Galilejo; tam ga boste videli, kakor vam je rekel.«',
        8: 'In hitro so odšle ven in pobegnile od mavzoleja, kajti trepetale so in bile osuple niti niso ničesar povedale nobenemu človeku, kajti bile so prestrašene.',
        9: 'Ko je torej Jezus zgodaj prvega dne v tednu vstal, se je najprej prikazal Mariji Magdaleni, iz katere je izgnal sedem hudičev.',
        10: 'In odšla je ter povedala tem, ki so bili z njim, ki so žalovali in jokali.',
        11: 'In ko so slišali, da je bil živ in da ga je videla, niso verovali.',
        12: 'Nató se je v drugi obliki prikazal dvema izmed njih, ki sta hodila in šla na deželo.',
        13: 'In odšla sta ter to povedala preostalim. Niti njima niso verovali.',
        14: 'Potem se je prikazal enajsterim, ko so sedeli pri obedu in jih oštel zaradi njihove nevere in trdote srca, ker niso verjeli tem, ki so ga videli potem, ko je bil obujen.',
        15: 'In rekel jim je: »Pojdite po vsem svetu in oznanite evangelij vsakemu ustvarjenemu bitju.',
        16: 'Kdor veruje in je krščen, bo rešen; toda kdor ne veruje, bo obsojen.',
        17: 'In ta znamenja bodo spremljala tiste, ki verujejo: ›V mojem imenu bodo izganjali hudiče, govorili bodo z novimi jeziki,',
        18: 'dvigali bodo kače in če popijejo kakršnokoli smrtonosno stvar, jim ta ne bo škodila; polagali bodo roke na bolne in ti bodo ozdraveli.‹«',
        19: 'Tako je bil potem, ko jim je Gospod govoril, sprejet gor v nebo in je sédel na Božjo desnico.',
        20: 'Oni pa so šli naprej ter povsod oznanjali in Gospod je delal z njimi in besedo potrjeval s spremljajočimi znamenji. Amen.',
    },
}
