NAME = 'FrePGR: Bible Perret-Gentil et Rilliet'
BOOK = 'Zechariah'

CHAPTERS = {
    1: {
        1: "Le huitième mois, la seconde année de Darius, la parole de l'Éternel fut adressée à Zacharie, fils de Barachie, fils de Iddo, le prophète, en ces mots:",
        2: "L'Éternel a été irrité, irrité contre vos pères.",
        3: "Dis-leur donc: Ainsi parle l'Éternel des armées: Revenez à moi, dit l'Éternel des armées, et je reviendrai à vous, dit l'Éternel des armées.",
        4: "Ne soyez pas comme vos pères à qui les premiers prophètes criaient et disaient: « Ainsi parle l'Éternel des armées: Quittez donc vos voies mauvaises et vos mauvaises œuvres! » mais ils n'écoutèrent point et ne tinrent nul compte de moi, dit l'Éternel.",
        5: 'Vos pères, où sont-ils? et les prophètes vivent-ils éternellement?',
        6: "Cependant mes paroles et mes décrets dont j'avais chargé mes serviteurs, les prophètes, n'ont-ils pas atteint vos pères? Et ils se convertirent et dirent: Comme l'Éternel des armées avait résolu de nous traiter selon nos voies et nos œuvres, ainsi nous a-t-Il traités.",
        7: "Le vingt-quatrième jour du onzième mois (c'est le mois de Sébat), la seconde année de Darius, la parole de l'Éternel fut adressée à Zacharie, fils de Barachie, fils de Iddo, le prophète, en ces mots:",
        8: "J'eus une vision pendant la nuit, et voici, c'était un homme monté sur un cheval rouge, et il se tenait parmi les myrtes qui étaient dans un fond, et derrière lui étaient des chevaux rouges, fauves et blancs.",
        9: "Et je dis: Qui sont-ils, mon Seigneur? Et l'ange qui parlait avec moi, me dit: Je te ferai voir qui ils sont.",
        10: "Et l'homme qui se tenait parmi les myrtes, prit la parole et dit: Ce sont ceux que l'Éternel a envoyés parcourir la terre.",
        11: "Et ils répondirent à l'ange de l'Éternel qui se tenait parmi les myrtes, et dirent: Nous avons parcouru la terre, et voici, toute la terre est calme et tranquille.",
        12: "Et l'ange de l'Éternel répondit et dit: Éternel des armées, jusques à quand seras-tu sans pitié pour Jérusalem et les villes de Juda contre lesquelles tu fus irrité ces soixante-dix ans?",
        13: "Et l'Éternel répondit à l'ange qui parlait avec moi, des paroles de bonté, des paroles de consolation.",
        14: "Et l'ange qui parlait avec moi, me dit: Proclame ces paroles: Ainsi parle l'Éternel des armées: J'ai pour Jérusalem et Sion une vive passion;",
        15: "aussi suis-je ému d'un grand courroux contre les nations [maintenant] en sécurité: quand j'étais un peu irrité [contre Juda], elles contribuèrent à son malheur.",
        16: "Aussi ainsi parle l'Éternel: Je reviens à Jérusalem avec des miséricordes; ma maison y sera bâtie, dit l'Éternel des armées, et le cordeau sera tendu sur Jérusalem.",
        17: "Proclame encore ces paroles: Ainsi parle l'Éternel des armées: Mes villes regorgeront encore de biens et l'Éternel consolera encore Sion et fera encore choix de Jérusalem.",
        18: 'Et je levai les yeux et regardai, et voici quatre cornes.',
        19: "Et je dis à l'ange qui parlait avec moi: Qu'est-ce? Et il me dit: Ce sont les cornes qui ont dispersé Juda, Israël et Jérusalem.",
        20: "Et l'Éternel me fit voir quatre forgerons.",
        21: 'Et je dis: Que viennent-ils faire? Et Il dit: Ce sont les cornes qui ont dispersé Juda de telle sorte que nul homme ne releva la tête; et ceux-ci viennent pour les épouvanter, pour abattre les cornes des nations qui ont levé la corne contre le pays de Juda pour le disperser.',
    },
    2: {
        1: 'Et je levai les yeux et regardai, et voici un homme ayant dans sa main un cordeau à mesurer.',
        2: 'Et je dis: Où vas-tu? Et il me dit: Prendre la mesure de Jérusalem, voir quelle en sera la largeur, et quelle en sera la longueur.',
        3: "Et voici, l'ange qui parlait avec moi s'avança, et un autre ange s'avança au-devant de lui.",
        4: "Et il dit à celui-ci: Cours! et parle ainsi à ce jeune homme-là: Jérusalem sera habitée comme ville ouverte, tant il y aura d'hommes et de bestiaux en son sein;",
        5: "et moi je serai pour elle, dit l'Éternel, un mur de feu qui l'entoure, et je serai une gloire au milieu d'elle.",
        6: "Sus! sus! fuyez du pays du nord, dit l'Éternel, car je vous ai disséminés aux quatre vents des Cieux, dit l'Éternel.",
        7: 'Sus, ô Sion! sauve-toi, toi qui habites chez la fille de Babel!',
        8: "Car ainsi parle l'Éternel des armées: C'est après la gloire qu'il m'a envoyé chez les peuples qui vous ont dépouillés (car qui vous touche, touche à la prunelle de son œil).",
        9: "En effet voici, je brandis ma main sur eux et ils seront la proie de ceux qui leur furent asservis, et vous saurez que l'Éternel des armées m'a envoyé.",
        10: "Sois dans la joie et l'allégresse, fille de Sion! car voici, je viens et j'habiterai dans ton sein, dit l'Éternel.",
        11: "Et beaucoup de peuples s'attacheront à l'Éternel en ce jour-là, et deviendront mon peuple, et j'habiterai dans ton sein et tu sauras que l'Éternel des armées m'a envoyé auprès de toi.",
        12: "Et l'Éternel possédera Juda comme son lot dans la terre sainte, et fera encore choix de Jérusalem.",
        13: "Silence, vous tous qui êtes chair, en présence de l'Éternel! car II se lève de sa demeure sainte.",
    },
    3: {
        1: "Et Il me fit voir Josué, le grand sacrificateur, debout devant l'ange de l'Éternel, et Satan debout à sa droite pour l'attaquer.",
        2: "Et l'Éternel dit à Satan: Que l'Éternel te tance, Satan, que l'Éternel te tance, lui qui a choisi Jérusalem! Celui-ci n'est-il pas un tison sauvé du feu?",
        3: "Et Josué était vêtu d'habits sales, et se tenait debout devant l'ange;",
        4: 'lequel prit la parole et dit à ceux qui étaient debout devant lui: Otez-lui ses habits sales! et lui dit: Voici! je te décharge de ton crime, et te revêts de superbes habits.',
        5: "Et je dis: Qu'on pose une tiare pure sur sa tête! Et ils posèrent une tiare pure sur sa tête et lui mirent des habits. Et l'ange de l'Éternel y présidait.",
        6: "Et l'ange de l'Éternel lit à Josué cette déclaration solennelle:",
        7: "Ainsi parle l'Éternel des armées: Si tu suis mes voies et observes mes ordonnances, tu jugeras aussi ma maison, et garderas mes parvis, et je te donnerai des guides parmi ceux qui sont ici présents.",
        8: 'Écoute donc, Josué, grand sacrificateur, toi et tes collègues siégeant devant toi! (Car ce sont des hommes figuratifs; car, voici, je fais arriver mon serviteur, le Germe.)',
        9: "Car, voici, la pierre que j'ai placée devant Josué, sur cette seule pierre sept yeux sont fixés et j'en graverai les traits, dit l'Éternel des armées, et j'enlèverai le crime de ce pays en un jour.",
        10: "En ce jour-là, dit l'Éternel des armées, vous vous crierez l'un à l'autre: Sous la vigne et sous le figuier!",
    },
    4: {
        1: "Et l'ange qui parlait avec moi revint, et me réveilla comme un homme que l'on réveille de son sommeil.",
        2: "Et il me dit: Que vois- tu? Et je dis: Je vois! et voici un chandelier tout d'or, ayant son réservoir à son sommet et portant sept lampes, et sept tuyaux pour chacune des lampes qui sont à son sommet;",
        3: 'et auprès, deux oliviers, un à droite du réservoir et un à sa gauche.',
        4: "Et je pris la parole et dis à l'ange qui parlait avec moi: Qu'est-ce que cela, mon Seigneur?",
        5: "Et l'ange qui parlait avec moi, répondit et me dit: Ne sais-tu pas ce que c'est? Et je dis: Non! mon Seigneur.",
        6: "Et il répondit et me dit: C'est ici la parole de l'Éternel adressée à Zorobabel: Ni par la force, ni par la puissance, mais par mon Esprit, dit l'Éternel des armées.",
        7: 'Qui es-tu, grosse montagne? Devant Zorobabel aplanis-toi! Il fait saillir la pierre du faîte aux cris de: La grâce! la grâce pour elle!',
        8: "Et la parole de l'Éternel me fut adressée en ces termes:",
        9: "Les mains de Zorobabel ont fondé cette maison, et ses mains l'achèveront, et tu sauras que l'Éternel des armées m'a envoyé à vous.",
        10: "Car qui pourrait mépriser le jour des faibles commencements? Avec joie ils contempleront le plomb dans la main de Zorobabel, ces sept, les yeux de l'Éternel qui parcourent toute la terre.",
        11: 'Et je répondis et lui dis: Que sont ces deux oliviers à la droite du chandelier et à sa gauche?',
        12: "Et reprenant une seconde fois la parole je lui dis: Que sont ces deux rameaux d'olivier qui touchent aux deux conduits d'or d'où découle la liqueur dorée.",
        13: "Et il me dit: Ne sais-tu pas ce que c'est? Et je dis: Non! mon Seigneur.",
        14: 'Et il dit: Ce sont les deux oints qui se tiennent debout auprès du Seigneur de toute la terre.',
    },
    5: {
        1: 'Et de nouveau je levai les yeux et regardai, et voici un volume qui volait.',
        2: 'Et il me dit: Que vois-tu? Et je dis: Je vois un volume qui vole; sa longueur est de vingt coudées, et sa largeur de dix coudées.',
        3: "Et il me dit: C'est la malédiction qui se promène sur tout le pays, et ensuite de laquelle, d'une part, tout voleur sera exterminé, et d'autre part, tout parjure sera exterminé.",
        4: "Je l'ai lancée, dit l'Éternel des armées, afin qu'elle entre dans la maison du voleur, et dans la maison de qui fait par mon nom de faux serments, qu'elle séjourne dans sa maison et la détruise toute, et son bois et ses pierres.",
        5: "Et l'ange qui parlait avec moi, parut et me dit: Lève donc les yeux et regarde! qu'est-ce qui sort là? Et je dis: Qu'est-ce?",
        6: "Et il dit: C'est l'épha sortant. Et il dit: C'est à cela qu'ils visent dans tout le pays.",
        7: "Et voici, une masse de plomb fut soulevée, et il y avait dans l'épha une femme assise.",
        8: "Et il dit: C'est l'Impiété. Et il la repoussa au dedans de l'épha dont il referma l'ouverture avec la masse de plomb.",
        9: "Et je levai les yeux et regardai, et voici, deux femmes parurent: le vent était dans leurs ailes, et elles avaient des ailes comme des ailes de cigogne, et elles enlevèrent l'épha entre la terre et le ciel.",
        10: "Et je dis à l'ange qui parlait avec moi: Où emportent-elles l'épha?",
        11: 'Et il me dit: Elles vont lui établir une demeure dans le pays de Sinear, et une fois consolidée, il y sera posé sur son piédestal.',
    },
    6: {
        1: "Et de nouveau je levai les yeux et je regardai, et voici quatre chars qui partaient d'entre deux montagnes, et les montagnes étaient des montagnes d'airain.",
        2: 'Au premier char étaient des chevaux rouges, et au second char des chevaux noirs,',
        3: 'et au troisième char des chevaux blancs, et au quatrième char des chevaux tachetés, vigoureux.',
        4: "Et je pris la parole et dis à l'ange qui parlait avec moi:",
        5: "Qu'est-ce, mon Seigneur? Et l'ange répondit et me dit: Ce sont les quatre vents des Cieux qui sortent après avoir pris les ordres du Seigneur de toute la terre.",
        6: "Les chevaux noirs attelés à l'un partirent pour le pays du nord, et les blancs partirent après eux, et les tachetés partirent pour le pays du midi.",
        7: 'Et les rouges partirent et demandèrent à parcourir la terre. Et il dit: Allez, parcourez la terre! Et ils parcoururent la terre.',
        8: "Et il m'interpella et me parla en disant: Vois, ceux qui partent pour le pays du nord, font reposer ma colère sur le pays du nord.",
        9: "Et la parole de l'Éternel me fut adressée en ces mots:",
        10: 'Accepte de la part des captifs, Heldaï, Tobie et Jédaïa (et en ce même jour va, va dans la maison de Josias, fils de Sophonie, où ils sont descendus en arrivant de Babel)',
        11: "accepte, [dis-je], de l'argent et de l'or et en fais des couronnes, et pose-les sur la tête de Josué, fils de Jéhotsadak, grand sacrificateur,",
        12: "et dis-lui: Ainsi parle l'Éternel des armées: Voici, un homme dont le nom est Germe et qui croîtra sur son lieu même, bâtira le temple de l'Éternel.",
        13: "Et c'est lui qui bâtira le temple de l'Éternel, et il portera les insignes de la majesté et siégera, et exercera la royauté sur son trône et la sacrificature sur son trône, et le conseil de la paix sera entre elles deux.",
        14: "Et les couronnes seront pour Hélem et pour Tobie, et pour Jédaïa, et pour Hen fils de Sophonie, un mémorial dans le temple de l'Éternel.",
        15: "Et des [peuples] lointains viendront et travailleront au temple de l'Éternel, et vous saurez que l'Éternel des armées m'a envoyé à vous. Et cela arrivera, si vous écoutez la voix de l'Éternel, votre Dieu.",
    },
    7: {
        1: "Et la quatrième année du roi Darius, la parole de l'Éternel fut adressée à Zacharie, le quatrième jour du neuvième mois, celui de Cisleu.",
        2: "Et la maison de Dieu envoya Scharetser et Régem-Mélech et leurs gens pour implorer l'Éternel,",
        3: "et dire aux sacrificateurs de la maison de l'Éternel des armées et aux prophètes: « Continuerai-je à prendre le deuil au cinquième mois, avec abstinence, ainsi que je le fais depuis combien d'années? »",
        4: "Et la parole de l'Éternel des armées me fut adressée en ces mots:",
        5: 'Dis à tout le peuple du pays et aux sacrificateurs: Quand vous avez jeûné et pris le deuil au cinquième et au septième mois, et cela pendant ces soixante-dix ans, est-ce pour moi que vous avez jeûné?',
        6: "Et quand vous mangez et buvez, n'est-ce pas vous qui mangez, et vous qui buvez?",
        7: "N'avez-vous pas les paroles que proclama l'Éternel par les premiers prophètes, quand Jérusalem était habitée et tranquille avec les villes de ses alentours, et que le midi et le bas pays étaient habités?",
        8: "Et la parole de l'Éternel fut adressée à Zacharie en ces mots: Ainsi a dit l'Éternel des armées:",
        9: "Rendez la justice en vérité, et traitez-vous l'un l'autre avec bonté et miséricorde;",
        10: "et n'opprimez ni la veuve, ni l'orphelin, ni l'étranger, ni le pauvre, et ne pensez pas à mal l'un contre l'autre dans vos cœurs.",
        11: "Mais ils refusèrent d'être attentifs, et opposèrent une épaule rénitente, et se bouchèrent les oreilles pour ne point entendre;",
        12: "et ils endurcirent leurs cœurs comme le diamant, pour ne pas entendre la loi et les paroles qu'envoyait l'Éternel des armées par son Esprit, par les premiers prophètes; et ainsi survint une grande colère de l'Éternel des armées.",
        13: "Et il arriva que, comme Il appela et qu'ils n'écoutèrent pas, de même ils appelèrent, et je n'écoutai pas, dit l'Éternel des armées;",
        14: "et je les disséminai parmi tous les peuples qu'ils ne connaissaient pas; et le pays demeura désert derrière eux; il n'y avait ni allant ni venant, et ils firent ainsi d'un pays de délices une solitude.",
    },
    8: {
        1: "Et la parole de l'Éternel des armées fut adressée en ces mots:",
        2: "Ainsi parle l'Éternel des armées: Pour Sion un grand zèle m'anime, et par un grand courroux je lui montre mon zèle.",
        3: "Ainsi parle l'Éternel: Je reviens en Sion et fixe ma demeure au sein de Jérusalem; et Jérusalem sera nommée Cité fidèle, et la montagne de l'Éternel des armées Montagne sainte.",
        4: "Ainsi parle l'Éternel des armées: Des vieillards et des femmes âgées s'assiéront encore dans les rues de Jérusalem, ayant chacun son bâton à la main à cause de leur grand âge;",
        5: 'et les rues de la ville seront remplies de jeunes garçons et de jeunes filles jouant dans ses rues.',
        6: "Ainsi parle l'Éternel des armées: Si la chose est impossible aux yeux des restes de ce peuple dans ces jours-là, sera-t-elle aussi impossible à mes yeux, dit l'Éternel des armées?",
        7: "Ainsi parle l'Éternel des armées: Voici, je sauverai mon peuple du pays du lever et du pays du coucher du soleil;",
        8: 'et je les ramènerai, et ils habiteront au sein de Jérusalem, et ils seront mon peuple, et moi je serai leur Dieu en vérité et en justice.',
        9: "Ainsi parle l'Éternel des armées: Que vos mains reprennent force, à vous tous qui en ces jours entendîtes ces paroles de la bouche des prophètes, qui parurent au temps où fût fondée la maison de l'Éternel des armées, le temple pour être relevé.",
        10: "Car avant ces jours-là l'homme ne retirait point le prix de sa peine, ni le bétail le prix de sa peine, et à ceux qui entraient et sortaient l'ennemi ne laissait point de paix, et je mettais aux prises les hommes les uns avec les autres.",
        11: "Mais maintenant je ne serai pas envers les restes de ce peuple, comme j'ai été dans les premiers jours, dit l'Éternel des armées.",
        12: 'Car les semailles se feront en paix, la vigne donnera son fruit et la terre donnera son produit, et les Cieux donneront leur rosée, et je donnerai au reste de ce peuple la propriété de toutes ces choses;',
        13: "et de même que vous fûtes parmi les peuples en malédiction, maison de Juda et maison d'Israël, de même je veux vous sauver, et vous serez en bénédiction. N'ayez point de peur, que vos mains se raffermissent!",
        14: "Car ainsi parle l'Éternel des armées: De même que je pensai à vous faire du mal, quand vos pères m'irritèrent, dit l'Éternel des armées, et que je n'en eus point de repentir,",
        15: "ainsi je pense de nouveau en ces jours à faire du bien à Jérusalem et à la maison de Juda. N'ayez point de peur!",
        16: "Voici les choses que vous devez faire: parlez-vous vrai l'un à l'autre, rendez vos jugements dans vos Portes selon la vérité et en vue de la paix;",
        17: "que nul ne pense à mal contre son prochain dans son cœur, et n'aimez pas le faux serment, car ce sont tout autant de choses que je hais, dit l'Éternel.",
        18: "Et la parole de l'Éternel des armées me fut adressée en ces mots:",
        19: "Ainsi parle l'Éternel des armées: Le jeûne du quatrième mois et le jeûne du cinquième, et le jeûne du septième et le jeûne du dixième se changeront pour la maison de Juda en joie et en allégresse, et en fêtes de bonheur… Mais aimez la vérité et la paix.",
        20: "Ainsi parle l'Éternel des armées: Un jour encore viendront des peuples et les habitants de beaucoup de villes,",
        21: "et les habitants d'une ville aborderont ceux de l'autre en disant: Allons implorer l'Éternel et chercher l'Éternel des armées! Je veux aller aussi!",
        22: "Et beaucoup de peuples et de nombreuses nations viendront chercher l'Éternel des armées à Jérusalem et implorer l'Éternel.",
        23: "Ainsi parle l'Éternel des armées: En ces jours-là dix hommes de toutes les langues des nations saisiront le pan du manteau d'un Juif et diront: Nous voulons aller avec vous, car nous avons appris que Dieu est avec vous!",
    },
    9: {
        1: "Prononcé de la parole de l'Éternel contre le pays de Hadrach, et sur Damas elle vient s'arrêter, (car l'Éternel a l'œil sur les hommes et sur toutes les tribus d'Israël)",
        2: 'et sur Hamath aussi qui touche à ses confins, sur Tyr et Sidon qui a tant de sagesse.',
        3: "Tyr se bâtit des remparts et entassa l'argent comme la poussière, et l'or comme la boue des rues.",
        4: "Voici, le Seigneur s'en rend maître et abat dans la mer ses fortifications, et elle est dévorée par le feu.",
        5: "Askalon le voit et s'effraie, et Gaza qui en tremble fort, ainsi que Hécron; car son espoir est déjoué, et le roi est exterminé de Gaza, et Askalon est sans habitants.",
        6: "Et une race étrangère habite en Asdod, et je détruis l'orgueil des Philistins.",
        7: "Et je lui ôte le sang de la bouche, et les abominations d'entre les lèvres, et celui-ci aussi reste pour notre Dieu, et il est comme un chef en Juda, et Hécron comme un Jébusien.",
        8: "Et par un camp je défends ma maison contre l'agresseur, et contre ceux qui passent et repassent, et l'oppresseur ne les envahira plus; car maintenant j'y regarde de mes yeux.",
        9: "Sois transportée de joie, fille de Sion! pousse des cris, fille de Jérusalem! Voici, ton Roi vient à toi, il est juste et rendu vainqueur, pauvre et ayant pour monture un âne, un poulain, le petit d'une ânesse.",
        10: "Et j'exterminerai les chars d'Éphraïm et les chevaux de Jérusalem, et les arcs de guerre seront exterminés: et il parlera de paix aux peuples, et son empire ira d'une mer à l'autre mer, et du Fleuve aux extrémités de la terre.",
        11: 'Et je veux aussi, en vertu de ton alliance scellée par le sang, retirer pour toi tes captifs de la fosse qui est sans eau.',
        12: "Revenez au fort, captifs qui espérez! Aujourd'hui encore je le déclare, je te rendrai au double.",
        13: "Car je me bande Juda comme un arc, et je l'arme d'Éphraïm, et je fais lever tes enfants, ô Sion, contre tes enfants, ô Javan, et je te rends pareille à l'épée d'un héros.",
        14: "Et l'Éternel sur eux apparaîtra, et sa flèche partira comme l'éclair, et le Seigneur, l'Éternel, sonnera de la trompette, et s'avancera dans les tempêtes du midi.",
        15: "L'Éternel des armées les protégera, et ils dévoreront [leurs ennemis] et les fouleront comme des pierres de fronde, et boiront [leur sang] et feront vacarme comme dans le vin, et seront remplis comme les coupes des sacrifices, comme les angles de l'autel.",
        16: "Et l'Éternel, leur Dieu, les sauvera en ce jour-là, comme un troupeau, son peuple, car ils seront les pierreries d'un diadème, saillantes dans son pays.",
        17: 'En effet, quelle sera leur beauté! quel sera leur éclat! Le blé donnera croissance à de jeunes hommes, et le moût à des vierges.',
    },
    10: {
        1: "Demandez à l'Éternel la pluie au temps de l'arrière-saison; l'Éternel fera éclater la foudre et Il leur donnera la pluie par torrents, à chacun de l'herbe dans son champ.",
        2: "Car les Théraphims ont un langage vain, et les devins des visions menteuses, les songes expriment ce qui n'est pas, c'est par le néant qu'ils consolent; c'est pourquoi ils sont emmenés comme des brebis, ils sont misérables, parce qu'il n'y a point de pasteurs.",
        3: "Contre les pasteurs ma colère s'enflamme et des boucs je veux tirer vengeance, car l'Éternel des armées vengera son troupeau, la maison de Juda, et Il en fait son superbe cheval de bataille.",
        4: 'De son sein sortira la pierre angulaire, de son sein ses soutiens, de son sein les arcs de guerre, de son sein tous les chefs ensemble.',
        5: "Et ils seront comme des héros qui foulent aux pieds la boue des rues dans le combat, et ils combattront, parce que l'Éternel sera avec eux, et les cavaliers sur leurs chevaux seront couverts de honte.",
        6: "Et je donnerai force à la maison de Juda et salut à la maison de Joseph, et leur rendrai leurs demeures, car je prends pitié d'eux, et ils seront comme n'ayant pas été rejetés de moi, car je suis l'Éternel, leur Dieu, et je les exaucerai.",
        7: "Et Éphraïm sera comme un héros, et leur cœur aura la joie que donne le vin, et leurs enfants le verront et en seront joyeux, et leur cœur se réjouira en l'Éternel.",
        8: "D'un cri je les appellerai et les recueillerai, car je les ai rachetés, et ils seront nombreux comme ils furent nombreux.",
        9: 'Je les dissémine parmi les peuples, mais dans les pays lointains ils se souviendront de moi: aussi vivront-ils avec leurs enfants, et il y aura pour eux un retour.',
        10: "Et je les tirerai du pays d'Egypte, et les recueillerai de l'Assyrie et les conduirai au pays de Galaad et au Liban, où l'espace ne leur suffira pas.",
        11: "Et [l'Éternel] passera la mer étroite et frappera les flots dans la mer, et toutes les profondeurs du Nil seront desséchées, et l'orgueil d'Assur abaissé, et le sceptre de l'Egypte disparu.",
        12: "Et je les fortifierai dans l'Éternel; et en son nom ils marcheront, dit l'Éternel.",
    },
    11: {
        1: 'Liban, ouvre tes portes, et que le feu dévore tes cèdres!',
        2: "Cyprès, gémis, car le cèdre tombe, ceux qui s'élèvent sont dévastés; gémissez, chênes de Basan, car la forêt inaccessible tombe!",
        3: 'Écoutez! les bergers gémissent, car leur gloire est anéantie. Écoutez! les lions rugissent, car la parure du Jourdain est anéantie.',
        4: "Ainsi parle l'Éternel, mon Dieu: Sois le pasteur des brebis à tuer,",
        5: "que leurs acheteurs égorgent sans être coupables, et dont les vendeurs disent: « Loué soit l'Éternel, car je me suis enrichi! » et que les pasteurs n'épargnent point.",
        6: "Car je n'épargnerai plus les habitants du pays, dit l'Éternel; et voici, je vais livrer les hommes aux mains les uns des autres, et aux mains de leur Roi, et ils extermineront le pays, et je ne délivrerai pas de leurs mains. –",
        7: "Et je fus le pasteur des brebis à tuer, à cause de leur misère extrême. Et je pris deux houlettes: à l'une je donnai le nom de Grâce, et à l'autre le nom d'Union, et je fis paître les brebis.",
        8: "Et je détruisis les trois pasteurs en un mois; et j'étais las d'eux, et ils avaient aussi de l'aversion pour moi.",
        9: "Alors je dis: Je ne veux pas être votre pasteur. Meure qui doit mourir, et périsse qui doit périr, et que les survivantes dévorent la chair l'une de l'autre!",
        10: 'Et je pris ma houlette Grâce et la brisai, pour rompre mon alliance conclue par moi avec tous les peuples.',
        11: "Et elle fut rompue en ce jour-là, et par là les plus malheureuses brebis qui regardèrent vers moi, comprirent que c'était la parole de l'Éternel.",
        12: "Et je leur dis: S'il vous semble bon, donnez-moi mon salaire; sinon, n'en faites rien! Et ils me pesèrent mon salaire, trente sicles d'argent.",
        13: "Et l'Éternel me dit: Jette-le au potier, ce prix magnifique auquel ils m'évaluent. Et je pris les trente sicles d'argent et les jetai dans la maison de l'Éternel pour le potier.",
        14: 'Et je brisai ma seconde houlette Union, pour rompre la fraternité entre Juda et Israël.',
        15: "Et l'Éternel me dit: Prends encore l'équipement d'un pasteur insensé;",
        16: "car voici, je susciterai un pasteur dans le pays, qui ne s'inquiétera pas des brebis perdues, n'ira pas à la recherche de celles qui s'égarent, et ne guérira pas les blessées, et ne sustentera pas les saines, et mangera la chair des grasses, et entr'ouvrira leur sabot.",
        17: "Malheur au méchant pasteur qui abandonne ses brebis! que l'épée fonde sur son bras et sur son œil droit! que son bras sèche, et que son œil droit s'éteigne.",
    },
    12: {
        1: "Prononcé de la parole de l'Éternel sur Israël. Ainsi parle l'Éternel, qui déploya les Cieux et fonda la terre, et forma l'esprit de l'homme au dedans de lui:",
        2: "Voici, je ferai de Jérusalem un seuil qui branle pour tous les peuples d'alentour, et Juda sera aussi compris dans le siège de Jérusalem.",
        3: "Et en ce jour-là je ferai de Jérusalem une pierre à soulever pour tous les peuples; tous ceux qui la soulèveront, s'y déchireront, et tous les peuples de la terre s'assembleront contre elle.",
        4: "En ce jour-là, dit l'Éternel, je frapperai tous les chevaux d'épouvante, et leurs cavaliers du délire, mais j'aurai l'œil ouvert sur la maison de Juda, et je frapperai tous les chevaux des peuples de cécité.",
        5: "Alors les chefs de Juda diront en leurs cœurs: Notre force est dans les habitants de Jérusalem, par l'Éternel des armées, leur Dieu.",
        6: "En ce jour-là je rendrai les chefs de Juda pareils à un fourneau ardent parmi des arbres, et à une torche ardente parmi des gerbes, et ils dévoreront à droite et à gauche tous les peuples d'alentour, et Jérusalem demeurera assise sur son sol à Jérusalem.",
        7: "Et l'Éternel sera d'abord en aide aux tentes de Juda, afin que la gloire de la maison de David et la gloire des habitants de Jérusalem ne s'élève pas au-dessus de Juda.",
        8: "En ce jour-là, l'Éternel protégera les habitants de Jérusalem, et le faible parmi eux en ce jour-là sera comme David, et la maison de David semblable à Dieu, à l'ange de l'Éternel à leur tête.",
        9: 'Et en ce jour je me mettrai à détruire toutes les nations qui auront marché contre Jérusalem.',
        10: "Alors je verserai sur la maison de David et sur les habitants de Jérusalem l'esprit de grâce et de supplication, et ils regarderont vers moi, celui qu'ils ont transpercé, et le pleureront comme on pleure un unique, et s'affligeront à son sujet, comme on s'afflige au sujet d'un premier-né.",
        11: 'En ce jour-là grand sera le deuil à Jérusalem, tel que fut le deuil à Hadadrimmon dans la vallée de Mégiddo.',
        12: 'Et tout le pays sera en deuil, chaque famille de son côté: la race de la maison de David de son côté, et leurs femmes de leur côté; la race de la maison de Nathan de son côté, et leurs femmes de leur côté;',
        13: 'la race de la maison de Lévi de son côté, et leurs femmes de leur côté; la race de Siméi de son côté, et leurs femmes de leur côté;',
        14: 'toutes les familles restées, chaque race de son côté, et leurs femmes de leur côté.',
    },
    13: {
        1: 'En ce jour-là il y aura une source ouverte pour la maison de David et pour les habitants de Jérusalem, pour le péché et la souillure.',
        2: "Et en ce jour-là, dit l'Éternel des armées, j'exterminerai du pays les noms des idoles, pour que leur mémoire se perde, et je bannirai aussi du pays les prophètes et l'esprit impur.",
        3: "Que si quelqu'un prophétise encore, son père et sa mère, ses parents lui diront: « Tu ne dois pas vivre, car tu as proféré le mensonge au nom de l'Éternel; » et son père et sa mère, ses parents, le transperceront lui prophétisant.",
        4: 'Et en ce jour-là les prophètes auront tous honte de leur vision eux prophétisant, et ils ne revêtiront plus le manteau velu pour tromper.',
        5: "Et chacun d'eux dira: Je ne suis point prophète, je suis laboureur, car quelqu'un me vendit dès ma jeunesse.",
        6: "Et si on lui dit: Qu'est-ce donc que ces blessures que tu as aux mains? il dira: J'ai reçu ces coups dans la maison de mes amants.",
        7: "Épée, réveille-toi! [fonds] sur mon pasteur et sur un homme qui est mon proche! dit l'Éternel des armées; frappe le pasteur, et le troupeau se dispersera, mais je reporterai ma main sur les petits.",
        8: "Et il arrivera dans tout le pays, dit l'Éternel, que les deux tiers en seront exterminés, périront, et que le tiers y survivra.",
        9: "Et je mettrai le tiers au feu et les purifierai, comme on purifie l'argent, et les éprouverai, comme on éprouve l'or. Et ce tiers invoquera mon nom, et moi je l'exaucerai; je dirai: C'est mon peuple; et ils diront: L'Éternel est mon Dieu.",
    },
    14: {
        1: "Voici, un jour arrive pour l'Éternel, et tes dépouilles seront partagées dans ton sein;",
        2: "et je rassemblerai toutes les nations contre Jérusalem pour y porter la guerre, et la ville sera prise, et les maisons pillées, et les femmes déshonorées; et la moitié delà ville s'en ira captive, mais le reste du peuple ne sera point exterminé de la ville.",
        3: "Alors l'Éternel s'avancera, et livrera bataille à ces nations-là, comme à la journée où Il livra bataille le jour de la mêlée.",
        4: "Et en ce jour-là ses pieds poseront sur la montagne des Oliviers, située en face de Jérusalem à l'orient; et la montagne des Oliviers se fendra par le milieu, de l'orient à l'occident, pour former une vallée très grande, et une moitié de la montagne reculera vers le nord, et une moitié vers le midi.",
        5: "Et vous fuirez par la vallée de mes montagnes, car la vallée des montagnes s'étendra jusqu'à Atsal, et vous fuirez comme vous avez fui devant le tremblement de terre, au temps de Hosias, roi de Juda. Et l'Éternel, mon Dieu, viendra, et tous ses Saints avec lui.",
        6: "Et en ce jour-là il n'y aura point de lumière, les splendeurs s'éclipseront:",
        7: "et ce sera un seul jour; (l'Éternel sait ce qu'il sera) il ne fera ni jour ni nuit, mais au temps du soir la clarté paraîtra.",
        8: 'Et en ce jour-là des eaux vives jailliront de Jérusalem, et une moitié ira à la mer orientale et une moitié à la mer occidentale, et cela été et hiver.',
        9: "Et l'Éternel régnera sur tout le pays; en ce jour-là il n'y aura qu'un seul Éternel; et il n'y aura que son nom seul.",
        10: "Tout le pays sera transformé, assimilé à la plaine, de Géba à Rimmon au midi de Jérusalem, qui sera éminente et assise sur son sol, de la porte de Benjamin jusqu'au lieu de la première porte, jusqu'à la porte de l'angle, et de la tour de Hananéel aux pressoirs du roi.",
        11: "Et ils y habiteront, et il n'y aura plus d'interdit, et Jérusalem siégera en sécurité.",
        12: "Or, voici la plaie qu'infligera l'Éternel à tous les peuples qui auront marché contre Jérusalem: Il fera tomber en pourriture la chair de chacun tandis qu'il est debout sur ses pieds, et leurs yeux tomberont en pourriture dans leurs cavités, et leur langue tombera en pourriture dans leur bouche.",
        13: "Et en ce jour-là il y aura un grand trouble de par l'Éternel parmi eux, l'un saisira la main de l'autre, et l'un lèvera la main sur la main de l'autre.",
        14: "Et Juda combattra aussi dans Jérusalem, et les richesses de toutes les nations d'alentour, or et argent et vêtements en grande abondance, seront ramassées.",
        15: 'Et pareille sera la plaie infligée aux chevaux, aux mulets, aux chameaux et aux ânes, et à tous les bestiaux qui seront dans ces camps, pareille a cette plaie-là.',
        16: "Et tous ceux qui survivront, de toutes les nations qui auront marché contre Jérusalem, monteront chaque année pour adorer le Roi, l'Éternel des armées, et célébrer la fête des Tabernacles.",
        17: "Et si des familles de la terre il en est qui ne montent pas à Jérusalem pour adorer le Roi, l'Éternel des armées, sur elles la pluie ne tombera pas.",
        18: "Et si la famille d'Egypte ne monte pas et ne vient pas, [la pluie ne tombera pas] non plus sur elle, mais ce sera la plaie que l'Éternel infligera aux nations qui ne monteront pas pour célébrer la fête des Tabernacles.",
        19: "Ce sera le péché de l'Egypte et le péché de tous les peuples qui ne monteront pas pour célébrer la fête des Tabernacles.",
        20: "En ce jour-là les clochettes des chevaux porteront: « Sainteté à l'Éternel! » Et les chaudières dans la maison de l'Éternel seront comme les vases des sacrifices devant l'autel.",
        21: "Et toute chaudière en Jérusalem et en Juda sera « sainteté à l'Éternel des armées, » et tous ceux qui sacrifieront, viendront et en prendront et y cuiront [les viandes], et il n'y aura plus de Cananéen dans la maison de l'Éternel des armées en ce jour-là.",
    },
}
