NAME = 'FreLXXGiguet: Traduction de la LXX par Pierre GIGUET et autres traducteurs, 1872.'
BOOK = 'Micah'

CHAPTERS = {
    1: {
        1: 'Et la parole de Dieu vint à Michée, fils de Morasthi, aux jours de Joatham, Achaz et Ézéchias, rois de Juda, sur les choses qu’il vit concernant Samarie et Jérusalem.',
        2: 'Écoutez, peuples, ces paroles; que toute la terre soit attentive, et tous ceux qu’elle contient. Et le Seigneur Maître sera parmi nous comme un témoignage, le Seigneur du haut de sa maison sainte.',
        3: 'Car voilà que le Seigneur sortira du lieu où il réside, et il descendra, et il marchera sur les hauteurs de la terre.',
        4: 'Et sous lui les montagnes seront émues, et les vallées fondront comme la cire devant le feu, et comme les eaux d’une cataracte.',
        5: 'Et tout cela arrivera à cause de l’impiété de Jacob et des péchés de la maison d’Israël. Quelle est l’impiété de Jacob? n’est-ce pas Samarie? Quel est le péché de Juda? n’est-ce pas Jérusalem?',
        6: 'Je rendrai Samarie comme la cabane d’un garde de vergers dans les champs, comme un plant de vigne; et j’arracherai ses pierres pour les jeter dans le ravin, et je mettrai à découvert ses fondations.',
        7: 'Et toutes ses statues tomberont; et tous les salaires qu’elle a reçus seront livrés aux flammes; et j’anéantirai toutes ses idoles; car elle a amassé des salaires de prostitution; et de ces salaires de prostitution elle s’est enrichie.',
        8: 'À cause de cela, elle se frappera la poitrine et se lamentera; elle ira nue et déchaussée; ses lamentations seront comme les sifflements du dragon, et ses plaintes comme celles des filles des Sirènes.',
        9: 'Car la plaie l’accable; sa plaie s’est étendue jusqu’en Juda, et touche aux portes de mon peuple, à Jérusalem.',
        10: 'O vous, gens de Geth, ne vous glorifiez pas; vous, gens d’Énacim, n’édifiez pas avec les ruines du temple par dérision; mais répandez de la poussière sur vos tétes par dérision de vous-mêmes!',
        11: 'La populeuse Sennaar, qui habite en joie ses villes, n’en est point sortie pour pleurer une maison voisine; elle entendra votre plainte douloureuse.',
        12: 'Qui a commencé à faire du bien à celle qui habitait dans la douleur? Car les maux sont aussi descendus, par le Seigneur, jusqu’aux portes de Jérusalem,',
        13: 'Avec le tumulte des chars et des cavaliers. Celle qui demeure en Lachis est pour la fille de Sion le principe de son péché; car en toi se sont trouvées les impiétés d’Israël.',
        14: 'À cause de cela, le Seigneur enverra des vengeurs jusqu’aux héritages de Geth, et jusqu’aux maisons vaines qui ont été vanités pour les rois d’Israël.',
        15: 'Et ils emmèneront tes héritiers, ô toi qui demeures en Lachis! L’héritage de gloire de la fille d’Israël ne subsistera pas au delà d’Odollam.',
        16: 'Rase-toi, coupe ta chevelure à cause de tes enfants, qui font tes délices; dilate ton veuvage comme un aigle; car on les a emmenés en captivité hors de toi.',
    },
    2: {
        1: 'Ils se préparent des peines; même sur leurs couches, ils songent à faire le mal; ils le font, dès que le jour paraît, parce qu’ils n’ont pas élevé les mains vers Dieu.',
        2: 'Ils ont désiré des champs, et ils ont dépouillé des orphelins; ils ont opprimé des familles; ils ont pris l’un avec sa demeure, l’autre avec son héritage.',
        3: 'À cause de cela, le Seigneur a dit: Voilà que je pense à me venger de cette tribu; vous ne relèverez plus la tête, et vous ne marcherez plus droit d’un pas superbe, parce que les temps sont mauvais.',
        4: 'En ces jours-là, vous serez des sujets de fables, et l’on chantera sur vous une lamentation, disant: Nous sommes accablés de misère; la part de mon peuple a été mesurée au cordeau, et nul n’était là pour empêcher le ravisseur et le mettre en fuite, et nos champs ont été partagés.',
        5: 'À cause de cela, nul n’étendra plus le cordeau pour te faire ta part de terre. Dans l’Église du Seigneur,',
        6: 'Ne versez point de larmes, et qu’on ne pleure point sur ces choses; car il ne rétractera pas ses reproches,',
        7: 'Celui qui dit: La maison de Jacob a irrité l’Esprit du Seigneur. N’est-ce point sa coutume? Les paroles du Seigneur ne sont-elles pas justes sur ce peuple? Et n’ont-elles pas cheminé avec droiture?',
        8: 'Jadis mon peuple s’est soulevé en ennemi contre sa paix. On l’a écorché et on lui a enlevé la peau comme pour lui ôter l’espérance, dans les brisements de la guerre.',
        9: 'Les chefs de mon peuple seront précipités de leurs maisons de délices; et à cause de leurs mœurs perverses, ils ont été rejetés. Allez aux montagnes éternelles.',
        10: 'Lève-toi et marche; car il n’est plus pour toi de repos à cause de ton impureté. Vous êtes perdus de corruption;',
        11: 'Vous avez fui quand personne ne vous poursuivait. L’esprit du mal a produit le mensonge, il s’est infiltré en toi comme le vin et l’ivresse. Et voici ce qui arrivera: d’une goutte de sang de ce peuple,',
        12: 'Il en naîtra la réunion de Jacob et de toutes ses tribus; je recueillerai avec amour les restes d’Israël, et je les ferai retourner au même lieu. Comme des brebis dans l’angoisse, comme un menu troupeau au milieu de son parc, ils s’élanceront des contrées des hommes,',
        13: 'À travers la brèche ouverte devant eux; ils en ont franchi l’ouverture, ils ont passé la porte par où ils étaient sortis; leur roi est devant eux, et le Seigneur sera le premier à leur tête.',
    },
    3: {
        1: 'Et il dira: Écoutez maintenant ces paroles, princes de la maison de Jacob, restes de la maison d’Israël; n’est-ce pas à vous de connaître le jugement?',
        2: 'Ceux qui haïssent le bien et cherchent le mal, arrachent eux-mêmes la peau de leur corps et la chair de leurs os.',
        3: 'De même qu’ils ont mangé les chairs de mon peuple, qu’ils l’ont écorché pour lui enlever la peau, qu’ils ont rompu ses os, qu’ils l’ont dépecé, comme les viandes qu’on fait cuire dans une marmite ou une chaudière:',
        4: 'De même ils crieront au Seigneur, et il ne les écoutera pas; et en ce temps-là il détournera d’eux sa face, parce qu’ils ont fait le mal en leurs pratiques contre le peuple.',
        5: 'Voici ce que dit le Seigneur contre les prophètes qui égarent mon peuple, qui mordent à pleines dents, qui lui annoncent la paix, et qui, si rien n’est donné à leur bouche, excitent la guerre contre lui:',
        6: 'À cause de cela, la nuit sera pour vous sans visions, il y aura pour vous ténèbres sans prophéties; et le soleil se couchera sur les prophètes, et pour eux le jour sera obscurci.',
        7: 'Et les voyants qui devinent les songes seront confondus, et les devins seront moqués, et tout le monde parlera contre eux, parce qu’il n’y aura personne pour les écouter.',
        8: 'Pour moi, je me remplirai de force, inspiré par le Seigneur, par le jugement et l’autorité, pour faire connaître ses impiétés à Jacob et ses péchés à Israël.',
        9: 'Écoutez donc ces paroles, chefs de la maison de Jacob, restes de la maison d’Israël, vous qui haïssez la justice et pervertissez toute droiture,',
        10: 'Qui bâtissez Sion dans le sang et Jérusalem dans l’iniquité.',
        11: 'Les princes de Jérusalem ont jugé pour des présents; ses prêtres ont parlé pour un salaire; ses prophètes ont prédit pour de l’argent, et ils se sont reposés sur le Seigneur, disant: Est-ce que le Seigneur n’est pas avec nous? Jamais il ne nous arrivera malheur.',
        12: 'À cause de cela, à cause de vous, la charrue passera sur Sion comme sur un champ; Jérusalem ressemblera à la cabane d’un garde de vergers, et la montagne du temple sera une forêt de chênes.',
    },
    4: {
        1: 'Et voici ce qui arrivera: au dernier jour, la montagne du Seigneur apparaîtra; on la verra au-dessus des cimes des monts; elle s’élèvera plus haut que les collines. Et les peuples auront hâte de s’en approcher;',
        2: 'Et les gentils viendront en grand nombre, et diront Venons, montons sur la montagne du Seigneur, et au temple du Dieu de Jacob. On nous en montrera le chemin, et nous cheminerons en ses sentiers; car de Sion sortira la loi, et de Jérusalem la parole du Seigneur.',
        3: 'Et il jugera entre beaucoup de peuples, et il châtiera, même au loin, des nations puissantes; et chez elles on forgera les glaives pour en faire des socs de charrue, et des javelines pour en faire des faux; de nation à nation, on ne s’attaquera plus par l’épée, on n’apprendra plus à combattre.',
        4: 'Et chacun se reposera sous sa vigne et sous son figuier; et nul ne leur inspirera de crainte, parce que le Seigneur tout-puissant l’a dit de sa bouche.',
        5: 'Tous les peuples alors suivront chacun sa voie; mais nous, nous marcherons au nom du Seigneur, notre Dieu, dans tous les siècles et au delà.',
        6: 'En ce jour, dit le Seigneur, je réunirai celle qui a le cœur contrit et celle que j’avais repoussée, et j’accueillerai ceux que j’avais chassés;',
        7: 'Et je mettrai en réserve celle qui a eu le cœur contrit; et je ferai une nation puissante de celle que j’avais repoussée; et le Seigneur règnera sur elles en la montagne de Sion, depuis ce moment jusqu’à la fin des siècles.',
        8: 'Et toi, vieille tour du troupeau, Sion, ma fille, la principauté te reviendra et rentrera dans tes murs; et le premier royaume de Babylone reviendra à ma fille Jérusalem.',
        9: 'Et maintenant pourquoi as - tu connu le malheur? n’avais-tu pas un roi? Ou ta raison avait-elle péri pour que tu aies senti les douleurs de l’enfantement?',
        10: 'Souffre et prends courage, et approche, Sion, ma fille; souffre comme une femme qui enfante; car bientôt tu sortiras de tes murs, tu dresseras tes tentes dans la plaine, et tu iras jusqu’à Babylone; puis le Seigneur ton Dieu t’en délivrera, et il te tirera des mains de tes ennemis.',
        11: 'Et maintenant, contre toi maintes nations se sont rassemblées, elles disaient: Réjouissons-nous, et que nos yeux surveillent Sion!',
        12: 'Mais elles ne savaient pas la pensée du Seigneur; elles n’avaient point compris ses conseils; car il les avait rassemblées comme des gerbes dans une aire.',
        13: 'Lève-toi, Sion, ma fille, tombe sur elles comme le fléau; je te donnerai des cornes de fer; je te couvrirai d’armes d’airain, et tu briseras maintes nations, et tu consacreras leurs grains nombreux au Seigneur, et leurs richesses au Seigneur de toute la terre.',
    },
    5: {
        1: 'Maintenant la fille sera investie; le Seigneur a ordonné que nous fussions assiégés, et l’on battra de verges les joues des tribus d’Israël.',
        2: 'Et toi, Bethlehem, maison d’Éphratha, toi si petite parmi les milliers des fils de Juda, de toi me sortira un rejeton pour être prince d’Israël, et ses origines existent depuis le commencement, de toute éternité.',
        3: 'À cause de cela, le Seigneur les fera attendre jusqu’au temps de celle qui doit enfanter; elle enfantera, et les restes de leurs frères reviendront aux fils d’Israël.',
        4: 'Et le Seigneur s’arrêtera, et il surveillera, et il fera paître son troupeau dans sa force, et ils demeureront dans la gloire du Seigneur leur Dieu. Car alors ils seront glorifiés jusqu’aux extrémités de la terre.',
        5: 'Et ce sera la paix, quand Assur aura envahi votre terre et marché sur vos champs; ensuite sept pasteurs et huit morsures d’hommes seront suscités contre lui.',
        6: 'Et ils gouverneront Assur par le glaive, et la terre de Nebrod par des retranchements; et le Seigneur vous délivrera d’Assur, après que celui-ci aura envahi votre territoire, et marché sur vos frontières.',
        7: 'Et les restes de Jacob seront parmi les gentils au milieu de maintes nations comme la rosée qui tombe envoyée par le Seigneur, et comme des agneaux dans un pré, afin que nuls ne se rassemblent parmi les fils des hommes.',
        8: 'Et les restes de Jacob seront, parmi les gentils, au milieu de maintes nations, comme un lion dans une forêt avec du bétail, et comme un lionceau avec un troupeau de brebis. Partout où il passe, il déchire et ravit, et nul n’est capable de le détruire.',
        9: 'Ta main se lèvera sur ceux qui t’oppriment, et tous tes ennemis seront exterminés.',
        10: 'Et en ce jour voici ce qui arrivera, dit le Seigneur: Je ferai périr tes chevaux au milieu de toi, et je briserai tes chars;',
        11: 'Je raserai les villes de ta terre, et je détruirai tes forteresses.',
        12: 'J’ôterai de ta main les sortilèges, et il n’y aura plus de devins avec toi.',
        13: 'J’anéantirai tes statues et tes colonnes, et tu n’adoreras plus les œuvres de tes mains.',
        14: 'Je déracinerai les bois sacrés du milieu de tes champs, et j’effacerai tes cités.',
        15: 'Et dans les transports de ma colère je tirerai vengeance des gentils, parce qu’ils ne m’auront point entendu.',
    },
    6: {
        1: 'Écoutez donc la parole: Le Seigneur, le Seigneur a dit: Lève-toi, annonce le jugement aux montagnes, et que les collines entendent ta voix!',
        2: 'Écoutez, montagnes, le jugement du Seigneur, et vous aussi, vallées, fondements de la terre; car le Seigneur vient en jugement devant son peuple, et il plaidera avec Israël.',
        3: 'Mon peuple, que t’ai-je fait? En quoi t’ai-je contristé? En quoi t’ai-je déplu? Réponds-moi.',
        4: 'Est-ce parce que je t’ai fait sortir de la terre d’Égypte, que je t’ai affranchi de la maison de servitude, et que j’ai envoyé devant toi Moïse, Aaron et Marie?',
        5: 'Mon peuple, souviens-toi donc de ce qu’a médité contre toi Balac, roi de Moab, et de la réponse que lui a rapportée Balaam, fils de Béor, depuis Sétim jusqu’à Galgala, afin que l’on connût la justice du Seigneur.',
        6: 'Comment prendrai-je le Seigneur? Comment serai-je agréable à mon Dieu très-haut? Le prendrai-je par des holocaustes, par des veaux d’un an?',
        7: 'Le Seigneur accueillera-t-il des milliers de béliers, des myriades de chèvres grasses? Donnerai-je, pour mes impiétés, les premiers - nés de mes troupeaux, et, pour les péchés de mon âme, le fruit de mes entrailles?',
        8: 'O homme, faut-il te dire ce qui est bon? Est-ce que le Seigneur demande de toi quelque chose, sinon que tu pratiques la justice, que tu aimes la miséricorde, et que tu sois prêt à cheminer avec le Seigneur ton Dieu?',
        9: 'La voix du Seigneur sera invoquée dans la ville, et sauvera ceux qui craignent son nom. Écoute, tribu: Qui donc mettra l’ordre en ta cité?',
        10: 'Est-ce le feu? Est-ce la maison de l’impie amassant des trésors iniques, avec une insolente impiété?',
        11: 'Sera-t-il absous, l’homme injuste avec ses fausses balances et ses faux poids en un sac?',
        12: 'Car c’est ainsi que ceux qui demeurent dans la ville ont amassé leurs richesses impies; et ils ne disent que des mensonges, et dans leur bouche leur langue s’est enorgueillie.',
        13: 'Et moi je commencerai par te frapper, et je t’effacerai à cause de tes crimes.',
        14: 'Tu mangeras, et ne seras point rassasié, et il y aura sur toi des ténèbres; et le Seigneur se détournera; tu ne seras point, sauvée; et ceux qui échapperont seront livrés au glaive.',
        15: 'Tu sèmeras et ne moissonneras pas; tu pressureras l’olive, et tu ne seras pas oint de son huile; tu pressureras la grappe, et tu n’en boiras pas le vin; et les lois de mon peuple seront abolies.',
        16: 'Car tu as gardé les ordonnances de Zambri, et',
    },
    7: {
        1: 'Malheur à moi! me voilà comme celui qui ramasse du chaume en la moisson, ou qui cueille un grappillon de la vendange, n’ayant pas à lui une seule grappe pour en manger les prémices; malheur à mon âme!',
        2: 'Car le juste a péri sur la terre; et parmi les hommes il n’en est pas qui marche droit. Tous sont en justice pour avoir versé le sang; et chacun d’eux accable son prochain sous l’oppression.',
        3: 'Et leurs mains sont prêtes à faire le mal. Le prince exige; le juge dit des paroles douces; et voici le désir de son âme: Je prendrai leurs biens,',
        4: 'Comme le ver qui ronge, marchant décemment au jour de la visite. Malheur! Vos vengeances, Seigneur, sont venues, et maintenant vont venir leurs lamentations.',
        5: 'Ne vous fiez pas à vos amis, n’espérez pas en vos princes; garde-toi même de ton épouse, et ne lui confie quoi que ce soit.',
        6: 'Car le fils outragera le père; la fille se révoltera contre sa mère, la bru contre sa belle-mère; l’homme aura pour ennemis tous ceux de sa maison.',
        7: 'Pour moi, je regarderai le Seigneur; j’attendrai le Dieu mon Sauveur, et mon Dieu m’exaucera.',
        8: 'Ne m’insulte pas, ô mon ennemie, parçe que je suis tombée, je me relèverai; car, si je suis à terre dans les ténèbres, le Seigneur m’éclairera.',
        9: 'Parce que j’ai péché contre le Seigneur, je supporterai sa colère jusqu’à ce qu’il ait reconnu juste ma cause. Et alors il me rendra justice, et il me ramènera à la lumière, et je verrai son équité.',
        10: 'Et mon ennemie verra cela; et elle sera couverte de honte, celle qui dit maintenant: Où est le Seigneur ton Dieu? Mes yeux la regarderont alors, et elle sera foulée aux pieds comme la boue des rues.',
        11: 'Voici le jour où l’on enduit la brique; ce jour sera celui de ta destruction, et ce jour-là tes lois seront effacées.',
        12: 'Et tes villes seront mises au niveau du sol; elles seront partagées entre les Assyriens; et tes forteresses seront partagées, depuis Tyr jusqu’au fleuve, d’une mer à l’autre, et d’une montagne à l’autre.',
        13: 'Et ta terre et tous ceux qui l’habitent seront désolés, à cause des fruits de leur convoitise.',
        14: 'Votre verge à la main, Seigneur, paissez les brebis de votre héritage, qui d’elles-mêmes se sont abritées dans la forêt du Carmel. Elles trouveront leur pâture en Basan et Galaad, comme aux jours d’autrefois,',
        15: 'Comme aux jours où vous nous avez fait sortir d’Égypte. Vous verrez des prodiges;',
        16: 'Et les gentils les verront aussi, et ils en seront confondus malgré toute leur puissance, ils se mettront la main sur la bouche, et leurs oreilles n’entendront plus.',
        17: 'Ils lécheront la terre comme les serpents qui rampent dans la poussière; ils seront pleins de trouble dans l’enceinte de leurs remparts; ils seront hors d’eux-mêmes, à cause du Seigneur notre Dieu, et ils auront peur de lui.',
        18: 'Qui donc est Dieu comme vous, qui ôtez les péchés, et passez sous silence les impiétés de ce qui reste de votre héritage! Le Seigneur n’a point maintenu le témoignage de sa colère; il se complaît en sa miséricorde;',
        19: 'Il reviendra; il aura compassion de nous; il submergera nos iniquités; il jettera nos péchés au fond de la mer.',
        20: 'Il fera ses dons à Jacob, en vérité; il sera miséricordieux envers Abraham, comme il l’a juré à nos pères aux jours d’autrefois.',
    },
}
