NAME = 'FreLXXGiguet: Traduction de la LXX par Pierre GIGUET et autres traducteurs, 1872.'
BOOK = 'Song of Solomon'

CHAPTERS = {
    1: {
        1: 'Cantique des cantiques, qui est de Salomon. Qu’il me baise des baisers de sa bouche; car tes mamelles sont meilleures que le vin.',
        2: 'Et la senteur de tes parfums l’emporte sur tous les aromates; ton nom est l’essence de parfum: voilà pourquoi les jeunes filles t’aiment.',
        3: 'Elles t’attirent, et à ta suite nous courons aux senteurs de tes parfums. Le roi m’a introduite dans sa chambre secrète; nous tressaillirons, nous nous réjouirons en toi; nous aimerons tes mamelles plus que le vin; la droiture te chérit.',
        4: 'Filles de Jérusalem, je suis noire, et je suis belle, comme les tentes de Cédar, comme les tentures de Salomon.',
        5: 'Ne me dédaignez pas, parce que je suis noire; c’est que le soleil a altéré ma couleur. Les fils de ma mère se sont levés contre moi; ils m’avaient fait la gardienne des vignes, et ma propre vigne, je ne l’ai point gardée.',
        6: 'O toi que mon âme a aimé, indique-moi où tu pais ton troupeau, où tu reposes à midi, de peur que peut-être je ne m’égare à la suite des troupeaux de tes compagnons.',
        7: 'O toi, la plus belle des femmes, si tu ne te connais toi-même, suis les traces de mes troupeaux, et pais tes chevreaux près des tentes de mes pasteurs.',
        8: 'Ma bien-aimée, je t’ai comparée à mes cavales attelées aux chars de Pharaon.',
        9: 'Tes joues, elles sont belles comme la colombe, et ton cou, comme un collier.',
        10: 'Nous te ferons des ornements d’or émaillés d’argent.',
        11: 'Aussi longtemps que le roi a été à table, mon nard a répandu son parfum.',
        12: 'Mon frère bien-aimé est pour moi un bouquet de myrrhe; il reposera entre mes mamelles.',
        13: 'Mon frère bien-aimé est pour moi une grappe en fleur dans la vigne d’Engaddi.',
        14: 'Que tu es belle, ô ma bien-aimée, que tu es belle! Tes yeux sont ceux d’une colombe.',
        15: 'Et toi, que tu es beau, mon frère bien-aimé! que tu es charmant à l’ombre de notre couche!',
        16: 'Les solives de vos demeures sont de cèdre, et ses lambris de cyprès.',
    },
    2: {
        1: 'Je suis la fleur des champs et le lis des vallées.',
        2: 'Comme le lis des vallées au milieu des épines, est ainsi ma bien-aimée au milieu des jeunes filles.',
        3: 'Comme le pommier parmi les arbres de la forêt, ainsi est mon frère bien-aimé parmi les jeunes hommes. J’ai désiré son ombre, et je m’y suis assise, et son fruit est doux à mon palais.',
        4: 'Introduisez-moi dans le cellier au vin; faites-y venir ma bien-aimée.',
        5: 'Soutenez-moi avec des parfums; entourez-moi de fruits, car je suis blessée d’amour.',
        6: 'Sa main gauche sera sous ma tête, et de sa droite il m’embrassera.',
        7: 'Filles de Jérusalem, je vous adjure, par les puissances et les vertus de la campagne, n’éveillez pas, ne réveillez pas ma bien-aimée, qu’elle-même ne le désire.',
        8: 'C’est la voix de mon bien-aimé; le voilà qui vient en bondissant sur les monts, en franchissant les collines.',
        9: 'Mon frère bien-aimé ressemble au chevreuil ou au jeune faon sur les montagnes de Béthel. Le voilà derrière notre mur; il se penche par la fenêtre, il regarde à travers le treillis.',
        10: 'Mon frère bien-aimé me parle, et me dit: Lève-toi, ma bien-aimée; viens, ô ma belle, ô ma colombe.',
        11: 'Car voilà que l’hiver est passé; la pluie s’en est allée, elle est partie.',
        12: 'Les fleurs se montrent sur la terre; le temps de tailler est venu; le roucoulement de la tourterelle s’entend sur notre terre.',
        13: 'Les jeunes figues montrent leurs bourgeons; les vignes sont en fleur et donnent leur parfum. Lève-toi, ma bien-aimée; viens, ô ma belle, ô ma colombe. Viens,',
        14: 'Toi ma colombe, à l’abri sous les roches, dans le creux des murs. Montre-moi ton visage, que j’entende ta voix; car ta voix est douce, et ton visage est plein de grâces.',
        15: 'Prenez les jeunes renards, qui ravagent les vignes, quand nos vignes sont en fleur.',
        16: 'Mon frère bien-aimé est à moi, et moi à lui; et il fait paître son troupeau parmi les lis,',
        17: 'Jusqu’à ce que se lèvent les premières brises du jour et que les ténèbres se dissipent. Reviens, mon frère bien-aimé; accours comme le chevreuil ou le jeune faon sur les ravins des montagnes.',
    },
    3: {
        1: 'Sur ma couche, la nuit, j’ai désiré celui qu’aime mon âme; je l’ai cherché, et ne l’ai point trouvé; je l’ai appelé, et il ne m’a pas écouté.',
        2: 'Je me lèverai donc; j’irai par la ville, les marchés, les places, et je chercherai celui qu’aime mon âme. Je l’ai cherché, et ne l’ai point trouvé.',
        3: 'Les gardiens m’ont rencontrée, en faisant la ronde dans la ville N’avez-vous pas vu celui qu’aime mon âme?',
        4: 'A peine éloignée d’eux, j’ai trouvé celui qu’aime mon âme; je l’ai pris par la main, et ne l’ai point quitté que je ne l’eusse introduit dans la maison de ma mère, dans la chambre de celle qui m’a conçue.',
        5: 'Filles de Jérusalem, je vous adjure par les puissances et les vertus des campagnes, n’éveillez pas, ne réveillez pas ma bien-aimée, qu’elle ne le désire.',
        6: 'Qui est celle qui monte du désert, comme une colonne de fumée sortant de l’encens et de la myrrhe, et de toutes les poudres dont se composent les parfums?',
        7: 'Voilà la couche de Salomon; soixante vaillants des forts d’Israël sont rangés en cercle autour d’elle.',
        8: 'Tous exercés aux combats, ils ont l’épée au côté, pour en écarter les terreurs de la nuit.',
        9: 'Le roi Salomon s’est fait un lit de cèdres du Liban.',
        10: 'Les montants en sont d’argent, et le siège d’or; le marchepied est de porphyre, et l’intérieur est pavé de pierres précieuses, amour des filles de Jérusalem.',
        11: 'Filles de Sion, sortez, contemplez le roi Salomon avec la couronne que lui a posée sa mère le jour de son mariage, le jour de la joie de son cœur.',
    },
    4: {
        1: 'Que tu es belle, ô ma bien-aimée! que tu es belle! Tes yeux sont ceux des colombes, sans parler de tes beautés cachées. Ta chevelure est comme la toison des troupeaux de chèvres qu’on voit en Galaad.',
        2: 'Tes dents sont comme la laine des brebis sortant du lavoir après la tonte; toutes ont deux petits, et nulle n’est stérile.',
        3: 'Tes lèvres sont comme un ruban écarlate, et ton langage est plein de grâce; tes joues sont comme la peau de la grenade, sans parler de tes beautés cachées.',
        4: 'Ton cou est comme la tour de David, qu’il a bâtie pour être un arsenal; mille boucliers y sont suspendus, et tous les dards des vaillants.',
        5: 'Tes deux mamelles sont comme deux faons jumeaux du chevreuil, paissant parmi les lis,',
        6: 'Jusqu’à ce que se lèvent les premières brises du jour, et que les ténèbres se dissipent. J’irai à la montagne de myrrhe et à la colline d’encens.',
        7: 'Tu es toute belle, ô ma bien-aimée; et il n’est point de tache en toi.',
        8: 'Viens du Liban, mon épouse, viens du Liban; tu iras du puits du serment aux cimes de Sanir et d’Hermon, des antres des lions aux montagnes des panthères.',
        9: 'Tu m’as ravi mon cœur, ma sœur, mon épouse; tu m’as ravi mon cœur d’un seul de tes regards, d’un seul des cheveux de ton cou.',
        10: 'Que tes mamelles sont belles, ma sœur, mon épouse! tes mamelles sont plus précieuses que le vin; et les senteurs de tes vêtements plus douces que tous les aromates.',
        11: 'De tes lèvres découlent des rayons de miel, ô mon épouse; le miel et le lait sont sous ta langue, et l’odeur de tes vêtements est comme l’odeur de l’encens.',
        12: 'Ma sœur, mon épouse, est un jardin enclos; c’est un jardin enclos, une fontaine scellée.',
        13: 'Tes rejetons forment un jardin de grenades avec les fruits du noyer, des grappes en fleur et du nard,',
        14: 'Du nard et du safran, de la canne et du cinnamome, de tous les arbres du Liban, de la myrrhe, de l’aloès, et des parfums les plus exquis.',
        15: 'La fontaine de ce jardin est un puits d’eau vive, qui jaillit du Liban.',
        16: 'Fuis d’ici, vent du nord; viens, vent du midi, souffle sur mon jardin, et que mes parfums en découlent.',
    },
    5: {
        1: 'Que mon frère bien-aimé descende en son jardin, qu’il mange de ses fruits. Je suis entré dans mon jardin, ma sœur, mon épouse; j’ai récolté ma myrrhe et mes parfums; j’ai mangé mon pain avec un rayon de miel; j’ai bu mon vin et mon lait. Mangez, ô mes amis; buvez, mes frères, et enivrez-vous.',
        2: 'Pour moi, je dors, et mon cœur veille. C’est la voix de mon frère bien-aimé; il heurte à la porte: Ouvre-moi, dit-il, ma bien-aimée, ma sœur, ma colombe, ma parfaite; ma tête est pleine de rosée, et mes cheveux humides des gouttes de la nuit.',
        3: 'J’ai ôté ma tunique; comment la revêtirai-je? Je me suis lavé les pieds; comment puis-je maintenant les salir?',
        4: 'Mon frère bien-aimé a passé la main dans l’ouverture de la porte, et si près de mon bien-aimé mes entrailles ont tressailli,',
        5: 'Je me suis levée pour ouvrir à mon frère bienaimé; mes mains ont distillé la myrrhe; mes doigts ont rempli de myrrhe la poignée du verrou.',
        6: 'Et j’ai ouvert à mon frère bien-aimé, et mon frère bien-aimé n’était plus là; et mon âme était défaillante pendant qu’il parlait. Je l’ai cherché, et ne l’ai point trouvé; je l’ai appelé, et il ne m’a point entendue.',
        7: 'Les gardes m’ont rencontrée, en faisant la ronde dans la ville; ils m’ont battue et meurtrie; les sentinelles des remparts m’ont dépouillée de mon manteau.',
        8: 'Filles de Jérusalem, je vous adjure par les puissances et les vertus des campagnes, si vous avez trouvé mon frère bien-aimé, que lui direz-vous? Dites-lui que je suis blessée d’amour.',
        9: 'Qu’est donc ton frère bien-aimé auprès d’un autre frère, ô toi belle entre toutes les femmes? qu’est ton frère bien-aimé auprès d’un autre frère, pour que tu nous adjures ainsi?',
        10: 'Mon frère bien-aimé est blanc et rose, choisi entre dix mille.',
        11: 'Sa tête est de l’or fin de Céphaz; ses cheveux sont souples, et noirs comme le corbeau.',
        12: 'Ses yeux sont comme ceux des colombes sur des étangs pleins d’eau, lavées dans le lait, se reposant sur les étangs.',
        13: 'Ses joues sont comme des vases d’aromates exhalant des parfums; ses lèvres sont des lis distillant la myrrhe la plus pure.',
        14: 'Ses mains sont gracieuses et d’or, et pleines de béryl; sa poitrine est une tablette d’ivoire sur une pierre de saphir.',
        15: 'Ses jambes sont des colonnes de marbre posées sur des bases d’or; sa beauté est celle du Liban elle excelle comme le cèdre.',
        16: 'Sa bouche est pleine de douceur, et fait naître les désirs; tel est mon frère bien-aimé, tel est mon ami, filles de Jérusalem.',
        17: 'Où est allé ton frère bien-aimé, ô toi belle entre toutes les femmes? Où ton frère bien-aimé s’est-il retiré? et nous le chercherons avec toi.',
    },
    6: {
        1: 'Mon frère bien-aimé est descendu dans son jardin parmi les roses d’aromates, pour paître son troupeau dans sesjardins, et y cueillir des lis.',
        2: 'Je suis à mon frère bien-aimé, et mon frère bienaimé est à moi; il fait paître son troupeau parmi les lis.',
        3: 'Tu es belle, ô ma bien-aimée, comme la tendresse, gracieuse comme Jérusalem, terrible comme une armée en bataille.',
        4: 'Détourne de moi tes yeux, car ils m’ont transporté; ta chevelure est comme les troupeaux de chèvres que l’on voit en Galaad.',
        5: 'Tes dents sont comme la toison des brebis sortant du lavoir après la tonte, qui toutes ont deux petits, et dont nulle n’est stérile. Tes lèvres sont comme un ruban écarlate, et ton langage est plein de grâce.',
        6: 'Tes joues sont comme la peau de la grenade, sans parler de tes beautés cachées.',
        7: 'Il y a soixante reines et quatre-vingts concubines, et des jeunes filles sans nombre.',
        8: 'Mais ma colombe, ma parfaite est unique; elle est l’unique de sa mère; elle est l’élue de celle qui l’a enfantée. Les jeunes filles l’ont vue, et la déclarent heureuse; les reines et les concubines la loueront.',
        9: 'Quelle est celle qui regarde dehors comme le matin; belle comme la lune, élue comme le soleil, terrible comme une armée en bataille?',
        10: 'Je suis descendu au jardin des noyers, pour voir les fruits du vallon; si la vigne est en fleur, et si les grenades sont fleuries.',
        11: 'Là je te donnerai mes mamelles. Mon âme n’a rien su, et j’ai été comme emportée par les chars d’Aminadab.',
        12: 'Reviens, reviens, ma Sulamite; reviens, reviens, et nous ne verrons que toi.',
    },
    7: {
        1: 'Que verrez-vous en la Sulamite, qui vient comme les rangs d’une armée? Fille de Nadab, que les sandales donnent de grâce à tes pas! Les contours de tes jambes ressemblent à des colliers, chef-d’œuvre d’un artiste.',
        2: 'Ton nombril est comme un cratère fait au tour, оù le vin ne manque jamais. Ta poitrine est comme un monceau de froment enveloppé de lis.',
        3: 'Tes deux mamelles sont comme les deux faons jumeaux d’un chevreuil.',
        4: 'Ton cou est comme une tour d’ivoire, tes yeux comme les étangs d’Hésebon, près des portes de la fille issue de beaucoup de peuples. Ton nez est comme la tour du Liban qui regarde Damas.',
        5: 'Ta tête est posée sur toi semblable au mont Carmel, et ta chevelure est comme de la pourpre; le roi est retenu dans tes galeries.',
        6: 'O ma bien-aimée, que de grâce, que de suavité en tes délices!',
        7: 'Ta stature est celle d’un palmier; tes mamelles sont comme des grappes de raisin.',
        8: 'J’ai dit: Je monterai au palmier; j’atteindrai à son faîte, et tes mamelles seront comme les grappes de la vigne, l’odeur de tes narines comme celle des pommes,',
        9: 'Et ton gosier comme un bon vin. (Épouse) Qu’aime mon frère bien-aimé (époux), et qui plaît à mes dents et à mes lèvres.',
        10: 'Je suis à mon frère bien-aimé, et son regard est tourné vers moi.',
        11: 'Viens, mon frère bien-aimé, allons aux champs, dormons dans les bourgades.',
        12: 'Levons-nous dès l’aurore pour aller aux vignes; voyons si le raisin est en fleur, si les graines sont en fleur, si les grenades fleurissent: c’est là que je te donnerai mes mamelles.',
        13: 'Les mandragores ont donné leur senteur, et, au seuil de nos portes, tous les fruits verts et mùrs, ô mon frère bien-aimé, je les ai gardés pour toi.',
    },
    8: {
        1: 'O mon frère bien-aimé, que n’as-tu sucé les mamelles de ma mère! Si je te trouve dehors, je te baiserai, et nul ne me méprisera.',
        2: 'Je te prendrai par la main, je t’introduirai dans la maison de ma mère, dans la chambre de celle qui m’a conçu. Je te ferai boire du vin parfumé, et du jus de mes grenades.',
        3: 'Il posera sa main gauche sur ma tête, et, de la droite, il m’embrassera.',
        4: 'Je vous adjure, filles de Jérusalem, par les vertus de la campagne, n’éveillez pas, ne réveillez pas ma bien-aimée qu’elle ne le désire.',
        5: 'Quelle est celle qui se lève blanche comme l’aubépine, appuyée sur son frère bien-aimé (époux)? Je t’ai réveillée sous un pommier (4); c’est là que ta mère t’a enfantée; c’est là que t’a enfantée celle qui t’a conçu.',
        6: 'Mets-moi comme un sceau sur ton cœur, et comme un sceau sur ton bras. Car l’amour est fort comme la mort, et la jalousie est cruelle comme l’enfer; ses traits sont des traits de feu, ce sont ses flammes.',
        7: 'Des torrents d’eau ne pourront point éteindre l’amour, ni les fleuves le submerger. Si un homme donne toute sa vie par amour, les autres hommes auront pour lui le dernier mépris.',
        8: 'Notre sœur est petite, et n’a point de mamelles; que ferons-nous pour notre sœur, le jour où je viendrai lui parler?',
        9: 'Si elle est un mur, couronnons-la de créneaux d’argent; si elle est une porte, incrustons-la de bois de cèdre.',
        10: 'Moi (l’épouse) je suis un mur, et mes mamelles sont comme des tours; et j’ai été à leurs yeux comme ayant trouvé la paix.',
        11: '(Époux) Salomon avait une vigne en Béelamon; il a donné sa vigne à ceux qui la gardent; chacun rendra de ses fruits mille sicles d’argent.',
        12: 'Ma vigne est à moi; elle est devant mes yeux; que Salomon en ait mille sicles; que ceux qui gardent ses fruits en aient deux cents.',
        13: 'O toi qui demeures dans les jardins, mes compagnes écoutent ta voix; fais-la-moi entendre.',
        14: 'Fuis, mon frère bien-aimé; et, rapide comme le chevreuil ou comme le faon de la biche, fuis dans les montagnes des parfums.',
    },
}
