NAME = 'FreLXXGiguet: Traduction de la LXX par Pierre GIGUET et autres traducteurs, 1872.'
BOOK = 'Zechariah'

CHAPTERS = {
    1: {
        1: 'Le huitième mois de la seconde année, sous Darius, la parole du Seigneur vint à Zacharie, fils de Barachie, fils d’Addo, le prophète, disant:',
        2: 'Le Seigneur a été transporté d’un grand courroux contre vos pères.',
        3: 'Et tu diras au peuple: Voici ce que dit le Seigneur tout-puissant: Convertissez-vous à moi, dit le Seigneur des armées, et je reviendrai à vous, dit le Seigneur des armées.',
        4: 'Et ne soyez pas comme vos pères, à qui les prophètes d’autrefois firent des reproches, disant: Voici ce que dit le Seigneur, maître de toutes choses: Quittez vos mauvaises voies et vos œuvres criminelles; et ils n’écoutèrent pas, et il ne s’empressèrent pas de m’obéir, dit le Seigneur.',
        5: 'Où sont vos pères? Où sont les prophètes? Est-ce qu’ils vivront toujours?',
        6: 'Accueillez donc mes paroles et mes ordonnances, et tout ce que par mon Esprit j’ai intimé à mes serviteurs les prophètes, qui ont repris vos pères; or ceux-ci ont répondu, et ont dit: Le Seigneur nous a traités selon ce qu’il avait résolu, et ainsi a-t-il fait, à cause de nos voies et de nos œuvres.',
        7: 'Le vingt-quatrième jour du onzième mois, celui du Sabbat, la deuxième année du règne de Darius, la parole du Seigneur vint à Zacharie, fils de Barachie, fils d’Addo, le prophète, disant:',
        8: 'J’ai eu la nuit une vision. Et voilà qu’un homme était monté sur un cheval fauve, et il se tenait entre des montagnes ombreuses, et il y avait derrière lui des chevaux roux, gris-pommelé, tachetés et blancs.',
        9: 'Et je dis Qui sont ceux-là, Seigneur? Et l’ange qui parlait avec moi me dit: Je te montrerai ce que c’est.',
        10: 'Et l’homme, qui se tenait debout entre les montagnes, parla, et il me dit: Ceux-ci sont ceux que le Seigneur a envoyés pour aller par toute la terre.',
        11: 'Et ils parlèrent à l’ange du Seigneur qui se tenait entre les montagnes, et ils dirent: Nous sommes allés par toute la terre, et voilà que toute la terre est habitée, et elle est en repos.',
        12: 'Et l’ange du Seigneur répondit: Seigneur tout-puissant, dit-il, jusques à quand serez-vous sans miséricorde pour Jérusalem et pour les villes de Juda, que vous avez délaissées depuis soixante-dix ans?',
        13: 'Et le Seigneur tout-puissant répondit à l’ange qui parlait avec moi, et lui dit des paroles bonnes et consolantes;',
        14: 'Et l’ange qui parlait avec moi me dit: Crie de toute ta force. Voilà ce que dit le Seigneur tout-puissant: Je suis pris d’un grand zèle pour Jérusalem et pour Sion;',
        15: 'Mais j’ai une grande colère contre les gentils qui se sont coalisés; car me voyant un peu irrité contre elle, ils se sont coalisés pour lui faire du mal.',
        16: 'C’est pourquoi voici ce que dit le Seigneur: Je reviendrai à Jérusalem en ma miséricorde, et mon temple y sera réédifié, dit le Seigneur tout-puissant; et il étendra encore le cordeau sur Jérusalem.',
        17: 'Et l’ange qui parlait avec moi ajouta: Crie encore de toute ta force: Voilà ce que dit le Seigneur Tout-Puissant Leurs villes seront de nouveau remplies de biens, et le Seigneur sera miséricordieux envers Sion, et Jérusalem sera son élue.',
        18: 'Et je levai les yeux, et je regardai, et je vis quatre cornes.',
        19: 'Et je dis à l’ange qui parlait avec moi: Qu’est cela, Seigneur? Et il me dit: Ce sont les cornes qui ont dispersé Juda, Israël et Jérusalem.',
        20: 'Et le Seigneur me montra quatre ouvriers.',
        21: 'Et je dis Que vont faire ceux-ci? Et il dit: Voilà les cornes qui ont dispersé Juda et brisé Israël, sans que nul ait levé la tête; or ceux-ci sont venus pour les aiguiser de leurs mains, et les quatre cornes sont les nations qui ont levé la corne contre la terre du Seigneur, pour disperser mon peuple.',
    },
    2: {
        1: 'Et je levai les yeux, et je regardai, et voilà qu’un homme tenait en sa main un cordeau de mesureur.',
        2: 'Et je lui dis: Où vas-tu? Et il me dit: Je vais mesurer Jérusalem, et voir quelle est sa largeur et quelle est sa longueur.',
        3: 'Et voilà que l’ange qui parlait avec moi s’arrêta, et un autre ange marchait à sa rencontre.',
        4: 'Et il lui parla, disant: Cours et parle à ce jeune homme, et dis-lui: Jérusalem regorgera d’une multitude d’hommes et d’un nombreux bétail en son enceinte.',
        5: 'Et moi, dit le Seigneur, je serai un rempart de feu autour d’elle; et je résiderai au milieu d’elle en ma gloire.',
        6: 'Fuyez, fuyez de la terre de l’Aquilon, dit le Seigneur; car je vous ramènerai des quatre vents du ciel, dit le Seigneur;',
        7: 'Je vous ramènerai dans Sion; sauvez-vous, vous qui.habitez chez la fille de Babylone!',
        8: 'Car voici ce que dit le Seigneur tout-puissant: Sur les pas de leur gloire, il m’a envoyé contre les nations qui vous ont dépouillés; car celui qui touche à vous est comme celui qui touche à la prunelle de son œil.',
        9: 'Aussi voilà que je porte la main sur eux, et ils seront la proie de ceux qu’ils ont asservis; et vous connaîtrez que je suis l’envoyé du Seigneur tout-puissant..',
        10: 'Réjouis-toi, tressaille d’allégresse, Sion, ma fille; car voilà que j’arrive, et je placerai ma tente au milieu de toi, dit le Seigneur.',
        11: 'Et en ce jour nombre de nations se réfugieront auprès du Seigneur, et elles seront à lui comme un peuple nouveau; et elles résideront au milieu de toi, et tu connaîtras que le Seigneur tout-puissant m’a envoyé près de toi.',
        12: 'Et le Seigneur aura Juda pour héritage; ce sera sa part dans la terre sainte, et Jérusalem sera encore son élue.',
        13: 'Que toute chair craigne en face du Seigneur; car il s’est élancé de ses nuées saintes.',
    },
    3: {
        1: 'Et le Seigneur me montra Jésus, le grand prêtre, se tenant devant l’ange du Seigneur, et le diable était à sa droite, pour s’opposer à lui.',
        2: 'Et le Seigneur dit au diable: Que le Seigneur te réprime, ô Satan; que le Seigneur, qui a choisi Jérusalem, te réprime! Vois: cela n’est-il pas comme un tison retiré du feu?',
        3: 'Or Jésus avait des vêtements sordides, et il se tenait debout devant la face de l’ange.',
        4: 'Et celui-ci parla, et dit à ceux qui se tenaient debout devant sa face: Otez au prêtre ses vêtements sordides; et, s’adressant à lui, il ajouta: Voilà que je t’ai ôté tes iniquités; et vous, revêtez-le de la robe traînante,',
        5: 'Et posez sur sa tête une tiare pure. Et ils le couvrirent d’une tiare pure, et ils lui donnèrent d’autres vêtements; et l’ange du Seigneur se tenait auprès d’eux.',
        6: 'Et l’ange du Seigneur, s’expliquant avec Jésus, lui dit:',
        7: 'Voici ce que dit le Seigneur, maître de toutes choses: Si tu chemines en mes voies, si tu gardes mes commandements, tu seras le juge de ma maison; et si tu gardes mes parvis, je te donnerai des hommes pour marcher au milieu de ceux qui sont ici.',
        8: 'Écoute donc, Jésus, grand prêtre, écoutez aussi, vous qui êtes assis avec lui devant moi; car vous êtes des hommes attentifs aux prodiges; or voilà que j’amène mon serviteur ORIENT.',
        9: 'Car voici la pierre que j’ai placée devant la face de Jésus; sur cette pierre unique il y a sept yeux; et voilà que je creuse une fosse, dit le Seigneur tout-puissant, et en un seul jour j’ôterai toute l’iniquité de cette terre.',
        10: 'En ce jour, dit le Seigneur tout-puissant, chacun de vous invitera son ami sous sa vigne et sous son figuier.',
    },
    4: {
        1: 'Et l’ange qui parlait avec moi revint, et il me réveilla, et je fus comme un homme éveillé de son sommeil.',
        2: 'Et il me dit: Vois-tu? Et je dis: J’ai vu; voilà un chandelier tout d’or, et dessus un lampion et sept lampes, et sept burettes à verser l’huile, pour les sept lampes qui sont sur le chandelier;',
        3: 'Et au-dessus de lui deux oliviers, l’un à droite du lampion, l’autre à gauche.',
        4: 'Et je questionnai, et je parlai à l’ange qui était avec moi, disant: Qu’est-ce que cela, Seigneur?',
        5: 'Et l’ange qui était avec moi répondit, et il me parla, disant: Tu ne sais pas ce que c’est? Et je repris: Nullement, Seigneur.',
        6: 'Et il reprit, et il me parla, disant: C’est la parole du Seigneur à Zorobabel, disant: Il te faut non une grande puissance, ni la force, mais mon Esprit, dit le Seigneur tout-puissant.',
        7: 'Qui es-tu pour prospérer, ô grande montagne que je vois devant Zorobabel? Or je transporterai la pierre de l’héritage, dont la grâce est l’égale de ma grâce.',
        8: 'Et la parole du Seigneur me vint, disant:',
        9: 'Les mains de Zorobabel ont fondé ce temple, et ses mains l’achèveront; et tu connaîtras que le Seigneur tout-puissant m’a envoyé à toi.',
        10: 'Car qui a méprisé le temple dans les mauvais jours? Or on se réjouira, et on verra Zorobabel le plomb à la main. Ces sept yeux sont ceux qui regardent toute la terre.',
        11: 'Et je parlai, et je lui dis: Que sont ces deux oliviers, l’un à droite, l’autre à gauche du chandelier?',
        12: 'Et je l’interrogeai de nouveau, et lui dis: Que sont ces deux rameaux d’olivier, à côté des deux becs de lampe où coule l’huile des sept burettes d’or?',
        13: 'Et il me répondit: Tu ne sais pas ce que c’est? et je répondis: Nullement, Seigneur.',
        14: 'Et il dit: Ce sont les deux fils de l’onction qui se tiennent auprès du Seigneur de toute la terre.',
    },
    5: {
        1: 'Et je me retournai, et je levai les yeux, et je regardai; et voilà une faux volante.',
        2: 'Et l’ange me dit: Que vois-tu? Et je dis: Je vois une faux volante, longue de vingt coudées, et large de dix.',
        3: 'Et il me dit: C’est la malédiction qui se promène sur toute la face de la terre; car de ce côté-ci tout larron sera puni de mort, et de ce côté-là tout parjure sera puni.',
        4: 'Et je la ferai cheminer, dit le Seigneur tout-puissant; et elle entrera dans la maison du voleur et dans la maison de celui qui jure en vain mon nom, et elle demeurera au milieu de sa maison, et elle en consumera le bois et les pierres.',
        5: 'Et l’ange qui parlait avec moi sortit, et il me dit: Lève les yeux, et regarde ce qui s’avance.',
        6: 'Et je dis: Qu’est-ce? Et il reprit: C’est la mesure qui s’avance; et il ajouta: C’est leur iniquité qui couvre toute la terre.',
        7: 'Et voilà qu’un talent de plomb s’élevait, et voilà qu’une femme était assise au milieu de la mesure.',
        8: 'Et l’ange dit: Celle-ci est le péché; et il fit tomber la femme au fond de la mesure, et il fit tomber la masse de plomb dans sa bouche.',
        9: 'Et je levai les yeux, et je regardai, et voilà deux',
        10: 'Et je dis à l’ange qui parlait avec moi: Où emportent-elles la mesure?',
        11: 'Et il répondit: Elles vont lui bâtir une demeure en la terre de Babylone, et préparer pour cela une place; elles la mettront sur sa base.',
    },
    6: {
        1: 'Et je me retournai, et je levai les yeux, et je regardai, et voilà quatre chars sortant entre deux montagnes, et ces montagnes étaient d’airain.',
        2: 'Au premier char il y avait des chevaux roux, et au second char, des chevaux noirs,',
        3: 'Et au troisième char, des chevaux blancs, et au quatrième char, des chevaux gris-pommelé.',
        4: 'Et je parlai, et je dis à l’ange qui parlait avec moi: Qu’est cela, Seigneur?',
        5: 'Et l’ange qui parlait avec moi me répondit, et me dit: Ce sont les quatre vents du ciel; ils sortent pour se tenir devant le Seigneur de toute la terre.',
        6: 'Or les chevaux noirs s’en allaient sur toute la terre du septentrion; et les blancs venaient ensuite; et les gris-pommelé s’en allaient sur la terre du midi;',
        7: 'Et les autres sortirent, et ils regardèrent pour s’en aller et parcourir toute la terre; et l’ange leur dit: Marchez et parcourez toute la terre. Et ils parcoururent toute la terre.',
        8: 'Et il cria, et il me parla, disant: Voilà que ceux qui s’en vont sur la terre du septentrion ont satisfait à ma colère, en la terre du septentrion.',
        9: 'Et la parole du Seigneur vint à moi, disant:',
        10: 'Prends les dons des captifs, soit de leurs princes, soit des hommes serviables de la captivité, soit de ceux qui l’honorent; et ce jour-là entre en la maison de Josias, fils de Sophonie, qui est arrivé de Babylone.',
        11: 'Et tu prendras l’argent et l’or, et tu en feras des couronnes, et tu les poseras sur la tête de Jésus, fils de Josédec, le grand prêtre.',
        12: 'Et tu lui diras: Voici ce que dit le Seigneur tout-puissant: Voilà un homme: Orient est son nom, et il se lèvera venant de ce qui est sous lui.',
        13: 'Et il bâtira le temple du Seigneur, et il recevra la force, et il siégera, et il régnera sur son trône; et le prêtre sera à sa droite, et un conseil de la paix sera entre eux deux.',
        14: 'Et la couronne sera pour ceux qui ont souffert patiemment, et pour ceux de la captivité qui auront été serviables, et pour ceux qui l’ont honorée, afin de rendre des actions de grâces au fils de Sophonie, et les chanter dans le temple du Seigneur.',
        15: 'Et ceux qui demeurent au loin viendront et travailleront aussi à réédifier le temple du Seigneur; et vous saurez que le Seigneur tout-puissant m’a envoyé près de vous; et ces choses arriveront si vous êtes dociles à la voix du Seigneur votre Dieu.',
    },
    7: {
        1: 'Et en la quatrième année du règne de Darius, le quatrième jour du neuvième mois de chaseleu, la parole du Seigneur vint à Zacharie.',
        2: 'Sarasar et Arbeséer, le roi et ses hommes, envoyèrent en Béthel pour prier le Seigneur;',
        3: 'Disant aux prêtres du temple du Seigneur tout-puissant et aux prophètes: Les saintes offrandes sont entrées ici le cinquième mois, comme il a déjà été fait en un grand nombre d’années.',
        4: 'Et la parole du Seigneur, Dieu des armées, vint à moi, disant:',
        5: 'Parle à tout le peuple de la terre et aux prêtres, et dis-leur: Quand vous avez jeûné et pleuré les cinquième et septième mois de ces soixante-dix années, est-ce pour moi que vous avez jeûné?',
        6: 'Et quand vous avez mangé et bu, n’est-ce pas pour vous que vous mangiez et buviez?',
        7: 'N’est-ce point là ce que vous a dit le Seigneur, par les prophètes d’autrefois, lorsque Jérusalem était habitée et prospérait, ainsi que les villes d’alentour, et que les montagnes et la plaine regorgeaient d’habitants?',
        8: 'Et la parole du Seigneur vint à Zacharie, disant:',
        9: 'Voici ce que dit le Seigneur, maître de toutes choses Soyez justes quand vous jugez, et que chacun soit compatissant et miséricordieux envers son frère.',
        10: 'Gardez-vous d’opprimer la veuve, l’orphelin, l’étranger, le pauvre; et ne conservez point en vos cœurs un mauvais souvenir des méchancetés de vos frères.',
        11: 'Et ils ne le voulurent point entendre, et ils lui tournèrent le dos avec mépris, et pour ne point ouïr ils se bouchèrent les oreilles.',
        12: 'Et ils se firent des cœurs désobéissants, au point d’être indociles à ma loi et aux paroles que leur envoyait le Seigneur tout-puissant, par son Esprit et par les prophètes d’autrefois. Et le Seigneur tout-puissant en eut un grand courroux.',
        13: 'Or voici ce qui arrivera, dit le Seigneur tout-puissant: le Seigneur a parlé et ils n’ont point écouté; de même, quand ils crieront, je ne les écouterai pas.',
        14: 'Et je les chasserai; et je les disperserai parmi les nations qu’ils n’ont point connues; et derrière eux la terre sera dénuée d’allants et venants; et ils auront voué à la destruction une terre que j’avais choisie.',
    },
    8: {
        1: 'Et la parole du Seigneur, maître de toutes choses, me vint, disant:',
        2: 'Voici ce que dit le Seigneur, maître de toutes choses Je suis pris d’un grand zèle pour Jérusalem et pour Sion, et je suis en même temps pris d’une grande colère.',
        3: 'Voici ce que dit le Seigneur: Je reviendrai à Sion; je résiderai au milieu de Jérusalem, et Jérusalem sera appelée la ville de vérité, et la montagne du Seigneur sera la montagne sainte.',
        4: 'Voici ce que dit le Seigneur tout-puissant: Des anciens et des anciennes s’assoiront encore dans les rues de Jérusalem, ayant chacun à la main un bâton de vieillesse, à cause de la plénitude de leurs jours.',
        5: 'Et les places de la ville seront remplies de jeunes garçons et de jeunes filles qui joueront dans ses rues.',
        6: 'Voici ce que dit le Seigneur tout-puissant: Si en ces jours cela est impossible aux yeux de ceux qui sont restés de ce peuple, est-ce que cela sera impossible à mes yeux? dit le Seigneur tout-puissant.',
        7: 'Voici ce que dit le Seigneur tout-puissant: Je sauverai mon peuple des contrées de l’Orient et de celles de l’Occident;',
        8: 'Et je l’en ferai sortir, et je le ramènerai au milieu de Jérusalem; et il sera mon peuple, et moi je serai son Dieu de vérité et de justice.',
        9: 'Voici ce que dit le Seigneur tout-puissant: Que vos mains soient fortes, ô vous qui entendez en ces jours les paroles de la bouche des prophètes, en ce jour où l’on a jeté les fondations de la maison du Seigneur tout-puissant, et où le temple a été relevé.',
        10: 'Car avant ces jours le salaire des hommes ne sera point lucratif, le travail des bêtes ne profitera point, et ceux qui sont entrés, ceux qui sont sortis, n’auront pas trouvé de paix, à cause de leurs afflictions. Et alors je ferai marcher tous les hommes l’un contre l’autre.',
        11: 'Mais maintenant je ne traiterai plus les restes de ce peuple comme aux jours d’autrefois, dit le Seigneur tout-puissant.',
        12: 'Je lui ferai connaître la paix. La vigne produira son fruit; la terre produira ses récoltes; le ciel donnera sa rosée, et au reste de mon peuple je laisserai toutes ces choses en héritage.',
        13: 'Et voici ce qui arrivera: autant vous recevrez de malédictions chez les gentils, vous, maison de Juda, et vous, maison d’Israël, autant je mettrai de soins à vous sauver, et autant vous recevrez de bénédictions. Ayez bon courage, et fortifiez vos mains.',
        14: 'Car voici ce que dit le Seigneur tout-puissant: De même que j’ai songé à vous affliger parce que vos pères avaient excité mon courroux, dit le Seigneur tout-puissant,',
        15: 'Sans que je m’en repente de même je suis disposé et je songe, en ces jours, à combler de biens Jérusalem et la maison de Juda.',
        16: 'Voici les choses que vous ferez parlez selon la vérité à votre prochain; jugez devant vos portes selon la vérité, la justice et la paix.',
        17: 'Ne pensez pas à mal en vos discours contre votre prochain, et n’aimez pas le faux serment; car je hais toutes ces choses, dit le Seigneur tout-puissant.',
        18: 'Et la parole du Seigneur tout-puissant vint à moi, disant:',
        19: 'Voici ce que dit le Seigneur tout-puissant: Le jeûne du quatrième mois, le jeûne du cinquième, le jeûne du septième, le jeûne du dixième, seront alors pour la maison de Juda un sujet de joie, d’allégresse et de bonnes fêtes; réjouissez-vous; aimez la vérité et la paix.',
        20: 'Voici ce que dit le Seigneur tout-puissant: Vous deviendrez encore un peuple nombreux, et vous habiterez beaucoup de villes.',
        21: 'Et les habitants de cinq villes se réuniront en une seule, en disant: Allons prier devant la face et sous les yeux du Seigneur tout-puissant; et moi, j’irai à eux.',
        22: 'Et des peuples nombreux et des nations nombreuses viendront à Jérusalem chercher la face du Seigneur tout-puissant, et prier devant la face du Seigneur.',
        23: 'Voici ce que dit le Seigneur tout-puissant: En ces jours, dix hommes de toutes les langues prendront par la frange de son manteau un homme de la Judée, disant: Nous irons avec toi, parce que nous avons ouï dire que Dieu est avec vous.',
    },
    9: {
        1: 'Parole du Seigneur contre la terre de Sedrach; et celle de Damas sera sacrifiée comme elle; car le Seigneur surveille les hommes et toutes les tribus d’Israël.',
        2: 'Et cette parole est contre la terre d’Emath qui contient Tyr et Sidon, parce qu’elles ont trop connu la sagesse.',
        3: 'Or Tyr s’est bâti des forteresses, et elle a thésaurisé de l’argent par monceaux comme de la poussière, et des amas d’or comme la boue des chemins.',
        4: 'Et à cause de cela le Seigneur en prendra possession, et il jettera ses forces à la mer, et elle-même sera dévorée par le feu.',
        5: 'Ascalon le verra et en tremblera; Gaza le verra et en souffrira cruellement; Ascaron le verra et sera confondue de sa chute; et le roi de Gaza périra, et Ascalon ne sera plus habitée.',
        6: 'Et des étrangers repeupleront Azot; et j’abattrai l’orgueil des Philistins.',
        7: 'Et j’ôterai de leur bouche le sang des victimes, et l’abomination d’entre leurs dents; et ils seront aussi délaissés par notre Dieu, et ils seront comme un chef de mille hommes en Juda, et Accaron sera comme un Jébuséen.',
        8: 'Et j’élèverai un rempart autour de ma maison, pour qu’on ne puisse plus la traverser et y revenir, et que nul envahisseur n’y pénètre désormais; car maintenant je la vois de mes yeux.',
        9: 'Réjouis-toi grandement, Sion, ma fille, annonce à haute voix, Jérusalem, ma fille: Voilà que ton roi vient à toi, juste et sauveur, et il est plein de douleur, il est monté sur un âne, et sur un ânon, petit de l’ânesse.',
        10: 'Et il détruira les chars d’Éphraïm et la cavalerie de Jérusalem; et l’arc des batailles sera brisé, et il y aura paix et abondance parmi les nations; et il règnera depuis les eaux jusqu’à la mer, depuis les fleuves jusqu’aux confins de la terre.',
        11: 'Et toi, à cause du sang de ton alliance, tu as retiré tes captifs d’une citerne sans eau.',
        12: 'Et vous, captifs de la Synagogue, établissez-vous en des forteresses; et, pour un jour de captivité, je vous rétribuerai doublement.',
        13: 'Juda, tu es mon arc, et je l’ai tendu; j’ai rempli Éphraïm; j’exciterai tes enfants, ô Sion, contre les enfants des Hellènes, et je te manierai comme le glaive des combattants.',
        14: 'Et le Seigneur sera près d’eux; son trait partira comme un éclair; et le Seigneur tout-puissant sonnera de la trompette, et il s’avancera dans le tumulte de ses menaces.',
        15: 'Mais le Seigneur tout-puissant protégera les siens; ils extermineront leurs ennemis; ils les couvriront des pierres de leurs frondes; ils boiront leur sang comme du vin, et ils en rempliront leurs coupes, comme l’autel.',
        16: 'Et en ce jour le Seigneur leur Dieu les sauvera; il sauvera son peuple, comme un troupeau de brebis, parce que des pierres saintes sont roulées sur sa terre.',
        17: 'Car si quelque chose est son bien, si quelque chose est sa beauté, c’est le pain pour les jeunes hommes, et le vin d’odeur de suavité pour les vierges.',
    },
    10: {
        1: 'Demandez au Seigneur de la pluie selon la saison, le matin et le soir. Le Seigneur a créé des signes manifestes; il donnera aux hommes les pluies d’hiver, et à chacun de l’herbe en son champ.',
        2: 'Les faux prophètes ont fait des prédictions funestes; le devins ont rapporté des visions fausses et des songes trompeurs; ils ont donné de vaines consolations; à cause de cela, ils ont dépéri comme des brebis abandonnées; ils ont été affligés, parce qu’il n’y avait pas de remède.',
        3: 'Ma colère s’est enflammée contre les pasteurs, et je visiterai les agneaux. Et le Seigneur Dieu tout-puissant visitera son troupeau, la maison de Juda; et il la formera comme son coursier, prêt aux combats.',
        4: 'C’est de lui que vient la visite; de lui, l’ordre de bataille; de lui, l’arc de la colère; et aussi tout exacteur sortira de lui.',
        5: 'Et ils seront comme des guerriers, foulant aux pieds la boue des chemins dans la bataille; et ils en viendront aux mains, parce que le Seigneur sera avec eux; et les cavaliers seront confondus.',
        6: 'Et je fortifierai la maison de Juda; et je sauverai la maison de Joseph, et je les rétablirai, parce que je les aime; et ils seront comme si je ne les avais pas répudiés; car je suis le Seigneur leur Dieu, et je les exaucerai.',
        7: 'Et ils seront comme les guerriers d’Éphraïm, et leur cœur se réjouira, comme dans le vin; voilà ce que verront leurs enfants, et ils en seront charmés, et leur âme se réjouira dans le Seigneur.',
        8: 'Je leur donnerai le signal et je les rassemblerai; car je les affranchirai et les multiplierai, comme lorsqu’ils étaient le plus nombreux.',
        9: 'Et je les disséminerai parmi les peuples, et les plus lointains se souviendront de moi; ils élèveront leurs enfants, et ils reviendront de captivité.',
        10: 'Et je les ramènerai de la terre d’Égypte; je les accueillerai à leur retour de l’Assyrie, et je les conduirai en Galaad et sur le Liban; et pas un seul d’entre eux ne sera laissé en oubli.',
        11: 'Et ils traverseront les détroits de la mer, et ils frapperont ses vagues, et le fond des fleuves sera à sec, et tout l’orgueil des Assyriens sera abattu, et le sceptre de l’Égypte sera brisé.',
        12: 'Et je les fortifierai dans le Seigneur leur Dieu; et ils se feront gloire de son nom, dit le Seigneur.',
    },
    11: {
        1: 'Liban, ouvre tes portes, et que le feu dévore tes cèdres.',
        2: 'Que le pin gémisse, parce que le cèdre est tombé, parce que les plus grands sont détruits; chênes de Basan, gémissez, parce que la forêt épaisse est abattue.',
        3: 'Que la voix des pasteurs en larmes se fasse entendre, parce que leur grandeur s’est changée en détresse; et que les lions rugissent, parce que le Jourdain souffre en son orgueil.',
        4: 'Voici ce que dit le Seigneur tout-puissant: Paissez les brebis du sacrifice.',
        5: 'Leurs possesseurs les égorgeaient sans regret, tandis que ceux qui en avaient vendu disaient: Béni soit le Seigneur, nous voilà riches; et leurs bergers ne souffraient aucunement pour elles.',
        6: 'C’est pourquoi je n’épargnerai aucun des habitants de la terre, dit le Seigneur; et voilà que je livrerai chacun de ces hommes aux peuples voisins et aux mains de leurs rois; et ceux-ci désoleront la terre, et je ne la dětivrerai point de leurs mains.',
        7: 'Et je ferai paître dans le pays de Chanaan les brebis du sacrifice, et je prendrai pour moi deux houlettes, l’une que j’ai nommée la Beauté, l’autre que j’ai nommée le Cordeau; et je ferai paître les brebis.',
        8: 'Et je ferai périr trois pasteurs en un mois, et mon âme s’appesantira sur eux; car leurs âmes ont rugi contre moi.',
        9: 'Et j’ai dit: Je ne serai plus votre pasteur; que ce qui est mort soit mort, que ce qui est tombé soit tombé, et que les survivants dévorent les chairs les uns des autres.',
        10: 'Et je prendrai ma belle houlette, et je la rejetterai pour briser mon alliance, l’alliance que j’avais faite en faveur de tous les peuples.',
        11: 'Et ce jour-là elle sera rompue, et les Chananéens connaîtront les brebis que je garde; car telle est la parole du Seigneur.',
        12: 'Et je leur dirai: S’il vous semble bon, donnez-moi un salaire; sinon, refusez-le-moi. Et ils ont pesé pour mon salaire trente sicles d’argent.',
        13: 'Et le Seigneur me dit: Jette-les dans le creuset, et je verrai si l’argent a été éprouvé de la même manière que j’ai été éprouvé pour l’amour d’eux. Et je pris les trente sicles d’argent, et je les jetai au creuset, dans le temple du Seigneur.',
        14: 'Et je rejetai la seconde houlette, le Cordeau, pour briser les liens entre Juda et Israël.',
        15: 'Et le Seigneur me dit: Prends encore pour toi le bagage d’un pasteur, d’un pasteur insensé.',
        16: 'Car voilà que je susciterai un pasteur contre la terre; et il ne visitera pas ce qui périt; et il ne cherchera pas ce qui est égaré; et il ne guérira pas ce qui est blessé; et il ne gardera pas même ce qui est entier; et il mangera les chairs des bêtes d’élite, et il disloquera les jointures des os.',
        17: 'Malheur au pasteur des idoles, à celui qui délaisse les brebis! le glaive est levé sur son bras et sur son œil droit; son bras sera desséché, et son œil droit ne verra plus.',
    },
    12: {
        1: 'Parole du Seigneur concernant Israël; ainsi parle le Seigneur qui a tendu le ciel, fondé la terre et formé l’esprit de l’homme en lui:',
        2: 'Voilà que devant tout le peuple d’alentour je ferai Jérusalem comme le linteau tremblant d’une porte; et en Judée même on assiégera Jérusalem.',
        3: 'Et voici ce qui arrivera: en ce jour je ferai de Jérusalem une pierre que fouleront aux pieds tous les Gentils. Quiconque marchera sur elle s’en raillera, et toutes les nations de la terre se réuniront contre elle.',
        4: 'En ce jour, dit le Seigneur tout-puissant, je frapperai de stupeur le cheval, et de démence le cavalier. J’aurai les yeux ouverts sur la maison de Juda, et je frapperai d’aveuglement les chevaux de tous les peuples.',
        5: 'Et les chefs de mille hommes de Juda diront en leur cœur: Puissions-nous trouver pour nous les habitants de Jérusalem revenus au Seigneur leur Dieu tout-puissant!',
        6: 'En ce jour-là je rendrai les chefs de mille hommes de Juda comme un tison enflammé dans un bûcher, comme une lampe allumée dans la paille; ils dévoreront, à droite et à gauche, tous les peuples d’alentour, et Jérusalem d’elle-même repeuplera encore Jérusalem.',
        7: 'Et le Seigneur sauvera les habitants de Juda, comme dans les premiers jours; de telle sorte que l’orgueil de la maison de David et des hommes de Jérusalem ne s’élève point contre Juda.',
        8: 'Et voici ce qui arrivera: en ce jour le Seigneur protégera les habitants de Jérusalem; et le faible chez eux sera, ce jour-là, comme David, et la maison de David, comme la maison de Dieu, comme l’ange du Seigneur devant eux.',
        9: 'Et voici ce qui arrivera: en ce jour je rechercherai pour les anéantir toutes les nations qui auront marché contre Jérusalem.',
        10: 'Et je répandrai sur la maison de David et sur Jérusalem un esprit de grâce et de miséricorde; et ils tourneront les yeux vers moi, parce qu’ils m’auront insulté; et ils se lamenteront sur le peuple, comme sur un enfant bien-aimé; et ils seront pénétrés de douleur, comme sur un fils premier-né.',
        11: 'En ce jour les gémissements redoubleront en Jérusalem tel dans la campagne gémit, sous la hache du bûcheron, un bois de grenadiers.',
        12: 'Et la terre gémira famille par famille; la famille de la maison de David, et ses femmes à part; la famille de la maison de Nathan, et ses femmes à part;',
        13: 'La famille de la maison de Lévi, et ses femmes à part; la famille de Siméon, et ses femmes à part.',
        14: 'Et toutes les autres tribus, et leurs femmes à part.',
    },
    13: {
        1: 'En ce jour tout lieu sera ouvert à la maison de David et aux habitants de Jérusalem, pour le départ et la séparation.',
        2: 'Et ce jour-là voici ce qui arrivera, dit le Seigneur Dieu des armées: j’effacerai les noms des idoles sur la terre, et il n’y aura plus de ces noms aucun souvenir; et j’exterminerai de la terre les faux prophètes et l’esprit immonde.',
        3: 'Et voici ce qui arrivera si un homme prophétise encore, son père et sa mère qui l’ont engendré lui diront: Tu mourras, parce que tu as dit des mensonges au nom du Seigneur. Et son père et sa mère qui l’ont engendré l’empêcheront de prophétiser.',
        4: 'Et ce jour-là voici ce qui arrivera: les prophètes menteurs seront confondus, chacun par la vision même pour laquelle il aura prophétisé, et ils se ceindront de cilices de crin, parce qu’ils auront menti.',
        5: 'Et chacun d’eux dira: Je ne suis point prophète; je suis un homme travaillant à la terre, et c’est un homme qui m’a donné le jour, et m’a ainsi élevé depuis ma jeunesse.',
        6: 'Et je lui dirai: Qu’est-ce que ces plaies que tu as au milieu des mains? Et il répondra: Ce sont les plaies que j’ai reçues dans une maison bien-aimée.',
        7: 'Glaive, lève-toi contre mes pasteurs et contre l’homme qui habite ma ville, dit le Seigneur tout-puissant; frappez le berger, enlevez les brebis, et j’étendrai ma main sur les petits.',
        8: 'Et voici ce qui arrivera sur toute la terre, dit le Seigneur: j’en exterminerai deux parts, elles périront; et la troisième part sera épargnée.',
        9: 'Et je ferai passer la troisième part dans la flamme, et je la purifierai au feu, comme on purifie l’argent, et je l’éprouverai comme on éprouve l’or. Elle invoquera mon nom, et je l’exaucerai; et je dirai: Voici mon peuple; et elle dira: Le Seigneur est mon Dieu.',
    },
    14: {
        1: 'Voici que les jours du Seigneur arrivent; et tes dépouilles au milieu de toi vont être partagées.',
        2: 'Et je rassemblerai toutes les nations pour qu’elles combattent contre Jérusalem; et la ville sera prise, et les maisons seront livrées au pillage, et les femmes seront profanées; et la moitié des habitants sera emmenée captive, et le reste de mon peuple ne sera point massacré dans la ville.',
        3: 'Et le Seigneur sortira et il combattra les gentils, comme il combat au jour de la bataille.',
        4: 'Et ce jour-là ses pieds poseront sur la montagne des Oliviers, vis-à-vis Jérusalem, du côté de l’Orient. Et la montagne des Oliviers se fendra, moitié vers l’Orient, moitié du côté de la mer; il y aura entre les deux moitiés un immense ravin. Et l’une des deux moitiés s’inclinera au nord, et l’autre au midi.',
        5: 'Et la gorge de mes montagnes se fermera; et la gorge des montagnes sera resserrée jusqu’à Jasod, et elle sera close comme elle l’a été du temps du tremblement de terre, durant les jours d’Ozias, roi de Juda. Et le Seigneur mon Dieu viendra, et tous ses saints avec lui.',
        6: 'Et voici ce qui arrivera: en ce jour-là il n’y aura point de lumière, mais du froid et de la gelée, qui',
        7: 'Dureront tout le jour; et ce jour-là sera connu du Seigneur, et ce ne sera pas le jour, et ce ne sera pas la nuit; et, sur le soir, il y aura une lumière.',
        8: 'Et ce jour-là une eau vive sortira de Jérusalem, et la moitié coulera à la première mer, et l’autre moitié à la dernière; et il en sera ainsi pendant le printemps et l’été.',
        9: 'Et le Seigneur sera roi de toute la terre; et ce jour-là le Seigneur sera le seul Dieu, et son nom sera UN,',
        10: 'Tout autour de la terre et du désert de Gaza à Remmon, au midi de Jérusalem. Rama subsistera où il est, de la porte de Benjamin à la place de l’ancienne porte, et à la porte des Angles, et de la tour d’Anaméel aussi loin que les pressoirs du roi.',
        11: 'Jérusalem sera repeuplée; elle ne sera plus frappée d’anathème, et elle sera assise en assurance.',
        12: 'Et voici le fléau dont le Seigneur frappera tous les peuples qui auront marché contre elle. Leurs chairs se liquéfieront, eux debout sur leurs pieds; leurs yeux s’écouleront hors de leurs orbites, et leur langue se liquéfiera dans leur bouche.',
        13: 'Et ce jour-là voici ce qui arrivera: il y aura contre eux un grand transport du Seigneur; et ils se prendront par la main les uns les autres, et les mains entrelaceront les mains.',
        14: 'Et Juda se rangera en bataille contre Jérusalem; et on recueillera les richesses de tous les peuples d’alentour, l’or, l’argent et des vêtements innombrables.',
        15: 'Et les chevaux, les mulets, les chameaux, les ânes et toutes les bêtes qui seront dans les camps seront pareillement détruits.',
        16: 'Voici ce qui arrivera: les survivants parmi les gentils qui auront marché contre Jérusalem Y monteront chaque année pour y adorer le Roi, Seigneur tout-puissant, et pour célébrer la fête des Tabernacles.',
        17: 'Et voici ce qui arrivera: si de toutes les tribus de la terre on ne monte pas à Jérusalem pour adorer le Roi, Seigneur tout-puissant, ceux qui s’en abstiendront seront pareillement punis.',
        18: 'Et s’il est une des tribus de l’Égypte qui ne monte pas au temple, les mêmes fléaux l’atteindront; elle sera frappée comme toutes les nations qui ne viendront pas célébrer la fête des Tabernacles.',
        19: 'Ce sera le péché de l’Égypte, et le péché de toutes les nations qui ne viendront pas célébrer la fête des Tabernacles.',
        20: 'Et ce jour-là tout ce qui orne le frein des chevaux sera consacré au Seigneur tout-puissant; les chaudières seront dans le temple du Seigneur comme les coupes devant l’autel.',
        21: 'Et toutes les chaudières de Jérusalem et de Juda seront consacrées au Seigneur tout-puissant. Et tous ceux qui offriront des sacrifices viendront, et ils prendront de ces chaudières, et ils s’en serviront pour faire cuire les victimes; et ce jour-là il n’y aura plus de Chananéens dans la maison du Seigneur tout-puissant.',
    },
}
