NAME = 'Alb: Albanian Bible'
BOOK = 'II Timothy'

CHAPTERS = {
    1: {
        1: 'Pali, apostulli i Jezu Krishtit nëpërmjet vullnetit të Perëndisë, sipas premtimit të jetës që është në Krishtin Jezus,',
        2: 'Timoteut, birit të dashur: hir, mëshirë dhe paqe prej Perëndisë Atit, dhe prej Krishtit Jezus, Zotit tonë.',
        3: 'E falënderoj Perëndinë, të cilit i shërbej sikurse edhe të parët e mi me ndërgjegje të pastër, se pa pushim të kujtoj në lutjet e mia, ditë e natë;',
        4: 'dhe, kur kujtoj lotët e tu, kam shumë mall të të shoh që të mbushem me gëzim,',
        5: 'sepse kujtoj besimin e sinqertë që është në ty, i cili më parë ishte te gjyshja jote Loide dhe te nëna jote Eunike, dhe jam i bindur se është edhe te ti.',
        6: 'Për këtë arsye po të kujtoj ta zgjosh dhuntinë e Perëndisë që është në ty me anë të vënies së duarve të mia.',
        7: 'Sepse Perëndia nuk na ka dhënë frymë frike, por force, dashurie dhe urtësie.',
        8: 'Mos ki turp, pra, të dëshmosh Zotin tonë, as mua, të burgosurin e tij, por hiq keq bashkë me mua për ungjillin, sipas fuqisë së Perëndisë,',
        9: 'që na shpëtoi dhe na thirri me një thirrje të shenjtë, jo sipas veprave tona, por sipas qëllimit të tij dhe sipas hirit, që na u dha në Krishtin Jezus përpara fillimit të kohëve',
        10: 'dhe tani u shfaq me anë të dukjes së Shpëtimtarit tonë Jezu Krishtit, që e prishi vdekjen dhe nxori në dritë jetën dhe pavdekësinë me anë të ungjillit,',
        11: 'për të cilin unë u caktova predikues, apostull dhe mësues i johebrenjve.',
        12: 'Për këtë arsye unë po vuaj edhe nga këto gjëra, po nuk kam turp, sepse e di kujt i kam besuar dhe jam i bindur se ai është i zoti ta ruajë visarin tim deri në atë ditë.',
        13: 'Ruaje modelin e fjalëve të shëndosha që dëgjove prej meje me besim dhe dashuri, që janë në Krishtin Jezus.',
        14: 'Ruaje visarin e mirë me anë të Frymës së Shenjtë që rri te ne.',
        15: 'Ti e di se të gjithë ata që janë në Azi më kthyen krahët, dhe midis tyre Figeli dhe Hermogeni.',
        16: 'Zoti i dhëntë mëshirë familjes së Onesiforit, sepse shpeshherë më dha zemër dhe nuk pati turp nga prangat e mia;',
        17: 'madje, kur erdhi në Romë, më kërkoi me shumë zell dhe më gjeti.',
        18: 'Zoti i dhëntë të gjejë mëshirë nga ana e Zotit në atë ditë. Ti e di më mirë se askush sa shërbime më bëri në Efes.',
    },
    2: {
        1: 'Ti, pra, biri im, forcohu në hirin që është në Krishtin Jezus;',
        2: 'dhe ato që dëgjove nga unë përpara shumë dëshmitarëve, jepua njerëzve besnikë, që do të jenë të aftë të mësojnë edhe të tjerë.',
        3: 'Ti, pra, duro pjesën tënde të vuajtjeve, si një ushtar i mirë i Jezu Krishtit.',
        4: "Sepse asnjë nga ata që shkojnë ushtarë nuk ngatërrohet me punërat e jetës, që t'i pëlqejë atij që e mori ushtar.",
        5: 'Po ashtu, nëse dikush merr pjesë në gara, nuk kurorëzohet po të mos ketë luftuar sipas rregullave.',
        6: 'Bujku që mundohet duhet ta marrë i pari pjesën e fryteve.',
        7: 'Mendo për ato që të them, sepse Zoti do të të japë mend për të gjitha.',
        8: 'Kujto që Jezu Krishti, nga fisi i Davidit, u ngjall së vdekuri sipas ungjillit tim,',
        9: 'për të cilin unë po vuaj deri edhe në pranga posi keqbërës; por fjala e Perëndisë nuk lidhet në pranga.',
        10: 'Prandaj unë i duroj të gjitha për shkak të të zgjedhurve, që ata të kenë shpëtimin që është në Krishtin Jezus, bashkë me lavdi të përjetshme.',
        11: 'Kjo fjalë është e vërtetë, sepse, nëse ne vdiqëm me të, me të edhe do të rrojmë;',
        12: 'në qoftë se vuajmë, do të mbretërojmë bashkë me të; po ta mohojmë, edhe ai do të na mohojë.',
        13: 'Nëse jemi të pabesë, ai mbetet besnik, sepse ai nuk mund të mohojë vetveten.',
        14: 'Ua kujto atyre këto gjëra, duke u përbetuar përpara Zotit të mos hahen kot me fjalë pa asnjë dobi, në dëm të atyre që dëgjojnë.',
        15: 'Mundohu të dalësh përpara Perëndisë si i sprovuar, si punëtor që nuk ka pse të turpërohet, që thotë drejt fjalën e së vërtetës.',
        16: 'Shmangu nga fjalët e kota dhe profane, sepse do të çojnë në pabesi,',
        17: 'dhe fjala e tyre do të brejë si një gangrenë; ndër këta janë Himeneu dhe Fileti,',
        18: 'të cilët dolën jashtë rrugës së të vërtetës, duke thënë se ringjallja ka ngjarë dhe përmbysin besimin e disave.',
        19: 'Megjithatë themeli i fortë i Perëndisë qëndron i patundur, dhe ka këtë vulë: "Zoti i njeh të vetët", dhe: "Le t\'i largohet paudhësisë kushdo që përmend emrin e Krishtit".',
        20: 'Në një shtëpi të madhe nuk ka vetëm enë prej ari dhe argjendi, por edhe prej druri dhe balte; disa për të nderuar; të tjerat për të mos nderuar.',
        21: 'Pra, në qoftë se dikush pastrohet nga këto gjëra, do të jetë një enë nderi, e shenjtëruar dhe e dobishme për të zotin, e përgatitur për çdo vepër të mirë.',
        22: 'Largohu nga pasionet rinore dhe bjeru pas drejtësisë, besimit, dashurisë dhe paqes bashkë me ata që e thërresin në ndihmë Zotin me zemër të pastër.',
        23: 'Shmang gjithashtu diskutimet e marra dhe pa mend, duke ditur se shkaktojnë grindje.',
        24: 'Sepse shërbëtori i Zotit nuk duhet të zihet, por të jetë i butë me të gjithë, i aftë për të mësuar njerëzit dhe i durueshëm,',
        25: 'duke i mësuar me butësi kundërshtarët, me shpresë se Perëndia ua jep atyre të pendohen, që arrijnë të njohin të vërtetën,',
        26: 'dhe të vijnë në vete, duke shpëtuar nga laku i djallit, që i ka zënë robër të vullnetit të tij.',
    },
    3: {
        1: 'Dhe dije këtë: në ditët e fundit do të vijnë kohë të vështira,',
        2: 'sepse njerëzit do të jenë egoistë, lakmues parash, mburravecë, krenarë, blasfemues, të pabindur ndaj prindërve, mosmirënjohës, të paudhë,',
        3: "të padhembshur, të papajtueshëm, shpifës, të papërmbajtur, mizorë, që s'e duan të mirën,",
        4: 'tradhtarë, kokëshkretë, fodullë, dëfrimdashës më fort se perëndidashës,',
        5: 'të perëndishëm në dukje, por mohues të fuqisë së saj; edhe nga këta largohu.',
        6: 'Sepse prej këtyre janë ata që futen nëpër shtëpi dhe i bëjnë për vete femrat e ngarkuara me mëkate, të sunduara nga pasione të ndryshme,',
        7: 'të cilat mësojnë gjithnjë dhe kurrë nuk mund të arrijnë në njohjen e plotë të së vërtetës.',
        8: 'Dhe sikurse Janesi dhe Jambresi i kundërshtuan Moisiut, po kështu edhe këta i kundërvihen së vërtetës; janë njerëz mendjeprishur, të neveritshëm në çështjen e besimit.',
        9: 'Por këta nuk do të shkojnë shumë përpara, sepse marrëzia e tyre do të dalë në shesh për të gjithë, ashtu sikurse u ngjau edhe atyre.',
        10: 'Dhe ti ndoqe nga afër mësimin tim, sjelljen, këshillat, besimin, durimin, dashurinë, ngulmin,',
        11: 'përndjekjet, vuajtjet që më ndodhën në Antioki, në Ikonio, dhe në Listra; ti e di çfarë përndjekjesh hoqa, por Perëndia më shpëtoi nga të gjitha.',
        12: 'Të gjithë ata që duan të rrojnë me perëndishmëri në Krishtin Jezus do të përndiqen,',
        13: 'por njerëzit e këqij dhe mashtrues do të shkojnë keq e më keq, duke gënjyer dhe duke u gënjyer vetë.',
        14: 'Por ti qëndro në ato që mësove dhe u binde plotësisht, duke e ditur prej kujt i mësove,',
        15: 'dhe se që nga fëmijëria i njeh Shkrimet e shenjta, të cilat mund të të bëjnë të ditur për shpëtimin me anë të besimit që është në Krishtin Jezus.',
        16: 'I gjithë Shkrimi është i frymëzuar nga Perëndia dhe i dobishëm për mësim, bindje, ndreqje dhe për edukim me drejtësi,',
        17: 'që njeriu i Perëndisë të jetë i përkryer, tërësisht i pajisur për çdo vepër të mirë.',
    },
    4: {
        1: 'Po të përbej, pra, përpara Perëndisë dhe Zotit Jezu Krisht, që ka për të gjykuar të gjallë e të vdekur, në dukjen e tij dhe në mbretërinë e tij:',
        2: 'prediko fjalën, ngul këmbë me kohë e pa kohë, kritiko dhe qorto, këshillo me çdo durim e doktrinë.',
        3: 'Sepse do të vijë koha kur njerëzit nuk do ta durojnë doktrinën e shëndoshë, por, sipas ëndjeve të veta, do të mbledhin grumbull mësues për të gudulisur veshët',
        4: "dhe do t'i largojnë veshët nga e vërteta e do t'i sjellin drejt përrallave.",
        5: 'Por ti rri syçelë në çdo gjë, duro vuajtjet, kryeje punën e ungjilltarit, përmbushe plotësisht shërbesën tënde.',
        6: 'Sa për mua, po derdhem si ofertë pije, dhe koha e nisjes sime arriti.',
        7: 'Luftën e mirë e luftova, e përfundova vrapimin, e ruajta besimin.',
        8: 'Pas kësaj më pret gati kurora e drejtësisë që Perëndia, gjykatësi i drejtë, do të ma japë atë ditë, dhe jo vetëm mua, por edhe gjithë atyre që presin me dashuri të shfaqurit e tij.',
        9: 'Përpiqu të vish shpejt tek unë,',
        10: 'sepse Dema më la, sepse deshi këtë botë, dhe iku në Thesaloniki; Kreshenci në Galati, Titi në Dalmaci.',
        11: 'Me mua është vetëm Lluka; merre Markun dhe sille me vete, sepse e kam shumë të dobishëm për shërbesë.',
        12: 'Tikikun e dërgova në Efes.',
        13: 'Kur të vish, sill mantelin që lashë në Troadë, pranë Karpit, dhe librat, sidomos pergamenat.',
        14: 'Aleksandri, remtari, më bëri shumë të këqija; Zoti ia shpagoftë sipas veprave të tij.',
        15: 'Ruaju edhe ti prej tij, sepse ka qenë kundërshtar i madh i fjalëve tona.',
        16: 'Në mbrojtjen time të parë në gjyq askush nuk qe me mua, por të gjithë më lanë; kjo të mos u numërohet për faj.',
        17: 'Por Zoti më ndenji pranë dhe më dha fuqi, që me anën time predikimi i ungjillit të kryhej plotësisht dhe ta dëgjonin të gjithë johebrenjtë; dhe unë shpëtova nga goja e luanit.',
        18: 'Edhe Zoti do të më shpëtojë nga çdo vepër e keqe dhe do të më ruajë për mbretërinë e tij qiellore. Lavdi atij në shekuj të shekujve. Amen.',
        19: 'Të fala Prishilës dhe Akuilës dhe shtëpisë së Onesiforit.',
        20: 'Erasti mbeti në Korint, por Trofimin e lashë të sëmurë në Milet.',
        21: 'Përpiqu të vish përpara dimrit. Të përshëndetin Eubuli, Pudenti, Lini, Klaudja dhe të gjithë vëllezërit.',
        22: 'Zoti Jezu Krisht qoftë me frymën tënde! Hiri qoftë me ju! Amen.',
    },
}
