NAME = 'GerAlbrecht: German Albrecht Neues Testament und Psalmen'
BOOK = 'I John'

CHAPTERS = {
    1: {
        1: 'Was von Anfang war, was wir gehört und mit Augen gesehen, was wir geschaut und mit Händen betastet haben, das berichten wir von dem Wort des Lebens.',
        2: 'Ja, das Leben ist erschienen, und jenes ewige Leben, das bei dem Vater war und uns offenbar geworden ist, das haben wir gesehen, das bezeugen und verkünden wir euch.',
        3: 'Was wir gesehen und gehört, das verkündigen wir auch euch, damit auch ihr mit uns Gemeinschaft habt. Aber diese Gemeinschaft mit uns ist auch eine Gemeinschaft mit dem Vater und mit seinem Sohn Jesus Christus.',
        4: 'Dies schreiben wir, damit unsere Freude vollkommen sei.',
        5: 'Dies ist die Botschaft, die wir von ihm gehört und euch verkünden: "Gott ist Licht, und in ihm ist keine Finsternis."',
        6: 'Behaupten wir, wir haben Gemeinschaft mit ihm, und wandeln trotzdem in der Finsternis, so lügen wir und betätigen die Wahrheit nicht.',
        7: 'Wandeln wir aber im Licht, wie er im Licht ist, so haben wir Gemeinschaft miteinander, und das Blut Jesu, seines Sohnes, reinigt uns von jeder Sünde.',
        8: 'Behaupten wir: wir haben keine Sünde, so betrügen wir uns selbst, und die Wahrheit wohnt nicht in uns.',
        9: 'Bekennen wir aber unsere Sünden, dann ist er treu und gerecht, so daß er uns die Sünden erläßt und uns reinigt von jeglichem Unrecht.',
        10: 'Behaupten wir: wir haben nicht gesündigt, so machen wir ihn zum Lügner, und sein Wort wohnt nicht in uns.',
    },
    2: {
        1: 'Meine lieben Kinder! Dies schreibe ich euch, damit ihr nicht sündigt. Und sündigt doch jemand, so haben wir einen Fürsprecher bei dem Vater: Jesus Christus, den Gerechten.',
        2: 'Der ist die Sühne für unsere Sünden, und nicht für unsere allein, sondern auch für die Sünden der ganzen Welt.',
        3: 'Dies ist das Merkmal, daß wir ihn erkannt: wir halten seine Gebote.',
        4: 'Wer behauptet: "Ich habe ihn erkannt" und seine Gebote nicht hält, der lügt; in solchem Menschen wohnt nicht die Wahrheit.',
        5: 'Wer aber seinem Wort gehorcht, in dem ist wirklich die Liebe zu Gott vollkommen geworden. Daran zeigt sich, daß wir in ihm sind.',
        6: 'Wer da behauptet, er bleibe in ihm, der muß auch wandeln, wie Er gewandelt.',
        7: 'Geliebte, nicht ein neues Gebot schreibe ich euch nun, sondern ein altes Gebot, das ihr gehabt von Anfang an. Dies alte Gebot ist jenes Wort, das ihr bereits gehört.',
        8: 'Und doch schreibe ich euch ein neues Gebot; das ist es wirklich im Blick auf ihn und auf euch. Denn die Finsternis ist im Schwinden begriffen, und das wahre Licht hat zu leuchten begonnen.',
        9: 'Wer nun behauptet, er sei im Licht, und doch seinen Bruder haßt, der ist noch immer in Finsternis.',
        10: 'Wer seinen Bruder liebhat, der ist fort und fort im Licht, und in seinem Geist ist nichts, das ihn zu Fall bringen könnte.',
        11: 'Wer aber seinen Bruder haßt, der lebt in der Finsternis und wandelt in der Finsternis und weiß nicht, wohin er geht; denn die Finsternis hat seine Augen blind gemacht.',
        12: 'Ich schreibe euch, liebe Kinder, weil euch die Sünden um seines Namens willen vergeben sind.',
        13: 'Ich schreibe euch, ihr Väter, weil ihr den erkannt habt, der von Anfang ist. Ich schreibe euch, ihr Jünglinge, weil ihr den Bösen überwunden habt.',
        14: 'Ich habe euch geschrieben, liebe Kinder, weil ihr den Vater erkannt habt, der von Anfang ist. Ich habe euch, ihr Jünglinge, geschrieben, weil ihr stark seid durch das Wort Gottes unablässig in euch wohnt und ihr den Bösen überwunden habt.',
        15: 'Habt nicht lieb die Welt, noch was in der Welt ist! Wer die Welt liebhat, in dem wohnt nicht die Liebe zum Vater.',
        16: 'Denn alles weltliche Wesen — die Fleischeslust, die Augenlust und das großtuerische Leben — stammt nicht von dem Vater, sondern von der Welt.',
        17: 'Und die Welt fährt dahin mit ihrer Lust; wer aber den Willen Gottes tut, der bleibt in Ewigkeit.',
        18: 'Kinder! Die letzte Stunde ist da! Ihr habt gehört, ein Widerchrist soll kommen. Jetzt aber sind schon Widerchristen in großer Anzahl aufgetreten. Daran erkennen wir: die letzte Stunde ist da.',
        19: 'Sie sind aus unserer Mitte hervorgegangen, aber sie haben uns innerlich nicht angehört. Denn hätten sie uns angehört, so wären sie bei uns geblieben. Doch sie haben uns verlassen, damit es sich zeige, daß nicht alle zu uns gehören.',
        20: 'Ihr aber habt die Salbung von dem Heiligen empfangen und wißt alles.',
        21: 'Ich habe euch nicht geschrieben, weil ihr sie kennt und deshalb auch wissen müßt, daß keine Lüge aus der Wahrheit kommt.',
        22: 'Wer sonst ist der Lügner, als der da leugnet, Jesus sei auch der Christus? Ein solcher Leugner ist der Widerchrist: er leugnet den Vater und den Sohn.',
        23: 'Jeder, der den Sohn leugnet, hat auch den Vater nicht. Wer den Sohn bekennt, der hat auch den Vater.',
        24: 'Was ihr von Anfang an gehört, das soll in euern Herzen bleiben! Bleibt aber das in euch, was ihr von Anfang an gehört, so werdet auch ihr in dem Sohn und dem Vater bleiben.',
        25: 'Und dies hat er selbst uns verheißen: das ewige Leben.',
        26: 'So viel schreibe ich über die, die euch verführen wollen.',
        27: "Und die Salbung, die ihr von ihm empfangen habt, die bleibt in euch. Ihr habt nicht nötig, daß euch jemand belehre. Sondern wie euch seine Salbung über alles belehrt, so ist's auch wahr und keine Lüge. Wie sie euch belehrt, so bleibt in ihm!",
        28: 'Nun, liebe Kinder, bleibt in ihm! Dann haben wir, wenn er erscheint, auch freudige Zuversicht, und wir brauchen bei seiner Wiederkunft nicht mit Scham und Schande von ihm zu weichen.',
        29: 'Wenn ihr wißt, daß er gerecht ist, so bedenkt auch: jeder, der Gerechtigkeit übt, ist aus ihm erzeugt.',
    },
    3: {
        1: 'Seht, welch große Liebe hat uns der Vater bewiesen! Wir sollen Gottes Kinder heißen und sind es auch. Darum erkennt die Welt uns nicht, denn sie hat ihn nicht erkannt.',
        2: 'Geliebte, jetzt schon sind wir Gottes Kinder. Aber es ist noch nicht offenbar geworden, was wir sein sollen. Wir wissen jedoch: wenn er erscheint, so werden wir ihm ähnlich sein; denn wir werden ihn sehen.',
        3: 'Wer solche Hoffnung hat im Vertrauen auf ihn, der reinigt sich, wie Er rein ist.',
        4: 'Wer die Sünde tut, der frevelt auch gegen das Gesetz; denn die Sünde ist Gesetzlosigkeit.',
        5: 'Ihr wißt aber: Er ist erschienen, um die Sünden zu tilgen, und in ihm ist keine Sünde.',
        6: 'Wer in ihm bleibt, der sündigt nicht. Wer sündigt, der hat ihn nicht gesehen noch erkannt.',
        7: 'Liebe Kinder, laßt euch von niemand irreführen. Wer Gerechtigkeit übt, der ist gerecht, wie Er gerecht ist.',
        8: 'Wer die Sünde tut, der stammt vom Teufel; denn der Teufel sündigt von Anfang an. Dazu ist Gottes Sohn erschienen, daß er des Teufels Werke zerstöre.',
        9: 'Jeder, der aus Gott gezeugt ist, tut keine Sünde; denn sein Same bleibt in ihm. Ja er kann nicht sündigen, denn er ist aus Gott gezeugt.',
        10: 'Daran erkennt man Gottes Kinder und des Teufels Kinder. Jeder, der nicht Gerechtigkeit übt, stammt nicht von Gott, ebenso auch, wer seinen Bruder nicht liebt.',
        11: 'Denn dies ist die Botschaft, die ihr von Anfang an gehört: wir sollen einander lieben.',
        12: 'Wir sollen nicht Kain gleichen, der von dem Bösen stammte und seinen Bruder mordete. Und warum hat er ihn ermordet? Weil seine Taten böse waren, seines Bruders Taten aber gerecht.',
        13: 'Wundert euch nicht, meine Brüder, wenn die Welt euch haßt.',
        14: 'Wir wissen: wir sind aus dem Tod zum Leben gelangt, weil wir die Brüder lieben. Wer keine Liebe hat, der bleibt im Tod.',
        15: 'Wer seinen Bruder haßt, der ist ein Mörder; und ihr wißt: in einem Mörder wohnt nicht das ewige Leben.',
        16: "Daran haben wir das wahre Wesen der Liebe erkannt, daß Er sein Leben zu unserem Heil dahingegeben hat. So ist's auch unsere Pflicht, unser Leben zum Besten der Brüder einzusetzen.",
        17: 'Wer irdische Güter hat und seinen Bruder Not leiden sieht, aber sein Herz vor ihm verschließt: wie kann in dem die Liebe zu Gott noch wohnen?',
        18: 'Liebe Kinder, laßt uns nicht lieben mit Worten und mit der Zunge, sondern mit der Tat und in Wahrheit!',
        19: 'Daran werden wir dann auch erkennen, daß wir aus der Wahrheit sind, und dadurch können wir unser Herz vor seinem Angesicht zur Ruhe bringen,',
        20: 'daß wir bedenken, wenn unser Herz uns anklagt: Gott ist größer als unser Herz, und er weiß alles.',
        21: 'Geliebte, wenn unser Herz uns nicht anklagt, so haben wir freudige Zuversicht zu Gott.',
        22: 'Und was wir erbitten, das empfangen wir auch von ihm; denn wir halten seine Gebote und tun, was ihm wohlgefällig ist.',
        23: 'Und dies ist sein Gebot: Wir sollen glauben an den Namen seines Sohnes Jesus Christus und einander lieben, wie er uns geboten.',
        24: 'Wer seine Gebote hält, der bleibt in ihm und er in ihm. Und daß er bleibend in uns wohnt, erkennen wir an dem Geist, den er uns gegeben.',
    },
    4: {
        1: 'Geliebte, schenkt nicht jedem Geist Glauben! Prüft vielmehr die Geister, ob sie aus Gott sind! Denn viele Lügenpropheten sind ausgezogen in die Welt.',
        2: 'Daran erkennt Gottes Geist: Jeder Geist, der Jesus Christus als den im Fleisch Erschienenen bekennt, der ist aus Gott.',
        3: 'Doch jeder Geist, der Jesus nicht bekennt, ist nicht aus Gott: das ist der Geist des Widerchrists. Ihr habt gehört, daß er kommt; und er ist schon jetzt in der Welt.',
        4: 'Ihr seid aus Gott, liebe Kinder, und habt sie überwunden. Denn der in euch wirkt, ist stärker, als der in der Welt sein Wesen treibt.',
        5: 'Sie gehören der Welt an. Darum reden sie nach Art der Welt, und die Welt hört auf sie.',
        6: 'Wir sind von Gott gesandt. Wer Gott erkennt, der hört auf uns. Wer nicht aus Gott ist, der hört nicht auf uns. Hieran erkennen wir den Geist der Wahrheit und den Geist des Irrtums.',
        7: 'Geliebte, laßt uns einander lieben! Denn die Liebe stammt von Gott, und wer Liebe hat, der ist aus Gott erzeugt und erkennt Gott.',
        8: 'Wer keine Liebe hat, der hat Gott nicht erkannt; denn Gott ist Liebe.',
        9: 'Dadurch ist Gottes Liebe bei uns offenbar geworden, daß Gott seinen eingeborenen Sohn gesandt hat in die Welt, damit wir durch ihn das Leben hätten.',
        10: 'Darin zeigt sich die (wahre) Liebe: nicht wir haben Gott geliebt, sondern er hat uns geliebt und seinen Sohn gesandt als Sühne für unsere Sünden.',
        11: 'Geliebte, hat uns Gott so sehr geliebt, dann müssen auch wir einander lieben.',
        12: 'Keiner hat Gott je gesehen. Lieben wir aber einander, so wohnt Gott bleibend in uns, und seine Liebe ist in uns vollkommen.',
        13: 'Daß wir aber bleibend in ihm wohnen und er in uns, erkennen wir daran, daß er uns von seinem Geist gegeben hat.',
        14: 'Und wir haben gesehen und bezeugen, daß der Vater den Sohn gesandt hat als Heiland der Welt.',
        15: 'Wer nun bekennt, daß Jesus Gottes Sohn ist, in dem bleibt Gott und er in Gott.',
        16: 'Wir haben erkannt und geglaubt die Liebe, die Gott zu uns hat. Gott ist Liebe; und wer in der Liebe bleibt, der bleibt in Gott, und Gott bleibt auch in ihm.',
        17: 'Darin vollendet sich bei uns die Liebe, daß wir freudige Zuversicht haben am Tag des Gerichts; denn so, wie Er ist, so sind auch wir in dieser Welt.',
        18: 'Furcht ist nicht in der Liebe; die vollkommene Liebe vertreibt die Furcht. Die Furcht denkt ja an Strafe. Wer sich also fürchtet, der ist in der Liebe noch nicht vollkommen.',
        19: 'Wir lieben, weil Gott uns zuerst geliebt.',
        20: 'Wer da behauptet: "Ich liebe Gott", und doch seinen Bruder haßt, der ist ein Lügner. Denn wer seinen Bruder nicht liebt, den er leibhaftig sieht, der kann Gott, den er gar nicht sieht, unmöglich lieben.',
        21: 'Ja, dies Gebot haben wir von ihm: Wer Gott liebt, der muß auch seinen Bruder lieben.',
    },
    5: {
        1: 'Jeder, der glaubt, daß Jesus der Christus ist, der ist aus Gott gezeugt. Und wer seinen Erzeuger liebt, der liebt auch den von ihm Erzeugten.',
        2: 'Daran erkennen wir, daß wir Gottes Kinder lieben, wenn wir Gott lieben und seine Gebote erfüllen.',
        3: 'Denn darin zeigt sich die Liebe zu Gott, daß wir seine Gebote halten. Und seine Gebote sind nicht schwer.',
        4: 'Denn alles, was aus Gott erzeugt ist, überwindet die Welt. Und die Siegesmacht, die die Welt überwunden hat, ist unser Glaube.',
        5: 'Wer ist der Weltüberwinder? Nur wer da glaubt: Jesus ist Gottes Sohn.',
        6: 'Dieser hat seinen Weg genommen durch Wasser und Blut. Jesus ist als der Christus auch immer noch wirksam, nicht durch das Wasser allein, sondern durch das Wasser und das Blut. Auch der Geist legt Zeugnis für ihn ab, denn der Geist ist die Wahrheit.',
        7: "So sind's denn drei, die Zeugnis geben:",
        8: 'der Geist, das Wasser und das Blut, und diese drei bezeugen die eine Wahrheit.',
        9: 'Nehmen wir schon der Menschen Zeugnis an, so steht Gottes Zeugnis noch viel höher. Denn dies ist Gottes Zeugnis: er hat Zeugnis abgelegt von seinem Sohn.',
        10: 'Wer an den Sohn Gottes glaubt, der hat in der Gemeinschaft mit ihm dies Zeugnis. Wer Gott nicht glaubt, der hat ihn damit zum Lügner gemacht: er hat ja nicht geglaubt an das Zeugnis, das Gott von seinem Sohn abgelegt.',
        11: 'Und dies ist der Inhalt des Zeugnisses: "Gott hat uns das ewige Leben gegeben, und dieses Leben ist zu finden in der Gemeinschaft mit seinem Sohn."',
        12: 'Wer den Sohn hat, der hat das Leben. Wer den Sohn Gottes nicht hat, der hat das Leben nicht.',
        13: 'Dies schreibe ich euch, damit ihr wißt, daß ihr ewiges Leben habt: denn ihr glaubt ja an den Namen des Sohnes Gottes.',
        14: 'Dies zuversichtliche Vertrauen haben wir zu ihm: Wenn wir nach seinem Willen um etwas bitten, so erhört er uns.',
        15: 'Und wie wir wissen, daß er uns erhört auf unser Bitten, so wissen wir zugleich: wir werden das von ihm Erbetene auch sicherlich empfangen.',
        16: 'Sieht einer, daß sein Bruder eine Sünde tut, die nicht zum Tod führt, so bete er für ihn, und Gott wird diesem Bruder Leben geben — das heißt solchen, die nicht eine Sünde tun, die zum Tod führt. Es gibt wirklich Sünde, die zum Tod führt. Ich rede nicht davon, daß man bei solcher Sünde bitte.',
        17: 'Jede Ungerechtigkeit ist Sünde. Aber es gibt Sünde, die nicht zum Tod führt.',
        18: 'Wir wissen: wer aus Gott erzeugt ist, sündigt nicht; sondern der aus Gott Erzeugte ist auf seiner Hut, und der Böse tastet ihn nicht an.',
        19: 'Wir wissen: wir sind aus Gott, und die ganze Welt liegt in der Gewalt des Bösen.',
        20: 'Wir wissen aber: der Sohn Gottes ist gekommen und hat uns Verständnis gegeben, den Wahrhaftigen zu erkennen. Und wir stehen in Gemeinschaft mit dem Wahrhaftigen, weil wir in Gemeinschaft sind mit seinem Sohn Jesus Christus. Dieser ist der wahrhaftige Gott und das ewige Leben.',
        21: 'Liebe Kinder, hütet euch vor den Truggebilden!',
    },
}
