NAME = 'GerOffBiSt: Offene Bibel - Studienfassung'
BOOK = 'II Samuel'

CHAPTERS = {
    22: {
        1: 'David sprach zu JHWH die Worte dieses Lieds am Tag, als JHWH ihn rettete aus der Handfläche all seiner Feinde und aus der Handfläche Sauls.',
        2: 'Und er sagte: JHWH [ist] mein Fels und meine Burg und mein Retter,',
        3: 'Mein Gott [ist] (,) mein Berg, zu dem ich fliehe (auf den ich vertraue), Mein Schild, das Horn meiner Rettung, meine Klippe (Festung) und meine Zuflucht,Mein Retter, vor Gewalttat wirst du mich retten!',
        4: 'Als Lobenswerten will ich anrufen JHWH Und von meinen Feinden will (werde) ich gerettet werden.',
        5: 'Denn es umgaben mich Wogen des Todes,Die Flüsse Belias werden mich erschrecken!',
        6: 'Die Stricke des Scheol umfingen mich, Es ereilten mich die Schlingen des Todes.',
        7: '[Ich sprach:] „In meiner Not will ich anrufen JHWH Und meinen Gott will ich anrufen. Er soll hören in seinem Tempel meine StimmeUnd mein Schreien soll kommen in seinem Ohr!“',
        8: 'Da wankte und schwankte die ErdeUnd die Pfeiler des Himmels bebten und wanktenDenn es loderte in ihm.',
        9: 'Es stieg Rauch aus seiner NaseUnd Feuer fraß aus seinem Mund;Kohlen brannten aus ihm hervor (entbrannten durch es).',
        10: 'Und er öffnete (neigte) den Himmel und stieg herabUnd eine Wolke (Dunkelheit) [war] unter seinen Füßen.',
        11: 'Und er ritt auf einem Kerub und flogUnd schoß herab auf den Flügeln des Windes.',
        12: 'Und er setzte Dunkelheit als seine Bedeckung um sich,Seine Hütte [waren aus] Massen von Wassern in den Wolken des Himmels.',
        13: 'Aus dem Glanz vor ihm gingen ausHagel und Kohlen von Feuer.',
        14: 'Und es donnerte aus dem Himmel JHWH Und Eljon wird geben seine Stimme.',
        15: 'Und er warf Pfeile und zerstreute diese,Einen Blitz schoß er und verwirrte er.',
        16: 'Und es wurden gesehen die Betten der Wasser,Es werden bloßgelegt werden die Fundamente der Erde. Durch dein Schelten, JHWH,Durch das Schnauben des Windes deiner Nase.',
        17: '[Ich sprach:] „Er möge (wird) senden aus der Höhe, mich ergreifen,Mich herausziehen aus vielen Wassern,',
        18: 'Es möge mich retten vor meinem Feind der Starke Und vor meinen Hassern, weil sie kräftiger sind als ich!',
        19: 'Sie werden mir entgegentreten am Tag meines Unglücks!“Und JHWH war meine Stütze:',
        20: 'Er führte mich ins Weite. [Ich wusste:] „Er wird mich retten, weil er Gefallen hat an mir:',
        21: 'Es wird mich belohnen JHWH entsprechend meiner Gerechtigkeit,Entsprechend der Reinheit meiner Hände wird er mir zurückgeben,',
        22: 'Denn ich wahrte die Wege JHWH sUnd handelte nicht böse von meinem Gott,',
        23: 'Denn all seine Gesetze [waren] vor mirUnd seine Satzungen werde ich nicht von mir stoßen',
        24: 'Und ich verhielt mich gegen ihn perfektUnd ich hütete mich vor meinen Fehlern.“',
        25: 'Und es gab JHWH mir zurück entsprechend meiner Gerechtigkeit,Entsprechend meiner Reinheit vor seinen Augen.',
        26: '[Dem] Bundestreuen gegenüber wirst du dich bundestreu erweisen,Und [dem] perfekten Mann gegenüber wirst du dich perfekt erweisen,',
        27: '[Dem] Reinen gegenüber wirst du dich rein erweisen,Dem Falschen gegenüber wirst du dich verkehrt erweisen.',
        28: 'Du rettest das arme Volk,Doch die Augen Hochmütiger beugst du nieder.',
        29: 'Ja, du bist meine Lampe, JHWH, JHWH wird erhellen meine Dunkelheit.',
        30: 'Ja, mit dir werde (kann) ich überrennen (zerschmettern) eine TruppeUnd mit meinem Gott werde (kann) ich eine Mauer überspringen.',
        31: 'Gott - vollkommen [ist] sein Weg. Das Wort JHWH s ist erprobt, Ein Schild [ist] er für alle, die auf ihn vertrauen (die zu ihm flüchten).',
        32: 'Ja, wer ist Gott außer JHWH Und wer ein Berg außer unserem Gott –',
        33: 'Dem Gott, [der] mich stärkt [mit] KraftUnd der meinen Weg perfekt machte,',
        34: 'Der meinen Fuß einer Gazelle gleich machteUnd mich auf meine Höhen stellte,',
        35: 'Der meine Hände für den Kampf trainierte,Um zu stärken [wie] einen Kupferbogen meine Arme!?',
        36: 'Und du gabst mir den Schild der Rettung Und deine rechte Hand wird mich stützenUnd deine Erhörung wird mich vergrößern.',
        37: 'Du wirst weit machen meine Schritte unter mirUnd meine Knöchel wanken nicht.',
        38: 'Ich werde nachjagen meinen Feinden und sie erreichenUnd werde nicht umkehren, bis ich sie zerstört habe.',
        39: 'Ich werde sie zerschmettern und sie werden sich nicht erheben können,Sie werden unter meine Füße fallen!',
        40: 'Und du gürtetest mich mit Kraft für den Kampf,Du wirst beugen [die], die sich [gegen] mich erheben, unter mich!',
        41: 'Und meine Feinde – du gabst mir [ihren] Rücken;Meine Hasser werde ich vernichten.',
        42: 'Sie werden schreien, doch es [wird für sie] nicht geben einen Retter,Zu JHWH, aber er antwortete ihnen nicht.',
        43: 'Ich werde sie zermalmen wie Staub auf dem {Gesicht des} Weg {es},Wie Kot [auf] der Straße werde ich sie ausschütten!',
        44: 'Du wirst mich retten aus den Auseinandersetzungen des Volkes,Du wirst mich einsetzen als Haupt der Heiden,Ein Volk, [das] ich nicht kenne (kannte), wird mir dienen.',
        45: 'Auf Gehörtes des Ohrs [hin] werden sie auf mich hören, {Kinder von } Ausländer {n} werden mir [Ergebung] heucheln (mir schmeicheln),',
        46: '{Kinder von } Ausländer {n} werden vergehen Und sich [selbst] gürten mit ihren Banden.',
        47: '[So wahr] Gott lebt: Gesegnet [sei] mein FelsUnd erhoben werden soll der Gott meiner Rettung,',
        48: 'Der Gott, [der] mir Rache gab (gibt) Und Völker unter mich unterjocht hat,',
        49: 'Der mich aus meinen Feinden herausholt,Mich erhöhen wird über die, die sich gegen mich erheben,Der du mich von dem gewalttätigen Mann befreien wirst.',
        50: 'Darum will ich dich preisen, JHWH, [mitten] unter den Heiden,Und deinem Namen singen,',
        51: 'Der groß macht das Heil (der ein Turm des Heils [ist] für) seines KönigsUnd seinem Gesalbten Bundestreue erweist,David und seinen Nachkommen auf ewig.',
    },
}
