NAME = 'ACV: A Conservative Version'
BOOK = 'Ephesians'

CHAPTERS = {
    1: {
        1: 'Pavel, apostol Kristusa Jezusa po volji Božji, svetim, ki so v Efezu, in vernim v Kristusu Jezusu:',
        2: 'Milost vam in mir od Boga Očeta našega in Gospoda Jezusa Kristusa!',
        3: 'Hvaljen bodi Bog in Oče Gospoda našega Jezusa Kristusa, ki nas je blagoslovil z vsakim blagoslovom duhovnim v nebesih v Kristusu;',
        4: 'kakor nas je izvolil v njem pred ustanovitvijo sveta, da bodimo sveti in brezmadežni pred obličjem njegovim v ljubezni,',
        5: 'odmenivši nas naprej za sinovstvo po Jezusu Kristusu za sebe, kakor je ugajalo volji njegovi,',
        6: 'v hvalo slave milosti svoje, s katero nas je pomilostil v svojem Ljubljencu.',
        7: 'V katerem imamo odrešenje po krvi njegovi, odpuščenje grehov, po bogastvu milosti njegove,',
        8: 'katere nam je preobilo podelil v vsej modrosti in razumnosti,',
        9: 'razodevši nam skrivnost volje svoje po blagovoljnem sklepu svojem, ki ga je sklenil v sebi',
        10: 'za uravnavo izpolnitve časov, da vse zedini pod eno glavo v Kristusu, kar je na nebesih in kar je na zemlji, v njem,',
        11: 'v katerem smo tudi dobili delež kot naprej odmenjeni po sklepu njega, ki vse dela po ukrepu volje svoje,',
        12: 'da bodimo v hvalo slave njegove, ki smo prej stavili upanje v Kristusa.',
        13: 'V katerem ste tudi vi, ko ste slišali besedo resnice, evangelij zveličanja svojega, v katerem ste tudi, sprejemši vero, bili zapečateni s svetim Duhom obljube,',
        14: 'ki je zastava dediščine naše, v odrešitev lastnine božje, v hvalo slave njegove.',
        15: 'Zatorej se tudi jaz, ko sem zvedel za vero, ki je pri vas v Gospoda Jezusa, in za ljubezen do vseh svetih,',
        16: 'zahvaljujem neprestano za vas, spominjajoč se vas v molitvah svojih,',
        17: 'da vam dá Bog Gospoda našega Jezusa Kristusa, Oče slave, duha modrosti in razodetja v spoznanju njegovem,',
        18: 'razsvetljene oči srca vašega, da veste, kakšno je upanje poklica njegovega in kakšno bogastvo slave dediščine njegove v svetih,',
        19: 'in kakšna presilna velikost moči njegove do nas verujočih po delovanju silne moči njegove,',
        20: 'ki jo je pokazal v Kristusu, zbudivši ga izmed mrtvih in posadivši ga na desnico svojo v nebesih,',
        21: 'nad vsako poglavarstvo in oblast in moč in gospostvo, in nad vsako ime, ki se imenuje ne samo na tem svetu, ampak tudi v prihodnjem;',
        22: 'in vse je položil pod noge njegove in njega je dal kot glavo nad vsem cerkvi,',
        23: 'ki je telo njegovo, izpolnitev njega, ki vse v vsem izpolnjuje.',
    },
    2: {
        1: 'Tudi vas je oživil, ki ste bili mrtvi po prestopkih in grehih,',
        2: 'v katerih ste nekdaj hodili po navadi tega sveta, po knezu oblasti v zraku, po duhu, ki deluje zdaj v sinovih nepokorščine;',
        3: 'med katerimi smo tudi mi vsi nekdaj živeli v poželjivostih mesa svojega ter delali želje mesa in misli, in bili smo po naravi otroci jeze Božje, kakor tudi drugi.',
        4: 'Bog pa, bogat v usmiljenju, zaradi velike ljubezni svoje, ki nas je ž njo ljubil,',
        5: 'nas je, ko smo tudi bili mrtvi po grehih, oživil s Kristusom vred (po milosti ste rešeni)',
        6: 'in ž njim vred obudil in posadil v nebesih v Kristusu Jezusu,',
        7: 'da pokaže v prihodnjih vekih presilno bogastvo milosti svoje v dobrotljivosti do nas v Kristusu Jezusu.',
        8: 'Kajti iz milosti ste rešeni po veri, in to ni iz vas, dar Božji je to;',
        9: 'ne iz del, da se nihče ne hvali.',
        10: 'Njegovo namreč smo delo, ustvarjeni v Kristusu Jezusu za dobra dela, ki jih je Bog naprej pripravil, da živimo v njih.',
        11: 'Zatorej pomnite, da ste bili nekdaj vi, pogani v mesu, ki jih imenuje neobrezo tako imenovana obreza, ki pa je le na mesu, z roko storjena,',
        12: 'da ste bili v tistem času brez Kristusa, izključeni od meščanstva Izraelovega in tujci zavezam obljube, ne imajoč upanja in brez Boga na svetu.',
        13: 'Sedaj pa, v Kristusu Jezusu, ste vi, ki ste bili nekdaj daleč, postavljeni blizu po krvi Kristusovi.',
        14: 'Kajti on je mir naš, ki je naredil iz obojega eno in podrl ločilno pregrajo',
        15: 's tem, da je v mesu svojem odpravil sovraštvo, postavo zapovedi, obseženo v poveljih, da bi ta dva v sebi ustvaril v enega novega človeka, storivši mir,',
        16: 'in oba v enem telesu z Bogom spravil po križu, umorivši sovraštvo na njem.',
        17: 'In je prišel in oznanjal mir vam, ki ste bili daleč, in mir njim, ki so bili blizu;',
        18: 'ker po njem le imamo, oboji v enem Duhu, pristop k Očetu.',
        19: 'Tako torej niste več tujci in priseljenci, marveč ste someščani svetih in domačini Božji,',
        20: 'sezidani na temelju apostolov in prorokov, vogelni kamen pa je Jezus Kristus sam,',
        21: 'v katerem je vse poslopje točno sestavljeno in raste v svet tempelj v Gospodu,',
        22: 'v katerem se tudi vi z drugimi vred vzidavate v bivališče Božje v Duhu.',
    },
    3: {
        1: 'Zategadelj jaz, Pavel, jetnik Kristusa Jezusa za vas pogane –',
        2: 'ako ste sicer slišali o oskrbništvu milosti Božje, ki mi je dana za vas,',
        3: 'da se mi je po razodetju naznanila skrivnost (kakor sem prej pisal ob kratkem,',
        4: 'iz česar morete, ko berete, spoznati razumevanje moje skrivnosti Kristusove),',
        5: 'ki se v drugih rodovih ni naznanila sinovom človeškim, kakor se je zdaj razodela svetim apostolom njegovim in prorokom po Duhu,',
        6: 'namreč, da so pogani sodediči in soudje telesa in sodeležniki obljube v Kristusu Jezusu po evangeliju,',
        7: 'katerega služabnik sem postal po daru milosti Božje, podeljene mi po delovanju moči njegove.',
        8: 'Meni najmanjšemu izmed vseh svetih je dana milost ta, oznanjati poganom nezasledljivo bogastvo Kristusovo',
        9: 'in razsvetliti vse, kakšno je oskrbovanje skrivnosti, od vekomaj skrite v Bogu, ki je vse ustvaril,',
        10: 'zato da se naznani zdaj poglavarstvom in oblastim v nebesih po cerkvi mnogotera modrost Božja,',
        11: 'po sklepu od vekomaj, ki ga je storil v Kristusu Jezusu, Gospodu našem;',
        12: 'v katerem imamo srčnost in pristop v zaupanju po veri v njega.',
        13: 'Zato prosim, da ne opešate v stiskah mojih za vas, kar je vaša čast.',
        14: 'Zategadelj pripogibljem kolena pred Očetom,',
        15: 'po katerem se imenuje sleherna rodovina v nebesih in na zemlji,',
        16: 'da vam dá po bogastvu slave svoje, da se okrepčate v moči po Duhu njegovem v notranjem človeku,',
        17: 'da se Kristus po veri vseli v srca vaša, ko ste ukoreninjeni in utrjeni v ljubezni,',
        18: 'da morete razumeti z vsemi svetimi, kaj je širjava in dolžina ter globočina in visočina,',
        19: 'in spoznati ljubezen Kristusovo, ki presega spoznanje, da se napolnite do vse polnosti Božje.',
        20: 'Njemu pa, ki more nad vso mero storiti, preobilo več nego kar prosimo ali umemo, po moči, ki deluje v nas,',
        21: 'njemu slava v cerkvi in v Kristusu Jezusu na vse rodove na vekov veke! Amen.',
    },
    4: {
        1: 'Prosim vas torej jaz, jetnik v Gospodu, da živite dostojno poklicu, ki ste ž njim bili poklicani,',
        2: 'z vso ponižnostjo in krotkostjo, s potrpežljivostjo, prenašajoč se med seboj v ljubezni,',
        3: 'skrbno si prizadevajoč, ohraniti edinost Duha v vezi miru.',
        4: 'Eno je telo in en Duh, kakor ste tudi bili poklicani v enem upanju poklica svojega;',
        5: 'en Gospod, ena vera, en krst;',
        6: 'en Bog in Oče vseh, ki je nad vsemi in po vseh in v vseh nas.',
        7: 'Vsakemu pa izmed nas je dana milost po meri daru Kristusovega.',
        8: 'Zato pravi: „Šel je v višavo, ujete pripeljal jetnike, dal je dari ljudem“.',
        9: 'Tisto pa: Šel je v višavo, kaj je drugega, nego da je tudi šel prej doli v spodnje kraje zemlje?',
        10: 'On, ki je šel doli, je tisti, ki je šel tudi gori nad vsa nebesa, da bi vse napolnil.',
        11: 'In on je dal nekatere za apostole, nekatere za proroke, nekatere za evangeliste, nekatere za pastirje in učenike,',
        12: 'v pripravo svetih, za delo službe, za zdelovanje telesa Kristusovega,',
        13: 'dokler ne dospemo vsi do edinosti vere in spoznanja Sinu Božjega, do moža doraslega, do mere dovršene rasti polnosti Kristusove,',
        14: 'da ne bodemo več deca in nas ne bo semtertja metala in gonila vsaka sapa nauka, ki prihaja po zvijačnosti ljudi, po prekanjenosti za zvito zapeljevanje;',
        15: 'temuč da rastemo, držeč se resnice v ljubezni, v vsem do njega, ki je glava, Kristus;',
        16: 'iz katerega vse telo, združeno in zedinjeno po pripomoči slehernega člena, po delovanju v meri vsakega uda rast telesa vrši v napredek svoj, v ljubezni.',
        17: 'To torej pravim in pričam v Gospodu, da ne živite več tako, kakor žive tudi pogani v ničemurnosti srca svojega,',
        18: 'otemnjeni v razumu, odtujeni življenju Božjemu zaradi nevednosti, ki je v njih, vsled otrplosti njih srca,',
        19: 'ki so se, ko so postali brezčutni, vdali razuzdanosti, da strežejo sleherni nečistosti z lakomnostjo.',
        20: 'Vi pa se niste tako naučili Kristusa,',
        21: 'ako ste ga slišali in ste bili poučeni v njem, kakor je resnica v Jezusu:',
        22: 'da ste slekli z ozirom na prejšnje življenje starega človeka, ki gine po slah prevare,',
        23: 'a da se obnavljate v duhu uma svojega,',
        24: 'in ste oblekli novega človeka, ustvarjenega po Bogu v pravičnosti in svetosti resnice.',
        25: 'Zato, iznebivši se laži, govorite resnico vsak z bližnjim svojim, ker smo udje med seboj.',
        26: 'Jezite se, a ne grešite! Solnce naj ne zaide nad jezo vašo,',
        27: 'in ne dajte prostora hudiču.',
        28: 'Kdor je kradel, ne kradi več, temuč trudi se, delajoč dobro z lastnimi rokami, da ima kaj podeliti potrebnemu.',
        29: 'Nobena gnila beseda ne izidi iz vaših ust, ampak če je katera dobra za napredek, kjer je treba, da dá milost poslušalcem.',
        30: 'In ne žalite svetega Duha Božjega, ki ste ž njim zapečateni za odrešenja dan.',
        31: 'Vsaka bridkost in srd in jeza in vpitje in preklinjanje izgini od vas z vso hudobnostjo vred.',
        32: 'Bodite pa med seboj blagi, milosrčni, odpuščajte drug drugemu, kakor je tudi Bog v Kristusu vam odpustil.',
    },
    5: {
        1: 'Bodite torej posnemalci Boga, kakor otroci ljubljeni,',
        2: 'in živite v ljubezni, kakor je tudi Kristus ljubil nas in je dal sebe za nas kot daritev in žrtev Bogu v prijetno dišavo.',
        3: 'Nesramnost pa in sleherna nečistost ali lakomnost naj se še imenuje ne med vami, kakor se spodobi svetim,',
        4: 'tudi ne nečedno vedenje in nespametne besede ali norčevanje, kar je nespodobno, ampak rajši zahvaljevanje.',
        5: 'To namreč veste, da noben nesramnik, ali nečistnik, ali lakomnik, ki je malikovalec, nima dediščine v kraljestvu Kristusovem in Božjem.',
        6: 'Nihče vas ne varaj s praznimi besedami; kajti zavoljo teh pregreh prihaja jeza Božja na sinove nepokorščine.',
        7: 'Ne bodite torej njih deležniki.',
        8: 'Bili ste namreč nekdaj tema, zdaj pa ste svetloba v Gospodu: kakor svetlobe otroci živite',
        9: '(kajti sad svetlobe je v sleherni dobroti in pravičnosti in resnici),',
        10: 'in presojajte, kaj je Gospodu po volji;',
        11: 'in ne udeležujte se nerodovitnih del teme, marveč še grajajte jih;',
        12: 'kar namreč počenjajo skrivaj, grdo je celo samo praviti to.',
        13: 'Vse to pa se razodene, ko to graja svetloba; kajti vse razodeto je svetloba.',
        14: 'Zato pravi: Zbudi se, ki spiš, in vstani izmed mrtvih, in prisveti ti Kristus.',
        15: 'Glejte torej, da živite previdno, ne kakor nemodri, ampak kakor modri,',
        16: 'in skrbno rabite čas, ker dnevi so hudi.',
        17: 'Zatorej ne bodite nespametni, marveč umejte, kaj je volja Gospodova.',
        18: 'In ne upijanjajte se z vinom, v čemer je razuzdanost, temuč napolnjujte se z Duhom,',
        19: 'govoreč med seboj v psalmih, slavospevih in pesmih duhovnih, pojoč in citrajoč s srcem svojim Gospodu,',
        20: 'zahvaljujoč se vedno za vse v imenu Gospoda našega Jezusa Kristusa Bogu in Očetu;',
        21: 'pokorni bodite drug drugemu v strahu Kristusovem.',
        22: 'Žene, svojim možem bodite pokorne kakor Gospodu;',
        23: 'kajti mož je glava ženi, kakor tudi Kristus glava cerkvi; on je tudi rešitelj telesa.',
        24: 'Ali kakor je cerkev pokorna Kristusu, tako bodite tudi žene svojim možem v vsem.',
        25: 'Možje, ljubite žene svoje, kakor je tudi Kristus ljubil cerkev in je samega sebe dal zanjo,',
        26: 'da jo posveti, očistivši jo v kopeli vode, z besedo,',
        27: 'da pripravi sam sebi slavno cerkev, ki nima madeža ali gube ali kaj enakega, ampak da bode sveta in brezmadežna.',
        28: 'Tako so možje dolžni ljubiti žene kakor telesa svoja. Kdor ljubi ženo svojo, ljubi sebe;',
        29: 'kajti nihče ni nikoli sovražil svojega mesa, temuč hrani in goji ga kakor tudi Kristus cerkev,',
        30: 'ker udje smo telesa njegovega [iz mesa njegovega in iz kosti njegovih].',
        31: '„Zato zapusti človek očeta svojega in mater svojo ter se pridruži ženi svoji, in oba bodeta eno meso“.',
        32: 'Ta skrivnost je velika: jaz pa pravim za Kristusa in za cerkev.',
        33: 'Toda tudi vi, vsak posamezni naj ljubi ženo svojo tako kakor sebe; žena pa se boj moža.',
    },
    6: {
        1: 'Otroci, bodite poslušni roditeljem svojim v Gospodu; zakaj to je pravično.',
        2: '„Spoštuj očeta svojega in mater svojo“, ta je zapoved prva z obljubo:',
        3: '„da se ti bo dobro godilo in boš dolgo živel na zemlji“.',
        4: 'In očetje, ne dražite svojih otrok, temuč vzrejajte jih v strahu in svarjenju Gospodovem.',
        5: 'Hlapci, bodite poslušni telesnim gospodarjem svojim s strahom in trepetom, v preprostosti srca svojega kakor Kristusu;',
        6: 'ne služite le na oko, kakor bi hoteli ugajati ljudem, temuč kakor hlapci Kristusovi, delajoč voljo Božjo iz duše,',
        7: 'z dobro voljo opravljajoč službo, kakor Gospodu in ne ljudem,',
        8: 'vedoč, da kar kdo stori dobrega, prejme to od Gospoda, bodisi hlapec, bodisi svobodnik.',
        9: 'In gospodarji, ravnajte istotako ž njimi in opuščajte pretenje, vedoč, da je i njih i vaš Gospod v nebesih in da licegledja ni pri njem.',
        10: 'Sicer pa, ojačite se v Gospodu in v krepkosti moči njegove.',
        11: 'Odenite se z vsem orožjem Božjim, da boste mogli stati zoper zvijačne naklepe hudičeve.',
        12: 'Kajti vojskovati se nam ni zoper kri in meso, ampak zoper poglavarstva, zoper oblasti, zoper svetovne mogočnike te teme, zoper duhovne vojske hudobnosti v nebeških prostorih.',
        13: 'Zato primite za vse orožje Božje, da se morete v bran postaviti ob hudem dnevi in, vse premagavši, stati.',
        14: 'Stojte torej, opasani okoli ledij z resnico in oblečeni z oklepom pravičnosti',
        15: 'in obuti na nogah s pripravljenostjo, oznanjati evangelij miru,',
        16: 'vrhutega zgrabite ščit vere, s katerim boste mogli pogasiti vse goreče strele Hudobnega.',
        17: 'In vzemite čelado zveličanja in meč Duha, ki je beseda Božja,',
        18: 'in s sleherno molitvijo in prošnjo molite vsak čas v Duhu in bedite za to v vsej stanovitnosti in prošnji za vse svete,',
        19: 'tudi zame, da se mi dá beseda, ko odprem usta, da s srčnostjo oznanjam skrivnost evangelija,',
        20: 'ki sem zanj poslanec v sponah, da v njem srčno govorim, kakor mi je govoriti.',
        21: 'Da pa veste tudi vi, kar zadeva mene, kako se mi godi, naznani vam vse Tihik, ljubljeni brat in zvesti služabnik v Gospodu,',
        22: 'ki sem ga poslal k vam prav zato, da zveste, kako je z nami, in da potolaži srca vaša.',
        23: 'Mir bodi bratom in ljubezen z vero od Boga Očeta in Gospoda Jezusa Kristusa!',
        24: 'Milost z vsemi, ki ljubijo Gospoda našega Jezusa Kristusa v neminljivosti!',
    },
}
