NAME = 'SweKarlXII1873: Svenska Karl XII:s Bibel (1873)'
BOOK = 'Titus'

CHAPTERS = {
    1: {
        1: 'Paulus, Guds tjenare, men Jesu Christi Apostel, till att predika Guds utvaldom trona och sanningenes kunskap, hvilken till Gudaktighet förer,',
        2: 'I hoppet till evinnerligit lif, det Gud, som icke ljuga kan, för evigt utlofvat hafver;',
        3: 'Men i sinom tid hafver han uppenbarat sitt ord genom predikan, den mig betrodd är, efter Guds vår Frälsares befallning;',
        4: 'Minom rättsinniga son Tito, efter begges våra tro: Nåd, barmhertighet, frid af Gud Fader, och Herranom Jesu Christo, vårom Frälsare.',
        5: 'Fördenskull lät jag dig qvar i Creta, att hvad som ännu fattades, skulle du fullkomliga beställa, och besätta städerna här och der med Prester, såsom jag dig befallt hafver;',
        6: 'Den som är ostraffelig, ene hustrus man; den der trogen barn hafver, oberyktad för öfverflödighet och genstörtighet.',
        7: 'Ty en Biskop bör vara ostraffelig, såsom en Guds skaffare; icke ensinnig, icke sticken, ingen drinkare, icke bitter, icke sniken efter slem vinning;',
        8: 'Utan gästgifvare, och älskar det godt är; tuktig, rättvis, helig, kysk;',
        9: 'Och håller sig vid det ord, som visst är och lära kan; på det han må mägtig vara att förmana genom helsosam lärdom, och öfvervinna dem som deremot säga.',
        10: 'Ty månge äro genstörtige, onyttige sqvallrare, och bedragare, besynnerliga de af omskärelsen;',
        11: 'Hvilkom man måste tillstoppa munnen; de som hela husen förvända, och lära det intet doger, för slem vinnings skull.',
        12: 'En af dem hafver sagt, deras egen Prophet: De Creter äro alltid ljugare, ond djur, och late bukar.',
        13: 'Detta vittnesbörd är sant. Derföre straffa dem skarpeliga, att de äro rätte i trone;',
        14: 'Och icke akta på de Judiska fabler och menniskors bud, som sig draga ifrå sanningen.',
        15: 'Dem, som rene äro, äro all ting rene; men dem orenom och otrognom är intet rent; utan både deras sinne och samvet är orent.',
        16: 'De säga sig känna Gud; men med gerningarna neka de det; efter de äro styggelige för Gud, och olydige, och till alla goda gerningar odugelige.',
    },
    2: {
        1: 'Men tala du, såsom tillbörligit är, efter en helsosam lärdom;',
        2: 'De gamla, att de äro nyktre, ärlige, tuktige, rätte i trone, i kärlekenom, i tålamod;',
        3: 'De gamla qvinnor desslikes, att de ställa sig såsom heligom höfves, icke förtalerskor, icke drinkerskor, goda lärerskor;',
        4: 'Att de unga qvinnor lära tukt af dem; älska sina män, hafva sin barn kär;',
        5: 'Vara sediga, kyska, husaktiga, fromma, sina män underdåniga; på det Guds ord icke skall försmädt varda.',
        6: 'Sammalunda förmana ock de unga män, att de äro tuktige.',
        7: 'Uti all ting ställ dig sjelf för en eftersyn till goda gerningar, med oförfalskad lärdom, med ärlighet;',
        8: 'Med helsosam och ostraffelig ord; på det han, som emotstår, må blygas, intet ondt hafvandes det han om oss säga kan;',
        9: 'Tjenarena, att de äro sinom herrom underdånige, och uti all ting behagelige, icke gensvarige;',
        10: 'Icke otrogne; utan alla goda trohet bevisande; på det de måga pryda Guds vår Frälsares lärdom i all stycke.',
        11: 'Ty Guds nåd, helsosam allom menniskom, är uppenbarad;',
        12: 'Och lärer oss, att vi skole försaka alla ogudaktighet och verldslig lusta, och lefva tukteliga, rättfärdeliga, och gudeliga i denna verlden;',
        13: 'Och vänta det saliga hoppet, och den stora Guds och vår Frälsares Jesu Christi härliga uppenbarelse;',
        14: 'Den sig sjelf gaf för oss; på det han skulle förlossa oss ifrån all orättfärdighet, och rena oss sig sjelfvom ett folk till egendom, det sig om goda gerningar beflitar.',
        15: 'Sådant tala, och förmana, och straffa med fullt allvar. Låt ingen förakta dig.',
    },
    3: {
        1: 'Förmana dem, att de äro Förstarna och Öfverheten underdånige och lydige; redebogne till alla goda gerningar;',
        2: 'Om ingen illa tala, icke trätosamma; utan milde, bevisande all saktmodighet till alla menniskor.',
        3: 'Ty vi vorom ock fordom ovise, ohörige, villfarande, tjenande begärelsom och mångahanda lustom, och vandradom i ondsko och afund, hätske; och hatadom hvarannan inbördes.',
        4: 'Men sedan Guds, vår Frälsares, godhet och kärlek till menniskorna uppenbarades;',
        5: 'Icke för rättfärdighetenes gernings skull, som vi gjort hade; utan efter sina barmhertighet gjorde han oss saliga, genom den nya födelsens bad, och den Heliga Andas förnyelse;',
        6: 'Hvilken han öfver oss rikeliga utgjutit hafver, genom vår Frälsare Jesum Christum;',
        7: 'På det vi skole rättfärdige varda genom hans nåd, och arfvingar blifva till evinnerligit lif, efter hoppet.',
        8: 'Det är ju ett fast ord; detta vill jag att du lärer, såsom det der visst är, att de, som Gudi trott hafva, vinnlägga sig i goda gerningar föregå; ty sådant är menniskomen godt och nyttigt.',
        9: 'Men dåraktig spörsmål, och slägtregister, och trätor, och kämpning om lagen förkasta; ty de äro onyttig och fåfäng.',
        10: 'Fly en kättersk mennisko, då han en gång och annan förmanad är;',
        11: 'Vetandes, att en sådan är förvänd, och syndar, såsom den sig sjelf fördömt hafver.',
        12: 'Då jag till dig sänder Artheman, eller Tychicum, så skynda dig snart till mig till Nicopolis; ty jag hafver satt mig före att blifva der öfver vintren.',
        13: 'Zenan, den lagkloka, och Apollo, fordra med flit, att dem intet fattas.',
        14: 'Men låt ock dem, som våre äro, lära i goda gerningar föregå der det behöfves, att de icke äro ofruktsamme.',
        15: 'Helsa dig alla, som med mig äro. Helsa dem, som oss älska i trone. Nåd vare med eder allom. Amen. Skrifven af Nicopolis, i Macedonien.',
    },
}
