NAME = 'PorNVA: Bíblia Nova Versão de Acesso Livre'
BOOK = 'I Corinthians'

CHAPTERS = {
    1: {
        1: 'Paulo, chamado por Jesus Cristo para ser um apóstolo pela vontade de Deus, e Sóstenes nosso irmão,',
        2: 'para a igreja de Deus em Corinto, àqueles que foram santificados em Jesus Cristo, chamados para ser um povo santo. Nós também escrevemos para todos os chamados no nome do nosso Senhor Jesus Cristo em todo lugar, Senhor deles e nosso.',
        3: 'Que graça e paz sejam convosco da parte de Deus nosso Pai e do Senhor Jesus Cristo.',
        4: 'Sempre dou graças ao meu Deus por vós, por causa da graça de Deus que Jesus Cristo vos deu.',
        5: 'Ele vos tem feito ricos em tudo, em toda a palavra e com todo o conhecimento,',
        6: 'assim como o testemunho de Cristo foi confirmado como verdade entre vós.',
        7: 'De modo que não vos falta nenhum dom espiritual, enquanto ansiosamente esperais pela revelação de nosso Senhor Jesus Cristo.',
        8: 'Ele também vos fortalecerá para o final, para serdes irrepreensíveis no dia do nosso Senhor Jesus Cristo.',
        9: 'Deus é fiel, o qual vos chamou na comunhão de Seu filho, Jesus Cristo, nosso Senhor.',
        10: 'Agora rogo-vos irmãos em nome de nosso Senhor Jesus Cristo, que vivais em harmonia uns com os outros, e que não haja divisões entre vós. Rogo-vos que estejais unidos com o mesmo pensamento e pelo mesmo propósito.',
        11: 'Pois ficou claro para mim, meus irmãos, pelo que me disse a família de Cloé, que há divisões entre vós.',
        12: 'Refiro-me ao que cada um de vós diz: "Eu sou de Paulo", ou "Eu sou de Apolo", ou "Eu sou de Cefas", ou "Eu sou de Cristo".',
        13: 'Está Cristo dividido? Foi Paulo crucificado por vós? Fostes batizados em nome de Paulo?',
        14: 'Agradeço a Deus por não ter batizado nenhum de vós, exceto Crispo e Gaio.',
        15: 'Para que ninguém diga que fostes batizados em meu nome.',
        16: 'Também batizei a casa de Estéfanas. Além destes, eu não sei se batizei algum outro.',
        17: 'Porque Cristo não me enviou para batizar, mas para pregar o evangelho. Não com palavras de sabedoria humana, para que a cruz de Cristo não seja anulada.',
        18: 'Pois a mensagem sobre a cruz é loucura para aqueles que estão se perdendo. Mas entre aqueles que Deus está salvando, é o poder de Deus.',
        19: 'Pois está escrito: "Destruirei a sabedoria dos sábios e frustrarei a inteligência dos instruídos".',
        20: 'Onde está o sábio? Onde está o estudioso? Onde está o argumentador deste mundo? Deus não tornou a sabedoria do mundo em loucura?',
        21: 'Visto que o mundo, em sua sabedoria, não conheceu a Deus, aprouve a Deus através da loucura da pregação salvar aqueles que creem.',
        22: 'Porque os judeus pedem por milagres e os gregos buscam sabedoria.',
        23: 'Mas nós pregamos a Cristo crucificado, escândalo para os judeus e loucura para os gentios.',
        24: 'Mas para aqueles a quem Deus chamou, tanto judeus quanto gregos, nós pregamos a Cristo, poder e sabedoria de Deus.',
        25: 'Porque a loucura de Deus é mais sábia do que os homens, e a fraqueza de Deus é mais forte do que os homens.',
        26: 'Olhai para o vosso chamado, irmãos. Não muitos de vós ereis sábios segundo os padrões humanos, nem muitos ereis poderosos, nem muitos ereis de nobre nascimento.',
        27: 'Mas Deus escolheu as coisas loucas do mundo para envergonhar os sábios; e escolheu o que é fraco no mundo para envergonhar o que é forte.',
        28: 'Deus escolheu o que é humilde e desprezado no mundo, e escolheu as coisas que são consideradas como nada, para reduzir a nada as coisas que são tidas como valiosas.',
        29: 'Ele fez isso para que ninguém tivesse motivo de se gloriar diante Dele.',
        30: 'Mas vós estais em Cristo Jesus por causa do que Deus fez. Ele se tornou para nós sabedoria de Deus, justiça, santificação e redenção.',
        31: 'Por isso as escrituras dizem: "Aquele que se gloria, glorie-se no Senhor".',
    },
    2: {
        1: 'Quando eu vim a vós, irmãos, não vim com eloquência de discurso ou sabedoria, como se tivesse proclamado os mistérios ocultos sobre Deus.',
        2: 'Pois decidi não saber nada quando eu estava entre vós, exceto Jesus Cristo, e Ele crucificado.',
        3: 'E eu estava convosco em fraqueza, em medo e em muito tremor.',
        4: 'E minha palavra e a minha proclamação não foram com palavras persuasivas de sabedoria. Em vez disso, foram com demonstração do Espírito e de poder,',
        5: 'de forma que a vossa fé não esteja na sabedoria humana, mas no poder de Deus.',
        6: 'Agora, nós falamos com sabedoria entre os maduros, mas não a sabedoria deste mundo, ou a dos governantes desta era, que estão decaindo.',
        7: 'Mas falamos com a sabedoria de Deus em verdades ocultas, a sabedoria oculta, a qual Deus predestinou antes das eras para nossa glória.',
        8: 'Nenhum dos governantes desta era conheceu essa sabedoria, pois se a tivessem conhecido naquele tempo, eles não teriam crucificado o Senhor da glória.',
        9: 'Mas como está escrito: "As coisas que nenhum olho viu, nenhum ouvido ouviu, nenhuma mente imaginou, são as coisas que Deus preparou para aqueles que o amam".',
        10: 'Estas são as coisas que Deus revelou para nós através do Espírito. Pois o Espírito examina tudo, até as coisas profundas de Deus.',
        11: 'Pois quem conhece os pensamentos de uma pessoa a não ser o espírito da pessoa que nele está? Assim também, ninguém conhece as coisas profundas de Deus a não ser o Espírito de Deus.',
        12: 'Mas nós não recebemos o espírito do mundo, e sim o Espírito que é de Deus, para que possamos conhecer as coisas livremente dadas a nós por Deus.',
        13: 'Nós falamos sobre essas coisas em palavras que a sabedoria do homem não pode ensinar, mas que o Espírito nos ensina. O Espírito interpreta palavras espirituais com sabedoria espiritual.',
        14: 'Quem não é espiritual não recebe as coisas que pertencem ao Espírito de Deus, pois são loucura para ele. E não pode conhecê-las porque são discernidas espiritualmente.',
        15: 'Quem é espiritual julga todas as coisas, mas ele não está sujeito ao julgamento de outros.',
        16: '"Pois quem pode conhecer a mente do Senhor, que possa instruí-Lo?" Mas nós temos a mente de Cristo.',
    },
    3: {
        1: 'Irmãos, eu não vos pude falar como a pessoas espirituais, mas como a pessoas carnais, como a crianças em Cristo.',
        2: 'Eu vos alimentei com leite, não com alimento sólido, porque não estáveis prontos. E, mesmo agora, não estais.',
        3: 'Pois vós continuais carnais. Porque, se existe ciúme e contenda entre vós, não estais vivendo de acordo com a carne e andando por padrões humanos?',
        4: 'Porque, quando alguém diz: "Eu sigo Paulo," e outro diz: "Eu sigo Apolo", não estais vós vivendo segundo o homem?',
        5: 'Quem então é Apolo? E quem é Paulo? Servos por meio dos quais acreditastes, conforme a tarefa que o Senhor deu a cada um.',
        6: 'Eu plantei, Apolo regou, mas Deus deu o crescimento.',
        7: 'Então, nem o que planta, nem o que rega são nada. Mas é Deus quem dá o crescimento.',
        8: 'Agora, o que planta e o que rega são um, e cada um receberá sua recompensa de acordo com seu próprio trabalho.',
        9: 'Porque somos cooperadores de Deus. Vós sois jardim e edifício de Deus.',
        10: 'De acordo com a graça de Deus que me foi dada como um sábio construtor, eu lancei a fundação, e outro constrói sobre ela. Mas que cada homem cuide da maneira como constrói sobre ela.',
        11: 'Porque não se pode lançar outra fundação senão a que já foi lançada, que é Jesus Cristo.',
        12: 'Agora, se alguém constrói sobre a fundação com ouro, prata, pedras preciosas, madeira, feno ou palha,',
        13: 'sua obra será revelada, pois a luz do dia irá revelar. Porque será revelada no fogo; o fogo testará a qualidade do que cada um fez.',
        14: 'Se a obra de alguém permanecer, este receberá recompensa.',
        15: 'Mas, se a obra de alguém for queimada, sofrerá perda. Este será salvo, mas como que escapando pelo fogo.',
        16: 'Não sabeis que sois templo de Deus e que o Espírito de Deus vive em vós?',
        17: 'Se alguém destrói o templo de Deus, Deus o destruirá. Porque o templo de Deus, que sois vós, é santo.',
        18: 'Que ninguém engane a si mesmo. Se alguém entre vós pensa que é sábio neste tempo, que se torne um "tolo", para que ele possa se tornar sábio.',
        19: 'Porque a sabedoria deste mundo é tolice para Deus. Pois está escrito: "Ele apanha o sábio em sua astúcia".',
        20: 'E novamente: "O Senhor sabe que o pensamento dos sábios é fútil".',
        21: 'Então não mais se orgulhem nas pessoas! Porque todas as coisas são vossas,',
        22: 'seja Paulo, ou Apolo, ou Cefas, ou o mundo, ou a vida, ou a morte, ou coisas do presente, ou coisas do futuro. Tudo é vosso',
        23: 'e vós sois de Cristo, e Cristo é de Deus.',
    },
    4: {
        1: 'É assim que uma pessoa deveria nos considerar, como servos de Cristo e administradores dos mistérios de Deus.',
        2: 'Nesse sentido, é um requisito para os administradores que sejam dignos de confiança.',
        3: 'Mas para mim é insignificante que eu seja julgado por vós ou por qualquer tribunal humano. Pois, nem a mim mesmo julgo.',
        4: 'Eu não estou consciente de nenhuma acusação sendo feita contra mim; mas isso não significa que eu seja inocente. É o Senhor quem me julga.',
        5: 'Portanto, não julgueis qualquer coisa antes do tempo, antes que venha o Senhor. Ele trará à luz as coisas ocultas da escuridão, e revelará os propósitos do coração. Então, cada um receberá o seu louvor da parte de Deus.',
        6: 'Agora, irmãos, eu apliquei estes princípios a mim mesmo e a Apolo por causa de vós, para que aprendais conosco: "Não vades além do que está escrito"; assim, ninguém fica se orgulhando a favor de um e desprezando ao outro.',
        7: 'Pois, quem vê alguma diferença entre vós e os outros? O que tendes que não recebestes gratuitamente? Se o recebestes gratuitamente, por que vos gloriais como se não tivesseis recebido?',
        8: 'Vós já tendes tudo o que poderíeis querer! Já vos tornastes ricos! Começastes a reinar independente de nós! De fato, eu desejo que reinásseis, então poderíamos reinar convosco.',
        9: 'Pois penso que Deus expôs a nós, os apóstolos, em último lugar, e como homens sentenciados à morte. Nós temos nos tornado um espetáculo ao mundo, aos anjos e aos homens.',
        10: 'Nós somos loucos por causa de Cristo, mas vós sois sábios em Cristo. Nós somos fracos, mas vós sois fortes. Vós sois considerados em honra, mas nós somos considerados em desonra.',
        11: 'Até a presente hora, estamos famintos e sedentos, estamos miseravelmente vestidos, somos brutalmente espancados, e não temos casa.',
        12: 'Trabalhamos duro, com as próprias mãos. Quando somos ofendidos, nós bendizemos. Quando somos perseguidos, nós aguentamos.',
        13: 'Quando somos caluniados, nós falamos com bondade. Nós nos tornamos, e ainda somos considerados, o lixo do mundo e imundícia de todos.',
        14: 'Eu não escrevo essas coisas para vos envergonhar, mas para corrigir-vos como meus filhos amados.',
        15: 'Pois, mesmo que tenhais dez mil instrutores em Cristo, não tendes muitos pais. Pois, eu me tornei vosso pai em Cristo Jesus através do Evangelho.',
        16: 'Assim, insisto que sejais meus imitadores.',
        17: 'Por isso, vos envio Timóteo, meu amado e fiel filho no Senhor. Ele vos lembrará os meus caminhos em Cristo, assim como ensino em todo lugar e em cada igreja.',
        18: 'Alguns de vós vos tornastes arrogantes, agindo como se eu não estivesse para ir visitar-vos.',
        19: 'Mas logo irei a vós, se o Senhor quiser. Então conhecerei não meramente o discurso desses que são tão arrogantes, mas verei o poder deles.',
        20: 'Pois o reino de Deus não consiste em palavra, mas em poder.',
        21: 'O que quereis? Irei a vós com uma vara ou com amor e espírito de gentileza?',
    },
    5: {
        1: 'Nós ouvimos a notícia de que há imoralidade sexual entre vós, um tipo de imoralidade que nem mesmo é permitida entre os gentios. A notícia é que um de vós está dormindo com a esposa de seu pai.',
        2: 'Sois tão arrogantes! Em vez disso, não deveríeis vos lamentar? Quem fez isso deve ser removido de entre vós!',
        3: 'Pois, apesar de eu estar ausente em corpo, mas ainda presente em espírito, já julguei aquele que fez isso, como se eu estivesse aí.',
        4: 'Quando vos reunirdes no Nome de nosso Senhor Jesus, e meu espírito estando aí também no poder de nosso Senhor Jesus,',
        5: 'entregai esse homem a Satanás para a destruição da carne, assim então seu espírito poderá ser salvo no dia do Senhor.',
        6: 'O vosso orgulho não é bom. Não sabeis que um pouco de fermento leveda toda a massa?',
        7: 'Purificai-vos do velho fermento para que sejais uma nova massa, assim como sois agora, pães não levedados. Pois Cristo, nosso Cordeiro Pascal, foi sacrificado.',
        8: 'Assim, celebremos a festa, não com fermento velho, o fermento do mau comportamento e da maldade, mas com o pão não levedado da sinceridade e da verdade.',
        9: 'Eu vos escrevi com minha letra para não vos associardes com pessoas sexualmente imorais.',
        10: 'De maneira nenhuma me refiro às pessoas imorais deste mundo, ou aos gananciosos, aos trapaceiros ou aos idólatras, uma vez que para estar longe deles precisaríeis sair do mundo.',
        11: 'Mas agora estou vos escrevendo para não vos associardes a ninguém que é chamado de irmão, mas que está vivendo em imoralidade sexual, ou que é ganancioso, ou é um idólatra, ou é caluniador, ou é um beberrão ou um trapaceiro. Nem mesmo comais uma refeição com tal pessoa.',
        12: 'Pois, como posso estar envolvido com o julgamento daqueles que são de fora da igreja? Em vez disso, não julgais aqueles que estão dentro da igreja?',
        13: 'Mas Deus julga aqueles que estão fora: "Remova a pessoa má de entre vós".',
    },
    6: {
        1: 'Quando um de vós tem uma disputa contra outro irmão, como se atreve a ir ao tribunal perante os juízes incrédulos e não perante os santos?',
        2: 'Vós não sabeis que os santos julgarão o mundo? E, se vós julgareis o mundo, não sois capazes de resolver questões de pouca importância?',
        3: 'Não sabeis que julgaremos os anjos? Quanto mais as coisas pertencentes a esta vida!',
        4: 'Portanto, se vós tendes que fazer julgamentos sobre coisas normais da vida, por que colocais tais casos diante daqueles que não têm aceitação na igreja?',
        5: 'Eu falo isso para vossa vergonha. Não há alguém entre vós sábio o suficiente para resolver a disputa entre irmãos?',
        6: 'No entanto, um crente vai para o tribunal contra outro crente, e isso é colocado diante de um juiz incrédulo!',
        7: 'O fato de existir disputas judiciais entre cristãos já é uma derrota para vós. Porque não sofreis o mal? Porque não permitis a vós mesmos serdes traídos?',
        8: 'Mas vós tendes feito o mal e traído uns aos outros, sendo estes vossos próprios irmãos!',
        9: 'Não sabeis vós que os injustos não herdarão o Reino de Deus? Não vos enganeis: os sexualmente imorais, os idólatras, os adúlteros, os efeminados, e os homens que mantêm relação sexual com outros homens,',
        10: 'os ladrões, os gulosos, os bêbados, os difamadores e os roubadores, nenhum deles herdará o reino de Deus.',
        11: 'Tais fostes alguns de vós. Mas vós fostes lavados, santificados e justificados com Deus no nome do Senhor Jesus Cristo e pelo Espírito de nosso Deus.',
        12: '"Todas as coisas são lícitas para mim", mas nem tudo me convém. "Todas as coisas são legítimas para mim", mas eu não serei dominado por nenhuma delas.',
        13: '"Os alimentos são para o estômago, e o estômago é para os alimentos", mas Deus destruirá a ambos. O corpo não é para imoralidade sexual, porém para o Senhor, e o Senhor para o corpo.',
        14: 'Deus ressuscitou o Senhor e também nos ressuscitará pelo Seu poder.',
        15: 'Vós não sabeis que vossos corpos são membros de Cristo? Porventura tomaria os membros de Cristo e os associaria a uma prostituta? Claro que não!',
        16: 'Não sabeis que quem se une a uma prostituta torna-se um corpo com ela? Como diz a escritura: "Os dois se tornarão uma só carne."',
        17: 'Todavia, quem se une ao Senhor torna-se um espírito com Ele.',
        18: 'Fugi da imoralidade sexual! Qualquer outro pecado que uma pessoa comete é fora do corpo, mas a pessoa sexualmente imoral peca contra seu próprio corpo.',
        19: 'Não sabeis que vossos corpos são templo do Espírito Santo, que mora em vós, os quais recebestes da parte de Deus, e que não sois de vós mesmos?',
        20: 'Pois, fostes comprados por um preço. Portanto, glorificai a Deus em vossos corpos.',
    },
    7: {
        1: 'Com relação às coisas que escrevestes: "É bom para o homem não tocar em mulher".',
        2: 'Mas, por causa dos atos imorais e das tentações, cada homem deve ter a sua própria esposa, e cada mulher deve ter o seu próprio marido.',
        3: 'O marido deve dar para a esposa os seus direitos conjugais; e, do mesmo modo, a esposa para com o marido.',
        4: 'Não é a esposa que tem autoridade sobre seu próprio corpo, e sim, o marido. Da mesma forma, não é o marido que tem autoridade sobre seu próprio corpo, mas a esposa.',
        5: 'Não vos priveis um ao outro, exceto quando houver concordância mútua e por um período de tempo específico, para que possam se dedicar à oração. Então, depois disso, uni-vos novamente. Assim, Satanás não vos tentará por causa da falta de controle.',
        6: 'Porém eu vos digo estas coisas como concessão e não como uma ordem.',
        7: 'Eu gostaria que todos fôsseis como eu; todavia cada um tem seu próprio dom de Deus, um de um tipo e outro de outro.',
        8: 'Digo aos não casados e às viúvas que é bom que permaneçam sem se casar assim como eu.',
        9: 'Mas, se eles não podem exercer autocontrole, devem se casar. Pois é melhor que se casem do que arderem em paixão.',
        10: 'Agora para os casados dou esta ordem, não eu, mas o Senhor: "a esposa não deve se separar de seu marido".',
        11: 'Mas se ela se separar do seu marido, deverá permanecer sem se casar, ou que se reconcilie com ele. Assim como "o marido não deve se separar da sua esposa".',
        12: 'Mas, para os demais, digo eu, não o Senhor, que se algum irmão tem uma esposa descrente e se ela está contente de viver com ele, ele não deve se separar.',
        13: 'Se uma mulher tem um marido descrente e ele está contente em viver com ela, ela não deve se separar.',
        14: 'Pois o marido descrente é santificado por causa da sua esposa, e a mulher descrente é santificada porque o seu marido é crente. Caso contrário, os seus filhos poderiam ser impuros, quando na realidade são santos.',
        15: 'Mas, se o companheiro não cristão partir, deixa-o ir. Nesses casos, o irmão ou a irmã não estão presos aos seus votos. Deus nos chamou para viver em paz.',
        16: 'Pois, como sabes, mulher, se vais salvar o teu marido? Ou como sabes, homem, se vais salvar tua esposa?',
        17: 'Somente viva cada um a vida que o Senhor lhe designou e para a qual lhe chamou. Esta é a minha ordenança em todas as igrejas.',
        18: 'Era alguém circuncidado quando foi chamado a crer? Ele não deve tentar esconder a marca da circuncisão. Era alguém incircunciso quando Deus o chamou à fé? Ele não deve ser circuncidado.',
        19: 'Por isso, nem a circuncisão nem a incircuncisão importam. O que importa é obedecer as ordens de Deus.',
        20: 'Cada um permaneça no chamado em que estava quando Deus o chamou para crer.',
        21: 'Eras tu um escravo quando Deus te chamou? Não te preocupes com isso. Mas se te tornares livre, fazes bem.',
        22: 'Para alguém que é chamado pelo Senhor como escravo, este é um homem livre para o Senhor. Do mesmo modo, aquele que é livre quando foi chamado a crer, é escravo de Cristo.',
        23: 'Vós fostes comprados por um preço, não vos torneis escravos dos homens.',
        24: 'Irmãos, assim como cada um de nós éramos quando fomos chamados a crer, vamos permanecer assim.',
        25: 'Agora, em relação àqueles que nunca foram casados, eu não tenho uma ordem do Senhor. Todavia dou minha opinião como alguém que, pela misericórdia do Senhor, é confiável.',
        26: 'Portanto eu penso que, por causa das angústias presentes, é bom para um homem permanecer como ele está.',
        27: 'Tu estás comprometido com uma mulher? Não tentes te livrar dela. Estás livre de uma esposa? Não procures uma.',
        28: 'Mas se casares, não cometes um pecado. E se uma mulher solteira se casa, ela não comete pecado. Já aquele que se casa terá muitos tipos de problemas enquanto viver, e eu gostaria de te poupar disso.',
        29: 'Mas, isto eu digo irmãos: o tempo é curto. De agora em diante, deixai aqueles que têm esposas viverem como se não as tivessem.',
        30: 'Aqueles que choram como se não chorassem; os que se alegram, como se não se alegrassem; e os que compram, como se não tivessem posse de coisa alguma;',
        31: 'e os que negociam com o mundo, como se não negociassem; porque a presente forma deste mundo está chegando ao fim.',
        32: 'Eu gostaria que vós ficásseis livres de preocupações. O homem não casado está preocupado com as coisas do Senhor, em como agradar a Ele.',
        33: 'Mas o homem casado está preocupado com coisas do mundo, em como agradar sua esposa.',
        34: 'Ele está dividido. Assim também, a mulher não casada ou a virgem está preocupada com as coisas do Senhor, em como ser santa no corpo e no espírito. Mas a mulher casada está preocupada com as coisas do mundo, em como agradar seu marido.',
        35: 'Eu digo isto para o vosso próprio benefício, e não para vos pressionar, mas o correto é que possais ser dedicados ao Senhor sem nenhuma distração.',
        36: 'Mas se alguém pensa que não está tratando sua noiva virgem com respeito, e se ela está passando da idade de se casar, e se tiver que ser assim, faça o que quiser. Ele não peca; que se casem.',
        37: 'Mas se ele está firme em seu coração e não está sob pressão, mas controla suas próprias vontades, e se decidiu em seu próprio coração fazer isso, manter sua própria noiva virgem, fará bem',
        38: 'Então, aquele que casa com sua noiva virgem faz bem, e o que escolhe não casar, faz ainda melhor.',
        39: 'Uma mulher está ligada ao seu marido enquanto ele viver. Mas, se o marido dela morrer, ela está livre para casar com quem ela desejar, mas somente no Senhor.',
        40: 'Ainda em meu julgamento, ela seria mais feliz vivendo como está. E penso que também tenho o Espírito de Deus.',
    },
    8: {
        1: 'Agora, sobre comida sacrificada aos ídolos, sabemos que "todos temos conhecimento". O conhecimento ensoberbece, mas o amor edifica.',
        2: 'Se alguém pensa que sabe algo, essa pessoa ainda não sabe como deveria saber.',
        3: 'Mas se alguém ama a Deus, essa pessoa é conhecida por Ele.',
        4: 'Então, sobre comida sacrificada aos ídolos, sabemos que "um ídolo neste mundo não é nada", e "que não existe Deus a não ser o Deus único".',
        5: 'Pois existem os chamados deuses, seja no céu ou na terra, assim como há vários "deuses" e muitos "senhores".',
        6: 'Para nós, contudo, "existe apenas um Deus, o Pai, de quem são todas as coisas, e para quem vivemos, e um Senhor Jesus Cristo, por meio de quem todas as coisas existem, e por meio do qual existimos".',
        7: 'Contudo nem todos possuem esse conhecimento. Ao contrário, alguns anteriormente praticaram adoração a ídolos, e eles comem esse alimento como sendo algo sacrificado a um ídolo. Assim, a consciência deles está corrompida porque ela é fraca.',
        8: 'Mas não é a comida que nos apresentará diante de Deus. Nós não somos piores se não comemos, nem melhores se comemos.',
        9: 'Mas cuidai para que a vossa liberdade não se torne um motivo para fazer tropeçar quem seja fraco na fé.',
        10: 'Se alguém vir a vós, que tendes conhecimento, comendo uma refeição em um templo de ídolos, não estará sua fraca consciência encorajada a comer o que é oferecido a ídolos?',
        11: 'Então, por causa do vosso entendimento sobre a verdadeira natureza dos ídolos, o mais fraco, o irmão pelo qual Cristo morreu, é destruído.',
        12: 'Desse modo, quando pecais contra vossos irmãos, ferindo-lhes a fraca consciência, pecais contra Cristo.',
        13: 'Portanto, se o alimento faz meu irmão tropeçar, eu não comerei carne novamente, para não fazer meu irmão cair.',
    },
    9: {
        1: 'Não sou livre? Não sou um apóstolo? Eu não vi a Jesus nosso Senhor? Vós não sois meu trabalho no Senhor?',
        2: 'Se não sou um apóstolo para outros, ao menos o sou para vós, porque sois a prova do meu apostolado no Senhor.',
        3: 'Esta é a minha defesa para aqueles que me examinam.',
        4: 'Não temos nós o direito de comer e beber?',
        5: 'Não temos nós o direito de levar conosco uma esposa que seja crente, assim como fazem os demais apóstolos, e os irmãos do Senhor e Cefas?',
        6: 'Ou é apenas Barnabé e eu que devemos trabalhar?',
        7: 'Quem serve como um soldado às suas próprias custas? Quem planta uma vinha e não come de seus frutos? Ou quem cuida de um rebanho e não bebe de seu leite?',
        8: 'Digo isto baseado em autoridade humana? Não diz isso também a Lei?',
        9: 'Porque está escrito na Lei de Moisés: "Não atarás a boca do boi quando ele estiver pisando os grãos". É com os bois realmente que Deus Se importa?',
        10: 'Não está Ele falando sobre nós? Foi escrito para nós, porque quem ara a terra, deve arar com esperança, e o que debulha, deve debulhar com a confiança de compartilhar da colheita.',
        11: 'Se semeamos coisas espirituais entre vós, seria demais colhermos coisas materiais de vós?',
        12: 'Se outros exercem esse direito por meio de vós, não teríamos nós ainda mais? Não obstante, nós não reivindicamos esse direito, mas suportamos tudo ao invés de sermos um obstáculo para o Evangelho de Cristo.',
        13: 'Vós não sabeis que aqueles que servem no templo, recebem sua comida do templo? E aqueles que servem no altar repartem o que é oferecido no altar?',
        14: 'Do mesmo modo, o Senhor ordenou àqueles que proclamam o Evangelho que vivam do Evangelho.',
        15: 'Mas eu não reivindiquei nenhum desses direitos. E não escrevo isso para que algo seja feito por mim. Eu preferiria morrer a que alguém me retirasse esse orgulho.',
        16: 'Pois, se eu prego o Evangelho, não tenho razão para vanglória, porque tenho obrigação de fazer isso. E ai de mim se não pregar o Evangelho!',
        17: 'Porque, se de boa vontade eu faço isso, tenho uma recompensa; mas se não de boa vontade, ainda tenho uma responsabilidade que me foi confiada.',
        18: 'Qual então é a minha recompensa? Que quando eu pregue, eu possa oferecer o Evangelho sem custo, e então não faço uso de meu direito no Evangelho.',
        19: 'Porque mesmo eu sendo livre de tudo, tornei-me um servo de todos, a fim de que eu pudesse ganhar mais pessoas.',
        20: 'Para os judeus, eu me tornei como um judeu, a fim de ganhar judeus. Àqueles sujeitos à Lei, me tornei como alguém sujeito à lei, a fim de ganhá-los pela Lei..',
        21: 'Para os que estão sem lei, me tornei como sem lei, embora não estivesse sem a Lei de Deus, e sim sob a Lei de Cristo. Eu fiz isto para ganhar aqueles sem lei.',
        22: 'Para os fracos eu me tornei fraco, com o propósito de ganhar os fracos. Eu me tornei todas as coisas para todas as pessoas, para que possa, por todos os meios, salvar alguns.',
        23: 'E eu faço todas as coisas por causa do Evangelho, de modo a participar das suas bênçãos.',
        24: 'Não sabeis que em uma corrida todos correm a corrida, mas apenas um recebe o prêmio? Então, correi para ganhar o prêmio.',
        25: 'Um atleta exercita autocontrole em todo seu treinamento. Eles fazem isso para receber uma coroa que é perecível, mas nós corremos para que possamos receber uma coroa imperecível.',
        26: 'Portanto, não corro sem propósito, nem luto golpeando o ar;',
        27: 'mas subjugo meu corpo e o faço um escravo, para que, após ter pregado para outros, eu mesmo não seja desqualificado.',
    },
    10: {
        1: 'Quero que saibais, irmãos, que os nossos pais estiveram todos debaixo da nuvem, e todos atravessaram o mar.',
        2: 'Todos foram batizados por Moisés na nuvem e no mar,',
        3: 'e todos comeram a mesma comida espiritual,',
        4: 'e todos beberam a mesma bebida espiritual. Pois eles beberam de uma rocha espiritual que os acompanhava, e essa rocha era Cristo.',
        5: 'Entretanto, Deus não se agradou da maioria deles, e seus cadáveres foram esparramados pelo deserto.',
        6: 'Estas coisas são exemplos para nós, para que não desejemos fazer coisas más como eles fizeram.',
        7: 'Não sejais idólatras, como alguns deles foram. Como está escrito: "As pessoas se sentaram para comer e beber, e se levantaram para se divertir".',
        8: 'Não vamos cometer imoralidade sexual, como muitos deles fizeram, visto que, por causa disso, vinte e três mil pessoas morreram em um dia.',
        9: 'Nem coloquemos Cristo à prova, como muitos deles fizeram, e foram destruídos por serpentes.',
        10: 'Também não murmureis, como muitos deles fizeram, e foram destruídos por um anjo da morte.',
        11: 'Ora, estas coisas aconteceram a eles como exemplo para nós. Elas foram escritas para nossa instrução - para nós, sobre os quais o fim dos tempos tem vindo.',
        12: 'Portanto, qualquer um que pensa que está em pé tenha cuidado para que não caia.',
        13: 'Nenhuma tentação nos sobreveio que não seja comum a toda humanidade. Mas Deus é fiel. Ele não deixará que sejais tentados além de vossas capacidades, mas com a tentação Ele também providenciará a forma de escape, para que possais suportá-la.',
        14: 'Portanto, meus amados, fuji da idolatria.',
        15: 'Eu vos falo como a pessoas sensatas; assim, podeis julgar o que eu digo.',
        16: 'O cálice da bênção que nós abençoamos, não é o compartilhar do sangue de Cristo? O pão que nós partimos, não é o compartilhar do corpo de Cristo?',
        17: 'Porque há um só pão, nós que somos muitos somos um corpo. Todos nós participamos juntos de um só pão.',
        18: 'Olhai para o povo de Israel: não são aqueles que comem os sacrifícios participantes do altar?',
        19: 'O que estou dizendo então? Que um ídolo é alguma coisa? Ou que aquela comida sacrificada para um ídolo é alguma coisa?',
        20: 'Mas eu digo que as coisas que os pagãos gentios sacrificam, eles oferecem estas coisas para demônios e não para Deus. Não quero que sejais participantes com demônios!',
        21: 'Vós não podeis beber o cálice do Senhor e o cálice dos demônios. Não podeis ter associação com a mesa do Senhor e a mesa dos demônios.',
        22: 'Ou vamos provocar o ciúme do Senhor? Nós seríamos mais fortes que Ele?',
        23: '"Todas as coisas são lícitas", mas nem todas são benéficas. "Todas as coisas são lícitas", mas nem todas edificam as pessoas.',
        24: 'Ninguém deve procurar seu próprio bem. Em vez disso, cada um deve procurar o bem do seu próximo.',
        25: 'Podeis comer qualquer coisa vendida no mercado, sem questões de consciência.',
        26: 'Pois, a terra e a sua plenitude são de Deus.',
        27: 'Se um não crente vos convidar para comer um alimento, e desejardes ir, comei tudo o que estiver preparado diante de vós, nada perguntando por questões de consciência.',
        28: 'Mas se alguém disser: "Esta comida foi de um sacrifício pagão," não a comais. Isto é por causa daquele que vos informou, e por causa da consciência.',
        29: 'Eu não digo da vossa própria consciência, mas a consciência da outra pessoa. Pois, por que minha liberdade deve ser julgada pela consciência do outro?',
        30: 'Se eu partilho do alimento com gratidão, por que sou insultado por causa daquilo que dou graças?',
        31: 'Portanto, quer comais ou bebais, ou façais qualquer outra coisa, fazei tudo para a glória de Deus.',
        32: 'Não vos torneis motivo de tropeço a judeus ou a gregos, ou à igreja de Deus.',
        33: 'Assim como eu tento agradar a todos em todas as coisas, não procurando meu benefício, mas o de muitos, para que eles possam ser salvos.',
    },
    11: {
        1: 'Sede meus imitadores, assim como sou de Cristo.',
        2: 'Agora, eu vos louvo porque vos lembrais de mim em tudo, e vos agarrastes às tradições exatamente como as entreguei a vós.',
        3: 'Agora, quero que entendais que Cristo é a cabeça de todo homem, que o homem é a cabeça da mulher, e que Deus é a cabeça de Cristo.',
        4: 'Qualquer homem que ora ou profetiza com sua cabeça coberta desonra sua cabeça.',
        5: 'Mas qualquer mulher que ora ou profetiza com sua cabeça descoberta desonra sua cabeça; pois é da mesma forma como se sua cabeça estivesse rapada.',
        6: 'Pois, se uma mulher não cobrir sua cabeça, ela deve cortar seu cabelo curto. Se é vergonhoso para a mulher ter seu cabelo cortado ou rapar sua cabeça, que ela cubra sua cabeça.',
        7: 'Pois um homem não deve ter sua cabeça coberta, já que ele é a imagem e glória de Deus. Mas a mulher é a glória do homem.',
        8: 'Pois, o homem não foi feito da mulher, mas a mulher foi feita do homem.',
        9: 'Pois também o homem não foi criado para a mulher; mas a mulher para o homem.',
        10: 'Por isso, a mulher deve ter um símbolo de autoridade na sua cabeça, por causa dos anjos.',
        11: 'Entretanto, no Senhor, a mulher não é independente do homem, nem é o homem independente da mulher.',
        12: 'Pois, assim como a mulher vem do homem, da mesma forma o homem vem da mulher. E todas as coisas vêm de Deus.',
        13: 'Julgai por vós mesmos: é adequado para uma mulher orar a Deus com sua cabeça descoberta?',
        14: 'A natureza por si mesma não vos ensina que, se um homem tem cabelo longo, é uma vergonha para ele?',
        15: 'A natureza não vos ensina que se uma mulher tiver cabelos compridos, isto é a sua glória? Pois seu cabelo lhe foi dado em lugar do véu.',
        16: 'Mas, se alguém quer causar contendas sobre isto, nós não temos tal prática, nem as igrejas de Deus.',
        17: 'Nas seguintes instruções, porém, eu não vos louvo, porque quando vos juntais, não é para melhor, mas para pior.',
        18: 'Assim, em primeiro lugar, eu ouvi que quando vos reunis na igreja, há divisões entre vós, e em parte acredito nisto.',
        19: 'Pois é preciso que haja facções entre vós, de tal forma que aqueles que são aprovados possam ser vistos.',
        20: 'Pois, quando vos reunis, não é a ceia do Senhor que comeis.',
        21: 'Quando comeis, cada um come sua própria comida antes que os outros façam a sua refeição. Um está faminto, e outro fica bêbado.',
        22: 'Não tendes casas onde comer e beber? Vós ignorais a igreja de Deus e humilhais aqueles que nada têm? O que devo dizer-vos? Eu deveria vos parabenizar? Eu não vos parabenizo por isto!',
        23: 'Porque eu recebi do Senhor o que também vos passei, que o Senhor Jesus, na noite em que Ele foi traído, tomou o pão;',
        24: 'depois de ter dado graças, Ele o partiu e disse: "Este é o Meu corpo, que é para vós; fazei isto em memória de Mim".',
        25: 'Da mesma forma, após a ceia, Ele pegou o cálice e disse: "Este cálice é a Nova Aliança do Meu sangue. Fazei isto, sempre que beberdes, em memória de Mim".',
        26: 'Pois, toda vez que comerdes este pão e beberdes este cálice, proclamais a morte do Senhor, até que Ele venha.',
        27: 'De sorte que, aquele que comer do pão ou beber do cálice do Senhor de maneira indigna será culpado do corpo e do sangue do Senhor.',
        28: 'Que a pessoa examine-se a si mesmo primeiro, e assim coma do pão e beba do cálice.',
        29: 'Pois aquele que come e bebe sem discernimento do corpo, come e bebe julgamento para si.',
        30: 'Por isso há entre vós muitos fracos e doentes, e alguns que já morreram.',
        31: 'Mas se examinássemos a nós mesmos, não seríamos julgados.',
        32: 'Quando, porém, somos julgados pelo Senhor, somos disciplinados, para que não sejamos condenados juntamente com o mundo.',
        33: 'Portanto, meus irmãos, quando vos juntardes para comer, aguardai uns aos outros.',
        34: 'Se alguém está faminto, que coma em casa, de tal forma que quando vos juntardes não seja para julgamento. E sobre as outras coisas que vós escrevestes, darei instruções quando eu chegar.',
    },
    12: {
        1: 'Sobre os dons espirituais, irmãos, eu não quero que sejais desinformados.',
        2: 'Vós sabeis que quando éreis pagãos, éreis levados por ídolos mudos.',
        3: 'Portanto quero que saibais que ninguém que fala pelo Espírito de Deus pode dizer: "Jesus é maldito". E ninguém pode dizer: "Jesus é Senhor", senão pelo Espírito Santo.',
        4: 'Agora, há diferentes tipos de dons, mas o mesmo Espírito.',
        5: 'E há diferentes tipos de ministérios, mas o mesmo Senhor.',
        6: 'E há diferentes tipos de trabalhos, mas é o mesmo Deus quem os faz possível em todos.',
        7: 'A cada um é dada uma manifestação visível do Espírito para o benefício de todos.',
        8: 'Pois a um é dada pelo Espírito a palavra de sabedoria, e a outro a palavra de conhecimento pelo mesmo Espírito.',
        9: 'A outro é dado fé pelo mesmo Espírito, e a outro, dons de cura pelo mesmo Espírito,',
        10: 'e a outro, dons de poder, e a outro, profecia, a outro, a habilidade de discernir espíritos, e a outro, vários tipos de línguas, e a outro, a interpretação de línguas.',
        11: 'Mas o mesmo Espírito trabalha em todos, dando os dons a cada um individualmente, como Ele quiser.',
        12: 'Pois, como o corpo é um e tem muitos membros e todos são membros do mesmo corpo, assim é com Cristo.',
        13: 'Pois, em um só Espírito, todos fomos batizados em um só corpo: sejam judeus, sejam gregos; sejam presos, sejam livres; e todos foram feitos para beber de um único Espírito.',
        14: 'Porque o corpo não é um único membro, mas muitos.',
        15: 'Se os pés dizem: "Como eu não sou mão, eu não sou parte do corpo", eles não deixam de ser parte do corpo.',
        16: 'E se o ouvido disser: "Porque eu não sou olho, eu não sou parte do corpo", ele não deixa de ser parte do corpo.',
        17: 'Se todo o corpo fosse olho, onde estaria a audição? Se todo o corpo fosse ouvido, onde estaria o olfato?',
        18: 'Mas Deus arranjou cada parte do corpo como Ele designou.',
        19: 'E, se eles fossem todos o mesmo membro, onde estaria o corpo?',
        20: 'Portanto há muitos membros, mas só um corpo.',
        21: 'O olho não pode dizer à mão: "eu não preciso de ti", nem a cabeça aos pés: "eu não preciso de vós".',
        22: 'Mas os membros do corpo que parecem ser mais fracos são essenciais.',
        23: 'E as partes do corpo que nós pensamos ser menos honrosas, nós damos a elas maior honra, e os nossos membros indecorosos ganham mais dignidade.',
        24: 'Agora nossos membros apresentáveis não têm necessidade de serem tratados com dignidade, pois eles já têm isso. Porém Deus coordenou todos os membros juntos, e Ele deu mais honra àqueles que têm falta dela.',
        25: 'Ele fez isso assim para que não haja divisão no corpo, mas para que os membros cuidem uns dos outros com a mesma afeição.',
        26: 'E, quando um membro sofre, todos os membros sofrem juntamente. Ou, quando um membro é honrado, todos os membros alegram-se juntamente.',
        27: 'Portanto vós sois parte do corpo de Cristo e individualmente membros Dele.',
        28: 'E Deus designou à igreja primeiro apóstolos, em segundo profetas, em terceiro mestres, depois operadores de milagres, depois dons de cura, aqueles que proveem socorros, aqueles que fazem trabalhos administrativos, e aqueles que têm vários dons de línguas.',
        29: 'Somos todos apóstolos? Somos todos profetas? Somos todos mestres? Todos operamos milagres?',
        30: 'Todos têm dons de cura? Todos falam em línguas? Todos interpretam línguas?',
        31: 'Procurai zelosamente os melhores dons. E eu vos mostrarei um caminho mais excelente.',
    },
    13: {
        1: 'Mesmo que eu falasse as línguas dos homens e dos anjos, se eu não tivesse amor, seria como um sino que soa ou um címbalo que retine.',
        2: 'Mesmo que eu tivesse o dom de profecia e entendesse todas as verdades escondidas e todo o conhecimento e tivesse toda a fé para remover montanhas, se não tivesse amor, eu não seria nada.',
        3: 'E se eu desse tudo o que possuo para alimentar os pobres e se eu desse o meu corpo para ser queimado, mas não tivesse amor, de nada adiantaria.',
        4: 'O amor é paciente e bondoso. O amor não inveja, nem se orgulha; não é arrogante,',
        5: 'nem rude; não busca os próprios interesses; não se ira facilmente; não leva em conta o mal.',
        6: 'Não se alegra com a injustiça, mas se alegra com a verdade.',
        7: 'O amor tudo sofre, tudo crê, tudo espera e tudo suporta.',
        8: 'O amor jamais acaba. Havendo profecias, elas passarão; havendo línguas, elas cessarão; havendo conhecimento, este passará.',
        9: 'Pois nós conhecemos em parte e em parte profetizamos,',
        10: 'mas, quando o que é perfeito vier, aquilo que é em parte passará.',
        11: 'Quando eu era uma criança, eu falava como criança, pensava como criança, julgava como criança. Quando me tornei um adulto, deixei as coisas de criança.',
        12: 'Por agora, vemos como em espelho, sem clareza, mas depois veremos face a face. Agora eu conheço em parte, mas então conhecerei completamente assim como fui completamente conhecido.',
        13: 'Agora permanecem estes três: a fé, a esperança e o amor, mas o maior deles é o amor.',
    },
    14: {
        1: 'Segui o amor e desejai intensamente os dons espirituais, especialmente o de profetizar;',
        2: 'porque aquele que fala em uma língua não fala a pessoas, mas a Deus. Pois ninguém o entende, porque ele fala mistérios no Espírito;',
        3: 'mas aquele que profetiza fala a pessoas para as edificar, encorajar e confortar.',
        4: 'Aquele que fala em língua edifica a si mesmo, mas o que profetiza edifica a igreja.',
        5: 'Gostaria que todos vós falasseis em línguas; porém, muito mais que isso, gostaria que todos profetizásseis. Aquele que profetiza é maior do que o que fala em línguas (a menos que alguém interprete, para que a igreja seja edificada).',
        6: 'Entretanto, irmãos, se eu chegar a vós falando em línguas, que beneficio vos trarei? Nenhum! A não ser que vos fale com revelação, conhecimento, profecia ou ensino.',
        7: 'Se instrumentos sem vida que produzem sons, como a flauta ou a harpa, não produzem diferentes tons, como alguém saberá qual melodia a harpa ou a flauta estão tocando?',
        8: 'Porque se a trombeta tocar um som incerto, como alguém saberá quando é o tempo de se preparar para a batalha?',
        9: 'Assim é convosco: se pronunciardes discurso que é ininteligível, como alguém entenderá o que dizeis? Vós falareis, e ninguém vos entenderá.',
        10: 'Sem dúvida, existem muitas línguas diferentes no mundo, e nenhuma é sem sentido.',
        11: 'Todavia, se eu não souber o significado de uma língua, serei um estrangeiro para quem fala, e ele será um estrangeiro para mim.',
        12: 'Do mesmo modo, convosco: já que estais desejosos pelas manifestações do Espírito, sede zelosos para abundar na edificação da igreja.',
        13: 'Então, o que fala em uma língua deve orar para que a possa interpretar.',
        14: 'Porque se eu oro em línguas, meu espírito ora, mas minha mente está infrutífera.',
        15: 'O que devo fazer? Orarei com meu espírito, mas também com minha mente. Cantarei com meu espírito, e também com minha mente.',
        16: 'De outro modo, se louvais a Deus com o espírito, como a outra pessoa dirá "Amém" quando estiveres dando graça, se ele não souber o que tu estás dizendo?',
        17: 'Vós certamente dais graças muito bem, mas a outra pessoa não é edificada.',
        18: 'Eu agradeço a Deus por falar em línguas mais que todos vós,',
        19: 'mas na igreja eu preferiria falar cinco palavras com meu entendimento a fim de instruir a outros, a falar dez mil palavras em línguas.',
        20: 'Irmãos, não sejais crianças em vosso pensar. Particularmente, quanto ao mal, sede como criancinhas; mas em vosso pensar, sede maduros.',
        21: 'Na Lei está escrito: "Por homens de outras línguas e pelos lábios estrangeiros Eu falarei a este povo. Mesmo assim, não Me ouvirão", diz o Senhor.',
        22: 'Portanto, línguas são um sinal, não para os cristãos, mas para os não cristãos; mas profecia é um sinal, não para os não cristãos, mas para os cristãos.',
        23: 'Se, portanto, toda a igreja se juntar e todos falarem em línguas, e os de fora e os não cristãos chegarem, não diriam eles que vós estais loucos?',
        24: 'Mas se todos vós estiverdes profetizando e um não cristão ou alguém de fora chegar, ele seria convencido de tudo o que ouviu, e seria julgado por tudo o que foi dito.',
        25: 'Os segredos do seu coração seriam revelados; como resultado, ele se prostraria com seu rosto em terra, adoraria a Deus, e declararia que Deus está realmente entre vós.',
        26: 'Então, como é, irmãos? Quando vos reunis, cada um tenha um salmo, um ensinamento, uma revelação, uma língua ou uma interpretação. Fazei tudo para a edificação da igreja.',
        27: 'Se alguém fala em uma língua, que sejam dois ou no máximo três, e um de cada vez, então alguém deve interpretar o que é dito.',
        28: 'Contudo, se não há ninguém para interpretar, que cada um permaneça em silêncio na igreja. Deixe que ele fale sozinho consigo mesmo e com Deus.',
        29: 'Que dois ou três profetas falem, e que os outros ouçam com discernimento o que é dito.',
        30: 'Mas, se uma revelação for dada a quem está sentado no culto, que fique em silêncio o que estava falando.',
        31: 'Porque cada um de vós pode profetizar, um por um, para que cada um aprenda, e todos sejam encorajados.',
        32: 'Porque os espíritos dos profetas estão sob o controle dos profetas.',
        33: 'Porque Deus não é Deus de confusão, mas de paz. Esta é a ordenança em todas as igrejas dos santos.',
        34: 'As mulheres devem ficar em silêncio nas igrejas, porque não lhes é permitido falar. Ao invés disso, devem estar submissas, como também diz a Lei.',
        35: 'Se há alguma coisa que elas desejem aprender, que elas perguntem para seus maridos em casa. Porque é vergonhoso para a mulher falar na igreja.',
        36: 'Veio de vós a palavra de Deus? Vós sois os únicos que fostes alcançados?',
        37: 'Se alguém pensa ser um profeta ou espiritual, deveria reconhecer que as coisas que vos escrevi são mandamentos do Senhor.',
        38: 'Mas se alguém não reconhece isso, que não seja reconhecido.',
        39: 'Então, irmãos, desejai intensamente profetizar, e não proibais ninguém de falar em línguas.',
        40: 'Mas que todas as coisas sejam feitas decentemente e em ordem.',
    },
    15: {
        1: 'Lembro-vos irmãos, do Evangelho que vos proclamei, que recebestes, e no qual permanecestes.',
        2: 'É por este Evangelho que sois salvos, desde que segureis firmemente a palavra que preguei, a menos que tenhais crido em vão.',
        3: 'Pois vos entreguei em primeiro lugar o que também recebi: que Cristo morreu por nossos pecados, segundo as Escrituras;',
        4: 'e que Ele foi sepultado e ressuscitado ao terceiro dia, segundo as Escrituras.',
        5: 'E apareceu a Cefas, depois aos Doze.',
        6: 'Em seguida, apareceu a mais de quinhentos irmãos de uma vez, os quais, a maioria ainda vive, mas alguns já dormiram.',
        7: 'Depois apareceu a Tiago e, mais tarde, a todos os apóstolos.',
        8: 'Por último, Ele apareceu a mim, como a uma criança nascida fora do tempo.',
        9: 'Pois eu sou o menor dos apóstolos, indigno de ser chamado apóstolo porque persegui a igreja de Deus.',
        10: 'Mas, pela graça de Deus, sou o que sou, e sua graça em mim não foi em vão. Em vez disso, trabalhei muito mais do que todos eles, ainda que não tenha sido eu, mas a graça de Deus que está comigo.',
        11: 'Portanto, se fui eu ou eles, assim pregamos, e vós acreditastes.',
        12: 'Ora, se Cristo é proclamado como ressurreto da morte, como podem alguns de vós dizer que não há ressurreição da morte?',
        13: 'Mas, se não há ressurreição da morte, então nem mesmo Cristo ressuscitou.',
        14: 'E se Cristo não ressuscitou, então nossa pregação é em vão, e vossa fé também é em vão.',
        15: 'E fomos consideradas falsas testemunhas sobre Deus, porque testificamos contra Deus, dizendo que Ele ressuscitou a Cristo, quando Ele não o fez.',
        16: 'Pois se os mortos não são ressuscitados, nem mesmo Cristo foi ressuscitado.',
        17: 'E se Cristo não foi ressuscitado, vossa fé é em vão, e ainda estais em vossos pecados.',
        18: 'Então, aqueles que morreram em Cristo também pereceram.',
        19: 'Se somente nesta vida temos confiança para o futuro em Cristo, somos as mais miseráveis de todas as pessoas.',
        20: 'Mas agora, Cristo foi ressuscitado dentre os mortos, sendo o primeiro fruto daqueles que morreram.',
        21: 'Visto que a morte veio por um homem, por um homem também veio a ressurreição dos mortos.',
        22: 'Pois, como em Adão todos morrem, assim também em Cristo todos serão vivificados.',
        23: 'Mas, cada um, em sua própria vez: Cristo, o primeiro dos frutos, depois os que pertencem a Cristo, em Sua vinda.',
        24: 'Então será o fim, quando Cristo entregar o reino a Deus, o Pai, e abolir todo o principado e toda autoridade e poder.',
        25: 'Pois Ele deve reinar até ter posto todos os seus inimigos debaixo de Seus pés.',
        26: 'O último inimigo a ser destruído é a morte.',
        27: 'Porque "Ele pôs todas as coisas debaixo de Seus pés". Mas, quando se diz: "Ele pôs todas as coisas", está claro que isso não inclui Aquele que sujeitou a Ele todas as coisas.',
        28: 'Quando todas as coisas estiverem sujeitas a Ele, então o Filho Se sujeitará Àquele que todas as coisas Lhe sujeitou, para que Deus, o Pai, possa ser tudo em todos.',
        29: 'De outro modo, o que farão aqueles que se batizam pelos mortos? Se os mortos não ressuscitam de modo algum, por que se batizam por causa deles?',
        30: 'E por que estamos em perigo a todo o tempo?',
        31: 'Enfrento a morte todos os dias. Isto é uma certeza de que falo com orgulho a vós, o qual tenho em Cristo Jesus, nosso Senhor.',
        32: 'O que eu ganho se, por motivos humanos, lutei com animais ferozes em Éfeso, se os mortos não são ressuscitados? "Comamos e bebamos, pois amanhã morreremos".',
        33: 'Não sejais enganados: "Más companhias corrompem os bons costumes".',
        34: 'Tornai-vos sóbrios! Vivei justamente! Não pequeis. Pois, alguns de vós não têm conhecimento de Deus. Digo isto para vossa vergonha.',
        35: 'Mas alguém dirá: "Como os mortos são ressuscitados? E com que tipo de corpo eles virão?"',
        36: 'Vós sois tão ignorantes! O que vós semeais não crescerá a menos que morra.',
        37: 'E o que semeais não é o corpo que há de ser, mas uma simples semente, que se tornará trigo ou outra planta.',
        38: 'Mas Deus dará um corpo conforme Ele escolher, a cada semente dá seu corpo apropriado.',
        39: 'Nem toda carne é a mesma, mas uma é a carne dos homens, outra é a carne dos animais, outra a dos pássaros e outra a dos peixes.',
        40: 'Há também corpos celestiais e terrestres. Mas a glória do corpo celestial é um tipo, e a glória do terrestre é outra.',
        41: 'Há uma glória do sol, outra glória da lua e outra glória das estrelas, pois uma estrela difere da outra em glória.',
        42: 'Assim também é a ressurreição dos mortos: o que é semeado é perecível, e o que ressuscita é imperecível.',
        43: 'O que é semeado em desonra é ressuscitado em glória. O que é semeado em fraqueza é ressuscitado em poder.',
        44: 'O que é semeado num corpo natural é ressuscitado num corpo espiritual. Se há um corpo natural, também há um corpo espiritual.',
        45: 'Assim, também está escrito: "O primeiro homem, Adão, foi feito alma vivente"; o último Adão tornou-se espírito vivificante.',
        46: 'Todavia, o espiritual não veio primeiro; mas o natural, e depois o espiritual.',
        47: 'O primeiro homem é da terra, feito do pó; o segundo homem é do céu.',
        48: 'À semelhança do homem feito do pó, assim também são aqueles feitos do pó; e, à semelhança do homem do céu, assim também são aqueles que são do céu.',
        49: 'Assim como carregamos a imagem do homem do pó, também carregaremos a imagem do homem do céu.',
        50: 'Digo-vos isto, irmãos, que carne e sangue não podem herdar o reino de Deus, nem o perecível herdar o imperecível.',
        51: 'Eis um mistério que vos digo: nem todos morreremos, mas todos seremos transformados.',
        52: 'Nós seremos transformados em um instante, em um piscar de olhos, na última trombeta. Pois, a trombeta soará, e os mortos serão ressuscitados imperecíveis, e nós seremos transformados.',
        53: 'Porque este corpo perecível deve se revestir do imperecível, e este corpo mortal deve-se revestir de imortalidade.',
        54: 'Mas, quando este corpo perecível se revestir do que é imperecível, e este corpo mortal se revestir do que é imortal, então virá o que está escrito: "Tragada foi a morte pela vitória".',
        55: '"Morte, onde está a tua vitória?". "Morte, onde está o teu aguilhão?".',
        56: 'O aguilhão da morte é o pecado, e o poder do pecado é a lei.',
        57: 'Mas graças a Deus, que nos dá a vitória através do nosso Senhor Jesus Cristo!',
        58: 'Portanto, meus queridos irmãos, sede firmes e inabaláveis. Sempre abundantes na obra do Senhor, porque sabeis que o vosso trabalho no Senhor não é em vão.',
    },
    16: {
        1: 'Agora, quanto à coleta para os santos, como ordenei às igrejas da Galácia, assim fazei também.',
        2: 'No primeiro dia da semana, cada um de vós separe o que puder e armazene, para que não haja coleta quando eu for.',
        3: 'E quando eu chegar, aquele que vós aprovardes, eu o enviarei com cartas para entregar vossas ofertas em Jerusalém.',
        4: 'E se for apropriado que eu também vá, eles irão comigo.',
        5: 'Mas eu irei até vós quando passar pela Macedônia, pois passarei pela Macedônia.',
        6: 'Talvez eu possa ficar convosco ou passar o inverno, para que possais ajudar em minha jornada, aonde quer que eu vá.',
        7: 'Porque eu não desejo vos ver agora por um tempo curto, pois espero passar algum tempo convosco, se o Senhor permitir.',
        8: 'Mas eu ficarei em Éfeso até o Pentecostes,',
        9: 'porque se abriu para mim uma porta grande e eficaz, e há muitos adversários.',
        10: 'E, quando Timóteo chegar, cuidai para que ele esteja convosco sem medo, porque ele está fazendo a obra do Senhor, assim como eu.',
        11: 'Portanto, que ninguém o despreze. Mas encaminhai-o em paz para que venha a mim, pois o espero com os irmãos.',
        12: 'Quanto ao nosso irmão Apolo, eu fortemente o encorajei a ir vos visitar com os irmãos, mas de modo algum ele quis ir agora. Contudo, ele irá quando tiver oportunidade.',
        13: 'Vigiai, ficai firmes na fé, sede corajosos, sede fortes.',
        14: 'Tudo o que fizerdes fazei com amor.',
        15: 'Vós sabeis que os da casa de Estéfanas são os primeiros convertidos em Acaia e que se dedicaram ao serviço dos santos. Agora eu vos rogo, irmãos,',
        16: 'que sejais submissos a essas pessoas e a cada um que trabalha e coopera conosco.',
        17: 'E eu me alegro com a vinda de Estéfanas, Fortunato e Acaico. Eles supriram a vossa ausência.',
        18: 'Porque eles revigoraram meu espírito e o vosso. Então, reconhecei pessoas como essas.',
        19: 'As igrejas da Ásia vos saúdam. Áquila e Priscila intensamente vos saúdam no Senhor, com a igreja que está na casa deles.',
        20: 'Todos os irmãos vos saúdam. Saudai uns aos outros com beijo santo.',
        21: 'Eu, Paulo, escrevo isto com minhas próprias mãos:',
        22: 'Se alguém não ama o Senhor, seja maldito. Ora vem, SenhorJesus!',
        23: 'Que a graça do Senhor Jesus seja convosco.',
        24: 'Meu amor seja com todos vós em Cristo Jesus.',
    },
}
