NAME = 'PorNVA: Bíblia Nova Versão de Acesso Livre'
BOOK = 'II Timothy'

CHAPTERS = {
    1: {
        1: 'Paulo, apóstolo de Cristo Jesus pela vontade de Deus, de acordo com a promessa da vida que está em Cristo Jesus,',
        2: 'para Timóteo, filho amado: graça, misericórdia e paz de Deus o Pai e Cristo Jesus, nosso Senhor.',
        3: 'Eu agradeço a Deus, a quem eu sirvo desde meus antepassados com consciência limpa, porque lembro-me constantemente de ti nas minhas orações, noite e dia.',
        4: 'Recordando-me de tuas lágrimas desejo muito ver-te, para encher-me de alegria.',
        5: 'Lembro-me de tua fé genuína, que habitou primeiro na tua avó Loide e em tua mãe Eunice. E eu estou convencido de que essa fé também habita em ti.',
        6: 'Por essa razão, exorto-te que reacendas o dom de Deus, que está em ti pela imposição das minhas mãos.',
        7: 'Pois Deus não nos deu espírito de medo, mas de poder, de amor e de disciplina.',
        8: 'Então não te envergonhes do testemunho do nosso Senhor, nem de mim, Paulo, seu prisioneiro. Em vez disso, compartilha comigo o sofrimento pelo evangelho, de acordo com o poder de Deus.',
        9: 'Ele nos salvou e nos convocou com um chamado santo, não de acordo com nossas obras, mas de acordo com Seu próprio plano e graça, que Ele nos deu em Cristo Jesus, antes dos tempos terem começado.',
        10: 'Mas agora a salvação de Deus foi revelada através do aparecimento do nosso Salvador Cristo Jesus, que destruiu a morte e trouxe à luz a vida sem fim, por meio do evangelho.',
        11: 'Por causa disso, eu fui constituído pregador, apóstolo, e mestre.',
        12: 'Por essa razão eu também sofro essas coisas. Mas eu não estou envergonhado; pois eu conheço Aquele em quem eu tenho crido, e eu estou certo de que é poderoso para guardar o que eu confiei a Ele até aquele dia.',
        13: 'Mantenha o padrão de palavras saudáveis que de mim escutaste, com a fé e o amor que estão em Cristo Jesus.',
        14: 'O bom depósito que Deus confiou a ti, guarda pelo Espírito Santo, que vive em nós.',
        15: 'Tu sabes que todos os que vivem na Ásia me abandonaram; nesse grupo estão Fígelo e Hermógenes.',
        16: 'Que o senhor conceda misericórdia para a família de Onesíforo, pois muitas vezes ele me animou, e não teve vergonha da minha prisão.',
        17: 'Em vez disso, quando eu estava em Roma, ele me procurou de modo diligente, e me achou.',
        18: 'O Senhor permita que ele ache misericórdia da parte Dele naquele dia. E tu sabes muito bem de quantas formas ele me ajudou em Éfeso.',
    },
    2: {
        1: 'Tu, portanto, filho meu, sê fortalecido na graça que há em Cristo Jesus.',
        2: 'E o que ouviste de mim, diante de muitas testemunhas, confia-o a pessoas fiéis e também capazes para ensinar a outros.',
        3: 'Sofre comigo, como um bom soldado de Cristo Jesus.',
        4: 'Nenhum soldado, enquanto serve se compromete com afazeres dessa vida, pois deseja agradar o seu superior.',
        5: 'Da mesma maneira, se alguém compete como um atleta, ele não é coroado se não competir segundo as regras.',
        6: 'É necessário que o agricultor que trabalha arduamente seja o primeiro a receber sua porção da colheita.',
        7: 'Compreende o que estou dizendo, pois o Senhor te dará entendimento em todas as coisas.',
        8: 'Lembra-te de Jesus Cristo, da descendência de Davi, ressurreto dentre os mortos, segundo a minha mensagem do Evangelho,',
        9: 'pela qual eu sofro ao ponto de ser algemado como um criminoso. Mas a palavra de Deus não está algemada.',
        10: 'Portanto eu suporto todas as coisas por aqueles que são eleitos, para que eles também obtenham a salvação que está em Cristo Jesus, com glória eterna.',
        11: 'Confiável é esta palavra: "Se morremos com Ele, também viveremos com Ele.',
        12: 'Se perseveramos, também reinaremos com Ele. Se O negarmos, Ele também nos negará.',
        13: 'Se somos infiéis, Ele permanece fiel, pois não pode negar a Si mesmo."',
        14: 'Relembra-lhes continuamente dessas coisas. Adverte-os diante de Deus que não discutam sobre palavras, porque nisso nada há de proveitoso e sim destruição para os que ouvem.',
        15: 'Procura apresentar-te a Deus aprovado como obreiro que não tem de que se envergonhar, que maneja bem a Palavra da Verdade.',
        16: 'Evita conversas profanas, as quais levam cada vez mais para a impiedade.',
        17: 'As palavras dos que assim agem se alastram como câncer. Entre eles estão Himeneu e Fileto,',
        18: 'homens que se desviaram da verdade. Eles dizem que a ressurreição já aconteceu e perturbam a fé de alguns.',
        19: 'Todavia, o firme fundamento de Deus permanece tendo este selo: "O Senhor conhece os que são Seus", e, "Todo aquele que pronuncia o nome do Senhor deve apartar-se da injustiça".',
        20: 'Em um lar rico não há somente vasos de ouro e de prata, mas também de madeira e de barro; alguns para uso honroso, outros para uso desonroso.',
        21: 'Assim, pois, se alguém a si mesmo se purificar destes erros será vaso para honra, consagrado, útil ao Mestre, e preparado para toda boa obra.',
        22: 'Fuja das paixões da mocidade. Segue a justiça, a fé, o amor e a paz com os que invocam o Senhor de coração puro.',
        23: 'Mas rejeita as questões tolas e ignorantes. Sabes que delas geram contendas.',
        24: 'O servo do Senhor não deve contender. Em vez disso ele deve ser gentil para com todos, apto para ensinar, e paciente.',
        25: 'Ele deve corrigir com mansidão aqueles que se opõem a ele. Talvez Deus lhes dê arrependimento para o conhecimento da verdade.',
        26: 'Eles podem se tornar sóbrios novamente e escapar das armadilhas do diabo, tendo sido capturados por ele para a sua vontade.',
    },
    3: {
        1: 'Mas saibas isto: nos últimos dias haverá tempos difíceis.',
        2: 'Pois os homens serão egoístas, avarentos, orgulhosos, soberbos, blasfemadores, desobedientes aos pais, ingratos, profanos,',
        3: 'sem afeto natural, implacáveis, caluniadores, sem domínio próprio, violentos, inimigos do bem,',
        4: 'traidores, teimosos, arrogantes, mais amigos dos prazeres do que amigos de Deus.',
        5: 'Tendo aparência de piedade, mas negando o seu poder. Afasta-te desses.',
        6: 'Pois alguns deles são homens que entram em lares e capturam mulheres tolas, que estão cheias de pecado e que são guiadas por vários desejos.',
        7: 'Essas mulheres estão sempre aprendendo, mas nunca são capazes de chegar ao conhecimento da verdade.',
        8: 'Do mesmo modo que Janes e Jambres resistiram a Moisés, assim também esses falsos mestres resistem à verdade; são homens de mente corrompida, reprovados quanto à fé.',
        9: 'Mas eles não irão muito longe, pois a tolice deles será óbvia para todos, igual à tolice desses dois homens.',
        10: 'Mas tu tens seguido os meus ensinamentos, conduta, propósito, fé, longanimidade, amor, paciência,',
        11: 'perseguições, sofrimentos, e o que aconteceu comigo em Antioquia, Icônio e Listra. Suportei perseguições, e o Senhor me resgatou, tirando-me de todas elas.',
        12: 'Aliás, todos os que querem viver de maneira piedosa em Cristo Jesus serão perseguidos.',
        13: 'Mas impostores e pessoas más se tornarão ainda piores, enganando e sendo enganados.',
        14: 'Tu, porém, permanece naquilo que aprendeste e aceitaste com fé; pois sabes de quem o aprendeste.',
        15: 'Desde a infância conheces as Sagradas Escrituras, que são capazes de fazer-te sábio para salvação pela fé que está em Cristo Jesus.',
        16: 'Toda a Escritura é inspirada por Deus e proveitosa para ensino, para repreensão, para correção, e para instruir na justiça;',
        17: 'de modo que o homem de Deus possa ser competente e capacitado para toda boa obra.',
    },
    4: {
        1: 'Diante de Deus e de Jesus Cristo, que julgará os vivos e os mortos, e por causa de Sua manifestação e de Seu reino, eu te dou esta ordem solene:',
        2: 'Prega a Palavra, insiste, quando isso for conveniente e quando não for. Reprova, repreende, exorta com toda paciência e ensino.',
        3: 'Pois o tempo chegará em que as pessoas não suportarão a sã doutrina. Em vez disso, elas ajuntarão para si mestres conforme suas próprias cobiças. Isso será tão agradável aos seus ouvidos,',
        4: 'que se afastarão da verdade e se voltarão para os mitos.',
        5: 'Tu, porém, sê sóbrio em todas as coisas, sofre as aflições, faz o trabalho de um evangelista, cumpre o teu ministério.',
        6: 'Pois eu já estou sendo derramado como uma oferta. O tempo da minha partida chegou.',
        7: 'Combati o bom combate, terminei a corrida, guardei a fé.',
        8: 'A coroa de justiça me foi reservada, aquela que o Senhor, o justo Juiz, me dará naquele dia; e não só para mim, mas também para todos aqueles que amam a Sua vinda.',
        9: 'Faz o teu melhor para vires a mim rapidamente,',
        10: 'pois Demas me abandonou. Tendo ele amado este presente mundo, partiu para Tessalônica. Crescente foi para Galácia, e Tito foi para Dalmácia.',
        11: 'Somente Lucas está comigo. Busca Marcos e traze-o contigo, pois ele me é útil na obra.',
        12: 'Enviei Tíquico para Éfeso.',
        13: 'Quando vieres, traz a capa que deixei em Trôade com Carpo, e também os livros, especialmente os pergaminhos.',
        14: 'Alexandre, aquele que trabalha com metais, fez muitos males contra mim. O Senhor irá retribuí-lo de acordo com suas ações.',
        15: 'Tu também deves proteger-te dele, porque ele resistiu fortemente às nossas palavras.',
        16: 'Na minha primeira defesa, ninguém permaneceu comigo, mas todos me abandonaram. Que isso não seja considerado contra eles.',
        17: 'Mas o Senhor permaneceu do meu lado e me fortaleceu, para que a proclamação fosse totalmente cumprida por mim, e para que todos os gentios pudessem ouvi-la. E eu fui resgatado da boca do leão.',
        18: 'O Senhor me libertará de toda ação maligna e me salvará para o Seu reino celestial. A Ele seja a glória para todo o sempre. Amém.',
        19: 'Cumprimenta Prisca, Áquila e a casa de Onesíforo.',
        20: 'Erasto ficou em Corinto, mas eu deixei Trófimo doente em Mileto.',
        21: 'Faz o teu melhor para vir antes do inverno. Êubulo te saúda, também o fazem Pudente, Lino, Cláudia, e todos os irmãos.',
        22: 'Que o Senhor esteja com o teu espírito. A graça esteja convosco.',
    },
}
