NAME = 'PorNVA: Bíblia Nova Versão de Acesso Livre'
BOOK = 'Proverbs'

CHAPTERS = {
    1: {
        1: 'Provérbios de Salomão, filho de Davi, rei de Israel.',
        2: 'Estes provérbios são para ensinar a sabedoria e a instrução, para ensinar palavras de entendimento,',
        3: 'para que recebas correção, de forma que faças o que é direito, justo e correto.',
        4: 'Estes provérbios também são para dar sabedoria aos simples, entendimento e prudência aos jovens.',
        5: 'Para que os sábios ouçam e aumentem seu aprendizado, e para que as pessoas com discernimento sejam guiadas,',
        6: 'para que entendam os provérbios, os dizeres e as palavras dos sábios, e seus enigmas.',
        7: 'O temor de Yahweh é o princípio do conhecimento, mas os tolos desprezam a sabedoria e a disciplina.',
        8: 'Meu filho, ouve o ensino de teu pai e não desprezes a instrução de tua mãe;',
        9: 'eles serão como uma coroa graciosa para a tua cabeça e colares para o teu pescoço.',
        10: 'Meu filho, se pecadores tentarem te persuadir a pecar junto com eles, recusa-te a segui-los.',
        11: 'Se disserem: "Vem conosco! Armemos uma emboscada para matar alguém; fiquemos escondidos e ataquemos um inocente.',
        12: 'Vamos tragá-lo vivo, como a sepultura engole aqueles que estão saudáveis, como os que descem à cova.',
        13: 'Encontraremos todo tipo de coisas valiosas, encheremos nossas casas com o que roubamos de outros.',
        14: 'Vem conosco! Teremos tudo em comum".',
        15: 'Meu filho, não andes neste caminho com eles, nem deixes teu pé tocar por onde eles passam;',
        16: 'Pois seus pés correm para o mal e eles se apressam em derramar sangue.',
        17: 'É inútil armar uma rede para pegar um pássaro enquanto o pássaro está atento.',
        18: 'Esses homens, que ficam à espreita para se matarem, armam armadilhas para eles mesmos.',
        19: 'Assim são os caminhos de todo aquele que se enriquece com injustiça; o ganho injusto tira a vida daqueles que o buscam.',
        20: 'A sabedoria clama intensamente nas ruas e levanta a sua voz nas praças;',
        21: 'nas esquinas tumultuadas, ela brada; nos portões da entrada da cidade, ela proclama:',
        22: '"Até quando, vós que não possuís sabedoria, continuareis a amar a tolice? Até quando, vós zombadores, vos deleitareis na zombaria, e até quando, vós tolos, odiareis o conhecimento?',
        23: 'Prestai atenção na minha repreensão; Eu vos derramarei meus pensamentos e vos revelarei as minhas palavras.',
        24: 'Chamei, mas recusastes a me ouvir; estendi a minha mão e ninguém prestou atenção.',
        25: 'Ignorastes toda a minha instrução e desconsiderastes a minha repreensão.',
        26: 'Rirei na vossa calamidade, zombarei de vós quando o terror vier,',
        27: 'quando o pavor vier como uma tempestade e o desastre varrer como um redemoinho, então, a angústia e a aflição cairão sobre vós.',
        28: 'Clamareis a mim, e não responderei; Vós me procurareis desesperadamente, mas não me achareis.',
        29: 'Pois odiastes o conhecimento e não escolhestes o temor de Yahweh.',
        30: 'Não seguistes meus conselhos e desprezastes toda a minha repreensão.',
        31: 'Comereis o fruto dos vossos caminhos e, com o fruto das vossas intrigas, vos enchereis.',
        32: 'Pois os ingênuos são mortos quando se desviam, e a prosperidade dos tolos os destruirá.',
        33: 'Mas aquele que ouvir a mim viverá em segurança e descansará tranquilo, sem temer o mal".',
    },
    2: {
        1: 'Filho meu, se tu receberes minhas palavras e entesourares meus mandamentos contigo,',
        2: 'conserva teus ouvidos atentos à sabedoria e inclina teu coração ao entendimento.',
        3: 'Se clamares por entendimento e elevares tua voz por isso,',
        4: 'se buscares isso como quem busca prata e, procurares entendimento como quem procura tesouros escondidos,',
        5: 'então, tu entenderás o temor de Yahweh e encontrarás o conhecimento de Deus.',
        6: 'Pois Yahweh dá sabedoria; de Sua boca, vêm conhecimento e entendimento.',
        7: 'Ele reserva a verdadeira sabedoria para aqueles que Lhe agradam; Ele é um escudo para os que andam em integridade.',
        8: 'Ele guarda as veredas da justiça e preservará o caminho dos que são fiéis a Ele.',
        9: 'Então, tu entenderás a retidão, a justiça, a equidade e todo bom caminho.',
        10: 'Pois a sabedoria entrará no teu coração, e o conhecimento será agradável à tua alma.',
        11: 'O discernimento te vigiará, o entendimento te guardará.',
        12: 'Eles te resgatarão do caminho do mal, daqueles que falam coisas perversas,',
        13: 'daqueles que abandonam os caminhos justos e andam nos caminhos da escuridão.',
        14: 'Esses se alegram em fazer o mal e deleitam-se nas perversidades da maldade.',
        15: 'Eles seguem caminhos tortuosos e, usando o engano, escondem seus percursos.',
        16: 'A sabedoria e a discrição te salvarão da mulher adúltera, da mulher imoral e de suas palavras sedutoras.',
        17: 'Ela abandona o companheiro de sua mocidade e se esquece da aliança de seu Deus.',
        18: 'Pois a sua casa se inclina para a morte e as suas trilhas, para a sepultura.',
        19: 'Todos os que se dirigirem a ela não retornarão, nem encontrarão os caminhos da vida.',
        20: 'Porém, tu andarás no caminho dos bons e seguirás as veredas dos justos.',
        21: 'Pois os que agem corretamente habitarão na terra e os íntegros nela permanecerão.',
        22: 'Mas os perversos serão eliminados da terra, e dela os infiéis serão arrancados.',
    },
    3: {
        1: 'Meu filho, não te esqueças dos meus mandamentos e mantém meus ensinamentos em teu coração,',
        2: 'para que longos dias, anos de vida e paz, lhe sejam acrescentados.',
        3: 'Que a fidelidade e a lealdade à aliança jamais te abandonem; amarra-as ao teu pescoço e escreve-as na tábua do teu coração.',
        4: 'Então, acharás favor e boa reputação perante os olhos de Deus e do homem.',
        5: 'Confia em Yahweh com todo o teu coração e não te apoies em teu próprio entendimento;',
        6: 'reconhece-O em todos os teus caminhos e Ele fará retas as tuas veredas.',
        7: 'Não sejas sábio aos teus próprios olhos, teme Yahweh e afasta-te do mal.',
        8: 'Isso será cura para tua carne e repouso para o teu corpo.',
        9: 'Honra a Yahweh com tuas riquezas e com os primeiros frutos de toda a tua produção,',
        10: 'e teus celeiros se encherão, e teus barris transbordarão de vinho novo.',
        11: 'Meu filho, não desprezes a disciplina de Yahweh e não odeies Sua repreensão,',
        12: 'pois Yahweh disciplina a quem ama, como um pai lida com um filho que lhe agrada.',
        13: 'Abençoado é aquele que encontra a sabedoria, este também alcança entendimento.',
        14: 'O que tu ganhas com a sabedoria é melhor que a recompensa da prata e o seu lucro, melhor que o ouro.',
        15: 'A sabedoria é mais preciosa que joias e nada do que desejas se compara a ela.',
        16: 'Ela tem longevidade em sua mão direita; em sua mão esquerda, riquezas e honra.',
        17: 'Seus caminhos são caminhos de bondade e todas as suas veredas são de paz.',
        18: 'Ela é uma árvore de vida para aqueles que a pegam; aqueles que a mantêm são abençoados.',
        19: 'Pela sabedoria, Yahweh fundou a Terra; pelo entendimento, Ele estabeleceu os céus.',
        20: 'Pelo Seu conhecimento, os abismos se abriram e as nuvens pingaram o seu orvalho.',
        21: 'Meu filho, mantém o bom senso e o discernimento, e não os perca de vista.',
        22: 'Eles serão vida para a tua alma e um adorno de favor para o teu pescoço.',
        23: 'Então, andarás em segurança no teu caminho e teus pés não tropeçarão;',
        24: 'quando deitares, não terás medo; tu te deitarás e o teu sono será suave.',
        25: 'Não tenhas medo do terror repentino, nem da devastação causada pelo perverso quando ela vier,',
        26: 'pois Yahweh estará ao teu lado e guardará os teus pés de serem pegos em uma armadilha.',
        27: 'Não retenhas o bem aos que merecem, quando estiver em teu poder fazê-lo.',
        28: 'Não digas ao teu próximo: "Vai e volta de novo, e amanhã te darei", quando tiveres o dinheiro contigo.',
        29: 'Não faças plano algum contra o teu próximo, que vive perto de ti e confia em ti.',
        30: 'Não brigues, sem razão, com alguém, quando este nada fez para prejudicar-te.',
        31: 'Não invejes o homem violento, nem escolhas nenhum de seus caminhos.',
        32: 'Pois o homem desonesto é detestável para Yahweh, mas Ele faz do justo o Seu confidente.',
        33: 'A maldição de Yahweh está sobre a casa do perverso, mas Ele abençoa a casa dos justos.',
        34: 'Ele faz de tolos os zombadores, mas concede o Seu favor aos humildes.',
        35: 'Os sensatos herdarão honra, mas os tolos serão expostos em sua vergonha.',
    },
    4: {
        1: 'Escutai, filhos, a instrução do pai, e prestai atenção; assim conhecereis o que é o entendimento.',
        2: 'Estou vos dando boas instruções; não abandoneis o meu ensino.',
        3: 'Quando eu era o menino do meu pai, o tenro e único filho da minha mãe,',
        4: 'ele me ensinava e me dizia: "Que teu coração se agarre em minhas palavras; guarda meus mandamentos e vive.',
        5: 'Adquire sabedoria e entendimento; não te esqueças nem rejeites as palavras de minha boca;',
        6: 'não abandones a sabedoria, e ela te protegerá; ama-a, e ela te manterá em segurança.',
        7: 'A sabedoria é a coisa mais importante. Portanto, adquire sabedoria e usa tudo o que possuis para adquirir o entendimento.',
        8: 'Valoriza a sabedoria e ela te exaltará; ela te honrará quando tu a abraçares.',
        9: 'Ela colocará uma coroa de honra em tua cabeça; ela te dará um diadema de glória".',
        10: 'Ouve, meu filho, e presta atenção às minhas palavras, e tu terás muitos anos de vida.',
        11: 'Eu te conduzi no caminho da sabedoria; eu te guiei pelos caminhos justos.',
        12: 'Quando andares, ninguém impedirá os teus caminhos, e, se correres, tu não tropeçarás.',
        13: 'Apega-te à instrução, não a soltes; guarda-a, pois ela é a tua vida.',
        14: 'Não sigas a vereda dos perversos e não andes pelo caminho dos que fazem o mal.',
        15: 'Evita-o, não passes por ele; afasta-te dele e vai por outro caminho.',
        16: 'Pois eles não conseguem dormir até que façam o mal, e seu sono é roubado até que façam alguém tropeçar.',
        17: 'Pois eles comem o pão da maldade e bebem o vinho da violência.',
        18: 'Mas a vereda dos justos é como a primeira luz do dia, que tem brilho crescente; ela brilha mais e mais até que a plenitude do dia chegue.',
        19: 'O caminho dos perversos é como a escuridão; eles não sabem em que tropeçam.',
        20: 'Meu filho, presta atenção às minhas palavras; inclina o teu ouvido aos meus dizeres.',
        21: 'Que eles não se afastem de teus olhos; guarda-os em teu coração.',
        22: 'Pois as minhas palavras são vida para aqueles que as encontram e saúde para o seu corpo inteiro.',
        23: 'Mantém o teu coração seguro e guarda-o com toda a diligência, porque dele fluem as fontes da vida.',
        24: 'Remove de ti as palavras falsas e afasta de ti a fala perversa.',
        25: 'Que os teus olhos olhem para frente e fixa o teu olhar no que está diante de ti.',
        26: 'Faz um trajeto reto para os teus pés; então, todos os teus caminhos estarão seguros.',
        27: 'Não te desvies nem para a direita nem para a esquerda; afasta os teus pés do mal.',
    },
    5: {
        1: 'Meu filho, presta atenção à minha sabedoria; inclina os teus ouvidos ao meu entendimento,',
        2: 'para que aprendas sobre a discrição, e teus lábios protejam o conhecimento.',
        3: 'Pois os lábios da mulher adúltera destilam mel, e a sua boca é mais suave que o azeite,',
        4: 'mas, no final, é amarga como o absinto, e afiada como a espada.',
        5: 'Seus pés descem à morte, seus passos levam para o caminho do Sheol.',
        6: 'Ela não se preocupa com o rumo da vida; seus passos vagam, ela não sabe para onde vai.',
        7: 'Agora, meus filhos, escutai a mim; não desvieis das palavras da minha boca.',
        8: 'Mantém o teu caminho longe dela, e não te aproximes da porta da sua casa.',
        9: 'Faz desta maneira para não acontecer que dês tua honra a outros, ou teus anos de vida a uma pessoa cruel;',
        10: 'estranhos se fartem da tua riqueza; aquilo pelo qual trabalhaste vá para a casa de estranhos;',
        11: 'e, no fim da tua vida, gemas quando tua carne e corpo se esvaírem;',
        12: 'e digas: "Como odiei a disciplina e meu coração rejeitou a correção!',
        13: 'Não obedeci aos meus professores, nem inclinei os meus ouvidos aos que me instruíram.',
        14: 'Quase fui completamente arruinado no meio da assembleia, entre a congregação".',
        15: 'Bebe água da tua própria cisterna, e água corrente do teu próprio poço.',
        16: 'Por acaso, deveriam as tuas fontes se derramarem por todo lado, e teus ribeiros correrem em praça pública?',
        17: 'Sejam somente para ti, e não para estranhos contigo.',
        18: 'Que a tua fonte seja abençoada, e alegra-te com a esposa da tua mocidade;',
        19: 'porque ela é uma corça amorosa, uma gazela graciosa. Que os seios dela sempre te encham de prazer e tu estejas continuamente embriagado pelo seu amor.',
        20: 'Pois, por que tu, meu filho, serias cativado por uma adúltera? Por que abraçarias os seios de uma mulher imoral?',
        21: 'Yahweh vê tudo o que uma pessoa faz e observa todos os caminhos em que anda.',
        22: 'O corrupto será capturado por suas próprias iniquidades; as cordas do seu pecado o prenderão firmemente.',
        23: 'Ele morrerá por causa da sua falta de disciplina, e, pela sua insensatez, se desviará.',
    },
    6: {
        1: 'Meu filho, se puseste o teu dinheiro como garantia do empréstimo que o teu próximo pediu, se deste a tua palavra para o empréstimo de alguém que não conheces,',
        2: 'então, terás feito uma armadilha para ti mesmo por tua promessa, e tu foste pego pelas palavras de tua boca.',
        3: 'Neste caso, meu filho, faz isto e livra-te, pois caíste nas mãos do teu próximo. Vai, humilha-te e defende o teu caso perante o teu próximo.',
        4: 'Não dês aos teus olhos sono algum, e às tuas pálpebras, nenhum descanso.',
        5: 'Livra-te como uma gazela das mãos do caçador, como um pássaro da mão do passarinheiro.',
        6: 'Olha para a formiga, preguiçoso, considera os caminhos dela, e sê sábio.',
        7: 'Ela não tem comandante, oficial ou governante,',
        8: 'contudo, prepara seu alimento no verão, e, durante a colheita, armazena o que irá comer.',
        9: 'Quanto tempo dormirás, preguiçoso? Quando levantarás do teu sono?',
        10: '"Um pouco mais de sono, um pouco mais de descanso, um pouco mais de braços cruzados para descansar";',
        11: 'e a tua pobreza te alcançará como um ladrão e as tuas necessidades, como um soldado armado.',
        12: 'A pessoa inútil, o homem perverso, vive com um discurso tortuoso,',
        13: 'piscando seus olhos, fazendo sinais com seus pés e apontando com seus dedos.',
        14: 'Ele planeja o mal com o seu coração enganoso; ele sempre atiça a discórdia.',
        15: 'Por isso, sua desgraça o alcançará em um instante; em um momento, ele será quebrado sem possibilidade de cura.',
        16: 'Há seis coisas que Yahweh odeia, sete que são abomináveis a Ele:',
        17: 'os olhos do orgulhoso, a língua que mente, as mãos que derramam sangue dos inocentes,',
        18: 'o coração que inventa planos perversos, os pés que correm apressadamente para fazer o mal,',
        19: 'a testemunha que expira mentiras e aquele que semeia discórdia entre irmãos.',
        20: 'Meu filho, obedece ao mandamento de teu pai e não abandones o ensinamento de tua mãe.',
        21: 'Liga-os sempre ao teu coração; amarra-os ao redor do teu pescoço.',
        22: 'Quando andares, eles te guiarão; quando dormires, eles zelarão por ti, e, quando acordares, eles te ensinarão.',
        23: 'Pois o mandamento é lâmpada, e o ensinamento é luz; as repreensões que vêm da disciplina são o caminho de vida.',
        24: 'Ela te preserva da mulher imoral, das suaves palavras da adúltera.',
        25: 'Em teu coração, não cobice a sua beleza, e não sejas capturado por seus cílios.',
        26: 'Dormir com uma prostituta pode custar-te um pedaço de pão, mas a esposa de outro pode custar a tua própria vida.',
        27: 'Por acaso pode um homem transportar fogo junto ao seu peito sem queimar as suas roupas?',
        28: 'Pode um homem andar sobre brasas sem queimar seus pés?',
        29: 'Assim é o homem que dorme com a mulher do seu próximo; aquele que dormir com ela não ficará impune.',
        30: 'As pessoas não desprezam um ladrão se ele furta para saciar sua necessidade, quando está faminto.',
        31: 'Contudo, se for pego, pagará sete vezes o que furtou. Ele deverá entregar tudo de valor em sua casa.',
        32: 'Aquele que comete adultério não tem juízo; quem age assim destrói a si próprio.',
        33: 'Feridas e vergonha são o que ele merece, e sua desgraça não se apagará.',
        34: 'Pois o ciúme faz um homem ficar furioso; ele não mostrará nenhuma misericórdia quando se vingar.',
        35: 'Ele não aceitará nenhuma compensação, e não poderá ser comprado, ainda que tu lhe ofereças muitos presentes.',
    },
    7: {
        1: 'Meu filho, guarda as minhas palavras e conserva os meus mandamentos contigo.',
        2: 'Obedece aos meus mandamentos e vive; guarda a minha instrução como a menina dos teus olhos.',
        3: 'Amarra-os aos teus dedos; escreve-os na tábua do teu coração.',
        4: 'Diz à sabedoria: "És minha irmã", e chama ao entendimento o teu parente,',
        5: 'para te guardares da mulher adúltera, da mulher imoral e das suas suaves palavras.',
        6: 'Da janela de minha casa, eu estava olhando através das grades,',
        7: 'e, vendo os ingênuos, percebi, entre os jovens, um rapaz sem juízo.',
        8: 'Aquele rapaz passou pela rua, perto da esquina dela, e foi em direção à sua casa.',
        9: 'Era o crepúsculo, no final do dia, no tempo da noite e da escuridão.',
        10: 'Ali a mulher o encontrou, vestida como prostituta, com um coração enganoso.',
        11: 'Ela era barulhenta e teimosa, seus pés não paravam em casa,',
        12: 'ora nas ruas, ora no mercado, em toda esquina ela ficava à espreita.',
        13: 'Então, ela o agarrou e o beijou e, atrevidamente, disse:',
        14: '"Fiz minha oferta pacífica hoje, paguei os meus votos.',
        15: 'Então, saí para encontrar-te, procurando, ansiosamente, o teu rosto, e te achei.',
        16: 'Estendi cobertas em minha cama, lençóis coloridos do Egito.',
        17: 'Perfumei o meu leito com mirra, aloés e canela.',
        18: 'Vem! Embriaguemo-nos de amor até o amanhecer; saciemo-nos fazendo amores.',
        19: 'Pois meu marido não está em casa; ele foi fazer uma longa viagem.',
        20: 'Ele pegou uma bolsa com dinheiro e voltará no dia de lua cheia".',
        21: 'Com seu falar sedutor, ela o persuadiu, e, com seus suaves lábios, o convenceu.',
        22: 'Imediatamente, ele a seguiu, como um boi que vai ao matadouro ou como um cervo pego em uma armadilha,',
        23: 'até que uma flecha lhe perfure o fígado, ou como um pássaro que corre para o laço, sem saber que isso lhe custará a vida.',
        24: 'Agora, meus filhos, escutai-me, prestai atenção às palavras da minha boca.',
        25: 'Que teu coração não se desvie para os caminhos dela; não andes perdido em suas veredas.',
        26: 'Ela já causou a queda de muitos; não são poucas as suas vítimas fatais.',
        27: 'Sua casa está nos caminhos para o Sheol, que descem até as câmaras escuras da morte.',
    },
    8: {
        1: 'Por acaso a sabedoria não está exclamando? O entendimento não está levantando a sua voz?',
        2: 'No topo das colinas, ao lado da estrada, nas encruzilhadas, a sabedoria se posiciona.',
        3: 'Perto dos portões da entrada da cidade, à entrada dos portões, ela exclama:',
        4: '"Povo, é a vós que eu clamo; a minha voz é para os filhos dos homens.',
        5: 'Vós que sois ingênuos, aprendei a sabedoria; e vós que sois insensatos, acrescentai entendimento à vossa mente.',
        6: 'Escutai, porque falarei de coisas nobres e, quando meus lábios se abrirem, direi coisas que são corretas,',
        7: 'pois minha boca fala o que é confiável e meus lábios odeiam a maldade.',
        8: 'Todas as palavras da minha boca são justas, não há nada torcido ou enganoso nelas.',
        9: 'Todas as minhas palavras são retas para aquele que as entende; minhas palavras são corretas para aqueles que acham o conhecimento.',
        10: 'Escolhei a minha instrução acima da prata e o conhecimento mais do que o ouro puro.',
        11: 'Pois a sabedoria é melhor que joias; nenhum tesouro se compara a ela.',
        12: 'Eu, a sabedoria, vivo com a prudência, e possuo conhecimento e discrição.',
        13: 'O temor de Yahweh é odiar o mal; eu odeio o orgulho e a arrogância, o caminho maligno e o discurso perverso. Eu os odeio.',
        14: 'Eu tenho o bom conselho e a verdadeira sabedoria; eu tenho discernimento e a força pertence a mim.',
        15: 'Por mim, os reis reinam, e os governantes fazem leis que são justas.',
        16: 'Por mim, os príncipes lideram e os nobres governam com justiça.',
        17: 'Eu amo os que me amam, e encontram-me os que, diligentemente, me buscam.',
        18: 'Comigo há riquezas, honra, fartura duradoura e justiça.',
        19: 'Meu fruto é melhor que o ouro, melhor até mesmo que o ouro refinado; o que eu produzo é melhor do que a prata pura.',
        20: 'Eu ando no caminho que é correto, nas veredas que conduzem à justiça,',
        21: 'para que eu dê uma herança aos que me amam e encha os seus tesouros.',
        22: 'Yahweh me criou no princípio; antes de Seus feitos antigos.',
        23: 'Em eras passadas, fui feita, desde o princípio, desde o começo da Terra.',
        24: 'Antes que existissem os oceanos, eu fui gerada, antes que houvesse abundantes nascentes de água.',
        25: 'Antes que os montes fossem firmados, e antes das colinas, eu nasci.',
        26: 'Nasci antes que Yahweh tivesse feito a Terra ou os campos, ou mesmo a primeira poeira no mundo.',
        27: 'Eu estava lá quando Ele estabeleceu os céus, quando Ele desenhou o horizonte sobre a superfície do abismo.',
        28: 'Eu estava lá quando Ele estabeleceu as nuvens acima e quando as fontes do abismo foram firmadas.',
        29: 'Eu estava lá quando Ele fez o limite do mar, de modo que as águas não se espalhassem além de onde Ele as ordenou, e quando Ele pôs o limite dos fundamentos da terra seca.',
        30: 'Eu estava ao Seu lado, como um mestre artesão; eu era Seu deleite dia após dia, sempre me alegrando diante Dele.',
        31: 'Eu estava me alegrando em todo o Seu mundo, e meu deleite era nos filhos dos homens.',
        32: 'Agora, meus filhos, escutai-me, pois aqueles que mantêm meus caminhos serão benditos.',
        33: 'Escutai a minha instrução e sede sábios; não a negligencieis.',
        34: 'Aquele que me escuta será abençoado, vigiando a cada dia aos meus portões, esperando junto aos batentes das minhas portas.',
        35: 'Pois quem quer que me encontre, encontra vida, e encontrará o favor de Yahweh.',
        36: 'Mas aquele que falhar, faz mal à sua própria vida; todos os que me odeiam amam a morte".',
    },
    9: {
        1: 'A sabedoria já edificou sua própria casa; ela talhou sete pilares de pedras.',
        2: 'Ela já abateu seus animais para a refeição, misturou seu vinho e pôs a mesa.',
        3: 'Ela enviou convites com suas criadas e exclamou dos pontos mais altos da cidade:',
        4: '"Vós que sois ingênuos, vinde para cá!". Ela fala aos que não têm bom senso:',
        5: '"Vinde! Comei da minha comida e bebei do vinho que misturei.',
        6: 'Deixai vossas atitudes insensatas e vivei; andai no caminho do entendimento.',
        7: 'Quem corrige um zombador recebe afronta, e quem repreende uma pessoa maldosa recebe insultos.',
        8: 'Não repreendas o zombador, ou ele te odiará; repreende o sábio, e ele te amará.',
        9: 'Dá instrução a um sábio, e ele se tornará ainda mais sábio; ensina o justo, e ele crescerá em seu conhecimento.',
        10: 'O temor de Yahweh é o princípio da sabedoria, e o conhecimento do Santo é o entendimento.',
        11: 'Pois, através de Mim, teus dias serão multiplicados, e anos de vida te serão acrescentados.',
        12: 'Se tu fores sábio, serás sábio para ti mesmo, mas, se tu fores zombador, suportarás isso sozinho”.',
        13: 'A insensatez é mulher ignorante; ela é indisciplinada e não sabe de nada.',
        14: 'Ela se assenta à porta de sua casa, toma um assento nos lugares altos da cidade.',
        15: 'Ela chama os que passam, aqueles que andam em linha reta em seus caminhos.',
        16: '"Vinde aqui, vós que sois ingênuos!", ela diz para aqueles que não têm sensatez:',
        17: '"As águas roubadas são doces, e o pão comido em secreto é delicioso".',
        18: 'Eles, porém, não sabem que a morte está ali, que seus convidados estão nas profundezas do mundo dos mortos.',
    },
    10: {
        1: 'Provérbios de Salomão. Um filho sábio alegra o seu pai, mas um filho tolo traz aflição à sua mãe.',
        2: 'Tesouros acumulados por meio de perversidade não têm valor, mas fazer o que é correto te livra da morte.',
        3: 'Yahweh não deixa passar fome a alma do justo, mas frustra os desejos dos perversos.',
        4: 'A mão preguiçosa faz a pessoa empobrecer, mas a mão do diligente ganha riquezas.',
        5: 'O filho sábio ajunta a colheita no verão, mas aquele que dorme durante a colheita é vergonhoso.',
        6: 'Presentes de Deus estão sobre a cabeça do justo, mas a boca dos perversos encobre a violência.',
        7: 'A pessoa justa faz tornarem-se felizes os que se lembram dela, mas o nome dos perversos apodrecerá.',
        8: 'Aqueles que são sensíveis aceitam ordens, mas o tolo que fala muito irá à ruína.',
        9: 'Aquele que caminha em integridade caminha em segurança, mas aquele que faz seus caminhos tortos, este será descoberto.',
        10: 'Aquele que pisca o olho causa aflição, e o tolo que muito fala será derrubado.',
        11: 'A boca do justo é uma fonte de água de vida, mas a boca do perverso encobre a violência.',
        12: 'O ódio provoca conflitos, mas o amor cobre todas as ofensas.',
        13: 'A sabedoria é achada nos lábios da pessoa que tem discernimento, mas a vara é para as costas daquele que não tem juízo.',
        14: 'Os sábios acumulam conhecimento, mas a boca do tolo faz aproximar a destruição.',
        15: 'A riqueza do rico é sua cidade fortificada; a pobreza dos pobres é a sua miséria.',
        16: 'O salário do justo conduz à vida; o lucro dos perversos conduz ao pecado.',
        17: 'Está no caminho para a vida os que seguem a disciplina, mas aquele que rejeita a repreensão se desvia.',
        18: 'Quem esconde o ódio tem lábios mentirosos e o que espalha calúnias é tolo.',
        19: 'Quando há muitas palavras, transgressão não falta, mas aquele que é cuidadoso com o que diz é sábio.',
        20: 'A língua do justo é prata pura; há pouco valor no coração do perverso.',
        21: 'Os lábios do justo alimentam a muitos, mas os tolos morrem por causa da sua falta de bom senso.',
        22: 'Os bons presentes de Yahweh trazem riqueza, sem dor.',
        23: 'A perversidade é um jogo que o tolo pratica, mas a sabedoria é prazer ao homem de entendimento.',
        24: 'O medo do perverso virá sobre ele, mas o desejo dos justos será concedido.',
        25: 'Como a tempestade que passa, assim deixam de existir os perversos; mas o justo é como um fundamento que dura para sempre.',
        26: 'Como vinagre para os dentes e fumaça para os olhos, assim é o preguiçoso para aqueles que o enviam.',
        27: 'O temor a Yahweh prolonga a vida, mas os anos dos perversos serão curtos.',
        28: 'A esperança dos justos é sua alegria, mas a expectativa dos perversos perecerá.',
        29: 'O caminho de Yahweh protege os que possuem integridade, mas a destruição é para os perversos.',
        30: 'O justo nunca será derrotado, mas os perversos não permanecerão na terra.',
        31: 'Da boca do justo sai o fruto de sabedoria, mas a língua perversa será cortada fora.',
        32: 'Os lábios do justo sabem o que é aceitável, mas da boca dos perversos só vêm más palavras.',
    },
    11: {
        1: 'Yahweh odeia balanças que não são precisas, mas se alegra com um peso justo.',
        2: 'Quando vem o orgulho, vem a desgraça, mas com a humildade está a sabedoria.',
        3: 'A integridade dos justos os guia, mas as atitudes perversas dos traiçoeiros os destroem.',
        4: 'A riqueza é inútil no dia da ira, mas fazer o que é certo te protege da morte.',
        5: 'A conduta correta do inocente faz seu caminho reto, mas o perverso cairá por sua própria perversidade.',
        6: 'A integridade daqueles que agradam a Deus os manterá seguros, mas os traiçoeiros cairão em suas próprias cobiças.',
        7: 'Quando um homem perverso morre, sua esperança perece, e a esperança que estava em sua força se transforma em nada.',
        8: 'O justo é mantido longe da angústia, e esta recai sobre o perverso.',
        9: 'Com sua boca, o ímpio destrói o seu próximo, mas, por meio do conhecimento, os justos são mantidos em segurança.',
        10: 'Quando os justos prosperam, a cidade se alegra; quando os perversos perecem, há gritos de júbilo.',
        11: 'Através dos bons presentes dos que agradam a Deus, a cidade se torna grandiosa; pela boca dos perversos, a cidade é derrubada.',
        12: 'O homem que despreza seu amigo não tem bom senso, mas o homem de entendimento permanece quieto.',
        13: 'Aquele que espalha calúnias revela segredos, mas a pessoa fiel mantém o segredo guardado.',
        14: 'Quando não há direção sábia, a nação cai, mas a vitória vem por se consultar muitos conselheiros.',
        15: 'Aquele que se faz de fiador de empréstimo para um estranho, certamente, sofrerá, mas aquele que evita fazer parte desse tipo de promessa estará seguro.',
        16: 'A mulher graciosa é honrada, mas as pessoas impiedosas se agarram à riqueza.',
        17: 'A pessoa gentil beneficia a si mesma, mas aquele que é cruel machuca a si próprio.',
        18: 'O perverso mente para ganhar seu salário, mas aquele que semeia o que é justo colhe o salário da verdade.',
        19: 'A pessoa que faz o que é certo viverá, mas aquele que busca o mal morrerá.',
        20: 'Yahweh odeia aqueles cujos corações são perversos, mas se deleita nos que são inocentes.',
        21: 'Certamente, os perversos não passarão impunes, mas os descendentes dos justos serão mantidos seguros.',
        22: 'A mulher bonita, mas sem discrição, é como um anel de ouro no nariz de um porco.',
        23: 'Os desejos dos justos resultam no bem, mas os perversos podem esperar somente a ira.',
        24: 'Existe aquele que espalha, e acumulará ainda mais; existe outro que retém o que deveria dar, e se dirige para a pobreza.',
        25: 'A pessoa generosa prosperará, e aquele que dá água aos outros terá água para si mesmo.',
        26: 'O povo amaldiçoa o que se recusa a vender grãos, mas bons presentes coroam a cabeça do que os vende.',
        27: 'Aquele que busca, diligentemente, o bem encontra o favor, mas aquele que busca o mal, este o achará.',
        28: 'Os que confiam em suas próprias riquezas cairão, mas, à semelhança das folhas, os que fazem o bem florescerão.',
        29: 'O que traz problemas à sua própria casa herdará o vento, e o tolo será servo do sábio de coração.',
        30: 'O fruto do justo será como uma árvore de vida, e aquele que é sábio cativa almas.',
        31: 'Se o justo recebe o que merece, quanto mais o perverso e o pecador!',
    },
    12: {
        1: 'Aquele que ama a disciplina e o conhecimento, mas odeia a correção é estúpido.',
        2: 'Yahweh concede favor ao homem bom, mas condena o homem que faz planos maus.',
        3: 'Uma pessoa não pode se firmar pela maldade, mas os justos não podem ter suas raízes arrancadas.',
        4: 'Uma esposa digna é a coroa do seu marido, mas a que traz vergonha é como uma doença que lhe apodrece os ossos.',
        5: 'Os planos dos justos são corretos, mas o conselho dos imorais é enganoso.',
        6: 'As palavras dos corruptos são uma emboscada, esperando uma chance para matar, mas as palavras dos honestos os mantêm seguros.',
        7: 'Os corruptos são derrubados e se vão, mas a casa dos justos se manterá em pé.',
        8: 'Uma pessoa é elogiada pela sabedoria que possui, mas o que faz escolhas perversas é desprezado.',
        9: 'É melhor ter uma posição sem importância — ser somente um servo — do que te gabares da tua importância, mas não tiveres nenhuma comida.',
        10: 'O justo se importa com as necessidades do seu animal, mas até a compaixão do corrupto é falha.',
        11: 'O que lavra a sua terra terá abundância de comida, mas aquele que segue projetos inúteis não tem bom senso.',
        12: 'O corrupto deseja o que homens maus roubaram de outros, mas o fruto dos justos vem deles mesmos.',
        13: 'A pessoa má se prende em sua conversa maliciosa, mas o justo escapa da angústia.',
        14: 'Do fruto de suas palavras, uma pessoa se enche de boas coisas, assim como o trabalho de suas mãos a recompensa.',
        15: 'O caminho do tolo é correto aos seus próprios olhos, mas o sábio ouve o conselho.',
        16: 'O tolo mostra a sua ira imediatamente, mas o que ignora um insulto é prudente.',
        17: 'Aquele que fala a verdade diz o que é certo, mas a falsa testemunha diz mentiras.',
        18: 'As palavras do que fala precipitadamente são como golpes de uma espada, mas a língua dos sábios traz cura.',
        19: 'Os lábios verdadeiros duram para sempre, mas a língua mentirosa dura somente um momento.',
        20: 'Há engano nos corações dos que planejam fazer o mal, mas a alegria vem para os conselheiros de paz.',
        21: 'Nenhum mal vem ao justo, mas os corruptos estão cheios de dificuldades.',
        22: 'Yahweh odeia lábios mentirosos, mas os que vivem fielmente são Seu deleite.',
        23: 'O prudente esconde o seu conhecimento, mas o coração dos tolos exclama a insensatez.',
        24: 'As mãos dos diligentes governarão, mas os preguiçosos serão sujeitos ao trabalho forçado.',
        25: 'A ansiedade no coração de uma pessoa pesa sobre ela, mas uma boa palavra a alegra.',
        26: 'O justo é um guia para seu amigo, mas o caminho dos corruptos os desvia.',
        27: 'O preguiçoso não assará a sua caça, mas o diligente obterá preciosa riqueza.',
        28: 'Na vereda da justiça está a vida, e no caminho da sua carreira não há morte.',
    },
    13: {
        1: 'O filho sábio ouve a instrução do seu pai, mas o zombador não escuta a repreensão.',
        2: 'Do fruto de sua boca, o homem desfruta de coisas boas, mas o apetite do traiçoeiro é para a violência.',
        3: 'Aquele que guarda a sua boca protege sua vida, mas o que abre muito seus lábios arruinará a si mesmo.',
        4: 'O desejo do preguiçoso anseia e nada ganha, mas a vontade dos diligentes será ricamente satisfeita.',
        5: 'O justo odeia mentiras, mas o perverso torna-se repugnante, e o que faz é vergonhoso.',
        6: 'A justiça protege aqueles que são irrepreensíveis em seus caminhos, mas a perversidade desvia os pecadores.',
        7: 'Há quem diz ser rico, mas nada tem; há outro que entrega tudo o que tem, mas é, verdadeiramente, rico.',
        8: 'O resgate da vida de um homem rico é a sua fortuna, mas um homem pobre não escuta a ameaça.',
        9: 'A luz dos justos resplandece, mas a lâmpada dos perversos será apagada.',
        10: 'O orgulho só produz contenda, mas a sabedoria está com aqueles que ouvem bons conselhos.',
        11: 'As riquezas são diminuídas quando há excesso de vaidade, mas aquele que ganha trabalhando com as suas mãos fará seu dinheiro aumentar.',
        12: 'Quando a esperança é adiada, faz adoecer o coração, mas o desejo realizado é árvore de vida.',
        13: 'Aquele que despreza a instrução trará destruição a si mesmo, mas quem honra o mandamento será recompensado.',
        14: 'O ensino de uma pessoa sábia é fonte de vida que afasta dos laços da morte.',
        15: 'O bom conhecimento conquista favor, mas o caminho dos desleais é intransitável.',
        16: 'As pessoas prudentes agem com conhecimento em todas as suas decisões, mas o tolo expõe sua insensatez.',
        17: 'O mensageiro perverso cai em problemas, mas o enviado fiel traz reconciliação.',
        18: 'Quem ignora a disciplina terá pobreza e vergonha, mas a honra virá para aquele que aprende com a correção.',
        19: 'Um desejo realizado é doce para a alma, mas os tolos odeiam afastar-se do mal.',
        20: 'Caminha com pessoas sábias e tu serás sábio, mas o companheiro dos tolos sofrerá dano.',
        21: 'O desastre corre atrás dos pecadores, mas os justos são recompensados com o bem.',
        22: 'Uma boa pessoa deixa herança para seus netos, mas a riqueza do pecador é armazenada para a pessoa justa.',
        23: 'Um campo não arado na propriedade dos pobres poderia produzir muito alimento, mas é destruído pela injustiça.',
        24: 'Aquele que não disciplina seu filho o odeia, mas aquele que ama seu filho tem o cuidado de discipliná-lo.',
        25: 'O justo come até satisfazer o seu apetite, mas o estômago dos ímpios está sempre com fome.',
    },
    14: {
        1: 'A mulher sábia constrói a sua casa, mas a mulher tola a destrói com suas próprias mãos.',
        2: 'O que anda em retidão teme a Yahweh, mas o que é desonesto em seus caminhos O despreza.',
        3: 'Na boca do tolo está a vara do seu orgulho, mas a boca do sábio o preservará.',
        4: 'Onde não há boi, o celeiro fica limpo, mas uma colheita abundante pode vir pela força de um boi.',
        5: 'Uma testemunha verdadeira não mentirá, mas a falsa testemunha respira mentiras.',
        6: 'O zombador procura sabedoria e não a encontra, mas o conhecimento vem fácil ao prudente.',
        7: 'Foge da presença do homem insensato, pois tu não acharás conhecimento em seus lábios.',
        8: 'A sabedoria do prudente é entender seu próprio caminho, mas a tolice do tolo é engano.',
        9: 'Tolos zombam quando o sacrifício de culpa é oferecido, mas, entre os justos, o favor é boa vontade.',
        10: 'O coração conhece sua própria amargura e nenhum estranho partilha de sua alegria.',
        11: 'A casa dos perversos será destruída, mas a tenda dos justos florescerá.',
        12: 'Há um caminho que parece correto aos olhos do homem, mas o fim dele leva à morte.',
        13: 'Até no riso tem dor o coração, e o fim da alegria é a tristeza.',
        14: 'O que não é fiel terá aquilo que merece, mas uma pessoa boa terá o que é seu.',
        15: 'O homem que não foi ensinado acredita em tudo, mas o prudente pensa em seus passos.',
        16: 'O sábio teme e se afasta do mal, mas o tolo rejeita, confiantemente, um aviso.',
        17: 'O que se ira com facilidade cometerá erros, e o que planeja o mal será odiado.',
        18: 'Os ingênuos herdam a tolice, mas os prudentes são coroados de conhecimento.',
        19: 'Os maus se curvarão diante dos bons, e os perversos se curvarão aos portões dos justos.',
        20: 'O pobre é odiado até pelos próprios vizinhos, mas o rico tem muitos amigos.',
        21: 'O que mostra desprezo pelo seu vizinho está pecando, mas o que favorece o pobre encontra a felicidade.',
        22: 'Acaso, os que planejam o mal não erram? Mas aqueles que planejam fazer o bem receberão um compromisso de fidelidade e confiança.',
        23: 'Em todo o trabalho, haverá proveito, mas, quando só há conversa, isto leva à pobreza.',
        24: 'A coroa dos sábios é a sua riqueza, mas a loucura dos tolos só traz mais insensatez.',
        25: 'Uma testemunha verdadeira salva vidas, mas a falsa testemunha respira mentiras.',
        26: 'No temor de Yahweh, o homem forte tem esperança, e seus filhos terão local de proteção.',
        27: 'O temor de Yahweh é fonte de vida que afasta o homem dos laços da morte.',
        28: 'A glória do rei é achada no grande número de seu povo, mas sem o povo o príncipe está arruinado.',
        29: 'O paciente tem grande entendimento, mas o precipitado exalta a tolice.',
        30: 'Um coração tranquilo é vida para o corpo, mas a inveja apodrece os ossos.',
        31: 'O que oprime o pobre insulta o seu Criador, mas o que favorece o necessitado O honra.',
        32: 'O perverso cai pela sua má conduta, mas o justo tem refúgio mesmo na sua morte.',
        33: 'A sabedoria repousa no coração do prudente, mas o que existe no coração dos tolos será conhecido.',
        34: 'Fazer o que é correto exalta uma nação, mas o pecado é a vergonha para qualquer povo.',
        35: 'O favor do rei é com o servo que age com sabedoria, mas sua ira será para aquele que age vergonhosamente.',
    },
    15: {
        1: 'A resposta suave afasta a ira, mas a palavra áspera atiça a raiva.',
        2: 'A língua dos sábios honra o conhecimento, mas a boca dos tolos derrama loucura.',
        3: 'Os olhos de Yahweh estão por toda parte, observando os maus e os bons.',
        4: 'A língua que cura é uma árvore de vida, mas a língua enganadora esmaga o espírito.',
        5: 'O tolo despreza a disciplina de seu pai, mas aquele que aprende com a correção é prudente.',
        6: 'Na casa do justo, há um grande tesouro, mas os ganhos do ímpio lhe trazem aflições.',
        7: 'Os lábios dos sábios espalham conhecimento, mas o coração dos tolos nada oferece.',
        8: 'Yahweh odeia os sacrifícios dos corruptos, mas a oração dos justos é Seu deleite.',
        9: 'Yahweh odeia o caminho dos corruptos, mas Ele ama os que buscam o que é correto.',
        10: 'Haverá dura disciplina para qualquer um que abandonar o caminho, e o que odeia a correção morrerá.',
        11: 'O Sheol e a destruição estão abertos diante de Yahweh, quanto mais o coração dos filhos dos homens!',
        12: 'O escarnecedor se ofende com a correção; ele não vai ao encontro do sábio.',
        13: 'O coração feliz torna o rosto alegre, mas a dor do coração esmaga o espírito.',
        14: 'O coração do que entende procura conhecimento, mas a boca dos tolos se alimenta de loucura.',
        15: 'Todos os dias dos oprimidos são miseráveis, mas o coração alegre tem um banquete interminável.',
        16: 'Melhor é o pouco com temor a Yahweh, do que um grande tesouro com inquietação.',
        17: 'Melhor é uma refeição com verduras onde há amor que um boi cevado acompanhado de ódio.',
        18: 'O homem com raiva atiça brigas, mas o que demora a irar-se acalma as desavenças.',
        19: 'O caminho do preguiçoso é como um lugar cheio de espinhos, mas o caminho dos justos é uma estrada plana.',
        20: 'O filho sábio traz alegria ao seu pai, mas o tolo despreza sua mãe.',
        21: 'A insensatez diverte a pessoa que carece de bom senso, mas aquele que tem entendimento anda pelo caminho reto.',
        22: 'Os planos falham onde não há conselho, mas, com muitos conselheiros, os planos têm êxito.',
        23: 'A pessoa encontra alegria quando dá uma resposta pertinente; quão boa é uma palavra no tempo certo!',
        24: 'O caminho da vida leva o prudente para cima, para que ele se afaste do Sheol, que fica abaixo.',
        25: 'Yahweh derruba a casa dos orgulhosos, mas protege a propriedade da viúva.',
        26: 'Yahweh odeia os pensamentos dos corruptos, mas as palavras de bondade são puras.',
        27: 'O ladrão traz problema para sua família, mas aquele que odeia os subornos viverá.',
        28: 'O coração do justo pensa antes de responder, mas a boca dos corruptos derrama toda a sua maldade.',
        29: 'Yahweh está longe dos corruptos, mas ouve a oração dos justos.',
        30: 'A luz dos olhos traz alegria ao coração, e as boas notícias são saúde para o corpo.',
        31: 'Se prestares atenção quando alguém te corrige acerca de como vives, permanecerás entre os sábios.',
        32: 'Aquele que rejeita a disciplina despreza a si mesmo, mas aquele que escuta a correção ganha entendimento.',
        33: 'O temor a Yahweh ensina sabedoria, e a humildade vem antes da honra.',
    },
    16: {
        1: 'Os planos do coração pertencem ao homem, mas a resposta da língua vem de Yahweh.',
        2: 'Todos os caminhos de uma pessoa são puros ao seus próprios olhos, mas Yahweh pesa o espírito.',
        3: 'Submete os teus trabalhos a Yahweh, e teus planos serão bem sucedidos.',
        4: 'Yahweh fez tudo para o Seu propósito, até os homens maus para o dia da tribulação.',
        5: 'Yahweh odeia todos os que têm um coração arrogante. Certamente, eles não ficarão impunes.',
        6: 'Pela fidelidade à aliança, pela lealdade a ela, a iniquidade é expiada e, pelo temor a Yahweh, as pessoas se afastam do mal.',
        7: 'Quando os caminhos de uma pessoa são agradáveis a Yahweh, Ele faz com que até seus inimigos tenham paz com ela.',
        8: 'Melhor é ter pouco de uma forma correta que muito rendimento com injustiça.',
        9: 'No coração, uma pessoa planeja seu caminho, mas Yahweh dirige seus passos.',
        10: 'Decisões de autoridade estão nos lábios de um rei; sua boca não deve trair a justiça.',
        11: 'As balanças honestas vêm de Yahweh; todos os pesos da bolsa são obra Dele.',
        12: 'Praticar a perversidade é desprezível para os reis, pois o trono é estabelecido por fazer o que é certo.',
        13: 'Um rei tem prazer em lábios que falam o que é correto, e ama aquele que fala a verdade.',
        14: 'A fúria de um rei é um mensageiro da morte, mas o homem sábio tentará aplacar a sua ira.',
        15: 'Na luz da face de um rei está a vida, e o seu favor é como a nuvem que traz uma chuva da primavera.',
        16: 'É melhor adquirir sabedoria que ouro. Obter entendimento deve ser preferível à prata.',
        17: 'A estrada das pessoas corretas as afasta do mal; aquele que protege a sua vida guarda o seu caminho.',
        18: 'O orgulho vem antes da destruição, e o espírito altivo, antes da queda.',
        19: 'É melhor ser humilde entre os pobres que dividir os despojos com os orgulhosos.',
        20: 'Quem considera atentamente o que lhe é ensinado encontra o que é bom, e aqueles que confiam em Yahweh serão abençoados.',
        21: 'Aquele que é sábio de coração é chamado de prudente; a doçura da voz melhora a capacidade de ensinar.',
        22: 'O entendimento é uma fonte de vida para aqueles que o têm, mas a correção dos tolos é a sua própria tolice.',
        23: 'O coração da pessoa sensata instrui a sua boca e acrescenta conhecimento aos seus lábios.',
        24: 'As palavras agradáveis são como um favo de mel — doçura para a alma e cura para os ossos.',
        25: 'Há caminho que parece correto para o homem, mas o seu fim é caminho para a morte.',
        26: 'O apetite do trabalhador trabalha por ele, pois a sua fome o motiva.',
        27: 'A pessoa inútil escava o problema, e seu discurso é como fogo abrasador.',
        28: 'O perverso semeia o conflito; quem espalha boatos separa amigos próximos.',
        29: 'Um homem de violência mente ao seu próximo e o conduz para um caminho que não é bom.',
        30: 'Aquele que pisca o olho trama perversidades; aquele que morde os lábios fará o mal acontecer.',
        31: 'Os cabelos grisalhos são uma coroa de glória que se ganha vivendo de maneira correta.',
        32: 'É melhor ser lento para irar-se que ser um guerreiro; quem domina seu espírito é mais forte do que aquele que conquista uma cidade.',
        33: 'As sortes são lançada no colo, mas a decisão vem de Yahweh.',
    },
    17: {
        1: 'É melhor ter tranquilidade com um pedaço de pão seco que uma casa cheia de banquetes e conflitos.',
        2: 'O servo sábio governará sobre o filho que age vergonhosamente, e terá parte na herança como um dos filhos de seu senhor.',
        3: 'O crisol é para a prata, e a fornalha é para o ouro, mas Yahweh refina os corações.',
        4: 'A pessoa que faz o mal presta atenção aos lábios maliciosos; o mentiroso dá ouvidos à língua destruidora.',
        5: 'Quem zomba do pobre insulta ao seu Criador, e aquele que se regozija com a desgraça não ficará sem punição.',
        6: 'Os netos são a coroa dos idosos e os pais trazem honra a seus filhos.',
        7: 'O discurso eloquente não é apropriado ao tolo; muito menos os lábios mentirosos à realeza.',
        8: 'O suborno é como uma pedra mágica para aquele que o oferece; para onde quer que ele se volte, será bem sucedido.',
        9: 'Quem decide ignorar a ofensa busca o amor, mas aquele que repete o assunto separa amigos íntimos.',
        10: 'Uma repreensão penetra mais fundo na pessoa que tem entendimento do que cem golpes num tolo.',
        11: 'Uma pessoa má busca apenas a rebelião, por isso, um mensageiro cruel será enviado contra ela.',
        12: 'É melhor encontrar-se com uma ursa roubada dos seus filhotes que com um tolo na sua insensatez.',
        13: 'Quando alguém retribui o bem com o mal, o mal nunca deixará a sua casa.',
        14: 'O começo do conflito é como aquele que libera água por todo lugar; portanto, foge da disputa antes que ela se inicie.',
        15: 'Aquele que absolve o ímpio e aquele que condena o justo — ambos são abominação a Yahweh.',
        16: 'Por que o tolo pagaria para aprender a sabedoria se ele não tem capacidade de aprendê-la?',
        17: 'O amigo ama em todo o tempo, e um irmão nasce nos tempos de dificuldades.',
        18: 'O homem que não tem juízo faz promessas que impõem obrigações a si mesmo, e torna-se responsável pelas dívidas de seu próximo.',
        19: 'Aquele que ama o conflito ama o pecado; aquele que faz muito alta a soleira da sua porta causa ossos quebrados.',
        20: 'A pessoa que tem o coração corrupto não encontra nada de bom; aquele que tem a língua perversa cai na calamidade.',
        21: 'Aquele que gera um tolo traz sofrimento a si mesmo; quem quer que seja pai de um insensato não terá alegria.',
        22: 'O coração alegre é um bom remédio, mas o espírito abatido seca os ossos.',
        23: 'O homem perverso aceita o suborno secreto para perverter os caminhos da justiça.',
        24: 'Aquele que tem entendimento volta o seu rosto para a sabedoria, mas os olhos do tolo perdem-se nos confins da terra.',
        25: 'O filho tolo é o sofrimento do seu pai e a amargura da mãe que o gerou.',
        26: 'Nunca é bom punir o justo, nem açoitar os nobres que têm integridade.',
        27: 'Aquele que tem conhecimento usa poucas palavras, e aquele com entendimento tem um temperamento equilibrado.',
        28: 'Até um tolo é tido por sábio quando fica calado; se mantém a boca fechada, ele é considerado inteligente.',
    },
    18: {
        1: 'Aquele que se isola busca seu próprio desejo, e luta contra todo o bom senso.',
        2: 'O tolo não encontra satisfação no entendimento, mas apenas em revelar o que está em seu próprio coração.',
        3: 'Quanto ao ímpio, o desprezo vem com ele — juntamente com a vergonha e a repreensão.',
        4: 'As palavras da boca de um homem são águas profundas; a fonte da sabedoria é um ribeiro corrente.',
        5: 'Não é bom ser parcial com o perverso, nem negar justiça ao justo.',
        6: 'Os lábios do tolo trazem-lhe conflito, e a sua boca convida o golpe.',
        7: 'A boca do tolo é a sua ruína, e ele é pego na armadilha dos seus lábios.',
        8: 'As palavras do difamador são como deliciosos pedaços de comida que descem para as partes internas do corpo.',
        9: 'Quem é desleixado em seu trabalho é um irmão para aquele que o destrói.',
        10: 'O nome de Yahweh é uma torre forte; o justo corre para ela e fica seguro.',
        11: 'A riqueza do rico é a sua cidade fortificada e, em sua imaginação, é como um muro alto.',
        12: 'O orgulho precede a ruína, a humildade vem antes da honra.',
        13: 'Aquele que responde antes de ouvir mostra insensatez e passa vergonha.',
        14: 'O espírito de uma pessoa sobreviverá à doença, mas um espírito abatido, quem o pode suportar?',
        15: 'O coração do inteligente adquire conhecimento, e o ouvido do sábio o buscará.',
        16: 'O presente que homem der pode abrir-lhe o caminho, e trazê-lo até uma pessoa importante.',
        17: 'O primeiro a defender seu caso parece correto até que seu oponente venha e o questione.',
        18: 'Lançar a sorte faz cessar disputas e separa fortes oponentes.',
        19: 'Um irmão ofendido é mais difícil de conquistar que uma cidade forte, e a desavença é como as barras de um castelo.',
        20: 'O estômago de cada um é cheio do fruto de sua boca; da colheita dos seus lábios, ele fica satisfeito.',
        21: 'A morte e a vida são controladas pela língua, e aqueles que a amam comerão do seu fruto.',
        22: 'Aquele que encontra uma esposa encontra um bem, e alcança a benevolência de Yahweh.',
        23: 'O pobre implora por misericórdia, mas o rico responde duramente.',
        24: 'Aquele que acredita ter muitos amigos é levado à ruína por eles, mas há amigo que está mais próximo que um irmão.',
    },
    19: {
        1: 'Melhor é o pobre que anda em sua integridade que o tolo que fala de modo perverso.',
        2: 'Não é bom ter desejo sem conhecimento, e aquele que corre muito rápido perde o caminho.',
        3: 'É a insensatez de uma pessoa que arruína sua vida, mas seu coração se irrita contra Yahweh.',
        4: 'A riqueza traz muitos amigos; mas o pobre é deixado por seus amigos.',
        5: 'A falsa testemunha não ficará impune, e aquele que despeja mentiras não escapará.',
        6: 'Muitos pedirão favor à pessoa generosa, e todos são amigos daquele que dá presentes.',
        7: 'Se até os irmãos do pobre o odeiam, quanto mais os seus amigos se afastarão dele! Ele os chama, mas já foram embora.',
        8: 'Aquele que obtém sabedoria ama sua própria vida; aquele que guarda o conhecimento achará o que é bom.',
        9: 'A falsa testemunha não sairá impune; aquele que fala mentiras perecerá.',
        10: 'Não é adequado que o tolo viva no luxo; muito menos que o escravo domine príncipes.',
        11: 'A discrição faz a pessoa não perder a calma, e a sua glória é ignorar a ofensa.',
        12: 'A ira do rei é como o bramido de um leão jovem, mas seu favor é como orvalho sobre a relva.',
        13: 'O filho tolo é a ruína do seu pai, e a esposa rixosa é uma goteira constante.',
        14: 'A casa e a riqueza são heranças dos pais, mas a esposa prudente vem de Yahweh.',
        15: 'A preguiça lança a pessoa para um sono profundo, mas aquele que não é disposto a trabalhar terá fome.',
        16: 'Aquele que obedece ao mandamento guarda sua vida, mas a pessoa que não pensa a respeito de seus caminhos morrerá.',
        17: 'Quem é benevolente com os pobres empresta a Yahweh, e Ele lhe retribuirá pelo que houver feito.',
        18: 'Disciplina teu filho enquanto há esperança, não queiras levá-lo à morte.',
        19: 'A pessoa de temperamento forte deve pagar a pena; se tu o resgatares, terás que fazê-lo uma segunda vez.',
        20: 'Escuta o conselho e aceita a instrução, para te tornares sábio ao fim de tua vida.',
        21: 'Muitos são os planos no coração da pessoa, mas é o propósito de Yahweh que permanecerá.',
        22: 'A lealdade é o que uma pessoa deseja, e um pobre é melhor que um mentiroso.',
        23: 'O temor a Yahweh leva pessoas à vida; aquele que o tiver estará satisfeito e não afligido pelo perigo.',
        24: 'O preguiçoso põe a sua mão no prato, mas nem a levará de volta à boca.',
        25: 'Golpeia o zombador, e o ingênuo se tornará prudente; corrige o que tem discernimento, e ele ganhará conhecimento.',
        26: 'Aquele que rouba seu pai e faz sua mãe fugir é o filho que traz vergonha e reprovação.',
        27: 'Se parares de ouvir a instrução, meu filho, então, te desviarás das palavras de conhecimento.',
        28: 'A testemunha corrupta zomba da justiça, e a boca dos ímpios engole iniquidade.',
        29: 'A condenação está preparada para os zombadores, e os açoites, para as costas dos tolos.',
    },
    20: {
        1: 'O vinho é zombador e a bebida forte é briguenta; quem se deixar desviar por eles não é sábio.',
        2: 'O furor de um rei é como o rugido de um leão jovem; quem lhe provoca a ira peca contra a própria vida.',
        3: 'É uma honra para alguém evitar o conflito, mas os tolos saltam para dentro da briga.',
        4: 'O preguiçoso não lavra no outono; ele busca a produção na estação da colheita, mas não terá nada.',
        5: 'O propósito que está no coração humano é como águas profundas, mas a pessoa com entendimento trará isso para fora.',
        6: 'Muitas pessoas proclamam que são leais, mas quem achará alguém que seja fiel?',
        7: 'O justo caminha em sua integridade, seus filhos serão felizes se o seguirem.',
        8: 'Um rei que se assenta no trono para julgar separa todo o mal que está diante dos seus olhos.',
        9: 'Quem pode dizer: "Eu mantenho o meu coração puro; estou limpo do meu pecado"?',
        10: 'Pesos diferenciados e medidas desiguais; Yahweh odeia ambos.',
        11: 'Até um jovem é conhecido por suas ações, se a sua conduta for pura e correta.',
        12: 'Ouvidos que ouvem e olhos que veem, Yahweh fez ambos.',
        13: 'Não ames dormir ou tu ficarás pobre; abre os teus olhos e tu terás muito para comer.',
        14: '"Ruim! Ruim!" diz o comprador, mas, quando vai embora, se gaba.',
        15: 'Há ouro e pedras preciosas em abundância, mas os lábios de conhecimento são uma joia preciosa.',
        16: 'Pega a roupa daquele que se fez fiador da dívida de um estranho; que ela sirva de penhor por ele garantir a dívida de quem não conhece.',
        17: 'O pão adquirido por meio do engano tem sabor doce, mas, depois, sua boca se encherá de pedrinhas.',
        18: 'Os planos são estabelecidos por meio de conselho e, somente com orientação sábia, deve-se fazer guerra.',
        19: 'O mexeriqueiro revela segredos; por isso, não te associes com pessoas que falam demais.',
        20: 'Se uma pessoa amaldiçoa seu pai ou sua mãe, sua lâmpada será apagada no meio das trevas.',
        21: 'Uma herança recebida antecipadamente não será uma bênção no final.',
        22: 'Não digas: "Eu te retribuirei por esse mal!". Espera por Yahweh, e Ele te resgatará.',
        23: 'Yahweh odeia pesos desiguais; Ele não Se agrada de balanças desonestas.',
        24: 'Os passos de uma pessoa são direcionados por Yahweh; como, então, ela poderá entender o seu caminho?',
        25: 'É uma armadilha falar precipitadamente: “Está consagrado a Deus", e pensar sobre o que isso significa somente depois de ter feito seu voto.',
        26: 'O rei sábio espalha os perversos e, depois, faz passar a roda sobre eles.',
        27: 'O espírito humano é a lâmpada de Yahweh, que busca o mais íntimo do coração.',
        28: 'A piedade e a lealdade preservam o rei; o seu trono é assegurado pelo amor.',
        29: 'A glória do jovem está na sua força, e o esplendor dos idosos, em seus cabelos grisalhos.',
        30: 'Pancadas que fazem uma ferida purificam do mal, e golpes limpam o mais íntimo do corpo.',
    },
    21: {
        1: 'O coração do rei é uma corrente de água na mão de Yahweh; Ele o dirige para onde deseja.',
        2: 'O caminho de cada um parece correto aos seus próprios olhos, mas é Yahweh que sonda os corações.',
        3: 'Fazer o que é correto e justo é mais aceitável para Yahweh do que o sacrifício.',
        4: 'Os olhos altivos e o coração orgulhoso — a lâmpada dos corruptos — são pecado.',
        5: 'Os planos do diligente, certamente, conduzem à prosperidade, mas quem se apressa excessivamente se dirige à pobreza.',
        6: 'Adquirir riquezas por meio da língua mentirosa é neblina passageira e um laço que mata.',
        7: 'A violência dos maus os varrerá, porque se recusam a fazer o que é justo.',
        8: 'O caminho do culpado é tortuoso, mas aquele que é puro faz o que é correto.',
        9: 'É melhor viver num canto do terraço que na casa compartilhada com uma esposa briguenta.',
        10: 'O coração dos corruptos anseia o mal; seu vizinho não acha favor em seus olhos.',
        11: 'Quando o zombador é punido, o simples se torna sábio, e quando o sábio é instruído, ele recebe o conhecimento.',
        12: 'Deus, o Justo, observa a casa do corrupto e leva os maus à ruína.',
        13: 'Aquele que tapa os ouvidos ao clamor do pobre também clamará, mas não será ouvido.',
        14: 'Um presente entregue em secreto abranda a ira, um presente às escondidas aplaca o grande furor.',
        15: 'Quando a justiça é feita, ela traz alegria ao justo, mas traz terror para os malfeitores.',
        16: 'Aquele que vagueia afastando-se do caminho do entendimento descansará na assembleia dos mortos.',
        17: 'Quem ama o prazer se tornará pobre; aquele que ama o vinho e o azeite não será rico.',
        18: 'O corrupto é a redenção para o justo, e o traiçoeiro é a redenção para os que são corretos.',
        19: 'É melhor viver no deserto do que com uma esposa briguenta e raivosa.',
        20: 'Há azeite e tesouro precioso na casa do sábio, mas o homem insensato os devora por completo.',
        21: 'Aquele que pratica o que é justo e é benevolente encontra vida, justiça e honra.',
        22: 'O homem sábio escala a cidade dos poderosos e derruba a fortaleza em que confiavam.',
        23: 'Quem guarda sua boca e sua língua mantém-se longe de aflições.',
        24: 'O orgulhoso e altivo — cujo nome é "Zombador" — atua com orgulho arrogante.',
        25: 'O desejo do preguiçoso o mata, porque as suas mãos se recusam a trabalhar.',
        26: 'Todo o dia, ele anseia por mais e mais, mas aquele que é justo dá e não retém para si.',
        27: 'O sacrifício do corrupto já é detestável; torna-se mais ainda quando é oferecido com intenções malignas.',
        28: 'A falsa testemunha perecerá, mas aquele que escuta falará por todo o tempo.',
        29: 'O homem mau se mostra com uma face dura, mas a pessoa correta tem certeza de seus caminhos.',
        30: 'Não há sabedoria, nem entendimento, nem conselho que possa permanecer contra Yahweh.',
        31: 'O cavalo é preparado para o dia da batalha, mas a vitória vem de Yahweh.',
    },
    22: {
        1: 'O bom nome vale mais que grandes riquezas e o favor é melhor que prata e ouro.',
        2: 'Ricos e pobres têm algo em comum: Yahweh é o Criador de todos eles.',
        3: 'Um homem prudente percebe o perigo e se esconde, mas o tolo avança e sofre por isso.',
        4: 'A recompensa da humildade e do temor de Yahweh são riquezas, honra e vida.',
        5: 'Espinhos e laços se encontram no caminho do perverso; quem guarda sua vida se manterá longe deles.',
        6: 'Ensina a criança no caminho em que deve andar e, quando envelhecer, não se desviará dessa instrução.',
        7: 'Os ricos governam sobre os pobres e o que pega emprestado é escravo daquele que lhe empresta.',
        8: 'Quem semeia injustiça colherá problemas e a vara de sua fúria desaparecerá.',
        9: 'Aquele que tem olhos generosos será abençoado, pois compartilha do seu pão com os pobres.',
        10: 'Afasta o zombador e a contenda acabará, as disputas e os insultos cessarão.',
        11: 'Aquele que ama um coração puro e cujo discurso é gracioso terá o rei como seu amigo.',
        12: 'Os olhos de Yahweh preservam o conhecimento, mas as palavras do traiçoeiro, Ele as derruba.',
        13: 'O preguiçoso diz: "Há um leão na rua! Se eu sair, serei morto".',
        14: 'A boca da mulher adúltera é um poço profundo; aquele que está sob a ira de Yahweh cairá nela.',
        15: 'A tolice está ligada ao coração da criança, mas a vara da disciplina a afastará dela.',
        16: 'Aquele que oprime os pobres para aumentar sua riqueza, ou presenteia os ricos, empobrecerá.',
        17: 'Inclina o teu ouvido e escuta as palavras dos sábios e aplica o teu coração ao meu conhecimento,',
        18: 'pois será agradável para ti mantê-las em teu interior e estarem todas prontas em teus lábios.',
        19: 'Para que a tua confiança esteja em Yahweh, eu as ensino hoje, a ti mesmo.',
        20: 'Já não te escrevi trinta ditados de instrução e conhecimento,',
        21: 'para te ensinar a verdade nessas palavras de confiança, para que dês respostas confiáveis a quem te enviou?',
        22: 'Não roubes o pobre, porque ele é pobre, nem esmagues o aflito no portão,',
        23: 'pois Yahweh defenderá a causa deles e tirará a vida de quem os roubar.',
        24: 'Não sejas amigo de alguém que é dominado pela raiva e não andes com quem se enfurece,',
        25: 'para que tu não aprendas seus costumes, nem tua alma se envolva em alguma armadilha.',
        26: 'Não sejas aquele que logo aperta as mãos fazendo promessa, nem aquele que fica por fiador de dívidas.',
        27: 'Se tu não tens como pagar, o que impediria alguém de tirar a tua cama debaixo de ti?',
        28: 'Não removas o limite de pedra antigo que teus pais fixaram.',
        29: 'Já observaste um homem habilidoso em seu trabalho? Ele estará diante de reis, não no meio de pessoas comuns.',
    },
    23: {
        1: 'Quando te assentares para comer com um governador, observa cuidadosamente o que está diante de ti,',
        2: 'e coloca uma faca contra tua garganta, se tu fores uma pessoa que gosta de comer muita comida.',
        3: 'Não desejes as delícias dele, porque é a comida das mentiras.',
        4: 'Não trabalhes excessivamente para ganhar riqueza; sê sábio o suficiente para saber quando parar.',
        5: 'Por acaso, farás teus olhos brilharem pelo que, certamente, cria asas como a águia e sai voando pelo céu.',
        6: 'Não comas a comida daquele que tem o olho mau, nem desejes suas delícias,',
        7: 'porque ele é o tipo de homem que conta o preço da comida. "Come e bebe!", ele te diz, mas o coração dele não está contigo.',
        8: 'Tu vomitarás o pouco que comeste e terás desperdiçado teus elogios.',
        9: 'Não fales aos ouvidos de um tolo, porque ele desprezará a sabedoria de tuas palavras.',
        10: 'Não movas nenhuma pedra de limite antiga, nem invadas os campos dos órfãos,',
        11: 'porque o seu Redentor é forte, e Ele defenderá a causa deles contra ti.',
        12: 'Aplica o teu coração à instrução e os teus ouvidos, às palavras de conhecimento.',
        13: 'Não negues disciplina à criança, pois, se tu a castigares com uma vara, ela não morrerá.',
        14: 'Bata-lhe com uma vara, e salvarás a alma dela do Sheol.',
        15: 'Meu filho, se o teu coração for sábio, então, o meu coração também estará contente;',
        16: 'meu íntimo se alegrará quando os teus lábios falarem o que é correto.',
        17: 'Que o teu coração não inveje os pecadores, mas continue no temor a Yahweh o dia todo.',
        18: 'Certamente, há um futuro e a tua esperança não será eliminada.',
        19: 'Escuta, meu filho — tu mesmo! — sê sábio e dirige o teu coração no caminho.',
        20: 'Não te associes com os bêbados ou com os gulosos, comilões de carne,',
        21: 'pois bêbados e gulosos ficam pobres, e a sonolência os vestirá com trapos.',
        22: 'Escuta o teu pai, que te gerou, e não desprezes a tua mãe quando ela estiver velha.',
        23: 'Compra a verdade, mas não a vendas; compra sabedoria, instrução e entendimento.',
        24: 'O pai do justo grandemente se alegrará, e aquele que gera um filho sábio estará contente nele.',
        25: 'Que teu pai e tua mãe se alegrem, e que aquela que te concebeu se regozije.',
        26: 'Meu filho, dá-me o teu coração, e que os teus olhos observem os meus caminhos.',
        27: 'Pois a prostituta é uma cova profunda, e a mulher imoral, um poço estreito.',
        28: 'Ela fica à espreita como um ladrão e aumenta o número de traidores entre a humanidade.',
        29: 'Quem tem o “Ai”? Quem tem a tristeza? Quem tem as lutas? Quem está reclamando? Quem tem feridas sem causa? Quem tem olhos vermelhos?',
        30: 'Aqueles que passam horas bebendo vinho, aqueles que experimentam o vinho misturado.',
        31: 'Não olhes para o vinho quando está vermelho, quando ele brilha no copo e escorre suavemente.',
        32: 'No fim, ele morde como uma serpente e dá picada à semelhança da víbora.',
        33: 'Teus olhos verão coisas estranhas e o teu coração falará perversidades.',
        34: 'Tu serás como um que dorme em alto mar ou deita-se no topo do mastro.',
        35: '"Golpearam-me!”, tu dirás, "mas não me machucaram. Bateram-me, mas não senti. Quando despertarei para buscar outra bebida?".',
    },
    24: {
        1: 'Não sintas inveja daqueles que são maus, nem desejes associar-te a eles,',
        2: 'porque seus corações planejam violência, e seus lábios falam sobre o mal.',
        3: 'Por meio da sabedoria, uma casa é construída e, pelo entendimento, é estabelecida.',
        4: 'Pelo conhecimento, seus cômodos se enchem com todas as riquezas preciosas e agradáveis.',
        5: 'O guerreiro de sabedoria é forte, e a pessoa de conhecimento aumenta sua força,',
        6: 'porque, pela direção sábia, tu podes fazer a tua guerra e, com muitos conselheiros, há vitória.',
        7: 'A sabedoria é alta demais para o tolo, entre os líderes, no portão, ele não abre sua boca.',
        8: 'Há um que planeja fazer o mal; as pessoas o chamam de mestre das intrigas.',
        9: 'Um plano insensato é pecado, e os homens desprezam o zombador.',
        10: 'Se te mostrares fraco e com medo no dia de dificuldade, então, a tua força é pequena.',
        11: 'Resgata aqueles que são levados à morte, e segura aqueles que cambaleiam para a matança.',
        12: 'Se disseres: "Eis que não sabemos nada sobre isso", por acaso, Aquele que pesa os corações não entende o que estás dizendo? E Aquele que guarda tua vida não sabe? Por acaso, Deus não dará a cada um o que merece?',
        13: 'Meu filho, come mel, porque é bom, porque o gotejamento do favo de mel é doce para o teu paladar.',
        14: 'Assim é a sabedoria para tua alma; se tu a achares, haverá um futuro, e tua esperança não será cortada.',
        15: 'Não fiques à espreita, como o corrupto que ataca a casa do justo. Não destruas a casa dele.',
        16: 'Porque o justo cai sete vezes e se levanta de novo, mas os corruptos são abatidos pela calamidade.',
        17: 'Não celebres quando teu inimigo cair, e que o teu coração não fique contente quando ele tropeçar,',
        18: 'Yahweh verá e desaprovará e desviará Sua fúria dele.',
        19: 'Não te preocupes por causa dos malfeitores, nem invejes os corruptos,',
        20: 'porque a pessoa má não tem futuro, e a lâmpada dos corruptos se apagará.',
        21: 'Teme a Yahweh e teme o rei, meu filho; não te associes com aqueles que se rebelam contra eles,',
        22: 'pois, de repente, seu desastre virá, e quem sabe o tamanho da destruição que virá para ambos?',
        23: 'Estes também são dizeres dos sábios: parcialidade no julgamento de um caso da lei não é bom.',
        24: 'Quem diz ao corrupto: "Tú és justo" será amaldiçoado pelos povos e odiado pelas nações.',
        25: 'Mas aqueles que repreendem o corrupto terão deleite e presentes de bondade virão para eles.',
        26: 'Uma resposta honesta é como um beijo de amizade.',
        27: 'Prepara o teu trabalho de fora e deixa tudo pronto para ti mesmo no campo; depois disso, constrói a tua casa.',
        28: 'Não dês testemunho contra teu próximo sem causa, nem enganes com teus lábios.',
        29: 'Não digas: "Farei a ele o que ele fez a mim; eu lhe pagarei de volta pelo que ele fez".',
        30: 'Eu passei pelo campo do homem preguiçoso, passei pela vinha do homem sem entendimento.',
        31: 'Espinhos cresceram em todo o lugar, a terra estava coberta com urtigas e seu muro de pedra estava derrubado.',
        32: 'Então, eu vi e considerei isso; eu olhei e recebi instrução.',
        33: 'Um pouco dormindo, uma pouco cochilando, um pouco descansando de braços cruzados;',
        34: 'e a pobreza vem sobre ti como um ladrão, e as tuas necessidades, como um soldado armado.',
    },
    25: {
        1: 'Estes também são provérbios de Salomão, copiados pelos homens de Ezequias, rei de Judá.',
        2: 'A glória de Deus é encobrir as coisas, mas a glória dos reis é investigá-las.',
        3: 'Como os céus estão em altura e a terra em profundidade, assim o coração dos reis é indecifrável.',
        4: 'Remove a escória da prata e o fundidor poderá usar prata em sua obra.',
        5: 'Assim também, remove os ímpios da presença do rei e seu trono será estabelecido fazendo o que é justo.',
        6: 'Não honres a ti mesmo na presença do rei e não te coloques num lugar designado para os grandes.',
        7: 'É melhor que ele te diga: "Sobe aqui", do que tu seres humilhado por ele na presença de um nobre. O que tu testemunhaste',
        8: 'não tragas, apressadamente, diante do tribunal. O que tu farás no final, quando o teu próximo te envergonhar?',
        9: 'Discute o teu caso entre ti e teu próximo e não reveles o segredo de outrem,',
        10: 'ou aquele que te ouve trará vergonha sobre ti e a má fama a teu respeito não poderá ser silenciada.',
        11: 'Como maçãs de ouro em engastes de prata, assim é a palavra falada no tempo certo.',
        12: 'Como um brinco de ouro ou uma joia feita de ouro fino, assim é a repreensão sábia para um ouvido atento.',
        13: 'Como o frio da neve no tempo da colheita, assim é o mensageiro fiel para aqueles que o enviam, ele restaura a vida dos seus senhores.',
        14: 'Como nuvens e vento sem chuva, assim é aquele que se gaba de um presente que ele não deu.',
        15: 'Com paciência, um comandante pode ser persuadido, e uma língua suave pode quebrar um osso.',
        16: 'Se tu encontrares mel, come só o suficiente, senão, terás demais e vomitarás.',
        17: 'Não ponhas o teu pé com muita frequência na casa do teu próximo, ele poderá se cansar de ti e te odiar.',
        18: 'O homem que levanta falso testemunho contra o seu próximo é como um bastão usado na guerra, ou uma espada, ou uma flecha afiada.',
        19: 'Um homem infiel no qual tu confias no tempo de dificuldades é como um dente quebrado ou um pé que escorrega.',
        20: 'Como a pessoa que tira a roupa no tempo frio, ou como vinagre derramado sobre a soda, assim é aquele que canta canções para um coração pesado.',
        21: 'Se o teu inimigo está faminto, dá-lhe alimento para comer e, se ele está com sede, dá-lhe água para beber,',
        22: 'porque tu colocarás brasas ardentes sobre a sua cabeça e Yahweh te recompensará.',
        23: 'Tão certo como o vento norte traz a chuva, assim a língua que conta segredos produz rostos enraivecidos.',
        24: 'É melhor viver no canto do terraço que compartilhar a casa com uma mulher briguenta.',
        25: 'Como água fria para o que está com sede, assim são as boas notícias de um país distante.',
        26: 'Como a nascente suja ou a fonte arruinada, assim é o justo que cambaleia diante dos ímpios.',
        27: 'Não é bom comer muito mel, assim como buscar honra sobre honra.',
        28: 'A pessoa sem domínio próprio é como uma cidade com brechas ou sem muros.',
    },
    26: {
        1: 'Como a neve no verão ou a chuva na colheita, assim o tolo não merece honra.',
        2: 'Como o pardal bate asas e a andorinha se move ao voar, assim também a maldição injusta não se cumpre.',
        3: 'O chicote é para o cavalo, a rédea é para o jumento, e a vara é para as costas dos tolos.',
        4: 'Não respondas ao tolo conforme a sua insensatez, ou te tornarás como ele.',
        5: 'Responde ao tolo conforme é apropriado à insensatez dele, para que ele não se torne sábio aos seus próprios olhos.',
        6: 'Quem envia uma mensagem pela mão do tolo corta seus próprios pés e bebe violência.',
        7: 'Como as pernas de um paralítico, que pendem frouxas, assim é um provérbio na boca dos tolos.',
        8: 'Como amarrar uma pedra na funda, assim é dar honra ao tolo.',
        9: 'Como um espinho que entra na mão de um bêbado, assim é um provérbio na boca dos tolos.',
        10: 'Como um arqueiro que fere todos ao seu redor, assim é aquele que contrata um tolo ou qualquer um que passa.',
        11: 'Como um cachorro que retorna ao seu próprio vômito, assim é o tolo que repete a sua insensatez.',
        12: 'Vês alguém que é sábio a seus próprios olhos? Há mais esperança para o tolo do que para ele.',
        13: 'O preguiçoso diz: "Há um leão na estrada! Há um leão entre os lugares abertos!".',
        14: 'Assim como a porta vira nas dobradiças, assim é o preguiçoso sobre sua cama.',
        15: 'O preguiçoso põe sua mão no prato e nem sequer tem força para levá-la à boca.',
        16: 'O preguiçoso é mais sábio aos seus próprios olhos do que sete homens que respondem com bom senso.',
        17: 'Como aquele que segura as orelhas de um cão, assim é quem está passando e se enfurece numa disputa que não é sua.',
        18: 'Como o louco que atira flechas flamejantes,',
        19: 'assim é aquele que engana seu próximo e diz: "Eu estava brincando!".',
        20: 'Por falta de madeira, o fogo se apaga e, onde não há mexeriqueiro, a rixa cessa.',
        21: 'Como o carvão é para a brasa e a madeira para o fogo, assim é o briguento para acender um conflito.',
        22: 'As palavras do mexeriqueiro são como iguarias deliciosas, que descem ao interior do corpo.',
        23: 'Como a cobertura brilhante de um vaso de barro, assim são os lábios ardentes com um coração mau.',
        24: 'Aquele que odeia os outros disfarça, com os lábios, os seus sentimentos e armazena o engano dentro de si.',
        25: 'Ele falará graciosamente, mas não acredites nele, pois há sete abominações em seu coração.',
        26: 'Apesar de seu ódio estar encoberto pelo engano, sua perversidade será exposta na assembleia.',
        27: 'Aquele que cava uma cova, nela cairá; e a pedra rolará de volta ao que a empurrou.',
        28: 'A língua mentirosa odeia as pessoas que ela oprime, e a boca bajuladora causa a ruína.',
    },
    27: {
        1: 'Não te gabes sobre o amanhã, pois não sabes o que o dia poderá trazer.',
        2: 'Que outros te elogiem, não a tua própria boca, um estranho, e não teus próprios lábios.',
        3: 'Considera o peso de uma pedra e o peso da areia; a provocação do tolo é mais pesada que ambas.',
        4: 'Existe a crueldade da raiva e o transbordar da ira, mas quem é capaz de suportar o ciúme?',
        5: 'É melhor a repreensão aberta que o amor escondido.',
        6: 'Fiéis são as feridas causadas por um amigo, mas um inimigo pode beijar-te abundantemente.',
        7: 'Uma pessoa que está saciada rejeita até mesmo o favo de mel, mas, para o faminto, todo amargo é doce.',
        8: 'Como um pássaro que vai sem rumo, longe de seu ninho, assim é o homem que se afasta de onde vive.',
        9: 'Perfume e incenso fazem o coração alegrar-se, mas a doçura de um amigo vem de seu conselho sincero.',
        10: 'Não abandones teu amigo e o amigo de teu pai, e não vás à casa de teu irmão no dia da tua calamidade. Melhor é um vizinho que está próximo que um irmão que está longe.',
        11: 'Sê sábio, meu filho, e faz meu coração alegrar-se; então, eu responderei àquele que zomba de mim.',
        12: 'O homem prudente vê a adversidade e se esconde, mas os ingênuos seguem adiante e sofrem por causa disso.',
        13: 'Toma a veste daquele que se pôs por fiador de um estranho; e toma-a em penhor quando ele se tornar fiador de uma mulher imoral.',
        14: 'Aquele que bendisser seu vizinho em alta voz pela manhã, essa bênção será considerada uma maldição!',
        15: 'Uma esposa briguenta é como uma goteira constante em dia de chuva;',
        16: 'impedi-la é como tentar impedir o vento, ou tentar pegar óleo com a mão direita.',
        17: 'Ferro afia ferro; do mesmo modo, o homem afia seu amigo.',
        18: 'O que cuida da figueira comerá seu fruto, e o que protege seu senhor será honrado.',
        19: 'Como a água reflete a face de uma pessoa, assim o coração da pessoa reflete o que ela é.',
        20: 'Como o Sheol e Abaddon nunca estão satisfeitos, assim os olhos do homem nunca se satisfazem.',
        21: 'O crisol é para a prata e o forno é para o ouro; e uma pessoa é testada quando é elogiada.',
        22: 'Mesmo que tritures o tolo com o pilão, junto com o grão, ainda assim, a insensatez não o deixará.',
        23: 'Certifica-te de conheceres a condição de teus rebanhos, e preocupa-te com tuas manadas,',
        24: 'pois a riqueza não é para sempre. Por acaso uma coroa dura por todas as gerações?',
        25: 'Tu deves saber quando o feno é removido e os novos brotos aparecem, e o tempo em que a grama das montanhas é colhida.',
        26: 'Aqueles cordeiros fornecerão tuas roupas, e os bodes fornecerão o preço do campo.',
        27: 'Haverá leite das cabras para tua alimentação — o alimento de tua casa — e nutrição para tuas servas.',
    },
    28: {
        1: 'Os corruptos fogem quando ninguém os persegue, mas os justos são ousados como um leão jovem.',
        2: 'Por causa da transgressão da terra, ela possui muitos governantes, mas, com um homem de entendimento e conhecimento, ela durará muito tempo.',
        3: 'O pobre que oprime outro pobre é como chuva forte que não deixa alimento.',
        4: 'Aqueles que abandonam a lei elogiam os corruptos, mas aqueles que guardam a lei lutam contra eles.',
        5: 'Os homens maus não entendem a justiça, mas aqueles que buscam a Yahweh entendem tudo.',
        6: 'É melhor o pobre que anda em sua integridade que o rico que é tortuoso em seus caminhos.',
        7: 'Aquele que guarda a lei é um filho com entendimento, mas aquele que é companheiro dos gulosos envergonha seu pai.',
        8: 'Aquele que faz sua fortuna cobrando muitos juros ajunta sua riqueza para outro que terá compaixão dos pobres.',
        9: 'Se alguém desvia o ouvido de ouvir a lei, até a sua oração é detestável.',
        10: 'Quem fizer desviar o justo para o mau caminho cairá em sua própria cova, mas os irrepreensíveis terão uma boa herança.',
        11: 'O rico é sábio aos seus próprios olhos, mas o pobre que tem entendimento o avaliará.',
        12: 'Quando os justos triunfam, há grande glória, mas, quando os corruptos se levantam, o povo se esconde.',
        13: 'Aquele que esconde seus pecados não prosperará, mas aquele que os confessa e os abandona alcançará misericórdia.',
        14: 'Abençoado será aquele que sempre vive com reverência, mas quem endurece seu coração cairá em dificuldades.',
        15: 'Como um leão rugindo ou um urso quando ataca, assim é o governante corrupto sobre os pobres.',
        16: 'O governante a quem falta entendimento é um opressor cruel, mas aquele que odeia a desonestidade prolongará seus dias.',
        17: 'Se um homem é culpado porque derramou o sangue de alguém, ele será um fugitivo até a morte, e ninguém o ajudará.',
        18: 'Quem caminha com integridade será mantido a salvo, mas aquele que tem o caminho torto cairá logo.',
        19: 'Aquele que lavra a sua terra terá muita comida, mas quem segue objetivos inúteis terá muita pobreza.',
        20: 'O homem fiel terá grandes bênçãos, mas aquele que se enriquece rapidamente não ficará impune.',
        21: 'Não é bom mostrar parcialidade, mas, por um pedaço de pão, o homem cometerá uma transgressão.',
        22: 'O homem mesquinho corre atrás de riquezas, mas ele não sabe que a pobreza virá sobre ele.',
        23: 'Quem repreende alguém alcançará dele mais favor do que alguém que o bajule com sua língua.',
        24: 'Qualquer um que rouba seu pai e sua mãe e diz: "Isso não é pecado", esse é companheiro do que destrói.',
        25: 'O homem ganancioso provoca conflitos, mas o que confia em Yahweh prosperará.',
        26: 'Aquele que confia em seu próprio coração é um tolo, mas quem anda em sabedoria será mantido longe do perigo.',
        27: 'Àquele que dá aos pobres não lhe faltará nada, mas quem fecha os olhos para eles receberá muitas maldições.',
        28: 'Quando os corruptos se levantam, o povo se esconde, mas quando eles perecem, os justos aumentam.',
    },
    29: {
        1: 'A pessoa que recebeu muitas repreensões, mas endurece seu pescoço, será quebrada a tal ponto que não poderá ser curada.',
        2: 'Quando os justos se multiplicam, o povo se alegra, mas quando um ímpio é o governante, o povo suspira.',
        3: 'Aquele que ama a sabedoria faz seu pai regozijar-se, mas o que mantém a companhia de prostitutas destrói sua riqueza.',
        4: 'O rei estabelece a terra pela justiça, mas o que exige subornos a destrói.',
        5: 'O homem que bajula seu vizinho espalha uma rede para seus pés.',
        6: 'No pecado de uma pessoa má, existe uma armadilha, mas o justo canta e regozija-se.',
        7: 'O justo conhece os direitos do pobre; o corrupto não entende tal conhecimento.',
        8: 'Os zombadores incendeiam uma cidade, mas os que são sábios afastam a ira.',
        9: 'Quando um sábio tem uma discussão com um tolo, ele ri e se irrita, e não haverá descanso.',
        10: 'Os sanguinários odeiam o que não tem culpa e buscam a vida dos justos.',
        11: 'O tolo revela toda a sua ira, mas o homem sábio a contém e se acalma.',
        12: 'Se um governante presta atenção a mentiras, todos os seus oficiais serão corruptos.',
        13: 'O pobre e o opressor têm algo em comum, pois Yahweh dá luz aos olhos de ambos.',
        14: 'Se um rei julga os pobres com a verdade, seu trono será estabelecido para sempre.',
        15: 'A vara e a reprovação dão sabedoria, mas uma criança livre de disciplina envergonha sua mãe.',
        16: 'Quando os corruptos estão no poder, a transgressão aumenta, mas os justos verão a queda desses ímpios.',
        17: 'Dá disciplina ao teu filho, e ele te dará descanso; ele trará deleite para a tua vida.',
        18: 'Onde não há profecia, o povo perde o controle próprio, mas aquele que mantém a lei é abençoado.',
        19: 'O escravo não será corrigido por palavras, pois, apesar de ele entender, não haverá resposta.',
        20: 'Vês um homem precipitado em suas palavras? Há mais esperança para o tolo que para ele.',
        21: 'O que mima seu escravo desde a infância, no final disso, terá problemas.',
        22: 'Uma pessoa irada provoca conflito, e o enfurecido comete muitos pecados.',
        23: 'O orgulho de uma pessoa a humilha, mas o que tem um espírito humilde receberá honra.',
        24: 'O que é cúmplice de um ladrão odeia sua própria vida; ele ouve a maldição e não diz nada.',
        25: 'O medo do homem monta uma armadilha, mas o que confia em Yahweh será protegido.',
        26: 'Muitos são os que buscam a face do governante, mas o homem recebe a justiça que vem de Yahweh.',
        27: 'O homem injusto é uma abominação para os justos, mas aquele cujo caminho é correto é detestável para o corrupto.',
    },
    30: {
        1: 'As palavras de Agur, filho de Jaque — um enunciado. Este homem declarou para Itiel, Itiel e Ucal:',
        2: 'Certamente, eu sou mais como um animal do que como ser humano; não tenho o entendimento do ser humano.',
        3: 'Não aprendi a sabedoria, e não tenho o conhecimento do Santo.',
        4: 'Quem subiu ao céu e, de lá, desceu? Quem recolheu o vento no vazio de suas mãos? Quem reuniu as águas em um manto? Quem estabeleceu todas as extremidades da terra? Qual é o seu nome, e qual é o nome do seu filho? Se é que o sabes.',
        5: 'Toda palavra de Deus é pura. Ele é um escudo para os que Nele se refugiam.',
        6: 'Nada adiciones às Suas palavras, ou Ele te repreenderá e provará que és mentiroso.',
        7: 'Duas coisas eu peço a ti, não as retenhas de mim antes que eu morra.',
        8: 'Coloca a vaidade e a mentira longe de mim. Não me dês nem a pobreza nem a riqueza, somente a comida de que preciso.',
        9: 'Porque se eu tiver muito, Te negarei e direi: "Quem é Yahweh?" Ou se ficar pobre, roubarei e profanarei o Teu nome.',
        10: 'Não difameis um escravo diante do seu senhor, ou ele vos amaldiçoará, e vós sereis culpados.',
        11: 'A geração que amaldiçoa seu pai e não abençoa sua mãe',
        12: 'é a geração que é pura aos seus próprios olhos, mas não é lavada da sua imundícia.',
        13: 'Esta é a geração — quão altivos são seus olhos e levantadas as suas pálpebras! —',
        14: 'cujos dentes são espadas e suas mandíbulas são facas. Assim, eles podem devorar da terra os pobres e, da humanidade, os necessitados.',
        15: 'A sanguessuga tem duas filhas, "Dá e Dá", elas choram. Há três coisas que nunca estão satisfeitas, quatro que nunca dizem: “Basta!”',
        16: 'O Sheol, o útero estéril, a terra sedenta por água e o fogo que nunca diz: "Basta".',
        17: 'Os olhos que zombam do pai e desprezam a obediência da mãe; seus olhos serão arrancados pelos corvos do vale e comidos por abutres.',
        18: 'Há três coisas que são maravilhosas demais para mim, quatro que eu não entendo:',
        19: 'o caminho da águia para o céu, o caminho da cobra para a rocha, o caminho do navio no meio do mar e o caminho do homem com uma mulher virgem.',
        20: 'Este é o caminho de uma adúltera — ela come, limpa seus lábios, e diz: "Não fiz nada de errado".',
        21: 'Há três coisas que fazem a terra estremecer e a quarta, ela não pode suportar:',
        22: 'um escravo quando se torna rei; um tolo quando se farta de comer;',
        23: 'uma mulher odiada quando se casa; e uma empregada quando ela toma o lugar da sua senhora.',
        24: 'Quatro coisas são pequenas na terra e, ainda assim, são muito sábias:',
        25: 'as formigas, criaturas que não são fortes, mas preparam a comida no verão;',
        26: 'os coelhos, criaturas que não são poderosas, mas fazem suas casas nas rochas.',
        27: 'Os gafanhotos que não têm rei, mas todos eles marcham enfileirados.',
        28: 'Quanto ao lagarto, podes segurá-lo em tuas mãos, ainda assim, eles são encontrados nos palácios dos reis.',
        29: 'Há três coisas que são imponentes em seu caminhar, quatro que são imponentes na forma que andam:',
        30: 'o leão, o mais forte entre os animais selvagens, não foge de nada;',
        31: 'um galo firmado em esporas, um bode, e um rei, cujos soldados estão ao seu lado.',
        32: 'Se tens sido um tolo, exaltando-te a ti mesmo, ou se tens concebido o mal — coloca tuas mãos sobre a boca.',
        33: 'Assim como bater o leite produz manteiga, e o nariz produz sangue se for torcido, assim as obras feitas com raiva produzem conflito.',
    },
    31: {
        1: 'Palavras do rei Lemuel, um oráculo ensinado por sua mãe.',
        2: 'O quê, meu filho? O quê, filho do meu ventre? O quê, filho dos meus votos?',
        3: 'Não dês tua força às mulheres, ou os teus caminhos àqueles que destroem reis.',
        4: 'Não convém a reis, Lemuel, não convém a reis beber vinho, nem a governantes desejar a bebida forte;',
        5: 'porque quando eles bebem, esquecem-se do que foi decretado, e pervertem os direitos de todos os aflitos.',
        6: 'Dai bebida forte ao que está perecendo e vinho aos amargurados.',
        7: 'Ele beberá e se esquecerá de sua pobreza, e não se lembrará de suas dificuldades.',
        8: 'Fala por aqueles que não podem falar, pelas causas de todos os que estão perecendo.',
        9: 'Fala e julga pela medida do que é justo, e defende a causa dos pobres e necessitados.',
        10: 'Quem pode achar uma esposa virtuosa? Seu valor vai muito além de joias.',
        11: 'O coração de seu marido confia nela e ele não terá falta de nada.',
        12: 'Ela faz coisas boas por ele e não más, todos os dias de sua vida.',
        13: 'Ela escolhe lã e linho, e trabalha com o deleite de suas mãos.',
        14: 'Ela é como os navios mercantes, traz comida de longe.',
        15: 'Ela se levanta enquanto é noite, dá comida à sua família e distribui as tarefas entre suas servas.',
        16: 'Ela avalia um campo e o compra, com o fruto de suas mãos, planta uma vinha.',
        17: 'Ela se veste de força e fortalece os seus braços.',
        18: 'Ela percebe o que lhe trará bom lucro; durante toda a noite, sua lâmpada não se apaga.',
        19: 'Ela põe suas mãos no fuso e segura a roca de fiar.',
        20: 'Ela estende sua mão aos pobres, estende suas mãos aos necessitados.',
        21: 'Ela não teme a neve por sua família, pois toda a sua família está vestida com lã escarlate.',
        22: 'Ela faz cobertas para sua cama e veste-se de roupas de linho púrpura.',
        23: 'Seu marido é conhecido junto aos portões, quando ele se assenta com os anciãos da terra.',
        24: 'Ela faz vestes de linho e as vende, fornece faixas aos comerciantes.',
        25: 'Ela se veste de força e honra e ri para o futuro.',
        26: 'Ela abre sua boca com sabedoria e a lei dos benevolentes está em sua língua.',
        27: 'Ela vigia os caminhos de sua casa e não come do pão da preguiça.',
        28: 'Seus filhos crescem e a chamam de abençoada; seu marido a elogia, dizendo:',
        29: '"Muitas mulheres fizeram o bem, mas tu a todas superas".',
        30: 'A elegância é enganosa, a beleza é fútil, mas a mulher que teme a Yahweh, essa será elogiada.',
        31: 'Dai a ela o fruto de suas mãos e que seu trabalho a engrandeça nos portões.',
    },
}
