NAME = 'FreBBB: French Bible Bovet Bonnet (1900)'
BOOK = 'I Thessalonians'

CHAPTERS = {
    1: {
        1: "Paul, et Silvain, et Timothée, à l'Eglise des Thessaloniciens, en Dieu le Père, et dans le Seigneur Jésus-Christ: Que la grâce et la paix vous soient données!",
        2: 'Nous rendons toujours grâces à Dieu pour vous tous, faisant mention de vous dans nos prières;',
        3: "nous rappelant sans cesse, devant notre Dieu et Père, l'œuvre de votre foi, et le travail de votre charité, et la constance de votre espérance en notre Seigneur Jésus-Christ;",
        4: 'sachant, frères, bien-aimés de Dieu, votre élection,',
        5: "parce que notre Evangile n'a pas consisté à votre égard en parole seulement, mais aussi en puissance, et en Esprit saint, et en pleine persuasion, ainsi que vous savez quels nous avons été parmi vous à cause de vous;",
        6: "vous aussi, vous avez été nos imitateurs et ceux du Seigneur, ayant reçu la Parole au milieu de beaucoup d'afflictions avec la joie du Saint-Esprit;",
        7: "de sorte que vous êtes devenus un modèle pour tous ceux qui croient dans la Macédoine et dans l'Achaïe;",
        8: "car la Parole du Seigneur a retenti de chez vous, non seulement dans la Macédoine et dans l'Achaïe: mais la foi que vous avez en Dieu s'est répandue en tout lieu, de sorte que nous n'avons pas besoin d'en rien dire.",
        9: 'Car eux-mêmes racontent à notre sujet quel accès nous avons eu auprès de vous; et comment vous vous êtes convertis des idoles à Dieu, pour servir le Dieu vivant et véritable,',
        10: "et pour attendre des cieux son Fils, qu'il a ressuscité des morts, Jésus, qui nous délivre de la colère à venir.",
    },
    2: {
        1: "Vous savez vous-mêmes, frères, que notre entrée auprès de vous n'a point été vaine;",
        2: "mais ayant auparavant souffert et été outragés à Philippes, comme vous le savez, nous prîmes confiance en notre Dieu, pour vous annoncer l'Evangile de Dieu au milieu d'un grand combat.",
        3: "Car notre prédication n'a pas été faite par suite d'erreur ni par un motif impur, ni avec ruse;",
        4: "mais comme nous avons été jugés dignes par Dieu pour que l'Evangile nous fût confié, ainsi nous parlons, non pour plaire aux hommes, mais à Dieu qui éprouve nos cœurs.",
        5: "Car aussi nous n'avons jamais usé de paroles de flatterie, comme vous le savez, ni de prétextes d'avarice; Dieu en est témoin.",
        6: "Et nous n'avons point cherché la gloire qui vient des hommes, ni de vous, ni des autres, quoique nous pussions, comme apôtres de Christ, user d'autorité;",
        7: 'mais nous avons été doux au milieu de vous; comme une nourrice prend un tendre soin de ses propres enfants,',
        8: "ainsi, ayant une tendre affection pour vous, nous aurions voulu vous donner, non seulement l'Evangile de Dieu, mais aussi nos propres vies, tant vous nous étiez devenus chers.",
        9: "Car vous vous rappelez, frères, notre fatigue et notre peine; et comment nous vous avons prêché l'Evangile de Dieu, travaillant nuit et jour, pour n'être à charge à aucun de vous.",
        10: "Vous êtes témoins, et Dieu l'est aussi, combien nous nous sommes conduits saintement et justement, et d'une manière irréprochable envers vous qui croyez;",
        11: 'ainsi que vous le savez, exhortant et consolant chacun de vous, comme un père ses enfants;',
        12: "et vous conjurant de marcher d'une manière digne de Dieu, qui vous appelle à son royaume et à sa gloire.",
        13: "Et pour cela aussi, nous rendons grâces à Dieu sans cesse, de ce que, recevant de nous la Parole de Dieu que nous prêchons, vous l'avez reçue non comme une parole d'hommes, mais ainsi qu'elle l'est véritablement, comme la Parole de Dieu, laquelle agit avec efficace en vous qui croyez.",
        14: "En effet, frères, vous êtes devenus imitateurs des Eglises de Dieu qui sont en Judée, en Jésus-Christ; car vous aussi, vous avez souffert de la part de vos propres compatriotes les mêmes maux qu'elles aussi ont soufferts de la part des Juifs,",
        15: 'qui ont fait mourir et le Seigneur Jésus et les prophètes, et qui nous ont persécutés, et qui déplaisent à Dieu, et sont ennemis de tous les hommes,',
        16: "nous empêchant de parler aux païens afin qu'ils soient sauvés, pour combler toujours la mesure de leurs péchés. Mais la colère est parvenue sur eux au dernier terme.",
        17: "Pour nous, frères, ayant été séparés de vous pour un peu de temps, de visage, non de cœur, nous avons cherché avec d'autant plus d'empressement à voir votre visage, le souhaitant avec ardeur.",
        18: "C'est pourquoi nous avons voulu, et une fois et deux fois, aller vers vous, au moins moi, Paul; et Satan nous en a empêché.",
        19: "Car qui sera notre espérance, ou notre joie, ou notre couronne de gloire, si ce n'est vous aussi en la présence de notre Seigneur Jésus, à son avènement?",
        20: "Car c'est vous qui êtes notre gloire et notre joie.",
    },
    3: {
        1: "C'est pourquoi, n'y tenant plus, nous trouvâmes bon d'être laissé seul à Athènes,",
        2: "et de vous envoyer Timothée notre frère, coopérateur de Dieu dans l'Evangile de Christ, pour vous affermir, et vous exhorter au sujet de votre foi;",
        3: 'afin que personne ne fût ébranlé dans ces afflictions; car vous savez vous-mêmes que nous sommes destinés à cela.',
        4: 'Et, en effet, lorsque nous étions près de vous, nous vous prédisions que nous aurions à souffrir des afflictions; comme cela est aussi arrivé, et vous le savez.',
        5: "C'est pourquoi, moi aussi, n'y tenant plus, j'envoyai pour connaître votre foi, craignant que le tentateur ne vous eût tentés, et que notre travail ne fût devenu vain.",
        6: "Mais maintenant Timothée étant revenu vers nous d'auprès de vous, et nous ayant apporté de bonnes nouvelles de votre foi et de votre charité, et du bon souvenir que vous avez toujours de nous, désirant nous voir, comme nous désirons aussi vous voir,",
        7: 'nous avons donc été consolés, frères, à votre sujet par votre foi, dans toute notre nécessité et notre affliction.',
        8: 'Car maintenant nous vivons, si vous demeurez fermes dans le Seigneur.',
        9: 'Car quelles actions de grâces ne pouvons-nous pas rendre à Dieu à votre sujet, pour toute la joie dont nous nous réjouissons à cause de vous, en la présence de notre Dieu!',
        10: "priant jour et nuit avec d'autant plus d'ardeur pour voir votre visage et compléter ce qui manque à votre foi.",
        11: 'Or, notre Dieu et Père lui-même et notre Seigneur Jésus veuillent aplanir notre chemin auprès de vous!',
        12: 'Et vous, que le Seigneur vous fasse croître et abonder en charité les uns envers les autres et envers tous, comme nous aussi envers vous;',
        13: 'pour affermir vos cœurs et les rendre irrépréhensibles dans la sainteté, devant notre Dieu et Père, en la venue de notre Seigneur Jésus avec tous ses saints!',
    },
    4: {
        1: 'Au reste donc, frères, nous vous prions et nous vous exhortons dans le Seigneur Jésus, que, comme vous avez reçu de nous de quelle manière il vous faut marcher et plaire à Dieu, comme aussi vous le faites, vous y abondiez de plus en plus.',
        2: 'Car vous savez quels préceptes nous vous avons donnés par le Seigneur Jésus.',
        3: "Car ce que Dieu veut, c'est votre sanctification; c'est que vous vous absteniez de l'impudicité;",
        4: "que chacun de vous sache posséder son propre corps dans la sainteté et dans l'honneur,",
        5: 'non en passion de convoitise comme les païens qui ne connaissent point Dieu;',
        6: "que personne ne foule son frère, ni ne lui fasse tort dans les affaires, parce que le Seigneur est vengeur de toutes ces choses, comme nous vous l'avons déjà dit et attesté auparavant.",
        7: "Car Dieu ne nous a point appelés à l'impureté, mais à la sanctification.",
        8: 'Ainsi donc, celui qui nous rejette, ne rejette pas un homme, mais Dieu, qui aussi vous donne son Esprit saint.',
        9: "Pour ce qui est de l'amour fraternel, nous n'avons pas besoin de vous en écrire; car vous-mêmes vous êtes enseignés de Dieu à vous aimer les uns les autres;",
        10: 'et vous le faites aussi envers tous les frères dans toute la Macédoine; mais nous vous exhortons, frères, à y abonder de plus en plus;',
        11: "et à mettre votre honneur à vivre paisiblement; et à vous occuper de vos propres affaires, et à travailler de vos mains, comme nous vous l'avons recommandé;",
        12: "afin que vous vous conduisiez honnêtement envers ceux du dehors, et que vous n'ayez besoin de personne.",
        13: "Or, nous ne voulons pas, frères, que vous soyez dans l'ignorance au sujet de ceux qui dorment, afin que vous ne soyez pas attristés comme les autres, qui n'ont point d'espérance.",
        14: "Car si nous croyons que Jésus est mort, et qu'il est ressuscité, de même aussi Dieu ramènera par Jésus, avec lui, ceux qui se sont endormis.",
        15: "Car nous vous disons ceci par une parole du Seigneur, c'est que nous, les vivants, qui sommes laissés pour la venue du Seigneur, nous ne devancerons point ceux qui se sont endormis.",
        16: "Parce que lui-même, le Seigneur, à un signal de commandement, à la voix d'un archange, et au son d'une trompette de Dieu, descendra du ciel, et les morts en Christ ressusciteront premièrement;",
        17: "ensuite nous, les vivants qui sommes laissés, nous serons enlevés ensemble avec eux dans les nuées, au-devant du Seigneur en l'air, et ainsi nous serons toujours avec le Seigneur.",
        18: "C'est pourquoi consolez-vous les uns les autres par ces paroles.",
    },
    5: {
        1: "Pour ce qui regarde les temps et les époques, vous n'avez pas besoin, frères, qu'on vous en écrive;",
        2: 'car vous-mêmes vous savez très bien que le jour du Seigneur vient comme un voleur dans la nuit.',
        3: "Quand ils diront: paix et sûreté, alors une ruine subite les surprendra, comme les douleurs surprennent la femme enceinte, et ils n'échapperont point.",
        4: "Mais vous, frères, vous n'êtes point dans les ténèbres, pour que ce jour vous surprenne comme un voleur;",
        5: 'car vous êtes tous fils de la lumière et fils du jour; nous ne sommes point de la nuit ni des ténèbres.',
        6: 'Ne dormons donc pas comme les autres, mais veillons et soyons sobres.',
        7: "Car ceux qui dorment, dorment la nuit, et ceux qui s'enivrent, s'enivrent la nuit.",
        8: "Mais nous qui sommes du jour, soyons sobres, ayant revêtu la cuirasse de la foi et de la charité, et ayant pour casque l'espérance du salut.",
        9: "Car Dieu ne nous a point destinés à la colère, mais à l'acquisition du salut, par notre Seigneur Jésus-Christ,",
        10: 'qui est mort pour nous, afin que, soit que nous veillions, soit que nous dormions, nous vivions ensemble avec lui.',
        11: "C'est pourquoi exhortez-vous les uns les autres, et édifiez-vous l'un l'autre, comme aussi vous le faites.",
        12: "Or, nous vous prions, frères, d'avoir en considération ceux qui travaillent parmi vous, et qui président sur vous dans le Seigneur, et qui vous avertissent.",
        13: 'Estimez-les extrêmement avec amour, à cause de leur œuvre. Soyez en paix entre vous.',
        14: 'Or, nous vous exhortons, frères, avertissez ceux qui sont déréglés, consolez les découragés, soutenez les faibles, soyez patients envers tous.',
        15: "Prenez garde que quelqu'un ne rende à autrui mal pour mal; mais poursuivez toujours le bien, et les uns envers les autres, et à l'égard de tous.",
        16: 'Soyez toujours joyeux.',
        17: 'Priez sans cesse.',
        18: 'Rendez grâces en toutes choses; car cela est la volonté de Dieu, en Jésus-Christ à votre égard.',
        19: "N'éteignez point l'Esprit.",
        20: 'Ne méprisez point les prophéties,',
        21: 'mais éprouvez toutes choses, retenez ce qui est bon.',
        22: 'Abstenez vous de toute espèce de mal.',
        23: "Or, que lui-même, le Dieu de la paix, vous sanctifie parfaitement, et que votre être entier, l'esprit, l'âme et le corps, soit conservé irrépréhensible en l'avènement de notre Seigneur Jésus-Christ.",
        24: "Celui qui vous appelle est fidèle, et c'est lui aussi qui le fera.",
        25: 'Frères, priez pour nous.',
        26: 'Saluez tous les frères par un saint baiser.',
        27: 'Je vous adjure par le Seigneur, que cette épître soit lue à tous les frères.',
        28: 'La grâce de notre Seigneur Jésus-Christ soit avec vous.',
    },
}
