NAME = 'FreOltramare1874: Le Nouveau Testament Version Oltramare 1874'
BOOK = 'I Peter'

CHAPTERS = {
    1: {
        1: "Pierre, Apôtre de Jésus-Christ, aux fidèles qui sont étrangers et dispersés dans le Pont, dans la Galatie, dans la Cappadoce, dans l'Asie et dans la Bithynie,",
        2: 'qui sont élus selon la prescience de Dieu, le Père, et sanctifiés en leur esprit, pour être obéissants et purifiés par l’aspersion du sang de Jésus-Christ: que la grâce et la paix vous soient données de plus en plus!',
        3: "Béni soit Dieu, le Père de notre Seigneur Jésus-Christ, de ce que, dans sa grande miséricorde, il nous a régénérés, pour que nous ayons une espérance vivifiante, par la résurrection de Jésus-Christ d'entre les morts,",
        4: 'un héritage qui ne se peut ni gâter, ni souiller, ni flétrir. Il nous le réserve dans les cieux,',
        5: 'et sa puissance nous garde par la foi, pour nous mettre en possession du salut, qui est prêt à apparaître au moment final.',
        6: "Cette pensée vous remplit de joie, quoique maintenant, puisqu'il le faut, vous soyez attristés pour un peu de temps par diverses épreuves,",
        7: "afin que la solidité éprouvée de votre foi, qui est plus précieuse que l'or périssable, qu'on éprouve cependant par le feu, vous soit un sujet de louange, d'honneur et de gloire, quand Jésus-Christ paraîtra.",
        8: "Vous l’aimez, sans l'avoir vu; et, en croyant en lui quoique vous ne le voyiez point encore, vous tressaillez d'une joie ineffable et glorieuse,",
        9: 'parce que vous allez remporter le salut de vos âmes, qui est le but de votre foi.',
        10: "Ce salut a été l'objet des recherches et des investigations des prophètes qui ont parlé de la grâce qui vous est destinée.",
        11: "Ils recherchaient à quel temps et à quelles circonstances faisait allusion l'Esprit de Christ qui était en eux, et qui annonçait d'avance les souffrances réservées au Christ, et les gloires qui devaient les suivre.",
        12: "Il leur fut révélé que c'était, non pour eux-mêmes, mais pour nous, que leur ministère était requis pour les choses, que ceux qui vous ont prêché l'évangile par le Saint-Esprit envoyé du ciel, vous ont maintenant annoncées, et dans lesquelles les anges désirent plonger leurs regards.",
        13: "C'est pourquoi, ayant ceint les reins de votre esprit, étant sobres, attendez avec une parfaite espérance la grâce qui vous sera apportée, quand Jésus-Christ paraîtra.",
        14: "Comme des enfants obéissants, ne vous laissez point aller aux passions que vous aviez autrefois, quand vous étiez dans l'ignorance;",
        15: 'mais, comme Celui qui vous a appelés est saint, vous aussi soyez saints dans toute votre conduite,',
        16: "attendu qu'il est écrit: «Soyez saints, car je suis saint.»",
        17: 'Et si vous appelez Père, celui qui juge chacun selon ses oeuvres, sans faire acception des personnes, conduisez-vous avec crainte pendant le temps de votre séjour ici-bas;',
        18: "sachant que vous avez été affranchis de la vaine manière de vivre que vous teniez de vos pères, non par des choses périssables, de l'argent ou de l'or,",
        19: "mais par un sang précieux, comme celui d'un agneau sans défaut et sans tache,",
        20: 'par le sang de Christ qui a été prédestiné avant la création du monde, et qui a paru à la fin des temps, à cause de vous.',
        21: "C'est par lui que vous croyez en Dieu, qui l’a ressuscité des morts et qui lui a donné la gloire, en sorte que vous avez mis en Dieu votre foi et votre espérance.",
        22: "Puisqu'en obéissant à la vérité, vous avez purifié vos âmes par le moyen de l'Esprit, pour avoir un amour fraternel sincère, aimez-vous les uns les autres du fond du coeur, ardemment,",
        23: 'vous qui avez été régénérés, non par une semence corruptible, mais par une semence incorruptible, par la parole de Dieu vivifiante et éternelle;',
        24: 'car «toute chair est comme l’herbe, et toute sa gloire comme la fleur de l’herbe: l’herbe sèche et sa fleur tombe,',
        25: "mais la parole du Seigneur demeure éternellement:» c'est cette parole dont la bonne nouvelle vous a été portée.",
    },
    2: {
        1: "Ayant donc dépouillé toute méchanceté et toute ruse, la dissimulation, l'envie et toute espèce de médisance,",
        2: "désirez, comme des enfants nouveau-nés, le pur lait spirituel, afin qu'il vous fasse grandir pour le salut,",
        3: '«si réellement vous avez goûté que le Seigneur est bon.»',
        4: 'Approchez-vous de lui, «la pierre» vivante, «mise au rebut,» il est vrai, par les hommes, mais «choisie, précieuse» aux yeux de Dieu,',
        5: 'et comme des pierres vivantes, formez vous-mêmes un édifice, une maison spirituelle, pour constituer une sainte sacrificature, et offrir des sacrifices spirituels à Dieu par Jésus-Christ,',
        6: "puisqu'il est dit dans l'Ecriture: «Voici, je place en Sion une pierre angulaire, choisie, précieuse: celui qui met en elle sa confiance ne sera point confus.»",
        7: "A vous donc qui avez confiance, l'honneur; mais pour les incrédules, «cette même pierre que les constructeurs ont mise au rebut, est devenue la pierre angulaire,» et «une pierre d'achoppement, une pierre qui les fait trébucher,»",
        8: 'eux qui, par leur incrédulité, vont se heurter contre la Parole; comme aussi ils y ont été destinés.',
        9: "Pour vous, vous êtes une race élue, une sacrificature royale, une nation sainte, un peuple que Dieu s'est acquis, afin que vous publiiez les vertus de Celui qui vous a appelés à sa merveilleuse lumière,",
        10: "vous qui autrefois n'étiez pas un peuple, et qui êtes maintenant le peuple de Dieu; vous qui n'aviez point obtenu miséricorde et qui maintenant avez obtenu miséricorde.",
        11: "Mes bien-aimés, je vous recommande, comme étrangers et voyageurs, de vous abstenir des passions charnelles, parce qu'elles font la guerre à l'âme.",
        12: 'Ayez une bonne conduite parmi les Gentils, afin que sur le point même où ils vous calomnient comme si vous étiez des malfaiteurs, ils en viennent, en y regardant de près, à glorifier Dieu pour vos bonnes oeuvres, au jour de la Visitation.',
        13: 'Soyez donc soumis à toute institution humaine, à cause du Seigneur, soit au roi, comme souverain,',
        14: 'soit aux gouverneurs, comme délégués par lui pour faire justice des malfaiteurs, et pour approuver les gens de bien.',
        15: "Car c'est la volonté de Dieu, que, par votre bonne conduite, vous fermiez la bouche aux insensés qui vous méconnaissent.",
        16: 'Soyez soumis comme des hommes libres, non pas comme des hommes qui se font de la liberté un manteau pour couvrir leur méchanceté, mais comme des esclaves de Dieu;',
        17: 'honorez tous les hommes; aimez les frères; craignez Dieu; honorez le roi.',
        18: "Vous, serviteurs, soyez soumis à vos maîtres avec un profond respect, non seulement à ceux qui sont bons et doux, mais aussi à ceux qui sont d'une humeur difficile;",
        19: "car c'est une chose agréable à Dieu, quand, pour lui et par motif de conscience, on endure des peines en souffrant injustement.",
        20: "Quelle gloire y a-t-il pour vous à supporter patiemment d'être battus, quand vous avez commis quelque faute? Mais si vous supportez patiemment d'être maltraités, quand vous faites bien, voilà qui est agréable à Dieu.",
        21: "C'est à cela, en effet, que vous êtes appelés, puisque Christ même a souffert pour vous, vous laissant un exemple, afin que vous suiviez ses traces,",
        22: 'lui «qui n’a point commis de péché, et dans la bouche duquel il ne s’est point trouvé de fraude,»',
        23: "— lui qui, injurié, ne rendait point d'injure, qui, maltraité, ne faisait point de menaces, mais s'en remettait à Celui qui juge justement,",
        24: "— lui qui a lui-même porté nos péchés en son corps sur le bois, afin qu'étant morts au péché, nous vivions pour la justice, — lui par les meurtrissures duquel vous avez été guéris,",
        25: 'car «vous étiez comme des brebis errantes,» mais maintenant vous êtes retournés à celui qui est le pasteur et le gardien de vos âmes.',
    },
    3: {
        1: "Que les femmes soient soumises à leurs maris, afin que, s'il y a des maris qui n'obéissent pas à la Parole, ils soient gagnés par la conduite de leurs femmes, sans le secours de la parole,",
        2: "lorsqu'ils verront leur conduite chaste et respectueuse.",
        3: "Que leur parure ne soit pas cette parure extérieure, qui consiste à se tresser les cheveux, à se couvrir de bijoux d'or ou à s'ajuster des vêtements,",
        4: "mais qu'elles ornent l'être caché du coeur, de la parure impérissable d'un esprit doux et paisible, qui est d'un grand prix devant Dieu.",
        5: "C'est ainsi qu'autrefois se paraient les saintes femmes qui mettaient leur espérance en Dieu, en demeurant soumises à leurs maris:",
        6: "telle était Sarah, qui obéissait à Abraham, l'appelant son seigneur, elle, dont vous êtes devenues les filles par votre bonne conduite, et par votre courage qui ne s'effraie de rien.",
        7: 'Et vous de même, maris, comportez-vous sagement avec vos femmes, comme avec un sexe faible. Traitez-les avec honneur, comme héritant aussi avec vous la grâce de la vie, pour que rien ne vienne vous empêcher, les uns et les autres, de prier.',
        8: "Enfin soyez tous animés des mêmes pensées et des mêmes sentiments, pleins d'amour fraternel, de tendresse, d'humilité.",
        9: "Ne rendez point mal pour mal, ni injure pour injure; bénissez au contraire, car c'est à cela que vous avez été appelés, afin d'hériter la bénédiction.",
        10: 'Que celui, en effet, qui veut aimer la vie et voir des heureux jours, empêche sa langue de dire du mal et ses lèvres de proférer des paroles trompeuses;',
        11: 'qu’il se détourne du mal et fasse le bien; qu’il recherche la paix et la poursuive;',
        12: 'car le Seigneur a les yeux sur les justes, et se oreilles sont attentives à leurs prières; mais la face du Seigneur est contre ceux qui font le mal.»',
        13: 'Et qui vous maltraitera, si vous vous portez avec ardeur au bien?',
        14: 'Quand même vous souffririez pour la justice, soyez heureux. «Ne redoutez pas leurs menaces, et ne vous laissez pas troubler;',
        15: 'mais sanctifiez dans vos coeurs Christ, le Seigneur.» Soyez toujours prêts à répondre, mais avec douceur et respect, à quiconque vous demande raison de votre espérance,',
        16: 'ayant une bonne conscience, afin que, sur le point même où l’on vous calomnie, vous couvriez de confusion ceux qui diffament votre conduite en Christ:',
        17: "il vaut mieux souffrir, si telle est la volonté de Dieu, en faisant bien qu'en faisant mal.",
        18: "Christ aussi a bien souffert pour les péchés, lui juste pour les injustes, afin de nous donner accès auprès de Dieu, lorsqu'il a été mis à mort quant à la chair, mais qu'il a été rendu vivant quant à l'esprit.",
        19: 'Esprit, il est allé prêcher aux esprits qui sont en prison, pour avoir été jadis rebelles,',
        20: "lorsqu'au temps de Noé la longanimité de Dieu temporisait, pendant que se construisait l'arche, dans laquelle un petit nombre de personnes, huit seulement, furent sauvées à travers l'eau.",
        21: "Cette eau, dont le baptême est l'image — non ce baptême qui ôte les souillures du corps, mais celui qui est l'aspiration d'une bonne conscience vers Dieu — nous sauve maintenant, nous aussi, par la résurrection de Jésus-Christ,",
        22: 'qui est à la droite de Dieu, dans le ciel où il est allé, et où les anges, les principautés et les puissances lui sont soumis.',
    },
    4: {
        1: "Puis donc que Christ a souffert pour nous en la chair, vous aussi armez-vous de la même pensée: c'est que celui qui a souffert en la chair, a rompu avec le péché,",
        2: 'pour vivre, pendant le temps qui lui reste à passer en la chair, non plus selon les passions des hommes, mais selon la volonté de Dieu:',
        3: "c'est bien assez d'avoir accompli autrefois la volonté des Gentils, en vous livrant aux désordres, aux passions, à l'ivrognerie, aux excès de table et de vin et aux idolâtries criminelles.",
        4: 'Ils trouvent étrange que vous ne vous précipitiez pas avec eux dans les mêmes excès de dissolution, et ils se répandent en injures,',
        5: 'mais ils rendront compte à celui qui est tout prêt à juger les vivants et les morts;',
        6: "car, c'est en vue de ce jugement que la bonne nouvelle a été annoncée aussi aux morts, afin qu'après avoir été condamnés en la chair, comme on condamne les hommes, ils vivent, comme vit Dieu, par l'esprit.",
        7: 'La fin de toutes choses est proche: soyez donc sages et sobres, pour vaquer à la prière;',
        8: 'surtout ayez une ardente charité les uns pour les autres, car la charité couvrira une multitude de péchés.',
        9: "Exercez entre vous l'hospitalité, sans murmurer.",
        10: "Que chacun de vous mette le don qu'il a reçu au service des autres, comme de bons administrateurs de la grâce de Dieu, laquelle est variée dans ses dons.",
        11: "Si quelqu'un parle, que ce soit comme il convient à la parole de Dieu; si quelqu'un exerce un ministère, qu'il s'en acquitte comme usant d'une force que Dieu dispense, afin que tout se fasse à la gloire de Dieu, par Jésus-Christ, à qui appartiennent la gloire et la puissance aux siècles des siècles. Amen!",
        12: "Mes bien-aimés, ne trouvez pas étrange que le feu qui doit vous éprouver, ait éclaté au milieu de vous, comme s'il vous arrivait quelque chose d'extraordinaire;",
        13: "mais réjouissez-vous dans la mesure même où vous avez part aux souffrances de Christ, afin que vous vous réjouissiez aussi lors de l'apparition de sa gloire, en tressaillant de joie.",
        14: "Si vous êtes outragés pour le nom de Christ, vous êtes bienheureux, car l'esprit de gloire, l'Esprit de Dieu repose sur vous.",
        15: "Que nul de vous ne souffre comme meurtrier, comme voleur ou comme s'ingérant dans les affaires d'autrui;",
        16: "mais s'il souffre comme chrétien, qu'il n'en ait point de honte, au contraire, qu'il glorifie Dieu de ce nom même.",
        17: "En effet, le moment du jugement est venu; il va commencer par la maison de Dieu, et s'il débute par nous, quelle sera la fin de ceux qui n'obéissent point à l’évangile de Dieu?",
        18: "Et si le juste se sauve à grand'peine, qu'en sera-t-il de l'impie et du pécheur?",
        19: "Que ceux donc qui souffrent par la volonté de Dieu, lui remettent leur âme, comme au fidèle créateur, en s'attachant au bien.",
    },
    5: {
        1: "Je m'adresse maintenant aux anciens qui sont parmi vous, moi qui suis ancien avec eux et témoin des souffrances de Christ, et qui ai part aussi à la gloire qui doit apparaître.",
        2: "Paissez le troupeau de Dieu, qui vous est confié, veillant sur lui, non par contrainte, mais de bon gré; non en vue d'un gain sordide, mais par dévouement;",
        3: 'non en maîtrisant ceux qui vous sont échus en partage, mais en vous rendant les modèles du troupeau;',
        4: 'et, lorsque le souverain Pasteur paraîtra, vous remporterez la couronne immortelle de gloire.',
        5: "De même, vous qui êtes jeunes, soyez soumis aux anciens, et tous revêtez les uns à l'égard des autres la livrée de l'humilité, car «Dieu résiste aux orgueilleux, mais il fait grâce aux humbles.»",
        6: "Humiliez-vous sous la puissante main de Dieu, afin qu'il vous élève quand il en sera temps,",
        7: 'vous déchargeant sur lui de tout ce qui vous inquiète, car lui-même prend soin de vous.',
        8: 'Soyez sobres; veillez. Le diable, votre adversaire, rôde autour de vous, comme un lion rugissant, cherchant qui il pourra dévorer:',
        9: 'résistez-lui par votre fermeté dans la foi, sachant que vos frères dispersés dans le monde subissent les mêmes épreuves que nous; et, après quelque temps de souffrance,',
        10: 'le Dieu de toute grâce, qui vous a appelés en Jésus-Christ à son éternelle gloire, vous rétablira, vous soutiendra, vous fortifiera et vous rendra inébranlables.',
        11: 'A lui soient la gloire et la puissance aux siècles des siècles. Amen!',
        12: "Je vous écris ces quelques mots par Silvain, que j'estime être un fidèle frère, pour vous exhorter et pour vous assurer que c'est bien à la vraie grâce de Dieu que vous êtes attachés.",
        13: 'L’église élue qui est à Babylone, vous salue, ainsi que Marc mon fils.',
        14: 'Saluez-vous les uns les autres par un baiser affectueux. Que la paix soit avec vous tous qui êtes en Jésus-Christ!',
    },
}
