NAME = 'GerBoLut: Deutsch Bolsingerߴs Luther 1545 Bibel (moderne Rechtschreibung)'
BOOK = 'I Peter'

CHAPTERS = {
    1: {
        1: 'Petrus, ein Apostel Jesu Christi: Den erwahlten Fremdlingen hin und her in Pontus, Galatien, Kappadozien, Asien und Bithynien,',
        2: 'nach der Versehung Gottes des Vaters, durch die Heiligung des Geistes, zum Gehorsam und zur Besprengung des Blutes Jesu Christi. Gott gebe euch viel Gnade und Frieden!',
        3: 'Gelobet sei Gott und der Vater unsers Herrn Jesu Christi, der uns nach seiner groften Barmherzigkeit wiedergeboren hat zu einer lebendigen Hoffnung durch die Auferstehung Jesu Christi von den Toten',
        4: 'zu einem unverganglichen und unbefleckten und unverwelklichen Erbe, das behalten wird im Himmel',
        5: 'euch, die ihr aus Gottes Macht durch den Glauben bewahret werdet zur Seligkeit, welche zubereitet ist, daß sie offenbar werde zu der letzten Zeit,',
        6: 'in welcher ihr euch freuen werdet, die ihr jetzt eine kleine Zeit (wo es sein soil) traurig seid in mancherlei Anfechtungen,',
        7: 'auf daß euer Glaube rechtschaffen und viel kostlicher erfunden werde denn das vergangliche Gold, das durchs Feuer bewahret wird, zu Lobe, Preis und Ehren, wenn nun offenbaret wird Jesus Christus,',
        8: 'welchen ihr nicht gesehen und doch liebhabt und nun an ihn glaubet, wiewohl ihr ihn nicht sehet; so werdet ihr euch freuen mit unaussprechlicher und herrlicher Freude,',
        9: 'und das Ende eures Glaubens davonbringen, namlich der Seelen Seligkeit.',
        10: 'Nach welcher Seligkeit haben gesucht und geforschet die Propheten, die von der zukunftigen Gnade auf euch geweissaget haben,',
        11: 'und haben geforschet, auf welche und welcherlei Zeit deutete der Geist Christi, der in ihnen war, und zuvor bezeuget hat die Leiden, die in Christo sind, und die Herrlichkeit danach,',
        12: "welchen es offenbaret ist. Denn sie haben's nicht sich selbst, sondern uns dargetan, welches euch nun verkundiget ist durch die, so euch das Evangelium verkundiget haben, durch den Heiligen Geist vom Himmel gesandt, welches auch die Engel gelustet zu schauen.",
        13: 'Darum so begurtet die Lenden eures Gemutes, seid nuchtern und setzet eure Hoffnung ganz auf die Gnade, die euch angeboten wird durch die Offenbarung Jesu Christi,',
        14: 'als gehorsame Kinder; und stellet euch nicht gleich wie vorhin, da ihr in Unwissenheit nach den Lusten lebetet,',
        15: 'sondern nach dem, der euch berufen hat und heilig ist, seid auch ihr heilig in allem eurem Wandel.',
        16: 'Denn es stehet geschrieben: Ihr sollt heilig sein; denn ich bin heilig.',
        17: 'Und sintemal ihr den zum Vater anrufet, der ohne Ansehen der Person richtet nach eines jeglichen Werk, so fuhret euren Wandel, solange ihr hier wallet, mit Furcht;',
        18: 'und wisset, dafi ihr nicht mit verganglichem Silber Oder Gold erloset seid von eurem eitlen Wandel nach vaterlicher Weise,',
        19: 'sondern mit dem teuren Blut Christi, als eines unschuldigen und unbefleckten Lammes,',
        20: 'der zwar zuvor versehen ist, ehe der Welt Grund gelegt ward, aber offenbaret zu den letzten Zeiten um euretwillen,',
        21: 'die ihr durch ihn glaubet an Gott, der ihn auferwecket hat von den Toten und ihm die Herrlichkeit gegeben, auf daß ihr Glauben und Hoffnung zu Gott haben mochtet.',
        22: 'Und machet keusch eure Seelen im Gehorsam der Wahrheit durch den Geist zu ungefarbter Bruderliebe und habt euch untereinander brunstig lieb aus reinem Herzen,',
        23: 'als die da wiederum geboren sind, nicht aus verganglichem, sondern aus unverganglichem Samen, namlich aus dem lebendigen Wort Gottes, das da ewiglich bleibet.',
        24: 'Denn alles Fleisch ist wie Gras und aile Herrlichkeit der Menschen wie des Grases Blume. Das Gras ist verdorret, und die Blume abgefailen;',
        25: 'aber des Herrn Wort bleibet in Ewigkeit. Das ist das Wort, welches unter euch verkundiget ist.',
    },
    2: {
        1: 'So leget nun ab aile Bosheit und alien Betrug und Heuchelei und Neid und alles Afterreden;',
        2: 'und seid gierig nach der vernunftigen lautern Milch als die jetzt gebornen Kindlein, auf daß ihr durch dieselbige zunehmet,',
        3: 'so ihr anders geschmecket habt, daß der Herr freundlich ist,',
        4: 'zu welchem ihr kommen seid als zu dem lebendigen Stein, der von den Menschen verworfen, aber bei Gott ist er auserwahlet und kdstlich.',
        5: 'Und auch ihr, als die lebendigen Steine, bauet euch zum geistlichen Hause und zum heiligen Priestertum, zu opfern geistliche Opfer, die Gott angenehm sind durch Jesum Christum.',
        6: 'Darum stehet in der Schrift: Siehe da, ich lege einen auserwahlten, kostlichen Eckstein in Zion; und wer an ihn glaubet, der soil nicht zuschanden werden.',
        7: 'Euch nun, die ihr glaubet, ist er kostlich; den Unglaubigen aber ist der Stein, den die Bauleute verworfen haben, und zum Eckstein worden ist,',
        8: 'ein Stein des Anstoftens und ein Fels des Argernisses, die sich stoften an dem Wort und glauben nicht daran, darauf sie gesetzt sind.',
        9: 'Ihr aber seid das auserwahlte Geschlecht, das konigliche Priestertum, das heilige Volk, das Volk des Eigentums, daß ihr verkundigen sollt die Tugenden des, der euch berufen hat von der Finsternis zu seinem wunderbaren Licht,',
        10: 'die ihrweiland nichtein Volk waret, nun aber Gottes Volk seid, und weiland nicht in Gnaden waret, nun aber in Gnaden seid.',
        11: 'Liebe Bruder, ich ermahne euch, als die Fremdlinge und Pilgrime, enthaltet euch von fleischlichen Lusten, welche wider die Seele streiten,',
        12: 'und führet einen guten Wandel unter den FHeiden, auf daß die, so von euch afterreden als von Ubeltatern, eure guten Werke sehen und Gott preisen, wenn es nun an den Tag kommen wird.',
        13: 'Seid untertan aller menschlichen Ordnung um des Herm willen, es sei dem Kdnige, als dem Obersten,',
        14: 'Oder den FHauptleuten, als den Gesandten von ihm zur Rache uber die Ubeltater und zu Lobe den Frommen.',
        15: 'Denn das ist der Wille Gottes, daß ihr mit Wohltun verstopfet die Unwissenheit der torichten Menschen,',
        16: 'als die Freien, und nicht als hattet ihr die Freiheit zum Deckel der Bosheit, sondern als die Knechte Gottes.',
        17: 'Tut Ehre jedermann! Habt die Bruder lieb! Furchtet Gott! Ehret den Konig!',
        18: 'Ihr Knechte, seid untertan mit aller Furchtden Herren, nicht allein den gutigen und gelinden, sondern auch den wunderlichen.',
        19: 'Denn das ist Gnade, so jemand um des Gewissens willen zu Gott das Ubel vertragt und leidet das Unrecht.',
        20: 'Denn was ist das fur ein Ruhm, so ihr um Missetat willen Streiche leidet? Aber wenn ihr um Wohltat willen leidet und erduldet, das ist Gnade bei Gott.',
        21: 'Denn dazu seid ihr berufen, sintemal auch Christus gelitten hat fur uns und uns ein Vorbild gelassen, daß ihr sollt nachfolgen seinen Fußtapfen;',
        22: 'welcher keine Sünde getan hat, ist auch kein Betrug in seinem Munde erfunden;',
        23: 'welcher nicht wiederschalt, da er gescholten ward, nicht drauete, da er lift; er stellete es aber dem heim, der da recht richtet;',
        24: 'welcher unsere Sunden selbst geopfert hat an seinem Leibe auf dem Holz, auf daßwir, der Sunde abgestorben, der Gerechtigkeit leben; durch welches Wunden ihr seid heil worden.',
        25: 'Denn ihr waret wie die irrenden Schafe; aber ihr seid nun bekehret zu dem Hirten und Bischof eurer Seelen',
    },
    3: {
        1: 'Desselbigengleichen sollen die Weiber ihren Mannern untertan sein, auf daß auch die, so nicht glauben an das Wort, durch der Weiber Wandel ohne Wort gewonnen werden,',
        2: 'wenn sie ansehen euren keuschen Wandel in der Furcht;',
        3: 'welcher Schmuck soil nicht auswendig sein mit Haarflechten und Goldumhangen Oder Kleideranlegen,',
        4: 'sondern der verborgene Mensch des Flerzens unverrückt mit sanftem und stillem Geiste; das ist kostlich vor Gott.',
        5: 'Denn also haben sich auch vorzeiten die heiligen Weiber geschmuckt, die ihre Hoffnung auf Gott setzten und ihren Mannern untertan waren,',
        6: 'wie die Sara Abraham gehorsam war und hieß ihn Herr, welcher Tdchter ihr worden seid, so ihr wohl tut und nicht so schuchtern seid.',
        7: 'Desselbigengleichen, ihr Manner, wohnet bei ihnen mit Vernunft und gebet dem weiblichen als dem schwachsten Werkzeuge seine Ehre, als auch Miterben der Gnade des Lebens, auf daß eure Gebete nicht verhindert werden.',
        8: 'Endlich aber seid allesamt gleichgesinnet, mitleidig, bruderlich, barmherzig, freundlich.',
        9: 'Vergeltet nicht Boses mit Bosem Oder Scheltwort mit Scheltwort, sondern dagegen segnet und wisset, daß ihr dazu berufen seid, daß ihr den Segen erbet.',
        10: 'Denn wer leben will und gute Tage sehen, der schweige seine Zunge, daß sie nichts Boses rede, und seine Lippen, daß sie nicht trugen;',
        11: 'er wende sich vom Bosen und tue Gutes; er suche Frieden und jage ihm nach.',
        12: 'Denn die Augen des Herm sehen auf die Gerechten und seine Ohren auf ihr Gebet; das Angesicht aber des Herm siehet auf die, so Boses tun.',
        13: 'Und wer ist, der euch schaden konnte, so ihr dem Guten nachkommet?',
        14: 'Und ob ihr auch leidet um Gerechtigkeit willen, so seid ihr doch selig. Furchtet euch aber vor ihrem Trotzen nicht und erschrecket nicht!',
        15: 'Heiligetaber Gott den Herm in euren Herzen. Seid aber allezeit bereit zur Verantwortung jedermann, der Grund fordert der Hoffnung, die in euch ist,',
        16: 'und das mit Sanftmutigkeit und Furcht; und habt ein gut Gewissen, auf daß die, so von euch afterreden als von Ubeltatern, zuschanden werden, daß sie geschmahet haben euren guten Wandel in Christo.',
        17: 'Denn es ist besser, so es Gottes Wille ist, daß ihr von Wohltat wegen leidet denn von Ubeltat wegen,',
        18: 'sintemal auch Christus einmal fur unsere Sunden gelitten hat, der Gerechte fur die Ungerechten, auf daß er uns Gott opferte; und ist getotet nach dem Fleisch, aber lebendig gemacht nach dem Geist.',
        19: 'In demselbigen ist er auch hingegangen und hat geprediget den Geistern im Gefangnis,',
        20: 'die etwa nicht glaubeten, da Gott einstmals harrete und Geduld hatte zu den Zeiten Noahs, da man die Arche zurustete, in welcher wenig, das ist, acht Seelen, behalten wurden durchs Wasser,',
        21: 'welches nun auch uns selig macht in der Taufe, die durch jenes bedeutet ist, nicht das Abtun des Unflats am Fleisch, sondern der Bund eines guten Gewissens mit Gott durch die Auferstehung Jesu Christi,',
        22: 'welcher ist zur Rechten Gottes in den Himmel gefahren, und sind ihm untertan die Engel und die Gewaltigen und die Krafte.',
    },
    4: {
        1: 'Weil nun Christus im Fleisch fur uns gelitten hat, so wappnet euch auch mit demselbigen Sinn: denn wer am Fleisch leidet, der horet auf von Sünden,',
        2: 'daiß er hinfort, was noch hinterstelliger Zeit im Fleisch ist, nicht der Menschen Lüsten, sondern dem Willen Gottes lebe.',
        3: 'Denn es ist genug, daß wir die vergangene Zeit des Lebens zugebracht haben nach heidnischem Willen, da wirwandelten in Unzucht, Lüsten, Trunkenheit, Fresserei, Sauferei und greulichen Abgottereien.',
        4: 'Das befremdet sie, dafi ihr nicht mit ihnen laufet in dasselbige wüste, unordentliche Wesen, und lastern;',
        5: 'welche werden Rechenschaft geben dem, der bereit ist, zu richten die Lebendigen und die Toten.',
        6: 'Denn dazu ist auch den Toten das Evangelium verkundiget, auf dafi sie gerichtet werden nach dem Menschen am Fleisch, aber im Geist Gott leben.',
        7: 'Es ist aber nahe kommen das Ende aller Dinge.',
        8: 'So seid nun mafüg und nuchtern zum Gebet. Vor alien Dingen aber habt untereinander eine brunstige Liebe; denn die Liebe decket auch der Sünden Menge.',
        9: 'Seid gastfrei untereinander ohne Murmeln!',
        10: 'Und dienet einander, ein jeglicher mit der Gabe, die er empfangen hat, als die guten Haushalter der mancherlei Gnade Gottes.',
        11: "So jemand redet, dafi er's rede als Gottes Wort; so jemand ein Amt hat, dafi er's tue als aus dem Vermogen, das Gott darreichet, auf daß in alien Dingen Gott gepreiset werde durch Jesum Christum, welchem sei Ehre und Gewalt von Ewigkeit zu Ewigkeit! Amen.",
        12: 'Ihr Lieben, lasset euch die Hitze, so euch begegnet, nicht befremden (die euch widerfahret, daü ihr versucht werdet), als widerfuhre euch etwas Seltsames,',
        13: 'sondern freuet euch, dafi ihr mit Christo leidet, auf daü ihr auch zu der Zeit der Offenbarung seiner Herrlichkeit Freude und Wonne haben moget.',
        14: 'Selig seid ihr, wenn ihr geschmahet werdet uber dem Namen Christi; denn der Geist, der ein Geist der Herrlichkeit und Gottes ist, ruhet auf euch. Bei ihnen ist er verlastert, aber bei euch ist er gepreiset.',
        15: 'Niemand aber untereuch leide als ein Morder Oder Dieb Oder Ubeltater Oder der in ein fremd Amt greifet.',
        16: 'Leidet er aber als ein Christ, so schame er sich nicht; er ehre aber Gott in solchem Fall.',
        17: "Denn es ist Zeit, daü anfange das Gericht an dem Hause Gottes. So aber zuerst an uns, was will's fur ein Ende werden mit denen, die dem Evangelium Gottes nicht glauben?",
        18: 'Und so der Gerechte kaum erhalten wird, wo will der Gottiose und Sunder erscheinen?',
        19: 'Darum, welche da leiden nach Gottes Willen, die sollen ihm ihre Seelen befehlen als dem treuen Schopfer in guten Werken.',
    },
    5: {
        1: 'Die Altesten, so unter euch sind, ermahne ich, der Mitalteste und Zeuge der Leiden, die in Christo sind, und teilhaftiq der Herrlichkeit, die offenbaret werden soil:',
        2: 'Weidet die Herde Christi, so euch befohlen ist, und sehetwohl zu, nicht gezwungen, sondern williglich, nicht urn schandlichen Gewinns willen, sondern von Herzensgrund,',
        3: 'nicht als die uber das Volk herrschen, sondern werdet Vorbilder der Herde;',
        4: 'so werdet ihr, wenn erscheinen wird der Erzhirte, die unverwelkliche Krone der Ehren empfangen.',
        5: 'Desselbigengleichen, ihr Jungen, seid untertan den Altesten. Allesamt seid untereinander untertan und haltet test an der Demut; denn Gott widerstehet den Hoffartigen, aber den Demütigen gibt er Gnade.',
        6: 'So demutiget euch nun unter die gewaltige Hand Gottes, daß er euch erhohe zu seiner Zeit.',
        7: 'Alle eure Sorge werfet auf ihn; denn er sorget fur euch.',
        8: 'Seid nuchtern und wachet; denn euer Widersacher, der Teufel, gehet umher wie ein brullender Lowe und suchet, welchen er verschlinge.',
        9: 'Dem widerstehet fest im Glauben und wisset, daß eben dieselbigen Leiden uber eure Bruder in der Welt gehen.',
        10: 'Der Gott aber aller Gnade, der uns berufen hat zu seiner ewigen Herrlichkeit in Christo Jesu, derselbige wird euch, die ihr eine kleine Zeit leidet, vollbereiten, starken, kraftigen, grunden.',
        11: 'Demselbigen sei Ehre und Macht von Ewigkeit zu Ewigkeit! Amen.',
        12: 'Durch euren treuen Bruder Silvanus (als ich achte) habe ich euch ein wenig geschrieben, zu ermahnen und zu bezeugen, daü das die rechte Gnade Gottes ist, darinnen ihr stehet.',
        13: 'Es gruften euch, die samt euch auserwahlt sind zu Babylon, und mein Sohn Markus.',
        14: 'Gruf Jet euch untereinander mit dem Kuft der Liebe. Friede sei mit alien, die in Christo Jesu sind! Amen. Der zweite Brief des Petrus',
    },
}
