NAME = 'ManxGaelic: Manx Gaelic Scripture Portions'
BOOK = 'Jonah'

CHAPTERS = {
    1: {
        1: 'Nish haink goo yn Chiarn gys Jonah mac Amittai gra,',
        2: "Trog ort, immee gys Nineveh yn ard valley mooar shen, as trog seose dty choraa noi eck, son ta'n mee chraueeaght oc er jeet seose kiongoyrt rhym.",
        3: 'Agh dirree Jonah seose dy roie er-chea gys Tarshish veih fenish y Chiarn, as hie eh sheese gys Joppa; as hooar eh lhong goll gys Tarshish: myr shen deeck eh yn leagh-shiaullee, as hie eh er boayrd, dy gholl maroo gys Tarshish, veih fenish y Chiarn.',
        4: 'Agh hug y Chiarn magh geay vooar er yn aarkey, as va sterrym dorrinagh ayns y cheayn, myr shen dy row yn lhong ayns gaue brishey.',
        5: "Eisht va aggle er ny marrinee, as deie ad dagh dooinney gys e yee, as hilg ad magh yn chooid v'er boayrd 'sy cheayn, dy eddrymaghey yn lhong: agh va Jonah ersooyl sheese 'sy chabbane, as lhie eh, as v'eh trome ny chadley.",
        6: "Myr shen haink mainshtyr y lhong huggey, as dooyrt eh rish, Kys t'ou cadley myr shoh, y chadlag? irree, eie er dty Yee, my she shen dy jean Jee smooinaghtyn orrin, nagh bee mayd caillit.",
        7: "As dooyrt ad, dagh fer rish e heshey, Tar-jee, as lhig dooin lottyn y hayrn, dy vod fys y ve ain, quoi by-chyndagh ta'n olk shoh er jeet orrin. Myr shen hilg ad lottyn, as huitt y lot er Jonah.",
        8: "Eisht dooyrt ad rish, Insh dooin, ta shin guee ort, quoi by-chyndagh ta'n olk shoh er jeet orrin: cre ta dty aght beaghee? as cre voish t'ou? cre'n cheer t'ou jeh? as cre'n sleih t'ou jeh?",
        9: "As dooyrt eh roo, She Hebrew mee, as ta mee goaill aggle roish y Chiarn, Jee ny flaunys, t'er chroo yn aarkey as y thalloo chirrym.",
        10: "Eisht va ny deiney erskyn-towse agglagh, as dooyrt ad rish, Cre'n-fa t'ou uss er n'yannoo shoh? (son va fys ec ny deiney dy row eh er-chea veih fenish y Chiarn, son v'eh er n'insh daue).",
        11: "Eisht dooyrt ad rish, Cre nee mayd rhyt, dy vod y keayn ve kiune dooin? (son va'n keayn freaney, as erskyn-towse stermagh).",
        12: "As dooyrt eh roo, Trog-jee mee seose, as tilg-jee mee magh 'sy cheayn; myr shen vees y keayn kiune diuish: son ta fys aym dy nee by-chyndagh rhym's ta'n sterrym mooar shoh er jeet erriu.",
        13: ". Ny-yeih, ren ny deiney gymmyrt dy doccaragh, dy chosney yn thalloo, agh cha voddagh ad roshtyn, son va'n keayn freaney, as dowil-dorrinagh noi oc.",
        14: "Shen-y-fa, deie ad gys y Chiarn, as dooyrt ad, Ta shin guee ort, O Hiarn, ta shin guee ort, ny lhig dooin cherraghtyn son bioys yn dooinney shoh, as ny cur gys nyn lieh yn uill gyn-loght; son t'ou uss, O Hiarn, er n'yannoo myr s'gooidsave lhiat.",
        15: "Myr shen hrog ad seose Jonah, as hilg ad eh magh 'sy cheayn, as ghow yn aarkey kiunid veih freaney.",
        16: "Eisht ghow ny deiney aggle roish y Chiarn erskyn-towse, as ren ad breearrey dy hebbal oural da'n Chiarn.",
        17: "Nish va'n Chiarn er chiarail eeast mooar dy lhuggey seose Jonah, as va Jonah ayns bolg yn eeast, three laa as three oieghyn.",
    },
    2: {
        1: 'Eisht ghow Jonah padjer gys y Chiarn e Yee veih bolg yn eeast,',
        2: 'As dooyrt eh, Deie mee kyndagh rish my heaghyn gys y Chiarn, as ren eh my chlashtyn; veih diunid yn oaie deie mee, as cheayll oo my choraa',
        3: "Son t'ou er my hilgey ayns y diunid, ayns mean ny marrey, as haink ny thooillaghyn mygeayrt-y-moom, ta ooilley ny ushtaghyn as ny tonnyn ayd's er n'gholl harrym.",
        4: "Eisht dooyrt mee Ta mee ceaut magh ass dty hilley; agh ny yeih nee'm jeeaghyn reesht lesh dty hiamble casherick.",
        5: "Haink ny ushtaghyn mygeayrt-y-moom, eer gys my annym: ren y diunid m'y chruinnaghey mygeayrt, va'n amlagh cast mysh my chione.",
        6: "Hie mee sheese choud's undin ny sleityn; bee yn thalloo as ny barryn eck my-geayrt-y-moom dy bragh, mannagh jean oo my vioys y livrey veih toyrt-mow, O Hiarn my Yee.",
        7: "Tra ren my annym gannooinaghey cheu sthie jee'm, chooinee mee er y Chiarn, as haink my phadjer stiagh hood, gys dty hiamble casherick.",
        8: "T'adsyn, ta cur geill da fardalyssyn breagagh, treigeil nyn myghin hene.",
        9: "Agh chebb-yms oural dhyt lesh y choraa dy hoyrt-booise, eeck-ym shen ny ta mee er vreearrey: ta saualtys veih'n Chiarn.",
        10: 'As hug y Chiarn currym er yn eeast, as hilg eh magh Jonah er y thalloo chirrym.',
    },
    3: {
        1: 'As haink goo yn Chiarn gys Jonah yn nah cheayrt, gra,',
        2: 'Trog ort, immee gys Nineveh yn ard valley mooar shen, as jean preacheil ayn ny goan ver-ym royd.',
        3: 'Myr shen dirree Jonah, as hie eh gys Nineveh cordail rish goo yn Chiarn: (nish va Nineveh ard-valley feer vooar jeh jurnah three laa.)',
        4: "As ghow Jonah toshiaght dy gholl stiagh 'syn ard-valley lesh jurnah laa, as dockle eh magh e choraa, as dooyrt eh, Foast ec kione da-eed laa, as bee Nineveh er ny stroie.",
        5: "Myr shen ren sleih Nineveh credjal ayns Jee, as doardee ad laa troshtee, as hug ad orroo aanrit-sack veih'n vooinjer b'yrjey jeu, dy jarroo gys yn vooinjer b'inshley jeu.",
        6: "Son haink y goo gys ree Nineveh, as dirree eh veih e stoyl-reeoil, as hug eh jeh e choamrey-reeoil, as choodee eh eh-hene lesh aanrit-sack as lhie eh 'sy leoie.",
        7: "As doardee eh eam dy v'er ny ockley-magh, as er ny hoilshaghey trooid Nineveh (liorish sarey yn ree as e gheiney ooasle) gra, Ny lhig da dooinney ny baagh, shelloo ny shioltane blaystyn nhee erbee; ny lhig daue goaill beaghey, ny giu ushtey.",
        8: "Agh lhig da dooinney as baagh ve er ny choodaghey lesh aanrit-sack, as geamagh dy jeean gys Jee: dy jarroo lhig daue chyndaa dy chooilley unnane veih e ghrogh-raad, as veih'n tranlaase t'ayns nyn laueyn.",
        9: 'Quoi ec ta fys my nee Jee chyndaa as meiyghey, as e ymmoose hrome y lhiettal, nagh jean mayd cherraghtyn?',
        10: "As honnick Jee nyn obbraghyn, dy hyndaa ad veih nyn ghrogh-raad, as ren Jee meiyghey mychione yn olk, v'eh er chiarail dy choyrt orroo, as cha dug eh orroo eh.",
    },
    4: {
        1: "Agh va Jonah erskyn-towse jymmoosagh, as v'eh feer chorree.",
        2: 'As ghow eh padjer gys y Chiarn, as dooyrt eh, Guee-ym ort, O Hiarn, nagh nee shoh va my raa, choud as va mee foast ayns my heer hene? shen-y-fa chossyn mee roym (dy gholl) gys Tarshish: son va fys aym dy vel oo Jee graysoil as myghinagh, moal gys corree, as jeh kenjallys vooar, as meiygh chreeagh ayns kerraghey.',
        3: 'Shen-y-fa nish, O Hiarn, gow, ta mee guee ort, my vioys voym; son te ny share dooys dy gheddyn baase, na dy ve bio.',
        4: 'Eisht dooyrt y Chiarn, Vel uss jannoo dy mie, ayns dy vel oo corree?',
        5: "Er shoh hie Jonah magh ass yn ard valley as hoie eh er cheu-har jeh'n ard valley, as hrog eh bwaag da hene ayns shen, as hoie eh fo yn scadoo echey, dy chur-my-ner cre'n erree harragh er yn ard-valley.",
        6: "As chiare yn Chiarn Jee gourd, as hug eh er gaase seose harrish Jonah, son scadoo harrish e chione, dy gherjaghey eh ayns e hrimshey. My shen ghow Jonah boggey erskyn-towse jeh'n ghourd.",
        7: 'Agh chiare Jee beishteig, moghrey yn laa er-giyn, as woaill eh yn gourd, dy ren eh fioghey.',
        8: 'As haink eh gy-kione, tra dirree yn ghrian, dy doardee Jee geay-niar fowanagh; as cha lajer shen va chiass ny greiney er kione Yonah, dy huitt eh my-neealloo, as yeearree eh ayns e chree, dy gheddyn baase, as dooyrt eh, Te ny share dooys dy ve marroo na dy ve bio.',
        9: 'As dooyrt Jee rish Jonah, Vel uss jannoo dy mie, dy vel dty chorree er ny vrasnaghey son y ghourd? As dooyrt eh, Ta mee jannoo dy mie dy ve corree, eer gys sproght baaish.',
        10: "Eisht dooyrt y Chiarn, Ta chymmey er ve ayd's jeh'n ghourd, er y hon cha vel oo er laboragh, chamoo she uss hug er gaase, son daase eh ayns oie, as hie eh naardey ayns oie.",
        11: "As nagh lhisin's sparail Nineveh yn ard-valley mooar shen, ayn ta ny smoo na shey feed thousane persoon, nagh vel fys oc er nyn laue yesh shaghey nyn laue chiare, as myrgeddin ymmodee maase?",
    },
}
