NAME = 'SloKJV: Slovenian translation of Holy Bible King James Version (1769)'
BOOK = 'Jonah'

CHAPTERS = {
    1: {
        1: 'Torej Gospodova beseda je prišla k Jonu, Amitájevemu sinu, rekoč:',
        2: '»Vstani, pojdi v Ninive, to veliko mesto in kliči zoper njega, kajti njihova zlobnost je prišla predme.«',
        3: 'Toda Jona se je dvignil, da pred Gospodovo prisotnostjo zbeži v Taršíš in je odšel dol v Jopo in našel ladjo, ki je šla v Taršíš. Tako je plačal njeno voznino in odšel dol vanjo, da gre z njimi v Taršíš, proč od Gospodove prisotnosti.',
        4: 'Toda Gospod je na morje odposlal velik veter in tam na morju je bil mogočen vihar, tako da je ladjo hotel zlomiti.',
        5: 'Potem so bili mornarji prestrašeni in vsak je klical k svojemu bogu in odvrgli [so] blago, ki je bilo na ladji, v morje, da jo olajšajo. Jona pa je odšel dol med ladijske boke in legel ter trdno zaspal.',
        6: 'Tako je kapitan prišel k njemu in mu rekel: »Kaj ti misliš, oh zaspanec? Vstani, kliči k svojemu Bogu, če je tako, da bo Bog mislil na nas, da se ne pogubimo.«',
        7: 'In rekli so vsak svojemu tovarišu: »Pridimo in mečimo žrebe, da bomo lahko izvedeli zaradi čigavega vzroka je nad nami to zlo.« Tako so metali žrebe in žreb je padel na Jona.',
        8: 'Potem so mu rekli: »Povej nam, prosimo te, zaradi čigavega vzroka je nad nami to zlo. Kakšen je tvoj poklic? In od kod prihajaš? Katera je tvoja dežela? In iz katerega ljudstva si?«',
        9: 'Rekel jim je: »Jaz sem Hebrejec in se bojim Gospoda, Boga nebes, ki je naredil morje in kopno zemljo.«',
        10: 'Potem so bili ljudje silno prestrašeni in mu rekli: »Zakaj si to storil?« Kajti ljudje so vedeli, da je pobegnil izpred Gospodovega obličja, ker jim je povedal.',
        11: 'Potem so mu rekli: »Kaj naj ti storimo, da se nam morje lahko umiri?« Kajti morje se je maščevalo in bilo viharno.',
        12: 'Rekel jim je: »Vzemite me in me vrzite v morje. Tako se vam bo morje umirilo, kajti vem, da je zaradi mene ta veliki vihar nad vami.«',
        13: 'Kljub temu so možje trdo veslali, da jo privedejo k obali, toda niso mogli, kajti morje se je maščevalo in bilo viharno proti njim.',
        14: 'Zato so klicali h Gospodu in rekli: »Rotimo te, oh Gospod, rotimo te, naj se ne pogubimo zaradi življenja tega moža in ne položi na nas nedolžne krvi, kajti ti, oh Gospod, si storil, kakor ti je ugajalo.«',
        15: 'Tako so vzeli Jona in ga vrgli v morje in morje je odnehalo od svojega besnenja.',
        16: 'Potem so se možje silno zbali Gospoda in Gospodu darovali klavno daritev in naredili zaobljube.',
        17: 'Torej Gospod je pripravil veliko ribo, da je pogoltnila Jona. In Jona je bil v ribjem trebuhu tri dni in tri noči.',
    },
    2: {
        1: 'Potem je Jona iz ribjega trebuha molil h Gospodu, svojemu Bogu',
        2: '§ in rekel: »Zaradi razloga svoje stiske sem klical h Gospodu in me je slišal. Ven iz trebuha pekla sem klical in ti si slišal moj glas.',
        3: 'Kajti vrgel si me v globino, v sredo morij, in poplave so me obkrožile. Vsi tvoji veliki valovi in tvoji valovi so me preleteli.«',
        4: 'Potem sem rekel: »Vržen sem iz tvojega pogleda, vendar bom ponovno gledal k tvojemu svetemu templju.',
        5: 'Vode so me obkrožile, celó do duše, globine so me zaprle naokoli, plevel je bil zavit okoli moje glave.',
        6: 'Odšel sem navzdol, k vznožjem gora. Zemlja, s svojimi zapahi, je bila okoli mene na veke, vendar si ti moje življenje privedel gor iz trohnenja, oh Gospod, moj Bog.',
        7: 'Ko je moja duša slabela znotraj mene, sem se spomnil Gospoda. Moja molitev je vstopila k tebi, v tvoj sveti tempelj.',
        8: 'Tisti, ki obeležujejo lažnive ničevosti, zapuščajo svoje lastno usmiljenje.',
        9: 'Toda jaz ti bom žrtvoval z glasom zahvaljevanja; plačal bom to, kar sem se zaobljubil. Rešitev duš je od Gospoda.«',
        10: 'In Gospod je spregovoril ribi in izbljuvala je Jona na kopno zemljo.',
    },
    3: {
        1: 'Gospodova beseda je drugič prišla Jonu, rekoč:',
        2: '»Vstani, pojdi v Ninive, to veliko mesto in mu oznani pridigo, ki sem ti jo zapovedal.«',
        3: 'Tako je Jona vstal in odšel v Ninive, glede na Gospodovo besedo. Torej Ninive so bile silno veliko mesto treh dni potovanja.',
        4: 'Jona je začel vstopati v mesto [prvi] dan potovanja ter vpil in govoril: »Še štirideset dni in Ninive bodo uničene.«',
        5: 'Tako je ljudstvo v Ninivah verovalo Bogu in razglasilo post in si nadelo vrečevino, od največjih izmed njih, celo do najmanjših izmed njih.',
        6: 'Kajti beseda je prišla h kralju Niniv in vstal je s svojega prestola in iz sebe odložil svoje svečano oblačilo in se pokril z vrečevino in sédel na pepel.',
        7: 'In storil je to, da se je razglasilo in oznanilo skozi Ninive, po odloku kralja in njegovih plemičev, rekoč: »Naj niti človek niti žival, [niti] trop niti čreda ničesar ne pokusijo, naj se ne pasejo niti ne pijejo vode,',
        8: 'temveč naj bosta človek in žival pokrita z vrečevino in mogočno kličeta k Bogu, da naj se oni, vsakdo izmed njih, obrnejo od svoje zle poti in od nasilja, ki je v njihovih rokah.',
        9: 'Kdo lahko pove, če se bo Bog obrnil, pokesal in odvrnil proč od svoje krute jeze, da se ne pogubimo?«',
        10: 'In Bog je videl njihova dela, da so se odvrnili od svoje zle poti in Bog se je pokesal od zla, ki ga je rekel, da jim bo storil in tega ni storil.',
    },
    4: {
        1: 'Toda to je Jona silno razžalilo in bil je zelo jezen.',
        2: 'Molil je h Gospodu ter rekel: »Prosim te, oh Gospod, ali ni bila to moja beseda, ko sem bil še v svoji deželi? Zatorej sem prej pobegnil v Taršíš, kajti vedel sem, da si milostljiv Bog in usmiljen, počasen za jezo in zelo prijazen in se kesaš zlega.',
        3: 'Zatorej sedaj, oh Gospod, vzemi, rotim te, moje življenje od mene, kajti zame je bolje, da umrem, kakor da živim.«',
        4: 'Potem je Gospod rekel: »Delaš pravilno, da si jezen?«',
        5: 'Tako je Jona odšel ven iz mesta in se usedel na vzhodni strani mesta in si tam postavil šotor in sedèl pod njim v senco, toliko časa, da lahko vidi kaj bo iz mesta nastalo.',
        6: 'Gospod Bog pa je pripravil bučo in ji storil, da vzklije nad Jona, da bi bila ta lahko senca nad njegovo glavo, da ga osvobodi pred njegovo žalostjo. Tako je bil Jona buče silno vesel.',
        7: 'Toda ko je naslednjega dne vstalo jutro, je Bog pripravil ličinko in ta je napadla bučo, da je ovenela.',
        8: 'Ko je sonce vstalo, se je pripetilo, da je Bog pripravil silovit vzhodnik. Sonce je udarjalo na Jonovo glavo, da je slabel in si v sebi želel, da umre ter rekel: »Zame je boljše, da umrem, kakor da živim.«',
        9: 'Bog je Jonu rekel: »Delaš pravilno, da si jezen zaradi buče?« Ta je rekel: »Pravilno delam, da sem jezen, celó do smrti.«',
        10: 'Potem je Gospod rekel: »Usmiljenje imaš za bučo, za katero nisi delal niti ji storil, da zraste, ki je v [eni] noči vzklila in v [eni] noči propadla,',
        11: 'jaz pa naj ne bi prizanesel Ninivam, temu velikemu mestu, v katerem je več kot sto dvajset tisoč oseb, ki ne morejo razlikovati med svojo desnico in svojo levico in tudi veliko živine?«',
    },
}
