NAME = 'sml_BL_2008: Kitab Awal-Jaman maka Kitab Injil'
BOOK = 'I Peter'

CHAPTERS = {
    1: {
        1: "Sulat itu min aku, si Petros, a'a kawakilan e' si Isa Al-Masi magnasihat lapalna. Pasampayku sulat itu pi'ilu ni ka'am saga a'a bay tapene'na, ya maglihan-lihan ma dunya itu. Ilu kam apulak-palik ma kalahat-lahatan buwattina'an, ma sakalibut lahat Puntus, Galatiya, Kappadoke, Asiya, maka ma lahat Bitiniya.",
        2: "Bay kam tapene' e' Mma'tam Tuhan min maksudna, jari suku'na na kam ma sabab hinang Rū Tuhan ya ma deyom ataybi. Tapene' kam supaya kam ameya' ma si Isa Al-Masi, bo' pinuwasan dusabi ma sabab laha'na. Mura-murahan, bang pa'in kam pinaniya'an tatabangan maka kasannangan atay ma halam aniya' kulangna.",
        3: "Mahaldika' ni Tuhan, ya mma' Panghū'tam si Isa Al-Masi. Aheya to'ongan ka'ase'na ma kitam, ya angkan kitam binuwanan kallum baha'u buwat sapantun a'a nianakan pabīng. Makaholat isab kitam pinakallum min kamatay, sabab ya du si Isa Al-Masi bay pinakallum isab min kamatayna.",
        4: "Jari angagad na kitam pinaniya'an pusaka' ya tinau' e' Tuhan ma saga a'a suku'na. Tinau' e'na ma deyom sulga', ati maina'an mbal magka'at, mbal magkahalu', mbal magkapinda.",
        5: "Nihampanan kam pahāp sabab min kawasa Tuhan, pagka kam angandol ma iya. Tantu kam nihampanan sampay ta'abutbi kasalamatan ya pinabukis ma llaw kahinapusan.",
        6: "Angkan kam kinōgan minsan ma deyom susa ma dunya pinjaman itu, ma sabab katiksa'an indaginis ya kalabayanbi.",
        7: "Pinaniya'an kam katiksa'an ilu bo' sinulayan pangandolbi bang b'nnal atawa ngga'i ka. Minsan bulawan, subay pinalabay min api bo' nila'anan l'mmi'na. Sagō' ahalga' lagi' pangandolbi min bulawan, sabab mbal anatas bulawan ni kasaumulan. Bang kam angandol sab'nnal-b'nnal, sinanglitan du kam maka minahaldika'an bang ta'abut llaw pamatuwa' si Isa Al-Masi.",
        8: "Alasa kam ma iya minsan halam ta'nda'bi. Maka minsan iya mbal ta'nda'bi ma buwattitu, angandol kam asal ma iya. Jari aheya sidda kakōganbi, mbal tasibahat,",
        9: "sabab kaniya'an kam kasalamatan kakkal, ya kamaksuran pangandolbi.",
        10: "Bay amikilan pahāp saga kanabihan ma masa awal e', bay angahangpat to'ongan pasal kasalamatan itu. Bay pinagbissala e' sigām kahāpan ya pinama-ka'am ma ahil jaman itu.",
        11: "Pinatulunan sigām Rū Al-Masi, angkan sigām bay angabtang pasal kabinasahan ya subay kalabayanna, maka ma pasal sanglit-sahaya ma iya puwas kabinasahan e'. Jari sidda bilahi saga nabi inān makata'u bang sumiyan kat'kkana maka bang buwattingga kal'ngngananna.",
        12: "Pinata'u sigām e' Tuhan in pakaradja'an bay pagbissala sigām inān ngga'i ka ma baran sigām, sagō' ma saga a'a ma tahun sinōng, hatina ma ka'am. Manjari ka'am na ya pinakale na e' saga a'a bay magnasihat lapal ahāp min kawasa Rū Tuhan ya pinatulunan sigām min sulga'. Minsan saga mala'ikat, bilahi to'ongan makahati ma pasal saga pakaradja'an itu.",
        13: "Angkan kam soho'ku subay pahatul-hatul ma deyom pamikilbi. Pahalli' kam, maka holatunbi kahāpan ya pamuwan ka'am bang ta'abut na llaw pamatuwa' si Isa Al-Masi.",
        14: "Beya'unbi panoho'an Tuhan, sengorinbi onde'-onde' ahatul. Da'a parūlunbi kanapsuhan ya bay kabiyaksahanbi waktu tagna', ma halam gi' aniya' kata'ubi.",
        15: "Subay kam a'adil ma ai-ai hinangbi sabab a'adil asal Tuhan, ya bay anoho' ka'am ameya' ma iya.",
        16: "Sabab tasulat ma deyom Kitab bay bissala Tuhan, ya yuk-i, “Wajib kam sussi ma kaulbi maka pi'ilbi, sabab aku itu mahasussi asal.”",
        17: "Angahukum Tuhan ma manusiya' kamemon, tinongoran kahinangan sigām pakaniya-pakaniya ma halam aniya' papagbidda'na. Angkanna, pagga pangōnbi ‘Mma'’ ma Tuhan bang aniya' pangamu'-ngamu'bi, subay kam magmatāw ma iya t'ggolbi pat'nna' ma dunya itu.",
        18: "Kata'uwanbi du bang ai bay pamuwan e' Tuhan pangal'kkat ka'am min bay kajarihanbi halam taga-pūs inān, ya kajarihan bay pang'bba ka'am e' kamatto'ahanbi. Ngga'i ka alta' magkaka'at buwat bulawan atawa pilak ya bay pangal'kkat ka'am,",
        19: "sagō' laha' Al-Masi ahalga', ya bay pabu'us ma kamatayna. Ibarat iya bili-bili halam aniya' tamakna atawa salla'na, pagkulban pamapuwas dusatam.",
        20: "Ya na itu asal pangahandak Tuhan ma iya ma halam gi' aniya' dunya, jari makapi'itu na iya ma masa damuli itu, ma sababbi du.",
        21: "Min hinang si Isa Al-Masi angkan kam angandol na ma Tuhan, ya bay amakallum si Isa min kamatayna sampay amabangsa iya ma deyom kasahaya'an. Jari ahogot na pangandolbi maka pangasabi ma Tuhan.",
        22: "Na buwattina'an, pagka kam angisbat na ma pandu' kasab'nnalan, tabowa na kam ang'bba min kasabulan kamemon bo' aniya' kasi-lasabi b'nnal ma pagkahibi bebeya'an si Isa. Angkan kam soho'ku: maglasa-liyasahi kam min deyom ataybi.",
        23: "Sabab ka'am ilu sali' sapantun onde' baha'u bay nianakan. In kapaganak ma ka'am itu ngga'i ka min manusiya' ya magkamatay, sagō' min palman Tuhan. A'a baha'u na kam sabab min kapagsab'nnalbi ma palman Panghū', ya makakallum ma manusiya' maka mbal magkapinda.",
        24: "Yuk ayat Kitab, “Pinjaman sadja saga manusiya' kamemon, sapantun parang. Kamemon kabantugan sigām sapantun sumping-sumping. Angalanos du parang, magkapakpak du isab kasumpingan,",
        25: "saguwā' anatas palman Panghū' salama-lama.” In palman Panghū' itu, ya na lapal ahāp bay panganasihat ka'am.",
    },
    2: {
        1: "Angkan kam subay ang'bbahan kamemon kahinanganbi ajahil. Da'a kam magputing. Da'a kam magbau'-bau' in ka'am ahāp bo' pa'in masi ala'at deyom ataybi. Da'a kam angalindi, maka da'a kam angalimut sehe'bi.",
        2: "Pasali' kam ni onde'-onde' baha'u nianakan, ya aruru' na pa'in. Ya du ka'am subay angabut-ngabut angadji' palman Tuhan. Sali' dalil gatas ahāp ko' inān, ya makapasangpot pangandolbi sampay ta'abutbi kasalamatanna,",
        3: "pagka tananambi na bang buwattingga kahāp Panghū' ma ka'am.",
        4: "Pasekot na kam ni si Isa, ya dalil batu allum ni kasaumulan. Pasekot kam bo' kam pinagguna e' Tuhan pangahinanganna luma' pat'nna'an Rū-na. Pinaralil isab kam ni batu allum, maka si Isa iya batu aheya pamahogotan luma' Tuhan. Bay tasulak si Isa Al-Masi e' saga a'a, sagō' pinene' iya e' Tuhan sabab landu' ahalga' ma atayna. Jari maina'an du kam ma luma' Tuhan maghinang ni iya min itikad abontol, buwat dalil imam. Maina'an kam anukbal ni iya saga kapudjihanbi maka kahinanganbi ahāp. Jari ka'amuhan iya ma panukbalbi sabab si Isa Al-Masi ya pamanyabutanbi.",
        5: "Pasekot na kam ni si Isa, ya dalil batu allum ni kasaumulan. Pasekot kam bo' kam pinagguna e' Tuhan pangahinanganna luma' pat'nna'an Rū-na. Pinaralil isab kam ni batu allum, maka si Isa iya batu aheya pamahogotan luma' Tuhan. Bay tasulak si Isa Al-Masi e' saga a'a, sagō' pinene' iya e' Tuhan sabab landu' ahalga' ma atayna. Jari maina'an du kam ma luma' Tuhan maghinang ni iya min itikad abontol, buwat dalil imam. Maina'an kam anukbal ni iya saga kapudjihanbi maka kahinanganbi ahāp. Jari ka'amuhan iya ma panukbalbi sabab si Isa Al-Masi ya pamanyabutanbi.",
        6: "Buwattitu ya tasulat ma deyom Kitab: “Aniya' batu landu' ahalga' tapene'ku, pat'nna'ku nihinang papagan luma' ma da'ira Siyun. Jari sasuku angandol ma iya halam du aniya' kapagsusunanna.”",
        7: "Tantu ahalga' batu itu ma ka'am ya magpangandol ma si Isa. Saguwā' aniya' mbal bilahi magkahagad, ya sinambat ma ayat Kitab dakayu', ya yuk-i, “Ya batu bay tasulak e' saga a'a maghinang luma', kinabā' halam aniya' gunana, ya na ina'an batu aheya to'ongan kalagihanna.”",
        8: "Maka aniya' gi' ayat dakayu', yuk-i, “Ya ina'an batu parugtulan tape' a'a, batu pamah'bba'an.” B'nnal ko' he'. Mbal sigām magkahagad ma palman Tuhan pasal si Isa, ya po'on sigām sali' dalil a'a makarugtul ni batu. Ya na tu'ud pangahandak Tuhan ma sigām.",
        9: "Malaingkan tapene' kam e' Tuhan bo' kam tahinang kaimaman magsusultan, bangsa sussi, a'a palsuku'an Tuhan. Nilinganan kam e'na paluwas min kalendoman, bo' papinda ni kasawahanna makainu-inu. Tapene' kam bo' supaya patanyagbi pasal kahinangan Tuhan ahāp makalandu'.",
        10: "Ma waktu bay dahū inān ngga'i ka kam suku' Tuhan, sagō' a'a Tuhan na kam ma buwattitu. Bay kam a'awam ma pasal ka'ase' Tuhan ma waktu palabay, saguwā' tananambi na ka'ase'na.",
        11: "Saga bagay kalasahanku, sali' kitam a'a liyu ma dunya itu sabab aniya' lahattam saddī. Angkan buwattitu panganjunjungku ma ka'am: da'a to'ongan dūlinbi napsu baranbi ala'at, sabab napsuta itu magsagga' asal maka kapameya'ta ma Tuhan.",
        12: "Ya kal'ngngananbi subay ahantap sadja minsan kam ma deyoman saga a'a mbal ata'uwan Tuhan. Minsan sigām bilahi anuna'an ka'am maghinang ala'at, ta'nda' e' sigām saga hinangbi ahāp, ya po'on sigām ananglitan Tuhan ma llaw kapi'ituna.",
        13: "Subay kam magpabeya' sadja ma saga a'a kamemon sasuku taga-kag'llal, ma sabab Panghū' Isa ya pameya'anbi. Kaissana, beya'unbi panoho'an min sultan mahatinggi, ya alanga min kamemon ma lahat itu.",
        14: "Pasunu', beya'unbi panoho'an min saga gubnul, ya kabuwanan kapatut aminasa sasuku maghinang ala'at, maka ananglit ma sasuku maghinang ahāp.",
        15: "Sabab ya na itu kabaya'an Tuhan ma ka'am, hinangunbi kahāpan. Jari pag'nda' saga a'a kulang panghati inān ma kahinanganbi, magtūy patambol bowa' sigām. Pahondong sigām amūng-mūng karupangan.",
        16: "Limaya na kam, maka ahāp isab. Saguwā' da'a kam anumagal in ka'am makajari maghinang ala'at ma sabab limaya na. Ata Tuhan na kam, angkan kam limaya maghinang panoho'anna sadja.",
        17: "Pagaddatinbi manusiya' kamemon. Kalasahinbi pagkahibi magpangandol ma si Isa, pagmatāwinbi Tuhan, pagaddatinbi sultan mahatinggi.",
        18: "Ka'am saga sosoho'an maghinang ma a'a, angalilla' sadja kam ma a'a ya paghinanganbi. Ngga'i ka hal a'a ahāp kasuddahanna, a'a alasa ma ka'am ya subay pagaddatanbi. Subay pagaddatinbi sigām minsan isab ab'ngngis.",
        19: "Bang kam ganta' bininasa ma halam aniya' sā'bi paminasahan ka'am, bo' pa'in sandalanbi ma sabab Tuhan ya paheyabi ma atay, kasulutan Tuhan ma ka'am.",
        20: "Sagō' bang kam angimanan katiksa'an ya pinapagtongod maka hinangbi ala'at, mbal kam patut sinanglitan. Sagō' bang kam anandal kabinasahan minsan bay makahinang ahāp, kasulutan du Tuhan ma ka'am.",
        21: "Ya na he' asal kabaya'an Tuhan ma ka'am, in ka'am subay asandal ma deyom kabinasahan. Al-Masi ya panunuranbi sabab bay na iya anandalan kabinasahan ma sababanbi. Pasali' kam ni iya.",
        22: "Halam to'ongan iya bay makarusa, halam iya bay makapah'lling puting minsan min t'dda.",
        23: "Ma waktu bay kapamūng-mūng ala'at ma iya, halam iya bay anambung ala'at. Waktu kapaminasa ma iya, halam iya bay ananggupan sai-sai. Gom pa'in pangandolna baranna ni Tuhan ya abontol hukumanna.",
        24: "Bay tinanggung e' si Isa karusahantam pagka amatay ma hāg pangalansangan ma iya, supaya kitam ang'bba min dusatam bo' amanuyu' kahinangan abontol. Kauli'an kitam ma sabab saga bakat bay tananamna.",
        25: "Bay kam sali' sapantun bili-bili alungay min paglabayan, sagō' ma buwattina'an pabibud na kam bo' pabeya' ma Al-Masi, ya angupiksa' ka'am sampay anganjagahan nyawabi.",
    },
    3: {
        1: "Ka'am saga kar'ndahan, subay sulutbi kabaya'an h'llabi. Manjari bang aniya' sigām mbal gi' magsab'nnal ma lapal Tuhan, bo' pag'nda' sigām kaul-pi'ilbi ahāp du, minnē' aniya' pagsab'nnalan sigām. Minsan sigām mbal bissalahanbi, tabowa sigām asulut",
        2: "pag'nda' sigām ma kabontol itikadbi sampay ma pana'atbi ma Tuhan.",
        3: "Mbal kam tahinang alingkat ma sabab pangari-ngaribi ma pangluwahanbi, buwat saga pama'alti bu'unbi, maka pamulawanbi maka pan'mmekbi ahalga'.",
        4: "Ya wajib tuyu'anbi bo' kam ahāp d'nda, subay addat ahāp. Bang kam ahongpot, bang areyo' pangatayanbi, anatas du kamanisbi sampay ni kato'abi. Maka landu' ahalga' kamanisbi buwattē' ma pang'nda' Tuhan.",
        5: "Buwattē' isab kahinangan saga d'nda suku' Tuhan ma masa awal. Bay sigām pasangdol ma iya, angkan sigām ahāp d'nda. Bay sinulut e' sigām kabaya'an h'lla sigām",
        6: "buwat si Sara, h'nda si Ibrahim. Sinulut e'na kabaya'an h'llana, niōnan e'na nakura'na. Na, ka'am saga d'nda ma buwattitu, bang ahāp hinangbi, maka bang kam mbal aluhay pinakitāw, sali' kam dī tubu' si Sara.",
        7: "Ka'am kal'llahan, subay ahāp akkalbi magpūn maka paghola'bi. Pagaddatinbi sigām pahāp pagka alunuk baran sigām min baranbi, sabab sali'-sali' du kam pinahampitan kallum taptap ma deyom sulga'. Bang buwattē' hinangbi halam aniya' makalimbit pangamu'-ngamu'bi ni Tuhan.",
        8: "Ya na itu bissalaku katapusan ma ka'am, subay kam dauyunan kamemon, magkannal-kiyannali. Sunurinbi addat magdanakan maglasa-liyasahi, ka'ase'inbi pagkahibi ma areyo' pangatayanbi.",
        9: "Bang kam ganta' nila'at, da'a balosinbi la'at. Bang kam sinukna'an, da'a pellenginbi sukna'. Ya pamalosbi ma sigām subay kahāpan sabab ya na kabaya'an Tuhan ma ka'am, supaya kam pinusaka'an kahāpan.",
        10: "Sabab tasulat ma deyom Kitab, ya yuk-i, “Sai-sai bilahi ahāp palasahanna, supaya tananamna waktu kasannangan, subay pahondong maghimumungan ala'at, subay mbal magbissala kaputingan.",
        11: "Subay iya pataikut min hinang ala'at, bo' maghinang ahāp. Subay iya atuyu' magsulut maka kasehe'anna, maka subay pagmatayanna kasannangan.",
        12: "Sabab anganjaga du Panghū' ma saga a'a abontol, kinale e'na pamanyabut sigām. Sagō' sinagga' e'na saga a'a jahallis.”",
        13: "Halam aniya' angala'at ka'am bang kam atuyu' maghinang ahāp.",
        14: "Maka minsan kam saupama pinuhinga' ma sabab hinangbi ahāp, aheya du kakōganbi. Da'a kam atāw ma pananggup manusiya', da'a isab kam magkahanggawan.",
        15: "Sagō' paheya'unbi Al-Masi ma deyom pangatayanbi, in iya tantu Panghū'bi. Subay kam asakap sakahaba' waktu supaya kam makasambungan sai-sai atilaw ka'am bang angay kam makatantu pinaniya'an kahāpan.",
        16: "Sagō' subay ahanunut maka a'addat panambungbi. Subay abontol isab itikadbi bo' magkaiya'an saga a'a ya anoway kahinanganbi ahāp ma sabab pameya'bi ma Al-Masi.",
        17: "Bang Tuhan ya magkahandak, ahāp kam taluwa' kabinasahan ma sabab ahāp hinangbi, bang pa'in da'a hinang ala'at.",
        18: "Sabab bay amatay Al-Masi pinamint'dda ma sabab kamemon paldusahan manusiya'. Ngga'i ka ma sabab dusa baranna, sabab halam aniya' dusana minsan dakayu'. Tu'ud iya amatay supaya kam binowa maghāp maka Tuhan. Bay iya pinapatay sagō' pinakallum e' Rū Tuhan.",
        19: "Min Rū Tuhan isab angkan iya bay pehē' magmahalayak ni saga umagad ya bay tinambolan e' Tuhan ma deyom ahirat.",
        20: "Ya na ina'an umagad saga a'a bay mbal ameya' ma kabaya'an Tuhan waktu kapangahinang adjung e' si Nū. Bay angagad Tuhan ma samantala' si Nū angahinang adjung inān, ya aniya' ameya' ma iya. Saguwā' pagtumbuk latap, walu' du a'a bay pasakat ni adjung bo' lappasan min latap.",
        21: "Ya kalappas sigām min latap inān sali' paralilan kalappastam labay min bohe' pagpandi ma waktu itu. Bang nihati pagpandi itu, ngga'i ka hinang pamala'an lumut baranta saguwā' paltanda'an in kitam bay anganjanji' ni Tuhan min itikad abontol. Manjari lappasan kitam sabab min kallum si Isa pabalik min kamatayna.",
        22: "Wa'i na iya pehē' ni sulga' aningkō' ma bihing Tuhan tampal ni kowan. Mahē' na iya magbaya' ma bangsa mala'ikat kamemon, maka ma ai-ai taga-kapatut atawa taga-ga'osan ma deyom sulga'.",
    },
    4: {
        1: "Na, pagka Al-Masi bay makalabayan kabinasahan ma ginhawa-baranna, ya du ka'am subay anengoran iya bo' kam sakap anandal kabinasahan. Sabab sai-sai angananam kabinasahan buwattē', ang'bba na min katagihanna magdusa.",
        2: "Jari puwas itu, sat'ggolbi maitu ma dunya, subay kam pinagagihan e' kabaya'an Tuhan. Da'a na kam pinagagihan e' napsu maka baya' manusiya',",
        3: "ya pinene' e' saga a'a ya mbal ata'uwan Tuhan. At'ggol bay kapaghinangbi kasabulan makatamparasa, magba'is maka maglangohan. Sakahaba' waktu pagtipunbi maglami-lami, landu' aheka bay inumbi. Bay kam pasumba isab ni ta'u-ta'u ya sammal ma pang'nda' Tuhan. Sagō' sarang na.",
        4: "Ma buwattina'an ainu-inu saga a'a bay sehe'bi waktu tagna' bang angay kam mbal na palamugay ni sigām angandūlan napsubi. Angkanna kam binissalahan la'at e' sigām.",
        5: "Saguwā' aniya' du waktu paharap saga a'a inān ni Tuhan angahaka pasal bay kahinangan sigām. Asakap asal Tuhan angahukum binangsa manusiya', saga a'a masi allum sampay a'a bay magpatayan.",
        6: "Ya itu sababanna angkan lapal ahāp itu bay pinagnasihat sampay ni umagad saga a'a magpatayan, bo' supaya sigām pinaniya'an kallum ma haddarat Tuhan, minsan sigām bay pinalabayan hukuman ya pangangganta'an manusiya' pagma-dunya lagi'.",
        7: "Sōng na kiyamat dunya itu, angkan subay ahāp sadja kōkbi. Subay ahantap e'bi amikil bo' ahāp pangamu'-ngamu'bi ni Tuhan.",
        8: "Maka ya na itu subay pahalga'bi min kamemon: maglasa-liyasahi kam to'ongan, sabab bang kam maglasa sab'nnal-b'nnal tantu kam magampun-iyampuni minsan painay heka kasā'anbi.",
        9: "Bang aniya' saga pagkahibi bebeya'an si Isa ganta' pahapit ni luma'bi, da'a kam magmusmud. Pa'iddahunbi sadja sigām min atay pote'.",
        10: "Aniya' ma ka'am kapandayan bay pamuwan e' Tuhan pakaniya-kaniya. Jari paggunahunbi kapandayanbi ilu panabangbi ni kasehe'an, sabab patut du bang ahāp e'bi angangguna kata'u atawa kapandayan bay pangandol ma ka'am e' Tuhan.",
        11: "Sai-sai apanday magnasihat, subay lapal min Tuhan ya pagnasihatna. Sai-sai ata'u anabang ma sehe'na, subay iya anabang to'ongan min kosog bay pangahandak iya e' Tuhan. Sabab minnē' pinaheya ōn Tuhan ma ai-ai hinangbi, pagka si Isa Al-Masi ya pamanyabutanbi. Patut iya pinasuku'an kasahaya'an maka barakat sampay ni kasaumulan. Amin.",
        12: "Saga bagay kalasahanku, da'a kam kinobla'an ma sabab kabinasahan aheya ya tum'kka panulayan ka'am, sabab maumu aniya' buwattē'.",
        13: "Sagō' palasigunbi ataybi, sabab tananambi na kabinasahan buwat bay kalabayan Al-Masi, jari aheya du kakōganbi bang pina'nda'an na sanglit sahayana ni kamemon.",
        14: "Subay kam kinōgan bang kam pinamūng-mūngan ala'at ma sabab Al-Masi ya pameya'anbi, sabab ilu pat'nna' ma ka'am Rū barakatan, ya na Rū Tuhan.",
        15: "Bang kam taluwa' kabinasahan, subay halam aniya' sababanna, buwat saga bay amapatay a'a, bay anangkaw, bay magpilliyu, atawa minsan bay palamud ma palkala' a'a ngga'i ka lamudbi.",
        16: "Sagō' bang kam pinananaman kabinasahan ma sabab Almasihin kam, da'a kam aiya'. Magsukul sadja kam ni Tuhan ma sabab ōn Al-Masi ya pangōn ka'am.",
        17: "Song na waktu panagna' hukuman Tuhan, sagō' kitam ma deyomanna ya nihukum dahū. Bang buwattē' kahālanna, bang kitam suku'na pinat'nna'an hukuman, ai kamaujuran saga a'a mbal magkahagad ma lapal ahāp ya min Tuhan?",
        18: "Buwat yukna ma deyom Kitab, “Bang a'a adil mbal agon lappasan, luba'-lagi'na na a'a baldusa, ya mbal angisbat Tuhan!”",
        19: "Angkanna, sai-sai kam angalabayan kabinasahan sabab iya na kahandak Tuhan ma ka'am, pasangdan kam maghinang ahāp. Pangandolunbi isab baranbi ni bay amapanjari ka'am, sabab tantu iya kapangandolan.",
    },
    5: {
        1: "Aniya' isab pamituwaku ma saga pagmatto'ahan ya ma deyomanbi, sabab pagmatto'ahan isab aku. Mataku itu bay maka'nda' kabinasahan Al-Masi, maka aniya' du isab lamudku ma sinosōng bang iya pinabangsa na ma pang'nda' saga manusiya' kamemon. Ya na itu amu'ku ni ka'am:",
        2: "Upiksa'unbi pahāp saga a'a bay pangandol ma ka'am e' Tuhan, ya sali' dalil bili-bili pinaipat ma ka'am. Ayarinbi sigām min kōg maka baya', sabab ya na itu kabaya'an Tuhan. Da'a kam subay nihagda. Ya pangupiksa'bi ma sigām subay ngga'i ka pagpilak, subay min kahilasanbi sadja.",
        3: "Da'a pagmandahinbi saga a'a bay pama'atas ka'am, gom pa'in kam panunuran sigām.",
        4: "Jari bang pi'itu pabalik si Isa Al-Masi, ya dalil nakura' magupiksa' bili-bili, landu' ahāp panungbasna ma ka'am. Ya tungbas inān mbal magkapinda kahāpna, sabab makahampit kam ma sahayana.",
        5: "Na, ka'am isab saga l'lla abata' lagi', beya'unbi pamituwa pagmatto'ahanbi ilu. Subay areyo' pangatayanbi sabubi magtabang-tiyabangi, sabab yuk lling Kitab, “Angatu Tuhan ma a'a alanga atayna, sagō' tabangna sasuku areyo' atayna.”",
        6: "Angkan kam subay magpatireyo' ni Tuhan Sangat Kawasa, bo' kam pinalanga e'na bang ta'abut llaw bay pangangganta'na.",
        7: "Tukbalunbi kasusahanbi kamemon ni Tuhan, sabab magka'inagon du iya.",
        8: "Pahāpunbi pamikilbi, pajaga kam to'ongan. Sabab ilu bantabi nakura' saitan amiha ka'am. Sali' iya sapantun halimaw maglunsul na pa'in, kalu aniya' tapihana nil'kkob e'na.",
        9: "Atuhunbi nakura' saitan ma ahogot pangandolbi ma si Isa, sabab kata'uwanbi ngga'i ka hal ka'am ya t'kkahan kabinasahan, sampay isab saga pagkahibi Almasihin ma kaluha'an dunya.",
        10: "Sagō' aubus pa'in e'bi anandalan kabinasahan ma dai'-dai', binawi' du kam e' Tuhan sampay halam aniya' salla'bi. Pinatotog e'na imanbi, binuwanan du kam kosog bo' mbal apinda min pangandolbi ma iya. In iya Tuhan po'onan tatabangan. Pinagabbit kam e'na supaya kam pinabangsa ma deyom kasahaya'anna ya mbal magkapinda, pagka Al-Masi ya parakayu'anbi.",
        11: 'Sanglitantam Tuhan, ya sangat kawasa sampay ni kasaumulan. Amin.',
        12: "Si Silas bay anabangan aku anulat sulat apu'ut itu. Bang ma bistahanku in iya dakayu' danakantam tantu kapangandolan. Bilahi aku amahogot ataybi, ya po'on aku amabeya' sulat itu. Sugpatanku isab saksi'ku, in itu tatabangan sab'nnal-b'nnal deyo' bay min Tuhan. Da'a bbahinbi.",
        13: "Amabeya' minsan la'a hal lapal sigām saga pagkahibi bebeya'an Al-Masi ya magsakaum maitu ma lahat Babilon, a'a tapene' e' Tuhan buwat ka'am. Ya du si Markus itu, ya itungku sali' anakku.",
        14: "Magsiyum kam tanda' sin paglasabi dangan maka dangan. Mura-murahan, bang pa'in kam pinaniya'an kasannangan deyom atay, sasuku kam suku' Al-Masi. Wassalam",
    },
}
