NAME = 'sml_BL_2008: Kitab Awal-Jaman maka Kitab Injil'
BOOK = 'II Thessalonians'

CHAPTERS = {
    1: {
        1: "Sulat itu min aku, si Paul, maka min sehe'ku si Silas maka si Timuti, pinasampay pi'ilu ni palhimpunan Tessaloneka, ya ka'am suku' Mma'tam Tuhan maka Panghū'tam si Isa Al-Masi.",
        2: "Mura-murahan, bang pa'in kam pinaniya'an tatabangan maka kasannangan atay e' Mma'ta Tuhan maka e' Panghū'tam si Isa Al-Masi.",
        3: "Saga dauranakanku angandol ma Al-Masi, wajib kami magsukul na pa'in ni Tuhan ma sababbi sakahaba' waktu. Ya angkan kami patut magsukul sabab aheya na kasōngan pagimanbi ni si Isa Al-Masi, maka pasōng gom pa'in paglasabi dangan maka dangan.",
        4: "Ya na itu sababanna angkan kami amantug ma pasalbi ni saga kajama'ahan Tuhan. Sabab minsan kam ma deyom katiksa'an maka kabinasahan, asandal kam maka anatas pangandolbi ma iya.",
        5: "Saga pakaradja'an itu kamemon amuwan bainat in hukuman Tuhan abontol, sabab kasandalanbi katiksa'an ma sabab suku' Tuhan kam, ati minnē' kinata'uwan in ka'am tōp pinasōd ni deyom pagparintahanna.",
        6: "Abontol asal hukuman Tuhan, tiniksa' du e'na saga a'a bay aniksa' ka'am.",
        7: "Ka'am sasuku magkasusahan buwattina'an, binuwanan du kasalamatan ma sinosōng, beya' isab kami. Nihinang itu e' Tuhan bang panyata' Panghū' Isa pi'itu min deyom sulga' magbeya' maka saga mala'ikatna akawasa.",
        8: "Asahaya kapi'ituna sali' sapantun api asuleyab. Amat'nna' iya hukuman ma sasuku mbal magmatāw ma Tuhan, maka ma sasuku isab mbal ameya' ma lapal ahāp pasal Panghū' Isa.",
        9: "Ya pangahukum Tuhan ma saga a'a inān mulka' halam aniya' katobtobanna. Binutawanan sigām min Panghū'tam maka min kawasana asahaya,",
        10: "ma llaw pagbīng si Isa Al-Masi pi'itu. Ya na ina'an waktu pangamahaldika' iya e' a'a suku'na, waktu pamaheya ma iya e' saga a'a magpangandol kamemon. Talapay isab ka'am ilu ma waktu sinōng inān, sabab tapagkahagadbi saksi' kami pasal si Isa.",
        11: "Angkanna kami angamu'-ngamu' na pa'in ni Tuhan ma sababbi. Ya pangamu' kami, bang pa'in kam tubus ma kaul maka pi'il pagka kam bay tapene' e' Tuhan. Ya pangamu' kami isab, bang pa'in kam tinabangan min kawasana bo' tatalusbi kamemon niyatbi ma sabab si Isa ya pangandolanbi.",
        12: "Angkan kami angamu'-ngamu' buwattitu supaya pinaheya ōn si Isa Panghū'tam ma sababbi. Maka pinaheya du isab kam e'na, ma sabab tatabangan min Tuhantam sampay min Panghū' Isa Al-Masi.",
    },
    2: {
        1: "Na, in pasal kapi'itu Panghū'tam si Isa Al-Masi, maka pasal pagtimuktam maina'an maka iya, ya na itu pangamu' kami ma ka'am saga dauranakanku.",
        2: "Da'a kam magtūy asasaw atawa asusa bang aniya' a'a magbau'-bau' in llaw pagbīng Panghū' Isa ni dunya ta'abut na. Da'a beya'unbi minsan kami ya tinugpang bay amabeya' lapal atawa sulat atawa bissala bay patulun min Tuhan.",
        3: "Da'a kam ameya' nilingu e' sai-sai minsan buwattingga pamissala sigām. Sabab ya llaw Panghū' inān mbal gi' magtūy at'kka, sabab in kaheka'an manusiya' ma dunya itu subay anagga' dahū ma Tuhan. Maka aniya' dakayu' a'a mamarahi la'atna subay patuwa' dahū bo' yampa at'kka llaw ina'an-i. Nalka' ya pamakadal ma a'a inān.",
        4: "Kinuntarahan e'na ai-ai kamemon ya pagtuhanan e' manusiya', maka kamemon ya sinumba e' sigām. Magpalanga iya di-na min kamemon, ati pasōd iya aningkō' ma langgal pangarapan Tuhan magnahu'-nahu' in iya Tuhan.",
        5: "Halam bahā' taentombi? Bay na itu pangahakaku ma ka'am waktu lagi' bay kamailuku.",
        6: "Kata'uwanbi du bang ai ya angagpang a'a mamarahi ala'at e', ya angkan mbal magtūy paniya' bay yukku-i. Subay ta'abut waktu bay pangangganta' iya bo' yampa iya palahil.",
        7: "Ma buwattina'an magkahinangan asal a'a mamarahi la'atna inān, sagō' ma deyom sipuk. Mbal gi' tino'ongan hinangna sat'ggol masi maitu ya manghahawid.",
        8: "Subay nila'anan manghahawid inān bo' yampa palahil a'a mamarahi la'atna itu. Sagō' atubag du iya e' Panghū' Isa ma waktu kabalikna pi'itu. Amatay iya e' napas Panghū', magmula iya katūyan ma sabab sahaya Panghū'.",
        9: "Jari paglahil a'a itu, aniya' kawasana min nakura' saitan ya angkan iya makahinang kaginisan hinang kawasahan maka saga paltanda'an maka saga hinang makainu-inu, sagō' ngga'i ka b'nnal.",
        10: "Ginuna e'na kala'atan indaginis pamarupangna saga a'a anudju nalka'. Ya angkan sigām anudju nalka' sabab mbal sigām bilahi ma pandu' kasab'nnalan. Halam tataima' e' sigām bo' supaya sigām lappasan min hukuman dusa.",
        11: "Pagka buwattē', pinat'kkahan sigām e' Tuhan akkal-pikilan abengkok, ya po'on sigām magkahagad ma kaputingan.",
        12: "Angkan pinat'kkahan hukuman sasuku mbal magkahagad ma pandu' kasab'nnalan saguwā' kinōgan gom pa'in maghinang kala'atan.",
        13: "Sagō' wajib kami magsukul ni Tuhan sakahaba' waktu ma sabab ka'am, saga dauranakan kinalasahan e' Panghū'tam. Sabab bay kam tapene' asal e' Tuhan min awal tagna' lagi', supaya kam lappasan ma sabab hinang Rū Tuhan amasussi deyom ataybi, maka ma sabab pagkahagadbi ma pandu' kasab'nnalan pasal si Isa Al-Masi.",
        14: "Ya na ko' he' po'onna angkan kam tapene' e' Tuhan, pagka takalebi lapal ahāp ya bay pagnasihat kami ma ka'am. Tapene' kam e'na supaya kam pinahampitan sanglit maka sahaya Panghū'tam si Isa Al-Masi.",
        15: "Angkanna, saga dauranakanku, patotogunbi pangandolbi. Bogboginbi to'ongan saga pandu' bay takalebi min bowa' kami, sampay saga pandu' ma deyom sulat bay pabeya'an kami ni ka'am.",
        16: "Kinalasahan kitam e' Mma'tam Tuhan, maka tinabang kitam e'na, angkan pamuwanna na ma kitam katotogan atay anatas ni kasaumulan. Pamuwanna isab pangasa mbal magkapinda. Mura-murahan, bang pa'in Mma'tam Tuhan maka Panghū'tam si Isa Al-Masi",
        17: "amahogot ataybi maka amakosog ka'am supaya ahāp sadja hinangbi maka bissalabi.",
    },
    3: {
        1: "Na, saga dauranakanku, ya itu llingku katapusan. Amu'-amu'inbi kami tabang ni Tuhan, bang pa'in al'kkas palatag lapal pasal Panghū'tam, bang pa'in nihulmat isab lapal itu e' saga a'a makakale, buwat bay kapangahulmatbi.",
        2: "Angamu'-ngamu' kam isab bang pa'in kami pinuwas e' Tuhan min a'a jahulaka', sabab ngga'i ka a'a kamemon ya magkahagad ma lapal ahāp.",
        3: "Daipara kapangandolan to'ongan Panghū'tam. Pinahogot e'na imanbi, nihampanan isab kam bo' mbal ni'inay e' nakura' saitan.",
        4: "Angandol kami ma ka'am ma sabab Panghū'tam, ati kata'uwan kami in ka'am tantu ameya' ma bay panoho'an kami, maka hinangbi na pa'in.",
        5: "Mura-murahan, bang pa'in kam niulinan e' Panghū' bo' pasōng ta'ubi pasal lasa Tuhan ma ka'am, maka pasal kasandal Al-Masi.",
        6: "Manjari, saga dauranakanku, pagka aniya' kapatut kami min Panghū'tam si Isa Al-Masi, soho'ta kam paokat min pagkahibi bebeya'an si Isa kasehe', ya lisu'an magusaha, maka mbal ameya' ma bay pamandu' kami ma ka'am.",
        7: "Sabab kata'uwanbi asal in kami subay panunuranbi. Halam kami bay lisu'an maghinang waktu gi' kamailu kami ma ka'am.",
        8: "Halam kami bay mikibalanja', sagō' bayaran kami ai-ai bay pagnapaka kami. Gom pa'in kami maghulas-sangsā' llaw maka sangom bo' supaya aniya' kalluman kami. Jari mbal kam kabuhatan amalanja'.",
        9: "Patut asal bang kami mikibalanja' ni ka'am, sagō' amalanja'an kami di-kami bo' aniya' kapamintānganbi.",
        10: "Sabab minsan ma waktu kamailu kami, aniya' bay pamandu' kami ma ka'am, yuk-i, “Bang a'a mbal bilahi maghinang, subay iya mbal pakanbi.”",
        11: "Ya angkan itu binissala, sabab makakale kami aniya' ilu ma ka'am saga a'a lisu'an magusaha maka kabiyaksahan sigām palamud ma palkala' ngga'i ka suku' sigām.",
        12: "Ya panoho'an kami maka pamituwa kami ma sigām min kapatut Panghū'tam si Isa Al-Masi, subay sigām pahantap magusaha.",
        13: "Sagō' ka'am, saga dauranakanku, da'a kam sinumu maghinang ahāp.",
        14: "Bang aniya' ganta' mailu agagga ameya' ma panoho'an kami ya ma deyom sulat itu, gindaninbi a'a inān ati da'a kam magbeya' maka iya bo' supaya iya aiya'.",
        15: "Da'a pa'in iya itungunbi sali' bantabi, sagō' banda'anbi iya sali' dakayu' danakanbi.",
        16: "Mura-murahan, bang pa'in kam pinaniya'an kasannangan e' Panghū'tam, ya po'onan kasannangan, sakahaba' waktu minsan ai makani-ka'am. Mura-murahan isab, bang pa'in iya pagapi' ma ka'am kamemon.",
        17: "Na, aku baranku ya anulat katapusan sulat itu, tanda' in aku si Paul ya amabeya'. Buwattitu asal kabiyaksahanku ma sulatku kamemon.",
        18: "Mura-murahan, bang pa'in ka'am kamemon pinaniya'an tatabangan aheya e' Panghū' Isa Al-Masi. Wassalam",
    },
}
