NAME = 'sml_BL_2008: Kitab Awal-Jaman maka Kitab Injil'
BOOK = 'Romans'

CHAPTERS = {
    1: {
        1: "Sulat itu deyo' min aku, si Paul, pinasampay ni ka'am ma da'ira Rōm. Aku itu dakayu' sosoho'an si Isa Al-Masi. Tapene' aku e' Tuhan, kawakilan e'na magnasihat lapalna ahāp.",
        2: "Lapal ahāp itu bay panganjanji' e' Tuhan ma masa awal. Bay pinalatun e'na ma saga nabi, ati sinulat e' sigām ma deyom Kitab.",
        3: "Si Isa anak Tuhan ya pinagbissala ma lapal ahāp itu. Bang takdil ni kapaga'ana, tubu' iya min sultan Da'ud.",
        4: "Bang takdil ni kajarihanna maka palnyawahanna, asussi iya luwas bay min Rū Sussi, maka manyatakan isab in iya b'nnal Anak Tuhan ma sabab kosog kawasa Tuhan ya bay pamakallum iya min kamatay. Si Isa Almasi Panghū'tam ko' itu.",
        5: "Iya ya palsababan angkan aku kabuwanan kapatut e' Tuhan ati kawakilan magnasihat bo' supaya aniya' saga a'a min bangsa kamemon tabowa e'ku magsab'nnal maka ameya' ma si Isa.",
        6: "Ya du ka'am maglahat ma da'ira Rōm ilu, tapene' du isab kam e' Tuhan bo' pasuku' ma si Isa Al-Masi.",
        7: "Amabeya' aku sulat itu ni ka'am kamemon mailu ma Rōm, a'a kinalasahan e' Tuhan maka pinene' e'na bo' kam manjari a'ana. Mura-murahan, bang pa'in kam kaniya'an tatabangan maka kasannangan atay e' Mma'tam Tuhan maka e' si Isa Al-Masi Panghū'tam.",
        8: "Tagna'anku na bissalaku ma ka'am: magsukul aku ni Tuhan labay min si Isa Al-Masi, maka magsukul aku ma pasalanbi kamemon sabab abantug na pangandolbi sampay ma kaluha'an dunya.",
        9: "Saksi'ku Tuhan ya paghinanganku min deyom atay pagka aku magnasihat lapal ahāp pasal Anakna. Taentomku kam sakahaba'",
        10: "waktu kapangarapku ni Tuhan. Amu'ku isab ni iya bang pa'in aku kinahandakan e'na supaya makaluhaya pi'ilu patibaw ni ka'am ma waktu itu.",
        11: "Landu' to'ongan aku bilahi mag'nda' maka ka'am sabab aniya' kahāpan min Rū Tuhan bowahanku ka'am, supaya angahogot imanbi tudju ni Tuhan.",
        12: "Saguwā' bang aku makamailu ma ka'am, magkalasigan kitam sali'-sali', ka'am ma sabab pangandolku, aku isab ma sabab pangandolbi.",
        13: "Saga dauranakanku, kabaya'anku subay kam mbal a'awam ma pasalanku. Min heka na aku bay agara' anibaw ka'am, saguwā' aniya' na pa'in makabimbang, ya po'on aku halam bay makalanjal. Ya maksudku pi'ilu, subay aniya' paluntungan min pagnasihatku, hatina aniya' a'a tabowaku magsab'nnal ma si Isa, buwat bay kapamowaku ma bangsa kasehe' ya ngga'i ka isab Yahudi.",
        14: "Sabab aniya' hinang bay pama'atas ma aku, ya po'on aku subay magnasihat lapal ahāp ma a'a kamemon minsan ai bangsa, bangsa Girīk ka atawa bangsa saddī, a'a taga-pangadji' ka atawa halam aniya' pangadji'na.",
        15: "Angkan aku atuyu' to'ongan magnasihat lapal ahāp itu sampay ma ka'am ya maglahat mailu ma da'ira Rōm.",
        16: "Mbal aku aiya' magnasihat lapal ahāp itu sabab aniya' barakatna min Tuhan pamapuwas a'a kamemon min hukuman dusa, bangsa Yahudi dahū bo' yampa bangsa kasehe', ya sasuku magsab'nnal ma lapal itu.",
        17: "Lapal ahāp itu amahatian kitam bang buwattingga pamabontol Tuhan ma kitam manusiya'. Subay kitam angandol sadja, min tagna'anna sampay ni katapusanna, buwat bay tasulat ma deyom Kitab, ya yuk-i, “Sai-sai angandol ma Tuhan, bo' tabista e'na abontol, allum du iya.”",
        18: "In mulka' Tuhan pinabukis na min deyom sulga', pinat'kkahan saga manusiya' ma sabab ya nihinang e' sigām ma halam aniya' pagmatāw ma Tuhan. Katambunan e' sigām in pangita'u b'nnal.",
        19: "Patut sigām minulka'an sabab manyatakan asal kajarihan Tuhan, sabab baran Tuhan ya bay amata'uwan sigām. Tu'ud sigām mbal bilahi am'nnal.",
        20: "Sangay min waktu bay pamapanjari dunya itu e' Tuhan atampal asal palantarana, minsan iya mbal ta'nda' e' manusiya'. Atampal in iya taga-kawasa taptap ni kasaumulan. Atampal isab in iya Tuhan, takilā asal min kamemon ai-ai bay papanjarina. Manjari halam aniya' a'a makara'awa in iya a'awam pasal Tuhan.",
        21: "Makata'u asal sigām ma pasal Tuhan, in iya patut pagtuhanan, saguwā' mbal sigām bilahi angamahaltabat iya atawa angōn Tuhan ma iya. Mbal sigām minsan magsarang-sukul. Ya pinikil na pa'in e' sigām pikilan halam aniya' kagunahanna, ati alendom akkal sigām kabowa karupangan ya tahinang sigām.",
        22: "Maglaku-laku sigām in sigām taga-pangita'u sagō' magkarupangan sadja.",
        23: "Arapun sigām amudji Tuhan ya taptap allum, saguwā' ya pinudji e' sigām saga ta'u-ta'u pinaka luwa manusiya' ya magkamatay. Pinudji isab e' sigām ta'u-ta'u luwa hayop, luwa manuk-manuk, luwa ai-ai maglelehan ma kuwit tana'.",
        24: "Angkanna manusiya' itu pinasagaran e' Tuhan magdūl-baya' ma kasabulan ai-ai kinanapsuhan e' sigām. Magkahinangan na pa'in sigām kalumu'an dapagkahian.",
        25: "Sinulak e' sigām bissala b'nnal pasal Tuhan ati pinene' e' sigām bissala puting. Ya sinumba e' sigām saga ai-ai bay pinapanjari e' Tuhan, sagō' Tuhan ya mbal sinanglitan minsan iya ya Magpapanjari angkan patut subay pinudji sampay ni kasaumulan. Amin.",
        26: "Pagka buwattē' kahinangan manusiya', pinasagaran sigām e' Tuhan magpangandūlan napsu sigām makatamparasa. Ang'bba kar'ndahan min addat sigām kar'ndahan bo' magkabaya' maka pagkahi d'nda maghinang ala'at.",
        27: "Damikiyanna isab kal'llahan, mbal bilahi ma d'nda sagō' magkabaya' maka pagkahi sigām l'lla. Magbeya' sigām maghinang kasabulan, angkan sigām pinat'kkahan la'at pinapagtongod maka kala'atan ya bay tahinang sigām.",
        28: "Na, pagka bangsa manusiya' itu mbal bilahi angisbat pangita'u b'nnal pasal Tuhan, pinasagaran sigām e'na magpikil karupangan, ati nihinang e' sigām ya mbal manjari nihinang.",
        29: "Ap'nno' panahu'an sigām e' kala'atan maka dusa kaginisan, hawa napsu maka kajahilan. Makalandu' heka kala'atan ma deyom pangatayan sigām, buwat saga angalindi, amono' pagkahi sigām manusiya', angalugat, angulli', anganjahulaka', amalatun bissala ala'at,",
        30: "angalimut isab sigām ma kasehe'an sigām. Ab'nsi saga a'a buwattē' ma Tuhan. Ajingki sigām ma pagkahi sigām, alanga to'ongan atay sigām maka magabbu-abbu na pa'in. Ya sadja pinikil e' sigām bang buwattingga kasōng hinang sigām ala'at-i. Agagga sigām ma pami'at matto'a",
        31: "maka ala'at pamikil sigām. Mbal sigām kapangandolan, mbal alasa atawa ma'ase' ma pagkahi sigām, mbal tabowa magkahāp.",
        32: "Makata'u saga manusiya' itu abontol asal pangahandak Tuhan ma pasal a'a maghinang saga dusa itu, in sigām subay pinapatay. Sagō' minsan buwattē', luhūy sigām maghinang kala'atan maka kinōgan gom pa'in bang aniya' a'a kasehe' makasali' ni sigām.",
    },
    2: {
        1: "Angkanna kam mbal makara'awa, sasuku kam anoway pagkahibi ma sabab ala'at hinangna. Yukbi in sigām patut pinat'nna'an hukuman, sagō' amat'nna'an kam di-bi hukuman sabab ya du ka'am maghinang kala'atan. Hatina, bang kam anoway kasehe'anbi, sali' ka'am baranbi ya sinoway.",
        2: "Kata'uwanta asal, abontol hukuman Tuhan ya pamat'nna'na ma sasuku maghinang ginisan la'at bay sambatku he'.",
        3: "Kumpasbi bahā' in ka'am makapuwas min hukuman Tuhan, bo' pa'in masi maghinang kala'atan ya panowaybi sehe'bi?",
        4: "Ma'ase' Tuhan ma ka'am, angkan kam halam pinat'nna'an hukuman saru'un-du'un, sagō' halam tapaheyabi ma atay in kahāpanna, maka ka'ase'na, maka kalunuk pangatayanna. Ya sadja kabaya'anna in ka'am subay pataikut sampay ang'bba min dusabi.",
        5: "Sagō' atuwas kam, mbal bilahi apinda min dusabi. Angkanna paruhun kabinasahan ma ka'am bang ta'abut llaw pamatuwa' e' Tuhan astolna maka hukumanna abontol.",
        6: "Sabab in manusiya' kamemon tinungbasan du e' Tuhan pakaniya-pakaniya, pinapagtongod maka ai-ai bay hinang sigām ma dunya.",
        7: "Aniya' manusiya' kasehe' atukid maghinang ahāp sabab sanglit maka hulmat min Tuhan ya niangut e'na, maka kallum kakkal. Ya pamuwan Tuhan ma a'a buwattē' kallum taptap ni kasaumulan.",
        8: "Aniya' isab a'a kabintanan magpalanga di-na min kasehe'anna. Sinulak e' sigām kasab'nnalan ati ameya' ma kala'atan. Tantu pinat'kkahan mulka' Tuhan saga a'a buwattē'.",
        9: "Sasuku biyaksa maghinang ala'at taluwa' du katiksa'an maka kabinasahan, bangsa Yahudi bo' yampa bangsa kasehe'.",
        10: "Saguwā' sasuku maghinang ahāp sinanglitan du e' Tuhan, binuwanan kahulmatan maka kasannangan atay, bangsa Yahudi bo' yampa isab bangsa kasehe',",
        11: "sabab Tuhan mbal amapagbidda' ma manusiya'. Sali'-sali' sigām ma pang'nda'na minsan ai bangsa.",
        12: "Saga bangsa kasehe', ya halam bay kapat'nna'an sara' si Musa, amutawan du min Tuhan minsan halam aniya' sara' pangalanggalan sigām. Maka bangsa Yahudi isab, taluwa' sigām hukuman ma buwat panoho'an sara' si Musa.",
        13: "Sabab ngga'i ka min kakaleta ma sara' si Musa ya angkan kita abontol ma pang'nda' Tuhan, saguwā' min kapameya'ta ma panoho'anna.",
        14: "Halam aniya' sara' si Musa ma saga a'a ya ngga'i ka Yahudi, sagō' bang sigām angahinang kahāpan luwas min deyom atay sigām, hatina tabeya' e' sigām sara' Tuhan.",
        15: "Aniya' tanda' saksi' in panoho'an sara' pat'nna' asal ma deyom itikad sigām, jari minnē' aniya' pangita'u sigām pasal hinang ya patut nihinang maka mbal.",
        16: "Manjari bang ta'abut llaw damuli, ya llaw pangahukum Tuhan ma manusiya' labay min si Isa Al-Masi, tinanding e'na ai-ai bay katapukan ma deyom pamikil, ati minnē' sigām nihukum. Buwattē' isab ma lapal ahāp ya pagnasihatku.",
        17: "Na ka'am saga Yahudi, ya pasangdol ma sara'-panoho'an min si Musa bo' supaya kam tinaima' e' Tuhan. Tuhan isab ya pagmalangkahianbi ni a'a kasehe'an.",
        18: "Kata'uwanbi bang ai pangahandak Tuhan ma ka'am, maka bang ai ya wajib hinangbi ma sabab sara' si Musa ya pangadji'anbi.",
        19: "Pangannalbi in ka'am tōp magmalim ma a'a buta, ya halam pangadji'na. Yukbi in ka'am sali' sawa pamasawa akkal a'a kasehe', ya ma deyom kalendoman.",
        20: "Pangannalbi isab in ka'am jukup ma akkal maka ma pangita'u sabab ilu sara' ma ka'am, angkan yukbi in ka'am ata'u amaguru ma a'a mbal ata'u, amituwa isab ma saga a'a a'awam.",
        21: "Ata'u kam amandu' ma a'a kasehe'an, angay kam mbal amandu'an di-bi? Banda'anbi a'a kasehe' subay mbal anangkaw, bo' ka'am ya anangkaw du!",
        22: "Pamandu'bi subay mbal angaliyu-lakad ma ngga'i ka paghola'na, bo' ka'am ya labi magd'nda. Asammal kono' ma pang'nda'bi bang a'a anumba ta'u-ta'u, bo' pa'in ka'am ya angagaw ai-ai ahalga' min luma' pagsusumbahan ta'u-ta'u inān!",
        23: "Magabbu-abbu kam in ka'am kabuwanan sara' Tuhan, sagō' ka'am ya amuwan kamaruhan ma Tuhan pagka halam beya'bi panoho'anna.",
        24: "Buwat bay tasulat ma deyom Kitab, ya yuk-i, “Ka'am saga Yahudi ya sababna angkan Tuhan pinah'llingan pangkal e' bangsa kasehe'an.”",
        25: "In kitam Yahudi sinō' ni'islam tanda' saksi' in kitam a'a suku' Tuhan. Saguwā' bang kam maglalanggal sara', sali' halam aniya' pūs ma pagislambi. Ahāp lagi' kam halam bay ni'islam.",
        26: "Bang takdil ni a'a ngga'i ka Yahudi, a'a halam bay ni'islam, abila sigām ameya' ma panoho'an sara', binista sigām e' Tuhan suku'na sali' du maka a'a bay ni'islam.",
        27: "Manjari ka'am saga Yahudi katōngan dusa e' bangsa kasehe' inān, minsan kam kaniya'an Kitab Tawrat. Katōngan kam dusa sabab ka'am ya angalanggal sara' minsan bay ni'islam, sagō' sigām ya angisbat sara' minsan halam bay ni'islam.",
        28: "Ya dī Yahudi ngga'i ka a'a ya amogbogan addat maka usulan Yahudi, ya taga-bainat pagislam isab ma baranna.",
        29: "Ya taluwa' niōnan Yahudi to'ongan bang a'a taga-bainat ma deyom pangatayanna. Hinang Rū Tuhan ko' itu, ngga'i ka min pamogbogna ma sara'. A'a inān mbal sinanglitan e' pagkahina manusiya' bang buwattē' kapagyahudina, sagō' sinanglitan iya e' Tuhan.",
    },
    3: {
        1: "Kalu aniya' atilaw, yuk-i, “Na bang buwattē', halam bahā' aniya' kasōngan kami bangsa Yahudi? Maka addat kami pagislam halam aniya' kapūsanna?”",
        2: "Buwattitu panambungku ma a'a inān: tantu aheya kasōngan bangsa Yahudi. Muna-muna, pangandol ma sigām ya dī palman Tuhan.",
        3: "Kalu aniya' anilaw, yuk-i, “Painay Yahudi kasehe'an ya mbal angandol ma Tuhan? Taluwa' bahā' bang yukta in Tuhan mbal kapangandolan ma sabab manusiya' mbal angandol?”",
        4: "Tantu mbal. Minsan magputing kamemon manusiya', mbal magputing Tuhan. Buwat bay tasulat ma deyom Kitab, ya yuk-i, “Mattan in ka'adilannu min ai-ai pamissalanu. Anganda'ug sadja ka bang ma paghuhukuman.”",
        5: "Aniya' gi' anganjawab, yuk-i, “Tantu atampal to'ongan ka'adilan Tuhan sabab katā pagbidda'anna maka manusiya' ya ngga'i ka a'adil. Jari ai pamikilta bang buwattē'? Asā' bahā' hinang Tuhan bang pagmulka'anna dusatam?”",
        6: "Tantu mbal. Abontol pangamulka' Tuhan, patut iya amat'nna' hukuman ma binangsa manusiya'.",
        7: "Aniya' gi' isab anganjawab, yuk-i, “Bang aku saupama magputing, bo' minnē' kasakupan du in Tuhan b'nnal to'ongan angkan subay minahaldika', angay aku subay pinat'nna'an hukuman dusa?",
        8: "Gom gi' kita magdusa, sabab minnē' aniya' pangamahaldika' ma Tuhan.” Asā' panganjawab e', sagō' aniya' saga a'a bay anuna'an aku in aku kono' bay amitnahan a'a subay angandusa paheka bo' supaya paheya kamahaldika'an Tuhan. Putingan asal panuna' he'. Saga a'a inān tōp pinataluwa'an hukuman Tuhan.",
        9: "Na, ahāp bahā' kahālanta bangsa Yahudi itu min bangsa kasehe'? Ngga'i ka. Bay na kam pata'uku in bangsa kamemon, Yahudi maka ngga'i ka, kapagbaya'an sali'-sali' e' paldusahan sigām,",
        10: "buwat bay tasulat ma deyom Kitab, ya yuk-i, “Halam aniya' manusiya' abontol ma pang'nda' Tuhan.",
        11: "Halam aniya' pangita'u sigām pasal Tuhan, halam aniya' atuyu' angisbat iya.",
        12: "Magsiha'an a'a kamemon min kabontolan, halam aniya' kagunahan sigām. Halam aniya' minsan dangan maghinang ahāp.",
        13: "Bowa' sigām sali' dalil kubul halam katambunan, hal paluwasan bissala pangakkal. Sapantun sigām sowa sabab makamula bowa' sigām.",
        14: "Anukna' na pa'in sigām, sabab landu' ab'nsi.",
        15: 'Tagihan sigām anganjuri, kabintanan sigām amapatay.',
        16: "Kabiyaksahan sigām amaka'at, amasukkal.",
        17: "Mbal sigām ata'u angahāp atawa amapagsulut.",
        18: "Halam aniya' pagmatāw sigām tudju ni Tuhan.”",
        19: "Kata'uwanta asal, ai-ai panoho'an ma deyom sara' inān bay pinat'nna'an saga a'a ya ma deyo'an sara', supaya halam aniya' makapanganda'awa bang katōngan dusa. Manjari tabowa manusiya' kamemon pinat'nna'an hukuman e' Tuhan.",
        20: "Sabab halam to'ongan aniya' manusiya' binista abontol e' Tuhan ma sabab pameya'na ma panoho'an sara'. Saguwā' sara' Tuhan ya po'onanna angkan tata'utam in kitam dusahan.",
        21: "Saguwā' ma buwattina'an pinata'u kita bang buwattingga kapangampun Tuhan ma dusa manusiya', bo' supaya sigām tabista e'na abontol minsan ngga'i ka min pamogbog sara'. Tasulat asal ma deyom Kitab Tawrat maka Kitab Jabul pasal maksud Tuhan itu,",
        22: "hatina sai-sai angandol ma si Isa Al-Masi, minsan ai bangsa, niampun dusana ati abontol iya ma bistahan Tuhan. Halam aniya' kapagbidda'an manusiya',",
        23: "sabab makarusa sigām sali'-sali' ati halam aniya' maka'abut ni ka'adilan Tuhan.",
        24: "Malaingkan pina'nda'an e' Tuhan lasana maka ase'na ni manusiya' minsan halam aniya' tongodna. Ati tahinang sigām abontol ma bistahanna, sali' halam bay makarusa, ma sabab kapangal'kkat sigām min hukuman dusa e' si Isa Al-Masi.",
        25: "Bay pinalahil si Isa e' Tuhan bo' supaya amabu'us laha'na pangampun dusa manusiya', sasuku angandol ma iya. Buwattē' hinang Tuhan pama'nda'na kabontolanna, sabab halam bay inayna karusahan manusiya' ma waktu palabay, hal bay sabalanna.",
        26: "Ta'nda' isab kabontol Tuhan ma buwattina'an, sabab aniya' na taluwa' hukuman ma sabab dusa manusiya'. Minnē' magmattan in Tuhan abontol to'ongan, maka sasuku angandol ma si Isa abontol isab ma pang'nda' Tuhan.",
        27: "Jari bang buwattē' kahinangan Tuhan ma kitam, mbal na kita makapagabbu pasal ai-ai bay hinangta. Kalu-kalu bang bay kita binista abontol ma sabab kapamogbogta ma sara', sagō' ngga'i ka. Subay min pangandolta sadja ya angkan kita binista abontol e' Tuhan.",
        28: "Atampal du, ya po'on manusiya' tabista abontol e' Tuhan, min pangandolna sadja, ngga'i ka min pamogbogna ma sara'.",
        29: "Arai' pangannalbi in Tuhan itu pagtuhanan e' bangsa Yahudi sadja, sagō' ngga'i ka. Pagtuhanan iya sampay e' bangsa ngga'i ka Yahudi,",
        30: "sabab dakayu' du Tuhan. Bangsa Yahudi maka bangsa kasehe', sali'-sali' du sigām binista abontol e' Tuhan, sasuku sigām angandol ma si Isa.",
        31: "Kalu yukbi in sara' Tuhan inān subay tinimanan pagka aniya' na pangandolta ma si Isa. Sagō' mbal isāb, sabab bang si Isa ya pangandolanta, gom pa'in isbatta sara' Tuhan.",
    },
    4: {
        1: "Manjari ai na pamūngta pasal bay kalabayan si Ibrahim, ya pag'mma'an pangkattam Yahudi?",
        2: "Saupama si Ibrahim, bang iya bay binista abontol e' Tuhan ma sabab ahāp kahinanganna, aniya' pamantugna ma baranna. Saguwā' halam aniya' pamantuganna ma pang'nda' Tuhan, sabab ngga'i ka min kahinanganna ya angkan iya binista abontol.",
        3: "Entomunbi bay tasulat ma deyom Kitab, ya yuk-i, “Bay am'nnal si Ibrahim ma Tuhan, ati binista iya abontol sabab min kapam'nnalna.”",
        4: "Saupama bang aniya' a'a maghinang ni a'a dakayu' bo' ginadjihan, mbal yukta in gadji inān hal paglasa ma iya. Tu'ud gadjina, tongod hulas-sangsā'na. Bang halam aniya' hinangna, halam du aniya' tongodna.",
        5: "Buwattitu isab hatulanna: bang a'a mbal angandol ma hinangna, sagō' angandol ma Tuhan ya amuwan ka'adilan ma manusiya' baldusa, in a'a inān binista abontol e' Tuhan ma sabab pangandolna.",
        6: "Buwattē' du isab bissala si Da'ud, waktu kapamissalana pasal kalasig a'a bang binista abontol e' Tuhan ma halam aniya' hinang ahāp pasangdolanna. Yukna he',",
        7: "“Aheya kahāpan ma sasuku niampun kala'atanna, maka sasuku pinapasan paldusahanna.",
        8: "Aheya kahāpan ma iya bang mbal ni'itung dusana e' Tuhan.”",
        9: "Kalu pangannalbi in kahāpan ya binissala e' si Da'ud itu pamasuku' ma saga Yahudi sadja, pagka bangsa magislam. Ngga'i ka, sabab pamasuku' isab sampay ma bangsa kasehe', ya mbal magislam. Bay na sambatku si Ibrahim dahū inān, in iya bay binista abontol e' Tuhan ma sabab pam'nnalna.",
        10: "Na, sumiyan bay kapamista Tuhan itu? Dahū min kapagislam ma si Ibrahim, atawa damuli? Kata'uwanta, si Ibrahim bay tabista abontol e' Tuhan dahū lagi' min bay kapagislam ma iya.",
        11: "Bay iya am'nnal ma janji' Tuhan dahū bo' yampa ni'islam tanda' palsaksi'an in iya bay tabista abontol e' Tuhan ma halam gi' bay ni'islam. Manjari itu si Ibrahim sali' hantang pag'mma'an a'a kamemon ya magpam'nnal ma Tuhan, sasuku tabista abontol e' Tuhan minsan halam bay makalabay pagislam.",
        12: "Pag'mma'an isab si Ibrahim ma sasuku bay magislam, ngga'i ka ma saukat na ni'islam, saguwā' ma sabab panunud sigām ma si Ibrahim, ya bay angandol ma Tuhan ma halam gi' bay ni'islam.",
        13: "Na aniya' bay janji' Tuhan ma si Ibrahim ma masa awal e', in iya maka saga panubu'na subay pinusaka'an kaluha'an dunya itu. Ya po'on si Ibrahim nijanji'an buwattē', ngga'i ka min pamogbogna ma sara' sagō' min pangandolna ma Tuhan, angkan iya binista abontol.",
        14: "Bang hal a'a amogbogan sara' ya panganjanji'an pusaka', halam du aniya' pūs pangandolta ma Tuhan. Maka janji' Tuhan inān halam aniya' kamaujuranna bang sara' ya subay binogbogan.",
        15: "Sabab hatina, in sara' itu amuwan palsababan ma mulka' Tuhan. Bang bay halam aniya' sara' halam aniya' bay makalanggal iya.",
        16: "Angkan yukta in panganjanji' Tuhan subay ajatu labay min pangandol manusiya'. Ati minnē' atayudtud, in janji'na ngga'i ka hal tungbas, saguwā' pamusaka'na ma saga panubu' si Ibrahim kamemon. Ngga'i ka sadja ma bangsa Yahudi, ya amogbogan sara' itu, saguwā' ma a'a kamemon sasuku angandol ma Tuhan buwat bay pangandol si Ibrahim. Jari pag'mma'antam si Ibrahim,",
        17: "buwat tasulat ma Kitab, ya yuk-i, “Hinangta ka pag'mma'an saga kabangsa-bangsahan kamemon.” Jari pag'mma'antam si Ibrahim bang ma bistahan Tuhan, sabab am'nnal iya ma Tuhan, in iya makapakallum a'a magpatayan maka amaniya' ai-ai bay halam aniya', min pangallamna sadja.",
        18: "Bin'nnal e' si Ibrahim janji' Tuhan, ati angagad iya ma halam aniya' niholat. Angkan iya wajib pag'mma'an e' kamemon bangsa, buwat bay panganjanji' Tuhan ma iya. Buwattitu ya tasulat ma deyom Kitab, yuk-i, “Ya heka tubu'nu buwat du heka bitu'un.”",
        19: "Ya umul si Ibrahim waktu bay kapanganjanji' Tuhan ma iya marai' na dahatus tahun, saguwā' halam apinda pangandolna minsan tapikilna baranna inān agon-agon amatay na. Sampay h'ndana si Sara, mbal na maka'anak,",
        20: "sagō' halam iya bay pahondong angandol ma Tuhan. Halam aniya' pagduwa-duwana pasal bay janji' Tuhan e', sagō' pasōng gom pa'in pangandolna maka e'na magmahaldika'an Tuhan.",
        21: "Tatantuna asal in Tuhan makaga'os du angahinang ai-ai bay panganjanji'na.",
        22: "Angkan si Ibrahim bay binista abontol e' Tuhan, ma sabab pangandolna.",
        23: "Maka ngga'i ka hal si Ibrahim bay pinagsulat inān, ya yuk-i, “binista iya abontol e' Tuhan.”",
        24: "Sampay kitam, sabab tahinang kitam abontol ma bistahan Tuhan, sasuku kitam am'nnal ma iya, ya bay amakallum Panghū'tam si Isa min kamatay.",
        25: "Bay tinukbalan si Isa pinapatay ma sabab dusatam, maka pinakallum iya pabīng e' Tuhan supaya kitam binista abontol.",
    },
    5: {
        1: "Manjari itu, pagka niampun na kitam sampay nihinang abontol ma bistahan Tuhan ma sabab pangandoltam, magkahāp na kitam maka iya, min bay tahinang e' Panghū'tam si Isa Al-Masi.",
        2: "Pinananaman kitam kaheya tabang Tuhan ma sabab pangandoltam ma si Isa, ati pataptapantam tabang itu buwattina'an. Magkōg-koyag kitam sabab aniya' holatantam in kitam pinahampitan kasahaya'an Tuhan.",
        3: "Ngga'i ka isab hal pakaradja'an sinōng ya amuwan kakōgan, sampay pakaradja'an ma buwattina'an minsan kitam ma deyom katiksa'an, sabab kata'uwantam isab, bang kalabayantam katiksa'an pasōng lagi' kasandaltam.",
        4: "Bang kitam anandal, ka'amuhan du Tuhan ma kaul-pi'iltam. Maka bang iya ka'amuhan, tantu aniya' holatantam ahāp.",
        5: "Halam aniya' pagsusunantam bang buwattē' kaholatantam, sabab itiya' 5 asal Tuhan pinat'nna' ma deyom pangatayantam, labay min Rū Sussi ya pamuwan e' Tuhan.",
        6: "Sabab hatina, ma waktu bay panugila' e' Tuhan, waktu halam aniya' ga'ostam, bay amatay Al-Masi ganti' saga a'a baldusa.",
        7: "Alahang aniya' manusiya' lilla' amatay ganti' sehe'na minsan painay ka'adilna. Kalu-kalu bang a'a ahāp to'ongan kasuddahanna, ya aniya' makatawakkal amatay ma pasalna.",
        8: "Saguwā' pina'nda'an kitam e' Tuhan bang buwattingga heya lasana ma kitam, sabab amatay Al-Masi ganti'tam, ma waktu lagi' kitam masi ma deyom karusahan.",
        9: "Na, pagka kitam abontol ma bistahan Tuhan ma sabab kamatay si Isa, manantuhi kitam lappasan e'na min mulka'na.",
        10: "Maghāp na kitam maka Tuhan sabab min kamatay Anakna, waktu lagi' kitam masi amantahan Tuhan. Na, bang kitam nihāp e' Tuhan ma sabab kamatay Anakna, palabi gi' kalappastam ma sabab kallumna pabalik.",
        11: "Maka ngga'i ka hal e'-i. Aniya' gi' isab kakōgantam aheya ma sabab bay tahinang e' si Isa Al-Masi Panghū'tam, angkan kitam maghāp na maka Tuhan.",
        12: "Na, aniya' dangan manusiya' bay makarusa, ya po'on aniya' dusa ma dunya itu. Bay iya makahinang dusa, ati minnē' aniya' kamatay ma dunya. Ya kamattihanna aniya' kamatay ma manusiya' kamemon, sabab magdusa kitam kamemon.",
        13: "Ma halam gi' aniya' sara' bay pamuwan ma si Musa e' Tuhan, aniya' asal dusa ma dunya itu. Sagō' sat'ggol halam aniya' sara' pinal'ngngan, in dusa sigām mbal kaōnan langgal sara'.",
        14: "Malaingkan in binangsa manusiya' kamemon min si Adam sampay ni si Musa bay kapagbaya'an he' kamatay. Beya' isab saga a'a ya mbal magsali' dusa sigām maka bay dusa si Adam waktu kapanagga'na panoho'an Tuhan. Si Adam itu sali' suntu'an pangā'antam panghati pasal a'a dangan ya pi'itu ni dunya ma llaw damuli.",
        15: "Sagō' atā pagbidda'an dusa si Adam maka kahāpan ya pamuwan kitam e' Tuhan. Magpatayan bangsa manusiya' ma sabab dusa a'a dakayu' inān, sagō' ballabi-labihan kahāpan Tuhan ya pangahilasna ma manusiya' labay min kasi-lasa si Isa Al-Masi, ya a'a dakayu' itu.",
        16: "Lāgi, magbidda' ya pamuwan e' Tuhan maka kamattihan dusa si Adam. Dakayu' du dusa bay tahinang e'na ati minnē' kitam kamemon katōngan dusa. Saguwā' saddī kahāpan ya pangahilas Tuhan ma manusiya' supaya sigām tabistana abontol, minsan landu' aheka paldusahan bay tahinang sigām.",
        17: "Hatina, in manusiya' kamemon kapagbaya'an na pa'in e' kamatay ma sabab dusa a'a dangan, malaingkan in kamatay itu mbal maka'atu ma kabontolan atay ya pamuwan e' Tuhan ma sasuku anaima' ase'na maka lasana. Ya kamaujuranna, sasuku makataima' kasi-lasa itu tahinang sali' sultan makapagbaya' ma dusa, sabab min a'a dakayu', ya si Isa Al-Masi.",
        18: "Ya hatulanna, dakayu' du dusa tahinang e' dangan a'a, jari hukuman Tuhan ya kamattihanna ma saga a'a kamemon. Damikiyanna, dakayu' du hinang abontol tahinang e' a'a dangan, jari kabontolan maka kallum kakkal ma a'a kamemon ya kamattihanna.",
        19: "Dakayu' du a'a bay anagga' panoho'an Tuhan, ati aheka tabowa angandusa ma sabab iya ya panunuran. Damikiyanna isab ma damuli itu, dakayu' du a'a bay ameya' ma panoho'an Tuhan, ya si Isa Al-Masi, ati aheka tahinang abontol ma bistahan Tuhan labay min si Isa he'.",
        20: "Na, pagka dusahan asal saga manusiya', aniya' sara' bay pinat'nna' e' Tuhan bo' supaya kak'nnopan kalanggal sara' sigām. Saguwā' minsan buwattingga kosog dusa manusiya', palabi lagi' lasa maka ase' Tuhan ma sigām.",
        21: "Jari in binangsa manusiya' kamemon bay kapagbaya'an asal e' dusa sigām, ati kamatay ya kamattihanna. Saguwā' kapagbaya'an na kitam e' lasa maka ase' Tuhan, ati kallum kakkal ya kamattihantam, sasuku kitam tabista abontol e' Tuhan ma sabab bay kahinangan si Isa Al-Masi Panghū'tam.",
    },
    6: {
        1: "Na, buwattingga? Pasangdantam bahā' kabaya'antam magdusa, bo' supaya pasōng lagi' ase' maka lasa Tuhan.",
        2: "Tantu mbal! Sabab kitam itu sali' hantang a'a amatay, ya mbal na makapagdusa, angkan kitam subay ang'bba min dusa.",
        3: "Sabab kata'uwanbi, bay kitam pinandi tanda' saksi' in kitam lamud na ma si Isa Al-Masi, ati minnē' aniya' lamudtam ma kamatayna.",
        4: "Hatina to'ongan, sali' kitam hantang paunung na ma Al-Masi kinubul maka iya, pagka buwattē' kapamandi ma kitam. Sali' kitam da-kamatay maka iya, bo' supaya kita kabuwanan kallum baha'u buwat bay pamakallum iya min kawasa Mma'na Tuhan.",
        5: 'Sabab hatina, bang kitam parongan amatay maka si Isa, tantu kitam magdongan maka iya pinakallum pabalik.',
        6: "Kata'uwantam isab, in kajarihantam tagna' wa'i pinapatay ma hāg magbeya' maka Al-Masi, bo' supaya pahalam kala'atantam. Jari mbal na kitam tabowa binanyaga' pabīng e' saga dusatam,",
        7: 'sabab sai-sai amatay apuwas na min hukuman dusa.',
        8: "Bang kitam bay parongan ma Al-Masi ma kamatayna, am'nnal du kitam in kitam parongan ma iya ma kallumna.",
        9: "Sabab kata'uwanta Al-Masi, in iya bay pinakallum pabīng min kamatay, angkan mbal na magkamatay pabalik. Puwas na iya min kamatay sampay ni kasaumulan.",
        10: "Min t'dda du iya bay amatay bo' supaya kapuwasanna paldusahan manusiya' kamemon. Saguwā' in kallumna buwattina'an ma okoman Tuhan na.",
        11: "Ya du ka'am, subay bistahunbi baranbi sali' hantang a'a amatay, ang'bba na min katagihanna magdusa. Allum na kam bang harap ni Tuhan, ma sabab si Isa Al-Masi ya parakayu'anbi.",
        12: "Angkan kam subay mbal kapagagihan e' dusa indaginis, bo' mbal beya'bi napsubi.",
        13: "Paggatunbi baya' ginhawa-baranbi bo' kam mbal tabowa angahinang kala'atan. Pamalilla'unbi baranbi ni Tuhan, sabab a'a kam bay pinakallum e'na pabīng min kamatay. In ginhawa-baranbi ilu subay pamasuku'bi ni iya paglagina ma kahinangan abontol.",
        14: "Da'a kam magpasagad pinagagihan e' dusabi, sabab puwas na kam min kal'ngnganan sara'. Ma gomgoman Tuhan na kam, kaniya'an ka'ase'na maka kalasana.",
        15: "Na, ai lagi'? Angandusa bahā' kitam ma sabab apinda min kal'ngnganan sara' ni ase' maka lasa Tuhan? Tantu mbal.",
        16: "Kata'uwanbi du, bang kam saupama magpatiata ni a'a dakayu', pinagbaya'an kam e'na sabab atana kam. Ati bang dusa ya pa'atahanbi, kamatay ya kamattihanna. Bang kabaya'an Tuhan ya pa'atahanbi, na, kabontolan atay ya kamattihanna.",
        17: "Angkan aheya pagsukulan ni Tuhan! Tagna', bay kam tabanyaga' e' dusa, sagō' makakale pa'in kam ma pamandu' ya pangandolanbi na, magtūy beya'bi magatay-pote'.",
        18: "Jari pinaluhaya na kam min dusa bay pamanyaga'an ka'am tagna', ati banyaga' Tuhan na kam maghinang kabontolan.",
        19: "Amaralil aku pasal banyaga' maka nakura' bo' supaya tahatibi, sabab kulang lagi' akkalbi. Ma waktu tagna' inān bay kam magparūl binanyaga' e' dusabi, ya po'on kam maghinang kasabulan maka kala'atan duhun manduhun. Saguwā' buwattina'an Tuhan ya pagbanyaga'anbi, angkan kam maghinang ai-ai abontol ya makasussi pangatayanbi.",
        20: "Sat'ggol kam sapantun banyaga' abowa-bowa e' ba'anan dusabi, mbal kam pasoho' maghinang kabontolan.",
        21: "Makaiya'-iya' ya bay kahinanganbi tagna', bang isab tapikilbi ma buwattina'an. Ai bay paluntunganna? Tantu halam, sabab kamatay ya kamattihanna.",
        22: "Sagō' ma buwattina'an tapuwas na kam e' Tuhan min dusa, ati banyaga'na na kam. Ya paluntunganbi atay asussi tudju ni iya, maka kallum kakkal ya kamattihanna.",
        23: "Tagna', bay kitam tabanyaga' e' dusa ati kamatay ya tungbasna, saguwā' kallum kakkal ya pangahilas Tuhan ma kitam bang si Isa Al-Masi Panghū'tam ya pameya'antam.",
    },
    7: {
        1: "Saga danakanku magpangandol ma si Isa, tantu kam makahati ma song pah'llingku itu sabab biyaksa du kam ma bowahan sara'. Kapagbaya'an kita e' sara'-manara' t'ggolta allum, sagō' puwas kita min sara' bang amatay na.",
        2: "Saupama d'nda taga-h'lla, wajib iya magpūn maka h'llana t'ggolna allum. Saguwā' bang h'llana amatay na, apuwas na iya min hatulan sara' pasal a'a maglakibini.",
        3: "Bang d'nda inān ganta' parakayu' ni l'lla saddī hinabu masi allum paghola'na tagna', makalanggal iya sara' sabab angaliyu-lakad. Saguwā' bang amatay h'llana ati magpūn iya maka l'lla saddī, mbal kaōnan pangaliyu-lakad sabab apuwas na iya min bowahan sara' he'.",
        4: "Buwattē' isab ma ka'am, saga dauranakanku. Apuwas na kam min sara' tasulat si Musa. Sali' kam hantang a'a magpatayan sabab dambeya'an na kam maka Al-Masi ma kamatayna. Bay iya pinakallum pabīng, manjari suku'na na kam bo' supaya kam maghinang ahāp ma Tuhan sadja.",
        5: "Ma waktu tagna', in ginhawa-baranta itu bay kapagbaya'an e' kajarihanta tagna'. Karuhunan gom pa'in napsuta pagka subay anagga' ma sara', jari kamatay ya kamattihanna.",
        6: "Sagō' buwattina'an alimaya na kita min kal'ngnganan sara' sabab hantang kita bay amatay, ati ang'bba na min dusa ya bay magbaya'an kita ma waktu tagna'. Ma buwattitu saddī na pameya'ta ma Tuhan. Ngga'i ka kal'ngnganan sara' ya beya'ta saguwā' kal'ngnganan baha'u, ya min Rū Tuhan.",
        7: "Manjari ai pamikilta pasal sara' itu? Dusahan bahā'? Tantu mbal. Atampal du, ya angkan kata'uwanku dusa maka kamattihanna, ma sabab aniya' sara' amata'u aku. Bay aku a'awam pasal napsu itu, manda' aniya' panoho'an sara' amata'u aku, ya yuk-i, “Wajib kam da'a anganapsuhan alta' pagkahibi.”",
        8: "Sagō' makata'u pa'in aku min sara' in napsu itu dusahan asal, luhūy pasōng saga dusa ma deyom ginhawa-baranku maka pak'nnop napsuku indaginis. Hatina, sat'ggol bay halam aniya' sara' mbal kinata'uwan in kitam dusahan.",
        9: "Ahāp asal palasahanku ma waktu tagna' pagka halam aniya' tata'uku pasal sara', ati pangannalku in aku a'a ahāp. Sagō' pagta'uku pa'in pasal sara' Tuhan itu, magtūy kata'uwanku aheya kasalla'anku, maka patut aku pinat'nna'an hukuman ni kamatay.",
        10: "Jari minnē' aheya kasusahanku. Sara' itu bay panganiyat Tuhan ma binangsa manusiya' supaya sigām binowa ni kallum, saguwā' ma kasulayanku, in sara' itu hal amowa aku ni kamatay sabab dusahan aku.",
        11: "Sali' aku nirupang e' dusaku sabab pangannalku in panoho'an sara' ta'anggapku du, sagō' mbal. Jari pinat'nna'an aku hukuman ni kamatay sabab min sara' itu.",
        12: "Ahāp asal sara' si Musa sabab min Tuhan du. Abontol maka ahāp panoho'anna kamemon.",
        13: "Jari taluwa' bahā' bang yukta in sara' ahāp ya amowa aku ni kamatay? Tantu mbal. In sara' ahāp itu hal pamabukisan dusaku bo' takilāku to'ongan. Dusaku ya amowa aku ni kamatay. Talhakit to'ongan in dusa itu mamarahi ala'at, ma sabab sara'.",
        14: "Kata'uwantam in sara' itu deyo' bay min Rū Tuhan. Saguwā' aku itu manusiya' sadja, tabanyaga' na pa'in e' dusaku.",
        15: "Mbal to'ongan tahatiku kaul-pi'ilku itu, sabab bang aku bilahi angahinang ahāp, sali' aniya' ma ginhawaku makabimbang. Ya balikna, bang aniya' mbal kabaya'anku nihinang, ya he' tahinangku.",
        16: "Jari bang aku ganta' ab'nsi ma hinang ala'at ya asal hinangku, angaho' du aku in sara' Tuhan ahāp du.",
        17: "Ngga'i ka itikadku to'ongan ya angahinang kala'atan ya kab'nsihanku he', tu'ud aku abowa-bowa e' dusa ya pat'nna' ma deyom kajarihanku.",
        18: "Kata'uwanku du, halam aniya' ahāp ma deyom baranku, hatina ma kajarihanku itu, sabab minsan kabaya'anku angahinang ahāp, mbal ta'anggapku.",
        19: "Mbal tahinangku kahāpan ya angutku, sagō' ya na pa'in hinangku kala'atan mbal kabaya'anku.",
        20: "Jari bang aku ganta' angahinang ai-ai ya mbal makasulut atayku, hatina ngga'i ka dī baranku ya angahinang inān, tu'ud aku tabowa-bowa e' dusa ya ma deyom kajarihanku itu.",
        21: "Buwattitu ya kal'ngngananna bang aku ganta' bilahi maghinang ahāp, maumu aku tabowa-bowa maghinang ala'at.",
        22: "Ma itikadku sadja landu' aku kasulutan ma sara' Tuhan,",
        23: "saguwā' pag'nda'ku pa'in ni deyom ginhawa-baranku, saddī isab kal'ngngananna. Sabab aniya' na pa'in la'at ma deyom kajarihanku magsagga' maka sara' Tuhan ya makasulutan aku. Minnē' aku binanyaga', pinagagihan na pa'in e' dusa ya amowa na pa'in ma deyom ginhawa-baranku.",
        24: "Allā! Mbal manjari susaku! Sai bahā' anabang aku supaya aku makapuwas min kajarihan ala'at itu, sabab itiya' aku binowa ni kamatay?",
        25: "Magsukul ni Tuhan, itiya' anabang si Isa Al-Masi Panghū'tam! Na ya du ilu kasusahanku: makaisbat aku sara' Tuhan ma deyom pikilanku, sagō' abowa-bowa aku magdusa pagga kapagbaya'an kajarihanku e' dusa.",
    },
    8: {
        1: "Malaingkan buwattina'an, pagka kitam sōd si Isa Al-Masi na, mbal na kapat'nna'an hukuman Tuhan.",
        2: "Apuwas na kitam min kal'ngnganan dusa maka min kamatay ya kamattihanna, sabab ameya' na kitam ma kal'ngnganan Rū Tuhan. Tabowa kitam ni kallum pagka si Isa Al-Masi ya parakayu'antam.",
        3: "Halam aniya' ga'osan sara' pamapuwas kitam min pagbaya'an dusa, sabab manusiya' sadja kitam mbal makabogbogan sara'. Sagō' Tuhan ya makaga'os. Pinapi'itu e'na Anakna lissi pamapuwas ba'anan dusatam. Daisi iya maka kitam, ati iya ya katōngan dusa ganti' min kitam.",
        4: "Buwattē' hinang Tuhan supaya tatuman kamemon ya tasulat ma panoho'an-sara' sabu pa'in kitam ang'bba min napsutam bo' ameya' ma kabaya'an Rū Sussi.",
        5: "Sai-sai angandūl ma napsu baranna kapagbaya'an du e' napsu. Sai-sai ameya' ma kabaya'an Rū Sussi, kapagbaya'an du e' Rū Sussi.",
        6: "Bang a'a abowa-bowa pikilanna e' napsu baranna, kamatay ya kamattihanna, sagō' bang kapagbaya'an pikilanna e' Rū Sussi, kallum kakkal ya kamattihanna maka kasannangan deyom atay.",
        7: "Manjari bang a'a abowa-bowa e' napsuna, sagga'na Tuhan pagga mbal magmaluluy ma panoho'anna. Maka minsan iya bilahi ameya', mbal to'ongan ta'anggapna.",
        8: "Bang a'a abowa-bowa e' napsuna, mbal tasulutna Tuhan.",
        9: "Malaingkan ka'am ilu mbal na abowa-bowa e' napsubi buwat bay kajarihanbi tagna', saguwā' Rū Tuhan ya pameya'anbi na ma ai-ai kabaya'anna, pagka ilu na iya pat'nna' ma deyom ataybi. Sai-sai halam kaniya'an Rū Tuhan e' Al-Masi, ngga'i ka iya suku' Al-Masi.",
        10: "Magkamatay baranbi sabab dusa, sagō' minsan na, kabuwanan du kam kallum taptap min Rū Sussi bang ilu Al-Masi ma deyom ataybi, sabab tabista kam abontol e' Tuhan.",
        11: "Bang pat'nna' ma ka'am Rū Tuhan, tantu kam pinakallum e' Tuhan buwat bay pamakallumna Al-Masi min kamatayna.",
        12: "Angkan yukku ma ka'am, saga dauranakanku, aniya' subay pagmatayantam saddī min kajarihan maka kanapsuhantam tagna'.",
        13: "Sabab bang kitam ganta' abowa-bowa na pa'in, e' kajarihantam dusahan, kamatay ya kamattihanna. Saguwā' bang paglagitam tabang min Rū Tuhan bo' bbahantam hinangtam ala'at, taptap du kallumtam.",
        14: "Panganak Tuhan sasuku minaliman e' Rū Tuhan.",
        15: "Sabab ngga'i ka umagad makatāw-tāw ya tasambuttam, sagō' Rū Sussi ya angahinang kitam panganak Tuhan. Kawasa min iya isab, ya angkan kitam makatawakkal angōn ‘Mma'’ ma Tuhan.",
        16: "Aniya' saksi' ma deyom palnyawahantam bay min Rū Sussi, angkan kitam makatantu in kitam tantu anak Tuhan.",
        17: "Na, pagka kitam panganak Tuhan sab'nnal-b'nnal, pinahampitan kitam pusaka' ma llaw damuli. Magdakayu' kitam maka Al-Masi pinasambutan pusaka' itu, sabab bang kitam palamud ma kabinasahanna ma buwattina'an, palamud isab kitam ma kasahaya'anna bang ta'abut waktuna.",
        18: "Bang ma aku, mbal angatu kasigpitan ya kalabayantam buwattina'an ma kasahaya'an ya pinabukisan kitam ma sinosōng.",
        19: "Angagad ai-ai pinapanjari kamemon ma waktu kapamabukis e' Tuhan saga panganakna.",
        20: "Sabab kamemon bay pinapanjari e' Tuhan kalungayan pūsna, ngga'i ka min kabaya'an ai-ai pinapanjari itu, saguwā' min kahandak Tuhan. Sabab aniya' niholat,",
        21: "hatina ma sinosōng in bay pinapanjari kamemon pinalimaya du min kasigpitan ya kalabayanna ma buwattina'an, pagka magka'ndang du maka magkamatay du kamemon. Saguwā' ma sinosōng magdakayu' du bay pinapanjari kamemon itu maka panganak Tuhan, bang sigām pinabangsa sampay pinalimaya na min kasigpitan kamatay.",
        22: "Kata'uwanta, in kamemon pinapanjari itu magsalinggā asal sampay ni kabuwattina'an, buwat hantang d'nda kap'ddi'an bang song anganak.",
        23: "Maka ngga'i ka hal ina'an-i, sampay kitam ya kabuwanan Rū Sussi e' Tuhan pangawalna, magsalinggā du isab sat'ggoltam angalagaran waktu pamabaha'u barantam. Bang ta'abut waktu ina'an pinatampal in kitam panganak Tuhan.",
        24: "Ya na he' holatantam pagka lappasan na kitam min hukuman dusa. Halam gi' mattan, angkan niōnan ‘holat’. Mbal kaōnan holat bang magmattan na.",
        25: "Saguwā' aniya' holatantam tantu minsan mbal gi' magmattan, ya angkan kitam mbal sinumu angagad.",
        26: "Pagapi' du Rū Sussi anabangan kitam bang mbal makakole'. Maumu kitam mbal ata'u bang buwattingga subay pangamu'-ngamu'tam ni Tuhan, sagō' Rū Sussi ya anibahat ma sababtam, bo' arapun mbal tapagsuli-suli sibahatna.",
        27: "Tatanding deyom pamikiltam e' Tuhan maka kasakupanna isab bang ai kinannal e' Rū Sussi, sabab palamud Rū Sussi itu angamu'an kitam suku' Tuhan kahāpan, ma buwat kahandak Tuhan.",
        28: "Ya ko' itu kata'uwantam: nihinangan kitam kahāpan e' Tuhan ma deyom pakaradja'an indaginis ahāp-ala'at, pagka kitam alasa ma iya. Jari minsan buwattingga pakaradja'an ya kalabayantam, ahāp sadja kaluwasanna.",
        29: "Bay kitam tapene' e' Tuhan min awal lagi', ginanta' kitam subay anunud ma Anakna supaya iya pagsiyakahan ma dauranakanna manusiya' kamemon.",
        30: "Sasuku bay ginanta' e' Tuhan anunud ma Anakna, pinene' isab e'na, maka sasuku ya pinene' binista e'na abontol. Sasuku isab abontol ma bistahanna binahagi'an du min deyom sahayana.",
        31: "Na, bang pikiltam bay pah'llingku-i, sali' halam aniya' sugpatna. Sabab bang Tuhan ya amogbogan kitam, mbal kitam takole' e' sai-na.",
        32: "Halam bay ka'lloganna Anakna lissi, sagō' sinōngan e'na pinapatay ma pasalantam kamemon. Bang buwattē' kalasa Tuhan anukbalan Anakna, tantu kitam binuwanan e'na ai-ai makahāp, luwas min kahilasanna.",
        33: "Halam aniya' makatuna'an kitam ya pinene' e' Tuhan, sabab Tuhan ya amabontol itikadtam.",
        34: "Angkanna halam aniya' amat'nna'an kitam kasā'an pinehē' ni deyom nalka'. Bay amatay si Isa Al-Masi ma sabab dusatam, ati pinakallum pabīng e' Tuhan. Pinabangsa na iya ma buwattitu, pinatingkō' ma bihing Tuhan tampal ni kowan, ati ina'an na iya magpatillot ma manusiya' maka Tuhan, angamu'an kitam tabang.",
        35: "Manjari sai bahā' amapagbutas kitam maka lasa Al-Masi? Tantu halam aniya'. Minsan ai kalabayantam, ai na kasusahan, ai na ka katiksa'an, ai na ka pagpuhinga' a'a, kasigpitan ka atawa kamiskinan, minsan ma deyom kapiligduhan, minsan kita pinapatay, tantu mbal apinda lasa Al-Masi ma kitam.",
        36: "Saga kabinasahan inān tasulat asal ma deyom Kitab, ya yuk-i, “Kasiya-siyahan kami sakahaba' llaw, hal angagad pinapatay ma sabab ka'a ya pameya'an. Sali' kami hantang hayop bili-bili ma pamista saga a'a, hal binowa sinumbali'.”",
        37: "Saguwā' mbal tapamagaytam saga pakaradja'an itu. Anganda'ug du kitam to'ongan ma sabab Al-Masi, ya alasa asal ma kitam.",
        38: "Makatantu du aku, halam aniya' makaga'os amapagbutas kitam maka lasa Al-Masi, minsan ma kallumta maka ma kamatayta. Minsan bangsa mala'ikat atawa bangsa mananasat, minsan ai kalabayantam ma masa itu maka ma masa sinōng, tantu kitam kinalasahan na pa'in.",
        39: "Minsan ma diyata' maka minsan ma deyo', halam aniya' min bay pinapanjari kamemon makaga'os amapagbutas kitam maka lasa Tuhan, ya bay pina'nda'an ni kitam e' si Isa Al-Masi Panghū'tam.",
    },
    9: {
        1: "B'nnal ya pah'llingku itu ma ka'am: mbal aku magputing sabab suku' Al-Masi aku. Anubali aku sab'nnal-b'nnal min atay pote', sabab kapagbaya'an aku e' Rū Sussi.",
        2: "Makalandu' heya dukkaku. Kasangdanan sukkalku ma pasal pagkahiku bangsa Yahudi. Bang bay makajari, lilla' aku taluwa' mulka' Tuhan sampay pinaokat min Al-Masi, bang pa'in sigām angandol ma iya.",
        3: "Makalandu' heya dukkaku. Kasangdanan sukkalku ma pasal pagkahiku bangsa Yahudi. Bang bay makajari, lilla' aku taluwa' mulka' Tuhan sampay pinaokat min Al-Masi, bang pa'in sigām angandol ma iya.",
        4: "Panubu' si Isra'il asal sigām, bangsa suku' Tuhan. Bay sigām nihinang panganakna, maka pina'nda'an sahayana ma deyoman sigām. Aniya' kapagsulutan sigām maka Tuhan, maka kabuwanan sigām sara'na. Ma sigām ya hatulan pagta'at b'nnal maka panganjanji' Tuhan.",
        5: "Tubu' asal sigām min saga pangkat Yahudi babantugun. Minnē' du isab Al-Masi bang harap ni pangkat manusiya'. Tuhan ya magbaya' ma kamemon, patut sinanglitan salama-lama. Amin.",
        6: "Mbal isab yukku in janji' Tuhan ma bangsa Isra'il halam aniya' pūsna. Sagō' ya yukku, aniya' tubu' si Isra'il kasehe' mbal manjari niōnan bangsa suku' Tuhan.",
        7: "Aniya' isab tubu' si Ibrahim mbal kaōnan panganak Tuhan. Ya tubu' si Ibrahim sab'nnal-b'nnal subay binista ma buwat bay pangallam Tuhan ma iya, ya yuk-i, “Ya panubu'nu to'ongan subay min anaknu dangan ilu, min si Isa'ak.”",
        8: "Bang pina'amu, aniya' panubu' si Ibrahim mbal kaōnan panganak Tuhan.",
        9: "Buwattitu bay panganjanji' Tuhan ma si Ibrahim, yukna, “Bang ta'abut waktuna, pabalik du aku pi'ilu ati maka'anak l'lla h'ndanu si Sara.”",
        10: "Ngga'i ka hal si Ibrahim ya pagsambatku. Pikilunbi isab duwangan anak si Ripka. Da'mma' sigām, si Isa'ak ya pag'mma'an bangsa Yahudi.",
        11: "Jari ma halam gi' palahil onde' inān, amissala Tuhan ni si Ripka, yukna, “Ya k'mbal siyaka ilu pinagagihan du e' siyali.” Minnē' kinata'uwan in kapamene' Tuhan min baya'na asal, ngga'i ka min kahinangan manusiya' ahāp-ala'at. Sabab k'mbal inān halam gi' bay makahinang ai-ai ahāp ka atawa ala'at, sabab masi ma deyom kandang. Manjari bang Tuhan ya amene', subay min palniyatanna.",
        12: "Jari ma halam gi' palahil onde' inān, amissala Tuhan ni si Ripka, yukna, “Ya k'mbal siyaka ilu pinagagihan du e' siyali.” Minnē' kinata'uwan in kapamene' Tuhan min baya'na asal, ngga'i ka min kahinangan manusiya' ahāp-ala'at. Sabab k'mbal inān halam gi' bay makahinang ai-ai ahāp ka atawa ala'at, sabab masi ma deyom kandang. Manjari bang Tuhan ya amene', subay min palniyatanna.",
        13: "Buwat du bay tasulat ma deyom Kitab pasal k'mbal itu, ya yuk-i, “Si Yakub kalasahanku, si Esaw ya kab'nsihanku.”",
        14: "Jari ai na pamikilta pasal kissa ina'an? Sowayta bahā' Tuhan in pamene'na mbal abontol? Tantu mbal,",
        15: "sabab Tuhan ya magkahandak, buwat yukna ma si Musa, “Ma'ase' aku ma sai-sai kabaya'anku, alasa aku ma sai-sai kabaya'anku.”",
        16: "Na minnē' tahatita, ngga'i ka min kabaya'anta manusiya' atawa min hulas-sangsā'ta maghinang ahāp ya angkan kita kina'ase'an e' Tuhan, sagō' min baya'na du.",
        17: "Aniya' isab bay tasulat ma deyom Kitab pasal pamissala Tuhan ni sultan ma lahat Misil ma masa awal e'. Yuk-i, “Aniya' kagunahanku ma ka'a, ya angkan ka g'llalku magsultan. Bay paluwasku kawasaku panganda'ug ka'a, bo' supaya abantug ōnku ma kaluha'an dunya.”",
        18: "Jari itu manyatakan du, ma'ase' Tuhan ma sasuku kabaya'anna. Maka sasuku kabaya'anna subay atuwas kōkna, patuwasna du.",
        19: "Kalu aniya' dakayu' min ka'am anganjawab, yuk-i, “Bang buwattē', bang hati' min kabaya'an Tuhan ya angkan a'a anuwas, angay iya subay sinoway e' Tuhan? Sabab halam aniya' makasagga' kabaya'an Tuhan.”",
        20: "Atawakkal pahāp ka anganjawab buwattilu! Manusiya' du ka, ati samlangnu Tuhan! Bang saupama kibut, aniya' bahā' anamlang a'a bay angahinang iya, yukna, “Angay aku hinangnu buwattitu?”",
        21: "Kata'uwanta, ya a'a angahinang kibut itu taga-kapatut du ma tana' inān angahinang ai-ai kabaya'anna. Daginis du tana', sagō' dabahagi'na nihinang kibut pangisihan llaw-llaw, maka dabahagi'na isab nihinang pagguna ahalga'.",
        22: "Buwattē' du isab ma Tuhan, taga-kapatut iya maghinang ai-ai kabaya'anna. Bilahi iya amatuwa' ka'astolna ma manusiya' baldusa bo' ta'nda' kaheya kawasana, daipara ni'imanan e'na saga a'a ka'astolanna minsan sigām patut pinataluwa'an mulka'.",
        23: "Angkan saga manusiya' itu ni'imanan e' Tuhan sabab kabaya'anna subay tata'u e' a'a kamemon pasal kahāpna ma saga a'a ka'ase'anna, ya sakapna supaya pinabangsa ma sinosōng.",
        24: "Kitam ko' inān, a'a pinene' e' Tuhan min bangsa Yahudi, sampay isab min saga bangsa kamemon.",
        25: "Buwattitu pamissala Tuhan bay tasulat e' nabi Hoseya, yuk-i, “Saga a'a ngga'i ka bay a'aku tagna', ōnanku a'a suku'ku buwattina'an. Ya bangsa halam bay kalasahanku, ōnanku na bangsa kalasahanku.”",
        26: "Maka itu gi': “Mahē' ma lahat bay pamah'llinganku sigām in sigām ngga'i ka suku'ku, mahē' du isab sigām ōnanku panganak Tuhan, ya Tuhan kakkal salama-lama.”",
        27: "Buwattitu isab ya tasulat e' nabi Isaya ma pasal bangsa Isra'il, yuk-i, “In bangsa Isra'il itu, minsan heka sigām sali' solagan gusung ma bihing tampe, akulang sigām makapuwas min mulka' Tuhan.",
        28: "Sabab pinuspusan e' Tuhan hukumanna ni dunya, mbal katangguhan.”",
        29: "Buwat bay pangallam si Isaya isab ma masa awal, ya yuk-i, “Bang kitam halam bay kinapinan tubu' e' Tuhan Sangat Kawasa, bay du kitam alaglag kamemon, buwat a'a min kauman Sodom maka kauman Gomora.”",
        30: "Manjari ai yukta pasal bay sambatanku baha'u si'? Ya itu: saga a'a ngga'i ka Yahudi, ya halam bay angangut ma kabontolan atay, angandol na ma Al-Masi jari abontol na sigām ma pang'nda' Tuhan.",
        31: "Saguwā' saga bangsa Isra'il, ya bay amanuyu'an sara' si Musa pangā'an sigām kabontolan atay, halam tabista abontol e' Tuhan.",
        32: "Angay bahā'? Sabab hinang baran sigām ya pasangdolan sigām, ngga'i ka pangandol ni Tuhan. Sapantun sigām a'a makarugtul ni ‘batu parugtulan’,",
        33: "buwat tasulat ma deyom Kitab, ya yuk-i, “Aniya' batu bay pat'nna'ku ma da'ira Siyun, batu parugtulan a'a, batu pamah'bba'an. Saguwā' sasuku angandol ma iya, halam to'ongan aniya' kapagsusunanna.”",
    },
    10: {
        1: "Saga dauranakanku bebeya'an si Isa, ya pagmatayanku to'ongan pagkahiku bangsa Yahudi, bang pa'in sigām lappasan bo' makasōd ni deyom sulga'. Ya ko' ina'an pangamu'-ngamu'ku ni Tuhan.",
        2: "Makasaksi' aku ma pasal katuyu' sigām ma Tuhan, sagō' halam tahati e' sigām bang ai kataluwa'anna.",
        3: "Halam tahati sigām bang buwattingga e' Tuhan angampun dusa, maka e'na amuwan kabontolan ma manusiya'. Angusul sigām ma agama sigām, ati mbal anambut kabontolan ya pamat'nna' Tuhan ma sigām.",
        4: "Ya sara' bay tasulat e' si Musa taga-katumanan na pagka makapi'itu na Al-Masi, manjari sai-sai angandol ma iya niōnan abontol e' Tuhan.",
        5: "Aniya' isab tasulat e' si Musa pasalan a'a amogbogan sara' supaya binista abontol e' Tuhan. Yuk sulat e', “Sai-sai angahinang panoho'an sara' itu, aniya' kallumna kakkal.”",
        6: "Aniya' sulat dakayu' pasal kabontolan atay ya pinaniya'an sasuku angandol, yuk-i, “Da'a kam atilaw-tilaw ma deyom ataybi bang sai patukad pariyata' ni sulga'.” (Hatina sai amareyo' Al-Masi minnē'.)",
        7: "“Da'a isab kam atilaw bang sai pareyo' ni deyom ahirat.” (Hatina sai amowa Al-Masi pariyata' min lahat kamatayan.)",
        8: "Kira-kirahunbi ayat Kitab dakayu', ya yuk-i, “Ilu na lapal Tuhan ma ka'am. Ilu ma deyom bowa'bi. Ilu isab ma deyom ataybi.” Hatina ilu na ma ka'am lapal bay nasihat kami pasal pangandol ma si Isa Al-Masi.",
        9: "Bang kam magpasab'nnal in si Isa Panghū'bi maka magkahagad to'ongan min deyom ataybi in iya bay pinakallum min kamatay e' Tuhan, tantu kam lappasan bo' pasōd ni deyom sulga'.",
        10: "Sabab min pagkahagadtam ma si Isa ya angkan kitam binista abontol e' Tuhan, ati bang kitam angahaka sab'nnal ni a'a kasehe'an pasal pagkahagadtam, minnē' kitam lappasan.",
        11: "Yuk sulat Kitab isab, “Sai-sai magkahagad ma iya halam aniya' pagsusunanna sapupud-daya.”",
        12: "Talapay manusiya' kamemon pinagbissala ma ayat Kitab itu, sabab mbal magbidda' Yahudi maka ngga'i ka Yahudi. Dakayu' du Tuhan ya pameya'an e' sigām kamemon, maka aheya kahāpan pamuwanna ma sasuku parahing ni iya.",
        13: "Buwat tasulat ma deyom Kitab, ya yuk-i, “Sai-sai parahing ni Panghū', tantu lappasan.”",
        14: "Buwattingga e' sigām parahing ni Panghū' bang halam gi' makapam'nnal ma iya? Maka buwattingga e' sigām am'nnal bang halam gi' bay makakale lapal ahāp? Buwattingga isab e' sigām akale lapal ahāp bang halam aniya' magnasihatan sigām?",
        15: "Maka buwattingga isab e' a'a magnasihat bang halam aniya' bay anoho' iya magnasihat? Sagō' aniya' bay sinoho', buwat tasulat ma deyom Kitab, ya yuk-i, “Kahāp du pa'in bang aniya' amowahan kita lapal ahāp!”",
        16: "Saguwā' ngga'i ka a'a kamemon bay akale lapal ahāp itu, buwat na bay pamūng si Isaya inān, ya yuk-i, “O Tuhan, kulang du a'a magkahagad ma panglapal kami.”",
        17: "Manjari lapal pasal Al-Masi subay pinagnasihat dahū bo' yampa takale e' a'a, ati minnē' aniya' pagkahagad sigām.",
        18: "Amikilan aku pasal bangsa Isra'il. Kalu baha' halam takale sigām lapal ahāp pasal si Isa Al-Masi? Sagō' tantu takale sabab atanyag lapal itu, buwat tasulat ma deyom Kitab, yukna, “Patanyag pamandu' sigām ni kamemon bangsa, pasampay bissala sigām ni mpat pidju alam.”",
        19: "Amikilan lagi' aku, kalu halam tahati e' bangsa Isra'il pasal lapal itu. Sagō' tahati du. Si Musa ya makarahū anambung, yukna, “Pagalakta kam ni bangsa kasehe', ya yukbi halam aniya' gunana. Pap'ddi'ku ataybi tudju ni bangsa dakayu', ya pangannalbi mbal makata'uwan aku.”",
        20: "Atampal du pangallam Tuhan ya tasulat e' si Isaya, yuk-i, “Tabāk aku e' saga a'a bay halam amiha aku. Panyata' aku ni saga a'a halam bay atilaw ma pasalanku.”",
        21: "Saguwā' buwattitu ya pamissala Tuhan ma pasal bangsa Isra'il, yukna, “Kahaba' llaw bilahi aku anaima' saga a'a anagga' aku, ya anagga' na pa'in ma kabaya'anku.”",
    },
    11: {
        1: "Manjari angannal-ngannal lagi' aku: “Tinimanan bahā' e' Tuhan bangsa dakayu'-kayu' ya palsuku'anna?” Tantu mbal. Bangsaku ko' inān sabab bangsa Isra'il aku, tubu' si Ibrahim, min panubu' si Benjamin.",
        2: "Halam katimanan e' Tuhan bangsa ya bay tapene'na sangay min awal tagna'. Kata'uwanbi ya tasulat ma deyom Kitab, waktu kapanutul si Elija ni Tuhan pasal bangsa Isra'il. Yuk si Elija e',",
        3: "“O Tuhan, pinapatay e' sigām saga nabi sosoho'annu. Nilubu e' sigām pagkukulbanan kami ni ka'a. Hal aku la'a takapin min ba'anan nabi, ati piniha aku e' sigām bo' pinapatay.”",
        4: "Entomunbi bay panambung Tuhan ma panutul si Elija e', yuk-i, “Aniya' gi' pitu' ngibu a'a bay kapinanku, a'a halam bay makasumba ni ta'u-ta'u Ba'al.”",
        5: "Damikiyanna ma buwattina'an, aniya' gi' takapin bangsa Isra'il halam pataikut min Tuhan, a'a isab tapene'na min lasana maka min ka'ase'na ma sigām.",
        6: "Bang kasi-lasa Tuhan ya sababanna angkan iya amene' a'a, tantu ngga'i ka kahinangan manusiya' ya makasabab. Sagō' bang Tuhan bay amene' a'a ma saukat na ahāp hinangna, sali' halam aniya' pūs ma ase' maka lasa Tuhan e'.",
        7: "Jari ai lagi'? Halam tabāk e' bangsa Isra'il ya pagmatayan sigām. Luwal a'a pinene' e' Tuhan ya makabāk. Bay pinatuwas kōk saga a'a kasehe'an,",
        8: "buwat tasulat ma kitab, ya yuk-i, “Pinabongog e' Tuhan pamikil sigām, ya po'on mbal makahati. Aniya' mata sigām sagō' mbal maka'nda', Aniya' tainga sigām sagō' mbal makakale.”",
        9: "Aniya' isab bay pamissala si Da'ud, yukna, “Bang pa'in sigām nijallat e' paglami sigām, Bang pa'in sigām palukbu' sampay ah'bba', panungbas kala'atan sigām.",
        10: "Bang pa'in palendom pang'nda' sigām bo' mbal maka'nda', bang pa'in parukkug bukut sigām sampay ni kasaumulan.”",
        11: "Amikilan lagi' aku pasal bangsa Isra'il itu. Ya kah'bba' sigām inān, anatas bahā' sampay ni kasaumulan? Tantu mbal. Sabab buwattitu ya pinagmohotan e' Tuhan: saga bangsa ngga'i ka Isra'il pas'lle' na lappasan min hukuman dusa ma sabab karusahan bangsa Isra'il. Minnē' isab in bangsa Isra'il tabowa angihid pagka tinaikutan.",
        12: "Kira-kirahunbi, bang kaniya'an kahāpan saga a'a ngga'i ka Isra'il ma sabab karusahan bangsa Isra'il, maka ma sabab kapanaikut Tuhan ma sigām, luhūy paheya kahāpan ma palbangsa-bangsahan kamemon bang jukup na saga a'a Isra'il magpangahagad.",
        13: "Aniya' pamissalaku ma ka'am ya ngga'i ka Yahudi. Kawakilan aku e' Tuhan magnasihat ma buwat ka'am. Paheyaku isāb pagnasihatku itu ma atay,",
        14: "bang pa'in pinaihid pagkahiku Yahudi bo' supaya aniya' sigām lappasan min mulka'.",
        15: "Sabab bang maghāp na Tuhan maka saga palbangsa-bangsahan ma sabab kataikut Tuhan ma bangsa Isra'il, ai kaluwasanna bang sigām tinaima' e' Tuhan pabīng? Lumandu'an ahāp. Sali' sigām a'a pinakallum pabīng min kamatay.",
        16: "Buwat tinapay bang ma pangaddat Yahudi. Niakup dangkuri' min addunan bay panukbal ni Tuhan, paltanda'an in tinapay inān kamemon palsuku'an Tuhan du. Atawa po'on kayu, panukbal gamutna ni Tuhan, jari palsuku'anna katibu'ukan kayu inān sampay ni sangana.",
        17: "Na, magparalilan aku: bang aniya' sanga sinagpe' min po'on kayu ni'ipat, bo' aniya' sanga kayu talun pinabatuk ni bay panagpe'an sanga tagna', jari kabahagi'an kajatuhan min kayu ni'ipat saga magdalos na maka gamutna.",
        18: "Sagō' da'a pagabbu-abbuhinbi, sabab ka'am ilu hal sanga, maka ngga'i ka sanga ya amuwan kallum ma gamut. Gamut ya amuwan kallum ma sanga.",
        19: "Kalu yukbi, “B'nnal ko' ilu, saguwā' sinagpe' sigām e' Tuhan supaya kami kapabatukan.”",
        20: "Aho', b'nnal. Sagō' ya po'on sigām bangsa Isra'il sinagpe' sabab agagga am'nnal ma Tuhan, ati ka'am ya pinabatuk ni po'on kayu ma sabab kapam'nnalbi. Sagō' da'a pagmalangkahianbi ina'an-i. Gom pa'in kam magmatāw, ya aniya' kam sinagpe' buwat bay sigām.",
        21: "Sabab hatina, bang mbal allog Tuhan ma saga sanga porol, ya du ka'am mbal ka'lloganna.",
        22: "Kira-kirahunbi ka'ase' Tuhan maka kab'ngngisna. Kab'ngngisanna saga a'a ya pataikut min iya, saguwā' ka'ase'anna kam bang pa'in pataptap ma kahāpna, mbal magla'an-la'an. Bang kam ganta' pataikut min pangandolbi, ya du ka'am sinagpe' du buwat ibarat sanga kayu.",
        23: "Ya balikna, pinabatuk bangsa Isra'il ni bay bai sigām, bang sigām ganta' pahali anulak Al-Masi. Sabab halam aniya' ahunit ma Tuhan.",
        24: "Ya hantang hatulanna, bang ka'am bay niā' min kayu jaitun talun bo' pinabatuk ni kayu ni'ipat, labi aluhay bang bangsa Isra'il pinabīng ni kayu bay panagpe'an sigām tagna', sabab ya na po'onan sigām.",
        25: "Saga dauranakanku, aniya' bay pamata'u aku e' Tuhan ma pasal bangsa Isra'il itu. Bilahi aku amahatian ka'am supaya kam mbal amikil di-bi in ka'am ahāp min sigām. Buwattitu: in bangsa Isra'il itu bay agagga am'nnal ma si Isa Al-Masi, saguwā' mbal anatas kagagga sigām. Bang ajukup na kaheka'an a'a min bangsa saddī ameya' ma Tuhan, ameya' isab bangsa Isra'il.",
        26: "Manjari lappasan isab bangsa Isra'il kamemon, buwat bay sinulat ma deyom Kitab, ya yuk-i, “Pi'itu min lahat Siyun ya Manglalappas. Pahalamna saga la'at bay tahinang e' panubu' si Yakub.",
        27: "Makapi'ilu pa'in aku, la'ananku dusa sigām kamemon, buwat bay asal tajanji'ku ma sigām.”",
        28: "In bangsa Isra'il itu bay banta Tuhan sabab tasulak e' sigām lapal ahāp pasal si Isa Al-Masi, sagō' in kahāpan bay ma sigām tagna' papelleng na ni bangsa saddī. Saguwā' mbal du taptap kapanagga' sigām, sabab nientom e' Tuhan bay kapamene'na ma ka'mbo'-mbo'an sigām, angkan sigām kinalasahan na pa'in.",
        29: "Sabab Tuhan, bang aniya' a'a bay pinene' e'na sampay lidjiki'anna, mbal to'ongan apinda niyatna.",
        30: "Ka'am ngga'i ka Yahudi ilu, bay kam anulang kabaya'an Tuhan ma waktu palabay inān, manda' kina'ase'an kam e'na buwattina'an ma sabab kapanulang bangsa Yahudi.",
        31: "Ya du isab bangsa Yahudi, tasulang e' sigām kabaya'an Tuhan buwattina'an, sagō' kina'ase'an sigām e' Tuhan buwat ka'ase'na ma ka'am.",
        32: "Min kahandak Tuhan angkan in kamemon bangsa manusiya' tahinang sali' sapantun pilisu mbal makalimaya min kapanulang sigām, bo' supaya in sigām kamemon pinat'kkahan ase'na.",
        33: "Mbal tapula'-pula' kahāp Tuhan, ka'ase'na, pangita'una maka panahu'anna. Halam aniya' min kitam makahati ma kagara'anna maka ma kahinanganna.",
        34: "Buwat yukna ma deyom Kitab, “Sai makata'u panahuan Tuhan? Sai makapituwahan iya?",
        35: 'Sai bay makabuwanan Tuhan ai-ai, atawa bay makapautang ma iya?”',
        36: "Min Tuhan asal ai-ai kamemon. Iya ya bay amaniya' kamemon maka iya isab sababanna angkan paniya' ba'anan ai-ai kamemon. Sanglitanta iya ni kasaumulan. Amin.",
    },
    12: {
        1: "Saga dauranakanku, landu' kitam kina'ase'an e' Tuhan, angkan buwattitu junjungku ma ka'am: pamasuku'unbi baranbi ni Tuhan, panukbalunbi ni iya t'ggolbi allum. Ai-ai hinangbi subay ma iya sadja, maka subay makasulut atayna. Bang buwattē' ajatu du pa'in pagta'atbi ma Tuhan.",
        2: "Da'a panunurinbi kajarihan ya maumu panunuran ma ahil jaman itu, sagō' parūlunbi Tuhan amabaha'u deyom panahu'anbi bo' supaya pinindahan e'na addat-tabi'atbi kamemon. Bang buwattē' kasakupanbi du bang ai kahandak Tuhan, kahāpna maka kasampulna'anna, ati kata'uwanbi bang ai makasulut iya.",
        3: "Bay aku kinahāpan e' Tuhan, binuwanan kapatut magnasihat, angkan yukku ma ka'am kamemon, da'a kam maglaku-laku in ka'am alanga min bay pamat'nna' ka'am. Subay kam amikilan di-bi pahāp-hāp. Bistahunbi to'ongan bang ai bay pamatulun Tuhan ma ka'am kaniya-kaniya, sabab min pangandolbi.",
        4: "Dalilunbi baran manusiya'. Baranta itu dakayu' du, bo' magginis pagdayawna. Magbidda' isab hinang pagdayaw dakayu' maka dakayu'.",
        5: "Buwattē' isab ma kitam magpangandol ma si Isa. Minsan kitam aheka, sapantun kitam dakayu' baran atibu'uk pagka suku' kitam Al-Masi. Magsugpat kitam dangan maka dangan minsan magbidda' kahinangantam, buwat pagdayaw baran.",
        6: "Kabuwanan kitam kapandayan ginisan ma sabab lasa Tuhan, saddī ma dangan maka ma dangan. Maka kapandayan itu subay ginuna pahāp-hāp, pinapagtongod maka pangandoltam. Bang a'a kabuwanan kapandayan magpaluwas bissala deyo' min Tuhan, subay paluwasna to'ongan.",
        7: "Bang a'a kabuwanan kapandayan anabangan pagkahina, subay tabanganna to'ongan. Bang kapandayan magpandu', subay amandu' to'ongan.",
        8: "Bang kapandayan amalasig atay kasehe', subay amalasig to'ongan. Bang a'a anulung ma sukkal kasehe', subay hilas panulungna. Bang a'a binuwanan kapatut magnakura', subay atukid e'na magpal'ngngan ai-ai. Bang a'a binuwanan kapandayan angayura a'a kasigpitan, subay iya magkalasigan angayura.",
        9: "Ya lasabi ma sehe'bi subay min deyom atay. Kab'nsihinbi ai-ai ala'at, balutinbi ai-ai ahāp.",
        10: "Subay kam maglasa-liyasahi to'ongan sabab magdanakan kam ma deyoman si Isa Al-Masi. Magaddat-iyaddati kam min deyom atay.",
        11: "Subay kam mbal lisu'an sabab Panghū' Isa ya paghinanganbi. Subay kam atukid sadja ma ai-ai pamahinang ka'am.",
        12: "Subay kam magkakōgan ma pangaholatbi ma Tuhan. Bang kam taluwa' sukkal sandalinbi sadja, maka da'a kam pahali angamu'-ngamu' ni iya.",
        13: "Buwaninbi pagkahibi suku' Tuhan bang kasigpitan, pa'iddahunbi isab sasuku pahapit ni luma'bi.",
        14: "Bang aniya' angala'at ka'am, amu'inbi sigām kahāpan ni Tuhan. Da'a balosinbi sukna'.",
        15: "Ameya' kam magkōg-koyag bang aniya' sehe'bi magkōg-koyag, ameya' kam magtangis bang aniya' sehe'bi ganta' magtangisan.",
        16: "Magsulut-siyuluti kam dapagkahian. Da'a palangahunbi bowahanbi, maka da'a kam aiya' magbagay maka a'a areyo'. Da'a kam maglaku-laku in pangita'ubi alalom.",
        17: "Bang aniya' angala'at ka'am, da'a pellenginbi la'at. Ai-ai binista abontol e' saga a'a kamemon, ya na he' subay tukirinbi.",
        18: "Amanuyu' kam magsulut maka a'a kamemon. Bang aniya' pagsagga'an subay ngga'i ka ka'am ya amowa sagga'.",
        19: "Saga bagay, da'a to'ongan kam amalos bang kam nila'at. Sagarinbi sigām binalos e' mulka' Tuhan. Entomunbi bay tasulat ma deyom Kitab, ya yuk-i, “Aku na amalos, aku na anungbas, yuk Panghū'.”",
        20: "Ahāp bang beya'bi panoho'an itu, ya bay tasulat isab ma Kitab, yuk-i, “Bang aniya' bantabi lingantu, pakanunbi. Bang iya patay bohe', painumunbi, sabab bang buwattē' lasabi ma iya, kalu iya sinōd susun.”",
        21: "Bang kam ganta' nila'at, da'a balosinbi. Hāpunbi a'a angala'at inān bo' tara'ug la'atna sabab min kahāpbi.",
    },
    13: {
        1: "In kitam manusiya' kamemon subay ameya' ma saga a'a magparinta ma paglahattam sabab halam aniya' kabuwanan kapatut magparinta bang ngga'i ka min kahandak Tuhan.",
        2: "Sasuku anagga' ma a'a magparinta, sali' Tuhan maka panoho'anna ya sagga'na, angkan iya taluwa' hukuman.",
        3: "Bang a'a maghinang ahāp mbal du tināw ma parinta. Luwal a'a maghinang kala'atan ya tināw. Bang kam mbal bilahi tināw ma a'a magparinta, subay ahāp sadja hinangbi. Sinanglitan kam e'na",
        4: "sabab sosoho'an Tuhan iya, a'a pinat'nna' maghinang kahāpan ma pasalanbi. Saguwā' bang kam ganta' maghinang kala'atan, patut kam tināw, sabab nakura' inān taga-kapatut aminasa ka'am. Sosoho'an Tuhan iya, wajib aminasa sasuku maghinang ala'at.",
        5: "Angkan kam subay magmaluluy ma saga a'a ang'ntan pagparinta, kaissana ma sabab kam tināw bininasa, karuwana ma sabab kata'uwanbi ma deyom itikadbi bang ai subay hinangbi.",
        6: "Ya he' sababanna angkan kam subay amayad sukay parinta, sabab sosoho'an Tuhan saga a'a ya maghinang ma deyo'an parinta inān.",
        7: "Subay kam amayaran sigām sukay pila-pila ya katongoranna, ai na ka tongod ni usahabi, ai na ka tongod ni baranbi. Pagaddatinbi sigām kamemon bang aniya' kawasa sigām patut pinagaddatan. Pagmahaltabatinbi bang patut pinagmahaltabatan.",
        8: "Bang aniya' utangbi, bayarinbi bang ta'abut waktuna. Aniya' isab utang mbal kabayaran, ya na lasa ma pagkahibi. Bang kam alasa ma pagkahibi tatuman e'bi panoho'an-sara' bay tasulat e' si Musa,",
        9: "ya yuk-i, “Wajib kam da'a angaliyu-lakad min paghola'bi. Wajib kam da'a amapatay, da'a anangkaw, da'a anganapsuhan alta' kasehe'anbi.” Ya panoho'an panambatku itu maka panoho'an kasehe', tapagdakayu' maka panoho'an dakayu'-dakayu', ya yuk-i, “Kalasahinbi pagkahibi buwat e'bi alasahan baranbi.”",
        10: "Hatulanna, sasuku alasa ma pagkahina mbal to'ongan bilahi angala'at iya. Angkan bang kitam alasahan pagkahita manusiya', tatuman e'tam sara' Tuhan maka panoho'anna kamemon.",
        11: "Patut subay hinangbi panoho'an itu sabab song na waktu pabīng si Isa. Asekot na min katagna' pam'nnalta ma si Isa. In kitam sali' hantang a'a bay magtulihan, sagō' abati' na.",
        12: "Sōng palabay kalendoman, ya masa pangandusa. Apote' na sobangan, angkan subay bbahanta kahinangan ala'at, ya nihinang ma deyom kalendoman. Subay kita sakap anagga' kala'atan, buwat ibarat sundalu magsakap.",
        13: "Kaul-pi'ilta subay ahāp, ya tōp ma a'a pat'nna' ma deyom kasawahan. Angkan da'a subay dumasiyaw paglami-lamita, da'a kita maglango-lango, da'a magba'is, da'a magkasabulan. Da'a kita magbono', da'a isab maglindi-lindi.",
        14: "Sapantun badju' paghaggut, ahāp lagi' bang Panghū'tam si Isa Al-Masi ya pangalampikbi. Da'a kannalunbi napsu baranbi bang buwattingga e'bi amarūl.",
    },
    14: {
        1: "Aniya' pamituwaku ma ka'am ma pasalan a'a alamma pangandolna ma si Isa. Bagayunbi iya, da'a iya bowahunbi magjawab ma saukat na aniya' kapam'nnalanna saddī.",
        2: "Buwat saupama ma pagkakan, aniya' a'a dakayu' makahalal pagkakan ai-ai sabab ahogot pangandolna ma si Isa Al-Masi. Aniya' isab a'a dangan, hal sayul ya palaukna pagka mbal gi' ahogot pangandolna.",
        3: "Na, ya a'a makahalal kinakan indaginis subay mbal angudju' ma a'a dangan ya mbal makahalal. Damikiyanna a'a amangan sayul sadja, subay mbal anoway a'a dangan ma saukat tahalalna kinakan ai-ai. Sabab tinaima' du a'a inān e' Tuhan.",
        4: "Halam aniya' kapatutbi anoway a'a dakayu' bang ngga'i ka ka'am ya pagnakura'an. Nakura'na sadja ya tag-kapatut amah'llingan iya ahāp-ala'at. Saguwā' tantu iya mbal tabowa ni kala'atan sabab tinabang iya e' Panghū' Isa angkan makasandal.",
        5: "Bang takdil ni llaw, aniya' a'a angisbat llaw mulliya sabab aheya bang ma bistahanna. Saddī isab bistahan a'a dangan, bang ma iya sali' du llaw kamemon. Jari ai-ai pamistabi pasal llaw, da'a pagduwa-duwahinbi.",
        6: "Sai-sai angamulliya llaw, Tuhan ya aheya ma atayna pagmahaldika'anna. Sai-sai angahalal kinakan ai-ai, Tuhan ya mahaldika'na sabab Tuhan ya pagsukulanna bang amangan. Damikiyanna isab, sai-sai amene' pagkakanna, Tuhan du isab mahaldika'na sampay pagsukulanna.",
        7: "Ngga'i ka baranta sadja ya pagka'inagonanta t'ggolta allum.",
        8: "Subay isbatta Panghū' Isa ma kallumta maka ma kamatayta sabab suku'na kita.",
        9: "Ya na itu sababanna angkan Al-Masi bay amatay sampay allum pabīng min kamatayna, supaya iya pagpanghū'an saga a'a suku'na, ai na ka allum, ai na ka bay magpatayan.",
        10: "Angkanna kam subay mbal anoway atawa angudju' danakanbi. Makapagbalharap du kitam kamemon maka Tuhan ma llaw damuli bo' nihukum e'na.",
        11: "Buwat tasulat ma Kitab, ya yuk-i, “B'nnal sadja bissalaku,” yuk Tuhan. “Pasujud du ni aku saga manusiya' kamemon. Magpanyabut sigām kamemon in aku asal Tuhan.”",
        12: 'Manjari in kitam kamemon subay magpamattan ni Tuhan ma sinosōng pasal ai-ai bay hinangtam ma dunya.',
        13: "Ya itu sababanna angkan kita subay pahali magsoway dangan maka dangan. Ahāp lagi' kita da'a magniyat angahinang ai-ai bang hinang inān amowa magdusa ma dakayu' danakanta.",
        14: "Aku itu, pagka parakayu' na ma Panghū' Isa, kata'uwanku to'ongan halam aniya' pagkakan haram min ka'asalna. Sagō' ma sehe'ta dakayu', bang aniya' pagkakan haram ma pamistana mbal to'ongan tas'llongna.",
        15: "Na, bang danakannu ganta' asusa ma sabab ka'a ya ta'nda'na amangan kinakan ya haram ma pamistana, sali' halam aniya' lasabi ma iya. Subay ka mbal pasangdan amangan e'-i bang amowa danakannu ni kala'atan, sabab bay amatay Al-Masi ma sababanna inān.",
        16: "Bang ma ka'a ahāp pagkakannu, saguwā' mbal ahāp bang binissalahan ala'at e' kasehe'an.",
        17: "Pagka kita ma deyoman pagparinta Tuhan, mbal subay pahalga'ta ma atay pagkakanta atawa paginumta. Ya subay paheyata kahinanganta abontol, maka kasannangan atay, maka kalasigan pamuwan e' Rū Sussi.",
        18: "Jari bang buwattē' paghinangta tudju ni Al-Masi kasulutan du Tuhan ma kita, maka pinagaddatan kita e' pagkahita manusiya'.",
        19: 'Angkan na, subay kita angamohot maghinang ai-ai makapagsulut pagkahita, maka magpahogot pangandolta dangan maka dangan.',
        20: "Da'a paka'atunbi hinang Tuhan ma saukat na magbidda' pangaddatbi pasal pagkakan. Tahalal asal pagkakan kamemon, saguwā' asā' kam bang kam amangan ai-ai, bo' kam ta'nda' e' dakayu' pagkahibi, ati minnē' iya ang'bba min pangandolna.",
        21: "Ahāp lagi' kita pahondong amangan susumbali'an, atawa anginum binu, atawa angahinang ai-ai bang ina'an-i manjari panababan pamowa danakanta angandusa atawa ang'bba min pangandolna.",
        22: "Manjari ai-ai pamistabi pasal itu-i subay hal ka'am maka Tuhan ya makata'u. Aheya kalasiganbi bang kam anganiyat angahinang ai-ai ma halam aniya' dusa tananam ma itikadbi.",
        23: "Sagō' bang a'a magduwa-ruwa pasal pagkakan bo' amangan na pa'in, katōngan iya dusa sabab mbal magtaluwa' maka pangandolna. Taga-dusa kita bang aniya' hinangta mbal magtaluwa' maka pangandolta.",
    },
    15: {
        1: "Sasuku kitam akosog pangandoltam ma Tuhan subay anabang ma a'a kasehe'an ya mbal angandol to'ongan. Subay tanggungtam kalammahan sigām. Ngga'i ka baranta ya subay sinulut,",
        2: "sagō' danakantam bebeya'an si Isa Al-Masi, pamahāp kahālanna bo' supaya pasōng pahogot pangandolna.",
        3: "Panunurantam Al-Masi sabab halam iya bay angandūlan di-na. Atumlang ya tasulat ma deyom Kitab, yuk-i, “Ka'a, Tuhan, pinamūng-mūngan ala'at, bo' aku ya t'kkahan himumungan sigām.”",
        4: "Ai-ai ma deyom Kitab bay pinasulat e' Tuhan ma awal jaman pangā'antam kapamintāngan, bo' supaya ahogot imantam maka kasandal ma katiksa'an. Minnē' kitam angaholat lappasan.",
        5: "Tuhan ya amasandal maka amahogot imantam. Mura-murahan, bang pa'in kam tinabang e'na bo' kam magdakayu' pikilan hinabubi anunud ma si Isa Al-Masi.",
        6: "Jari maguyun kam amudji ma Tuhan, ya Mma' sin Panghū' Isa Al-Masi.",
        7: "Taima'unbi kasehe'anbi angandol ma Al-Masi, buwat kapanaima' ka'am e' Al-Masi. Tapudji Tuhan bang buwattē' panaima'bi.",
        8: "Haka'anta kam pasal Al-Masi, bay iya pi'itu ni dunya anabang bangsa Yahudi bo' sigām makatantu in Tuhan kapangandolan du, ati bo' atuman bay janji'na ma pangkat kami.",
        9: "Ya minaksud e'na saga a'a ngga'i ka Yahudi bo' supaya sigām amudji Tuhan ma sabab ka'ase'na. Buwat bay tasulat ma deyom Kitab, ya yuk-i, “Magsukul aku ni ka'a, Tuhan, ma deyoman saga a'a ngga'i ka Yahudi. Magkalang aku kalangan pamudji ōnnu.”",
        10: "Aniya' gi' ayat Kitab dakayu', yuk-i, “Ka'am kabangsa-bangsahan ya ngga'i ka Yahudi, dai' kam magkōg-koyag sama-sama maka bangsa ya tapene' e' Tuhan.”",
        11: "Maka ayat itu gi': “Sanglitinbi Tuhan, ka'am kamemon ya ngga'i ka Yahudi. Pudjihunbi iya, ka'am sabarang bangsa.”",
        12: "Aniya' isab bay sinulat e' si Isaya pasal Al-Masi, yuk-i, “Aniya' tubu' si Jesse palahil ni dunya ma sinōng. Magbaya' du iya ma bangsa ngga'i ka Yahudi, ati iya ya pangasahan sigām.”",
        13: "Mura-murahan, bang pa'in kam kaniya'an kakōgan maka kasannangan deyom atay min Tuhan, ya po'onan holatanbi, pagka kam angandol na pa'in ma iya. Ati manglabi-labihan kaholatanbi ma sabab kawasa min Rū Sussi.",
        14: "Saga dauranakanku, halam aniya' hawal-hawalku ma sababanbi. Tatantuku in ka'am ahāp kasuddahanbi, aheya isab pangita'ubi, patut kam magpandu'-pandu'an di-bi.",
        15: "Saguwā' aniya' gi' pamaentomku ka'am, ya po'on aku atawakkal amabeya' sulat itu. Halam aniya' pagduwa-duwaku anulatan ka'am sabab taga-wakil aku min Tuhan.",
        16: "Maghinang aku ma si Isa Al-Masi ma pasalan saga bangsa saddī min Yahudi. Ibarat aku imam magnasihat lapal ahāp min Tuhan, bo' supaya angandol saga bangsa kasehe'an. Ungsuranku sigām ni Tuhan dalil tutukbalan. Kasulutan iya ma sigām, sabab tasussi na pangatayan sigām e' Rū Sussi.",
        17: "Na, mbal aku aiya' magpata'u pasal paghinangku ma Tuhan, sabab si Isa Al-Masi ya pagkōganku.",
        18: "Halam aniya' pagbissalahanku haliyu min bay pamahinang aku e' Al-Masi. Maka Al-Masi ya sababna angkan tabowa saga bangsa saddī ameya' ma Tuhan. Takale e' sigām pagnasihatku, ta'nda' e' sigām saga hinang bay hinanganku",
        19: "min kawasa Rū Sussi, hatina saga paltanda'an maka hinang kainu-inuhan a'a. Bay pasaplagku to'ongan lapal ahāp pasal si Isa Al-Masi, tinagna'an min Awrusalam sampay ta'abut lahat Ilirikum.",
        20: "Sangay min tagna' kapagnasihatku, ya pagmatayanku subay pinasaplag lapal ahāp itu ma lahat halam bay kapakalehan pasal Al-Masi, sabab mbal aku bilahi anugpat ni bay tahinang e' a'a bay dumahū min aku.",
        21: "Kabaya'anku subay atuman sulat Kitab itu, ya yuk-i, “Saga a'a halam bay pinata'u ma pasalanna, makata'u du ma sinosōng, maka a'a halam bay makakale, makahati na.”",
        22: "Ya ko' ina'an sababna angkan aku bay makat'ggol pi'ilu ni ka'am, sabab hinangku angalatag kalahatan ītu subay apuwas dahū.",
        23: "Sagō' atammat na hinangku ma jadjahan ītu. Bilahi na aku sidda patibaw ni ka'am,",
        24: "manjari agara' na aku amusay ni lahat Kastila', sagō' bilahi aku pahapit ni ka'am dahū bo' supaya kitam makapag'nda'. Bilahi isab aku patuntulbi, bang aku song pauntas ni papehē'anku he'. Subay na ahāp katibawku ma ka'am bo' yampa aku ala'an.",
        25: "Saguwā' aniya' gi' gawiku dahū. Itiya' aku ni Awrusalam ang'nde'an tutulungan ni saga a'a suku' si Isa mahē'.",
        26: "Sabab bay animuk sīn saga jama'a si Isa ya maglahat ma sakalibut lahat Makidunya maka Akaya itu, panulung saga miskin ma kajama'ahan suku' Tuhan ma Awrusalam.",
        27: "Hilas isab min deyom atay sigām, maka patut isab sabab Yahudi ya po'onna angkan sigām ngga'i ka Yahudi bay pinakalehan lapal min Tuhan. Tauwa' bang bangsa Yahudi ya pinahampitan ai-ai bay pangalidjiki' saga a'a ngga'i ka Yahudi.",
        28: "Manjari bang atangbus gawiku ang'nde'an kamemon bay pinabowa ma aku, pauntas aku tudju ni lahat Kastila' ati pahapit du ni ka'am.",
        29: "Kata'uwanku isab, bang aku ganta' makat'kka ni ka'am, tantu kam bowahanku kahāpan aheya min Al-Masi, kahāpan halam kulangna.",
        30: "Saga dauranakanku, kata'uwanku aheya pangisbatbi ma si Isa Al-Masi Panghū'tam maka aniya' lasabi luwas min Rū Tuhan, angkan aku angamu' junjung itu. Gapi'unbi aku, amu'inbi aku tabang ni Tuhan.",
        31: "Amu'-amu'inbi isab aku bo' aku mbal ainay e' saga a'a ma lahat Yahudi ya mbal magkahagad ma si Isa. Amu'inbi isab aku kahāpan pasal tutulungan ya bowaku pina'an, bang pa'in tinaima' sangkahāpan e' saga a'a suku' Tuhan he'.",
        32: "Jari bang kabaya'an Tuhan, pasampay du aku ni ka'am maka kalasiganku aheya, ati ahāp palasahanku bang kita makapag'nda'.",
        33: "Na, mura-murahan, bang pa'in kam ginapi' kamemon e' Tuhan, ya po'onan kasannangan. Amin.",
    },
    16: {
        1: "Bilahi aku amakilā ni ka'am dakayu' danakantam d'nda itu. Ōnna si Pebe, a'a anabang ma katipunan jama'a si Isa ma lahat Kengkereya.",
        2: "Aniya' gawina pi'ilu ni Rōm. Subay ahāp e'bi ama'idda iya bang makat'kka pi'ilu, pagka si Isa Al-Masi ya Panghū'bi sali'-sali', maka suku' Tuhan du kam. Subay iya patuntulbi ma ai-ai kalagihanna, sabab aheka a'a bay tatabang e'na, sampay isab aku.",
        3: "Amabeya' aku minsan la'a hal lapal kasi-lasaku ni disi Akila maka si Prisila ilu, a'a maglakibini bay sehe'ku maghinang ma si Isa Al-Masi.",
        4: "Bay sigā arak amatay ma sababanku waktu aku bay ma deyom kapiligduhan, angkanna aheya pagsukulanku ma sigā. Ngga'i ka hal aku ya magsukul, sampay saga jama'a si Isa kamemon ya ngga'i ka Yahudi, sasuku magpalhimpunan ma kalahat-lahatan ilu.",
        5: "Pabeya'ku isab lapalku ma saga jama'a si Isa ya magtipun ma luma' sigā. Damikiyanna si Epeneto bagayku kalalasahan, pabeya'anku minsan hal lapalku. Dahū asal iya min a'a kamemon ya magpangandol ma Al-Masi ma kaluha'an lahat Asiya.",
        6: 'Maka si Mariyam, ya akosog hinangna ma pasalanbi.',
        7: "Si Androniku maka si Juniyas, pagkahiku Yahudi bay sehe'ku ma deyom kalabusu. Abantug sigā bang takdil ni saga a'a kawakilan si Isa, dahū sigā min aku bay angandol ma Al-Masi.",
        8: "Pabeya'ku isab lapalku ni disi Ampliyatu, bagayku kinalasahan ma deyoman Panghū' Isa,",
        9: "maka si Urbanu, sehe'tam maghinang ma Al-Masi, maka si Istakis bagayku kinalasahan isab.",
        10: "Si Apelles isab, apa bay na iya kasulayan in pameya'na ma Al-Masi ahogot du. Sigām ma okoman si Aristobol,",
        11: "maka si Herodiyun pagkahiku Yahudi, maka sigām angandol ma Panghū' Isa min okoman si Narkissu.",
        12: "Damikiyanna disi Tripena maka si Triposa, d'nda maghinang ma Panghū' Isa, maka bagayku si Persis, d'nda kinalasahan, ya abasag paghinangna ni Panghū'tam. Amabeya' isab aku minsan la'a hal lapalku ni sigām.",
        13: "Si Rupus isab, a'a tapene' e' Panghū'ta, maka ina' si Rupus e'. Sapantun iya ina' angayura aku.",
        14: "Disi Asingkrit, si Plegon, si Hermes, si Patrobas, si Hermas maka saga sehe' sigām angandol ma si Isa.",
        15: "Disi Pilologo maka si Juliya isab, si Nereyo maka danakanna d'nda, si Olimpas isab maka a'a suku' Tuhan kamemon ya dansehe'an maka sigām. Pabeya'ku lapalku ni sigām ilu kamemon.",
        16: "Bang kam magsabu, subay kam magsiyum ta'nda' paglasabi. Kamemon saga jama'a Al-Masi ya magtipun-tipun maitu amabowa tambuku ni ka'am, in ka'am nientom kono' e' sigām.",
        17: "Saga dauranakanku, aniya' junjungku ni ka'am. Halli'inbi saga a'a anagga' pandu' bay pamandu' ka'am pasal si Isa Al-Masi. Saga a'a ilu bilahi amapagsagga' ka'am bo' kam aboklang duwa, maka bilahi isab amowa ka'am pasiha' min pangandolbi ni si Isa. Tangkisinbi saga a'a inān.",
        18: "Sabab bang a'a maghinang buwattē' ngga'i ka Panghū'tam Al-Masi ya paghinangan sigām, saguwā' baran sigām ya nirūlan. Binidjakan e' sigām saga a'a kulang panahu'anna, nilanahan bo' supaya tabowa niakkalan.",
        19: "In ka'am ilu abantug na ma sabab kahogot pameya'bi ma Al-Masi, angkan aku kinōgan ma sababbi. Kabaya'anku ma ka'am subay alalom pamikilbi pasal ai-ai makahāp, ma halam aniya' la'at makani-pikilanbi.",
        20: "Manjari Tuhan, ya po'onan kasannangan ataytam, pasa'ut du amaka'at nakura' saitan ni deyo' pād-tape'tam. Mura-murahan bang pa'in kam pinaniya'an tatabangan e' Panghū'tam si Isa.",
        21: "Si Timuti, ya sehe'ku maghinang ma Tuhan itu, amabeya' minsan la'a hal lapalna ni ka'am. Damikiyanna isab disi Lukiyus itu maka si Jason, maka kampungku si Sosepater.",
        22: "(Palamud si Tertiyu, ya bay kawakilan anulat sulat itu, yuk-i, “Amabeya' aku lapalku ni ka'am pagka kitam Almasihin sali'-sali'.”)",
        23: "Si Gayus, ya tag-luma' paokomanku itu, amabeya' isab minsan la'a hal lapalna ni ka'am. Ya du si Erastus, a'a ang'ntan alta' parinta ma da'ira itu, maka danakantam si Kuwartu.",
        24: "Mura-murahan, bang pa'in kam pinaniya'an tatabangan e' si Isa Al-Masi, ya Panghū'tam. Amin.",
        25: "Pudjitam Tuhan. Taga-kawasa iya amahogot pangandolbi, pagga beya'bi lapal ahāp ya bay pagnasihatku pasal si Isa Al-Masi. In lapal ahāp itu halam bay kinata'uwan e' manusiya' sangay min masa awal e', saguwā' buwattina'an pinamahalayak na ni a'a kamemon ma sabab panoho'an Tuhan, ya taptap allum. Bay pinasulat e'na lapalna ma kanabi-nabihan, pamata'u ma bangsa a'a kamemon ma deyom dunya bo' supaya sigām magkahagad sampay ameya' ma Tuhan.",
        26: "Pudjitam Tuhan. Taga-kawasa iya amahogot pangandolbi, pagga beya'bi lapal ahāp ya bay pagnasihatku pasal si Isa Al-Masi. In lapal ahāp itu halam bay kinata'uwan e' manusiya' sangay min masa awal e', saguwā' buwattina'an pinamahalayak na ni a'a kamemon ma sabab panoho'an Tuhan, ya taptap allum. Bay pinasulat e'na lapalna ma kanabi-nabihan, pamata'u ma bangsa a'a kamemon ma deyom dunya bo' supaya sigām magkahagad sampay ameya' ma Tuhan.",
        27: "Pudjitam Tuhan, ya tunggal tubus ma pangita'u. Pudjitam iya sampay ni kasaumulan, pagka si Isa Al-Masi ya pamanyabutantam. Amin. Wassalam",
    },
}
