NAME = 'SpaRV1865: La Santa Biblia Reina-Valera (1865) con arreglos ortográficos'
BOOK = 'James'

CHAPTERS = {
    1: {
        1: 'Santiago siervo de Dios y del Señor Jesu Cristo, a las doce tribus que están en la dispersión, salud.',
        2: 'Hermanos míos, tenéd por todo gozo cuando cayereis en diversas tribulaciones:',
        3: 'Sabiendo que la prueba de vuestra fe obra paciencia.',
        4: 'Mas tenga la paciencia su obra perfecta, para que seáis perfectos y cabales, sin faltar en alguna cosa.',
        5: 'Y si alguno de vosotros tiene falta de sabiduría, demánde la a Dios, (el cual da a todos dadivosamente, y no zahiere,) y serle ha dada.',
        6: 'Empero demande en fe, no dudando nada; porque el que duda, es semejante a la onda de la mar, que es movida del viento, y es echada de una parte a otra.',
        7: 'No piense pues el tal hombre que recibirá cosa alguna del Señor.',
        8: 'El hombre de doblado ánimo, es inconstante en todos sus caminos.',
        9: 'Además, el hermano que es de humilde condición, gloríese en su ensalzamiento;',
        10: 'Mas el que es rico, en su humillación; porque él se pasará como la flor de la yerba:',
        11: 'Que salido el sol con ardor, la yerba se secó, y su flor se cayó, y su hermosa apariencia pereció: así también se marchitará el rico en sus caminos.',
        12: 'Bienaventurado el varón que sufre tentación; porque después que fuere probado, recibirá la corona de vida, que Dios ha prometido a los que le aman.',
        13: 'Cuando alguno es tentado, no diga, que Dios me tienta; porque Dios no puede ser tentado por el mal, ni él tienta a alguno:',
        14: 'Sino que cada uno es tentado, cuando de su propia concupiscencia es atraído, y cebado.',
        15: 'Y la concupiscencia después que ha concebido, pare al pecado: y el pecado, siendo cumplido, engendra muerte.',
        16: 'Hermanos míos muy amados, no erréis.',
        17: 'Toda buena dádiva, y todo don perfecto es de lo alto, que desciende del Padre de las lumbres, en el cual no hay mudanza, ni sombra de variación.',
        18: 'El de su propia voluntad nos ha engendrado por la palabra de verdad, para que seamos como primicias de sus criaturas.',
        19: 'Así que, hermanos míos muy amados, todo hombre sea pronto para oír, tardío para hablar, tardío para airarse;',
        20: 'Porque la ira del hombre no obra la justicia de Dios.',
        21: 'Por lo cual dejando toda inmundicia, y superfluidad de malicia, recibíd con mansedumbre la palabra injerida en vosotros, la cual puede hacer salvas vuestras almas.',
        22: 'Mas sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos.',
        23: 'Porque si alguno oye la palabra, y no la pone por obra, este tal es semejante al hombre que considera en un espejo su rostro natural:',
        24: 'Porque él se consideró a sí mismo, y se fue; y luego se olvidó qué tal era.',
        25: 'Mas el que hubiere mirado atentamente en la ley perfecta que es la de la libertad, y hubiere perseverado en ella, no siendo oidor olvidadizo, sino hacedor de la obra, este tal será bienaventurado en su hecho.',
        26: 'Si alguno de entre vosotros piensa ser religioso, y no refrena su lengua, sino que engaña su propio corazón, la religión del tal es vana.',
        27: 'La religión pura y sin mácula delante de Dios y Padre es esta: Visitar los huérfanos y las viudas en sus tribulaciones, y guardarse sin mancha del mundo.',
    },
    2: {
        1: 'Hermanos míos, no tengáis la fe de nuestro Señor Jesu Cristo glorioso en acepción de personas.',
        2: 'Porque si en vuestra congregación entra algún varón, que trae anillo de oro, vestido de preciosa ropa, y también entra un pobre vestido de vestidura vil,',
        3: 'Y pusiereis los ojos en el que trae la vestidura preciosa, y le dijereis: Tú asiéntate aquí honorífica mente; y dijereis al pobre: Estáte tú allí en pie; o, siéntate aquí debajo del estrado de mis pies:',
        4: '¿Vosotros, no hacéis ciertamente distinción dentro de vosotros mismos, y sois hechos jueces de pensamientos malos?',
        5: 'Hermanos míos amados, oíd: ¿No ha elegido Dios los pobres de este mundo, que sean ricos en fe, y herederos del reino que ha prometido a los que le aman?',
        6: 'Mas vosotros habéis afrentado al pobre. ¿Los ricos no os oprimen con tiranía, y ellos mismos os arrastran a los juzgados?',
        7: '¿No blasfeman ellos el buen nombre que es invocado sobre vosotros?',
        8: 'Si ciertamente vosotros cumplís la ley real conforme a la Escritura, es a saber: Amarás a tu prójimo como a ti mismo; bien hacéis;',
        9: 'Mas si hacéis acepción de personas, cometéis pecado, y sois acusados de la ley como transgresores.',
        10: 'Porque cualquiera que hubiere guardado toda la ley, y sin embargo se deslizare en un punto, es hecho culpado de todos.',
        11: 'Porque el que dijo: No cometas adulterio, también ha dicho: No mates. Y si no hubieres cometido adulterio, empero hubieres matado, ya eres hecho transgresor de la ley.',
        12: 'Así hablád, y así obrád como los que habéis de ser juzgados por la ley de libertad.',
        13: 'Porque juicio sin misericordia será hecho a aquel que no hiciere misericordia; y la misericordia se gloría contra el juicio.',
        14: 'Hermanos míos, ¿qué aprovechará si alguno dice que tiene fe, y no tiene obras? ¿Podrá la fe salvarle?',
        15: 'Porque si el hermano, o la hermana estuvieren desnudos, o necesitados del mantenimiento de cada día,',
        16: 'Y alguno de vosotros les dijere: Id en paz, calentáos, y hartáos, empero no les diéreis las cosas que son necesarias para el cuerpo, ¿qué les aprovechará?',
        17: 'Así también la fe, si no tuviere obras, es muerta por sí misma.',
        18: 'Mas alguno dirá: Tú tienes fe, y yo tengo obras; muéstrame tu fe sin tus obras; y yo te mostraré mi fe por mis obras.',
        19: 'Tú crees que Dios es uno: haces bien: también los demonios lo creen, y tiemblan.',
        20: '¿Mas, oh hombre vano, quieres saber, que la fe sin las obras es muerta?',
        21: 'Abraham, nuestro padre, ¿no fue justificado por las obras, cuando ofreció a su hijo Isaac sobre el altar?',
        22: '¿ No ves que la fe obró con sus obras, y que por las obras la fe fue perfecta?',
        23: 'Y la Escritura fue cumplida, que dice: Abraham creyó a Dios, y le fue imputado a justicia, y fue llamado el amigo de Dios.',
        24: 'Vosotros, pues, veis, que por las obras es justificado el hombre, y no solamente por la fe.',
        25: 'Semejantemente también Raab la ramera, ¿no fue justificada por obras, cuando recibió los mensajeros, y los echó fuera por otro camino?',
        26: 'Porque como el cuerpo sin espíritu está muerto, así también la fe sin obras es muerta.',
    },
    3: {
        1: 'Hermanos míos, no os hagáis muchos de vosotros maestros, sabiendo que recibiremos mayor condenación.',
        2: 'Porque todos ofendemos en muchas cosas. Si alguno no ofende en palabra, éste es varón perfecto, que también puede con freno gobernar todo el cuerpo.',
        3: 'He aquí, nosotros ponemos a los caballos frenos en las bocas para que nos obedezcan, y gobernamos todo su cuerpo.',
        4: 'He aquí también las naos, siendo tan grandes, y siendo llevadas de impetuosos vientos, son sin embargo gobernadas con un muy pequeño gobernalle por donde quiera que quisiere la gana del que las gobierna.',
        5: 'Semejantemente también la lengua es un pequeñito miembro, mas se gloría de grandes cosas. He aquí, un pequeño fuego, ¡cuán grande bosque enciende!',
        6: 'Y la lengua es un fuego, digo, un mundo de maldad. Así la lengua está puesta entre nuestros miembros, la cual contamina todo el cuerpo, e inflama la rueda natural; y es inflamada del gehena.',
        7: 'Porque toda naturaleza de bestias fieras, y de aves, y de serpientes, y de los de la mar, se doma, y es domada por la naturaleza humana;',
        8: 'Pero ningún hombre puede domar la lengua: es un mal que no puede ser refrenado, y está llena de veneno mortal.',
        9: 'Con ella bendecimos a Dios, y al Padre, y con ella maldecimos a los hombres, los cuales son hechos a la semejanza de Dios.',
        10: 'De una misma boca procede bendición y maldición. Hermanos míos, no conviene que estas cosas sean así hechas.',
        11: '¿Echa alguna fuente por un mismo manantial agua dulce y amarga?',
        12: 'Hermanos míos, ¿puede la higuera producir aceitunas; o la vid, higos? Así ninguna fuente puede dar agua salada y dulce.',
        13: '¿Quién es sabio, y entendido entre vosotros? muestre por buena conversación sus obras en mansedumbre de sabiduría.',
        14: 'Empero si tenéis envidia amarga, y contención en vuestros corazones, no os glorieis, ni seáis mentirosos contra la verdad;',
        15: 'Porque esta sabiduría no es la que desciende de lo alto, sino que es terrena, animal, y demoniaca.',
        16: 'Porque donde hay envidia y contención, allí hay tumulto, y toda obra perversa.',
        17: 'Empero la sabiduría que es de lo alto, primeramente es pura, después pacífica, modesta, fácil de persuadir, llena de misericordia y de buenos frutos, no juzgadora, no fingida.',
        18: 'Y el fruto de justicia se siembra en paz para aquellos que hacen paz.',
    },
    4: {
        1: '¿De dónde vienen las guerras, y los pleitos entre vosotros? De aquí, es a saber, de vuestras concupiscencias, las cuales batallan en vuestros miembros.',
        2: 'Codiciáis, y no tenéis: tenéis envidia y odio, y no podéis alcanzar: combatís y guerreáis, empero no tenéis lo que deseáis, porque no pedís.',
        3: 'Pedís, y no recibís; porque pedís malamente, para gastar en vuestros deleites.',
        4: 'Adúlteros y adúlteras, ¿no sabéis que la amistad del mundo es enemistad con Dios? Cualquiera, pues, que quisiere ser amigo del mundo, se constituye enemigo de Dios.',
        5: '¿Pensáis que la Escritura dice sin causa: El espíritu que mora en nosotros, codicia envidiosamente?',
        6: 'Mas él da mayor gracia. Porque él dice: Dios resiste a los soberbios, empero da gracia a los humildes.',
        7: 'Sed pues sujetos a Dios: resistíd al diablo, y huirá de vosotros.',
        8: 'Allegáos a Dios, y él se allegará a vosotros. Pecadores, limpiád las manos; y vosotros de doblado ánimo, purificád los corazones.',
        9: 'Afligíos, y lamentád, y llorád. Vuestra risa conviértase en lloro, y vuestro gozo en tristeza.',
        10: 'Humilláos delante de la presencia del Señor, y él os ensalzará.',
        11: 'Hermanos, no digáis mal los unos de los otros: el que dice mal de su hermano, y juzga a su hermano, este tal dice mal de la ley, y juzga a la ley; mas si tú juzgas a la ley, no eres guardador de la ley, sino juez.',
        12: 'Solo uno es el dador de la ley, que puede salvar, y perder: ¿Quién eres tú que juzgas a otro?',
        13: 'Ea ahora, vosotros los que decís: Vamos hoy y mañana a tal ciudad, y estaremos allá un año, y compraremos mercadería, y ganarémos:',
        14: 'Vosotros que no sabéis lo que será mañana. Porque, ¿qué es vuestra vida? Ciertamente es un vapor que se aparece por un poco de tiempo, y después se desvanece.',
        15: 'En lugar de lo cual deberíais decir: Si el Señor quisiere, y si viviéremos, haremos esto o aquello.',
        16: 'Mas ahora triunfáis en vuestras soberbias. Toda gloria semejante es mala.',
        17: 'El pecado, pues, está en aquel que sabe hacer lo bueno, y no lo hace.',
    },
    5: {
        1: 'Ea ya ahora, ricos, llorád aullando por causa de las miserias que os han de sobrevenir.',
        2: 'Vuestras riquezas están podridas; y vuestras ropas están roidas de la polilla.',
        3: 'Vuestro oro y vuestra plata están orinecidos, y el orín de ellos será testimonio contra vosotros, y comerá del todo vuestras carnes como fuego: habéis allegado tesoro para en los postreros días.',
        4: 'He aquí, el jornal de los obreros que han segado vuestras tierras, (el cual por engaño no les ha sido pagado de vosotros,) clama; y los clamores de los que habían segado han entrado en el oído del Señor de los ejércitos.',
        5: 'Habéis vivido en deleites sobre la tierra, y sido disolutos, y habéis cebado vuestros corazones como en un día de matanza.',
        6: 'Habéis condenado y muerto al justo, y él no os resiste.',
        7: 'Por tanto, hermanos, sed pacientes hasta la venida del Señor. He aquí, el labrador espera el precioso fruto de la tierra, esperando pacientemente, hasta que reciba la lluvia temprana y tardía.',
        8: 'Sed pues también vosotros pacientes, y fortificád vuestros corazones; porque la venida del Señor se acerca.',
        9: 'Hermanos, no gimáis unos contra otros, porque no seáis condenados: He aquí, el juez está delante de la puerta.',
        10: 'Hermanos míos, tomád por ejemplo de sufrir el mal, y de paciencia, a los profetas que hablaron en el nombre del Señor.',
        11: 'He aquí, tenemos por bienaventurados a los que sufren. Vosotros habéis oído de la paciencia de Job, y habéis visto el fin del Señor, que el Señor es muy misericordioso y piadoso.',
        12: 'Empero, hermanos míos, ante todas cosas no juréis, ni por el cielo, ni por la tierra, ni por otro cualquier juramento; mas vuestro Sí, sea Sí; y vuestro No, No; porque no caigáis en condenación.',
        13: '¿Está alguno entre vosotros afligido? haga oración. ¿Está alguno alegre entre vosotros? salmodie.',
        14: '¿Está alguno enfermo entre vosotros? llame a los ancianos de la iglesia, y oren sobre él, ungiéndole con aceite en el nombre del Señor;',
        15: 'Y la oración de fe hará salvo al enfermo, y el Señor le aliviará; y si estuviere en pecados, le serán perdonados.',
        16: 'Confesáos vuestras faltas unos a otros, y rogád los unos por los otros, para que seáis sanos. La oración eficaz del justo puede mucho.',
        17: 'Elías era hombre sujeto a semejantes pasiones que nosotros, y rogó con oración que no lloviese, y no llovió sobre la tierra por tres años, y seis meses.',
        18: 'Y otra vez oró, y el cielo dio lluvia, y la tierra produjo su fruto.',
        19: 'Hermanos, si alguno de entre vosotros errare de la verdad, y alguno le convirtiere,',
        20: 'Sepa este tal que el que hubiere hecho convertir al pecador del error de su camino, salvará un alma de muerte, y cubrirá multitud de pecados.',
    },
}
