NAME = 'SloStritar: Novi testament in Psalmi Davidovi Josipa Stritarja (1882)'
BOOK = 'I Thessalonians'

CHAPTERS = {
    1: {
        1: 'Pavel in Silvan in Timotej občini Tesaloničanov v Bogu očetu in Gospodu Jezusu Kristusu; milost vam in mir od Boga očeta našega in Gospoda Jezusa Kristusa!',
        2: 'Zahvaljujemo se Bogu vedno za vas vse, spominjajoč se vas v molitvah svojih,',
        3: 'Neprestano spominjajoč se dela vašega v veri in truda v ljubezni, in stanovitnosti v tipanji Gospoda našega Jezusa Kristusa, pred Bogom in očetom našim;',
        4: 'Vedóč, bratje ljubljeni od Boga, za izvoljenje vaše;',
        5: 'Da evangelj naš ni prišel samo v besedi do vas, nego tudi v moči in v Duhu svetem, in v mnogem prepričanji, kakor veste, kakošni smo med vami postali za vas.',
        6: 'In vi ste postali posnemalci naši in Gospodovi, sprejemši besedo, v mnogi stiski z veseljem Duha svetega,',
        7: 'Tako da ste postali zgled vsem verujočim v Macedoniji in Ahaji.',
        8: 'Kajti od vas je zadonela beseda Gospodova ne samo po Macedoniji in Ahaji, nego tudi v vsakem kraji razširila se je vaša vera v Boga, tako da nam ni treba kaj govoriti.',
        9: 'Kajti sami oznanjajo za nas, kak smo imeli prihod k vam, in kako ste se obrnili k Bogu od malikov, služit Bogu živemu in resničnemu,',
        10: 'In čakat sina njegovega iz nebés, katerega je zbudil izmed mrtvih, Jezusa, ki nas rešuje jeze prihodnje.',
    },
    2: {
        1: 'Kajti sami veste, bratje, naš prihod k vam, da ni bil prazen;',
        2: 'Nego, dasì smo trpeli prej in zasramovani bili, kakor veste v Filipih, govorili smo prostodušno v Bogu našem proti vam evangelj Božji v mnogem boji.',
        3: 'Kajti opomin naš ni iz zmotnjave, ne iz nečistosti, ne v zvijači;',
        4: 'Nego kakor nas je Bog za vredne spoznal izročiti nam evangelj, tako govorimo, ne da bi bili ljudém po volji, nego Bogu, ki presoja srca naša.',
        5: 'Kajti ne s prilizovanja besedo nismo se pečali nikdar, kakor veste, ne s pretvezo lakomnosti; Bog priča!',
        6: 'In od ljudî nismo slave iskali, ne od vas, ne od drugih, ko smo bili lahko imenitni, kakor aposteljni Kristusovi;',
        7: 'Nego bili smo rahli sredi vas, kakor pač dójka goji otroke svoje.',
        8: 'Tako hrepeneč po vas, bila nas je volja ne samo podati vam evangelj Božji, nego tudi duše svoje, ker ste nam postali ljubljeni.',
        9: 'Kajti spominjate se, bratje, truda našega in težave; ker noč in dan smo delali, da bi ne bili nadležni komu izmed vas, in oznanjali vam evangelj Božji;',
        10: 'Vi priče in Gospod Bog, kako sveti in pravični in brez krivice smo bili z vami verujočimi;',
        11: 'Kakor veste, kako smo slehernega izmed vas kakor oče otroke svoje opominjali, izpodbujali,',
        12: 'In rotili, da živite pristojno Bogu, ki vas kliče v svoje kraljestvo in slavo.',
        13: 'Zato se tudi mi zahvaljujemo Bogu neprestano, da ste prejemši od nas besedo Božjo oznanovano, sprejeli ne besede človeške, nego (kakor je resnično) besedo Božjo, katera tudi deluje v vas verujočih.',
        14: 'Kajti vi ste postali posnemalci, bratje, občin Božjih v Judeji v Kristusu Jezusu, ker ste tudi vi isto trpeli od lastnih rojakov, kakor tudi oni od Judov,',
        15: 'Kateri so tudi Gospoda Jezusa umorili, in lastne preroke, in nas pregnali, in kateri niso Bogu po volji in so vsem ljudém zoprni;',
        16: 'Kateri nam branijo govoriti poganom, da se rešijo, da vedno napolnijo grehe svoje. Prišla pa je nad nje jeza v njih konec.',
        17: 'Mi pa, bratje, osiroteni za vami za nekaj časa, po obličji ne po srci, prizadevali smo si tolikanj bolj videti obličje vaše v mnogem poželenji.',
        18: 'Zato smo hoteli priti k vam, jaz Pavel, enkrat in dvakrat, a branil nam je satan.',
        19: 'Kajti kdo je upanje naše, ali veselje, ali slave venec? Ali ne tudi vi, pred Gospodom našim Jezusom Kristusom o prihodu njegovem?',
        20: 'Kajti vi ste slava naša in veselje.',
    },
    3: {
        1: 'Zato, ker več ne strpimo, sklenili smo raji sami ostati v Atenah,',
        2: 'In poslali smo Timoteja, brata našega in služabnika Božjega in sodelalca našega v evangelji Kristusovem, utrdit vas in opominjat vas o veri vaši;',
        3: 'Da nihče ne omahuje v teh stiskah; sami namreč veste, da smo namenjeni za to.',
        4: 'Saj smo tudi, ko smo bili pri vas, naprej povedali vam, da pridemo v stiske, kakor se je tudi zgodilo in veste.',
        5: 'Zato sem tudi jaz, ker nisem mogel več strpeti, poslal pozvedet za vero vašo, da bi vas ne bil morda izkušal izkušnjavec, in bi bil zastonj naš trud.',
        6: 'Ko je pa ravnokar Timotej k nam prišel od vas, in prinesel nam blago vest o veri in ljubezni vaši, in da nas imate vedno v dobrem spominu, hrepeneč videti nas, kakor tudi mi vas;',
        7: 'Zato smo bili, bratje, za vas potolaženi v vsej stiski in sili svoji po veri vaši;',
        8: 'Ker zdaj živimo, če vi stojite trdno v Gospodu.',
        9: 'Kajti káko zahvalo moremo Bogu vrniti za vas, za vse veselje, s katerim se radujemo za vas pred Bogom svojim,',
        10: 'Noč in dan presilno proseč, da bi videli obličje vaše in dopolnili pogreške vere vaše.',
        11: 'On pa Bog in oče naš, in Gospod naš Jezus Kristus naj vodi pot našo k vam;',
        12: 'Vas pa naj Gospod napolni in obogati z ljubeznijo med seboj in do vseh, kakor smo tudi mi do vas;',
        13: 'Da utrdi srca vaša brez madeža v svetosti pred Bogom in očetom našim, o prihodu Gospoda našega Jezusa Kristusa z vsemi njegovimi svetimi.',
    },
    4: {
        1: 'V ostalem pa, bratje, prosimo vas in opominjamo v Gospodu Jezusu, da, kakor ste prejeli od nas, kako vam je živeti in Bogu ugajati, če dalje bolj rastete v tem;',
        2: 'Kajti veste, kake nauke smo vam dali po Gospodu Jezusu.',
        3: 'To namreč je volja Božja, posvečenje vaše, da se zdržujete kurbarije;',
        4: 'Da vé vsak izmed vas posodo svojo pridobiti si v posvečenji in časti;',
        5: 'Ne v poželenja strasti, kakor tudi pogani ne poznajoči Boga;',
        6: 'Da ne prestopate in ne prekanjate brata svojega v stvari; ker Gospod je kaznovatelj vsega tega, kakor smo vam tudi naprej povedali in pričali.',
        7: 'Kajti Bog nas ni poklical za nečistost, nego v posvečenje.',
        8: 'Zatorej kdor zameta, ne zameta človeka, nego Boga, njega, ki je tudi dal Duha svojega svetega med nas.',
        9: 'Za bratoljubje pa ni treba vam pisati; kajti sami ste od Boga učeni, ljubiti se med seboj;',
        10: 'Saj tudi ravnate tako z vsemi brati po vsej Macedoniji. Opominjamo pa vas, bratje, da vedno bolj rastete,',
        11: 'In da si prizadevate mirno živeti, in opravljate svoje, in delate sè svojimi rokami, kakor smo vam naročili;',
        12: 'Da živite spodobno pred njimi, ki so zunaj, in ne potrebujete nikogar.',
        13: 'Nočem pa, da bi ne vedeli, bratje, za pokojne, da se ne žalite, kakor tudi drugi, ki nimajo upanja.',
        14: 'Kajti če verujemo, da je Jezus umrl in vstal, tako bode tudi Bog pokojne po Kristusu peljal z njim.',
        15: 'To namreč vam pravimo v besedi Gospodovi, da mi živeči, ostali za prihod Gospodov, ne bodemo prehiteli pokojnih;',
        16: 'Ker Gospod sam bode v zapovedi, v glasu nadangelovem in v trombi Božji stopil dol z nebes, in mrtvi v Kristusu bodo vstali najprej.',
        17: 'Potem bodemo mi živeči, ostali, z njimi vred zgrabljeni v oblakih Gospodu naproti kvišku, in tako bodemo vedno z Gospodom.',
        18: 'Zato se opominjajte s temi besedami med seboj.',
    },
    5: {
        1: 'O časih pa in prilikah, bratje, ni treba da se vam piše;',
        2: 'Kajti sami veste na tanko, da dan Gospodov, kakor tat ponoči, tako pride;',
        3: 'Ko namreč pravijo: Mir in varnost, tedaj jih mahoma doleti poguba, kakor porodne bolečine nosečo, in ušli ne bodo.',
        4: 'Vi pa, bratje, niste v temi, da vas dan zagrabi kakor tat;',
        5: 'Vi vsi ste luči sinovi in sinovi dneva; nismo od noči ali temé.',
        6: 'Torej ne spimo kakor tudi drugi, nego čujmo in trezni bodimo.',
        7: 'Kajti speči spé ponoči, in upijanjajoči se upijanjajo se ponoči;',
        8: 'Mi pa, ki smo od dneva, bodimo trezni, ter oblecimo oklep vere in ljubezni, in za šlem upanje blaginje;',
        9: 'Kajti ni nas Bog pripravil za jezo, nego za zadobljenje blaginje po Gospodu našem Jezusu Kristusu,',
        10: 'Kateri je umrl za nas, da, naj čujemo ali spimo, z njem vred živimo.',
        11: 'Zato opominjajte se med seboj in izpodbujajte drug druzega, kakor tudi delate.',
        12: 'Prosimo pa vas, bratje, da znate nje, ki se trudijo med vami, in so vam predpostavljeni v Gospodu in vas svaré,',
        13: 'In da jih visoko čislate v ljubezni za njih delo. Mirujte med seboj.',
        14: 'Opominjamo pa vas, bratje, svarite neredne, prigovarjajte malodušnim, skrbite za slabotne, potrpežljivi boditi z vsemi.',
        15: 'Glejte, da ne vrne kdo komu hudega za hudo, nego vedno za dobrim hodite med seboj in proti vsem.',
        16: 'Radujte se vedno!',
        17: 'Molite neprestano!',
        18: 'Hvaležni bodite v vsem; kajti to je volja Božja v Kristusu Jezusu za vas.',
        19: 'Duha ne gasite.',
        20: 'Prerokovanj ne zaničujte.',
        21: 'Poskusite vse, dobro ohranite.',
        22: 'Vsakoršnega hudega se zdržujte.',
        23: 'On pa, Bog mirú, posvéti vas cele, in duh vaš popoln, in duša in telo naj se ohrani brez krivice o prihodu Gospoda našega Jezusa Kristusa.',
        24: 'Zvest je, ki vaš kliče, kateri bode tudi storil.',
        25: 'Bratje, molite za nas.',
        26: 'Pozdravite brate vse v svetem poljubu.',
        27: 'Rotim vas pri Gospodu, da se naj list bere vsem svetim bratom.',
        28: 'Milost Gospoda našega Jezusa Kristusa z vami! Amen. Tesaloničanom list prvi pisan iz Atén.',
    },
}
