NAME = 'SloStritar: Novi testament in Psalmi Davidovi Josipa Stritarja (1882)'
BOOK = 'James'

CHAPTERS = {
    1: {
        1: 'Jakob Boga in Gospoda Jezusa Kristusa hlapec, dvanajsterim rodom v raztrosu: zdravi!',
        2: 'Za vso radost vam bodi, bratje moji, ako ste padli v mnogotere izkušnjave,',
        3: 'Spoznavajoč, da izkušnja vere vaše nareja stanovitnost;',
        4: 'Stanovitnost pa imej delo popolno, da bodete popolni in dovršeni, v ničemur pogrešni.',
        5: 'Če pa ima kdo izmed vas premalo modrosti, prosi je naj od Boga, kateri vsem daje obilo, in nikomur ne oponaša; in dala se mu bode.',
        6: 'Prosi pa naj v veri, brez dvomljenja; kdor namreč dvomi, podoben je valu morskemu, ki ga veter goni in premetava.',
        7: 'Naj namreč ne misli tisti človek, da bode kaj dobil od Gospoda;',
        8: 'Mož omahljiv je nestanoviten na vseh potih svojih.',
        9: 'Ponaša pa naj se brat nizki v visokosti svoji;',
        10: 'Bogati pa v ponižnosti svoji, kajti minil bode kakor trave cvet.',
        11: 'Kajti vzšlo je solnce z vročino in posušilo je travo, in cvet njen je odpadel, in lepota lica njenega je izginila. Tako bode tudi bogatin zvenil na potih svojih.',
        12: 'Blagor možu, kateri prebije izkušnjavo; ker izkušen zadobode venec življenja, katerega je obljubil Gospod njim, ki ga ljubijo.',
        13: 'Nihče naj, izkušan, ne reče: Od Boga sem izkušan; kajti Bog je neizkušljiv v hudo, in sam ne izkuša nikogar.',
        14: 'Sleherni pa je izkušan, kogar lastna sla vleče in vabi;',
        15: 'Potem ko je sla izpočela, rodi pregreho, pregreha pa, ko je dovršena, rodí smrt.',
        16: 'Ne tavajte, bratje moji ljubljeni;',
        17: 'Vsak dober dar in vsako darilo popolno prihaja dol od očeta luči, pri katerem ni izpremembe ali osenčanja obrnitve.',
        18: 'Po volji svoji nas je rodil po besedi resnice, da bodimo neka prvina stvarî njegovih.',
        19: 'Zatorej, bratje moji ljubljeni, bodi vsak človek nagel v poslušanje, počasen v govorjenje, počasen v jezo;',
        20: 'Kajti jeza človekova ne dela pravice Božje.',
        21: 'Zato odloživši sleherno nesnago in obilost hudobije sprejmite v krotkosti vsajeno besedo, ki more rešiti duše vaše.',
        22: 'Bodite pa delalci besede in ne samo poslušalci, ki se sami slepé.',
        23: 'Ker če je kdo poslušalec besede, ne pa delalec, on je podoben možu, ki ogleduje v ogledalu rojstva svojega obličje;',
        24: 'Pogledal se je namreč in odšel, in hitro je pozabil, kakošen je bil.',
        25: 'Kdor pa je pogledal v popolno postavo svobode in v njej ostal on, ki ni postal pozabljiv poslušalec nego delalec dela, on bode srečen v dejanji svojem.',
        26: 'Če meni kdo med vami, da je bogaboječ, pa ne brzda jezika svojega, nego vara svoje srce, njegova bogaboječnost je ničeva.',
        27: 'Bogaboječnost čista in neoskrunjena pred Bogom in očetom je ta, skrbeti za sirote in vdove v njih stiski, neomadeževanega se braniti od sveta.',
    },
    2: {
        1: 'Bratje moji, ne imejte v licegledji vere našega Gospoda slave, Jezusa Kristusa.',
        2: 'Če namreč v zbor vaš vnide mož sè zlatimi prstani, v sijajni obleki, vnide pa tudi berač v umazani obleki,',
        3: 'In pogledate njega, ki ima sijajno obleko, in mu rečete: Ti sédí sem lepo, in beraču rečete: Ti stoj tam, ali pa sedí sem pod podnožje moje;',
        4: 'Ali niste dvomili v sebi in ste postali sodniki slabih misli?',
        5: 'Čujte, bratje moji ljubljeni: ni li Bog izbral beračev tega sveta bogatih v veri in dedičev kraljestva, katerega je obljubil njim, ki ga ljubijo.',
        6: 'Vi pa ste zaničevali berača. Ali vas ne zatirajo bogatini, in oni vas vlačijo pred sodbe?',
        7: 'Ali ne preklinjajo oni lepega imena, katero se vam prideva?',
        8: 'Če pa izpolnjujete kraljevo postavo, po pismu: "Ljubi bližnjega svojega kakor sebe," prav delate;',
        9: 'Če pa gledate na lice, greh delate, in postava vas dopričuje za prestopnike.',
        10: 'Kajti kdor bi izpolnjeval celo postavo, pregrešil pa se zoper eno, postal je vseh dolžan.',
        11: 'Kajti on, ki je rekel: "Ne prešestvuj," rekel je tudi: "Ne ubijaj"; če pa ne bodeš prešestvoval, ubijal pa, postal si prestopnik postave.',
        12: 'Tako govorite in tako ravnajte, kakor kateri bodete sojeni po svobode postavi;',
        13: 'Kajti sodba je neusmiljena njemu, ki ni delal usmiljenja, in usmiljenje se ne méni za sodbo.',
        14: 'Kaj pomaga, bratje moji, če kdo pravi, da ima vero, dél pa nima? Vera ga vendar rešiti ne more!',
        15: 'Če pa je brat nag ali sestra, in pogrešata vsakdanje hrane,',
        16: 'Pa bi jima kdo izmed vas rekel: "Hodita v miru, grejta se in sitita", a jima ne bi dali, kar je telesu potrebno, kaj pomaga?',
        17: 'Tako tudi vera, ako nima dél, mrtva je ob sebi.',
        18: 'Ali poreče kdo: Ti imaš vero, in jaz imam dela; pokaži mi vero svojo iz svojih dél, in jaz ti pokažem iz svojih dél vero svojo.',
        19: 'Ti veruješ, da je Bog eden; prav delaš; tudi hudi duhovi verujejo in groza jih je;',
        20: 'Hočeš pa vedeti, človek prazni, da je vera brez del mrtva?',
        21: 'Ali Abraham, oče naš, ni bil po delih opravičen, ko je nesel Izaka sina svojega na oltar?',
        22: 'Vidiš, da je vera sodelovala z deli njegovimi, in iz del se je vera popolnila?',
        23: 'In izpolnilo se je pismo, ki pravi: "Abraham pa je veroval Bogu, in vštevalo se mu je v pravico" in "prijatelj Božji" se je imenoval.',
        24: 'Vidite torej, da se iz dél opravičuje človek, in ne iz vere samo?',
        25: 'Enako pa se ni tudi Rahab kurba opravičila iz dél, ko je sprejela poslance in odpravila po drugi poti?',
        26: 'Kakor je namreč telo brez duha mrtvo, tako je tudi vera brez del mrtva.',
    },
    3: {
        1: 'Ne bodite mnogi učitelji, bratje moji, vedóč da dobimo večjo sodbo;',
        2: 'Kajti mnogo grešimo vsi. Če kdo v besedi ne greši, ta je popoln mož, zmožen brzdati tudi celo telo.',
        3: 'Glej, konjem devamo brzde v gobce, da so nam poslušni, in vladamo cel njih život.',
        4: 'Glej, tudi ladije, ki so tako velike, in ki jih silni vetrovi gonijo, vlada najmanjše krmilo, kamorkoli hoče vodnikov naklep.',
        5: 'Tako je tudi jezik majhen ud in se ponaša. Glej, majhen ogenj, kolikošen gozd zažge!',
        6: 'Tudi jezik je ogenj, svet krivice. Tako se kaže jezik med udi našimi, ki oskrunja cel život in zažiga rojstva kolo, njega pa zažiga pekel;',
        7: 'Kajti sleherno naravo zverî in tičev, laznine in morske živali kroti in je ukrotila narava človeška;',
        8: 'Jezika pa ne more krotiti nobeden človek; zlo neukrotno, poln smrtnega strupa!',
        9: 'Z njim blagoslavljamo Boga in očeta, in z njim preklinjamo ljudí, vstvarjene po podobi Božji;',
        10: 'Iz istih ust izhaja blagoslov in kletev. To, bratje, ne sme se tako goditi!',
        11: 'Saj pač studenec iz iste votline ne bruha sladko in grenko!',
        12: 'Saj, bratje moji, smokva ne more roditi oliv ali trta smokev; tako noben studenec delati vode solne in sladke.',
        13: 'Kdo je moder in razumen med vami? Kaže naj iz lepega vedenja dela svoja v krotkosti modri.',
        14: 'Če pa imate bridko gorečnost in prepirljivost v srci svojem, ne ponašajte se in lagajte zoper resnico.',
        15: 'To ni modrost, ki prihaja od zgoraj, nego zemeljska, počutna, vražja.',
        16: 'Kjer je namreč gorečnost in prepirljivost, tam nerednost in vse zlo delo.',
        17: 'Modrost pa od zgoraj je prvič čista, potem mirna, rahla, poslušna, polna usmiljenja in dobrega sadú, nedvomna in odkritosrčna.',
        18: 'Sad pa pravice se seje v miru njim, ki hranijo mir.',
    },
    4: {
        1: 'Odkod vojske in bitve med vami? Ne odtod, od želj vaših, vojskujočih se v vaših udih?',
        2: 'Poželite, a nimate; morite in želite iskreno, in ne morete doseči; borite se in vojskujete, a nimate, ker ne prosite;',
        3: 'Prósite, a ne dobite, ker slabo prosite, da zapravljate v slah svojih.',
        4: 'Prešestniki in prešestnice, ali ne veste, da je prijateljstvo sveta sovraštvo Božje? Kdor torej hoče biti svetu prijatelj, postane Bogu sovražnik.',
        5: 'Ali menite, da pismo prazno govori: Zavistno želi duh, ki se je vselil v nas?',
        6: 'Daje pa večjo milost; zato pravi: "Bog se upira prevzetnim, ponižnim pa daje milost."',
        7: 'Podložni torej bodite Bogu. Ustavljajte se hudiču, in bežal bode od vas;',
        8: 'Bližajte se Bogu, in bližal se vam bode. Očedite roke, grešniki, in očistite srca, omahljivci!',
        9: 'Čutite svoje gorjé in žalujte in jokajte; smeh vaš naj se izpreobrne v žalovanje, in radost v pobitost.',
        10: 'Ponižajte se pred Gospodom in povišal vas bode.',
        11: 'Ne obrekujte se med seboj, bratje; kdor obrekuje brata, in sodi brata svojega, obrekuje postavo in sodi postavo; če pa sodiš postavo, nisi delalec postave, nego sodnik.',
        12: 'Eden je postavodaj, ki more rešiti in pogubiti; ti kdo si, ki sodiš druzega?',
        13: 'Dejte torej vi, ki pravite: Danes ali jutri bodemo potovali v to mesto, in bivali ondi eno leto in tržili in pridobivali;',
        14: 'Ki ne veste, kaj bode jutri; kakošno namreč je življenje vaše? Kajti hlap je, ki se malo časa prikaže, potem pa izgine;',
        15: 'Mesto da govorite: Ako Bog hoče in bodemo živeli, bodemo tudi storili to ali ono.',
        16: 'Sedaj pa se ponašate v širokoustji svojem; vsako ponašanje táko je hudobno.',
        17: 'Kdor torej zna dobro delati in ne dela, njemu je greh.',
    },
    5: {
        1: 'Dejte torej, bogatini, jokajte javkajoč o bedah, katere vam pridejo;',
        2: 'Bogastvo vaše je iztrohnelo, in oblačila vaša so moli snedli;',
        3: 'Zlato vaše in srebro je zrujavelo, in njih ruja bode v pričanje vam, in žrla meso vaše kakor ogenj; zaklade ste zbirali v zadnjih dnevih.',
        4: 'Glej, plačilo delalcev, kateri so kosili polja vaša, ki ste ga jim utrgali, kriči; in vpitje ženjic prišlo je do ušes Gospoda Sabaot.',
        5: 'V požréšnosti ste na zemlji živeli in razkošnosti; srca svoja ste redili kakor o dnevi klanja.',
        6: 'Obsodili, ubili ste pravičnega; ne ustavlja se vam!',
        7: 'Bodite torej potrpežljivi, bratje, do prihoda Gospodovega. Glej, ratar pričakuje drazega sadú zemljé, potrpežljiv zanj, da dobi dež zgodnji in kasni;',
        8: 'Bodite potrpežljivi tudi vi, pokrepčajte srca svoja, ker prihod Gospodov se je približal.',
        9: 'Ne zdihujte drug zoper druzega, bratje, da ne bodete obsojeni; glej, sodnik stoji pred vrati!',
        10: 'Za zgled vzemite trpljenja in potrpežljivosti, bratje, preroke, kateri so govorili v imenu Gospodovem.',
        11: 'Glej, blagrujemo stanovitne; o stanovitnosti Jobovi ste čuli, in konec Gospodov ste videli; ker usmiljen je Gospod in milosrčen.',
        12: 'Pred vsem pa, bratje moji, ne prisezajte; ne pri nebu, ne pri zemlji, ne kake druge prisege; bodi pa vaše; dá, dá, in ne, ne! da ne padete pod sodbo.',
        13: 'Trpi li kdo med vami? moli naj; je li kdo dobre volje? prepeva naj.',
        14: 'Je-li kdo bolan med vami? pokliče naj k sebi starejšine občine, in molijo naj nad njim, ter pomazilijo ga z oljem v imenu Gospodovem;',
        15: 'In molitev vere bode pomagala bolniku, in ozdravil ga bode Gospod; in ako je storil grehe, odpustilo se mu bode.',
        16: 'Izpovedujte si med seboj grehe, in molite zase med seboj, da bodete ozdravljeni! Mnogo more krepka molitev pravičnega.',
        17: 'Elija je bil človek enakočuten z nami in v molitvi je molil, naj ne dežuje, in deževalo ni na zemlji tri leta in mesece tri;',
        18: 'In zopet je molil, in nebo je dalo dežja, in zemlja je rodila sad svoj.',
        19: 'Bratje, ako kdo med vami zabrede od resnice in ga kdo nazaj pripelje,',
        20: 'Vedi, da kdor nazaj pripelje grešnika s krive poti, rešil bode dušo njegovo smrti, in pokril grehov obilost.',
    },
}
