NAME = 'GerOffBiSt: Offene Bibel - Studienfassung'
BOOK = 'Deuteronomy'

CHAPTERS = {
    5: {
        1: 'Und Mose rief ganz Israel herbei und sprach zu ihnen: Höre, Israel, die Sitten (Gewohnheiten) und Gesetze (Rechtssachen), die ich diesen Tag (heute) vor euren Ohren rede, und übt sie ein und gebt acht, sie zu tun (machen)!',
        2: 'JHWH, unser Gott, hat einen Bund mit uns am Horeb geschlossen.',
        3: 'Nicht mit unseren Vätern hat JHWH diesen Bund geschlossen, sondern mit uns, wir, die an diesem Ort (hier) heute alle leben.',
        4: 'Von Angesicht zu Angesicht hat JHWH mit euch auf dem Berg aus der Mitte des Feuers heraus gesprochen –',
        5: 'ich stand zwischen JHWH und {zwischen} euch in jener Zeit um euch zu verkündigen das Wort JHWH s, denn ihr habt das Feuer gefürchtet und ihr seid nicht auf den Berg gestiegen – {folgendermaßen}:',
        6: 'Ich bin JHWH, dein Gott, der dich herausgeführt hat aus dem Land Ägypten, aus dem Haus der Sklaven (Sklavenhaus).',
        7: 'Es gibt für dich keine anderen Götter neben mir.',
        8: 'Nicht machst du dir ein Gottesbild, irgendeine Gestalt (künstlich gemachte Figur) von dem, was im Himmel oben und {von dem, was} auf der Erde unten und {von dem, was} im Wasser unterhalb der Erde [ist].',
        9: 'Nicht wirfst du dich nieder vor ihnen und nicht dienst du ihnen, denn ich bin JHWH, dein Gott, ein eifersüchtiger Gott, der heimsucht (aufsucht) die Sünde der Väter bei den Söhnen (Kindern) und bei den dritten und bei den vierten Nachkommen (Generation), die mich hassen,',
        10: 'und der Gnade übt (macht, erweist) an Tausenden, die mich lieben und halten (bewahren) meine Gebote.',
        11: 'Nicht sprichst du aus den Namen JHWH s, deines Gottes, zum Nichtigen (Lüge, frevelhaft), denn JHWH wird nicht ungestraft lassen den, der seinen Namen zum Nichtigen ausspricht.',
        12: 'Bewahre (Hüte) den Sabbattag um ihn zu heiligen, wie JHWH, dein Gott, dir befohlen hat.',
        13: 'Sechs Tage arbeitest du und machst alle deine Arbeit.',
        14: 'Aber (und) der siebte Tag ist Sabbat für JHWH, deinen Gott; nicht machst du irgendeine Arbeit, du und deine Söhne und deine Töchter und deine Sklave und deine Sklavin und dein Rind und dein Esel und all dein Vieh und der Fremdling, der in deinen Toren [ist], damit dein Sklave und deine Sklavin ruhen wie du.',
        15: 'Und erinnere dich daran (denke daran), dass du ein Sklave im Land Ägypten warst und JHWH, dein Gott, dich von dort herausgeführt hat mit starker Hand und mit ausgestrecktem Arm; deshalb hat dir JHWH, dein Gott, befohlen den Sabbattag zu halten (machen).',
        16: 'Ehre deinen Vater und deine Mutter wie JHWH, dein Gott, dir befohlen hat, damit deine [Lebens-] tage lange dauern und damit es dir gut geht in dem Land (auf der Erde), das JHWH, dein Got, dir geben wird (gibt)!',
        17: 'Nicht tötest (ermordest) du.',
        18: 'Und nicht brichst du die Ehe.',
        19: 'Und nicht klaust du.',
        20: 'Und nicht legst du gegen deinen Nächsten (Freund, Stammverwandten) ein falsches Zeugnis ab.',
        21: 'Und nicht begehrst du die Frau deines Nächsten; und nicht begehrst (wünschst) du das Haus deines Nächsten, sein Land (Feld) und seinen Sklaven und seine Sklavin, sein Rind und seinen Esel und alles, was dein Nächsten [hat].',
        22: 'Diese Worte hat JHWH gesprochen zu eurer ganzen Versammlung (Gemeinde, Volksversammlung, Menschenmenge) auf dem Berg aus der Mitte des Feuers, dem Gewölk und dem Wolkendunkel [mit] großer (lauter, mächtiger) Stimme und er fügte nichts hinzu; und er schrieb sie auf zwei steinerne Tafeln und er gab sie mir.',
    },
    6: {
        1: 'Und das [sind] das Gebot, die Gesetze und die Rechtsvorschriften, die JHWH, euer Gott [mir] aufgetragen hat euch zu lehren, damit ihr [danach] handelt (tut) in dem Land, [in] das ihr zieht, um es in Besitz zu nehmen,',
        2: 'damit du JHWH, deinen Gott, fürchtest, indem (um) [du] alle seine Gesetze und Gebote befolgst, die ich die ich dir [heute] auftrage – du, {und} dein Sohn und dein Enkel (Sohnessohn) [an] allen Tagen deines Lebens, und damit deine Tage lange währen (du lange lebst).',
        3: 'Nun (und) höre, Israel, und achte darauf, [danach] zu handeln (tun), damit es dir gut geht und damit du sehr zahlreich (groß) {werden} wirst, wie JHWH, der Gott deiner Vorfahren (Väter), es dir zugesichert (gesagt) hat, [in] einem Land, [das von] Milch und Honig [über] fließt.',
        4: 'Höre, Israel, JHWH [ist] unser Gott, JHWH [ist] eins (einzig, einer).',
        5: 'Darum (und) sollst du (liebe) JHWH, deinen Gott mit deinem ganzen Herzen und deinem ganzen Sein (Leben, Seele) und deiner ganzen Kraft lieben.',
        6: 'Und (dann) diese Worte, die ich dir heute auftrage, sollen (werden) in deinem Herzen sein.',
        7: '{und} Du sollst sie deinen Kindern (Söhnen) einprägen (einschärfen, wiederholen) (präge ein) und über sie sprechen, wenn du in deinem Haus sitzt und wenn du auf der Straße gehst, {und} wenn du liegst und wenn du aufstehst,',
        8: 'und sie als Zeichen auf deine Hand binden (binde) und sie werden als Bänder (Erinnerungszeichen, Stirnbänder) zwischen deinen Augen sein,',
        9: 'und du sollst (schreibe) sie auf die Türpfosten deines Hauses und auf deine Tore (Eingänge) schreiben.',
    },
    8: {
        12: 'Dass (Damit) du nicht isst und satt wirst und schöne Häuser baust und [be] wohnst.',
        14: 'und dein Herz stolz wird und du JHWH vergisst, deinen Gott, der dich herausgeführt hat aus dem Land Ägypten, aus dem Haus der Sklaven (Sklavenhaus).',
    },
    12: {
        13: 'Hüte dich, dass nicht du heraufsteigen lässt (opferst) deine Brandopfer an jedem Ort, den du siehst/sehen wirst.',
        14: 'Sondern wenn am Ort, den auswählen/erwählen wird JHWH […] dort sollst du aufsteigen lassen deine Brandopfer und dort wirst du tun alles, was ich dir geboten habe/gebiete.',
        15: 'Gemäß allem Begehren deiner Seele sollst du opfern und Fleisch essen, wie dich hat gesegnet JHWH dein Gott, der dir gegeben hat in allen deinen Toren; der Unreine und der Reine wird es essen wie Gazelle und wie Hirsch.',
        16: 'Nur das Blut sollst du nicht essen; du sollst es auf die Erde gießen wie Wasser.',
        17: 'Du sollst nicht vermögen zu essen in deinen Toren von dem Zehnten deines Getreides und deines Weines und deines Öls und und der Erstgeburt deines Rindes und deines Kleinviehs und deines ganzen Gelübdes, das du gegeben hast, und deines freiwilligen Opfers und der Abgaben deiner Hand.',
        18: 'Sondern vor JHWH deinem Gott wirst du sie essen am Ort, den aussuchen wird JHWH dein Gott; du und dein Sohn und deine Tochter und dein Sklave und deine Magd und der Levit in deinen Toren; und du wirst dich freuen vor JHWH, deinem Gott, in jeder Unternehmung deiner Hand.',
        19: 'Hüte dich, dass du nicht verlässt den Leviten alle deine Tage in deinem Land.',
        20: 'Wenn es wird erweitern JHWH dein Gott deine Grenzen, wie er gesprochen hat zu dir und du sagen wirst: „Ich will essen Fleisch“, weil deine Seele gelüstet, Fleisch zu essen, dann sollst du mit aller Lust deiner Seele Fleisch essen.',
        21: 'Wenn fern sein wird von dir der Ort, den auserwählen wird JHWH, dein Gott, um dort zu setzen seinen Namen, dann du wirst opfern von deinen Rindern und von deinem Kleinvieh, das JHWH dir gegeben hat, wie ich dir geboten habe, und du wirst essen in deinen Toren in aller Lust deiner Seele.',
        22: 'Nur/Gewiss, wie er (man) wird essen die Gazelle und den Hirsch, so wirst du sie essen, der Reine und der Unreine miteinander (i.s.v. „beide“) werden es essen.',
        23: 'Nur […] nicht zu essen das Blut, denn das Blut [ist] die Seele und du sollst nicht essen die Seele mit dem Fleisch.',
        24: 'Du sollst sie nicht essen im Land [sondern] du sollst sie ausschütten wie Wasser.',
        25: 'Du sollst sie nicht essen, damit es dir gut gehen wird und deinen Söhnen nach dir, denn du tust Recht in den Augen JHWH s.',
        26: 'Nur deine Heiligtümer, die bei dir sind und deine Gelübde sollst du nehmen und du sollst gehen an den Ort, den JHWH erwählen wird.',
        27: 'Und du sollst tun dein verbrennen des Fleisches und des Blutes auf einem Altar JHWH s, deines Gottes und das Blut deiner Opfer soll ausgegossen werden auf einen Altar JHWHs, deines Gottes, aber das Fleisch sollst du essen.',
        28: 'Halte und höre alle diese Worte, die ich dir gebiete, damit es dir gut gehen wird und deinen Söhnen nach dir für immer; wenn du tun wirst das Gute und das Rechte in den Augen JHWH, deines Gottes.',
    },
    13: {
        4: 'Hört nicht auf die Worte dieses Propheten oder auf diesen Träumer von Träumen, denn JHWH, euer Gott, prüft euch um zu erkennen, ob ihr JHWH, euren Gott, mit eurem ganzen Herzen und eurer ganzen Seele liebt.',
    },
    14: {
        22: 'Verzehnte (Du sollst/musst verzehnten) allen Ertrag deiner Aussaat, der aus dem Feld hervorgeht, Jahr [um] Jahr!',
        23: 'Verzehre (Du sollst/musst verzehren) ihn im Angesicht (in der Gegenwart) JHWH s, deines Gottes, an dem Ort, den er erwählen wird, um seinen Namen dort wohnen zu lassen: Den Zehnten deines Getreides, deines Weins und deines Öls sowie die Erstgeburt deiner Rinder und deines Kleinviehs, damit du lernst, JHWH, deinen Gott, alle Tage (immer) zu fürchten.',
        24: '{und} Wenn der Weg von dir aus zu groß ist, wenn du ihn nicht tragen kannst, wenn der Ort von dir zu fern ist, den JHWH erwählen wird, um seinen Namen dort niederzulegen, wenn JHWH, dein Gott, dich segnen wird (segnet, segnen soll):',
        25: 'Gib (du sollst/musst geben) ihn hin für Silber und halte das Silber fest in deiner Hand und gehe zu dem Ort, den JHWH erwählen wird.',
        26: 'Gib (du darfst/sollst/musst geben) das Silber aus für alles, was dein Herz (Seele, Verlangen, Kehle) begehrt, für Rinder und Kleinvieh, für Wein und Bier und für alles, nach dem dein Herz dich gelüstet, und verzehre es dort im Angesicht (in der Gegenwart) JHWH s, deines Gottes und freue dich (du sollst/musst dich freuen), du und dein Haus (Familie, Haushalt)!',
        27: 'Und den Leviten, der in deinen Toren [wohnt]: Vergiss (du darfst vergessen) ihn nicht, denn er hat nicht Erbanteil und Besitz wie du!',
        28: 'Nach jedem dritten Jahr sollst (schaffe) du den ganzen Zehnten deines Ertrags in diesem Jahr bei Seite schaffen und in deiner Stadt lassen,',
        29: 'und es sollen kommen der Levit, denn er hat nicht Erbanteil und Besitz wie du, {und} der Fremde, {und} der Waise und die Witwe, die in deinen Toren [wohnen], und ihn verzehren und satt sein, damit JHWH, dein Gott, dich segnet bei allem Werk deiner Hand, das du verrichtest.',
    },
    16: {
        11: 'Und du sollst dich vor JHWH, deinem Gott, freuen, du und dein Sohn und deine Tochter und dein Sklave und deine Sklavin und der Levit, der in deinen Toren (ist) und der Fremde und die Waise und die Witwe, die in deiner Mitte (sind) an der Stätte, die JHWH, dein Gott erwählt hat, um seinen Namen dort wohnen zu lassen. 14 Und du sollst dich an deinem Fest freuen, du und dein sohn und deine Tochter und dein Sklave und deine Sklavin und der Levit und der Fremde und die Waise, die in deinen Toren (sind).',
    },
    29: {
        28: 'Was verborgen ist (das Verborgene), ist (gehört) JHWH unserem Gott und was offenbart ist, ist (gehört) uns und unseren Kindern (Söhnen/Nachkommen) für immer in Ewigkeit (in Zukunft), zu tun alle Worte (Dinge) dieser Weisung (Gesetz/Anweisung).',
    },
    32: {
        35: 'Mein ist Rache und Vergeltung, zu der Zeit, ihr Fuß wird wanken. Denn nahe ist der Tag ihres Verderbens und schnell kommt das Vorbereitete zu ihnen.',
        39: 'Nun seht, dass ich, ich es [bin], und kein Gott mit (neben) mir! Ich, ich werde töten und am Leben erhalten (lebendig machen), ich habe zerschmettert und ich, ich werde heilen. Und [es ist] keiner, der von meiner Hand entreißt (rettet, wegnimmt, entzieht).',
        43: 'Ihr Nationen preist sein Volk. Denn Blut seiner Sklaven rächt er und Rache bringt er zu den Feinden und den Ackerboden seines Volkes entsühnt er.',
        48: 'Und JHWH sprach zu Mose an eben diesem Tag {und sagte}:',
    },
}
