NAME = 'GerOffBiSt: Offene Bibel - Studienfassung'
BOOK = 'I Chronicles'

CHAPTERS = {
    1: {
        1: 'Adam, Set, Enosch.',
        2: 'Kenan, Mahalalel, Jered.',
        3: 'Henoch, Metuschelach, Lamech.',
        4: 'Noach, Sem, Ham und Jafet.',
        5: '[Die] Söhne Jafets [sind] Gomer und Magog und Madai und Jawan und Tubal und Meschech und Tiras.',
        6: 'Und [die] Söhne Gomers [sind] Aschkenas und Difat und Togarma.',
        7: 'Und [die] Söhne Jawans [sind] Elischa und Tarschisch, [die] Kittäer und [die] Rodaniter.',
        8: '[Die] Söhne Hams [sind] Kusch und Mizrajim, Put und Kanaan.',
        9: 'Und [die] Söhne Kuschs [sind] Seba und Hawila und Sabta und Ragma und Sabtecha. Und [die] Söhne Ragmas [sind] Saba und Dedan.',
        10: 'Und Kusch hatte (hat) gezeugt den Nimrod, der [dann] angefangen hat, zu werden ein Machthaber auf [der] Erde.',
        11: 'Und Mizrajim hat gezeugt die Luditer und die Anamiter und die Lehabiter und die Naftuhiter.',
        12: 'Und die Patrositer und die Kasluhiter, dass ausgegangen sind von dort [die] Philister, und die Kaftoriter.',
        13: 'Und Kanaan hat gezeugt den Sidon, seinen Erstgeborenen [Sohn], und den Het.',
        14: 'Und den Jebusiter und den Amoriter und den Girgaschiter.',
        15: 'Und den Hiwiter und den Arkiter und den Siniter.',
        16: 'Und den Arwaditer und den Zemariter und den Hamatiter.',
        17: '[Die] Söhne (Nachkommen) Sems [sind] Elam und Assur und Arpachschad und Lud und Aram und Uz und Hul und Geter und Meschech.',
        18: 'Und Arpachschad hatte (hat) gezeugt den Schelach und Schelach hat gezeugt [dann] den Eber.',
        19: 'Und für Eber sind geboren worden zwei Söhne, [der] Name des einen [ist] Peleg, entsprechend (denn/weil) in seinen Tagen es war zerteilt worden die Erde, und [der] Name seines Bruders [ist] Joktan.',
        20: 'Und Joktan hat gezeugt den Almodad und den Schelef und den Hazarmawet und den Jerach.',
        21: 'Und den Hadoram und den Usal und den Dikla.',
        22: 'Und den Obal und den Abimaël und den Saba.',
        23: 'Und den Ofir und den Hawila und den Jobab. Alle diese [sind] Söhne Joktans.',
        24: 'Sem, Arpachschad, Schelach.',
        25: 'Eber, Peleg, Regu.',
        26: 'Serug, Nahor, Terach.',
        27: 'Abram, der [ist] Abraham.',
        28: '[Die] Söhne Abrahams [sind] Isaak und Ismaël.',
        29: 'Diese [sind] ihre Genealogien: der Erstgeborene [Sohn] Ismaëls [ist] Nebajot, und [dann] Kedar und Adbeel und Mibsam.',
        30: 'Mischma und Duma, Massa, Hadad und Tema.',
        31: 'Jetur, Nafisch und Kedma; diese, sie [sind die] Söhne Ismaëls.',
        32: 'Und [die] Söhne Keturas, der Nebenfrau Abrahams: sie hat geboren den Simran und Jokschan und Medan und Midian und Jischbak und Schuach. Und [die] Söhne Jokschans [sind] Saba und Dedan.',
        33: 'Und [die] Söhne Midians [sind] Efa und Efer und Henoch und Abida und Eldaga. Alle diese [sind die] Söhne Keturas.',
        34: 'Und es zeugte Abraham den Isaak. [Die] Söhne Isaaks [sind] Esau und Israel.',
        35: '[Die] Söhne Esaus [sind] Elifas, Reguël und Jëusch und Jalam und Korach.',
        36: "[Die] Söhne Elifas' [sind] Teman und Omar, Zefo und Gatam, Kenas und Timna und Amalek.",
        37: '[Die] Söhne Reguëls [sind] Nahat, Serach, Schamma und Misa.',
        38: 'Und [die] Söhne Seïrs [sind] Lotan und Schobal und Zibon und Ana und Dischon und Ezer und Dischan.',
        39: 'Und [die] Söhne Lotans [sind] Hori und Hemam, und [die] Schwester Lotans [ist] Timna.',
        40: '[Die] Söhne Schobals [sind] Alwan und Manahat und Ebal, Schefi und Onam. Und [die] Söhne Zibons [sind] Aja und Ana.',
        41: '[Die/der?] Nachkommen? Anas [sind/ist?] Dischon, und [die] Söhne Dischons [sind] Hemdan und Eschban und Jitran und Keran.',
        42: '[Die] Söhne Ezers [sind] Bilhan und Saawan [und] Akan. [Die] Söhne Dischans: Uz und Aran.',
        43: 'Und diese [sind] die Könige, die regiert hatten (haben) im Lande Edom, bevor ein König regiert hat von [den] Söhnen (Nachkommen) Israels: Bela, [der] Sohn Beors, und [der] Name seiner Stadt [ist] Dinhaba.',
        44: 'Und es starb Bela, und es regierte nach ihm Jobab, der Sohn Serachs aus Bozra.',
        45: 'Und es starb Jobab, und es regierte nach ihm Huscham, aus [dem] Land der Temaniter.',
        46: 'Und es starb Huscham, und es regierte nach ihm Hadad, [der] Sohn Bedads, er vernichtete Midian im Gebiet Moabs, und [der] Name seiner Stadt [ist] Awit.',
        47: 'Und es starb Hadad, und es regierte nach ihm Samla aus Masreka.',
        48: 'Und es starb Samla, und es regierte nach ihm Schaul aus Rehobot [an] dem Strom.',
        49: 'Und es starb Saul, und es regierte nach ihm Baal-Hanan, [der] Sohn Achbors.',
        50: 'Und es starb Baal-Hanan, und es regierte nach ihm Hadad, und [der] Name seiner Stadt [ist] Pagu, und [der] Name seiner Frau [ist] Mehetabel, [die/eine] Tochter Matreds, [der] Tochter Me-Sahabs.',
        51: 'Und es starb Hadad. Und es waren [dann die] Häuptlinge Edoms: [Der] Häuptling Timna, [der] Häuptling Alwa, [der] Häuptling Jetet.',
        52: '[Der] Häuptling Oholibama, [der] Häuptling Ela, [der] Häuptling Pinon.',
        53: '[Der] Häuptling Kenas, [der] Häuptling Teman, [der] Häuptling Mibzar.',
        54: '[Der] Häuptling Magdiël, [der] Häuptling Iram. Diese [sind die] Häuptlinge Edoms.',
    },
    21: {
        1: 'Und {ein} Satan trat hin (stellte sich, trat auf) gegen Israel und er verführte (reizte, verlockte, verleitete) David, Israel zu zählen.',
        2: 'Und David sprach zu Joab und zu den Mächtigen (Obersten, Fürsten) des Volks: Geht, zählt Israel, von Beerscheba {und} bis Dan, und bringt (lasst kommen, tragt vor) mir, dass ich kenne (weiß) ihre Zahl (Aufzählung, Liste).',
        7: 'Und es war böse (schlecht) in den Augen Gottes diese Sache, und er schlug (schädigte, verheerte) Israel.',
        8: 'Und David sprach zu Gott: Ich habe sehr gesündigt (habe mich sehr verfehlt), dass (indem) ich diese Sache getan habe! Und nun, nimm doch weg die Sünde (Schuld) deines Knechtes (Dieners, Sklaven), denn ich habe sehr töricht gehandelt (ich habe mich sehr versündigt)!',
    },
    28: {
        1: 'Da versammelte David alle Fürsten Israels vor dem König, die Stammesfürsten, die Fürsten der Einheiten, welche dem König dienten, die Fürsten der tausenden, die Fürsten der hunderte, sowie die Fürsten des Erbtem und Erworbenem, und seine Weißen mit den Eunuchen und die Helden und alle starken Männer in Jerusalem.',
        2: 'Da richtete sich der König David auf und sprach: Hört mich an, meine Brüder und mein Volk, denn wer ist mit mir ein Haus als Ruhestätte für die Bundeslade zu bauen, wo unser Herr seine Füße anlegen kann und was ich zu bauen vorhatte.',
        3: 'Gott sagte mir: Baue meinem Namen kein Haus, denn du bist ein Kriegsmann und du hast Blut vergossen.',
        4: 'Der Herr, der Gott Israels erwählte mich aus meines Vaters Haus, um König über Israel für immer zu werden, denn er hat sich Juda erwählt zum Höchsten und das Haus meines Vaters [hat er erwählt] und von den Söhnen meines Vaters wollte er, dass ich über ganz Israel regieren soll.',
        5: 'Von allen Söhnen – denn der Herr hat mir viele Söhne gegeben – hat er sich Salomo, meinen Sohn, ausgesucht, auf dem Thron des Königreiches des Herrn über ganz Israel zu sitzen.',
        6: 'Und der sprach zu mir: Salomo, dein Sohn, wird mir mein Haus und meinen Vorhof bauen, denn ich habe ihn als meinen Sohn erwählt und ich werden sein Vater sein.',
        7: 'Ich werde seine Herrschaft auf ewig bestätigen, wenn er beständig sein und meine Gebote und mein Recht bis an diesen Tag halten wird.',
        8: 'Jetzt vor den Augen ganz Israels, der Menge des Herrn, vor den Ohren des Herrn haltet und fordert alle Gebote den Herrn eures Gottes, sodass ihr das ganze gute Land erben werdet und euren Söhnen bis in Ewigkeit weiter vererben könnt.',
        9: 'Du aber, mein Sohn Salomo, kenne den Gott deines Vaters und diene ihm von ganzem Herzen und liebe ihn von ganzer Seele! Denn der Herr will die Herzen und alles Trachten des Denkens versteht er. Wenn wir ihn suchen, wird er sich von dir finden lassen und wenn wir ihn verlassen, dann wird er dich für immer verlassen.',
        10: 'Nun siehe, denn der Herr hat dich auserwählt, einen starken Tempel zu bauen, und du sollst es tun.',
        11: 'Und David gab Salomo, seinem Sohn, das Modell für die Vorhalle des Tempels und für sein Haus, und seine Schatzkammer und seine Obergemache und seine inneren Räume und ein Haus für den Deckel der Bundeslade,',
        12: 'und ein Modell von allem, das im Geist von ihm war, für die Vorhöfe des Hauses JHWH s und für alle Zimmern ringsumher, für die Schätze des Hauses Gottes, und für die Schätze des Heiligen,',
        13: 'und für die Abteilungen der Priester und der Leviten und für alle Arbeiten des Dienstes im Hause JHWH s, und für alle Gegenstände des Dienstes im Hause JHWHs.',
        14: 'Für das Gold in dem Gewicht zu dem Gold, für alle Gegenstände des Dienstes und den Dienst, und für alle Gegenstände die Silber sind im Gewicht, für alle Gegenstände des Dienstes und den Dienst.',
        15: 'Und das Gewicht für die goldenen Leuchter und ihre goldenen Lampen, im Gewicht des Leuchters und der Leuchter und seiner Lampen, und für die silbernen Leuchter im Gewicht für den Leuchter und seine Lampen, nach dem Dienst des Leuchters und des Leuchters.',
        16: 'Und das Goldgewicht der Tische der Schaubrote, für den Tisch und den Tisch. Und das Silber für die silbernen Tische.',
        17: 'Und der Fleischgabeln und der Gefäße und der Trinkschalen von lauterem Gold. Und für die goldenen Becher im Gewicht für den Becher und den Becher und für die silbernen Becher im Gewicht für den Becher und den Becher.',
        18: 'Und für den Altar des Räucherwerks das geläuterte Gold im Gewicht. Und für das Modell des Wagens der goldenen Cherubim, die sich ausbreiteten und bedeckten die Lade des Bundes JHWH s.',
        19: 'Das alles ist in einer Schrift von der Hand JHWH s, die mich belehrte, in allen Arbeiten des Entwurfs.',
        20: 'Und es sprach David zu Salomo, seinem Sohn: Sei stark und mutig, mache es und fürchte dich nicht und werde nicht mutlos. Denn JHWH, der Herr, mein Gott, ist mit dir, er wird dich nicht verlassen und nicht zurücklassen, bis vollendet ist, alle Arbeit am Dienste des Hauses JHWHs.',
        21: 'Und siehe die Abteilungen der Priester und der Leviten, zu allen Diensten im Hause des Gottes; Und mit dir in allen Arbeiten für alles bereit, in der Weisheit für alle Dienste, und die Obersten und alles Volk für alle deine Reden.',
    },
}
