NAME = 'GerOffBiSt: Offene Bibel - Studienfassung'
BOOK = 'Ecclesiastes'

CHAPTERS = {
    1: {
        1: 'Worte des Kohelet, eines Sohnes Davids, eines Königs in Jerusalem:',
        2: 'Hauch, absoluter Hauch, pflegte Kohelet zu sagen, Hauch, absoluter Hauch, das alles ist Hauch.',
        3: 'Was bleibt dem Menschen übrig von all seinen Mühen, mit denen er sich abmüht unter der Sonne?',
        4: 'Ein Geschlecht geht und ein Geschlecht kommt, aber die Erde besteht für immer.',
        5: 'Die Sonne geht auf und die Sonne geht unter und zu ihrem Ort lechzt sie um dort [wieder] aufzugehen.',
        6: 'Er geht nach Süden und dreht sich nach Norden, drehend, drehend weht der Wind, kreisend kehrt er zurück, der Wind.',
        7: 'Alle Flüsse fließen ins Meer, aber das Meer wird nicht voll; an den Ort, an dem die Flüsse entspringen, dorthin kehren sie zurück, um [wieder] zu entspringen.',
        8: 'Alle Worte mühen sich ab, [doch] nicht kann jemand sprechen. Das Auge wird nicht satt vom Sehen, und das Ohr nicht gefüllt vom Hören.',
        9: 'Das, was geschah, das wird [wieder] geschehen, und das, was getan wurde, {das} wird wieder getan werden, und es gibt überhaupt nicht Neues unter der Sonne.',
        10: 'Gibt es eine Sache, von der man sagt: Siehe da, das ist neu? Das ist bereits geschehen in den Zeiten, die vor uns waren.',
        11: 'Es gibt keine Erinnerung an die Vorherigen und auch an die Nachfolgenden, die [noch] sein werden, wird es keine Erinnerung geben bei denen, die nach ihnen sein werden.',
        12: 'Ich, Kohelet, war König über Israel in Jerusalem.',
        13: 'Und ich richtete mein Herz darauf, zu untersuchen und zu erforschen in der Weisheit alles, was getan wird unter der Sonne. Solch schlechte Arbeit hat Gott den Menschenkindern gegeben, damit sie sich damit abmühen.',
        14: 'Ich sah all die Taten, die getan wurden unter der Sonne, und siehe, das alles ist Hauch und Haschen nach Wind.',
        15: 'Verbogenes kann nicht gerade sein, und Verlorenes kann nicht gezählt werden.',
        16: 'Das sprach ich in meinem Herzen: Siehe, ich habe die Weisheit vergrößert und vermehrt mehr als jeder, der vor mir über Jerusalem war (herrschte), und mein Herz hat gesehen (kennt) viel Weisheit und Wissen.',
        17: 'Und ich richtete mein Herz darauf, Weisheit zu erkennen und Tollheit und Torheit zu erkennen. Ich erkannte, dass auch das Streben nach Wind ist.',
        18: 'Denn wo viel Weisheit ist, ist viel Ärger, und wer Wissen vermehrt, vermehrt Sorge.',
    },
    2: {
        1: 'Da sprach ich in meinem Herzen: Auf geht’s, ich versuch’s mit Freude und genieße Gutes! Aber siehe, auch das ist Hauch.',
        2: 'Zum Lachen sagte ich: Du bist verrückt! Und zur Freude: Was machst (schaffst) du?',
        3: 'Ich beschloss in meinem Herzen, meinen Leib mit Wein zu laben währen das [mich] Herz leitet in Weisheit, und Torheit zu ergreifen bis ich sähe, was gut wäre für die Menschenkinder was sie tun unter dem Himmel, die Anzahl der Tage ihres Lebens.',
        4: 'Ich machte Taten groß: Ich bauten mir Häuser, ich pflanzte mir Weinberge,',
        5: 'ich machte mir Gärten und Parks, ich pflanzte in ihnen Bäume von jeder Frucht;',
        6: 'ich machte mir Teiche aus Wasser, um aus ihnen zu bewässern den Wald der sprießenden Bäume.',
        7: 'Ich kaufte Knechte und Mägde und hatte Hausgeborene, auch hatte ich eine größere Herde an Rindern und Schafen als jeder, der vor mir in Jerusalem war.',
        8: 'Ich sammelte mir auch Silber und Gold und Besitz von Königen und Ländern; ich machte mir Sänger und Sängerinnen und Vergnügen der Menschenkinder, jede Menge Frauen',
        9: 'und ich wurde mehr und mehr größer, als jeder, der vor mir in Jerusalem war, auch die Weisheit blieb bei mir.',
        10: 'Und alles, was meine Augen begehrten, verwehrte ich ihnen nicht und hielt von meinem Herzen keine der ganzen Freuden zurück, dass mein Herz fröhlich war von all seiner Mühe, und das war mein Anteil von all meinen Mühen',
        11: 'Und ich wandte mich all meinen Werken zu, die meine Hand geschaffen hatte, und die Mühen, die ich mich abmühte um zu schaffen, aber siehe, das alles war Hauch und Haschen nach Wind, und es gibt nichts, das über bleibt.',
        12: 'Und ich wandte mich um die Weisheit und die Tollheit und die Torheit zu betrachten, denn was [wird] der Mensch [tun], der nach dem König kommt? Das, was man schon getan hat.',
        13: 'Und ich sah, dass es einen Vorteil gibt der Weisheit gegenüber der Torheit wie des Lichts gegenüber der Finsternis:',
        14: 'Der Weise [hat] seine Augen im Kopf, aber der Tor geht in der Finsternis, aber ich merkte auch, dass ein [und dasselbe] Schicksal sie alle trifft.',
        15: 'Da sagte ich in meinem Herzen: Wenn das Schicksal des Toren auch mich ereilt, welchen Vorteil hat es dann, dass ich weise gewesen bin? Und ich sprach in meinem Herzen: Auch das ist Hauch.',
        16: 'Denn es gibt keine Erinnerung für immer, weder an die Weisen noch an die Toren, weil in den Tagen, die kommen, bereits das alles vergessen ist; und wie der Weise stirbt, so [auch] der Tor.',
        17: 'Und ich hasste das Leben, denn es war übel zu mir die Arbeit die getan wurde unter der Sonne, denn das alles war Hauch und Haschen nach Wind.',
        18: 'Und ich hasste all meine Arbeit, mit dem ich mich abmühte unter der Sonne, die ich dem Menschen hinterlasse, der nach mir sein wird.',
        19: 'Und wer weiß, ob er weise sein wird oder töricht? Aber er wird herrschen über all meine Werke, die ich mühevoll und weise getan habe unter der Sonne, auch das ist Hauch.',
        20: 'Da wandte ich um mein Herz verzweifeln zu lassen über all die Arbeit, mit der ich mich abgemüht hatte unter der Sonne.',
        21: 'Denn es gibt einen Menschen, der sich in Weisheit und Wissen und Können abgemüht hat und einem [anderen] Menschen, der sich nicht darin abgemüht hat, wird es als Erbteil gegeben werden, auch das ist Hauch und Haschen nach Wind.',
        22: 'Denn was bekommt der Mensch von all seiner Arbeit und dem Streben seines Herzens, mit der er sich abmüht unter der Sonne?',
        23: 'Denn alle seine Tage sind Leiden und Ärger ist seine Beschäftigung, auch bei Nacht ruht sein Herz nicht, auch das ist Hauch.',
        24: 'Nichts ist besser für den einen Menschen als dass er isst und trinkt und seine Seele Gutes sehen lässt bei seiner Arbeit. Auch dies sah ich, dass es aus der Hand Gottes kommt.',
        25: 'Denn wer kann essen und fröhlich sein ohne mich?',
        26: 'Denn dem Menschen, der gut vor ihm ist, gibt er Weisheit und Wissen und Freude, aber dem Sünder gibt er Arbeit, dass sammle und häufe, damit es dem vor Gott Guten gegeben werde. Auch das ist Hauch und Haschen nach Wind.',
    },
    3: {
        1: 'Für alles [gibt es] eine bestimmte Zeit, und jedes Vorhaben unter dem Himmel [hat] seine Zeit.',
        2: 'Zeit um zu gebären und Zeit, um zu sterben, Zeit um zu pflanzen und Zeit um gepflanztes auszureißen,',
        3: 'Zeit um zu töten und Zeit um zu heilen, Zeit um abzureißen und Zeit um zu bauen,',
        4: 'Zeit um zu weinen und Zeit um zu lachen, Zeit um zu klagen und Zeit um zu springen,',
        5: 'Zeit um Steine wegzuwerfen und Zeit um Steine zu sammeln, Zeit um zu umarmen und Zeit um Abstand zu nehmen vom Umarmen,',
        6: 'Zeit um zu suchen und Zeit um verloren gehen zu lassen, Zeit um aufzubewahren und Zeit um wegzuwerfen,',
        7: 'Zeit um zu zerreißen und Zeit um zu nähen, Zeit um zu schweigen und Zeit um zu reden,',
        8: 'Zeit um zu lieben und Zeit um zu Hassen, Zeit des Kriegs und Zeit des Friedens.',
        9: 'Was bleibt dem Schaffenden davon über, dass er sich abmüht?',
        10: 'Ich habe die Arbeit gesehen, die Gott den Menschenkindern gegeben hat, damit sie sich damit abmühen.',
        11: 'Das alles hat er schön gemacht zu seiner Zeit, auch hat er die Ewigkeit in ihr Herz gegeben, nur kann der Mensch das Werk nicht verstehen, das Gott von Anfang bis Ende getan hat.',
        12: 'Da merkte ich, dass es nichts Besseres gibt als diese: Fröhlich zu sein und Gutes zu tun in seinem Leben.',
        13: 'Aber jeder Mensch, der isst und trinkt und sieht Gutes bei all seinen Mühen, das [ist] ein Geschenk Gottes.',
        14: 'Ich merkte, dass alles was Gott tut, das ist für immer, zu ihm ist nichts hinzuzufügen noch von ihm wegzunehmen, und Gott tut [das/so], dass man sich vor ihm fürchtet.',
        15: 'Was geschieht, das [gab es] bereits, und was zu geschehen bestimmt ist, ist bereits geschehen, und Gott sucht nach dem Verschwunden.',
        16: 'Und weiter sah ich unter der Sonne Orte des Gerichts, dort [war] Unrecht, und Stätten der Gerechtigkeit, und dort [war] Ungerechtigkeit.',
        17: 'Ich sprach in meinem Herzen: Die Gerechten und die Ungerechten wird Gott richten, denn es gibt eine Zeit für jedes Vorhaben und jedes Tun dort.',
        18: 'Ich sprach in meinem Herzen: Wegen der Menschenkinder prüft Gott sie, damit sie selbst an sich sehen, dass sie wie Vieh sind.',
        19: 'Denn das Schicksal der Menschenkinder und das Schicksal des Viehs ist ein [und dasselbe] Schicksal für sie: Wie der eine Tod, so [ist] auch jener Tod, und es ist ein [und derselbe] Atem bei allen, und es gibt keinen Vorzug des Menschen vor dem Vieh, denn alles ist Hauch.',
        20: 'Alles geht an einen Ort, das alles ist aus Staub entstanden und das alles wird wieder zu Staub.',
        21: 'Wer weiß, ob der Atem des Menschen nach oben aufsteigt und der Atem des Viehs unter die Erde absteigt?',
        22: 'Und ich sah, dass es nichts Besseres gibt, als dass der Mensch fröhlich ist bei seiner Arbeit, denn das ist sein Anteil. Denn wer könnte ihn dazu bringen zu sehen, was nach ihm sein wird?',
    },
    4: {
        1: 'Und ich wandte mich um und sah auf all die Gewalttaten, die getan werden unter der Sonne, und siehe, [da waren] Tränen der Unterdrückten, und es gab keinen, der sie tröstete; und die Hand ihrer Unterdrücker war so mächtig, dass es keinen gab, der sie tröstete.',
        2: 'Und ich pries die Toten, die bereits gestorben waren, mehr als die Lebendigen, die noch ihre Leben haben.',
        3: 'Und besser als diese beiden [ist], wer noch nicht gewesen ist, der die üble Arbeit noch nicht gesehen hat (kennt), die unter der Sonne getan wird.',
        4: 'Und ich sah auf all die Mühen und all die Tüchtigkeit bei der Arbeit, dass es Eifersucht eines Menschen gegen seinen Nächsten ist. Auch das ist Hauch und Haschen nach Wind.',
        5: 'Der Tor legt seine Hände ineinander und isst sein eigenes Fleisch.',
        6: 'Besser eine Handvoll Ruhe als beide Hände voll Arbeit und Haschen nach Wind.',
        7: 'Und ich wandte mich um und sah Hauch unter der Sonne:',
        8: 'Es gibt einen, der hat keinen zweiten, auch kein Kind, und einen Bruder hat er nicht. Kein Ende hat all seine Mühe, auch seine Augen werden nicht satt am Reichtum. Für wen mühe ich mich ab lass meine Seele zu kurz kommen an Gutem? Auch das ist Hauch und eine üble Beschäftigung.',
        9: 'Die Zwei sind besser als der einzelne, denn es gibt für sie einen guten Lohn für ihre Mühen.',
        10: 'Denn wenn sie fallen, richtet einer seinen Gefährten auf, aber wehe dem Einzelnen, der fällt, denn es gibt keinen zweiten, um ihn aufzurichten.',
        11: 'Auch wenn zwei schlafen, wärmen sie sich, aber wie soll der einzelne warm werden?',
        12: 'Und wenn einer den einzelnen überwältigt, die Zwei [können] ihm widerstehen, und ein dreifacher Strick wird nicht schnell zerrissen.',
        13: 'Besser ein Junge arm aber weise, als ein König, alt aber töricht, der immer noch nicht weiß, sich warnen zu lassen.',
        14: 'Denn während aus dem Gefängnis einer heraus kommt, um König zu sein, sogleich verarmt einer, der unter seiner Königsherrschaft geboren wurde.',
        15: 'Ich habe alle Lebenden gesehen, die unter der Sonne umherlaufen, mit dem zweiten Jungen, der an jenes Stelle treten sollte.',
        16: 'Es gab kein Ende des ganzen Volkes, all die, die vor ihrem (seinem?) Angesicht waren, auch die danach kamen, freuten sich nicht über ihn. Hüte deinen Fuß, wenn du zum Haus Gottes gehst, und trete heran, um zu hören, als wenn die Toren Opfer geben, denn sie wissen nicht, dass sie böse handeln.',
    },
    5: {
        1: 'Sei nicht vorschnell mit deinem Mund, und dein Herz eile nicht darin, ein Wort vor Gott herauszubringen, denn Gott ist im Himmel und du bist auf der Erde, deshalb lass deine Worte sein wenige.',
        2: 'Denn es kommt der Traum bei viel Arbeit, und ein Tor [macht] mit vielen Worten Lärm.',
        3: 'Wenn du Gott einen Schwur schwörst, zögere nicht, es einzuhalten, denn es gibt kein Gefallen für die Toren; das was du schwörst, halte ein!',
        4: 'Besser, dass du nicht schwörst, als dass du schwörst und es nicht einhältst.',
        5: 'Gestatte deinem Mund nicht, dass er dein Fleisch sündigen lässt, und sprich nicht vor dem Engel: ja das war ein Versehen. Warum zürnt Gott [dann] über deine Stimme und zerstört die Arbeit deiner Hände?',
        6: 'Denn viele Träume vermehren auch Hauche und Worte, darum fürchte Gott!',
        7: 'Wenn du Unterdrückung siehst und Raub von Gerechtigkeit im Lande, wundere dich nicht über den Gefallen, wenn ein Hoher einen Höheren schützt und noch höhere über ihnen.',
        8: 'Und das, was der Erde bei all dem über bleibt ist dies: Ein König, um das Feld zu bestellen.',
        9: 'Wer Geld liebt, wird des Geldes nicht satt, und wer den Luxus liebt, nicht der Produkte; auch das ist Hauch.',
        10: 'Indem sich der Wohlstand vermehrt, mehren sich auch die, die ihn verzehren, und welchen Nutzen hat sein Besitzer, außer einem Blick seiner Augen?',
        11: 'Süß ist der Schlaf des Arbeiters, ob er wenig oder viel isst, aber der Überfluss lässt den Reichen weder ruhen noch schlafen.',
        12: 'Es gibt ein böses Übel, das ich gesehen hab unter der Sonne: Reichtum, aufbewahrt von seinem Besitzer zu seinem Unglück.',
        13: 'Und geht solch ein Reichtum durch eine unglückliche Begebenheit verloren, und ist ein Sohn gezeugt worden, ist überhaupt nichts in dessen Hand.',
        14: 'Wie er nackt aus dem Bauch seiner Mutter herausgekommen ist, so kehrt er zurück indem er geht wie er gekommen ist, und überhaupt nichts nimmt er mit von der Mühe seiner Hand wenn er geht.',
        15: 'Und auch das ist eine böses Übel, ganz genau wie er gekommen ist, so wird gehen, und was bleibt dem übrig, der auf Wind hin gearbeitet hat?',
        16: 'Auch isst er all seine Tage in der Dunkelheit und hat viel Ärger, Krankheit und Zorn.',
        17: 'Siehe, was ich Gutes gesehen habe, das schön ist: Zu essen und zu trinken und Gutes zu sehen bei all seiner Mühe, die man tut unter der Sonne die Zahl seiner Lebenstage, die ihm Gott gegeben hat, denn das ist sein Anteil.',
        18: 'Auch jeder Mensch, dem Gott Reichtum und Güter gegeben hat und die Macht, davon zu genießen und sich seinen Anteil zu nehmen und sich zu freuen bei seiner Mühe, das ist ein Geschenk Gottes.',
        19: 'Denn er denkt nicht viel an seine Lebenstage, weil Gott ihn mit der Freude seines Herzens beschäftigt.',
    },
    6: {
        1: 'Es gibt ein Übel, das ich gesehen habe unter Sonne, und es ist mächtig auf dem Menschen:',
        2: 'Jemand, dem Gott Reichtum und Güter und Ehre gibt, und nichts fehlt ihm hinsichtlich seiner Seele von allem, was er begehrt, aber ermächtigt ihn nicht, davon zu genießen, denn jemand fremdes genießt es. Das ist Hauch und ein böses Übel.',
        3: 'Wenn jemand Hundert zeugt und viele Jahre lebt und die Tage seiner Jahre viele werden, aber seine Seele nicht satt wird vom Guten und auch sein Grab nicht wird für ihn, sage ich: Eine Fehlgeburt ist besser [dran] als er.',
        4: 'Denn im Hauch kommt sie und in der Finsternis geht sie, und in der Finsternis bleibt ihr Name verhüllt.',
        5: 'Auch die Sonne hat sie nicht gesehen, und kennt sich nicht. Diese hat mehr Ruhe als jener.',
        6: 'Und wenn zweimal tausend Jahre lebt, aber Gutes nicht gesehen hat, geht nicht das alles an einen (denselben) Ort?',
        7: 'Alle Mühe des Menschen ist für seinen Mund, aber die Seele (sein Appetit) wird davon auch nicht satt (gestillt).',
        8: 'Denn was bleibt dem Weisen mehr übrig als dem Toren? Was dem Armen der zu laufen weiß vor den Lebenden?',
        9: 'Besser die Sicht der Augen als das Umhergehen der Seele (Begierde), auch das ist Hauch und Haschen nach Wind!',
        10: 'Was geschieht ist bereits bei seinem Namen gerufen/genannt, und es ist bekannt, was ein Mensch, und nicht kann er rechten mit dem, der stärker ist als er.',
        11: 'Denn es gibt viele Worte, die den Hauch vermehren, was bleibt übrig für den Menschen?',
        12: 'Denn wer weiß, was gut ist für den Menschen im Leben, in der Menge der Tage seines vergänglichen Lebens, die [Tage] sind wie der Schatten, denn wer kann dem Menschen erzählen, was nach ihm sein wird unter der Sonne?',
    },
    9: {
        1: 'Denn dieses alles habe ich in mein Herz gegeben und dieses alles überprüft: Die Gerechten und die Weisen und ihre Werke sind in Gottes Hand. Auch Liebe, auch Hass; der Mensch kennt sie nicht. Alles geht ihnen voraus.',
        2: 'Alles ist wie alles. Es ist ein Geschick für den Gerechten und für den Frevler, für den Guten und für den Reinen und für den Unreinen und für den, der opfert und für den, der nicht opfert. Wie dem Guten, so dem Sünder, der Schwörende wie der, der sich vor Eiden fürchtet.',
        3: 'Dies ist ein Übel in allem, was geschieht unter der Sonne, dass ein Geschick für alle ist. Und auch das Herz der Menschen ist voll von Bösem, und Irsinn ist in ihren Herzen in ihrem Leben. Und danach bei den Toten.',
        4: 'Denn wer noch zu den Lebenden gehört, für den ist Hoffnung. Denn ein lebender Hund, er ist besser als ein toter Löwe.',
        5: 'Denn die Lebenden erkennen, dass sie sterben werden. Aber die Toten erkennen nichts. Und es bleibt ihnen nichts übrig, denn ihr Andenken ist vergessen.',
        6: 'Auch ihr Lieben, auch ihr Hassen, auch ihr Eifern ist bereits vorbei. Und keinen Anteil haben sie mehr an alldem, was unter der Sonne geschieht.',
        7: 'Geh, iss mit Freude dein Brot und trinke mit gutem Herzen deinen Wein. Denn längst hat Gott Wohlgefallen an deinem Tun.',
        8: 'Zu aller Zeit seien deine Kleider weiß und Öl auf deinem Kopf soll nicht fehlen.',
        9: 'Genieße das Leben mit einer Frau, die du liebst alle Tage deines vorbeihauchenden Lebens, dass er dir unter der Sonne gegeben hat, alle deine vorbeihauchenden Tage. Denn das ist dein Anteil am Leben und an der Arbeit, die du tust unter der Sonne.',
        10: 'Alles, was deine Hand zu tun findet, das tue in deiner Kraft. Denn es gibt keine Werke und Berechnung und Wissen und Weisheit in der Unterwelt, in die du gehen wirst.',
        11: 'Wiederum habe ich mir unter der Sonne gedacht, dass nicht die Schnellen das Rennen machen und nicht die Helden den Krieg und auch nicht die Weisen Brot und auch die Verständigen Reichtum und auch nicht die Kenntnisreichen Beliebtheit, denn Zeit und Zufall treffen sie alle.',
        12: 'Denn auch kennt der Mensch seine Zeit nicht. Wie die Fische gefangen werden im bösen Netz und wie die Vögel gefangen werden in der Falle, so werden die Menschen sich verfangen zur bösen Zeit, wenn sie plötzlich über sie fällt.',
        13: 'Auch diese Weisheit sah ich unter der Sonne und groß war sie für mich:',
        14: 'Es war eine kleine Stadt und weniger Männer waren in ihr. Zu der kam ein großer König und umstellte sie und baute große Belagerungstürme gegen sie.',
        15: 'Und es fand sich in ihr ein armer, weiser Mann. Und er rettete die Stadt durch seine Weisheit. Aber kein Mensch erinnerte sich an diesen armen Mann.',
        16: 'Und ich sagte: Besser ist Weisheit als Stärke. Aber die Weisheit des Armen wird verachtet und seine Worte werden nicht gehört.',
        17: 'Worte der Weisen, die in Ruhe gehört werden sind besser als das Schreien des Herrschers unter den Dummen.',
        18: 'Weisheit ist besser als Kriegsgerät, aber ein Sünder verdirbt viel Gutes.',
    },
    11: {
        1: 'Wirf dein Brot auf die Wasseroberfläche, denn in vielen Tagen wirst du es finden.',
        2: 'Teile deinen Anteil durch sieben und durch acht, denn du weißt nicht, was böses geschehen wird auf der Erde.',
        3: 'Wenn die Wolken voll werden, entleeren sie den Regen auf die Erde, wenn ein Baum fällt nach Süden oder nach Norden – an dem Ort, wo der Baum hinfällt, da liegt er.',
        4: 'Wer auf den Wind achtet sät nicht und wer auf die Wolken blickt erntet nicht.',
        5: 'Gleich wie du nicht weißt, wie der Weg des Windes ist oder wie der Embryo (die Knochen) im Mutterleibe Gestalt annimmt, also kennst du nicht die Werke Gottes, der alles tut.',
        6: 'Am Morgen sähe deinen Samen und bis zum Abend lass deine Hand nicht ruhen, denn du weißt nicht, ob diese geraten werden oder jene, und wenn es beide zugleich sind, umso besser.',
        7: 'Das Licht ist süß und gut für die Augen ist es, die Sonne zu sehen.',
        8: 'Denn wenn der Mensch viele Jahre lebt und sich in ihnen freut, gedenkt er der Tage der Dunkelheit, denn viele werden es sein, alles, was kommt, ist Hauch.',
        9: 'Freue dich Jüngling in deiner Jugend und lass es deinem Herzen gut gehen in den Tagen deiner Jugendzeit, und gehe auf dem Weg deines Herzens und dem Blick deiner Augen; und wisse, dass Gott dich wegen all diesem vor Gericht bringen wird.',
        10: 'Entferne Ärger von deinem Herzen fern und halte Böses von deinem Leib, denn die Jugend und Dunkles Haar sind Hauch.',
    },
}
