NAME = 'ACV: A Conservative Version'
BOOK = 'Ecclesiastes'

CHAPTERS = {
    1: {
        1: 'Besede Propovednika, sinu Davidovega, kralja v Jeruzalemu.',
        2: 'Ničemurnost nečimurna! pravi Propovednik; ničemurnost ničemurna, vse je ničemurno!',
        3: 'Kaj ima dobička človek od vsega truda svojega, s katerim se trudi pod solncem?',
        4: 'Rod mineva, rod prihaja, a zemlja vedno ostaja.',
        5: 'In solnce vzhaja in solnce zahaja in hiti k mestu svojemu, odkoder izhaja.',
        6: 'Veter gre proti poldnevu in se obrača proti polnoči in kroži in kroži, in krožitve svoje vedno ponavlja veter.',
        7: 'Vse reke teko v morje, in morje se ne prepolni; v kraj, kamor teko reke, tja vedno in vedno teko.',
        8: 'Vse stvari so trudapolne: človek ne more tega dopovedati; oko se ne nasiti gledanja, ne uho poslušanja.',
        9: 'Kar je bilo, bode zopet, in kar se je storilo, se bo zopet storilo, in nič novega ni pod solncem.',
        10: 'Je li kaj, o čemer pravijo: Glej, to je novo? Zdavnaj je že bilo v vekih, ki so bili pred nami.',
        11: 'Ni spomina prejšnjih rodov, in prihodnjim, ki še bodo, tudi ne bo spomina pri tistih, ki pozneje nastanejo.',
        12: 'Jaz, Propovednik, sem bil kralj nad Izraelom v Jeruzalemu.',
        13: 'In obrnil sem srce svoje v to, da bi z modrostjo preiskoval in zasledoval vse, kar se godi pod nebom: težko opravilo, ki ga je naložil Bog sinom človeškim, da se ž njim ukvarjajo.',
        14: 'Videl sem vse dejanje, ki se godi pod solncem, in glej, vse je ničemurnost in lovljenje vetra.',
        15: 'Kar je krivo, se ne more zravnati, in česar ni, se ne more šteti.',
        16: 'Govoril sem v srcu svojem in rekel: Glej, dobil sem veliko modrost in prekosil vse, ki so bili pred menoj v Jeruzalemu, in srce moje je videlo obilost modrosti in spoznanja.',
        17: 'In obrnil sem srce svoje v to, da spoznam modrost in da spoznam nespamet in neumnost: spoznal sem, da je tudi to lovljenje vetra.',
        18: 'Zakaj pri mnogi modrosti je mnogo nejevolje, in kdor množi znanje, množi bolečino.',
    },
    2: {
        1: 'Rekel sem v srcu svojem: Daj le, da te izkusim z veseljem; uživaj, kar je dobro! A glej, tudi to je ničemurnost.',
        2: 'Smehu sem dejal, da je nespamet, in veselju, kaj pač napravi?',
        3: 'Namenil sem se v srcu, streči telesu svojemu z vinom, a vodi naj me pri tem z modrostjo srce moje, in se poprijeti nespameti, dokler spoznam, kaj bi bilo dobro sinovom človeškim delati vse svoje žive dni.',
        4: 'Lotil sem se velikih del: zidal sem si hiše, zasajal si vinograde,',
        5: 'napravljal sem si vrte in nasade in v njih zasajal vsakršno sadno drevje;',
        6: 'naredil sem si vodnjake, da bi iz njih namakal gozd rastočega drevja.',
        7: 'Kupil sem si hlapcev in dekel in imel doma rojene hlapce; tudi sem imel velike črede govedi in drobnice, več nego vsi, ki so bili pred menoj v Jeruzalemu.',
        8: 'Nakopičil sem si tudi srebra in zlata in dragotin, lastnih kraljem in deželam; oskrbel sem si pevcev in pevk in kar je sinom človeškim v veselje: ženo in žene.',
        9: 'Tako sem postal velik in sem prekosil vse, ki so bili pred menoj v Jeruzalemu; tudi modrost moja je ostala pri meni.',
        10: 'In karkoli so želele moje oči, nisem jim odrekel; srcu svojemu nisem zabranil nobenega veselja, kajti srce moje se je veselilo ob vsem trudu mojem, in to je bil moj delež od vsega truda mojega.',
        11: 'Potem sem se ozrl po vseh delih svojih, ki so jih storile roke moje, in po trudu, ki sem si ga prizadel, da bi bil vse dovršil; in glej, vse je bilo ničemurnost in lovljenje vetra, in dobička ni pod solncem nobenega.',
        12: 'In obrnil sem se, da bi gledal modrost in nespamet in budalost. Ker kaj more delati človek, ki pride za kraljem? To, kar so oddavnaj delali.',
        13: 'In videl sem, da je boljša modrost nego budalost, prav kakor je boljša svetloba od teme.',
        14: 'Modri ima oči v glavi, bedak pa hodi po temi. A hkrati sem tudi zaznal, da se jim vsem godi po isti naključbi.',
        15: 'Tedaj sem dejal v srcu svojem: Kakor se godi bedaku, se naključi tudi meni, in čemu sem potem tolikanj moder? In rekel sem v srcu svojem, da je ničemurnost tudi to.',
        16: 'Zakaj modremu in enako bedaku ne bode večnega spomina, ker v prihodnjih dneh bode že vse pozabljeno. Ah, kako da mora umreti modrec takisto kakor bedak!',
        17: 'Tedaj sem sovražil življenje, ker mi ni ugajalo dejanje, ki se godi pod solncem; kajti vse je ničemurnost in lovljenje vetra.',
        18: 'In zasovražil sem ves trud svoj, s katerim sem se trudil pod solncem, zato ker ga moram zapustiti človeku, ki bode za menoj.',
        19: 'In kdo ve, bode li moder ali nespameten? Pa vendar bo vladal vsemu, kar sem s težkim trudom in z modrostjo pridobil pod solncem. Ničemurnost je tudi to.',
        20: 'Tedaj sem se obrnil, da bi izročil srce obupu nad vsem trudom, s katerim sem se trudil pod solncem.',
        21: 'Kar si je namreč kdo težko pridobil z modrostjo in z znanjem in s spretnostjo, to mora zapustiti v delež človeku, ki se ni trudil za to. Tudi to je ničemurnost in veliko zlo.',
        22: 'Ker kaj ima človek pri vsem trudu svojem in pri srca svojega teženju, s katerim se trudi pod solncem?',
        23: 'Kajti vse dni svoje trpi bolečine in nejevoljo pri opravilu svojem, celo po noči ni počitka njegovemu srcu. Tudi to je ničemurnost.',
        24: 'Nič ni boljšega za človeka, nego da bi jedel in pil in dal duši svoji uživati dobro v trudu svojem. A videl sem, da je tudi to iz roke Božje.',
        25: 'Kajti kdo more jesti in kdo more uživati kaj brez Njega?',
        26: 'Človeku namreč, ki Mu ugaja, daje Bog modrost, spoznanje in veselje; ali grešniku daje težavo, da spravlja in kopiči, pa vse zapusti njemu, ki Bogu ugaja. Tudi to je ničemurnost in lovljenje vetra.',
    },
    3: {
        1: 'Vse ima svoj določeni čas in vsako početje pod nebom svojo dobo.',
        2: 'Je čas rojenja in je čas smrti; je čas, da se sadi, in čas, da se vsajeno izruje;',
        3: 'je čas morjenja in čas ozdravljanja, čas podiranja in čas zidanja,',
        4: 'čas jokanja in čas smejanja, čas žalovanja in čas plesanja,',
        5: 'čas razmetavanja kamenov in čas zbiranja kamenov, čas objemanja in čas, zdrževati se objemanja,',
        6: 'čas iskanja in čas izgubljanja, čas spravljanja in čas zametanja,',
        7: 'čas, da se raztrga, in čas, da se sešije, čas molčanja in čas govorjenja,',
        8: 'čas ljubezni in čas sovraštva, čas vojne in čas miru.',
        9: 'Kaj ima koristi, kdor karkoli dela, od tega, s čimer se trudi?',
        10: 'Videl sem trudno opravilo, ki ga je Bog dal otrokom človeškim, da se ž njim ukvarjajo.',
        11: 'On je vse storil, da je lepo ob svojem času; tudi večnost jim je položil v srce, samo da ne more človek doumeti dela, ki ga je Bog napravil, od začetka do konca.',
        12: 'Spoznal sem, da ni nič boljšega med njimi, nego da se veselé in delajo dobro v življenju svojem;',
        13: 'pa tudi, ko človek jé in pije in uživa dobro pri vsem trudu svojem, da je to vsakemu dar Božji.',
        14: 'Spoznal sem, da bode vse, kar Bog dela, za večno: nič se temu ne more prideti, nič od tega vzeti; in Bog je to storil, da se ga boje.',
        15: 'Kar je, je bilo že preje, in kar bode, je bilo zdavnaj, in Bog gleda, da pride na svetlo, kar je minilo.',
        16: 'Dalje sem videl pod solncem: na mestu sodbe je bila nepravda in na mestu pravičnosti je bila brezbožnost.',
        17: 'Rekel sem v srcu svojem: Bog bo sodil pravičnega in brezbožnega, zakaj on je določil čas vsakemu počenjanju in vsakemu delu.',
        18: 'Rekel sem v srcu svojem: Zaradi otrok človeških se tako godi, da jih Bog izkusi in da vidijo, da sami ob sebi so kakor živina.',
        19: 'Kajti kar se naključi otrokom človeškim in kar se naključi živalim, je ista naključba: kakor te umrjo, umrjo tudi oni, in enak dih imajo vsi, in človek nima prednosti proti živini; zakaj vse je ničemurnost.',
        20: 'Vse gre na eno mesto; vse je postalo iz prahu in vse se vrača zopet v prah.',
        21: 'Kdo pozna dih otrok človeških, če gre navzgor, in dih živine, če gre navzdol k zemlji?',
        22: 'Tako sem videl, da ni nič boljšega, nego da se človek veseli del svojih, zakaj to je delež njegov. Kajti kdo ga privede nazaj, da bi videl, kaj bode za njim?',
    },
    4: {
        1: 'In obrnil sem se in sem videl vse stiskanje, kar se ga godi pod solncem; in glej, solze stiskanih, in niso imeli tolažitelja; in na strani njih tlačiteljev je bila moč in ni jim bilo tolažitelja.',
        2: 'Zato sem blagroval mrtve, ki so bili davno umrli, bolj nego žive, ki so še v življenju;',
        3: 'in za srečnejšega nego oboje sem štel njega, ki ga še ni bilo, ki še ni videl zlega dejanja, ki se godi pod solncem.',
        4: 'Tedaj sem videl ves trud in ves uspeh v delu, da zaradi tega zavidajo drug drugemu. Tudi to je ničemurnost in lovljenje vetra!',
        5: 'Bedak sklepa roke in jé svoje lastno meso.',
        6: 'Boljša je peščica s pokojem nego dve pesti, polni truda in lovljenja vetra.',
        7: 'In obrnil sem se in sem videl ničemurnost pod solncem:',
        8: 'Samec je in nima druga, tudi nima sina, ne brata, a mnogemu trudu njegovemu ni konca; pri vsem tem se ne nasitijo bogastva oči njegove. Ne misli: Za koga se trudim in kratim duši svoji dobro? Tudi to je ničemurnost in prehudo opravilo.',
        9: 'Bolje je dvema nego enemu, ker imata dobro plačilo za svoj trud.',
        10: 'Zakaj če padeta, vzdigne tovariš tovariša; ali gorje samemu, ko pade in nima druga, da bi ga vzdignil!',
        11: 'Tudi kadar dva vkup ležita, se grejeta; a kako se hoče kdo zgreti, ko je sam?',
        12: 'In če enega siloma napadejo, se dva v bran postavita; in trojna vrvica se ne raztrga lahko.',
        13: 'Boljši ubog in moder deček nego star in bedast kralj, ki nima več toliko uma, da bi se dal posvariti.',
        14: 'Zakaj iz jetnišnice je prišel deček, da bi kraljeval, čeprav se je ubog rodil v kraljestvu njegovem.',
        15: 'Videl sem vse živeče, ki hodijo pod solncem, da so bili pri dečku, drugem, ki je imel stopiti na onega mesto;',
        16: 'ni bilo konca vsemu tistemu ljudstvu, ki mu je bil na čelu; a potomci se ga ne bodo veselili. Res, tudi to je ničemurnost in lovljenje vetra.',
    },
    5: {
        1: 'Pazi na nogo svojo, kadar greš v hišo Božjo! Kajti bližati se, da poslušaš, je bolje nego darovati bedakov daritve; nimajo namreč spoznanja, da delajo hudo.',
        2: 'Ne bodi nagel s svojimi usti in srcu svojemu ne daj hiteti, da izreče besedo pred Bogom; zakaj Bog je v nebesih, ti pa si na zemlji: zato bodi tvojih besed malo.',
        3: 'Kajti sanje prihajajo po mnogem trudu in bedak se oglaša z mnogimi besedami.',
        4: 'Kadar storiš obljubo Bogu, je ne odlašaj izpolniti; kajti Njemu ne ugajajo bedaki. Kar obljubiš, izpolni!',
        5: 'Bolje, da ne obljubiš, nego da obljubiš, a ne izpolniš.',
        6: 'Ne dopusti ustom svojim, da v greh zapeljejo meso tvoje, in ne govóri pred poslancem Božjim: Bila je pomota! Čemu naj bi se jezil Bog nad glasom tvojim in uničil rok tvojih delo?',
        7: 'Zakaj pri mnogih sanjah in besedah je tudi mnogo ničemurnosti. Le Boga se boj!',
        8: 'Kadar vidiš, da stiskajo uboge ter da siloma dero sodbo in pravičnost v deželi, ne čudi se tej reči; kajti visok čuva nad visokim, a nad njima je še višji.',
        9: 'A kralj, ki služi poljedelstvu, je vsekakor deželi v prid.',
        10: 'Kdor ljubi srebro, ne bo nikoli srebra sit, in kdor ljubi bogastvo, ne dobi nikdar dosti. Tudi to je ničemurnost.',
        11: 'Ko se množi imovina, se množe tudi tisti, ki jo uživajo; in kakšen užitek ima posestnik, nego da jo z očmi gleda?',
        12: 'Delavcu je spanje sladko, če je jedel veliko ali malo; bogatinu pa sitost ne da mirno spati.',
        13: 'Je hudo zlo, ki sem ga videl pod solncem: bogastvo, ki si ga hrani njega posestnik sebi v nesrečo.',
        14: 'Ker tako bogastvo se izgubi po zli nezgodi, in sinu, ki ga je rodil, ga ne ostane nič v roki.',
        15: 'Kakor je prišel nag iz telesa matere svoje, prav tako zopet odide in za trud svoj ne vzame še kaj malega ne, kar bi v roki odnesel s seboj.',
        16: 'Pa tudi to je hudo zlo, da mora oditi prav tako, kakor je prišel; in kaj ima dobička od tega, da se trudi za veter?',
        17: 'Vrhutega mora vse svoje dni jesti v temi in ima dosti nejevolje, bolezni in jeze.',
        18: 'Glej, kar sem spoznal za dobro in za lepo: da človek jé in pije in uživa dobro pri vsem trudu svojem, s katerim se trudi pod solncem, vse dni svojega življenja, kar mu jih je Bog dal; kajti to je delež njegov.',
        19: 'Saj vsakemu človeku, ki mu je Bog dal bogastvo in zaklade in ga je pooblastil, da to uživa in vzame delež svoj in se veseli pri trudu svojem, prav to je dar Božji.',
        20: 'Kajti ne bo se veliko spominjal dni življenja svojega; ker mu Bog odgovarja v veselju srca njegovega.',
    },
    6: {
        1: 'Je zlo, ki sem ga videl pod solncem, in težko tlači ljudi:',
        2: 'Bog podeli komu bogastva in zakladov in časti, da ne manjka duši njegovi ničesar, karkoli bi si želel: a Bog mu ne da oblasti, da bi to užival, ampak tujec bo užil! To je ničemurnost in huda bolečina.',
        3: 'Ako bi kdo rodil sto otrok in živel mnogo let, kakorkoli veliko bi bilo let njegovih število, a duša njegova bi se ne nasitila dobrega in nazadnje bi mu ne napravili pogreba, tedaj rečem: Izpovitek je srečnejši od njega!',
        4: 'Ker ta pride v ničevosti in se odpravi v temi in njegovo ime ostane skrito v temi;',
        5: 'solnca tudi ni videl, ne česa spoznal. Ta počiva bolje nego on.',
        6: 'In ako bi bil tudi dvakrat tisoč let živel, pa ne videl nič dobrega: ne gre li vse v en kraj?',
        7: 'Ves trud človekov je za usta njegova, a duša se mu vendar ne nasiti!',
        8: 'Ker kaj ima modri več nego bedak? kaj ubožec, ki se ume vesti pred živečimi?',
        9: 'Bolje, da oči kaj vidijo, nego da želje okoli tavajo. Tudi to je ničemurnost in lovljenje vetra.',
        10: 'Kar je postalo, je bilo že zdavnaj imenovano. In Bogu je znano, kaj bode človek, in ta se ne more pravdati z Onim, ki je močnejši od njega.',
        11: 'In ker je mnogo besed, ki pomnožujejo ničemurnost, kaj ima dobička človek od tega?',
        12: 'Kajti kdo ve, kaj je dobro človeku v življenju, vse dni ničemurnega življenja njegovega, ki jih preživi kakor senca? Kajti kdo more povedati človeku, kaj bode za njim pod solncem?',
    },
    7: {
        1: 'Dobro ime je boljše nego dišeče mazilo in dan smrti boljši nego dan rojstva.',
        2: 'Bolje je iti v hišo žalosti nego v hišo pojedine, ker v oni se vidi konec vseh ljudi, in živeči si to vtisne v srce.',
        3: 'Boljša je žalost nego smeh, kajti po otožnem obličju se poboljšava srce.',
        4: 'Srce modrih je v hiši žalosti, bedakov srce pa v hiši veselja.',
        5: 'Bolje je poslušati karanje modrega nego petje bedakov.',
        6: 'Kajti smeh bedakov je kakor prasketanje trnja, gorečega pod loncem. Tudi to je ničemurnost.',
        7: 'Res, nasilstvo omami modrega in podkupilo uniči razum.',
        8: 'Boljši je konec reči nego njen začetek; boljši je potrpežljivi nego ošabni.',
        9: 'Ne bodi prenaglega duha za jezo, kajti jeza počiva v nedrjih bedakov.',
        10: 'Ne govóri: Kako da so bili prejšnji dnevi boljši nego sedanji? Kajti tega ne vprašuješ v modrosti.',
        11: 'Modrost je enako dobra kakor dediščina in še boljša njim, ki gledajo solnce.',
        12: 'Kajti modrost je obrana in denar je obrana, toda prednost znanja je ta, da modrost ohrani v življenju njega, kdor jo ima.',
        13: 'Glej delo Božje! Kajti kdo more zravnati, kar je on skrivil?',
        14: 'Ob dnevi blagostanja bodi vesel, a ob dnevi nesreče pomisli: Tudi ta dan je Bog naredil z onim vred, da človek ne iznajde, kar bode za njim.',
        15: 'Marsikaj sem videl v dnevih ničemurnosti svoje: je pravičnik, ki gine v pravičnosti svoji, in je brezbožnik, ki podaljša življenje svoje v hudobnosti svoji.',
        16: 'Ne bodi prepravičen in ne kaži se modrega čez mero: zakaj bi se pogubljal?',
        17: 'Ne bodi preveč brezbožen in ne bodi bedast: zakaj bi umrl, preden pride tvoj čas?',
        18: 'Dobro je, da se oprimeš tega, pa tudi onega ne izpustiš iz roke, zakaj kdor se boji Boga, uide vsem tem skrajnostim.',
        19: 'Modrost jači modrega bolj nego deset mogotcev, ki so v mestu.',
        20: 'Res, na zemlji ni pravičnega človeka, ki dela dobro in ne greši.',
        21: 'Naj ti tudi ne sega do srca vse, kar se govori, da ne boš moral slišati, kako te hlapec tvoj preklinja;',
        22: 'kajti mnogoterikrat, tvoje srce ve, si tudi ti druge klel.',
        23: 'Vse to sem preizkušal v modrosti. Dejal sem: Hočem biti moder, a daleč je ostala od mene modrost.',
        24: 'Daleč je, kar je, in pregloboko: kdo more to doseči?',
        25: 'Obrnil sem se in srce mi je bilo namenjeno, spoznavati in zasledovati in iskati modrost in pravi razsodek, da bi spoznal, kako je brezbožnost neumna in nespamet besna.',
        26: 'In našel sem, kar je grenkejše nego smrt: ženo, čije srce se mreže in zadrge in roke njene spone. Kdor je ugoden Bogu, ji ubeži, grešnika pa ulovi.',
        27: 'Poglej, to sem našel, pravi Propovednik, ko sem zlagal drugo z drugim, da bi dobil pravi razsodek:',
        28: 'Česar duša moja še vedno išče, pa nisem našel, je to: enega moža iz tisoč sem našel, ali žene med temi vsemi nisem našel nobene.',
        29: 'Poglej, samo to sem našel, da je Bog ustvaril človeka poštenega, oni pa iščejo veliko spletk!',
    },
    8: {
        1: 'Kdo je kakor modrijan? in kdo zna razlago stvari? Modrost razsvetljuje človeku obraz, in trma z lica njegovega izgine.',
        2: 'Jaz ti svetujem: Ukaz kraljev spoštuj, in to z ozirom na prisego Božjo.',
        3: 'Ne prenagli se, da greš izpred obličja njegovega, in ne vtikaj se v hudo reč! Zakaj on stori vse, kar hoče,',
        4: 'ker beseda kraljeva ima moč, in kdo mu more reči: Kaj delaš?',
        5: 'Kdor izpolnjuje zapoved, se ne ozira na nič hudega; in srce modrega razpoznava čas in pravo sodbo.',
        6: 'Zakaj za vsako početje je čas in sodba; kajti težko obremenja človeka zlo.',
        7: 'Zakaj on ne ve, kaj se zgodi; ker kdo mu oznani, kako se zgodi?',
        8: 'Noben človek ni vladar duhu, da bi zadržal duha; in nihče nima vlade nad dnevom smrti; in v vojski ni nobenega oproščenja; in brezbožnost ne reši tistega, ki ji je vdan.',
        9: 'Vse to sem videl, in obrnil sem srce svoje k vsemu dejanju, ki se godi pod solncem, ob času, ko človek vlada ljudem v njih nesrečo.',
        10: 'In tako sem videl brezbožne, da so jih pokopavali in so prišli v grob; tisti pa, ki so prav ravnali, so morali oditi iz svetega kraja in so jih pozabili v mestu. Tudi to je ničemurnost.',
        11: 'Ker se hitro ne izvrši sodni izrek proti hudemu dejanju, zato je srce otrok človeških polno smelosti, da delajo hudo.',
        12: 'Čeprav grešnik stokrat stori hudo in se mu daljšajo dnevi, vendar vem za gotovo, da se bo njim, ki se Boga boje, dobro godilo, ker se ga boje;',
        13: 'ali brezbožniku se ne bo dobro godilo, tudi ne podaljša dni svojih, ki so kakor senca, ker se Boga ne boji.',
        14: 'Je ničemurnost, ki se dogaja na zemlji: da so pravični, katerim se godi po delih brezbožnikov, in so brezbožni, katerim se godi po delih pravičnikov. Rekel sem, da tudi to je ničemurnost.',
        15: 'Tedaj sem hvalil veselje, ker ni nič boljšega človeku pod solncem, nego da jé in pije in se veseli, in to naj pri njem ostane ob trudu njegovem vse njegove žive dni, kar mu jih je dal Bog pod solncem.',
        16: 'Ko sem obrnil srce svoje v to, da bi spoznaval modrost in ogledoval počenjanje, ki se godi na zemlji (saj tudi ne okusi človek ne po dne, ne po noči spanja s svojimi očmi):',
        17: 'tedaj sem videl glede vsega dela Božjega, da človek ne more doumeti dela, ki se godi pod solncem; kakorkoli se napenja, da ga izsledi, ga z umom ne doseže; in čeprav bi modrijan menil, da ga razume, ga vendar ne bo mogel doseči.',
    },
    9: {
        1: 'Kajti vse to sem premišljeval v srcu, da bi vse to preizkusil: da so pravični in modri in njih dela v roki Božji; bodisi ljubezen ali sovraštvo, človek tega vnaprej ne pozna; vse je pred njimi v prihodnosti skrito.',
        2: 'Vse je enako vsem, eno naključje za pravičnega in brezbožnega, za dobrega in čistega in nečistega, za njega, ki daruje, in za njega, ki ne daruje; enako dobremu kakor grešniku, enako njemu, ki prisega, kakor njemu, ki se prisege boji.',
        3: 'To je zlo v vsem, kar se godi pod solncem, da eno naključje zadeva vse, pa tudi srce otrok človeških je polno zlobe in blaznosti, dokler žive, in potem gredo k mrtvim.',
        4: 'Zakaj njemu, ki je združen z vsemi živečimi, je še upanje; ker tudi živečemu psu je bolje nego mrtvemu levu.',
        5: 'Kajti živeči vedo, da jim je umreti, mrtvi pa ničesar ne vedo ter nimajo plačila več, ker je njih spomin pozabljen.',
        6: 'Kakor njih ljubezen, tako je njih sovraštvo in njih gorečnost davno izginila, in nimajo več deleža vekomaj na vsem, kar se godi pod solncem.',
        7: 'Pojdi, jej z veseljem kruh svoj in pij vino svoje z blagim srcem; kajti Bog je že zdavnaj odobril dejanje tvoje.',
        8: 'Ob vsakem času naj bodo čista oblačila tvoja in olja naj ne manjka na glavi tvoji!',
        9: 'Uživaj življenje z ženo, ki jo ljubiš, vse dni svojega ničemurnega življenja, ki ga ti je dal pod solncem, vse dni ničemurnosti svoje; kajti to je tvoj delež v življenju in v trudu, s katerim se trudiš pod solncem.',
        10: 'Čvrsto se poprimi vsega, kar ti pride pod roko, da storiš z močjo svojo; kajti ni ne dela, ne preudarjanja, ne znanja, ne modrosti v kraju smrti, kamor greš.',
        11: 'Obrnil sem se, in videl sem pod solncem, da ni hitrim zagotovljen tek, ne junakom zmaga, tudi ne modrim kruh, a tudi ne razumnim bogastvo, in tudi ne veščakom priljubljenost, kajti čas in razmere naklanjajo vse.',
        12: 'Kajti tudi svojega časa ne ve človek; kakor ribe, ki se ujamejo v pogubno mrežo, in kakor ptice, ki se zadrgnejo v zanko, tako se zapleto otroci človeški v mrežo ob času nesreče, ko jih nenadoma zadene.',
        13: 'Tudi to sem videl kot modrost pod solncem, in zdelo se mi je veliko:',
        14: 'Bilo je majhno mesto in malo ljudi v njem, in prišel je zoper njega velik kralj in ga obkolil in zgradil obležne nasipe proti njemu.',
        15: 'A živel je v njem ubog, pa moder mož, ki je rešil mesto po modrosti svoji; ali nihče se ni spomnil tega ubogega človeka.',
        16: 'Tedaj sem rekel: Modrost je boljša nego moč; toda modrost ubožčevo zaničujejo in besed njegovih ne poslušajo.',
        17: 'Besede modrih, ki jih slišimo na tihem, so boljše nego vpitje vladarja med bedaki.',
        18: 'Modrost je boljša nego vojno orožje, ali eden grešnik pokazi mnogo dobrega.',
    },
    10: {
        1: 'Mrtve muhe napravijo, da se mazilarju mazilo skazi in usmradi: enako malo neumnosti lahko prevlada modrost in slavo.',
        2: 'Modrega srce je na pravi strani njegovi, a bedakovo na napačni.',
        3: 'Saj tudi ko po poti gre, manjka bedaku razuma in vsakemu pove, da je bedak.',
        4: 'Ako se vzdigne vladarjeva jeza zoper tebe, ne zapusti mesta svojega; kajti krotkost zabrani velike pregrehe.',
        5: 'Je zlo, ki sem ga videl pod solncem, pomota namreč, ki jo povzroča vladar:',
        6: 'neumnost posajajo na najvišja mesta in bogatini morajo sedeti na nizkih.',
        7: 'Videl sem hlapce na konjih, knezi pa so šli peš kakor hlapci.',
        8: 'Kdor koplje jamo, lahko pade vanjo, in kdor predira ograjo, ga piči gad.',
        9: 'Kdor lomi kamenje, se lahko ž njim poškoduje, in kdor kolje drva, je v nevarnosti od njih.',
        10: 'Kadar se železo skrha in ostrine kdo ne nabrusi, tedaj mora človek bolj napenjati svojo moč; ali modrost je koristna, da dosežeš uspeh.',
        11: 'Če kača piči, preden jo zakolne, nima nič dobička zaklinjalec.',
        12: 'Besede iz ust modrega moža so milobne, ustnice bedakove pa njega samega pogoltnejo.',
        13: 'Začetek besed ust njegovih je neumnost in konec govorjenja njegovega je zlobna blaznost.',
        14: 'Bedak rad govori veliko besed; toda človek ne ve, kaj bode, in kar pride za njim, kdo mu oznani?',
        15: 'Trud bedaka izmozgava, ker niti ne ve, kako bi šel v mesto.',
        16: 'Gorje ti, o dežela, ako je tvoj kralj otrok in tvoji knezi se gosté že zjutraj!',
        17: 'Srečna si, o dežela, če je tvoj kralj sin plemenitnikov in tvoji knezi jedo o pravem času v okrepčavo in ne iz požrešnosti!',
        18: 'Vsled lenobe gnije streha in po zanikarnosti kaplje v hišo.',
        19: 'Gostí se napravljajo v razveseljevanje in vino razvedruje življenje, denar pa zagotovi vse.',
        20: 'Ne preklinjaj kralja, še v svojih mislih ne, in v svoji spalnici ne kolni bogatina, kajti ptice nebeške bi odnesle glas in krilatci bi oznanil besedo.',
    },
    11: {
        1: 'Meči kruh svoj po vodi, kajti po mnogih dneh ga najdeš.',
        2: 'Daj po kosu sedmerim, tudi osmerim; zakaj ne veš, kaka nesreča se utegne pripetiti na zemlji.',
        3: 'Kadar so oblaki polni dežja, se izpraznjujejo na zemljo; in ko pade drevo proti jugu ali proti severu, na kateri kraj pade, tam obleži.',
        4: 'Kdor pazi na veter, ne bo sejal, in kdor gleda na oblake, ne bo žel.',
        5: 'Kakor ne veš, po kateri poti hodi veter in kako rasto kosti v materinem telesu, tako ne veš za delo Božje, ki dela vse.',
        6: 'Zjutraj sej seme svoje in zvečer ne daj počivati roki svoji; zakaj ne veš, katero bo raslo, ali to ali ono, in ako oboje hkratu zraste, tem bolje!',
        7: 'Res, sladka je svetloba in dobro de očem gledati solnce.',
        8: 'Zatorej če živi človek veliko let, naj se veseli v njih vseh, a pomni naj dni teme, da jih bode mnogo. Vse, kar prihaja, je ničemurnost.',
        9: 'Veseli se, o mladenič, v mladosti svoji in srce ti bodi dobre volje v dnevih mladosti tvoje, in hodi po potih, ki jih voli srce tvoje in jih gledajo oči tvoje, ali vedi, da te za to vse Bog privede na sodbo!',
        10: 'Zato odpravi nevoljo iz srca svojega in odstrani hudo od telesa svojega; kajti mladost in jutro življenja je ničemurnost.',
    },
    12: {
        1: 'In spominjaj se Stvarnika svojega v dnevih mladosti svoje, preden pridejo hudi dnevi in se približajo leta, o katerih porečeš: Niso mi všeč!',
        2: 'preden otemni solnce in svetloba in mesec in zvezde ter se oblaki povrnejo po dežju,',
        3: 'ob dnevi, ko bodo trepetali hišni varuhi in se močni možje skrivé in bodo mlinarji praznovali, ker jih je že malo, in se omračijo, ki skozi okna gledajo,',
        4: 'in se duri proti ulicam zapro; ko potihne mlina klopotanje in človek vztrepeče ob glasu ptička in se zamolklo glasé vse hčere petja;',
        5: 'ko se tudi bojí višine in strahote vidi na poti, in ko mandljevec cvete in se kobilica težko vzdigne in jed ne diši več; kajti človek odhaja v večno domovje svoje in žalujoči pohajajo po ulicah –',
        6: 'preden se utrga vrvica srebrna in se razbije zlata oljenica in se razpoči vedro pri studencu in se razdere črpalno kolo nad vodnjakom,',
        7: 'in prah se povrne v zemljo, kakor je bil, duh pa se vrne k Bogu, ki ga je dal.',
        8: 'Ničemurnost ničemurna! pravi Propovednik; vse je ničemurnost!',
        9: 'In ne samo moder je bil Propovednik, tudi ljudstvo je učil spoznanja, in globoko je premišljal in izpraševal, tudi je sestavil mnogo pregovorov.',
        10: 'Propovednik si je prizadeval, da najde prijetnih besed; in napisano je bilo, kar je pošteno, besede resnice.',
        11: 'Besede modrih so kakor ostni in kakor globoko zabiti žeblji so zbrani izreki; in izdal jih je eden pastir.',
        12: 'Sicer pa, sin moj, daj se posvariti: sestavljanje mnogih knjig nima konca, in mnogo učenja utruja telo.',
        13: 'Poslušajmo konec vse propovedi: Boga se boj in zapovedi njegove izpolnjuj, kajti to je vsa dolžnost človekova.',
        14: 'Zakaj Bog privede vsako delo, bodisi dobro ali hudo, na sodbo o vsem skritem.',
    },
}
