NAME = 'CebPinadayag: Cebuano Pinadayag'
BOOK = 'II Peter'

CHAPTERS = {
    1: {
        1: 'Si Simon Pedro, ulipon ug apostol ni Jesu-Cristo,',
        2: 'Ang grasya ug kalinaw ipadagaya unta kaninyo diha sa inyong kahibalo sa Dios ug kang Jesus nga atong Ginoo.',
        3: 'Ang iyang diosnong gahum naghatag kanato sa tanang butang bahin sa kinabuhi ug pagkadiosnon, pinaagi sa atong kahibalo kaniya nga nagtawag kanato sa iyang kaugalingong himaya ug pagkahalangdon,',
        4: 'nga tungod niana kita iyang gikahatagan sa bililhon ug dagku uyamot nga mga saad, aron nga pinaagi niini kamo managpakaikyas gikan sa pagpangadunot nga ania sa kalibutan tungod sa pangibog, ug mangahimo kamong mag-aambit sa diosnong kinaiya.',
        5: 'Ug tungod niining maong hinungdan, himoa ninyo ang tanang paningkamot aron nga sa inyong pagtoo ipuno ninyo ang maligdong nga batasan, ug sa maligdong nga batasan ipuno ang kahibalo,',
        6: 'ug sa kahibalo ipuno ang pagpugong sa kaugalingon, ug sa pagpugong sa kaugalingon ipuno ang pagkamainantuson, ug sa pagkamainantuson ipuno ang pagkadiosnon,',
        7: 'ug sa pagkadiosnon ipuno ang pagbati nga inigsoon, ug sa pagbati nga inigsoon ipuno ang gugma.',
        8: 'Kay kon kining mga butanga inyong mabatonan ug magatubo, kini magapahilayo kaninyo sa pagkataspukan o sa pagkadili mabungahon diha sa inyong kahibalo sa atong Ginoong Jesu-Cristo.',
        9: 'Kay bisan kinsa nga nakulangan niining mga butanga, siya buta ug igo lamang makakita sa duol ug nahikalimot nga siya nahinloan na gikan sa iyang karaan nga mga sala.',
        10: 'Busa, mga igsoon, paningkamoti sa labi pa gayud nga masiguro ang inyong pagkatinawag ug pagkapinili, kay kon inyong himoon kini, dili gayud kamo mahulog;',
        11: 'ug sa ingon niana aduna unyay madagayaong pagpahigayon alang kaninyo sa usa ka madaugong pagsulod ninyo ngadto sa dayong gingharian sa atong Ginoo ug Manluluwas nga si Jesu-Cristo.',
        12: 'Busa sa kanunay ako andam sa pagpahinumdum kaninyo niining mga butanga, bisan pa nga nasayud na kamo niini ug nalig-on na kamo sa kamatuoran nga inyong ginabatonan.',
        13: 'Akong giisip nga maoy matarung, samtang ania pa ako niining lawas, ang pagdasig kaninyo pinaagi sa pagpahinumdom kaninyo,',
        14: 'kay ako nasayud nga kining akong lawas dili na madugayng pagabiyaan, sumala sa gipadayag kanako sa atong Ginoong Jesu-Cristo.',
        15: 'Ug paningkamotan ko aron nga bisan kon unya patay na ako, makahimo gihapon kamo sa paghinumdom niining mga butanga bisan kanus-a.',
        16: 'Kay sa among pagpahibalo kaninyo sa gahum ug pag-anhi sa atong Ginoong Jesu-Cristo, kami wala magsubayg mga sugilanon nga maayong pagkaminaomao, hinonoa kami mga saksi-nga-nakakita sa iyang pagkahalangdon.',
        17: 'Kay sa iyang pagkadawat sa pasidungog ug himaya gikan sa Dios nga Amahan sa diha nga gihatud kaniya sa Halangdong Himaya ang tingog nga nag-ingon, "Kini mao ang akong pinalanggang Anak nga kaniya may kalipay ako,"',
        18: 'kami gayud mao ang nanagpakabati sa maong tingog gikan sa langit, kay kami uban man kaniya didto sa bukid nga balaan.',
        19: 'Labi pa gayud diay nga nahimatud-an ang pulong sa profesiya nga among ginabatonan. Maayo nga inyong himoon ang pagtagad niini maingon sa inyong pagtagad sa usa ka suga nga nagasiga sa dapit nga mangitngit, hangtud mobanagbanag ang panahon ug mosubang bitoong kabugason diha sa inyong mga kasingkasing.',
        20: 'Kinahanglan inyong mahibaloan kini, una sa tanan, nga walay profesiya diha sa kasulatan nga arang kahimoan sa kinaugalingon nga pagpanabut,',
        21: 'tungod kay wala may profesiya nga miabut pinaagi sa kabubot-on sa tawo, hinonoa minandoan sa Espiritu Santo nanagpanulti ang mga balaang tawo sa Dios.',
    },
    2: {
        1: 'Apan diha usab ing mga mini nga profeta sa taliwala sa katawhan, maingon nga sa taliwala ninyo aduna usab gayuy mobarug nga mga mini nga magtutudlo nga sa tago magapasulod sa makapadaut nga mga herejia, ug magapanghimakak pa gani sa Agalon nga maoy nagpalit kanila, ug busa magpahimutang sa kalit nga pagkalaglag diha sa ilang kaugalingon.',
        2: 'Ug daghan ang managsunod sa ilang pagpatuyang sa kaulag, ug tungod kanila pagapasipad-an ang dalan sa kamatuoran.',
        3: 'Ug tungod sa ilang kadalo kamo ilang panapion pinaagi sa tinumotomo nga mga pulong; sukad pa kaniadto sa karaan ang hukom kanila sa silot wala maghunong, ug ang ilang pagkalaglag wala magkatulog.',
        4: 'Kay kon ang mga manulonda wala kaloy-i sa Dios sa diha nga nakasala sila, hinonoa iyang gitambog sila ngadto sa infierno ug gibalhog ngadto sa mga lungib nga mangiob aron igatagana hangtud sa pagpanghukom;',
        5: 'kon ang karaang kalibutan wala kaloy-i sa Dios bisan tuod giluwas niya si Noe nga magwawali sa pagkamatarung kauban sa pito ka mga tawo, sa diha nga gipalunopan niya kadtong kalibutan sa mga dili diosnon;',
        6: 'kon sa iyang paghimong abo sa mga lungsod sa Sodoma ug Gomorra sila iyang gihukman ngadto sa pagkawagtang ug gihimong panig-ingnan alang kanila nga magkinabuhi nga dili diosnon;',
        7: 'ug kon iyang giluwas ang matarung nga si Lot nga naguol sa hilabihan tungod sa maulagon nga pagpatuyang sa mga tawong dautan',
        8: '(kay ang mga nakita ug nadungog sa maong matarung nga tawo samtang nagpuyo siya uban kanila, sa adlaw-adlaw nakapasakit sa iyang matarung nga kalag tungod sa ilang mga malinapasong binuhatan),',
        9: 'nan, ang Ginoo mahibalo sa pagluwas sa mga tawong diosnon gikan sa mga pagtintal, ug sa pagbantay nga ang mga dili matarung magapabilin ubos sa silot hangtud sa adlaw sa paghukom,',
        10: 'ug labi na gayud sila nga nagapahiuyon sa makapahugawng pangibog sa unod ug dili motagad sa langitnong kagamhanan.',
        11: 'samtang ang mga manolunda, bisan tuod labi pa silang kusgan ug gamhanan, dili man gani mopasipala paghukom batok kanila sa atubangan sa Ginoo.',
        12: 'Apan kini silang mga tawhana, sama sa walay kabuot nga mga mananap nga nanghimugso sa lonlon lamang kinaiya aron pagadakpon ug pagapatyon, nga nagapasipala sa mga butang nga wala nila mahibaloi kini sila pagalaglagon gayud unya diha sa mao rang pagkalaglag uban kanila,',
        13: 'nga magaantus sa kadaut nga balus sa ilang pagpangdaut. Alang kanila ang pagkalipay mao ang paghudyaka sa maadlaw. Sila mga buling ug mga hugaw, nga nanagpanghudyaka sa ilang pagpatuyang samtang anaa sila managkombira uban kaninyo.',
        14: 'Sila may mga mata nga puno sa panapaw ug dili matagbaw sa sala. Ilang ginahaylo ang maduhaduhaon nga mga tawo. Sila adunay mga kasingkasing nga batid sa kadalo, kaliwatan sila nga tinunglo!',
        15: 'Sila mitalikod sa matuod nga dalan ug nanghisalaag; sila nagasunod sa agi ni Balaam nga anak ni Beor, nga nahigugma sa suhol gikan sa pagkadili matarung,',
        16: 'apan nga gibadlong siya tungod sa iyang kaugalingong kalapasan; ang amang nga asno militok sa tawhanong paningog ug misumpo sa kaboang sa maong profeta.',
        17: 'Kini sila maoy mga tuboran nga walay tubig, ug mga gabon nga pinalid sa unos; alang kanila gitagana ang labing mangiob nga kangitngit.',
        18: 'Kay sa magalitok silag mga pinaburot nga kakawangan, pinaagi sa maulagon nga mga pangibog sa lawas, ilang ginahaylo ang mga tawo nga bag-o pa lamang nga nga nanagpakaikyas gikan kanila nga nagakinabuhi sa kasaypanan.',
        19: 'Sila magasaad kanilag kagawasan, samtang sa ilang kaugalingon sila mga ulipon nga iya sa pagkadunot; kay ang tawo ulipon man sa bisan unsa nga makabuntog kaniya.',
        20: 'Kay kon tapus sila makaikyas gikan sa mga kahugawan sa kalibutan pinaagi sa ilang kahibalo sa atong Ginoo ug Manluluwas nga si Jesu-Cristo, kon tapus niini sila magapusgapos pag-usab diha kanila ug pagabuntugon, ang ulahing kahimtang nila labi pa unyang mangil-ad kay sa nahauna.',
        21: 'Kay alang kanila maayo pa lamang unta hinoon nga wala sila mahibalo sa dalan sa pagkamatarung kay sa motalikod sila tapus mahibalo niini, motalikod gikan sa balaang sugo nga gitugyan kanila.',
        22: 'Sila hingmatud-an sa tinuod nga sanglitanan nga nagaingon, "Gibalikan sa iro ang iyang kaugalingong suka; ug tapus madigo ang anay, sa yanang mobalik siya sa paglunang."',
    },
    3: {
        1: 'Mga hinigugma, kini karon mao ang ikaduhang sulat nga gisulat ko kaninyo. Ug niining duha ko ka sulat nagadasig ako sa inyong lunsay nga salabutan agig pagpahinumdom;',
        2: 'nga kinahanglan inyong hinumduman ang mga profesiya sa balaang mga profeta ug ang sugo nga gihatag sa Ginoo ug Manluluwas pinaagi sa inyong mga apostoles.',
        3: 'Una sa tanan kinahanglan inyong mahibaloan kini, nga sa ulahing mga adlaw may mga mayubiton nga managpanungha nga managyubit, nga magapahiuyon sa ilang kaugalingong pangibog',
        4: 'ug magaingon, "Hain na man ang saad sa iyang pag-anhi? Kay sukad sa pagkamatay sa mga amahan, ang tanang mga butang nagapabilin man nga mao ra gihapon sukad pa sa pagkatukod sa kalibutan."',
        5: 'Sila nagpakabuta sa tinuod nga butang nga mao kini, nga sa karaang panahon pinaagi sa pulong sa Dios, dihay mga langit nga nanaglungtad, ug usa ka yuta nga naumol gikan sa tubig ug pinaagi sa tubig,',
        6: 'nga pinaagi niini ang kalibutan nga naglungtad kaniadto gilunopan sa tubig ug nalaglag.',
        7: 'Apan pinaagi sa mao ra usab nga pulong ang mga langit ug ang yuta nga karon nagalungtad gikatagana alang sa kalayo, ginatipigan alang sa adlaw sa panudya ug sa kalaglagan sa mga tawong dili diosnon.',
        8: 'Apan mga hinigugma, ayaw kamo pagpakabuta niining usa ka butang nga tinuod, nga alang sa Ginoo ang usa ka adlaw ingon sa usa ka libo ka tuig, ug ang usa ka libo ka tuig ingon sa usa ka adlaw.',
        9: 'Bahin sa iyang saad ang Ginoo dili langaylangayan, nianang paglangaylangay nga maoy pagsabut sa uban; hinonoa siya mapailubon kaninyo, nga wala magtinguha nga adunay mahanaw kondili nga ang tanan managpakakab-ot unta sa paghinulsol.',
        10: 'Apan ang adlaw sa Ginoo moabut sama sa usa ka kawatan, ug unya ang mga langit mawagtang uban sa dakung dinagook, ug ang mga kasugdanan sa kalibutan mangatunaw sa hilabihang kainit, ug pagasunogon ang yuta ug ang mga buhat nga ania niini.',
        11: 'Sanglit kining tanang mga butanga pagatunawon man sa ingon, pagkakinahanglanon gayud diay nga magkinabuhi kamo sa pagkabalaan ug pagkadiosnon,',
        12: 'nga magapaabut ug magapadali sa pag-abut sa adlaw sa Dios, nga tungod niini pagaduslitan ug pagatunawon ang mga langit, ug ang mga kasugdanan sa kalibutan mangatunaw sa kalayo!',
        13: 'Apan sumala sa iyang saad kita nagapaabut sa bag-ong nga langit ug usa ka bag-ong yuta diin nagapuyo ang pagkamatarung.',
        14: 'Busa, mga hinigugma, sanglit nagapaabut man kamo niining mga butanga, paningkamoti gayud ninyo nga mahikaplagan kamo nga wala untay buling o hugaw, ug nga maanaa kamo sa kalinaw.',
        15: 'Ug isipa ninyong kaluwasan ang pagkamainantuson sa Ginoo. Sa ingon usab niini ang atong hinigugmang igsoon nga si Pablo nagsulat kaninyo sumala sa kaalam nga gihatag kaniya,',
        16: 'nga nagsulti mahitungod niini sumala sa iyang ginahimo sa tanan niyang mga sulat; nga sa maong mga sulat aduna ganiy mga butang nga malisud sabton, nga ginatuis sa mga walay alamag ug sa mga mabalhinon ug kinaiya, ingon sa ginabuhat usab nila sa ubang kasulatan, sa pagtuis niini ngadto sa ilang kaugalingong pagkalaglag.',
        17: 'Busa, mga hinigugma, sa nasayud na kamong daan niini, magbantay kamo basi bayag madaldal kamo sa kasaypanan sa mga tawong masupilon ug mangahulog kamo ug mawad-an kamo sa inyong kalig-on.',
        18: 'Apan kinahanglan managtubo hinoon kamo sa grasya ug sa kahibalo sa atong Ginoo ug Manluluwas nga si Jesu-Cristo. Kaniya ang himaya karon ug hangtud sa kahangturan. Amen.',
    },
}
