NAME = 'GerTafel: German Tafelbibel (1911)'
BOOK = 'II Peter'

CHAPTERS = {
    1: {
        1: 'Simon Petrus, ein Knecht und Apostel Jesu Christi, denen, die mit uns durch die Gerechtigkeit unseres Gottes und Heilandes Jesus Christus den gleich teuren Glauben erlangt haben:',
        2: 'Gnade und Friede werde euch in Fülle zuteil durch die Erkenntnis Gottes und Jesus, unseres Herrn.',
        3: 'Weil uns Seine göttliche Kraft alles Vermögen zum Leben und zur Gottseligkeit geschenkt hat, durch die Anerkennung Dessen, Der uns durch Seine Herrlichkeit und Tugend berufen hat,',
        4: 'Mittelst welcher Er uns die herrlichsten und köstlichsten Verheißungen gegeben hat, auf daß ihr durch sie, nachdem ihr dem Verderben der Weltlust entronnen, göttlichen Wesens teilhaftig würdet.',
        5: 'So wendet denn allen Fleiß an, daß ihr durch den Glauben an Ihn Kraft zur Tugend, und durch die Kraft zur Tugend Erkenntnis,',
        6: 'Und durch die Erkenntnis Selbstbezwingung, und durch die Selbstbezwingung Standhaftigkeit,',
        7: 'Und durch die Standhaftigkeit Gottseligkeit, und durch die Gottseligkeit Bruderliebe, und durch die Bruderliebe Liebe',
        8: 'Denn wo solches bei euch ist, und immer mehr wird, läßt es euch nicht lässig noch unfruchtbar bleiben für die Erkenntnis unseres Herrn Jesus Christus.',
        9: 'Wer aber solches nicht hat, der ist blödsichtig, blind und vergißt, sich von seinen vorigen Sünden zu reinigen.',
        10: 'Darum fleißigt euch, Brüder, desto mehr, eure Berufung und Erwählung fest zu machen; denn so ihr solches tut, werdet ihr nimmermehr zu Fall kommen.',
        11: 'Denn so wird euch in reichem Maße die Gnade zuteil, zum ewigen Reiche unseres Herrn und Heilandes Jesus Christus einzugehen.',
        12: 'Darum will ich nicht unterlassen, euch immer daran zu erinnern, obwohl ihr es schon wißt und in der euch gewordenen Wahrheit befestigt seid.',
        13: 'Denn ich halte es für Pflicht, solange ich in dieser Hütte bin, euch durch Mahnungen wach zu erhalten;',
        14: 'Weil ich weiß, daß ich diese meine Hütte bald verlassen muß, wie mir auch unser Herr Jesus Christus kundgetan hat.',
        15: 'Ich will mich aber fleißigen, daß ihr nach meinem Hinscheiden dessen allezeit eingedenk bleibt.',
        16: 'Denn wir sind keinen schlau ersonnenen Märchen gefolgt, da wir euch die Kraft und Zukunft von Jesus Christus kund getan, und sind Augenzeugen Seiner Herrlichkeit geworden.',
        17: 'Denn Er empfing von Gott dem Vater Ehre und Preis, da unter herrlichem Glanze die Stimme von oben erscholl: Dies ist Mein lieber Sohn, an Dem Ich Wohlgefallen habe.',
        18: 'Und diese Stimme haben wir gehört, wie sie vom Himmel herabkam, da wir mit Ihm auf dem heiligen Berge waren.',
        19: 'Und wir haben ein noch festeres prophetisches Wort, auf das zu achten ihr wohl tut, als auf ein Licht, das da scheint an einem dunklen Ort, bis der Tag anbricht und der Morgenstern aufgeht in euren Herzen.',
        20: 'Und das sollt ihr vor allem wissen, daß jegliche Prophezeiung der Schrift nicht aus eigener Deutung geschieht.',
        21: 'Denn es ist noch keine Weissagung aus menschlichem Willen hervorgebracht worden, sondern, vom Heiligen Geist getrieben, haben heilige Männer Gottes geredet.',
    },
    2: {
        1: 'Es waren aber auch falsche Propheten unter dem Volk, wie auch unter euch falsche Lehrer sein werden, die verderbliche Sekten nebenbei einführen und den Herrn, Der sie erkauft hat, verleugnen und eine schnelle Verdammnis über sich herbeiführen werden.',
        2: 'Und viele werden ihnen ins Verderben nachfolgen, durch die der Weg der Wahrheit wird verlästert werden.',
        3: 'Und aus Gewinnsucht wollen sie euch mit Trugreden überlisten; aber das längst über sie verhängte Urteil säumt nicht, und ihre Verdammnis schlummert nicht.',
        4: 'Hat doch Gott der Engel, die gesündigt hatten, nicht verschont, sondern sie in Ketten der Finsternis in den Höllengrund verstoßen und dort lassen zum Gericht aufbewahren;',
        5: 'Und hat nicht der alten Welt verschont, sondern nur Noach, den Prediger der Gerechtigkeit, selbacht erhalten, über die Welt der Gottlosen aber die Sündflut herbeigeführt.',
        6: 'Auch hat Er die Städte Sodom und Gomorrah in Asche gelegt, umgekehrt und verdammt, und damit ein warnendes Beispiel für Gottlose gesetzt, die hernach kommen werden.',
        7: 'Und hat erlöst den gerechten Lot, dem die zügellosen Leute mit ihrem unzüchtigen Wandel alles Leid angetan;',
        8: 'Denn dem Gerechten, der unter ihnen wohnte, daß er es mit ansehen und hören mußte, quälten sie die gerechte Seele von Tag zu Tag mit ihren ungerechten Werken.',
        9: 'Der Herr weiß die Gottseligen aus der Anfechtung zu erlösen, die Ungerechten aber auf den Tag des Gerichtes zur Peinigung aufzubewahren;',
        10: 'Allermeist aber die, so nach dem Fleische ihrer unreinen Lust nachgehen, die Seine Herrschermacht verachten und in frecher Selbstgefälligkeit sich nicht scheuen, das, was herrlich ist, zu verlästern,',
        11: 'So doch die Engel, die größer an Stärke und Macht sind, gegen sie vor dem Herrn kein lästerndes Urteil fällen.',
        12: 'Aber sie sind wie unvernünftige, sinnliche Tiere, zum Fang und zur Schlachtung geboren, lästern, davon sie nichts wissen, und werden in ihrer Verderbnis umkommen,',
        13: 'Und so den Lohn der Ungerechtigkeit davontragen, weil sie ihre zeitliche Lust in sinnlichem Wohlleben finden, diese Schandund Lasterbuben, die sich noch auf ihre Betrügereien etwas zugute tun und mit euch schmausen;',
        14: 'Deren Augen voll Ehebruchs sind, die sich von der Sünde nicht abbringen lassen, und unbefestigte Seelen verlocken, deren Herz voll verschmitzter Habgier ist, Kinder des Fluches,',
        15: 'Die den geraden Weg verlassen, in der Irre gehen, und in dem Irrweg Bileams, des Sohnes Beors, folgen, den nach dem Lohne der Ungerechtigkeit gelüstete;',
        16: 'Er hatte aber eine Zurechtweisung für seine Übertretung; denn das stumme, lastbare Tier redete mit Menschenstimme und wehrte der Torheit des Propheten.',
        17: 'Das sind Brunnen ohne Wasser, Wolken, vom Wirbelwind umgetrieben, denen der Finsternis ewiges Dunkel vorbehalten ist.',
        18: 'Denn sie reden hohle Worte, da nichts dahinter ist, reizen durch fleischliche Lüste und Ausschweifungen solche an, die denen, welche auf Irrwegen gehen, schon entronnen waren,',
        19: 'Und verheißen ihnen Freiheit, indes sie selbst Knechte des Verderbens sind; denn wem einer untertan ist, dessen Knecht ist er.',
        20: 'Denn so sie den Befleckungen der Welt durch die Erkenntnis des Herrn und Heilandes Jesus Christus entgangen, aber wieder in solche hineingezogen werden und ihnen erliegen, ist mit ihnen das letzte ärger geworden, als das erste.',
        21: 'Denn es wäre ihnen besser gewesen, wenn sie den Weg der Gerechtigkeit nicht erkannt hätten, als daß sie, nachdem sie ihn erkannt, von dem heiligen Gebot, das ihnen gegeben ist, sich wieder abkehren.',
        22: 'Dann trifft bei ihnen das wahre Sprichwort ein: Der Hund frißt wieder, was er gespieen hat, und das Schwein wälzt sich nach der Schwemme wieder im Kot.',
    },
    3: {
        1: 'Dies, Geliebte, ist schon der zweite Brief, den ich euch schreibe, darin ich euch erinnere und ermahne zu lauterem Sinn,',
        2: 'Eingedenk zu sein der Worte, die euch zuvor von den heiligen Propheten gesagt worden sind, und unseres Gebotes, die wir Apostel des Herrn und Heilandes sind.',
        3: 'Und daß ihr vor allen Dingen wisset, daß in den letzten Tagen Spötter kommen werden, die mit ihrem Gespött nach ihren eigenen Gelüsten wandeln und sagen:',
        4: 'Wo ist die Verheißung Seiner Zukunft? Denn seit die Väter entschlafen sind, bleibt alles, wie es seit Anfang der Schöpfung gewesen ist.',
        5: 'Aber denen, die solches aufstellen wollen, ist unbekannt, daß Himmel von Alters her waren, und die Erde durch das Wort Gottes aus dem Wasser und durch Wasser erstanden ist,',
        6: 'Durch welches',
        7: 'Die jetzigen Himmel aber und die Erde werden durch Sein Wort aufbewahrt und für das Feuer behalten auf den Tag des Gerichts und der Verdammnis der gottlosen Menschen.',
        8: 'Eins aber sei euch unverhalten, Geliebte, daß ein Tag vor dem Herrn ist wie tausend Jahre, und tausend Jahre wie ein Tag.',
        9: 'Der Herr verzieht nicht mit Seiner Verhei-ßung, wie etliche es für einen Verzug erachten, sondern hat Geduld mit uns, und will nicht, daß etwelche verlorengehen, sondern daß sich alle zur Buße kehren.',
        10: 'Es wird aber der Tag des Herrn kommen wie ein Dieb in der Nacht, an dem die Himmel rauschend dahinfahren, ihre Grundstoffe brennen und zergehen, und die Erde mit den Gebilden auf ihr im Feuer aufgehen werden.',
        11: 'So nun all das vergeht, wie sehr müßt ihr euch befleißigen, in heiligem Wandel und in Gottseligkeit zu erscheinen,',
        12: 'Indem ihr erwartet und beschleunigt die Zukunft des Tages des Herrn, an dem die Himmel im Feuer zergehen und die Grundstoffe brennend zerschmelzen werden.',
        13: 'Wir erwarten nach Seiner Verheißung neue Himmel und eine neue Erde, in denen Gerechtigkeit wohnt.',
        14: 'Darum, Geliebte, weil ihr solches erwartet, befleißigt euch, daß ihr vor Ihm unbefleckt und unsträflich im Frieden erfunden werdet.',
        15: 'Und die Langmut unseres Herrn erachtet als Heil, gleichwie auch unser geliebter Bruder Paulus nach seiner ihm verliehenen Weisheit euch geschrieben hat;',
        16: 'Wie er auch in allen den Briefen tut, wenn er davon redet; wo einiges schwer zu verstehen ist, was Ungelehrige und Unbefestigte verdrehen, wie auch die anderen Schriften, zu ihrer eigenen Verdammnis.',
        17: 'Ihr aber, Geliebte, die ihr dies zuvor wißt, seid auf eurer Hut, daß ihr nicht durch die Irrlehre ruchloser Leute mitverführt und aus eurer eigenen festen Stellung hinweggerückt werdet.',
        18: 'Wachset vielmehr in der Gnade und Erkenntnis unseres Herrn und Heilandes Jesus Christus! Ihm sei Ehre nun und in alle Ewigkeit! Amen.',
    },
}
