NAME = 'FreGeneve1669: Le Nouveau Testament de la Bible de Genève de 1669'
BOOK = 'I Timothy'

CHAPTERS = {
    1: {
        1: 'PAUL Apoftre de Jefus Chrift par le mandement de Dieu noftre Sauveur, & du Seigneur Jefus Chrift noftre efperance:',
        2: 'A Timothée mon vrai fils en la foi, grace, & mifericorde, & paix de par Dieu noftre Pere, & de par Jefus Chrift noftre Seigneur.',
        3: "Suivant ce dont je t'ai prié que tu demeuraffes à Ephefe, quand j'allois en Macedone, je t'avertis que tu denonces à certains qu'ils n'enfeignent point une diverfe doctrine.",
        4: "Et qu'ils ne s'adonnent point aux fables & genealogies qui font fans fin, lefquelles engendrent pluftoft des queftions que l'edification de Dieu, laquelle confifte en foi.",
        5: "Or la fin du commandement, c'eft la charité procedante d'un cœur pur, & d'une bonne confcience, & d'une foi non feinte.",
        6: "Defquelles chofes quelques-uns s'eftant dévoyez, fe font deftournez à un vain babil:",
        7: "Voulant eftre docteurs de la Loi, n'entendant point les chofes qu'ils difent, ni defquelles ils affeurent.",
        8: "Or nous fçavons que la Loi eft bonne, fi quelqu'un en ufe legitimement:",
        9: "Sçachant cela, que la Loi n'eft point mife pour le jufte, mais pour les iniques, & qui ne fe peuvent ranger: pour ceux qui font fans pieté, & les mal-vivans: pour les gens fans religion, & profanes: pour les meurtriers de pere & de mere, & homicides:",
        10: "Pour les paillards, pour ceux qui habitent avec les mafles, les parjures: & s'il y a quelque autre chofe qui foit contraire à la faine doctrine:",
        11: "Suivant l'Evangile de la gloire de Dieu bien-heureux, lequel Evangile m'eft commis.",
        12: "Et je rens graces à celui qui m'a fortifié, affavoir à Jefus Chrift noftre Seigneur, de ce qu'il m'a eftimé fidele, m'ayant eftabli au miniftere:",
        13: "Moi qui eftois auparavant un blafphemateur, & perfecuteur, & oppreffeur: mais mifericorde m'a efté faite, entant que je l'ai fait par ignorance, eftant en infidelité.",
        14: "Mais la grace de noftre Seigneur a d'autant plus abondé avec foi & dilection, laquelle eft en Jefus Chrift.",
        15: "Cette parole eft certaine, & digne d'eftre entierement receuë, c'eft que Jefus Chrift eft venu au monde pour fauver les pecheurs, defquels je fuis le premier.",
        16: "Mais pour cette caufe mifericorde m'a efté faite, afin que Jefus Chrift montraft en moi le premier toute clemence, pour un exemplaire à ceux qui viendront à croire en lui à vie eternelle.",
        17: 'Or au Roi des fiecles, immortel, invifible, à Dieu feul fage, foit honneur & gloire és fiecles des fiecles. Amen.',
        18: 'Mon fils Timothée, je te recommande ce Commandement, que felon les propheties qui auparavant ont efté de toi, par elles tu faffes devoir de guerroyer en bonne guerre.',
        19: 'Ayant foi & bonne confcience, laquelle quelques-uns ayant rejettée ont fait naufrage quant à la foi:',
        20: "D'entre lefquels font Hymenée, & Alexandre, lefquels j'ai livré à Satan, afin qu'ils apprennent par ce chaftiment à ne plus blafphemer.",
    },
    2: {
        1: "J'ADMONESTE donc qu'avant toutes chofes on faffe des requeftes, des fupplications & des actions de graces pour tous les hommes:",
        2: 'Pour les Rois, & pour tous ceux qui font conftituez en dignité, afin que nous puiffions mener une vie paifible & tranquille, en toute pieté & honnefteté.',
        3: 'Car cela eft bon & agreable devant Dieu noftre Sauveur:',
        4: 'Lequel veut que tous les hommes foyent fauvez, & viennent à la connoiffance de la verité.',
        5: 'Car il y a un feul Dieu, & un feul Moyenneur entre Dieu & les hommes, affavoir Jefus Chrift homme:',
        6: "Qui s'eft donné foi-mefme en rançon pour tous, afin d'eftre en témoignage en fon propre temps.",
        7: "A quoi j'ai efté eftabli Heraut & Apoftre (je dis verité en Chrift, je ne mens point) Docteur des Gentils en foi & en verité.",
        8: 'Je veux donc que les hommes prient en tout lieu, levant leurs mains pures, fans colere, & fans queftion.',
        9: "Pareillement auffi que les femmes fe parent d'un accouftrement honnefte avec vergogne & modeftie, non point avec treffes, ni or, ni perles, ni habillemens fomptueux:",
        10: 'Mais de bonnes œuvres, comme il eft feant à des femmes qui font profeffion de fervir Dieu.',
        11: 'Que la femme apprene en filence, en toute fujettion.',
        12: "Car je ne permets point que la femme enfeigne, ni qu'elle ufe d'authorité fur le mari, mais qu'elle foit en filence.",
        13: 'Car Adam a efté formé le premier, & puis apres Eve.',
        14: "Et ce n'a point efté Adam qui a efté feduit, mais la femme ayant efté feduite, a efté en tranfgreffion.",
        15: 'Or elle fera fauvée en engendrant des enfans, fi elle demeure en foi, dilection, & fanctification, avec modeftie.',
    },
    3: {
        1: "CETTE parole eft certaine, Si quelqu'un a affection d'eftre Evefque, il defire une œuvre excellente.",
        2: "Mais il faut que l'Evefque foit irreprehenfible, mari d'une feule femme, vigilant, attrempé, honorable, hofpitalier, propre à enfeigner:",
        3: 'Non point addonné au vin, non batteur, non convoiteux de gain deshonnefte: mais benin, non quereleux, non avaricieux:',
        4: 'Conduifant honneftement fa propre maifon, ayant fes enfans fujets en toute reverence:',
        5: "(Car fi quelqu'un ne fçait pas conduire fa propre maifon, comment pourra-t'il gouverner l'Eglife de Dieu?)",
        6: "Non point nouvel apprenti: de peur qu'eftant enflé d'orgueil: il ne tombe en la condamnation du calomniateur.",
        7: "Il faut auffi qu'il ait bon témoignage de ceux qui font de dehors, afin qu'il ne tombe point en reproche, & au piege du diable.",
        8: 'Semblablement il faut que les Diacres foyent graves, non doubles en parole, non adonnez à beaucoup de vin, non convoiteux de gain deshonnefte:',
        9: 'Retenans le myftere de la foi en une confcience pure.',
        10: "Et que ceux-ci auffi foyent premierement efprouvez, puis qu'ils fervent, eftant trouvez irreprehenfibles.",
        11: 'Semblablement il faut que leurs femmes foyent honneftes, non mefdifantes, fobres, fideles en toutes chofes.',
        12: "Que les Diacres foyent maris d'une feul femme, conduifant honneftes leurs enfans, & leurs propres maifons.",
        13: 'Car ceux qui auront bien fervi, acquierent un bon degré pour eux, & une grande liberté en la foi, laquelle eft en Jefus Chrift.',
        14: "Je t'écris ces chofes, efperant que je viendrai bien-toft vers toi:",
        15: "Que fi je tarde, c'eft afin que tu fçaches, comment il faut converfer en la maifon de Dieu, qui eft l'Eglife du Dieu vivant, la colomne & l'appui de la vérité.",
        16: 'Et fans contredit le myftere de pieté eft grand, affavoir que Dieu a efté manifefté en chair, juftifié en Efprit, veu des Anges, prefché aux Gentils, creu au monde, & enlevé en gloire.',
    },
    4: {
        1: "OR l'Efprit dit notamment qu'és derniers temps, quelques-uns fe revolteront de la foi, s'adonnant aux efprits abufeurs, & aux doctrines des diables:",
        2: 'Enfeignant des menfonges par hypocrifie, eftant cauterizez en leur propre confcience:',
        3: "Defendant de fe marier, commandant de s'abftenir des viandes que Dieu a creées pour les fideles: & pour en ufer avec action de graces.",
        4: "Car toute creature de Dieu eft bonne, & rien n'eft à rejetter, eftant pris avec action de graces.",
        5: 'Car elle eft fanctifiée par la parole de Dieu, & par la priere.',
        6: 'Si tu propofes ces chofes aux freres, tu feras bon Miniftre de Jefus Chrift, nourri és paroles de la foi & de la bonne doctrine que tu as foigneufement fuivie.',
        7: "Mais rejette les fables profanes, & femblables à celles des vieilles: & t'exerce en la pieté.",
        8: "Car l'exercice corporel eft profitable à peu de chofes, mais la pieté eft profitable à toutes chofes, ayant les promeffes de la vie prefente, & de celle qui eft à venir.",
        9: "Cette parole eft certaine, & digne d'eftre entierement receuë.",
        10: 'Car pour cela auffi nous travaillons, & fommes en opprobre, parce que nous efperons au Dieu vivant: qui eft le confervateur de tous les hommes, mais principalement des fideles.',
        11: 'Annonce ces chofes, & les enfeigne.',
        12: 'Que nul ne mefprife ta jeuneffe: mais fois patron des fideles en paroles, en converfation, en dilection, en efprit, en foi, en pureté.',
        13: "Sois attentif à la lecture, à l'exhortation, & a l'endoctrinement jufques à ce que je vienne.",
        14: "Ne neglige point le don qui eft en toi, lequel t'a efté donné par prophetie, par l'impofotion des mains de la compagnie des Anciens.",
        15: "Pratique ces chofes, & y fois attentif: afin qu'il foit connu à tous que tu profites.",
        16: "Entens à toi & à l'endoctrinement: fois perfeverant en ces chofes: car en ce faifant tu te fauveras toi-mefme, & ceux qui t'écoutent.",
    },
    5: {
        1: "NE reprens pas rudement l'homme ancien; mais admonefte le comme pere: les jeunes comme freres:",
        2: 'Les femmes anciennes comme meres: les jeunes comme fœurs, en toue pureté.',
        3: 'Honore les veuves qui font vraiment veuves.',
        4: "Mais fi quelque veuve a des enfans ou des enfans de fes enfans, qu'ils apprennent premierement à montrer leur pieté envers leur propre maifon, & à rendre la pareille à leurs devanciers: car cela eft bon & agreable devant Dieu.",
        5: 'Or celle qui eft vraiment veuve & delaiffée feule, efpere en Dieu, & perfevere en prieres & oraifons nuit & jour.',
        6: 'Mais celle qui vit en delices, eft morte en vivant.',
        7: "Denonce donc ces chofes, afin qu'elles foyent irreprehenfibles.",
        8: "Que fi quelqu'un n'a pas foin des fiens, & principalement de ceux de fa famille, il a renié la foi, & eft pire qu'un infidele.",
        9: "Que la veuve foit enrôlée n'ayant pas moins de foixante ans, & qui ait efté femme d'un feul mari:",
        10: "Ayant témoignage d'avoir fait de bonnes œuvres, fi elle a nourri fes propres enfans, fi elle a logé les eftrangers, fi elle a lavé les pieds des Saints, fi elle a fubvenu aux affligez, fi elle a foigneufement fuivi toute bonne œuvre.",
        11: 'Mais refufe les veuves qui font plus jeunes: car quand elles font devenuës lafcives contre Chrift, elles fe veulent marier:',
        12: "Ayant leur condamnation, entant qu'elles ont fauffé leur premiere foi.",
        13: "Et avec cela auffi eftant oifeufes, elles apprennent d'aller de maifon en maifon: & font non feulement oifeufes, mais auffi babillardes, & curieufes, en babillant de chofes malfeantes.",
        14: "Je veux donc que les jeunes veuves fe marient, qu'elles procréent lignée, qu'elles gouvernent le mefnage: & qu'elles ne donnent aucune occafion à l'adverfaire de mefdire.",
        15: 'Car quelques-unes fe font déja devoyées apres Satan.',
        16: "Que fi quelque homme ou femme fidele a des veuves, qu'il leur fubvienne, & que l'Eglife n'en foit point chargée, afin qu'il y ait affez pour celles qui font vraiment veuves.",
        17: "Que les Anciens qui prefident deuëment, foyent reputez dignes de double honneur: principalement ceux qui travaillent en la Parole & en l'endoctrinement.",
        18: "Car l'Efcriture dit, Tu n'emmufeleras point le bœuf qui foule le grain: Et l'ouvrier eft digne de fon falaire.",
        19: "Ne reçoi point d'accufation contre l'Ancien, finon fous deux ou trois tefmoins.",
        20: 'Reprens publiquement ceux qui pechent, afin que les autres auffi en ayent crainte.',
        21: "Je t'adjure devant Dieu, & le Seigneur Jefus Chrift, & les Anges éleus, que tu gardes ces chofes fans preferer l'un à l'autre, ne faifant rien en panchant d'un cofté.",
        22: "N'impofe point haftivement les mains fur aucun, & ne communique point aux pechez d'autrui: garde toi pur toi-mefme.",
        23: "Ne boi plus d'eau, mais ufe d'un peu de vin à caufe de ton eftomac, & à caufe des maladies que tu as fouvent.",
        24: "Les pechez de quelques-uns fe manifeftent devant, & viennent en avant à leur condamnation: mais en d'autres ils fuivent apres.",
        25: 'Semblablement auffi les bonnes œuvres fe manifeftent devant, & celles qui font autrement ne peuvent eftre cachées.',
    },
    6: {
        1: 'QUE tous ferfs qui font fous le joug, reputent leur propres maiftres dignes de tout honneur, afin que le Nom de Dieu & fa doctrine ne foit blafphemée.',
        2: "Et ceux qui ont des maiftres fideles, qu'ils ne les méprifent point à caufe qu'ils font freres, mais pluftoft qu'ils les fervent, à caufe qu'ils font fideles & bien-aimez, eftant participans du benefice. Enfeigne ces chofes, & exhorte.",
        3: "Si quelqu'un enfeigne autrement, & ne confent point aux faines paroles de noftre Seigneur Jefus Chrift, & à la doctrine qui eft felon la pieté;",
        4: "Il eft enflé, ne fçachant rien, mais eftant fol apres des queftions & debats de paroles, defquelles s'engendrent envies, querelles, médifances, mauvais foupçons,",
        5: "Vaines difputes d'hommes qui font corrompus d'entendement, & deftituez de verité, reputans la pieté eftre gain: retire toi de ceux qui font tels.",
        6: "Or la pieté avec contentement d'efprit eft un grand gain.",
        7: "Car nous n'avons rien apporté au monde: auffi eft-il evident que nous n'en pouvons rien emporter.",
        8: 'Mais ayans la nourriture, & dequoi nous puiffions eftre couverts, cela nous fuffira.',
        9: 'Or ceux qui veulent devenir riches, tombent en tentation, & au piege, & en plufieurs defirs fols & nuifibles, qui plongent les hommes en deftruction & perdition.',
        10: "Car la racine de tous maux c'eft la convoitife des richeffes: defquelles quelques-uns ayans envie, fe font defvoyez de la foi, & font eux-mefmes enferrez en plufieurs douleurs.",
        11: 'Mais toi, ô homme de Dieu, fui ces chofes, & pourchaffe juftice, pieté, foi, charité, patience, debonnaireté.',
        12: 'Combats le bon combat de la foi: apprehende la vie eternelle, à laquelle auffi tu es appellé, & en as fait une bonne profeffion devant beaucoup de tefmoins.',
        13: "Je t'enjoins devant Dieu qui vivifie toutes chofes, & devant Jefus Chrift qui a fait cette belle confeffion devant Ponce Pilate:",
        14: "Que tu gardes ce commandement, eftant fans macule & fans reprehenfion, jufques à l'apparition de noftre Seigneur Jefus Chrift.",
        15: 'Laquelle le bien-heureux & feul Prince, Roi des rois, & Seigneur des Seigneurs, montrera en fa propre faifon.',
        16: "Lequel feul a immortalité, & habite en une lumiere inacceffible; lequel nul des hommes n'a veu, & ne peut voir: auquel foit honneur & force eternelle. Amen.",
        17: "Denonce à ceux qui font riches en ce monde, qu'ils ne foyent point hautains: qu'ils ne mettent point leur confiance en l'incertitude des richeffes, mais au Dieu vivant qui nous baille toutes chofes abondamment pour en joüir.",
        18: "Qu'ils faffent du bien, qu'ils foyent riches en bonnes œuvres, qu'ils foyent faciles à diftribuer, communicatifs:",
        19: "Se faifans un trefor d'un bon fondement pour l'avenir, afin qu'ils apprehendent la vie eternelle.",
        20: "O Timothée! Garde le depoft, fuyant les crieries vaines & profanes, & les contradictions d'une fcience fauffement ainfi nommée:",
        21: 'De laquelle quelques-uns faifant profeffion, fe font dévoyez de la foi. Grace foit avec toi. Amen.',
    },
}
