NAME = 'ACV: A Conservative Version'
BOOK = 'I Timothy'

CHAPTERS = {
    1: {
        1: 'Pavel, apostol Kristusa Jezusa po povelju Boga, Rešitelja našega, in Kristusa Jezusa, upanja našega,',
        2: 'Timoteju, pravemu otroku svojemu v veri: Milost, usmiljenje, mir od Boga Očeta in Kristusa Jezusa, Gospoda našega.',
        3: 'Kakor sem te prosil, potujoč v Macedonijo, da ostani v Efezu, da zapoveš nekaterim, naj ne uče drugačnega nauka,',
        4: 'tudi naj se ne ubijajo z basnimi in brezkončnimi rodopisi, ki pospešujejo bolj prepire nego oskrbovanje službe Božje, ki je v veri, tako te prosim zdaj.',
        5: 'Namen zapovedi pa je ljubezen iz čistega srca in dobre vesti in nehinavske vere,',
        6: 'kar so nekateri zgrešili in se obrnili k praznemu besedovanju,',
        7: 'hoteč biti učeniki postave, dasi ne umejo, ne kaj govore, ne kaj trdijo.',
        8: 'Vemo pa, da je postava dobra, če jo kdo postavno rabi,',
        9: 'v svesti si, da za pravičnega ni postavljena postava, ampak za nepravične in uporne, brezbožne in grešnike, nesvete in skrunilce svetega, ubijalce očeta in matere, ljudomorce,',
        10: 'nečistnike, moželežnike, ljudokradce, lažnike, krivoprisežnike in če je še kaj drugega nasprotnega zdravemu uku;',
        11: 'kakor priča evangelij slave blaženega Boga, ki je bil poverjen meni.',
        12: 'Hvaležen sem njemu, ki mi je dal moč, Kristusu Jezusu, Gospodu našemu, da me je za zvestega imel in me postavil v službo,',
        13: 'ki sem bil prej preklinjalec in preganjalec in silovitnik; ali usmiljenje sem zadobil, ker sem delal to iz nevednosti v neveri;',
        14: 'preobilo pa se je pomnožila milost Gospoda našega z vero in ljubeznijo, ki je v Kristusu Jezusu.',
        15: 'Resnična je ta beseda in vsekakor vredna, da se sprejme: da je Kristus Jezus prišel na svet rešit grešnike, katerih prvi sem jaz.',
        16: 'Ali zato sem zadobil usmiljenje, da bi na meni prvem Kristus Jezus pokazal vso svojo potrpežljivost, za zgled njim, ki bodo verovali vanj za večno življenje.',
        17: 'Kralju vekov pa, neminljivemu, nevidnemu, edinemu Bogu, čast in slava na vekov veke! Amen.',
        18: 'To zapoved ti izročam, moj otrok Timotej, po prejšnjih prorokovanjih o tebi, da biješ po njih dobri boj',
        19: 'in ohraniš vero in dobro vest, ki so jo nekateri pahnili od sebe ter se ponesrečili v veri;',
        20: 'med katerimi sta Himenej in Aleksander, ki sem ju izročil satanu, da se po kazni naučita ne preklinjati.',
    },
    2: {
        1: 'Opominjam torej pred vsem, naj se opravljajo prošnje, molitve, klici, zahvale za vse ljudi,',
        2: 'za kralje in vse prvake, da živimo mirno in tiho življenje v vsej pobožnosti in poštenosti.',
        3: 'To je dobro in prijetno pred Bogom, Rešiteljem našim,',
        4: 'ki hoče, da se rešijo vsi ljudje in pridejo do spoznanja resnice.',
        5: 'Zakaj eden je Bog, eden tudi srednik med Bogom in ljudmi, človek Kristus Jezus,',
        6: 'ki je dal samega sebe v odkupnino za vse, v pričevanje ob svojem času;',
        7: 'za kar sem bil jaz postavljen kot glasnik in apostol (resnico govorim, ne lažem), učitelj poganov v veri in resnici.',
        8: 'Hočem torej, da molijo možje v vsakem kraju, dvigajoč svete roke brez jeze in dvoma.',
        9: 'Istotako tudi žene v spodobni opravi, naj se dičijo s sramežljivostjo in zmernostjo, ne s kitami ali z zlatom ali z biseri ali z drago obleko,',
        10: 'marveč (kakor se spodobi ženskam, ki pripoznavajo bogaboječnost) z dobrimi deli.',
        11: 'Žena naj se na tihem uči v vsej podložnosti.',
        12: 'Ženi pa učiti ne dovoljujem, ne gospodovati možu, nego naj živi na tihem.',
        13: 'Kajti Adam je bil prvi ustvarjen, potem Eva;',
        14: 'in Adam ni bil prevaran, žena pa je prevarana padla v pregreho;',
        15: 'rešena pa bo v rojenju otrok, ako ostane v veri in ljubezni in posvečenju z zmernostjo.',
    },
    3: {
        1: 'Resnica je beseda: Če kdo išče škofovske službe, želi lepega dela.',
        2: 'Škof torej treba, da je brez oponosa, ene žene mož, trezen, zmeren, spodoben, gostoljuben, dober učitelj;',
        3: 'ne pijanec, ne pretepač, ampak krotak, ne prepirljiv, ne denarja lakomen;',
        4: 'svoji hiši dober gospodar, otroke strahujoč, da so pokorni, z vso resnobo',
        5: '(če pa kdo svoji hiši ne zna gospodariti, kako bo skrbel za cerkev Božjo?)',
        6: 'ne novinec, da napihnjen ne pade v obsodbo hudičevo.',
        7: 'Treba pa tudi, da ima dobro pričevanje od teh, ki so zunaj, da ne pade v očitanje in past hudičevo.',
        8: 'Diakoni istotako treba, da so resnobni, ne dvojezični, ne mnogemu vinu vdani, ne grdega dobička željni;',
        9: 'ki hranijo skrivnost vere v čisti vesti.',
        10: 'A tudi ti naj se najprej preizkusijo; potem naj služijo kot diakoni, ako so brez graje.',
        11: 'Žene istotako, da so resnobne, ne obrekljive, trezne, zveste v vsem.',
        12: 'Diakoni naj bodo ene žene možje, otrokom in svojim hišam dobri gospodarji.',
        13: 'Kateri so namreč dobro opravljali diakonsko službo, si pridobé lepo stopnjo in veliko srčnost v veri, ki je v Kristusu Jezusu.',
        14: 'To ti pišem, upajoč, da skoro pridem k tebi;',
        15: 'ako se pa zamudim, da veš, kako se je treba vesti v hiši Božji, ki je cerkev Boga živega, stolp in podstavek resnice.',
        16: 'In kakor vsi priznavamo, velika je skrivnost pobožnosti: on, ki je bil razodet v mesu, je bil opravičen v duhu, prikazal se je angelom, je bil oznanjevan poganom, verovalo se mu je na svetu, gori je bil vzet v slavi.',
    },
    4: {
        1: 'Duh pa razločno pravi, da bodo v poslednjih časih nekateri odpadli od vere in poslušali zapeljive duhove in nauke hudobnih duhov,',
        2: 'vsled licemerstva lažigovornikov, ki nosijo vžgano znamenje v svoji vesti,',
        3: 'ki branijo ženiti se in možiti in zapovedujejo zdrževati se jedil, katera je Bog ustvaril, da jih z zahvaljevanjem uživajo verni in ti, ki so spoznali resnico.',
        4: 'Kajti vsaka stvar Božja je dobra in ničesar ni, da bi zametali, ako prejemljemo z zahvaljevanjem:',
        5: 'posvečuje se namreč po besedi Božji in molitvi.',
        6: 'To naročajoč bratom, bodeš dober služabnik Kristusa Jezusa, vzrejen v besedah vere in dobrega nauka, ki si mu doslej sledil.',
        7: 'Posvetne in starobabje basni pa zavračaj. Vadi se pa v pobožnosti;',
        8: 'zakaj telesna vaja je za malo koristna, pobožnost pa je za vse koristna, ker ima obljubo življenja sedanjega in prihodnjega.',
        9: 'Resnična je ta beseda in vsekakor vredna, da se sprejme.',
        10: 'Kajti zato se tudi trudimo in nas sramoté, ker smo upanje svoje postavili na živega Boga, ki je Rešitelj vseh ljudi, sosebno vernih.',
        11: 'Zapoveduj to in úči!',
        12: 'Nihče naj ne zaničuje mladosti tvoje; marveč zgled bodi vernim v besedi, v vedenju, v ljubezni, v veri, v čistosti.',
        13: 'Dokler ne pridem, bodi priden v branju, opominjanju, poučevanju.',
        14: 'Ne zanemarjaj daru milosti, ki je v tebi, ki ti je bil dan po proroštvu s pokladanjem rok starejšinstva.',
        15: 'Za to skrbi, v tem bivaj, da bode napredek tvoj očiten vsem.',
        16: 'Pazi nase in na svoj nauk. Stanoviten bodi v tem; kajti to delajoč, boš rešil sebe in nje, ki te poslušajo.',
    },
    5: {
        1: 'Starejšega ne prijemlji trdo, temuč opominjaj ga kakor očeta, mlajše kakor brate,',
        2: 'žene starejše kakor matere, mlajše kakor sestre, v vsej čistosti.',
        3: 'Vdove spoštuj, ki so res vdove.',
        4: 'Ako pa ima kaka vdova otroke ali vnuke, ti naj se uče najprej izkazovati spoštovanje do svoje hiše in povračati roditeljem; zakaj to je prijetno pred Bogom.',
        5: 'Katera je pa res vdova in osamela, je postavila upanje svoje na Boga in je stanovitna v prošnjah in molitvah noč in dan.',
        6: 'Razuzdana pa je mrtva, dasi še živi.',
        7: 'Tudi to zapoveduj, da bodo brez oponosa.',
        8: 'Ako pa kdo ne skrbi za svoje, zlasti pa za domače, je zatajil vero in je hujši od nevernika.',
        9: 'Vdova naj se ne sprejme pod šestdesetimi leti v imenik, ki je bila enega moža žena',
        10: 'in je na dobrem glasu zaradi dobrih del, če je vzredila otroke, če je sprejemala tujce, če je svetim umivala noge, če je pomagala stiskanim, če si je prizadevala za sleherno dobro delo.',
        11: 'Mlajših vdov pa ne sprejmi v imenik; ko so namreč pohotne postale zoper Kristusa, se hočejo možiti',
        12: 'in si nakopljejo sodbo, ker so se izneverile prvi veri.',
        13: 'Zraven pa se tudi navadijo brez dela pohajkovati po hišah; in ne samo brez dela, ampak tudi jezične in vedečne so, govoreč, česar ni potreba.',
        14: 'Hočem torej, da naj se mlajše možé, otroke rode, gospodinjijo in nobenega povoda ne dajo nasprotniku za obrekovanje.',
        15: 'Kajti že se jih je nekaj odvrnilo za satanom.',
        16: 'Če ima kateri vernik ali vernica vdove, naj jim pomaga, in cerkev ne imej težave, da more pomagati pravim vdovam.',
        17: 'Starejšine, ki so dobri predstojniki, naj štejejo za dvojne časti vredne, zlasti nje, ki se trudijo v besedi in poučevanju.',
        18: 'Pismo namreč govori: „Ne zaveži gobca volu, ki vrši žito“, in: Vreden je delavec svojega plačila.',
        19: 'Zoper starejšino ne sprejmi tožbe, razen na dve priči ali tri.',
        20: 'Tiste, ki greše, svari vpričo vseh, da bodo imeli tudi drugi strah.',
        21: 'Rotim te pred Bogom in Kristusom Jezusom in angeli izvoljenimi, da hraniš to brez predsodka in ne storiš ničesar po lastnem nagnjenju.',
        22: 'Rok nikomur prenaglo ne pokladaj in ne udeležuj se tujih grehov. Ohrani samega sebe čistega.',
        23: 'Ne pij več same vode, ampak uživaj malo vina, zaradi želodca svojega in pogostnih slabosti svojih.',
        24: 'Nekaterih ljudi grehi so očitni in gredo pred njimi v sodbo; nekaterim pa tudi slede šele pozneje.',
        25: 'Tako so tudi dobra dela očitna, in ona, ki je drugače ž njimi, se ne dado skriti.',
    },
    6: {
        1: 'Vsi, ki so kot hlapci pod jarmom, naj imajo svoje gospodarje za vse časti vredne, da se ne govori grdo o imenu Božjem in nauku.',
        2: 'Kateri pa imajo verne gospodarje, naj jih ne zaničujejo, ker so bratje; ampak tem rajši naj služijo, ker so verni in ljubljeni, kateri prejemajo to dobroto. To uči in opominjaj.',
        3: 'Ako kdo drugače uči in noče pristati na zdrave besede, besede Gospoda našega Jezusa Kristusa, in na nauk, ki vodi k pobožnosti,',
        4: 'je napihnjen in ničesar ne ume, marveč boleha za pregovarjanjem in besednimi prepiri, iz katerih se izcimi zavist, pričkanje, preklinjanje, natolcevanje,',
        5: 'neprestano besedičenje ljudi, popačenih na umu in brez resnice, ki mislijo, da je pobožnost dobiček.',
        6: 'Je pa velik dobiček pobožnost, združena z zadovoljnostjo.',
        7: 'Zakaj ničesar nismo prinesli na svet, ker tudi odnesti ne moremo ničesar;',
        8: 'če pa imamo hrane in odeje, bodimo s tem zadovoljni.',
        9: 'Kateri pa hočejo biti bogati, padejo v izkušnjavo in past in v mnoga poželenja, nespametna in škodljiva, ki pogrezajo ljudi v pogubljenje in pogin.',
        10: 'Korenina vsega zlega namreč je srebroljubje; njemu vdani, so nekateri zabredli od vere in sami so se presunili z mnogimi bolečinami.',
        11: 'Ti pa, o človek Božji, beži od tega; hodi pa za pravičnostjo, pobožnostjo, vero, ljubeznijo, stanovitnostjo, krotkostjo.',
        12: 'Bij dobri boj vere, poprimi se večnega življenja, ki si bil zanje poklican in si pripoznal lepo veroizpoved pred mnogimi pričami.',
        13: 'Zapovedujem ti pred Bogom, ki vse oživlja, in Kristusom Jezusom, ki je izpričal pred Poncijem Pilatom lepo izpoved,',
        14: 'da hraniš zapoved brez madeža, brez graje do prikazni Gospoda našega Jezusa Kristusa,',
        15: 'ki jo pokaže ob svojem času blaženi in edini Vladar, Kralj kraljujočih in gospodujočih Gospod,',
        16: 'ki ima sam neumrjočnost in biva v nedostopni svetlobi, ki ga ni videl ljudi nobeden in ga tudi videti ne more; njemu čast in moč večna! Amen.',
        17: 'Bogatinom v sedanjem svetu zapoveduj, naj se ne prevzemajo, niti ne stavijo upa v bogastva negotovost, ampak v živega Boga, ki nam deli vsega obilo za uživanje;',
        18: 'naj dobro delajo, bogaté v dobrih delih, naj bodo radodarni, sočutni,',
        19: 'nabirajoč si zaklade v dobro podstavo za prihodnost, da se poprimejo resničnega življenja.',
        20: 'O Timotej, hrani to, kar ti je poverjeno, ogibajoč se posvetnega govoričenja in nasprotij znanosti, ki se po krivem tako imenuje;',
        21: 'katero si pripisujoč, so nekateri zgrešili vero. Milost bodi z vami!',
    },
}
