NAME = 'SweKarlXII: Svenska Karl XII:s Bibel (1703)'
BOOK = 'Philippians'

CHAPTERS = {
    1: {
        1: 'Paulus och Thimotheus, Jesu Christi tjenare, allom heligom i Christo Jesu, som äro i Philippis, samt med Biskopar och tjenare.',
        2: 'Nåd vare med eder, och frid af Gudi, vårom Fader, och Herranom Jesu Christo.',
        3: 'Jag tackar min Gud, så ofta jag tänker på eder;',
        4: 'Hvilket jag alltid gör i alla mina böner för eder alla, och gör samma bön med glädje;',
        5: 'Att I ären delaktige vordne i Evangelio, ifrå första dagen intill nu;',
        6: 'Och förser mig detsamma, att den uti eder ett godt verk begynt hafver, han skall det ock fullborda, intill Jesu Christi dag;',
        7: 'Såsom mig rätt är, att jag den meningen hafver om eder alla; derföre att jag i minom bojom, i hvilkom jag försvarar och stadfäster Evangelium, hafver eder i mitt hjerta, såsom de der alle med mig delaktige ären i nådene.',
        8: 'Ty Gud är mitt vittne, huru jag åstundar eder alla af hjertans grund i Jesu Christo;',
        9: 'Och beder, att edar kärlek ju mer och mer må rik varda i all kunskap, och i allt förstånd;',
        10: 'Att I mågen bepröfva hvad bäst är; på det I mågen vara rene, och ingom till förargelse, intill Christi dag;',
        11: 'Uppfyllde med rättfärdighetenes frukt, hvilken genom Jesum Christum kommer till Guds pris och lof.',
        12: 'Jag vill att I veta skolen, käre bröder, att det med mig skedt är, det är mer kommet Evangelio till framgång;',
        13: 'Så att mina bojor äro uppenbara vordna i Christo, öfver hela Rådhuset, och när alla andra;',
        14: 'Och att månge bröder i Herranom, styrkte af minom bojom, äro dess dristigare vordne till att tala ordet utan räddhåga.',
        15: 'Somlige predika ock Christum för afunds och trätos skull, och somlige uti en god mening.',
        16: 'De förre predika Christum af kif, och icke renliga; menandes dermed föröka bedröfvelsen till mitt fängelse;',
        17: 'Men de sednare af kärlek, vetandes att jag här ligger till Evangelii försvarelse.',
        18: 'Hvad äret då? Att ju Christus förkunnad varder, i hvad måtto det ske kan, antingen af tillfälle, eller sannskyldeliga; deraf fröjdar jag mig, och jemväl fröjda vill.',
        19: 'Ty jag vet, att det kommer mig till salighet, genom edra bön, och Jesu Christi Andas tillhjelp;',
        20: 'Såsom jag visserliga väntar och förhoppas, att jag uti ingen ting skall till blygd komma; utan med all frihet, såsom alltid, så ock nu, måtte Christus afhållen varda i minom lekamen, ehvad det är genom lif, eller genom död.',
        21: 'Ty Christus är mitt lif, och döden är min vinning.',
        22: 'Men efter det, att lefva i köttet, tjenar mer till att göra frukt, så vet jag icke hvilket jag utvälja skall;',
        23: 'Ty både delarne ligga mig hårdt uppå. Jag åstundar skiljas hädan, och vara när Christo; hvilket ock mycket bättre vore;',
        24: 'Men det är mer nödtorftigt blifva i köttet för edra skull.',
        25: 'Och vet jag visserliga, att jag skall blifva, och med eder allom vara, eder till godo, och till trones fröjd;',
        26: 'På det I mågen storliga berömma eder af mig i Christo Jesu, genom min igenkommelse till eder.',
        27: 'Allenast vandrer såsom Christi Evangelio värdt är; att hvad jag heldre kommer och får eder se, eller frånvarandes får höra om eder, att I blifven ståndande uti enom anda och ene själ, samt med oss kämpande uti Evangelii tro;',
        28: 'Och uti ingen ting förskräcken eder för edra motståndare, hvilket dem är ett tecken till förtappelse; men eder till salighet, och det af Gudi!',
        29: 'Ty eder är gifvet för Christo, icke allenast att I tron på honom, utan jemväl liden för hans skull;',
        30: 'Hafvande samma stridena, som I sågen i mig, och I nu hören om mig.',
    },
    2: {
        1: 'Är nu någor förmaning när eder i Christo; är någor tröst i kärlekenom; är någor Andans delaktighet; är någor hjertelig kärlek och barmhärtighet;',
        2: 'Så, uppfyller mina glädje, att I ären ens till sinnes, lika kärlek hafvande, endrägtige, samhällige;',
        3: 'Att intet sker med kif eller fåfäng äro; utan med ödmjukhet räkne hvar den andra yppare än sig.',
        4: 'Ser icke hvar på sitt eget bästa, utan hvar och en på ens annars bästa.',
        5: 'Hvar och en vare så till sinnes, som ock Christus Jesus var;',
        6: 'Hvilken, ändå han var i Guds skepelse, räknade han icke för rof Gudi jemlik vara;',
        7: 'Utan förnedrade sig sjelf, tagandes på sig en tjenares skepelse, och vardt lika som en annor menniska, och i åthäfvor funnen som en menniska;',
        8: 'Ödmjukade sig sjelf; vardt lydig intill döden, ja, intill korsens död.',
        9: 'Derföre hafver ock Gud förhöjt honom, och gifvit honom ett Namn, det öfver all namn är;',
        10: 'Att i Jesu Namn skola sig böja all knä, deras som i himmelen, på jordene, och under jordene äro;',
        11: 'Och alla tungor skola bekänna, att Jesus Christus är Herren, Gud Fader till äro;',
        12: 'Så, mine älskelige, som I alltid hafven varit lydige, icke allenast i mine närvaro, utan ock nu mycket mer i mine frånvaro, skaffer med fruktan och bäfvan, att I salige varden.',
        13: 'Ty Gud är den som verkar i eder både vilja och gerning, efter sitt goda behag.',
        14: 'Görer all ting utan knorr och tvekan;',
        15: 'På det I mågen vara oförtalade och rene, och Guds barn ostraffelige, midt ibland det vanartiga och vrånga slägtet; ibland hvilka lyser såsom ljus i verldene;',
        16: 'Att I blifven vid lifsens ord, mig till en berömmelse på Christi dag, att jag icke fåfängt lupit, eller fåfängt arbetat hafver.',
        17: 'Och om jag än offras öfver edra tros offer och Gudstjenst, så gläder jag mig, och fröjdar mig med eder alla.',
        18: 'För det sammas skull skolen I ock glädjas, och skolen glädjas med mig.',
        19: 'Men jag hoppas i Herranom Jesu, att jag innan kort varder sändandes till eder Timotheum; att jag ock må varda vid ett godt mod, då jag förnimmer huru med eder tillstår.',
        20: 'Ty jag hafver ingen, den som så alldeles lika med mig till sinnes är, den så hjerteliga omsorg hafver för eder.',
        21: 'Ty de söka alle efter sitt eget, icke det Christo Jesu tillhörer.',
        22: 'Men I veten, att han bepröfvad är; ty såsom ett barn med fadrenom, hafver han med mig tjent uti Evangelio.',
        23: 'Honom hoppas mig nu sända, det första jag hafver besett min ärende.',
        24: 'Jag tröstar ock på Herran, att jag ock sjelf snart kommandes varder.',
        25: 'Mig hafver ock synts nödtorftigt vara sända till eder Epaphroditum, brödren, min medhjelpare och medstridare, och edar Apostel, den ock mig uti mine nödtorft tjenar;',
        26: 'Efter han hade en åstundan till eder alla, och var storliga bekymrad deraf, att I sport haden honom krankan;',
        27: 'Som han ock visserliga var dödssjuk; men Gud förbarmade sig öfver honom; och icke allenast öfver honom, utan ock öfver mig, att jag icke skulle få sorg på sorg.',
        28: 'Jag hafver nu sändt honom dess snarare, att I skolen få se honom, och dess gladare varda igen, och jag dess mindre sorg hafva.',
        29: 'Så undfår nu honom i Herranom med alla glädje; och de sådane äro, dem hafver i vördning;',
        30: 'Ty för Christi verks skull var han dödenom så när kommen, att han fögo tänkte på lifvet; på det han skulle tjena mig i edar stad.',
    },
    3: {
        1: 'Ytterligare, mine bröder, fröjder eder i Herranom. Att jag eder ju allt detsamma skrifver, det förtryter mig intet; men det gör eder dess vissare.',
        2: 'Vakter eder för de hundar, vakter eder för de onda arbetare, vakter eder för afskärelsen.',
        3: 'Ty vi äre omskärelsen, vi som tjene Gudi i Andanom, och berömmom oss af Christo Jesu, och sättom icke tröst på köttet;',
        4: 'Ändock jag ock väl må trösta på köttet. Hvar en annar sig tycka låter, att han må förtrösta sig på köttet, jag mycket mer;',
        5: 'Som på åttonde dagen omskoren är, en af Israels folk och Benjamins slägte, en Ebree af Ebreer, efter lagen en Pharisee;',
        6: 'Efter nitet förföljandes församlingen, efter den rättfärdighet, som är af lagen, ostraffelig.',
        7: 'Men det mig en vinning var, det hafver jag räknat för skada, för Christi skull.',
        8: 'Ja, jag räknar det allt för skada emot den öfver svinnleliga mins Herras Christi Jesu kunskap; för hvilkens skull jag allt hafver för skada räknat, och håller det för träck, på det jag må vinna Christum;',
        9: 'Och varda funnen i honom, icke hafvandes mina rättfärdighet, som kommer af lagen, utan den som af Christi tro kommer; nämliga den rättfärdighet, som af Gudi kommer genom trona.',
        10: 'Till att känna honom, och hans uppståndelses kraft, och hans pinos delaktighet, lik vorden hans död;',
        11: 'Om jag ock måtte komma emot honom i de dödas uppståndelse.',
        12: 'Icke att jag allaredo hafver det fattat, eller allaredo fullkommen är; men jag far fast der efter, om jag det ock fatta må, som jag ock fattad är af Christo Jesu.',
        13: 'Käre bröder, jag kan icke säga, att jag ännu sjelf det fattat hafver; men ett säger jag: Jag förgäter det till rygga är, och sträcker mig till det som frammantill är;',
        14: 'Jagandes efter målet, som föresatt är, till den lön som förehålles ofvanefter, af Guds kallelse i Christo Jesu.',
        15: 'Så månge vi nu fullkomne äre, varom så sinnade; och om I något annorlunda hålla skolen, så låter Gud eder det uppenbara;',
        16: 'Dock så, att vi uti det, der vi allaredo tillkomne äre, vandrom efter ena reglo, och äre ens sinnade.',
        17: 'Varer ock, käre bröder, mine efterföljare, och ser på dem som så vandra, som I oss för en efterdömelse hafven.',
        18: 'Ty månge vandra, af hvilkom jag eder ofta sagt hafver, men nu säger jag ock gråtandes, fiendar till Christi kors;',
        19: 'Hvilkas ände är förtappelse, och deras buk deras Gud, och deras ära till skam, de der akta hvad jordena tillhörer.',
        20: 'Men vår umgängelse är i himmelen, dädan vi ock vänte Frälsaren, Herran Jesum Christum;',
        21: 'Hvilken vår skröpliga lekamen skall förklara; på det han skall göra honom lik med sinom förklarada lekamen, af den kraft der han med förmår sig all ting underlägga.',
    },
    4: {
        1: 'Så, mine käre och önskade bröder, min fröjd och min krona, blifver så ståndande i Herranom, mine älskelige.',
        2: 'Evodiam förmanar jag, och Syntychen förmanar jag, att de äro ens till sinnes i Herranom.',
        3: 'Ja, jag beder ock dig, min rättsinniga make, var dem behjelpelig, som med mig öfver Evangelium stridt hafva, samt med Clement, och andra mina medarbetare, hvilkas namn äro uti lifsens bok.',
        4: 'Fröjder eder i Herranom alltid; och åter säger jag: Fröjder eder.',
        5: 'Edor saktmodighet låter allom menniskom kunnoga varda. Herren är när.',
        6: 'Hafver ingen omsorg; utan edart begär vare kunnigt inför Gud, i all ting, med bön, åkallan, och tacksägelse.',
        7: 'Och Guds frid, som öfvergår allt förstånd, förvare edor hjerta, och edart sinne, i Christo Jesu.',
        8: 'Yttermera, käre bröder, hvad sant är, hvad ärligit är, hvad rätt, hvad kyskt, hvad ljufligit, hvad väl lyder; är någor dygd, och är något lof, tänker derefter.',
        9: 'Hvad I ock lärt, och undfått, och hört, och sett hafven på mig, det görer; och så varder fridsens Gud med eder.',
        10: 'Men jag är storliga fröjdad i Herranom, att I ären åter komne dertill, att I hafven omsorg om mig; ändock I väl allstädes omsorg haft hafven; men tiden sade icke så till.',
        11: 'Detta säger jag icke derföre, att mig något fattas; ty jag hafver lärt, ibland dem jag umgår, låta mig nöja.',
        12: 'Jag kan låg vara; jag kan ock hög vara; allestäds och i all ting är jag skickelig, både mätt och hungrig vara, både nog hafva och nöd lida.',
        13: 'All ting förmår jag, genom Christum, som mig mägtigan gör.',
        14: 'Dock hafven I rätt gjort, att I hafven tagit eder min bedröfvelse till.',
        15: 'Veten I ock väl, I Philipper, att af första Evangelii begynnelse, då jag drog utu Macedonien, ingen församling hafver något delat med mig, efter räkenskap, i utgift och uppbörd, utan I allena;',
        16: 'Ty I sänden ena reso, och så andra, till mig i Thessalonica, till min nödtorft.',
        17: 'Icke att jag söker sådana skänker; utan söker derefter, att uti edar räkenskap skall en öfverflödig frukt finnas.',
        18: 'Ty jag hafver allt, och öfverflödar, och är uppfylld, sedan jag undfick, med Epaphroditus, det som ifrån eder sändt var, en söt lukt, ett offer, Gudi täckt och anammeligit.',
        19: 'Men min Gud skall eder uppfylla alla edra nödtorft, efter sina rikedomar i härlighetene, genom Christum Jesum.',
        20: 'Men Gudi och vårom Fader vare pris af evighet till evighet. Amen.',
        21: 'Helser all helgon i Christo Jesu. Eder helsa de bröder, som med mig äro.',
        22: 'Eder helsa all helgon, enkannerliga de, som äro utaf Kejsarens hus.',
        23: 'Vårs Herras Jesu Christi nåd vare med eder allom. Amen. Skrifven af Rom, med Epaphrodito.',
    },
}
