NAME = 'SweKarlXII: Svenska Karl XII:s Bibel (1703)'
BOOK = 'Nehemiah'

CHAPTERS = {
    1: {
        1: 'Dessa äro Nehemia, Hachalja sons, ord. Det begaf sig uti dem månadenom Chislev, i tjugonde årena, att jag var i Susan på slottet.',
        2: 'Då kom Hanani, en af mina bröder, med några män utaf Juda; och jag frågade dem, huru det gick med Judarna, som behållne och igenlefde voro af fängelset; och huru det tillgick i Jerusalem.',
        3: 'Och de sade till mig: De igenlefde af fängelset äro der i landena uti stor vedermödo och försmädelse; murarna i Jerusalem äro nederbrutne, och dess portar uppbrände med eld.',
        4: 'Då jag nu sådana ord hörde, satt jag och gret, och jämrade mig i några dagar, och fastade, och bad inför Gud af himmelen;',
        5: 'Och sade: Ack! Herre Gud af himmelen, du store och förskräckelige Gud, som håller förbund och barmhertighet dem som dig älska och hålla din bud:',
        6: 'Låt dock din öron höra härtill, och din ögon öppne vara, så att du hörer dins tjenares bön, som jag nu beder inför dig, bide dag och natt, för dina tjenare Israels barn, och bekänner Israels barnas synd, som vi emot dig gjort hafve; och jag med mins faders hus hafvom också syndat.',
        7: 'Vi äre vordne förderfvade, att vi icke hafve hållit din bud, befallningar och rätter, som du dinom tjenare Mose budit hafver.',
        8: 'Men tänk dock uppå det ord, som du dinom tjenare Mose böd, och sade: Om I förtagen eder, så vill jag förströ eder ibland folk;',
        9: 'Men om I omvänden eder till mig, och hållen min bud, och gören dem; och om I än bortdrefne voren allt intill himmelens ända, så vill jag dock dädan församla eder, och skall låta eder komma till det rum, som jag utvalt hafver, till att mitt Namn der bo skall.',
        10: 'De äro dock dine tjenare, och ditt folk, som du förlossat hafver, igenom dina stora kraft och mägtiga hand.',
        11: 'Ack! Herre, låt din öron höra till din tjenares bön, och till dina tjenares bön, som begära frukta ditt Namn; och låt lyckosamliga tillgå i dag med dinom tjenare, och gif honom barmhertighet för denna mannenom. Ty jag var Konungens skänk.',
    },
    2: {
        1: 'Uti den månaden Nisan, i tjugonde årena Konungs Arthahsasta, då vin stod för honom, tog jag vinet upp, och fick Konungenom; och jag var icke lustig för honom.',
        2: 'Då sade Konungen till mig: Hvi ser du så illa ut? Du är ju icke krank? Det äret icke, utan du äst bedröfvad. Men jag fruktade mig svårliga.',
        3: 'Då sade jag till Konungen: Konungen lefve evinnerliga! Skulle jag icke se illa ut? Den staden, der mina faders begrafningshus är, ligger öde, och dess portar äro med eld uppbrände.',
        4: 'Då sade Konungen till mig: Hvad är då ditt begär? Då bad jag Gud af himmelen;',
        5: 'Och sade till Konungen: Om Konungenom så godt tyckte, och din tjenare funne nåd för dig, att du ville sända mig till Juda, till den staden, der mina fäder begrafne äro, att jag måtte uppbygga honom.',
        6: 'Och Konungen sade till mig, och Drottningen, som jemte honom satt: Huru lång kan din resa varda? Och när kan du komma igen? Och Konungenom föll i sinnet, att han skulle sända mig åstad. Och jag satte honom en bestämd tid före;',
        7: 'Och sade till Konungen: Om Konungenom så godt tycker, så gifve han mig bref till landshöfdingarna på hinsidon älfvena, att de ledsaga mig derigenom, tilldess jag kommer in i Juda;',
        8: 'Och bref till Assaph, Konungens skogshöfvitsman, att han låter mig få trä till bjelkar åt portarna i palatset i husena, och till stadsmurarna, och till huset, der jag infara skall. Och Konungen gaf mig det, efter mins Guds goda hand öfver mig.',
        9: 'Och då jag kom till landshöfdingarna på hinsidon älfvena, fick jag dem Konungens bref. Och Konungen sände med mig höfvitsmän och resenärar.',
        10: 'Då nu Saneballat den Horoniten, och Tobia tjenaren, den Ammoniten, det hörde, förtröt det dem svårliga, att någor menniska kommen var, som något godt sökte för Israels barn.',
        11: 'Och då jag kom till Jerusalem, och hade varit der i tre dagar,',
        12: 'Stod jag om nattena upp, och någre få män med mig; ty jag sade det ingen menniska, hvad mig min Gud ingifvit hade till att göra med Jerusalem; och intet djur var med mig, utan det jag red uppå.',
        13: 'Och jag red ut genom dalporten om nattena, och framom drakabrunnen, och åt dyngoportenom, och besåg Jerusalems murar, som sönder voro, och portarna, som med eld uppbrände voro;',
        14: 'Och gick öfver till brunnporten, och till Konungsdammen; och var intet rum, der djuret, som under mig var, uppå gå kunde.',
        15: 'Så drog jag om nattena bort åt bäcken, och besåg murarna, och vände om, och kom igenom dalporten hem igen.',
        16: 'Och öfverstarna visste icke hvart jag gick, eller hvad jag gjorde; förty jag hade ändå intet sagt Judarna, och Presterna, rådherrarna och öfverstarna, och dem androm, som uppå verket arbetade.',
        17: 'Så sade jag dem nu: I sen den uselhet, som vi uti äre, att Jerusalem ligger öde, och dess portar äro med eld uppbrände; kommer, låter oss bygga murarna till Jerusalem, att vi icke länger skola vara till en försmädelse.',
        18: 'Och jag lät dem förstå min Guds hand, den öfver mig god var; dertill Konungens ord, som han med mig talat hade. Och de sade: Så låt oss nu vara uppe. Och vi byggde, och deras händer voro tröste till godt.',
        19: 'Då nu Saneballat den Horoniten, och Tobia tjenaren, den Ammoniten, och Gesem den Araben, hörde det, begabbade de oss, och föraktade oss, och sade: Hvad är det I gören? Viljen I åter falla af ifrå Konungenom?',
        20: 'Då svarade jag dem, och sade: Gud af himmelen gifver oss lycko; ty vi hans tjenare hafve uppe varit, och byggom; men I hafven ingen del eller rätt, eller åminnelse i Jerusalem.',
    },
    3: {
        1: 'Och Eljasib, öfverste Presten, stod upp med sina bröder Presterna, och byggde fåraporten; honom helgade de, och satte in hans dörrar; men de helgade honom allt intill det tornet Mea, nämliga allt intill det tornet Hananeel.',
        2: 'Bredevid dem byggde de män af Jericho; och näst dem byggde Saccur, Imri son.',
        3: 'Men fiskaporten byggde Senaa barn; honom täckte de, och satte in hans dörrar, lås och bommar.',
        4: 'Näst dem byggde Meremoth, Uria son, Hakkoz sons; näst dem byggde Mesullam, Berechia son, Mesesabeels sons; näst dem byggde Zadok, Baana son.',
        5: 'Näst dem byggde de af Thekoa; men deras väldige böjde icke sin hals till sins herras tjenst.',
        6: 'Den gamla porten byggde Jojada, Paseahs son, och Mesullam, Besodeja son; honom täckte de, och satte in hans dörrar, och lås och bommar.',
        7: 'Näst dem byggde Melatia af Gibeon, och Jadon af Merono, män af Gibeon och Mizpa, på landshöfdingans säte, på denna sidon älfven.',
        8: 'Näst efter honom byggde Ussiel, Harhaja son, guldsmeden; näst honom byggde Hanania, apothekarens son, och de förstärkte Jerusalem allt intill de breda murar.',
        9: 'Näst honom byggde Rephaja, Hurs son, öfversten öfver en half fjerding af Jerusalem.',
        10: 'Näst honom byggde Jedaja, Harumaphs son, tvärtöfver sitt hus; näst honom byggde Hattus, Hasabenja son.',
        11: 'Men Malchija, Harims son, och Hasub, Pahath Moabs son, byggde ett annat stycke, och tornet med ugnarna.',
        12: 'Näst honom byggde Sallum, Halohes son, öfversten för en half fjerding i Jerusalem, han och hans döttrar.',
        13: 'Dalporten byggde Hanun och borgarena af Sanoah; de byggde honom, och satte in hans dörrar, och lås och bommar, och tusende alnar på murenom allt intill dyngoporten.',
        14: 'Men dyngoporten byggde Malchija, Rechabs son, öfversten i vingårdsmännernas fjerding; han byggde honom, och satte in hans dörrar, lås och bommar.',
        15: 'Brunnporten byggde Sallum, CholHose son, en öfverste för en fjerding i Mizpa; han byggde honom, och täckten, och satte in hans dörrar, lås och bommar; dertill ock murarna vid dammen Selah, vid Konungsörtagården, allt intill trapporna, som gå nederåt ifrå Davids stad.',
        16: 'Näst honom byggde Nehemia, Asbuks son, öfversten för den halfva fjerdingen i BethZur, allt intill gentemot Davids grafvar, och allt intill den dammen Asuja, och allt intill de väldigas hus.',
        17: 'Efter honom byggde de Leviter, Rehum, Bani son; bredevid honom byggde Hasabia, öfversten för halfva fjerdingen i Kegila, i hans fjerding.',
        18: 'Efter honom byggde deras broder Bavai, Henadads son, öfversten för en half fjerding i Kegila.',
        19: 'Efter honom byggde Eser, Jesua son, öfversten i Mizpa, ett annat stycke, inåt harneskhushörnet.',
        20: 'Efter honom, uppå berget, byggde Baruch, Sabbi son, ett annat stycke, ifrå hörnet allt intill Eljasibs öfversta Prestens husdörr.',
        21: 'Efter honom byggde Meremoth, Uria son, Hakkoz sons, ett annat stycke, ifrån Eljasibs husdörr, allt intill ändan af Eljasibs hus.',
        22: 'Efter honom byggde Presterna, de män af landsbygdene.',
        23: 'Efter dem byggde BenJamin och Hasub, tvärsöfver deras hus; efter dem byggde Asaria, Maaseja son, Anania sons, jemte sitt hus.',
        24: 'Efter honom byggde Binnui, Henadads son, ett annat stycke, ifrån Asaria hus intill båget, och allt intill hörnet;',
        25: 'Palal, Usai son, emot båget, och det höga tornet, som synes utaf Konungshuset, vid fångahusens gård; efter honom Pedaja, Paros son.',
        26: 'Men de Nethinim bodde uti Ophel, allt intill vattuporten österut, der tornet ut synes.',
        27: 'Efter dem byggde de af Thekoa ett annat stycke, tvärtemot det stora tornet, som ut synes, allt intill murarna Ophel.',
        28: 'Men ifrå hästaporten byggde Presterana, hvardera emot sitt hus.',
        29: 'Efter dem byggde Zadok, Immers son, emot sitt hus; efter honom byggde Semaja, Sechania son, den dörravaktaren, östantill.',
        30: 'Efter honom byggde Hanania, Selemia son, och Hanun, Zalaphs son, den sjette, ett annat stycke; efter honom byggde Mesullam, Berechia son, emot sin fatabur.',
        31: 'Efter honom byggde Malchija guldsmedssonen, allt intill de Nethinims och krämares hus, emot rådsporten, och intill hörnsalen.',
        32: 'Och emellan hörnsalen allt intill fåraporten byggde guldsmederna och krämarena.',
    },
    4: {
        1: 'Då nu Saneballat hörde, att vi byggde murarna, vardt han vred, och förgrymmade sig svårliga; och han bespottade Judarna;',
        2: 'Och sade för sina bröder, och för de väldiga i Samarien: Hvad göra de vanmägtige Judar? Månn man så skola låta betämma dem? Månn de skola offra? Månn de skola en dag fullkomna det? Månn de göra stenarna lefvande af stofthopar, som förbrände äro?',
        3: 'Men Tobia den Ammoniten, som när honom var, sade: Låt bygga dem; när räfvarna löpa ditupp, skola de väl sönderrifva deras stenmurar.',
        4: 'Hör, vår Gud, huru föraktade äre vi; vänd deras försmädelse in uppå deras hufvud, så att du gifver dem uti föraktelse i deras fängelses lande.',
        5: 'Öfverskyl icke deras missgerning, och bortskrapa icke deras synd för dig; förty de hafva rett byggningsmännerna.',
        6: 'Men vi byggde murarna, och fogde dem alla tillhopa intill halfva höjd; och folket fick hjerta till att arbeta.',
        7: 'Då nu Saneballat och Tobia, och de Araber och Ammoniter, och Asdoditer hörde, att murarna i Jerusalem voro igenbyggde, och de hade begynt igentäppa det öppet var, vordo de ganska vrede;',
        8: 'Och gjorde alla ett förbund tillhopa, att de skulle komma och strida emot Jerusalem, och göra en villo derinne.',
        9: 'Men vi bådom vår Gud, och satte vakt uppå dem dag och natt, emot dem.',
        10: 'Och Juda sade: Dragarenas magt är allt för svag, och gruset är för mycket; vi kunne icke bygga uppå murenom.',
        11: 'Men våre fiender tänkte: De skola icke få vetat, eller set, förr än vi komme midt i hopen uppå dem, och slå dem ihjäl, och förhindre arbetet.',
        12: 'Då nu Judarna, som när dem bodde, kommo, och sade oss det väl tio gånger, af all rum, der de omkring oss bodde;',
        13: 'Då satte jag nedre utmed muren i grafvene folket, efter deras slägter, med deras svärd, spetsar och bågar.',
        14: 'Och besåg det, och stod upp, och sade till rådherrarna, och öfverstarna, och till det andra folket: Frukter eder intet för dem; tänker uppå den stora förskräckeliga Herran, och strider för edra bröder, söner, döttrar, hustrur och hus,',
        15: 'Då nu våre fiender hörde, att vi hade fått vetat, gjorde Gud deras råd omintet; och vi vände oss åter alle till muren, hvar och en till sitt arbete.',
        16: 'Och det skedde sedan, att hälften af de unga män gjorde arbetet; den andre hälften höllo spetsar, sköldar, bågar, och pansar; och öfverstarne stodo bakför hela Juda hus.',
        17: 'De som byggde på muren, och de som båro bördor ifrå dem som uppå ladde; med den ena handene gjorde de arbetet, och med den andra höllo de värjona.',
        18: 'Och hvar och en af dem, som byggde, hade sitt svärd bundet vid sidona, och byggde så; och den som blåste med basunen, var när mig.',
        19: 'Och jag sade till rådherrarna, och öfverstarna, och till det andra folket: Arbetet är stort och vidt, och vi äre förströdde på murenom, långt ifrå hvarannan.',
        20: 'På hvilket rum I nu hören blåsa i basunen, dit kommer till oss. Vår Gud varder för oss stridandes;',
        21: 'Och vi vilje arbeta på verket; och hälften af dem höll spetsar, allt ifrå morgonrodnan intill stjernorna uppgingo.',
        22: 'Ock sade jag på den tiden till folket: Hvar och en blifve med sinom dräng öfver natten i Jerusalem, att vi om nattena tage vara på vaktena, och om dagen på arbetet.',
        23: 'Men jag och mine bröder, och mine tjenare, och de män i vaktene efter mig, drogo intet vår kläder af, när någor i vattnet gick.',
    },
    5: {
        1: 'Och sig upphof ett stort rop af folket, och deras hustrur, emot sina bröder Judarna.',
        2: 'Och voro somlige, som sade: Våre söner och döttrar äro allt för månge; låt oss taga säd, och äta, att vi måge lefva.',
        3: 'Och somlige sade: Låt oss utsätta våra åkrar, vingårdar och hus, och taga säd i denna hårda tiden.',
        4: 'Somlige sade: Låt oss låna penningar på ränto till Konungen, på våra åkrar och vingårdar.',
        5: 'Ty våra bröders kropp är såsom vår kropp, och deras barn såsom vår barn; eljest gifve vi våra söner och döttrar i träldom, och äre allaredo våra döttrar somliga undergifna, och ingen magt är i våra händer; komma också våra åkrar och vingårdar androm tillhanda.',
        6: 'Då jag nu deras rop och dessa orden hörde, vardt jag ganska vred.',
        7: 'Och mitt hjerta fick till råds, att jag straffade rådherrarna och öfverstarna, och sade till dem: Viljen I drifva ocker, den ene på den andra? Och jag hade tillhopa emot dem en stor församling;',
        8: 'Och sade till dem: Vi hafve igenköpt våra bröder Judarna, som Hedningomen sålde voro, efter våra förmågo; och I viljen också sälja edra bröder, de vi till oss köpt hafve? Då tego de, och funno intet till att svara.',
        9: 'Och jag sade: Det är icke godt, som I gören. Skullen I icke vandra i Gudsfruktan, för Hedningarnas försmädelses skull, våra fiendars?',
        10: 'Jag och mine bröder, och mine tjenare, hafvom ock fått dem penningar och säd; men ockret vilje vi låta blifva tillbaka.',
        11: 'Så får dem nu i denna dag igen sina åkrar, vingårdar, oljogårdar och hus, och hundradedelen af penningomen för säd, vin och oljo, som I på dem ockrat hafven.',
        12: 'Då sade de: Vi vilje få dem det igen, och vilje intet äska af dem; och vilje göra såsom du sagt hafver. Och jag kallade Presterna, och tog en ed af dem, att de så göra skulle.',
        13: 'Och jag skuddade mitt sköte ut, och sade: Så skudde Gud hvar och en af sitt hus, och ifrå hans arbete, den icke blifver vid detta ord, så att han blifve utskuddad och blottad. Och hela församlingen sade Amen; och lofvade Herran. Och folket gjorde så.',
        14: 'Desslikes, ifrå den tiden, då mig vardt befaldt att vara landshöfding i Juda land, nämliga ifrå tjugonde årena, allt intill annat och tretionde året Konungs Arthahsasta, det är i tolf år, höll jag mig och mina bröder intet af höfdingakoste.',
        15: 'Förty de förre landshöfdingar, som för mig varit hade, hade besvärat folket, och hade tagit af dem bröd och vin, och dertill fyratio siklar silfver, och deras tjenare hade haft sig väldeliga med folket; men jag gjorde icke så, för Gudsfruktans skull.',
        16: 'Arbetade jag ock på murarbetet, och köpte ingen åker; och alle mine tjenare måste der komma samman till arbetes.',
        17: 'Dertill voro ock af Judarna och Förstarna hundrade och femtio vid mitt bord, som till mig komne voro ifrå Hedningarna, som kringom oss äro.',
        18: 'Och man måste beställa mig om dagen en oxa, och sex utvald får, och foglar, och ju i tio dagar allahanda vin tillfyllest. Likväl äskade jag intet höfdingakosten; förty tungen var svår på folkena.',
        19: 'Min Gud, betänk mig till godo allt det jag desso folkena gjorde.',
    },
    6: {
        1: 'Då Saneballat, Tobia och Gesem den Araben, och andre våre fiender förnummo, att jag murarna byggt hade, och intet gap var mer deruppå; ändock jag ändå på den tiden icke upphängt hade dörrarna i portomen,',
        2: 'Sände Saneballat och Gesem till mig, och läto säga mig: Kom, och låt oss komma tillsammans på bygdene, på slättene vid den staden Ono. Och de aktade göra mig ondt.',
        3: 'Men jag sände båd till dem, och lät säga dem; Jag hafver ett stort verk till att uträtta, jag kan icke komma neder; det måtte försummadt blifva, om jag tager handena af, och far neder till eder.',
        4: 'De sände väl fyra gånger till mig vid samma sinnet; och jag svarade dem allt vid samma sätt.',
        5: 'Då sände Saneballat femte gången sin tjenare till mig, med ett öppet bref i hans hand.',
        6: 'Derutinnan var skrifvet: Det är kommet för Hedningarna, och Gesem hafver det sagt, att du och Judarna viljen affalla; derföre uppbygger du murarna, och du vill vara deras Konung i denna sakene.',
        7: 'Och du hafver beställt dig Propheter, som om dig skola utropa i Jerusalem, och säga: Han är Juda Konung. Sådant kommer för Konungen. Så kom nu, låt oss rådslå med hvarannan.',
        8: 'Men jag sände till honom, och lät säga honom: Detta är icke skedt, som du säger, du hafver diktat det af ditt hjerta.',
        9: 'Ty de ville alle rädda oss, och mente: De varda aflåtande af arbetet, och varda stille. Men jag förstärkte mina hand desto mer.',
        10: 'Och jag kom uti Semaja hus, Delaja sons, Mehetabeels sons, och han hade innelyckt sig; och sade: Låt oss komma tillhopa i Guds hus, midt i templet, och sluta dörrarna till af templet; förty de varda kommande till att dräpa dig, och komma om nattena, att de skola slå dig ihjäl.',
        11: 'Men jag sade: Skulle en sådana man fly? Skulle en sådana man, som jag är, gå uti templet, på det han skall blifva lefvandes? Jag vill icke gå derin.',
        12: 'Ty jag förmärkte, att Gud hade intet sändt honom. Han spådde väl sådant om mig; men Tobia och Saneballat hade gifvit honom penningar.',
        13: 'Derföre tog han penningar, på det jag skulle taga en fruktan till mig, och göra så, och synda; och de skulle hafva ett ondt rop uppå mig, dermed de måtte förlasta mig.',
        14: 'Tänk, min Gud, på Tobia och Saneballat, efter dessa deras gerningar, och på Propheten Noadja, och de andra Propheterna, som mig afskräcka ville.',
        15: 'Och muren vardt redo på femte och tjugonde dagen af den månaden Elul, i två och femtio dagar.',
        16: 'Och då alle våre fiender det hörde, fruktade sig alle Hedningar, som omkring oss voro, och deras mod förföll dem; förty de märkte, att detta verk var af Gudi.',
        17: 'Voro ock på den tiden månge af Juda öfverstar, hvilkas bref gingo till Tobia; och ifrå Tobia till dem.',
        18: 'Ty de voro månge i Juda, som honom besvorne voro; förty han var Sechania svåger, Arahs sons; och hans son Johanan hade Mesullams dotter, Berechia sons.',
        19: 'Och de talade godt om honom för mig, och förde mitt tal ut för honom. Så sände nu Tobia bref till att afskräcka mig.',
    },
    7: {
        1: 'Då vi nu hade byggt murarna, hängde jag portarna före, och vordo beställde porthållare, sångare och Leviter.',
        2: 'Och jag böd min broder Hanani, och Hanania palatsfogdanom i Jerusalem; ty han var en trofast man, och gudfruktig för många andra;',
        3: 'Och sade till dem: Man skall icke upplåta portarna i Jerusalem, tilldess solen varder varm; och medan man ännu arbetar, skall man slå portarna till, och bommen före. Och väktare vordo beställde utaf borgarena i Jerusalem, hvar och en på sine vakt, och om sitt hus.',
        4: 'Och staden var vid till rum, och stor; men folket litet derinne, och husen voro icke uppbyggd.',
        5: 'Och min Gud gaf mig i hjertat, att jag församlade rådherrarna och öfverstarna, och folket, till att räkna dem; och jag fann ett register på mantalet, deras som tillförene uppkomne voro, och fann deruti så skrifvet:',
        6: 'Desse äro landsens barn, som uppkomne voro utaf fängelset, af dem som NebucadNezar, Konungen i Babel, hade bortfört, och i Jerusalem bodde, och i Juda, hvar och en i sin stad;',
        7: 'Och voro komne med Serubbabel: Jesua, Nehemia, Asaria, Raamja, Nahamani, Mordechai, Bilsan, Misperet, Bigvai, Nehum och Baana. Detta är talet af männerna af Israels folk:',
        8: 'Paros barn voro tutusend hundrade två och sjutio.',
        9: 'Sephatja barn, trehundrad två och sjutio.',
        10: 'Arahs barn, sexhundrad två och femtio.',
        11: 'PahathMoabs barn, ibland Jesua och Joabs barn, tutusend åttahundrad och aderton.',
        12: 'Elams barn, tusende tuhundrad fyra och femtio.',
        13: 'Sattu barn, åttahundrad fem och fyratio.',
        14: 'Saccai barn, sjuhundrad och sextio.',
        15: 'Binnui barn, sexhundrad åtta och fyratio.',
        16: 'Bebai barn, sexhundrad åtta och tjugu.',
        17: 'Asgads barn, tutusend trehundrad två och tjugu.',
        18: 'Adonikams barn, sexhundrad sju och sextio.',
        19: 'Bigvai barn, tutusend sju och sextio.',
        20: 'Adins barn, sexhundrad fem och femtio.',
        21: 'Aters barn af Hiskia, åtta och niotio.',
        22: 'Hasums barn, trehundrad åtta och tjugu.',
        23: 'Bezai barn, trehundrad fyra och tjugu.',
        24: 'Hariphs barn, hundrade och tolf.',
        25: 'Gibeons barn, fem och niotio.',
        26: 'De män af BethLehem och Nethopha, hundrade åtta och åttatio.',
        27: 'De män af Anathot, hundrade åtta och tjugu.',
        28: 'De män af BethAsmaveth, två och fyra tio.',
        29: 'De män af KiriathJearim, Chephira och Beeroth, sjuhundrad tre och fyratio.',
        30: 'De män af Rama och Gaba, sexhundrad en och tjugu.',
        31: 'De män af Michmas, hundrade två och tjugu.',
        32: 'De män af BethEl och Aj, hundrade tre och tjugu.',
        33: 'De män af Nebo dess andras, två och femtio.',
        34: 'Dens andras Elams barn, tusende tuhundrad fyra och femtio.',
        35: 'Harims barn, trehundrad och tjugu.',
        36: 'Jerecho barn, trehundrad fem och fyratio.',
        37: 'Lod, Hadid, och Ono barn, sjuhundrad en och tjugu.',
        38: 'Senaa barn, tretusend niohundrad och tretio.',
        39: 'Presterna: Jedaja barn, af Jesua hus, niohundrad tre och sjutio.',
        40: 'Immers barn, tusende två och femtio.',
        41: 'Pashurs barn, tusende tuhundrad sju och fyratio.',
        42: 'Harims barn, tusende och sjutton.',
        43: 'Leviterna: Jesua barn, af Kadmiel, ibland Hodeva barn, fyra och sjutio.',
        44: 'Sångarena: Assaphs barn, hundrade åtta och fyratio.',
        45: 'Dörravaktarena: Sallums barn, Aters barn, Talmons barn, Akkubs barn, Hatita barn, Sobai barn; alle tillhopa hundrade åtta och tretio.',
        46: 'De Nethinim: Ziha barn, Hasupha barn, Tabaoths barn,',
        47: 'Keros barn, Sia barn, Padons barn,',
        48: 'Lebana barn, Hagaba barn, Salmai barn,',
        49: 'Hanans barn, Giddels barn, Gahars barn,',
        50: 'Reaja barn, Rezins barn, Nekoda barn,',
        51: 'Gassams barn, Ussa barn, Paseahs barn,',
        52: 'Besai barn, Meunims barn, Nephisesims barn,',
        53: 'Bakbuks barn, Hakupha barn, Harhurs barn,',
        54: 'Bazliths barn, Mehida barn, Harsa barn,',
        55: 'Barkos barn, Sisera barn, Thamahs barn,',
        56: 'Neziahs barn, Hathipha barn.',
        57: 'Salomos tjenares barn: Sotai barn, Sophereths barn, Perida barn,',
        58: 'Jaala barn, Darkons barn, Giddels barn,',
        59: 'Sephatja barn, Hattils barn, Pocherets barn af Zebaim, Amons barn.',
        60: 'Alle de Nethinim, och Salomos tjenares barn, voro trehundrad två och niotio.',
        61: 'Desse drogo också med upp, af ThelMelah, ThelHarsa, Cherub, Addon och Immer; men de kunde icke bevisa deras fäders hus, eller deras säd, om de voro af Israel.',
        62: 'Delaja barn, Tobia barn, Nekoda barn, voro sexhundrad två och fyratio.',
        63: 'Och af Presterna: Habaja barn, Hakkoz barn, Barsillai barn, hvilken hustru tog af Barsillai den Gileaditens döttrar, och vardt efter deras namn nämnd.',
        64: 'Desse sökte deras börds register; och då de icke funno det, vordo de qvitte vid Presterskapet.',
        65: 'Och Thirsatha sade till dem, att de icke skulle äta utaf det aldrahelgaste, intilldess en Prest uppkomme med Ljus och Fullkomlighet.',
        66: 'Hela menigheten, såsom en man, var tu och fyratio tusend trehundrad och sextio;',
        67: 'Undantagne deras tjenare och tjenarinnor, de voro sjutusend trehundrad sju och tretio; och de hade tuhundrad fem och fyratio sångare och sångerskor;',
        68: 'Sjuhundrad sex och tretio hästar; tuhundrad fem och fyratio mular;',
        69: 'Fyrahundrad fem och tretio camelar; sextusend sjuhundrad och tjugu åsnar.',
        70: 'Och somlige af öfversta fäderna gåfvo till verket: Thirsatha gaf till drätselen tusende gylden, och femtio bäcken, femhundrad och tretio Prestakjortlar.',
        71: 'Och somlige af de öfversta fäder gåfvo i drätselen till verket tjugutusend gylden, tutusend och tuhundrad pund silfver.',
        72: 'Och det andra folket gaf tjugutusend gylden, och tutusend pund silfver, och sju och sextio Prestakjortlar.',
        73: 'Och Presterna, och Leviterna, och dörravaktarena, sångare, och somlige af folket, och de Nethinim, och hele Israel, satte sig uti sina städer.',
    },
    8: {
        1: 'Då nu sjunde månaden kom, och Israels barn voro i sina städer, församlade sig allt folket, såsom en man, på breda gatone inför vattuporten, och sade till Esra den skriftlärda, att han skulle hemta fram Mose lagbok, som Herren Israel budit hade.',
        2: 'Och Esra Presten hemtade fram lagen inför menighetena, både män och qvinnor, och för alla dem som det förstå kunde, på första dagen i sjunde månadenom;',
        3: 'Och las deruti, på breda gatone, som för vattuporten är, allt ifrå morgonlysningen intill middag, för män och qvinnor, och för dem som det förstå kunde; och hela folkens öron voro vänd till lagbokena.',
        4: 'Och Esra den Skriftlärde stod uppå en hög trästol, den de till predikan gjort hade; och när honom stodo Mattithia, Serna, Anaja, Uria, Hilkia och Maaseja, på hans högra sido; och på hans venstra Pedaja, Misael, Malchija, Hasum, Hasbadana, Zacharia och Mesullam.',
        5: 'Och Esra lät upp bokena för hela folket; förty han stod högt öfver allt folket; och då han upplät henne, stod allt folket.',
        6: 'Och Esra lofvade Herran den stora Guden; och allt folket svarade: Amen, Amen, med uppräckta händer; och bugade sig, och tillbådo Herran med ansigtet ned på jordena.',
        7: 'Och Jesua, Bani, Serebia, Jamin, Akkub, Sabbethai, Hodija, Maaseja. Kelita, Asaria, Josabad, Hanan, Pelaja, och Leviterna, beställde att folket gaf akt uppå lagen; och folket stod uppå sitt rum.',
        8: 'Och de läste uti Guds lagbok klarliga och förståndeliga, så att man förstod, då läset vardt.',
        9: 'Och Nehemia, hvilken är Thirsatha, och Esra Presten, den Skriftlärde, och Leviterna, som folket höllo till att akta på, sade till allt folket: Denne dagen är helig Herranom edrom Gud; derföre sörjer intet, och gråter icke; ty allt folket gret, då de hörde lagsens ord.',
        10: 'Derföre sade han till dem: Går bort, och äter det feta, och dricker det söta, och sänder dem ock delar, som intet för sig tillredt hafva; förty denne dagen är helig vårom Herra. Derföre bekymrer eder icke; ty fröjd i Herranom är edor starkhet.',
        11: 'Och Leviterna stillade allt folket, och Sade: Varer tyste, ty dagen är helig; bekymrens intet.',
        12: 'Och allt folket gick bort till att äta, dricka och del sända, och gjorde sig en stor glädje; förty de hade förståndit orden, som man dem förkunnat hade.',
        13: 'På annan dagen församlade sig öfversta fäderna ibland allt folket, och Presterna, och Leviterna, till Esra den Skriftlärda, att han skulle undervisa dem i lagsens ordom.',
        14: 'Och de funno beskrifvet i lagen, att Herren genom Mose budit hade, att Israels barn skulle bo i löfhyddor, på den högtidene i sjunde månadenom.',
        15: 'Och de läto det varda kunnigt, och utropadt i alla deras städer, och i Jerusalem, och sade: Går ut uppå berget, och hemter oljoqvistar, balsamqvistar, myrthenqvistar, palmqvistar och qvistar af tjockqvistadt trä, att man må göra löfhyddor, såsom skrifvet står.',
        16: 'Och folket gick ut, och hemtade, och gjorde sig löfhyddor, hvar uppå sitt tak, och i sina gårdar, och i Guds hus gårdar; och uppå den breda gatone vid vattuporten, och uppå den breda gatone vid Ephraims port.',
        17: 'Och hela menigheten af dem, som af fängelset igenkomne voro, gjorde löfhyddor, och bodde deruti; ty Israels barn hade ifrå Josua, Nuns sons, tid, allt intill denna dag, intet så gjort; och var en ganska stor glädje.',
        18: 'Och vardt hvar dag läset i Guds lagbok, ifrå första dagen allt intill den yttersta; och de höllo den högtiden i sju dagar; och på åttonde dagen församlingenes dag, såsom det borde sig.',
    },
    9: {
        1: 'På fjerde och tjugonde dagen i denna månadenom kommo Israels barn tillsammans med fasto, och säcker, och mull uppå dem;',
        2: 'Och afskiljde Israels säd ifrån all främmande barn, och gingo fram, och bekände sina synder och sina fäders missgerning;',
        3: 'Och stodo upp i sin rum; och man las i Herrans deras Guds lagbok, fyra gånger om dagen; och de bekände och tillbådo Herran sin Gud, fyra gånger om dagen.',
        4: 'Och Leviterna stodo upp i höjdene; nämliga Jesua, Bani, Kadmiel, Sebanja, Bunni, Serebia, Bani och Chenani, och ropade högt till Herran deras Gud.',
        5: 'Och Leviterna, Jesua, Kadmiel, Bani, Hasabnia, Serebia, Hodija, Sebanja, Pethahja, sade: Står upp, och lofver Herran edar Gud ifrån evighet till evighet; och man lofve dins härlighets Namn, hvilken upphöjd är med all välsignelse och lof.',
        6: 'Herre, du äret allena; du hafver gjort himmelen och alla himlars himlar, med all deras här, jordena och allt det deruppå är, hafvet och allt det derinne är: du gör allt lefvande, och den himmelske hären tillbeder dig.',
        7: 'Du äst Herren Gud, som Abram utvalde, och förde honom ut ifrån Ur i Chaldeen, och nämnde honom Abraham.',
        8: 'Och du fann hans hjerta trofast för dig, och gjorde ett förbund med honom, till att gifva hans säd de Cananeers, Hetheers, Amoreers, Phereseers, Jebuseers och Girgaseers land; och du hafver hållit din ord; ty du äst rättfärdig.',
        9: 'Och du hafver sett till våra fäders jämmer i Egypten, och hört deras rop vid röda hafvet;',
        10: 'Och gjort tecken och under på Pharao, och alla hans tjenare, och på allt folket i hans land; ty du förnam, att de voro stolte emot dem; och hafver gjort dig ett Namn, såsom det i denna dag för ögon är;',
        11: 'Och hafver åtskiljt hafvet för dem, så att de gingo torre midt igenom hafvet; och kastat deras förföljare i djupet, såsom stenar i mägtig vatten;',
        12: 'Och fört dem om dagen uti en molnstod, och om nattena uti en eldstod, till att lysa dem på vägen, den de drogo;',
        13: 'Och hafver nederstigit uppå berget Sinai, och talat med dem af himmelen, och gifvit dem rättvisa rätter, och trofast lag, god bud och seder;',
        14: 'Och kungjort dem din helga Sabbath; och budit dem bud, seder och lag, genom din tjenare Mose;',
        15: 'Och gifvit dem bröd af himmelen, då de hungrade, och låtit gå vatten utaf bergklippone, då dem törste; och sagt dem, att de skulle gå in, och taga in landet, der du dina hand öfver upplyft hade, att du skulle det gifva dem.',
        16: 'Men våre fäder vordo stolte och halsstyfve, så att de icke lydde din bud;',
        17: 'Och ville icke höra dem, och tänkte intet uppå din under, som du med dem gjort hade; utan vordo halsstyfve, och uppkastade en höfvitsman, att de skulle vända sig till sin träldom i sine olydno; men du, (min) Gud, gaf dem till, och var dem nådelig, barmhertig, tålig, och af en stor barmhertighet, och öfvergaf dem icke.',
        18: 'Och ändock de gjorde en gjuten kalf, och sade: Det är din Gud, som dig utur Egypti land fört hafver; och gjorde stor försmädelse;',
        19: 'Likväl öfvergaf du dem icke i öknene, efter din stora barmhertighet; och molnstoden vek icke ifrå dem om dagen, att ledsaga dem på vägen; ej heller eldstoden om nattena, till att lysa dem på vägen, den de drogo.',
        20: 'Och du gafst din goda Anda, till att undervisa dem; och ditt Man vände du icke ifrå deras mun, och gaf dem vatten, när dem törste.',
        21: 'I fyratio år besörjde du dem i öknene, så att dem intet fattades; deras kläder föråldrades intet, och deras fötter svullnade intet:',
        22: 'Och gaf dem rike och folk, och fördelade dem här och der, så att de intogo Sihons land, Konungens i Hesbon, och Ogs land, Konungens i Basan.',
        23: 'Ock förökade du deras barn, såsom stjernorna på himmelen, och lät komma dem i landet, det du deras fader tillsagt hade, att de skulle draga derin, och intaga det.',
        24: 'Och barnen kommo derin, och togo landet in; och du undertryckte för dem landsens inbyggare, de Cananeer, och gafst dem uti deras händer, och deras Konungar, och folken i landena, så att de gjorde med dem efter sin vilja.',
        25: 'Och de vunno fasta städer, och ett fett land, och intogo hus full med allahanda ägodelar, uthuggna brunnar, vingårdar, oljogårdar och trä, der man af äter, väl mång. Och de åto och vordo mätte och fete, och lefde i vällust af dine stora godhet.',
        26: 'Men de vordo olydige, och vordo dig genstörtige, och kastade din lag tillrygga bakom sig, och slogo ihjäl dina Propheter, som dem betygade att de skulle omvända sig till dig; och gjorde stor försmädelse.',
        27: 'Derföre gafst du dem uti deras fiendars hand, hvilke dem betvingade; och uti deras ångests tid ropade de till dig; och du hörde dem af himmelen, och genom dina stora barmhertighet gafst du dem frälsare, som dem hulpo utu deras fiendars hand.',
        28: 'När de nu till rolighet kommo, vände de om igen, till att göra det ondt var för dig; så öfvergaf du dem uti deras fiendars hand, att de skulle råda öfver dem. Så omvände de sig då, och ropade till dig; och du hörde dem af himmelen, och halp dem efter dina stora barmhertighet i flera resor.',
        29: 'Och du lät betyga dem, att de skulle omvända sig till din lag; men de voro stolte, och lydde intet din bud, och syndade emot dina rätter; hvilka om en menniska gör, lefver hon derutinnan; och vände sina skuldror bort, och vordo halsstyfve, och lydde intet.',
        30: 'Och du fördröjde i mång år med dem, och lät betyga dem genom din Anda i dina Propheter: men de skötte der intet om, derföre hafver du gifvit dem i folks hand i landena.',
        31: 'Dock, af dine stora barmhertighet, hafver du icke platt gjort ända på dem, eller öfvergifvit dem; förty du äst en nådelig och barmhertig Gud.',
        32: 'Nu, vår Gud, du store Gud, mägtige och förskräckelige, du som håller förbund och barmhertighet; akta icke ringa all den vedermöda, som på oss drabbat hafver, och på våra Konungar, Förstar, Prester, Propheter, fäder, och allt ditt folk, ifrå Konungarnas tid i Assur, allt intill denna dag.',
        33: 'Du äst rättvis i allt det du hafver låtit komma öfver oss; ty du hafver gjort rätt, men vi hafve varit ogudaktige;',
        34: 'Och våre Konungar, Förstar, Prester och fäder, hafva icke gjort efter din lag, och intet aktat på din bud och vittnesbörd, som du hafver låtit betyga dem.',
        35: 'Och de hafva icke tjent dig i sitt rike, och i dina stora ägodelar, som du dem gifvit hafver, och uti det vida och feta landet, som du dem infått hafver, och hafva icke omvändt sig ifrå sitt onda väsende.',
        36: 'Si, vi äre i denna dag trälar, och i de lande, som du våra fäder gafst, till att äta dess frukt och goda, si, der äre vi trälar uti.',
        37: 'Och dess årsväxt förökar sig Konungomen, som du öfver oss satt hafver för våra synders skull; och de råda öfver våra kroppar och vår boskap, efter sin vilja; och vi äre i stor nöd.',
        38: 'Och i allt detta göre vi nu ett fast förbund, och skrifvom, och låte våra Förstar, Leviter och Prester besegla det.',
    },
    10: {
        1: 'Men de som beseglade det, voro desse: Nehemia Thirsatha, Hachalia son, och Zedekia,',
        2: 'Seraja, Asaria, Jeremia,',
        3: 'Pashur, Amaria, Malchija,',
        4: 'Hattus, Sebanja, Malluch,',
        5: 'Harim, Meremoth, Obadja,',
        6: 'Daniel, Ginnethon, Baruch,',
        7: 'Mesullam, Abia, Mijamin,',
        8: 'Maasia, Bilgai, och Semaja: De voro Presterna.',
        9: 'Men Leviterna voro: Jesua, Asanja son, Binnui af Henadads barnom, Kadmiel;',
        10: 'Och deras bröder, Sebanja, Hodija, Kelita, Pelaja, Hanan,',
        11: 'Micha, Rehop, Hasabia,',
        12: 'Saccur, Serebia, Sebanja,',
        13: 'Hodija, Bani och Benihu.',
        14: 'Hufvuden i folken voro: Paros, PahathMoab, Elam, Sattu, Bani,',
        15: 'Bunni, Asgad, Bebai,',
        16: 'Adonia, Bigvai, Adin,',
        17: 'Ater, Hiskia, Assur,',
        18: 'Hodija, Hasum, Bezai,',
        19: 'Hariph, Anathoth, Nebai,',
        20: 'Magpias, Mesullam, Hesir,',
        21: 'Mesesabeel, Zadok, Jaddua,',
        22: 'Pelatja, Hanan, Anaja,',
        23: 'Hosea, Hanania, Hasub,',
        24: 'Hallohes, Pilha, Sobek,',
        25: 'Rehum, Hasabna, Maaseja,',
        26: 'Ahija, Hanan, Anan,',
        27: 'Malluch, Harim och Baana.',
        28: 'Och det andra folket, Presterna, Leviterna, dörravaktarena, sångarena, Nethinim, och alle de som hade söndrat sig ifrå folken i landen, intill Guds lag, med sina hustrur, söner och döttrar, alle de som det kunde förstå;',
        29: 'Och deras mägtige, togo sig det till för sina bröder, och de kommo till att svärja och förpligta sig med ed, till att vandra i Guds lag, som igenom Guds tjenare Mose gifven är, att de hålla och göra ville efter all Herrans vår Guds bud, rätter och seder;',
        30: 'Och att vi icke skulle gifva folken i landena våra döttrar; ej heller vårom sönom taga deras döttrar.',
        31: 'Desslikes, när folket i landet förer om Sabbathsdagen någon varo och allahanda spisning, till att sälja, att vi icke ville taga det af dem om Sabbathen och helgedagar; och att vi i sjunde årena ville göra förlösning på allahanda tunga;',
        32: 'Och lägga ett bud uppå oss, att vi årliga gifva skulle en tridiung af en sikel silfver, till tjensten i vår Guds hus;',
        33: 'Nämliga till skådobröd, till dagligit spisoffer, till dagligit bränneoffer, på Sabbaths, nymånads och högtidsdagom, och till det helgada, och till syndoffer, der Israel skulle med försonad varda, och till all verk i vår Guds hus.',
        34: 'Och vi kastade lott emellan Presterna, Leviterna och folket, om vedoffer, det man till vår Guds hus årliga framföra skulle, efter våra fäders hus, på bestämd tid, att bränna på Herrans vår Guds altare, såsom det i lagen skrifvet är;',
        35: 'Och till att årliga frambära förstlingen af vårt land, och förstlingen af allo frukt, af all trä till Herrans hus;',
        36: 'Och förstlingen af vara söner, och af vår boskap, såsom det i lagen skrifvet står; och förstlingen af vårt fä, och af vår får, att vi allt detta skulle hafva in uti vår Guds hus till Presterna, som i vår Guds hus tjena;',
        37: 'Och att vi ville frambära förstlingen af vår deg, och vårt häfoffer, och frukt af allahanda trä, vin och oljo, till Presterna, i kistorna vid vår Guds hus; och vårt lands tiond till Leviterna, så att Leviterna skulle hafva tionden i alla städer, der vårt åkerverk är.',
        38: 'Och Presten Aarons son skall ock del hafva af Leviternas tiond, med Leviterna; så att Leviterna skola bära tionden af sine tiond upp till vår Guds hus, i kistorna, uti skatthuset.',
        39: 'Ty Israels barn, och Levi barn, skola bära häfoffret af säd, vin och oljo, upp i kistorna. Dersammastäds äro helgedomens kärile, och Presterna, som der tjena, och dörravaktare, och sångare; att vi vår Guds hus icke öfvergifve.',
    },
    11: {
        1: 'Och öfverstarna för folket bodde i Jerusalem; men det andra folket kastade lott derom, att af tio skulle en del draga till Jerusalem, den helga staden, till att bo der, och nio delar i städerna.',
        2: 'Och folket välsignade alla de män, som friviljoge voro till att bo i Jerusalem.',
        3: 'Desse äro hufvuden i landskapen, de som i Jerusalem bodde; men i Juda städer bodde hvar och en på sina ägor, som i deras städer voro; nämliga Israel, Presterna, Leviterna, Nethinim och Salomos tjenares barn.',
        4: 'Och i Jerusalem bodde någre af Juda barn, och BenJamin. Af Juda barn: Athaja, Ussia son, Zacharia sons, Amaria sons, Sephatja sons, Mahalaleels sons, af Parez barn;',
        5: 'Och Maaseja, Baruchs son. CholHose sons, Hasaja sons, Adaja sons, Jojaribs sons, Zacharia sons, Siloni sons.',
        6: 'All Parez barn, som i Jerusalem bodde, voro fyrahundrad åtta och sextio dugelige män.',
        7: 'Desse äro BenJamins barn: Sallu, Mesullams son, Joeds sons, Pedaja sons, Kolaja sons, Maasesa sons, Ithiels sons, Jesaja sons.',
        8: 'Och efter honom Gabbai, Sallia, niohundrad åtta och tjugu.',
        9: 'Och Joel, Sichri son, var deras föreståndare; och Juda, Hasuna son, öfver den andra delen i stadenom.',
        10: 'Af Presterna bodde: Jedaja, Jojaribs son, Jachin.',
        11: 'Seraja, Hilkia son, Mesullams sons, Zadoks sons, Merajoths sons, Ahitobs sons, var Förste i Guds hus.',
        12: 'Och deras bröder, som i husena skaffa hade, voro åttahundrad två och tjugu. Och Adaja, Jerohams son, Pelalja sons, Amzi sons, Zacharia sons, Pashurs sons, Malchija sons,',
        13: 'Och hans bröder öfverstar ibland fäderna, voro tuhundrad två och fyratio; och Amassai, Asareels son, Ahsai sons, Mesillemoths sons, Immers sons,',
        14: 'Och deras bröder, väldige män, voro hundrade åtta och tjugu; och deras föreståndare var Sabdiel, Gedolims son.',
        15: 'Af Leviterna: Semaja, Hasubs son, Asrikams sons, Hasabia sons, Bunni sons;',
        16: 'Och Sabbethai, och Josabad af Leviternas öfverstar, uti de ärende, som utantill voro vid Guds hus;',
        17: 'Och Matthania, Micha son, Sabdi sons, Assaphs sons, den hufvudet var till att begynna tacksägelse i bönene; och Bakbukia den andre ibland sina bröder: och Abda, Sammua son, Galals sons, Jeduthuns sons.',
        18: 'Alle Leviterna i dem helga stadenom voro tuhundrad fyra och åttatio.',
        19: 'Och dörravaktarena, Akkub och Talmon, och deras bröder, som vid dörrarna vaktade, voro hundrade två och sjutio.',
        20: 'Men de andre Israel, Prester och Leviter, voro uti alla Juda städer, hvar och en i sinom arfvedel.',
        21: 'Och de Nethmim bodde i Ophel; och Ziha, och Gispa hörde till de Nethinim.',
        22: 'Föreståndaren öfver de Leviter i Jerusalem var Ussi, Bani son, Hasabia sons. Mattania sons, Micha sons. Utaf Assaphs barn voro sångare vid tjensten i Guds hus;',
        23: 'Förty Konungens bud var öfver dem, att sångarena skulle handla troliga, hvar och en på den dag, som honom borde.',
        24: 'Och Petahja, Mesesabeels son, af Serahs barn, Juda sons, var i Konungens stad i all ärende till folket.',
        25: 'Och Juda barn, som ute voro på bygdene i sin land, bodde somlige i KiriathArba, och i dess döttrom, och i Dibon, och i dess döttrom, och i Kabzeel, och dess döttrom.',
        26: 'Och i Jesua, Molada, BethPhalet,',
        27: 'HazarSual, BerSeba, och dess döttrom,',
        28: 'Och i Ziklag, och Mechona, och dess döttrom,',
        29: 'Och i EnRimmon, Sarega, Jarmuth,',
        30: 'Sanoah, Adullam, och dess döttrom; i Lachis, och på dess mark; i Aseka, och i dess döttrom. Och de lägrade sig, allt ifrå BerSeba intill Hinnoms dal.',
        31: 'Men BenJamins barn af Geba bodde i Michmas, Aija, BethEl och dess döttrar,',
        32: 'Och i Anathoth, Nob, Anania,',
        33: 'Hazor, Rama, Gittaim,',
        34: 'Hadid, Zeboim, Neballat,',
        35: 'Lod, Ono, i timberdalenom.',
        36: 'Och somlige Leviterna, som del hade i Juda, bodde ibland BenJamin.',
    },
    12: {
        1: 'Desse äro de Prester och Leviter, som uppdrogo med Serubbabel, Sealthiels son, och Jesua: Seraja, Jeremia, Esra,',
        2: 'Amaria, Malluch, Hattus,',
        3: 'Sechania, Rehum, Meremoth,',
        4: 'Iddo, Ginnethoi, Abia,',
        5: 'Mijamin, Maadia, Bilga,',
        6: 'Semaja, Jojarib, Jedaja,',
        7: 'Sallu, Amok, Hilkia och Jedaja. Desse voro hufvuden ibland Presterna, och deras bröder i Jesua tid.',
        8: 'Men Leviterna voro desse: Jesua, Binnui, Kadmiel, Serebia, Juda och Mattania, öfver tackämbetet, han och hans bröder.',
        9: 'Bakbukia och Unni, deras bröder, voro omkring dem i vakt.',
        10: 'Jesua födde Jojakim. Jojakim födde Eljasib. Eljasib födde Jojada.',
        11: 'Jojada födde Jonathan. Jonathan födde Jaddua.',
        12: 'Och i Jojakims tid voro desse öfverste fäder ibland Presterna, nämliga af Seraja var Meraja; af Jeremia var Hanania;',
        13: 'Af Esra var Mesullam; af Amaria var Johanan;',
        14: 'Af Malluch var Jonathan; af Sebania var Joseph;',
        15: 'Af Harim var Adna; af Merajoth var Helkai;',
        16: 'Af Iddo var Zacharia; af Ginnethon var Mesullam;',
        17: 'Af Abia var Sichri; af MinjaminMoadia var Piltai;',
        18: 'Af Bilga var Sammua; af Semaja var Jonathan;',
        19: 'Af Jojarib var Mattenai; af Jedaja var Ussi;',
        20: 'Af Sallai var Kallai; af Amok var Eber;',
        21: 'Af Hilkia var Hasabia; af Jedaja var Nethaneel.',
        22: 'Och i Eljasibs tid, Jojada, Johanan och Jaddua, vordo öfverste fäderna ibland Leviterna och Presterna beskrifne, under Darios, den Persens rike.',
        23: 'Men Levi barn, öfverste fäderna vordo beskrifne i Chrönicon, allt intill Johanans tid, Eljasibs sons.',
        24: 'Och desse voro öfverstarne i Leviterna: Hasabia, Serebia och Jesua, Kadmiels son; och deras bröder jemte dem, till att lofva och tacka, såsom den Guds mannen David det budit hade, den ena vakten vid den andra.',
        25: 'Mattania, Bakbukia, Obadja, Mesullam, Talmon och Akkub, voro dörravaktare i vaktene vid dörrena i portomen.',
        26: 'Desse voro i Jojakims tid, Jesua sons, Jozadaks sons; och i Nehemia den landshöfdingans, och Prestens Esra den Skriftlärdas tid.',
        27: 'Och uti murens vigning i Jerusalem sökte man Leviterna utur all deras rum, att man skulle hafva dem till Jerusalem, till att hålla vigning med glädje, med tacksägelse, med sång, med cymbaler, psaltare och harpor.',
        28: 'Och sig församlade sångarenas barn, och af den ängden omkring Jerusalem, och af Netophati byar,',
        29: 'Och af Gilgals hus, och af den mark i Geba, och Asmaveth; förty sångarena hade byggt sig byar omkring Jerusalem.',
        30: 'Och Presterna och Leviterna renade sig, och renade folket, portarna och muren.',
        31: 'Och jag lät Juda Förstar stiga upp på muren, och beställde två stora tackchorar; de gingo åstad, den ene på högra sidone ofvan uppå murenom, åt dyngoporten;',
        32: 'Och efter dem gick Hosaja, och hälften af Juda Förstar,',
        33: 'Och Asaria, Esra, Mesullam,',
        34: 'Juda, BenJamin, Semaja och Jeremia;',
        35: 'Och någre af Prestabarnen med trummeter, nämliga Zacharia, Jonathans son, Semaja sons, Mattania sons, Michaja sons, Saccurs sons, Assaphs sons;',
        36: 'Och hans bröder, Semaja, Asareel, Milalai, Gilalai, Maai, Nethaneel och Juda, Hanani med den Guds mansens Davids strängaspel; men Esra den Skriftlärde för dem.',
        37: 'Och vid brunnporten, gentöfver dem, gingo de på trappomen åt Davids stad, uppåt muren om Davids hus, allt intill vattuporten östantill.',
        38: 'Den andre tackchoren gick tvärsifrå dem, och jag efter honom, och hälften af folket, utåt murenom uppåt ugnatornet, allt intill den breda muren;',
        39: 'Och uppåt Ephraims port, och till gamla porten, och till fiskaporten, och till Hananeels torn, och till Mea torn, allt intill fåraporten; och blefvo ståndande i fängelseportenom.',
        40: 'Och stodo alltså de två tackchorer uti Guds huse, och jag, och hälften af öfverstarna med mig;',
        41: 'Och Presterna, nämliga Eljakim, Maaseja, Minjamin, Michaja, Eljoenai, Zacharia, Hanania, med trummeter;',
        42: 'Och Maaseja, Semaja, Eleasar, Ussi, Johanan, Malchija, Elam och Eser; och sångarena söngo högt; och Jisrahja var föreståndaren.',
        43: 'Och stor offer vordo offrad på den samma dagen, och de voro glade; ty Gud hade gjort dem en stor glädje, så att både qvinnor och barn fröjdade sig; och Jerusalems glädje hördes långan väg.',
        44: 'På den tiden vordo män förskickade öfver skattkistona, der häfoffer, förstling och tiond uti var, att de skulle samka tillhopa af åkromen omkring städerna, till att utdela efter lagen för Prester och Leviter; ty Juda hade en glädje af Presterna och Leviterna, att de stodo.',
        45: 'Och de höllo sins Guds vakt, och reningenes vakt; och sångarena och dörravaktarena stodo efter Davids och hans sons Salomos bud.',
        46: 'Förty i Davids och Assaphs tid vordo stiktade öfverste sångare, och lofsånger, och tacksägningar till Gud.',
        47: 'Men hele Israel gaf sångarena och dörravaktarena delar uti Serubbabels och Nehemia tid, hvar dagen sin del. Och de gåfvo af det helgada Levitomen; och Leviterna gåfvo Aarons barnom af det helgada.',
    },
    13: {
        1: 'Och på den tid vardt Mose bok läsen för folkens öron; och vardt funnet deruti skrifvet, att de Ammoniter och de Moabiter skulle aldrig komma uti Guds församling;',
        2: 'Derföre, att de icke mötte Israels barnom med bröd och vatten, utan lejde Bileam emot dem, att han skulle förbanna dem; ändock vår Gud vände den förbannelsen uti välsignelse.',
        3: 'Då de nu hörde denna lagen, af skiljde de allt blandningsfolk ifrån Israel.',
        4: 'Och tillförene hade Presten Eljasib lagt Tobia håfvor uti offerkammaren, i vår Guds hus.',
        5: 'Förty han hade gjort honom en stor kammar, der de hade tillförene lagt spisoffer, rökelse, redskap och tiond af säd, vin och oljo, efter Leviternas, sångarenas och dörravaktarenas bud; dertill Presternas häfoffer.',
        6: 'Men i allt detta var jag icke i Jerusalem; ty uti andra och tretionde årena Arthahsasta, Konungens i Babel, kom jag till Konungen; och efter några dagar förvärfde jag lof af Konungenom.',
        7: 'Och jag drog åter till Jerusalem; och jag förmärkte, att det icke godt var, som Eljasib med Tobia gjort hade, i det han gjorde honom en kammar i gårdenom till Guds hus.',
        8: 'Och mig förtröt det svårliga; och jag kastade all Tobia hus tyg ut för kammaren,',
        9: 'Och bad, att de skulle rena kamrarna; och jag lät komma dit i samma staden Guds hus tyg, spisoffer och rökelse.',
        10: 'Och jag förnam, att Leviternas delar vordo dem icke gifne; för hvilka sak Leviterna och sängarena voro bortflydde, hvar till sin åker, till att arbeta.',
        11: 'Då straffade jag öfverstarna, och sade: Hvi öfvergifve vi Guds hus? Men jag församlade dem, och satte dem i sitt rum.',
        12: 'Och hele Juda lät komma fram tiond af säd, vin och oljo, i drätselen.',
        13: 'Och jag satte öfver drätselen Selemia Presten, och Zadok den Skriftlärda, och af Leviterna, Pedaja; och under deras hand Hanan, Saccurs son, Mattania sons; förty de voro hållne för trogna män, och dem vardt befaldt utskifta sinom brödrom.',
        14: 'Tänk uppå mig, min Gud, derföre, och bortkasta icke mina barmhertighet, som jag med mins Guds huse, och i hans vakt, gjorde.',
        15: 'På samma tiden såg jag i Juda trampas i presserna om Sabbathen, och införas kärfvar, och åsnar ladda med vin, drufvor, fikon och allahanda bördor, till Jerusalem, på Sabbathsdagen; och jag betygade dem på den dagen, då de sålde spisningen.',
        16: 'Bodde desslikes Tyrer derinne; de förde fisk och allahanda varor, och sålde det på Sabbatherna, Juda barnom och Jerusalem.',
        17: 'Då straffade jag de öfversta i Juda, och sade till dem: Hvad är det för en ond ting, som I gören, och bryten Sabbathsdagen?',
        18: 'Gjorde icke våre fäder så, och vår Gud lät komma alla denna olyckon öfver oss, och öfver denna staden? Och I gören ännu vredena öfver Israel större, brytande Sabbathen.',
        19: 'Och då portarna i Jerusalem uppdragne voro för Sabbathen, böd jag tillsluta portarna, och befallde, att man icke skulle upplåta dem intill efter Sabbathen; och jag satte några af mina tjenare vid portarna, att ingen börda skulle föras derin om Sabbathsdagen.',
        20: 'Så blefvo de krämare och köpmän, med allahanda varor, om nattena, utanför porten af Jerusalem, en gång och annan.',
        21: 'Då betygade jag dem, och sade till dem: Hvi blifven I om nattene utanför muren? Om I gören så mer, skall min hand komma uppå eder. Ifrå den tiden kommo de intet om Sabbathen.',
        22: 'Och jag sade till Leviterna, som rene voro, att de skulle komma och vakta portarna, till att helga Sabbathsdagen. Min Gud, tänk ock på mig för detta här, och skona mig efter dina stora barmhertighet.',
        23: 'Jag såg ock på den tiden, att Judarna togo sig hustrur af Asdod, Ammon och Moab;',
        24: 'Och deras barn talade half Asdodisko, och kunde icke tala Judisko, utan efter hvars folkens mål.',
        25: 'Och jag straffade dem, och bannade dem, och slog några män, och hårdrog dem, och tog en ed af dem vid Gud: I skolen icke gifva edra döttrar deras söner, icke heller taga deras döttrar till edra söner, eller till eder sjelf.',
        26: 'Hafver icke Salomo, Israels Konung, syndat dermed? Och var dock ibland många Hedningar ingen Konung honom lik. Och han var sinom Gud kär; och Gud satte honom till Konung öfver hela Israel. Likväl kommo de utländska qvinnor honom till att synda.',
        27: 'Hafven I det icke hört, medan I sådant stort ondt gören, och förtagen eder emot vår Gud med främmande qvinnors giftermål?',
        28: 'Och en af Jojada barn, Eljasibs sons, öfversta Prestens, hade befryndat sig med Saneballat den Horoniten; men jag dref honom ifrå mig.',
        29: 'Tänk uppå dem, min Gud, som besmitta Presterskapet, och Presterskapens förbund, och Leviternas.',
        30: 'Alltså renade jag dem ifrån alla utländska; och beställde Presternas och Leviternas vakt, hvar och en till sitt ämbete;',
        31: 'Och till att offra ved, på bestämd tid, och förstling. Tänk uppå mig, Gud, till det bästa.',
    },
}
