NAME = 'GerBoLut: Deutsch Bolsingerߴs Luther 1545 Bibel (moderne Rechtschreibung)'
BOOK = 'I John'

CHAPTERS = {
    1: {
        1: 'Das da von Anfang war, das wir gehoret haben, das wir gesehen haben mit unsern Augen, das wir beschauet haben, und unsere Hande betastet haben, vom Wort des Lebens',
        2: '(und das Leben ist erschienen, und wir haben gesehen und zeugen und verkundigen euch das Leben, das ewig ist, welches war bei dem Vater und ist uns erschienen);',
        3: 'was wir gesehen und gehoret haben: das verkundigen wir euch, auf daß auch ihr mit uns Gemeinschaft habet, und unsere Gemeinschaft sei mit dem Vater und mit Sohn, Jesu Christo.',
        4: 'Und solches schreiben wir euch, auf daß eure Freude vollig sei.',
        5: 'Und das ist die Verkundigung, die wir von ihm gehoret haben und euch verkundigen, dafi Gott ein Licht ist, und in ihm keine Finsternis.',
        6: 'So wir sagen, daß wir Gemeinschaft mit ihm haben, und wandeln in Finsternis, so lugen wir und tun nicht die Wahrheit.',
        7: 'So wir aber im Licht wandeln, wie er im Lichte ist, so haben wir Gemeinschaft untereinander, und das Blut Jesu Christi, seines Sohnes, macht uns rein von aller Sünde.',
        8: 'So wir sagen, wir haben keine Sünde, so verfuhren wir uns selbst, und die Wahrheit ist nicht in uns.',
        9: 'So wir aber unsere Sünde bekennen, so ist er treu und gerecht, daß er uns die Sünde vergibt und reiniget uns von aller Untugend.',
        10: 'So wir sagen, wir haben nicht gesündiget, so machen wir ihn zum Lügner, und sein Wort ist nicht in uns.',
    },
    2: {
        1: 'Meine Kindlein, solches schreibe ich euch, auf daß ihr nicht sundiget. Und ob jemand sündiget, so haben wir einen Fürsprecher bei dem Vater, Jesum Christum, der gerecht ist.',
        2: 'Und derselbige ist die Versohnung für unsere Sünde, nicht allein aber für die unsere, sondern auch für die der ganzen Welt.',
        3: 'Und an dem merken wir, daß wir ihn kennen, so wir seine Gebote halten.',
        4: 'Wer da sagt: Ich kenne ihn, und halt seine Gebote nicht, der ist ein Lügner, und in solchem ist keine Wahrheit.',
        5: 'Wer aber sein Wort halt, in solchem ist wahrlich die Liebe Gottes vollkommen. Daran erkennen wir, daß wir in ihm sind.',
        6: 'Wer da sagt, daß er in ihm bleibet, der soil auch wandeln, gleichwie er gewandelt hat.',
        7: 'Brüder, ich schreibe euch nicht ein neu Gebot, sondern das alte Gebot, das ihr habt von Anfang gehabt. Das alte Gebot ist das Wort, das ihr von Anfang gehoret habt.',
        8: 'Wiederum ein neu Gebot schreibe ich euch, das da wahrhaftig ist bei ihm und bei euch; denn die Finsternis ist vergangen, und das wahre Licht scheinet jetzt.',
        9: 'Wer da sagt, er sei im Licht, und hasset seinen Bruder, der ist noch in Finsternis.',
        10: 'Wer seinen Bruder liebet, der bleibet Licht, und ist kein Argernis bei ihm.',
        11: 'Wer aber seinen Bruder hasset, der ist in Finsternis und wandelt in Finsternis und weift nicht, wo er hingehet; denn die Finsternis hat seine Augen verblendet.',
        12: 'Liebe Kindlein, ich schreibe euch, daß euch die Sünden vergeben werden durch seinen Namen.',
        13: 'Ich schreibe euch Vatern; denn ihr kennet den, der von Anfang ist. Ich schreibe euch Junglingen; denn ihr habt den Bosewicht überwunden. Ich schreibe euch Kindern; denn ihr kennet den Vater.',
        14: 'Ich habe euch Vatern geschrieben, daß ihr den kennet, der von Anfang ist. Ich habe euch Junglingen geschrieben, daß ihr stark seid, und das Wort Gottes bei euch bleibet, und den Bosewicht überwunden habt.',
        15: 'Habt nicht lieb die Welt, noch was in der Welt ist. So jemand die Welt liebhat, in dem ist nicht die Liebe des Vaters.',
        16: 'Denn alles, was in der Welt ist (namlich des Fleisches Lust und der Augen Lust und hoffartiges Leben), ist nicht vom Vater, sondern von der Welt.',
        17: 'Und die Welt vergehet mit ihrer Lust; wer aber den Willen Gottes tut, der bleibet in Ewigkeit.',
        18: 'Kinder, es ist die letzte Stunde; und wie ihr gehoret habt, daß der Widerchrist kommt, und nun sind viel Widerchristen worden; daher erkennen wir, daß die letzte Stunde ist.',
        19: 'Sie sind von uns ausgegangen, aber sie waren nicht von uns. Denn wo sie von uns gewesen waren, so waren sie ja bei uns geblieben; aber auf daß sie offenbar würden, daß sie nicht alle von uns sind.',
        20: 'Und ihr habt die Salbung von dem, der heilig ist; und wisset alles.',
        21: 'Ich habe euch nicht geschrieben, als wüfttet ihr die Wahrheit nicht, sondern ihr wisset sie und wisset, daß keine Luge aus der Wahrheit kommt.',
        22: 'Wer ist ein Lügner, ohne der da leugnet, daß Jesus der Christus sei? Das ist der Widerchrist, der den Vater und den Sohn leugnet.',
        23: 'Wer den Sohn leugnet, der hat auch den Vater nicht.',
        24: 'Was ihr nun gehoret habt von Anfang, das bleibe bei euch. So bei euch bleibet, was ihr von Anfang gehoret habt, so werdet ihr auch bei dem Sohn und Vater bleiben.',
        25: 'Und das ist die Verheiftung, die er uns verheiften hat: das ewige Leben.',
        26: 'Solches habe ich euch geschrieben von denen, die euch verfuhren.',
        27: "Und die Salbung, die ihr von ihm empfangen habt, bleibet bei euch, und durfet nicht, daß euch jemand lehre, sondern wie euch die Salbung allerlei lehret, so ist's wahr, und ist keine Luge; und wie sie euch gelehret hat, so bleibet bei demselbigen.",
        28: 'Und nun, Kindlein, bleibet bei ihm, auf daß, wenn er offenbaret wird, daß wir Freudigkeit haben und nicht zuschanden werden vor ihm in seiner Zukunft.',
        29: 'So ihrwisset, daß er gerecht ist, so erkennet auch, daß, wer recht tut, der ist von ihm geboren.',
    },
    3: {
        1: 'Sehet, welch eine Liebe hat uns der Vater erzeiget, daß wir Gottes Kinder sollen heilien! Darum kennet euch die Welt nicht, denn sie kennet ihn nicht.',
        2: 'Meine Lieben, wirsind nun Gottes Kinder, und ist noch nicht erschienen, was wir sein werden. Wir wissen aber, wenn es erscheinen wird, daß wir ihm gleich sein werden; denn wir werden ihn sehen, wie er ist.',
        3: 'Und ein jeglicher, der solche Hoffnung hat zu ihm, der reiniget sich, gleichwie er auch rein ist.',
        4: 'Wer Sunde tut, der tut auch Unrecht; und die Sünde ist das Unrecht.',
        5: 'Und ihr wisset, daß er ist erschienen, auf daß er unsere Sunden wegnehme; und ist keine Sünde in ihm.',
        6: 'Wer in ihm bleibet, der sundiget nicht; wer da sundiget, der hat ihn nicht gesehen noch erkannt.',
        7: 'Kindlein, lasset euch niemand verfuhren! Wer recht tut, der ist gerecht, gleichwie er gerecht ist.',
        8: 'Wer Sünde tut, der ist vom Teufel; denn der Teufel sundiget von Anfang. Dazu ist erschienen der Sohn Gottes, daß er die Werke des Teufels zerstore.',
        9: 'Wer aus Gott geboren ist, der tut nicht Sunde; denn sein Same bleibet bei ihm, und kann nicht sündigen; denn er ist von Gott geboren.',
        10: "Daran wird's offenbar, welche die Kinder Gottes und die Kinder des Teufels sind. Wer nicht recht tut, der ist nicht von Gott, und wer nicht seinen Bruder liebhat.",
        11: 'Denn das ist die Botschaft, die ihr gehoret habt von Anfang, daß wir uns untereinander lieben sollen.',
        12: 'Nicht wie Kain, der von dem Argen war und erwurgete seinen Bruder. Und warum erwurgete er ihn? Dali seine Werke bose waren und seines Binders gerecht.',
        13: 'Verwundert euch nicht, meine Bruder, ob euch die Welt hasset!',
        14: 'Wir wissen, daß wir aus dem Tode in das Leben kommen sind; denn wir lieben die Bruder. Wer den Bruder nicht liebet, der bleibet im Tode.',
        15: 'Wer seinen Bruder hasset, der ist ein Totschlager; und ihrwisset, daß ein Totschlager nicht hat das ewige Leben bei ihm bleibend.',
        16: 'Daran haben wir erkannt die Liebe, daß er sein Leben fur uns gelassen hat; und wir sollen auch das Leben fur die Bruder lassen.',
        17: 'Wenn aber jemand dieser Welt Guter hat und siehet seinen Bruder darben und schlielit sein Herz vor ihm zu: wie bleibet die Liebe Gottes bei ihm?',
        18: 'Meine Kindlein, lasset uns nicht lieben mit Worten noch mit der Zunge, sondern mit der Tat und mit der Wahrheit.',
        19: 'Daran erkennen wir, daß wir aus der Wahrheit sind, und konnen unser Herz vor ihm stillen,',
        20: 'dati, so uns unser Herz verdammt, daß Gott grolier ist denn unser Herz und erkennet alle Dinge.',
        21: 'Ihr Lieben, so uns unser Herz nicht verdammt, so haben wir eine Freudigkeit zu Gott;',
        22: 'und was wir bitten, werden wir von ihm nehmen; denn wir halten seine Gebote und tun, was vor ihm gefallig ist.',
        23: 'Und das ist sein Gebot, daß wir glauben an den Namen seines Sohnes Jesu Christi und lieben uns untereinander, wie er uns ein Gebot gegeben hat.',
        24: 'Und wer seine Gebote halt, der bleibet in ihm und er in ihm. Und daran erkennen wir, daß er in uns bleibet: an dem Geist, den er uns gegeben hat.',
    },
    4: {
        1: 'Ihr Lieben, glaubet nicht einem jeglichen Geist, sondern prufet die Geister, ob sie von Gott sind; denn es sind viel falsche Propheten ausgegangen in die Welt.',
        2: 'Daran sollt ihr den Geist Gottes erkennen: Ein jeglicher Geist, der da bekennet, daß Jesus Christus ist in das Fleisch kommen, der ist von Gott;',
        3: 'und ein jeglicher Geist, der da nicht bekennet, daß Jesus Christus ist in das Fleisch kommen, der ist nicht von Gott. Und das ist der Geist des Widerchrists, von welchem ihr habt gehoret, daß er kommen werde, und ist jetzt schon in der Welt.',
        4: 'Kindlein, ihrseid von Gott und habtjene überwunden; denn der in euch ist, ist grolier, denn der in der Welt ist.',
        5: 'Sie sind von der Welt; darum reden sie von der Welt, und die Welt horet sie.',
        6: 'Wir sind von Gott, und wer Gott erkennet, der horet uns; welcher nicht von Gott ist, der horet uns nicht. Daran erkennen wir den Geist der Wahrheit und den Geist des Irrtums.',
        7: 'Ihr Lieben, lasset uns untereinander liebhaben; denn die Liebe ist von Gott; und wer liebhat, der ist von Gott geboren und kennet Gott.',
        8: 'Wer nicht liebhat, der kennet Gott nicht; denn Gott ist die Liebe:',
        9: 'Daran ist erschienen die Liebe Gottes gegen uns, daß Gott seinen eingebornen Sohn gesandt hat in die Welt, daß wir durch ihn leben sollen.',
        10: 'Darinnen stehet die Liebe, nicht daß wir Gott geliebet haben, sondern dad er uns geliebet hat und gesandt seinen Sohn zur Versohnung fur unsere Sünden.',
        11: 'Ihr Lieben, hat uns Gottalso geliebet, sosollen wir uns auch untereinander lieben.',
        12: 'Niemand hatßottjemals gesehen. So wir uns untereinander lieben, so bleibet Gott in uns, und seine Liebe ist vollig in uns.',
        13: 'Daran erkennen wir, daß wir in ihm bleiben und er in uns, dad er uns von seinem Geist gegeben hat.',
        14: 'Und wir haben gesehen und zeugen, dad der Vater den Sohn gesandt hat zum Heiland der Welt.',
        15: 'Welcher nun bekennet, dad Jesus Gottes Sohn ist, in dem bleibet Gott und er in Gott.',
        16: 'Und wir haben erkannt und geglaubet die Liebe, die Gott zu uns hat. Gott ist die Liebe; und wer in der Liebe bleibet, der bleibet in Gott und Gott in ihm.',
        17: 'Daran ist die Liebe vollig bei uns, auf dad wir eine Freudigkeit haben am Tage des Gerichts; denn gleichwie er ist, so sind auch wir in dieser Welt.',
        18: 'Furcht ist nicht in der Liebe, sondern die vollige Liebe treibet die Furcht aus; denn die Furcht hat Pein. Wer sich aber furchtet, der ist nicht vollig in der Liebe.',
        19: 'Lasset uns ihn lieben; denn er hat uns erst geliebet.',
        20: 'So jemand spricht: Ich liebe Gott, und hasset seinen Bruder, der ist ein Lugner; denn wer seinen Bruder nicht liebet, den er siehet, wie kann er Gott lieben, den er nicht siehet?',
        21: 'Und dies Gebot haben wir von ihm, dad, wer Gott liebet, dad der auch seinen Bruder liebe.',
    },
    5: {
        1: 'Wer da glaubet, dad Jesus sei der Christus, der ist von Gott geboren. Und wer da liebet den, der ihn geboren hat, der liebet auch den, der von ihm geboren ist.',
        2: 'Daran erkennen wir, dad wir Gottes Kinder lieben, wenn wir Gott lieben und seine Gebote halten.',
        3: 'Denn das ist die Liebe zu Gott, dad wir seine Gebote halten; und seine Gebote sind nicht schwer.',
        4: 'Denn alles, was von Gott geboren ist, uberwindet die Welt; und unser Glaube ist der Sieg, der die Welt uberwunden hat.',
        5: 'Wer ist aber, der die Welt uberwindet ohne der da glaubet, dad Jesus Gottes Sohn ist?',
        6: "Dieser ist's, der da kommt mit Wasser und Blut, Jesus Christus, nicht mit Wasser allein, sondern mit Wasser und Blut. Und der Geist ist's, der da zeuget, dad Geist Wahrheit ist.",
        7: 'Denn drei sind, die da zeugen im Himmel: der Vater, das Wort und der Heilige Geist; und diese drei sind eins.',
        8: 'Und drei sind, die da zeugen auf Erden: der Geist und das Wasser und das Blut; und die drei sind beisammen.',
        9: 'So wir der Menschen Zeugnis annehmen, so ist Gottes Zeugnis grafter; denn Gottes Zeugnis ist das, das er gezeuget hat von seinem Sohne.',
        10: 'Wer da glaubet an den Sohn Gottes, der hat solch Zeugnis bei sich. Wer Gott nicht glaubet, der macht ihn zum Lugner; denn er glaubet nicht dem Zeugnis, das Gott zeuget von seinem Sohn.',
        11: 'Und das ist das Zeugnis, daß uns Gott das ewige Leben hat gegeben, und solches Leben ist in seinem Sohn.',
        12: 'Wer den Sohn Gottes hat, der hat das Leben; wer den Sohn Gottes nicht hat, der hat das Leben nicht.',
        13: "Solches hab' ich euch geschrieben, die ihr glaubet an den Namen des Sohnes Gottes, auf daß ihr wisset, daß ihr das ewige Leben habet, und daß ihr glaubet an den Namen des Sohnes Gottes.",
        14: 'Und das ist die Freudigkeit, die wir haben zu ihm, daß, so wir etwas bitten nach seinem Willen, so horet er uns.',
        15: 'Und so wir wissen, daß er uns horet, was wir bitten, so wissen wir, daß wir die Bitten haben, die wir von ihm gebeten haben.',
        16: 'So jemand siehet seinen Bruder sundigen, eine Sunde nicht zum Tode, der mag bitten; so wird er geben das Leben denen, die da sundigen nicht zum Tode. Es ist eine Sunde zum Tode; dafür sage ich nicht, daß jemand bitte.',
        17: 'Alle Untugend ist Sunde; und es ist etliche Sunde nicht zum Tode.',
        18: 'Wir wissen, daß, wer von Gott geboren ist, der sundiget nicht, sondern wer von Gott geboren ist, der bewahret sich, und der Arge wird ihn nicht antasten.',
        19: 'Wir wissen, daß wir von Gott sind; und die ganze Welt liegt im Argen.',
        20: 'Wir wissen aber, daß der Sohn Gottes kommen ist und hat uns einen Sinn gegeben, daß wir erkennen den Wahrhaftigen und sind in dem Wahrhaftigen, in seinem Sohn Jesu Christo. Dieser ist der wahrhaftige Gott und das ewige Leben.',
        21: 'Kindlein, hütet euch vor den Abgottern! Amen. Der zweite Brief des Johannes',
    },
}
