NAME = 'FreGeneve1669: Le Nouveau Testament de la Bible de Genève de 1669'
BOOK = 'Ephesians'

CHAPTERS = {
    1: {
        1: 'PAUL Apoftre de Jefus Chrift par la volonté de Dieu, aux Saints & Fideles en Jefus Chrift, qui font à Ephefe:',
        2: 'Grace vous foit & paix de par Dieu noftre Pere, & de par le Seigneur Jefus Chrift.',
        3: 'Benit foit Dieu, qui eft le Pere de noftre Seigneur Jefus Chrift, qui nous a benits en toute benediction fpirituelle, és lieux celeftes en Chrift:',
        4: "Selon qu'il nous avoit éleus en lui, devant la fondation du monde, afin que nous fuffions faincts & irreprehenfibles devant lui en charité:",
        5: 'Nous ayans predeftinez pour nous adopter à foi par Jefus Chrift, felon le bon plaifir de fa volonté:',
        6: 'A la loüange de la gloire de fa grace, de laquelle il nous a rendus agreables en fon bien-aimé.',
        7: 'En qui nous avons redemption des offenfes, felon les richeffes de fa grace:',
        8: 'Laquelle il a fait largement abonder fur nous en toute fapience & intelligence:',
        9: 'Nous ayant donné à connoiftre le fecret de fa volonté, felon fon bon plaifir, lequel il avoit premierement arrefté en foi:',
        10: "Afin qu'en la difpenfation de l'accompliffement des temps, il recueillift enfemble le tout en Chrift, tant les chofes qui font aux cieux que celles qui font en la terre, en lui mefme.",
        11: 'En qui auffi nous fommes faits fon heritage, ayans efté predeftinez, fuivant le propos arrefté de celui qui accomplit en efficace toutes chofes felon le confeil de fa volonté:',
        12: 'Afin que nous foyons à la loüange de fa gloire, nous qui avons les premiers efperé en Chrift.',
        13: "En qui vous eftes auffi, ayans ouï la parole de verité, affavoir l'Evangile de voftre falut: auquel auffi ayans creu vous avez efté feellez du S. Efprit de la promeffe.",
        14: "Lequel eft l'arrhe de noftre heritage, jusques à la redemption de la poffeffion acquife, à la loüange de fa gloire.",
        15: 'Pour cette caufe moi auffi ayant entendu la foi que vous avez au Seigneur Jefus, & la charité que vous avez envers tous les Saints,',
        16: 'Je ne ceffe de rendre graces pour vous, faifant mention de vous en mes prieres:',
        17: "Afin que le Dieu de noftre Seigneur Jefus Chrift, le Pere de gloire, vous donne l'Efprit de fapience & de revelation, par la connoiffance d'icelui:",
        18: "Affavoir les yeux de voftre entendement illuminez, afin que vous fçachiez quelle eft l'efperance de fa vocation: & quelles font les richeffes de la gloire de fon heritage és Saints:",
        19: "Et quelle eft l'excellente grandeur de fa puiffance envers nous qui croyons, felon l'efficace de la puiffance de fa force:",
        20: "Laquelle il a déployée avec efficace en Chrift, quand il l'a reffufcité des morts, & l'a fait feoir à fa dextre és lieux celeftes:",
        21: 'Par deffus toute principauté, & puiffance, & vertu, & feigneurie, & par deffus tout nom qui fe nomme, non feulement en ce fiecle, mais auffi en celui qui eft à venir.',
        22: "Et a affujetti toutes chofes fous les pieds d'icelui, & l'a donné fur toutes chofes pour eftre chef à l'Eglife:",
        23: "Laquelle eft fon corps, & l'accompliffement de celui qui accomplit tout en tous.",
    },
    2: {
        1: 'ET lors que vous eftiez morts en vos fautes & pechez,',
        2: "Efquels autrefois vous avez cheminé, fuivant le train de ce monde, felon le prince de la puiffance de l'air, qui eft l'efprit qui opere maintenant avec efficace és enfans de rebellion:",
        3: "Entre lefquels auffi nous avons tous converfé autrefois és convoitifes de noftre chair, accompliffans les defirs de la chair & de nos penfées: & nous eftions de nature enfans d'ire, comme auffi les autres.",
        4: 'mais Dieu, qui eft riche en mifericorde, par fa grande charité de laquelle il nous a aimez,',
        5: 'Du temps mefme que nous eftions morts en nos fautes, nous a vivifiez enfemble avec Chrift, par la grace duquel vous eftes fauvez.',
        6: 'Et nous a reffufcité enfemble, & nous a fait feoir enfemble és lieux celeftes en Jefus Chrift:',
        7: "Afin qu'il montraft és fiecles à venir les abondamment excellentes richeffes de fa grace, par fa benignité envers nous en Jefus Chrift.",
        8: "Car vous eftes fauvez par grace, par la foi: & cela non point de vous, c'est le don de Dieu:",
        9: 'Non point par les œuvres, afin que nul ne fe glorifie.',
        10: 'Car nous fommes fon ouvrage, eftans créez en Jefus Chrift à bonnes œuvres, que Dieu a preparées, afin que nous cheminions en elles.',
        11: 'Partant, ayez fouvenance que vous qui eftiez autrefois Gentils en la chair, & eftiez appellez Prepuce par celle qui eft appellée la Circoncifion, faite de main en la chair,',
        12: "Eftiez en ce tems-là hors de Chrift, n'ayans rien de commun avec la republique d'Ifraël; eftant eftrangers des alliances de la promeffe, n'ayans point d'efperance, & eftans fans Dieu au monde.",
        13: 'Mais maintenant par Jefus Chrift, vous qui eftiez autrefois loin, eftes approchez par le fang de Chrift.',
        14: 'Car il eft noftre paix, qui de tous les deux en a fait un, ayant rompu la clofture de la paroi entre-moyenne:',
        15: "Ayant aboli en fa chair l'inimité, affavoir la Loi des commandemens, qui confifte en ordonnances: afin qu'il creaft les deux en foi-mefme, en un homme nouveau, en faifant la paix:",
        16: "Et qu'il ralliaft les uns & les autres en un corps à Dieu, par la croix, ayant deftruit en elle l'inimitié.",
        17: 'Et eftant venu il a evangelizé la paix à vous qui eftiez loin, & à ceux qui eftoyent prés.',
        18: 'Car nous avons par lui, les uns & les autres, accez au Pere en un mefme Efprit.',
        19: "Vous n'eftes donc plus eftrangers ni forains, mais combourgeois des Saints, & domeftiques de Dieu:",
        20: 'Eftans edifiez fur le fondement des Apoftres & des Prophetes, Jefus Chrift lui-mefme eftant la maiftreffe pierre du coin:',
        21: "En qui tout l'edifice rapporté & ajufté enfemble, fe leve pour eftre un temple fainct au Seigneur:",
        22: 'En qui vous auffi eftes enfemble edifiez, pour eftre un tabernacle de Dieu en Efprit.',
    },
    3: {
        1: 'POUR cette caufe, moi Paul fuis le prifonnier de Jefus Chrift pour vous les Gentils:',
        2: "Voire fi vous avez entendu la difpenfation de la grace de Dieu, qui m'a efté donnée envers vous:",
        3: "Comment par revelation il m'a donné à connoiftre le myftere: (ainfi que par ci-devant je vous ai efcrit en peu de mots:",
        4: "D'où le lifant vous pouvés connoiftre l'intelligence que j'ai au myftere de Chrift.)",
        5: "Lequel n'a point efté donné à connoiftre aux enfans des hommes és autres âges, ainfi que maintenant il a efté revelé par l'Efprit à fes faints Apoftres & Prophetes:",
        6: "Affavoir que les Gentils font coheritiers, & d'un mefme corps, & participans enfemble de la promeffe d'icelui en Jefus Chrift, par l'Evangile.",
        7: "Duquel j'ai efté fait miniftre, felon le don de la grace de Dieu, lequel m'a efté donné fuivant l'efficace de fa puiffance.",
        8: "Cette grace m'a efté donnée à moi qui fuis le moindre de tous les Saincts, pour annoncer entre les Gentils les richeffes incomprehenfibles de Chrift:",
        9: 'Et pour mettre en evidence devant tous quelle eft la communication du myftere, qui eftoit caché de tout temps en Dieu, qui a creé toutes chofes par Jefus Chrift:',
        10: "Afin que la fapience de Dieu, qui eft diverfe en toutes fortes, foit maintenant donnée à connoiftre aux Principautez & aux Puiffances, és lieux celeftes, par l'Eglife:",
        11: 'Suivant le propos arrefté dés les fiecles, lequel il a eftabli en Jefus Chrift noftre Seigneur:',
        12: 'Par lequel nous avons hardieffe & accez en confiance, par la foi que nous avons en lui.',
        13: "C'eft pourquoi je requiers que vous ne vous laffiez point à caufe de mes tribulations que j'endure pour l'amour de vous; ce qui eft voftre gloire.",
        14: 'Pour laquelle caufe je ploye mes genoux, devant le Pere de noftre Seigneur Jefus Chrift.',
        15: '(Duquel toute la parenté eft nommée és cieux & en la terre.)',
        16: "Afin que felon les richeffes de fa gloire, il vous donne d'eftre puiffament fortifiez par fon Efprit en l'homme interieur:",
        17: 'Tellement que Chrift habite en vos cœurs par la foi:',
        18: "Afin qu'eftant enracinez & fondez en charité, vous puiffiez finalement comprendre avec tous les Saincts, quelle est la largeur & la longueur, & la profondeur & la hauteur;",
        19: 'Et connoiftre la dilection de Chrift, laquelle furpaffe toute connoiffance: afin que vous foyez remplis en toute plenitude de Dieu.',
        20: 'Or à celui qui par la puiffance qui agit en nous avec efficace, peut faire en toute abondance par deffus tout ce que nous demandons & penfons,',
        21: "A lui foit gloire en l'Eglife, en Jefus Chrift, en tous les âges du fiecle des fiecles. Amen.",
    },
    4: {
        1: 'JE vous prie donc, moi le prifonnier au Seigneur, que vous cheminez dignement comme il eft féant à la vocation à la vocation à laquelle vous eftes appellés:',
        2: "Avec toute humilité & douceur, avec un efprit patient, fupportans l'un l'autre en charité.",
        3: "Eftans foigneux de garder l'unité de l'Efprit par le lien de la paix.",
        4: 'Il y a un feul corps & un feul Efprit, comme auffi vous eftes appellez en une feule efperance de voftre vocation.',
        5: 'Il y a un feul Seigneur, une feule foi, un feul Baptefme.',
        6: 'Un feul Dieu & Pere de tous, qui eft fur tous, & parmi tous, & en nous tous.',
        7: 'Mais la grace eft donnée à chacun de nous, felon la mefure du don de Chrift.',
        8: 'Pour laquelle chofe il dit, Eftant monté en haut il a mené captive une grande multitude de captifs, & a donné des dons aux hommes.',
        9: "Or ce qu'il eft monté, qu'eft-ce autre chofe finon que premierement il eftoit defcendu és parties les plus baffes de la terre?",
        10: "Celui qui eft defcendu, c'eft le mefme qui eft monté fur tous les cieux, afin qu'il remplift toutes chofes.",
        11: 'Lui mefme donc a donné les uns pour eftre Apoftres, & les autres pour eftre Prophetes, & les autres pour eftre Evangeliftes, & les autres pour eftre Pafteurs & Docteurs:',
        12: "Pour l'affemblage des Saints, pour l'œuvre du miniftere, pour l'edification du corps de Chrift:",
        13: "Jufques à ce que nous nous rencontrions tous en l'unité de la foi, & de la connoiffance du Fils de Dieu, en homme parfait, à la mefure de la parfaite ftature de Chrift.",
        14: 'Afin que nous ne foyons plus enfans, flottans, & eftans demeurez çà & là à tous vents de doctrine, par la piperie des hommes, & par leur rufe à cauteleufement feduire:',
        15: 'Mais afin que fuivans la verité avec charité, nous croiffions en tout en celui qui eft le chef, affavoir Chrift.',
        16: "Duquel tout le corps bien ajufté & ferré enfemble par toutes les jointures du fourniffement, prend l'accroiffement du corps, felon la vigueur qui eft en la mefure de chaque partie, pour l'edification de foi-mefme en charité.",
        17: "Voici donc ce que je dis & attefte de par le Seigneur, c'eft que vous ne cheminez plus comme auffi le refte des Gentils chemine en la vanité de leur penfée:",
        18: "Ayans leur entendement obfcurci de tenebres, & eftans eftrangez de la vie de Dieu, à caufe de l'ignorance qui eft en eux, par l'endurciffement de leur cœur.",
        19: 'Lefquels ayans perdu tout fentiment, fe font abandonnez à diffolution, pour commettre toute fouilleure, à qui en feroit pis.',
        20: "Mais vous n'avez point ainfi appris Chrift:",
        21: "Voire fi vous l'avez efcouté, & fi vous avez efté enfeignez de par lui, ainfi que la verité eft en Jefus:",
        22: 'Affavoir que vous defpouilliez le vieil homme, quant à la converfation precedente, lequel fe corrompt par les convoitifes qui feduifent:',
        23: "Et que vous foyez renouvellez en l'efprit de voftre entendement:",
        24: 'Et que vous foyez reveftus du nouvel homme, creé felon Dieu en juftice & vraye fainteté.',
        25: "C'eft pourquoi ayans defpouillé le menfonge, parlez en verité chacun avec fon prochain: car nous fommes membres les uns des autres.",
        26: 'Courroucez-vous, & ne pechez point: que le Soleil ne fe couche point fur voftre courroux.',
        27: 'Et ne donnez point de lieu au diable.',
        28: "Que celui qui defroboit, ne defrobbe plus, mais pluftoft qu'il travaille en ouvrant de fes mains en ce qui eft bon: afin qu'il ait pour departir à celui qui en a befoin.",
        29: "Que nul propos infect ne forte de voftre bouche: mais celui qui eft bon à l'ufage d'edification, afin qu'il donne grace à ceux qui l'oyent.",
        30: 'Et ne contriftez point le Saint Efprit de Dieu, par lequel vous avez efté feellez pour le jour de la redemption.',
        31: 'Que toute amertume, & colere, & ire, & crierie, & mefdifance, foyent oftées de vous, avec toute malice.',
        32: 'Mais foyez benins les uns envers les autres, pleins de compaffion, & pardonnans les uns aux autres, ainfi auffi que Dieu vous a pardonné par Chrift.',
    },
    5: {
        1: 'SOYEZ donc imitateurs de Dieu, comme chers enfans.',
        2: "Et cheminez en charité, ainfi que Chrift auffi nous a aimez, & s'eft donné foi-mefme pour nous, en oblation & facrifice à Dieu, en odeur de bonne fenteur.",
        3: "Que la paillardife, & toute fouileure, ou avarice, ne foit pas mefmes nommé entre vous, ainfi qu'il appartient aux Saints:",
        4: 'Ni chofes vilaine, ni parole folle, ni plaifanterie, qui font chofes qui ne font pas bien feantes: mais pluftoft action de graces.',
        5: "Car vous fçavez ceci, que nul paillard, ou immonde, ou avaricieux, qui eft idolatre, n'a point d'heritage au royaume de Chrift & de Dieu.",
        6: "Que nul ne vous feduife par de vains difcours: car pour ces chofes l'ire de Dieu vient fur les enfans de rebellion.",
        7: 'Ne foyez donc point leurs compagnons.',
        8: 'Car vous eftiez autrefois tenebres: mais maintenant vous eftes lumiere au Seigneur: cheminez comme enfans de lumiere:',
        9: "(Car le fruit de l'Efprit confifte en toute debonnaireté, juftice, & verité.)",
        10: 'Efprouvans ce qui eft agreable au Seigneur.',
        11: 'Et ne communiquez point aux œuvres infructueufes de tenebres, mais mefmes redarguez-les pluftoft.',
        12: 'Car il eft mefmes deshonnefte de dire les chofes qui font faites par eux en cachette.',
        13: 'Mais toutes chofes eftant redarguées par la lumiere, font renduës manifeftes: car la lumiere eft celle qui manifefte tout.',
        14: "A caufe dequoi il dit, Reveille-toi, toi qui dors, & te releve des morts, & Chrift t'éclairera.",
        15: 'Avifez donc comment vous cheminez foigneufement, non point comme eftant dénuez de fageffe, mais comme eftans fages:',
        16: 'Rachetans le temps: car les jours font mauvais.',
        17: "C'eft pourquoi ne foyez point fans prudence, mais bien entendans quelle eft la volonté du Seigneur.",
        18: "Et ne vous enyvrez point de vin, auquel il y a de la diffolution: mais foyez remplis de l'Efprit:",
        19: 'Parlans entre vous par Pfeaumes, loüange, & chanfons fpirituelles: chantans & pfalmodians en voftre cœur au Seigneur:',
        20: 'Rendans toûjours graces pour toutes chofes, au non de noftre Seigneur Jefus Chrift, à noftre Dieu & Pere:',
        21: 'Vous foufmettans les uns aux autres en la crainte de Dieu.',
        22: 'Femmes, foyez fujettes à vos propres maris, comme au Seigneur.',
        23: "Car le mari eft le chef de la femme, ainfi que Chrift auffi eft le chef de l'Eglife, & pareillement eft le Sauveur de fon corps.",
        24: "Comme donc l'Eglife eft fujette à Chrift, que femblablement auffi les femmes le foyent à leurs propres maris, en toutes chofes.",
        25: "Vous maris, aimez vos femmes, comme auffi Chrift a aimé l'Eglife, & s'eft donné foi-mefme pour elle.",
        26: "Afin qu'il la fanctifiaft, apres l'avoir nettoyée par le lavement d'eau par la parole:",
        27: "Afin qu'il fe la rendift une Eglife glorieufe, n'ayant point de tache, ni ride, ni autre telle chofe: mais afin qu'elle fuft fainte & irreprehenfible.",
        28: "Ainfi les maris doivent aimer leurs femmes comme leurs propres corps: Celui qui aime fa femme, s'aime foi-mefme.",
        29: "Car perfonne n'eut jamais en haine fa chair, mais il la nourrit & l'entretient, comme auffi le Seigneur l'Eglife.",
        30: 'Car nous fommes membres de fon corps, eftant de fa chair & de fes os.',
        31: "Pour cela l'homme delaiffera fon pere & fa mere, & s'adjoindra à fa femme: & les deux feront une mefme chair.",
        32: "Ce myftere eft grand: or je parle touchant Chrift & l'Eglife.",
        33: 'Partant quant à vous auffi, que chacun en fon endroit aime fa femme comme foi-mefme, & que la femme revere fon mari.',
    },
    6: {
        1: 'ENFANS, obeïffez à vos peres & meres au Seigneur: car cela eft jufte.',
        2: 'Honore ton pere & ta mere, (qui eft le premier commandement, avec promeffe.)',
        3: 'Afin que bien te foit, & que tu fois de longue vie fur la terre.',
        4: 'Et vous peres, ne depitez point vos enfans: mais nourriffez-les en la difcipline & remontrance du Seigneur.',
        5: 'Serviteurs, obeïffez à ceux qui font vos maiftres felon la chair, avec crainte & tremblement, en fimplicité de voftre cœur, comme à Chrift:',
        6: "Non point fervans à l'œil, comme voulans complaire aux hommes, mais comme ferfs de Chrift, faifans de courage la volonté de Dieu.",
        7: 'Servans de bonne affection au Seigneur & non point aux hommes:',
        8: "Sçachans que chacun recevra du Seigneur le bien qu'il aura fait, foit ferf, foit franc.",
        9: "Et vous maiftres, faites envers eux le femblable, relachans les menaces, fçachans que le Seigneur au tant d'eux que de vous, eft és cieux: & qu'envers lui il n'y a point d'acception de perfonne.",
        10: 'Au refte, mes freres, fortifiez-vous au Seigneur, & en la puiffance de fa force.',
        11: 'Soyez reveftus de toutes les armures de Dieu, afin que vous puiffiez refifter contre les embufches du diable.',
        12: "Car nous n'avons point la luite contre le fang & la chair, mais contre les Principautez, contre les Puiffances, contre les Seigneurs du monde, gouverneurs des tenebres de ce fiecle, contre les malices fpirituelles qui font és lieux celeftes.",
        13: "C'eft pourquoi prenez toutes les armures de Dieu, afin que vous puiffiez refifter au mauvais jour, & ayans tout achevé demeurer fermes.",
        14: 'Soyez donc fermes, ayans vos reins ceints de verité, & eftans reveftus de la cuiraffe de juftice:',
        15: "Et ayans les pieds chauffez de la preparation de l'Evangile de paix.",
        16: 'Prenans fur tout le bouclier de la foi, par lequel vous puiffiez éteindre tous les dards enflammez du malin.',
        17: "Prenez auffi le cafque de falut, & l'efpée de l'Efprit, qui eft la Parole de Dieu.",
        18: 'Prians en toutes fortes de priere & de requefte, en tout temps, en efprit, & veillans à cela avec toute perfeverance & requefte pour tous les Saints:',
        19: "Et pour moi, afin que la parole me foit donnée à bouche ouverte en hardieffe: afin de donner à connoiftre le myftere de l'Evangile.",
        20: 'Pour lequel je fuis ambaffadeur en la chaîne, afin que je parle franchement comme il me faut parler.',
        21: 'Or afin que vous auffi entendiez mon eftat, & ce que je fais, Tychique noftre frere bien-aimé, & fidele miniftre au Seigneur, vous fera fçavoir le tout.',
        22: "Lequel je vous ai envoyé exprés pour cela, afin que vous entendiez noftre eftat, & qu'il confole vos cœurs.",
        23: 'Paix foit aux freres, & charité avec foi, de par Dieu le Pere, & de par le Seigneur Jefus Chrift.',
        24: 'Grace foit avec tous ceux qui aiment noftre Seigneur Jefus Chrift en pureté. amen.',
    },
}
