NAME = 'GerBoLut: Deutsch Bolsingerߴs Luther 1545 Bibel (moderne Rechtschreibung)'
BOOK = 'Ephesians'

CHAPTERS = {
    1: {
        1: 'Paulus, ein Apostel Jesu Christi durch den Willen Gottes: Den Heiligen zu Ephesus und Glaubigen an Christo Jesu.',
        2: 'Gnade sei mit euch und Friede von Gott, unserm Vater, und dem Herrn Jesu Christo!',
        3: 'Gelobet sei Gott und der Vater unsers Herrn Jesu Christi, der uns gesegnet hat mit allerlei geistlichem Segen in himmlischen Gutern durch Christum;',
        4: 'wie er uns denn erwahlet hat durch denselbigen, ehe der Welt Grund gelegt war, daß wir sollten sein heilig und unstraflich vor ihm in der Liebe;',
        5: 'und hat uns verordnet zur Kindschaft gegen ihn selbst durch Jesum Christum, nach dem Wohlgefallen seines Willens,',
        6: 'zu Lob seiner herrlichen Gnade, durch welche er uns hat angenehm gemacht in dem Geliebten,',
        7: 'an welchem wir haben die Erlosung durch sein Blut, namlich die Vergebung der Sünden, nach dem Reichtum seiner Gnade,',
        8: 'welche uns reichlich widerfahren ist durch allerlei Weisheit und Klugheit.',
        9: 'Und hat uns wissen lassen das Geheimnis seines Willens nach seinem Wohlgefallen und hat dasselbige hervorgebracht durch ihn,',
        10: 'daß es geprediget würde, da die Zeit erfullet war, auf daß alle Dinge zusammengefassetwürden in Christo, beide, das im Himmel und auch auf Erden ist, durch ihn selbst,',
        11: 'durch welchen wir auch zum Erbteil kommen sind, die wir zuvor verordnet sind nach dem Vorsatz des, der alle Dinge wirket nach dem Rat seines Willens,',
        12: 'auf daß wir etwas seien zu Lob seiner Herrlichkeit, die wir zuvor auf Christum hoffen;',
        13: 'durch welchen auch ihr gehoret habtdas Wort der Wahrheit, namlich das Evangelium von eurer Seligkeit; durch welchen ihr auch, da ihrglaubetet, versiegelt worden seid mit dem Heiligen Geist der Verheiliung,',
        14: 'welcher ist das Pfand unsers Erbes zu unserer Erlosung, daß wir sein Eigentum würden zu Lob seiner Herrlichkeit.',
        15: 'Darum auch ich, nachdem ich gehoret habe von dem Glauben bei euch an den Herrn Jesum und von eurer Liebe zu alien Heiligen,',
        16: 'hore ich nichtauf, zu danken fur euch, und gedenke euer in meinem Gebet,',
        17: 'daß der Gott unsers Herrn Jesu Christi, der Vater der Herrlichkeit, gebe euch den Geist der Weisheit und der Offenbarung zu seiner selbst Erkenntnis',
        18: 'und erleuchtete Augen eures Verstandnisses, daß ihr erkennen moget, welche da sei die Hoffnung eurer Berufung, und welcher sei der Reichtum seines herrlichen Erbes an seinen Heiligen,',
        19: 'und welche da sei die uberschwengliche Grolie seiner Kraft an uns, die wir glauben nach der Wirkung seiner machtigen Starke,',
        20: 'welche er gewirket hat in Christo, da er ihn von den Toten auferwecket hat und gesetzt zu seiner Rechten im Himmel',
        21: 'uber alle Furstentümer, Gewalt, Macht, Herrschaft und ailes, was genannt mag werden, nicht allein in dieser Welt, sondern auch in derzukunftigen.',
        22: 'Und hat alle Dinge unter seine Fülie getan und hat ihn gesetzt zum Haupt der Gemeinde uber ailes,',
        23: 'welche da ist sein Leib, namlich die Fülle des, der ailes in alien erfullet.',
    },
    2: {
        1: 'Und auch euch, da ihr tot waret durch Ubertretungen und Sunden,',
        2: 'in welchen ihrweiland gewandelt habt nach dem Lauf dieser Welt und nach dem Fursten, der in der Luft herrschet, namlich nach dem Geist, der zu dieser Zeit sein Werk hat in den Kindern des Unglaubens,',
        3: 'unter welchen wir auch alle weiland unsern Wandel gehabt haben in den Lusten unsers Fleisches, und taten den Willen des Fleisches und der Vernunft und waren auch Kinder des Zorns von Natur, gleichwie auch die andern;',
        4: 'aber Gott, der da reich ist von Barmherzigkeit, durch seine grolie Liebe, damit er uns geliebet hat:',
        5: 'da wir tot waren in den Sunden, hat er uns samt Christo lebendig gemacht (denn aus Gnaden seid ihr selig worden)',
        6: 'und hat uns samt ihm auferwecket und samt ihm in das himmlische Wesen gesetzt in Christo Jesu,',
        7: 'auf dafi er erzeigete in den zukünftigen Zeiten den uberschwenglichen Reichtum seiner Gnade durch seine Güte uber uns in Christo Jesu.',
        8: 'Denn aus Gnaden seid ihr selig worden durch den Glauben, und dasselbige nicht aus euch, Gottes Gabe ist es;',
        9: 'nicht aus den Werken, auf daß sich nicht jemand rühme.',
        10: 'Denn wir sind sein Werk, geschaffen in Christo Jesu zu guten Werken, zu welchen Gott uns zuvor bereitet hat, daü wir darinnen wandeln sollen.',
        11: 'Darum gedenket daran, daß ihr, die ihr weiland nach dem Fleisch Heiden gewesen seid und die Vorhaut genannt wurdet von denen, die genannt sind die Beschneidung nach dem Fleisch, die mit der Hand geschieht,',
        12: 'daß ihr zu derselbigen Zeit waret ohne Christum, fremd und aulier der Burgerschaft Israels und fremd von den Testamenten der Verheiliung; daher ihr keine Hoffnung hattet und waret ohne Gott in der Welt.',
        13: 'Nun aber, die ihr in Christo Jesu seid und weiland feme gewesen, seid nun nahe worden durch das Blut Christo.',
        14: 'Denn er ist unser Friede, der aus beiden eins hat gemacht und hat abgebrochen den Zaun, der dazwischen war, in dem, daß erdurch sein Fleisch wegnahm die Feindschaft,',
        15: 'namlich das Gesetz, so in Geboten gestellet war, auf daß er aus zweien einen neuen Menschen in ihm selber schaffete und Frieden machete,',
        16: 'und daß er beide versohnete mit Gott in einem Leibe durch das Kreuz; und hat die Feindschaft getotet durch sich selbst',
        17: 'und ist kommen, hat verkundiget im Evangelium den Frieden euch, die ihr feme waret, und denen, die nahewaren.',
        18: 'Denn durch ihn haben wirden Zugang alle beide in einem Geiste zum Vater.',
        19: 'So seid ihr nun nicht mehr Gaste und Fremdlinge, sondern Burger mit den Heiligen und Gottes Hausgenossen,',
        20: 'erbauetaufden Grund der Apostel und Propheten, da Jesus Christus der Eckstein ist',
        21: 'auf welchem derganze Bau, ineinandergefuget, wachset zu, einem heiligen Tempel in dem Herrn,',
        22: 'auf welchem auch ihr mit erbauet werdet zu einer Behausung Gottes. im Geist.',
    },
    3: {
        1: 'Derhalben ich, Paulus, der Gefangene Christi Jesu fur euch Heiden,',
        2: 'nachdem ihr gehoret habt von dem Amt der Gnade Gottes, die mir an euch gegeben ist,',
        3: 'daß mir ist kund worden dieses Geheimnis durch Offenbarung, wie ich droben aufs kurzeste geschrieben habe,',
        4: "daran ihr, so ihr's leset, merken konnet meinen Verstand an dem Geheimnis Christi,",
        5: 'welches nicht kundgetan ist in den vorigen Zeiten den Menschenkindern, als es nun offenbart ist seinen heiligen Aposteln und Propheten durch den Geist,',
        6: 'namlich daß die Heiden Miterben seien und mit eingeleibet und Mitgenossen seiner Verheiftung in Christo durch das Evangelium,',
        7: 'des ich ein Diener worden bin nach der Gabe aus der Gnade Gottes, die mir nach seiner machtigen Kraft gegeben ist:',
        8: 'mir, dem allergeringsten unter alien Heiligen, ist gegeben diese Gnade, unter den Heiden zu verkundigen den unausforschlichen Reichtum Christi',
        9: 'und zu erleuchten jedermann, welche da sei die Gemeinschaft des Geheimnisses, das von der Welt her in Gott verborgen gewesen ist, der alle Dinge geschaffen hat durch Jesum Christum,',
        10: 'auf daß jetzt kund wurde den Furstentumern und Herrschaften in dem Himmel an der Gemeinde die mannigfaltige Weisheit Gottes',
        11: 'nach dem Vorsatz von der Welt her, welche er beweiset hat in Christo Jesu, unserm Herrn,',
        12: 'durch welchen wir haben Freudigkeit und Zugang in aller Zuversicht durch den Glauben an ihn.',
        13: 'Darum bitte ich, daß ihr nicht mude werdet urn meiner Trubsal willen, die ich fur euch leide, welche euch eine Ehre sind.',
        14: 'Derhalben beuge ich meine Kniee gegen den Vater unsers Herrn Jesu Christi,',
        15: 'der der rechte Vater ist über alles, was da Kinder heiftt im Himmel und auf Erden,',
        16: 'daß er euch Kraft gebe nach dem Reichtum seiner Herrlichkeit, stark zu werden durch seinen Geist an dem inwendigen Menschen,',
        17: 'und Christum zu wohnen durch den Glauben in euren Herzen, und durch die Liebe eingewurzelt und gegrundet zu werden,',
        18: 'auf daß ihr begreifen moget mit alien Heiligen, welches da sei die Breite und die Lange und die Tiefe und die Hohe,',
        19: 'auch erkennen, daß Christum liebhaben viel besser ist denn alles Wissen, auf daß ihr erfullet werdet mit allerlei Gottesfulle.',
        20: 'Dem aber, der überschwenglich tun kann uber alles, was wir bitten Oder verstehen, nach der Kraft, die da in uns wirket,',
        21: 'dem sei Ehre in der Gemeinde, die in Christo Jesu ist, zu aller Zeit, von Ewigkeit zu Ewigkeit! Amen.',
    },
    4: {
        1: "So ermahne nun euch ich Gefangener in dem Herrn, daß ihr wandelt, wie sich's gebuhrt eurer Berufung, darinnen ihr berufen seid,",
        2: 'mit aller Demut und Sanftmut, mit Geduld und vertraget einer den andern in der Liebe',
        3: 'und seid fleiftig, zu halten die Einigkeit im Geist durch das Band des Friedens.',
        4: 'Ein Leib und ein Geist, wie ihr auch berufen seid auf einerlei Hoffnung eurer Berufung.',
        5: 'Ein Herr, ein Glaube, eine Taufe,',
        6: 'ein Gott und Vater (unser) aller, der da ist fiber euch alle und durch euch alle und in euch alien.',
        7: 'Einem jeglichen aber unter uns ist gegeben die Gnade nach dem Maft der Gabe Christi.',
        8: 'Darum spricht er: Er ist aufgefahren in die Hohe und hat das Gefangnis gefangen gefuhret und hat den Menschen Gaben gegeben.',
        9: "Daft er aber aufgefahren ist, was ist's, denn daß er zuvor ist hinuntergefahren in die untersten Orter der Erde?",
        10: 'Der hinuntergefahren ist, das ist derselbige, der aufgefahren ist über alle Himmel, auf daß er alles erfullete.',
        11: 'Und er hat etliche zu Aposteln gesetzt, etliche aberzu Propheten, etliche zu Evangelisten, etliche zu Hirten und Lehrern,',
        12: 'daß die Heiligen zugerichtet werden zum Werk des Amts, dadurch der Leib Christi erbauet werde,',
        13: 'bis daß wir alle hinankommen zu einerlei Glauben und Erkenntnis des Sohnes Gottes und ein vollkommener Mann werden, der da sei im Maße des vollkommenen Alters Christi,',
        14: 'auf daß wir nicht mehr Kinder seien und uns wagen und wiegen lassen von allerlei Wind der Lehre durch Schalkheit der Menschen und Tauscherei, damit sie uns erschleichen zu verfuhren.',
        15: 'Lasset uns aber rechtschaffen sein in der Liebe und wachsen in alien Stricken an dem, der das Haupt ist, Christus,',
        16: 'aus welchem der ganze Leib zusammengefuget, und ein Glied am andern hanget durch alle Gelenke, dadurch eines dem andern Handreichung tut nach dem Werk eines jeglichen Gliedes in seinem Maße und machet, dafi der Leib wachset zu seiner selbst Besserung; und das alles in der Liebe:',
        17: 'So sage ich nun und zeuge in dem Herrn, dati ihr nicht mehr wandelt, wie die andern Heiden wandeln der Eitelkeit ihres Sinnes,',
        18: 'welcher Verstand verfinstert ist, und sind entfremdet von dem Leben, das aus Gott ist, durch die Unwissenheit, so in ihnen ist, durch die Blindheit ihres Herzens.',
        19: 'welche ruchlos sind und ergeben sich der Unzucht und treiben allerlei Unreinigkeit samt dem Geiz.',
        20: 'Ihr aber habt Christum nicht also gelernet,',
        21: 'so ihr anders von ihm gehoret habt und in ihm gelehret seid, wie in Jesu ein rechtschaffen Wesen ist.',
        22: 'So leget nun von euch ab nach dem vorigen Wandel den alten Menschen, der durch Lüste in Irrtum sich verderbet.',
        23: 'Erneuert euch aber im Geist eures Gemüts',
        24: 'und ziehet den neuen Menschen an, der nach Gott geschaffen ist in rechtschaffener Gerechtigkeit und Heiligkeit.',
        25: 'Darum leget die Luge ab und redet die Wahrheit, ein jeglicher mit seinem Nachsten, sintemal wir untereinander Glieder sind.',
        26: 'Zürnet, und sundiget nicht; lasset die Sonne nicht uber eurem Zorn untergehen.',
        27: 'Gebet auch nicht Raum dem Lasterer!',
        28: 'Wer gestohlen hat, der stehle nicht mehr, sondern arbeite und schaffe mit den Handen etwas Gutes, auf daß er habe, zu geben dem Dürftigen.',
        29: 'Lasset kein faul Geschwatz aus eurem Munde gehen, sondern was nutzlich zur Besserung ist, da es not tut, daß es holdselig sei zu horen.',
        30: 'Und betrubet nicht den Heiligen Geist Gottes, damit ihr versiegelt seid auf den Tag der Erlosung.',
        31: 'Alle Bitterkeit und Grimm und Zorn und Geschrei und Lasterung sei feme von euch samt aller Bosheit.',
        32: 'Seid aber untereinander freundlich, herzlich und vergebet einer dem andern, gleichwie Gott euch vergeben hat in Christo.',
    },
    5: {
        1: 'So seid nun Gottes Nachfolger als die lieben Kinder!',
        2: 'Und wandelt in der Liebe, gleichwie Christus uns hat geliebet und sich selbst dargegeben fur uns zur Gabe und Opfer, Gott zu einem süßen Geruch.',
        3: 'Hurerei aber und alle Unreinigkeit Oder Geiz lasset nicht von euch gesagt werden, wie den Heiligen zustehet,',
        4: 'auch schandbare Worte und Narrenteidinge Oder Scherz, welche euch nicht ziemen, sondern vielmehr Danksagung.',
        5: 'Denn das sollt ihr wissen, dafi kein Hurer Oder Unreiner Oder Geiziger (welcher ist ein Gotzendiener) Erbe hat an dem Reich Christi und Gottes.',
        6: 'Lasset euch niemand verfuhren mit vergeblichen Worten! Denn urn dieser willen kommt der Zorn Gottes über die Kinder des Unglaubens.',
        7: 'Darum seid nicht ihre Mitgenossen!',
        8: 'Denn ihrwaretweiland Finsternis; nun aber seid ihr ein Licht in, dem Herrn.',
        9: 'Wandelt wie die Kinder des Lichts! Die Frucht des Geistes ist allerlei Gütigkeit und Gerechtigkeit und Wahrheit.',
        10: 'Und prüfet, was da sei wohlgefallig dem Herrn.',
        11: 'Und habt nicht Gemeinschaft mit den unfruchtbaren Werken der Finsternis; strafet sie aber vielmehr.',
        12: 'Denn was heimlich von ihnen geschieht, das ist auch schandlich zu sagen.',
        13: 'Das alles aber wird offenbar, wenn es vom Licht gestraft wird. Denn alles, was offenbar wird, das ist Licht.',
        14: 'Darum spricht er: Wache auf, der du schlafest, und stehe auf von den Toten, so wird dich Christus erleuchten.',
        15: 'So sehet nun zu, wie ihrvorsichtiglich wandelt, nicht als die Unweisen, sondern als die Weisen.',
        16: 'Und schicket euch in die Zeit; denn es ist bose Zeit.',
        17: 'Darum werdet nicht unverstandig, sondern verstandig, was da sei des Herrn Wille.',
        18: 'Und saufeteuch nicht voll Weins, daraus ein unordentlich Wesen folget, sondern werdet voll Geistes',
        19: 'und redet untereinander von Psalmen und Lobgesangen und geistlichen Liedern; singet und spielet dem Herrn in euren Herzen.',
        20: 'Und saget Dank allezeit fur alles Gott und dem Vater in dem Namen unsers Herrn Jesu Christi.',
        21: 'Und seid untereinander untertan in der Furcht Gottes.',
        22: 'Die Weiber seien untertan ihren Mannern als dem Herrn.',
        23: 'Denn der Mann ist des Weibes Haupt, gleichwie auch Christus das Haupt ist der Gemeinde, und er ist seines Leibes Heiland.',
        24: 'Aber wie nun die Gemeinde ist Christo untertan, also auch die Weiber ihren Mannern in alien Dingen.',
        25: 'Ihr Manner, liebet eure Weiber, gleichwie Christus auch geliebet hat die Gemeinde und hat sich selbst fur sie gegeben,',
        26: 'auf daß er sie heiligte, und hat sie gereiniget durch das Wasserbad im Wort,',
        27: 'auf daß er sie sich selbst darstellete als eine Gemeinde, die herrlich sei, die nicht habe einen Flecken Oder Runzel Oder des etwas, sondern dafi sie heilig sei und unstraflich.',
        28: 'Also sollen auch die Manner ihre Weiber lieben als ihre eigenen Leiber. Wersein Weib liebet, der liebet sich selbst.',
        29: 'Denn niemand hat jemals sein eigen Fleisch gehasset, sondern er nahret es und pfleget sein, gleichwie auch der Herr die Gemeinde.',
        30: 'Denn wir sind Glieder seines Leibes, von seinem Fleisch und von seinem Gebeine.',
        31: 'Urn deswillen wird ein Mensch verlassen Vater und Mutter und seinem Weibe anhangen, und werden zwei ein Fleisch sein.',
        32: 'Das Geheimnis ist groß; ich sage aber von Christo und der Gemeinde;',
        33: 'Doch auch ihr, ja ein jeglicher habe lieb sein Weib als sich selbst; das Weib aber furchte den Mann.',
    },
    6: {
        1: 'Ihr Kinder, seid gehorsam euren Eltern in dem Herm; denn das ist billig.',
        2: 'Ehre Vater und Mutter; das ist das erste Gebot, das Verheifiung hat:',
        3: "Auf daß dir's wohl gehe, und du lange lebest auf Erden.",
        4: 'Und ihr Vater, reizet eure Kinder nicht zum Zorn, sondern ziehet sie auf in der Zucht und Vermahnung zu dem Herm.',
        5: 'Ihr Knechte, seid gehorsam euren leiblichen Herren mit Furcht und Zittern, in Einfaltigkeit eures Herzens, als Christo;',
        6: 'nicht mit Dienst allein vor Augen, als den Menschen zu gefallen, sondern als die Knechte Christi, daß ihr solchen Willen Gottes tut von Herzen, mitgutem Willen.',
        7: 'Lasset euch dunken, daß ihr dem Herm dienet und nicht den Menschen;',
        8: 'und wisset, was ein jeglicher Gutes tun wird, das wird er von dem Herm empfangen, er sei ein Knecht Oder ein Freier.',
        9: 'Und ihr Herren, tut auch dasselbige gegen sie und lasset das Drauen; und wisset, daß auch euer Herr im Himmel ist, und ist bei ihm kein Ansehen der Person.',
        10: 'Zuletzt meine Bruder, seid stark in dem Herm und in der Macht seiner Starke!',
        11: 'Ziehet an den Harnisch Gottes, daß ihr bestehen konnet gegen die listigen Anlaufe des Teufels.',
        12: 'Denn wir haben nicht mit Fleisch und Blut zu kampfen, sondern mit Fursten und Gewaltigen, namlich mit den Herren der Welt, die in der Finsternis dieser Welt herrschen, mit den bosen Geistern unter dem Himmel.',
        13: 'Urn deswillen so ergreifet den Harnisch Gottes, auf da(S ihr an dem bosen Tage Widerstand tun und alles wohl ausrichten und das Feld behalten moget.',
        14: 'So stehet nun, umgurtet an euren Lenden mit Wahrheit und angezogen mit dem Krebs der Gerechtigkeit',
        15: 'und an den Beinen gestiefelt, als fertig, zu treiben das Evangelium des Friedens, damit ihr bereitet seid.',
        16: 'Vor alien Dingen aber ergreifet den Schild des Glaubens, mit welchem ihr ausloschen konnt alle feurigen Pfeile des Bosewichts.',
        17: 'Und nehmet den Helm des Heils und das Schwert des Geistes, welches ist das Wort Gottes.',
        18: 'Und betet stets in allem Anliegen mit Bitten und Flehen im Geist und wachet dazu mit allem Anhalten und Flehen fur alle Heiligen',
        19: 'und fur mich, auf daß mir gegeben werde das Wort mit freudigem Auftun meines Mundes, daß ich moge kundmachen das Geheimnis des Evangeliums,',
        20: "welches Bote ich bin in der Kette, auf daß ich darinnen freudig handeln moge und reden, wie sich's gebuhrt.",
        21: "Auf daß aber ihr auch wisset, wie es urn mich stehet, und was ich schaffe, wird's euch alles kundtun Tychikus, mein lieber Bruder und getreuer Diener in dem Herrn",
        22: 'welchen ich gesandt habe zu euch urn desselbigenwillen, daß ihr erfahret, wie es urn mich stehet, und daß er eure Herzen troste.',
        23: 'Friede sei den Brudern und Liebe mit Glauben von Gott dem Vater und dem Herrn Jesu Christo!',
        24: 'Gnade sei mit alien, die da liebhaben unsern Herrn Jesum Christum unverruckt! Amen.',
    },
}
