NAME = 'DaOT1871NT1907: Danish OT1871 + NT1907 with original orthography'
BOOK = 'Song of Solomon'

CHAPTERS = {
    1: {
        1: 'Højsangen, som er af Salomo.',
        2: 'Han kysse mig med Kys af sin Mund; thi din Kærlighed er bedre end Vin.',
        3: 'Dine Salver ere gode at lugte, dit Navn er som en Salve, der udgydes; derfor elske unge Piger dig.',
        4: 'Drag mig! efter dig ville vi løbe; Kongen førte mig ind i sine inderste Kamre; vi ville fryde os og glæde os i dig, vi ville prise din Kærlighed mere end Vin; de oprigtige elske dig.',
        5: 'Jeg er sort, dog yndig, I Jerusalems Døtre! som Kedars Pauluner, som Salomos Telte.',
        6: 'Ser ikke paa mig, at jeg er sort; thi Solen har brændt mig; min Moders Sønner ere blevne vrede paa mig, de have sat mig til Vingaardenes Vogterinde; min Vingaard, som jeg havde, har jeg ikke bevogtet.',
        7: 'Giv mig til Kende, du, hvem min Sjæl elsker! hvor du vogter, hvor du lader Hjorden ligge om Middagen, at jeg ikke skal være som en Kvinde, der gaar tilhyllet ved dine Medbrødres Hjorde.',
        8: 'Dersom du ikke ved det, du dejligste iblandt Kvinderne! da gak ud i Faarenes Spor, og vogt dine Kid ved Hyrdernes Boliger!',
        9: 'Ved Hestene for Faraos Vogn ligner jeg dig, min Veninde!',
        10: 'Dine Kinder ere yndige under Kæderne og din Hals under Perlesnorene.',
        11: 'Vi ville gøre dig Guldkæder med Sølvprikker.',
        12: 'Saa længe Kongen var i sin Kreds, gav min Nardus sin Lugt.',
        13: 'Min elskede er mig en Myrrakugle, som forbliver imellem mine Bryster.',
        14: 'Min elskede er mig en Koferdrue, i Vingaardene, udi En-Gedi.',
        15: 'Se, du, min Veninde! er dejlig; se, du er dejlig, dine Øjne ere Duer.',
        16: 'Se, du, min elskede! er yndig, ja yndig, ja, vort Leje er grønt.',
        17: 'Vore Huses Bjælker ere Cedre, vort Loft er Cypresser.',
    },
    2: {
        1: 'Jeg er Sarons Rose, Dalenes Lillie.',
        2: 'Som en Lillie iblandt Tornene, saa er min Veninde iblandt Døtrene.',
        3: 'Ligesom et Æbletræ iblandt Skovens Træer, saa er min elskede iblandt Sønnerne; jeg begærer at sidde under hans Skygge, og hans Frugt er sød for min Gane.',
        4: 'Han fører mig til Vinhuset, og Kærlighed er hans Banner over mig.',
        5: 'Styrker mig med Rosinkager, vederkvæger mig med Æbler! thi jeg er syg af Kærlighed.',
        6: 'Hans venstre Haand er under mit Hoved, og hans højre Haand omfavner mig.',
        7: 'Jeg besværger eder, I Jerusalems Døtre! ved Raaerne eller ved Hinderne paa Marken, at I ikke vække eller forstyrre den kære, førend hun har Lyst dertil.',
        8: 'Min elskedes Røst! se, der kommer han, springende over Bjergene, hoppende over Højene.',
        9: 'Min elskede er lig en Raa eller en ung Hjort: se, han staar bag vor Væg, han ser ind igennem Vinduerne, kiger igennem Vinduesgitteret.',
        10: 'Min elskede svarer og siger til mig: Staa op, min Veninde! min skønne! og gak frem.',
        11: 'Thi se, Vinteren er forbi, Regnen er gaaet over og dragen bort.',
        12: 'Blomsterne ere komne til Syne i Landet, Sangens Tid er kommen, og Turtelduens Røst er hørt i vort Land.',
        13: 'Figentræet har udskudt sine smaa Figen, og Vinstokkene staa i Blomster og dufte; staa du op, min Veninde! min skønne! og gak frem!',
        14: 'Min Due i Klippens Revner, i Fjeldvæggens Skjul, lad mig se din Skikkelse, lad mig høre din Røst! thi din Røst er sød, og din Skikkelse er yndig.',
        15: 'Griber os Rævene, de smaa Ræve, som fordærve Vingaardene; vore Vingaarde staa i Blomster.',
        16: 'Min elskede er min, og jeg er hans, som vogter Hjorden iblandt Lillierne.',
        17: 'Indtil Dagens Luftning kommer, og Skyggerne fly, vend om, bliv lig, min elskede! med en Raa eller en ung Hjort paa Adskillelsens Bjerge!',
    },
    3: {
        1: 'Paa mit Leje om Natten søgte jeg den, som min Sjæl elsker; jeg søgte efter ham, men fandt ham ikke.',
        2: 'Jeg vil dog staa op og gaa omkring i Staden, paa Stræderne og paa Gaderne, jeg vil søge efter den, som min Sjæl elsker; jeg søgte efter ham og fandt ham ikke.',
        3: 'Vægterne, som gaa omkring i Staden, fandt mig; til dem sagde jeg: Have I set den, som min Sjæl elsker?',
        4: 'Næppe var jeg kommen forbi dem, førend jeg fandt den, som min Sjæl elsker; jeg greb ham og vil ikke lade ham fare, førend jeg faar bragt ham til min Moders Hus og til hendes Kammer, som undfangede mig.',
        5: 'Jeg besværger eder, I Jerusalems Døtre! ved Raaerne eller Hinderne paa Marken, at I ikke vække eller forstyrre den kære, førend hun har Lyst dertil.',
        6: 'Hvo er hun, der kommer op fra Ørken, som Støtter af Røg, omduftet af Myrra og Virak, af alle Haande vellugtende Sager?',
        7: 'Se Salomos Seng! der staar tresindstyve vældige trindt omkring den, af de vældige i Israel.',
        8: 'Alle forstaa de at bruge Sværd, de ere oplærte til Krig; hver har sit Sværd ved sin Side imod Nattens Rædsel.',
        9: 'Kong Salomo lod sig gøre en Bærestol af Træ fra Libanon.',
        10: 'Dens Stolper gjorde han af Sølv og Ryggen dertil af Guld, dens Sæde af Purpur; dens Indre var belagt med Kærlighed af Jerusalems Døtre.',
        11: 'I Zions Døtre! gaar ud og ser paa Kong Salomo med den Krone, som hans Moder kronede ham med paa hans Bryllupsdag og paa hans Hjertes Glædes Dag.',
    },
    4: {
        1: 'Se, du er dejlig, min Veninde! se, du er dejlig, dine Øjne ere Duer imellem dine Lokker; dit Haar er som en Gedehjord, der kommer op fra Gileads Bjerg.',
        2: 'Dine Tænder ere som en Hjord klippede Faar, som komme op af Svømmestedet, som alle sammen føde Tvillinger, og iblandt hvilke intet er ufrugtbart.',
        3: 'Dine Læber ere som en Skarlagens Snor, og din Tale er liflig; dine Tindinger ere som et Stykke af et Granatæble imellem dine Lokker.',
        4: 'Din Hals er som Davids Taarn, bygget til Rustkamre; der er hængte tusinde Skjolde derpaa, alle de vældiges Skjolde.',
        5: 'Dine to Bryster ere ligesom to unge Raatvillinger, som græsse iblandt Lillier.',
        6: 'Indtil Dagens Luftning kommer, og Skyggerne fly, vil jeg gaa til Myrrabjerget og til Virakshøjen.',
        7: 'Hel dejlig er du, min Veninde! og der er ingen Lyde paa dig.',
        8: 'Med mig, o Brud! fra Libanon, med mig fra Libanon skal du komme; du skal skue ned fra Amanas Top, fra Senirs og Hermons Top, fra Løvers Boliger, fra Parders Bjerge.',
        9: 'Du har opfyldt mit Hjerte, min Søster, o Brud! du har opfyldt mit Hjerte med et af dine Øjekast, med en af dine Halskæder.',
        10: 'Hvor liflig er din Kærlighed, min Søster, o Brud! hvor meget bedre end Vin er din Kærlighed og Duften af dine Salver fremfor alle vellugtende Urter.',
        11: 'Dine Læber, o Brud! dryppe af Honning; der er Honning og Mælk under din Tunge, og Duften af dine Klæder er ligesom Duften af Libanon.',
        12: 'Min Søster og Brud er en tillukt Have, et tillukt Væld, en forseglet Kilde.',
        13: 'Dine Vækster ere en Lysthave med Granatæbler, med kostelig Frugt, Koferblomster med Narder;',
        14: 'Nardus og Safran, Kalmus og Kanel, med alle Haande Viraks Træer, Myrra og Aloe, samt alle de bedste Urter;',
        15: 'en Kilde i Haverne, en Brønd med levende Vande og Strømme fra Libanon!',
        16: 'Vaagn op, Nordenvind! og kom, Søndenvind! blæs igennem min Have, at dens Vellugt maa brede sig ud; min elskede komme i sin Have og æde sine kostelige Frugter!',
    },
    5: {
        1: 'Jeg er kommen, min Søster, o Brud! i min Have, jeg har plukket min Myrra tillige med min duftende Urt, jeg har ædt min Honningkage tillige med min Honning, jeg har drukket min Vin tillige med min Mælk; æder, I Venner! drikker og bliver drukne, I elskelige!',
        2: 'Jeg sov, men mit Hjerte vaagede. Min elskedes Røst! Han banker: Luk op for mig, min Søster! min Veninde! min Due! min rene! thi mit Hoved er fuldt af Dug, mine Lokker af Nattens Draaber. —',
        3: 'Jeg har afført mig min Kjortel; hvorledes skal jeg iføre mig den igen? jeg har toet mine Fødder; hvorledes skal jeg gøre dem urene igen?',
        4: 'Min elskede stak sin Haand igennem Aabningen, og mit Indre blev heftigt bevæget for hans Skyld.',
        5: 'Da stod jeg op for at lukke op for min elskede; og mine Hænder dryppede med Myrra og mine Fingre med flydende Myrra over Haandfangene paa Laasen.',
        6: 'Jeg lukkede op for min elskede, men min elskede havde vendt sig bort, han var gaaet forbi; jeg var gaaet ud af mig selv, da han talte; jeg ledte efter ham, men fandt ham ikke; jeg kaldte ad ham, men han svarede mig ikke.',
        7: 'Vægterne, som gaa omkring i Staden, fandt mig, de sloge mig, de saarede mig; Vægterne paa Murene toge mit Slør fra mig.',
        8: 'Jeg besværger eder, I Jerusalems Døtre! om I finde min elskede, hvad skulle I forkynde ham? At jeg er syg af Kærlighed.',
        9: 'Hvad er din elskede fremfor en andens elskede, du dejligste iblandt Kvinderne? hvad er din elskede fremfor en andens elskede, at du har saaledes besvoret os?',
        10: 'Min elskede er hvid og rød, udmærket fremfor ti Tusinde.',
        11: 'Hans Hoved er fineste Guld; hans Lokker ere krusede, sorte som Ravnen.',
        12: 'Hans Øjne ere som Duer ved Vandbække, badende sig i Mælk, siddende ved fulde Strømme.',
        13: 'Hans Kinder ere som duftende Blomsterbede, Taarne af vellugtende Urter; hans Læber ere som Lillier, der dryppe med flydende Myrra;',
        14: 'hans Hænder ere Guldringe, besatte med Krysoliter; hans Bug er skinnende Elfenben, belagt med Safirer;',
        15: 'hans Ben ere Marmorstøtter, grundfæstede i Fodstykker af Guld; hans Skikkelse er som Libanon, udvalgt som Cedertræerne;',
        16: 'hans Gane er Sødhed, og han er lutter Yndighed; dette er min elskede, og dette er min Ven, I Jerusalems Døtre!',
    },
    6: {
        1: 'Hvor er din elskede hengangen, du dejligste iblandt Kvinderne? hvor har din elskede vendt sig hen? saa ville vi opsøge ham med dig.',
        2: 'Min elskede er nedgangen i sin Have, til de duftende Blomsterbede for at vogte Hjorden i Haverne og at sanke Lillier.',
        3: 'Jeg er min elskedes, og min elskede er min, han, som vogter Hjorden iblandt Lillierne.',
        4: 'Du, min Veninde! er skøn som Tirza, yndig som Jerusalem, forfærdelig som Hære under Banner.',
        5: 'Vend dine Øjne bort fra mig, thi de gøre mig heftig; dit Haar er som en Gedehjord, der kommer op fra Gilead.',
        6: 'Dine Tænder ere som en Faarehjord, som kommer op af Svømmestedet, som alle sammen føde Tvillinger, og blandt hvilke intet er ufrugtbart.',
        7: 'Dine Tindinger ere som et Stykke af Granatæble imellem dine Lokker.',
        8: 'Der er tresindstyve Dronninger og firsindstyve Medhustruer og utallige Jomfruer.',
        9: 'Een er min Due, min fuldkomne, hun er sin Moders eneste, hun er ren for den, som hende fødte; Døtre saa hende og priste hende lykkelig, Dronninger og Medhustruer, og roste hende.',
        10: 'Hvo er hun, der titter frem som Morgenrøden, dejlig som Maanen, ren som Solen, forfærdelig som Hære under Banner?',
        11: 'Jeg var nedgangen i Nøddehaven at se, hvor det grønnedes i Dalen, at se, om Vintræet havde skudt, om Granattræerne havde blomstret.',
        12: 'Førend jeg vidste det, gjorde min Sjæl mig som mit ædle Folks Vogne.',
        13: 'Vend om, vend om, Sulamith! vend om, vend om, at vi maa se paa dig. Hvad ville I se paa Sulamith? Hun er som Dansen i Mahanaim.',
    },
    7: {
        1: 'Hvor skønne ere dine Trin i Skoene, du ædelbaarne! dine Lænders Bøjninger ere som Smykker, Værk af Kunstnerhaand.',
        2: 'Din Navle er det runde Bæger, — det mangler aldrig krydret Vin, din Bug er en Hvededynge, omhegnet med Lillier.',
        3: 'Dine to Bryster ere ligesom to unge Raatvillinger.',
        4: 'Din Hals er som Elfenbenstaarnet, dine Øjne ere Fiskedamme i Hesbon ved Bath-Rabbins Port, din Næse er som Libanons Taarn, der skuer ud imod Damaskus.',
        5: 'Dit Hoved paa dig er som Karmel, og Haaret paa dit Hoved er som Purpur; Kongen er fængslet i Lokkerne.',
        6: 'Hvor dejlig og hvor yndig er du, o kære! i Elskelighed.',
        7: 'Denne din ranke Vækst er ligt et Palmetræ og dine Bryster som Drueklaser.',
        8: 'Jeg sagde: Jeg vil stige op i Palmetræet, jeg vil tage fat paa dets Grene; og dine Bryster vorde som Vinstokkens Drueklaser og din Næses Aande som Æblerne;',
        9: 'og din Gane som den gode Vin, der gaar glat ned for min elskede og bringer sovendes Læber til at tale.',
        10: 'Jeg er min elskedes, og til mig er hans Attraa.',
        11: 'Kom, min elskede! lader os gaa ud paa Marken, lader os blive Natten over i Landsbyerne!',
        12: 'Lader os aarle gaa til Vingaardene, lader os se, om Vinstokken har skudt, om Blomsterne ere udsprungne, og om Granattræerne blomstre; der vil jeg skænke dig min Kærlighed.',
        13: 'Dudaim give Lugt, og ved vore Døre er der alle Haande kostelige Frugter, nye og gamle; o, min elskede! jeg har gemt dem til dig.',
    },
    8: {
        1: 'Gid du var mig som en Broder, som den, der diede min Moders Bryst! jeg skulde finde dig paa Gaden, jeg skulde kysse dig; og de skulde ikke foragte mig.',
        2: 'Jeg vilde lede dig, jeg vilde føre dig til min Moders Hus, du skulde lære mig; jeg skulde give dig af krydret Vin at drikke, af mit Granattræs Most.',
        3: 'Hans venstre Haand er under mit Hoved, og hans højre Haand omfavner mig.',
        4: 'Jeg besværger eder, I Jerusalems Døtre! hvi ville I vække, og hvi ville I forstyrre den kære, førend hun har Lyst dertil?',
        5: 'Hvo er hun, som drager op af Ørken, støttende sig til sin elskede? Jeg vækkede dig under Æbletræet; der fødte din Moder dig, der fødte hun, som bar dig.',
        6: 'Sæt mig som et Segl paa dit Hjerte, som et Segl paa din Arm; thi Kærlighed er stærk som Døden, Nidkærhed er haard som Dødsriget, dens Gløder ere brændende Gløder, en Herrens Lue.',
        7: "Mange Vande kunne ikke slukke Kærligheden, ej heller Strømme overskylle den; om nogen vilde give alt sit Hus's Gods for Kærlighed, man vilde dog foragte ham.",
        8: 'Vi have en liden Søster, og hun har ikke Bryster; hvad skulle vi gøre ved vor Søster paa den Dag, da der bejles til hende?',
        9: 'Dersom hun er en Mur, da ville vi bygge et Hus af Sølv over hende; og dersom hun er en Dør, da ville vi lukke for hende med Cederfjæle.',
        10: 'Jeg er en Mur, og mine Bryster ere som Taarne. Da blev jeg i hans Øjne som hun, der finder Fred.',
        11: 'Salomo havde en Vingaard i Baal-Hamon; han overgav Vingaarden til Vogterne, at enhver af dem skulde bringe ham for dens Frugt tusinde Sekel Sølv.',
        12: 'Min Vingaard, som hører mig til, er for mit Ansigt; de tusinde tilkomme dig, Salomo! men de to Hundrede dem, som vogte dens Frugt.',
        13: 'O du, som bor i Haverne! Medbrødre agte paa din Røst; lad mig høre den!',
        14: 'Fly min elskede! og vær lig en Raa eller en ung Hind paa de duftende Urters Bjerge.',
    },
}
