NAME = 'KLV: Klingon Language Version of the World English Bible'
BOOK = 'Hosea'

CHAPTERS = {
    1: {
        1: "The mu' vo' joH'a' vetlh ghoSta' Daq Hosea the puqloD vo' Beeri, Daq the jajmey vo' Uzziah, Jotham, Ahaz, je Hezekiah, joHpu' vo' Judah, je Daq the jajmey vo' Jeroboam the puqloD vo' Joash, joH vo' Israel.",
        2: "ghorgh joH'a' jatlhta' Daq wa'Dich Sum Hosea, joH'a' ja'ta' Daq Hosea, “jaH, tlhap vaD SoH'egh a be'nal vo' prostitution je puqpu' vo' unfaithfulness; vaD the puH commits Dun voqHa'moHlu', forsaking joH'a'.”",
        3: "vaj ghaH mejta' je tlhapta' Gomer the puqbe' vo' Diblaim; je ghaH conceived, je boghmoH ghaH a puqloD.",
        4: "joH'a' ja'ta' Daq ghaH, “ja' Daj pong Jezreel; vaD yet a mach qaStaHvIS, je jIH DichDaq bortaS the 'Iw vo' Jezreel Daq the tuq vo' Jehu, je DichDaq cause the kingdom vo' the tuq vo' Israel Daq mev.",
        5: "'oH DichDaq qaS Daq vetlh jaj vetlh jIH DichDaq ghor the bow vo' Israel Daq the ngech vo' Jezreel.”",
        6: "ghaH conceived again, je boghmoH a puqbe'. vaj ghaH ja'ta' Daq ghaH, “ja' Daj pong Lo-Ruhamah { Note: Lo-Ruhamah means “ghobe' loved.” }; vaD jIH DichDaq ghobe' longer ghaj pung Daq the tuq vo' Israel, vetlh jIH should Daq vay' way pardon chaH.",
        7: "'ach jIH DichDaq ghaj pung Daq the tuq vo' Judah, je DichDaq toD chaH Sum joH'a' chaj joH'a', je DichDaq ghobe' toD chaH Sum bow, 'etlh, may', horses, joq horsemen.”",
        8: "DaH ghorgh ghaH ghajta' weaned Lo-Ruhamah, ghaH conceived, je boghmoH a puqloD.",
        9: "ghaH ja'ta', “ja' Daj pong Lo-Ammi { Note: Lo-Ammi means “ghobe' wIj ghotpu” }; vaD SoH 'oH ghobe' wIj ghotpu, je jIH DichDaq ghobe' taH yours.",
        10: "Yet the mI' vo' the puqpu' vo' Israel DichDaq taH as the sand vo' the biQ'a', nuq ta'laHbe' taH juvta' ghobe' toghta'; je 'oH DichDaq ghoS Daq juS vetlh, Daq the Daq nuqDaq 'oH ghaHta' ja'ta' Daq chaH, ‘SoH 'oH ghobe' wIj ghotpu,' chaH DichDaq taH ja' ‘puqloDpu' vo' the yIntaH joH'a'.'",
        11: "The puqpu' vo' Judah je the puqpu' vo' Israel DichDaq taH boSta' tay', je chaH DichDaq appoint themselves wa' nach, je DichDaq jaH Dung vo' the puH; vaD Dun DichDaq taH the jaj vo' Jezreel.",
    },
    2: {
        1: "“jatlh Daq lIj loDnI'pu', ‘wIj ghotpu!' { Note: ‘Ammi' Daq Hebrew } je Daq lIj sisters, ‘wIj loved wa'!' { Note: ‘Ruhamah' Daq Hebrew }",
        2: "Contend tlhej lIj SoS! Contend, vaD ghaH ghaH ghobe' wIj be'nal, ghobe' 'oH jIH Daj loDnal; je chaw' Daj lan DoH Daj prostitution vo' Daj qab, je Daj adulteries vo' joj Daj breasts;",
        3: "Lest jIH strip Daj naked, je chenmoH Daj bare as Daq the jaj vetlh ghaH ghaHta' bogh, je chenmoH Daj rur a ngem, je cher Daj rur a dry puH, je HoH Daj tlhej thirst.",
        4: "Indeed, Daq Daj puqpu' jIH DichDaq ghaj ghobe' pung; vaD chaH 'oH puqpu' vo' unfaithfulness;",
        5: "vaD chaj SoS ghajtaH played the naybe'wI'. ghaH 'Iv conceived chaH ghajtaH ta'pu' shamefully; vaD ghaH ja'ta', ‘jIH DichDaq jaH after wIj lovers, 'Iv nob jIH wIj tIr Soj je wIj bIQ, wIj wool je wIj flax, wIj Hergh je wIj tlhutlh.'",
        6: "vaj, yIlegh, jIH DichDaq hedge Dung lIj way tlhej thorns, je jIH DichDaq chen a reD Daq Daj, vetlh ghaH ta'laHbe' tu' Daj way.",
        7: "ghaH DichDaq tlha' after Daj lovers, 'ach ghaH won't overtake chaH; je ghaH DichDaq nej chaH, 'ach won't tu' chaH. vaj ghaH DichDaq jatlh, ‘jIH DichDaq jaH je chegh Daq wIj wa'Dich loDnal; vaD vaj ghaHta' 'oH better tlhej jIH than DaH.'",
        8: "vaD ghaH ta'ta' ghobe' Sov vetlh jIH nobta' Daj the grain, the chu' HIq, je the Hergh, je multiplied Daq Daj baS chIS je SuD baS, nuq chaH used vaD Baal.",
        9: "vaj jIH DichDaq tlhap DoH wIj grain Daq its poH, je wIj chu' HIq Daq its season, je DichDaq pluck DoH wIj wool je wIj flax nuq should ghaj covered Daj nakedness.",
        10: "DaH jIH DichDaq uncover Daj lewdness Daq the leghpu' vo' Daj lovers, je ghobe' wa' DichDaq toD Daj pa' vo' wIj ghop.",
        11: "jIH DichDaq je cause Hoch Daj celebrations Daq mev: Daj yupma'mey, Daj chu' maSmey, Daj Sabbaths, je Hoch Daj Sagh yejmey.",
        12: "jIH DichDaq lay waste Daj vines je Daj fig Sormey, about nuq ghaH ghajtaH ja'ta', ‘Dochvammey 'oH wIj wages vetlh wIj lovers ghaj nobpu' jIH; je jIH DichDaq chenmoH chaH a forest,' je the Ha'DIbaH vo' the yotlh DIchDaq Sop chaH.",
        13: "jIH DichDaq visit Daq Daj the jajmey vo' the Baals, Daq nuq ghaH meQpu' He', ghorgh ghaH decked herself tlhej Daj earrings je Daj jewels, je mejta' after Daj lovers, je forgot jIH,” jatlhtaH joH'a'.",
        14: '“vaj, yIlegh, jIH DichDaq allure Daj, je qem Daj Daq the ngem, je jatlh tenderly Daq Daj.',
        15: "jIH DichDaq nob Daj vineyards vo' pa', je the ngech vo' Achor vaD a lojmIt vo' tul; je ghaH DichDaq respond pa', as Daq the jajmey vo' Daj youth, je as Daq the jaj ghorgh ghaH ghoSta' Dung pa' vo' the puH vo' Egypt.",
        16: "'oH DichDaq taH Daq vetlh jaj,” jatlhtaH joH'a', “vetlh SoH DichDaq ja' jIH ‘wIj loDnal,' je ghobe' longer ja' jIH ‘wIj pIn.'",
        17: "vaD jIH DichDaq tlhap DoH the pongmey vo' the Baals pa' vo' Daj nujDu', je chaH DichDaq ghobe' longer taH mentioned Sum pong.",
        18: "Daq vetlh jaj jIH DichDaq chenmoH a lay' vaD chaH tlhej the Ha'DIbaH vo' the yotlh, je tlhej the toQmey vo' the sky, je tlhej the creeping Dochmey vo' the yav. jIH DichDaq ghor the bow, the 'etlh, je the may' pa' vo' the puH, je DichDaq chenmoH chaH Qot bIng safely.",
        19: "jIH DichDaq betroth SoH Daq jIH reH. HIja', jIH DichDaq betroth SoH Daq jIH Daq QaQtaHghach, Daq ruv, Daq muSHa'taH pung, je Daq compassion.",
        20: "jIH DichDaq 'ach betroth SoH Daq jIH Daq voqtaHghach; je SoH DIchDaq Sov joH'a'.",
        21: "'oH DichDaq qaS Daq vetlh jaj, jIH DichDaq respond,” jatlhtaH joH'a', “jIH DichDaq respond Daq the chal, je chaH DichDaq respond Daq the tera';",
        22: "je the tera' DichDaq respond Daq the grain, je the chu' HIq, je the Hergh; je chaH DichDaq respond Daq Jezreel.",
        23: "jIH DichDaq sow Daj Daq jIH Daq the tera'; je jIH DichDaq ghaj pung Daq Daj 'Iv ghajta' ghobe' obtained pung; je jIH DichDaq ja' chaH 'Iv were ghobe' wIj ghotpu, ‘SoH 'oH wIj ghotpu;' je chaH DichDaq jatlh, ‘wIj joH'a'!'”",
    },
    3: {
        1: "joH'a' ja'ta' Daq jIH, “jaH again, muSHa' a be' loved Sum another, je an be' voqHa'moH, 'ach as joH'a' muSHa'taH the puqpu' vo' Israel, 'a' chaH tlhe' Daq latlh Qunpu', je muSHa' cakes vo' raisins.”",
        2: "vaj jIH je'ta' Daj vaD jIH'egh vaD fifteen pieces vo' baS chIS je a homer { Note: 1 homer ghaH about 220 litres joq 6 bushels } je a bID vo' barley.",
        3: "jIH ja'ta' Daq Daj, “SoH DIchDaq stay tlhej jIH law' jajmey. SoH DIchDaq ghobe' play the naybe'wI', je SoH DIchDaq ghobe' taH tlhej vay' latlh loD. jIH DichDaq je taH vaj toward SoH.”",
        4: "vaD the puqpu' vo' Israel DIchDaq abide law' jajmey Hutlh joH, je Hutlh joHHom, je Hutlh sacrifice, je Hutlh sacred nagh, je Hutlh ephod joq idols.",
        5: "Afterward the puqpu' vo' Israel DIchDaq chegh, je nej joH'a' chaj joH'a', je David chaj joH, je DIchDaq ghoS tlhej trembling Daq joH'a' je Daq Daj blessings Daq the last jajmey.",
    },
    4: {
        1: "Qoy the mu' vo' joH'a', SoH puqpu' vo' Israel; vaD joH'a' ghajtaH a yov Daq the nganpu' vo' the puH: “Indeed pa' ghaH ghobe' vIt, ghobe' QaQ, ghobe' Sov vo' joH'a' Daq the puH.",
        2: "pa' ghaH cursing, lying, chot, stealing, je committing voqHa'moHlu'; chaH ghor veHmey, je bloodshed causes bloodshed.",
        3: "vaj the puH DichDaq mourn, je Hoch 'Iv yIntaH therein DichDaq waste DoH. Hoch yIntaH Dochmey Daq Daj, 'ach the Ha'DIbaH vo' the yotlh je the toQmey vo' the sky; HIja', the fish vo' the biQ'a' je Hegh.",
        4: "“Yet chaw' ghobe' loD qem a yov, ghobe' chaw' vay' loD accuse; vaD lIj ghotpu 'oH rur chaH 'Iv qem charges Daq a lalDan vumwI'.",
        5: "SoH DichDaq stumble Daq the jaj, je the leghwI'pu' DichDaq je stumble tlhej SoH Daq the ram; je jIH DichDaq Qaw' lIj SoS.",
        6: "wIj ghotpu 'oH Qaw'ta' vaD Hutlh vo' Sov. Because SoH ghaj rejected Sov, jIH DichDaq je reject SoH, vetlh SoH may taH ghobe' lalDan vumwI' Daq jIH. Because SoH ghaj forgotten lIj joH'a' chut, jIH DichDaq je forget lIj puqpu'.",
        7: "As chaH were multiplied, vaj chaH yempu' Daq jIH. jIH DichDaq change chaj batlh Daq tuH.",
        8: "chaH feed Daq the yem vo' wIj ghotpu, je cher chaj tIq Daq chaj He'taHghach.",
        9: "'oH DichDaq taH, rur ghotpu, rur lalDan vumwI'; je jIH DichDaq punish chaH vaD chaj Hemey, je DichDaq repay chaH vaD chaj deeds.",
        10: "chaH DichDaq Sop, je ghobe' ghaj yap. chaH DichDaq play the naybe'wI', je DichDaq ghobe' increase; because chaH ghaj abandoned giving Daq joH'a'.",
        11: "Prostitution, HIq, je chu' HIq tlhap DoH yajtaHghach.",
        12: "wIj ghotpu consult tlhej chaj wooden idol, je jang Daq a stick vo' wood. Indeed the qa' vo' prostitution ghajtaH led chaH astray, je chaH ghaj taH unfaithful Daq chaj joH'a'.",
        13: "chaH sacrifice Daq the tops vo' the Hudmey, je meQ He' Daq the hills, bIng Sor'a'mey je poplars je terebinths, because its shade ghaH QaQ. vaj lIj puqbe'pu' play the naybe'wI', je lIj brides commit voqHa'moHlu'.",
        14: "jIH DichDaq ghobe' punish lIj puqbe'pu' ghorgh chaH play the naybe'wI', ghobe' lIj brides ghorgh chaH commit voqHa'moHlu'; because the loDpu' consort tlhej prostitutes, je chaH sacrifice tlhej the shrine prostitutes; vaj the ghotpu Hutlh yajtaHghach DichDaq ghoS Daq ruin.",
        15: "“'a' SoH, Israel, play the naybe'wI', yet yImev chaw' Judah offend; je yImev ghoS Daq Gilgal, ghobe' jaH Dung Daq Beth Aven, ghobe' swear, ‘As joH'a' yIn.'",
        16: "vaD Israel ghajtaH behaved extremely stubbornly, rur a stubborn heifer. vaj chay' DichDaq joH'a' feed chaH rur a lamb Daq a meadow.",
        17: 'Ephraim ghaH joined Daq idols. mej ghaH mob!',
        18: "chaj tlhutlh ghajtaH moj wIb. chaH play the naybe'wI' continually. Daj DevwIpu' dearly muSHa' chaj shameful way.",
        19: "The SuS ghajtaH wrapped Daj Dung Daq its telDu'; je chaH DIchDaq taH disappointed because vo' chaj nobmey.",
    },
    5: {
        1: "“'Ij Daq vam, SoH lalDan vumwI'pu'! 'Ij, tuq vo' Israel, je nob qogh, tuq vo' the joH! vaD the yoj ghaH Daq SoH; vaD SoH ghaj taH a tojta'ghach Daq Mizpah, je a net ngeH Daq Tabor.",
        2: "The rebels 'oH deep Daq HoHqu'; 'ach jIH discipline Hoch vo' chaH.",
        3: "jIH Sov Ephraim, je Israel ghaH ghobe' hidden vo' jIH; vaD DaH, Ephraim, SoH ghaj played the naybe'wI'. Israel ghaH defiled.",
        4: "chaj deeds won't allow chaH Daq tlhe' Daq chaj joH'a'; vaD the qa' vo' prostitution ghaH within chaH, je chaH yImev Sov joH'a'.",
        5: "The pride vo' Israel testifies Daq Daj qab. vaj Israel je Ephraim DichDaq stumble Daq chaj He'taHghach. Judah je DichDaq stumble tlhej chaH.",
        6: "chaH DichDaq jaH tlhej chaj flocks je tlhej chaj herds Daq nej joH'a'; 'ach chaH won't tu' ghaH. ghaH ghajtaH withdrawn himself vo' chaH.",
        7: "chaH 'oH unfaithful Daq joH'a'; vaD chaH ghaj borne illegitimate puqpu'. DaH the chu' maS DichDaq Sop chaH tlhej chaj fields.",
        8: "“Blow the cornet Daq Gibeah, je the trumpet Daq Ramah! wab a may' SaQ Daq Beth Aven, behind SoH, Benjamin!",
        9: "Ephraim DichDaq moj a desolation Daq the jaj vo' rebuke. Among the tuqpu' vo' Israel, jIH ghaj chenmoHta' Sovta' vetlh nuq DichDaq DIch taH.",
        10: "The joHHom vo' Judah 'oH rur chaH 'Iv teq a landmark. jIH DichDaq pour pa' wIj QeHpu' Daq chaH rur bIQ.",
        11: "Ephraim ghaH Suvta', ghaH ghaH crushed Daq yoj; Because ghaH ghaH intent Daq Daj pursuit vo' idols.",
        12: "vaj jIH 'oH Daq Ephraim rur a moth, je Daq the tuq vo' Judah rur rottenness.",
        13: "“ghorgh Ephraim leghta' Daj sickness, je Judah Daj wound, vaj Ephraim mejta' Daq Assyria, je ngeHta' Daq joH Jareb: 'ach ghaH ghaH ghobe' laH Daq heal SoH, ghobe' DichDaq ghaH cure SoH vo' lIj wound.",
        14: "vaD jIH DichDaq taH Daq Ephraim rur a HaDI'baH, je rur a Qup HaDI'baH Daq the tuq vo' Judah. jIH jIH'egh DichDaq tear Daq pieces je jaH DoH. jIH DichDaq carry litHa', je pa' DichDaq taH ghobe' wa' Daq toD.",
        15: 'jIH DichDaq jaH je chegh Daq wIj Daq, until chaH acknowledge chaj offense, je nej wIj qab. Daq chaj affliction chaH DichDaq nej jIH earnestly.”',
    },
    6: {
        1: "“ghoS, je chaw' maH chegh Daq joH'a'; vaD ghaH ghajtaH torn maH Daq pieces, je ghaH DichDaq heal maH; ghaH ghajtaH injured maH, je ghaH DichDaq bind Dung maj QIDpu'ghachmey.",
        2: "After cha' jajmey ghaH DichDaq revive maH. Daq the wejDIch jaj ghaH DichDaq raise maH Dung, je maH DichDaq yIn qaSpa' ghaH.",
        3: "chaw' maH acknowledge joH'a'. chaw' maH press Daq Daq Sov joH'a'. As DIch as the pemHov rises, joH'a' DichDaq nargh. ghaH DichDaq ghoS Daq maH rur the rain, rur the spring rain vetlh bIQmey the tera'.”",
        4: "“Ephraim, nuq DIchDaq jIH ta' Daq SoH? Judah, nuq DIchDaq jIH ta' Daq SoH? vaD lIj muSHa' ghaH rur a po cloud, je rur the dew vetlh disappears early.",
        5: "vaj jIH ghaj pe' chaH Daq pieces tlhej the leghwI'pu'; jIH HoHta' chaH tlhej the mu'mey vo' wIj nujDu'. lIj judgments 'oH rur a flash vo' lightning.",
        6: "vaD jIH neH pung, je ghobe' sacrifice; je the Sov vo' joH'a' latlh than meQqu'pu' nobmey.",
        7: "'ach chaH, rur Adam, ghaj ghorta' the lay'. chaH were unfaithful Daq jIH, pa'.",
        8: "Gilead ghaH a veng vo' chaH 'Iv vum He'taHghach; 'oH ghaH stained tlhej 'Iw.",
        9: "As gangs vo' robbers loS Daq ambush a loD, vaj the company vo' lalDan vumwI'pu' chot Daq the way toward Shechem, committing shameful crimes.",
        10: "Daq the tuq vo' Israel jIH ghaj leghpu' a horrible Doch. pa' ghaH prostitution Daq Ephraim. Israel ghaH defiled.",
        11: "“je, Judah, pa' ghaH a harvest wIv vaD SoH, ghorgh jIH nobHa' the fortunes vo' wIj ghotpu.",
    },
    7: {
        1: "ghorgh jIH would heal Israel, vaj the He'taHghach vo' Ephraim ghaH uncovered, je the mIghtaHghach vo' Samaria; vaD chaH commit falsehood, je the thief enters Daq, je the gang vo' robbers ravages outside.",
        2: "chaH yImev qel Daq chaj tIQDu' vetlh jIH qaw Hoch chaj mIghtaHghach. DaH chaj ghaj deeds ghaj engulfed chaH. chaH 'oH qaSpa' wIj qab.",
        3: "chaH chenmoH the joH Quchqu' tlhej chaj mIghtaHghach, je the joHHom tlhej chaj lies.",
        4: "chaH 'oH Hoch voqHa'moHwI'pu'. chaH 'oH burning rur an oven vetlh the vutwI' stops stirring, vo' the kneading vo' the dough, until 'oH ghaH leavened.",
        5: "Daq the jaj vo' maj joH, the joHHom chenmoHta' themselves rop tlhej the heat vo' HIq. ghaH joined Daj ghop tlhej mockers.",
        6: "vaD chaH ghaj chenmoHta' ready chaj tIq rur an oven, qaStaHvIS chaH Qot Daq loS. chaj vutwI' QongtaH Hoch the ram. Daq the po 'oH burns as a flaming qul.",
        7: "chaH 'oH Hoch hot as an oven, je Sop chaj judges. Hoch chaj joHpu' ghaj fallen. pa' ghaH ghobe' wa' among chaH 'Iv calls Daq jIH.",
        8: "Ephraim, ghaH mixes himself among the tuqpu'. Ephraim ghaH a pancake ghobe' tlhe'ta' Dung.",
        9: "novpu' ghaj Soppu' Daj HoS, je ghaH ta'be' realize 'oH. Indeed, gray jIb 'oH naDev je pa' Daq ghaH, je ghaH ta'be' realize 'oH.",
        10: "The pride vo' Israel testifies Daq Daj qab; yet chaH ghajbe' cheghta' Daq joH'a' chaj joH'a', ghobe' nejta' ghaH, vaD Hoch vam.",
        11: "“Ephraim ghaH rur an easily deceived dove, Hutlh yajtaHghach. chaH ja' Daq Egypt. chaH jaH Daq Assyria.",
        12: "ghorgh chaH jaH, jIH DichDaq ngeH wIj net Daq chaH. jIH DichDaq qem chaH bIng rur the toQmey vo' the sky. jIH DichDaq chastise chaH, as chaj tay' ghotpu' ghajtaH Qoyta'.",
        13: "Woe Daq chaH! vaD chaH ghaj wandered vo' jIH. QIH Daq chaH! vaD chaH ghaj trespassed Daq jIH. 'a' jIH would redeem chaH, yet chaH ghaj jatlhpu' lies Daq jIH.",
        14: "chaH ghajbe' SaQta' Daq jIH tlhej chaj tIq, 'ach chaH howl Daq chaj beds. chaH assemble themselves vaD grain je chu' HIq. chaH tlhe' DoH vo' jIH.",
        15: "'a' jIH ghaj taught je strengthened chaj arms, yet chaH plot mIghtaHghach Daq jIH.",
        16: "chaH chegh, 'ach ghobe' Daq the HochHom jen. chaH 'oH rur a faulty bow. chaj joHHom DichDaq pum Sum the 'etlh vaD the rage vo' chaj jat. vam DichDaq taH chaj derision Daq the puH vo' Egypt.",
    },
    8: {
        1: "“lan the trumpet Daq lIj wuSDu'! Something rur an eagle ghaH Dung joH'a' tuq, because chaH ghaj ghorta' wIj lay', je lotlhpu' Daq wIj chut.",
        2: "chaH SaQ Daq jIH, ‘wIj joH'a', maH Israel acknowledge SoH!'",
        3: "Israel ghajtaH chuH litHa' vetlh nuq ghaH QaQ. The jagh DichDaq pursue ghaH.",
        4: "chaH ghaj cher Dung joHpu', 'ach ghobe' Sum jIH. chaH ghaj chenmoHta' joHHom, je jIH ta'be' approve. vo' chaj baS chIS je chaj SuD baS chaH ghaj chenmoHta' themselves idols, vetlh chaH may taH pe' litHa'.",
        5: "chaw' Samaria throw pa' Daj calf idol! wIj QeH burns Daq chaH! chay' tIq DichDaq 'oH taH until chaH 'oH capable vo' purity?",
        6: "vaD vam ghaH 'ach vo' Israel! The workman chenmoHta' 'oH, je 'oH ghaH ghobe' joH'a'; indeed, the calf vo' Samaria DIchDaq taH ghorta' Daq pieces.",
        7: "vaD chaH sow the SuS, je chaH DichDaq reap the whirlwind. ghaH ghajtaH ghobe' standing grain. The stalk DichDaq yield ghobe' nach. chugh 'oH ta'taH yield, novpu' DichDaq swallow 'oH Dung.",
        8: "Israel ghaH swallowed Dung. DaH chaH 'oH among the tuqpu' rur a worthless Doch.",
        9: "vaD chaH ghaj ghoSta' Dung Daq Assyria, rur a wild SarghHom wandering mob. Ephraim ghajtaH hired lovers vaD himself.",
        10: "'ach although chaH sold themselves among the tuqpu', jIH DichDaq DaH tay'moH chaH; je chaH begin Daq waste DoH because vo' the oppression vo' the joH vo' HoS ones.",
        11: "Because Ephraim ghajtaH multiplied altars vaD yemtaH, chaH mojta' vaD ghaH altars vaD yemtaH.",
        12: "jIH wrote vaD ghaH the chut' Dochmey vo' wIj law; 'ach chaH were regarded as a strange Doch.",
        13: "As vaD the nobmey vo' wIj nobmey, chaH sacrifice ghab je Sop 'oH; 'ach joH'a' ta'be' accept chaH. DaH ghaH DichDaq qaw chaj He'taHghach, je punish chaj yemmey. chaH DichDaq chegh Daq Egypt.",
        14: "vaD Israel ghajtaH forgotten Daj Maker je chenta' palaces; je Judah ghajtaH multiplied fortified vengmey; 'ach jIH DichDaq ngeH a qul Daq Daj vengmey, je 'oH DichDaq Sop its fortresses.”",
    },
    9: {
        1: "yImev yItIv, Israel, Daq jubilation rur the tuqpu'; vaD SoH were unfaithful Daq lIj joH'a'. SoH muSHa' the wages vo' a naybe'wI' Daq Hoch grain threshing floor.",
        2: "The threshing floor je the winepress won't feed chaH, je the chu' HIq DichDaq fail Daj.",
        3: "chaH won't yIn Daq joH'a' puH; 'ach Ephraim DichDaq chegh Daq Egypt, je chaH DichDaq Sop Say'Ha' Soj Daq Assyria.",
        4: "chaH won't pour pa' HIq nobmey Daq joH'a', ghobe' DichDaq chaH taH pleasing Daq ghaH. chaj nobmey DichDaq taH Daq chaH rur the tIr Soj vo' mourners; Hoch 'Iv Sop vo' 'oH DichDaq taH polluted; vaD chaj tIr Soj DichDaq taH vaD chaj appetite. 'oH DichDaq ghobe' ghoS Daq the tuq vo' joH'a'.",
        5: "nuq DichDaq SoH ta' Daq the jaj vo' Sagh yej, je Daq the jaj vo' the 'uQ'a' vo' joH'a'?",
        6: "vaD, yIlegh, chaH ghaj ghoSta' DoH vo' QIH. Egypt DichDaq tay'moH chaH Dung. Memphis DichDaq bury chaH. Nettles DichDaq ghaj chaj bel Dochmey vo' baS chIS. Thorns DichDaq taH Daq chaj tents.",
        7: "The jajmey vo' visitation ghaj ghoS. The jajmey vo' reckoning ghaj ghoS. Israel DichDaq qel the leghwI'pu' Daq taH a fool, je the loD 'Iv ghaH inspired Daq taH insane, because vo' the abundance vo' lIj yemmey, je because lIj hostility ghaH Dun.",
        8: "A leghwI'pu' watches Dung Ephraim tlhej wIj joH'a'. A fowler's tojta'ghach ghaH Daq Hoch vo' Daj Hemey, je hostility Daq the tuq vo' Daj joH'a'.",
        9: "chaH ghaj deeply corrupted themselves, as Daq the jajmey vo' Gibeah. ghaH DichDaq qaw chaj He'taHghach. ghaH DichDaq punish chaH vaD chaj yemmey.",
        10: "jIH tu'ta' Israel rur grapes Daq the ngem. jIH leghta' lIj vavpu' as the wa'Dich ripe Daq the fig Sor Daq its wa'Dich season; 'ach chaH ghoSta' Daq Baal Peor, je consecrated themselves Daq the shameful Doch, je mojta' abominable rur vetlh nuq chaH loved.",
        11: "As vaD Ephraim, chaj batlh DichDaq puv DoH rur a toQ. pa' DichDaq taH ghobe' birth, pagh tlhej puq, je ghobe' conception.",
        12: "'a' chaH qem Dung chaj puqpu', yet jIH DichDaq bereave chaH, vaj vetlh ghobe' a loD DIchDaq taH poS. Indeed, woe je Daq chaH ghorgh jIH mej vo' chaH!",
        13: "jIH ghaj leghpu' Ephraim, rur Tyre, planted Daq a bel Daq; 'ach Ephraim DichDaq qem pa' Daj puqpu' Daq the chotwI'.",
        14: "nob chaH— joH'a' nuq DichDaq SoH nob? nob chaH a miscarrying womb je dry breasts.",
        15: "“Hoch chaj mIghtaHghach ghaH Daq Gilgal; vaD pa' jIH hated chaH. Because vo' the mIghtaHghach vo' chaj deeds jIH DichDaq drive chaH pa' vo' wIj tuq! jIH DichDaq muSHa' chaH ghobe' latlh. Hoch chaj joHHom 'oH rebels.",
        16: "Ephraim ghaH struck. chaj root ghajtaH dried Dung. chaH DichDaq SIQ ghobe' baQ. 'ach 'a' chaH qem vo', yet jIH DichDaq HoH the parmaqqay ones vo' chaj womb.”",
        17: "wIj joH'a' DichDaq chuH chaH DoH, because chaH ta'ta' ghobe' 'Ij Daq ghaH; je chaH DichDaq taH wanderers among the tuqpu'.",
    },
    10: {
        1: "Israel ghaH a luxuriant vine vetlh puts vo' Daj baQ. According Daq the abundance vo' Daj baQ ghaH ghajtaH multiplied Daj altars. As chaj puH ghajtaH chepta', chaH ghaj adorned chaj sacred naghmey.",
        2: "chaj tIq ghaH divided. DaH chaH DichDaq taH tu'ta' guilty. ghaH DichDaq demolish chaj altars. ghaH DichDaq Qaw' chaj sacred naghmey.",
        3: "DIch DaH chaH DichDaq jatlh, “maH ghaj ghobe' joH; vaD maH yImev taHvIp joH'a'; je the joH, nuq laH ghaH ta' vaD maH?”",
        4: "chaH chenmoH promises, swearing falsely Daq making covenants. vaj yoj springs Dung rur poisonous weeds Daq the furrows vo' the yotlh.",
        5: "The nganpu' vo' Samaria DichDaq taH Daq ghIjvIptaH vaD the calves vo' Beth Aven; vaD its ghotpu DichDaq mourn Dung 'oH, Along tlhej its lalDan vumwI'pu' 'Iv rejoiced Dung 'oH, vaD its batlh, because 'oH ghajtaH departed vo' 'oH.",
        6: "'oH je DichDaq taH qengta' Daq Assyria vaD a present Daq a Dun joH. Ephraim DichDaq Hev tuH, je Israel DichDaq taH tuH vo' Daj ghaj qeS.",
        7: 'Samaria je Daj joH float DoH, rur a twig Daq the bIQ.',
        8: "The jen Daqmey je vo' Aven, the yem vo' Israel, DichDaq taH Qaw'ta'. The thorn je the thistle DichDaq ghoS Dung Daq chaj altars. chaH DichDaq ja' the Hudmey, “So' maH!” je the hills, “pum Daq maH!”",
        9: "“Israel, SoH ghaj yempu' vo' the jajmey vo' Gibeah. pa' chaH remained. The may' Daq the puqpu' vo' He'taHghach ta'be' overtake chaH Daq Gibeah.",
        10: "ghorgh 'oH ghaH wIj neH, jIH DichDaq chastise chaH; je the tuqpu' DichDaq taH boSta' Daq chaH, ghorgh chaH 'oH bagh Daq chaj cha' transgressions.",
        11: "Ephraim ghaH a trained heifer vetlh muSHa'taH Daq thresh; vaj jIH DichDaq lan a yoke Daq Daj 'IH neck. jIH DichDaq cher a rider Daq Ephraim. Judah DichDaq plow. Jacob DichDaq ghor Daj clods.",
        12: "Sow Daq tlhIH'egh Daq QaQtaHghach, reap according Daq pung. ghor Dung lIj fallow yav; vaD 'oH ghaH poH Daq nej joH'a', until ghaH choltaH je rains QaQtaHghach Daq SoH.",
        13: "SoH ghaj plowed mIghtaHghach. SoH ghaj reaped He'taHghach. SoH ghaj eaten the baQ vo' lies, vaD SoH trusted Daq lIj way, Daq the qevmey vo' lIj HoS loDpu'.",
        14: "vaj a may' roar DichDaq Hu' among lIj ghotpu, je Hoch lIj fortresses DichDaq taH Qaw'ta', as Shalman Qaw'ta' Beth Arbel Daq the jaj vo' may'. The SoS ghaHta' dashed Daq pieces tlhej Daj puqpu'.",
        15: "vaj Bethel DichDaq ta' Daq SoH because vo' lIj Dun mIghtaHghach. Daq daybreak the joH vo' Israel DichDaq taH Qaw'ta'.",
    },
    11: {
        1: "“ghorgh Israel ghaHta' a puq, vaj jIH loved ghaH, je ja' wIj puqloD pa' vo' Egypt.",
        2: "chaH ja' Daq chaH, vaj chaH mejta' vo' chaH. chaH sacrificed Daq the Baals, je meQpu' He' Daq engraved images.",
        3: "Yet jIH taught Ephraim Daq yIt. jIH tlhapta' chaH Sum Daj arms; 'ach chaH ta'be' Sov vetlh jIH healed chaH.",
        4: "jIH drew chaH tlhej cords vo' a loD, tlhej ties vo' muSHa'; je jIH ghaHta' Daq chaH rur chaH 'Iv lift Dung the yoke Daq chaj necks; je jIH SIHta'bogh bIng Daq ghaH je jIH Sopta' ghaH.",
        5: "“chaH won't chegh Daq the puH vo' Egypt; 'ach the Assyrian DichDaq taH chaj joH, because chaH refused Daq repent.",
        6: "The 'etlh DichDaq pum Daq chaj vengmey, je DichDaq Qaw' the bars vo' chaj lojmItmey, je DichDaq lan an pItlh Daq chaj plans.",
        7: "wIj ghotpu 'oH determined Daq tlhe' vo' jIH. 'a' chaH ja' Daq the HochHom jen, ghaH certainly won't exalt chaH.",
        8: "“chay' laH jIH nob SoH Dung, Ephraim? chay' laH jIH ghop SoH Dung, Israel? chay' laH jIH chenmoH SoH rur Admah? chay' laH jIH chenmoH SoH rur Zeboiim? wIj tIq ghaH tlhe'ta' within jIH, wIj compassion ghaH aroused.",
        9: "jIH DichDaq ghobe' execute the fierceness vo' wIj QeH. jIH DichDaq ghobe' chegh Daq Qaw' Ephraim: vaD jIH 'oH joH'a', je ghobe' loD; the le' wa' Daq the midst vo' SoH; je jIH DichDaq ghobe' ghoS Daq QeHpu'.",
        10: "chaH DichDaq yIt after joH'a', 'Iv DichDaq roar rur a HaDI'baH; vaD ghaH DichDaq roar, je the puqpu' DichDaq ghoS trembling vo' the pemHov 'et.",
        11: "chaH DichDaq ghoS trembling rur a toQ pa' vo' Egypt, je rur a dove pa' vo' the puH vo' Assyria; je jIH DichDaq settle chaH Daq chaj juHmey,” jatlhtaH joH'a'.",
        12: "Ephraim surrounds jIH tlhej falsehood, je the tuq vo' Israel tlhej deceit. Judah vIHHa' strays vo' joH'a', je ghaH unfaithful Daq the le' wa'.",
    },
    12: {
        1: "Ephraim feeds Daq SuS, je chases the pemHov 'o' SuS. ghaH continually multiplies lies je desolation. chaH chenmoH a lay' tlhej Assyria, je Hergh ghaH qengta' Daq Egypt.",
        2: "joH'a' je ghajtaH a controversy tlhej Judah, je DichDaq punish Jacob according Daq Daj Hemey; according Daq Daj deeds ghaH DichDaq repay ghaH.",
        3: "Daq the womb ghaH tlhapta' Daj loDnI' Sum the heel; je Daq Daj manhood ghaH contended tlhej joH'a'.",
        4: "Indeed, ghaH struggled tlhej the Duy, je prevailed; ghaH wept, je chenmoHta' supplication Daq ghaH. ghaH tu'ta' ghaH Daq Bethel, je pa' ghaH jatlhta' tlhej maH,",
        5: "'ach joH'a', the joH'a' vo' Armies; joH'a' ghaH Daj pong vo' renown!",
        6: "vaj tlhe' Daq lIj joH'a'. pol pung je ruv, je loS continually vaD lIj joH'a'.",
        7: "A merchant ghajtaH dishonest scales Daq Daj ghop. ghaH muSHa'taH Daq defraud.",
        8: "Ephraim ja'ta', “DIch jIH ghaj moj rich, jIH ghaj tu'ta' jIH'egh wealth. Daq Hoch wIj wealth chaH won't tu' Daq jIH vay' He'taHghach vetlh ghaH yem.”",
        9: "“'ach jIH 'oH joH'a' lIj joH'a' vo' the puH vo' Egypt. jIH DichDaq yet again chenmoH SoH yIn Daq tents, as Daq the jajmey vo' the Sagh 'uQ'a'.",
        10: "jIH ghaj je jatlhpu' Daq the leghwI'pu', je jIH ghaj multiplied visions; je Sum the ministry vo' the leghwI'pu' jIH ghaj used parables.",
        11: "chugh Gilead ghaH mIgh, DIch chaH 'oH worthless. Daq Gilgal chaH sacrifice Qa'mey. Indeed, chaj altars 'oH rur heaps Daq the furrows vo' the yotlh.",
        12: "Jacob Haw'ta' Daq the Hatlh vo' Aram, je Israel served Daq tlhap a be'nal, je vaD a be'nal ghaH tended flocks je herds.",
        13: "Sum a leghwI'pu' joH'a' qempu' Israel Dung pa' vo' Egypt, je Sum a leghwI'pu' ghaH ghaHta' polta'.",
        14: "Ephraim ghajtaH bitterly provoked QeH. vaj Daj 'Iw DichDaq taH poS Daq ghaH, je Daj joH DichDaq repay Daj contempt.",
    },
    13: {
        1: "ghorgh Ephraim jatlhta', pa' ghaHta' trembling. ghaH exalted himself Daq Israel, 'ach ghorgh ghaH mojta' guilty Daq Baal, ghaH Heghta'.",
        2: "DaH chaH yem latlh je latlh, je ghaj chenmoHta' themselves molten images vo' chaj baS chIS, 'ach idols according Daq chaj ghaj yajtaHghach, Hoch vo' chaH the vum vo' the craftsmen. chaH jatlh vo' chaH, ‘chaH nob human sacrifice je kiss the calves.'",
        3: "vaj chaH DichDaq taH rur the po mist, je rur the dew vetlh passes DoH early, rur the yub vetlh ghaH driven tlhej the whirlwind pa' vo' the threshing floor, je rur the tlhIch pa' vo' the chimney.",
        4: "“Yet jIH 'oH joH'a' lIj joH'a' vo' the puH vo' Egypt; je SoH DIchDaq acknowledge ghobe' joH'a' 'ach jIH, je je jIH pa' ghaH ghobe' toDwI'.",
        5: "jIH knew SoH Daq the ngem, Daq the puH vo' Dun drought.",
        6: "According Daq chaj tI yotlh, vaj were chaH tebta'; chaH were tebta', je chaj tIq ghaHta' exalted. vaj chaH ghaj forgotten jIH.",
        7: "vaj jIH 'oH rur a HaDI'baH Daq chaH. rur a leopard, jIH DichDaq lurk Sum the path.",
        8: "jIH DichDaq ghom chaH rur a SIQ vetlh ghaH bereaved vo' Daj cubs, je DichDaq tear the covering vo' chaj tIq. pa' jIH DichDaq Sop chaH rur a lioness. The wild animal DichDaq tear chaH.",
        9: "SoH 'oH Qaw'ta', Israel, because SoH 'oH Daq jIH, Daq lIj QaH.",
        10: "nuqDaq ghaH lIj joH DaH, vetlh ghaH may toD SoH Daq Hoch lIj vengmey? je lIj judges, vo' 'Iv SoH ja'ta', ‘nob jIH a joH je joHHom?'",
        11: "jIH ghaj nobpu' SoH a joH Daq wIj QeH, je ghaj tlhappu' ghaH DoH Daq wIj QeHpu'.",
        12: "The guilt vo' Ephraim ghaH stored Dung. Daj yem ghaH stored Dung.",
        13: "The QoSqu'ghachmey vo' a travailing be' DichDaq ghoS Daq ghaH. ghaH ghaH an valHa' puqloD; vaD ghorgh 'oH ghaH poH, ghaH ta'be' ghoS Daq the opening vo' the womb.",
        14: "jIH DichDaq ransom chaH vo' the HoS vo' Sheol { Note: Sheol ghaH the Daq vo' the Heghpu'. }. jIH DichDaq redeem chaH vo' Hegh! Hegh, nuqDaq 'oH lIj plagues? Sheol, nuqDaq ghaH lIj QIH? “Compassion DichDaq taH hidden vo' wIj mInDu'.",
        15: "'a' ghaH ghaH fruitful among Daj loDnI'pu', an pemHov 'o' SuS DichDaq ghoS, the breath vo' joH'a' choltaH Dung vo' the ngem; je Daj spring DichDaq moj dry, je Daj fountain DichDaq taH dried Dung. ghaH DichDaq plunder the storehouse vo' treasure.",
        16: "Samaria DichDaq SIQ Daj guilt; vaD ghaH ghajtaH lotlhpu' Daq Daj joH'a'. chaH DichDaq pum Sum the 'etlh. chaj infants DichDaq taH dashed Daq pieces, je chaj pregnant taH'pu' DichDaq be ripped poSmoH.”",
    },
    14: {
        1: "Israel, chegh Daq joH'a' lIj joH'a'; vaD SoH ghaj fallen because vo' lIj yem.",
        2: "tlhap mu'mey tlhej SoH, je chegh Daq joH'a'. ja' ghaH, “Forgive Hoch maj yemmey, je accept vetlh nuq ghaH QaQ: vaj maH nob maj wuSDu' rur Qa'mey.",
        3: "Assyria ta'laHbe' toD maH. maH won't ride Daq horses; ghobe' DichDaq maH jatlh vay' latlh Daq the vum vo' maj ghopmey, ‘maj Qunpu'!' vaD Daq SoH the vav ghajbe' finds pung.”",
        4: "“jIH DichDaq heal chaj waywardness. jIH DichDaq muSHa' chaH freely; vaD wIj QeH ghaH tlhe'ta' DoH vo' ghaH.",
        5: 'jIH DichDaq taH rur the dew Daq Israel. ghaH DichDaq blossom rur the lily, je ngeH bIng Daj roots rur Lebanon.',
        6: "Daj branches DichDaq ngeH, je Daj 'IhtaHghach DichDaq taH rur the olive Sor, je Daj fragrance rur Lebanon.",
        7: "loDpu' DichDaq yIn Daq Daj shade. chaH DichDaq revive rur the grain, je blossom rur the vine. chaj fragrance DichDaq taH rur the HIq vo' Lebanon.",
        8: "Ephraim, nuq ghaj jIH Daq ta' vay' latlh tlhej idols? jIH jang, je DichDaq tlhap care vo' ghaH. jIH 'oH rur a SuD fir Sor; vo' jIH lIj baQ ghaH tu'ta'.”",
        9: "'Iv ghaH val, vetlh ghaH may understand Dochvammey Dochmey? 'Iv ghaH prudent, vetlh ghaH may Sov chaH? vaD the Hemey vo' joH'a' 'oH nIH, je the QaQtaHghach yIt Daq chaH; 'ach the lotlhqu' stumble Daq chaH.",
    },
}
