NAME = 'KLV: Klingon Language Version of the World English Bible'
BOOK = 'II Peter'

CHAPTERS = {
    1: {
        1: "Simon Peter, a toy'wI' je apostle vo' Jesus Christ, Daq chaH 'Iv ghaj obtained a rur precious HartaHghach tlhej maH Daq the QaQtaHghach vo' maj joH'a' je toDwI', Jesus Christ:",
        2: "Grace Daq SoH je roj taH multiplied Daq the Sov vo' joH'a' je vo' Jesus maj joH,",
        3: "leghtaH vetlh Daj divine HoS ghajtaH granted Daq maH Hoch Dochmey vetlh pertain Daq yIn je godliness, vegh the Sov vo' ghaH 'Iv ja' maH Sum Daj ghaj batlh je virtue;",
        4: "Sum nuq ghaH ghajtaH granted Daq maH Daj precious je exceedingly Dun promises; vetlh vegh Dochvammey SoH may moj partakers vo' the divine nature, ghajtaH escaped vo' the corruption vetlh ghaH Daq the qo' Sum lust.",
        5: "HIja', je vaD vam very cause adding Daq lIj part Hoch diligence, Daq lIj HartaHghach supply moral excellence; je Daq moral excellence, Sov;",
        6: 'je Daq Sov, self-control; je Daq self-control patience; je Daq patience godliness;',
        7: "je Daq godliness brotherly affection; je Daq brotherly affection, muSHa'.",
        8: "vaD chugh Dochvammey Dochmey 'oH yours je abound, chaH chenmoH SoH Daq taH ghobe' idle ghobe' unfruitful Daq the Sov vo' maj joH Jesus Christ.",
        9: "vaD ghaH 'Iv lacks Dochvammey Dochmey ghaH blind, leghtaH neH nuq ghaH Sum, ghajtaH forgotten the cleansing vo' Daj qan yemmey.",
        10: "vaj, loDnI'pu', { Note: The mu' vaD “loDnI'pu'” naDev je nuqDaq context allows may je taH correctly translated “loDnI'pu' je sisters” joq “siblings.” } taH latlh diligent Daq chenmoH lIj ja'taH je election sure. vaD chugh SoH ta' Dochvammey Dochmey, SoH DichDaq never stumble.",
        11: "vaD thus SoH DichDaq taH richly supplied tlhej the entrance Daq the eternal Kingdom vo' maj joH je toDwI', Jesus Christ.",
        12: "vaj jIH DichDaq ghobe' taH negligent Daq remind SoH vo' Dochvammey Dochmey, 'a' SoH Sov chaH, je 'oH established Daq the present vIt.",
        13: "jIH think 'oH nIH, as tIq as jIH 'oH Daq vam juHHom, Daq stir SoH Dung Sum reminding SoH;",
        14: "knowing vetlh the putting litHa' vo' wIj juHHom choltaH swiftly, 'ach as maj joH Jesus Christ chenmoHta' clear Daq jIH.",
        15: "HIja', jIH DichDaq chenmoH Hoch effort vetlh SoH may always taH laH Daq qaw Dochvammey Dochmey 'ach after wIj departure.",
        16: "vaD maH ta'ta' ghobe' tlha' cunningly devised fables, ghorgh maH chenmoHta' Sovta' Daq SoH the HoS je choltaH vo' maj joH Jesus Christ, 'ach maH were eyewitnesses vo' Daj majesty.",
        17: "vaD ghaH Hevta' vo' joH'a' the vav quv je batlh, ghorgh the ghogh ghoSta' Daq ghaH vo' the Majestic batlh, “vam ghaH wIj parmaqqay puqloD, Daq 'Iv jIH 'oH QaQ pleased.” { Note: Matthew 17:5; Mark 9:7; Luke 9:35 }",
        18: "maH Qoyta' vam ghogh ghoS pa' vo' chal ghorgh maH were tlhej ghaH Daq the le' HuD.",
        19: "maH ghaj the latlh sure mu' vo' prophecy; je SoH ta' QaQ vetlh SoH heed 'oH, as Daq a lamp shining Daq a dark Daq, until the jaj dawns, je the po Hov arises Daq lIj tIQDu':",
        20: "knowing vam wa'Dich, vetlh ghobe' prophecy vo' Scripture ghaH vo' private interpretation.",
        21: "vaD ghobe' prophecy ever ghoSta' Sum the DichDaq vo' loD: 'ach le' loDpu' vo' joH'a' jatlhta', taH vIHta' Sum the le' qa'.",
    },
    2: {
        1: "'ach false leghwI'pu' je Hu' among the ghotpu, as false teachers DichDaq je taH among SoH, 'Iv DichDaq secretly qem Daq destructive heresies, denying 'ach the pIn 'Iv je'ta' chaH, bringing Daq themselves swift QIH.",
        2: "law' DichDaq tlha' chaj immoral { Note: TR reads “destructive” instead vo' “immoral” } Hemey, je as a result, the way vo' the vIt DichDaq taH maligned.",
        3: "Daq covetousness chaH DichDaq exploit SoH tlhej deceptive mu'mey: 'Iv sentence DaH vo' vo' qan ta'be' linger, je chaj QIH DichDaq ghobe' slumber.",
        4: "vaD chugh joH'a' ta'be' spare Duy''a'pu' ghorgh chaH yempu', 'ach chuH chaH bIng Daq Tartarus { Note: Tartarus ghaH another pong vaD Hell }, je committed chaH Daq pits vo' HurghtaHghach, Daq taH reserved vaD yoj;",
        5: "je ta'be' spare the ancient qo', 'ach polta' Noah tlhej Soch others, a preacher vo' QaQtaHghach, ghorgh ghaH qempu' a flood Daq the qo' vo' the ungodly;",
        6: "je turning the vengmey vo' Sodom je Gomorrah Daq ashes, condemned chaH Daq QIH, ghajtaH chenmoHta' chaH an example Daq chaH 'Iv would yIn ungodly;",
        7: "je toDta' QaQtaHghach Lot, 'Iv ghaHta' very distressed Sum the lustful yIn vo' the mIgh",
        8: "(vaD vetlh QaQtaHghach loD dwelling among chaH, ghaHta' tormented Daq Daj QaQtaHghach qa' vo' jaj Daq jaj tlhej leghtaH je hearing lawless deeds):",
        9: "the joH SovtaH chay' Daq toD the godly pa' vo' temptation je Daq pol the unrighteous bIng punishment vaD the jaj vo' yoj;",
        10: "'ach chiefly chaH 'Iv yIt after the ghab Daq the lust vo' defilement, je despise authority. Daring, self-willed, chaH 'oH ghobe' vIp Daq jatlh mIghtaHghach vo' dignitaries;",
        11: "whereas Duy''a'pu', 'a' greater Daq might je HoS, yImev qem a railing yoj Daq chaH qaSpa' the joH.",
        12: "'ach Dochvammey, as unreasoning creatures, bogh natural Ha'DIbaH Daq taH tlhappu' je Qaw'ta', speaking mIghtaHghach Daq matters about nuq chaH 'oH ignorant, DichDaq Daq chaj destroying DIch taH Qaw'ta',",
        13: "receiving the wages vo' unrighteousness; ghotpu 'Iv count 'oH pleasure Daq revel Daq the pem, spots je blemishes, reveling Daq chaj deceit qaStaHvIS chaH 'uQ'a' tlhej SoH;",
        14: "ghajtaH mInDu' teblu'ta' vo' voqHa'moHlu', je 'Iv ta'laHbe' mev vo' yem; enticing unsettled qa'pu'; ghajtaH a tIq trained Daq greed; puqpu' vo' cursing;",
        15: "forsaking the nIH way, chaH mejta' astray, ghajtaH tlha'ta' the way vo' Balaam the puqloD vo' Beor, 'Iv loved the wages vo' wrongdoing;",
        16: "'ach ghaH ghaHta' rebuked vaD Daj ghaj disobedience. A mute SarghHom jatlhta' tlhej a man's ghogh je stopped the madness vo' the leghwI'pu'.",
        17: "Dochvammey 'oH wells Hutlh bIQ, clouds driven Sum a storm; vaD 'Iv the blackness vo' HurghtaHghach ghajtaH taH reserved reH.",
        18: "vaD, uttering Dun swelling mu'mey vo' emptiness, chaH entice Daq the lusts vo' the ghab, Sum licentiousness, chaH 'Iv 'oH indeed escaping vo' chaH 'Iv yIn Daq error;",
        19: "promising chaH liberty, qaStaHvIS chaH themselves 'oH bondservants vo' corruption; vaD a loD ghaH qempu' Daq bondage Sum 'Iv overcomes ghaH.",
        20: "vaD chugh, after chaH ghaj escaped the defilement vo' the qo' vegh the Sov vo' the joH je toDwI' Jesus Christ, chaH 'oH again entangled Daq 'oH je overcome, the last state ghajtaH moj worse vaD chaH than the wa'Dich.",
        21: "vaD 'oH would taH better vaD chaH ghobe' Daq ghaj Sovta' the way vo' QaQtaHghach, than, after knowing 'oH, Daq tlhe' DoH vo' the le' ra'ta'ghach mu' toDta' Daq chaH.",
        22: "'ach 'oH ghajtaH qaSta' Daq chaH according Daq the true proverb, “The dog turns Daq Daj ghaj vomit again,” { Note: Proverbs 26:11 } je “the sow vetlh ghajtaH washed Daq wallowing Daq the mire.”",
    },
    3: {
        1: "vam ghaH DaH, parmaqqay, the cha'DIch letter vetlh jIH ghaj ghItlhta' Daq SoH; je Daq both vo' chaH jIH stir Dung lIj 'Il yab Sum reminding SoH;",
        2: "vetlh SoH should qaw the mu'mey nuq were jatlhpu' qaSpa' Sum the le' leghwI'pu', je the ra'ta'ghach mu'mey vo' maH, the apostles vo' the joH je toDwI':",
        3: "knowing vam wa'Dich, vetlh Daq the last jajmey mockers DichDaq ghoS, walking after chaj ghaj lusts,",
        4: "je ja'ta', “nuqDaq ghaH the promise vo' Daj choltaH? vaD, vo' the jaj vetlh the vavpu' pumta' asleep, Hoch Dochmey continue as chaH were vo' the tagh vo' the creation.”",
        5: "vaD vam chaH willfully forget, vetlh pa' were chal vo' vo' qan, je an tera' formed pa' vo' bIQ je amid bIQ, Sum the mu' vo' joH'a';",
        6: "Sum nuq means the qo' vetlh vaj ghaHta', taH overflowed tlhej bIQ, perished.",
        7: "'ach the chal vetlh DaH 'oH, je the tera', Sum the rap mu' ghaj taH stored Dung vaD qul, taH reserved Daq the jaj vo' yoj je QIH vo' ungodly loDpu'.",
        8: "'ach yImev forget vam wa' Doch, parmaqqay, vetlh wa' jaj ghaH tlhej the joH as a SaD DISmey, je a SaD DISmey as wa' jaj.",
        9: "The joH ghaH ghobe' slow concerning Daj promise, as 'op count slowness; 'ach ghaH patient tlhej maH, ghobe' wishing vetlh vay' should chIlqu', 'ach vetlh Hoch should ghoS Daq repentance.",
        10: "'ach the jaj vo' the joH DichDaq ghoS as a thief Daq the ram; Daq nuq the chal DichDaq juS DoH tlhej a Dun noise, je the elements DichDaq taH dissolved tlhej fervent heat, je the tera' je the vum vetlh 'oH Daq 'oH DichDaq taH meQpu' Dung.",
        11: "vaj since Hoch Dochvammey Dochmey DichDaq taH Qaw'ta' rur vam, nuq kind vo' ghotpu ought SoH Daq taH Daq le' yIntaH je godliness,",
        12: "leghtaH vaD je earnestly desiring the choltaH vo' the jaj vo' joH'a', nuq DichDaq cause the burning chal Daq taH dissolved, je the elements DichDaq melt tlhej fervent heat?",
        13: "'ach, according Daq Daj promise, maH legh vaD chu' chal je a chu' tera', Daq nuq QaQtaHghach yIntaH.",
        14: "vaj, parmaqqay, leghtaH vetlh SoH legh vaD Dochvammey Dochmey, taH diligent Daq taH tu'ta' Daq roj, Hutlh blemish je blameless Daq Daj leghpu'.",
        15: "Regard the patience vo' maj joH as toDtaHghach; 'ach as maj parmaqqay loDnI' Paul je, according Daq the valtaHghach nobpu' Daq ghaH, wrote Daq SoH;",
        16: "as je Daq Hoch vo' Daj letters, speaking Daq chaH vo' Dochvammey Dochmey. Daq chaH, pa' 'oH 'op Dochmey vetlh 'oH hard Daq understand, nuq the ignorant je unsettled twist, as chaH je ta' Daq the latlh Scriptures, Daq chaj ghaj QIH.",
        17: "SoH vaj, parmaqqay, knowing Dochvammey Dochmey qaSpa', beware, lest taH qengta' DoH tlhej the error vo' the mIgh, SoH pum vo' lIj ghaj steadfastness.",
        18: "'ach grow Daq the grace je Sov vo' maj joH je toDwI' Jesus Christ. Daq ghaH taH the batlh both DaH je reH. Amen.",
    },
}
