NAME = 'SweKarlXII1873: Svenska Karl XII:s Bibel (1873)'
BOOK = 'Mark'

CHAPTERS = {
    1: {
        1: 'Detta är begynnelsen af Jesu Christi, Guds Sons, Evangelio;',
        2: 'Såsom skrifvet är i Propheterna: Si, jag sänder min Ängel framför ditt ansigte, hvilken bereda skall din väg för dig;',
        3: 'Ens ropandes röst är i öknene: Bereder Herrans väg; görer hans stigar rätta.',
        4: 'Johannes var i öknene, döpte, och predikade bättringenes döpelse, till syndernas förlåtelse.',
        5: 'Och till honom gingo ut hela Judiska landet, och de utaf Jerusalem; och läto sig alle döpa af honom i Jordans flod, och bekände sina synder.',
        6: 'Och Johannes var klädd med camelahår, och med en lädergjording om sina länder; och åt gräshoppor och vildhannog;',
        7: 'Och predikade, och sade: En kommer efter mig, som starkare är än jag, hvilkens skotvänger jag icke värdig är att nederfalla och upplösa.',
        8: 'Jag döper eder med vatten; men han skall döpa eder med dem Helga Anda.',
        9: 'Och det begaf sig i de dagar, att Jesus kom utaf Galileen ifrå Nazareth, och lät sig döpa af Johanne i Jordan.',
        10: 'Och straxt steg han upp utu vattnet, och såg himlarna öppnas, och Andan, såsom en dufvo, nederkomma öfver honom.',
        11: 'Och en röst kom af himmelen: Du äst min käre Son, i hvilkom mig väl behagar.',
        12: 'Och Anden dref honom straxt uti öknena;',
        13: 'Och han var i öknene i fyratio dagar, och frestades af Satana; och var med vilddjuren; och Änglarna tjente honom.',
        14: 'Men sedan Johannes vardt fången, kom Jesus uti Galileen, och predikade Evangelium om Guds rike,',
        15: 'Sägandes: Tiden är fullkomnad, och Guds rike är för handene; bättrer eder, och tror Evangelio.',
        16: 'När han gick utmed det Galileiska hafvet, såg han Simon, och Andream, hans broder, kasta sin nät i hafvet; ty de voro fiskare.',
        17: 'Och Jesus sade till dem: Följer mig, och jag vill göra eder till menniskofiskare.',
        18: 'Straxt gåfvo de sin nät öfver, och följde honom.',
        19: 'Och då han gick dädan litet fram bätter, såg han Jacobum, Zebedei son, och Johannem, hans broder, att de i båtenom byggde sin nät.',
        20: 'Och straxt kallade han dem; då öfvergåfvo de sin fader, Zebedeum, uti båten, med legodrängarna, och följde honom.',
        21: 'Och de gingo till Capernaum; och straxt, om Sabbatherna, gick han in i Synagogon och lärde.',
        22: 'Och de förundrade storliga på hans lärdom; förty han lärde väldeliga, och icke såsom de Skriftlärde.',
        23: 'Och i deras Synagogo var en menniska besatt med den orena andan; och han ropade,',
        24: 'Och sade: Ack! hvad hafve vi med dig beställa, Jesu Nazarene? Äst du kommen till att förderfva oss? Jag vet ho du äst, nämliga den Guds Helige.',
        25: 'Och Jesus näpste honom, sägandes: Tig, och gack ut af menniskone.',
        26: 'Då ref den orene anden honom, och ropade högt, och for ut af honom.',
        27: 'Och alle förundrade sig svårliga, så att de sporde hvarannan till, och sade: Hvad är detta? Hvad ny lärdom är detta? Ty han bjuder de orena andar med väldighet, och de lyda honom.',
        28: 'Och hans rykte gick straxt allt omkring i Galilee gränsor.',
        29: 'Och de gingo straxt utu Synagogon, och kommo uti Simons och Andree hus, med Jacobo och Johanne.',
        30: 'Och Simons svära låg sjuk i skälfvo; och straxt sade de honom om henne.',
        31: 'Då gick han till och reste henne upp, och tog henne vid handena; och i det samma öfvergaf skälfvosjukan henne, och hon gick sedan och tjente dem.',
        32: 'Om aftonen, då solen nedergången var, hade de till honom allahanda sjuka, och dem som qvaldes af djeflar;',
        33: 'Och hele staden var församlad för dörrena.',
        34: 'Och han gjorde många helbregda, som kranke voro af allahanda sjukdom; och dref ut många djeflar, och tillstadde icke djeflarna tala; ty de kände honom.',
        35: 'Och om morgonen, ganska bittida för dag, stod han upp och gick ut; och Jesus gick bort uti ett öde rum, och der bad han.',
        36: 'Och Simon kom efter farandes, och de med honom voro.',
        37: 'Och då de funno honom, sade de till honom: Alle söka dig.',
        38: 'Sade han dem: Låt oss gå uti nästa städerna, att jag ock der predikar; ty fördenskull är jag kommen.',
        39: 'Och han predikade i deras Synagogor, öfver hela Galileen, och utdref djeflar.',
        40: 'Och till honom kom en spitelsk man, och bad honom, föll på knä för honom, och sade till honom: Vill du, så kan du göra mig ren.',
        41: 'Då varkunnade sig Jesus öfver honom, och uträckte sina hand, och tog uppå honom, och sade: Jag vill, var ren.',
        42: 'Och när han det sagt hade, gick straxt spitelskan af honom, och han vardt ren.',
        43: 'Och Jesus hotade honom, och sänden straxt ifrå sig;',
        44: 'Och sade honom: Se till, att du säger ingom detta; utan gack bort, och visa dig Prestenom, och offra, för din rening, det Mose budit hafver, till ett vittnesbörd öfver dem.',
        45: 'Men då han utgången var, begynte han förkunna mycket, och berykta det som skedt var; så att han icke nu mer kunde uppenbarliga gå in uti staden, utan blef ute i öde rum; och de kommo till honom af alla ändar.',
    },
    2: {
        1: 'Och efter några dagar gick han åter in i Capernaum; och det spordes, att han var i huset.',
        2: 'Och straxt församlades der månge, så att de icke rum hade, icke heller utanför dörrene; och han hade tal för dem.',
        3: 'Och de hade fram för honom en borttagnan, den der framburen var af fyra.',
        4: 'Och då de icke kunde komma till honom, för folkets skull, refvo de taket på huset, der han var; och gjorde ett hål på taket, och med tåg släppte neder sängena, der den borttagne uti låg.',
        5: 'När Jesus såg deras tro, sade han till den borttagna: Min son, dina synder vare dig förlåtna.',
        6: 'Så voro der någre utaf de Skriftlärde sittande, som tänkte i sin hjerta:',
        7: 'Hvi talar denne sådana hädelse? Ho kan förlåta synder, utan allena Gud?',
        8: 'Och straxt Jesus förnam det i sinom anda, att de sådant tänkte vid sig sjelfva, sade han till dem: Hvi tänken I sådant i edor hjerta?',
        9: 'Hvilket är lättare säga till den borttagna: Dina synder vare dig förlåtna; eller säga: Statt upp, och tag dina säng och gack?',
        10: 'Men på det I skolen veta, att menniskones Son hafver magt på jordene förlåta synder, sade han till den borttagna:',
        11: 'Dig säger jag: Statt upp; tag dina säng, och gack i ditt hus.',
        12: 'Och straxt stod han upp, tog sina säng, och gick ut i allas deras åsyn; så att alle undrade storliga, och prisade Gud, sägande: Sådant såge vi aldrig.',
        13: 'Och han gick åter ut till hafvet; och allt folket kom till honom, och han lärde dem.',
        14: 'Och då Jesus gick der fram, såg han Levi, Alphei son, sittandes vid tullen, och sade till honom: Följ mig. Och han stod upp, och följde honom.',
        15: 'Och det begaf sig, då han satt till bords i hans hus, såto ock desslikes månge Publicaner och syndare till bords med Jesu och hans Lärjungar; ty de voro månge, som hade följt honom.',
        16: 'Och då de Skriftlärde och Phariseer sågo, att han åt med de Publicaner och syndare, sade de till hans Lärjungar: Hvi äter och dricker han med Publicaner och syndare?',
        17: 'När Jesus det hörde, sade han till dem: De der helbregda äro, behöfva icke läkare, utan de som kranke äro; jag är icke kommen till att kalla de rättfärdiga, utan syndare, till bättring.',
        18: 'Och Johannis lärjungar och de Phariseers fastade mycket; och de kommo, och sade till honom: Hvi fasta Johannis lärjungar och de Phariseers, och dine Lärjungar fasta intet?',
        19: 'Sade Jesus till dem: Bröllopsfolket, kunna de fasta, så länge brudgummen är med dem? Så länge de hafva brudgummen när sig, kunna de icke fasta.',
        20: 'Men de dagar skola komma, att brudgummen skall varda ifrå dem tagen; och då skola de fasta i de dagar.',
        21: 'Och ingen sömmar en klut af nytt kläde på gammalt kläde; förty han rifver dock det nya stycket ifrå det gamla, och hålet varder värre.',
        22: 'Och ingen låter nytt vin i gamla flaskor; annars slår det nya vinet flaskorna sönder, och vinet spilles ut, och flaskorna förderfvas; utan nytt vin skall man låta i nya flaskor.',
        23: 'Och det begaf sig, att han på Sabbathen gick genom säd; och hans Lärjungar begynte, vid de gingo, taga af axen.',
        24: 'Och de Phariseer sade till honom: Si, hvi göra de om Sabbathen det som icke lofligit är?',
        25: 'Då sade han till dem: Hafven I aldrig läsit, hvad David gjorde, då honom omträngde, och var hungrig, han och de der med honom voro?',
        26: 'Huru han gick in i Guds hus, under den öfversta Presten Abjathar, och åt skådobröden, hvilka ingom voro loflige äta, utan Prestomen; och gaf desslikes dem som med honom voro.',
        27: 'Och han sade till dem: Sabbathen är gjord för menniskones skull, och icke menniskan för Sabbathens skull.',
        28: 'Så är nu menniskones Son en Herre, desslikes ock öfver Sabbathen.',
    },
    3: {
        1: 'Och han gick åter in uti Synagogon; och der var en man, som hade ena bortvissnada hand.',
        2: 'Och de vaktade på honom, om han ock skulle bota honom om Sabbathen; på det att de skulle få anklaga honom.',
        3: 'Då sade han till mannen, som den vissna handen hade: Gack hitfram.',
        4: 'Och sade till dem: Hvilketdera är lofligit, göra väl om Sabbathen, eller göra illa; hjelpa lifvet, eller dräpa? Då tigde de.',
        5: 'Då såg han uppå dem med vrede, och förömkade sig öfver deras hjertas blindhet, och sade till mannen: Räck ut dina hand; och han räckte henne ut; och handen vardt honom färdig igen, såsom den andra.',
        6: 'Men de Phariseer gingo ut, och höllo straxt råd med de Herodianer, emot honom, huru de kunde förgöra honom.',
        7: 'Men Jesus, med sina Lärjungar, gick afsides bort till hafvet; och honom följde ett stort tal folk, utaf Galileen, och utaf Judeen;',
        8: 'Och utaf Jerusalem, och utaf Idumeen, och utaf hinsidon Jordan och de der bodde vid Tyrus och Sidon, en ganska stor hop folk, som kommo till honom, när de hörde af hans gerningar.',
        9: 'Och sade han till sina Lärjungar, att de skulle fly honom en båt, för folkets skull, att de icke skulle tränga honom.',
        10: 'Förty han gjorde många helbregda, så att de öfverföllo honom, och ville taga på honom, så månge som några plågo hade.',
        11: 'Och de orene andar, när de sågo honom, föllo de neder för honom, och ropade, sägande: Du äst Guds Son.',
        12: 'Och han hotade dem hårdeliga, att de icke skulle uppenbara honom.',
        13: 'Och han steg upp på ett berg, och kallade till sig hvilka han ville; och de kommo till honom.',
        14: 'Och då skickade han tolf, att de skulle vara med honom, och att han skulle utsända dem till att predika;',
        15: 'Och att de skulle hafva magt till att bota sjukdomar och utdrifva djeflar.',
        16: 'Och gaf Simon det namnet Petrus;',
        17: 'Och Jacobus, Zebedei son, Johannes, Jacobs broder, och nämnde dem Boanerges, det är sagdt: Tordönsbarn;',
        18: 'Och Andreas och Philippus, och Bartholomeus, och Mattheus, och Thomas, och Jacobus, Alphei son, och Thaddeus, och Simon Cananeus;',
        19: 'Och Judas Ischarioth, den honom ock förrådde.',
        20: 'Och de kommo i huset; och folket församlade sig åter, så att de icke tid hade till att äta.',
        21: 'Och när de detta hörde, som honom åkomne voro, gingo de ut, och ville taga fatt på honom, och sade: Han kommer ifrå sig.',
        22: 'Men de Skriftlärde, som af Jerusalem nederkomne voro, sade: Han hafver Beelzebub, och med den öfversta djefvulen drifver han djeflar ut.',
        23: 'Då kallade han dem till sig, och sade till dem i liknelser: Huru kan en Satan den andra utdrifva?',
        24: 'Och om ett rike söndradt varder emot sig sjelft, då kan det riket icke stå;',
        25: 'Och der ett hus är söndradt emot sig sjelft, det huset kan icke blifva ståndandes.',
        26: 'Sätter nu Satan sig upp emot sig sjelf, och är söndrad, då kan han icke blifva beståndandes, utan det är då ute med honom.',
        27: 'Ingen kan infalla uti en starks hus, och taga hans hustyg bort, utan han först binder den starka; och så skinnar han hans hus.',
        28: 'Sannerliga säger jag eder: Alla synder varda menniskors barnom förlåtna; ock försmädelse, dermed de försmäda;',
        29: 'Men den der försmäder den Heliga Anda, han hafver ingen förlåtelse i evig tid, utan blifver saker till evig fördömelse.',
        30: 'Ty de sade: Han hafver den orena andan.',
        31: 'Och då kommo hans bröder och hans moder, och stodo ute, och sände några till honom, som honom utkalla skulle.',
        32: 'Och folket satt när honom, och de sade till honom: Si, din moder och dine bröder äro derute, och söka efter dig.',
        33: 'Han svarade dem, och sade: Ho är min moder och mine bröder?',
        34: 'Och då han omkringsett hade på Lärjungarna, som der kringom honom såto, sade han: Si, min moder och mine bröder.',
        35: 'Ty den som gör Guds vilja, han är min broder, och min syster, och min moder.',
    },
    4: {
        1: 'Och han begynte åter lära vid hafvet; och till honom församlades mycket folk, så att han måste stiga uti ett skepp, och satt der på hafvet; och allt folket blef på landet vid hafvet.',
        2: 'Och han lärde dem mycket genom liknelser; och sade till dem uti sin predikan:',
        3: 'Hörer till: Si, en sädesman gick ut till att så.',
        4: 'Och hände sig, vid han sådde, föll somt vid vägen; och foglarna under himmelen kommo, och åto det upp.',
        5: 'Men somt föll på stenören, der icke mycken jord var; och det gick straxt upp, ty der var icke djup jord.',
        6: 'Men då solen gick upp, förvissnade det; och efter det var icke väl berotadt, förtorkades det.',
        7: 'Och somt föll i törne; och törnen växte upp, och förqvafde det; och det bar ingen frukt.',
        8: 'Och somt föll i goda jord, och det bar frukt, som uppgick, och växte; ett bar tretiofaldt, och ett sextiofaldt, och ett hundradefaldt.',
        9: 'Och han sade till dem: Den der öron hafver till att höra, han höre.',
        10: 'Då han nu allena var, sporde de, som med honom voro med de tolf, honom till om den liknelsen.',
        11: 'Och han sade till dem: Eder är gifvet att veta Guds rikes hemlighet; men dem der utantill äro sker all ting genom liknelser;',
        12: 'På det de skola med seende ögon se, och dock icke förnimmat; och med hörande öron höra, och dock icke förståt; på det de sig icke ens skola omvända, och synderna dem förlåtna varda.',
        13: 'Och han sade till dem: Förstån I icke denna liknelsen? Huru viljen I då förstå alla liknelser?',
        14: 'Sädesmannen sår ordet.',
        15: 'Men desse äro de som vid vägen äro, der ordet sådt varder; och de hafva det hört, straxt kommer Satan, och tager bort ordet, som sådt var i deras hjertan.',
        16: 'Alltså äro ock de som på stenören sådde äro; då de hafva hört ordet, anamma de det straxt med fröjd;',
        17: 'Och de hafva inga rötter i sig, utan stå till en tid; då någor bedröfvelse kommer uppå, eller förföljelse, för ordets skull, straxt förargas de.',
        18: 'Och desse äro de som i törne sådde äro; de der höra ordet;',
        19: 'Och denna verldenes omsorger, och de bedrägelige rikedomar, och mycken annor begärelse, gå derin, och förqväfva ordet, och det varder ofruktsamt.',
        20: 'Och desse äro de som uti goda jord sådde äro; de der ordet höra, och anammat, och bära frukt, somt tretiofaldt, och somt sextiofaldt, och somt hundradefaldt.',
        21: 'Och han sade till dem: Icke varder ett ljus upptändt fördenskull, att man skall sätta det under ena skäppo, eller under bordet? Sker det icke fördenskull, att det skall uppsättas på ljusastakan?',
        22: 'Ty intet är fördoldt, som icke uppenbaras skall; ej heller hemligit, som icke skall uppkomma.',
        23: 'Den der öron hafver till att höra, han höre.',
        24: 'Och han sade till dem: Ser till, hvad I hören: Med hvad mått I mälen, der skola andra mäla eder med; och eder varder ändå tillgifvet, I som hören detta.',
        25: 'Ty den der hafver, honom varder gifvet; och den der icke hafver, af honom skall ock taget varda det han hafver.',
        26: 'Och han sade: Så är Guds rike, som en man kastar ena säd i jordena;',
        27: 'Och sofver, och står upp, natt och dag; och säden går upp, och växer, så att han der intet af vet.',
        28: 'Ty jorden bär utaf sig sjelf, först brodd, sedan ax, sedan fullbordadt hvete i axena.',
        29: 'När nu frukten mogen är, straxt brukar han lian; ty skördetiden är för handen.',
        30: 'Och han sade: Vid hvem skole vi likna Guds rike? Och med hvad liknelse skole vi beteckna det?',
        31: 'Det är såsom ett senapskorn, hvilket, då det sådt varder i jordena, är det mindre än all annor frö på jordene;',
        32: 'Och då det sådt är, går det upp, och varder större än all annor krydder, och får stora grenar, så att foglarna under himmelen måga bo under dess skugga.',
        33: 'Och med mång sådana liknelser sade han dem ordet, efter som de förmådde hörat;',
        34: 'Och utan liknelse talade han intet till dem; men Lärjungomen uttydde han all ting afsides.',
        35: 'Och den samma dagen, då aftonen vardt, sade han till dem: Låt oss fara utöfver, på den andra stranden.',
        36: 'Så läto de folket gå, och togo honom, med skeppet der han redo uti var; voro ock desslikes någor annor skepp med honom.',
        37: 'Och der uppväxte en stor storm, och vågen slog in i skeppet, så att det förfylldes.',
        38: 'Och han sof bak i skeppet på ett hyende; då väckte de honom upp, och sade till honom: Mästar, sköter du intet derom, att vi förgås?',
        39: 'Och då han uppväckt var, näpste han vädret, och sade till hafvet: Tig, och var stilla. Och vädret saktade sig, och vardt ett stort lugn.',
        40: 'Och han sade till dem: Hvarföre ären I så rädde? Huru kommer det till, att I icke hafven trona?',
        41: 'Och de vordo ganska förskräckte, och sade emellan sig: Ho är denne? Ty vädret och hafvet äro honom lydig.',
    },
    5: {
        1: 'Så kommo de öfver hafvet, in i de Gadareners ängd.',
        2: 'Och straxt han steg utu skeppet, lopp emot honom, utu grifter, en man besatt med den orena andan;',
        3: 'Den der plägade bo uti grifter; och ingen kunde honom binda med kedjor.',
        4: 'Förty han hade många resor varit bunden med fjettrar och kedjor; och kedjorna voro sletna af honom, och fjettrarna sönderslagne; och ingen kunde späka honom.',
        5: 'Och han var alltid, dag och natt, på bergen, och i grifterna, ropade och slog sig sjelf med stenar.',
        6: 'Då han nu såg Jesum fjerran ifrå sig, lopp han till, och föll neder för honom.',
        7: 'Och ropade med höga röst, och sade: Hvad hafver jag med dig göra, Jesu, den högstas Guds Son? Jag besvär dig vid Gud, att du icke qväl mig.',
        8: 'Då sade han till honom: Far ut af menniskone, du orene ande.',
        9: 'Och sporde han honom: Hvad är ditt namn? Svarade han och sade: Legio är mitt namn; förty vi äre månge.',
        10: 'Och han bad honom storliga, att han icke skulle drifva honom bort utu den ängden.',
        11: 'Och der var vid bergen en stor svinahjord, den der gick och födde sig;',
        12: 'Och djeflarna bådo honom alle, sägande: Sänd oss i svinen, att vi må fara in uti dem.',
        13: 'Och Jesus tillstadde dem det straxt. Och de orene andar drogo straxt ut, och foro in uti svinen; och hjorden brådstörte sig i hafvet; och de voro vid tutusend, och vordo fördränkte i hafvet.',
        14: 'Men de, som skötte svinen, flydde och förkunnade det in i staden, och på bygdene; och de gingo ut till att se hvad skedt var;',
        15: 'Och kommo till Jesum, och sågo honom, som hade besatt varit, och haft legionen, sittandes kläddan, och vid sin skäl; och vordo förfärade.',
        16: 'Och de som det sett hade, förtäljde dem hvad den besatta vederfaret var, och om svinen.',
        17: 'Och de begynte bedja honom, att han skulle draga utu deras ängd.',
        18: 'Och då han var stigen till skepps, bad honom den som hade besatt varit, att han måtte vara när honom.',
        19: 'Men Jesus tillstadde det icke, utan sade till honom: Gack dina färde uti ditt hus till dina, och förkunna dem, huru stor ting Herren hafver gjort med dig, och hafver miskundat sig öfver dig.',
        20: 'Och han gick sina färde, och begynte förkunna uti de tio städer, huru stor ting Jesus med honom gjort hade. Och alle förundrade sig.',
        21: 'Och då Jesus var öfverfaren igen med skeppet, församlades till honom mycket folk; och var vid hafvet.',
        22: 'Och si, der kom en af Synagogones öfverstar, benämnd Jairus; och då han fick se honom, föll han ned för hans fötter;',
        23: 'Och bad honom storliga, och sade: Min dotter är i sitt yttersta; jag beder dig, att du kommer, och lägger händer på henne, att hon måtte vederfås, och lefva.',
        24: 'Och han gick med honom; och honom följde mycket folk, och de trängde honom.',
        25: 'Och der var en qvinna, som hade haft blodgång i tolf år.',
        26: 'Och hade mycket lidit af mångom läkarom, och förtärt dermed allt sitt, och hade dock ingen hjelp förnummit; utan det vardt heldre värre med henne.',
        27: 'Då hon hörde om Jesu, kom hon ibland folket bakefter, och tog på hans kläder;',
        28: 'Ty hon sade: Kunde jag åtminstone taga på hans kläder, då vorde jag helbregda.',
        29: 'Och straxt förtorkades hennes blods källa; och hon kände det i kroppen, att hon botad var utaf den plågon.',
        30: 'Och Jesus kändet straxt i sig sjelf, att kraft utgången var af honom; och vände sig om ibland folket, och sade: Ho kom vid min kläder?',
        31: 'Och hans Lärjungar sade till honom: Ser du icke, folket tränger dig på alla sidor, och du säger: Ho kom vid mig?',
        32: 'Och han såg omkring efter henne, som det gjort hade.',
        33: 'Men qvinnan fruktade och bäfvade; ty hon visste, hvad med henne skedt var; och kom, och föll neder för honom, och sade honom alla sanningena.',
        34: 'Då sade han till henne: Dotter, din tro hafver gjort dig helbregda; gack med frid, och var helbregda af dine plågo.',
        35: 'Vid han ännu talade, kommo någre ifrå Synagogones öfversta, och sade: Din dotter är död; hvi gör du Mästaren yttermera omak?',
        36: 'Men straxt Jesus hörde talet, som sades, sade han till Synagogones öfversta: Frukta dig intet; allenast tro.',
        37: 'Och han tillstadde icke, att honom någor följa skulle, förutan Petrus och Jacobus, och Johannes, Jacobi broder.',
        38: 'Och så kom han i Synagogones öfverstas hus, och fick se sorlet, och dem som mycket sörjde och greto.',
        39: 'Och han gick in, och sade till dem: Hvad sorlen I, och gråten? Pigan är icke död; men hon sofver.',
        40: 'Och de gjorde gäck af honom. Då dref han alla ut, och tog med sig pigones fader och moder, och dem som med honom voro, och gick in der pigan låg.',
        41: 'Och fattade pigona vid handena, sägande till henne: Talitha kumi; det uttydes: Piga, jag säger dig, statt upp.',
        42: 'Och straxt stod pigan upp, och gick; och hon var vid tolf år gammal. Och de vordo öfvermåtton förskräckte.',
        43: 'Och han förböd dem strängeliga, att ingen skulle det veta; och böd gifva henne äta.',
    },
    6: {
        1: 'Och han gick ut dädan, och kom in uti sitt fädernesland; och hans Lärjungar följde honom.',
        2: 'Och när Sabbathen kom, begynte han lära i Synagogon; och månge, som det hörde, förundrade sig storliga, sägande: Hvadan kommer honom detta? Och hvad visdom är denne, som honom gifven är, och sådana krafter, som ske igenom hans händer?',
        3: 'Är icke denne den timbermannen, Marie Son, Jacobi broder, och Jose, och Jude och Simons? Äro ock icke hans systrar här när oss? Och de förargades på honom.',
        4: 'Då sade Jesus till dem: En Prophet varder icke föraktad, utan i sitt fädernesland, och ibland sina fränder, och sitt folk.',
        5: 'Och han kunde der ingen kraft göra, utan det att han lade händerna på några få sjuka, och botade dem.',
        6: 'Och han förundrade sig på deras otro; och han gick omkring i byarna allestäds deromkring, och lärde.',
        7: 'Och han kallade för sig de tolf, tog till att utsända dem, två och två; gifvandes dem magt emot de orena andar;',
        8: 'Och böd dem, att de intet skulle taga med sig till vägs, utan käppen allena; icke skräppo, icke bröd, inga penningar i pungen;',
        9: 'Utan de skulle vara skodde; och att de icke skulle kläda sig uti två kjortlar;',
        10: 'Och sade till dem: Hvar som helst I ingån uti ett hus, blifven der, tilldess I dragen dädan.',
        11: 'Och hvilken som icke anammar eder, eller icke hörer eder, går derut, och skudder af eder det stoft, som är under edra fötter till vittnesbörd öfver dem. Sannerliga säger jag eder: Drägeligare varder Sodome och Gomorre på domedag, än dem stadenom.',
        12: 'Och de gingo ut, och predikade, att man skulle bättra sig;',
        13: 'Och utdrefvo många djeflar, och smorde många kranka med oljo, och botade dem.',
        14: 'Och fick Konung Herodes detta höra; ty hans namn var redo kunnigt; och sade: Den Johannes, som döpte, är uppstånden ifrå de döda; och derföre gör han sådana krafter.',
        15: 'Somlige sade: Det är Elias; och somlige sade: Det är en Prophet, eller såsom en af Propheterna.',
        16: 'Då Herodes sådant hörde, sade han: Denne är Johannes, som jag halshögg; han är uppstånden ifrå de döda.',
        17: 'Ty Herodes hade sändt bort, och låtit gripa Johannes, och satt honom i fängelse, för Herodias, sins broders Philippi hustrus skull; ty han hade tagit henne till hustru;',
        18: 'Men Johannes sade till Herodes: Dig är icke lofligit att hafva dins broders hustru.',
        19: 'Men Herodias gick efter hans argesta, och hade gerna dräpit honom; och kunde dock icke komma dess vid;',
        20: 'Ty Herodes fruktade Johannem, vetandes att han var en from och helig man; och aktade honom, och lydde honom i mång stycke, och hörde honom gerna.',
        21: 'Då nu en belägen dag kom, att Herodes på sin födelsedag gaf de öfversta, och höfvitsmän, och de yppersta i Galileen, en aftonkost;',
        22: 'Gick Herodias dotter in, och dansade, och det behagade Herodi, och dem der med honom såto vid bordet. Då sade Konungen till pigona: Bed utaf mig hvad du vill, jag vill gifva dig det;',
        23: 'Och svor henne en ed; Hvad du bedjande varder af mig, vill jag gifva dig, allt intill hälften af mitt rike.',
        24: 'Hon gick ut, och sade till sina moder: Hvad skall jag bedja? Hon sade: Johannis Döparens hufvud.',
        25: 'Och hon gick straxt med hast in till Konungen, och bad, sägandes: Jag vill, att du gifver mig nu straxt, på ett fat, Johannis Döparens hufvud.',
        26: 'Då vardt Konungen bedröfvad; dock, för edens skull, och för deras skull, som der såto vid bordet, ville han icke visa henne af;',
        27: 'Utan straxt sände Konungen bödelen, och böd inhemta hans hufvud. Han gick åstad, och halshögg honom i fångahuset;',
        28: 'Och bar fram hans hufvud på ett fat, och fick pigone; och pigan fick det sine moder.',
        29: 'Då hans lärjungar det sporde, kommo de, och togo hans lekamen upp, och begrofvo honom.',
        30: 'Och Apostlarna församlades till Jesum, och förkunnade honom all stycke; och hvad de gjort och lärt hade.',
        31: 'Då sade han till dem: Kommer I allene afsides med mig uti ödemarken, och hviler eder något litet; ty der voro månge, som gingo till och ifrå, så att de hade icke tid till att äta.',
        32: 'Och så for han bort afsides till skepps uti ödemarken.',
        33: 'Och folket såg, att de foro sina färde; och månge kände honom, och lupo dit tillsammans af alla städer, till fot, och kommo fram förr än de, och församlades till honom.',
        34: 'Så gick Jesus ut, och fick se det myckna folket, och varkunnade sig öfver dem; förty de voro såsom får, de ingen herdan hade; och begynte lära dem mycket.',
        35: 'Och då nu dagen var fast framliden, gingo hans Lärjungar till honom, och sade: Här är öknen, och tiden är fast förliden;',
        36: 'Släpp dem ifrå dig, att de måga gå bort i byarna och torpen här omkring, och köpa sig bröd; ty de hafva intet äta.',
        37: 'Då svarade han dem, och sade: Gifver I dem äta. Då sade de till honom: Skole vi gå bort, och köpa för tuhundrade penningar bröd, och gifva dem äta?',
        38: 'Då sade han till dem: Huru mång bröd hafven I? Går, och ser till. Och sedan de hade sett till, sade de: Fem, och två fiskar.',
        39: 'Då böd han dem, att de skulle sätta sig alle i matskap, i gröna gräset.',
        40: 'Och de satte sig i hopar, hundrade och hundrade, femtio och femtio.',
        41: 'Och så tog han de fem bröd och de två fiskar; och upplyfte sin ögon till himmelen, tackade, och bröt bröden, och fick sinom Lärjungom, att de skulle lägga för dem; och de två fiskar bytte han emellan dem alla.',
        42: 'Och de åto alle, och vordo mätte;',
        43: 'Och togo sedan upp tolf korgar fulla med styckom, och fiskomen.',
        44: 'Och de der ätit hade, voro vid femtusend män.',
        45: 'Och straxt dref han sina Lärjungar, att de skulle gå till skepps, och fara för honom öfver hafvet till Bethsaida, medan han skiljde folket ifrå sig.',
        46: 'Och när han hade skiljt dem ifrå sig, gick han dädan upp på ett berg, till att bedja.',
        47: 'Och då aftonen kom, var skeppet midt på hafvet, och han på landet allena.',
        48: 'Och han såg att de hade plats med roende; ty vädret var dem emot. Och vid fjerde väkten om nattena kom han till dem, gångandes på hafvet; och han ville gå framom dem.',
        49: 'Och när de sågo honom gångandes på hafvet, mente de det hade varit ett spökelse, och ropade;',
        50: 'Ty de sågo honom alle, och vordo förskräckte. Då talade han dem straxt till, och sade till dem: Varer vid en god tröst, jag äret; varer icke rädde.',
        51: 'Och han steg upp till dem i skeppet, och vädret stillade sig; och de vordo storliga förskräckte, förundrande vid sig sjelfva öfvermåtton.',
        52: 'Ty de hade icke fått förstånd af bröden; ty deras hjerta var förblindadt.',
        53: 'Och då de öfverfarne voro, kommo de till det landet Genesaret, och lade der i hamn.',
        54: 'Och när de gingo utu skeppet, kände de honom straxt;',
        55: 'Och lupo omkring allan den landsändan; och begynte omkringföra de sjuka på sängar, dit de hörde han var.',
        56: 'Och hvar han ingick, i byar, eller städer, eller torp, der lade de kranka på gatorna, och bådo honom, att de åtminstone måtte taga på hans klädefåll; och så månge, som kommo vid honom, de vordo helbregda.',
    },
    7: {
        1: 'Och till honom församlades de Phariseer, och någre af de Skriftlärda, som ifrå Jerusalem komne voro.',
        2: 'Och då de fingo se, att somlige hans Lärjungar åto bröd med menliga, det är, med otvagna händer, straffade de det;',
        3: 'Ty de Phariseer och alle Judar äta icke, utan de alltid två händerna, hållande de äldstas stadgar;',
        4: 'Och när de komne äro utaf torget, äta de icke, utan de äro tvagne. Och mycket sådant är, som de hafva tagit sig uppå att hålla, som är, att två dryckekar, och krukor, och kopparkar, och bord.',
        5: 'Sedan frågade honom de Phariseer och de Skriftlärde: Hvi vandra icke dine Lärjungar efter de stadgar, som de äldste uppåbudit hafva; utan äta bröd med otvagna händer?',
        6: 'Då svarade han, och sade till dem: Väl hafver Esaias propheterat om eder, I skrymtare, som skrifvet är: Detta folket ärar mig med läpparna; men deras hjerta är långt ifrå mig.',
        7: 'Men fåfängt dyrka de mig, lärande den lärdom, som är menniskors bud;',
        8: 'Ty I bortkasten Guds bud, och hållen menniskors stadgar, som är, att två krukor, och dryckekar; och mycket sådant gören I.',
        9: 'Och han sade till dem: Skönliga bortkasten I Guds bud, på det att I skolen hålla edar stadga.',
        10: 'Ty Mose hafver sagt: Ära din fader och dina moder; och: Den der bannar fader eller moder, han skall döden dö.',
        11: 'Men I sägen: En menniska må säga till fader och moder: Corban; det är sagdt: Gudi är det gifvet, som dig af mig skulle hafva kommit till nytto;',
        12: 'Och tillåten så icke, att han något gör sinom fader, eller sine moder;',
        13: 'Och gören Guds ord omintet med edar stadga, som I uppålagt hafven. Och mycket sådant gören I.',
        14: 'Och han kallade till sig allt folket, och sade till dem: Hörer mig alle, och förstår.',
        15: 'Intet går utanefter in i menniskona, det henne besmitta kan; men det som går utaf menniskone, det är det som besmittar menniskona.',
        16: 'Den der hafver öron till att höra, han höre.',
        17: 'Och då han skiljdes ifrå folket, och kom i huset, frågade hans Lärjungar honom om liknelsen.',
        18: 'Och han sade till dem: Ären I också oförståndige? Förstån I icke ännu, att allt det utanefter ingår i menniskona, det kan icke besmitta henne?',
        19: 'Ty det går icke in i hennes hjerta, utan i buken; och hafver sin naturliga utgång, der all mat med rensas.',
        20: 'Och han sade: Det utaf menniskone går, det besmittar menniskona;',
        21: 'Ty innanefter, utu menniskors hjerta, utgå onda tankar, hor, boleri, mandråp,',
        22: 'Stöld, girighet, svek, listighet, otuktighet, ondt öga, hädelse, högfärd, galenskap;',
        23: 'All denna onda stycke gå innanefter ut, och de besmitta menniskona.',
        24: 'Så stod han upp dädan, och gick in i Tyri och Sidons gränsor; och gick in uti ett hus, och ville att det ingen veta skulle; och kunde dock icke blifva fördold.',
        25: 'Ty en qvinna, hvilkens dotter hade en oren anda, straxt hon fick höra om honom, kom hon, och föll ned för hans fötter.',
        26: 'Och det var en Grekisk qvinna, utaf Syrophenice, och bad honom, att han ville utdrifva djefvulen af hennes dotter.',
        27: 'Men Jesus sade till henne: Låt barnen först mätta varda; det är icke höfveligit, att man tager barnens bröd och kastar för hundarna.',
        28: 'Då svarade hon, och sade till honom: Ja, Herre; dock äta hundarna, under bordet, utaf barnens smulor.',
        29: 'Då sade han till henne: För detta talets skull, gack; djefvulen är utgången af dine dotter.',
        30: 'Och då hon kom i sitt hus, fann hon djefvulen utgången vara, och dottrena liggande på sängene.',
        31: 'Och då han åter utgick ifrå Tyri och Sidons gränsor, kom han till det Galileiska hafvet, midt genom de landsändar vid de tio städer.',
        32: 'Och de hade fram för honom en döfvan, den der ock en dumbe var; och bådo honom, att han ville lägga handena på honom.',
        33: 'Då tog han honom afsides ut ifrå folket, och satte sina finger i hans öron, och spottade ut, dermed han tog på hans tungo;',
        34: 'Och såg upp i himmelen, suckade, och sade till honom: Hephethah; det är sagdt: Upplåt dig.',
        35: 'Och straxt öppnades hans öron, och hans tungos band vardt löst, och han talade redeliga.',
        36: 'Och böd han dem, att de skulle ingom sägat; men ju mer han det förböd, ju mer de förkunnade det.',
        37: 'Och de förundrade sig öfvermåtton, sägande: Allt hafver han väl beställt; de döfva låter han höra, och dumbar tala.',
    },
    8: {
        1: 'Uti de dagar, då folket var ganska mycket, och hade intet det de äta kunde, kallade Jesus till sig sina Lärjungar, och sade till dem:',
        2: 'Jag varkunnar mig öfver folket; ty de hafva nu i tre dagar töfvat när mig, och hafva intet äta;',
        3: 'Och om jag låter dem fastande gå hem, gifvas de upp i vägen; ty somlige utaf dem voro komne långväga.',
        4: 'Och hans Lärjungar svarade honom: Hvar tager man bröd här i öknene, der man dem med mätta kan?',
        5: 'Då sporde han dem: Huru mång bröd hafven I? Svarade de: Sju.',
        6: 'Och han böd folket sätta sig ned på jordena; och han tog de sju bröd, tackade, bröt, och gaf sina Lärjungar; att de skulle lägga dem fram; och de lade fram för folket.',
        7: 'Hade de ock några små fiskar; och då han välsignat hade, bad han ock lägga dem fram.',
        8: 'Så åto de, och vordo mätte; och de togo upp sju korgar med aflefvor, som öfver voro.',
        9: 'Och de der ätit hade, voro vid fyratusend; och så lät han fara dem.',
        10: 'Och straxt steg han till skepps med sina Lärjungar, och kom intill de landsändar Dalmanutha.',
        11: 'Och de Phariseer gingo ut, och begynte disputera med honom, frestande honom, och begärande af honom tecken af himmelen.',
        12: 'Då suckade han i sinom Anda, och sade: Hvi söker detta slägtet tecken? Sannerliga säger jag eder: Desso slägte skall intet tecken gifvas.',
        13: 'Så gaf han dem öfver; och gick åter i skeppet, och for utöfver.',
        14: 'Och de hade förgätit taga bröd, så att de hade icke mer än ett bröd med sig i skeppet.',
        15: 'Då böd han dem, sägandes: Ser till, vakter eder för de Phariseers surdeg, och för Herodis surdeg.',
        16: 'Och de tänkte hit och dit, sägande emellan sig: Det äret, vi hafve intet bröd.',
        17: 'Då Jesus det förnam, sade han till dem: Hvad bekymren I eder, att I hafven icke bröd? Kunnen I ännu intet akta, eller förstå? Hafven I ännu edor hjerta förblindadt?',
        18: 'Hafvandes ögon, och sen intet? och hafvandes öron, och hören intet?',
        19: 'Och minnens I icke, då jag bröt fem bröd ibland femtusend, huru många korgar upptogen I fulla med aflefvor? Sade de: Tolf.',
        20: 'Och då jag bröt sju bröd ibland fyratusend, huru många korgar upptogen I utaf de aflefvor? De sade: Sju.',
        21: 'Och han sade till dem: Hvi förstån I då intet?',
        22: 'Och han kom till Bethsaida; och de hade fram för honom en blindan, och bådo honom, att han ville taga på honom.',
        23: 'Och så tog han den blinda vid handena, och ledde honom utu byn; och spottade i hans ögon, och lade händer på honom, och frågade honom, om han något såg.',
        24: 'Då såg han upp, och sade: Jag ser folket gå, lika som det vore trä.',
        25: 'Sedan lade han åter händerna på hans ögon, och gjorde det så att han fick synen igen; och vardt så botad, att han sedan såg klarliga alla.',
        26: 'Och han lät gå honom hem, och sade: Gack intet in i byn, och säg icke heller det någrom derinne.',
        27: 'Och Jesus gick ut, och hans Lärjungar, till de byar vid Cesarea, som kallas Philippi; och i vägen frågade han sina Lärjungar, sägandes till dem: Hvem säger folket mig vara?',
        28: 'De svarade: Johannes Döparen; och somlige Elias; och somlige en af Propheterna.',
        29: 'Då sade han till dem: Hvem sägen I mig vara? Svarade Petrus, och sade till honom: Du äst Christus.',
        30: 'Då hotade han dem, att de skulle ingom säga om honom;',
        31: 'Och begynte till att undervisa dem, att menniskones Son skulle mycket lida, och förkastas af de äldsta, och af de öfversta Presterna, och af de Skriftlärda, och dödas; och efter tre dagar uppstå igen.',
        32: 'Och talade han det talet uppenbart. Då tog Petrus honom till sig, och begynte näpsa honom.',
        33: 'Då vände han sig om, och såg på sina Lärjungar, och näpste Petrum, sägandes: Gack bort ifrå mig, du Satan; ty du besinnar icke det Gudi tillhörer, utan det menniskor tillhörer.',
        34: 'Och kallade han till sig folket, med sina Lärjungar, och sade till dem: Den mig vill följa, han försake sig sjelf, och tage sitt kors uppå sig, och följe mig.',
        35: 'Ty den, som vill behålla sitt lif, han skall mista det; och den som mister sitt lif, för mina och Evangelii skull, han skall det behålla.',
        36: 'Ty hvad hjelper det menniskone, om hon kunde vinna hela verldena, och toge skada till sin själ?',
        37: 'Eller hvad kan en menniska gifva, der hon sin själ med lösa må?',
        38: 'Men den som blyges vid mig och min ord, uti detta horiska och syndiga slägtet, vid honom skall ock menniskones Son blygas, när han kommer i sins Faders härlighet, med de helga Änglar.',
    },
    9: {
        1: 'Och han sade till dem: Sannerliga säger jag eder, någre äro ibland dem som här stå, de der icke skola smaka döden, tilldess de få se Guds rike komma med kraft.',
        2: 'Och efter sex dagar tog Jesus Petrum, Jacobum och Johannem till sig; och hade dem allena upp på ett högt berg afsides, och vardt förklarad för dem.',
        3: 'Och hans kläder vordo klar, och ganska hvit såsom snö, att ingen färgare på jordene kan göra dem så hvit.',
        4: 'Och dem syntes Elias med Mose, och de talade med Jesu.',
        5: 'Då svarade Petrus, sägandes till Jesum: Rabbi, här är oss godt att vara; låt oss göra här tre hyddor, dig en, Mosi en, och Elie en.',
        6: 'Men han visste icke hvad han sade; ty de voro häpne vordne.',
        7: 'Och en sky kom, som öfverskyggde dem; och en röst kom utaf skyn, och sade: Denne är min käre Son; honom hörer.',
        8: 'Och i det samma som de sågo sig om, sågo de ingen vara der när dem, utan allena Jesus.',
        9: 'Men då de gingo neder af berget, böd han dem, att de skulle ingom säga hvad de sett hade, förr än menniskones Son vore uppstånden ifrå de döda.',
        10: 'Och de behöllo det ordet när sig, och befrågade emellan sig, hvad det skulle vara, att han sade: uppstå ifrå de döda.',
        11: 'Och de sporde honom, sägande: Hvad är det, som de Skriftlärde säga, att Elias måste komma först?',
        12: 'Men han svarade, och sade till dem: Elias skall ju komma först, och sätta all ting i lag igen; och att menniskones Son skall mycket lida, och föraktad varda, såsom skrifvet är.',
        13: 'Men jag säger eder: Elias är kommen, och de gjorde honom allt det de ville, såsom skrifvet var om honom.',
        14: 'Då han kom till sina Lärjungar, såg han mycket folk omkring dem, och de Skriftlärda disputerande med dem.',
        15: 'Och straxt allt folket såg honom, vordo de häpne; och lupo till och helsade honom.',
        16: 'Och han sporde de Skriftlärda: Hvad disputeren I med dem?',
        17: 'Och en af folket svarade, och sade: Mästar, jag hafver haft min son hit till dig, den der hafver en stum anda;',
        18: 'Och då han tager honom fatt, far han illa med honom; och han fradgas, och gnisslar med sina tänder, och förtvinar. Jag talade med dina Lärjungar, att de skulle drifva honom ut; och de kunde icke.',
        19: 'Då svarade han honom, och sade: O I otrogna slägte; huru länge skall jag vara när eder? Huru länge skall jag lida eder? Leder honom hit till mig.',
        20: 'Och de ledden fram till honom. Då anden fick se honom, straxt for han illa med honom; och föll neder på jordena, och välte sig, och fradgades.',
        21: 'Då sporde han hans fader till: Huru länge är, sedan detta kom honom uppå? Då sade han: Utaf barndom.',
        22: 'Och han hafver ofta kastat honom i elden, och i vattnet, att han måtte förgöra honom; men förmår du något, så varkunna dig öfver oss, och hjelp oss.',
        23: 'Jesus sade till honom: Om du tro kan; all ting äro möjelig honom, som tror.',
        24: 'Och straxt ropade drängens fader, med gråtande tårar, sägandes: Herre, jag tror; hjelp mina otro.',
        25: 'När Jesus såg, att folket lopp till med, näpste han den orena andan, och sade till honom: Du ande, döfver och dumbe, jag bjuder dig, gack ut af honom, och gack intet mer härefter in uti honom.',
        26: 'Så ropade anden, och for ganska illa med honom, och gick ut. Och han vardt som han hade varit död; så att månge sade: Han är död.',
        27: 'Då tog Jesus honom vid handena, och reste honom upp; och han stod upp.',
        28: 'Och när han kom hem i huset, frågade hans Lärjungar honom afsides: Hvi förmådde icke vi utdrifva honom?',
        29: 'Sade han till dem: Detta slägtet kan med ingen ting utfara, utan med bön och fasto.',
        30: 'Och de gingo dädan, och vandrade genom Galileen; och han ville icke, att någor skulle vetat.',
        31: 'Ty han underviste sina Lärjungar, och han sade till dem: Menniskones Son skall varda öfverantvardad i menniskors händer, och de skola döda honom; och då han är dödad, skall han på tredje dagen uppstå.',
        32: 'Men de förstodo intet hvad han sade, och torde icke spörja honom.',
        33: 'Så kom han till Capernaum; och när han var kommen i huset, sporde han dem: Hvad handladen I eder emellan i vägen?',
        34: 'Men de tigde; förty de hade handlat emellan sig i vägen, hvilken af dem ypperst var.',
        35: 'Och då han hade satt sig, kallade han de tolf, och sade till dem: Hvilken som vill den främste vara, han skall vara ytterst af allom, och allas tjenare.',
        36: 'Och så tog han ett barn, och ställde det midt ibland dem. Och då han hade tagit det i sin famn, sade han till dem:',
        37: 'Hvilken som anammar ett sådant barn i mitt Namn, han anammar mig; och hvilken mig anammar, han anammar icke mig, utan honom som mig sändt hafver.',
        38: 'Men Johannes svarade honom, sägandes: Mästar, vi sågom en utdrifva djeflar uti ditt Namn, och han följer oss icke; och vi förböde honom det, efter han icke följer oss.',
        39: 'Då sade Jesus: Förbjuder honom icke; ty ingen är den som gör krafter i mitt Namn, som snarliga kan tala ondt på mig;',
        40: 'Förty den der icke är emot oss, han är med oss.',
        41: 'Men hvilken som gifver eder dricka en bägare vatten, i mitt Namn, derföre att I Christo tillhören, sannerliga säger jag eder, han skall ingalunda mista sin lön.',
        42: 'Och hvilken som förargar en af de små, som tro på mig, bättre vore honom, att vid hans hals hängdes en qvarnsten, och han bortkastades uti hafvet.',
        43: 'Nu, om din hand vore dig till förargelse, hugg henne af. Bättre är dig enhändtan ingå uti lifvet, än att du hafver två händer, och far till helvetet, uti evig eld;',
        44: 'Der deras matk icke dör, och elden icke utsläckes.',
        45: 'Och om din fot vore dig till förargelse, hugg honom af. Dig är bättre, att du ingår uti lifvet halter, än att du hafver två fötter, och varder kastad till helvetet, uti evig eld;',
        46: 'Der deras matk icke dör, och elden icke utsläckes.',
        47: 'Och om ditt öga vore dig till förargelse, rif det ut. Bättre är dig, att du enögder ingår uti Guds rike, än att du skulle hafva tu ögon, och bortkastas i helvetes eld;',
        48: 'Der deras matk icke dör, och elden icke utsläckes.',
        49: 'Ty hvar och en måste med eld saltad varda, och allt offer måste med salt saltas.',
        50: 'Salt är ett godt ting; hvar nu saltet mister sin sälto, hvarmed skall man salta? Hafver salt uti eder, och hafver frid emellan eder inbördes.',
    },
    10: {
        1: 'Och då han stod upp dädan, kom han uti Judee landsändar, vid sidon af Jordan. Och folket församlades åter till honom; och åter lärde han dem, såsom hans seder var.',
        2: 'Då gingo de Phariseer till, och frågade honom: Är det ock mannenom lofligit skilja sina hustru ifrå sig? frestande honom.',
        3: 'Då svarade han, och sade till dem: Hvad hafver Mose budit eder?',
        4: 'Sade de: Mose tillstadde skrifva ett skiljobref, och öfvergifva henne.',
        5: 'Svarade Jesus, och sade till dem: För edor hjertas hårdhets skull skref han eder detta budet.',
        6: 'Men af första skapelsen hafver Gud gjort dem man och qvinno;',
        7: 'Fördenskull skall man öfvergifva sin fader och moder, och blifva vid sina hustru;',
        8: 'Och de tu varda ett kött; så äro de nu icke tu, utan ett kött.',
        9: 'Hvad Gud hafver tillhopafogat, det skall menniskan icke åtskilja.',
        10: 'Och i huset frågade hans Lärjungar honom på nytt om samma ärende.',
        11: 'Och han sade till dem: Hvilken som skiljer sina hustru ifrå sig, och tager ena andra, han bedrifver hor emot henne.',
        12: 'Och om qvinnan öfvergifver sin man, och tager en annan, hon bedrifver hor.',
        13: 'Och de hade barn till honom, att han skulle taga på dem; men Lärjungarna näpste dem, som dem fram hade.',
        14: 'Men när Jesus det såg, vardt han misslynt, och sade till dem: Låter barnen komma till mig, och förmener dem icke; ty sådana hörer Guds rike till.',
        15: 'Sannerliga säger jag eder; Hvilken som icke undfår Guds rike såsom ett barn, han kommer der aldrig in.',
        16: 'Och han tog dem upp i famnen, och lade händerna på dem, och välsignade dem,',
        17: 'Och då han dädan utgången var på vägen, lopp en till, och föll på knä för honom, och frågade honom: Gode Mästar, hvad skall jag göra, att jag måtte få evinnerligit lif?',
        18: 'Men Jesus sade till honom: Hvi kallar du mig godan? Ingen är god utan en, det är Gud.',
        19: 'Budorden vetst du: Du skall icke bedrifva hor: Du skall icke dräpa: Du skall icke stjäla: Du skall icke tala falskt vittnesbörd: Du skall ingen bedraga: Ära din fader och moder.',
        20: 'Då svarade han, och sade till honom: Mästar, det hafver jag allt hållit utaf min ungdom.',
        21: 'Jesus såg på honom, och älskade honom, och sade till honom: Ett fattas dig; gack bort, sälj allt det du hafver, och gif de fattiga, och du skall få en skatt i himmelen; och kom, följ mig, och tag korset uppå dig.',
        22: 'Och han vardt bedröfvad af talet, och gick bort sörjandes; ty han hade många ägodelar.',
        23: 'Och Jesus såg sig om, och sade till sina Lärjungar: Huru svårliga kunna de rike komma in uti Guds rike!',
        24: 'Men hans Lärjungar vordo förskräckte af hans ord. Då svarade åter Jesus, och sade till dem: Huru svårt är det, kära barn, dem som sätta sina tröst på sina rikedomar, ingå uti Guds rike.',
        25: 'Lättare är en camel gå igenom ett nålsöga, än en rik gå in uti Guds rike.',
        26: 'Men de förundrade sig öfvermåtton, och sade vid sig sjelfva: Ho kan då varda salig?',
        27: 'Men Jesus såg på dem, och sade: För menniskom är det omöjeligit; men icke för Gud; ty när Gudi äro all ting möjelig.',
        28: 'Och Petrus begynte säga till honom: Si, vi hafve öfvergifvit all ting, och följt dig.',
        29: 'Svarade Jesus, och sade: Sannerliga säger jag eder: Ingen är den som hafver öfvergifvit hus, eller bröder, eller systrar, eller fader, eller moder, eller hustru, eller barn, eller åkrar, för min och Evangelii skull;',
        30: 'Den icke får hundradefaldt igen, nu i denna tiden, hus, och bröder, och systrar, och mödrar, och barn, och åkrar, med förföljelsen; och i tillkommande verld evinnerligit lif.',
        31: 'Men månge, de som de främste äro, varda de ytterste, och de ytterste de främste.',
        32: 'Och de voro på vägen, gångande upp till Jerusalem; och Jesus gick för dem, och de voro förskräckte, och gingo efter honom, fruktande sig. Så tog Jesus åter till sig de tolf, och begynte säga dem, hvad honom öfvergå skulle:',
        33: 'Si, vi gåm upp till Jerusalem; och menniskones Son skall öfverantvardas de öfversta Presterna, och de Skriftlärda; och de skola fördöman till döds, och öfverantvardan Hedningomen;',
        34: 'Och de skola begabban, och hudflängan, bespottan, och dödan; och tredje dagen skall han uppstå igen.',
        35: 'Då gingo till honom Jacobus och Johannes, Zebedei söner, och sade: Mästar, vi vilje att du gör oss hvad som helst vi bedje.',
        36: 'Sade han till dem: Hvad viljen I jag skall göra eder?',
        37: 'Sade de till honom: Gif oss, att vi sitte, den ene på dine högra hand, och den andre på dine venstra, uti din härlighet.',
        38: 'Men Jesus sade till dem: I veten icke hvad I bedjen; kunnen I dricka den kalken, som jag dricker; och döpas med den döpelsen, der jag med döpes?',
        39: 'Då sade de till honom: Ja, kunne vi så. Sade Jesus till dem: Den kalken jag dricker, skolen I ock dricka; och med den döpelse, der jag med döpes, skolen I döpas;',
        40: 'Men sitta på mine högra och venstra hand, står icke mig till att gifva; utan dem händer det, som det beredt är.',
        41: 'När de tio hörde detta, begynte de vara illa tillfrids med Jacobo och Johanne.',
        42: 'Men Jesus kallade dem till sig, och sade till dem: I veten, att verldslige Förstar äro rådande, och de mägtige ibland dem hafva välde;',
        43: 'Men det skall icke så vara ibland eder; utan den, som ibland eder vill ypperst vara, han skall vara edar tjenare.',
        44: 'Och den, som ibland eder vill vara den främste, han skall vara allas dräng;',
        45: 'Ty ock menniskones Son är icke kommen, på det han skulle låta tjena sig; utan på det han ville tjena, och gifva sitt lif till återlösning för många.',
        46: 'Och de kommo till Jericho. Och då han gick ut af Jericho, och hans Lärjungar, och en mägtig stor hop folk, då satt der vid vägen en blinder, Bartimeus, Timei son, tiggandes.',
        47: 'Och när han hörde, att det var Jesus af Nazareth, begynte han ropa, och säga: Jesu, Davids Son, varkunna dig öfver mig.',
        48: 'Och månge näpste honom, att han skulle tiga; men han ropade dessmer: Davids Son, varkunna dig öfver mig.',
        49: 'Så stadnade Jesus, och lät kalla honom. Och de kallade den blinda, och sade till honom: Var vid ett godt mod; statt upp, han kallar dig.',
        50: 'Han kastade ifrå sig sin mantel, stod upp, och kom till Jesum.',
        51: 'Då svarade Jesus, och sade till honom: Hvad vill du, att jag skall göra dig? Den blinde sade till honom: Rabboni, att jag måtte få min syn.',
        52: 'Jesus sade till honom: Gack, din tro hafver gjort dig helbregda. Och straxt fick han sin syn, och följde Jesum i vägen.',
    },
    11: {
        1: 'Och då de kommo in mot Jerusalem, till Bethphage och Bethanien, vid Oljoberget, utsände han två af sina Lärjungar;',
        2: 'Och han sade till dem: Går i byn, som för eder är; och straxt I kommen derin, varden I finnande en fåla bunden, der ännu ingen menniska på sutit hafver; löser honom, och hafver honom hit.',
        3: 'Och om någor säger till eder: Hvi gören I detta? säger: Herren behöfver honom; och då skall han straxt sända honom hit.',
        4: 'Så gingo de bort, och funno fålan bunden för dörrene, vid vägamotet, och löste honom.',
        5: 'Och somlige, som der stodo, sade till dem: Hvad gören I, att I lösen fålan?',
        6: 'Då sade de till dem, såsom Jesus hade budit dem; så läto de betämma dem.',
        7: 'Och de hade fålan till Jesum, och kastade sin kläder på honom; och han satte sig deruppå.',
        8: 'Och månge bredde sin kläder på vägen; och somlige skåro qvistar af trän, och strödde på vägen.',
        9: 'Och de der föregingo, och der efterföljde, ropade, och sade: Hosianna! välsignad vare den, som kommer i Herrans Namn.',
        10: 'Välsignad vare vårs faders Davids rike, som kommer i Herrans Namn; Hosianna i höjdene!',
        11: 'Och Herren gick in i Jerusalem, och i templet, och besåg all ting. Och när det led åt aftonen, gick han ut till Bethanien, med de tolf.',
        12: 'Och dagen derefter, då de gingo ut ifrå Bethanien, hungrade honom.',
        13: 'Och han fick se ett fikonaträ der långt ifrå, som löf hade; dit kom han, om han tilläfventyrs måtte finna der något uppå; och då han kom dit, fann han der intet annat än löf; ty det var icke då tid till fikon.',
        14: 'Och Jesus svarade, och sade till det: Äte aldrig någor härefter frukt af dig till evig tid. Och hans Lärjungar hörde det.',
        15: 'Och de kommo till Jerusalem. Och Jesus gick in i templet, och begynte utdrifva dem som sålde och köpte i templet; och förstörte de vexlares bord, och deras stolar som dufvor sålde;',
        16: 'Och stadde icke till, att någor bar något genom templet.',
        17: 'Och han lärde, och sade till dem: Är icke skrifvet: Mitt hus skall kallas ett bönehus allom folkom? Men I hafven gjort det till en röfvarekulo.',
        18: 'Och de Skriftlärde och öfverste Presterne fingo det höra; och begynte söka efter, huru de kunde förgöra honom, men de fruktade för honom; ty allt folket förundrade sig på hans lärdom.',
        19: 'Och då aftonen kom, gick han utu staden.',
        20: 'Och om morgonen gingo de der framom, och sågo fikonaträt förtorkadt vara intill roten.',
        21: 'Då kom Petrus det ihåg, och sade till honom: Rabbi, si, det fikonaträt, som du bannade, är förtorkadt.',
        22: 'Jesus svarade, och sade till dem: Hafver trona till Gud.',
        23: 'Sannerliga säger jag eder: Hvilken som helst sade till detta berg: Häf dig upp, och kasta dig i hafvet; och han tviflade intet i sitt hjerta, utan trodde så ske skola som han sade; honom skall ske allt det han säger.',
        24: 'Derföre säger jag eder: Allt det I bedjen i edra böner, tror att I fån det, så skall det ske eder.',
        25: 'Och när I stån och bedjen, så förlåter, om I något hafven emot någon; på det edar Fader, som i himmelen är, skall ock förlåta eder edra brister.',
        26: 'Men om I icke förlåten, så skall icke heller edar Fader, som är i himmelen, förlåta det I bryten.',
        27: 'Och som de kommo åter till Jerusalem, och han gick i templet, kommo till honom de öfverste Presterna, och de Skriftlärde, och de äldste;',
        28: 'Och de sade till honom: Af hvad magt gör du detta? Och hvilken hafver gifvit dig denna magten, att du detta göra skall?',
        29: 'Jesus svarade, och sade till dem: Jag vill ock något spörja eder; svarer mig, så vill jag säga eder, af hvad magt jag detta gör.',
        30: 'Johannis döpelse, var den af himmelen, eller af menniskor? Svarer mig.',
        31: 'Och de tänkte vid sig, och sade: Säge vi, af himmelen; då säger han: Hvi trodden I honom icke då?',
        32: 'Men säge vi, att den var af menniskom, rädes vi för folket; ty alle höllo Johannes för en sann Prophet.',
        33: 'Och så svarade de, sägande till Jesum: Vi vete det icke. Svarade Jesus, och sade till dem: Icke heller säger jag eder, af hvad magt jag detta gör.',
    },
    12: {
        1: 'Och han begynte tala dem till i liknelser: En man plantade en vingård, och gärde deromkring en gård, och grof en press, och byggde ett torn, och lejde honom ut vingårdsmännom; och for så ut i fremmande land.',
        2: 'Och då rätta tiden var, sände han sin tjenare till vingårdsmännerna, att han skulle anamma, af vingårdsmännerna, utaf vingårdsens frukt;',
        3: 'Men de togo honom, och slogo honom, och läto honom gå ifrå sig tomhändtan.',
        4: 'Åter sände han till dem en annan tjenare; den kastade de hufvudet sönder med sten, och läto honom gå ifrå sig försmäddan.',
        5: 'Åter sände han en annan, den dråpo de; och många andra, somliga hudflängde de, och somliga dråpo de.',
        6: 'Så hade han ännu en enda son, den han kär hade; honom sände han ock till dem på det sista, sägandes: De hafva ju en försyn för min son.',
        7: 'Men vingårdsmännerna sade emellan sig: Denne är arfvingen; kommer, låter oss dräpa honom, så varder arfvedelen vår.',
        8: 'Då togo de honom, och dråpo honom, och kastaden utu vingården.',
        9: 'Hvad skall nu vingårdsherren göra? Han skall komma, och förgöra vingårdsmännerna, och få vingården androm.',
        10: 'Hafven I ock icke läsit denna Skriften? Den stenen, som byggningsmännerne bortkastade, är vorden en hörnsten;',
        11: 'Af Herranom är detta gjordt, och är underligit för vår ögon.',
        12: 'Och de sökte efter att gripa honom; men de räddes för folket; ty de förstodo att han sade denna liknelsen om dem. Så gåfvo de honom öfver, och gingo sin väg.',
        13: 'Och sände de till honom några af de Phariseer, och de Herodianer, att de skulle gripa honom i orden.',
        14: 'Då de kommo, sade de till honom; Mästar, vi vete, att du äst sannfärdig, och sköter om ingen; ty du ser icke efter menniskors person, utan lärer Guds väg rätt. Är det ock rätt, att man gifver Kejsarenom skatt, eller icke? Skole vi gifvan, eller icke gifvan?',
        15: 'Men han förstod deras skrymtan, och sade till dem: Hvi fresten I mig? Tager hit penningen, att jag må se honom.',
        16: 'Och de båro honom fram. Då sade han till dem: Hvars beläte och öfverskrift är detta? Sade de till honom: Kejsarens.',
        17: 'Då svarade Jesus, och sade till dem: Så gifver Kejsarenom hvad Kejsarenom tillhörer, och Gudi det Gudi tillhörer. Och de förundrade sig på honom.',
        18: 'Så kommo de Sadduceer till honom, hvilke säga att ingen uppståndelse är, och sporde honom, sägande:',
        19: 'Mästar, Mose hafver skrifvit oss: Om någors mans broder dör, och låter hustru efter sig, och låter ingen barn efter sig, då skall hans broder taga hans hustru, och uppväcka sinom broder säd.',
        20: 'Det voro sju bröder; och den förste tog sig hustru, och han blef död, och lefde ingen säd efter sig;',
        21: 'Och den andre tog henne, och blef död; den icke heller lefde säd efter sig; och den tredje sammalunda;',
        22: 'Så att sju togo henne, och lefde dock ingen säd. Sist af allom dödde ock hustrun.',
        23: 'Hvilkensderas hustru skall hon nu vara i uppståndelsen, då de skola uppstå? Ty sju hade haft henne till hustru.',
        24: 'Svarade Jesus, och sade till dem: I faren ville, derföre att I icke veten Skriftena, ej heller Guds kraft.',
        25: 'Ty då de uppståndne äro ifrå de döda, tager man sig icke hustru, och icke gifs heller hustru manne; utan de äro såsom Änglar, som i himmelen äro.',
        26: 'Men om de döda, att de skola uppstå, hafven I icke läsit i Mose bok, huruledes Gud talade med honom i buskanom, sägandes: Jag är Abrahams Gud, och Isaacs Gud, och Jacobs Gud?',
        27: 'Han är icke de dödas Gud, utan deras Gud, som lefva. Så faren I nu mycket ville.',
        28: 'Då gick en fram af de Skriftlärda, den derpå hört hade, huru de tillhopa disputerat hade, och hade sett att han hade väl svarat dem, och sporde honom till: Hvilket är det yppersta af all budorden?',
        29: 'Jesus svarade honom: Det yppersta af all budorden är detta: Hör, Israel; Herren vår Gud är allena Herre;',
        30: 'Och du skall älska din Herra Gud, af allt ditt hjerta, och af allo dine själ, och af all din håg, och af allo dine magt. Detta är det yppersta budet.',
        31: 'Och det andra är desso likt: Älska din nästa som dig sjelf. Intet annat bud är större än dessa.',
        32: 'Och den Skriftlärde sade till honom: Mästar, du hafver allt rätt sagt, att Gud är en, och ingen annar är förutan honom;',
        33: 'Och att älska honom af allt hjerta, och af allt förstånd, och af allo själ, och af allo magt, och älska sin nästa som sig sjelf, det är mer än bränneoffer, och all offer.',
        34: 'Då Jesus såg, att han visliga svarat hade, sade han till honom: Du äst icke långt ifrå Guds rike. Och sedan torde ingen fråga honom.',
        35: 'Och svarade Jesus, och sade, lärandes i templet: Huru säga de Skriftlärde, att Christus är Davids Son?',
        36: 'Ty David, genom den Helga Anda, säger: Herren sade till min Herra: Sätt dig på min högra hand, tilldess jag hafver satt dina ovänner dig till en fotapall.',
        37: 'Så kallar nu David honom Herra; hvadan är han då hans Son? Och en stor del af folket hörde honom gerna.',
        38: 'Och han lärde dem, och sade till dem: Vakter eder för de Skriftlärda; de gå gerna i sid kläder, och låta gerna helsa sig på torgen;',
        39: 'Och sitta gerna främst i Synagogorna, och främst vid bordet i gästabåden;',
        40: 'Hvilke uppäta enkors hus, förebärande långa böner; desse skola få dess svårare fördömelse.',
        41: 'Och satte sig Jesus tvärtemot offerkistona, och såg uppå huruledes folket lade penningar i kistona; och månge rike lade mycket in.',
        42: 'Och en fattig enka kom, och lade in två skärfvar, det var en penning.',
        43: 'Då kallade han sina Lärjungar till sig, och sade till dem: Sannerliga säger jag eder, denna fattiga enkan lade mer in i kistona, än alle de andre som der inlade.',
        44: 'Ty de hafva alle inlagt af det dem öfverlopp; men hon inlade, utaf sin fattigdom, allt det hon hade, alla sina näring.',
    },
    13: {
        1: 'Och då han gick ut af templet, sade till honom en af hans Lärjungar: Mästar, se hurudana stenar, och hurudana byggning är detta.',
        2: 'Jesus svarade, och sade till honom: Ser du denna stora byggningen? En sten varder icke qvarliggandes på den andra, den icke afbruten varder.',
        3: 'Och då han satt på Oljoberget, tvärtemot templet, frågade honom Petrus, och Jacobus, och Johannes, och Andreas, afsides:',
        4: 'Säg oss, när detta skall ske? Och hvad tecken är dertill, när detta skall allt fullbordas?',
        5: 'Svarade Jesus, och begynte säga: Ser till, att ingen bedrager eder.',
        6: 'Ty månge varda kommande i mitt Namn, sägande: Jag är Christus; och de skola bedraga många.',
        7: 'Men när I fån höra örlig, och örligs rykte, varer icke bedröfvade; ty det måste så ske; men det är icke straxt änden.',
        8: 'Det ena folket skall uppsätta sig emot det andra, och det ena riket emot det andra; och jordbäfning skall varda mångastäds; och hunger och förskräckelser skola varda. Detta är begynnelsen till vedermödon.',
        9: 'Men tager I eder vara; ty de skola öfverantvarda eder in på Rådhusen och Synagogorna; och I skolen varda hudflängde, och framdragne för Förstar och Konungar, för mina skull, till ett vittnesbörd öfver dem.',
        10: 'Och Evangelium måste först predikadt varda för all folk.',
        11: 'När de nu draga eder fram, och öfverantvarda eder, så hafver ingen omsorg, hvad I skolen säga; och tänker der intet på framföreåt; utan, hvad eder ingifvet varder i samma stunden, det taler; ty det ären icke I, som talen, utan den Helge Ande.',
        12: 'Och den ene brodren skall öfverantvarda den andra i döden, och fadren sonen; och barnen skola sig uppsätta mot föräldrarna, och hjelpa till att döda dem.',
        13: 'Och I skolen varda förhatade af allom, för mitt Namns skull; men den som härdar intill ändan, han varder salig.',
        14: 'Men då I fån se förödelsens styggelse, deraf sagdt är genom Propheten Daniel, ståndandes der det icke skall; (den det läs, han förstå det) de som då äro i Judeen, de fly upp på bergen.',
        15: 'Men den der är på taket, han gånge icke neder i huset, och gånge icke in, till att taga något utu sitt hus.',
        16: 'Och den som är på åkren, han vände icke tillbaka, till att taga sin kläder.',
        17: 'Ve dem, som hafvande äro, eller dia gifva, i de dagar.',
        18: 'Men beder, att edor flykt icke sker om vinteren;',
        19: 'Ty i de dagar varder sådana bedröfvelse, att slik hafver icke varit, ifrå kreaturens begynnelse, dem Gud skapat hafver, intill nu; och ej heller varder.',
        20: 'Och hvar Herren icke hade förkortat de dagar, vorde intet kött saligt; men för de utkorades skull, som han utkorat hafver, förkortade han dagarna.',
        21: 'När då någor ville säga till eder: Si, här är Christus; eller si, han är der; tror det intet;',
        22: 'Ty falske Christi och falske Propheter skola upphäfva sig, och skola göra tecken och under, så att de ock skola förföra de utkorada, om möjeligit vore.',
        23: 'Men tager I eder vara; si, jag hafver sagt eder all ting framföreåt.',
        24: 'Men i de dagar, efter den bedröfvelsen, skall solen förmörkas, och månen skall icke gifva sitt sken;',
        25: 'Och himmelens stjernor skola nederfalla, och himmelens krafter skola bäfva.',
        26: 'Och då skola de få se menniskones Son komma i skyn, med stor magt och härlighet.',
        27: 'Och då skall han sända sina Änglar, till att församla sina utkorada, ifrå fyra väder; ifrå jordenes ända intill himmelens ända.',
        28: 'Lärer af fikonaträt en liknelse: När nu dess qvist är klen, och begynner bära löf, så veten I, att sommaren är när;',
        29: 'Sammalunda ock, när I sen detta ske, så veter att det är när för dörrene.',
        30: 'Sannerliga säger jag eder, att detta slägtet skall icke förgås, förr än allt detta skedt är.',
        31: 'Himmel och jord skola förgås; men min ord skola icke förgås.',
        32: 'Men om den dagen, och den stunden, vet ingen; icke Änglarna, som i himmelen äro, ej heller Sonen; utan Fadren allena.',
        33: 'Ser till, vaker och beder; ty I veten icke, när tiden är.',
        34: 'Såsom en man, den der drog bort i främmande land, och lät blifva sitt hus, och gaf sina tjenare magt, och hvarjom och enom sina sysslo, och böd dörravaktaren, att han skulle vaka.',
        35: 'Vaker fördenskull; ty I veten icke, när husbonden kommer, antingen om aftonen, eller midnattstid, eller i hönsgälden, eller om morgonen;',
        36: 'Att, då han kommer hasteliga, han icke skall finna eder sofvande.',
        37: 'Men hvad jag säger eder, det säger jag allom: Vaker.',
    },
    14: {
        1: 'Och två dagar derefter instundade Påska och Sötbrödsdagarna; och de öfverste Presterna och de Skriftlärde sökte efter, huru de kunde svikliga få fatt på honom, och döda honom.',
        2: 'Men de sade: Icke om högtidsdagen, att ett upplopp icke sker ibland folket.',
        3: 'Och då han var i Bethanien, i den spitelska Simons hus, vid han satt till bords, kom en qvinna, som hade ett glas med oförfalskadt och kosteligit nardus smörjelse; hon bröt glaset sönder, och utgöt det på hans hufvud.',
        4: 'Så voro der någre, som icke togo det väl vid sig, och sade: Hvarefter förspilles denna smörjelsen?',
        5: 'Ty det måtte väl varit såldt mer än för trehundrade penningar, och gifvet fattigom; och läto illa på henne.',
        6: 'Då sade Jesus: Låter henne med frid; hvi gören I henne illa tillfrids? Hon hafver gjort en god gerning på mig;',
        7: 'Ty I hafven alltid fattiga när eder; och när som helst I viljen, kunnen I göra dem till godo; men mig hafven I icke alltid.',
        8: 'Det hon kunde, det gjorde hon; hon är förekommen att smörja min lekamen till begrafning.',
        9: 'Sannerliga säger jag eder: Hvar detta Evangelium predikadt varder uti hela verldene, skall ock detta, som hon gjorde, sagdt varda, henne till åminnelse.',
        10: 'Och Judas Ischarioth, en af de tolf, gick bort till de öfversta Presterna, på det han skulle förråda honom dem i händer.',
        11: 'När de det hörde, vordo de glade, och lofvade honom, att de ville gifva honom penningar; och han sökte, huru han lämpeligast kunde förråda honom.',
        12: 'På första Sötbrödsdagen, då man offrade Påskalambet, sade hans Lärjungar till honom: Hvar vill du, att vi skole gå och reda till, att du äter Påskalambet?',
        13: 'Och han sände två af sina Lärjungar, och sade till dem: Går in i staden, och der möter eder en man, bärandes ena kruko vatten; följer honom efter;',
        14: 'Och hvar han ingår, säger till husbondan: Mästaren låter säga dig: Hvar är gästahuset, der jag med minom Lärjungom kan äta Påskalambet?',
        15: 'Och han skall visa eder en stor sal, beredd och tillpyntad; der reder till för oss.',
        16: 'Och hans Lärjungar gingo ut, och kommo in i staden, och funno som han dem sagt hade, och tillredde Påskalambet.',
        17: 'Då nu aftonen vardt, kom han med de tolf.',
        18: 'Och vid de såto till bords, och åto, sade Jesus: Sannerliga säger jag eder, en af eder, som äter med mig, skall förråda mig.',
        19: 'Men de begynte vara illa tillfrids, och sade till honom, hvar i sin stad: Är det jag? och den andre: Är det jag?',
        20: 'Han svarade och sade till dem: En af de tolf, den som tager i fatet med mig.',
        21: 'Ja, menniskones Son varder så gångandes, som skrifvet är om honom; men ve de mennisko, genom hvilken menniskones Son varder förrådder; de mennisko vore bättre, att hon icke vore född.',
        22: 'Och vid de åto, tog Jesus brödet; tackade, och bröt det, och gaf dem, och sade: Tager, äter, detta är min lekamen;',
        23: 'Och tog kalken, och tackade, och gaf dem; och de drucko deraf alle.',
        24: 'Och sade han till dem: Detta är min blod, dess nya Testamentsens, hvilken för många utgjuten varder.',
        25: 'Sannerliga säger jag eder: Härefter skall jag icke dricka af vinträs frukt, intill den dagen att jag dricker det nytt i Guds rike.',
        26: 'Och då de hade sagt lofsången, gingo de ut på Oljoberget.',
        27: 'Och Jesus sade till dem: I skolen alle i denna nattene förargas på mig; ty det är skrifvet: Jag skall slå herdan, och fåren varda förskingrad.',
        28: 'Men då jag är uppstånden, vill jag gå fram för eder uti Galileen.',
        29: 'Då sade Petrus till honom: Om än alle förargades, skall jag icke förargas.',
        30: 'Jesus sade till honom: Sannerliga säger jag dig, i dag, i denna natt, förr än hanen hafver två resor galit, skall du tre resor försaka mig.',
        31: 'Då sade han ändå ytterligare: Ja, skulle jag än dö med dig, jag skall icke försaka dig. Sammalunda sade de ock alle.',
        32: 'Och de kommo på den platsen, som kallades Gethsemane. Och han sade till sina Lärjungar: Sitter här, så länge jag går afsides, till att bedja.',
        33: 'Och så tog han med sig Petrum, och Jacobum, och Johannem, och begynte till att förskräckas och ängslas;',
        34: 'Och sade till dem: Min själ är bedröfvad allt intill döden; blifver här, och vaker.',
        35: 'Och han gick litet fram bätter, och föll ned på jordena, och bad att, om möjeligit vore, skulle den stunden undgå honom;',
        36: 'Och sade: Abba, Fader; all ting äro dig möjelig; unddrag mig denna kalken; dock icke hvad jag vill, utan hvad du vill.',
        37: 'Och han kom, och fann dem sofvande, och sade till Petrum: Simon, sofver du? Förmådde du icke vaka ena stund?',
        38: 'Vaker, och beder, att I icke kommen uti frestelse; anden är viljog, men köttet är svagt.',
        39: 'Och så gick han åter bort, och bad; och talade samma orden.',
        40: 'Och då han kom igen, fann han dem åter sofvande; ty deras ögon voro tung; och de visste icke hvad de honom svarade.',
        41: 'Och han kom tredje gången, och sade till dem: Ja, sofver nu, och hviler eder; det är nog, stunden är kommen: Si, menniskones Son varder öfverantvardad uti syndares händer.',
        42: 'Står upp, låt oss gå: Si, den mig förråder, är hardt när.',
        43: 'Och straxt, med samma orden, steg Judas fram, den der en var af de tolf; och med honom ett stort tal folk, med svärd och stafrar, ifrå de öfversta Presterna, och de Skriftlärda, och de äldsta.',
        44: 'Så hade den, som förrådde honom, gifvit dem ett tecken, sägandes: Hvilken jag kysser, den äret; tager fatt på honom, och förer honom varliga.',
        45: 'Och som han kom, trädde han hasteliga fram till honom, och sade till honom: Rabbi, Rabbi; och kysste honom.',
        46: 'Då båro de händer på honom, och grepo honom.',
        47: 'Men en, af de der när stodo, drog ut sitt svärd, och slog öfversta Prestens tjenare, och högg honom ett öra af.',
        48: 'Och Jesus svarade, och sade till dem: Såsom till en röfvare ären I utgångne, med svärd och stafrar, till att gripa mig.',
        49: 'Jag hafver hvar dag varit när eder i templet, och lärt, och I togen intet fatt på mig; men detta sker, på det att Skrifterna skola fullbordas.',
        50: 'Och Lärjungarna gåfvo honom då alle öfver, och flydde.',
        51: 'Men en unger man följde honom, klädd på blotta kroppen uti ett linkläde; och unge män grepo honom.',
        52: 'Men han lät fara linklädet, och kom undan ifrå dem naken.',
        53: 'Så ledde de Jesum till den öfversta Presten, och med honom församlades alle öfverste Presterna, och de äldste, och Skriftlärde.',
        54: 'Och Petrus följde långt efter honom, tilldess han kom uti den öfversta Prestens palats; och satte sig ibland tjenarena, och värmde sig vid ljuset.',
        55: 'Men de öfverste Presterna, och hela Rådet, sökte efter vittne emot Jesum, att de måtte låta döda honom; och kunde dock ingen finna;',
        56: 'Ty månge hade burit falskt vittnesbörd emot honom; dock gjorde deras vittnesbörd icke fyllest.',
        57: 'Då stodo någre upp, och båro falskt vittnesbörd emot honom, och sade:',
        58: 'Vi hörde honom säga: Jag vill nederslå detta templet, som är med händer uppbygdt, och i tre dagar sätta ett annat upp igen, utan händer uppbygdt.',
        59: 'Och deras vittnesbörd gjorde ändå icke fyllest.',
        60: 'Då stod den öfverste Presten upp ibland dem, och frågade Jesum, sägandes: Svarar du intet? Hvad vittna desse emot dig?',
        61: 'Men han tigde, och svarade platt intet. Åter sporde den öfverste Presten, och sade till honom: Äst du Christus, dens välsignades Son?',
        62: 'Jesus sade: Jag är så; och I skolen få se menniskones Son sitta på kraftenes högra hand, och komma i himmelens sky.',
        63: 'Då ref den öfverste Presten sin kläder sönder, och sade: Hvad behöfve vi numera vittne?',
        64: 'I hörden hädelsen. Hvad synes eder? Då fördömde de honom alle, att han var saker till döds.',
        65: 'Och somlige begynte till att spotta på honom, och förtäcka hans ansigte, och slå honom med näfvarna, sägande till honom: Spå till. Och tjenarena kindpustade honom.',
        66: 'Och Petrus var nedre i palatset; då kom en öfversta Prestens tjensteqvinna;',
        67: 'Och då hon fick se Petrum värma sig, såg hon på honom, och sade: Du vast ock med Jesu Nazareno.',
        68: 'Då nekade han, och sade: Jag känner honom intet, ej heller vet jag hvad du säger. Och så gick han ut i gården, och hanen gol.',
        69: 'Och qvinnan såg honom åter, och begynte säga till de der när stodo: Denne är utaf dem.',
        70: 'Då nekade han åter. Och litet derefter talade de åter till Petrum, som när stodo: Sannerliga äst du utaf dem; ty du äst ock en Galileisk man, och ditt mål lyder derefter.',
        71: 'Då begynte han till att förbanna sig, och svärja: Jag känner icke denna mannen, der I om talen.',
        72: 'Och åter gol hanen. Då begynte Petrus draga till minnes det ordet, som Jesus hade sagt till honom: Förr än hanen hafver galit två resor, skall du försaka mig tre resor. Och han begynte till att gråta.',
    },
    15: {
        1: 'Och straxt om morgonen höllo de öfverste Presterna råd, med de äldsta och Skriftlärda, och med hela Rådet; och bundo Jesum, och ledde honom bort, och antvardade honom Pilato.',
        2: 'Och Pilatus frågade honom: Äst du den Judarnas Konung? Då svarade han, och sade till honom: Du säger det.',
        3: 'Och öfverste Presterna anklagade honom om mång ting.',
        4: 'Då frågade åter Pilatus honom, och sade: Svarar du intet? Si, huru mång stycke de vittna på dig.',
        5: 'Men Jesus svarade sedan platt intet; så att Pilatus förundrade sig.',
        6: 'Så plägade han i Påskahögtidene gifva dem en fånga lös, hvilken de helst begärade.',
        7: 'Så var der en, benämnd Barabbas, som gripen var med somliga, de der ett upplopp gjort hade, och hade uti upploppet bedrifvit ett dråp.',
        8: 'Då ropade folket, och begynte bedja, att han skulle göra dem som hans plägsed alltid var.',
        9: 'Svarade Pilatus, sägandes: Viljen I, att jag skall eder lösgifva Judarnas Konung?',
        10: 'Ty han visste, att de öfverste Presterna hade utaf afund öfverantvardat honom.',
        11: 'Men öfverste Presterna eggade folket, att han heldre skulle gifva dem Barabbam lös.',
        12: 'Pilatus svarade åter, och sade till dem: Hvad viljen I då att jag skall göra honom, den I kallen Judarnas Konung?',
        13: 'Då ropade de åter: Korsfäst honom.',
        14: 'Pilatus sade till dem: Hvad hafver han då illa gjort? Då ropade de ännu fastare: Korsfäst honom.',
        15: 'Så ville då Pilatus göra folkena fyllest, och gaf dem Barabbam lös; och öfverantvardade dem Jesum, att han skulle hudflängas och korsfästas.',
        16: 'Då hade krigsknektarna honom in uti Rådhuset, och kallade tillhopa hela skaran;',
        17: 'Och klädde honom uti ett purpurkläde, och vredo tillhopa ena krono af törne, och satte på honom;',
        18: 'Och begynte till att helsa honom: Hel, Judarnas Konung;',
        19: 'Och slogo hans hufvud med en rö, och spottade på honom; föllo på knä, och tillbådo honom.',
        20: 'Och när de hade så begabbat honom, afklädde de honom purpurklädet, och klädde honom uti sin egen kläder; och ledde honom ut till att korsfästan.',
        21: 'Då tvingade de en man, som der framgick, benämnd Simon af Cyrene, Alexandri och Rufi fader, den af markene inkom, att han måste bära hans kors.',
        22: 'Och de ledde honom på det rummet Golgatha; det är, om man det uttyder, hufvudskallaplatsen.',
        23: 'Och de gåfvo honom bemyrrhadt vin dricka; men han tog det intet till sig.',
        24: 'Och när de hade korsfäst honom, bytte de hans kläder, kastande lott på dem, hvad hvar få skulle.',
        25: 'Och det var vid tredje timman; och de korsfäste honom.',
        26: 'Och det man skyllde honom före, var skrifvet öfver hans hufvud, nämliga: Judarnas Konung.',
        27: 'Och de korsfäste med honom två röfvare, en på hans högra, och den andra på hans venstra sido.',
        28: 'Och så blef Skriften fullbordad, som säger: Ibland ogerningsmän vardt han räknad.',
        29: 'Och de, som gingo der framom, hädde honom, och riste sin hufvud, och sade: Tvi dig! Skönliga slår du omkull templet, och i tre dagar uppbygger det.',
        30: 'Fria dig sjelfvan, och stig neder af korset.',
        31: 'Sammalunda ock de öfverste Presterna gjorde spe af honom emellan sig, med de Skriftlärda, och sade: Androm hafver han hulpit, sig sjelfvom kan han icke hjelpa.',
        32: 'Christus, Israels Konung, stige nu neder af korset, att vi måtte det se, och tro. Och de der korsfäste voro med honom, försmädde honom ock.',
        33: 'Och i sjette timman vardt ett mörker öfver allt landet, till nionde timman.',
        34: 'Och i nionde timman ropade Jesus med höga röst, sägandes: Eloi, Eloi, Lamma Sabachthani? det är uttydt: Min Gud, min Gud, hvi hafver du öfvergifvit mig?',
        35: 'Och somlige, de der när stodo, och hörde det, sade: Si, Eliam kallar han.',
        36: 'Så lopp en till med en svamp, uppfylldan med ättiko; den satte han på en rö, och böd honom dricka, och sade: Håll, låt se, om Elias kommer, till att taga honom neder.',
        37: 'Då ropade Jesus med höga röst, och gaf upp andan.',
        38: 'Och förlåten i templet remnade i tu stycke, ifrån öfverst och neder igenom.',
        39: 'Då höfvitsmannen, som stod der när gentemot honom, såg att han med ett sådant rop gaf upp andan, sade han: Sannerliga var denne mannen Guds Son.',
        40: 'Och voro ock qvinnor der, som långt ifrå detta skådade; ibland hvilka var Maria Magdalena, och Maria, litsle Jacobs och Jose moder, och Salome.',
        41: 'Hvilka ock, medan han var i Galileen, hade följt honom, och tjent honom; och många andra, som med honom uppfarit hade till Jerusalem.',
        42: 'Då aftonen kom, efter det var tillredelsedagen, den som går före Sabbathen,',
        43: 'Kom Joseph, bördig af den staden Arimathia, en ärlig rådherre, den ock vänte efter Guds rike; han tog sig dristighet till, och gick in till Pilatum, och beddes af honom Jesu lekamen.',
        44: 'Då förundrade Pilatus, att han allaredo var död; och kallade till sig höfvitsmannen, och frågade, om han länge sedan död var.',
        45: 'Och då han det förnummit hade af höfvitsmannenom, gaf han Joseph lekamen.',
        46: 'Och han köpte ett linkläde, och tog honom ned, och svepten uti linklädet, och lade honom ned uti ena graf, som uthuggen var uti ett hälleberg; och välte en sten för grafvenes dörr.',
        47: 'Men Maria Magdalena och Maria Jose sågo till hvart han lades.',
    },
    16: {
        1: 'Och då Sabbathen framgången var, köpte Maria Magdalena, och Maria Jacobi, och Salome, välluktande krydder, på det de skulle komma och smörja honom.',
        2: 'Och på den ena Sabbathen kommo de till grafvena, ganska bittida, då solen uppgick;',
        3: 'Och sade emellan sig sjelfva: Ho skall välta oss stenen ifrå grafvenes dörr?',
        4: 'Och då de sågo till, sågo de stenen vara afvältad, den ganska stor var.',
        5: 'Och när de ingångne voro uti grafvena, sågo de en ung man sittandes på högra sidon, klädd i ett sidt hvitt kläde; och de vordo förfärada.',
        6: 'Men han sade till dem: Varer icke förfärada; I söken Jesum af Nazareth, som korsfäst var; han är uppstånden, han är icke här; si rummet, der de hade lagt honom.',
        7: 'Men går bort, och säger hans Lärjungar, och Petro, att han går fram för eder uti Galileen; der skolen I få se honom, såsom han eder sagt hafver.',
        8: 'Och de gingo hasteliga derut, och flydde ifrå grafvene; ty dem var bäfning och häpenhet påkommen; icke heller sade de något för någrom, ty de räddes.',
        9: 'Men när Jesus uppstånden var om morgonen, på första Sabbathsdagen, syntes han först Marie Magdalene, af hvilka han sju djeflar utdrifvit hade.',
        10: 'Hon lopp bort, och bådade dem som plägade vara med honom, de der sörjande och gråtande voro.',
        11: 'Och de samme, när de hörde att han var lefvandes, och var sedder af henne, trodde de intet.',
        12: 'Derefter, då två af dem vandrade ut åt landsbygden, syntes han dem uti en annor skepelse.',
        13: 'Och de gingo ock bort, och bådade det dem androm; och de trodde icke heller dem.',
        14: 'Sedan, när de ellofva såto till bords, syntes han dem, och förekastade dem deras otro och hjertas hårdhet, att de icke trott hade dem, som hade sett honom vara uppstånden;',
        15: 'Och sade till dem: Går ut i hela verldena, och prediker Evangelium allom kreaturom.',
        16: 'Den der tror, och blifver döpt, han skall varda salig; men den der icke tror, han skall varda fördömd.',
        17: 'Men dem, som tro, skola dessa tecken efterfölja: genom mitt Namn skola de utdrifva djeflar; de skola tala med nya tungor;',
        18: 'De skola fördrifva ormar; och om de dricka något det dödeligit är, skall det dem intet skada; på de kranka skola de lägga händerna, så varder det bättre med dem.',
        19: 'Då nu Herren Jesus med dem talat hade, vardt han upptagen i himmelen, och sitter på Guds högra hand.',
        20: 'Men de gingo ut, och predikade allestäds; och Herren verkade med dem, och stadfäste ordet med efterföljande tecken.',
    },
}
