NAME = 'FreOltramare1874: Le Nouveau Testament Version Oltramare 1874'
BOOK = 'Revelation of John'

CHAPTERS = {
    1: {
        1: 'Révélation de Jésus-Christ. Dieu lui a fait cette révélation pour mettre sous les yeux de ses serviteurs les événements qui doivent bientôt arriver; et Jésus ayant envoyé son ange les annoncer à Jean, son serviteur,',
        2: 'celui-ci a rapporté la parole de Dieu et le témoignage de Jésus, toutes choses dont il a eu la vision.',
        3: '— Heureux celui qui lit, et ceux qui entendent les paroles de cette prophétie, et qui observent les recommandations qui y sont faites, car le moment est proche.',
        4: "Jean aux sept églises d'Asie: que la grâce et la paix vous soient données par Celui qui est, qui était et qui va venir, par les sept esprits qui sont devant son trône,",
        5: "et par Jésus-Christ, qui est le témoin fidèle, le premier-né d'entre les morts et le prince des rois de la terre!",
        6: 'A celui qui nous aime, qui nous a délivrés de nos péchés par son sang, et qui nous a faits rois et sacrificateurs de Dieu son Père, à lui soient la gloire et la force aux siècles des siècles! Amen!',
        7: "Le voici qui vient sur les nuées. Tout oeil le verra, et ceux même qui l'ont percé; et toutes les tribus de la terre se frapperont la poitrine en le voyant. Oui. Amen!",
        8: "Je suis l'alpha et l'oméga, dit le Seigneur Dieu, Celui qui est, qui était et qui va venir, le Tout-Puissant.",
        9: "Moi, Jean, qui suis votre frère, et qui ai part avec vous aux afflictions, à la royauté et à la patience en Jésus, j'étais dans l'île de Pathmos, pour la parole de Dieu et le témoignage de Jésus-Christ,",
        10: "lorsque je fus ravi en esprit le jour du Seigneur, et que j'entendis derrière moi une voix éclatante, comme le son d'une trompette,",
        11: 'qui disait: «Ce que tu vois, écris-le dans un livre, et envoie ce livre aux sept églises, à Éphèse, à Smyrne, à Pergame, à Thyatire, à Sardes, à Philadelphie et à Laodicée.»',
        12: "Alors je me tournai pour découvrir quelle était la voix qui me parlait, et, quand je me fus tourné, je vis sept candélabres d'or,",
        13: "et, au milieu des sept candélabres, un être semblable à un fils d'homme: il était vêtu d'une robe qui lui tombait jusqu'aux pieds, et ceint, vers la poitrine, d'une ceinture d'or;",
        14: 'sa tête et ses cheveux étaient blancs comme de la laine blanche, comme de la neige, et ses yeux étaient flamboyants comme du feu;',
        15: "ses pieds étaient semblables à de l'airain qu'on aurait chauffé à blanc dans un fourneau, et sa voix égalait le bruit des grosses eaux.",
        16: 'Il avait sept étoiles dans sa main droite, et de sa bouche sortait une épée aiguë, à deux tranchants, et son visage était comme le soleil, quand il brille dans sa force.',
        17: 'Quand je le vis, je tombai à ses pieds, comme mort. Il posa sa main droite sur moi, en disant: «Ne crains point; je suis le premier et le dernier; je suis le vivant:',
        18: "j'ai été mort, et voici, je suis vivant aux siècles des siècles; même je tiens les clefs de la mort et de l'Hadès.",
        19: 'Mets donc par écrit les choses que tu viens de voir, soit celles qui sont actuellement, soit celles qui doivent arriver ensuite.',
        20: "Voici le mystère des sept étoiles que tu as vues dans ma main droite, et des sept candélabres d'or: les sept étoiles sont les sept anges des sept églises, et les sept candélabres sont les sept églises.»",
    },
    2: {
        1: "«Écris à l'ange de l'église d'Éphèse: «Voici ce que dit celui qui tient les sept étoiles dans sa main droite, celui qui marche au milieu des sept candélabres d'or:",
        2: '«Je connais tes oeuvres, ton labeur et ta constance; je sais que tu ne peux souffrir les méchants; que tu as éprouvé ceux qui se disent apôtres et ne le sont point, et que tu les a trouvés menteurs;',
        3: "que tu as de la constance, car tu as eu à souffrir pour mon nom et tu ne t'en es point lassé.",
        4: "Mais j'ai un reproche à te faire, c'est que tu as abandonné ton premier amour.",
        5: "Souviens-toi donc d'où tu es tombé, repens-toi, et reviens à tes premières oeuvres, sinon je vais aller vers toi, et j'ôterai ton candélabre de sa place, si tu ne te repens.",
        6: "Pourtant tu as une qualité, c'est que tu hais les oeuvres des Nicolaïtes; moi aussi, je les hais.»",
        7: "— Que celui qui a des oreilles entende ce que l'Esprit dit aux églises: «A celui qui vaincra, je lui donnerai à manger de l'arbre de vie, qui est dans le paradis de mon Dieu.»",
        8: "«Écris à l'ange de l'église de Smyrne: «Voici ce que dit celui qui est le premier et le dernier, qui a été mort et qui est revenu à la vie:",
        9: '«Je connais tes oeuvres; je sais la persécution, la pauvreté (pourtant tu es riche) et les insultes que tu endures de la part de ceux qui se disent Juifs et ne le sont point, mais qui sont une synagogue de Satan.',
        10: "Ne redoute pas les souffrances que tu vas éprouver. Voici, le diable va jeter en prison quelques-uns de vous, afin de vous mettre à l'épreuve et de vous faire subir une persécution de dix jours. Sois fidèle jusqu’à la mort, et je te donnerai la couronne de vie.»",
        11: "— Que celui qui a des oreilles, entende ce que l'Esprit dit aux églises: «Celui qui vaincra n'aura point à souffrir la seconde mort.»",
        12: "«Ecris aussi à l’ange de l’église de Pergame: «Voici ce que dit celui qui a l'épée aiguë, à deux tranchants:",
        13: "«Je connais tes oeuvres et je sais où tu habites; c'est là qu'est le trône de Satan. Je sais que tu es fermement attachée mon nom, et que tu n'as point renié ta foi, même au temps où Antipas, mon fidèle témoin, a été mis à mort chez vous, où Satan habite.",
        14: "Mais j'ai un reproche à te faire; c'est que tu gardes là des gens qui retiennent les leçons de Balaam, celui qui enseignait à Balach à mettre une pierre d'achoppement devant les fils d'Israël, en les induisant à manger des viandes sacrifiées aux idoles et à se livrer au libertinage.",
        15: 'De même, tu gardes, toi aussi, des gens qui retiennent pareillement les principes des Nicolaïtes.',
        16: "Repens-toi donc, sinon je vais aller bientôt vers toi, et je leur ferai la guerre avec l'épée de ma bouche.»",
        17: "Que celui qui a des oreilles, entende ce que l'Esprit dit aux églises: «A celui qui vaincra, je lui donnerai de la manne cachée; je lui donnerai encore un caillou blanc; et sur ce caillou est écrit un nom nouveau, que nul ne connaît que celui qui le reçoit.»",
        18: "«Écris aussi à l'ange de l'église de Thyatire: «Voici ce que dit le Fils de Dieu, celui qui a des yeux flamboyants comme du feu, et dont les pieds sont semblables à de l'airain:",
        19: '«Je connais tes oeuvres, ton amour, ta foi, le soin que tu prends des pauvres, ta constance et tes dernières oeuvres plus nombreuses que les premières.',
        20: "Mais j'ai un reproche à t'adresser, c'est que tu laisses faire ta femme Jésabel, cette soi-disant prophétesse qui enseigne et qui séduit mes serviteurs, les entraînant à se livrer au libertinage et à manger des viandes sacrifiées aux idoles.",
        21: 'Je lui ai donné du temps pour se repentir; néanmoins elle ne veut pas se repentir de son libertinage.',
        22: "Voici, je vais la jeter sur un lit de douleur, et plonger ses compagnons d'adultère dans une grande détresse, à moins qu'ils ne se repentent des oeuvres qu'elle leur a enseignées.",
        23: 'Je détruirai ses enfants par la mort, et toutes les églises connaîtront que je suis celui qui sonde les reins et les coeurs; et je rendrai à chacun selon ses oeuvres.',
        24: "Quant à vous autres qui ne partagez pas ces principes, qui n'avez pas connu les profondeurs de Satan (comme ils les appellent), je vous dis: «Je ne vous impose, pas de nouvelle charge;",
        25: 'seulement, tenez ferme ce que vous avez, jusqu’à ce que je vienne.»',
        26: '— «Et à celui qui vaincra et qui aura accompli jusqu’à la fin les oeuvres que je commande, je lui donnerai pouvoir sur les Gentils;',
        27: "et il les gouvernera avec une verge de fer, les brisant comme on brise des vases d'argile, ainsi que j'en ai moi-même reçu le pouvoir de mon Père;",
        28: "et je lui donnerai l'étoile du matin.»",
        29: "Que celui qui a des oreilles entende ce que l'Esprit dit aux églises.",
    },
    3: {
        1: "Écris aussi à l'ange de l'église de Sardes: «Voici ce que dit celui qui a les sept esprits de Dieu et les sept étoiles: «Je connais tes oeuvres: tu as le renom de vivre, pourtant tu es mort.",
        2: "Sois vigilant et affermis le reste qui s'en va mourir; car je n'ai pas trouvé tes oeuvres parfaites devant mon Dieu.",
        3: 'Souviens-toi donc de quelle manière tu as reçu et entendu la Parole; garde-la, et repens-toi. Si tu ne veilles pas, je viendrai comme un voleur, et tu ne sais point à quelle heure je viendrai te surprendre.',
        4: "Toutefois, tu as à Sardes quelques personnes qui n'ont pas souillé leurs vêtements, eh bien! elles marcheront avec moi en vêtements blancs, parce qu'elles en sont dignes.»",
        5: "— «Celui qui vaincra, sera ainsi paré de vêtements blancs; je n'effacerai point son nom du livre de vie, et je confesserai son nom devant mon Père et devant ses anges.»",
        6: "Que celui qui a des oreilles entende ce que l'Esprit dit aux églises.",
        7: "«Écris aussi à l'ange de l'église de Philadelphie: «Voici ce que dit le Saint, le Vrai, celui qui a la clef de David, celui qui ouvre et personne ne ferme, qui ferme et personne n'ouvre:",
        8: "«Je connais tes oeuvres: voici, j'ai ouvert devant toi une porte que personne ne peut fermer; je l'ai fait parce que tu as peu de puissance, que tu as gardé ma parole et que tu n'as pas renié mon nom.",
        9: "Voici, je te donne quelques membres de la synagogue de Satan, quelques-uns de ceux qui se disent Juifs: ils ne le sont point, mais ils mentent. Je ferai en sorte qu'ils viennent eux-mêmes, qu'ils se prosternent à tes pieds et qu'ils sachent que je t'ai aimé.",
        10: "Parce que tu as gardé ma parole avec constance, moi aussi je te garderai de l'heure de l’épreuve qui va venir sur le monde entier pour éprouver les habitants de la terre.",
        11: 'Je viendrai bientôt: tiens ferme ce que tu as, afin que personne ne te ravisse ta couronne.»',
        12: "— «Celui qui vaincra, je ferai de lui une colonne dans le sanctuaire de mon Dieu, et il n'en sortira jamais; j'écrirai aussi sur lui le nom de mon Dieu, et le nom de la ville de mon Dieu, de la nouvelle Jérusalem qui va descendre du ciel d'auprès de mon Dieu, et mon nom nouveau.»",
        13: "Que celui qui a des oreilles, entende ce que l'Esprit dit aux églises.",
        14: "«Écris aussi à l'ange de l'église de Laodicée: «Voici ce que dit l'Amen, le témoin fidèle et véritable, le chef des créatures de Dieu:",
        15: "«Je connais tes oeuvres: tu n'es ni froid ni bouillant. Plût à Dieu que tu fusses froid ou bouillant!",
        16: "Ainsi, parce que tu es tiède, et que tu n'es ni froid ni bouillant, je te vomirai de ma bouche.",
        17: "Tu dis: «Je suis riche, j'ai acquis de grands biens; je n'ai besoin de rien;» tu ne sais donc pas que tu es, toi, le malheureux, le misérable; que tu es pauvre, aveugle et nu.",
        18: "Je te conseille d'acheter de moi de l'or affiné au feu, afin que tu sois riche, — et des vêtements blancs pour te vêtir, pour ne pas laisser voir la honte de ta nudité, — et un collyre pour oindre tes yeux, afin que tu voies.",
        19: "Pour moi, je reprends et je châtie tous ceux que j'aime; aie donc du zèle et repens-toi.",
        20: "Voici, je me tiens à la porte et je frappe: si quelqu'un entend ma voix et ouvre la porte, j'entrerai chez lui, je souperai avec lui et lui avec moi.»",
        21: "— «Celui qui vaincra, je le ferai asseoir avec moi sur mon trône, comme moi-même, j'ai vaincu et je me suis assis avec mon Père sur son trône.»",
        22: "Que celui qui a des oreilles entende ce que l'Esprit dit aux églises.",
    },
    4: {
        1: "Après cela, je regardai, et voici, une porte était ouverte dans le ciel, et la première voix que j'avais entendue, comme le son d'une trompette, et qui m'avait parlé, disait: «Monte ici, je te ferai voir ce qui doit arriver dans la suite.»",
        2: "— Aussitôt je fus ravi en esprit; et voici, un trône était dressé dans le ciel, et sur ce trône, quelqu'un était assis.",
        3: "Celui qui était assis, avait l'aspect d'une pierre de jaspe et de cornaline; et le trône était environné d'un arc-en-ciel de la couleur de l'émeraude.",
        4: "Tout autour du trône étaient vingt-quatre trônes, et je vis des vieillards assis sur ces vingt-quatre trônes: ils étaient vêtus de blanc, et avaient des couronnes d'or sur la tête.",
        5: 'Du trône sortent des éclairs, des bruits et des tonnerres; et sept lampes ardentes brûlent devant le trône: ce sont les sept esprits de Dieu.',
        6: "Devant le trône, s'étend comme une mer de verre semblable à du cristal; et au milieu de chacun des quatre côtés du trône se tient un animal couvert d'yeux devant et derrière:",
        7: "le premier animal ressemble à un lion, le second ressemble à un jeune taureau, le troisième a la face comme celle d'un homme, et le quatrième animal ressemble à un aigle qui vole.",
        8: "Ces quatre animaux ont chacun six ailes; ils sont couverts d'yeux tout autour du corps et sous les ailes, et ils ne cessent jour et nuit de dire: «Saint, saint, saint est le Seigneur Dieu, le Tout Puissant, Celui qui était, qui est et qui va venir!»",
        9: 'Et toutes les fois que les animaux rendent gloire, honneur et actions de grâces à celui qui est assis sur le trône, à celui qui vit aux siècles des siècles,',
        10: 'les vingt-quatre vieillards se prosternent devant celui qui est assis sur le trône, et adorent celui qui vit aux siècles des siècles, et ils jettent leurs couronnes devant le trône, en disant:',
        11: "«Tu es digne, notre Seigneur et notre Dieu, de recevoir la gloire, l'honneur et la puissance, car c'est toi qui as créé toutes choses, c'est par ta volonté qu'elles ont eu l'être, qu'elles ont été créées.»",
    },
    5: {
        1: 'Puis je vis dans la main droite de celui qui était assis sur le trône un rouleau écrit en dedans et en dehors, scellé de sept sceaux.',
        2: "Ensuite je vis un ange vigoureux, qui criait d'une voix forte: «Qui est-ce qui est digne d'ouvrir le livre et d'en rompre les sceaux?",
        3: "Et personne, ni dans le ciel, ni sur la terre, ni sous la terre, ne pouvait ouvrir le livre ni voir ce qu'il contenait.",
        4: "Pour moi, je me mis à fondre en larmes, de ce qu'il ne se trouvait personne qui fût digne d'ouvrir le livre, ni de voir ce qu'il contenait.",
        5: "Alors un des vieillards me dit: «Ne pleure point; voici, il a vaincu, le lion de la tribu de Juda, le rejeton de David, c'est lui qui va ouvrir le livre et briser les sept sceaux.»",
        6: "Et je vis, debout près du trône, entre les quatre animaux et les vieillards, un agneau qu'on aurait dit avoir été immolé: il avait sept cornes et sept yeux qui sont les sept esprits de Dieu envoyés par toute la terre.",
        7: "Il s'avança, et prit le livre de la main droite de celui qui était assis sur le trône;",
        8: "et quand il eut pris le livre, les quatre animaux et les vingt-quatre vieillards se prosternèrent devant l'agneau. Ils avaient tous des harpes, et des coupes d'or pleines de parfums, qui sont les prières des saints;",
        9: "et ils chantaient un cantique nouveau, disant: «Tu es digne de prendre le livre et d'en briser les sceaux, car tu as été immolé; et, par ton sang, tu as acheté pour Dieu des gens de toute tribu, de toute langue, de tout peuple et de toute nation;",
        10: 'et tu les as faits rois et sacrificateurs, et ils vont régner sur la terre.»',
        11: "Et je vis, et j'entendis tout autour du trône, autour des animaux et des vieillards, la voix d'une multitude d'anges: le nombre de ces anges s'élevait à des myriades de myriades et des milliers de milliers,",
        12: "et ils disaient d'une voix forte: «L'agneau qui a été immolé, est digne de recevoir la puissance, la richesse, la sagesse, la force, l'honneur, la gloire et la louange.»",
        13: "Et j'entendis toutes les créatures, dans le ciel, sur la terre, sous la terre, sur la mer, et les choses qui y sont, je les entendis toutes, qui disaient: «A celui qui est assis sur le trône et à l'agneau, soient la louange, l'honneur, la gloire et la force aux siècles des siècles!»",
        14: 'Et les quatre animaux disaient: «Amen!» Et les vieillards se prosternèrent et adorèrent.',
    },
    6: {
        1: "Quand l'agneau eut brisé l'un des sept sceaux, j'entendis l'un des quatre animaux, qui disait comme d'une voix de tonnerre: «Viens.»",
        2: 'Et je vis paraître un cheval blanc. Celui qui le montait avait un arc, on lui donna une couronne, et il partit en vainqueur pour aller remporter la victoire.',
        3: "Quand l'agneau eut brisé le deuxième sceau, j'entendis le second animal qui disait: «Viens,»",
        4: "Et il sortit un autre cheval, qui était rouge. Celui qui le montait, reçut le pouvoir d'ôter la paix de dessus la terre, afin que ses habitants s’entr’égorgeassent; et on lui donna une grande épée.",
        5: "Quand l'agneau eut brisé le troisième sceau, j'entendis le troisième animal qui disait: «Viens.» Et je vis paraître un cheval noir. Celui qui le montait tenait une balance à la main;",
        6: "et j'entendis au milieu des quatre animaux, comme une voix qui disait: «A un denier le chénice de froment! A un denier les trois chénices d'orge!» — et: «Ne gâte pas l'huile, ni le vin.»",
        7: "Quand l'agneau eut brisé le quatrième sceau, j'entendis la voix du quatrième animal qui disait: «Viens.»",
        8: "Et je vis paraître un cheval de couleur pâle. Celui qui le montait se nommait la Mort, l'Hadès le suivait. On leur donna le pouvoir sur le quart de la terre, pour en faire périr les habitants par l’épée, par la famine, par la mortalité et par les bêtes féroces.",
        9: "Quand l'agneau eut brisé le cinquième sceau, je vis sous l'autel les âmes de ceux qui avaient été immolés pour avoir gardé la parole de Dieu et le témoignage de Jésus.",
        10: "Et elles crièrent d'une voix forte: «Maître, toi qui es saint et véritable, jusques à quand différeras-tu de faire justice et de demander compte de notre sang à ceux qui habitent sur la terre?»",
        11: 'Alors on leur donna à chacun une robe blanche, et on leur dit de demeurer en repos encore un peu de temps, jusqu’à ce que fût complet le nombre de leurs compagnons de service et de leurs frères, qui devaient être mis à mort comme eux.',
        12: "Quand l'agneau eut brisé le sixième sceau, je regardai, et il se fit un grand tremblement de terre: le soleil devint noir comme un sac de crin, la lune tout entière parut comme du sang,",
        13: "et les étoiles du ciel tombèrent sur la terre, comme les figues vertes tombent d'un figuier secoué par un gros vent.",
        14: "Le ciel se retira comme un parchemin qu'on enroule, et toutes les montagnes et les îles furent remuées de leur place.",
        15: 'Et les rois de la terre, les grands, les généraux, les riches, les hommes forts, tout esclave et tout homme libre se cachèrent dans les cavernes et dans les rochers des montagnes,',
        16: "et ils disaient aux montagnes et aux rochers: «Tombez sur nous et dérobez-nous à la vue de celui qui est assis sur le trône, et à la colère de l'agneau;",
        17: 'car il est venu, le grand jour de sa colère, et qui peut subsister?»',
    },
    7: {
        1: "Ensuite je vis quatre anges qui étaient debout aux quatre coins de la terre et qui retenaient les quatre vents de la terre, afin qu'aucun vent ne soufflât, ni sur la terre, ni sur la mer, ni sur aucun arbre.",
        2: "Et je vis un autre ange qui montait du côté où se lève le soleil; il tenait le sceau du Dieu vivant, et il cria d'une voix forte aux quatre anges à qui il avait été donné de sévir contre la terre et contre la mer,",
        3: 'disant: «Ne sévissez pas encore contre la terre, ni contre la mer, ni contre les arbres, jusqu’à ce que nous ayons marqué au front les serviteurs de notre Dieu.',
        4: "Et j'entendis que le nombre de ceux qui avaient été marqués, était de cent quarante-quatre mille, choisis dans toutes les tribus des fils d'Israël:",
        5: 'dans la tribu de Juda douze mille de marqués; dans la tribu de Ruben, douze mille; dans la tribu de Gad, douze mille;',
        6: "dans la tribu d'Asser, douze mille; dans la tribu de Nephthali, douze mille; dans la tribu de Manassé, douze mille;",
        7: "dans la tribu de Syméon, douze mille; dans la tribu de Lévi, douze mille; dans la tribu d'Issachar, douze mille;",
        8: 'dans la tribu de Zabulon, douze mille; dans la tribu de Joseph, douze mille; dans la tribu de Benjamin douze mille de marqués.',
        9: "Ensuite je vis une foule immense, que personne n'aurait pu compter, composée de gens de toute nation, de toute tribu, de tout peuple et de toute langue, qui étaient debout devant le trône et devant l'agneau: ils étaient vêtus de robes blanches, et tenaient des palmes dans leurs mains,",
        10: "ils criaient d'une voix forte, disant: «Le salut vient de notre Dieu qui est assis sur le trône, et de l'agneau.»",
        11: 'Tous les anges étaient debout autour du trône, autour des vieillards et des quatre animaux; ils se prosternèrent devant le trône et adorèrent Dieu,',
        12: 'disant: «Amen! Louange, gloire, sagesse, actions de grâces, honneur, puissance, et force à notre Dieu, aux siècles des siècles!»',
        13: "Alors un des vieillards prenant la parole, me dit: «Ceux qui sont vêtus de robes blanches, qui sont-ils et d'où viennent-ils?",
        14: "Je lui dis: «Mon Seigneur, tu le sais.» Et il me dit: «Ce sont ceux qui viennent de la grande tribulation; ils ont lavé leurs robes et les ont blanchies dans le sang de l'agneau.",
        15: "C'est pour cela qu'ils sont devant le trône de Dieu, et qu'ils servent Dieu jour et nuit dans son sanctuaire. Et celui qui est assis sur le trône les abritera:",
        16: "ils n'auront plus faim, ils n'auront plus soif; le soleil ni aucune chaleur brûlante ne les accablera;",
        17: "car l'agneau qui est là au milieu, devant le trône, les paîtra, et les conduira aux sources des eaux de la vie; et Dieu essuiera toute larme de leurs yeux.»",
    },
    8: {
        1: "Lorsqu'il eut brisé le septième sceau, il se fit dans le ciel un silence d'environ une demi-heure.",
        2: 'Et je vis les sept anges qui se tiennent en la présence de Dieu, et on leur donna sept trompettes.',
        3: "Puis il vint un autre ange qui se tint debout sur l'autel, un encensoir d'or à la main: on lui donna une quantité de parfums, afin qu'il les mêlât aux prières de tous les saints, sur l'autel d'or qui est devant le trône;",
        4: "et la fumée des parfums, mêlée aux prières des saints, monta de la main de l'ange devant Dieu.",
        5: "Et l'ange prit l'encensoir, le remplit du feu de l'autel et jeta ce feu sur la terre, et il y eut des bruits, des tonnerres, des éclairs, et la terre trembla.",
        6: 'Et les sept anges qui avaient les sept trompettes, se préparèrent à en sonner.',
        7: "Le premier sonna de la trompette, et il y eut de la grêle et du feu, mêlés de sang, qui furent jetés sur la terre. Et le tiers de la terre, ainsi que le tiers des arbres, et toute l'herbe verte furent consumés.",
        8: 'Le second ange sonna de la trompette, et une masse semblable à une grosse montagne ardente fut jetée dans la mer. Et le tiers de la mer fut changé en sang,',
        9: 'et le tiers des créatures marines qui ont vie, périt, et le tiers des navires fut détruit.',
        10: 'Le troisième ange sonna de la trompette, et une grosse étoile enflammée comme une torche, tomba du ciel sur le tiers des fleuves et sur les sources des eaux.',
        11: "Le nom de cette étoile est Absinthe. Et le tiers des eaux fut changé en absinthe, et une multitude d'hommes moururent de ces eaux, parce qu'elles avaient été rendues amères.",
        12: "Le quatrième ange sonna de la trompette, et le tiers du soleil fut frappé, ainsi que le tiers de la lune et le tiers des étoiles, afin que le tiers de chacun d'eux fut rendu obscur et que la clarté du jour fût réduite d'un tiers, et celle de la nuit pareillement.",
        13: "Et je regardai, et j'entendis un aigle qui volait dans le haut des airs, disant d'une voix forte: Malheur! Malheur! Malheur à ceux qui habitent sur la terre, à cause du son des trompettes, dont les trois autres anges vont sonner!",
    },
    9: {
        1: "Et le cinquième ange sonna de la trompette, et je vis une étoile qui était tombée du ciel sur la terre, et on lui donna la clef du puits de l'abîme.",
        2: "Elle ouvrit le puits de l'abîme, et il s'éleva du puits une fumée comme celle d'un grand fourneau, et le soleil et l'atmosphère furent obscurcis par la fumée du puits;",
        3: 'de cette fumée, il sortit des sauterelles qui se répandirent sur la terre: on leur donna un pouvoir pareil à celui des scorpions de la terre,',
        4: "et on leur commanda de ne point faire de mal à l'herbe de la terre, ni à la verdure, ni à aucun arbre, mais seulement aux hommes qui n'ont pas le sceau de Dieu sur le front.",
        5: "Il leur fut donné, non de les tuer, mais de les tourmenter durant cinq mois; et le tourment qu'elles faisaient éprouver était pareil à celui que cause à un homme la piqûre du scorpion.",
        6: "En ces jours-là, les hommes chercheront la mort, et ils ne la trouveront pas; ils souhaiteront de mourir, et la mort fuira loin d'eux.",
        7: "Ces sauterelles ressemblaient à des chevaux caparaçonnés pour le combat: elles avaient sur la tête comme des diadèmes d'or, leurs visages étaient comme des visages d'hommes,",
        8: 'leurs cheveux comme des cheveux de femmes, et leurs dents comme des dents de lions.',
        9: 'Elles avaient des poitrines comme des cuirasses de fer, et le bruit de leurs ailes était comme un bruit de chariots à plusieurs chevaux qui courent au combat.',
        10: "Elles ont des queues semblables à celles des scorpions, et des aiguillons; c'est dans leurs queues qu'est leur pouvoir de faire aux hommes un mal qui dure cinq mois.",
        11: "Elles ont à leur tête, comme roi, l'ange de l'abîme, qui se nomme en hébreu, Abaddon, et en grec, Apollyon.",
        12: 'Ce premier «malheur!» est passé; en voici venir encore deux autres après lui.',
        13: "Le sixième ange sonna de la trompette, et j'entendis une voix sortir des cornes de l'autel d'or qui est devant Dieu.",
        14: 'Elle disait au sixième ange qui avait la trompette: «Délie les quatre anges qui sont liés au bord du grand fleuve de l’Euphrate.»',
        15: "Alors furent déliés les quatre anges qui s'étaient tenus prêts pour l'heure, le jour, le mois et l'année, où ils devaient tuer le tiers des hommes.",
        16: "Les corps de cavalerie de ces anges s'élevaient à deux cents millions de cavaliers: j'en entendis articuler le nombre.",
        17: "Et voici comment les chevaux me parurent dans la vision, ainsi que ceux qui les montaient: les cavaliers avaient des cuirasses couleur de feu, d'hyacinthe et de soufre; les têtes des chevaux étaient comme des têtes de lions et leur bouche jetait du feu, de la fumée et du soufre.",
        18: 'Le tiers des hommes fut tué par ces trois fléaux, par le feu, par la fumée, et par le soufre qui sortaient de la bouche des chevaux,',
        19: "car la puissance de ces chevaux est dans leur bouche et dans leur queue: ces queues, semblables à des serpents, ont des têtes, et c'est avec ces queues qu'ils blessent.",
        20: "Les autres hommes qui ne furent pas tués par ces fléaux, ne se repentirent point des oeuvres de leurs mains: ils ne cessèrent pas d'adorer les démons, ni les idoles d'or, d'argent, d'airain, de pierre, de bois, qui ne peuvent ni voir, ni entendre, ni marcher;",
        21: 'ils ne se repentirent ni de leurs meurtres, ni de leurs enchantements, ni de leurs débauches, ni de leurs vols.',
    },
    10: {
        1: "Je vis un autre ange vigoureux, qui descendait du ciel, enveloppé d'un nuage; l'arc-en-ciel brillait au-dessus de sa tête; son visage était comme le soleil, et ses pieds étaient comme des colonnes de feu.",
        2: 'Il tenait à la main un petit livre ouvert; il posa le pied droit sur la mer et le pied gauche sur la terre;',
        3: "puis il poussa un cri d'une voix forte, comme un lion qui rugit, et, quand il eut poussé ce cri, les sept tonnerres firent entendre leurs voix.",
        4: "Après que les tonnerres eurent parlé, je me disposais à écrire, lorsque j'entendis une voix qui venait du ciel, et qui me disait: «Tiens secret ce qu'ont dit les sept tonnerres, ne l'écris point.»",
        5: "Alors l'ange que j'avais vu debout sur la mer et sur la terre, leva sa main droite vers le ciel,",
        6: "et jura par celui qui vit aux siècles des siècles, qui a créé le ciel et les choses qui y sont, la terre et les choses qui y sont, et la mer et les choses qui y sont, qu'il n'y aurait plus de délai,",
        7: "mais qu'aux jours où le septième ange ferait entendre sa voix en sonnant de la trompette, le mystère de Dieu s'accomplirait aussi, comme il l'a annoncé à ses serviteurs, les prophètes.",
        8: "Et la voix que j'avais entendue venant du ciel, me parla de nouveau, et me dit: «Va, prends le petit livre ouvert dans la main de l'ange qui se tient debout sur la mer et sur la terre.»",
        9: "J'allai donc vers l'ange, et je lui demandai le petit livre, et il me dit: «Prends-le et l'avale; il sera amer à tes entrailles, mais ta bouche le trouvera doux comme du miel.»",
        10: "Je pris le petit livre de la main de l'ange, et je l'avalai; il fut doux à ma bouche comme du miel, puis, quand je l'eus avalé, je sentis de l'amertume dans les entrailles.",
        11: 'Et l’on me dit: «Il faut que tu prophétises de nouveau sur des peuples, des nations, des langues diverses et des rois en grand nombre.»',
    },
    11: {
        1: "Alors on me donna un roseau semblable à un bâton, en me disant: «Lève-toi, et mesure le sanctuaire de Dieu, l'autel, et l'espace occupé par les adorateurs.",
        2: 'Quant au parvis extérieur du sanctuaire, laisse-le en dehors, ne le mesure pas, car il a été abandonné aux nations: elles fouleront aux pieds la ville sainte pendant quarante-deux mois.',
        3: 'Et je donnerai à mes deux témoins de prophétiser, et, revêtus de sacs, ils prophétiseront pendant douze cent soixante jours.',
        4: 'Ces deux témoins sont les deux oliviers et les deux candélabres qui sont devant le Seigneur de la terre.',
        5: "Si quelqu'un veut leur faire du mal, il sort de leur bouche un feu qui dévore leurs ennemis: c'est ainsi que doit périr quiconque voudra leur faire du mal.",
        6: "Ils ont le pouvoir de fermer le ciel, afin qu'il ne tombe point de pluie pendant les jours de leur prédication. Ils ont aussi le pouvoir de changer les eaux en sang, et de frapper la terre de toutes sortes de plaies, aussi souvent qu'ils le voudront.",
        7: 'Quand ils auront achevé de rendre leur témoignage, la bête qui monte de l’abîme leur fera la guerre, les vaincra et les tuera;',
        8: "et leurs cadavres resteront gisant dans la rue de la grande ville qui est appelée figurément Sodome et Egypte; c'est là que leur Seigneur même a été crucifié.",
        9: "Des gens de tout peuple, de toute tribu, de toute langue et de toute nation regardent leurs cadavres pendant trois jours et demi, sans permettre qu'on leur donne la sépulture.",
        10: "Les habitants de la terre sont dans la joie de ce qui est arrivé aux prophètes; ils se livrent à l'allégresse et s'envoient des présents les uns aux autres, parce que ces deux prophètes ont fait le tourment de ceux qui habitent sur la terre.",
        11: "Au bout de trois jours et demi, un esprit de vie venant de Dieu, pénètre dans ces cadavres; ils se dressent sur leurs pieds; et une grande terreur s'empare de ceux qui les regardaient.",
        12: "Et j'entendis une voix forte qui venait du ciel, et qui disait aux prophètes: «Montez ici.» Et ils montèrent au ciel dans la nuée, et leurs ennemis les virent.",
        13: "En ce même moment, il se fit un grand tremblement de terre; la dixième partie de la ville s'écroula, et sept mille personnes périrent dans ce tremblement de terre; toutes les autres, saisies d'effroi, rendirent gloire au Dieu du ciel.",
        14: 'Le second «malheur!» est passé; voici venir bientôt le troisième.',
        15: "Le septième ange sonna de la trompette, et des voix fortes se firent entendre dans le ciel, et elles disaient: «L'empire du monde appartient maintenant à notre Seigneur et à son Oint, et il régnera aux siècles des siècles.»",
        16: 'Et les vingt-quatre vieillards, qui sont assis devant Dieu sur leurs trônes, se prosternèrent et adorèrent Dieu,',
        17: "en disant: «Nous te rendons grâces, Seigneur Dieu, Tout-Puissant, toi qui es et qui étais, de ce que tu t'es armé de ta grande puissance et de ce que tu es entré dans ton règne.",
        18: 'Les nations se sont irritées, et ta colère est venue. Et il est venu, le moment de juger les morts, de donner la récompense à tes serviteurs, aux prophètes, aux saints, à ceux qui craignent ton nom, petits et grands, et de perdre ceux qui perdent la terre.»',
        19: "Alors le sanctuaire de Dieu, qui est dans le ciel, s'ouvrit, et l’on vit l'arche de l'alliance dans son sanctuaire. Et il y eut des éclairs, des bruits, des tonnerres, un tremblement de terre et une forte grêle.",
    },
    12: {
        1: 'Et il parut dans le ciel un grand prodige, une femme enveloppée de la lumière du soleil, ayant la lune sous ses pieds, et sur sa tête une couronne de douze étoiles.',
        2: "Elle était enceinte, et elle criait, parce qu'elle était dans le travail et les douleurs de l'enfantement.",
        3: 'Un autre prodige parut aussi dans le ciel: tout à coup on vit un grand dragon rouge; il avait sept têtes et dix cornes, et sur ses têtes sept diadèmes;',
        4: "de sa queue, il entraînait le tiers des étoiles du ciel, et il les jeta sur la terre; et il se dressa devant la femme qui allait enfanter, afin de dévorer son enfant, dès qu'elle l'aurait mis au monde.",
        5: "La femme donna le jour à un fils, un enfant mâle, qui devait gouverner toutes les nations avec une verge de fer. L'enfant fut enlevé auprès de Dieu et vers son trône,",
        6: "et la femme s'enfuit au désert, où Dieu lui avait préparé une retraite, afin qu'elle y fût nourrie pendant douze cent soixante jours.",
        7: "Alors il y eut un combat dans le ciel: Michel et ses anges s'avancèrent pour combattre le dragon; et le dragon et ses anges combattirent,",
        8: "mais ils ne purent vaincre, et la place même qu'ils occupaient ne se retrouva plus dans le ciel.",
        9: 'Il fut précipité, le grand dragon, le serpent ancien, celui qui est appelé le diable et Satan, le séducteur de toute la terre, il fut précipité sur la terre, et ses anges avec lui.',
        10: "Et j'entendis dans le ciel une voix forte, qui disait: «Maintenant, le salut, la puissance et l'empire appartiennent à notre Dieu, et l'autorité, à son Oint; car il a été précipité, l'accusateur de nos frères, celui qui les accusait jour et nuit devant notre Dieu.",
        11: "Eux aussi l'ont vaincu par le sang de l'agneau et par la fermeté de leur témoignage, ayant renoncé à l'amour de la vie, jusqu’à souffrir la mort.",
        12: "C'est pourquoi, tressaillez de joie, cieux, et vous qui les habitez! Malheur à la terre et à la mer! parce que le diable est descendu vers vous, plein d'une grande fureur, sachant qu'il ne lui reste que peu de temps.»",
        13: "Lorsque le dragon se vit précipité sur la terre, il poursuivit la femme qui avait mis au monde l'enfant mâle;",
        14: "mais la femme reçut deux ailes de grand aigle, pour s'envoler au désert, en sa retraite, où elle devait être nourrie pendant un temps, des temps et la moitié d'un temps, loin de la vue du dragon.",
        15: "Alors le dragon lança de sa gueule, après la femme, de l'eau comme un fleuve, pour l'entraîner dans le fleuve;",
        16: "mais la terre vint au secours de la femme, elle s'entr'ouvrit, et engloutit le fleuve que le dragon avait vomi de sa gueule.",
        17: "Et le dragon fut transporté de fureur contre la femme; il alla faire la guerre au reste de ses enfants, à ceux qui observent les commandements de Dieu et qui gardent le témoignage de Jésus; et il s'arrêta sur le sable de la mer.",
    },
    13: {
        1: 'Je vis alors monter de la mer, une bête féroce qui avait dix cornes et sept têtes, et sur ses cornes, dix diadèmes, et sur ses têtes, un nom de blasphème.',
        2: "La bête que je vis, ressemblait à un léopard; ses pieds étaient comme ceux d'un ours, et sa gueule comme une gueule de lion. Le dragon lui donna sa puissance, son trône et une grande autorité.",
        3: "On aurait dit que l'une de ses têtes avait été blessée à mort, mais sa blessure mortelle avait été guérie.",
        4: "Tous les habitants de la terre, saisis d'admiration, suivaient la bête; ils adorèrent le dragon, parce qu'il avait donné l'autorité à la bête, et ils adorèrent la bête, en disant: «Qui est semblable à la bête, et qui peut se mesurer avec elle?»",
        5: "On lui donna une bouche qui profère des paroles arrogantes et blasphématoires, et le pouvoir d'agir pendant quarante-deux mois.",
        6: 'Elle ouvrit donc la bouche pour blasphémer contre Dieu, pour blasphémer son nom, son tabernacle, et ceux qui habitent dans le ciel.',
        7: 'Et on lui donna de faire la guerre aux saints et de les vaincre, ainsi que le pouvoir sur toute tribu, tout peuple, toute langue et toute nation:',
        8: "et tous les habitants de la terre l'adoreront, ceux du moins dont le nom n'a pas été écrit, dès la fondation du monde, dans le livre de vie de l'agneau qui a été immolé.",
        9: 'Que celui qui a des oreilles entende.',
        10: "Celui qui mène en captivité, sera mené lui-même en captivité; celui qui tue par l'épée, doit être tué lui-même par l'épée. C'est ici que la patience et la foi des saints doivent se montrer.",
        11: "Je vis ensuite monter de la terre une autre bête féroce qui avait deux cornes semblables à celles d'un agneau, et qui parlait comme un dragon.",
        12: "Elle exerçait toute l'autorité de la première bête, sous ses yeux, et elle amenait la terre et ses habitants à adorer la première bête, dont la blessure mortelle avait été guérie;",
        13: 'elle opérait aussi de grands prodiges, jusqu’à faire descendre du ciel du feu sur la terre, à la vue des hommes.',
        14: "Séduisant les habitants de la terre par les prodiges qu'il lui avait été donné d'opérer sous les yeux de la bête, elle leur persuada de faire une image en l'honneur de la bête qui porte la blessure du glaive, et qui a repris vie.",
        15: "Et il lui fut donné d'animer l'image de la bête, afin que cette image parlât, et qu'elle fît mettre à mort tous ceux qui n'adoreraient pas l'image de la bête.",
        16: "Elle amena tous les hommes, petits et grands, riches et pauvres, libres et esclaves, à s'imprimer eux-mêmes une marque sur la main droite ou sur le front,",
        17: "afin que nul ne pût acheter ni vendre, s'il n'avait pas la marque, savoir le nom de la bête ou le nombre de son nom.",
        18: "C'est ici que la sagesse doit se montrer. Que celui qui a de l'intelligence, calcule le nombre de la bête, car c'est le nombre d'un homme, et son nombre est six cent soixante-six.",
    },
    14: {
        1: "Puis je regardai, et voici, l'agneau était sur la montagne de Sion, et avec lui cent quarante-quatre mille personnes, qui avaient son nom et le nom de son Père, écrits sur leurs fronts.",
        2: "Et j'entendis une voix qui venait du ciel, forte comme le bruit des grosses eaux et comme celui d'un puissant tonnerre, et harmonieuse comme le son des harpes jouées par des musiciens.",
        3: 'On chantait un cantique nouveau devant le trône et devant les quatre animaux et les vieillards: nul ne pouvait apprendre ce cantique, que les cent quarante-quatre mille qui ont été achetés de la terre.',
        4: "Ceux-ci ne se sont point souillés avec des femmes, car ils sont vierges ceux qui accompagnent l'agneau partout où il va; ils ont été achetés d'entre les hommes, comme des prémices consacrées à Dieu et à l'agneau;",
        5: "et il ne s'est point trouvé de mensonge dans leur bouche, car ils sont irréprochables.",
        6: "Après cela, je vis un autre ange qui volait dans le haut des airs, tenant un évangile éternel, pour l'annoncer à ceux qui sont sur la terre, à toute nation, à toute tribu, à toute langue et à tout peuple.",
        7: "Il disait d'une voix forte: «Craignez Dieu et lui donnez gloire, car l'heure de son jugement est venue; adorez celui qui a fait le ciel, la terre, la mer et les sources d'eau.»",
        8: 'Et un autre ange, un second, suivit, qui disait: «Elle est tombée, elle est tombée, Babylone la grande, celle qui a abreuvé toutes les nations du vin de la fureur de son libertinage.»',
        9: "Et un autre ange, un troisième, les suivit, qui disait d'une voix forte: «Si quelqu'un adore la bête et son image, et en prend la marque sur son front ou sur sa main,",
        10: "il boira, lui aussi, du vin de la fureur de Dieu, du vin pur versé dans la coupe de sa colère; et il sera tourmenté dans le feu et le soufre sous les yeux des saints anges et de l'agneau.",
        11: "La fumée de son supplice s'élèvera aux siècles des siècles; et il n'y aura de repos, ni jour ni nuit, pour ceux qui adorent la bête et son image, ni pour quiconque aura pris la marque de son nom.»",
        12: "C'est ici que doit se montrer la patience des saints qui gardent les commandements de Dieu et la foi en Jésus.",
        13: "Alors j'entendis une voix venant du ciel, qui disait: «Ecris: Heureux dès à présent ceux qui meurent dans le Seigneur!» — «Oui,» dit l'Esprit, «ils se reposent de leurs travaux, et leurs oeuvres les suivent.»",
        14: "Puis je regardai, et voici, une nuée blanche parut, et sur la nuée était assis quelqu'un qui ressemblait à un fils d'homme; il avait sur la tête une couronne d'or, et dans sa main une faucille tranchante.",
        15: "Et un autre ange sortit du sanctuaire, en criant d'une voix forte à celui qui était assis sur la nuée: «Sers-toi de ta faucille et moissonne, car le moment de moissonner est venu, parce que la moisson de la terre est mûre.»",
        16: 'Alors celui qui était assis sur la nuée passa sa faucille sur la terre, et la terre fut moissonnée.',
        17: 'Un autre ange sortit du sanctuaire qui est dans le ciel; il tenait, lui aussi, une serpette tranchante.',
        18: "Et un autre ange, celui qui a pouvoir sur le feu, sortit de l'autel, et s'adressa d'une voix forte à celui qui tenait la serpette tranchante, disant: «Sers-toi de ta serpette tranchante, et coupe les grappes de la vigne de la terre, car les raisins en sont mûrs.»",
        19: "Alors l'ange passa sa serpette sur la terre, et il vendangea la vigne de la terre; puis il en jeta les grappes dans la grande cuve de la fureur de Dieu:",
        20: 'on foula la cuve hors de la ville, et il en sortit du sang jusqu’à la hauteur des mors des chevaux sur un espace de mille six cents stades.',
    },
    15: {
        1: "Et je vis un autre prodige dans le ciel, un grand, un étonnant prodige, sept anges ayant en main les sept derniers fléaux, car c'est par ces fléaux que doit se consommer le courroux de Dieu.",
        2: 'Et je vis comme une mer de verre mêlée de feu, et au bord de cette mer de verre étaient debout les vainqueurs de la bête, de son image et du nombre de son nom, ayant en main les harpes sacrées.',
        3: "Ils chantaient le cantique de Moïse, serviteur de Dieu, et le cantique de l'agneau, disant: «Tes oeuvres sont grandes et admirables, Seigneur Dieu, Tout-Puissant! Tes voies sont justes et véritables, ô Roi des nations!",
        4: 'Qui ne craindrait, Seigneur, et ne glorifierait ton nom, car toi seul es Saint. Et toutes les nations viendront se prosterner devant toi, parce que tes jugements ont éclaté.»',
        5: "Après cela, je vis s'ouvrir le sanctuaire qui est dans le ciel et qui renferme le tabernacle du témoignage.",
        6: "Les sept anges qui ont en main les sept fléaux sortirent du sanctuaire; ils étaient vêtus d'un lin pur et éclatant, et portaient des ceintures d'or autour de la poitrine.",
        7: "Alors l'un des quatre animaux donna aux sept anges sept coupes d'or pleines du courroux du Dieu qui vit aux siècles des siècles;",
        8: 'et le sanctuaire fut rempli du parfum de la gloire de Dieu et de sa puissance; et nul ne pouvait entrer dans le sanctuaire, jusqu’à ce que les sept fléaux des sept anges eussent été consommés.',
    },
    16: {
        1: "Alors j'entendis une voix forte qui sortait du sanctuaire, et qui disait aux sept anges: «Allez, et versez sur la terre les sept coupes de la colère de Dieu.»",
        2: "Le premier ange partit, et répandit sa coupe sur la terre: et un ulcère malin et douloureux frappa les hommes qui avaient la marque de la bête, et ceux qui en adoraient l'image.",
        3: "Le second ange répandit sa coupe dans la mer; et la mer devint comme le sang d'un mort, et tout être vivant qui était dans la mer, mourut.",
        4: "Le troisième répandit sa coupe dans les fleuves et dans les sources d'eau; et les eaux furent changées en sang.",
        5: "Alors j'entendis l'ange des eaux qui disait: «Tu es juste, ô toi qui es et qui étais; tu es saint, d'avoir rendu ce jugement:",
        6: 'ils ont versé le sang des saints et des prophètes, et tu leur as donné du sang à boire: ils en sont dignes.»',
        7: "Et j'entendis l'autel qui disait: «Oui, Seigneur, Dieu tout-puissant, tes jugements sont véritables et justes.»",
        8: 'Le quatrième répandit sa coupe sur le soleil, et il lui fut donné de brûler les hommes par le feu:',
        9: "et les hommes furent frappés d'une chaleur brûlante, ils blasphémèrent le nom de Dieu qui dispose de ces fléaux, et ils ne se repentirent point pour lui rendre gloire.",
        10: 'Le cinquième ange répandit sa coupe sur le trône de la bête; et le royaume de la bête fut plongé dans les ténèbres; les hommes se mordaient la langue de douleur;',
        11: 'et ils blasphémèrent le Dieu du ciel, à cause de leurs tourments et de leurs ulcères; et ils ne se repentirent point de leurs oeuvres.',
        12: "Le sixième répandit sa coupe sur le grand fleuve de l'Euphrate; et les eaux en furent desséchées, afin de livrer passage aux rois qui venaient de l'Orient.",
        13: 'Et je vis sortir de la gueule du dragon, et de la gueule de la bête, et de la bouche du faux-prophète, trois esprits impurs semblables à des crapauds.',
        14: "Ce sont, en effet, des esprits de démons, qui font des prodiges et qui vont rassembler les rois de l'univers entier pour la bataille du grand jour du Dieu tout-puissant.",
        15: '(«Voici, je viens comme un voleur. Heureux celui qui veille et qui conserve ses vêtements, afin de ne pas aller nu et de ne pas laisser voir sa honte!»)',
        16: '— Et ces esprits rassemblèrent les rois en un lieu nommé en hébreu, «Harmagédon.»',
        17: "Le septième ange répandit sa coupe sur l'atmosphère; et il sortit du sanctuaire du ciel, du trône même, une voix forte qui disait: «C'en est fait!»",
        18: "Et il y eut des éclairs, des bruits, des tonnerres; il se fit un tremblement de terre tel qu'il n'y en a jamais eu un semblable depuis qu'il y a des hommes sur la terre;",
        19: 'la grande ville se partagea en trois, et les villes des nations croulèrent: et Dieu se souvint de Babylone la grande, pour lui faire boire la coupe pleine du vin de son ardente colère.',
        20: "Toutes les îles disparurent, et l'on ne retrouva plus de montagnes.",
        21: 'Une forte grêle, dont les grêlons pouvaient peser un talent, tomba du ciel sur les hommes; et les hommes blasphémèrent Dieu à cause du fléau de la grêle, parce que ses dégâts étaient immenses.',
    },
    17: {
        1: "L'un des sept anges qui tenaient les sept coupes, vint, et me dit: «Viens, je te montrerai le jugement de la grande prostituée qui est assise sur les grandes eaux,",
        2: 'avec laquelle les rois de la terre se sont souillés, et qui a enivré les habitants de la terre du vin de son libertinage.»',
        3: "Et il m'emmena en esprit dans un désert. Et je vis une femme assise sur une bête écarlate, couverte de noms de blasphème, et qui avait sept têtes et dix cornes.",
        4: "Cette femme était vêtue de pourpre et d'écarlate, elle était couverte d'or, de pierres précieuses et de perles; elle tenait à la main une coupe d'or pleine d'abominations et des souillures de son libertinage;",
        5: 'sur son front était écrit un nom, nom mystérieux, «Babylone la grande, la mère des prostituées et des abominations de la terre.»',
        6: 'Je vis cette femme ivre du sang des saints et du sang des martyrs de Jésus, et sa vue me jeta dans un grand étonnement.',
        7: "Alors l'ange me dit: «Pourquoi t'étonnes-tu? Je te dirai, moi, le mystère de la femme et de la bête qui la porte, et qui a les sept têtes et les dix cornes.",
        8: "La bête que tu vois, était et elle n'est plus; elle doit monter de l'abîme et s'en aller à sa perte. Et les habitants de la terre, dont le nom n'est pas écrit dans le livre de vie, dès la fondation du monde, seront dans l'étonnement, en voyant la bête, parce qu'elle était et qu'elle n'est plus, et qu'elle reparaîtra.»",
        9: "(C'est ici que doit se montrer l'esprit doué de sagesse.) «Les sept têtes sont sept montagnes sur lesquelles la femme est assise;",
        10: "ce sont aussi sept rois: les cinq premiers sont tombés, l'un subsiste, l'autre n'est pas encore venu, et quand il sera venu, il ne doit demeurer que peu de temps.",
        11: "Et la bête qui était et qui n'est plus, est elle-même un huitième roi et en même temps l’un des sept rois, et elle s'en va à sa perte.",
        12: "Les dix cornes que tu as vues, sont dix rois qui n'ont pas encore reçu de royaumes, mais qui recevront un pouvoir de rois pour une heure, avec la bête.",
        13: "Ils n'ont qu'une seule et même pensée, et ils mettent au service de la bête leur puissance et leur autorité.",
        14: "Ils feront la guerre à l'agneau; mais l'agneau les vaincra, parce qu'il est Seigneur des seigneurs et Roi des rois, et ceux qui l'accompagnent, les appelés, les élus, les fidèles, les vaincront avec lui.»",
        15: 'Et il me dit: «Les eaux que tu as vues, sur lesquelles la prostituée est assise, ce sont des peuples, des foules, des nations et des langues;',
        16: 'et les dix cornes que tu as vues et la bête haïront elles-mêmes la prostituée; elles la rendront désolée et nue; elles mangeront ses chairs et la consumeront par le feu.',
        17: "Car Dieu leur a mis au coeur d'exécuter la pensée de la bête, une seule et même pensée, et de mettre leur royauté au service de la bête, jusqu’à ce que ses paroles à lui soient accomplies.",
        18: "Quant à la femme que tu as vue, c'est la grande ville qui possède l'empire sur les rois de la terre.»",
    },
    18: {
        1: 'Après cela, je vis descendre du ciel un autre ange, qui avait un grand pouvoir; et la terre fut illuminée de sa gloire.',
        2: "Il cria d'une voix puissante, disant: «Elle est tombée, elle est tombée, Babylone la grande! Elle est devenue une habitation de démons, un réceptacle de toutes sortes d'esprits impurs et un repaire de toutes sortes d'oiseaux immondes et odieux,",
        3: "parce que toutes les nations ont bu du vin de son libertinage furieux, que les rois de la terre se sont souillés avec elle et que les marchands de la terre se sont enrichis par l'excès de son luxe.»",
        4: "Et j'entendis une autre voix qui venait du ciel, et qui disait: «Sortez de cette ville, vous qui êtes mon peuple, afin de ne point participer à ses péchés, et de n'être point enveloppés dans ses calamités,",
        5: "car ses péchés se sont accumulés jusqu'au ciel, et Dieu s'est souvenu de ses iniquités.",
        6: 'Faites-lui comme elle a fait elle-même, et rendez-lui au double selon ses oeuvres; faites-lui boire double dose dans le calice où elle vous a fait boire:',
        7: "autant elle s'est glorifiée et plongée dans le luxe, autant il faut lui donner de tourment et de deuil. Elle dit dans son coeur: «Je suis une reine sur son trône, je ne suis point veuve, et je ne connaîtrai point le deuil.»",
        8: "Eh bien! en un même jour, les calamités fondront sur elle, la mort, le deuil, la famine, et elle sera consumée par le feu, parce que Dieu qui l'a jugée, est un puissant Seigneur.»",
        9: 'Les rois de la terre, qui se sont plongés avec elle dans le libertinage et dans le luxe, pleurent et se lamentent sur son sort en voyant la fumée de son embrasement.',
        10: 'Ils se tiennent à distance dans la crainte de partager ses tourments, et ils disent: «Malheur! Malheur! Toi, la grande ville, Babylone la puissante cité, en une seule heure est venu ton jugement!»',
        11: "Et les marchands de la terre la pleurent et se désolent, parce que personne n'achète plus leur cargaison,",
        12: "une cargaison d'or, d'argent, de pierres précieuses, de perles, de fin lin, de pourpre, de soie et d'écarlate, de bois de senteur de toute espèce, d'objets d'ivoire, de bois très précieux, d'airain, de fer et de marbre, de toutes sortes;",
        13: "de cannelle, d'essence, de parfums, de myrrhe, d'encens, de vin, d'huile, de fine farine, de blé, de bestiaux, de moutons, de chevaux, d'équipages, de cochers et d'esclaves.»",
        14: "Les fruits, dont tu faisais tes délices, s'en sont allés loin de toi; toutes les choses exquises et magnifiques sont perdues pour toi; tu ne les retrouveras plus.»",
        15: 'Ces marchands, qui se sont enrichis avec elle, se tiennent à distance, dans la crainte de partager ses tourments; ils pleurent et se désolent,',
        16: "disant: «Malheur! Malheur! Qu'est devenue la grande ville, celle qui était vêtue de fin lin, de pourpre et d'écarlate, et qui était couverte d'or, de pierres précieuses et de perles? En une seule heure ont été détruites tant de richesses!»",
        17: 'Et tous les pilotes, tous ceux qui naviguent à destination de la grande ville, les matelots et ceux qui exploitent la mer se tiennent à distance',
        18: 'et crient en voyant la fumée de son embrasement: «Quelle ville était semblable à la grande cité?»',
        19: "Ils se jettent de la poussière sur la tête, et ils crient en pleurant et en se désolant: «Malheur! Malheur! La grande ville, dont l'opulence a enrichi tous ceux qui avaient des vaisseaux sur mer, en une heure elle a été détruite!»",
        20: 'Ciel, réjouis-toi de sa catastrophe; vous aussi, saints, apôtres, prophètes: en la jugeant, Dieu vous a fait justice..',
        21: "Alors un ange vigoureux prit une pierre aussi grosse qu'une meule, et la jeta dans la mer, en disant: «Ainsi sera précipitée avec fracas Babylone la grande ville, et on ne la retrouvera plus.",
        22: "On n'entendra plus chez toi les sons des joueurs de harpe, des musiciens, des joueurs de flûte ni des trompettes; on n'y trouvera plus d'artisan d'aucun métier; on n'y entendra plus le bruit de la meule;",
        23: "on n'y verra plus briller la lumière de la lampe; on n'y entendra plus la voix de l'époux et de l'épouse, parce que tes marchands étaient les grands de la terre, parce que toutes les nations ont été égarées par tes enchantements,",
        24: "et qu'on a trouvé chez toi le sang des prophètes et des saints, et de tous ceux qui ont été égorgés sur la terre.»",
    },
    19: {
        1: "Après cela, j'entendis dans le ciel comme la grande voix d'une foule immense qui disait: «Alléluia! Le salut, la gloire et la puissance appartiennent à notre Dieu,",
        2: 'parce que ses jugements sont véritables et justes. Il a jugé la grande prostituée qui a corrompu la terre par son libertinage, et il lui a demandé compte du sang de ses serviteurs, versé par sa main.»',
        3: 'Et la voix dit une seconde fois: «Alléluia!» Et la fumée de la grande cité monte aux siècles des siècles.',
        4: 'Et les vingt-quatre vieillards et les quatre animaux se prosternèrent et adorèrent Dieu, qui est assis sur le trône, et dirent: «Amen! Alléluia!»',
        5: 'Et il sortit du trône une voix qui disait: «Louez notre Dieu, Vous tous ses serviteurs, qui le craignez, petits et grands.»',
        6: "Et j'entendis une voix forte, comme celle d'une foule immense, comme le bruit de grosses eaux, comme le bruit de violents tonnerres; elle disait: «Alléluia! car il règne, le Seigneur Dieu tout-puissant.",
        7: "Réjouissons -nous, tressaillons d'allégresse et lui rendons gloire: les noces de l'agneau sont venues, son épouse s'est préparée,",
        8: 'et il lui a été donné de se vêtir de lin fin, magnifique et pur.» (Ce fin lin, ce sont les vertus des saints.)',
        9: "Et l'ange me dit: «Écris: Heureux ceux qui sont invités au repas des noces de l'agneau!» Et il ajouta: «Ces paroles sont de véritables paroles de Dieu.»",
        10: "Je tombai à ses pieds pour l'adorer, mais il me dit: «Garde-toi de le faire; je suis ton compagnon de service, et celui de tes frères qui gardent le témoignage de Jésus-Christ: adore Dieu.» — En effet, le témoignage de Jésus, c'est l'esprit de la prophétie.",
        11: "Alors je vis le ciel ouvert, et il parut un cheval blanc: celui qui le montait s'appelle Fidèle et Véritable; il juge et combat avec justice.",
        12: 'Ses yeux sont une flamme ardente; il a sur la tête plusieurs diadèmes, et porte un nom écrit, que nul ne connaît que lui-même;',
        13: "il est vêtu d'un manteau teint de sang; son nom est La Parole de Dieu.",
        14: "Les armées du ciel l'accompagnent sur des chevaux blancs; les cavaliers sont vêtus de fin lin, blanc et pur.",
        15: "De sa bouche sort une épée aiguë, pour frapper les nations; c'est lui qui les gouvernera avec une verge de fer; c'est lui qui foule la cuve du vin de l'ardente colère du Dieu tout-puissant.",
        16: 'Sur son manteau et sur sa cuisse, il porte écrit ce nom, Roi des rois, et Seigneur des seigneurs.',
        17: "Et je vis un ange qui était debout dans le soleil, et qui cria d'une voix forte à tous les oiseaux qui volaient dans le haut des airs: «Venez, rassemblez-vous pour le grand festin que Dieu vous donne,",
        18: 'pour manger la chair des rois, la chair des généraux, la chair des hommes forts, la chair des chevaux et de ceux qui les montent, la chair de tous les hommes, libres et esclaves, petits et grands.»',
        19: 'Et je vis la bête et les rois de la terre, avec leurs armées rassemblées pour livrer bataille à celui qui est monté sur le cheval blanc, et à son armée.',
        20: "La bête fut prise, ainsi que le faux-prophète qui l'accompagnait, et qui, par ses prodiges faits devant elle, avait séduit ceux qui avaient pris la marque de la bête, et ceux qui en adoraient l'image. Tous les deux furent jetés vivants dans l'étang de feu où le soufre brûle;",
        21: "le reste fut tué par l'épée qui sort de la bouche de celui qui est monté sur le cheval; et tous les oiseaux se rassasièrent de leurs chairs.",
    },
    20: {
        1: "Et je vis descendre du ciel un ange qui tenait dans sa main la clef de l'abîme et une grosse chaîne;",
        2: "il saisit le dragon, le serpent ancien, qui est le diable, Satan, et il l'enchaîna pour mille ans.",
        3: "Puis il le jeta dans l'abîme, qu'il ferma à clef et scella sur lui, afin qu'il n'égarât plus les nations, jusqu’à ce que les mille ans fussent écoulés. Après cela, il doit être relâché pour un peu de temps.",
        4: "Et je vis des trônes: des personnes s'assirent sur ces trônes, et le jugement leur fut remis. Je vis aussi les âmes de ceux qui avaient été décapités pour le témoignage de Jésus et pour la parole de Dieu, et celles de ceux qui n'avaient point adoré la bête ni son image, et qui n'en avaient point pris la marque sur le front, ni sur la main: ils revinrent à la vie, et régnèrent avec Christ pendant mille ans;",
        5: "mais le reste des morts ne revint point à la vie, jusqu’à ce que les mille ans fussent écoulés. C'est la première résurrection.",
        6: "Heureux et saints ceux qui ont part à la première résurrection! La seconde mort n'a point de pouvoir sur eux; ils seront sacrificateurs de Dieu et de Christ, et régneront avec lui pendant mille ans.",
        7: 'Quand les mille ans seront écoulés, Satan sera relâché de sa prison,',
        8: 'et il en sortira pour égarer les nations qui sont aux quatre extrémités de la terre, Gog et Magog, afin de les rassembler pour le combat. Nombreuses comme le sable de la mer,',
        9: "elles se répandront sur l'étendue de la terre, elles cerneront le camp des saints et la ville bien-aimée, mais un feu tombera du ciel et les dévorera.",
        10: "Le diable, qui les égarait, sera jeté dans l'étang de feu et de soufre, où sont plongés la bête et le faux-prophète; et ils seront tourmentés jour et nuit aux siècles des siècles.",
        11: "Je vis un grand trône blanc et celui qui était assis dessus: le ciel et la terre s'enfuirent de devant sa face, de sorte qu'il n'y eut plus de place pour eux.",
        12: "Je vis les morts, grands et petits, debout devant le trône: des livres furent ouverts; on ouvrit encore un autre livre, qui est le livre de vie; et les morts furent jugés selon leurs oeuvres, d'après ce qui était consigné dans ces livres.",
        13: 'La mer rendit ses morts: la Mort et l’Hadès rendirent les leurs; et ces morts furent jugés, chacun selon ses oeuvres.',
        14: "Après quoi la Mort et l’Hadès furent jetés dans l'étang de feu: c'est la seconde mort, l’étang de feu.",
        15: "Quiconque ne fut pas trouvé inscrit dans le livre de vie fut jeté dans l'étang de feu.",
    },
    21: {
        1: "Alors je vis un nouveau ciel et une nouvelle terre, car le premier ciel et la première terre avaient disparu, et il n'y avait plus de mer.",
        2: "Et je vis descendre du ciel, d'auprès de Dieu, la ville sainte, une Jérusalem nouvelle, prête comme une épouse qui s'est parée pour son époux.",
        3: "Et j'entendis une voix forte qui venait du ciel, et qui disait: «Voici le tabernacle de Dieu, qui va être dressé au milieu des hommes: il habitera avec eux, et ils seront son peuple, et Dieu même sera avec eux comme leur Dieu.",
        4: "Il essuiera toute larme de leurs yeux, la mort ne sera plus, il n'y aura plus ni deuil, ni cri, ni labeur, car les premières choses ont disparu.»",
        5: 'Et celui qui était assis sur le trône, dit: «Voici, je vais faire toutes choses nouvelles.» Et il ajouta: «Ecris, car cette parole est sûre et véritable.»',
        6: "Puis il me dit: «C'est fait! Je suis l'alpha et l'oméga, le commencement et la fin. A celui qui a soif, je donnerai gratuitement de la source d'eau de la vie.",
        7: 'Celui qui vaincra possédera ces choses; je serai son Dieu et il sera mon fils.',
        8: "Quant aux lâches, aux incrédules, aux abominables, aux meurtriers, aux libertins, aux magiciens et à tous les menteurs, leur part sera dans l‘étang ardent de feu et de soufre: c'est la seconde mort.»",
        9: "Alors l'un des sept anges qui tenaient les sept coupes pleines des sept derniers fléaux, vint me parler, et me dit: «Viens, je te montrerai l’épouse, la femme de l’agneau.»",
        10: "Et m'ayant transporté en esprit sur une grande et haute montagne, il me montra la ville sainte, Jérusalem, qui descendait du ciel d'auprès de Dieu, resplendissante de la gloire de Dieu.",
        11: "L'astre qui l'éclaire est semblable à une pierre très précieuse, on dirait une pierre de jaspe cristallin.",
        12: "Elle a une grande et haute muraille avec douze portes; à ces portes sont douze anges, et sur ces portes sont des noms écrits, ceux des douze tribus des fils d'Israël.",
        13: "Il y a trois portes à l'orient, trois portes au nord, trois portes au midi et trois portes à l'occident.",
        14: 'La muraille de la ville a pour fondements douze pierres, sur lesquelles sont douze noms, ceux des douze apôtres de l’agneau.',
        15: "L'ange qui me parlait, tenait une mesure, un roseau d'or, pour mesurer la ville, ses portes et sa muraille.",
        16: "La ville est quadrangulaire, d'une longueur égale à sa largeur. Il mesura la ville avec son roseau, et trouva douze mille stades; la longueur, la largeur et la hauteur en sont égales.",
        17: "Il en mesura aussi la muraille, et trouva cent quarante-quatre coudées, mesure d'homme qui est aussi mesure d'ange.",
        18: "La muraille est construite en jaspe; la ville est d'un or pur semblable à du verre pur.",
        19: 'Les fondements de la ville sont faits de toutes sortes de pierres précieuses: le premier fondement est du jaspe; le second, du saphir; le troisième, de calcédoine; le quatrième, de l’émeraude;',
        20: "le cinquième, du sardonyx; le sixième, de la cornaline; le septième, de la chrysolithe: le huitième, du béryl; le neuvième, de la topaze; le dixième, de la chrysoprase; le onzième, de l'hyacinthe; le douzième de l'améthyste.",
        21: "Les douze portes sont douze perles; chacune des portes est d'une seule perle; la rue de la ville est d'un or pur, comme du verre transparent.",
        22: "Je n'y vis point de sanctuaire, car le Seigneur Dieu tout-puissant et l'agneau en sont le sanctuaire.",
        23: "La ville n'a besoin ni du soleil, ni même de la lune pour l'éclairer, car la gloire de Dieu l'illumine, et l’agneau en est le flambeau.",
        24: 'Les nations marcheront à sa lumière, et les rois de la terre y apporteront leurs magnificences et leurs richesses.',
        25: "Les portes ne seront point fermées chaque jour, car il n'y aura point de nuit.",
        26: 'On y apportera les magnificences et les richesses des nations;',
        27: "et il n'y entrera rien de souillé, ni personne qui se livre à l'abomination ou au mensonge, mais ceux-là seulement qui sont inscrits dans le livre de vie de l'agneau.",
    },
    22: {
        1: "Et l'ange me montra le fleuve d'eau de la vie, clair comme du cristal; il sortait du trône de Dieu et de l'agneau.",
        2: 'Au milieu de la rue de la ville et des deux côtés du fleuve, se trouvent des arbres de vie qui donnent douze récoltes, une récolte par mois, et dont les feuilles servent à la guérison des nations.',
        3: "Il n'y aura plus d'anathème. Le trône de Dieu et de l'agneau sera dans la ville; les serviteurs de Dieu le serviront,",
        4: 'ils verront sa face, son nom sera sur leurs fronts.',
        5: "Il n'y aura point de nuit, et ils n'auront besoin ni de lampe, ni de lumière, parce que le Seigneur Dieu les illuminera; et ils régneront aux siècles des siècles.",
        6: 'Et l’ange me dit: «Ces paroles sont sûres et véritables; et le Seigneur, le Dieu des esprits des prophètes, a envoyé son ange, pour montrer à ses serviteurs les événements qui doivent bientôt arriver.',
        7: '«Voici, je viens bientôt. «Heureux celui qui garde les paroles de la prophétie de ce livre!»',
        8: "C'est moi, Jean, qui ai entendu et vu ces choses, et, après les avoir entendues et vues, je tombai aux pieds de l'ange qui me les montrait, pour l'adorer.",
        9: 'Mais il me dit: «Garde-toi de le faire; je suis ton compagnon de service, le compagnon de tes frères, les prophètes, et de ceux qui gardent les paroles de ce livre: adore Dieu.»',
        10: 'Et il me dit: «Ne tiens point secrètes les paroles de la prophétie de ce livre; le moment est proche.',
        11: "«Que l'injuste fasse encore le mal; que l'impur se souille encore; que le juste pratique encore la justice, et que le saint se sanctifie encore.",
        12: 'Voici, je viens bientôt, et la rétribution est avec moi: je rendrai à chacun selon ses oeuvres.',
        13: "Je suis l'alpha et l'oméga, le premier et le dernier, le commencement et la fin.»",
        14: "Heureux ceux qui pratiquent ses commandements, afin d'avoir droit à l'arbre de vie, et d'entrer dans la ville par les portes!",
        15: "Dehors, les chiens, les magiciens, les libertins, les meurtriers, les idolâtres, et quiconque aime le mensonge et s'y adonne!",
        16: "«C'est moi, Jésus, qui ai envoyé mon ange, pour vous annoncer ces choses, à vous, églises. C'est moi qui suis le rejeton et le fils de David, l'étoile brillante du matin.»",
        17: "Et l'Esprit et l'épouse disent: «Viens.» Que celui qui entend, dise aussi: «Viens.» Que celui qui a soif, vienne. Que celui qui désire l'eau de la vie, en prenne gratuitement.",
        18: "Je déclare à quiconque entend les paroles de ce livre, que si quelqu'un y ajoute, Dieu le frappera des calamités qui sont décrites dans ce livre;",
        19: "et que, si quelqu'un retranche des paroles de ce livre prophétique, Dieu lui retranchera sa part de l'arbre de vie et l’exclura de la ville sainte, qui sont décrits dans ce livre.",
        20: 'Celui qui atteste ces choses, dit: «Oui, je viens bientôt.» — «Amen! Viens, Seigneur Jésus!',
        21: 'Que la grâce du Seigneur Jésus soit avec tous!',
    },
}
