NAME = 'GerAlbrecht: German Albrecht Neues Testament und Psalmen'
BOOK = 'Revelation of John'

CHAPTERS = {
    1: {
        1: 'Dies ist eine Offenbarung Jesu Christi: / Gott hat sie ihm gegeben, um seinen Knechten kundzutun, was bald geschehen soll; und er hat sie durch seinen Engel seinem Knecht Johannes zugesandt und bekannt gemacht.',
        2: 'Der hat dann das, was er gesehen, aufgezeichnet und bezeugt nunmehr, was Gott geredet und was Jesus Christus ihm als wahr verbürgt hat.',
        3: 'Selig ist, der die Worte dieser Weissagung vorliest, und selig sind, die sie hören und zu Herzen nehmen, was darin geschrieben ist! Denn die Zeit ist nahe!',
        4: 'Johannes entbietet den sieben Gemeinden in Asien seinen Gruß. Gnade sei mit euch und Friede von dem, der da ist, der da war und der da kommt, und von den sieben Geistern, die vor dem Thron Gottes sind,',
        5: 'und von Jesus Christus, dem zuverlässigen Zeugen dem Erstgeborenen von den Toten und dem Herrscher über die Könige der Erde!',
        6: 'Ihm, der uns geliebt und uns von unseren Sünden durch sein Blut erlöst und uns zu einem Königtum, zu Priestern für seinen Gott und Vater gemacht hat; ihm gebührt die Herrlichkeit und Macht in alle Ewigkeit! Amen.',
        7: 'Seht, er kommt in den Wolken! Jedes Auge wird ihn schauen, auch die, die ihn durchstochen haben, und bei seinem Anblick werden wehklagen alle Völker der Erde. Ja, so ist es!',
        8: '"Ich bin das A und das O", spricht Gott der Herr, der da ist, der da war und der da kommt, der Allgewaltige.',
        9: 'Ich, Johannes, euer Bruder und euer Genosse in der Trübsal und auch in der Königsherrschaft und in der beharrlichen Hoffnung auf das Kommen Jesu, ich war auf der Insel, die Patmos heißt, weil ich Gottes Wort verkündigt und das Zeugnis von Jesus abgelegt hatte.',
        10: 'Da ward ich an des Herrn Tag vom Geist erfüllt. Ich hörte hinter mir eine laute Stimme gleich einem Posaunenschall,',
        11: 'die sprach: "Was du siehst, das schreibe in ein Buch und sende es an die sieben Gemeinden: nach Ephesus, nach Smyrna, nach Pergamus, nach Thyatira, nach Sardes, nach Philadelphia und nach Laodizea."',
        12: 'Da wandte ich mich um nach der Stimme, die mit mir redete. Und als ich mich umwandte, sah ich sieben goldene Leuchter,',
        13: 'und inmitten der Leuchter sah ich jemand, der einem Menschensohn glich: Er war bekleidet mit einem Mantel, der bis zu den Füßen reichte, und um die Brust trug er einen goldenen Gürtel.',
        14: 'Sein Haupt und seine Haare waren weiß wie weiße Wolle und wie Schnee; seine Augen waren wie eine Feuerflamme;',
        15: 'seine Füße glichen Silbererz, das im Feuerofen weißglühend geworden ist; seine Stimme klang wie das Rauschen vieler Wasser.',
        16: 'In seiner rechten Hand hielt er sieben Sterne; aus seinem Mund ging ein scharfes zweischneidiges Schwert, und sein Antlitz strahlte wie die Sonne in ihrer vollen Kraft.',
        17: 'Als ich ihn sah, sank ich wie tot zu seinen Füßen. Er aber legte seine Hand auf mich und sprach: "Fürchte dich nicht! Ich bin der Erste und der Letzte',
        18: 'und der Lebendige. Ich war tot, aber ich bin nun lebendig in alle Ewigkeit und habe die Schlüssel des Todes und der Unterwelt.',
        19: 'Schreib nun (später) auf, was du gesehen hast: das, was jetzt schon ist, und das, was einst geschehen soll!',
        20: '(Schreib jetzt zunächst) das Geheimnis der sieben Sterne, die du in meiner rechten Hand gesehen hast, und der sieben goldenen Leuchter! Die sieben Sterne sind die Engel der sieben Gemeinden, und die sieben Leuchter sind die sieben Gemeinden.',
    },
    2: {
        1: 'Dem Engel der Gemeinde in Ephesus schreibe: So spricht, der die sieben Sterne in seiner Rechten hält, die inmitten der sieben goldenen Leuchter wandelt:',
        2: "'Ich kenne deine Werke, deine unverdrossene Arbeit und deine Ausdauer. Ich weiß, du kannst böse Menschen nicht ertragen und hast die Leute, die sich fälschlich für Apostel ausgeben, geprüft und sie als Lügner entlarvt.",
        3: 'Du zeigst auch Ausdauer und hast um meines Namens willen standhaft gelitten und bist nicht müde geworden.',
        4: 'Aber ich habe wider dich, daß du nicht mehr in deiner ersten Liebe stehst.',
        5: 'Nimm darum zu Herzen, von welcher Höhe du gefallen bist! Ändere deinen Sinn und tu die ersten Werke! Sonst komme ich über dich und stoße deinen Leuchter von seiner Stätte, wenn du dich nicht bekehrst.',
        6: 'Dies gereicht dir noch zum Lobe: du haßt die Werke der Nikolaiten, die ich auch hasse.',
        7: "Wer Ohren hat, der höre, was der Geist den Gemeinden sagt! Dem Sieger will ich zu essen geben von der Frucht des Lebensbaumes, der in dem Paradies Gottes ist.'",
        8: 'Dem Engel der Gemeinde in Smyrna schreibe: So spricht der Erste und der Letzte, der tot war und wieder lebt:',
        9: "'Ich kenne deine Trübsal und deine Armut — doch du bist reich! — und ich weiß, wie du von denen gelästert wirst, die sich selbst (mit Stolz) Juden nennen; aber in Wirklichkeit sind sie's nicht, sondern sie sind eine Satansgemeinde.",
        10: 'Fürchte dich nicht vor dem, was du noch leiden sollst! Seht, der Teufel wird einige von euch ins Gefängnis bringen, damit ihr geprüft werdet; und ihr werdet eine Trübsal von zehn Tagen zu leiden haben. Bleib mir treu bis in den Tod, dann will ich dir das (ewige) Leben als Siegeskrone geben!',
        11: "Wer Ohren hat, der höre, was der Geist den Gemeinden sagt! Dem Sieger soll kein Leid geschehen von dem zweiten Tod.'",
        12: 'Dem Engel der Gemeinde in Pergamus schreibe: / So spricht, der das scharfe, zweischneidige Schwert trägt:',
        13: "'Ich weiß, wo du wohnst: da, wo des Satans Thron ist. Doch du hältst fest an meinem Namen und hast den Glauben, den ich in dir gewirkt, nicht verleugnet in jenen Tagen, als Antipas, mein treuer Zeuge, bei euch, wo der Satan wohnt, getötet wurde.",
        14: 'Doch ich habe etwas wider dich: Du hast dort Leute, die der Lehre Bileams anhangen, der den Balak unterwies, den Israeliten einen Fallstrick zu legen, so daß sie von den Götzenopfern aßen und Unzucht trieben.',
        15: 'So hast auch du in deiner Mitte Leute, die der Lehre der Nikolaiten folgen.',
        16: 'Darum ändere deinen Sinn! Sonst komme ich bald über dich und werde sie bekämpfen mit dem Schwert meines Mundes.',
        17: "Wer Ohren hat, der höre, was der Geist den Gemeinden sagt! / Dem Sieger will ich geben von dem verborgenen Manna, und ich will ihm geben einen weißen Stein; auf dem Stein soll ein neuer Name stehen, den niemand kennt als der Empfänger.'",
        18: 'Dem Engel der Gemeinde in Thyatira schreibe: / So spricht der Sohn Gottes, der Augen hat wie eine Feuerflamme, und dessen Füße dem Silbererz gleichen:',
        19: "'Ich kenne deine Werke — deine Liebe, deinen Glauben, deine Dienstleistungen und deine Beharrlichkeit —, und ich weiß, du hast in letzter Zeit noch mehr gewirkt als früher.",
        20: 'Aber ich habe dies wider dich: Du läßt Isebel, dein Weib, gewähren: die gibt sich für eine Prophetin aus und verführt meine Knechte durch ihre Lehre, Hurerei zu treiben und Götzenopferfleisch zu essen.',
        21: 'Ich habe ihr Frist gegeben zur Bekehrung; doch sie will sich nicht bekehren von ihrer Unzucht.',
        22: 'Sieh, ich werfe sie aufs Krankenbett, und die mit ihr die Ehe brechen, bringe ich in große Trübsal, wenn sie sich nicht von ihren Werken bekehren.',
        23: 'Und ihre Kinder will ich des Todes sterben lassen. Denn alle Gemeinden sollen erkennen, daß ich es bin, der Nieren und Herzen erforscht; und ich will einem jeden von euch vergelten nach seinen Werken.',
        24: "Euch anderen aber in Thyatira sage ich, allen, die dieser Lehre nicht folgen und die Tiefen Satans nicht 'erkannt' haben — wie sie sich rühmen —: Ich lege euch weiter keine Last auf.",
        25: 'Doch haltet fest an dem, was ihr schon habt, bis ich komme!',
        26: 'Wer siegt und meine Werke bis ans Ende hält, dem will ich Macht geben über die Völker,',
        27: 'und er soll sie mit eisernem Stab weiden, wie man Töpfergeschirr in Stücke bricht.',
        28: 'Diese Macht habe auch ich empfangen von meinem Vater. Und ich will ihm geben den Morgenstern.',
        29: "Wer Ohren hat, der höre, was der Geist den Gemeinden sagt!'",
    },
    3: {
        1: "Dem Engel der Gemeinde in Sardes schreibe: / So spricht, der die sieben Geister Gottes hat und die sieben Sterne: / 'Ich kenne deine Werke: du lebst nur dem Namen nach; in Wirklichkeit bist du tot!",
        2: 'Werde wach und stärke das, was noch da ist, und was auch schon dem Tod nahe war! Denn ich habe deine Werke nicht völlig erfunden vor meinem Gott.',
        3: 'Denke daran, mit welcher Lust du einst (das Wort) aufgenommen und gehört hast! Bewahre es und ändere deinen Sinn! Doch wachst du nicht, so will ich kommen wie ein Dieb, und du sollst nicht wissen, zu welcher Stunde ich über dich kommen werde.',
        4: 'Du hast indes noch einige Leute in Sardes, die ihre Kleider nicht befleckt haben: die sollen mit mir wandeln in weißen Kleidern, denn sie sind es wert.',
        5: 'Der Sieger soll mit weißen Kleidern geschmückt werden, und ich will seinen Namen nicht auslöschen aus dem Lebensbuch; sondern ich werde seinen Namen bekennen vor meinem Vater und vor seinen Engeln.',
        6: "Wer Ohren hat, der höre, was der Geist den Gemeinden sagt!'",
        7: 'Dem Engel der Gemeinde in Philadelphia schreibe: / So spricht der Heilige, der Wahrhaftige, der den Schlüssel Davids hat, der öffnet, so daß niemand schließen kann, der schließt, so daß niemand öffnen darf;',
        8: "'Ich kenne deine Werke! Sieh, ich habe dir eine Tür aufgetan, die niemand schließen kann. Denn du hast nur eine kleine Kraft; trotzdem hast du mein Wort festgehalten und meinen Namen nicht verleugnet.",
        9: 'Sieh, ich führe dir (Anhänger) zu aus Satans Versammlung, aus dem Kreis derer, die sich Juden nennen; doch sie sind es nicht, sie lügen! Sieh, ich will sie dahin bringen, daß sie kommen und sich zu deinen Füßen niederwerfen und erkennen, daß ich dich geliebt.',
        10: 'Weil du das Wort, das zum geduldigen Warten auf mein Kommen mahnt, bewahrt hast, so will auch ich dich bewahren vor der Stunde der Versuchung, die über den ganzen Weltkreis kommen soll, um die Erdbewohner zu versuchen.',
        11: 'Ich komme bald! Halte fest, was du hast, damit dir niemand deine Krone raube!',
        12: 'Den Sieger will ich zu einer Säule in dem Tempel meines Gottes machen, und er soll seinen Platz nie mehr verlassen. Ich will auf ihn schreiben den Namen meines Gottes und den Namen der Stadt meines Gottes, des neuen Jerusalems, das aus dem Himmel herniedersteigt von meinem Gott, und meinen neuen Namen.',
        13: "Wer Ohren hat, der höre, was der Geist den Gemeinden sagt!'",
        14: 'Dem Engel der Gemeinde in Laodizea schreibe: / So spricht, der das Jawort ist, der treue und wahrhaftige Zeuge, der Anfang der Schöpfung Gottes:',
        15: "'Ich kenne deine Werke: du bist weder kalt noch warm. Ach, daß du kalt oder warm wärst!",
        16: 'So aber, weil du lau bist und weder kalt noch warm, will ich dich ausspeien aus meinem Mund.',
        17: 'Du sagst: Ich bin reich, ich habe Schätze gewonnen und bedarf nichts! Und dabei weißt du nicht, daß gerade du elend bist und jämmerlich, arm, blind und bloß.',
        18: 'Darum rate ich dir: kaufe von mir Gold, wie es geglüht aus dem Feuer kommt, damit du reich werdest, und weiße Kleider zum Anziehen, damit sich nicht die Schande deiner Blöße offenbare, und Salbe zum Bestreichen deiner Augen, damit du sehen könnest!',
        19: 'Alle, die ich liebhabe, die weise ich zurecht und züchtige ich. So raffe dich denn auf zu neuem Eifer und ändere deinen Sinn!',
        20: 'Sieh, ich stehe vor der Tür und klopfe an. Wer meine Stimme hört und mir die Tür öffnet, bei dem will ich einkehren und das Mahl mit ihm halten, und er mit mir.',
        21: 'Dem Sieger will ich geben, mit mir auf meinem Thron zu sitzen, wie auch ich den Sieg errungen habe und nun mit meinem Vater auf seinem Thron sitze.',
        22: 'Wer Ohren hat, der höre, was der Geist den Gemeinden sagt!\'"',
    },
    4: {
        1: 'Dann schaute ich, und sieh, eine Tür war aufgetan im Himmel. Da rief die erste Stimme, die ich wie Posaunenschall mit mir hatte reden hören: "Steig hierher empor! Ich will dir zeigen, was hernach geschehen soll."',
        2: 'Sofort ward ich vom Geist erfüllt. Ich sah: es stand ein Thron im Himmel, und auf dem Thron saß einer.',
        3: 'Der da saß, glich an Aussehen einem Jaspis und Sarder, und ein Regenbogen war rings um den Thron, wie ein Smaragd.',
        4: 'Rings um den Thron sah ich vierundzwanzig Älteste sitzen; die waren angetan mit weißen Kleidern und hatten auf ihren Häuptern goldene Kronen.',
        5: 'Von dem Thron gingen Blitze aus und laute Donnerschläge. Sieben Feuerfackeln brannten vor dem Thron: das sind die sieben Geister Gottes.',
        6: 'Vor dem Thron war (eine weite Fläche) wie ein Meer, durchsichtig gleich Kristall. Mitten in dem Thron und um den Thron sah ich vier Lebewesen voller Augen vorn und hinten.',
        7: 'Das erste Lebewesen glich einem Löwen, das zweite glich einem Stier, das dritte hatte ein Antlitz wie ein Mensch, und das vierte glich einem fliegenden Adler.',
        8: 'Jedes der vier Lebewesen hatte sechs Flügel; ringsum und innen waren sie voll Augen, und sie sangen unaufhörlich Tag und Nacht: / Heilig, heilig, heilig ist Gott der Herr, der Allgewaltige, Er, der war und ist und kommt!"',
        9: 'Und sooft die Lebewesen Preis, Ehre und Dank darbringen dem, der auf dem Thron sitzt, der da lebt in alle Ewigkeit,',
        10: 'fallen die vierundzwanzig Ältesten nieder vor dem, der auf dem Thron sitzt, und beten ihn an, der da lebt in alle Ewigkeit. Sie legen ihre Kronen nieder vor dem Thron und sprechen:',
        11: '"Du, unser Herr und Gott, bist würdig, den Lobpreis zu empfangen, die Ehre und die Macht. Denn du hast alle Dinge erschaffen, und weil es dein Wille war, sind sie ins Dasein eingetreten und erschaffen worden."',
    },
    5: {
        1: 'Ich sah in der rechten Hand dessen, der auf dem Thron saß, ein Buch, beschrieben auf der Innenseite und auf der Außenseite verschlossen mit sieben Siegeln.',
        2: 'Auch sah ich einen starken Engel, der rief mit lauter Stimme: "Wer ist würdig, das Buch zu öffnen und seine Siegel zu lösen?"',
        3: 'Doch niemand im Himmel, auf Erden und unter der Erde vermochte das Buch zu öffnen und hineinzusehen.',
        4: 'Da weinte ich sehr, weil niemand würdig erfunden wurde, das Buch zu öffnen und hineinzusehen.',
        5: 'Aber einer der Ältesten sprach zu mir: "Weine nicht! Sieh, es hat gesiegt der Löwe aus dem Stamme Juda, Davids Wurzelsproß, so daß er öffnen kann das Buch und seine sieben Siegel!"',
        6: 'Da sah ich inmitten des Throns und der vier Lebewesen und inmitten der Ältesten ein Lamm stehen, das aussah, als wäre es geopfert: das hatte sieben Hörner und sieben Augen — ein Sinnbild der sieben Geister Gottes, die ausgesandt sind über die ganze Erde —.',
        7: 'Es trat hinzu und nahm das Buch aus der rechten Hand dessen, der auf dem Thron saß.',
        8: 'Als es das Buch ergriffen hatte, da fielen die vier Lebewesen und die vierundzwanzig Ältesten nieder vor dem Lamm. Jeder hatte eine Harfe und goldene Schalen voller Weihrauch — die sind ein Bild von den Gebeten der Heiligen —.',
        9: 'Sie sangen ein neues Lied und sprachen: / Du bist würdig, das Buch zu nehmen und seine Siegel zu lösen; denn du bist geopfert worden und hast Menschen für Gott erkauft mit deinem Blut aus allen Stämmen, Sprachen, Völkern und Geschlechtern',
        10: 'und hast sie gemacht für unseren Gott zu Königen und Priestern, und herrschen werden sie als Könige auf Erden."',
        11: 'Dann sah ich hin: Da hörte ich die Stimme vieler Engel rings um den Thron, die Lebewesen und die Ältesten. Ihre Zahl war zehntausendmal Zehntausende und tausendmal Tausende.',
        12: 'Sie riefen mit lauter Stimme: / "Das Lamm, das geopfert ist, ist würdig, zu empfangen Macht, Reichtum, Weisheit und Kraft, Ehre, Herrlichkeit und Lob!"',
        13: 'Und alle Geschöpfe im Himmel, auf Erden, unter der Erde und auf dem Meer, ja alles, was darinnen ist, hörte ich sagen: / "Dem, der auf dem Thron sitzt, und dem Lamm, gebühren Lob und Ehre, Herrlichkeit und Kraft in alle Ewigkeit!"',
        14: 'Die vier Lebewesen sprachen: "Amen". Und die Ältesten fielen nieder und beteten an.',
    },
    6: {
        1: 'Nun sah ich, wie das Lamm das erste von den sieben Siegeln löste, und ich hörte eins der vier Lebewesen wie mit Donnerstimme rufen: "Komm!"',
        2: 'Da sah ich: es erschien ein weißes Roß. Sein Reiter hatte einen Bogen, und ihm ward ein Kranz gereicht. Dann zog er aus von Sieg zu Sieg.',
        3: 'Als das Lamm das zweite Siegel löste, hörte ich das zweite Lebewesen rufen: "Komm!"',
        4: 'Da kam ein anderes Roß hervor, von feuerroter Farbe, und seinem Reiter ward die Macht gegeben, den Frieden von der Erde wegzunehmen und die Menschen anzureizen, einander hinzumorden; es ward ihm auch ein großes Schwert gegeben.',
        5: 'Als das Lamm das dritte Siegel löste, hörte ich das dritte Lebewesen rufen: "Komm!" Da sah ich: es erschien ein schwarzes Roß, und sein Reiter hatte eine Waage in der Hand.',
        6: 'Ich hörte, wie eine Stimme in der Mitte der vier Lebewesen sagte: "Ein Maß Weizen für einen Silberling und drei Maß Gerste für einen Silberling! Dem Öl und Wein jedoch tu keinen Schaden!"',
        7: 'Als das Lamm das vierte Siegel löste, hörte ich die Stimme des vierten Lebewesens rufen: "Komm!"',
        8: 'Da sah ich: es erschien ein fahles Roß. Sein Reiter trug den Namen "Tod", und die "Unterwelt" folgte ihm auf dem Fuß. Und sie empfingen Macht über den vierten Teil der Erde, (die Menschen) zu töten durch Schwert, Hunger und Pest und durch die wilden Tiere der Erde.',
        9: 'Als das Lamm das fünfte Siegel löste, sah ich unter dem Altar die Seelen derer, die hingeschlachtet waren um des Wortes Gottes willen und wegen des Zeugnisses, das sie treu bewahrt hatten.',
        10: 'Sie riefen mit lauter Stimme und sprachen: "Wie lange, o heiliger und wahrhaftiger Herr, soll es noch währen, bis du das Gericht vollziehst und unser Blut an den Erdbewohnern rächst?"',
        11: 'Jeder von ihnen empfing ein weißes Kleid, und sie wurden aufgefordert, noch eine kurze Weile in Geduld zu warten, bis auch ihre Mitknechte ihren Lauf vollendet hätten: ihre Brüder, die ebenso wie sie den Tod erleiden sollten.',
        12: 'Dann sah ich, wie das Lamm das sechste Siegel löste. Da entstand ein starkes Erdbeben. Die Sonne wurde schwarz wie ein härener Sack. Der ganze Mond erschien wie Blut.',
        13: 'Die Sterne des Himmels fielen auf die Erde, als wenn ein Feigenbaum, von starkem Wind bewegt, seine unreifen Früchte abwirft.',
        14: 'Der Himmel entwich wie ein Buch, das man zusammenrollt; und alle Berge und Inseln wurden von ihrer Stelle gerückt.',
        15: 'Die Könige der Erde, die Gewaltigen und die Feldobersten, die Reichen und die Starken, alle Leibeigenen und alle Freien verbargen sich in die Höhlen und die Felsen der Berge',
        16: 'und sprachen zu den Bergen und Felsen: "Fallt über uns und verbergt uns vor dem Angesicht dessen, der auf dem Thron sitzt, und vor dem Zorn des Lammes!',
        17: 'Denn der große Tag ihres Zornes ist gekommen; wer kann da bestehen?"',
    },
    7: {
        1: 'Dann sah ich vier Engel stehen an den vier Enden der Erde, die hielten die vier Winde der Erde fest, damit kein Wind wehe über die Erde noch über das Meer noch über irgendeinen Baum.',
        2: 'Auch sah ich einen anderen Engel aufsteigen von Sonnenaufgang her, der trug das Siegel des lebendigen Gottes, und er rief mit lauter Stimme den vier Engeln zu, die Macht empfangen hatten, die Erde und das Meer zu beschädigen,',
        3: 'und sprach: "Beschädigt nicht die Erde noch das Meer noch die Bäume, bis wir die Knechte unseres Gottes versiegelt haben auf ihren Stirnen!"',
        4: 'Dann vernahm ich die Zahl der Versiegelten: es waren hundertvierundvierzigtausend aus allen Stämmen der Kinder Israels.',
        5: 'Aus dem Stamm Juda waren zwölftausend versiegelt, aus dem Stamm Ruben zwölftausend, aus dem Stamm Gad zwölftausend.',
        6: 'Aus dem Stamm Asser zwölftausend, aus dem Stamm Naphtali zwölftausend, aus dem Stamm Manasse zwölftausend.',
        7: 'Aus dem Stamm Simeon zwölftausend, aus dem Stamm Levi zwölftausend, aus dem Stamm Isaschar zwölftausend.',
        8: 'Aus dem Stamm Sebulon zwölftausend, aus dem Stamm Josef zwölftausend, aus dem Stamm Benjamin waren zwölftausend versiegelt.',
        9: 'Danach sah ich eine große Schar, die niemand zählen konnte, aus allen Geschlechtern, Stämmen, Völkern und Sprachen, die stand vor dem Thron und dem Lamm. Sie waren angetan mit weißen Kleidern und trugen Palmenzweige in den Händen.',
        10: 'Sie riefen mit lauter Stimme: / "Das Heil wird uns zuteil von unserem Gott, der auf dem Thron sitzt, und von dem Lamm."',
        11: 'Alle Engel standen rings um den Thron und um die Ältesten und die vier Lebewesen. Sie fielen vor dem Thron nieder auf ihr Angesicht, beteten Gott an',
        12: 'und sprachen: / "Ja, so ist\'s. Lob, Herrlichkeit und Weisheit, Dank und Ehre, Macht und Stärke gebühren unserem Gott in alle Ewigkeit. Amen."',
        13: 'Da nahm einer von den Ältesten das Wort und sprach zu mir: "Wer sind diese, die die weißen Kleider tragen, und woher sind sie gekommen?"',
        14: 'Ich antwortete ihm: "Mein Herr, du weißt es." Da sprach er zu mir: "Diese sind gekommen aus der großen Trübsal und haben ihre Kleider in des Lammes Blut gewaschen und gebleicht.',
        15: 'Darum stehen sie nun vor Gottes Thron und dienen ihm bei Tag und Nacht in seinem Tempel; und er, der auf dem Thron sitzt, wird sie in seinem Zelt schützen.',
        16: 'Sie wird nicht mehr hungern, nicht mehr dürsten; die Sonne und der Glutwind trifft sie nicht.',
        17: 'Denn das Lamm, das mitten vor dem Thron steht, wird sie weiden und leiten zu des Lebens Wasserquellen, und Gott wird alle Tränen aus ihren Augen wischen."',
    },
    8: {
        1: 'Als das Lamm das siebente Siegel löste, trat eine Stille ein im Himmel etwa eine halbe Stunde lang.',
        2: 'Ich sah die sieben Engel, die vor Gott stehen, und sie empfingen sieben Posaunen.',
        3: 'Dann kam ein anderer Engel und trat an den Altar. Der hatte ein goldenes Rauchfaß, und er empfing viel Weihrauch, damit er ihn zugleich mit den Gebeten aller Heiligen auf dem goldenen Altar vor dem Thron darbringe.',
        4: 'Und die Weihrauchwolke stieg zugleich mit den Gebeten der Heiligen aus des Engels Hand vor Gott empor.',
        5: 'Dann nahm der Engel das Rauchfaß, füllte es mit glühenden Kohlen vom Altar und schüttete es auf die Erde. Da folgten laute Donnerschläge, Blitze und Erdbeben.',
        6: 'Nun rüsteten sich die sieben Engel, die die sieben Posaunen hatten, sie zu blasen.',
        7: 'Der erste Engel stieß in die Posaune. Da kam Hagel und Feuer, mit Blut vermischt, und fiel auf die Erde nieder. Der dritte Teil der Erde verbrannte, der dritte Teil der Bäume verbrannte, und alles grüne Gras verbrannte.',
        8: 'Der zweite Engel stieß in die Posaune. Da ward eine Masse, die aussah wie ein großer, feuerflammender Berg, ins Meer geschleudert. Dadurch ward der dritte Teil des Meeres in Blut verwandelt,',
        9: 'der dritte Teil der Tiere, die im Meer lebten, starb, und der dritte Teil der Schiffe ging zugrunde.',
        10: 'Der dritte Engel stieß in die Posaune. Da fiel ein großer Stern vom Himmel, brennend wie eine Fackel. Der fiel auf den dritten Teil der Ströme und auf die Wasserquellen;',
        11: 'und des Sternes Name heißt "Wermut". Da ward der dritte Teil der Wasser zu Wermut, und viele Menschen starben von den Wassern, weil sie bitter geworden waren.',
        12: 'Der vierte Engel stieß in die Posaune. Da ward geschlagen der dritte Teil der Sonne, der dritte Teil des Mondes und der dritte Teil der Sterne, so daß ihr dritter Teil verfinstert wurde. Darum hatte nun der dritte Teil des Tages und ebenso der Nacht kein Licht.',
        13: 'Dann sah ich hin. Da hörte ich einen Adler, der hoch oben am Himmel flog, mit lauter Stimme rufen: "Weh, weh, weh den Erdbewohnern wegen der anderen Posaunenstimmen der drei Engel, die noch posaunen sollen!"',
    },
    9: {
        1: 'Nun stieß der fünfte Engel in die Posaune. Da sah ich einen Stern, der war vom Himmel her gefallen auf die Erde, und er empfing den Schlüssel zu dem Brunnen des Abgrunds.',
        2: 'Er tat des Abgrunds Brunnen auf. Da stieg ein Rauch empor aus diesem Brunnen wie eines großen Ofens Rauch, und es wurden die Sonne und die Luft verfinstert von dem Rauch des Brunnens.',
        3: 'Aus dem Rauch kamen Heuschrecken über die Erde; die empfingen Macht ähnlich wie irdische Skorpione.',
        4: 'Ihnen wurde gesagt, sie sollten dem Gras der Erde keinen Schaden tun, auch nicht dem Grün noch irgendeinem Baum, sondern nur den Menschen, die nicht Gottes Siegel an ihren Stirnen haben.',
        5: 'Aber sie durften sie nicht töten, sie sollten sie nur peinigen fünf Monate lang. Die Pein, die sie bereiteten, glich der Pein, die ein Skorpion verursacht, wenn er einen Menschen sticht.',
        6: 'In jenen Tagen werden die Menschen den Tod suchen und nicht finden; sie werden Sehnsucht haben zu sterben, doch der Tod entflieht vor ihnen.',
        7: 'Die Heuschrecken glichen Rossen, die zum Kampf gerüstet sind. Auf ihren Häuptern hatten sie einen Schmuck, der goldenen Kronen ähnlich war. Ihre Gesichter waren wie Menschengesichter,',
        8: 'ihre Haare waren so lang wie Weiberhaare, ihre Zähne glichen Löwenzähnen.',
        9: 'Sie trugen Panzer wie von Eisen. Das Rauschen ihrer Flügel klang wie das Rasseln von Kriegswagen, wenn viele Rosse in den Kampf stürmen.',
        10: 'Sie hatten Schwänze gleich Skorpionen und Stacheln; in ihren Schwänzen lag ihre Kraft, den Menschen fünf Monate lang Schaden zu tun.',
        11: 'Als König hatten sie über sich den Engel des Abgrunds; der heißt auf hebräisch Abaddón, und auf griechisch heißt er Apollyon.',
        12: 'Das erste Weh ist vorüber. Doch es kommen noch zwei Wehe hinterher.',
        13: 'Nun stieß der sechste Engel in die Posaune. Da hörte ich eine Stimme aus den vier Hörnern des goldenen Altars, der vor Gott steht,',
        14: 'die sprach zu dem sechsten Engel, der die Posaune hatte: "Laß die vier Engel los, die bei dem großen Strom Euphrat angebunden sind!"',
        15: 'Die vier Engel, die auf die Stunde, den Tag, den Monat und das Jahr bereitstanden, den dritten Teil der Menschen zu töten, wurden nun losgelassen.',
        16: 'Ihr Reiterheer hatte zweihundert Millionen Geschwader, ich hörte ihre Zahl.',
        17: 'Und dies war das Aussehen der Rosse und der Reiter, die ich in dem Gesichte sah: Die Reiter hatten rote, blaue und goldgelbe Panzer. Die Köpfe der Rosse waren wie Löwenköpfe, und aus ihren Mäulern gingen Feuer, Rauch und Schwefel.',
        18: 'Durch diese drei Plagen, das Feuer, den Rauch und den Schwefel, die aus ihren Mäulern gingen, wurde ein Drittel der Menschen getötet.',
        19: 'Denn die Kraft der Rosse liegt in ihrem Maul und in ihren Schwänzen. Ihre Schwänze sehen wie Schlangen aus und haben Köpfe, und mit diesen tun sie Schaden.',
        20: 'Die anderen Menschen, die bei diesen Plagen nicht ums Leben kamen, bekehrten sich trotzdem nicht von den Werken ihrer Hände, sondern fuhren fort, die bösen Geister anzubeten und die Götzenbilder aus Gold und Silber, Erz, Stein und Holz, die doch nicht sehen, hören und gehen können.',
        21: 'Sie bekehrten sich nicht von ihren Mordtaten, ihren Zaubereien, ihrer Hurerei und ihren Diebereien.',
    },
    10: {
        1: 'Dann sah ich einen anderen starken Engel aus dem Himmel niedersteigen. Der war bekleidet mit einer Wolke, ein Regenbogen war auf seinem Haupt, sein Antlitz strahlte wie die Sonne, und seine Füße glichen Feuersäulen.',
        2: 'In seiner Hand hatte er ein offenes kleines Buch. Er setzte seinen rechten Fuß auf das Meer, den linken auf das Land',
        3: 'und rief mit lauter Stimme, als wenn ein Löwe brüllt. Und als er rief, da ließen die sieben Donner ihre Stimme erschallen.',
        4: 'Als die sieben Donner geredet hatten, wollte ich ihre Botschaft niederschreiben. Da hörte ich eine Stimme aus dem Himmel sagen: "Versiegele, was die sieben Donner geredet haben, und schreibe es nicht nieder!"',
        5: 'Nun hob der Engel, den ich auf dem Meer und auf dem Land stehen sah, seine rechte Hand zum Himmel auf',
        6: 'und schwur bei dem, der lebt in alle Ewigkeit, der den Himmel und was darin ist, die Erde und was darauf ist und das Meer und was darin ist geschaffen hat: "Es soll jetzt kein Verzug mehr sein!',
        7: 'Sondern in den Tagen, wenn der siebente Engel sich anschickt zu posaunen, da vollendet sich der geheime Ratschluß Gottes, wie er ihn seinen Knechten, den Propheten, als Frohe Botschaft kundgetan."',
        8: 'Dann redete die Stimme, die ich vom Himmel aus gehört, ein andermal mit mir und sprach: "Geh, nimm das Buch, das offen daliegt in der Hand des Engels, der auf dem Meer und auf dem Land steht!"',
        9: 'Da ging ich zu dem Engel und bat ihn, mir das kleine Buch zu geben. Und er sprach zu mir: "Nimm und verzehre es! Es wird dir zwar in deinem Magen Bitterkeit bereiten, in deinem Mund aber wird es süß wie Honig sein."',
        10: "So nahm ich denn das Büchlein aus des Engels Hand und aß es, und wirklich war's in meinem Mund süß wie Honig. Doch als ich es gegessen hatte, da ward es mir im Magen bitter.",
        11: 'Und eine Stimme sprach zu mir: "Du mußt noch einmal weissagen über viele Völker, Scharen, Sprachen und Könige."',
    },
    11: {
        1: 'Danach ward mir ein Rohr gegeben, einem Meßstab gleich, und eine Stimme sprach: / Steh auf und miß den Tempel Gottes mit dem Altar und denen, die dort anbeten!',
        2: 'Doch den äußeren Tempelvorhof laß aus und miß ihn nicht! Denn er ist den Heiden preisgegeben, und sie werden die heilige Stadt verwüsten zweiundvierzig Monate lang.',
        3: 'Ich will aber meinen zwei Zeugen Auftrag geben, und sie sollen weissagen zwölfhundertsechzig Tage lang, mit Säcken angetan.',
        4: 'Dies sind die beiden Ölbäume und die beiden Leuchter, die vor dem Herrn der Erde stehen.',
        5: 'Will sich jemand an ihnen vergreifen, so geht Feuer aus ihrem Mund und verzehrt ihre Feinde. Ja, will sich jemand an ihnen vergreifen, der soll auf diese Weise getötet werden.',
        6: 'Sie haben die Vollmacht, den Himmel zu verschließen, damit kein Regen falle in den Tagen ihrer Weissagung. Sie haben auch die Vollmacht, das Wasser in Blut zu verwandeln und die Erde zu schlagen mit allerlei Plagen, sooft sie wollen.',
        7: 'Wenn sie aber ihr Zeugnis vollendet haben, dann wird das Tier, das aus dem Abgrund steigt, mit ihnen kämpfen, er wird sie überwinden und töten.',
        8: 'Ihre Leichen werden liegen auf dem Marktplatz jener großen Stadt, die geistlich Sodom und Ägypten heißt, wo auch ihr Herr gekreuzigt worden ist.',
        9: 'Leute aus allen Völkern, Stämmen, Sprachen und Geschlechtern werden ihre Leichen drei und einen halben Tag daliegen sehen; aber sie werden nicht dulden, daß man ihre Leichen begrabe.',
        10: 'Denn die Erdbewohner freuen sich über ihren Tod und sind voll Jubel, ja sie werden einander Geschenke senden; denn diese beiden Propheten bereiteten den Erdbewohnern Qual.',
        11: 'Nach der halben Woche aber kam ein Lebenshauch von Gott in sie: sie stellten sich auf ihre Füße, und große Furcht erfaßte alle, die sie sahen.',
        12: 'Dann hörte ich, wie eine laute Stimme vom Himmel zu ihnen sprach: "Kommt hierher!" Da stiegen sie vor den Augen ihrer Feinde in einer Wolke zum Himmel auf.',
        13: 'Zu derselben Stunde geschah ein großes Erdbeben: der zehnte Teil der Stadt sank in Trümmer, und siebentausend Menschen fanden bei dem Erdbeben ihren Tod. Die Überlebenden aber wurden mit Furcht erfüllt und gaben dem Gott des Himmels die Ehre.',
        14: 'Das zweite Weh ist vorüber. Das dritte Weh kommt eilend.',
        15: 'Nun stieß der siebente Engel in die Posaune. Da erschallten laute Stimmen im Himmel, die sprachen: / "Die Herrschaft über die Welt gehört jetzt unserem Herrn und seinem Gesalbten, und er wird König sein in alle Ewigkeit."',
        16: 'Da fielen die vierundzwanzig Ältesten, die in Gottes Gegenwart auf ihren Thronen sitzen, auf ihr Angesicht; sie beteten Gott an',
        17: 'und sprachen: / Wir danken dir, Herr Gott, du Allgewaltiger, der ist und der da war; denn du hast deine große Macht an dich genommen und herrschst nun als König.',
        18: 'Die Völker sind in Wut geraten; darum ist dein Zorn entbrannt. Die Zeit ist da, da du die Toten richtest, den Lohn austeilst deinen Knechten, den Propheten, und den Heiligen samt allen, die deinen Nahmen fürchten, den Kleinen wie den Großen, und wo du über die Verderben bringst, die die Welt verderben."',
        19: 'Da öffnete sich der Tempel Gottes im Himmel, daß die Lade seines Bundes in seinem Tempel sichtbar wurde. Zugleich entstanden Blitze, laute Donnerschläge, Erdbeben und ein starkes Hagelwetter.',
    },
    12: {
        1: 'Dann erschien ein großes Zeichen im Himmel: ein Weib, das war mit der Sonne bekleidet, der Mond lag unter ihren Füßen, und auf ihrem Haupt trug sie eine Krone von zwölf Sternen.',
        2: 'Sie sah ihrer Niederkunft entgegen und schrie in Wehen und Kindesnöten.',
        3: 'Zugleich erschien ein anderes Zeichen im Himmel: ein großer feuerroter Drache, der hatte sieben Häupter und zehn Hörner, und auf seinen Häuptern (glänzten) sieben Kronen;',
        4: 'sein Schweif fegte den dritten Teil der Sterne des Himmels weg und warf sie nieder auf die Erde. Dieser Drache stellte sich vor das Weib, das im Begriff war zu gebären, um ihr Kindlein sofort nach der Geburt zu verschlingen.',
        5: 'Und sie gebar einen Sohn, einen kraftvollen Knaben, der alle Völker mit eisernem Stab weiden soll. Ihr Kind ward entrückt zu Gott und seinem Thron.',
        6: 'Das Weib entfloh in die Wüste: dort fand sie eine Stätte, von Gott bereitet, wo sie zwölfhundertsechzig Tage lang ernährt werden sollte.',
        7: 'Da entstand ein Kampf im Himmel: Michael und seine Engel stritten mit dem Drachen. Der Drache setzte sich zur Wehr mit seinen Engeln;',
        8: 'doch sie wurden überwunden, und ihres Bleibens war nicht länger mehr im Himmel.',
        9: 'Es ward hinabgestürzt der große Drache, die alte Schlange, die auch der Teufel oder der Satan heißt und die ganze Welt verführt; hinabgestürzt ward er zur Erde, und seine Engel mit ihm.',
        10: 'Dann hörte ich eine laute Stimme im Himmel rufen: / Jetzt sind erschienen unseres Gottes Heil und Kraft und Königreich, und sein Gesalbter hat die Macht empfangen. Denn der Verkläger unserer Brüder ist hinabgestürzt, der sie vor unserem Gott verklagt hat Tag und Nacht.',
        11: 'Sie haben über ihn gesiegt; als Waffen hatten sie des Lammes Blut und jenes Wort, durch das sie Zeugnis abgelegt. Dabei sind sie sogar bereit gewesen, ihr Leben in den Tod zu geben.',
        12: 'Darum freut euch, ihr Himmel, und alle, die ihr darin wohnt! Doch weh der Erde und dem Meer! Der Teufel ist zu euch hinabgekommen mit großem Grimm. Er weiß ja: seine Frist ist nur noch kurz."',
        13: 'Als der Drache sah, daß er hinabgestürzt war auf die Erde, verfolgte er das Weib, das den Knaben geboren hatte.',
        14: 'Das Weib aber empfing die beiden Flügel des großen Adlers, damit sie in die Wüste fliege an die ihr bestimmte Stätte, wo sie, sicher vor dem Grimm der Schlange, eine Zeit und (zwei) Zeiten und eine halbe Zeit ernährt werden sollte.',
        15: 'Da schoß die Schlange aus ihrem Maul einen Strom von Wasser hinter dem Weib her, um es in dieser Flut zu ertränken.',
        16: 'Doch die Erde kam dem Weib zu Hilfe: sie öffnete ihren Mund und verschluckte den Strom, den der Drache aus seinem Maul ergossen hatte.',
        17: 'Da ward der Drache grimmig über das Weib und ging hin, um zu streiten mit ihren anderen Kindern, die Gottes Gebote halten und das Jesuszeugnis treu bewahren. Ich trat nun an den Strand des Meeres.',
    },
    13: {
        1: 'Da sah ich aus dem Meer ein Tier aufsteigen, das hatte zehn Hörner und sieben Häupter. Auf seinen Hörnern trug es zehn Kronen, und auf seinen Häuptern standen gotteslästerliche Namen.',
        2: 'Dies Tier, das ich sah, glich einem Panther; seine Füße waren wie Bärenfüße, und sein Rachen war wie ein Löwenrachen. Und der Drache gab ihm seine Kraft, seinen Thron und große Macht.',
        3: 'Ich sah, wie eins von seinen Häuptern gleichsam einen Todesstreich empfangen hatte. Aber seine Todeswunde ward geheilt. Da beugte sich die ganze Welt bewundernd vor dem Tier.',
        4: 'Man betete den Drachen an, weil er dem Tier die Gewalt gegeben, und man betete auch das Tier an und sprach: "Wer gleicht dem Tier, und wer kann mit ihm streiten?"',
        5: 'Das Tier empfing ein Maul, das Reden ausstieß voller Stolz und Lästerung; und ihm wurde erlaubt, es zweiundvierzig Monate so zu treiben.',
        6: 'Es öffnete sein Maul zur Lästerung gegen Gott; es lästerte seinen Namen und seine Wohnung: jene, die im Himmel wohnen.',
        7: 'Es ward ihm auch erlaubt, mit den Heiligen zu kämpfen und sie zu überwinden. Ja es empfing Gewalt über alle Stämme, Völker, Sprachen und Geschlechter.',
        8: 'Alle Erdbewohner beteten es an: alle, deren Namen nicht seit Anbeginn der Welt verzeichnet sind im Lebensbuch des Lammes, das geopfert ist.',
        9: 'Wer Ohren hat, der höre:',
        10: 'Wer andere in Gefangenschaft führt, soll selbst in die Gefangenschaft wandern; wer andere mit dem Schwert tötet, soll selbst durchs Schwert getötet werden! Hier gilt es für die Heiligen, Standhaftigkeit und Treue zu beweisen.',
        11: 'Dann sah ich ein anderes Tier aufsteigen aus der Erde, das hatte zwei Hörner, ähnlich wie ein Lamm, es redete aber wie der Drache.',
        12: 'Es vollzog alle Befehle des ersten Tieres unter dessen Augen. Es brachte die Erde und ihre Bewohner dahin, das erste Tier, dessen Todeswunde heil geworden war, göttlich zu verehren.',
        13: 'Es tat auch große Wunderzeichen; sogar Feuer ließ es vor der Menschen Augen vom Himmel auf die Erde fallen.',
        14: 'Durch diese Wunderzeichen, die ihm verliehen wurden in des Tieres Gegenwart zu tun, verführte es die Erdbewohner. Ja es forderte sie auf, dem Tier, das trotz seiner Schwertwunde am Leben geblieben war, ein Standbild zu errichten.',
        15: 'Es empfing auch die Macht, dieses Bild des Tieres mit Leben zu erfüllen. Daher konnte des Tieres Bild sogar reden; und es erreichte, daß alle, die des Tieres Bild nicht anbeten wollten, getötet wurden.',
        16: 'Ja alle Leute, klein und groß, reich und arm, frei und unfrei, alle brachte es dazu, auf ihrer rechten Hand oder auf ihrer Stirn ein Zeichen anzunehmen.',
        17: 'Keiner sollte kaufen oder verkaufen dürfen, der nicht dies Zeichen hätte: entweder des Tieres Namen oder seines Namens Zahl.',
        18: 'Hier gilt es Weisheit! Wer Einsicht hat, der mag des Tieres Zahl berechnen; denn sie ist eines Menschen Zahl. Und zwar ist seine Zahl 666.',
    },
    14: {
        1: 'Ich schaute ein Gesicht: das Lamm stand auf dem Berg Zion, umgeben von hundertvierundvierzigtausend, die seinen Namen und seines Vaters Namen auf ihrer Stirn geschrieben trugen.',
        2: 'Auch hörte ich eine Stimme aus dem Himmel; die klang wie Meeresrauschen und starkes Donnerrollen. Die Stimme, die ich hörte, klang zugleich wie das Spiel von Saitenspielern, die ihre Harfen schlagen.',
        3: 'Sie sangen ein neues Lied vor dem Thron, den vier Lebewesen und den Ältesten, und niemand konnte dieses Lied erlernen als nur die Hundertvierundvierzigtausend, die von der Erde abgesondert und erkauft sind.',
        4: 'Diese haben sich nicht durch den Verkehr mit Weibern befleckt, denn sie sind (rein wie) Jungfrauen. Sie folgen dem Lamm, wohin es auch gehen mag. Sie sind aus der Menschheit erkauft worden als eine Erstlingsschar für Gott und das Lamm.',
        5: 'In ihrem Mund findet sich kein Trug; sie sind ganz ohne Fehl und Flecken.',
        6: 'Ich sah einen anderen Engel hoch oben am Himmel fliegen, der hatte den Erdbewohnern, ja allen Geschlechtern, Stämmen, Sprachen und Völkern eine seit Ewigkeit beschlossene Frohe Botschaft zu verkündigen.',
        7: 'Er rief mit lauter Stimme: "Fürchtet Gott und gebt ihm Ehre, denn die Stunde seines Gerichts ist nun da! Betet ihn an, der Himmel und Erde, Meer und Wasserquellen geschaffen hat!"',
        8: 'Ein zweiter Engel folgte ihm und sprach: / "Gefallen, gefallen ist das große Babylon, das von dem Glutwein seiner Buhlerei hat alle Völker trinken lassen!"',
        9: 'Ein dritter Engel folgte diesen beiden, der rief mit lauter Stimme: / Alle, die das Tier anbeten und sein Bild, und die ein Zeichen nehmen auf ihre Stirn oder ihre Hand,',
        10: 'die sollen trinken von dem Glutwein Gottes, der unvermischt in seinem Zornesbecher steht, und vor der heiligen Engel und des Lammes Augen in Feuer und in Schwefel Qualen leiden.',
        11: 'Der Rauch von ihrer Qual steigt auf in Ewigkeit, und ruhelos sollen sein bei Tag und Nacht die Menschen, die das Tier anbeten und sein Bild und seines Namens Zeichen an sich nehmen.',
        12: 'Hier gilt es standhaft auszuharren für die Heiligen, die treu bewahren die Gebote Gottes und den Jesusglauben."',
        13: 'Dann hörte ich eine Stimme aus dem Himmel, die sprach: "Schreibe: / \'Selig sind von nun an alle Toten, die in dem Herrn sterben!\' — Ja — so spricht der Geist — sie sollen ruhen von ihren Mühen; denn ihre Werke folgen ihnen nach."',
        14: 'Ich nahm auch eine weiße Wolke wahr, und auf der Wolke sah ich einen sitzen gleich einem Menschensohn, der trug auf seinem Haupt eine goldene Krone, und eine scharfe Sichel hielt er in der Hand.',
        15: 'Da trat ein anderer Engel aus dem Tempel, der rief mit lauter Stimme zu dem, der auf der Wolke saß: "Leg deine Sichel an und ernte! Die Erntezeit ist da, denn reif geworden ist der Erde Ernte."',
        16: 'Jetzt ließ der, der auf der Wolke saß, seine Sichel über die Erde fahren, und die Erde wurde geerntet.',
        17: 'Ein anderer Engel trat aus dem Himmelstempel; auch er hielt eine scharfe Sichel.',
        18: 'Ein anderer Engel trat aus dem Altar hervor, der hatte Macht über das Feuer und sprach mit lauter Stimme zu dem, der die scharfe Sichel hatte: "Leg deine scharfe Sichel an und ernte die Trauben von dem Weinstock der Erde; denn seine Beeren sind nun reif!"',
        19: 'Da warf der Engel seine Sichel auf die Erde, er erntete die Trauben von dem Weinstock der Erde und warf sie in die große Kelter des Zornes Gottes.',
        20: 'Die Kelter ward außerhalb der Stadt getreten. Da floß Blut aus der Kelter hervor bis hinauf an die Zügel der Rosse, etwa vierzig Meilen weit.',
    },
    15: {
        1: 'Ich sah ein anderes Zeichen im Himmel, groß und wunderbar: sieben Engel mit den letzten sieben Plagen, womit sich Gottes Zorn vollendet.',
        2: 'Auch sah ich (eine weite Fläche) wie ein gläsern Meer, gemengt mit Feuer. An diesem Meer von Glas sah ich alle stehen, die in dem Kampf mit dem Tier, seinem Bild und seines Namens Zahl den Sieg errungen hatten. Sie priesen Gott auf Saitenspiel',
        3: 'und sangen das Lied Moses, des Knechtes Gottes, und des Lammes Lied mit diesen Worten: / Groß und wunderbar sind deine Werke, Herr Gott, du Allgewaltiger; gerecht und wahr sind deine Wege, du Völkerkönig!',
        4: 'Wer sollte dich nicht fürchten, Herr, nicht deinen Namen preisen? Denn du allein bist heilig. Alle Völker werden kommen und vor dir anbeten, denn dein gerechtes Walten hat sich offenbart."',
        5: 'Dann sah ich, wie sich der Tempel der himmlischen Stiftshütte öffnete.',
        6: 'Aus dem Tempel traten die sieben Engel mit den sieben Plagen. Sie trugen ein glänzend weißes Linnenkleid, und goldene Gürtel umgaben ihre Brust.',
        7: 'Eins der vier Lebewesen reichte den sieben Engeln sieben goldene Schalen, voll des Zornes Gottes, der da lebt in alle Ewigkeit.',
        8: 'Da füllte sich der Tempel mit Rauch, weil Gottes Herrlichkeit und seine Macht sich offenbarten; und niemand konnte in den Tempel gehen, bis die sieben Plagen der sieben Engel zu Ende waren.',
    },
    16: {
        1: 'Nun hörte ich eine laute Stimme aus dem Tempel zu den sieben Engeln sagen: "Geht, gießt jetzt die sieben Schalen des Zornes Gottes auf die Erde aus!"',
        2: 'Da ging der erste Engel hin und goß seine Schale auf die Erde. Da kamen bösartige, verderbliche Geschwüre auf alle, die des Tieres Zeichen trugen und sein Bild anbeteten.',
        3: 'Der zweite Engel goß seine Schale auf das Meer. Da wurde es zu Blut, wie Leichenblut, und alle Lebewesen, die im Meer waren, starben.',
        4: 'Der dritte Engel goß seine Schale auf die Flüsse und die Wasserquellen. Da wurden sie in Blut verwandelt.',
        5: 'Dann hörte ich den Engel der Gewässer sagen: "Gerecht bist du, der ist und der da war, du Heiliger, daß du also gerichtet hast!',
        6: 'Weil sie der Heiligen und Propheten Blut vergossen haben, hast du auch Blut sie trinken lassen. Sie haben\'s so verdient."',
        7: 'Und ich hörte den Altar sagen: "Ja, Herr Gott, du Allgewaltiger, wahrhaftig und gerecht sind deine Urteilssprüche."',
        8: 'Der vierte Engel goß seine Schale auf die Sonne, und sie empfing Gewalt, die Menschen mit Feuerglut zu quälen.',
        9: 'Da wurden die Menschen von gewaltiger Glut versengt. Trotzdem lästerten sie den Namen Gottes, der Macht hat über diese Plagen, und bekehrten sich nicht dazu, ihm Ehre zu geben.',
        10: 'Der fünfte Engel goß seine Schale auf den Thron des Tieres. Da ward sein Reich mit Finsternis bedeckt. Ja die Menschen zerbissen sich vor Schmerz die Zungen',
        11: 'und lästerten den Gott des Himmels wegen ihrer Schmerzen und Geschwüre. Aber von ihren bösen Werken bekehrten sie sich nicht.',
        12: 'Der sechste Engel goß seine Schale auf den großen Euphratstrom. Da trocknete sein Wasser aus, damit den Königen, die von Osten kommen sollen, der Weg gebahnt würde.',
        13: 'Dann sah ich aus des Drachen Maul und aus des Tieres Maul und aus dem Mund des falschen Propheten drei unreine Geister kommen, die Fröschen ähnlich waren',
        14: '- es gibt ja böse Geister, die Wunderzeichen tun —. Die zogen aus zu den Königen der ganzen Erde, um sie zu sammeln für den Kampf, der an dem großen Tag Gottes, des Allgewaltigen, gehalten werden soll.',
        15: '"Sieh, ich komme wie ein Dieb! Selig ist, der wacht und seine Kleider bereit hat, damit er nicht nackt gehen und seine Blöße zeigen müsse!"',
        16: 'Die bösen Geister sammelten die Könige an dem Ort, der auf hebräisch Harmagedon heißt.',
        17: 'Der siebente Engel goß seine Schale in die Luft. Da kam eine laute Stimme aus dem Tempel vom Thron her, die sprach: "Es ist geschehen!"',
        18: 'Nun folgten Blitze und laute Donnerschläge; und es entstand ein großes Erdbeben, wie noch nie eins dagewesen ist, solange Menschen auf Erden wohnen, so furchtbar und so schrecklich!',
        19: 'Die große Stadt barst in drei Teile auseinander, und die Städte der Völker sanken in Trümmer. So gedachte Gott des großen Babylon und reichte ihm dar den Becher des Glutweins seines Zornes.',
        20: 'Alle Inseln verschwanden, und Berge waren nicht mehr zu sehen.',
        21: 'Große Hagelstücke, etwa einen halben Zentner schwer, fielen auf die Menschen nieder. Aber die Menschen lästerten Gott wegen der Plage des Hagelwetters, denn diese Plage war sehr groß.',
    },
    17: {
        1: 'Da kam einer von den sieben Engeln, die die sieben Schalen hatten, redete mit mir und sprach: "Komm, ich will dir zeigen das Gericht über die große Buhlerin, die an großen Wassern wohnt,',
        2: 'mit der die Könige der Erde gebuhlt und an deren Buhlwein sich die Erdbewohner berauscht haben."',
        3: 'Dann führte er mich im Geist in eine Wüste. Dort sah ich ein Weib auf einem scharlachroten Tier sitzen. Dies Tier war ganz bedeckt mit Lästernamen und hatte sieben Häupter und zehn Hörner.',
        4: 'Das Weib war in Purpur und Scharlach gekleidet und ganz bedeckt mit Gold, Edelsteinen und Perlen. In ihrer Hand hielt sie einen goldenen Becher voller Greuel und gefüllt mit dem Schmutz ihrer Buhlerei.',
        5: 'Auf ihrer Stirn stand ein geheimnisvoller Name: Das große Babylon, die Mutter der Buhlerinnen und der Greuel auf Erden.',
        6: 'Ich sah das Weib berauscht von dem Blut der Heiligen und von dem Blut der Zeugen Jesu. Bei ihrem Anblick war ich sehr erstaunt.',
        7: 'Da sprach der Engel zu mir: "Warum bist du so erstaunt? Ich will dir kundtun das Geheimnis dieses Weibes und des Tieres mit den sieben Häuptern und den zehn Hörnern, von dem das Weib getragen wird.',
        8: 'Das Tier, das du gesehen, ist schon früher dagewesen und ist jetzt nicht mehr. Doch wird es wieder aus dem Abgrund steigen, und dann geht es für immer ins Verderben. Alle Erdbewohner, deren Namen nicht seit Anbeginn der Welt im Lebensbuch geschrieben stehen, werden staunen, wenn sie das Tier erblicken. Denn es ist schon früher dagewesen, ist jetzt nicht mehr und soll doch wieder dasein.',
        9: "Hier gilt's, mit Weisheit nachzudenken! Die sieben Häupter bedeuten sieben Berge: auf diesen sitzt das Weib. Sie bedeuten aber auch sieben Könige.",
        10: 'Fünf von ihnen sind gefallen; der eine ist jetzt da. Der andere ist noch nicht gekommen; doch wenn er kommt, soll er nur eine kurze Weile bleiben.',
        11: 'Das Tier aber, das schon früher dagewesen und jetzt nicht mehr ist, ist selbst ein achter König; aber es ist auch einer von den sieben, und es geht ins Verderben.',
        12: 'Die zehn Hörner, die du gesehen, bedeuten zehn Könige. Sie sind noch nicht zur Macht gekommen; aber sie empfangen, wenn auch nur für eine kleine Weile, eine Herrschaft, wie sie Könige besitzen, und zwar gemeinsam mit dem Tier.',
        13: 'Diese (zehn Könige) haben einen Sinn und übertragen ihre Kraft und Macht dem Tier.',
        14: 'Sie werden mit dem Lamm kämpfen. Doch das Lamm wird sie besiegen, denn es ist der Herr aller Herren und der König aller Könige. Und seine Genossen — die Berufenen, Auserwählten und Getreuen — werden mit ihm überwinden."',
        15: 'Weiter sprach er zu mir: "Die Wasser, an deren Ufern du die Buhlerin hast sitzen sehen, bedeuten Völker und Scharen, Geschlechter und Sprachen.',
        16: 'Die zehn Hörner, die du gesehen — und das Tier selbst —, die werden die Buhlerin hassen und völlig ausplündern; ja sie werden ihr Fleisch verzehren und sie mit Feuer verbrennen.',
        17: 'Denn Gott hat es ihnen ins Herz gegeben, daß sie, um seinen Willen auszuführen, ganz in einem Sinn handeln und ihre Herrschaft so lange dem Tier übertragen, bis sich Gottes Worte erfüllt haben.',
        18: 'Das Weib, das du gesehen, ist die große Stadt, die über die Könige der Erde die Herrschaft führt."',
    },
    18: {
        1: 'Dann sah ich einen anderen Engel aus dem Himmel herniedersteigen, der war ausgerüstet mit großer Macht, so daß die Erde von dem Glanz seiner Herrlichkeit erleuchtet wurde.',
        2: 'Er rief mit gewaltiger Stimme: / Gefallen, gefallen ist Babylon, die große Stadt! Sie ist nun eine Teufelswohnung und ein Gefängnis aller unreinen Geister und ein Gefängnis aller unreinen und verhaßten Vögel.',
        3: 'Denn alle Völker haben von dem Glutwein ihrer Buhlerei getrunken; es haben mit ihr Buhlerei getrieben die Könige der Erde, und die Kaufleute auf Erden sind reich geworden durch ihre große Üppigkeit."',
        4: 'Eine andere Stimme aus dem Himmel hörte ich sagen: / Geht aus von ihr, mein Volk, damit ihr nicht teilhaftig werdet ihrer Sünden und nicht empfangt einen Teil von ihren Plagen!',
        5: 'Denn ihre Sünden reichen bis zum Himmel, und Gott gedenkt nun ihrer Frevel.',
        6: 'Tut ihr, wie sie getan, ja zahlt ihr zwiefach ihre Werke heim und schenkt ihr doppelt ein den Becher, den sie euch gereicht!',
        7: "So sehr sie sich in Stolz erhoben und geschwelgt, so große Pein und Trauer fügt ihr zu! / Weil sie in ihrem Herzen spricht: 'Ich throne hier als Königin, bin keine Witwe und werde nimmer Trauer sehen',",
        8: 'darum werden an einem Tag ihre Plagen kommen: Tod, Leid und Hungersnot, ja Feuer soll sie niederbrennen bis zum Grund. Denn stark ist Gott der Herr, ihr Richter.',
        9: 'Es werden weinend klagen über sie die Könige der Erde, die mit ihr Buhlerei getrieben und geschwelgt, wenn sie den Rauch von ihrem Brand sehen.',
        10: "Entsetzt von ihrer Plage, stehen sie von fern und rufen: 'Wehe, wehe! Babylon, du große, starke Stadt! In einer Stunde ist nun dein Gericht gekommen!'",
        11: 'Auch die Kaufleute der Erde werden weinend klagen über sie. / Denn niemand kauft nun ihre Waren mehr:',
        12: 'Die Waren von Gold und Silber, von Edelsteinen und Perlen, von feiner Leinwand, Purpur, Seide und Scharlach, all das edle Duftholz und Gerät von Elfenbein, all das Gerät aus feinstem Holz, aus Kupfer, Eisen und Marmor;',
        13: 'Zimt und Balsam nebst Gewürz und Salben, Weihrauch, Wein und Öl; Feinmehl und Weizen, Groß- und Kleinvieh; Rosse, Wagen und leibeigene Leute.',
        14: 'Auch all die Früchte, die dein Herz erfreuten, sind nun für dich dahin, und aller Glanz und Flitter ist dir hingeschwunden und nimmermehr zu finden.',
        15: 'Die mit solchen Waren handelten und an ihr reich geworden sind, die werden entsetzt vor ihrer Plage, von ferne stehen und unter Tränen klagen:',
        16: "'Weh, weh! Die große Stadt, die einst sich kleidete in feine Leinwand, Purpurstoff und Scharlach, und die von Gold, von Edelsteinen und von Perlen strotzte,",
        17: "in einer Stunde hat sie alle Pracht verloren!' / Auch alle Steuerleute, alle Küstenfahrer, die Schiffer, und die sonst zur See beschäftigt sind, die alle blieben von ferne stehen.",
        18: "Und als sie sahen den Rauch von ihrem Brand, da riefen sie mit lauter Stimme: 'Welche Stadt war zu vergleichen mit der großen Stadt?'",
        19: "Sie warfen Staub auf ihre Häupter, und weinend und wehklagend riefen sie: 'Weh, weh! Die große Stadt, von deren Schätzen alle, die Schiffe auf dem Meer hatten, reich geworden sind, in einer Stunde ist sie wüst geworden!'",
        20: 'Frohlocke über ihren Sturz, o Himmel, frohlockt auch, ihr Heiligen, ihr Apostel und Propheten! Denn Gott hat euch an ihr gerächt."',
        21: 'Da nahm ein starker Engel einen Stein, der groß war wie ein Mühlstein, und schleuderte ihn ins Meer mit diesen Worten: / Mit solcher Wucht soll Babylon, die große Stadt, hinabgeschleudert werden und nimmermehr zu finden sein!',
        22: 'Kein Harfenspiel und kein Gesang, kein Flötenton und kein Trompetenschall soll fernerhin in dir erklingen, kein Künstler je in deinen Mauern wohnen! Kein Mühlrad soll in Zukunft in dir rauschen,',
        23: 'kein Licht der Lampe soll mehr in dir scheinen, kein Brautpaar soll sich mehr in deinen Mauern freuen! / Deine Kaufherren waren ja der Erde Fürsten, und alle Völker sind betört durch deine Zauberkünste.',
        24: 'In deinen Mauern ist vergossen der Propheten und der Heiligen Blut, ja aller derer Blut, die hingeschlachtet sind auf Erden."',
    },
    19: {
        1: 'Dann hörte ich, wie eine große Schar im Himmel mit lauter Stimme sang: / Halleluja! Das Heil, die Herrlichkeit und Macht gehören unserem Gott.',
        2: 'Wahrhaftig und gerecht sind seine Urteilssprüche: / Er hat die große Buhlerin gerichtet, die durch ihr Buhlen hat verderbt die Erde. / So hat er seiner Knechte Blut gerächt, das sie mit ihrer Hand vergossen."',
        3: 'Sie sangen weiter: / "Halleluja! Der Rauch von ihrem Brand steigt auf in Ewigkeit."',
        4: 'Da fielen die vierundzwanzig Ältesten und die vier Lebewesen vor Gott, der auf dem Thron sitzt, anbetend nieder und sprachen: "Amen. Halleluja!"',
        5: 'Und von dem Thron ging eine Stimme aus, die sprach: / "Preist unseren Gott, ihr seine Knechte alle; preist ihn, die ihr ihn fürchtet, beide klein und groß!"',
        6: 'Dann hörte ich, wie eine große Schar gleich Meeresrauschen und starkem Donnerrollen also sang: / Halleluja! Der Herr hat nun die Herrschaft angetreten, er, unser Gott, der Allgewaltige.',
        7: 'Laßt freudig uns frohlocken und ihm die Ehre geben! Denn des Lammes Hochzeit ist gekommen, und sein Weib hat sich bereitet.',
        8: 'Sie hat sich kleiden dürfen in glänzend reine Leinwand. Die Leinwand ist der Heiligen Gerechtigkeit."',
        9: 'Und er sprach zu mir: "Schreibe: \'Selig alle, die zu des Lammes Hochzeitsmahl geladen sind\'!" Dann fuhr er fort: "Dies sind wahrhaftig Gottes Worte."',
        10: 'Da fiel ich ihm zu Füßen, um ihn anzubeten. Er aber sprach zu mir: "Tu das nicht! Ich bin (ja nur) dein Mitknecht und (der Mitknecht) deiner Brüder, die das Jesuszeugnis treu bewahren. Bete Gott an!" / Das Jesuszeugnis ist der Geist der Weissagung.',
        11: 'Darauf sah ich den Himmel offen, und es erschien ein weißes Roß. Sein Reiter heißt "Treu und Wahrhaftig"; er richtet und kämpft mit Gerechtigkeit.',
        12: 'Seine Augen leuchteten wie Feuerflammen. Auf seinem Haupt trug er viele Königskronen. Ein Name war ihm angeschrieben, den niemand kennt als er allein.',
        13: 'Das Oberkleid, das ihn umhüllte, war in Blut getaucht. Sein Name ist "Gottes Wort".',
        14: 'Die Himmelsheere, angetan mit weißer reiner Leinwand, folgten ihm auf weißen Rossen.',
        15: 'Aus seinem Mund geht hervor ein scharfes Schwert, womit er niederschlagen soll die Völker. Er wird sie mit eisernem Stab weiden, und er tritt die Kelter des Glutweins des Zornes Gottes, des Allgewaltigen.',
        16: 'Auf seinem Oberkleid, und zwar an seiner Hüfte, trägt er geschrieben diesen Namen: König der Könige und Herr der Herren.',
        17: 'Und ich sah einen Engel stehen im vollen Sonnenglanz, der rief mit lauter Stimme allen Vögeln zu, die hoch oben am Himmel flogen: "Eilt herbei und sammelt euch zu dem großen Mahl, das euch Gott bereitet!',
        18: 'Ihr sollt verzehren das Fleisch der Könige, das Fleisch der Feldobersten und das Fleisch der starken Helden, das Fleisch der Rosse und der Reiter, das Fleisch von Leuten aller Art: von Freien und Leibeigenen, von Kleinen und von Großen."',
        19: 'Dann sah ich das Tier und die Könige der Erde. Sie hatten ihre Heere versammelt, um mit dem Reiter auf dem Roß und mit seinem Heer Krieg zu führen.',
        20: 'Doch das Tier ward gefangen und mit ihm der falsche Prophet, der vor seinen Augen die Wunder getan, wodurch er die verführte, die des Tieres Zeichen trugen und sein Bild anbeteten. Lebendig wurden beide in den Feuersee geworfen, der mit Schwefel brennt.',
        21: 'Die anderen aber fielen durch das Schwert, das aus dem Mund dessen ging, der auf dem Roß saß; und alle Vögel wurden satt von ihrem Fleisch.',
    },
    20: {
        1: 'Dann sah ich einen Engel aus dem Himmel niedersteigen, der hielt den Schlüssel zum Abgrund und eine große Kette in seiner Hand.',
        2: 'Er griff den Drachen, die alte Schlange, den Teufel, den Satan, band ihn für tausend Jahre',
        3: 'und warf ihn in den Abgrund. Dann verschloß er über ihm den Eingang und legte ein Siegel darauf, damit er bis zu dem Ablauf der tausend Jahre die Völker nicht mehr verführe. Nach dieser Zeit muß er (noch einmal) für eine kleine Weile losgelassen werden.',
        4: 'Und ich sah Throne. Darauf setzten sie sich nieder, und sie empfingen Vollmacht, das Gericht zu halten. / Auch sah ich die Seelen derer, die enthauptet waren, weil sie von Jesus Zeugnis abgelegt und Gottes Wort verkündigt, sowie die Seelen jener, die das Tier und sein Bild nicht angebetet noch das Zeichen auf ihre Stirn und ihre Hand genommen hatten. Sie (alle) wurden wieder lebendig und herrschten tausend Jahre lang als Könige mit Christus.',
        5: '- Die anderen Toten aber wurden erst nach Ablauf der tausend Jahre wieder lebendig. Dies ist die erste Auferstehung.',
        6: 'Selig und heilig ist, wer teilhat an der ersten Auferstehung! Über sie hat der zweite Tod keine Gewalt, sondern sie werden Priester Gottes und Christi sein und mit ihm in den tausend Jahren als Könige herrschen.',
        7: 'Wenn aber die tausend Jahre zu Ende sind, so wird der Satan aus seinem Gefängnis losgelassen werden.',
        8: 'Dann geht er aus, um die Völker Gog und Magog, die an den vier Enden der Erde wohnen, zu verführen und sie so zahlreich wie Sand am Meer zum Kampf zu versammeln.',
        9: 'Sie zogen hinauf über die Erde, so weit sie ist, und umringten das Heerlager der Heiligen und die geliebte Stadt. Da fiel Feuer vom Himmel und verzehrte sie.',
        10: 'Und ihr Verführer, der Teufel, ward in den Feuer- und Schwefelsee geworfen, wo auch das Tier und der falsche Prophet sind, und sie sollen Tag und Nacht gequält werden bis in alle Ewigkeit.',
        11: 'Dann sah ich einen großen, glänzenden Thron und den, der darauf saß. Vor dessen Antlitz flohen die Erde und der Himmel, und keine Stätte fand sich mehr für sie.',
        12: 'Ich sah die Toten, groß und klein, vor dem Thron stehen, und Bücher wurden aufgeschlagen. Auch ein anderes Buch, das Buch des Lebens, ward geöffnet. Und die Toten wurden gerichtet nach ihren Werken, so wie es in diesen Büchern aufgezeichnet war.',
        13: 'Das Meer gab die Toten zurück, die es barg; auch der Tod und die Unterwelt gaben ihre Toten heraus, und jeder ward gerichtet nach seinen Werken.',
        14: 'Dann wurden Tod und Unterwelt in den Feuersee geworfen. Dieser Feuersee ist der zweite Tod.',
        15: 'Wer nicht in dem Lebensbuch verzeichnet stand, der wurde in den Feuersee geworfen.',
    },
    21: {
        1: 'Dann sah ich einen neuen Himmel und eine neue Erde. Denn der erste Himmel und die erste Erde waren nicht mehr da, und das Meer war verschwunden.',
        2: 'Darauf sah ich die heilige Stadt, ein neues Jerusalem, von Gott aus dem Himmel niedersteigen, so herrlich wie eine für ihren Bräutigam geschmückte Braut.',
        3: 'Auch hörte ich eine laute Stimme von dem Thron her rufen: / Gottes Hütte ist jetzt bei den Menschen! Er wird bei ihnen wohnen, und sie sind sein Volk. Er selbst wird unter ihnen weilen als ihr Gott',
        4: 'und wird von ihren Augen alle Tränen wischen. Es wird kein Tod mehr sein, kein Trauern, keine Klage und kein Leid. Denn was einst war, ist nun vergangen."',
        5: 'Der auf dem Thron saß, sprach: "Ich mache jetzt alles neu." Dann fuhr er fort: "Schreib diese Worte nieder, denn sie sind zuverlässig und wahrhaftig!"',
        6: 'Weiter sprach er zu mir: "Es ist geschehen! Ich bin das A und das O, der Anfang und das Ende. Umsonst will ich dem Durstigen zu trinken geben von dem Quell des Lebenswassers.',
        7: 'Wer siegt, soll dies ererben: ich will sein Gott sein, und er soll mein Sohn sein.',
        8: 'Die Verzagten aber, die Ungläubigen, die Unreinen, die Mörder, die Unzüchtigen, die Zauberer, die Götzendiener und alle Lügner — die sollen ihre Stätte finden in dem See, der mit Feuer und Schwefel brennt. Das ist der zweite Tod."',
        9: 'Da kam einer von den sieben Engeln, die vorher die sieben Schalen mit den letzten sieben Plagen hatten, und sprach zu mir: "Komm, ich will dir die Braut, das Weib des Lammes zeigen!"',
        10: 'Im Geist führte er mich nun auf einen großen, hohen Berg und zeigte mir die heilige Stadt Jerusalem, wie sie von Gott aus dem Himmel herabstieg,',
        11: 'erfüllt mit Gottes Herrlichkeit. Ihr Glanz strahlte wie köstlicher Edelstein, wie durchsichtiger Jaspis.',
        12: 'Sie hatte eine große, hohe Mauer mit zwölf Toren. An den Toren standen zwölf Engel, und (in den Toren) waren Namen eingegraben: die Namen der zwölf Stämme der Kinder Israel.',
        13: 'Drei Tore lagen nach Osten, drei nach Norden, drei nach Süden und drei nach Westen.',
        14: 'Die Mauer der Stadt hatte zwölf Grundsteine; darauf standen zwölf Namen: die Namen der zwölf Apostel des Lammes.',
        15: 'Der Engel, der mit mir redete, hatte ein goldenes Meßrohr, um die Stadt, ihre Tore und ihre Mauer damit zu messen.',
        16: 'Die Stadt bildete ein Viereck, und ihre Länge war so groß wie ihre Breite. Er maß die Stadt mit seinem Rohr: das Ergebnis war dreihundert Meilen. Die Länge, die Breite und die Höhe der Stadt waren gleich.',
        17: 'Dann maß er ihre Mauer: das Ergebnis war hundertvierundvierzig Ellen, und zwar gemessen nach Menschenmaß, das auch das Maß des Engels war.',
        18: 'Die Mauer war ganz aus Jaspis und die Stadt selbst aus lauterem Gold, das durchsichtig war wie reines Glas.',
        19: 'Die Grundsteine der Stadtmauer waren mit allerlei köstlichen Edelsteinen geziert. Der erste Grundstein war aus Jaspis, der zweite aus Saphir, der dritte aus Chalzedon, der vierte aus Smaragd,',
        20: 'der fünfte aus Sardonyx, der sechste aus Sarder, der siebente aus Chrysolith, der achte aus Beryll, der neunte aus Topas, der zehnte aus Chrysopras, der elfte aus Hyazinth, der zwölfte aus Amethyst.',
        21: 'Die zwölf Tore waren zwölf Perlen; jedes Tor bestand aus einer einzigen Perle. Der Marktplatz der Stadt war aus lauterem Gold (und glänzte) wie Spiegelglas.',
        22: 'Ich sah keinen Tempel in der Stadt; denn Gott der Herr, der Allgewaltige, ist ihr Tempel und das Lamm.',
        23: 'Die Stadt braucht nicht Sonnenlicht, nicht Mondlicht; denn die Herrlichkeit Gottes strahlt in ihr, und ihre Leuchte ist das Lamm.',
        24: 'In ihrem Licht werden die Völker wandeln, und die Könige der Erde werden ihr die herrlichsten Geschenke bringen.',
        25: "Tagsüber — denn Nacht wird's dort nicht geben — sollen ihre Tore nie geschlossen werden,",
        26: 'so daß man fort und fort die kostbaren Schätze der Völker in ihre Mauern bringen kann.',
        27: 'Doch nie darf in sie eingehen irgend etwas Unreines, besonders keiner, der Greuel übt und Lügen redet. Nur solche finden Einlaß, die in des Lammes Lebensbuch verzeichnet sind.',
    },
    22: {
        1: 'Dann zeigte mir der Engel einen Strom von Lebenswasser, klar wie Kristall, der von dem Thron Gottes und des Lammes ausging.',
        2: 'Zwischen dem Marktplatz der Stadt und dem Strom standen auf beiden Seiten Lebensbäume, die (jährlich) zwölf Arten Früchte brachten, jeden Monat ihre besondere Frucht; und die Blätter der Bäume dienten als Arznei für die Völker.',
        3: 'Dort wird es nichts mehr geben, was unter einem Fluch steht. Denn Gottes und des Lammes Thron ist in der Stadt. Seine Knechte werden ihm dort anbetend dienen,',
        4: 'sie werden sein Antlitz schauen, und sein Name wird geschrieben stehen auf ihrer Stirn.',
        5: 'Nacht wird dort nicht mehr sein. Man bedarf auch keiner Lampen, keines Sonnenlichtes; denn Gott der Herr wird sie mit seinem Licht bestrahlen. So herrschen sie als Könige in alle Ewigkeit.',
        6: 'Dann sprach er zu mir: "Diese Worte sind zuverlässig und wahrhaftig! Der Herr, der Gott der Geister der Propheten, hat seinen Engel gesandt, um seinen Knechten kundzutun, was bald geschehen soll.',
        7: 'Sieh, ich komme bald! Selig, wer die Worte der Weissagung in diesem Buch zu Herzen nimmt!"',
        8: 'Ich, Johannes, habe dies gehört und gesehen. Und als ich es gehört und gesehen hatte, da fiel ich dem Engel, der es mir gezeigt, zu Füßen, um ihn anzubeten.',
        9: 'Er aber sprach zu mir: "Tu das nicht! Ich bin (ja nur) dein Mitknecht und (der Mitknecht) deiner Brüder, der Propheten, und aller, die die Worte dieses Buches zu Herzen nehmen. Bete Gott an!"',
        10: 'Dann fuhr er fort: "Versiegele nicht die Worte der Weissagung in diesem Buch, denn die Zeit ist nahe!',
        11: 'Der Übeltäter mag noch weiter übeltun, der Schuldbefleckte mag sich weiterhin beflecken. Der Gerechte aber übe auch fernerhin Gerechtigkeit, und der Heilige halte sich auch weiter heilig!"',
        12: 'Sieh, ich komme bald und bringe meinen Lohn mit mir, um jedem zu vergelten nach seinen Werken.',
        13: 'Ich bin das A und das O, der Erste und der Letzte, der Anfang und das Ende.',
        14: 'Selig sind, die ihre Kleider waschen: die sollen von der Frucht des Lebensbaumes essen und durch die Tore eingehen in die Stadt!',
        15: 'Draußen aber bleiben die Hunde, die Zauberer, die Unzüchtigen, die Mörder, die Götzendiener und alle, die die Lüge lieben und üben.',
        16: 'Ich, Jesus, habe meinen Engel gesandt, um euch für die Gemeinden diese Offenbarung kundzutun. Ich bin der Wurzelsproß aus Davids Stamm, der helle Morgenstern.',
        17: 'Der Geist und die Braut sprechen: "Komm!" Und wer es hört, der spreche: "Komm!" Wen da dürstet, der komme; und wer es begehrt, der nehme von dem Lebenswasser umsonst!',
        18: 'Allen, die die Worte der Weissagung in diesem Buch hören, erkläre ich feierlich: Wer diesen Worten etwas zufügt, dem wird Gott die Plagen zufügen, wovon in diesem Buch die Rede ist.',
        19: 'Und wer von den Worten des Buches dieser Weissagung etwas wegnimmt, dem wird Gott seinen Anteil nehmen an dem Baum des Lebens und an der heiligen Stadt, die in diesem Buch beschrieben sind.',
        20: 'Der diese Offenbarung kundtut, spricht: "Ja, ich komme bald!" / Amen! Komm, Herr Jesus!',
        21: 'Die Gnade des Herrn Jesus Christus sei mit allen Heiligen! Amen.',
    },
}
