NAME = 'Est: Estonian Bible'
BOOK = 'II Peter'

CHAPTERS = {
    1: {
        1: 'Siimon Peetrus, Jeesuse Kristuse sulane ja apostel, neile, kes on saanud niisama kalli usu kui meiegi meie Jumala ja Õnnistegija Jeesuse Kristuse õiguses.',
        2: 'Armu ja rahu lisatagu teile rohkesti Jumala ja Jeesuse, meie Issanda tunnetuses!',
        3: 'Nõnda nagu Tema jumalik vägi meile on annetanud kõik, mida vajatakse eluks ja jumalakartuseks, Tema tunnetuse kaudu, Kes meid on kutsunud Oma au ja vooruslikkusega,',
        4: 'millega on meile kingitud kallid ja suurimad tõotused, et te nende läbi saaksite osa jumalikust loomust, kui te olete põgenenud ära hukkumisest, mis on maailmas himude tõttu;',
        5: 'siis kandke sellesama pärast kõikepidi hoolt ja osutage oma usus vooruslikkust ja vooruslikkuses tunnetust,',
        6: 'tunnetuses taltumust, taltumuses kannatlikkust, kannatlikkuses jumalakartust,',
        7: 'jumalakartuses vennaarmastust ja vennaarmastuses armastust kõikide vastu.',
        8: 'Sest kui teil seda kõike on ja veel lisatakse, siis ei lase see teid olla viitsimatud ja viljatud meie Issanda Jeesuse Kristuse tunnetamises.',
        9: 'Aga kellel see kõik puudub, on pime, lühinägelik, ja on unustanud puhastuse endistest pattudest.',
        10: 'Sellepärast, vennad, püüdke seda enam teha kindlaks oma kutsumine ja valik; sest kui te seda teete, siis te ei komista iialgi.',
        11: 'Sest nõnda avaneb teile rohkel mõõdul sissepääs meie Issanda ja Õnnistegija Jeesuse Kristuse igavesse Kuningriiki.',
        12: 'Sellepärast ma tahan alati teile seda meelde tuletada, ehk te küll seda teate ja olete kindlasti rajatud tõele, mis teil on käes.',
        13: 'Ma pean õigeks, niikaua kui ma selles ihulikus telgis olen, teid meeldetuletuse kaudu virgutada,',
        14: 'sest et ma tean, et ma varsti maha panen oma telgi, nagu ka meie Issand Jeesus Kristus mulle on avaldanud.',
        15: 'Ent ma tahan ka hoolt kanda, et teil pärast minu lahkumist alati oleks võimalik seda meelde tuletada.',
        16: 'Sest me ei ole Issanda Jeesuse Kristuse väge ja tulemist teile teatavaks tehes mitte järginud kavalasti sepitsetud tühje jutte, vaid me oleme ise oma silmaga näinud Tema suurt aulisust.',
        17: 'Sest Tema sai Jumalalt Isalt au ja austust kõige kõrgemalt ault, kui Temale kostis niisugune hääl: "See on Minu armas Poeg, Kellest Mul on hea meel!"',
        18: 'Ja selle hääle me kuulsime taevast tulevat, olles ühes Temaga pühal mäel.',
        19: 'Ja meil on veel kindlam prohvetlik sõna, ja te teete hästi, et te seda tähele panete kui küünalt, mis paistab pimedas paigas, kuni päev jõuab kätte ning koidutäht tõuseb teie südameis.',
        20: 'Ja see olgu teile kõigepealt teada, et ükski prohvetikuulutus Kirjas ei ole omavolilise seletuse jaoks.',
        21: 'Sest inimese tahtel ei ole iialgi ühtki prohveti kuulutust esile toodud, vaid Pühast Vaimust kantuina on inimesed rääkinud, saades seda Jumala käest.',
    },
    2: {
        1: 'Aga valeprohveteidki tõusis rahva seas, nõnda nagu teiegi seas saab olema lahkõpetajaid, kes salamahti toovad sisse hukutavaid valeõpetusi, salgavad ära Peremehegi, Kes nad on ostnud, ja tõmbavad eneste peale äkilise hukatuse.',
        2: 'Ja paljud järgivad nende lodevat elu, kelle pärast pilgatakse tõe teed;',
        3: 'ja ahnuses kasutavad nad teid petlike sõnadega. Nende kohus on juba ammu valvas ja nende hukatus ei tuku.',
        4: 'Sest kui Jumal ei säästnud ingleidki, kes pattu tegid, vaid tõukas nad põrgupimeduse soppidesse säilitatavaiks kohtu jaoks,',
        5: 'ja kui Ta ei säästnud muistset maailma, vaid varjas ainult õigusekuulutajat Noad, neid kaheksakesi, kui ta laskis tulla veeuputuse jumalatute maailma peale;',
        6: 'ja mõistis ka hukka Soodoma ja Gomorra linnad, põletades need tuhaks ja pannes hirmu täheks neile, kes tulevikus on jumalatud,',
        7: 'ja päästis Loti, kes oli õige ja keda üleannetud inimesed piinasid oma kiimalise käitumisega -',
        8: 'sest elades nende keskel see õige vaevas päevast päeva oma vaga hinge, nähes ja kuuldes ülekohtusi tegusid -',
        9: 'nii Issand teab päästa jumalakartlikke kiusatusest, aga ülekohtusi säilitada kohtupäevaks, et neid nuhelda,',
        10: 'iseäranis aga neid, kes liha järgi elavad roppudes himudes ja põlgavad Issanda valitsust. Need on jultunud, iseennast täis, ei karda pilgata aukandjaid vaime,',
        11: 'kuna Inglidki, kuigi nad küll võimuselt ja väelt on suuremad, ühtki pilkavat otsust ei lausu nende kohta Issanda ees.',
        12: 'Ent need on nagu mõistmatud loomad, kes on oma loomu poolest sündinud püütavaiks ja hukutavaiks; nad pilkavad seda, mida nad ei tea, ja hukkuvad ka oma hukus,',
        13: 'saades kätte ülekohtu palga; nad peavad lõbuks igapäevast laiutamist; nad on ebapuhtuse ja häbi laigud, kes oma pettuste varal lõbutsevad, kui nad pidutsevad ühes teiega;',
        14: 'nende silmad õhkuvad abielurikkumisest ja nende iha ei lakka; nemad ahvatlevad kinnitamatuid hingi, neil on ahnusega vilunud süda, nad on needuse lapsed!',
        15: 'Nad on hüljanud otsese tee, nad on ära eksinud, käies Bileami, Beori poja teed, kellele ülekohtu palk oli armas,',
        16: 'aga kes oma üleastumise pärast sai karistada: keeletu koormakandja loom rääkis inimese häälega ja takistas prohveti jõledust.',
        17: 'Need on ilma veeta lätted, marutuulest aetavad udupilved, kellele on varutud pilkane pimedus.',
        18: 'Sest rääkides tühje ülerinna sõnu, ahvatlevad nad lodevate lihahimudega neid, kes vaevalt olid pääsenud pakku eksiteel käijate seast;',
        19: 'nad tõotavad neile vabadust, olles ise kaduvuse orjad, sest kelle võidetud keegi on, selle ori ta on.',
        20: 'Sest kui nad Issanda ja Õnnistegija Jeesuse Kristuse tunnetuse läbi pääsesid pakku maailma ebapuhtusest, kuid jälle segunevad sellega ja jäävad alla, siis on nende viimne lugu saanud pahemaks kui esimene.',
        21: 'Sest neil oleks parem, et õiguse tee oleks jäänud neile tundmatuks, kui seda tundes ära pöörduda käsust, mis neile on antud.',
        22: 'Neile on tulnud kätte, mis tõeline vanasõna ütleb: "Koer pöördub tagasi oma okse juurde" ja "pestud emis läheb porisse püherdama!"',
    },
    3: {
        1: 'See on, armsad, juba teine kiri, mille ma teile kirjutan, ja mõlematega ma hoian oma meeldetuletamisega ärkvel teie puhast meelt,',
        2: 'et te meenutaksite neid sõnu, mis pühad prohvetid enne on rääkinud, ja Issanda ning Õnnistegija käsku, mille on andnud teie Apostlid.',
        3: 'Seda teadke kõigepealt, et viimseil päevil tuleb pilkesõnadega pilkajaid, kes elavad iseeneste himude järgi',
        4: 'ning ütlevad: "Kus on Tema tulemise tõotus? Sest sellest ajast, kui isad läksid hingama, jääb kõik nõnda, nagu oli loomise algusest!"',
        5: 'Sest neil, kes seda tahavad, on teadmata, et taevad olid vanasti olemas ja maa koosnes veest ja vee läbi Jumala sõna väe tõttu',
        6: 'ja et nende läbi tookordne maailm hukkus veeuputuses.',
        7: 'Ent praegused taevad ja maa säilitatakse sama Sõna läbi ning hoitakse alal tule jaoks jumalatute inimeste kohtu ja hukatuse päevaks.',
        8: 'Aga see üks asi ärgu olgu teile, armsad, teadmata, et üks päev on Issanda juures nagu tuhat aastat ja tuhat aastat nagu üks päev!',
        9: 'Issand ei viivita tõotust täitmast, nõnda nagu mõned peavad seda viivituseks, vaid Tema on pika meelega teie vastu; sest Ta ei taha, et keegi hukkuks, vaid et kõik tuleksid meeleparandusele!',
        10: 'Aga Issanda päev tuleb otsekui varas öösel, mil taevad raginal hukkuvad ja maailma algained tules laostuvad ja ilmamaad ja kõiki seal tehtud töid ei leidu enam.',
        11: 'Kui see nüüd kõik nõnda laostub, missugused siis teie peate olema pühas elus ja jumalakartuses,',
        12: 'oodates ja igatsedes Jumala päeva tulekut, mille pärast taevad süüdatult laostuvad ja maailma algained kuumuses ära sulavad?',
        13: 'Aga meie ootame tema tõotuse järgi uusi taevaid ja uut maad, kus õigus elab!',
        14: 'Sellepärast, armsad, seda oodates püüdke, et Ta teid leiaks veatuina ja laitmatuina rahus;',
        15: 'ja meie Issanda pikka meelt arvake õndsuseks, nõnda nagu ka meie armas vend Paulus teile on kirjutanud temale antud tarkust mööda,',
        16: 'nagu ka kõigis kirjades, milles ta räägib neist asjust, kus on raske aru saada mõnest asjast, mida õppimatud ja kinnitamatud inimesed nagu muidki kirju väänavad iseeneste hukatuseks.',
        17: 'Et teie nüüd, armsad, seda ette ära teate, siis hoiduge sellest, et üleannetute eksitused teid ei kisuks ühtlasi kaasa eksitusse ning te ei langeks ära oma kindlalt aluselt.',
        18: 'Aga kasvage meie Issanda ja Õnnistegija Jeesuse Kristuse armus ja tunnetuses. Temale olgu austus nii nüüd kui igaviku päevil!',
    },
}
