NAME = 'Est: Estonian Bible'
BOOK = 'James'

CHAPTERS = {
    1: {
        1: 'Jakoobus, Jumala ja Issanda Jeesuse Kristuse sulane, saadab tervisi hajuvil asuvaile kaheteistkümnele suguharule.',
        2: 'Pidage lausa rõõmuks, mu vennad, kui te satute mitmesugustesse kiusatustesse,',
        3: 'ja teadke, et teie usu katsumine saadab kannatlikkust!',
        4: 'Ent kannatlikkus omagu täiuslikku tegu, et te oleksite täiuslikud ja laitmatud ega oleks teil mingit puudust.',
        5: 'Aga kui kellelgi teist on puudu tarkusest, see palugu Jumalalt, Kes kõigile annab suisa ega tee etteheiteid, ja siis antakse temale.',
        6: 'Ent ta palugu usus, ilma kahtlemata; sest kes kahtleb, sarnaneks merelainele, mida tuul tõstab ning sinna ja tänna peksab.',
        7: 'Niisugune inimene ärgu ometi arvaku, et ta midagi saab Issandalt;',
        8: 'ta on kaksipidise meelega mees, ebakindel kõigil oma teedel.',
        9: 'Ent madal vend kiidelgu oma suurusest,',
        10: 'aga rikas oma madalusest, sest ta kaob nagu rohu õieke.',
        11: 'Sest päike tõusis palavaga ja kuivatas rohu ära, ja selle õieke varises maha ning tema näo ilu hävis. Nõnda närtsib ka rikas oma retkedel!',
        12: 'Õnnis see mees, kes ära kannatab kiusatuse; sest kui ta on läbi katsutud, saab ta elukrooni, mille Issand on tõotanud neile, kes Teda armastavad.',
        13: 'Ärgu ükski kiusatuses olles öelgu: "Mind kiusab Jumal!" Sest Jumalat ei kiusata kurjaga ja Tema Ise ei kiusa kedagi.',
        14: 'Aga igaüht kiusatakse, kui tema enese himu teda veab ning ahvatleb;',
        15: 'pärast, kui himu on rasestunud, toob ta patu ilmale, aga kui patt on täiesti tehtud, sünnitab ta surma.',
        16: 'Ärge eksige, mu armsad vennad!',
        17: 'Kõik hea and ja kõik täiuslik annetus on ülalt ja tuleb valguse Isalt, Kelle juures ei ole muutust ega varjutuste varju.',
        18: 'Tema on meid Oma tahtel sünnitanud tõe sõnaga, et oleksime Tema loodute esmasündinute hulgast.',
        19: 'Teie teate seda, mu armsad vennad. Olgu vaid iga inimene nobe kuulma, pikaline rääkima, pikaline vihale.',
        20: 'Sest mehe viha ei tekita õigust Jumala ees.',
        21: 'Sellepärast heitke ära kõik rüvedus ja viimnegi paha ning võtke tasase meelega vastu sõna, mis teisse istutati ja võib teie hinged päästa!',
        22: 'Aga olge sõna tegijad ja mitte ükspäinis kuuljad, iseendid pettes.',
        23: 'Sest kui keegi on sõna kuulja ja mitte tegija, siis on ta mehe sarnane, kes vaatab oma ihulikku palet peeglis.',
        24: 'Ta vaatas ennast, läks minema ja unustas varsti, missugune ta oli.',
        25: 'Aga kes vabaduse täiusliku käsu sisse kummardades on vaadanud ja jääb selle juurde, ei ole unustav kuulja, vaid on teo tegija; see on õnnis oma tegemises.',
        26: 'Kui keegi arvab Jumalat teenivat ja ei talitse oma keelt, vaid petab oma südant, selle jumalateenistus on tühine.',
        27: 'Puhas ja laitmatu jumalateenistus Jumala ja Isa ees on see: vaestelaste ja lesknaiste eest hoolitseda nende viletsuses ja hoida ennast maailmast reostamatuna.',
    },
    2: {
        1: 'Mu vennad, pidage usku meie au Issandasse Jeesusesse Kristusesse, sõltumata isikute lugupidamisest.',
        2: 'Sest kui teie koosolekule tuleb mees, kuldsõrmus sõrmes ja uhkes rüüs, ent tuleb ka vaene räpases rüüs,',
        3: 'ja te vaatate sellele, kes kannab uhket rüüd ning ütlete temale: "Sina istu siia mugavasse kohta!", ja ütlete vaesele: "Sina seisa seal!" või: "Istu siia mu jalajäri ette!",',
        4: 'kas te siis ei ole valesti otsustanud ja saanud halbade juhtmõtetega kohtumõistjaiks?',
        5: 'Kuulge, mu armsad vennad, kas ei ole Jumal valinud selle maailma vaesed saama rikkaiks usus ja Kuningriigi pärijaiks, mille Ta on tõotanud neile, kes Teda armastavad?',
        6: 'Teie aga olete vaest halvaks pannud. Eks tarvita just rikkad vägivalda teie vastu ja vea teid kohtukodadesse?',
        7: 'Eks nemad pilka seda kallist nime, mis on nimetatud teie üle?',
        8: 'Kui te tõesti täidate kuninglikku käsku Kirja sõna järgi: "Armasta oma ligimest nagu iseennast!", siis te teete hästi;',
        9: 'aga kui te peate ühest rohkem lugu kui teisest, siis te teete pattu ja käsk tunnistab teid üleastujaiks.',
        10: 'Sest kes kogu käsuõpetust peab ja eksib ühe vastu, on saanud süüdlaseks kõigi vastu.',
        11: 'Sest See, Kes on öelnud: "Sa ei tohi abielu rikkuda!", on ka öelnud: "Sa ei tohi tappa!" Kui sa nüüd ei riku abielu, aga tapad, siis oled saanud käsust üleastujaks.',
        12: 'Nõnda rääkige ja nõnda toimige kui need, kellele tuleb kohut mõista vabaduse käsu järgi.',
        13: 'Sest kohus on halastuseta sellele, kes ei ole osutanud halastust; kuid halastus võib võidurõõmutseda kohtu üle!',
        14: 'Mis kasu on sellest, mu vennad, kui keegi ütleb enesel usku olevat, aga tegusid temal ei ole? Ega usk või teda õndsaks teha?',
        15: 'Kui vend või õde on alasti ja neil puudub igapäevane toidus,',
        16: 'ja keegi teie seast ütleb neile: "Minge rahuga, soojendage endid ja sööge kõhud täis!", aga te ei anna neile ihu tarbeid, mis on sellest kasu?',
        17: 'Nõnda ka usk, kui tal ei ole tegusid, on iseenesest surnud.',
        18: 'Aga mõni ehk ütleb: "Sinul on usk ja minul on teod!" Näita mulle oma usku lahus tegudest, küll mina näitan sulle usku oma tegudega!',
        19: 'Sina usud, et Jumal on ainus. Sa teed hästi! Ka kurjad vaimud usuvad seda ja värisevad.',
        20: 'Ent kas tahad teada, oh tühine inimene, et usk lahus tegudest on tõhutu?',
        21: 'Eks Aabraham, meie isa, mõistetud õigeks tegudest, kui ta oma poja Iisaki viis ohvrialtarile?',
        22: 'Sa näed, et usk töötas ühes tema tegudega ja et tegudest sai usk täiuslikuks',
        23: 'ja täitus Kiri, mis ütleb: "Aabraham uskus Jumalat ja see arvati temale õiguseks ning ta nimetati Jumala sõbraks."',
        24: 'Te näete, et inimene mõistetakse õigeks tegudest ja mitte ükspäinis usust.',
        25: 'Ja eks nõndasamuti ka hoor Raahab mõistetud õigeks tegudest, kui ta vastu võttis käskjalad ja nad ära saatis teist teed?',
        26: 'Sest samuti nagu ihu ilma vaimuta on surnud, nõnda ka usk ilma tegudeta on surnud.',
    },
    3: {
        1: 'Mu vennad, ärgu püüdku paljud saada õpetajaiks, sest te teate, et me saame seda suurema nuhtluse.',
        2: 'Sest me kõik eksime palju. Kui keegi kõnes ei eksi, siis ta on täiuslik mees ja võib ka talitseda kogu ihu.',
        3: 'Kui me paneme suulised hobustele suhu, et nad oleksid meile sõnakuulelikud, siis me juhime kogu nende keha.',
        4: 'Vaata laevugi, ehk need küll on suured ja kangeist tuultest aetavad, juhitakse üsna väikese tüüriga sinna, kuhu päramehe tahtele meeldib.',
        5: 'Nõnda on ka keel pisuke liige ja kiitleb suurist asjust. Vaata, kui pisuke tuli süütab suure metsa!',
        6: 'Samuti on keel tuli, on maailm täis ülekohut; keel meie liikmete seas saab selliseks, mis reostab kogu ihu ja süütab põlema eluratta, nagu ta ise on süüdatud põrgust.',
        7: 'Sest kõikide, niihästi metselajate kui lindude, niihästi roomajate kui mereelajate loomu võib inimese loomujõud talitseda ja on talitsenud,',
        8: 'kuid keelt ei suuda ükski inimene talitseda, seda rahutut pahategijat, täis surmavat mürki.',
        9: 'Sellega me täname Issandat ja Isa, ja sellega me sajatame inimesi, kes on loodud Jumala sarnaseiks.',
        10: 'Samast suust lähtuvad tänu ja sajatus! Nii ei tohi olla, mu vennad!',
        11: 'Kas allikas samast soonest keedab välja magusat ja mõru vett?',
        12: 'Ega viigipuu, mu vennad, või kanda õlimarju või viinapuu viigimarju? Ei soolaallikas või anda magusat vett!',
        13: 'Kes teie seas on tark ja arusaaja? Näidaku see oma hea eluviisiga oma tegusid targas tasaduses.',
        14: 'Kui teil aga on südames kibedat kadedust ja riiakat meelt, siis ärge kiidelge ja ärge valetage tõe vastu.',
        15: 'See ei ole see tarkus, mis tuleb ülalt, vaid muldne, maine, kurjast vaimust pärit.',
        16: 'Sest kus on kadedust ja riiakust, seal on korratust ja igat halba asja.',
        17: 'Ent tarkus, mis on ülalt on küll kõigepealt puhas, siis rahulik, leplik, sõnakuulelik, täis halastust ja head vilja, kahtluseta, teeskluseta.',
        18: 'Õiguse vilja aga külvatakse rahus nende heaks, kes peavad rahu!',
    },
    4: {
        1: 'Kust tõusevad võitlemised ja kust tülid teie seas? Kas mitte sealt, teie himudest, mis sõdivad teie liikmetes?',
        2: 'Te himustate ja teil siiski ei ole; te tapate ja kadestate ega või midagi saavutada; te tülitsete ja sõdite. Teil ei ole, sest te ei palu.',
        3: 'Te palute ja ei saa, sest te palute pahasti, tahtes seda kulutada oma himudes.',
        4: 'Te abielurikkujad, eks te tea, et maailma sõprus on vaen Jumala vastu? Kes nüüd tahab olla maailma sõber, see saab Jumala vaenlaseks.',
        5: 'Või arvate, et Kiri asjata ütleb: "Kadeduseni ta himustab vaimu, kes meis elab"?',
        6: 'Aga ta annab veel suuremat armu; sellepärast Kiri ütleb: "Jumal paneb suurelistele vastu, aga alandlikele Ta annab armu."',
        7: 'Siis alistuge Jumalale! Seiske vastu kuradile, siis ta põgeneb teie juurest.',
        8: 'Tulge Jumala ligi, siis Tema tuleb teie ligi! Puhastage käed, te patused, ja kasige südamed, te kaksipidi mõtlejad!',
        9: 'Tundke ära oma viletsus ja leinake ja nutke! Teie naer muutugu nutuks ja teie rõõm tusaks!',
        10: 'Alanduge Issanda ette, siis Ta ülendab teid!',
        11: 'Ärge rääkige, vennad, paha üksteisest! Kes vennast räägib paha ja mõistab kohut venna üle, see räägib paha käsuõpetusest ja mõistab kohut käsuõpetuse üle. Aga kui sa mõistad kohut käsuõpetuse üle, siis sa ei ole käsutäitja, vaid kohtumõistja.',
        12: 'Üks on Käsuandja ja Kohtumõistja, Kes võib teha õndsaks ja panna hukka; aga kes oled sina, kes mõistad kohut ligimese üle?',
        13: 'Kuulge nüüd, kes ütlete: "Täna või homme me läheme sinna linna ja viibime seal aasta ja kaupleme ning saavutame kasu!" -',
        14: 'teie, kes ei teagi, missugune on homme teie elu; sest te olete suits, mida pisut aega nähakse ja mis siis haihtub -',
        15: 'selle asemel et öelda: "Kui Issand tahab ja me elame, siis teeme seda või teist!"',
        16: 'Ent nüüd te kiitlete oma hooplemisega. Kõik niisugune kiitlemine on paha.',
        17: 'Kes siis mõistab teha head ja ei tee seda, sellele on see patuks!',
    },
    5: {
        1: 'Kuulge nüüd, te rikkad, nutke ja uluge oma viletsusi, mis on tulemas!',
        2: 'Teie rikkus on mädanenud ja teie riided on koitanud!',
        3: 'Teie kuld ja hõbe on roostetanud ja nende rooste on teile tunnistuseks ja sööb ära kõik teie liha nagu tuli! Te olete kogunud vara viimseil päevil.',
        4: 'Vaata, töötegijate palk, mille te olete kinni pidanud neilt, oma põldudel lõikajailt, kisendab teie vastu, ja lõikajate kaebed on tunginud vägede Issanda kõrvade ette!',
        5: 'Te olete priisanud ja prassinud maa peal; te olete nuumanud oma südameid otsekui veristuspäeval!',
        6: 'Te olete hukka mõistnud Õige ja olete Ta tapnud; Ta ei pane teile vastu.',
        7: 'Siis olge nüüd pikameelsed, vennad, Issanda tulemiseni! Vaata, põllumees ootab maa kallist vilja ja on pikameelne seda oodates, kuni ta saab varajase ja hilise vihma.',
        8: 'Olge nüüd teiegi pikameelsed, kinnitage oma südameid, sest Issanda tulemine on lähedal!',
        9: 'Ärge ägage, vennad, üksteise pärast, et teid hukka ei mõistetaks! Vaata, Kohtumõistja seisab ukse ees!',
        10: 'Võtke, vennad, vaeva kannatamise ja pikameelse ootamise eeskujuks prohvetid, kes Issanda nimel on rääkinud.',
        11: 'Vaata, me kiidame õndsaks neid, kes on olnud püsivad kannatustes; Iiobi püsivusest te olete kuulnud ja näinud Issanda antud otsa, et Issand on väga halastav ja armuline.',
        12: 'Aga kõigepealt, mu vennad, ärge vanduge, ei taeva ega maa juures ega mingit muud vannet! Teie "jah" olgu "jah", ja teie "ei" olgu "ei", et te ei langeks kohtu alla!',
        13: 'Kui kellelgi teie seast on vaeva, siis ta palvetagu; kui kellegi käsi hästi käib, siis ta laulgu kiituslaule.',
        14: 'Kui keegi teie seast on haige, siis ta kutsugu enese juurde Koguduse vanemad ja need palvetagu tema kohal ja võidku teda õliga Issanda nimel.',
        15: 'Ja usupalve päästab tõbise, ja Issand teeb ta terveks; ja kui ta on pattu teinud, siis see antakse temale andeks.',
        16: 'Tunnistage üksteisele oma eksimused ja palvetage üksteise eest, et saaksite terveks; õige inimese vägev palve suudab palju.',
        17: 'Eelija oli samasugune nõder inimene nagu meiegi, ja ta palus kangesti, et ei sajaks vihma; ja kolm aastat ja kuus kuud ei sadanud vihma maa peale.',
        18: 'Ja tema palus jälle ja taevas andis vihma ja maa kandis oma vilja.',
        19: 'Vennad, kui keegi teie seast eksib ära tõest ja keegi pöörab tema tagasi,',
        20: 'siis teadke, et kes patuse pöörab tema eksiteelt, see päästab tema hinge ja katab kinni pattude hulga.',
    },
}
