NAME = 'FreStapfer1889: Le Nouveau Testament traduction de Stapfer - 1889'
BOOK = 'Galatians'

CHAPTERS = {
    1: {
        1: "Paul, apôtre (non par la grâce des hommes ou par une institution humaine, mais par la grâce de Jésus-Christ et de Dieu le Père qui a ressuscité Jésus d'entre les morts)",
        2: 'et tous les frères qui sont avec moi, aux églises de Galatie.',
        3: 'Grâce et paix vous soient accordées par Dieu le Père et par notre Seigneur Jésus-Christ,',
        4: "qui s'est donné lui-même pour nos péchés afin de nous délivrer de ce monde pervers où nous vivons, conformément à la volonté de notre Dieu et Père,",
        5: 'auquel soit la gloire aux siècles des siècles! amen.',
        6: "J'admire que si vite vous vous détourniez de celui qui vous a appelés par la grâce de Christ, pour adopter un autre Évangile!",
        7: "Un autre! il n'y en a point; il n'y a que certains brouillons qui veulent pervertir l'Évangile du Christ!",
        8: "Eh bien, écoutez: Si jamais quelqu'un, fût-ce moi, fût-ce un ange du ciel, venait vous évangéliser autrement que je ne l'ai fait, qu'il soit anathème!",
        9: "Je viens de le dire, et je vous le répète: Si quelqu'un prêche autre chose que ce que vous avez appris, qu'il soit anathème!",
        10: "Est-ce la faveur des hommes que je cherche ou celle de Dieu? Est-ce aux hommes que je veux plaire? Ah! si j'en étais encore à plaire aux hommes, je ne serais pas serviteur de Christ!",
        11: "Je vous déclare, mes frères, que l'Évangile qui vous a été prêché par moi n'est pas d'origine humaine.",
        12: "Ce n'est pas même des hommes que je l'ai reçu ou appris, c'est d'une révélation de Jésus-Christ.",
        13: "Vous avez entendu parler de ma vie passée, quand j'étais dans le Judaïsme. Vous savez que je persécutais à outrance l'Église de Dieu, que je la ravageais.",
        14: "Vous savez que je surpassais dans mon Judaïsme bon nombre de ceux de mon âge et de ma race; j'étais plus que fanatique de mes traditions nationales.",
        15: "Mais quand Celui qui m'a choisi dès le sein de ma mère et qui m'a appelé par sa grâce,",
        16: 'jugea bon de me révéler intérieurement son Fils, pour que je fusse son évangéliste parmi les païens, sur-le-champ, sans prendre conseil de personne',
        17: 'sans aller à Jérusalem, auprès de ceux qui étaient apôtres avant moi, je me retirai en Arabie, puis je revins à Damas.',
        18: "Ensuite, trois années plus tard, j'allai, il est vrai, à Jérusalem, pour faire la connaissance de Képhas; et je passai quinze jours auprès de lui;",
        19: "mais je ne vis aucun des autres apôtres, si ce n'est Jacques, le frère du Seigneur.",
        20: "Ce que je vous écris, j'affirme en présence de Dieu que ce n'est pas un mensonge!",
        21: 'Je me rendis ensuite dans les provinces de Syrie et de Cilicie;',
        22: "mais j'étais personnellement inconnu des Églises de Christ qui sont en Judée;",
        23: 'elles avaient seulement entendu dire ceci: «Notre ancien persécuteur prêche maintenant la foi que naguère il voulait détruire»;',
        24: 'et on rendait gloire à Dieu à mon sujet.',
    },
    2: {
        1: 'Ensuite, quatorze années plus tard, je montai de nouveau à Jérusalem, avec Barnabas; je pris aussi Tite avec moi.',
        2: "J'y montai sur une révélation; je leur communiquai l'Évangile tel que je le prêche aux païens. J'eus des entretiens particuliers avec les plus considérés d'entre eux, de peur que mes courses passées ou présentes ne fussent inutiles.",
        3: "Eh bien, on n'exigea pas même que Tite qui, m'accompagnait, et qui était Grec, se fit circoncire.",
        4: "Cependant, par égard pour les intrus, les faux frères qui s'étaient glissés parmi nous pour espionner la liberté dont nous jouissons grâce à Jésus-Christ et qui voudraient nous remettre en esclavage...",
        5: "Nous ne leur avons pas cédé, nous ne nous sommes pas soumis un seul instant, afin que la vérité de l'Évangile fût maintenue pour vous.",
        6: "Quant à ceux que l'on considérait comme des personnages (ce qu'ils étaient jadis peu m'importe, Dieu ne fait pas acception de personnes)... ceux, dis-je, qui étaient considérés comme des personnages ne m'apprirent rien de plus.",
        7: "Au contraire, voyant que l'évangélisation des non-circoncis m'était confiée, comme l'était à Pierre celle des circoncis",
        8: "(car Celui qui a donné à Pierre la force d'être apôtre des circoncis m'a donné aussi à moi la force d'être apôtre des païens),",
        9: "connaissant, dis-je, la grâce qui m'avait été accordée, Jacques, Képhas et Jean, qui passaient pour les colonnes de l'Église, nous donnèrent la main, à Barnabas et à moi, en signe d'union, afin que nous fussions, pour les païens, ce qu'ils étaient pour les circoncis.",
        10: 'Ils nous prièrent seulement de nous souvenir des pauvres; aussi me suis-je empressé de le faire.',
        11: 'Quand Képhas vint à Antioche, je lui résistai en face, parce qu’il avait évidemment tort.',
        12: "En effet, avant l'arrivée de certains individus, envoyés par Jacques, il mangeait avec les païens; après leur arrivée, il se tint à l'écart, il s'isola, parce qu'il avait peur des partisans de la circoncision. Les autres Juifs firent les hypocrites avec lui,",
        13: 'si bien que Barnabas lui-même fut entraîné dans cette hypocrisie.',
        14: "Alors, quand je vis qu'ils ne marchaient pas dans le droit chemin de la vérité de l'Évangile, je dis à Képhas devant tout le monde: «Si toi qui es Juif, tu agis comme les païens et non comme les Juifs, comment peux-tu obliger les païens à faire comme les Juifs?",
        15: 'Nous autres, nous sommes Juifs de naissance; nous ne sommes pas des pécheurs comme tous ces païens...»',
        16: "Sachant cependant que l'homme n'est pas justifié par les oeuvres de la Loi, mais qu'il l'est uniquement par la foi en Jésus-Christ. nous avons cru en Jésus-Christ pour être justifiés par cette foi. Ce n'est pas par les oeuvres de la Loi, parce que les oeuvres de la Loi << Ne justifient aucune créatures.»",
        17: "S'il se trouve alors que nous, qui cherchons notre justification en Christ, nous sommes aussi des pécheurs, Christ aura été (ce qu'à Dieu ne plaise) un ministre de péché!",
        18: "Si je rebâtis ce que j'avais abattu, je me constitue moi-même prévaricateur!",
        19: "Pour moi, c'est par égard pour la Loi que je suis mort à la Loi, afin de vivre à Dieu.",
        20: "J'ai été crucifié avec Christ; je ne vis plus, c'est Christ qui vit en moi. Le reste de vie que je traîne en la chair, je le vis dans la foi au Fils de Dieu a qui m'a aimé et s'est livré pour moi.",
        21: "Je ne veux pas anéantir la grâce de Dieu, et si la justice s'obtient par la Loi, alors Christ est mort pour rien!",
    },
    3: {
        1: "Ô Galates insensés! qui est-ce donc qui vous a ensorcelés, vous sous les yeux desquels on a fait passer l'image de Jésus-Christ crucifié!",
        2: "Je ne vous poserai qu'une question: Est-ce pour avoir observé la Loi que vous avez reçu l'Esprit, ou est-ce pour avoir entendu prêcher la foi?",
        3: "Que vous êtes donc fous! Vous avez commencé par l'Esprit, et puis vous finissez par la chair!",
        4: "Tant d'expériences pour rien! Et encore si c'était pour rien!",
        5: "Celui qui vous confère l'Esprit et qui fait des miracles parmi vous, agit-il ainsi parce que vous observez la Loi ou parce que vous avez entendu prêcher la foi?",
        6: "Souvenez-vous qu'Abraham «eut foi en Dieu et cela lui fut compté pour justice».",
        7: "Sachez donc que ceux qui ont la foi pour principe sont fils d'Abraham.",
        8: "L'Écriture a prévu que Dieu justifierait les païens par la foi, et elle a d'avance annoncé cette bonne nouvelle à Abraham:",
        9: '«Toutes les nations seront bénies en toi.» Ainsi ceux qui ont la foi sont bénis avec Abraham le croyant.',
        10: "Ceux qui en restent aux oeuvres de la Loi sont sous le poids d'une malédiction, car il est écrit: «Maudit est quiconque n'observe pas tout ce qui est écrit dans le Livre de la Loi de manière à le pratiquer.»",
        11: "De plus, il est bien évident que personne n'est justifié devant Dieu par la Loi, puisque: «Le juste vivra par la foi.»",
        12: 'Or la Loi ne se base pas sur la foi, mais: «Celui qui pratiquera ces commandements aura la vie par eux.»',
        13: "Christ nous a rachetés de la malédiction de la Loi, en devenant malédiction pour nous, (puisqu'il est écrit: «Maudit est quiconque est pendu au bois»),",
        14: "afin que la bénédiction accordée à Abraham passât aux païens par Jésus-Christ, et que nous obtenions par la foi l'Esprit promis.",
        15: "Mes frères, quand un contrat est passé en bonne forme (je parle des usages du monde), personne ne peut l'annuler ou le modifier par addition.",
        16: "Or, c'est à Abraham que les promesses ont été faites et à sa postérité. Il n'est pas dit: «et à ses postérités», comme s'il s'agissait de plusieurs personnes, mais, comme pour parler d'une seule: «et à ta postérité.» Il s'agit de Christ.",
        17: 'Eh bien, je dis ceci: Dieu ayant passé un contrat en bonne forme, la Loi venue quatre cent trente ans plus tard, ne peut le casser; elle ne peut annuler la promesse.',
        18: "Si on obtient l'héritage par une Loi, il ne vient plus d'une promesse. Or ce qu'Abraham a reçu de Dieu, il l'a reçu par une promesse.",
        19: "Alors, pourquoi la Loi? elle a été ajoutée à la promesse à cause des transgressions, jusqu'à la venue de «la postérité» au sujet de laquelle les promesses avaient été faites. Elle a été promulguée par des anges et par le ministère d'un médiateur.",
        20: "Or, un médiateur ne dépend pas d'un seul parti. Dieu au contraire est un!.",
        21: "Y aurait-il alors une contradiction entre la Loi et les promesses? Pas le moins du monde. Ah! sans doute, s'il avait été donné une Loi capable de produire la vie,",
        22: "alors la justice viendrait de la Loi. L'Écriture a au contraire tout enfermé sous le péché, afin que la promesse soit réalisée, pour les croyants, par la foi en Jésus-Christ.",
        23: 'Avant la venue de la foi, la Loi nous tenait prisonniers et nous gardait;',
        24: "nous attendions la foi qui devait être révélée. La Loi a été pour nous ce qu'est un pédagogue; elle nous a conduits au Christ, pour que nous fussions justifiés par la foi.",
        25: 'Maintenant que la foi est venue, nous ne sommes plus soumis au pédagogue.',
        26: 'Car vous êtes tous fils de Dieu par la foi en Jésus-Christ.',
        27: 'Oui, vous qui avez tous été baptisés pour être à Christ, vous êtes revêtus de Christ.',
        28: "Il n'y a plus là ni Juif, ni païen; ni esclave, ni libre; ni homme, ni femme; vous êtes tous un en Jésus-Christ.",
        29: "Et si vous êtes à Christ, vous êtes par conséquent de la famille d'Abraham, vous héritez en vertu de la promesse.",
    },
    4: {
        1: "Eh bien, voici ce que j'affirme: tant que l'héritier est mineur, il ne diffère en rien de l'esclave. Il possède tout l'héritage,",
        2: "et cependant il est sous des tuteurs et des administrateurs jusqu'au temps marqué par le père.",
        3: 'De même nous, tant que nous étions mineurs, nous étions esclaves des prescriptions du monde.',
        4: "Quand le temps fut accompli, Dieu envoya son Fils, né d'une femme, né sous la Loi,",
        5: 'pour racheter ceux qui étaient sous la Loi, et pour que nous jouissions des privilèges de fils.',
        6: "Et c'est parce que vous êtes fils, que Dieu a envoyé en nos coeurs l'Esprit de son Fils, s'écriant: Abba! c'est-à-dire Père!",
        7: "Vous n'êtes donc plus esclaves, vous êtes fils, et si vous êtes fils, vous êtes aussi héritiers, grâce à Dieu.",
        8: 'Autrefois, ne connaissant pas Dieu, vous serviez des êtres qui ne sont pas dieux,',
        9: 'mais maintenant que vous connaissez Dieu, bien mieux! que vous êtes connus de Dieu, comment retournez-vous à ces pauvres et misérables commencements, dont vous voulez de nouveau devenir esclaves?',
        10: 'Vous observez certains jours, et les lunaisons, et les époques des fêtes, et certaines années!',
        11: "ah! j'ai bien peur pour vous de n'avoir travaillé chez vous en pure perte!",
        12: "Faites comme moi; car moi, j'ai fait comme vous; frères, je vous en supplie, jusqu'ici vous ne m'aviez fait aucun tort.",
        13: "Vous savez comme j'étais malade la première fois que je vous ai annoncé l'Évangile;",
        14: "et vous ne m'avez pas méprisé, vous ne m'avez pas repoussé, quand ma chair passait ainsi par l'épreuve; au contraire, vous m'avez reçu comme un ange de Dieu, comme Jésus-Christ!",
        15: "Qu'est devenue votre joie d'alors? Je vous rends témoignage que, Si vous l'aviez pu, vous vous seriez arraché les yeux pour me les donner.",
        16: 'Et me voilà devenu votre ennemi, parce que je vous ai dit la vérité!',
        17: "Il y a des gens pleins de zèle pour vous, mais non en vue du bien; ce qu'ils veulent c'est vous détacher de moi, pour que vous les aimiez seuls.",
        18: "S'aimer en vue du bien, c'est une belle chose; mais il faut que cela dure, et ne pas seulement m'aimer quand je suis là.",
        19: "Oh! mes enfants, vous que j'enfante de nouveau dans la douleur jusqu'à ce que Christ soit formé en vous,",
        20: 'que je voudrais être près de vous dans ce moment, et changer de langage, car je suis bien inquiet de vous!',
        21: "Dites-moi, vous qui voulez être sous la Loi, n'entendez-vous pas la lecture de la Loi?",
        22: "Il y est écrit qu'Abraham avait deux fils, l'un de sa servante, l'autre de sa femme libre.",
        23: "Celui de la servante était né selon l'ordre de la nature, celui de la femme libre à la suite de la promesse.",
        24: "Tout cela est allégorique: ces femmes sont deux alliances, l'une, celle du mont Sinaï, a enfanté pour la servitude; c'est Agar.",
        25: '(Le mot Agar désigne, en effet, le mont Sinaï en Arabie.) Elle correspond à la Jérusalem actuelle',
        26: "qui est en servitude avec ses enfants. Mais la Jérusalem d'en haut est libre, c'est notre mère à nous.",
        27: "Il est écrit, en effet: Réjouis-toi, femme stérile, qui n'as point enfanté! Pousse des cris de joie, élève la voix, toi qui n'as pas senti les douleurs maternelles, Car les enfants de la femme abandonnée sont plus nombreux Que ceux de la femme mariée.»",
        28: "Et nous, mes frères, nous sommes les vrais descendants d'Isaac, les enfants de la promesse.",
        29: "Mais comme alors le fils né selon l'ordre de la nature persécutait celui qui était né selon l'Esprit, il en est encore ainsi aujourd'hui.",
        30: 'Mais que dit l’Écriture: «Chasse la servante et son fils, car le fils de la servante ne doit pas hériter avec le fils de la femme libre.»',
        31: 'Ainsi, mes frères, nous ne sommes pas enfants de la servante, mais de la femme libre.',
    },
    5: {
        1: "Christ nous a libérés; restez fermes dans cette liberté et ne reprenez pas le joug de l'esclavage.",
        2: "C'est moi, Paul, qui vous le dis: Si vous vous faites circoncire, Christ ne vous servira de rien.",
        3: "Je déclare encore une fois à tout homme qui se fait circoncire que cet acte l'oblige à observer toute la Loi.",
        4: 'Vous êtes absolument séparés de Christ, vous tous qui cherchez la justification dans la Loi; vous êtes déchus de la grâce.',
        5: "Nous, par l'Esprit, nous attendons de la foi l'espérance de la justification.",
        6: "Car, en Jésus-Christ, peu importe circoncision ou non-circoncision; ce qui importe c'est la foi devenant active par l'amour.",
        7: 'Vous couriez si bien! Qui donc vous a arrêtés, détournés de la vérité?',
        8: 'Ah! ce conseil ne vient pas de Celui qui vous appelle!',
        9: 'Un peu de levain fait lever la pâte tout entière...',
        10: "J'ai la confiance — dans le Seigneur — que vous reviendrez à penser comme moi... Quant à celui qui vous trouble, il portera la peine de tout ceci, quel qu'il soit",
        11: "Et moi, mes frères, je n'ai qu'à prêcher la circoncision, on ne me persécutera plus!",
        12: 'mais alors la croix et son scandale sont anéantis Ah! Je les voudrais plus que circoncis, ceux qui vous troublent',
        13: "Vous, mes frères, c'est à la liberté que vous avez été appelés; mais que cette liberté ne vous entraîne pas vers la chair. Vous devez, en vous aimant, vous servir les uns les autres.",
        14: "Toute la Loi se résume d'un seul mot: «Tu aimeras ton prochain comme toi-même.»",
        15: 'Et si, les uns les autres, vous vous mordez et vous dévorez, prenez garde, les uns par les autres vous vous perdrez.',
        16: "Marchez, vous dis-je, sous la direction de l'Esprit et résistez aux passions de la chair.",
        17: "La chair, en effet, conspire contre l'Esprit, et l'Esprit contre la chair; tous deux sont en lutte pour que vous ne fassiez pas ce que vous voudriez faire.",
        18: "Mais si l'Esprit vous conduit, vous n'êtes plus sous le joug de la Loi.",
        19: "Les oeuvres de la chair sont faciles à reconnaître; c'est la fornication, l'impureté, la débauche,",
        20: "l'idolâtrie, la sorcellerie, les haines, les disputes, l'envie, la colère, les querelles, les factions, l'esprit de parti,",
        21: "les jalousies, l'ivresse, les orgies et autres choses semblables, et, je vous le déclare d'avance (je vous en ai déjà prévenus), ceux qui agissent ainsi n'auront pas en héritage le Royaume de Dieu.",
        22: "Le fruit de l'Esprit, au contraire, est l'amour, la joie, la paix, la patience, l'indulgence, la bonté, la fidélité, la douceur, la tempérance.",
        23: "Pour ceux qui vivent ainsi, il n'y a pas de Loi.",
        24: 'Ceux qui sont à Jésus-Christ ont crucifié leur chair avec ses passions et ses désirs.',
        25: "Si nous vivons par l'Esprit, marchons aussi avec l'Esprit.",
        26: 'Ne devenons pas vains et vaniteux en nous provoquant les uns les autres, et en nous portant mutuellement envie.',
    },
    6: {
        1: "Mes frères, lors même que vous surprenez un homme en faute, vous qui êtes dirigés par l'Esprit, corrigez-le avec douceur; veille sur toi-même, que tu ne sois pas tenté, toi aussi.",
        2: 'Supportez mutuellement le poids de vos fautes et accomplissez ainsi la loi du Christ;',
        3: "car s'imaginer valoir quelque chose, quand on n'est rien, c'est se faire illusion à soi-même.",
        4: 'Que chacun examine ses propres actes, et alors il gardera ses motifs de vanité pour lui seul, et il ne les gardera plus pour autrui.',
        5: 'Chacun, en effet, aura son propre fardeau à porter.',
        6: "Celui à qui l'on enseigne la Parole de Dieu, doit faire part de tous ses biens à celui qui enseigne.",
        7: "Ne vous y trompez pas, on ne se moque pas de Dieu; ce que l'homme sème, il le récolte.",
        8: "Celui qui sème dans sa chair, récoltera ce que produit la chair: la mort; celui qui sème dans l'Esprit, récoltera ce que produit l'Esprit: la vie éternelle.",
        9: 'Ne nous, lassons pas de faire le bien et, le moment venu, nous récolterons, si nous avons tenu bon.',
        10: "Maintenant que nous en avons l'occasion, faisons du bien à tout le monde, et surtout à nos frères dans la foi.",
        11: 'Remarquez ces grands caractères, ils sont de ma main.',
        12: "Des gens qui veulent plaire par la chair, voilà ceux qui vous forcent à vous faire circoncire, et seulement pour n'être pas persécutés au nom de la croix du Christ.",
        13: "Car ces circoncis n'observent pas la Loi, mais ils veulent vous faire circoncire pour tirer gloire de votre chair.",
        14: 'Pour moi, Dieu me garde de me glorifier, sauf de la croix de notre Seigneur Jésus-Christ. Par lui le monde est crucifié pour moi, comme je le suis pour le monde.',
        15: "Il ne s'agit ni d'être circoncis, ni de ne pas l'être, mais d'être créé à nouveau.",
        16: "Sur tous ceux qui observeront cette règle, paix et miséricorde, ainsi que sur l'Israël de Dieu!",
        17: "Qu'à l'avenir personne ne me fasse de la peine, car je porte sur mon corps les stigmates de Jésus.",
        18: 'La grâce de notre Seigneur Jésus-Christ soit avec votre esprit, frères. Amen',
    },
}
