NAME = 'TpiKJPB: King Jems Pisin Baibel'
BOOK = 'Revelation of John'

CHAPTERS = {
    1: {
        1: '¶ Revelesen bilong Jisas Kraist, dispela God i givim long em, long soim long ol wokboi bilong em ol dispela samting i mas kamap klostu nau. Na em i salim na mekim klia dispela long han bilong ensel bilong em i go long wokboi bilong em Jon,',
        2: 'Husat i tokaut klia long tok bilong God, na long testimoni bilong Jisas Kraist, na long olgeta dispela samting em i lukim.',
        3: '¶ Blesing i stap long em husat i ritim, na ol husat i harim ol toktok bilong dispela tok profet, na holimpas ol dispela samting, dispela em i raitim insait long en. Long wanem, taim em i klostu.',
        4: 'Jon i go long dispela sevenpela sios i stap long Esia. Marimari i ken stap long yupela, na bel isi, i kam long em husat i stap, na husat i bin stap, na husat bai kam, na long dispela sevenpela Spirit i stap long ai bilong sia king bilong em,',
        5: 'Na long Jisas Kraist, husat em i dispela witnes yu inap bilip long em, na namba wan man God i kamapim long dai, na hetman bilong ol king bilong dispela graun. I go long em husat i laikim yumi tru, na wasim yumi long ol sin bilong yumi long blut bilong em yet,',
        6: 'Na husat i bin mekim yumi ol king na ol pris i go long God na Papa bilong em. Long em glori na biknem long bosim i stap oltaim oltaim na oltaim. Amen.',
        7: 'Lukim, em i kam wantaim ol klaut. Na olgeta wan wan ai bai lukim em, na ol tu husat i bin sutim em. Na olgeta kandre bilong dispela graun bai krai wantaim singaut bilong tingim em. Yes, olsem tasol, Amen.',
        8: 'Mi stap Alpa na Omega, stat na pinis, Bikpela i tok, husat i stap, na husat i bin stap, na husat bai kam, God i Gat Olgeta Strong.',
        9: '¶ Mi Jon, husat tu em i brata bilong yupela, na poroman long bikpela hevi, na long kingdom na pasin bilong sanap strong long traim bilong Jisas Kraist, i stap long dispela ailan ol i kolim Patmos, bilong tingim tok bilong God, na bilong tingim testimoni bilong Jisas Kraist.',
        10: 'Mi stap long Spirit long de bilong Bikpela, na harim baksait long mi wanpela bikpela nek, olsem i bilong wanpela biugel,',
        11: 'I spik, Mi stap Alpa na Omega, namba wan na las. Na, Wanem samting yu lukim, raitim insait long wanpela buk, na salim i go long dispela sevenpela sios i stap long Esia, i go long Efesas, na i go long Smerna, na i go long Pergamos, na i go long Taiataira, na i go long Sardis, na i go long Filadelfia, na i go long Leodisia.',
        12: 'Na mi tanim long lukim dispela nek i toktok wantaim mi. Na taim mi tanim pinis, mi lukim sevenpela stik kandel gol,',
        13: 'Na namel bilong dispela sevenpela stik kandel wanpela i wankain olsem Pikinini Man bilong man, husat i werim wanpela klos i go daun inap long fut, na em i pas nabaut long bros wantaim wanpela bikpela let gol.',
        14: 'Het bilong em na ol gras bilong em i waitpela olsem gras bilong sipsip, waitpela olsem ais. Na tupela ai bilong em i olsem lait bilong paia.',
        15: 'Na tupela lek bilong em i wankain olsem naispela bras, olsem sapos ol i kuk long ples bilong strongpela paia. Na nek bilong em i olsem nois bilong planti wara.',
        16: 'Na em i gat long han sut bilong em sevenpela sta. Na ausait long maus bilong em bainat i gat tupela sap i go. Na pes bilong em i olsem lait bilong san long strong bilong en.',
        17: 'Na taim mi lukim em, mi pundaun long tupela lek bilong em olsem mi dai pinis. Na em i slipim han sut bilong em antap long mi, taim em i spik long mi, No ken pret. Mi stap namba wan na las.',
        18: 'Mi stap em husat i stap laip, na i bin dai pinis, na, lukim, mi stap laip oltaim oltaim, Amen. Na mi gat ol ki bilong hel na bilong dai.',
        19: 'Raitim ol dispela samting yu bin lukim, na ol dispela samting i stap, na ol dispela samting bai i stap bihain long nau,',
        20: 'Samting hait bilong dispela sevenpela sta yu lukim long han sut bilong mi, na dispela sevenpela stik kandel gol. Dispela sevenpela sta em ol ensel bilong dispela sevenpela sios. Na dispela sevenpela stik kandel yu lukim em dispela sevenpela sios.',
    },
    2: {
        1: '¶ Raitim i go long ensel bilong sios bilong Efesas, Ol dispela samting em i tok bilong em husat i holim dispela sevenpela sta long han sut bilong em, husat i wokabaut namel long dispela sevenpela stik kandel gol.',
        2: 'Mi save long ol wok bilong yu, na hatwok bilong yu, na pasin bilong yu long sanap strong long traim, na olsem wanem long yu no laikim ol husat i nogut. Na yu bin traim ol husat i tok ol i ol aposel, na ol i no ol aposel, na yu bin painimaut pinis ol i ol man bilong giaman.',
        3: 'Na yu bin karim, na yu bin sanap strong long traim, na bilong tingim nem bilong mi yu bin hatwok, na yu no bin hap i dai.',
        4: 'Tasol mi gat samting i birua long yu, bilong wanem, yu bin lusim namba wan laikim tru bilong yu.',
        5: 'Olsem na holim tingting long yu bin pundaun pinis long we, na tanim bel, na mekim ol namba wan wok bilong yu. O sapos nogat, mi bai kam long yu kwiktaim, na mi bai rausim stik kandel bilong yu ausait long ples bilong en, sapos yu no tanim bel.',
        6: 'Tasol dispela yu gat, long yu hetim ol pasin bilong ol lain bilong Nikolas, dispela mi tu i hetim.',
        7: 'Em husat i gat ia, larim em harim wanem samting Spirit i tokim ol sios. Long em husat i winim bai mi givim long kaikai long diwai bilong laip, dispela i stap namel long paradais bilong God.',
        8: '¶ Na raitim i go long ensel bilong sios i stap long Smerna, Ol dispela samting em i tok bilong em husat i namba wan na las, husat i bin dai pinis, na i stap laip.',
        9: 'Mi save long ol wok bilong yu, na bikpela hevi, na long yu stap rabis tru, (tasol yu stap maniman tru) na mi save long tok bilas bilong ol husat i tok ol i ol Ju, na ol i no ol Ju, tasol ol i sinagog bilong Seten.',
        10: 'No ken pret long wanpela bilong ol dispela samting, dispela yu bai karim pen long en. Lukim, Seten bai tromoi sampela bilong yupela i go long kalabus, inap long ol i ken kotim yupela. Na yupela bai gat bikpela hevi tenpela de. Yu mas stap man yu inap bilip long em i go inap long dai, na mi bai givim yu wanpela hat king bilong laip.',
        11: 'Em husat i gat ia, larim em harim wanem samting Spirit i tokim ol sios. Em husat i winim bai i no inap kisim pen long namba tu dai.',
        12: '¶ Na raitim long ensel bilong sios i stap long Pergamos, Ol dispela samting em i tok bilong em husat i gat bainat i gat tupela sap.',
        13: 'Mi save long ol wok bilong yu, na we yu stap, yes, we sia bilong Seten i stap. Na yu holimpas strong nem bilong mi, na yu no bin tok nogat long bilip tru bilong mi, yes, insait long ol dispela de we Antipas, man yu inap bilip long em bilong mi, i sanap strong long bilip inap long dai, husat ol i kilim i dai namel long yupela, we Seten i stap.',
        14: 'Tasol mi gat wan wan samting i birua long yu, bilong wanem, yu gat long dispela hap ol husat i holimpas skul bilong Belam, husat i skulim Belak long tromoi samting bilong sutim lek long ai bilong ol pikinini bilong Israel, long kaikai long ol samting ol i sakrifais i go long ol piksa bilong god giaman, na long mekim pamuk pasin.',
        15: 'Olsem tasol tu yu gat ol husat i holimpas skul bilong ol lain bilong Nikolas, dispela samting mi hetim.',
        16: 'Tanim bel. O sapos nogat, mi bai kam long yu kwiktaim, na mi bai pait birua long ol wantaim bainat bilong maus bilong mi.',
        17: 'Em husat i gat ia, larim em harim wanem samting Spirit i tokim ol sios. Long em husat i winim bai mi givim long kaikai long mana hait, na mi bai givim em wanpela waitpela ston, na insait long dispela ston mi raitim wanpela nupela nem, dispela i no gat arapela man i save long en, em husat i kisim tasol bai save long en.',
        18: '¶ Na raitim i go long ensel bilong sios i stap long Taiataira, Ol dispela samting em i tok bilong Pikinini Man bilong God, husat i gat tupela ai bilong em i wankain olsem lait bilong paia, na tupela lek bilong em i olsem naispela bras.',
        19: 'Mi save long ol wok bilong yu, na pasin bilong laikim tru, na wok yu wokim, na bilip tru, na sanap strong long traim bilong yu, na ol wok bilong yu. Na dispela las i stap moa long dispela bilong pastaim.',
        20: 'Tasol mi gat wan wan samting i birua long yu, bilong wanem, yu larim dispela meri Jesebel, husat i kolim em yet wanpela profet meri, long skulim na long grisim ol wokboi bilong mi long mekim pamuk pasin, na long kaikai ol samting ol i sakrifais i go long ol piksa bilong god giaman.',
        21: 'Na mi givim em taim long tanim bel long ol pamuk pasin bilong em. Na em i no tanim bel.',
        22: 'Lukim, mi bai tromoi em i go long wanpela bet, na ol husat i bagarapim marit long pamuk pasin wantaim em i go long taim bilong bikpela hevi, sapos ol i no tanim bel long ol pasin bilong ol.',
        23: 'Na mi bai kilim ol pikinini bilong em wantaim dai. Na olgeta sios bai save tru long mi stap em husat i painim tru long ol stia bilong bel na ol bel. Na mi bai givim i go long olgeta wan wan bilong yupela bilong bihainim olgeta wok bilong yupela.',
        24: 'Tasol long yu mi tok, na long olgeta arapela i stap long Taiataira, hamas man i no gat dispela skul, na husat i no bin save long ol dip samting bilong Seten, olsem ol i toktok, mi bai i no inap putim wanpela arapela hevi antap long yupela.',
        25: 'Tasol dispela samting yupela i gat pinis, holimpas strong inap long mi kam.',
        26: 'Na em husat i winim, na holimpas ol wok bilong mi inap long pinis, long em bai mi givim pawa long bosim ol kantri.',
        27: 'Na em bai bosim ol wantaim wanpela stik ain. Olsem ol sospen samting bilong man bilong wokim sospen graun, bai ol i bruk bruk liklik tru. Yes, olsem mi kisim long Papa bilong mi.',
        28: 'Na mi bai givim em dispela moning sta.',
        29: 'Em husat i gat ia, larim em harim wanem samting Spirit i tokim ol sios.',
    },
    3: {
        1: '¶ Na raitim i go long ensel bilong sios i stap long Sardis, Ol dispela samting em tok bilong em husat i gat dispela sevenpela Spirit bilong God, na dispela sevenpela sta. Mi save long ol wok bilong yu, long yu gat nem long yu stap laip, na yu stap daiman.',
        2: 'Was gut, na strongim ol dispela samting i stap yet, dispela i redi long dai. Long wanem, mi no bin lukim olsem ol wok bilong yu i inap tru long ai bilong God.',
        3: 'Olsem na holim tingting long yu bin kisim na harim olsem wanem, na holimpas strong, na tanim bel. Olsem na sapos yu no laik was, mi bai kam long yu olsem stilman, na yu bai i no inap save long wanem aua mi bai kam long yu.',
        4: 'Yu gat wan wan nem, yes, long Sardis husat i no bin mekim ol klos bilong ol doti. Na ol bai wokabaut wantaim mi long waitpela klos. Long wanem, ol i gat namba inap.',
        5: 'Em husat i winim, em stret bai pasim waitpela klos. Na mi bai i no inap rausim i go nem bilong em ausait long buk bilong laip, tasol mi bai tok yes long nem bilong em long ai bilong Papa bilong mi, na long ai bilong ol ensel bilong em.',
        6: 'Em husat i gat ia, larim em harim wanem samting Spirit i tokim ol sios.',
        7: '¶ Na raitim long ensel bilong sios i stap long Filadelfia, Ol dispela samting em tok bilong em husat i holi, em husat i tru, em husat i gat ki bilong Devit, em husat i opim, na i no gat man i pasim, na pasim, na i no gat man i opim.',
        8: 'Mi save long ol wok bilong yu. Lukim, mi bin putim long ai bilong yu wanpela dua i op, na i no gat man i ken pasim dispela. Long wanem, yu gat liklik strong, na yu bin holimpas tok bilong mi, na yu no bin tok nogat long nem bilong mi.',
        9: 'Lukim, mi bai mekim ol bilong sinagog bilong Seten, husat i tok ol i ol Ju, na ol i no ol Ju, tasol ol i giaman, lukim, mi bai mekim ol long kam na lotu long ai bilong ol fut bilong yu, na long save tru long mi bin laikim yu tru.',
        10: 'Bikos yu bin holimpas tok bilong sanap strong long traim bilong mi, mi tu bai pasim yu longwe long dispela aua bilong traim, dispela i bai kam antap long olgeta dispela graun, long traim ol husat i stap long dispela graun.',
        11: 'Lukim, mi bai kam kwiktaim. Holimpas strong dispela samting yu gat, inap long i no gat man i kisim hat king bilong yu.',
        12: 'Em husat i winim bai mi mekim wanpela bikpela pos insait long tempel bilong God bilong mi, na em bai i no inap go ausait moa. Na mi bai raitim antap long em nem bilong God bilong mi, na nem bilong biktaun bilong God bilong mi, dispela em i nupela Jerusalem, dispela i kam daun ausait long heven i lusim God bilong mi. Na mi bai raitim antap long em nupela nem bilong mi.',
        13: 'Em husat i gat ia, larim em harim wanem samting Spirit i tokim ol sios.',
        14: '¶ Na raitim i go long ensel bilong sios bilong ol lain bilong Leodisia, Ol dispela samting em tok bilong dispela Amen, witnes yu inap bilip long em na i tru, stat bilong samting God i kamapim long nating.',
        15: 'Mi save long ol wok bilong yu, long yu no stap kolpela o hatpela. Mi gat laik long yu stap kolpela o hatpela.',
        16: 'Olsem nau bikos yu stap hatpela liklik tasol, na i no kolpela o hatpela, mi bai trautim yu long maus bilong mi.',
        17: 'Bilong wanem, yu tok, Mi stap maniman, na mi pulap wantaim ol kago, na mi no gat nid long wanpela samting. Na yu no save long yu stap bagarap tru, na yu pulap long ol hevi nogut, na yu rabisman, na yu aipas, na yu skin nating.',
        18: 'Mi givim tok helpim long yu long baim long mi gol ol i traim insait long paia, inap long yu ken stap maniman, na waitpela klos, inap long yu ken gat klos, na inap long sem bilong skin nating bilong yu i no kamap ples klia. Na welim tupela ai bilong yu wantaim gris marasin bilong ai, inap long yu ken lukluk.',
        19: 'Hamas man mi laikim tru, mi hatim na stikim. Olsem na hatwok long bihainim mi, na tanim bel.',
        20: 'Lukim, mi sanap long dua, na paitim. Sapos wanpela man i harim nek bilong mi, na opim dua, mi bai kam insait long em, na mi bai kaikai wantaim em, na em wantaim mi.',
        21: 'Long em husat i win bai mi tok orait long sindaun wantaim mi long sia king bilong mi, yes, olsem mi tu i bin win, na sindaun wantaim Papa bilong mi long sia king bilong em.',
        22: 'Em husat i gat ia, larim em harim wanem samting Spirit i tok long ol sios.',
    },
    4: {
        1: '¶ Bihain long dispela mi lukluk, na, lukim, ol i opim wanpela dua long heven. Na dispela namba wan nek mi harim i samting olsem em i bilong wanpela biugel i toktok wantaim mi, husat i tok, Kam antap long hia, na mi bai soim yu ol dispela samting i mas stap bihain long nau.',
        2: 'Na wantu mi stap long spirit. Na, lukim, wanpela sia king i sindaun long heven, na wanpela i sindaun antap long sia king.',
        3: 'Na em husat i sindaun, long lukluk bilong em, i olsem jaspa na sardin ston. Na i gat wanpela renbo raun nabaut long sia king, long lukluk bilong en i wankain olsem wanpela emeral.',
        4: 'Na raun nabaut long sia king i gat 24 sia. Na antap long ol sia mi lukim 24 lapun hetman i sindaun, ol i werim waitpela klos. Na ol i gat antap long ol het bilong ol ol hat king gol.',
        5: 'Na ausait long sia king ol lait bilong klaut na ol nois bilong klaut i pairap na ol nek i kam ausait. Na i gat sevenpela lam bilong paia i kuk long ai bilong sia king, dispela em dispela sevenpela Spirit bilong God.',
        6: 'Na long ai bilong sia king i gat wanpela biksi bilong glas i wankain olsem kristal. Na long namel bilong sia king, na raun nabaut long sia king, i gat fopela animal, pulap long ol ai long fran na long baksait.',
        7: 'Na namba wan animal i olsem wanpela laion, na namba tu animal i olsem wanpela pikinini bulmakau, na namba tri animal i gat pes olsem man, na namba foa animal i olsem igal i flai.',
        8: '¶ Na dispela fopela animal i gat, olgeta wan wan bilong ol, sikispela wing nabaut long em. Na ol i pulap long ol ai insait. Na ol i no malolo san na nait, i spik, Holi, holi, holi, God Bikpela i Gat Olgeta Strong, husat i bin stap, na husat i stap, na husat bai kam.',
        9: 'Na taim ol dispela animal i givim glori na ona na tok tenkyu long em husat i sindaun long sia king, husat i stap laip oltaim oltaim na oltaim,',
        10: 'Dispela 24 lapun hetman i pundaun long ai bilong em husat i sindaun long sia king, na lotuim em husat i stap laip oltaim oltaim na oltaim, na tromoi ol hat king bilong ol long ai bilong sia king, i spik,\u200b',
        11: 'Yu gat namba inap, O Bikpela, long kisim glori na ona na pawa. Long wanem, yu bin kamapim long nating olgeta samting, na bilong amamasim bel bilong yu ol i stap na yu bin kamapim ol long nating.',
    },
    5: {
        1: '¶ Na mi lukim long han sut bilong em husat i sindaun long sia king wanpela buk ol raitim long insait na long baksait, na ol i pasim wantaim sevenpela samting bilong pasim.',
        2: 'Na mi lukim wanpela strongpela ensel i autim toksave wantaim bikpela nek, Husat i gat namba inap long opim dispela buk, na long lusim ol samting bilong pasim bilong en?',
        3: 'Na i no gat man long heven, o long dispela graun, o aninit long dispela graun husat em inap long opim dispela buk, o long lukluk long en.',
        4: 'Na mi krai tru planti, bilong wanem, ol i no painim pinis man husat i gat namba inap long opim na long ritim dispela buk, o long lukluk long en.',
        5: 'Na wanpela bilong ol lapun hetman i tokim mi, No ken krai tru. Lukim, Laion bilong lain bilong Juda, Rop Daunbilo bilong Devit, i bin win long opim dispela buk, na long lusim dispela sevenpela samting bilong pasim bilong en.',
        6: '¶ Na mi lukim, na, harim, long namel bilong sia king na bilong dispela fopela animal, na long namel bilong ol lapun hetman, wanpela Pikinini Sipsip i sanap olsem ol i bin kilim em i dai, taim em i gat sevenpela kom na sevenpela ai, dispela em dispela sevenpela Spirit bilong God em i salim i go long olgeta hap bilong dispela graun.',
        7: 'Na em i kam na kisim dispela buk ausait long han sut bilong em husat i sindaun antap long sia king.',
        8: 'Na taim em i bin kisim dispela buk, dispela fopela animal na 24 lapun hetman i pundaun long ai bilong Pikinini Sipsip, taim olgeta wan wan bilong ol i gat ol harp, na ol dis gol i pulap long ol smel, dispela em ol beten bilong ol seint.',
        9: 'Na ol i singim wanpela nupela song, i spik, Yu gat namba inap long kisim dispela buk, na long opim ol samting bilong pasim bilong en. Long wanem, ol i bin kilim yu i dai, na yu bin baim bek mipela i go long God long blut bilong yu ausait long olgeta wan wan kandre, na tok ples, na lain manmeri, na kantri.',
        10: 'Na yu bin mekim mipela ol king na ol pris long God bilong mipela. Na mipela bai bosim kingdom long dispela graun.',
        11: 'Na mi lukim, na mi harim nek bilong planti ensel raun nabaut long sia king na ol animal na ol lapun hetman. Na namba bilong ol em 10,000 taims 10,000, na ol tausen tausen.',
        12: 'Ol i spik wantaim bikpela nek, Pikinini Sipsip husat ol i kilim i dai i gat namba inap long kisim pawa, na planti mani samting, na save tru, na strong, na ona, na glori, na blesing.',
        13: 'Na olgeta wan wan samting God i wokim husat i stap long heven, na long dispela graun, na aninit long dispela graun, na ol kain samting i stap long biksi, na olgeta husat i stap insait long ol, mi harim ol i spik, Blesing, na ona, na glori, na pawa, i go long em husat i sindaun antap long sia king, na i go long Pikinini Sipsip oltaim oltaim na oltaim.',
        14: 'Na dispela fopela animal i tok, Amen. Na dispela 24 lapun hetman i pundaun na lotuim em husat i stap laip oltaim oltaim na oltaim.',
    },
    6: {
        1: '¶ Na mi lukim taim Pikinini Sipsip i opim wanpela bilong ol dispela samting bilong pasim, na mi harim, samting olsem nois bilong klaut i pairap, wanpela bilong dispela fopela animal i spik, Kam na lukim.',
        2: 'Na mi lukluk, na lukim, wanpela waitpela hos. Na em husat i sindaun antap long en i gat banara. Na ol i givim wanpela hat king long em. Na em i go ausait long em i ken winim pait olgeta, na long winim pait olgeta.',
        3: '¶ Na taim em i bin opim namba tu samting bilong pasim, mi harim namba tu animal i spik, Kam na lukim.',
        4: 'Na i gat i go ausait narapela hos husat i retpela. Na ol i givim pawa long em husat i sindaun antap long en long tekewe bel isi long dispela graun, na long ol i ken kilim ol yet wan wan. Na ol i givim long em wanpela bikpela bainat.',
        5: 'Na taim em i bin opim namba tri samting bilong pasim, mi harim namba tri animal i spik, Kam na lukim. Na mi lukim, na harim, wanpela blakpela hos. Na em husat i sindaun antap long en i gat skel i gat tupela sait long han bilong em.',
        6: 'Na mi harim wanpela nek long namel bilong dispela fopela animal i spik, Wanpela hap skel bilong wit long wanpela peni, na tripela hap skel bilong bali long wanpela peni. Na lukluk gut long yu no bagarapim dispela wel na dispela wain.',
        7: 'Na taim em i bin opim namba foa samting bilong pasim, mi harim nek bilong namba foa animal i spik, Kam na lukim.',
        8: 'Na mi lukluk, na lukim, wanpela hos i waitpela liklik. Na nem bilong em husat i sindaun antap long en em Dai, na Hel i kam bihain wantaim em. Na ol i givim pawa long tupela long winim namba foa hap bilong dispela graun, long kilim wantaim bainat, na wantaim hangre, na wantaim dai, na wantaim ol animal bilong dispela graun.',
        9: '¶ Na taim em i bin opim namba faiv samting bilong pasim, mi lukim aninit long alta ol tewel bilong ol husat ol i kilim i dai bilong tingim tok bilong God, na bilong tingim dispela testimoni ol i holimpas.',
        10: 'Na ol i singaut wantaim wanpela bikpela nek, i spik, Inap long wanem taim, O Bikpela, holi na tru, long yu no jasim na bekim pe nogut long blut bilong mipela antap long ol husat i stap long dispela graun?',
        11: 'Na ol i givim ol waitpela longpela saket long olgeta wan wan bilong ol. Na ol i tokim ol long dispela, long ol i mas malolo yet long liklik taim, inap long ol wanwok bilong ol tu na ol brata bilong ol, husat ol i mas kilim ol olsem ol, i ken kamap pinis.',
        12: 'Na mi lukim taim em i bin opim namba sikis samting bilong pasim, na, harim, i gat bikpela guria. Na san i kamap blakpela olsem bek laplap bilong gras bilong bodi, na mun i kamap olsem blut.',
        13: 'Na ol sta bilong heven i pundaun long dispela graun, yes, olsem diwai fik i tromoi nating ol fik bilong en i no kam long taim stret, taim strongpela win i seksekim em.',
        14: 'Na heven i go olsem pepa ol i tantanim taim ol i tantanim dispela wantaim. Na olgeta wan wan maunten na ailan i muv ausait long ol ples bilong ol.',
        15: 'Na ol king bilong dispela graun, na ol bikman, na ol maniman, na ol nambawan kepten, na ol strongpela man, na olgeta wan wan wokboi nating, na olgeta wan wan man i stap fri, i haitim ol yet insait long ol hul na insait long ol ston bilong ol maunten.',
        16: 'Na ol i tokim ol maunten na ol ston, Pundaun antap long mipela, na haitim mipela long pes bilong em husat i sindaun antap long sia king, na long belhat tru bilong Pikinini Sipsip.',
        17: 'Long wanem, bikpela de bilong belhat tru bilong em i kam pinis. Na husat bai stap inap long sanap?',
    },
    7: {
        1: '¶ Na bihain long ol dispela samting mi lukim fopela ensel i sanap long fopela kona bilong dispela graun, taim ol i holim dispela fopela win bilong dispela graun, inap long win i no ken ran antap long dispela graun, o antap long biksi, o antap long wanpela diwai.',
        2: 'Na mi lukim narapela ensel i lusim hap is i go antap, husat i gat mak bilong God i stap laip. Na em i singaut wantaim bikpela nek long dispela fopela ensel, long husat God i givim pawa long bagarapim dispela graun na biksi,',
        3: 'I spik, No ken bagarapim dispela graun, o biksi, o ol diwai, inap long yumi bin makim ol wokboi bilong God bilong yumi insait long ol poret bilong ol.',
        4: 'Na mi harim namba bilong ol husat ol i makim. Na i gat 144,000 bilong olgeta lain bilong ol pikinini bilong Israel ol i makim.',
        5: 'Bilong lain bilong Juda ol i makim 12,000. Bilong lain bilong Ruben ol i makim 12,000. Bilong lain bilong Gat ol i makim 12,000.',
        6: 'Bilong lain bilong Aser ol i makim 12,000. Bilong lain bilong Neptalim ol i makim 12,000. Bilong lain bilong Manasas ol i makim 12,000.',
        7: 'Bilong lain bilong Simion ol i makim 12,000. Bilong lain bilong Livai ol i makim 12,000. Bilong lain bilong Isakar ol i makim 12,000.',
        8: 'Bilong lain bilong Sabyulon ol i makim 12,000. Bilong lain bilong Josef ol i makim 12,000. Bilong lain bilong Benjamin ol i makim 12,000.',
        9: 'Bihain long dispela mi lukim, na, harim, wanpela traipela lain tru, husat i no gat man i ken kaunim, bilong olgeta kantri, na ol kandre, na ol lain manmeri, na ol tok ples, i sanap long ai bilong sia king, na long ai bilong Pikinini Sipsip, husat i werim ol waitpela longpela saket, na i gat ol palmen long ol han bilong ol.',
        10: 'Na ol i singaut wantaim bikpela nek, i spik, Pasin bilong kisim bek i go long God bilong yumi husat i sindaun antap long sia king, na i go long Pikinini Sipsip.',
        11: 'Na olgeta ensel i sanap raun nabaut long sia king, na nabaut long ol lapun hetman na dispela fopela animal, na pundaun long ai bilong sia king long ol pes bilong ol, na lotuim God,',
        12: 'I spik, Amen. Blesing, na glori, na save tru, na tok tenkyu, na ona, na pawa, na strong i go long God bilong yumi oltaim oltaim na oltaim. Amen.',
        13: '¶ Na wanpela bilong ol lapun hetman i bekim, i spik long mi, Ol dispela husat i putim ol waitpela naispela klos long longpela saket i wanem? Na ol i kam we?',
        14: 'Na mi tokim em, Bikman, yu save. Na em i tokim mi, Ol dispela em ol husat i kam ausait long taim bilong bikpela hevi, na husat i bin wasim ol longpela saket bilong ol, na mekim ol waitpela long blut bilong Pikinini Sipsip.',
        15: 'Olsem na ol i stap long ai bilong sia king bilong God, na wokim wok long em san na nait insait long tempel bilong em. Na em husat i sindaun long sia king bai stap namel long ol.',
        16: 'Ol bai i no inap hangre moa, o nekdrai moa liklik, na tu san bai i no inap lait antap long ol, o wanpela hat.',
        17: 'Long wanem, Pikinini Sipsip husat i stap namel long sia king bai givim kaikai long ol, na bai stiaim ol i go long ol ai bilong wara i sut i stap laip. Na God bai rausim i go olgeta aiwara long ol ai bilong ol.',
    },
    8: {
        1: '¶ Na taim em i bin opim namba seven samting bilong pasim, i no gat nois long heven klostu olsem taim bilong namba tu hap bilong wanpela aua.',
        2: 'Na mi lukim sevenpela ensel husat i sanap long ai bilong God. Na long ol ol i givim sevenpela biugel.',
        3: 'Na narapela ensel i kam na sanap long alta, taim em i gat wanpela dis bilong insens gol. Na ol i givim em planti insens, inap long em i ken ofaim dispela wantaim ol beten bilong olgeta seint antap long dispela alta gol i stap long ai bilong sia king.',
        4: 'Na smuk bilong insens, dispela i kam wantaim ol beten bilong ol seint, i go antap long ai bilong God ausait long han bilong ensel.',
        5: 'Na ensel i kisim dis bilong insens, na pulimapim dispela wantaim paia bilong alta, na tromoi dispela i go long dispela graun. Na i gat ol nek, na ol klaut i pairap, na ol lait bilong klaut, na wanpela guria.',
        6: 'Na dispela sevenpela ensel husat i gat dispela sevenpela biugel i redim ol yet long winim ol biugel.',
        7: '¶ Namba wan ensel i winim biugel, na bihain long en i gat ren ais na paia i abusim wantaim blut, na ol i tromoi ol i go daun long dispela graun. Na namba tri hap bilong ol diwai i kuk olgeta, na olgeta gras i grin i kuk olgeta.',
        8: 'Na namba tu ensel i winim biugel, na samting olsem wanpela bikpela maunten i kuk wantaim paia ol i tromoi i go insait long biksi. Na namba tri hap bilong biksi i kamap blut.',
        9: 'Na namba tri hap bilong olgeta animal husat i stap insait long biksi, na i gat laip, i dai pinis. Na namba tri hap bilong olgeta sip i bagarap olgeta.',
        10: 'Na namba tri ensel i winim biugel, na i gat wanpela bikpela sta i pundaun long heven, i kuk samting olsem wanpela lam, na em i pundaun antap long namba tri hap bilong ol riva, na antap long ol ai bilong wara i sut bilong ol wara.',
        11: 'Na nem bilong dispela sta ol i kolim Womwut. Na namba tri hap bilong ol wara i kamap womwut. Na planti man i dai pinis long ol wara, bilong wanem, dispela sta i mekim ol wara i gat pait tru.',
        12: 'Na namba foa ensel i winim biugel, na ol i paitim namba tri hap bilong san, na namba tri hap bilong mun, na namba tri hap bilong ol sta, olsem inap long namba tri hap bilong ol i go tudak, na de i no lait long namba tri hap bilong en, na nait i wankain olsem.',
        13: 'Na mi lukim, na harim wanpela ensel i flai insait long namel bilong heven, i spik wantaim bikpela nek, Tok lukaut, tok lukaut, tok lukaut, i go long ol lain i stap long dispela graun bikos ol arapela nek bilong biugel bilong dispela tripela ensel i stap, husat i no winim biugel yet!',
    },
    9: {
        1: '¶ Na namba faiv ensel i winim biugel, na mi lukim wanpela sta i pundaun long heven i go long dispela graun. Na long em ol i givim ki bilong dispela bikpela hul i no gat as bilong en.',
        2: 'Na em i opim dispela bikpela hul i no gat as bilong en. Na i gat smuk i kirap i kam ausait long dispela bikpela hul, olsem smuk bilong wanpela bikpela ples bilong wokim paia. Na san na win i go tudak bikos dispela bikpela smuk bilong bikpela hul i kam ausait.',
        3: 'Na i gat i kam ausait long smuk ol lokas antap long dispela graun. Na long ol ol i givim pawa, olsem ol skopian bilong dispela graun i gat pawa.',
        4: 'Na ol i tok strong long ol long ol i no ken bagarapim gras bilong dispela graun, o wanpela samting i grinpela, o wanpela diwai. Tasol ol bai bagarapim ol dispela man tasol husat i no gat mak bilong God antap long ol poret bilong ol.',
        5: 'Na long ol ol i givim tok long ol i no ken kilim ol, tasol long ol i ken givim traipela pen long ol faipela mun. Na traipela pen bilong ol i olsem traipela pen bilong skopian, taim em i paitim wanpela man.',
        6: 'Na long ol dispela de bai ol man i painim dai, na ol bai i no inap painim dispela pinis. Na ol bai gat laik long dai, na dai bai ranawe long ol.',
        7: 'Na ol lukluk bilong ol lokas i wankain olsem ol hos ol i redim long pait. Na antap long ol het bilong ol i stap samting olsem ol hat king i olsem gol, na ol pes bilong ol i luk olsem ol pes bilong ol man.',
        8: 'Na ol i gat gras olsem gras bilong ol meri, na ol tit bilong ol i olsem ol tit bilong ol laion.',
        9: 'Na ol i gat ol klos pait bilong bros, samting olsem ol klos pait bilong bros bilong ain. Na nois bilong ol wing bilong ol i olsem nois bilong ol karis bilong planti hos i ran i go long pait.',
        10: 'Na ol i gat ol tel i wankain olsem ol skopian, na ol samting bilong givim pen i stap insait long ol tel bilong ol. Na pawa bilong ol em bilong givim pen long ol man faipela mun.',
        11: 'Na ol i gat wanpela king long bosim ol, husat em i dispela ensel bilong bikpela hul i no gat as bilong en, husat nem bilong em long tok ples Hibru em Abadon, tasol long tok ples Grik em i gat nem Apoleon.',
        12: 'Wanpela tok lukaut i pinis. Na, lukim, i gat tupela tok lukaut moa i kam bihain long nau.',
        13: '¶ Na namba sikis ensel i winim biugel, na mi harim wanpela nek i kam long fopela kom bilong dispela alta gol i stap long ai bilong God,',
        14: 'I spik long namba sikis ensel husat i gat biugel, Lusim dispela fopela ensel ol i pasim insait long bikpela wara Yufretis.',
        15: 'Na em i lusim dispela fopela ensel, husat ol i redim bilong wanpela aua, na wanpela de, na wanpela mun, na wanpela yia, bilong kilim i dai namba tri hap bilong ol man.',
        16: 'Na namba bilong ami bilong ol man i ran long hos em 200,000,000. Na mi harim namba bilong ol.',
        17: 'Na olsem tasol mi lukim ol hos long dispela driman samting, na ol husat i sindaun antap long ol, taim ol i gat ol klos pait bilong bros bilong paia, na bilong jasint, na ston salfa. Na ol het bilong ol hos i olsem ol het bilong ol laion. Na ausait long ol maus bilong ol paia na smuk na ston salfa i kam.',
        18: 'Long dispela tripela ol i kilim i dai namba tri hap bilong ol man, long paia, na long smuk, na long ston salfa, dispela i kam ausait long ol maus bilong ol.',
        19: 'Long wanem, pawa bilong ol i stap long maus bilong ol, na long ol tel bilong ol. Long wanem, ol tel bilong ol i wankain olsem ol snek, na ol i gat ol het, na wantaim ol ol i givim pen.',
        20: 'Na olgeta arapela man husat ol i no kilim i dai wantaim ol dispela bikpela hevi, yet ol i no tanim bel long ol wok bilong ol han bilong ol, inap long ol i no ken lotuim ol spirit nogut, na ol piksa bilong god giaman gol, na silva, na bras, na ston, na diwai, husat i no inap long lukluk, o harim, o wokabaut.',
        21: 'Na tu ol i no tanim bel long ol pasin bilong ol bilong kilim man i dai, o long ol pasin poisin bilong ol, o long ol pamuk pasin bilong ol, o long ol stil pasin bilong ol.',
    },
    10: {
        1: '¶ Na mi lukim narapela strongpela ensel i kam daun long heven, wantaim klaut i klos bilong em. Na wanpela renbo i stap antap long het bilong em, na pes bilong em i stap samting olsem san, na tupela lek bilong i em olsem ol bikpela pos paia.',
        2: 'Na em i gat long han bilong em wanpela liklik buk i op. Na em i putim han sut fut bilong em antap long biksi, na han kais futbilong em antap long dispela graun.',
        3: 'Na em i singaut wantaim wanpela bikpela nek, olsem taim laion i krai bikpela. Na taim em i bin singaut, sevenpela klaut i pairap i toktok wantaim ol nek bilong ol.',
        4: 'Na taim ol dispela sevenpela klaut i pairap i bin toktok wantaim ol nek bilong ol, mi redi long raitim. Na mi harim wanpela nek i kem long heven i spik long mi, Pasim ol dispela samting dispela sevenpela klaut i pairap i toktok, na no ken raitim ol.',
        5: 'Na dispela ensel mi lukim i sanap antap long biksi na antap long dispela graun i litimapim han bilong em i go long heven,',
        6: 'Na em i wokim strongpela promis long nem bilong em husat i stap laip oltaim oltaim na oltaim, husat i kamapim long nating heven, na ol dispela samting i stap long en, na dispela graun, na ol dispela samting i stap long en, na biksi, na ol dispela samting i stap long en, inap long taim i no ken stap moa.',
        7: 'Tasol long ol de bilong nek bilong namba seven ensel, taim em bai stat long winim biugel, samting hait bilong God i ken pinis, olsem em i bin tokaut long ol wokboi bilong em ol profet.',
        8: '¶ Na dispela nek mi harim long heven i toktok long mi gen, na tok, Go na kisim dispela liklik buk i op long han bilong dispela ensel i sanap antap long biksi na antap long dispela graun.',
        9: 'Na mi go long dispela ensel, na tokim em, Givim mi dispela liklik buk. Na em i tokim mi, Kisim dispela, na kaikai dispela olgeta. Na em bai mekim bel bilong yu i gat pait tru, tasol em bai stap long maus bilong yu switpela olsem hani.',
        10: 'Na mi kisim dispela liklik buk ausait long han bilong ensel, na kaikai dispela olgeta. Na em i stap long maus bilong mi switpela olsem hani. Na long taim stret long mi bin kaikai dispela, bel bilong mi i gat pait tru.',
        11: 'Na em i tokim mi, Yu mas autim tok profet gen long ai bilong planti lain manmeri, na ol kantri, na ol tok ples, na ol king.',
    },
    11: {
        1: '¶ Na wanpela i givim mi wanpela tiktik i wankain olsem wanpela stik. Na ensel i sanap, i spik, Kirap, na mitaim tempel bilong God, na alta, na ol husat i lotu insait long en.',
        2: 'Tasol dispela ples op i stap ausait long tempel lusim, na no ken mitaim dispela. Long wanem, God i givim dispela long ol man i no Ju. Na dispela biktaun holi ol bai krungutim aninit long lek 42 mun.',
        3: '¶ Na mi bai givim pawa long tupela witnes bilong mi, na ol bai autim tok profet 1,260 de, taim ol i werim bek laplap.',
        4: 'Dispela tupela em i dispela tupela diwai oliv, na dispela tupela stik kandel i sanap long ai bilong God bilong dispela graun.',
        5: 'Na sapos wanpela man i gat laik long givim pen long ol, paia i kam ausait long maus bilong ol, na kaikai olgeta ol birua bilong ol. Na sapos wanpela man i gat laik givim pen long ol, long dispela pasin ol i mas kilim em i dai.',
        6: 'Dispela tupela i gat pawa long pasim heven, inap long em i no inap ren long ol de bilong tok profet bilong ol. Na ol bai gat pawa long bosim ol wara long tanim ol i kamap blut, na long paitim dispela graun wantaim olgeta bikpela hevi, hamas taim ol i gat laik.',
        7: 'Na taim ol i bin pinisim testimoni bilong ol, dispela animal husat i kam antap ausait long bikpela hul i no gat as bilong en bai wokim bikpela pait i birua long ol, na bai winim ol, na kilim tupela i dai.',
        8: 'Na tupela dai bodi bilong ol bai slip long rot bilong dispela bikpela biktaun, dispela long spirit sait ol i kolim Sodom na Isip, we tu ol i bin nilim long diwai kros Bikpela bilong yumi.',
        9: 'Na ol bilong ol lain manmeri na ol kandre na ol tok ples na ol kantri bai lukim ol dai bodi bilong ol tripela de na hap, na ol bai i no inap larim ol i putim ol dai bodi bilong ol insait long ol matmat.',
        10: 'Na ol husat i stap long dispela graun bai wokim amamas tru antap long ol, na wokim amamas, na ol bai salim ol presen wanpela i go long narapela. Bilong wanem, dispela tupela profet i givim traipela pen long ol husat i stap long dispela graun.',
        11: 'Na bihain long tripela de na hap, Spirit bilong laip i kam long God i go insait long ol, na ol i sanap antap long ol lek bilong ol. Na bikpela pret i pundaun antap long ol husat i lukim ol.',
        12: 'Na ol i harim wanpela bikpela nek i kam long heven i spik long ol, Kam antap hia. Na ol i go antap long heven insait long wanpela klaut. Na ol birua bilong ol i lukim ol.',
        13: 'Na dispela aua stret i gat wanpela bikpela guria, na namba ten hap bilong dispela biktaun i pundaun, na dispela guria i kilim i dai 7,000 man. Na hap lain i stap yet i pret, na givim glori long God bilong heven.',
        14: '¶ Namba tu tok lukaut i pinis. Na, lukim, namba tri tok lukaut i kam kwiktaim.',
        15: 'Na namba seven ensel i winim biugel. Na i gat ol bikpela nek long heven, i spik, Ol kingdom bilong dispela graun i kamap ol kingdom bilong Bikpela bilong yumi, na bilong Kraist bilong em. Na em bai bosim kingdom oltaim oltaim na oltaim.',
        16: 'Na dispela 24 lapun hetman, husat i sindaun long ai bilong God long ol sia bilong ol, i pundaun long ol pes bilong ol, na lotuim God,',
        17: 'I spik, Mipela i givim tok tenkyu long yu, O God Bikpela i Gat Olgeta Strong, husat i stap, na husat i bin stap, na husat bai kam. Bilong wanem, yu bin kisim long yu dispela bikpela pawa bilong yu, na yu bin bosim kingdom.',
        18: 'Na ol kantri i belhat, na belhat tru bilong yu i kam pinis, na taim bilong ol daiman, inap long ol i ken kisim kot, na long yu ken givim pe long ol wokboi bilong yu ol profet, na long ol seint, na ol husat i pret long nem bilong yu, man nating na bikman, na long yu ken bagarapim olgeta ol husat i bagarapim dispela graun olgeta.',
        19: 'Na tempel bilong God i op long heven, na ol i lukim insait long tempel bilong em bokis kontrak bilong testamen bilong em. Na i gat ol lait bilong klaut, na ol nek, na ol klaut i pairap, na wanpela guria, na bikpela ren ais.',
    },
    12: {
        1: '¶ Na i gat i kamap ples klia wanpela bikpela samting bilong winim tingting long heven. Wanpela meri i werim san olsem klos, na mun i stap aninit long tupela lek bilong em, na antap long het bilong em i gat hat kwin i gat twelpela sta.',
        2: 'Na taim em i gat bel em i singaut, taim em i hatwok long karim pikinini, na i gat pen long taim bilong karim.',
        3: 'Na i gat narapela samting bilong winim tingting i kamap ples klia long heven. Na lukim, wanpela bikpela retpela dregon, na em i gat sevenpela het na tenpela kom, na sevenpela hat king antap long ol het bilong em.',
        4: 'Na tel bilong em i pulim namba tri hap bilong ol sta bilong heven, na em i bin tromoi ol i go daun long dispela graun. Na dispela dregon i sanap long ai bilong dispela meri husat i redi long karim, long wanem, bilong kaikai pikinini bilong em olgeta long taim stret long em i karim em.',
        5: 'Na em i karim wanpela man pikinini, husat i bilong bosim olgeta kantri wantaim wanpela stik ain. Na ol i kisim pikinini bilong dispela meri i go antap long ples bilong God na long sia king bilong em.',
        6: 'Na dispela meri i ranawe i go long ples i no gat man, we em i gat wanpela ples God i redim, inap long ol i ken givim kaikai long em long dispela hap 1,260 de.',
        7: 'Na i gat bikpela pait long heven. Maikel na ol ensel bilong em i pait birua long dispela dregon. Na dispela dregon i pait na ol ensel bilong em,',
        8: 'Na ol i no win. Na tu ol i no gat ples bilong ol moa liklik long heven.',
        9: 'Na dispela bikpela dregon ol i tromoi i go ausait, dispela snek bilong bipo, husat ol i kolim Spirit Nogut, na Seten, husat i bin giamanim dispela graun olgeta. Ol i tromoi em ausait i go long dispela graun, na ol ensel bilong em ol i tromoi i go ausait wantaim em.',
        10: 'Na mi harim wanpela bikpela nek i spik long heven, Nau pasin bilong kisim bek i kam, na strong, na kingdom bilong God bilong yumi, na pawa bilong Kraist bilong em. Long wanem, ol i tromoi i go daun dispela man bilong sutim tok long ol brata bilong yumi, husat i bin sutim tok long ol long ai bilong God bilong yumi san na nait.',
        11: 'Na ol i winim em long blut bilong Pikinini Sipsip, na long tok bilong testimoni bilong ol. Na ol i no laikim tru ol laip bilong ol i go inap long dai.',
        12: '¶ Olsem na wokim amamas tru, yupela ol heven, na yupela husat i stap long ol. Tok lukaut i go long ol lain i stap long dispela graun na long biksi! Long wanem, Seten i kam daun long yupela, na em i gat bikpela belhat tru, bilong wanem, em i save long em i gat liklik taim tasol.',
        13: 'Na taim dispela dregon i luksave long ol i tromoi em long dispela graun, em i givim hevi long dispela meri husat i karim dispela man pikinini.',
        14: 'Na long dispela meri God i givim tupela wing olsem wanpela bikpela igal, inap long em i ken flai i go long ples i no gat man, i go long ples bilong em, we ol bai givim kaikai long em long wanpela taim, na ol taim, na wanpela namba tu hap taim, i lusim pes bilong dispela snek.',
        15: 'Na dispela snek i tromoi wara ausait long maus bilong em olsem wanpela tait i bihainim dispela meri, inap long em i ken mekim tait long karim em i go.',
        16: 'Na dispela graun i helpim dispela meri, na graun i opim maus bilong em, na daunim dispela tait dispela dregon i tromoi ausait long maus bilong em.',
        17: 'Na dregon i belhat tru long meri, na em i go long wokim bikpela pait wantaim hap lain i stap yet bilong tumbuna pikinini bilong em, husat i holimpas ol tok strong bilong God, na husat i gat testimoni bilong Jisas Kraist.',
    },
    13: {
        1: '¶ Na mi sanap antap long wesan bilong biksi, na lukim wanpela animal i kirap ausait long biksi, na em i gat sevenpela het na tenpela kom, na antap long ol kom bilong em tenpela hat king, na antap long ol het bilong em dispela nem bilong tok bilas.',
        2: 'Na dispela animal husat mi lukim i wankain olsem wanpela lepat, na ol fut bilong em i olsem ol fut bilong bea, na maus bilong em i olsem maus bilong laion. Na dispela dregon i givim em pawa bilong em, na sia bilong em, na bikpela namba bilong bosim.',
        3: 'Na mi lukim wanpela bilong ol het bilong em i samting olsem em kisim bagarap inap long i dai. Na dispela bagarap inap long i dai bilong em i kamap orait gen. Na olgeta manmeri bilong dispela graun i tingting planti long dispela animal.',
        4: 'Na ol i lotuim dispela dregon husat i givim pawa long dispela animal. Na ol i lotuim dispela animal, i spik, Husat i wankain olsem dispela animal? Husat em inap long wokim bikpela pait wantaim em?',
        5: 'Na dregon i givim em wanpela maus i toktok long ol bikpela samting na ol tok bilas. Na em i givim em pawa long stap yet 42 mun.',
        6: 'Na em i opim maus bilong em long tok bilas i birua long God, long tok bilas long nem bilong em, na haus holi bilong em, na ol husat i stap long heven.',
        7: 'Na dregon i givim em pawa long wokim bikpela pait wantaim ol seint, na long winim ol. Na dregon i givim em pawa long winim olgeta kandre, na ol tok ples, na ol kantri.',
        8: 'Na olgeta husat i stap antap long dispela graun bai lotuim em, husat God i no raitim nem bilong ol insait long buk bilong laip bilong Pikinini Sipsip ol i kilim i dai long stat bilong ol as ston bilong dispela graun.',
        9: 'Sapos wanpela man i gat ia, larim em harim.',
        10: 'Em husat i stiaim ol lain i go long kalabus bai go long kalabus. Em husat i kilim i dai man wantaim bainat ol i mas kilim wantaim bainat. Dispela em i pasin bilong sanap strong long traim na bilip tru bilong ol seint.',
        11: '¶ Na mi lukim narapela animal i kam antap ausait long dispela graun. Na em i gat tupela kom olsem wanpela pikinini sipsip, na em i toktok olsem wanpela dregon.',
        12: 'Na em i yusim olgeta pawa bilong dispela namba wan animal i kam bipo long em, na mekim dispela graun na ol husat i stap insait long en long lotuim namba wan animal, husat i bin kamap orait gen long bagarap inap long i dai bilong em.',
        13: 'Na em i wokim ol bikpela samting bilong winim tingting, inap long em i mekim paia i kam daun long heven antap long dispela graun long hap ai bilong ol man i lukim.',
        14: 'Na em i giamanim ol husat i stap long dispela graun long wok bilong ol dispela mirakel, dispela em i gat pawa long wokim long hap ai bilong dispela animal i lukim, taim em i spik long ol husat i stap long dispela graun, long ol i mas wokim wanpela piksa long dispela animal, dispela i bin gat bagarap i kam long bainat, na em i no bin dai.',
        15: 'Na em i gat pawa long givim laip long dispela piksa bilong dispela animal, inap long dispela piksa bilong dispela animal i ken toktok, na mekim long hamas man i no gat laik long lotuim piksa bilong dispela animal ol i mas kilim ol i dai wantaim.',
        16: 'Na em i mekim olgeta, man nating na bikman, maniman na rabisman, friman na slevman wantaim, long kisim wanpela mak long han sut bilong ol, o long ol poret bilong ol,',
        17: 'Na long i no gat wanpela man i ken baim o salim samting, em tasol husat i gat dispela mak i ken, o nem bilong dispela animal, o namba bilong nem bilong em.',
        18: 'Dispela em i save tru. Larim em husat i gat gutpela save kaunim namba bilong dispela animal. Long wanem, em i namba bilong wanpela man. Na namba bilong em em 666.',
    },
    14: {
        1: '¶ Na mi lukluk, na, harim, wanpela Pikinini Sipsip i sanap antap long maunten Saion, na wantaim em 144,000, husat ol i raitim nem bilong Papa bilong em antap long ol poret bilong ol.',
        2: 'Na mi harim wanpela nek i kam long heven, olsem nek bilong planti wara, na olsem nek bilong wanpela bikpela klaut i pairap. Na mi harim nek bilong ol man bilong paitim harp i pilai wantaim ol harp bilong ol.',
        3: 'Na ol i singim samting olsem wanpela nupela song long ai bilong sia king, na long ai bilong dispela fopela animal, na ol lapun hetman. Na i no gat man i ken lainim dispela singsing, dispela 144,000 tasol, husat God i baim bek long dispela graun.',
        4: 'Ol dispela em ol husat i no kamap doti pinis wantaim ol meri. Long wanem, ol i ol man i no bin slip wantaim meri. Ol dispela em i ol husat i bihainim Pikinini Sipsip long wanem hap we em i go. Ol dispela God i baim bek namel long ol man, taim ol i stap ol namba wan kaikai i go long God na long Pikinini Sipsip.',
        5: 'Na ol man i no lukim gris tingting insait long maus bilong ol. Long wanem, ol i no gat asua long ai bilong sia king bilong God.',
        6: '¶ Na mi lukim narapela ensel i flai insait long namel bilong heven, taim em i gat gutnius bilong oltaim oltaim long autim tok i go long ol husat i stap long dispela graun, na long olgeta wan wan kantri, na ol kandre, na ol tok ples, na ol lain manmeri,',
        7: 'I spik wantaim wanpela bikpela nek, Pret long God, na givim glori long em. Long wanem, aua bilong kot bilong em i kamap pinis. Na lotuim em husat i wokim heven, na dispela graun, na biksi, na ol ai bilong wara i sut.',
        8: 'Na narapela ensel i kam bihain, i spik, Babilon i pundaun pinis, i pundaun pinis, dispela bikpela biktaun, bilong wanem, em i mekim olgeta kantri dring long wain bilong belhat tru bilong pamuk pasin bilong em.',
        9: 'Na namba tri ensel i bihainim ol, i spik wantaim wanpela bikpela nek, Sapos wanpela man i lotuim dispela animal na piksa bilong em, na kisim mak bilong em long poret bilong em, o long han bilong em,',
        10: 'Em stret bai dring long wain bilong belhat tru bilong God, dispela i no gat samting em i abusim wantaim i go long kap bilong bel nogut bilong em. Na em bai kisim traipela pen wantaim paia na ston salfa long pes bilong ol ensel holi, na long pes bilong Pikinini Sipsip.',
        11: 'Na smuk bilong traipela pen bilong ol bai go antap oltaim oltaim na oltaim. Na ol bai i no inap gat malolo san o nait, husat i lotuim dispela animal na piksa bilong em, na husat man i kisim mak bilong nem bilong em.',
        12: 'Dispela em i pasin bilong sanap strong long traim bilong ol seint. Dispela em ol husat i holimpas ol tok strong bilong God, na bilip tru bilong Jisas.',
        13: '¶ Na mi harim wanpela nek i kam long heven i spik long mi, Raitim, Blesing i stap long ol daiman husat i dai insait long Bikpela i stat long nau i go. Yes, Spirit i tok, inap long ol i ken malolo long ol hatwok bilong ol. Na ol wok bilong ol i bihainim ol.',
        14: 'Na mi lukluk, na lukim, wanpela waitpela klaut, na antap long klaut wanpela i sindaun i wankain olsem Pikinini Man bilong man, na em i gat wanpela hat king gol antap long het bilong em, na wanpela sarip i sap long han bilong em.',
        15: 'Na narapela ensel i kam ausait long tempel, taim em i singaut wantaim bikpela nek long em husat i sindaun antap long klaut, Sutim sarip bilong yu i go insait, na kamautim kaikai. Long wanem, taim i kamap pinis long yu long kamautim kaikai. Long wanem, kaikai bilong kamautim bilong dispela graun i mau pinis.',
        16: 'Na em husat i sindaun long dispela klaut i sutim sarip bilong em i go insait long dispela graun, na kamautim kaikai long dispela graun.',
        17: 'Na narapela ensel i kam ausait long dispela tempel i stap long heven, taim em tu i gat wanpela sarip i sap.',
        18: 'Na narapela ensel i kam ausait long alta, husat i gat pawa long bosim paia. Na em i singaut wantaim bikpela singaut long em husat i gat dispela sarip i sap, i spik, Sutim sarip bilong yu i sap i go insait, na bungim ol lain bung bilong diwai wain bilong dispela graun. Long wanem, ol pikinini wain bilong en i mau olgeta.',
        19: 'Na dispela ensel i sutim sarip bilong em i go insait long dispela graun, na bungim diwai wain bilong dispela graun, na tromoi dispela i go long dispela bikpela masin bilong krungutim wain bilong belhat tru bilong God.',
        20: 'Na masin bilong krungutim wain ol i krungutim ausait long biktaun, na blut i kam ausait long masin bilong krungutim wain, yes, i go antap long ol baklain bilong stiaim bilong hos, long spes bilong 1,600 furlong.',
    },
    15: {
        1: '¶ Na mi lukim narapela mak long heven, bikpela na i wok long mekim ol man tingting planti, sevenpela ensel husat i gat dispela las sevenpela bikpela hevi. Long wanem, insait long ol i pulap long belhat tru bilong God.',
        2: 'Na mi lukim samting olsem wanpela biksi bilong glas ol i abusim wantaim paia. Na ol husat i bin winim pait long winim dispela animal, na long winim piksa bilong em, na long winim mak bilong em, na long winim namba bilong nem bilong em, i sanap antap long dispela biksi bilong glas, taim ol i gat ol harp bilong God.',
        3: 'Na ol i singim song bilong Moses, wokboi bilong God, na song bilong Pikinini Sipsip, i spik, Ol wok bilong yu i bikpela na i wok long mekim ol man tingting planti, God Bikpela i Gat Olgeta Strong. Stretpela na tru em ol rot bilong yu, yu King bilong ol seint.',
        4: 'Husat bai i no inap pret long yu, O Bikpela, na givim glori long nem bilong yu? Long wanem, yu tasol i stap holi. Long wanem, olgeta kantri bai kam na lotu long ai bilong yu. Long wanem, ol kot bilong yu i kamap ples klia.',
        5: '¶ Na bihain long dispela mi lukluk, na, lukim, tempel bilong haus holi bilong testimoni long heven i op.',
        6: 'Na dispela sevenpela ensel i kam ausait long tempel, taim ol i gat dispela sevenpela bikpela hevi, na werim ol naispela laplap i klin na waitpela, na ol bros bilong ol i pas nabaut wantaim ol bikpela let gol.',
        7: 'Na wanpela bilong dispela fopela animal i givim i go long dispela sevenpela ensel sevenpela dis gol i pulap wantaim belhat tru bilong God, husat i stap laip oltaim oltaim na oltaim.',
        8: 'Na tempel i pulap wantaim smuk i kam long glori bilong God, na long pawa bilong em. Na i no gat man husat em inap long go insait long tempel, inap long dispela sevenpela bikpela hevi bilong dispela sevenpela ensel i kamap pinis.',
    },
    16: {
        1: '¶ Na mi harim wanpela bikpela nek i kam ausait long tempel i spik long dispela sevenpela ensel, Go long ol rot bilong yupela, na kapsaitim ol dis bilong belhat tru bilong God antap long dispela graun.',
        2: 'Na namba wan i go, na kapsaitim dis bilong em long dispela graun. Na i gat wanpela sua i karim sik na i givim pen i pundaun antap long ol man husat i gat mak bilong dispela animal, na antap long ol husat lotuim piksa bilong em.',
        3: 'Na namba tu ensel i kapsaitim dis bilong em antap long biksi. Na em i kamap olsem blut bilong wanpela daiman. Na olgeta wan wan tewel i stap laip insait long biksi i dai.',
        4: 'Na namba tri ensel i kapsaitim dis bilong em antap long ol riva na ol ai bilong wara i sut. Na ol i kamap blut.',
        5: 'Na mi harim ensel bilong ol wara i spik, Yu stap stretpela, O Bikpela, husat i stap, na husat i bin stap, na husat bai stap, bilong wanem, yu bin jasim olsem.',
        6: 'Long wanem, ol i bin kapsaitim blut bilong ol seint na ol profet, na yu bin givim ol blut long dringim. Long wanem, ol i gat namba inap.',
        7: 'Na mi harim narapela ausait long alta i spik, Yes, olsem tasol, God Bikpela i Gat Olgeta Strong, tru na stretpela em ol kot bilong yu.',
        8: '¶ Na namba foa ensel i kapsaitim dis bilong em antap long san. Na God i givim pawa long em long kukim ol man wantaim paia.',
        9: 'Na ol man i kuk wantaim bikpela hat, na ol i tok bilas long nem bilong God, husat i gat pawa long bosim ol dispela bikpela hevi. Na ol i no tanim bel, long givim em glori.',
        10: 'Na namba faiv ensel i kapsaitim dis bilong em antap long sia bilong dispela animal. Na kingdom bilong em i pulap long tudak. Na ol i kaikaim ol tang bilong ol bikos pen i traipela.',
        11: 'Na ol i tok bilas long God bilong heven, bilong tingim ol pen bilong ol na ol sua bilong ol, na ol i no tanim bel long ol pasin bilong ol.',
        12: '¶ Na namba sikis ensel i kapsaitim dis bilong em antap long dispela bikpela wara Yufretis. Na wara bilong en i go drai olgeta, inap long em i ken redim rot bilong ol king bilong hap is.',
        13: 'Na mi lukim tripela spirit i no klin, olsem ol rokrok, i kam ausait long maus bilong dispela dregon, na ausait long maus bilong dispela animal, na ausait long maus bilong dispela giaman profet.',
        14: 'Long wanem, ol i ol spirit bilong ol spirit nogut, ol i wokim ol mirakel, husat i go long ol king bilong dispela graun na bilong dispela graun olgeta, long bungim ol long pait bilong dispela bikpela de bilong God i Gat Olgeta Strong.',
        15: 'Lukim, mi kam olsem wanpela stilman. Blesing i stap long em husat i was, na lukautim gut ol klos bilong em, nogut em i wokabaut skin nating, na ol i lukim sem bilong em.',
        16: 'Na em i bungim ol wantaim i go long wanpela ples ol i kolim long tok ples Hibru Armagedon.',
        17: '¶ Na namba seven ensel i kapsaitim dis bilong em i go long skai. Na wanpela bikpela nek i kam ausait long tempel bilong heven, i kam long sia king, i spik, em i pinis.',
        18: 'Na i gat ol nek, na ol klaut i pairap, na ol lait bilong klaut. Na i gat wanpela bikpela guria, kain olsem ol man i no lukim long taim man i kam long dispela graun inap long nau, em i strongpela guria olsem, na bikpela olsem.',
        19: 'Na dispela bikpela biktaun i bruk pinis i go long tripela hap, na ol biktaun bilong ol kantri i pundaun. Na bikpela Babilon i kam insait long tingting gen long ai bilong God, long givim long em dispela kap bilong wain bilong strong bilong belhat tru bilong em.',
        20: 'Na olgeta wan wan ailan i ranawe i go, na ol i no lukim ol maunten.',
        21: 'Na bikpela ren ais i pundaun ausait long heven antap long ol man, olgeta wan wan ston i hevi klostu olsem wanpela talen. Na ol man i tok bilas long God, bilong tingim dispela bikpela hevi bilong ren ais. Long wanem, bikpela hevi bilong en i bikpela moa yet.',
    },
    17: {
        1: '¶ Na wanpela bilong dispela sevenpela ensel husat i gat dispela sevenpela dis i kam, na toktok wantaim mi, i spik long mi, Kam hia. Mi bai soim long yu pe bilong kot bilong dispela bikpela pamuk meri husat i sindaun antap long planti wara,',
        2: 'Wantaim husat ol king bilong dispela graun i bin mekim pamuk pasin, na ol lain i stap long dispela graun i bin kamap spak wantaim wain bilong pamuk pasin bilong em.',
        3: 'Olsem na em i karim mi i go long spirit i go long ples i no gat man. Na mi lukim wanpela meri i sindaun antap long wanpela animal i gat kala skalet, i pulap long ol nem bilong tok bilas, na i gat sevenpela het na tenpela kom.',
        4: 'Na dispela meri i putim naispela klos i purpelpela na kala skalet, na em i bilas tru wantaim gol na ol ston i dia tumas na ol kiau bilong golip, taim em i gat wanpela kap gol long han bilong em i pulap long ol sting samting na samting i doti tru bilong ol pamuk pasin bilong em.',
        5: 'Na antap long poret bilong em ol i raitim wanpela nem, SAMTING HAIT, BIKPELA BABILON, MAMA BILONG OL PAMUK MERI NA OL STING SAMTING BILONG DISPELA GRAUN.',
        6: 'Na mi lukim dispela meri i spak wantaim blut bilong ol seint, na wantaim blut bilong ol man bilong Jisas i sanap strong inap long i dai. Na taim mi lukim em, mi tingting planti wantaim bikpela tingim wantaim laikim.',
        7: '¶ Na ensel i tokim mi, Bilong wanem yu bin tingting planti? Mi bai tokim yu long samting hait bilong dispela meri, na bilong dispela animal i karim em, husat i gat sevenpela het na tenpela kom.',
        8: 'Dispela animal husat yu lukim i bin stap, na i no stap. Na em bai kam antap ausait long dispela bikpela hul i no gat as bilong en, na go long bagarap olgeta. Na ol husat i stap long dispela graun bai tingting planti, husat ol nem bilong ol God i no raitim insait long buk bilong laip long stat bilong ol as ston bilong dispela graun, taim ol i lukim dispela animal husat i bin stap, na i no stap, na yet em i stap.',
        9: 'Na hia em dispela tingting i gat save tru. Dispela sevenpela het em sevenpela maunten, long dispela, dispela meri i sindaun.',
        10: 'Na i gat sevenpela king. Faipela i pundaun pinis, na wanpela i stap, na arapela i no kam pinis yet. Na taim em i kam, em i mas stap yet liklik taim.',
        11: 'Na dispela animal husat i bin stap, na i no stap, yes, em i namba et, na em i bilong dispela sevenpela, na em i go long bagarap olgeta.',
        12: 'Na dispela tenpela kom yu lukim em tenpela king, husat i no bin kisim wanpela kingdom yet. Tasol ol i kisim pawa olsem ol king wanpela aua wantaim dispela animal.',
        13: 'Ol dispela i gat wanpela tingting, na ol bai givim pawa na strong bilong ol i go long dispela animal.',
        14: '¶ Ol dispela bai wokim bikpela pait wantaim Pikinini Sipsip, na Pikinini Sipsip bai winim ol. Long wanem, em i Bikpela bilong ol bikpela, na King bilong ol king. Na ol husat i stap wantaim em em i singautim, na makim, na ol i ol man yu inap bilip long ol.',
        15: 'Na em i tokim mi, Ol dispela wara yu lukim, we dispela pamuk meri i sindaun, em ol lain manmeri, na ol bikpela lain tru, na ol kantri, na ol tok ples.',
        16: 'Na dispela tenpela kom yu lukim antap long dispela animal, ol dispela bai i hetim dispela pamuk meri, na ol bai mekim em i stap nating na skin nating, na ol bai kaikai bodi bilong em, na kukim em wantaim paia.',
        17: 'Long wanem, God i bin putim insait long ol bel bilong ol long inapim laik bilong em, na long stap wanbel, na givim kingdom bilong ol long dispela animal, inap long ol toktok bilong God bai kamap pinis.',
        18: 'Na dispela meri yu bin lukim em dispela bikpela biktaun, dispela i bosim kingdom antap long ol king bilong dispela graun.',
    },
    18: {
        1: '¶ Na bihain long ol dispela samting mi lukim narapela ensel i kam daun long heven, taim em i gat bikpela pawa. Na dispela graun i kisim lait wantaim glori bilong em.',
        2: 'Na em i singaut strong wantaim strongpela nek, i spik, Bikpela Babilon i pundaun pinis, i pundaun pinis, na i kamap ples bilong ol spirit nogut, na ples hait bilong olgeta wan wan spirit i paul, na bokis kalabus bilong olgeta wan wan pisin i no klin na ol man i hetim.',
        3: 'Long wanem, olgeta kantri i bin dring pinis long wain bilong belhat tru bilong pamuk pasin bilong em, na ol king bilong dispela graun i bin mekim pamuk pasin wantaim em, na ol bisnisman bilong dispela graun i wok long kamap ol maniman long wok bilong ol naispela samting bilong em i planti moa yet.',
        4: 'Na mi harim narapela nek i kam long heven, i spik, Kam ausait long em, ol lain manmeri bilong mi, inap long yupela i no ken kisim hap insait long ol sin bilong em, na inap long yupela i no kisim hap bilong ol bikpela hevi bilong em.',
        5: 'Long wanem, ol sin bilong em i bin go antap inap long heven, na God i bin holim tingting long ol sin nogut bilong em.',
        6: 'Givim pe long em, yes, olsem em i givim pe long yupela, na dabolim long em dabol bilong bihainim ol wok bilong em. Insait long dispela kap em i bin pulimapim, pulimapim long em dabol.',
        7: 'Hamas em i bin givim glori long em yet, na em i gat switpela laip, long wanmak olsem givim traipela pen na bel hevi long em. Long wanem, em i bin tok long bel bilong em, Mi sindaun wanpela kwin, na mi no meri man bilong em i dai pinis, na mi bai i no inap lukim bel hevi.',
        8: 'Olsem na ol bikpela hevi bilong em bai kam long wanpela de, dai, na soim sori, na bikpela taim hangre. Na ol bai kukim em olgeta wantaim paia. Long wanem, God Bikpela em strong, husat i jasim em.',
        9: '¶ Na ol king bilong dispela graun, husat i bin mekim pamuk pasin na i gat switpela laip wantaim em, bai krai wantaim singaut long em, na krai sori long em, taim ol bai lukim smuk bilong kuk bilong em,',
        10: 'Taim ol i sanap longwe bikos ol i pret long traipela pen bilong em, i spik, Sori tru, sori tru, dispela bikpela biktaun Babilon, dispela strongpela biktaun! Long wanem, long wanpela aua pe bilong kot bilong yu i kam.',
        11: 'Na ol bisnisman bilong dispela graun bai krai tru na soim sori antap long em. Long wanem, i no gat man i baim ol kago bilong ol moa liklik,',
        12: 'Ol kago bilong gol, na silva, na ol ston i dia tumas, na bilong ol kiau bilong golip, na ol laplap i naispela tru, na purpelpela, na silk, na skalet, na olgeta diwai tain, na olgeta kain kain sospen samting bilong aivori, na olgeta kain kain sospen samting bilong ol diwai i dia tumas, na bilong bras, na ain, na marbel,',
        13: 'Na sinamin, na ol smel, na ol wel i gat marasin, na frankinsens, na wain, na wel, na naispela plaua, na wit, na ol animal, na ol sipsip, na ol hos, na ol karis, na ol slev, na ol tewel bilong ol man.',
        14: 'Na ol dispela kaikai tewel bilong yu i aigris long ol i go lusim yu, na olgeta dispela gutpela samting i naispela na nambawan i go lusim yu, na yu bai i no inap lukim ol moa liklik.',
        15: 'Ol bisnisman bilong ol dispela samting, husat i kamap ol maniman long em, bai sanap longwe bikos ol i pret long traipela pen bilong em, na krai tru na krai wantaim singaut,',
        16: 'Na i spik, Sori tru, sori tru, dispela bikpela biktaun, dispela i werim laplap i naispela tru, na purpelpela, na skalet, na bilas tru wantaim gol, na ol ston i dia tumas, na ol kiau bilong golip!',
        17: 'Long wanem, long wanpela aua ol bikpela kain planti mani samting olsem i kamap samting nating. Na olgeta wan wan papa bilong sip, na olgeta lain insait long ol sip, na ol boskru bilong sip, na hamas man i wokim bisnis long biksi, i sanap longwe,',
        18: 'Na singaut taim ol i lukim smuk bilong kuk bilong em, i spik, Wanem biktaun em i wankain olsem dispela bikpela biktaun!',
        19: 'Na ol i tromoi das antap long ol het bilong ol, na krai, krai tru na krai wantaim singaut, i spik, Sori tru, sori tru, dispela bikpela biktaun, we insait long en olgeta husat i gat ol sip long biksi i kamap ol maniman bikos em i gat bikpela pe! Long wanem, long wanpela aua ol i mekim em long stap nating.',
        20: 'Wokim amamas tru antap long em, yu heven, na yupela ol aposel holi na ol profet. Long wanem, God i bin bekim pe nogut long em long tingim yupela.',
        21: 'Na wanpela strongpela ensel i kisim wanpela ston i olsem wanpela bikpela ston bilong krungutim wit, na tromoi dispela i go insait long biksi, i spik, Wantaim wankain pasin pait olsem bai God i tromoi i go daun dispela bikpela biktaun Babilon, na ol bai i no inap lukim em moa liklik.',
        22: 'Na nek bilong ol man bilong pilai long harp, na ol man bilong wokim musik, na bilong ol man bilong winim paip, na ol man bilong winim biugel, bai ol i no inap harim ol moa liklik insait long yu. Na ol man bilong wokim naispela wok bai ol i no inap lukim moa liklik i stap insait long yu, maski wanem kain naispela wok em i wokim. Na nois bilong ston bilong krungutim wit bai ol i no inap harim moa insait long yu liklik.',
        23: 'Na lait bilong kandel bai i no inap lait moa insait long yu liklik. Na nek bilong man i laik marit na meri i laik marit ol bai i no inap harim insait long yu moa liklik. Long wanem, ol bisnisman bilong yu i bin stap ol bikman bilong dispela graun. Long wanem, wantaim ol pasin poisin bilong yu yu bin giamanim olgeta kantri.',
        24: 'Na insait long em ol i lukim blut bilong ol profet, na bilong ol seint, na bilong olgeta husat ol i kilim i dai antap long dispela graun.',
    },
    19: {
        1: '¶ Na bihain long ol dispela samting mi harim wanpela bikpela nek bilong planti manmeri long heven, i spik, Aleluya. Pasin bilong kisim bek, na glori, na ona, na pawa, i go long Bikpela, God bilong yumi.',
        2: 'Long wanem, tru na stretpela em ol kot bilong em. Long wanem, em i bin jasim dispela bikpela pamuk meri, husat i bin bagarapim dispela graun wantaim ol pamuk pasin bilong em, na em i bin bekim pe nogut long tingim blut bilong ol wokboi bilong em long han bilong meri.',
        3: 'Na gen ol i tok, Aleluya. Na smuk bilong meri i kirap i go antap oltaim oltaim na oltaim.',
        4: 'Na dispela 24 lapun hetman na dispela fopela animal i pundaun na lotuim God husat i sindaun long sia king, i spik, Amen. Aleluya.',
        5: '¶ Na wanpela nek i kam ausait long sia king, i spik, Givim biknem long God bilong yumi, olgeta yupela ol wokboi bilong em, na yupela husat i pret long em, man nating na bikman wantaim.',
        6: 'Na mi harim samting olsem nek bilong wanpela traipela lain tru, na olsem nek bilong ol planti wara, na olsem nek bilong planti strongpela klaut i pairap, i spik, Aleluya. Long wanem, God Bikpela i gat olgeta pawa i bosim kingdom.',
        7: 'Larim yumi stap amamas na wokim amamas tru, na givim ona long em. Long wanem, marit bilong Pikinini Sipsip i kam, na meri bilong em i bin mekim em yet redi.',
        8: 'Na long em God i tok orait long em i ken putim naispela klos long naispela laplap, klinpela na waitpela. Long wanem, laplap i naispela tru em i stretpela pasin bilong ol seint.',
        9: 'Na em i tokim mi, Raitim, Blesing i stap long ol husat ol i singautim long marit kaikai bilong Pikinini Sipsip. Na em i tokim mi, Ol dispela em ol trupela toktok bilong God.',
        10: 'Na mi pundaun long tupela lek bilong em long lotuim em. Na em i tokim mi, Lukluk gut long yu no mekim dispela. Mi stap wanwok bilong yu, na bilong ol brata bilong yu husat i gat testimoni bilong Jisas. Lotuim God. Long wanem, testimoni bilong Jisas em i spirit bilong tok profet.',
        11: '¶ Na mi lukim heven i op, na lukim, wanpela waitpela hos, na em husat i sindaun antap long en ol i kolim Man Yu Inap Bilip Long Em na Tru, na long stretpela pasin em i jasim na wokim bikpela pait.',
        12: 'Tupela ai bilong em i olsem lait bilong paia, na antap long het bilong em planti hat king i stap. Na em i gat wanpela nem em i raitim, i no gat man i save long dispela, em em yet tasol.',
        13: 'Na em i werim klos long wanpela naispela klos ol i putim liklik long blut. Na nem bilong em ol i kolim Tok bilong God.',
        14: 'Na ol dispela ami i stap long heven i bihainim em antap long ol waitpela hos, na werim ol laplap i naispela tru, waitpela na klinpela.',
        15: 'Na wanpela bainat i sap i go ausait long maus bilong em, inap long wantaim dispela em i ken paitim ol kantri. Na em bai bosim ol wantaim wanpela stik ain. Na em i krungutim masin bilong krungutim wain bilong strongpela pasin na belhat tru bilong God i Gat Olgeta Strong.',
        16: 'Na em i gat long naispela klos bilong em na long antap bilong lek bilong em wanpela nem ol i raitim, KING BILONG OL KING, NA BIKPELA BILONG OL BIKPELA.',
        17: 'Na mi lukim wanpela ensel i sanap long ai bilong san. Na em i singaut wantaim wanpela bikpela nek, i spik long olgeta pisin husat i flai long namel bilong heven, Kam na bungim yupela yet wantaim i go long kaikai bilong dispela nambawan God.',
        18: 'Inap long yupela i ken kaikai mit bilong ol king, na mit bilong ol kepten, na mit bilong ol strongpela man, na mit bilong ol hos, na bilong ol husat i sindaun antap long ol, na mit bilong olgeta man, friman na slevman wantaim, man nating na bikman wantaim.',
        19: 'Na mi lukim dispela animal, na ol king bilong dispela graun, na ol ami bilong ol, i bung wantaim long wokim bikpela pait i birua long em husat i sindaun antap long hos, na i birua long ami bilong em.',
        20: 'Na ol i kisim dispela animal, na wantaim em dispela giaman profet husat i wokim ol mirakel long ai bilong em, wantaim ol dispela em i bin giamanim ol husat i bin kisim mak bilong dispela animal, na ol husat i lotuim piksa bilong em. Dispela tupela ol i tromoi, taim ol stap laip, i go insait long wanpela raunwara paia i kuk wantaim ston salfa.',
        21: 'Na hap lain i stap yet em i kilim i dai wantaim bainat bilong em husat i sindaun antap long hos, dispela bainat i kam ausait long maus bilong em. Na olgeta pisin i pulap wantaim mit bilong ol.',
    },
    20: {
        1: '¶ Na mi lukim wanpela ensel i kam daun long heven, taim em i gat ki bilong bikpela hul i no gat as bilong en na wanpela bikpela sen long han bilong em.',
        2: 'Na em i holimpas dispela dregon, dispela snek bilong bipo, husat em dispela Spirit Nogut, na Seten, na pasim em wan tausen yia.',
        3: 'Na em i tromoi em i go long bikpela hul i no gat as bilong en, na pasim em olgeta, na putim wanpela samting bilong pasim antap long em, inap long em i no ken giamanim ol kantri moa, inap long dispela wan tausen yia i ken kamap pinis. Na bihain long dispela ol i mas lusim em liklik taim.',
        4: 'Na mi lukim ol sia king, na ol i sindaun antap long ol, na God i givim ol pawa bilong jasim. Na mi lukim ol tewel bilong ol husat ol i bin rausim ol het bilong ol bilong tingim witnes bilong Jisas, na bilong tingim tok bilong God, na husat i no bin lotuim dispela animal, o piksa bilong em, na tu ol i no bin kisim mak bilong em antap long ol poret bilong ol, o insait long ol han bilong ol. Na ol stap laip na bosim kingdom wantaim Kraist wan tausen yia.',
        5: 'Tasol olgeta arapela daiman i no kisim laip gen inap long dispela wan tausen yia i pinis. Dispela em i namba wan kirap bek.',
        6: 'Blesing na pasin holi i stap long em husat i gat hap insait long namba wan kirap bek. Long kain man olsem namba tu dai i no gat pawa, tasol ol bai stap ol pris bilong God na bilong Kraist, na ol bai bosim kingdom wantaim em wan tausen yia.',
        7: 'Na taim dispela wan tausen yia i pinis, ol bai lusim Seten ausait long kalabus bilong em,',
        8: 'Na em bai go ausait long giamanim ol kantri husat i stap long fopela namba foa hap bilong dispela graun, Gok na Megok, long bungim ol wantaim long pait, namba bilong husat i olsem wesan bilong biksi.',
        9: 'Na ol i go antap long brait bilong dispela graun, na raunim kem bilong ol seint raun nabaut, na dispela biktaun i stap klostu long bel bilong God. Na paia i kam daun long God ausait long heven, na kaikai ol olgeta.',
        10: 'Na Seten husat i giamanim ol ol i tromoi i go long raunwara paia na ston salfa, we dispela animal na dispela giaman profet i stap, na ol bai gat traipela pen san na nait oltaim oltaim na oltaim.',
        11: '¶ Na mi lukim wanpela bikpela waitpela sia king, na em husat i sindaun antap long en, long pes bilong husat dispela graun na heven i ranawe i go. Na i no gat ples bilong ol long stap.',
        12: 'Na mi lukim ol daiman, man nating na bikman, i sanap long ai bilong God. Na ol i opim ol buk. Na ol i opim narapela buk, dispela em i buk bilong laip. Na em i jasim ol daiman ausait long ol dispela samting, dispela ol i bin raitim insait long ol buk, bilong bihainim ol wok bilong ol.',
        13: 'Na biksi i givim bek ol daiman husat i stap insait long en. Na dai na hel i givim bek ol daiman husat i stap insait long ol. Na em i jasim olgeta wan wan man bilong bihainim ol wok bilong ol.',
        14: 'Na dai na hel ol i tromoi i go insait long raunwara paia. Dispela em i namba tu dai.',
        15: 'Na husat man ol i no lukim long God i raitim insait long buk bilong laip ol i tromoi i go long raunwara paia.',
    },
    21: {
        1: '¶ Na mi lukim wanpela nupela heven na wanpela nupela graun. Long wanem, namba wan heven na namba wan graun i pinis olgeta. Na i no gat biksi moa.',
        2: 'Na mi Jon mi lukim dispela biktaun holi, nupela Jerusalem, i kam daun long God ausait long heven, i redi olsem meri i laik marit i bilas gut tru long amamasim man bilong em.',
        3: 'Na mi harim wanpela bikpela nek ausait long heven i spik, Lukim, haus holi bilong God i stap wantaim ol man, na em bai stap wantaim ol, na ol bai stap lain manmeri bilong em, na God em yet bai stap wantaim ol, na stap God bilong ol.',
        4: 'Na God bai rausim i go olgeta aiwara long ol ai bilong ol. Na bai i no gat dai moa, o bel hevi, o krai, na tu bai i no gat pen moa liklik. Long wanem, ol samting bilong bipo i pinis olgeta',
        5: 'Na em husat i sindaun antap long sia king i tok, Lukim, mi mekim olgeta samting nupela. Na em i tokim mi, Raitim. Long wanem, ol dispela toktok i tru na samting yu inap bilip long ol.',
        6: 'Na em i tokim mi, Em i pinis. Mi stap Alpa na Omega, stat na pinis. Mi bai givim fri long em husat i nekdrai long ai bilong wara i sut bilong laip.',
        7: 'Em husat i winim bai kisim olgeta samting olsem samting papa i givim pikinini. Na mi bai stap God bilong em, na em bai stap pikinini man bilong mi.',
        8: 'Tasol ol man i pulap long pret, na ol man i no gat bilip, na ol man i gat sting pasin, na ol man bilong kilim man i dai, na ol pamuk man, na ol poisin man, na ol man bilong lotuim piksa bilong god giaman, na olgeta man bilong giaman, bai gat hap bilong ol long dispela raunwara i kuk wantaim paia na ston salfa. Dispela em i namba tu dai.',
        9: '¶ Na i gat i kam long mi wanpela bilong dispela sevenpela ensel husat i bin gat dispela sevenpela dis i pulap long dispela las sevenpela bikpela hevi, na em i toktok wantaim mi, i spik, Kam hia, mi bai soim yu meri i laik marit, meri bilong Pikinini Sipsip.',
        10: 'Na em i karim mi i go long spirit long wanpela maunten i bikpela na i antap, na soim mi dispela bikpela biktaun, holi Jerusalem, i kam daun long God ausait long heven,',
        11: 'Taim em i gat glori bilong God. Na lait bilong en i wankain olsem wanpela ston i dia tumas, yes, olsem wanpela ston jaspa, klia olsem kristal.',
        12: 'Na em i gat wanpela banis i bikpela na i antap, na em i gat twelpela dua bilong banis, na long ol dua bilong banis twelpela ensel, na i gat ol nem ol i raitim antap long ol, dispela em ol nem bilong dispela twelpela lain bilong ol pikinini bilong Isrel.',
        13: 'Long hap is tripela dua bilong banis. Long hap not tripela dua bilong banis. Long hap saut tripela dua bilong banis. Na long hap wes tripela dua bilong banis.',
        14: 'Na banis bilong dispela biktaun i gat twelpela as ston, na insait long ol em ol nem bilong dispela twelpela aposel bilong Pikinini Sipsip.',
        15: 'Na em husat i toktok wantaim mi i gat wanpela tiktik gol long mitaim dispela biktaun, na ol dua bilong banis bilong en, na banis bilong en.',
        16: 'Na biktaun i slip skwea stret, na longpela bilong en em i traipela olsem brait. Na em i mitaim dispela biktaun wantaim dispela tiktik, 12,000 furlong. Na longpela na brait na antap bilong en i wanmak stret.',
        17: 'Na em i mitaim banis bilong en, 144 kyubit, bilong bihainim skel bilong wanpela man, em i olsem, bilong dispela ensel.',
        18: 'Na ol i wokim banis bilong en long jaspa. Na dispela biktaun em i gol i klin, wankain olsem glas i klia.',
        19: 'Na ol as ston bilong banis bilong dispela biktaun ol i bilasim wantaim olgeta kain kain ston i dia tumas. Namba wan as ston em i jaspa, namba tu, sapaia, namba tri, wanpela kalsedoni, namba foa, wanpela emeral,',
        20: 'Namba faiv, sardoniks, namba sikis, sardias, namba seven, krisolait, namba et, beril, namba nain, topas, namba ten, krisopresas, namba eleven, jasint, namba twelv, wanpela ametis.',
        21: 'Na twelpela dua bilong banis i twelpela kiau bilong golip. Olgeta wan wan dua bilong banis em yet em bilong wanpela kiau bilong golip. Na rot bilong biktaun em i gol i klin, samting olsem glas i klia tru.',
        22: 'Na mi no lukim tempel insait long en. Long wanem, God Bikpela i Gat Olgeta Strong na Pikinini Sipsip ol i tempel bilong en.',
        23: 'Na dispela biktaun i no gat nid long san, o long mun, long lait insait long en. Long wanem, glori bilong God i bin givim lait long en, na Pikinini Sipsip em i lait bilong en.',
        24: 'Na ol kantri bilong ol husat God i kisim bek pinis bai wokabaut long lait bilong en. Na ol king bilong dispela graun i bringim glori na ona bilong ol i go insait long en.',
        25: 'Na ol dua bilong banis bilong en ol bai i no inap pasim liklik long san. Long wanem, bai i no gat nait long dispela hap.',
        26: 'Na ol bai bringim glori na ona bilong ol kantri i go insait long en.',
        27: 'Na bai i no gat olgeta, bilong go insait long en, wanpela samting i inap long mekim doti, o wanem samting i wokim sting pasin, o wokim giaman. Tasol ol husat God i raitim insait long buk bilong laip bilong Pikinini Sipsip bai go insait.',
    },
    22: {
        1: '¶ Na em i soim mi wanpela riva i klin bilong wara bilong laip, klia olsem kristal, i kam ausait long sia king bilong God na bilong Pikinini Sipsip.',
        2: 'Long namel bilong rot bilong en, na long tupela sait wantaim bilong riva, i gat diwai bilong laip, dispela i karim twelpela kain prut, na givim prut bilong en olgeta wan wan mun. Na ol lip bilong diwai em bilong oraitim sik bilong ol kantri.',
        3: 'Na bai i no gat tok nogut moa. Tasol sia king bilong God na bilong Pikinini Sipsip bai stap insait long en. Na ol wokboi bilong em bai wokim wok wokboi long em.',
        4: 'Na ol bai lukim pes bilong em. Na nem bilong em bai stap long ol poret bilong ol.',
        5: 'Na bai i no gat nait long dispela hap. Na ol i no gat nid long kandel, o lait bilong san. Long wanem, God Bikpela i givim ol lait. Na ol bai bosim kingdom oltaim oltaim na oltaim.',
        6: '¶ Na em i tokim mi, Ol dispela toktok em i samting yu inap bilip long ol na i tru. Na God Bikpela bilong ol profet holi i salim ensel bilong em long soim ol wokboi bilong em ol dispela samting i mas kamap klostu nau.',
        7: 'Lukim, mi kam kwiktaim. Blesing i stap long em husat i holimpas ol toktok bilong tok profet bilong dispela buk.',
        8: 'Na mi Jon mi lukim ol dispela samting, na harim ol. Na taim mi bin harim na lukim, mi pundaun long lotu long ai bilong tupela lek bilong dispela ensel i soim mi ol dispela samting.',
        9: 'Nau em i tokim mi, Lukluk gut long yu no mekim dispela. Long wanem, mi stap wanwok bilong yu, na bilong ol brata bilong yu ol profet, na bilong ol husat i holimpas ol toktok bilong dispela buk. Lotuim God.',
        10: 'Na em i tokim mi, No ken pasim ol toktok bilong tok profet bilong dispela buk. Long wanem, taim i laik kam klostu.',
        11: 'Em husat i no stretpela, larim em i no stap stretpela yet. Na em husat i doti tru, larim em stap doti tru yet. Na em husat i stretpela, larim em stap stretpela yet. Na em husat i holi, larim em stap holi yet.',
        12: 'Na, lukim, mi kam kwiktaim. Na pe bilong mi i stap wantaim mi, long givim olgeta wan wan man bilong bihainim olsem wok bilong em bai stap.',
        13: 'Mi stap Alpa na Omega, stat na pinis, namba wan na las.',
        14: 'Blesing i stap long ol husat i mekim ol tok strong bilong em, inap long ol i ken gat rait long kisim long diwai bilong laip, na ol i ken go insait long ol dua bilong banis long go insait long dispela biktaun.',
        15: 'Long wanem, ausait ol dok i stap, na ol poisin man, na ol pamuk man, na ol man bilong kilim man i dai, na ol man bilong lotuim ol piksa bilong god giaman, na husat man i laikim tru tok giaman na em i wokim.',
        16: 'Mi Jisas i bin salim ensel bilong mi long tokaut klia long yu long ol dispela samting insait long ol sios. Mi stap rop daunbilo na pikinini i kamaut long Devit, na dispela sta i lait tru bilong moning.',
        17: 'Na Spirit na meri i laik marit i tok, Kam. Na larim em husat i harim i ken tok, Kam. Na larim em husat i nekdrai kam. Na husat man i gat laik, larim em kisim fri long wara bilong laip.',
        18: 'Long wanem, mi tokaut klia long olgeta wan wan man husat i harim ol toktok bilong tok profet bilong dispela buk, Sapos wanpela man bai skruim tok long ol dispela samting, God bai skruim long em ol dispela bikpela hevi em i raitim insait long dispela buk.',
        19: 'Na sapos wanpela man bai tekewe long ol toktok bilong buk bilong dispela tok profet, God bai tekewe hap bilong em ausait long buk bilong laip, na ausait long dispela biktaun holi, na long ol dispela samting ol i raitim insait long dispela buk.',
        20: '¶ Em husat i tokaut klia long ol dispela samting i tok, Tru tumas, mi kam kwiktaim. Amen. Yes, olsem tasol, kam, Bikpela Jisas.',
        21: 'Marimari bilong Bikpela bilong yumi Jisas Kraist i ken stap wantaim yupela olgeta. Amen.',
    },
}
