NAME = 'FinPR: Finnish Pyhä Raamattu (1933/1938)'
BOOK = 'Tobit'

CHAPTERS = {
    1: {
        1: 'Tämä on kertomus Toobitista, Toobielin pojasta, joka oli Hananielin poika, joka Aduelin poika, joka Gabaelin poika, Asielin suvusta, Naftalin sukukunnasta.',
        2: 'Hänet oli Assurin kuninkaan Enemessarin päivinä viety pois vankina Tisbestä, joka oli etelään Kydioksesta Naftalissa, Galileassa, Asserin yläpuolella.',
        3: 'Minä, Toobit, vaelsin totuuden teillä ja vanhurskaudessa kaiken elinaikani. Ja minä annoin runsaasti almuja veljilleni ja kansalaisilleni, joiden oli täytynyt lähteä kanssani assyrialaisten maahan, Niiniveen',
        4: 'Minun nuoruudessani, ollessani kotiseudullani Israelin maassa, oli minun kantaisäni Naftalin koko sukukunta luopunut Jerusalemin temppelistä, sen kaupungin, joka oli valittu kaikista israelin sukukunnista, että kaikki heimot siellä uhraisivat; ja se temppeli, Korkeimman asumus, oli pyhitetty ja rakennettu ikuisiksi ajoiksi.',
        5: 'Ja kaikki sukukunnat, jotka olivat mukana luopumuksessa, uhrasivat Baalin vasikalle, niin myös minun kantaisäni Naftalin huonee.',
        6: 'Minä yksin vaelsin usein Jerusalemiin juhlina, niinkuuin on määrätty koko Israelille ikuisella säädöksellä, ja vein mukanani uutiset ja kymmenykset maantuotteista ja esikoiset villoista',
        7: 'ja annoin ne papeille, Aaronin pojille, alttaria varten; kymmenykset maan tuotteista minä annoin Leevin pojille, jotka tekevät palvelusta Jerusalemissa; ja toisen kymmenyksen minä myin ja menin Jerusalemiin ja käytin sen siellä joka vuosi.',
        8: 'Ja kolmannen kymmenyksen minä annoin niille, joille se kuuluu, niinkuin Debora, minun isäni äiti, oli käskenyt minun tehdä; sillä minä olin jäänyt isästäni orvoksi.',
        9: 'Sittenkuin minä olin tullut mieheksi, minä otin vaimokseni Hannan, joka kuului meidän omaan sukuumme, ja hän synnytti minulle Tobiaan.',
        10: 'Kun meidät oli viety vankeina Niiniveen, söivät kaikki minun veljeni ja kansalaiseni pakanain ruokia.',
        11: 'Mutta minä varoin niitä syömästä,',
        12: 'sillä minä ajattelin Jumalaa kaikesta sydämestäni.',
        13: 'Ja korkein antoi minun näyttää sorealta ja kauniilta Enemessarin silmissä, ja minä sain tehdä hänelle ostoksia.',
        14: 'Niin minä tein matkan Meediaan ja jätin säilytettäväksi kymmenen talenttia hopeaa Gabaelille, Gabriaan veljelle, Meedian Rageksessa.',
        15: 'Ja Enemessarin kuoltua tuli hänen poikansa Sennakerim kuninkaaksi hänen jälkeensä. Hänen aikanaan olivat tiet epävarmat, niin etten minä enää voinut matkustaa Meediaan.',
        16: 'Jo Enemessarin päivinä minä annoin runsaasti almuja veljilleni:',
        17: 'leipääni minä annoin isoaville ja vaatteitani alastomille. Ja jos näin jonkun kansalaiseni kuolleen ja viskatun Niiniven muurin taakse, niin minä hautasin hänet.',
        18: 'Ja jos kuningas Sennakerim, palattuaan pakolaisena Juudeasta, surmautti jonkin, niin minä salaa hautasin hänet. Sillä hän surmautti monta kiivaudessansa; ja jos kuningas etsi heidän ruumiitaan, ei niitä löydetty.',
        19: 'Mutta muuan Niiniveen asukas meni ja ilmiantoi kuninkaalle, että minä niitä hautasin; silloin minä lymysin. Ja kun sain tietää, että minua etsittiin tapettavaksi, niin minä peljästyin ja lähdin pois.',
        20: 'Ja kaikki minun omaisuuteni ryöstettiin, eikä minulle jätetty mitään paitsi minun vaimoni Hanna ja minun poikani Tobias.',
        21: 'Mutta ei ollut kulunut viittäkymmentä päivää, ennenkuin hänet murhasi kaksi hänen poikaansa, jotka pakenivat Araratin vuorille. Ja hänen poikansa Sakerdon tuli kuninkaaksi hänen jälkeensä, ja hän asetti Akiakarin, Hanaelin pojan, minun veljenpoikani, valtakuntansa kaikkien rahavarain hoitajaksi ja koko hallinnon johtajaksi.',
        22: 'Ja Akiakar rukoili minun puolestani, ja niin minä sain palata Niiniveen. Akiakar oli juomanlaskija ja sinetinvartija, valtiokansleri ja rahavarainhoitaja; ja Sakerdon oli asettanut hänet lähimmäksi mieheksensä. Ja hän oli minun veljenpoikani.',
    },
    2: {
        1: 'Kun minä olin palannut jälleen kotiini ja saanut takaisin vaimoni Hannan ja poikani Tobiaan, niin minä helluntaijuhlana, joka on seitsemän viikon pyhä, valmistin juhlapöydän ja asetuin aterialle.',
        2: 'Nähdessäni nyt paljot ruuat minä sanoin pojalleni: »mene, ja jos löydät veljiemme joukosta jonkun köyhän, joka ajattelee Herraa, niin tuo hänet tänne; katso, minä odotan sinua.»',
        3: 'Ja hän tuli takaisin ja sanoi: »Isäni, muuan kansalaisemme on kuristettu ja viruu torilla».',
        4: 'Ja ennenkuin olin mitään nauttinut, minä nousin kiiruusti ja korjasin hänet suojaan, kunnes aurinko laskisi.',
        5: 'Sitten minä palasin takaisin ja peseydyin ja söin leipäni murheessa.',
        6: 'Ja mieleeni johtui Aamoksen ennustus, kuinka hän sanoi: »Teidän juhlanne muuttuvat murheeksi ja kaikki teidän iloitsemisenne valitusvirreksi».',
        7: 'Ja minä purskahdin itkuun. Kun aurinko sitten oli laskenut, niin minä menin ja kaivoin haudan ja hautasin hänet.',
        8: 'Muta naapurit pilkkasivat minua ja sanoivat: »Nyt hän ei enää pelkää, että hänet tapettaisiin tämän teon tähden; hänen oli pakko paeta, ja katso, nyt hän taas hautaa kuolleita!»',
        9: 'Samana yönä minä palasin takaisin toimitettuani hautauksen. Ja koska olin tullut saastaiseksi, minä paneuduin nukkumaan pihan muurin viereen, ja kasvoni olivat peittämättömät.',
        10: 'Mutta minä en tietänyt, että muurissa oli varpusia. Ja silmieni ollessa auki laskivat varpuset lämmintä likaa minun silmiini; ja silloin tuli silmiini valkeita pilkkuja, ja minä menin lääkäriin, mutta lääkärit eivät voineet minua auttaa. Mutta Akiakar elätti minua, kunnes hän meni Elymaikseen.',
        11: 'Ja vaimoni Hanna teki palkasta naisten töitä.',
        12: 'ja lähetti ne sitten työnantajilla, ja nämä maksoivat hänelle palkan ja antoivat lisäksi vohlan.',
        13: 'Mutta kun hän tuli minun tyköni, niin se alkoi määkiä. Silloin minä kysyin häneltä: »Mistä on tämä vohla? Eihän se vain ole varastettu? Anna se takaisin sen omistajille, sillä ei ole luvallista syödä varastettua.»',
        14: 'Hän vastasi:»Se on annettu minulle lahjaksi, palkkani lisäksi». Mutta minä en uskonut häntä, vaan käskin antaa sen omistajille takaisin, ja minä vihastuin häneen. Silloin hän vastasi ja sanoi minulle: »Missä ovat nyt sinun almusi ja vanhurskaat tekosi? Katso, nyt sen tietää, millainen sinä olet.»',
    },
    3: {
        1: 'Silloin minä tulin murheelliseksi ja purskahdin itkuun; ja minä rukoilin tuskassani ja sanoin:',
        2: '»Herra, sinä olet vanhurskas, ja kaikki sinun tekosi ja kaikki sinun tiesi ovat laupeus ja totuus; sinä tuomitset aina oikean ja vanhurskaan tuomion.',
        3: 'Muista minua ja katso minun puoleeni. Älä rankaise minua syntieni mukaan, joita isäni ovat tehneet sinun edessäsi.',
        4: 'Sillä he olivat tottelemattomat sinun käskyillesi; ja niin sinä annoit meidät alttiiksi ryöstölle, vankeudelle ja kuolemalle ja sallit meidän tulla pilkaksi ja sananparreksi kaikille pakanakansoille, joiden keskuuteen me olemme hajotetut.',
        5: 'Niin ovat nyt sinun monet tuomiosi oikeat, kun sinä teet minulle minun ja isieni syntien mukaan, koska emme ole pitäneet sinun käskyjäsi; sillä me emme ole vaeltaneet totuudessa sinun edessäsi.',
        6: 'Tee nyt minulle, niinkuin sinulle on otollista. Käske ottaa pois minun henkeni, että minä saisin täältä erota ja tulla maaksi, sillä minulle on parempi kuolla kuin elää, koska minun on täytynyt kuulla valheellisia parjauksia. Minä olen suuren murheen vallassa. Käske, että jo nyt saisin päästä ahdistuksesta ja mennä iankaikkiseen asuntoon. Älä käännä minusta pois kasvojasi.»',
        7: 'Tapahtui niin, että samana päivänä myös Raguelin tytär Saara Meedian Ekbatanassa sai kuulla herjauksia isänsä palvelusnaisilta.',
        8: 'Sillä hänet oli annettu seitsemälle miehelle, mutta paha henki, Asmodeus, oli tappanut heidät, ennenkuin he olivat yhtyneet häneen. Ja naiset sanoivat hänelle: »Oletko mieletön, kun surmaat miehesi? Sinulla on jo ollut seitsemän miestä, mutta sinua ei ole kutsuttu niistä yhdenkään nimen mukaan.',
        9: 'Miksi lyöt meitä? Jos he kuolivat, niin mene heidän perässänsä. Älköön meidän ikinä tarvitko nähdä sinun poikaasi tai tytärtäsi.»',
        10: 'Kun hän tämän kuuli, tuli hän niin kovin murheelliseksi, että hän tahtoi hirttäytyä. Mutta hän sanoi: »Minä olen isäni ainoa lapsi. Jos minä sen teen, niin hänelle tulee häpeä, ja minä saatan hänen harmaat hapsensa vaipumaan murheella tuonelaan.»',
        11: 'Ja hän rukoili ikkunan edessä ja sanoi: »Ole kiitetty sinä, Herra, minun Jumalani, ja olkoon kiitetty sinun pyhä ja kunnioitettu nimesi iankaikkisesti. Kiittäkööt sinua kaikki sinun tekosi ainiaan.',
        12: 'Ja nyt, Herra, minä käännän silmäni ja kasvoni sinun puoleesi.',
        13: 'Käske minun erota tämän maan päältä, ettei minun enää tarvitsisi kuulla herjausta.',
        14: 'Sinä tiedät, Herra, että minä olen puhdas kaikesta miehen kanssa tehdystä synnistä,',
        15: 'ja etten ole saastuttanut nimeäni enkä isäni nimeä siinä maassa, jossa minä elän vankina. Minä olen isäni ainoa lapsi, eikä hänellä ole muuta lasta, joka hänet perisi, eikä muuta läheistä omaista tai tämän poikaa, jolle minun pitäisi säilyttää itseni vaimoksi. Minulta on jo kuollut seitsemän miestä; mitä varten minä vielä eläisin? Mutta jos sinä et näe hyväksi surmata minua, niin käske, että saan kokea laupeutta ja armoa, ettei minun enää tarvitse kuulla herjausta.»',
        16: 'Ja molempien rukous tuli kuulluksi Jumalan kirkkauden edessä.',
        17: 'Ja Raafael lähetettiin parantamaan heidät molemmat: ottamaan pois Toobitin silmistä valkeat pilkut ja antamaan Saara, Raguelin tytär, vaimoksi Tobiaalle, Toobitin pojalle, koska Tobiaalla oli sukuoikeus saada hänet vaimoksi, sekä kahlehtimaan paha henki Asmodeus. Samaan aikaan palasi Toobit takaisin ja meni taloonsa, ja Saara, Raguelin tytär, astui alas yliskammiostansa.',
    },
    4: {
        1: 'Sinä päivänä muistui Toobitin mieleen rahat, jotka hän oli tallettanut Gabaelin haltuun Meedian Rageksessa.',
        2: 'Ja hän sanoi itsekseen: »Minä olen pyytänyt saada kuolla;miksi en kutsu luokseni poikaani Tobiasta, ilmaistakseni asian hänelle, ennenkuin kuolen?»',
        3: 'Ja hän kutsui hänet ja sanoi: »Poikani, kun minä olen kuollut, niin hautaa minut ja pidä huoli äidistäsi. Kunnioita häntä kaikkina elämäsi päivinä ja tee sitä, mikä hänelle on mieleen, äläkä tuota hänelle murhetta.',
        4: 'Muista, poikani, että hän on nähnyt monta vaaraa sinun tähtesi, kun hän kantoi sinua kohdussansa. Ja kun hän on kuollut, hautaa hänet minun viereeni samaan hautaan.',
        5: 'Ajattele, poikani, joka päivä Herraa, meidän Jumalaamme, äläkä ole altis tekemään syntiä ja rikkomaan hänen käskyjänsä. Harjoita vanhurskautta kaikkina elämäsi päivinä, äläkä vaella vääryyden teillä.',
        6: 'Sillä jos sinä teet totuuden, niin on sinulla oleva menestys töissäsi.',
        7: 'Anna almuja omaisuudestasi kaikille, jotka harjoittavat vanhurskautta, ja kun almuja annat, älköön sinun silmäsi olko karsas. Älä käännä kasvojasi pois kenestäkään köyhästä, ja niin ei Jumalakaan käännä sinusta pois kasvojansa.',
        8: 'Jos sinulla on paljon, niin anna paljon almuja paljostasi; jos sinulla on vähän, niin älä arkaile antaa almuja vähästäsi.',
        9: 'Niin sinä keräät itsellesi hyvän aarteen hädän päiväksi.',
        10: 'Sillä almut pelastavat kuolemasta eivätkä salli joutua pimeyteen.',
        11: 'Almut ovat hyvä uhrilahja Korkeimman edessä kaikkien niitä antavien hyväksi.',
        12: 'Kavahda, poikani, kaikkinaista haureutta; ja ennen kaikkea: ota vaimo isiesi suvusta. Älä ota avioksi vierasta naista, joka ei ole isiesi sukukuntaa, sillä me olemme profeettain poikia. Ajattele, poikani, kuinka Nooa, Aabraham, Iisak ja Jaakob, meidän isämme muinaisilta päiviltä, ottivat kaikki itselleen vaimot sukulaisistansa; he saivat siunauksen lapsissansa, ja heidän jälkeläisensä saavat periä maan.',
        13: 'Ja nyt, poikani, rakasta veljiäsi äläkä ylpisty sydämmessäsi, niin että halveksut veljiäsi ja kansasi poikia ja tyttäriä etkä ota itsellesi heistä vaimoa. Sillä ylpeydestä tulee turmio ja paljon onnettomuutta, kelvottomasta elämästä köyhyys ja suuri puute. Sillä kelvoton elämä on nälän äiti.',
        14: 'Älä pidätä yön ylitse palkkaa keneltäkään, joka on sinun työssäsi, vaan maksa se hänelle kohta. Jos sinä palvelet Jumalaa, niin se sinulle korvataan, Poikani, ota vaari itsestäsi kaikissa teoissasi, ja käyttäydy soveliaasti kaikessa vaelluksessasi.',
        15: 'Mitä itse vihaat, sitä älä tee kenellekkään muulle. Älä juo viiniä päihtymykseen asti, älköönkä päihtymys vaeltako sinun kanssasi tiellä.',
        16: 'Anna leipääsi nälkäiselle ja vaatteitasi alastomille. Kaikesta, mitä sinulla on yltäkyllin, anna almuja, älköönkä sinun silmäsi olko karsas almuja antaessasi.',
        17: 'Anna runsaasti leipääsi vanhurskasten hautajaisiin, mutta syntisille älä anna.',
        18: 'Etsi neuvoa kaikilta ymmärtäväisiltä, äläkä mitään hyödyllistä neuvoa halveksu.',
        19: 'Kiitä aina Herraa Jumalaa ja pyydä häneltä, että tiesi olisivat tasaiset ja kaikki polkusi ja neuvosi onnelliset. Sillä ihmiset ovat kaikki neuvottomia, mutta Herra itse antaa kaiken hyvän; ja kenen hän tahtoo, sen hän alentaa, niinkuin hyväksi näkee. Nyt siis, poikani, muista minun käskyjäni, älköötkä ne hävitkö sinun sydämmestäsi.',
        20: 'Tahdon nyt kertoa sinulle niistä kymmenestä hopeatalentista, jotka minä talletin Gabaelin, Gabriaan veljen, haltuun Meedian Rageksessa.',
        21: 'Älä pelkää, poikani, vaikka me olemme köyhtyneet; sinulla on paljon, jos pelkäät Jumalaa ja pysyt erilläsi kaikkinaisesta synnistä ja teet sitä, mikä on otollista hänen edessänsä.»',
    },
    5: {
        1: 'Ja Tobias vastasi hänelle:»Isäni, minä teen kaiken, mitä olet käskenyt minun tehdä.',
        2: 'Mutta kuinka voin saada rahat, kun minä en tunne sitä miestä?»',
        3: 'Silloin hän antoi hänelle talletuskirjan ja sanoi hänelle: »Etsi itsellesi joku, joka matkustaa kanssasi; minä annan hänelle palkan, niin kauan kuin vielä elän. Lähde sitten matkalle ja hae rahat.»',
        4: 'Ja hän lähti etsimään sellaista miestä ja löysi Raafaelin, joka oli enkeli, vaikka Tobias ei sitä tiennyt.',
        5: 'ja sanoi hänelle: »Voinko matkustaa sinun kanssasi Meedian Ragekseen ja tunnetko ne seudut?»',
        6: 'Enkeli sanoi hänelle: »Matkustan mielelläni sinun kanssasi, minä tunnen tien ja olen majaillut veljemme Gabaelin tykönä.»',
        7: 'Tobias sanoi hänelle: »Odota minua, minä ilmoitan sen isälleni».',
        8: 'Hän vastasi: »Mene, mutta älä viivy kauan».',
        9: 'Ja hän meni isänsä tykö ja sanoi hänelle: »Katso, minä olen löytänyt erään, joka tahtoo matkustaa kanssani». Isä sanoi: »Kutsu hänet luokseni, että saisin tietää, mistä sukukunnasta hän on ja onko hän luotettava matkatoveriksesi».',
        10: 'Silloin hän kutsui hänet, ja hän astui sisään, ja he tervehtivät toisiaan.',
        11: 'Ja Toobit sanoi hänelle: »Mistä sukukunnasta ja mistä perheestä sinä olet, veljeni? Ilmoita se minulle.»',
        12: 'Hän vastasi: »Etsitkö heimoa ja sukua vai palkkalaista, joka matkustaisi poikasi kanssa?» Toobit sanoi hänelle: »Tahtoisin, veljeni, tietää sukusi ja nimesi».',
        13: 'Hän vastasi: »Minä olen Asarias, suuren Ananiaan poika, sinun veljiäsi».',
        14: 'Silloi Toobit sanoi hänelle: »Ole tervetullut, veljeni; älä ole siitä minulle vihoissasi, että koetin saada tietää sukukuntasi ja perheesi. Satutkin olemaan, veljeni, hyvää ja jaloa sukua. Sillä minä opin tuntemaan Ananiaan ja Joonatanin, suure Semeaan pojat, kun yhdessä matkustimme Jerusalemiin siellä kumartaen rukoilemaan ja uhraamaan uutiset ja kymmenykset kylvön sadosta; he eivät olleet hairahtuneet samaan eksytykseen kuin muut veljemme. Olet hyvää juurta, veljeni.',
        15: 'Mutta sano minulle, mikä palkka minun tulee sinulle antaa? Ehkä drakma päivää kohti ja mitä muutoin on tarpeen itseäsi ja poikaani varten?',
        16: 'Ja palkan lisäksi minä annan sinulle vielä lahjan, jos tulette terveinä takaisin.»',
        17: 'Näin he sopivatkin. Ja isä sanoi Tobiaalle: »Valmistaudu matkalle, ja olkoon matkanne onnellinen». Kun poika oli varustautunut matkalle, sanoi isä hänelle: »Lähde tämän miehen kanssa. Mutta Jumala, joka asuu taivaassa, antakoon teidän matkanne onnistua, ja hänen enkelinsä seuratkoon teitä.» Sitten he molemmat menivät ulos lähteäkseen matkalle, ja nuorukaisen koira lähti mukaan.',
        18: 'Mutta hänen äitinsä Hanna alkoi itkeä ja sanoi Toobitille: »Miksi olet lähettänyt pois poikamme? Eikö hän ole kuin sauva kädessämme, kun hän joka päivä tulee ja menee silmäimme edessä.',
        19: 'Älköön raha tuljo rahan lisäksi, vaan olkoon se poikamme hengen lunastusraha.',
        20: 'Sillä minkä Herra on antanut meille siitä elääkseemme, se meille riittää.»',
        21: 'Mutta Toobit sanoi hänelle: »Älä ole huolissasi, sisareni. Hän on palaava terveenä takaisin, ja sinun silmäsi saavat nähdä hänet jälleen.',
        22: 'Sillä hyvä enkeli on saattava häntä, ja hänen matkansa on onnistuva, ja hän palaava terveenä takaisin.»',
    },
    6: {
        1: 'Silloin hän taukosi itkemästä.',
        2: 'He kulkivat nyt tietä ja tulivat illalla Tigris-virran rannalle ja yöpyivät siihen.',
        3: 'Ja nuorukainen astui veteen kylpemään. Silloin hyppäsi kala ylös virrasta ja aikoi niellä nuorukaisen.',
        4: 'Mutta enkeli sanoi hänelle: »Tartu kiinni kalaan». Silloin nuorukainen tarttui kalaan ja viskasi sen maalle.',
        5: 'Ja enkeli sanoi hänelle: »Leikkaa kala auki ja ota sydän, maksa ja sappi ja säilytä ne huolellisesti.»',
        6: 'Ja nuorukainen teki, niinkuin enkeli oli hähelle sanonut; mutta kalan he paistoivat ja söivät. Sitten molemmat kulkivat eteenpäin, kunnes tulivat Ekbatanan läheisyyteen.',
        7: 'Silloin sanoi nuorukainen enkelille: »Asarias, veljeni, mitä varten meillä on sen kalan maksa, sydän ja sappi?»',
        8: 'Hän vastasi hänelle: »Sydäntä ja maksaa on, jos jotakin ihmistä vaivaa riivaaja tai paha henki, savustettava sen ihmisen, miehen tai vaimon, edessä, ja niin vaiva lakkaa.',
        9: 'Sapella taas on voideltava sitä, jonka silmissä on valkoisia pilkkuja, ja niin hän paranee.»',
        10: 'Kun he lähestyivät Ragesta,',
        11: 'sanoi enkeli nuorukaiselle: »Veljeni, tänään me jäämme yöksi Raguelin tykö; hän on sinun sukulaisesi, ja hänellä on Saara niminen tytär.',
        12: 'Minä puhun isälle hänestä, että hän antaa hänet sinulle vaimoksi, sillä sinulle kuuluu hänen perintönsä; sinähän olet ainoa mies hänen sukuansa. Tyttö on myös kaunis ja ymmärtäväinen.',
        13: 'Kuule siis minua, minä puhuttelen hänen isäänsä, ja kun me palaamme Rageksesta, vietämme häät. Sillä minä tiedän, että Raguel Mooseksen lain mukaan ei voi antaa häntä kenellekkään muulle miehelle tulematta kuolemaan vikapääksi; sillä sinulla on oikeus ennen ketään muuta miestä saada perintö.»',
        14: 'Silloin nuorukainen sanoi enkelille: »Asarias, veljeni, minä olen kuullut, että tyttö on annettu seitsemälle miehelle, mutta että kaikki ovat kuolleet, morsiuskammiossa.',
        15: 'Ja minä olen isäni ainoa poika, ja minä pelkään, että kun menen hänen tykönsä, niin minä kuolen niinkuin nuo edellisetkin. Sillä häntä rakastaa paha henki, ja se ei tee kenellekkään muulle pahaa kuin niille, jotka häntä lähestyvät. Sentähden minä pelkään, että minäkin kuolen ja niin saatan isäni ja äitini vaipumaan hautaan minua murehtien; eikä heillä ole toista poikaa, joka heidät hautaisi.»',
        16: 'Mutta enkeli sanoi hänelle: »Etkö muista käskyä, minkä isäsi sinulle antoi, että sinun tulee ottaa vaimo omasta suvustasi? Ja nyt, kuule minua, veljeni: hän on tuleva sinun vaimoksesi. Älä ole huolissasi pahan hengen tähden, sillä tänä yönä Saara annetaan sinulle vaimoksi.',
        17: 'Kun sinä menet morsiuskammioon, tulee sinun ottaa hehkuvaa suitsutustuhkaa ja panna sen päälle kalan sydäntä ja maksaa ja savustaa sillä.',
        18: 'Kun paha henki tuntee käryn, niin se pakenee eikä enää ikinä tule takaisin. Ja kun sinä sitten tahdot lähestyä vaimoasi, nouskaa molemmat ylös ja huutakaa avuksenne armollista Jumalaa; hän on pelastava teidät ja oleva armollinen. Älä pelkää, sillä hänet on määrätty sinulle alusta alkaen, ja sinä olet pelastava hänet; hän on lähtevä sinun kanssasi, ja minä luulen, että sinä saat hänestä lapsia.» Kun Tobias tämän kuuli, syttyi hänessä rakkaus Saaraan, ja hänen sydämensä kiihtyi suuresti.',
    },
    7: {
        1: 'Ja niin he tulivat Ekbatanaan, ja kun he saapuivat Raguelin taloon, tuli Saara heitä vastaan ja tervehti heitä ja he häntä. Ja hän vei heidät kotiinsa.',
        2: 'Ja Raguel sanoi vaimolleen Ednalle: »Kuinka samannäköinen onkaan tämä nuorukainen kuin sisareni poika Toobit!»',
        3: 'Ja Raguel kysyi häneltä: »Mistä olet veljeni?» He vastasivat hänelle: »Me olemme niitä naftalilaisia, jotka elävät pakkosiirtolaisina Niinivessä».',
        4: 'Silloin hän sanoi heille: »Tunnetteko veljemme Toobitin?»',
        5: 'He vastasivat: »Kyllä tunnemme. Hän on elossa ja terveenä.» Ja Tobias lisäsi: »Hän on minun isäni».',
        6: 'Silloin Raguel nousi kiiruusti ylös ja suuteli häntä ja purskahti itkuun.',
        7: 'Ja hän siunasi häntä ja sanoi hänelle: »Sinä olet hyvän ja jalon miehen poika.» Ja kuultuaan, että Toobit oli menettänyt näkönsä, hän tuli murheelliseksi ja itki.',
        8: 'Myös hänen vaimonsa Edna ja hänen tyttärensä Saara itkivät. Ja he ottivat heidät vastaan auliisti. Sitten he teurastivat oinaan ja panivat esille paljon ruokia.',
        9: 'Mutta Tobias sanoi Raafaelille: »Asarias, veljeni, puhu nyt siitä, mistä mainitsit matkalla, että asia saataisiin päätökseen».',
        10: 'Silloin hän ilmoitti asian Raguelille ja Raguel sanoi Tobiaalle: »Syö, juo ja ole iloinen, sillä sinun tulee saada minun tyttäreni; kuitenkin minun on ilmoitettava sinulle totuus.',
        11: 'Olen antanut tyttäreni seitsemälle miehelle, mutta jokainen heistä, niin pian kuin meni hänen tykönsä, kuoli kohta yön tultua. Mutta ole nyt iloinen.» Mutta Tobias sanoi: »En maista täällä mitään, ennenkuin välillämme on tehty laillinen sopimus». Raguel sanoi: »Ota hänet tästä hetkestä, lain mukaan; sinä olet hänen sukulaisensa, ja hän on sinun. Armollinen Jumala antakoon teille ylimmän onnen.»',
        12: 'Sitten hän kutsui tyttärensä Saaran, tarttui hänen käteensä ja antoi hänet Tobiaalle vaimoksi sanoen: »Katso, ota hänet Mooseksen lain mukaan ja vie hänet isäsi tykö». Ja hän siunasi heidät.',
        13: 'Senjälkeen hän kutsui vaimonsa Ednan; ja hän otti lehden ja kirjoitti sille aviosopimuksen ja sinetöitsi sen.',
        14: 'Sitten he rupesivat aterioimaan.',
        15: 'Senjälkeen Raguel kutsui vaimonsa Ednan ja sanoi hänelle: »Sisareni, valmista toinen kammio ja vie Saara sinne».',
        16: 'Vaimo teki, niinkuin hän oli käskenyt, ja vei Saaran sinne; mutta tämä alkoi itkeä. Ja hän hyvin ymmärsi tyttärensä kyyneleet ja sanoi hänelle: »Lapseni, ole turvallisella mielellä. Taivaan ja maan Herra antakoon sinulle ilon tämän murheen sijasta. Ole rohkealla mielellä, tyttäreni.»',
    },
    8: {
        1: 'Kun he olivat aterioineet, veivät he Tobiaan Saaran kammioon.',
        2: 'Mutta kun hänen piti mennä sinne, muisti hän Raafaelin sanat ja otti kuumaa suitsuketuhkaa ja pani sen päälle kalan sydäntä ja maksaa ja savusti sillä.',
        3: 'Kun paha henki tunsi käryn, niin se pakeni hamaan Ylä-Egyptiin asti, ja enkeli sitoi sen.',
        4: 'Mutta kun ovi oli suljettu heidän molempien jälkeen, nousi Tobias ylös vuoteesta ja sanoi: »Nouse ylös, sisareni, ja rukoilkaamme, että Herra armahtaisi meitä».',
        5: 'Ja Tobias alkoi rukoilla ja sanoi: »Ole kiitetty sinä, isiemme Jumala, ja kiitetty olkoon sinun pyhä ja kunnioitettu nimesi iankaikkisesti. Sinua kiittäkööt taivaat ja kaikki sinun luotusi.',
        6: "Sinä loit Aadamin ja annoit hänelle Eevan, hänen vaimonsa, avuksi ja tueksi. Heistä on ihmissuku saanut alkunsa. Sinä sanoit: 'Ei ole ihmisen hyvä olla yksinänsä, tehkäämme hänelle apu, joka on hänen kaltaisensa'.",
        7: 'Ja nyt, Herra: minä en ota tätä sisartani haureellisesta halusta, vaan puhtaasta mielestä. Käske, että saisin armon ja että hänen kanssaan vanhaksi eläisin.»',
        8: 'Ja Saara sanoi hänen kanssaan: »Aamen!»',
        9: 'Ja he nukkuivat molemmat sen yön. Mutta Raguel nousi ylös, meni ja kaivoi haudan.',
        10: 'Sillä hän ajatteli: »Kaiketi tämäkin kuolee.»',
        11: 'Kun Raguel oli tullut takaisin kotiinsa,',
        12: 'sanoi hän vaimolleen Ednalle: »Lähetä yksi palvelusnaisista katsomaan, onko hän hengissä; jollei, niin me hautaamme hänet, eikä kukaan saa siitä mitään tietää».',
        13: 'Kun palvelusnainen avasi oven ja meni sisään, havaitsi hän heidän molempien nukkuvan.',
        14: 'Hän meni silloin ulos ja ilmoitti isäntäväelleen, että ylkä eli.',
        15: 'Silloi Raguel kiitti Jumalaa sanoen: »Ole kiitetty sinä, Jumala, kaikella kiitoksella, ja sinua kiittäkööt sinun pyhäsi ja kaikki sinun luotusi; kaikki sinun enkelisi ja valittusi kiittäkööt sinua iankaikkisesti.',
        16: 'Ole kiitetty, sillä sinä olet valmistanut minulle ilon; minulle ei käynyt niinkuin minä luulin, vaan suuren laupeutesi mukaan sinä tämän meille teit.',
        17: 'Ole kiitetty, sillä sinä olet armahtanut näitä kahta, jotka ovat vanhempansa ainoat lapset; tee heille, Herra, laupeus ja suo heidän elää elämänsä terveydessä, ilossa ja armossa.»',
        18: 'Sitten hän käski palvelijainsa luoda haudan umpeen.',
        19: 'Ja hän laittoi heille häät, jotka kestivät neljätoista päivää.',
        20: 'Mutta ennenkuin hääpäivät olivat loppuun kuluneet, vannotti Raguel häntä, ettei hän saisi lähteä pois, ennenkuin ne neljätoista hääpäivää olivat loppuneet.',
        21: 'Silloin hän oli saava puolet hänen omaisuudestaan ja voisi terveenä mennä takaisin isänsä tykö. Ja hän lisäsi: »Loput saat, kun minä ja vaimoni olemme kuolleet.»',
    },
    9: {
        1: 'Ja Tobias kutsui luoksensa Raafaelin ja sanoi hänelle:',
        2: '»Asarias, veljeni, ota mukaasi palvelija ja kaksi kamelia ja mene Meedian Ragekseen, Gabaelin luo, ja toimita minulle rahat ja tuo myös hänet itsensä häihin.',
        3: 'Sillä Raguel on vannonut, etten saa lähteä täältä,',
        4: 'ja isäni lukee päivät, niin että hän käy kovin levottomaksi, jos minä viivyn kauan.»',
        5: 'Silloin Raafael lähti matkalle, ja hän yöpyi Gabaelin luo ja antoi hänelle talletuskirjan. Tämä taas toi esiin sinetöidyt kukkarot ja antoi ne hänelle.',
        6: 'Ja varhain aamulla he lähtivät yhdessä matkalle ja tulivat häihin. Ja Tobias ylisti vaimoansa.',
    },
    10: {
        1: 'Mutta hänen isänsä Toobit luki jokaisen kuluvan päivän. Ja kun matkaan tarvittavat päivät olivat kuluneet umpeen eikä häntä kuulunut kotiin,',
        2: 'niin Toobit sanoi: »Kenties ei heitä ole otettu vastaan? Tai on Gabael ehkä kuollut, niin ettei kukaan anna hänelle rahoja?»',
        3: 'Ja hän oli kovin murheissaan.',
        4: 'Mutta hänen vaimonsa sanoi hänelle: »Poika on joutunut tuhon omaksi, koska hän viipyy niin kauan». Ja hän alkoi itkeä häntä ja sanoi:',
        5: '»Kuinka minua surettaakaan, lapseni, että päästin sinut, silmieni valon, menemään!»',
        6: 'Mutta Toobit sanoi hänelle: »Ole vaiti; älä ole huolissasi, hän on terveenä».',
        7: 'Vaimo vastasi hänelle: »Ole vaiti! Älä minua petä! Minun lapseni on joutunut tuhon omaksi.» Ja joka päivä hän meni tielle, jota pitkin poika oli lähtenyt matkalle; päivällä hän ei syönyt mitään, ja yökaudet hän itki lakkaamatta poikaansa Tobiasta, kunnes ne neljätoista hääpäivää, joiden ajaksi Raguel oli vannottanut hänet jäämään sinne, olivat loppuun kuluneet. Mutta Tobias sanoi Raguelille: »Päästä minut menemään, sillä isäni ja äitini eivät enää toivo näkevänsä minua».',
        8: 'Silloin hänen appensa vastasi hänelle: »Jää tänne luokseni; minä lähetän sinun isällesi tiedon voinnistasi».',
        9: 'Tobias sanoi: »Päästä minut isäni tykö».',
        10: 'Ja Raguel nousi ja antoi hänelle hänen vaimonsa Saaran ja puolet omaisuudesta: orjia, karjaa ja rahaa.',
        11: 'Sitten hän siunasi heidät ja lähetti heidät matkalle sanoen: »Taivaan Jumala suokoon teille onnea, lapseni, ennenkuin minä kuolen».',
        12: 'Ja tyttärelleen hän sanoi: »Kunnioita appivanhempiasi; he ovat nyt sinun vanhempasi. Toivon kuulevani sinusta hyvää.» Ja hän suuteli häntä. Ja Edna sanoi Tobiaalle: »Rakas veljeni, vieköön taivaan Jumala sinut kotiin ja suokoon minun nähdä sinulla lapsia tyttärestäni Saarasta, että minä saisin riemuita Herran edessä. Katso, minä uskon tyttäreni sinun huomaasi; älä tuota hänelle murhetta.»',
    },
    11: {
        1: 'Senjälkeen Tobias lähti matkalle, ja hän kiitti Jumalaa siitä, että hän oli tehnyt hänen matkansa onnelliseksi. Ja hän sanoi jäähyväiset Raguelille ja hänen vaimolleen Ednalle. Sitten hän kulki eteenpäin, kunnes saapui Niinivee läheisyyteen.',
        2: 'SilloinRaafael sanoi Tobiaalle: »Etkö tiedä, veljeni, kuinka oli isäsi laita lähtiessäsi hänen luotansa?',
        3: 'Kiiruhtakaamme vaimosi edellä ja laittakaamme talo järjestykseen.',
        4: 'Ja ota kalan sappi käteesi.» Sitten he lähtivät matkalle, ja koira seurasi heitä.',
        5: 'Mutta hHanna istui ja katsoi tietä pitkin nähdäkseen poikansa.',
        6: 'Ja kun hän huomasi hänen tulevan, sanoi hän hänen isälleen: »Katso, poikani tulee ja mies, joka lähti hänen kanssaan».',
        7: 'Ja Raafael sanoi: »Minä tiedän, että isäsi tulee avaamaan silmänsä.',
        8: 'Voitele sapella hänen silmänsä; kun hän tuntee kirvelyä, niin hän hieroo niitä, ja valkeat pilkut putoavat pois, ja hän näkee sinut.»',
        9: 'Mutta Hanna kiiruhti heitä vastaan ja lankesi poikansa kaulaan ja sanoi hänelle: »Minä olen nähnyt sinut, lapseni, nyt tahtoisin kuolla». Ja he molemmat purskahtivat itkuun.',
        10: 'Silloin Toobit meni ovelle ja oli loukata itsensä. Mutta poika riensi häntä vastaan,',
        11: 'tarttui isäänsä ja siveli sapella isänsä silmiä sanoen: »Ole turvallisella mielellä, isä».',
        12: 'Kun nyt silmiä alkoi kirvellä, hieroi hän niitä.',
        13: 'Silloin lähtivät hänen silmistään valkoiset pilkut, ja hän näki poikansa ja lankesi hänen kaulaansa',
        14: 'ja purskahti itkuun ja sanoi: »Ylistettävä olet sinä, Jumala, ylistettävä sinun nimesi iankaikkisesti, ja ylistettävät kaikki sinun pyhät enkelisi.',
        15: 'Sillä sinä olet kurittanut minua, mutta olet nyt minua armahtanut. Katso, minä näen poikani Tobiaan.» Silloin hänen poikansa meni riemuiten huoneeseen; ja hän kertoi isälleen, mitä suurta ja ihmeellistä hänelle oli tapahtunut Meediassa.',
        16: 'Senjälkeen Toobit meni ulos kohtaamaan miniänsä Niiniveen portille; ja hän iloitsi ja kiitti Jumalaa. Ja ne, jotka näkivät hänen käyvän, ihmettelivät sitä, että hän oli saanut näkönsä.',
        17: 'Mutta Toobit tunnusti heidän edessään, että Jumala oli armahtanut häntä. Ja kun Toobit lähesty miniäänsä Saaraa, tervehti hän häntä sanoen: »Ole tervetullut, tyttäreni; ylistetty olkoon Jumala, joka on tuonnut sinnut meidän tykömme, niin olkoot myös isäsi ja äitisi». Ja kaiken hänen veljiensä keskuudessa Niinivessä oli ilo.',
        18: 'Myös Akiakar ja hänen veljensä poika Nasbas saapuivat häihin. Ja Tobiaan häitä vietettiin ilon vallitessa seitsemän päivää.',
    },
    12: {
        1: 'Ja Toobit kutsui luokseen poikansa Tobiaan ja sanoi hänelle: »Katso, poikani, että mies, joka oli sinun matkakumppanisi, saa palkkansa; hänen tulee saada vähän lisääkin».',
        2: 'Hän vastasi: »Isä, minä voin vahingoitta antaa hänelle puolet siitä, mitä olen tuonut mukanani.',
        3: 'Sillä hän on tuonut minut terveenä sinun tykösi, on parantanut minun vaimoni, tuonut minun rahani ja samoin parantanut sinut.»',
        4: 'Silloin vanhus sanoi: »Sen hän on ansainnut».',
        5: 'Sitten hän kutsui tykönsä enkelin ja sanoi hänelle: »Ota puolet kaikesta, minkä olette mukananne tuoneet».',
        6: 'Mutta tämä kutsui heidät molemmat syrjään ja sanoi heille: »Ylistäkää Jumalaa ja kiittäkää häntä; antakaa hänelle kunnia ja kiittäkää häntä kaikkien elävien olentojen edessä siitä, mitä hän on teille tehnyt. Hyvä on ylistää Jumalaa ja korottaa hänen nimeänsä ja kunnioittaen julistaa Jumalan tekoja. Älkää olko hitaat häntä kiittämään.',
        7: 'On hyvä pitää salassa kuninkaan salaisuus, mutta saattaa julki, kunniaan, Jumalan teot. Tehkää sitä, mikä hyvä on, niin paha ei teitä kohtaa.',
        8: 'Hyvä on rukous yhdessä paaston, almujenannon ja vanhurskauden kanssa. Parempi vähäisen vanhurskaudella kuin paljon vääryydellä. Parempi antaa almuja kuin kerätä kulta-aarteita.',
        9: 'Almut pelastavat kuolemasta ja puhdistavat kaikesta synnistä. Jotka almuja antavat ja vanhurskautta harjoittavat, ne saavat kauan elää,',
        10: 'mutta synnintekijät ovat oman elämänsä vihollisia.',
        11: 'En tahdo teiltä mitään salata. Minähän sanoin, että on hyvä pitää salassa kuninkaan salaisuus, mutta saattaa julki, kunniaan, Jumalan teot.',
        12: 'Niinpä siis: kun sinä rukoilit ja niin myös sinun miniäsi Saara, niin minä vein teidän rukouksenne Pyhän eteen, että hän ne muistaisi; ja kun sinä hautasit kuolleita, niin minä samoin olin sinun rinnallasi.',
        13: 'Ja kun sinä viivyttelemättä nousit ylös ja jätit ateriasi mennäksesi hautaamaan kuolleen, silloin ei sinun hyvä tekosi jäänyt minulta salaan, vaan minä olin sinun kanssasi.',
        14: 'Ja nyt on Jumala lähettänyt minut parantamaan sinut ja sinun miniäsi Saaran.',
        15: 'Minä olen Raafael, yksi niistä seitsemästä pyhästä enkelistä, jotka esiinkantavat pyhien rukoukset ja jotka astuvat Pyhän eteen hänen kirkkaudessaan.»',
        16: 'Silloin molemmat kauhistuivat ja lankesivat kasvoilleen, sillä heidät valtasi pelko.',
        17: 'Mutta hän sanoi heille: »Älkää peljätkö: teillä on oleva rauha; ylistäkää Jumalaa iankaikkisesti.',
        18: 'Sillä en minä ole tullut omasta suosiostani, vaan teidän Jumalanne tahdosta. Ylistäkää siis häntä iankaikkisesti.',
        19: 'Kaiken tämän ajan minä olen ollut teidän näkyvissänne, mutta minä en ole syönyt enkä juonut, te olette nähneet vain näyn.',
        20: 'Kiittäkää nyt siis Jumalaa, sillä minä nousen hänen tykönsä, joka on minut lähettänyt. Ja kirjoittakaa kirjaan kaikki, mitä on tapahtunut.»',
        21: 'Ja kun he nousivat ylös, eivät he enää nähneet häntä.',
        22: 'Ja he ylistivät hänen suuria ja ihmeellisiä tekojansa, kuinka Herran enkeli oli heille ilmestynyt.',
    },
    13: {
        1: 'Ja Toobit kirjoitti rukouksen, riemuvirren, ja sanoi: Ylistetty olkoon Jumala, joka elää iankaikkisesti, ja hänen kuninkuutensa.',
        2: 'Sillä hän kurittaa ja armahtaa, hän vie alas tuonelaan ja sieltä jälleen ylös, eikä kukaan voi paeta hänen kädestänsä.',
        3: 'Kiittäkää häntä, te Israelin lapset, pakanain edessä, sillä heidän keskuuteensa hän on meidät hajottanut.',
        4: 'Julistkaa siellä hänen valtasuuruuttansa, korottakaa häntä kaikkien elävien edessä: Sillä hän on meidän Herramme, ja hän on Jumala, meidän isämme, hamaan kaikkiin iankaikkisuuksiin.',
        5: 'Ja jos hän meitä kurittaakin pahojen tekojemme tähden, niin hän meitä jälleen armahtaa ja kokoaa meidät kaikista pakanakansoista, minne ikinä teidät on hajotettu heidän keskuuteensa.',
        6: 'Jos te käännytte hänen puoleensa kaikesta sydämestänne ja kaikesta sielustanne, ja teette totuuden hänen edessänsä, silloin hän kääntyy teidän puoleenne eikä enää peitä teiltä kasvojansa. Katsokaa, mitä hän on teille tekevä, ja olkoon suunne täynnä hänen kiitostansa. Ylstäkää vanhurskauden Herraa ja korottakaa iankaikkista Kuningasta. Minä kiitän häntä vankeuteni maassa ja julistan hänen voimaansa ja valtasuuruuttansa synnintekijäin kansalle. Kääntykää, te synnintekijät, ja noudattakaa vanhurskautta hänen edessänsä. Kenties hän mielistyy teihin ja tekee laupeuden.',
        7: 'Jumalaani minä ylistän taivaan Kuningasta, se riemuitsee hänen valtasuuruudestaan.',
        8: 'Näin sanokoot kaikki ja kiittäkööt kaikki Jerusalemissa:',
        9: '»Jerusalem, sinä pyhä kaupunki, hän kyllä kurittaa sinua lapsiesi tekojen tähden, mutta hän armahtaa jälleen vanhurskasten lapsia.',
        10: 'Kiitä Herraa hyvästi ja ylistä iankaikkisuuksien Kuningasta, että jälleen rakennettaisiin hänen majansa ilolla sinun keskuuteesi ja hän ilahuttaisi vangittuja sinun keskuudessasi ja osoittaisi sinussa rakkautta vaivatuille sukupolvesta sukupolveen iankaikkisesti.',
        11: 'Monet kansat tulevat kaukaa Herran Jumalan nimen tykö, lahjat käsissänsä, lahjat taivaan Kuninkaalle. Sukukuntien sukukunnat sinua riemuiten kiittävät.',
        12: 'Kirotut olkoot kaikki, jotka sinua vihaavat; siunatut kaikki jotka sinua rakastavat, iankaikkisesti.',
        13: 'Iloitse ja riemuitse vanhurskasten lapsista, sillä heidät kootaan yhteen, ja he ylistävät vanhurskasten Herraa.',
        14: 'Autuaat ne, jotka sinua rakastavat! He saavat iloita sinun rauhastasi. Autuaat ovat kaikki, joille sinun lyöntisi tuottivat murhetta, sillä he saavat iloita sinusta nähdessään kaiken sinun kirkkautesi. Niin he saavat riemuita iankaikkisesti.',
        15: 'Kiitä, minun sieluni, Jumalaa, suurta Kuningasta.',
        16: 'Sillä Jerusalem rakennetaan safiirista ja smaragdista, ja kalliista kivestä sinun muurisi, ja sinun tornisi ja suojavarustuksesi puhtaasta kullasta.',
        17: 'Ja Jerusalemin kadut lasketaan beryllillä ja rubiinilla ja Suufirin kivellä. Ja kaikki sen kujat lausuvat hallelujaa ja kiitosta, sanoen: Ylistetty olkoon Jumala, joka on korottanut sinut, aina ja iankaikkisesti.»',
    },
    14: {
        1: 'Ja Toobit lopetti kiitosvirtensä.',
        2: 'Toobit oli viidenkymmenen kahdeksan vuoden vanha, kun hän menetti näkönsä, ja kahdeksan vuoden perästä hän sai sen takaisin. Hän antoi almuja ja pelkäsi edelleenkin Herraa Jumalaa ja kiitti häntä.',
        3: 'Hän eli hyvin vanhaksi. Ja hän kutsui tykönsä poikansa ja tämän pojat, ja hän sanoi hänelle: »Poikani, katso, minä olen nyt vanha ja valmis eromaan tästä elämästä: ota poikasi',
        4: 'ja mene Meediaan, poikani. Sillä minä olen varma siitä, että niinive kukistuu, niinkuin profeetta Joonas on sanonut. Mutta Meediassa on jonkun aikaa oleva rauhallisempaa. Ja minä olen varma siitä, että kotimaassa olevat veljemme hajotetaan pois hyvästä maasta, ja Jerusalem tulee autioksi, ja Jumalan huone, joka siellä on, poltetaan poroksi ja jää joksikin aikaa autioksi.',
        5: 'Sitten Jumala jälleen armahtaa heitä ja vie heidät takaisin heidän omaan maahansa, ja he rakentavat temppelin - ei kuitenkaan edellisen vertaista - ja se pysyy, kunnes maailmanajat ovat täyttyneet. Senjälkeen he palaavat pakkosiirtolaisuutensa paikoista ja rakentavat Jerusalemin ihanaksi. Ja Jumalan huone, joka siellä on, rakennetaan ylen loistavaksi, niinkuin profeetat ovat siitä kaupungista puhuneet.',
        6: 'Ja kaikki pakanat kääntyvät totuudessa pelkäämään Herraa Jumalaa, ja he kaivavat maahan epäjumalainsa kuvat.',
        7: 'Ja kaikki pakanat ylistävät Herraa. Ja hänen oma kansansa kiittää Jumalaa, ja Herra korottaa kansansa. Ja niin saavat iloita kaikki, jotka totuudessa ja vanhurskaudessa rakastavat Herraa Jumalaa, osoittaen laupeutta veljillemme.',
        8: 'Ja nyt, lapseni, lähde pois Niinivestä, sillä on käyvä, juuri niinkuin profeetta Joonas on puhunut.',
        9: 'Mutta sinä pidä laki ja käskyt ja ole armelias ja oikeamielinen, että menestyisit.',
        10: 'Hautaa minut kunniallisesti, ja äitisi minun viereeni, mutta älkää sitten enää jääkö Niiniveen. Ajattela, poikani, mitä Naadab teki kasvatusisälleen Akiakarille, kuinka hän syöksi hänet valosta pimeyteen ja kuinka hän hänet palkitsi. Akiakar pelastui, mutta tuota toista kohtasi kosto, ja hänen täytyi astua alas pimeyteen. Akiakar antoi almuja, ja hän pelastui kuoleman paulasta, minkä Naadab oli hänelle virittänyt; mutta tämä lankesi siihen itse ja joutui tuhon omaksi.',
        11: 'Katsokaa nyt siis, lapseni, mitä armeliaisuus vaikuttaa ja miten vanhurskaus pelastaa.» Näin sanoen hän vaipui kuolemaan vuoteellensa. Hän oli silloin sadan viidenkymmenen kahdeksan vuoden vanha. Ja Tobias hautasi hänet suurella kunnialla.',
        12: 'Ja kun Hanna kuoli, hautasi hän hänet isän viereen. Sitten Tobias lähti vaimonsa ja poikiensa kanssa Ekbatanaan, appensa Raguelin tykö.',
        13: 'Ja hän eli hyvin vanhaksi, kunnioitusta nauttien. Ja hän hautaasi appivanhempansa suurella kunnialla, ja hän peri heidän omaisuutensa, niin myös isänsä Toobitin omaisuuden.',
        14: 'Hän kuoli Meedian Ekbatanassa sadan kahdenkymmenen seitsemän vuoden vanhana.',
        15: 'Ja ennen kuin hän kuoli, sai hän kuulla Niiniven kukistuneen; sen valloittivat Nebukadnessar ja Averus, Niin hän ennen kuolemaansa sai iloita Niiniven häviöstä. Aamen.',
    },
}
