NAME = 'SpaRV1865: La Santa Biblia Reina-Valera (1865) con arreglos ortográficos'
BOOK = 'Amos'

CHAPTERS = {
    1: {
        1: 'Las palabras de Amós, que fue entre los pastores de Tecua, las cuales vio sobre Israel en días de Osías, rey de Judá, y en días de Jeroboam, hijo de Joas, rey de Israel, dos años antes del terremoto.',
        2: 'Y dijo: Jehová bramará desde Sión, y desde Jerusalem dará su voz, y las habitaciones de los pastores pondrán luto, y la cumbre del Carmelo se secará.',
        3: 'Así dijo Jehová: Por tres pecados de Damasco, y por el cuarto, no la convertiré; porque trillaron con trillos de hierro a Galaad.',
        4: 'Y meteré fuego en la casa de Hazael, y consumirá los palacios de Ben-adad.',
        5: 'Y quebraré la barra de Damasco, y talaré los moradores de Bicat-aven, y los gobernadores de Bet-eden; y el pueblo de Siria será traspasado en Kir, dijo Jehová.',
        6: '¶ Así dijo Jehová: Por tres pecados de Gaza, y por el cuarto, no la convertiré; porque llevó cautiva una cautividad entera para entregar los a Edom.',
        7: 'Y meteré fuego en el muro de Gaza, y quemará sus palacios.',
        8: 'Y talaré los moradores de Azoto, y los gobernadores de Ascalón; y tornaré mi mano sobre Accarón, y los residuos de los Palestinos perecerán, dijo el Señor Jehová.',
        9: '¶ Así dijo Jehová: Por tres pecados de Tiro, y por el cuarto, no la convertiré; porque entregaron la cautividad entera a Edom, y no se acordaron del concierto de hermano.',
        10: 'Y meteré fuego en el muro de Tiro, y consumirá sus palacios.',
        11: '¶ Así dijo Jehová: Por tres pecados de Edom, y por el cuarto, no la convertiré; porque persiguió a cuchillo a su hermano, y rompió sus misericordias; y con su furor le ha robado siempre, y ha guardado el enojo perpetuamente.',
        12: 'Y meteré fuego en Temán, y consumirá los palacios de Bosra.',
        13: '¶ Así dijo Jehová: Por tres pecados de los hijos de Amón, y por el cuarto, no los convertiré; porque rompieron los montes de Galaad, para ensanchar su término.',
        14: 'Y encenderé fuego en el muro de Rabba, y consumirá sus palacios como con estruendo en día de batalla, como con tempestad en día tempestuoso.',
        15: 'Y su rey irá en cautividad, él y sus príncipes todos, dijo Jehová.',
    },
    2: {
        1: 'Así dijo Jehová: Por tres pecados de Moab, y por el cuarto, no le convertiré; porque quemó los huesos del rey de Idumea hasta tornarlos en cal.',
        2: 'Y meteré fuego en Moab, y consumirá los palacios de Cariot, y morirá Moab, en alboroto, en estrépito, y sonido de trompeta.',
        3: 'Y quitaré el juez de en medio de él, y a todos sus príncipes mataré con él, dijo Jehová.',
        4: '¶ Así dijo Jehová: Por tres pecados de Judá, y por el cuarto, no la convertiré; porque menospreciaron la ley de Jehová, y no guardaron sus ordenanzas; y sus mentiras los hicieron errar, en pos de las cuales anduvieron sus padres.',
        5: 'Y meteré fuego en Judá, el cual consumirá los palacios de Jerusalem.',
        6: 'Así dijo Jehová: Por tres pecados de Israel, y por el cuarto, no le convertiré; porque vendieron por dinero al justo, y al pobre por un par de zapatos:',
        7: 'Que anhelan porque haya un polvo de tierra sobre la cabeza de los pobres, y tuercen la carrera de los humildes; y el hombre y su padre entraron a una moza, profanando mi santo nombre.',
        8: 'Y sobre las ropas empeñadas se acuestan junto a cualquier altar; y el vino de los penados beben en la casa de sus dioses.',
        9: 'Y yo destruí al Amorreo delante de ellos, cuya altura era como la altura de los cedros, y fuerte como un alcornoque; y destruí su fruto arriba, y sus raíces abajo.',
        10: 'Y yo os hice a vosotros subir de la tierra de Egipto, y trájeos por el desierto cuarenta años, para que poseyeseis la tierra del Amorreo.',
        11: 'Y levanté de vuestros hijos para profetas, y de vuestros mancebos para que fuesen Nazareos: ¿No es esto así, hijos de Israel? dijo Jehová.',
        12: 'Y vosotros distes de beber vino a los Nazareos, y a los profetas mandasteis, diciendo: No profeticéis.',
        13: 'Pues he aquí que yo os apretaré en vuestro lugar, como se aprieta el carro lleno de haces.',
        14: 'Y la huida perecerá del ligero, y el fuerte no esforzará a su fuerza, ni el valiente escapará su vida.',
        15: 'Y el que toma el arco no estará en pie, ni el ligero de pies escapará, ni el que cabalga en caballo escapará su vida.',
        16: 'El esforzado entre esforzados, aquel día huirá desnudo, dijo Jehová.',
    },
    3: {
        1: 'Oíd esta palabra que ha hablado Jehová contra vosotros, hijos de Israel: contra toda la familia que hice subir de la tierra de Egipto. Dice así:',
        2: 'A vosotros solamente he conocido de todas las familias de la tierra, por tanto visitaré contra vosotros todas vuestras maldades.',
        3: '¿Andarán dos juntos, si no estuvieren de concierto?',
        4: '¿Bramará en el monte el león, sin hacer presa? ¿el leoncillo dará su bramido desde su morada, si no prendiere?',
        5: '¿Caerá el ave en el lazo de la tierra, sin haber armador? ¿Alzarse ha el lazo de la tierra, si no se ha prendido algo?',
        6: '¿Tocarse ha la trompeta en la ciudad, y el pueblo no se alborotará? ¿Habrá algún mal en la ciudad, el cual Jehová no haya hecho?',
        7: 'Porque no hará nada el Señor Jehová, sin que revele su secreto a sus siervos los profetas.',
        8: 'Bramando el león, ¿quién no temerá? hablando el Señor Jehová, ¿quién no profetizará?',
        9: 'Hacéd pregonar sobre los palacios de Azoto, y sobre los palacios de tierra de Egipto, y decíd: Congregáos sobre los montes de Samaria, y ved muchas opresiones en medio de ella, y muchas violencias en medio de ella.',
        10: 'Y no saben hacer lo recto, dijo Jehová, atesorando rapiñas y despojos en sus palacios.',
        11: 'Por tanto el Señor Jehová dijo así: Enemigo vendrá que cercará la tierra; y derribará de ti tu fortaleza, y tus palacios serán saqueados.',
        12: 'Así dijo Jehová: De la manera que el pastor escapa de la boca del león dos piernas, o la punta de una oreja, así escaparán los hijos de Israel, que moran en Samaria, al rincón de la cama, y al canto del lecho.',
        13: 'Oíd, y protestád en la casa de Jacob, dijo Jehová, Dios de los ejércitos:',
        14: 'Que el día que visitaré las rebeliones de Israel sobre él, visitaré también sobre los altares de Bet-el; y serán cortados los cuernos del altar, y caerán a tierra.',
        15: 'Y heriré la casa del invierno con la casa del verano, y las casas de marfil perecerán; y muchas casas serán taladas, dijo Jehová.',
    },
    4: {
        1: 'Oíd esta palabra, vacas de Basán, que estáis en el monte de Samaria, que oprimís los pobres: que quebrantáis los menesterosos: que decís a sus señores: Traed y beberemos.',
        2: 'El Señor Jehová juró por su santidad, que he aquí vienen días sobre vosotros en que os llevará en anzuelos, y a vuestros descendientes en barquillos de pescador.',
        3: 'Y saldrán por los portillos la una en pos de la otra, y seréis echadas del palacio, dijo Jehová.',
        4: 'Id a Bet-el, y rebelád en Gálgala: aumentád la rebelión, y traed de mañana vuestros sacrificios, y vuestros diezmos cada tres años.',
        5: 'Y ofrecéd sacrificio de acción de gracias con pan leudo, y pregonád sacrificios voluntarios, pregonád: pues que así queréis, hijos de Israel, dijo el Señor Jehová.',
        6: '¶ Yo también os di limpieza de dientes en todas vuestras ciudades, y falta de pan en todos vuestros pueblos: y no os tornasteis a mí, dijo Jehová.',
        7: 'Y también yo os detuve la lluvia tres meses antes de la segada; e hice llover sobre una ciudad, y sobre otra ciudad no hice llover: sobre una parte llovió, y la parte sobre la cual no llovió, se secó.',
        8: 'Y venían dos, tres ciudades a una ciudad para beber agua, y no se hartaban; y no os tornasteis a mí, dijo Jehová.',
        9: 'Heríos con viento solano, y oruga, vuestros muchos huertos, y vuestras viñas, y vuestros higuerales; y vuestros olivares comió la langosta; y nunca os tornasteis a mí, dijo Jehová.',
        10: 'Envié en vosotros mortandad en el camino de Egipto: maté a cuchillo vuestros mancebos, con cautiverio de vuestros caballos; e hice subir el hedor de vuestros reales hasta vuestras narices; y nunca os tornasteis a mí, dijo Jehová.',
        11: 'Trastornéos, como cuando Dios trastornó a Sodoma y a Gomorra, y fuisteis como tizón escapado del fuego; y nunca os tornasteis a mí, dijo Jehová.',
        12: 'Por tanto de esta manera haré a ti, o! Israel; y porque te he de hacer esto, aparéjate para venir al encuentro a tu Dios, o! Israel.',
        13: 'Porque he aquí, el que forma los montes, y cria el viento, y denuncia al hombre su pensamiento; el que hace a las tinieblas mañana, y pasa sobre las alturas de la tierra, Jehová Dios de los ejércitos es su nombre.',
    },
    5: {
        1: 'Oíd esta palabra, porque yo levanto endecha sobre vosotros, casa de Israel.',
        2: 'Cayó, nunca más se levantará la virgen de Israel: fue dejada sobre su tierra, no hay quien la levante.',
        3: 'Porque así dijo el Señor Jehová: la ciudad que sacaba mil, quedará con ciento; y la que sacaba ciento, quedará con diez en la casa de Israel.',
        4: 'Porque así dijo Jehová a la casa de Israel: Buscádme, y vivíd.',
        5: 'Y no busquéis a Bet-el, ni entréis en Gálgala, ni paséis a Beer-seba; porque Gálgala será llevada en cautividad, y Bet-el será deshecha.',
        6: 'Buscád a Jehová, y vivíd; porque no hienda, como fuego, a la casa de José, y la consuma, y no haya en Bet-el quien lo apague.',
        7: 'Que convierten en ajenjo el juicio, y dejan en tierra la justicia.',
        8: 'El que hace el Arcturo y el Orión, y las tinieblas vuelve en mañana, y hace oscurecer el día en noche: el que llama a las aguas de la mar, y las derrama sobre la haz de la tierra, Jehová es su nombre.',
        9: 'El que da esfuerzo al robador sobre el fuerte, y que el robador venga contra la fortaleza.',
        10: 'Aborrecieron en la puerta al reprensor, y al que hablaba lo recto abominaron.',
        11: 'Por tanto por vuestro molestar al pobre, y recibís de él carga de trigo, edificasteis casas de sillares, mas no las habitaréis: plantasteis hermosas viñas, mas no beberéis el vino de ellas.',
        12: 'Porque sabido he vuestras muchas rebeliones, y vuestros gruesos pecados: que afligen al justo, y reciben cohecho, y a los pobres en la puerta hacen perder su causa.',
        13: 'Por lo cual el prudente en tal tiempo calla, porque el tiempo es malo.',
        14: 'Buscád lo bueno, y no lo malo, para que viváis: porque así será con vosotros Jehová Dios de los ejércitos, como decís.',
        15: 'Aborrecéd el mal, y amád el bien, y ponéd juicio en la puerta: quizá Jehová Dios de los ejércitos habrá piedad de la resta de José.',
        16: 'Por tanto así dijo Jehová Dios de los ejércitos, el Señor: En todas las plazas habrá llanto, y en todas las calles dirán; ¡Ay, ay! y al labrador llamarán a lloro, y a endecha, a los que supieren endechar.',
        17: 'Y en todas las viñas habrá llanto, porque pasaré por medio de ti, dijo Jehová.',
        18: '¡Ay de los que desean el día de Jehová! ¿para qué queréis este día de Jehová? Tinieblas, y no luz.',
        19: 'Como el que huye de delante del león, y se topa con el oso; o, si entrare en casa, y arrime su mano a la pared, y le muerda la culebra.',
        20: '¿El día de Jehová, no es tinieblas, y no luz: oscuridad, que no tiene resplandor?',
        21: 'Aborrecí, abominé vuestras solemnidades, y no me darán buen olor vuestras congregaciones.',
        22: 'Y si me ofreciereis holocaustos y vuestros presentes, no los recibiré: ni miraré a los sacrificios pacíficos de vuestros engordados.',
        23: 'Quita de mí la multitud de tus cantares; y las salmodias de tus instrumentos no oiré.',
        24: 'Y corra como las aguas el juicio, y la justicia como arroyo impetuoso.',
        25: '¿Habéisme ofrecido sacrificios y presente en el desierto en cuarenta años, casa de Israel?',
        26: 'Y ofrecisteis a Sicut, vuestro rey, y a Quión, vuestros ídolos, estrella de vuestros dioses que os hicisteis.',
        27: 'Haréos pues trasportar de ese cabo de Damasco, dijo Jehová, Dios de los ejércitos es su nombre.',
    },
    6: {
        1: '¡Ay de los reposados en Sión, y de los confiados en el monte de Samaria, nombrados entre las mismas naciones principales, las cuales vendrán sobre ellos, o! casa de Israel!',
        2: 'Pasád a Calanna, y mirád; y de allí id a la gran Emat; y descendéd a Get de los Palestinos, ¿si son aquellos reinos mejores que estos reinos? ¿si su término es mayor que vuestro término?',
        3: 'Los que dilatáis el día malo, y acercáis la silla de iniquidad:',
        4: 'Los que duermen en camas de marfil, y se extienden sobre sus lechos, y comen los corderos del rebaño, y los becerros de en medio del engordadero:',
        5: 'Los que hacen de garganta al son de la flauta, e inventan instrumentos músicos, como David:',
        6: 'Los que beben vino en tazones, y se ungen con los ungüentos más preciosos, ni se afligen por el quebrantamiento de José.',
        7: 'Por tanto ahora pasarán en el principio de los que pasaren; y se acercará el lloro de los extendidos.',
        8: 'El Señor Jehová juró por su alma, Jehová Dios de los ejércitos dijo: Tengo en abominación la grandeza de Jacob, y sus palacios aborrezco; y la ciudad, y su plenitud entregaré al enemigo.',
        9: 'Y acontecerá que si diez hombres quedaren en una casa, morirán.',
        10: 'Y su tio tomará a cada uno, y le quemará, para sacar los huesos de casa; y dirá al que estará en los rincones de la casa: ¿Hay aun alguno contigo? y dirá: No. Y dirá: Calla, que no conviene hacer memoria del nombre de Jehová.',
        11: 'Porque he aquí que Jehová mandará, y herirá de hendeduras la casa mayor; y la casa menor de aberturas.',
        12: '¿Correrán los caballos por las piedras? ¿ararán con vacas? ¿por qué habéis vosotros tornado el juicio en veneno, y el fruto de justicia en ajenjo?',
        13: 'Los que os alegráis en nada: los que decís: ¿Nosotros no nos tomamos cuernos con nuestra fortaleza?',
        14: 'Porque he aquí que yo levantaré sobre vosotros, o! casa de Israel, dijo Jehová Dios de los ejércitos, nación, que os apretará desde la entrada de Emat, hasta el arroyo del desierto.',
    },
    7: {
        1: 'El Señor Jehová me mostró así; y he aquí que él criaba langostas al principio que comenzaba a crecer el heno tardío. Y he aquí que el heno tardío creció después de las segadas del rey.',
        2: 'Y acaeció que como acabó de comer la yerba de la tierra, yo dije: Señor Jehová, perdona ahora: ¿quién levantará a Jacob? porque es pequeño.',
        3: 'Arrepintióse Jehová de esto: no será, dijo Jehová.',
        4: 'El Señor Jehová después me mostró así; y he aquí que llamaba para juzgar por fuego el Señor Jehová: y consumió un gran abismo, y consumió la parte.',
        5: 'Y dije: Señor Jehová, cesa ahora: ¿quién levantará a Jacob? porque es pequeño.',
        6: 'Arrepintióse Jehová de esto: Tampoco esto no será, dijo el Señor Jehová.',
        7: 'Enseñóme también así: He aquí que el Señor estaba sobre un muro edificado a plomo de albañil; y tenía en su mano un plomo de albañil.',
        8: 'Jehová entonces me dijo: ¿Qué ves Amós? Y dije: Un plomo de albañil. Y el Señor dijo: He aquí que yo pongo plomo de albañil en medio de mi pueblo Israel: nunca más le pasaré.',
        9: 'Y los altares de Isaac serán destruidos, y los santuarios de Israel serán asolados, y levantarme he con espada sobre la casa de Jeroboam.',
        10: '¶ Entonces Amasías sacerdote de Bet-el envió a decir a Jeroboam, rey de Israel: Amós ha conjurado contra ti en medio de la casa de Israel: la tierra no puede ya sufrir todas sus palabras.',
        11: 'Porque así ha dicho Amós: Jeroboam morirá a cuchillo; e Israel pasará de su tierra en cautividad.',
        12: 'Y Amasías dijo a Amós: Vidente, vete, y huye a tierra de Judá, y come allá tu pan, y profetiza allá.',
        13: 'Y no profetices más en Bet-el; porque es santuario del rey, y cabecera del reino.',
        14: 'Y Amós respondió, y dijo a Amasías: No soy profeta, ni soy hijo de profeta: mas soy boyero, y cogedor de cabrahígos.',
        15: 'Y Jehová me tomó de tras el ganado; y díjome Jehová: Vé, y profetiza a mi pueblo Israel.',
        16: 'Ahora pues, oye palabra de Jehová: Tú dices: No profetices contra Israel, ni hables contra la casa de Isaac.',
        17: 'Por tanto así dijo Jehová: Tu mujer fornicará en la ciudad, y tus hijos y tus hijas caerán a cuchillo, y tu tierra será partida por suertes; y tu morirás en tierra inmunda; e Israel será traspasado de su tierra.',
    },
    8: {
        1: 'Jehová me enseñó así; y he aquí un canastillo de fruta de verano.',
        2: 'Y dijo: ¿Qué ves Amós? Y dije: Un canastillo de fruta de verano. Y Jehová me dijo: Venido ha el fin sobre mi pueblo Israel: nunca más le pasaré.',
        3: 'Y los cantores del templo aullarán en aquel día, dijo el Señor Jehová: los cuerpos muertos serán aumentados en todo lugar, echados en silencio.',
        4: 'Oíd esto los que tragáis los menesterosos, y taláis los pobres de la tierra,',
        5: 'Diciendo: Cuando pasare el mes, venderemos el trigo; y pasada la semana, abriremos el pan; y achicaremos la medida, y engrandeceremos el precio, y falsearemos el peso engañoso.',
        6: 'Y compraremos los pobres por dinero, y los necesitados por un par de zapatos; y venderemos las ahechaduras del trigo.',
        7: 'Jehová juró por la gloria de Jacob: Que no me olvidaré para siempre de todas sus obras.',
        8: '¶ ¿No se ha de estremecer la tierra sobre esto? ¿y todo habitador de ella, no llorará? y toda subirá como un río, y será arrojada, y será hundida como el río de Egipto.',
        9: 'Y acaecerá en aquel día, dijo el Señor Jehová, que haré que se ponga el sol al mediodía, y la tierra cubriré de tinieblas en el día claro.',
        10: 'Y tornaré vuestras fiestas en lloro, y todos vuestros cantares en endechas, y haré poner saco sobre todos lomos, y peladura sobre toda cabeza; y tornarla he como en llanto de unigénito, su postrimería como día amargo.',
        11: 'He aquí que vienen días, dijo el Señor Jehová, en los cuales enviaré hambre en la tierra: no hambre de pan, ni sed de agua, mas de oír palabra de Jehová.',
        12: 'E irán vagabundos desde la una mar hasta la otra mar: desde el norte hasta el oriente discurrirán buscando palabra de Jehová, y no la hallarán.',
        13: 'En aquel tiempo las doncellas hermosas, y los mancebos desmayarán de sed.',
        14: 'Los que juran por el pecado de Samaria, y dicen: Vive tú, Dios de Dan; y: Vive el camino de Beer-seba: caerán, y nunca más se levantarán.',
    },
    9: {
        1: 'Ví al Señor que estaba sobre el altar, y dijo: Hiere el umbral, y estremézcanse las puertas; y córtalos en piezas la cabeza de todos; y el postrero de ellos mataré a cuchillo: no habrá de ellos quien huya, ni quien escape.',
        2: 'Si cavaren hasta el infierno, de allá los tomará mi mano; y si subieren hasta el cielo, de allá los haré descender:',
        3: 'Y si se escondieren en la cumbre del Carmelo, allí los buscaré, y los tomaré; y si se escondieren de delante de mis ojos en el profundo de la mar, allí mandaré a la culebra, y morderlos ha:',
        4: 'Y si fueren en cautiverio delante de sus enemigos, allí mandaré a la espada, y matarlos ha; y pondré sobre ellos mis ojos para mal, y no para bien.',
        5: 'El Señor Jehová de los ejércitos, que toca la tierra, y se derretirá, y llorarán todos los que en ella moran; y subirá toda como un río, y será hundida como el río de Egipto.',
        6: 'El edificó en el cielo sus grados, y su conjunto fundó sobre la tierra: él llama las aguas de la mar, y las derrama sobre la haz de la tierra: Jehová es su nombre.',
        7: 'Hijos de Israel, ¿no me sois vosotros como hijos de Etiopes? dijo Jehová: ¿No hice yo subir a Israel de la tierra de Egipto, y a los Palestinos de Caftor, y a los Siros de Kir?',
        8: 'He aquí que los ojos del Señor Jehová están contra el reino pecador; y yo le asolaré de la haz de la tierra: mas no destruiré del todo la casa de Jacob, dijo Jehová.',
        9: 'Porque he aquí que yo mandaré, y haré que la casa de Israel sea zarandada en todas las naciones, como se zaranda el grano en un harnero, y no cae una chinica en la tierra.',
        10: 'A espada morirán todos los pecadores de mi pueblo, que dicen: No se acercará, ni se anticipará el mal por causa nuestra.',
        11: 'En aquel día yo levantaré la cabaña de David caída, y cerraré sus portillos, y levantaré sus ruinas, y edificarle he como en el tiempo pasado:',
        12: 'Para que aquellos sobre los cuales es llamado mi nombre, posean la resta de Idumea, y a todas las naciones, dijo Jehová que hace esto.',
        13: '¶ He aquí que vienen días, dijo Jehová, en que el que ara se llegará al segador, y el pisador de las uvas al que lleva la simiente; y los montes destilarán mosto, y todos los collados se derretirán.',
        14: 'Y tornaré el cautiverio de mi pueblo Israel; y edificarán las ciudades asoladas, y habitarlas han; y plantarán viñas, y beberán el vino de ellas; y harán huertos, y comerán el fruto de ellos.',
        15: 'Y plantarlos he sobre su tierra, y nunca más serán arrancados de su tierra, la cual yo les dí, dijo Jehová Dios tuyo.',
    },
}
