NAME = 'FreLXX: Traduction de la LXX par P. GIGUET et autres traducteurs, 1872.'
BOOK = 'Malachi'

CHAPTERS = {
    1: {
        1: 'Parole du Seigneur sur Israël transmise à Son envoyé; déposez-la maintenant dans vos cœurs.',
        2: "Je vous ai aimés, dit le Seigneur, et vous avez dit: En quoi donc nous as- Tu aimés? Ésaü n'était-il pas le frère de Jacob? dit le Seigneur; n'ai-Je point aimé Jacob",
        3: "et pris en haine Ésaü? J'ai voulu que ses confins fussent dévastés, et que son héritage devînt comme les maisons du désert.",
        4: "Or si l'on dit: L'Idumée est détruite, revenons et repeuplons le désert, voici ce que dit le Seigneur: Ils rebâtiront, et Je renverserai, et leur terre sera surnommée l'impiété, et ce sera un peuple à qui le Seigneur sera hostile pour jamais.",
        5: "Et vos yeux verront cela, et vous direz: Le Seigneur a montré Sa puissance au delà des limites d'Israël.",
        6: "Le fils glorifie le père, et le serviteur son maître; et si Je suis père, où est Ma gloire? Et si Je suis maître, où est la crainte que J'inspire? dit le Seigneur tout-puissant. Et vous, prêtres, c'est vous qui méprisez Mon Nom, et qui dites: En quoi méprisons-nous Ton Nom?",
        7: "C'est vous qui présentez à l'autel des aliments souillés, et qui dites: En quoi les avons-nous souillés? Vous les avez souillés en disant: La table du Seigneur est souillée; et ce qu'on y déposait Tu l'as méprisé.",
        8: "Si vous présentez pour le sacrifice une victime aveugle, n'est-ce point mal? Si vous en présentez une boiteuse ou malade, n'est-ce point mal? Offre-les à ton prince, et tu verras s'il te recevra, s'il accueillera ton visage, dit le Seigneur tout-puissant.",
        9: 'Maintenant priez devant votre Dieu, et adressez-Lui votre oraison; mais si de telles offrandes Me sont faites par vos mains, pourrai-Je bien accueillir vos visages? dit le Seigneur tout-puissant.',
        10: "Et cependant chez vous les portes sont fermées, et vous n'allumez pas pour rien le feu de l'autel. Aussi Je ne Me complais pas en vous, dit le Seigneur tout-puissant, et Je n'accueillerai pas le sacrifice de vos mains.",
        11: "Du lever du soleil à son coucher, Mon Nom a été glorifié parmi les gentils; en tout lieu on brûle en Mon Nom de l'encens et on offre une victime pure; parce que Mon Nom est grand parmi les nations, dit le Seigneur, Maître de toutes choses.",
        12: "Et ce Nom vous Le profanez quand vous dites: La table du Seigneur est souillée, et les chairs que l'on y dépose sont méprisables.",
        13: "Vous avez dit encore: Ces offrandes sont le fruit de notre labeur; c'est pourquoi Je les ai rejetées avec mépris, dit le Seigneur tout-puissant; car vous Me présentez des victimes dérobées, ou boiteuses ou infirmes; et si vous Me les offrez en sacrifice, puis-Je les accepter de vos mains? dit le Seigneur tout-puissant.",
        14: 'Maudit soit le riche qui possédait en son bétail un bélier voué au sacrifice, et qui sacrifie au Seigneur une chose corrompue; car Moi Je suis un grand roi, dit le Seigneur Dieu tout-puissant, et Mon Nom est éclatant parmi les nations.',
    },
    2: {
        1: 'Et maintenant voici un ordre pour vous, ô prêtres',
        2: "Si vous Me désobéissez, et si vous ne mettez pas en vos cœurs qu'il faut glorifier Mon Nom, dit le Seigneur tout-puissant, Je vous enverrai Ma malédiction; et votre bénédiction sera maudite, et Je la maudirai, et Je la rendrai vaine, et la Mienne ne sera pas en vous, parce que vous n'aurez point déposé Mes paroles en vos cœurs.",
        3: "Voilà que Je vous prive de l'épaule de vos victimes, et Je répandrai sur votre face leur fiente, la fiente de vos fêtes, et Je vous prendrai en même temps à leur place.",
        4: "Et vous connaîtrez que c'est Moi qui vous ai envoyé ce commandement, que Mon alliance doit être avec les lévites, dit le Seigneur tout-puissant.",
        5: "Mon alliance était avec Lévi, une alliance de vie et de paix, et Je lui avais donné Ma crainte, de sorte qu'à Mon Nom il était frappé de crainte.",
        6: "La loi de vérité était en sa bouche, et nulle iniquité n'eût été trouvée sur ses lèvres; il marchait avec Moi, dirigeant sa voie en paix, et il a détourné du mal nombre d'hommes.",
        7: "Les lèvres du prêtre doivent garder la doctrine; on cherchera la loi dans les paroles de sa bouche; car il est l'envoyé du Seigneur tout-puissant.",
        8: "Mais vous vous êtes retirés de la voie, et vous avez détourné plusieurs de la loi, et vous avez profané l'alliance de Lévi, dit le Seigneur tout-puissant.",
        9: "Aussi ai-Je fait de vous le mépris et le rebut de toutes les nations, parce que vous n'avez point gardé Mes voies, mais qu'en la loi vous avez fait acception des personnes.",
        10: "N'avez-vous pas tous un seul Père? N'est-ce pas le Dieu unique qui vous a créés? Pourquoi donc chacun de vous a-t-il abandonné son frère en souillant l'alliance de vos ancêtres?",
        11: "Juda a failli, et l'abomination a été en Israël et en Jérusalem, parce que Juda a profané les choses saintes du Seigneur, où Dieu Se complaisait, et qu'il s'est attaché à des dieux étrangers.",
        12: "Le Seigneur exterminera tout homme qui fera ainsi pour l'expulser des tentes de Jacob, et le séparer de ceux qui sacrifient au Seigneur tout- puissant.",
        13: "Et vous avez fait ce que Je déteste; vous avez couvert de larmes l'autel du Seigneur: vous vous êtes frappé la poitrine au milieu des cris et des gémissements. Est-il convenable que Je considère vos victimes, ou que J'agrée quelque chose de vos mains?",
        14: "Et vous avez dit: Pour quel motif? C'est parce que le Seigneur a porté témoignage contre toi et la femme de ta jeunesse que tu as abandonnée: elle qui était ta compagne; elle qui était la femme de ton alliance.",
        15: "Ne l'a-t-Il pas éternellement créée? n'est-elle pas Son esprit? Et tu as dit: Que demande Dieu, sinon des enfants issus de moi? Or garde cette parole en ton esprit: N'abandonne pas la femme de ta jeunesse.",
        16: "Mais si, l'ayant haïe, tu la répudies, dit le Seigneur Dieu d'Israël, l'impiété couvrira toutes tes pensées, dit le Seigneur tout-puissant; c'est pourquoi garde cette parole en ton esprit: N'abandonne pas la femme de ta jeunesse.",
        17: "Ô vous qui, par vos paroles, provoquez Dieu, et qui dites: En quoi L'avons-nous provoqué? C'est en disant: Quiconque fait le mal est bien vu du Seigneur; Il Se complaît en ceux-là; où donc est le Dieu de la justice?",
    },
    3: {
        1: "Voilà que J'envoie Mon ange, et il surveillera la voie devant Moi, et le Seigneur que vous cherchez viendra soudain dans Son temple, avec l'ange de l'alliance que vous avez désiré; Le voici, Il vient, dit le Seigneur tout- puissant.",
        2: "Et qui donc aura le pied ferme le jour de Sa venue? Qui supportera Sa présence? Il vient comme le feu d'une fournaise, ou comme l'herbe à foulons.",
        3: "Il siégera pour fondre et purifier, comme on purifie l'argent et l'or, et Il purifiera les fils de Lévi, et Il les coulera comme l'or et l'argent. Et ils offriront des victimes au Seigneur selon la justice.",
        4: "Et les sacrifices de Juda et de Jérusalem seront agréables au Seigneur, comme durant les jours anciens, comme durant les années d'autrefois.",
        5: "Et Je M'approcherai de vous en jugement, et Je serai un témoin empressé contre les magiciens, contre les femmes adultères, contre ceux qui prennent en vain Mon Nom, contre ceux qui retiennent le salaire du journalier, contre ceux qui oppriment la veuve, contre ceux qui maltraitent l'orphelin, contre ceux qui faussent le jugement envers l'étranger et n'ont pas la crainte de Moi, dit le Seigneur tout-puissant.",
        6: 'Car Je suis le Seigneur votre Dieu, et Je ne change pas.',
        7: "Et vous, fils de Jacob, vous ne vous êtes point abstenus des iniquités de vos pères; vous vous êtes retirés de Ma loi, et vous ne l'avez point gardée. Convertissez-vous à Moi, et Je reviendrai à vous, dit le Seigneur tout- puissant. Et vous avez dit: En quoi nous convertirons-nous?",
        8: "Est-ce que l'homme fera tomber Dieu dans ses pièges? Car vous cherchez à Me tromper; et vous direz: En quoi cherchons-nous à Te tromper? C'est en retenant pour vous les dîmes et les prémices.",
        9: "Vous M'avez regardé avec mépris, et vous avez cherché à Me tromper. L'année est révolue,",
        10: "et vous avez porté toutes les récoltes dans vos greniers; mais elles seront mises au pillage en chaque maison. Convertissez-vous sur ce point, dit le Seigneur tout-puissant. Et vous verrez alors si Je n'ouvrirai pas pour vous les cataractes du ciel, et si Je ne répandrai pas sur vous Ma bénédiction, jusqu'à ce que vous soyez satisfaits.",
        11: "Et Je vous distribuerai votre nourriture, et Je n'endommagerai pas les fruits de votre champ, et votre vigne ne souffrira d'aucune maladie dans votre terre, dit le Seigneur tout-puissant.",
        12: 'Et toutes les nations vous estimeront heureux, parce que vous serez une terre bien-aimée, dit le Seigneur tout-puissant.',
        13: 'Vous avez tenu contre Moi des discours injurieux, dit le Seigneur, et vous avez dit: En quoi avons-nous parlé contre Toi?',
        14: "Et vous avez dit: Bien fou qui sert le Seigneur; qu'avons-nous de plus pour avoir gardé Ses commandements, et avoir paru comme suppliants devant Sa face?",
        15: 'Et maintenant nous estimons heureux les étrangers, ils se sont enrichis à mal faire; ils ont résisté à Dieu et ils ont été sauvés.',
        16: 'Mais bien autrement ont parlé les hommes craignant Dieu. Et le Seigneur a été attentif, et Il a écouté, et Il a écrit un livre, un mémorial devant Lui, pour ceux qui craignent le Seigneur et vénèrent Son Nom.',
        17: 'Et ils seront à Moi, dit le Seigneur Dieu tout-puissant, le jour que Je ferai naître, pour Me les réserver, et Je les aimerai comme un homme aime son fils qui le sert.',
        18: 'Et vous vous convertirez, et vous distinguerez le juste du méchant; le serviteur de Dieu, de celui qui refuse de Le servir.',
        19: "Voilà que le jour approche, brûlant comme une fournaise, et il les consumera; et tous les étrangers et tous ceux qui font le mal seront comme de la paille; et le jour qui approche les dévorera, dit le Seigneur tout-puissant; et il ne restera d'eux ni branche ni racine.",
        20: 'Et le Soleil de justice Se lèvera pour vous qui craignez Mon Nom; et sur Ses ailes Il portera le salut; et vous sortirez, et vous bondirez comme de jeunes bœufs délivrés de leurs liens.',
        21: 'Et vous foulerez les impies; car ils seront sous vos pieds comme de la cendre, le jour que Je ferai naître, dit le Seigneur tout-puissant.',
        22: 'Et voilà que Je vous enverrai Élie le Thesbite, avant que vienne ce jour du Seigneur, jour grand et éclatant,',
        23: "qui réunira au fils le cœur de son père, à l'homme le cœur de son prochain, de peur que Je ne survienne et que Je n'anéantisse la terre.",
        24: 'Souvenez-vous de la loi de Moïse, Mon serviteur, telle que Je la lui ai intimée, en Horeb, devant tout Israël, dans ses commandements et ses préceptes.',
    },
}
