NAME = 'Alb: Albanian Bible'
BOOK = 'Galatians'

CHAPTERS = {
    1: {
        1: 'Pali, apostull (jo nga njerëzit, as me anë të njeriut, por nëpërmjet Jezu Krishtit dhe Perëndisë Atit, që e ringjalli prej së vdekurish),',
        2: 'dhe gjithë vëllezërit që janë me mua, kishave të Galatisë:',
        3: 'Paçi hir e paqe nga Perëndia Ati dhe nga Zoti ynë Jezu Krishti,',
        4: 'që e dha veten e tij për mëkatet tona, për të na shpëtuar nga kjo kohë e mbrapshtë, sipas vullnetit të Perëndisë, Atit tonë,',
        5: 'i cili pastë lavdi në shekuj të shekujve. Amen.',
        6: 'Çuditëm që kaluat kaq shpejt nga ai që ju thirri ju me anë të hirit të Krishtit, në një ungjill tjetër,',
        7: 'i cili nuk është tjetër; por ka disa njerëz që ju turbullojnë dhe që duan ta shtrëmbërojnë ungjillin e Krishtit.',
        8: "Por, edhe sikur ne ose një engjëll i qiellit t'ju predikonte një ungjill të ndryshëm nga ai që ju kemi predikuar, qoftë i mallkuar.",
        9: 'Ashtu si e thamë më përpara, po e them përsëri: Në qoftë se dikush ju predikon një ungjill tjetër nga ai që keni marrë, qoftë i mallkuar.',
        10: "Sepse unë tani vallë kërkoj të fitoj miratimin e njerëzve apo të Perëndisë? Apo kërkoj t'u pëlqej njerëzve? Sepse, po të kërkoja t'u pëlqej njerëzve, nuk do të isha shërbëtori i Krishtit.",
        11: 'Tani, o vëllezër, po ju vë në dijeni se ungjilli që është shpallur nga unë, nuk është sipas njeriut,',
        12: 'sepse unë nuk e kam marrë as e kam mësuar nga ndonjë njeri, por e kam marrë nëpërmjet një zbulese nga Jezu Krishti.',
        13: 'Sepse ju keni dëgjuar për sjelljen time të atëhershme në judaizëm, si e përndiqja me egërsi të madhe kishën e Perëndisë dhe e shkatërroja.',
        14: 'Dhe si përparoja në judaizëm më tepër se shumë bashkëkohës të kombit tim, duke qenë jashtëzakonisht i zellshëm për traditat e etërve të mi.',
        15: 'Po, kur i pëlqeu Perëndisë, që më kishte ndarë që nga barku i nënës dhe më thirri me anë të hirit të tij,',
        16: "që të zbulojë në mua Birin e tij, që unë t'ua shpall midis joçifutëve, unë nuk mora menjëherë këshill nga mish dhe gjak,",
        17: 'as nuk u ngjita në Jeruzalem tek ata që ishin apostuj përpara meje, por shkova në Arabi dhe u ktheva përsëri në Damask.',
        18: 'Pastaj, pas tre vjetësh, u ngjita në Jeruzalem për të takuar Pjetrin dhe ndenja me të pesëmbëdhjetë ditë.',
        19: 'Dhe nuk pashë asnjë nga apostujt e tjerë, përveç Jakobit, vëllait të Zotit.',
        20: 'Dhe në këto që po ju shkruaj, ja, përpara Perëndisë, nuk gënjej.',
        21: 'Pastaj shkova në krahinat e Sirisë dhe të Kilikisë.',
        22: 'Por unë personalisht isha i panjohur nga kishat e Judesë, që janë në Krisht,',
        23: "po ato kishin dëgjuar vetëm: ''Ai që na persekutonte më përpara, tani po shpall atë besim që ai shkatërronte'',",
        24: 'dhe përlëvdonin Perëndinë për shkakun tim.',
    },
    2: {
        1: 'Pastaj, pas katërmbëdhjetë vjetësh, u ngjita përsëri në Jeruzalem me Barnabën; dhe mora me vete edhe Titin.',
        2: 'Dhe u ngjita sipas një zbulese dhe u shtjellova atyre ungjillin që unë po predikoj ndër johebrenjtë, por në mënyrë të veçantë, atyre që kishin më shumë emër, që të mos bridhja ose vrapoja më kot.',
        3: 'Por as Titi që ishte me mua, ndonëse ishte Grek, nuk qe shtrënguar që të rrethpritej;',
        4: 'edhe kjo për shkak të vëllezërve të rremë, që kishin hyrë tinëz, që kishin depërtuar për të përgjuar lirinë tonë që kemi në Krishtin Jezu, që të na robërojnë.',
        5: 'Këtyre ne nuk iu nënshtruam as edhe për një moment, që e vërteta e ungjillit të mbetej e pacënuar te ju.',
        6: 'Por nga ana e atyre që gëzonin një farë kredie (nuk ka rëndësi se kush ishin, Perëndia nuk shikon dukjen e njeriut), pra, ata që gëzonin kredinë më të madhe nuk shtuan gjë tek unë.',
        7: "Madje, duke parë se mua m'u besua ungjilli për të parrethprerët, sikurse Pjetrit ai për të rrethprerët,",
        8: '(sepse ai që kishte vepruar në mënyrë të fuqishme në Pjetrin për apostullim tek të rrethprerëve, kishte vepruar në mënyrë të fuqishme edhe në mua për johebrenjtë),',
        9: "duke njohur hirin që m'u dha, Jakobi, Kefa dhe Gjoni, të cilët i konsideronin shtylla, më dhanë mua dhe Barnabës të djathtat e tyre si shenjë shoqërie, që të shkonim ne ndër johebrenjtë dhe ata ndër të rrethprerë.",
        10: 'Vetëm na porositën që të kujtoheshim për të varfrit, pikërisht atë që edhe unë e kisha ndërmend ta bëja.',
        11: "Por kur erdhi Pjetri në Antioki, unë e kundërshtova në sy, sepse ishte për t'u qortuar.",
        12: 'Në fakt, para se të vinin disa njerëz nga ana e Jakobit, ai hante me johebrenjtë; po, kur erdhën ata, ai u tërhoq dhe u nda, duke druajtur ata të rrethprerjes.',
        13: 'Edhe Judenj të tjerë shtireshin bashkë me të, aq sa edhe Barnaba u tërhoq nga hipokrizia e tyre.',
        14: "Po kur unë pashë se ata nuk ecnin drejt sipas së vërtetës së ungjillit, i thashë Pjetrit përpara të gjithëve: ''Në qoftë se ti, që je Jude, rron porsi johebrenjtë dhe jo si Judenjtë, pse i detyron johebrenjtë të rrojnë si Judenj?''.",
        15: 'Ne, që jemi Judenj nga lindja dhe jo mëkatarë në mes johebrenjsh,',
        16: 'duke ditur se njeriu nuk shfajësohet me anë të veprave të ligjit, por me anë të besimit në Jezu Krishtin, besuam edhe ne në Jezu Krishtin, që të shfajësoheshim me anë të besimit në Krishtin dhe jo me anë të veprave të ligjit, sepse asnjë mish nuk do të shfajësohet me anë të veprave të ligjit.',
        17: 'Dhe, në qoftë se duke kërkuar të shfajësohemi në Krishtin, u gjetëm edhe ne mëkatarë, mos vallë Krishti qënka shërbenjës i mëkatit. Kurrsesi jo!',
        18: 'Sepse, në qoftë se unë ndërtoj përsëri ato gjërat që prisha, unë bëhem vetë shkelës,',
        19: 'sepse përmes ligjit, vdiqa për ligjin, që unë të rroj për Perëndinë.',
        20: 'Unë u kryqëzova bashkë me Krishtin dhe nuk rroj më unë, po Krishti rron në mua; dhe ajo jetë që tani jetoj në mish, e jetoj në besimin e Birit të Perëndisë, që më deshi dhe dha veten për mua.',
        21: 'Unë nuk e hedh poshtë hirin e Perëndisë sepse, në qoftë se drejtësia vjen me anë të ligjit, atëherë Krishti ka vdekur më kot.',
    },
    3: {
        1: 'O Galatas të marrë! Kush ju ka yshtur që të mos i bindeni së vërtetës, ju, që para syve tuaj Jezu Krishti është përshkruar i kryqëzuar midis jush?',
        2: 'Vetëm këtë dua të di nga ju: a e morët Frymën me anë të veprave të ligjit apo nëpërmjet dëgjimit të besimit?',
        3: 'A jeni kaq të marrë sa që, mbasi nisët në Frymë, të përfundoni në mish?',
        4: 'A thua hoqët kaq shumë gjëra më kot, nëse kanë qenë vërtetë më kot?',
        5: 'Ai që ju jep juve Frymën, dhe kryen midis jush vepra të fuqishme, i bën me anë të veprave të ligjit apo me anë të predikimit të besimit?',
        6: "Kështu Abrahami ''e besoi Perëndinë, dhe kjo iu numërua për drejtësi'';",
        7: 'Ta dini, pra, se ata që janë nga besimi janë bij të Abrahamit.',
        8: "Dhe Shkrimi, duke parashikuar se Perëndia do t'i shfajësonte kombet me anë të besimit, ia dha më përpara Abrahamit lajmin e mirë: ''Të gjitha kombet do të bekohen në ty''.",
        9: 'Prandaj ata që themelohen mbi besimin bekohen bashkë me të besueshmin Abraham.',
        10: "Dhe të gjithë ata që themelohen mbi veprat e ligjit janë nën mallkim, sepse është shkruar: ''I mallkuar është kushdo që nuk qëndron në të gjitha ato që shkruhen në librin e ligjit për t'i praktikuar''.",
        11: "Sepse me anë të ligjit askush nuk shfajësohet përpara Perëndisë, sepse: ''I drejti do të rrojë me anë të besimit''.",
        12: "Dhe ligji nuk është nga besimi, por ''njeriu që do t'i bëjë ato, do të rrojë me anë të tyre''.",
        13: "Krishti na shpengoi nga mallkimi i ligjit, sepse u bë mallkim për ne (duke qenë se është shkruar: ''I mallkuar është kushdo që varet në dru''),",
        14: "që bekimi i Abrahamit t'u vijë johebrenjve me anë të Jezu Krishtit, që ne të marrim premtimin e Frymës me anë të besimit.",
        15: 'O vëllezër, po ju flas në mënyrën e njerëzve: në qoftë se një besëlidhje është aprovuar, edhe pse është besëlidhje njeriu, askush nuk e zhvleftëson as nuk i shton gjë.',
        16: "Dhe premtimet iu bënë Abrahamit dhe pasardhjes së tij. Shkrimi nuk thotë: ''Edhe pasardhësve'' si të ishin shumë, por të një të vetme: ''Dhe pasardhjes sate'', pra Krishti.",
        17: 'Dhe unë them këtë: ligji, që erdhi katërqind e tridhjetë vjet më pas, nuk e zhvleftëson besëlidhjen e aprovuar më parë nga ana e Perëndisë në Krishtin, në mënyrë që të prishë premtimin.',
        18: 'Sepse, në qoftë se trashëgimi është nga ligji, nuk është më nga premtimi. Por Perëndia ia fali atë Abrahamit me anë të premtimit.',
        19: 'Atëherë, pse u dha ligji? Ai u shtua për shkak të shkeljeve, deri sa të vinte pasardhja së cilës i qe bërë premtimi; dhe ky ligj u shpall nëpërmjet engjëjve, me anë të një ndërmjetësi.',
        20: 'Dhe ndërmjetësi nuk është ndërmjetës i një ane të vetme, kurse Perëndia është një.',
        21: 'A thua atëherë ligji është kundër premtimeve të Perëndisë? Kurrsesi jo! Sepse po të ishte dhënë një ligj që mund të jepte jetë, drejtësia do të ishte me të vërtetë prej ligjit.',
        22: "Por Shkrimi i mbylli të gjitha gjërat nën mëkatin, që t'u jepej besimtarëve premtimi nëpërmjet besimit të Jezu Krishtit.",
        23: 'Dhe, para se të vinte besimi, ne ruheshim nën ligjin, si të mbyllur, duke pritur besimin që duhej të zbulohej.',
        24: 'Kështu ligji qe mësuesi ynë për te Krishti, që ne të shfajësohemi me anë të besimit.',
        25: 'Por, mbasi besimi erdhi, ne nuk jemi më nën ndonjë mësues,',
        26: 'sepse të gjithë ju jeni bij të Perëndisë me anë të besimit te Jezu Krishti.',
        27: 'Sepse të gjithë ju që jeni pagëzuar në Krishtin, Krishtin keni veshur.',
        28: 'Nuk ka as Jude, as Grek, nuk ka as skllav as të lirë, nuk ka as mashkull as femër, sepse të gjithë jeni një në Jezu Krishtin.',
        29: 'Dhe, në qoftë se jeni të Krishtit, jeni pra pasardhja e Abrahamit dhe trashëgimtarë sipas premtimit.',
    },
    4: {
        1: 'Edhe them se për sa kohë trashëgimtari është i mitur, nuk dallohet fare nga skllavi, megjithëse është zot i të gjithave,',
        2: 'por ai është nën kujdestarë dhe administratorë deri në kohën e caktuar nga i ati.',
        3: 'Kështu edhe ne, sa ishim të mitur, ishim të robëruar nën elementet e botës,',
        4: 'por, kur u mbush koha, Perëndia dërgoi Birin e tij, të lindur prej gruaje, të nënshtruar ligjit,',
        5: 'që të shpengonte ata që ishin nën ligj, që ne të fitojmë birërinë.',
        6: "Dhe, duke qenë se jeni bij, Perëndia dërgoi Frymën e Birit të tij në zemrat tuaja që thërret: ''Abba, Atë!''.",
        7: 'Prandaj ti nuk je më shërbëtor, por bir; dhe në qoftë se je bir, je edhe trashëgimtar i Perëndisë me anë të Krishtit.',
        8: 'Por atëherë, duke mos njohur Perëndinë, u shërbyet atyre që prej natyre nuk janë perëndi;',
        9: "kurse tani, mbasi njohët Perëndinë, më mirë të them se u njohët prej Perëndisë, vallë si ktheheni përsëri te elementet e dobët dhe të varfër, tek të cilët doni përsëri t'u nënshtroheni?",
        10: 'Sepse ju i kremtoni me kujdes disa ditë, muaj, stinë dhe vite.',
        11: 'Kam frikë se mos jam munduar më kot për ju.',
        12: "O vëllezër, bëhuni si unë, sepse edhe unë jam si ju; ju lutem, o vëllezër, ju s'më keni bërë asnjë të keqe.",
        13: 'Dhe ju e dini se në të kaluarën unë ju predikova ungjillin me dobësi të mishit;',
        14: "dhe ju nuk më përbuzët aspak dhe s'patët neveri për provën që ishte në mishin tim, por më pranuat si engjëll Perëndie, si Jezu Krishtin vet.",
        15: "Cili ishte, pra, gëzimi juaj? Sepse unë dëshmoj për ju se, po të qe e mundur, ju do të nxirrnit edhe sytë tuaj dhe do të m'i jepnit mua.",
        16: 'A thua u bëra armiku juaj, duke ju thënë të vërtetën?',
        17: "Ata tregohen të zellshëm ndaj jush, por jo për qëllime të ndershme; madje ata duan t'ju shkëputin që të jeni të zellshëm ndaj tyre.",
        18: 'Mirë është të jesh gjithnjë i zellshëm për të mirë, dhe jo vetëm kur ndodhem midis jush.',
        19: 'Djemtë e mi, që unë i lind përsëri, derisa të formohet Krishti në ju!',
        20: 'Do të doja tashti të isha midis jush dhe ta ndryshoja tingullin e zërit tim, sepse jam ndërdyshas ndaj jush.',
        21: 'Po më thoni, ju që doni të jeni nën ligj, a nuk e dëgjoni ligjin?',
        22: 'Sepse është shkruar se Abrahami pati dy bij: një nga shërbëtorja dhe tjetri nga e lira.',
        23: 'Dhe ai që lindi nga shërbëtorja lindi sipas mishit, por ai që lindi nga e lira lindi për hir të premtimit.',
        24: 'Këto gjëra kanë një kuptim alegorik, sepse këto dy gra janë dy besëlidhje: një nga mali Sinai, që ngjiz për skllavëri, dhe është Agari.',
        25: 'Dhe Agari është mali Sinai në Arabi dhe i përgjigjet Jeruzalemit të kohës së sotme; dhe ajo është skllave me bijtë e saj.',
        26: 'Ndërsa Jeruzalemi nga lart është i lirë dhe është nëna e ne të gjithëve.',
        27: "Sepse është shkruar: ''Gëzohu ti, o shterpë, që nuk lind! Shpërthe dhe klith, ti që nuk i provon dhembjet e lindjes, sepse bijtë e së braktisurës do të jenë më të shumtë se të asaj që e kishte burrin''.",
        28: 'Kurse ne, o vëllezër, jemi bij të premtimit, sikundër ishte Isaku.',
        29: 'Po, sikurse atëherë ai që lindi sipas mishit përndiqte atë që kishte lindur sipas Frymës, kështu është edhe tani.',
        30: "Po çfarë thotë shkrimi? ''Dëboje skllaven dhe djalin e saj, sepse i biri i skllaves nuk mund të jetë trashëgimtar bashkë me djalin e së lirës''.",
        31: 'Kështu, pra, vëllezër, ne nuk jemi bij të skllaves, por të së lirës.',
    },
    5: {
        1: 'Qëndroni, pra, të patundur në lirinë, me të cilën Krishti na liroi, dhe mos hyni përsëri nën zgjedhën e skllavërisë.',
        2: "Ja, unë, Pali, po ju them se, në qoftë se rrethpriteni, Krishti nuk do t'ju bëjë dobi aspak.",
        3: 'Edhe i dëshmoj përsëri çdo njeriu që rrethpritet, se ai është i detyruar të zbatojë mbarë ligjin.',
        4: 'Ju që kërkoni të shfajësoheni me anë të ligjit, jeni ndarë nga Krishti; ratë poshtë nga hiri.',
        5: 'Ne në fakt në Frymë, nëpërmjet besimit presim shpresën e drejtësisë,',
        6: "sepse në Jezu Krishtin, as rrethprerja, as parrethprerja s'kanë ndonjë vlerë, por besimi që vepron me anë dashurie.",
        7: 'Ju vraponit bukur; kush ju ka penguar që të mos i bindeni së vërtetës?',
        8: 'Kjo bindje nuk vjen nga ai që ju thërret.',
        9: 'Pak maja e bën të vijë gjithë brumin.',
        10: 'Kam besim te Perëndia për ju, se nuk do të mendoni ndryshe; por ai që ju turbullon juve, kushdo qoftë, do të marrë dënimin.',
        11: 'Sa për mua, o vëllezër, në qoftë se unë vazhdoj të predikoj rrethprerjen, përse më përndjekin akoma? Atëherë skandali i kryqit ra poshtë.',
        12: 'Oh, sikur ata që ju turbullojnë, të gjymtoheshin vetë!',
        13: "Sepse ju, o vëllezër, u thirrët në liri; por mos e përdorni këtë liri si një rast për mishin, por, me dashuri t'i shërbeni njëri-tjetrit.",
        14: "Sepse gjithë ligji përmblidhet në këtë fjalë, të vetme: ''Duaje të afërmin tënd porsi vetveten!''.",
        15: 'Sepse nëse ju kafshoni dhe hani njëri-tjetrin, ruhuni mos prisheni njëri nga tjetri.',
        16: 'Dhe unë them: Ecni sipas Frymës dhe nuk do ta përmbushni dëshirat e mishit,',
        17: 'sepse mishi ka dëshira kundër Frymës, dhe Fryma ka dëshira kundër mishit; dhe këto janë të kundërta me njëra-tjetrën, që ju të mos bëni ato që dëshironi.',
        18: 'Por në qoftë se udhëhiqeni nga Fryma, ju nuk jeni nën ligj.',
        19: 'Dhe veprat e mishit janë të zbuluar dhe janë: kurorëshkelja, kurvëria, ndyrësia, shthurja,',
        20: 'idhujtaria, magjia, armiqësimi, grindjet, xhelozitë, mëritë, zënkat, përçarjet, tarafet,',
        21: 'smira, vrasjet, të dehurit, grykësia dhe gjëra të ngjashme me këto, për të cilat po ju paralajmëroj, si kurse ju thashë edhe më parë, se ata që i bëjnë këto gjëra nuk do të trashëgojnë mbretërinë e Perëndisë.',
        22: 'Por fryti i Frymës është: dashuria, gëzimi, paqja, durimi, mirëdashja, mirësia, besimi, zemërbutësia, vetëkontrolli.',
        23: 'Kundër këtyre gjërave nuk ka ligj.',
        24: 'Edhe ata që janë të Krishtit e kanë kryqëzuar mishin bashkë me pasionet dhe lakmitë të tij.',
        25: 'Në qoftë se rrojmë në Frymë, në Frymë edhe duhet të ecim.',
        26: 'Le të mos jemi mburravecë, duke provokuar dhe duke pasur smirë njëri-tjetrin.',
    },
    6: {
        1: 'Vëllezër, në qoftë se dikush bie në ndonjë faj, ju që jeni frymëror, lartësojeni me frymë butësie. Por ki kujdes veten tënde, se mos tundohesh edhe ti.',
        2: 'Mbani barrët e njëri-tjetrit dhe kështu do të përmbushni ligjin e Krishtit.',
        3: 'Sepse në qoftë se dikush mendon se është diçka, pa qenë asgjë, ai gënjen veten e vet.',
        4: 'Dhe secili të analizojë veprën e tij dhe atëherë do të ketë arsye të mburret vetëm për veten e tij dhe jo lidhur me tjetrin.',
        5: 'Sepse secili do të mbajë barrën e vet.',
        6: 'Ai që merr mësim në fjalën, le ta bëjë pjestar të të gjitha të mirave të tij atë që e mëson.',
        7: "Mos u gënjeni: Perëndia nuk vihet dot në lojë, sepse ç'të mbjellë njeriu, atë edhe do të korrë.",
        8: 'Sepse ai që mbjell për mish të tij, do të korrë nga mishi i tij prishje, por ai që mbjell për Frymë, do të korrë nga Fryma jetë të përjetshme.',
        9: 'Le të mos lodhemi duke bërë të mirën; sepse, po të mos lodhemi, do të korrim në kohën e vet.',
        10: "Prandaj, sa të kemi rast, le t'u bëjmë të mirën të gjithëve, por në radhë të parë atyre që janë në familjen e besimit.",
        11: 'Shikoni me çfarë shkronjash të mëdha ju kam shkruar me dorën time!',
        12: 'Të gjithë ata që duan të duken të mirë në mish, ju shtrëngojnë që të rrethpriteni vetëm që të mos përndiqeni për kryqin e Krishtit.',
        13: 'Sepse as vetë ata që rrethpriten nuk e zbatojnë ligjin, por duan që ju të rrethpriteni, që ata të mburren në mishin tuaj.',
        14: 'Sa për mua, mos ndodhtë kurrë që unë të mburrem me tjetër gjë, veç për kryqin e Zotit tonë Jezu Krisht, për të cilin bota është kryqëzuar tek unë edhe unë te bota.',
        15: "Sepse në Jezu Krishtin as rrethprerja, as parrethprerja s'kanë ndonjë vlerë, por krijesa e re.",
        16: 'Dhe të gjithë ata që do të ecin sipas kësaj rregulle paçin paqe dhe mëshirë, e ashtu qoftë edhe për Izraelin e Perëndisë.',
        17: 'Tash e tutje askush të mos më trazojë, sepse unë mbaj në trupin tim shenjat e Zotit Jezus.',
        18: 'Vëllezër, hiri i Zotit tonë Jezu Krisht qoftë me frymën tuaj. Amen.',
    },
}
