NAME = 'FinSTLK2017: Pyhä Raamattu (STLK 2017)'
BOOK = 'Galatians'

CHAPTERS = {
    1: {
        1: 'Paavali, apostoli, ei ihmisten toimesta eikä ihmisen kautta, vaan Jeesuksen Kristuksen kautta ja Isän Jumalan, joka on hänet kuolleista herättänyt,',
        2: 'ja kaikki veljet, jotka ovat kanssani, Galatian seurakunnille.',
        3: 'Armo teille ja rauha Jumalalta, Isältämme, ja Herralta Jeesukselta Kristukselta,',
        4: 'joka antoi itsensä alttiiksi syntiemme tähden pelastaakseen meidät nykyisestä pahasta maailmanajasta Jumalamme ja Isämme tahdon mukaan!',
        5: 'Hänelle kunnia iäisyyksien iäisyyksiin! Aamen.',
        6: 'Ihmettelen, että te niin äkkiä käännytte hänestä, joka on kutsunut teidät Kristuksen armossa, pois toiseen evankeliumiin,',
        7: 'joka ei ole toinen. On vain eräitä, jotka hämäävät teitä ja tahtovat muuttaa Kristuksen evankeliumin.',
        8: 'Mutta vaikka me, tai vaikka enkeli taivaasta julistaisi teille evankeliumia toisin kuin me olemme teille julistaneet, hän olkoon kirottu.',
        9: 'Niin kuin olemme ennenkin sanoneet, ja taas nytkin sanon: jos joku julistaa teille evankeliumia vastoin sitä, minkä te olette saaneet, hän olkoon kirottu.',
        10: 'Sillä etsinkö nyt ihmisten suosiota vai Jumalan? Vai ihmisillekö pyrin olemaan mieliksi? Jos vielä olen ihmisten mieliksi, en ole Kristuksen palvelija.',
        11: 'Sillä teen teille tiettäväksi, veljet, että julistamani evankeliumi ei ole ihmisten mukainen,',
        12: 'sillä en olekaan sitä ihmisiltä saanut enkä oppinut, vaan Jeesuksen Kristuksen ilmestyksen kautta.',
        13: 'Olettehan kuulleet aikaisemmasta vaelluksestani juutalaisuudessa, että vainosin ylenmäärin Jumalan seurakuntaa ja hävitin sitä',
        14: 'ja että edistyin juutalaisuudessa pidemmälle kuin monet samanikäiset heimossani ja kiivailin hyvin innokkaasti isieni perinnäissääntöjen puolesta.',
        15: 'Mutta kun hän, joka äitini kohdusta saakka on minut erottanut ja kutsunut armonsa kautta, näki hyväksi',
        16: 'ilmoittaa minussa Poikansa, että julistaisin evankeliumia hänestä pakanoiden seassa, niin en ensinkään kysynyt neuvoa lihalta ja vereltä,',
        17: 'enkä lähtenyt ylös Jerusalemiin niiden luo, jotka ennen minua olivat apostoleja, vaan menin pois Arabiaan ja palasin taas Damaskoon.',
        18: 'Sitten, kolmen vuoden kuluttua, menin ylös Jerusalemiin tutustuakseni Keefaaseen ja viivyin hänen luonaan viisitoista päivää.',
        19: 'Mutta ketään toista apostolia en nähnyt paitsi Jaakobin, Herran veljen.',
        20: 'Sen, minkä teille kirjoitan, katso, kirjoitan Jumalan edessä, sillä en valehtele.',
        21: 'Sitten menin Syyrian ja Kilikian seudulle.',
        22: 'Mutta olin kasvoiltani tuntematon Juudean seurakunnille, jotka ovat Kristuksessa.',
        23: 'He olivat vain kuulleet: "Meidän entinen vainoojamme julistaa nyt sitä uskoa, jota hän ennen hävitti",',
        24: 'ja he ylistivät Jumalaa minun tähteni.',
    },
    2: {
        1: 'Sitten neljäntoista vuoden kuluttua menin taas ylös Jerusalemiin Barnabaan kanssa ja otin mukaani Tiituksenkin.',
        2: 'Mutta menin sinne ilmestyksen johdosta ja esitin heille sen evankeliumin, jota julistan pakanoiden keskuudessa. Esitin sen yksityisesti heistä arvostetuimmille, etten ehkä juoksisi tai olisi juossut turhaan.',
        3: 'Mutta ei edes Tiitusta, joka oli kanssani ja oli kreikkalainen, pakotettu ympärileikkauttamaan itseään.',
        4: 'Noiden sisään tunkeutuneiden valheveljien tähden, jotka orjuuttaakseen meitä olivat tulleet salaa vakoilemaan vapauttamme, mikä meillä on Kristuksessa Jeesuksessa,',
        5: 'emme hetkeksikään alistuneet antamaan heille myöden, jotta evankeliumin totuus säilyisi keskuudessanne.',
        6: 'Mutta noista arvostetuista – millaisia olivat ennen olleetkin, ei kuulu minulle, Jumala ei katso henkilöön – nuo arvossapidetyt eivät lisänneet siihen mitään,',
        7: 'vaan päinvastoin, kun näkivät, että minulle oli uskottu evankeliumin julistaminen ympärileikkaamattomille, samoin kuin Pietarille sen julistaminen ympärileikatuille –',
        8: 'sillä hän, joka antoi Pietarille voimaa hänen apostolinvirkaansa ympärileikattujen keskuudessa, antoi minullekin siihen voimaa pakanoiden parissa –',
        9: 'ja kun olivat tulleet tuntemaan sen armon, mikä minulle oli annettu, niin Jaakob, Keefas ja Johannes, joita pidettiin pylväinä, antoivat minulle ja Barnabaalle kättä yhteyden merkkinä sopien, että me teemme työtä pakanoille ja he ympärileikatuille.',
        10: 'Meidän tuli vain muistaa köyhiä, ja sitä olenkin ahkeroinut tehdä.',
        11: 'Mutta kun Keefas tuli Antiokiaan, vastustin häntä julkisesti, koska häntä vastaan oli esitetty syytöksiä.',
        12: 'Sillä ennen kuin Jaakobin luota oli tullut muutamia miehiä, hän oli syönyt yhdessä pakanoiden kanssa, mutta heidän tultuaan hän vetäytyi pois ja pysytteli erillään peläten ympärileikattuja,',
        13: 'ja hänen kanssaan lankesivat ulkokultaisuuteen muutkin juutalaiset, niin että heidän ulkokultaisuutensa tempasi mukaansa Barnabaankin.',
        14: 'Mutta kun näin, etteivät he vaeltaneet suoraan evankeliumin totuuden mukaan, sanoin Keefaalle kaikkien edessä: "Jos sinä, joka olet juutalainen, noudatat pakanoiden tapoja etkä juutalaisten, miksi pakotat pakanoita noudattamaan juutalaisten tapoja?"',
        15: 'Me olemme luonnostamme juutalaisia emmekä pakanasyntisiä.',
        16: 'Mutta koska tiedämme, ettei ihmistä julisteta vanhurskaaksi lain teoista, vaan uskon kautta Jeesukseen Kristukseen, mekin olemme uskoneet Kristukseen Jeesukseen, että meidät julistettaisiin vanhurskaiksi uskosta Kristukseen eikä lain teoista, koska mitään lihaa ei julisteta vanhurskaaksi lain teoista.',
        17: 'Mutta jos meidät itsemmekin on havaittu syntisiksi tavoitellessamme sitä, että meidät julistetaan vanhurskaiksi Kristuksessa, onko sitten Kristus synnin palvelija? Ei ikinä!',
        18: 'Sillä jos uudestaan rakennan sitä, minkä olen hajottanut maahan, osoitan olevani lainrikkoja.',
        19: 'Sillä minä olen lain kautta kuollut pois laista, jotta eläisin Jumalalle.',
        20: 'Olen Kristuksen kanssa ristiinnaulittu, mutta elän, en enää minä, vaan Kristus elää minussa, ja minkä nyt elän lihassa, sen elän uskossa Jumalan Poikaan, häneen, joka on rakastanut minua ja antanut itsensä minun edestäni.',
        21: 'En tee mitättömäksi Jumalan armoa, sillä jos vanhurskaus on lain kautta, silloin Kristus on turhaan kuollut.',
    },
    3: {
        1: 'Voi teitä, te typerät galatalaiset! Kuka on lumonnut teidät luottamasta totuuteen, teidät, joiden silmien eteen Jeesus Kristus oli kirjoitettu ristiinnaulittuna?',
        2: 'Tahdon saada teiltä tietää vain tämän: lain teoistako saitte Hengen vai uskon saarnasta?',
        3: 'Niinkö typeriä olette? Te aloititte Hengessä, lihassako nyt lopetatte?',
        4: 'Niin paljonko olette turhaan kärsineet? – jos se on ollut turhaa.',
        5: 'Joka siis antaa teille Hengen ja tekee voimatekoja keskuudessanne, saako hän sen aikaan lailla vai uskon saarnalla,',
        6: 'samalla tavalla kuin "Aabraham uskoi Jumalaa, ja se luettiin hänelle vanhurskaudeksi"?',
        7: 'Tietäkää siis, että ne, jotka ovat uskosta, ovat Aabrahamin lapsia.',
        8: 'Raamatun nähdessä edeltä, että Jumala lukee pakanat vanhurskaiksi uskosta, se julisti Aabrahamille edeltä tämän hyvän sanoman: "Sinussa kaikki kansat tulevat siunatuiksi."',
        9: 'Näin ollen ne, jotka ovat uskosta, siunataan uskovan Aabrahamin kanssa.',
        10: 'Sillä kaikki, jotka ovat lain teoista, ovat kirouksen alaisia, sillä kirjoitettu on: "Kirottu on jokainen, joka ei pysy kaikessa, mikä on kirjoitettuna lain kirjassa, niin että hän sen tekee."',
        11: 'Selvää on, ettei ketään julisteta vanhurskaaksi Jumalan edessä lain kautta, koska "vanhurskas on elävä uskosta."',
        12: 'Mutta laki ei ole uskosta, vaan: "Se, joka ne täyttää, on niistä elävä."',
        13: 'Kristus on lunastanut meidät lain kirouksesta, kun hän tuli kiroukseksi edestämme – sillä kirjoitettu on: "Kirottu on jokainen, joka on puuhun ripustettu " –',
        14: 'että Aabrahamin siunaus tulisi Jeesuksessa Kristuksessa pakanoiden osaksi ja uskon kautta saisimme luvatun Hengen.',
        15: 'Veljet, puhun ihmisten tavalla. Eihän kukaan voi kumota ihmisenkään vahvistettua testamenttia eikä siihen mitään lisätä.',
        16: 'Mutta nyt lausuttiin lupaukset Aabrahamille ja hänen siemenelleen. Hän ei sano: "Ja siemenille", ikään kuin monesta, vaan ikään kuin yhdestä: "Ja sinun siemenellesi", joka on Kristus.',
        17: 'Tarkoitan tätä: Jumalan ennen vahvistamaa testamenttia ei neljänsadan kolmenkymmenen vuoden perästä tullut laki voi kumota, niin että se tekisi lupauksen mitättömäksi.',
        18: 'Sillä jos perintö olisi laista, se ei olisi lupauksesta. Mutta Aabrahamille Jumala on lahjoittanut sen lupauksen kautta.',
        19: 'Mitä varten sitten on laki? Se on rikosten tähden perästäpäin lisätty olemaan siihen asti, kunnes oli tuleva se siemen, jolle lupaus oli annettu. Se säädettiin enkelien kautta, välimiehen kädellä.',
        20: 'Välimies taas ei ole yhtä varten, mutta Jumala on yksi.',
        21: 'Onko sitten laki vastoin Jumalan lupauksia? Ei ikinä! Sillä jos olisi annettu laki, joka voisi tehdä eläväksi, niin vanhurskaus olisi laista.',
        22: 'Mutta Raamattu on sulkenut kaikki synnin alle, että lupaus uskosta Jeesukseen Kristukseen annettaisiin niille, jotka uskovat.',
        23: 'Mutta ennen kuin usko tuli, vartioitiin meitä lain alle suljettuina tulevaa uskoa varten, joka oli vastedes ilmestyvä.',
        24: 'Niin ollen laista on tullut meille kurittaja Kristukseen, että meidät julistettaisiin uskosta vanhurskaiksi.',
        25: 'Mutta uskon tultua me emme enää ole kurittajan alaisia.',
        26: 'Sillä te olette kaikki uskon kautta Jumalan lapsia Kristuksessa Jeesuksessa.',
        27: 'Sillä kaikki te, jotka olette Kristukseen kastetut, olette Kristuksen päällenne pukeneet.',
        28: 'Ei ole tässä juutalaista eikä kreikkalaista, ei ole orjaa eikä vapaata, ei ole miestä eikä naista, sillä kaikki te olette yksi Kristuksessa Jeesuksessa.',
        29: 'Mutta jos te olette Kristuksen omat, olette siis Aabrahamin siementä ja perillisiä lupauksen mukaan.',
    },
    4: {
        1: 'Mutta sanon: niin kauan kuin perillinen on alaikäinen, hän ei missään kohden eroa orjasta, vaikka onkin kaiken herra,',
        2: 'vaan hän on holhoojien ja taloudenhoitajien alainen isän määräämään aikaan asti.',
        3: 'Samoin mekin, kun olimme alaikäisiä, olimme orjuutetut maailman alkeisvoimien alle.',
        4: 'Mutta kun aika täyttyi, Jumala lähetti Poikansa, vaimosta syntyneen, lain alaiseksi syntyneen,',
        5: 'lunastamaan lain alaiset, että saisimme lapsen aseman.',
        6: 'Mutta koska olette lapsia, Jumala on lähettänyt sydämiinne Poikansa Hengen, joka huutaa: "Abba! Isä!"',
        7: 'Niinpä et siis enää ole orja, vaan lapsi. Mutta jos olet lapsi, olet myös perillinen Jumalan kautta.',
        8: 'Mutta silloin, kun ette tunteneet Jumalaa, palvelitte jumalia, jotka eivät ole luonnoltaan jumalia.',
        9: 'Nyt sitä vastoin, kun olette tulleet tuntemaan Jumalan – paremminkin, kun Jumala tuntee teidät, – kuinka te jälleen käännytte noiden heikkojen ja köyhien alkeisvoimien puoleen, joiden orjiksi tahdotte taas uudestaan tulla?',
        10: 'Te otatte vaarin päivistä, kuukausista, juhla-ajoista ja vuosista.',
        11: 'Pelkään teidän tähtenne, että olen ehkä nähnyt turhaan teistä vaivaa.',
        12: 'Tulkaa kaltaisikseni, koska minäkin olen kuin te, veljet, sitä teiltä pyydän. Ette ole minua millään tavoin loukanneet.',
        13: 'Tiedättehän, että lihan heikkouden tähden ensi kerralla julistin teille evankeliumia.',
        14: 'Mutta te ette halveksineet ettekä hylkineet minun koetustani lihassa, vaan otitte minut vastaan kuin Jumalan enkelin, jopa kuin Kristuksen Jeesuksen.',
        15: 'Kuinka autuaita te silloin olitte? Sillä minä annan teistä sen todistuksen, että te, jos olisi ollut mahdollista, olisitte kaivaneet silmät päästänne ja antaneet minulle.',
        16: 'Onko minusta siis tullut teidän vihamiehenne sen tähden, että puhun teille totuuden?',
        17: 'Heillä on intoa teidän hyväksenne, mutta ei oikeaa, vaan he tahtovat eristää teidät, että teillä olisi intoa heidän hyväkseen.',
        18: 'On hyvä olla innokas aina hyvässä, eikä ainoastaan silloin, kun olen teidän luonanne.',
        19: 'Lapsukaiseni, jotka minun täytyy jälleen kivulla synnyttää, kunnes Kristus saa muodon teissä,',
        20: 'tahtoisinpa nyt olla teidän luonanne ja äänenikin muuttaa! Sillä olen teistä aivan ymmällä.',
        21: 'Sanokaa minulle te, jotka tahdotte olla lain alaisia, ettekö kuule lakia?',
        22: 'Onhan kirjoitettu, että Aabrahamilla oli kaksi poikaa, toinen orjattaresta, toinen vapaasta.',
        23: 'Mutta orjattaren poika oli syntynyt lihan mukaan, vapaan taas lupauksen kautta.',
        24: 'Tämä on kuvaannollista puhetta: naiset ovat kaksi liittoa: toinen on Siinain vuorelta, joka synnyttää orjuuteen, ja se on Haagar.',
        25: 'Haagar on näet Siinain vuori Arabiassa ja vastaa nykyistä Jerusalemia, joka elää orjuudessa lapsineen.',
        26: 'Mutta se Jerusalem, joka ylhäällä on, on vapaa, ja se on meidän äitimme.',
        27: 'Sillä kirjoitettu on: "Iloitse, sinä hedelmätön, joka et synnytä, puhkea riemuun ja huuda sinä, jolla ei ole synnytyskipuja. Sillä yksinäisellä on paljon lapsia, enemmän kuin sillä, jolla on mies."',
        28: 'Mutta me, veljet, olemme Iisakin mukaan lupauksen lapsia.',
        29: 'Mutta niin kuin lihan mukaan syntynyt silloin vainosi Hengen mukaan syntynyttä, niin nytkin.',
        30: 'Mutta mitä sanoo Raamattu? "Aja pois orjatar poikineen, sillä orjattaren poika ei saa periä vapaan vaimon pojan kanssa."',
        31: 'Niin siis, veljet, emme ole orjattaren lapsia, vaan vapaan.',
    },
    5: {
        1: 'Vapauteen Kristus siis vapautti meidät. Seisokaa lujina, älkääkä antako uudestaan sitoa itseänne orjuuden ikeeseen.',
        2: 'Katso, minä, Paavali, sanon teille, että jos ympärileikkautatte itsenne, Kristus ei ole teille miksikään hyödyksi.',
        3: 'Mutta todistan taas jokaiselle ihmiselle, joka ympärileikkauttaa itsensä, että hän on velvollinen täyttämään koko lain.',
        4: 'Olette joutuneet pois Kristuksesta, te, jotka tahdotte lain kautta tulla vanhurskaiksi, olette langenneet pois armosta.',
        5: 'Sillä me odotamme Hengessä uskosta vanhurskauden toivoa.',
        6: 'Sillä Kristuksessa Jeesuksessa ei auta ympärileikkaus eikä ympärileikkaamattomuus, vaan usko, joka vaikuttaa rakkauden kautta.',
        7: 'Te juoksitte hyvin, kuka esti teitä noudattamasta totuutta?',
        8: 'Houkutus siihen ei ole hänestä, joka teitä kutsuu.',
        9: 'Vähäinen hapate hapattaa koko taikinan.',
        10: 'Minulla on teihin se luottamus Herrassa, ettette missään kohden tule ajattelemaan toisin. Mutta teidän eksyttäjänne saa kantaa tuomionsa, olkoon kuka hyvänsä.',
        11: 'Mutta jos minä, veljet, vielä saarnaan ympärileikkausta, miksi minua vielä vainotaan? Silloinhan ristin pahennus olisi poistettu.',
        12: 'Kunpa teidän kiihottajanne leikkaisivat itsensä pois!',
        13: 'Te olette näet kutsutut vapauteen, veljet, älkää vain salliko vapauden tuoda tilaisuutta lihalle, vaan palvelkaa toisianne rakkaudessa.',
        14: 'Sillä kaikki laki on täytetty yhdessä sanassa, tässä: "Rakasta lähimmäistäsi niin kuin itseäsi."',
        15: 'Mutta jos te purette ja syötte toisianne, katsokaa, ettette toinen toistanne hävitä.',
        16: 'Sanon: vaeltakaa Hengessä, niin ette lihan himoa täytä.',
        17: 'Sillä liha himoitsee Henkeä vastaan, ja Henki lihaa vastaan. Nämä ovat nimittäin toisiaan vastaan, niin ettette tee sitä, mitä tahdotte.',
        18: 'Mutta jos olette Hengen kuljetettavina, ette ole lain alla.',
        19: 'Mutta lihan teot ovat ilmeiset, ja niitä ovat: aviorikos, haureus, saastaisuus, irstaus,',
        20: 'epäjumalanpalvelus, noituus, vihamielisyys, riita, kateuden teot, vihat, juonet, eriseurat, lahkot,',
        21: 'kateus, juomingit, ylensyömiset ja muut sellaiset, joista teille edeltäpäin sanon, niin kuin jo ennenkin olen sanonut, että ne, jotka sellaista harjoittavat, eivät peri Jumalan valtakuntaa.',
        22: 'Mutta Hengen hedelmä on rakkaus, ilo, rauha, pitkämielisyys, ystävällisyys, hyvyys, uskollisuus, sävyisyys, itsehillintä.',
        23: 'Sellaista vastaan ei ole laki.',
        24: 'Mutta ne, jotka ovat Kristuksen Jeesuksen omat, ovat ristiinnaulinneet lihansa himoineen ja haluineen.',
        25: 'Jos Hengessä elämme, Hengessä myös vaeltakaamme.',
        26: 'Älkäämme olko turhan kunnian pyytäjiä, niin että toisiamme ärsytämme, toisiamme kadehdimme.',
    },
    6: {
        1: 'Veljet, jos joku tavataan jostakin rikoksesta, ojentakaa te, hengelliset, häntä sävyisyyden hengessä, ja ole varuillasi, ettet sinäkin joutuisi kiusaukseen.',
        2: 'Kantakaa toistenne kuormia, ja niin täytätte Kristuksen lain.',
        3: 'Sillä jos joku luulee olevansa jotakin, vaikka ei ole mitään, hän pettää itsensä.',
        4: 'Mutta tutkikoon kukin omat tekonsa, ja silloin hänen kerskaamisensa on vain siinä, mitä hän itse on, ei siinä, mitä toinen on,',
        5: 'sillä jokaisen on kannettava oma taakkansa.',
        6: 'Mutta se, jolle sanaa opetetaan, jakakoon kaikkea hyvää opettajalleen.',
        7: 'Älkää eksykö, Jumala ei salli itseään pilkata, sillä mitä ihminen kylvää, sitä hän myös niittää.',
        8: 'Se, joka lihaansa kylvää, lihasta turmeluksen niittää, mutta se, joka Henkeen kylvää, Hengestä iankaikkisen elämän niittää.',
        9: 'Kun hyvää teemme, älkäämme lannistuko, sillä saamme ajan tullen niittää, jos emme väsy.',
        10: 'Sen tähden, kun meillä vielä on aikaa, tehkäämme hyvää kaikille, mutta varsinkin uskon perheväelle.',
        11: 'Katsokaa, kuinka suurilla kirjaimilla omakätisesti teille kirjoitan!',
        12: 'Kaikki ne, jotka pyrkivät lihassa olemaan mieliksi, pakottavat teitä ympärileikkauttamaan itsenne vain siksi, ettei heitä Kristuksen ristin tähden vainottaisi.',
        13: 'Eiväthän nekään, jotka ympärileikkauttavat itsensä, itse noudata lakia, vaan he tahtovat teitä ympärileikkauttamaan itsenne saadakseen kerskua lihastanne.',
        14: 'Mutta pois se minusta, että minä muusta kerskaan kuin meidän Herramme Jeesuksen Kristuksen rististä, jonka kautta maailma on ristiinnaulittu minulle, ja minä maailmalle!',
        15: 'Sillä Kristuksessa Jeesuksessa ei ympärileikkaus ole mitään eikä ympärileikkaamattomuus, vaan uusi luomus.',
        16: 'Kaikille, jotka tämän säännön mukaan vaeltavat, kaikille heille rauha ja laupeus, ja Jumalan Israelille!',
        17: 'Tästedes älköön kukaan tuottako minulle vaivoja, sillä minä kannan Jeesuksen arpia ruumiissani.',
        18: 'Meidän Herramme Jeesuksen Kristuksen armo olkoon teidän henkenne kanssa, veljet. Aamen.',
    },
}
