NAME = 'GerGruenewald: 1924 Grünewaldbibel'
BOOK = 'Galatians'

CHAPTERS = {
    1: {
        1: 'Paulus, Apostel nicht von Menschen noch durch Menschen, vielmehr durch Jesus Christus und durch Gott den Vater, der ihn von den Toten auferweckt hat,',
        2: 'und alle Brüder, die bei mir sind, an die Gemeinden in Galatien.',
        3: 'Gnade werde euch zuteil und Friede von Gott, unserem Vater, und von dem Herrn Jesus Christus,',
        4: 'der sich selbst für unsere Sünden hingegeben hat, um uns aus dieser bösen Welt -zeit zu retten. So ist auch der Wille unseres Gottes und Vaters,',
        5: 'dem Ehre ist von Ewigkeit zu Ewigkeiten. Amen.',
        6: 'Ich wundere mich, daß ihr so schnell euch abwendig machen laßt von dem, der euch in der Gnade Christi berufen hat, zu einem anderen Evangelium.',
        7: 'Es gibt doch kein anderes. Allein, manche wollen euch verwirren und das Evangelium Christi verfälschen.',
        8: 'Doch wenn wir selbst oder sogar ein Engel vom Himmel das Evangelium euch anders verkündeten, als wir es euch verkündet haben, der sei verflucht!',
        9: 'Ich wiederhole, was ich eben sagte: Wer euch das Evangelium anders predigt, als ihr es empfangen habt, der sei verflucht!',
        10: 'Rede ich jetzt Menschen oder Gott zulieb? Suche ich etwa Menschen zu gefallen? Wenn ich noch Menschen zu gefallen suchte, dann wäre ich nicht Christi Knecht.',
        11: 'Liebe Brüder, ich versichere euch: Das Evangelium, das ich verkünde, ist nicht Menschenwerk.',
        12: 'Denn nicht von einem Menschen habe ich es übernommen, auch nicht durch Unterricht gelernt, sondern durch Offenbarung Jesu Christi.',
        13: 'Ihr habt von meinem früheren Wandel im Judentum gehört, wie ich die Gemeinde Gottes über die Maßen verfolgte und sie zugrunde zu richten suchte.',
        14: 'Ich zeichnete mich an jüdischer Gesinnungstüchtigkeit vor vielen meiner Altersgenossen in meinem Volke aus und eiferte ganz übertrieben für die väterlichen Überlieferungen.',
        15: 'Doch da gefiel es dem, der mich vom Mutterschoß an ausersehen und mich kraft seiner Gnade berufen hat,',
        16: 'in mir seinen Sohn zu offenbaren, damit ich ihn der Heidenwelt verkünde. Von Anfang an zog ich nicht Fleisch und Blut zu Rate,',
        17: 'noch ging ich nach Jerusalem hinauf zu denen, die vor mir Apostel waren; nein, ich ging fort nach Arabien und kam dann wieder nach Damaskus.',
        18: 'Erst dann, drei Jahre später, ging ich nach Jerusalem, um dort Kephas persönlich kennenzulernen. Ich hielt mich vierzehn Tage bei ihm auf.',
        19: 'Sonst sah ich keinen der anderen Apostel, den Jakobus, den Bruder des Herrn, ausgenommen.',
        20: 'Was ich da schreibe - ich bezeuge es vor Gott -, ist keine Lüge.',
        21: 'Darauf kam ich in die Gegenden von Syrien und Cilizien.',
        22: 'Den Christengemeinden in Judäa blieb ich also persönlich unbekannt.',
        23: 'Sie hatten nur gehört: Der einstens uns verfolgt hat, verkündet jetzt den Glauben, den er vorher zu vernichten suchte.',
        24: 'Und sie priesen Gott um meinetwillen.',
    },
    2: {
        1: 'Vierzehn Jahre später ging ich wieder nach Jerusalem hinauf mit Barnabas; auch Titus nahm ich mit.',
        2: 'Ich unternahm die Reise auf eine Offenbarung hin. Ich legte ihnen das Evangelium vor, das ich bei den Heiden verkündige. Ganz besonders tat ich es vor den Maßgebenden; ich wollte nämlich nicht vergeblich laufen oder gelaufen sein.',
        3: 'Doch nicht einmal mein Begleiter Titus, ein Grieche, ward zum Empfang der Beschneidung angehalten,',
        4: 'obwohl sich falsche Brüder eingeschlichen und eingedrängt hatten. Die lagen auf der Lauer gegen unsere Freiheit, die wir in Christus Jesus besitzen; sie wollten uns zu Sklaven machen.',
        5: 'Doch gaben wir ihnen nicht einen Augenblick nach, daß wir uns etwa unterworfen hätten, damit bei euch das echte Evangelium bleibe.',
        6: 'Von den Maßgebenden - wie immer sie waren, ist mir gleichgültig; vor Gott gibt es kein Ansehen der Person -, die Maßgebenden also haben mir nichts weiter mitgeteilt.',
        7: 'Im Gegenteil, sie haben eingesehen, daß ich mit dem Evangelium für die Unbeschnittenen betraut bin, wie Petrus mit dem für die Beschnittenen.',
        8: 'Denn der dem Petrus seinen Beistand lieh zu dem Apostelwirken unter den Beschnittenen, stand auch mir zur Seite bei den Heiden.',
        9: 'Als sie erkannten, daß mir eine ganz besondere Gnade verliehen ward, da gaben Jakobus, Kephas und Johannes, die doch als "Säulen" gelten, mir und dem Barnabas die rechte Hand zum Zeichen der Gemeinschaft. Wir sollten zu den Heiden, sie wollten darin zu den Beschnittenen gehen;',
        10: 'nur sollten wir der Armen gedenken. Das habe ich auch gewissenhaft getan.',
        11: "Als Kephas nach Antiochien kam, trat ich ihm Aug' in Aug' entgegen; denn er war schon gerichtet.",
        12: 'Bevor nämlich einige aus der Umgebung des Jakobus gekommen waren, pflog er Tischgemeinschaft mit den Heiden. Nach ihrer Ankunft aber zog er sich zurück und sonderte sich von ihnen ab, weil er sich vor den Beschneidungsmännern fürchtete.',
        13: 'Mit ihm verstellten sich dann auch die anderen Juden, ja, Barnabas sogar ließ sich durch ihre Verstellung mitreißen.',
        14: 'Als ich nun sah, daß ihre Handlungsweise dem echten Evangelium nicht entspräche, da sagte ich vor allen anderen zu Kephas: "Wenn du als Jude nach heidnischer und nicht nach jüdischer Gewohnheit lebst, wie magst dann du die Heiden zwingen, die jüdische Gewohnheit anzunehmen?"',
        15: 'Wir sind Juden von Geburt und nicht Sünder aus der Heidenwelt.',
        16: 'Wir wissen aber, daß der Mensch gerecht wird nicht auf Grund von Werken des Gesetzes, sondern durch den Glauben an Jesus Christus. Wir haben ja den Glauben an Christus Jesus angenommen, damit wir gerecht wurden durch den Glauben an Christus und nicht durch Werke des Gesetzes; denn durch Gesetzeswerke wird kein Mensch gerecht.',
        17: 'Doch würden wir bei unserem Streben, in Christus gerecht zu werden, doch also Sünder erfunden, wäre dann nicht Christus Diener der Sünde? Nein, nimmermehr!',
        18: 'Denn wenn ich das, was ich eingerissen habe, von neuem wieder aufbaue, dann erweise ich mich selbst als Übertreter.',
        19: 'Denn durch Gesetz bin ich dem Gesetz abgestorben, um nur für Gott zu leben; mit Christus bin ich an das Kreuz geheftet.',
        20: 'Ich lebe, aber nicht mehr ich, Christus lebt in mir. Soweit ich aber jetzt noch im Fleische lebe, lebe ich im Glauben an den Gottessohn, der mich geliebt und sich selbst für mich geopfert hat.',
        21: 'Ich tue der Gnade Gottes keinen Eintrag; denn wenn Rechtfertigung durch das Gesetz käme, dann wäre Christus umsonst gestorben.',
    },
    3: {
        1: 'Ihr unverständigen Galater! Wer hat euch denn behext der Wahrheit nicht zu gehorchen, euch, denen Jesus Christus vor Augen gezeichnet ward als der Gekreuzigte?',
        2: 'Nur dieses eine möchte ich von euch wissen: Habt ihr den Geist empfangen durch Werke des Gesetzes oder durch die Botschaft des Glaubens?',
        3: 'Seid ihr denn so unverständig? Ihr habt im Geiste begonnen und wolltet nun im Fleisch enden?',
        4: 'So Schweres wolltet ihr umsonst erduldet haben?',
        5: 'Wahrlich, umsonst! Der euch den Geist verleiht und Wunder bei euch wirkt, tut er das der Gesetzeswerke wegen oder aus dem Hören des Glaubens?',
        6: 'Es ist so wie bei Abraham: "Er glaubte Gott, und dies ward ihm als Gerechtigkeit angerechnet."',
        7: 'So wisset denn: die aus dem Glauben stammen, sind Kinder Abrahams.',
        8: 'Da nun die Schrift vorausgesehen hat, daß Gott die Heiden rechtfertige aus dem Glauben, so verkündet sie von vornherein dem Abraham die frohe Kunde: "Alle Völker sollen in dir gesegnet werden."',
        9: 'So werden also die, die aus dem Glauben kommen, mit Abraham, dem Glaubenden, gesegnet.',
        10: 'Denn alle, die sich an Gesetzeswerke halten, stehen unter dem Fluche. Denn also steht geschrieben: "Verflucht sei jeder, der nicht alles treulich hält, was im Buche des Gesetzes vorgeschrieben ist, damit es gehalten werde."',
        11: 'Daß aber niemand durch das Gesetz vor Gott gerecht wird, ist klar, denn: "Der aus dem Glauben Gerechte wird leben."',
        12: 'Das Gesetz jedoch stammt nicht aus dem Glauben, denn also heißt es: "Wer das tut, wird dadurch leben."',
        13: 'Von dem Fluche des Gesetzes hat uns Christus erlöst dadurch, daß er unseretwegen selbst zum Fluche ward, wie denn geschrieben steht: "Verflucht sei jeder, der am Holze hängt.\'',
        14: 'So sollte denn der Segen Abrahams auf die Heiden übergehen in Christus Jesus: wir sollten durch den Glauben den verheißenen Geist empfangen.',
        15: 'Liebe Brüder, ich will ein Gleichnis aus dem Leben bringen: Ein Testament, das rechtsgültig ist, stößt niemand um, noch fügt man ihm einen Zusatz an.',
        16: 'Die Verheißungen wurden aber dem Abraham und seinem Nachkommen zugesagt. Nun heißt es nicht: "den Nachkommen" in der Mehrzahl, vielmehr in der Einzahl: "deinem Nachkommen"; damit ist Christus gemeint.',
        17: 'Ich denke nun, ein Testament, das früher schon durch Gott rechtskräftig ward, kann nicht durch das Gesetz, das erst vierhundertdreißig Jahre später kam, noch umgestoßen werden, so daß die Verheißung dadurch nichtig würde.',
        18: 'Denn würde das Erbe durch Gesetz erlangt, dann käme es nicht mehr durch die Verheißung; dem Abraham jedoch hat Gott es durch Verheißung in Gnaden geschenkt.',
        19: 'Welchen Zweck hat aber dann das Gesetz? Es kam der Sünden wegen dazu, bis der Nachkomme auftreten würde, dem die Verheißung gilt. Durch Engel angeordnet, kam es aus der Hand eines Mittlers.',
        20: 'Ein Mittler ist aber nicht für einen allein da; Gott jedoch ist nur Einer.',
        21: 'So stünde also das Gesetz im Widerspruch zu dem, was Gott verheißen hat? Gewiß nicht. Wenn ein Gesetz gegeben worden wäre, das Leben hätte schaffen können, dann käme in der Tat die Rechtfertigung aus dem Gesetze.',
        22: 'Allein die Schrift hat alles unter Sünde eingeschlossen, damit die Verheißung den Gläubigen gegeben werde auf Grund des Glaubens an Jesus Christus.',
        23: 'Denn bevor der Glaube kam, wurden wir unter dem Gesetz eingeschlossen, im Gewahrsam für den Glauben, der erst geoffenbart werden sollte.',
        24: 'So ward uns das Gesetz ein Erzieher zu Christus, damit wir gerecht würden durch den Glauben.',
        25: 'Da aber jetzt der Glaube gekommen ist, stehen wir nicht mehr unter dem Erzieher.',
        26: 'Denn ihr alle seid Kinder Gottes durch den Glauben an Christus Jesus.',
        27: 'Ihr alle, die ihr auf Christus getauft seid, habt Christus angezogen.',
        28: 'Jetzt gibt es nicht mehr Juden oder Heiden, nicht mehr Sklaven oder Freie, nicht mehr Mann noch Weib; denn ihr alle seid Einer in Christus Jesus.',
        29: 'Wenn ihr aber Christus angehört, dann seid ihr Nachkommen Abrahams und Erben, wie es verheißen ward.',
    },
    4: {
        1: 'Ich sage nun: Solange der Erbe noch nicht mündig ist, unterscheidet er sich in nichts von einem Sklaven, obgleich er Herr von allem ist.',
        2: 'Er steht vielmehr unter Vormündern und Verwaltern bis auf die vom Vater festgesetzte Zeit.',
        3: 'So war es auch bei uns: Solange wir noch nicht mündig waren, lebten wir geknechtet unter den Weltgeistern.',
        4: 'Da kam die Fülle der Zeit, und Gott sandte seinen Sohn, der, vom Weib geboren, dem Gesetz unterworfen war.',
        5: 'Er sollte die, die unter dem Gesetze standen, loskaufen, und wir sollten die Annahme an Sohnes Statt erhalten.',
        6: 'Weil ihr nun Söhne seid, so sandte Gott in unsere Herzen den Geist seines Sohnes, und dieser ruft:"Abba!" "Vater!"',
        7: 'So bist du also nicht mehr Sklave, sondern Sohn; wenn aber Sohn, dann Erbe durch Gott.',
        8: 'Damals freilich, als ihr Gott nicht kanntet, da dientet ihr den Göttern, die es in Wirklichkeit doch gar nicht gibt.',
        9: 'Jetzt aber erkennt ihr Gott, vielmehr, ihr seid von Gott erkannt. Wie könnt ihr euch wiederum den schwachen und armseligen Geistern zuwenden und ihnen noch einmal von neuem dienstbar werden?',
        10: 'Ihr beobachtet ja Tage, Monate, Festzeiten und Jahre.',
        11: 'Ich fürchte für euch, ob ich mich nicht vergeblich unter euch abgemüht habe.',
        12: 'Liebe Brüder, ich bitte euch, werdet wie ich! Auch ich bin euch gleich geworden, ihr habt mir nichts zuleid getan.',
        13: 'Ihr wißt, wie ich in körperlicher Schwachheit euch damals das Evangelium verkündet habe.',
        14: 'Jedoch trotz der Prüfung, die für euch in meinem schwachen Zustande lag, habt ihr mich nicht verachtet noch vor mir ausgespuckt, vielmehr mich aufgenommen wie einen Engel Gottes, ja wie Christus Jesus selbst.',
        15: 'Wo ist jetzt eure freudige Begeisterung? Ich kann es euch bezeugen: Ihr hättet, wenn es möglich wäre, euch die Augen ausgerissen und sie mir gegeben.',
        16: 'Bin ich denn nunmehr euer Feind geworden, weil ich euch die Wahrheit Sage?',
        17: 'Jene werben um euch nicht in guter Absicht. Sie möchten euch abwendig machen, damit ihr sie alsdann umwerbet.',
        18: 'Es ist ja schön, wenn man umworben wird, allerdings nur in einer guten Sache und allezeit und nicht bloß, solange ich bei euch bin.',
        19: 'Liebe Kinder! Von neuem liege ich mit euch in Wehen, bis Christus in euch Gestalt gewonnen hat.',
        20: 'Ich möchte jetzt bei euch sein und einen anderen Ton anschlagen können; in großer Sorge bin ich euretwegen.',
        21: 'Sagt mir, ihr, die ihr so gern unter dem Gesetz stehen möchtet: Hört ihr das Gesetz nicht?',
        22: 'Es steht geschrieben: "Abraham hatte zwei Söhne, den einen von der Magd, den anderen von der Freien.',
        23: 'Der Sohn der Magd war natürlich geboren worden; der Sohn der Freien aber durch Verheißung."',
        24: 'Das ist bildlich zu verstehen: Diese (Frauen) sind die beiden Testamente; das eine das Testament vom Berge Sinai, das nur Knechte gebiert, das ist die Agar.',
        25: 'Agar bedeutet nämlich den Berg Sinai in Arabien. Es entspricht dem jetzigen Jerusalem, das samt den Kindern in der Knechtschaft ist.',
        26: 'Doch frei ist das Jerusalem dort oben, und das ist unsere Mutter.',
        27: 'Es steht ja auch geschrieben: "Freu dich, du unfruchtbare, die du nicht geboren hast, o juble laut du, die du keine Wehen kennst! Zahlreicher sind die Kinder der Vereinsamten als die der Vermählten."',
        28: 'Ihr aber, liebe Brüder, seid, wie Isaak, Kinder der Verheißung.',
        29: 'Wie aber damals der natürlich Geborene den nach dem Geiste Geborenen verfolgte, so ist es auch heute noch. Was sagt jedoch die Schrift?',
        30: '"Verstoße die Magd und ihren Sohn; der Sohn der Magd darf nicht mit dem Sohn der Freien erben!"',
        31: 'So sind wir also, meine lieben Brüder, nicht Kinder der Magd, sondern der Freien.',
    },
    5: {
        1: 'Für die Freiheit hat Christus uns befreit. So steht denn fest und laßt euch nicht wieder das Joch der Sklaverei aufbürden.',
        2: 'Seht! Ich, Paulus, sage euch:Wenn ihr euch beschneiden laßt, dann nützt euch Christus nichts.',
        3: 'Und noch einmal versichere ich jedem, der sich beschneiden läßt: Er ist dann verpflichtet, das ganze Gesetz zu halten.',
        4: 'Ihr seid von Christus losgetrennt, wenn ihr euch durch das Gesetz Rechtfertigung zu verschaffen sucht; ihr geht dann der Gnade verlustig.',
        5: 'Denn wir erwarten die Rechtfertigung, auf die wir hoffen, durch den Geist in Kraft des Glaubens.',
        6: 'In Christus Jesus nützt die Beschneidung nichts noch das Unbeschnittensein, sondern Glaube, der durch die Liebe wirkt.',
        7: 'Ihr waret in so gutem Lauf. Wer hat euch aufgehalten, daß ihr der Wahrheit nicht mehr folgen wollt?',
        8: 'Die Umstimmung kommt nicht von dem, der euch berufen hat.',
        9: 'Ein wenig Sauerteig durchsäuert den ganzen Teig.',
        10: 'Ich habe zu euch das Vertrauen im Herrn, daß ihr nicht anderen Sinnes werdet. Doch wird sein Urteil ertragen müssen, mag sein, wer es will, wer bei euch Verwirrung stiftet.',
        11: 'Wenn ich aber, liebe Brüder, noch die Beschneidung predigte, warum werde ich dann noch verfolgt? Dann ist ja das Ärgernis des Kreuzes aus der Welt geschafft.',
        12: 'Möchten doch die, die euch verwirren, sich gleich entmannen lassen.',
        13: 'Zur Freiheit seid ihr berufen worden, liebe Brüder. Mißbraucht aber die Freiheit nicht als einen Vorwand für ein Leben nach dem Fleische; nein, dient einander in Liebe!',
        14: 'Denn das ganze Gesetz ist mit dem einen Wort erfüllt: "Du sollst deinen Nächsten lieben wie dich selbst!"',
        15: 'Wenn ihr jedoch einander beißt und auffreßt, seht dann nur zu, daß ihr nicht voneinander aufgefressen werdet.',
        16: 'Ich sage: Wandelt im Geiste, dann werdet ihr die Lüste des Fleisches nicht mehr vollbringen.',
        17: 'Das Fleisch gelüstet es ja gegen den Geist, des Geistes Begehren widerspricht dem Fleische; sie liegen in Streit miteinander, so daß ihr das nicht tut, was ihr möchtet.',
        18: 'Laßt ihr euch aber vom Geiste leiten, dann steht ihr nicht unter dem Gesetze.',
        19: 'Offenkundig sind die Werke des Fleisches, zum Beispiel Unzucht, Unkeuschheit Schamlosigkeit, Wollust,',
        20: 'Abgötterei, Zauberei, Feindschaft, Streit, Eifersucht, Zorn, Zwietracht, Spaltungen, Parteien,',
        21: 'Neid Mord, Trunkenheit, Schlemmerei und anderes dergleichen. Was ich euch früher schon gesagt habe, das wiederhole ich: Die solches treiben, werden das Reich Gottes nicht erben.',
        22: 'Des Geistes Frucht dagegen ist: Liebe, Freude, Friede, Langmut, Wohlwollen, Güte, Vertrauen,',
        23: 'Sanftmut Keuschheit und Enthaltsamkeit. Dem steht das Gesetz auf keinen Fall entgegen.',
        24: 'Die aber Christus Jesus angehören, haben ihr Fleisch mitsamt den Leidenschaften und den Lüsten ans Kreuz geschlagen.',
        25: 'Wenn wir nun durch den Geist das Leben haben, dann laßt uns auch im Geiste wandeln.',
        26: 'Laßt uns nicht nach eitlem Ruhme trachten und nicht einander reizen und gegenseitig uns beneiden!',
    },
    6: {
        1: 'Liebe Brüder! Wenn einer in der Übereilung einen Fehltritt tut, dann weist ihn, die ihr Geistesmänner seid, im Geiste der Sanftmut zurecht. Doch achte dabei auf dich selbst, damit nicht auch du in Versuchung kommst.',
        2: 'Der eine trage die Last des anderen. Also erfüllt ihr das Gesetz Christi.',
        3: 'Denn wer sich schmeichelt, er habe etwas zu bedeuten, während er doch nichts ist, betrügt sich selbst.',
        4: 'Jeder prüfe nur sein eigenes Handeln, dann wird er seinen Ruhm für sich behalten und andere damit verschonen.',
        5: 'Hat doch ein jeder an seiner eigenen Last zu tragen.',
        6: 'Wer in der Lehre Unterricht erhält, der soll dem Lehrer Teil an all seiner Habe geben.',
        7: 'Täuscht euch nicht: Gott läßt seiner nicht spotten. Was der Mensch sät, wird er ernten.',
        8: 'Wer auf sein Fleisch sät, wird vom Fleische Verderben ernten; wer aber auf den Geist sät, wird vom Geiste das ewige Leben ernten.',
        9: 'Laßt uns im Gutestun nicht müde werden! Denn schließlich werden wir doch einmal ernten, wenn wir nicht nachlassen.',
        10: 'So lasset uns denn allen Gutes tun, solange wir noch Gelegenheit dazu haben, besonders aber unseren Glaubensgenossen.',
        11: 'Seht, mit was für großen Buchstaben ich euch eigenhändig schreibe.',
        12: 'Alle, die bei den Menschen eine Rolle spielen möchten, wollen euch die Beschneidung aufnötigen, nur damit sie um des Kreuzes Christi willen nicht verfolgt werden.',
        13: 'Und dabei halten sie, obwohl beschnitten, nicht einmal selber das Gesetz. Nur deshalb wollen sie euch ja beschneiden, damit sie sich mit eurem Fleische rühmen können.',
        14: 'Mir aber sei es ferne, mich zu rühmen, es sei denn im Kreuz unseres Herrn Jesus Christus. Durch ihn ist mir die Welt gekreuzigt und ich der Welt.',
        15: 'Denn in Christus Jesus weder die Beschneidung noch das Unbeschnittensein hat Wert, vielmehr nur eine Neuschöpfung.',
        16: 'Über alle, die nach diesem Grundsatz wandeln, komme Friede und Erbarmen und über das Israel Gottes.',
        17: 'In Zukunft mache mir keiner Unannehmlichkeiten; ich trage ja die Male des Herrn Jesu an meinem Leibe.',
        18: 'Die Gnade unseres Herrn Jesus Christus sei mit eurem Geiste, liebe Brüder. Amen.',
    },
}
