NAME = 'GerTafel: German Tafelbibel (1911)'
BOOK = 'Daniel'

CHAPTERS = {
    1: {
        1: 'Im dritten Jahre der Regierung Jehojakims, des Königs von Jehudah, kam Nebuchadnezzar, der König von Babel, nach Jerusalem und belagerte es.',
        2: 'Und der Herr gab Jehojakim, den König von Jehudah, und einen Teil der Geräte des Hauses Gottes in seine Hand, und er brachte sie hinein in das Land Schinear in das Haus seines Gottes, und brachte die Geräte hinein in das Haus des Schatzes seines Gottes.',
        3: 'Und der König sprach zu Aschpenas, dem Hauptmann seiner Verschnittenen, er solle einige von den Söhnen Israels und vom Samen des Königtums und von den Vornehmen hereinbringen,',
        4: 'Knaben, die keinerlei Fehl an sich hätten, und von gutem Aussehen, und klug in aller Weisheit und kundig an Wissen und einsichtsvoll an Kenntnis, und welche die Kraft hätten, zu stehen im Palaste des Königs, und sie Schrift und Zunge der Chaldäer lehren.',
        5: 'Und der König bestimmte ihnen den Bedarf des Tages an seinem Tage von den leckeren Speisen des Königs und von dem Wein, den er trank, und drei Jahre sollten sie großgezogen werden, und am Ende derselben vor dem König stehen.',
        6: 'Und es waren unter ihnen von den Söhnen Jehudahs: Daniel, Chananjah, Mischael und Asarjah.',
        7: 'Und der Oberste der Verschnittenen legte ihnen Namen bei und nannte Daniel Beltschazzar, und Chananjah Schadrach, und Mischael Meschach, und Asarjah Abed Nego.',
        8: 'Daniel aber setzte sich vor in seinem Herzen, daß er sich nicht mit den leckeren Speisen des Königs und mit dem Weine, den er trank, beflecken wollte, und ersuchte den Obersten der Verschnittenen, daß er sich nicht beflecken müßte.',
        9: 'Und Gott gab Daniel Barmherzigkeit und Erbarmen vor dem Obersten der Verschnittenen.',
        10: 'Und der Oberste der Verschnittenen sprach zu Daniel: Ich fürchte meinen Herrn, den König, der eure Speise und euren Trank bestimmt hat: denn würde er sehen, daß eure Angesichter verdrossen wären gegen die der Knaben eures Alters, so würdet ihr mein Haupt dem König verwirken.',
        11: 'Und Daniel sprach zu Melzar, den der Oberste der Verschnittenen über Daniel, Chananjah, Mischael und Asarjah bestimmt hatte:',
        12: 'Versuche es doch mit deinen Knechten zehn Tage, daß man uns von den Hülsenfrüchten zu essen und Wasser zu trinken gebe.',
        13: 'Und man sehe an vor dir unser Aussehen und das Aussehen der Knaben, die des Königs leckere Speisen essen, und wie du sehen wirst, so tue mit deinen Knechten.',
        14: 'Und er hörte auf sie in dieser Sache, und versuchte es mit ihnen zehn Tage.',
        15: 'Und am Ende der zehn Tage sah man, daß ihr Aussehen besser und ihr Fleisch feister war, als bei allen Knaben, die des Königs leckere Speisen aßen.',
        16: 'Und Melzar nahm ihre leckeren Speisen und den Wein, den sie trinken sollten, weg, und gab ihnen Hülsenfrüchte.',
        17: 'Und diesen vier Knaben gab Gott Kenntnisse und Verstand in aller Schrift und Weisheit, und Daniel hatte eine Einsicht in allerlei Gesichte und Träume.',
        18: 'Und am Ende der Tage, nach denen der König befohlen hatte sie hereinzubringen, brachte sie der Oberste der Verschnittenen, hinein vor Nebuchadnezzar.',
        19: 'Und der König redete mit ihnen, und es fand sich unter allen keiner, wie Daniel, Chananjah, Mischael und Asarjah, und sie standen vor dem König.',
        20: 'Und in allem Worte der Weisheit der Einsicht, über das der König sie befragte, fand er sie zehnmal über allen Magiern und Wahrsagern in seinem ganzen Reich.',
        21: 'Und Daniel war bis in das erste Jahr des Königs Koresch.',
    },
    2: {
        1: 'Und im zweiten Jahre der Regierung Nebuchadnezzars träumte Nebuchadnezzar Träume, und sein Geist war beunruhigt, und sein Schlaf war ihm dahin.',
        2: 'Und der König befahl, die Magier und die Wahrsager und die Zauberer und die Chaldäer zu rufen, daß sie dem König seine Träume ansagen sollten, und sie kamen hinein und standen vor dem König.',
        3: 'Und der König sprach zu ihnen: Ich habe einen Traum geträumt, und mein Geist ist beunruhigt, daß ich den Traum wissen möchte.',
        4: 'Und die Chaldäer redeten zum König aramäisch: O König, lebe in Ewigkeit, sage deinen Knechten den Traum, so wollen wir dir die Deutung anzeigen.',
        5: 'Der König antwortete und sprach zu den Chaldäern: Das Wort ist mein Ernst: Wenn ihr mir nicht den Traum kundtut und seine Deutung, so sollt ihr in Stücke zerhauen und eure Häuser zu Düngerhaufen gemacht werden.',
        6: 'Wenn ihr aber den Traum und seine Deutung anzeigt, so sollet ihr viele Gaben und Ehrensold und viele Kostbarkeiten von mir empfangen. Darum zeigt mir den Traum und seine Deutung an.',
        7: 'Sie antworteten ihm zum zweitenmal und sprachen: Der König sage seinen Knechten den Traum, so wollen wir die Deutung anzeigen.',
        8: 'Der König antwortete und sprach: Gewiß-lich weiß ich nun, daß ihr Zeit gewinnen wollt, weil ihr erschaut habt, daß das Wort mein Ernst ist.',
        9: 'Wenn ihr den Traum mir nicht kundtut, so ist dies der alleinige Erlaß für euch: Ihr habt verabredet ein falsch und verdorbenes Wort vor mir zu sprechen, bis daß die Zeit sich ändere. Darum sagt mir den Traum, daß ich erkenne, daß ihr mir auch seine Deutung anzeigen könnt.',
        10: 'Die Chaldäer antworteten vor dem König und sprachen: Kein Mensch ist auf dem Erdboden, der das Wort dem König anzeigen könnte, alldieweil kein König, wie groß und gewaltig er auch sei, ein Ding, wie dieses, von irgendeinem Magier und Wahrsager und Chaldäer fordert.',
        11: 'Und das Wort, das der König fordert, ist zu schwer, und einen anderen gibt es nicht, der es vor dem König anzeigen könnte, als die Götter, deren Verweilen nicht beim Fleische ist.',
        12: 'Ob alledem ward der König sehr aufgebracht und entrüstet, und befahl, alle Weisen Babels zu zerstören.',
        13: 'Und es erging der Erlaß, daß die Weisen sollten getötet werden, und sie suchten Daniel und seine Gesellen, um sie zu töten.',
        14: 'Da erteilte Daniel Rat und Weisung Arjoch, dem Hauptmann der Leibwachen des Königs, der ausging, die Weisen Babels zu töten.',
        15: 'Er antwortete und sprach zu Arjoch, dem Gewalthaber des Königs: Warum ergeht so hastig der Erlaß vom König? Und Arjoch tat Daniel die Sache kund.',
        16: 'Und Daniel ging hinein und ersuchte den König, daß er ihm Frist gebe, auf daß er dem König die Deutung anzeige.',
        17: 'Da ging Daniel nach Haus, und tat Chananjah, Mischael und Asarjah, seinen Gesellen, die Sache kund,',
        18: 'Daß sie vom Gott der Himmel Erbarmen ersuchten ob diesem Geheimnisse, damit sie Daniel und seine Gesellen nicht samt den übrigen Weisen Babels zerstörten.',
        19: 'Da ward dem Daniel in dem Gesichte der Nacht das Geheimnis geoffenbart. Da segnete Daniel den Gott der Himmel.',
        20: 'Daniel antwortete und sprach: Gesegnet sei der Name Gottes von Ewigkeit zu Ewigkeit: denn Sein ist die Weisheit und die Macht.',
        21: 'Und Er ändert Zeiten und Fristen, läßt Könige dahingehen und läßt erstehen Könige, Er gibt Weisen die Weisheit und Wissenschaft denen, die Einsicht kennen.',
        22: 'Er offenbart die Tiefen und das Verborgene, Er weiß, was in der Finsternis ist, und bei Ihm wohnt das Licht.',
        23: 'Dich, o Gott meiner Väter, bekenne ich und preise Dich, Der Du mir Weisheit und Macht gegeben hast, und mich jetzt hast wissen lassen, was wir von Dir ersuchten, Der Du uns hast die Sache des Königs kundgetan.',
        24: 'Deswegen ging Daniel hinein zu Arjoch, den der König bestimmt hatte, die Weisen Babels zu zerstören. Er ging hin und sprach zu ihm also: Die Weisen Babels sollst du nicht zerstören, bringe mich hinein vor den König, und ich werde dem König die Deutung anzeigen.',
        25: 'Da brachte Arjoch den Daniel eilig hinein vor den König und sprach zu ihm also: Ich habe einen Mann von den Söhnen der Verbannung aus Jehudah gefunden, der dem König die Deutung kundtun wird.',
        26: 'Der König antwortete und sprach zu Daniel, dessen Name Beltschazzar war: Ver- magst du den Traum, den ich geschaut, und dessen Deutung mir kundzutun?',
        27: 'Daniel antwortete vor dem König und sprach: Das Geheimnis, das der König gefordert hat, vermögen Weise, Wahrsager, Magier und Sterndeuter dem König nicht anzuzeigen.',
        28: 'Jedoch ist ein Gott in den Himmeln, Der Geheimnisse offenbart, und ließ den König Nebuchadnezzar wissen, was in den letzten der Tage sein wird. Dein Traum und das Gesicht deines Hauptes auf deinem Lager ist dies:',
        29: 'Du, König, warst mit deinen Gedanken auf deinem Lager; sie gingen dahin, was wohl hernach sein werde? Und Der da offenbart Geheimnisse, tat dir kund, was da sein wird.',
        30: 'Und mir ist nicht durch eine Weisheit, die in mir wäre vor allen, die da leben, dies Geheimnis geoffenbart worden, sondern damit sie die Deutung dem König kundtun möchten und du die Gedanken deines Herzens wissest.',
        31: 'Du, König, schautest und siehe, ein gewaltig Standbild war da, dies Standbild war groß und sein Glanz über die Maßen, und stand dir gegenüber, und war schauerlich anzusehen.',
        32: 'Das Haupt dieses Standbildes war von gutem Gold, seine Brust und seine Arme von Silber, sein Bauch und seine Hüften von Erz.',
        33: 'Seine Schenkel von Eisen, seine Füße waren teils von Eisen und teils von Ton.',
        34: 'Solches schautest du, bis daß ein Stein ausgehauen ward, nicht durch Hände, und stieß das Standbild an seine Füße, die Eisen und Ton waren, und zermalmte sie.',
        35: 'Da wurden mit einem Mal das Eisen, der Ton, das Erz, das Silber und das Gold zermalmt, und sie wurden wie Spreu von den Tennen des Sommers, und der Wind nahm sie weg, so daß man ihre Stätte nicht mehr ausfand, und der Stein, der an das Standbild stieß, ward zu einen großen Felsen, und füllte die ganze Erde.',
        36: 'Dies ist der Traum, und seine Deutung wollen wir vor dem Könige sagen.',
        37: 'Du, o König, bist der König der Könige, dem der Gott der Himmel das Königtum, die Gewalt und die Stärke und Herrlichkeit gegeben hat.',
        38: 'Und überall, da Menschensöhne verweilen, das wilde Tier des Feldes und das Gevögel der Himmel hat Er in deine Hand gegeben und dich schalten lassen über sie alle: du bist das Haupt von Gold.',
        39: 'Und nach dir ersteht ein anderes Reich, niedriger denn das deine, und ein anderes drittes Reich von Erz, das auf der ganzen Erde schalten wird.',
        40: 'Und das vierte Reich wird stark sein wie das Eisen, alldieweil das Eisen alles zermalmt und zerschlägt, und wie das Eisen, das zerschmettert all dies, wird es zermalmen und zerschmettern.',
        41: 'Und da du schautest die Füße und die Zehen teils vom Ton des Töpfers und teils von Eisen, so wird es ein zerteiltes Reich sein, und von der Beständigkeit des Eisens wird darinnen sein, alldieweil du erschautest, daß Eisen mit dem schlammigen Ton vermengt war,',
        42: 'Und da die Zehen der Füße teils von Eisen und teils von Ton waren, so wird das Reich teilweise stark, und teilweise gebrechlich sein.',
        43: 'Und weil du erschautest das Eisen mit schlammigem Ton vermengt, so werden sie durch Samen des Menschen sich vermengen, aber nicht kleben das eine an dem anderen, so wie Eisen sich nicht mit Ton vermengen läßt.',
        44: 'Und in den Tagen dieser Könige wird der Gott der Himmel ein Königreich aufrichten, das in Ewigkeiten nicht umgestoßen, und dessen Königtum keinem anderen Volk überlassen werden wird. Es wird zermalmen und wegraffen alle jene Königreiche, es wird aber bestehen in Ewigkeit.',
        45: 'Alldieweil du erschautest, daß ein Stein ausgehauen ward aus dem Felsen nicht durch Hände, und zermalmte das Eisen, das Erz, den Ton, das Silber und das Gold; hat der große Gott den König wissen lassen, was hernach sein wird, und gewiß ist der Traum, und seine Deutung wahrhaftig.',
        46: 'Da fiel der König Nebuchadnezzar auf sein Antlitz, und betete an vor Daniel und befahl, ihm Speiseopfer und Ruheopfer zu spenden.',
        47: 'Der König antwortete dem Daniel und sprach: Es ist eine Wahrheit, daß euer Gott ist der Gott der Götter, und der Herr der Könige, und Er offenbart Geheimnisse, weil du vermochtest dies Geheimnis zu offenbaren.',
        48: 'Da machte der König Daniel groß und gab ihm viele große Gaben, und ließ ihn schalten über die ganze Landschaft Babel, und machte ihn zum Hauptvorsteher über alle die Weisen Babels.',
        49: 'Und Daniel ersuchte den König, daß er einsetzen sollte über die Verwaltung der Landschaft Babel Schadrach, Meschach und Abed Nego; und Daniel war im Tore des Königs.',
    },
    3: {
        1: 'Der König Nebuchadnezzar machte ein Standbild von Gold, seine Höhe sechzig Ellen, seine Breite sechs Ellen; er richtete es auf in der Ebene Dura in der Landschaft Babel.',
        2: 'Und der König Nebuchadnezzar sandte aus, daß zusammentreten die Satrapen, Landvögte, Statthalter, Oberrichter, Schatzmeister, Richter, Rechtsgelehrten und alle Verwalter der Landschaften, zur Einweihung des Standbildes zu kommen, das der König Nebuchadnezzar aufgerichtet hatte.',
        3: 'Da traten zusammen die Satrapen, die Landvögte und die Statthalter, die Oberrichter, die Schatzmeister, die Richter, die Rechtsgelehrten und alle Verwalter der Landschaften zur Einweihung des Standbildes, das der König Nebuchadnezzar hatte aufgerichtet, und sie traten vor das Bild, das Nebuchadnezzar aufgerichtet hatte.',
        4: 'Und der Herold rief mit Macht: Euch wird es gesagt: ihr Völker, Volksstämme und Zungen!',
        5: 'Zur Zeit, da ihr hören werdet den Schall des Horns, der Pfeife, der Harfe, der Sambuke, des Psalters, der Sackpfeife und allerlei Saitenspiele, sollt ihr niederfallen und anbeten das Standbild von Gold, das der König Nebuchadnezzar aufgerichtet hat.',
        6: 'Und wer nicht niederfällt und anbetet, der soll im selben Augenblick mitten in den Ofen, der mit Feuer brennt, hinabgeworfen werden.',
        7: 'Darum zur Zeit, da alle Völker den Schall des Horns, der Pfeife, der Harfe, der Sambuke, des Psalters und von allerlei Saitenspiel hörten, fielen alle Völker, Volksstämme und Zungen nieder, und beteten das Standbild von Gold an, das der König Nebuchadnezzar aufgerichtet hatte.',
        8: 'Darum, zur selben Zeit, nahten sich chaldäische Männer und klagten die Juden an.',
        9: 'Sie antworteten und sagten zu dem König Nebuchadnezzar: Lebe, o König, in Ewigkeit!',
        10: 'Du hast, o König, eine Weisung erlassen, daß jeder Mensch, wenn er höre den Schall des Horns, der Pfeife, der Harfe, der Sambuke, des Psalters, der Sackpfeife und allerlei Saitenspiel, niederfallen und das Standbild von Gold anbeten soll.',
        11: 'Wer aber nicht niederfällt und anbetet, der soll mitten in den Ofen, der mit Feuer brennt, hinabgeworfen werden.',
        12: 'Da sind jüdische Männer, die du zur Verwaltung der Landschaft Babel eingesetzt, Schadrach, Meschach und Abed Nego. Diese Männer haben nicht auf deine Weisung geachtet, o König. Deinen Gott verehren sie nicht, und das Standbild von Gold, das du aufgerichtet, beten sie nicht an.',
        13: 'Da befahl Nebuchadnezzar in Wut und Grimm, Schadrach, Meschach und Abed Nego herbeizubringen. Da brachten sie diese Männer vor den König.',
        14: 'Nebuchadnezzar antwortete und sprach zu ihnen: Ist es aus Vorsatz, daß ihr, Schadrach, Meschach und Abed Nego, meinen Gott nicht verehrt und das Standbild von Gold nicht anbetet, das ich aufgerichtet habe?',
        15: 'Nun denn, wenn ihr bereit seid, zur Zeit, da ihr hört den Schall des Horns, der Pfeife, der Harfe, der Sambuke, des Psalters, der Sackpfeife und allerlei Saitenspiel, niederzufallen und das Standbild anzubeten, das ich gemacht habe - und wenn ihr es nicht anbetet, sollt ihr augenblicklich mitten in den Ofen, der mit Feuer brennt, hinabgeworfen werden! Und wer ist der Gott, der euch aus meinen Händen befreien kann?',
        16: 'Da antworteten Schadrach, Meschach und Abed Nego, und sprachen zu dem König Nebuchadnezzar: Es ist nicht notwendig, daß wir auf die Rede erwidern.',
        17: 'Siehe, unser Gott, Den wir verehren, vermag uns aus dem Ofen, der mit Feuer brennt, zu befreien, und aus deiner Hand, o König, wird Er uns befreien.',
        18: 'Und wenn nicht, so wisse, o König, daß wir deinen Gott nicht verehren, und das goldene Standbild, das du aufgerichtet hast, nicht anbeten wollen.',
        19: 'Da ward Nebuchadnezzar voll Grimmes und das Bild seines Antlitzes veränderte sich wider Schadrach, Meschach und Abed Nego. Er antwortete und befahl, den Ofen siebenmal mehr zu heizen, als man ihn jemals hatte heizen geschaut;',
        20: 'Und den Männern, den Helden der Tapferkeit in seiner Streitmacht, befahl er, Schadrach, Meschach und Abed Nego zu binden, um sie in den Ofen, der mit Feuer brennt, hinabzuwerfen.',
        21: 'Da wurden diese Männer gebunden in ihren Beinkleidern, ihren Unterkleidern und ihren Mänteln und ihren Anzügen, und wurden mitten in den Ofen, der mit Feuer brennt, hinabgeworfen.',
        22: 'Weil das Wort des Königs so hastig war, und der Ofen über die Maßen geheizt worden, tötete die Flamme des Feuers die Männer, die Schadrach, Meschach und Abed Nego hinaufbrachten.',
        23: 'Und diese drei Männer, Schadrach, Meschach und Abed Nego fielen gebunden mitten in den Ofen, der mit Feuer brennt.',
        24: 'Da entsetzte sich der König Nebuchadnezzar und stand bestürzt auf, hob an und sprach zu seinen Räten: Haben wir nicht drei Männer gebunden mitten ins Feuer hinabgeworfen? Sie antworteten und sprachen zum König: Gewißlich, o König!',
        25: 'Er antwortete und sprach: Siehe, ich schaue vier Männer lose mitten im Feuer umhergehen, und haben keinen Schaden an sich und das Aussehen des vierten gleicht einem Sohne der Götter.',
        26: 'Da nahte Nebuchadnezzar dem Tor des Ofens, der mit Feuer brennt, hob an und sprach: Schadrach, Meschach und Abed Nego, ihr Knechte des höchsten Gottes, geht heraus und kommt her. Da gingen Schadrach, Meschach und Abed Nego mitten aus dem Feuer heraus.',
        27: 'Und die Satrapen, die Landvögte, die Statthalter und die Räte des Königs traten zusammen, und schauten die Männer, über deren Leib das Feuer nicht schaltete, und das Haar von deren Haupt nicht versengt, und deren Beinkleider nicht verändert waren, und an die der Geruch des Feuers nicht gekommen war.',
        28: 'Da hob Nebuchadnezzar an und sprach: Gesegnet sei der Gott von Schadrach, Meschach und Abed Nego, Der Seinen Engel gesandt und Seine Knechte, die auf Ihn vertrauten, befreit hat, daß sie das Wort des Königs und ihre Leiber hingaben, daß sie einen anderen Gott, als ihren Gott, nicht verehrten und ihn anbeteten.',
        29: 'Und von mir ergeht die Weisung, daß jegliches Volk, jeder Volksstamm und jede Zunge, die gegen den Gott Schadrachs, Meschachs und Abed Negos etwas spricht, soll in Stücke zerhauen und sein Haus zu einem Düngerhaufen gemacht werden, alldieweil daß kein anderer Gott ist, der erretten kann, wie Dieser.',
        30: 'Dann gab der König dem Schadrach, Meschach und Abed Nego Gedeihen in der Landschaft Babel. Nebuchadnezzar, der König an alle Völker, Volksstämme und Zungen, die wohnen auf der ganzen Erde, euer Friede mehre sich! Es hat mir gefallen, die Zeichen und Wunder, die der höchste Gott an mir getan, euch anzuzeigen. Seine Zeichen, wie groß sind sie, und wie gewaltig Seine Wunder, Sein Reich ist ein Reich der Ewigkeit, und Seine Herrschaft zu Geschlecht und Geschlecht.',
    },
    4: {
        1: 'Ich, Nebuchadnezzar, war ruhig in meinem Hause und gedeihlich in meinem Palast.',
        2: 'Da schaute ich einen Traum, und schauderte, und die Gedanken auf meinem Lager und die Gesichte meines Hauptes bestürzten mich.',
        3: 'Da erging von mir eine Weisung, alle Weisen Babels vor mich zu bringen, daß sie mir die Deutung des Traumes kundtun möchten.',
        4: 'Da kamen herein die Magier, die Wahrsager, die Chaldäer und die Sterndeuter, und ich sagte vor ihnen den Traum, aber sie machten mir seine Deutung nicht kund.',
        5: 'Und zuletzt trat vor mich Daniel, dessen Name ist Beltschazzar, wie der Name meines Gottes, und in dem der Geist der heiligen Götter ist, und ich sagte vor ihm den Traum:',
        6: 'Beltschazzar, du Oberster der Magier, von dem ich weiß, daß der Geist der heiligen Götter in dir ist, und daß dir kein Geheimnis zu schwer ist: Sage mir die Gesichte meines Traumes, die ich geschaut, und die Deutung davon.',
        7: 'Und dies sind die Gesichte meines Hauptes auf meinem Lager: Ich schaute, und siehe, ein Baum inmitten der Erde, und seine Höhe war gewaltig.',
        8: 'Der Baum ward groß und stark, und bis an die Himmel reichte seine Höhe, und er war zu schauen bis an das Ende der Erde.',
        9: 'Sein Gezweige war schön, und seiner Frucht viel, und Nahrung an ihm für alle, und das Tier des Feldes hatte Schatten unter ihm, und auf seinen Ästen verweilten die Vögel der Himmel, und alles Fleisch nährte sich von ihm.',
        10: 'Ich schaute in Gesichten meines Hauptes auf meinem Lager, und siehe, ein Wächter und ein Heiliger stieg von Himmel herab.',
        11: 'Er rief mit Macht und sprach also: Hauet um den Baum, und hauet ab seine Äste, streifet ab sein Gezweige und streut umher seine Frucht. Es fliehe weg unter ihm das Getier und die Vögel von seinen Ästen.',
        12: 'Doch den Stamm seiner Wurzel belasset in der Erde, aber in Banden von Eisen und Erz, im jungen Grün auf dem Felde. Und mit dem Tau der Himmel werde er benetzt, und mit dem Getier habe er sein Teil am Kraut der Erde.',
        13: 'Sein Herz soll von dem eines Menschen verändert, und ihm das Herz eines Tieres gegeben werden, und sieben Zeiten sollen über ihn hingleiten.',
        14: 'Im Beschlusse der Wächter ist die Sache, und auf dem Befehl der Heiligen das Betreffnis zu dem Ende, daß erkennen die Lebendigen, daß der Höchste Gewalt hat über das Reich des Menschen und gibt es, wem er will, und den niedrigsten der Menschen darauf erhebt.',
        15: 'Diesen Traum schaute ich, der König Nebuchadnezzar, und du, Beltschazzar, sage mir die Deutung, alldieweil alle Weisen meines Reiches nicht vermögen, mir die Deutung kundzutun, du aber vermagst es, denn der Geist der heiligen Götter ist in dir.',
        16: 'Da war Daniel, dessen Name Beltschazzar ist, bei einer Stunde lang in Erstaunen, und seine Gedanken machten ihn bestürzt. Der König hob an und sprach: Beltschazzar, der Traum und seine Deutung mache dich nicht bestürzt! Beltschazzar antwortete und sprach: Mein Herr! Der Traum sei für die, so dich hassen, und seine Deutung deinen Widersachern!',
        17: 'Der Baum, den du schautest, daß er groß und stark ward, und dessen Höhe bis an die Himmel reichte, und der auf der ganzen Erde zu schauen war,',
        18: 'Und dessen Gezweige schön und dessen Frucht viel war, und Nahrung für alle darauf, unter dem das Tier des Feldes verweilte, und auf dessen Ästen die Vögel der Himmel wohnten:',
        19: 'Dies bist du, o König, der du groß und stark wurdest, und deine Größe wuchs und reichte bis zu den Himmeln, und deine Herrschaft bis an das Ende der Erde;',
        20: 'Und daß der König schaute einen Wächter und einen Heiligen herabsteigen von den Himmeln, und daß er sprach: Hauet den Baum um und zerstört ihn, aber den Stamm seiner Wurzeln belasset in der Erde und in Banden von Eisen und Erz im jungen Grün des Feldes, und vom Tau der Himmel werde er benetzt und habe sein Teil mit dem Getier des Feldes, bis daß sieben Zeiten über ihm hingleiten:',
        21: 'Dies ist die Deutung, o König! und solcher Beschluß des Höchsten ergeht über meinen Herrn, den König.',
        22: 'Dich verstößt man von dem Menschen, und bei dem wilden Tier des Feldes mußt du verweilen, und sie lassen dich das Kraut schmecken wie die Ochsen und vom Tau der Himmel benetzt werden; und sieben Zeiten werden hingleiten über dich, bis daß du erkennst, daß der Höchste schaltet über das Reich des Menschen und es gibt, wem Er will.',
        23: 'Daß sie aber sagten: man solle den Stamm der Wurzeln des Baumes belassen: Dein Königtum soll dir bestehen, daß du wissest, daß die Himmel schalten.',
        24: 'Darum, o König, laß dir meinen Rat gefallen und brich ab von deinen Sünden durch Gerechtigkeit, und von deinen Verkehrtheiten durch Gnade gegen die Elenden, wenn deine Ruhe soll verlängert werden.',
        25: 'Das alles traf den König Nebuchadnezzar.',
        26: 'Am Ende von zwölf Monden erging er sich auf dem Palast des Königtums in Babel.',
        27: 'Da hub der König an und sprach: Ist dies nicht die große Babel, die ich erbaut habe zum Königshause durch die Stärke meiner Macht und zum Ruhme meiner Ehre?',
        28: 'Noch war das Wort im Munde des Königs, da fiel eine Stimme vom Himmel: Dir, König Nebuchadnezzar, wird gesagt: das Reich ist von dir gewichen.',
        29: 'Und von den Menschen wirst du verstoßen und bei dem Getier des Feldes wirst du verweilen, gleich den Ochsen lassen sie das Kraut dich schmecken, und sieben Zeiten werden über dich hingleiten, bis du wissest, daß der Höchste schaltet über das Reich des Menschen, und gibt es dem, dem Er Sich zuneigt.',
        30: 'Zur selben Stunde ward das Wort an Nebuchadnezzar vollzogen, und von den Menschen ward er verstoßen, und wie die Ochsen aß er vom Kraut, und vom Tau der Himmel ward sein Leib benetzt, bis daß sein Haar wuchs wie das der Adler, und seine Nägel wie Vogelklauen.',
        31: 'Und am Ende der Tage hob ich, Nebuchadnezzar, meine Augen auf zu den Himmeln, und meine Erkenntnis kehrte mir zurück, und ich segnete den Höchsten, und pries und ehrte Ihn, Der da lebt in Ewigkeit, Dessen Herrschaft eine ewige Herrschaft ist, und Dessen Reich ist zu Geschlecht und Geschlecht.',
        32: 'Und alle Bewohner der Erde sind als nichts zu achten, und nach Seiner Neigung tut Er mit der Streitmacht der Himmel und mit denen, die auf der Erde wohnen. Und da ist keiner, der Seiner Hand wehrete und zu Ihm spräche: Was tust du?',
        33: 'Zur selben Zeit kam mir meine Kenntnis zurück, und die Pracht meines Reiches, meine Ehre und mein Glanz kehrte mir zurück, und meine Räte und meine Großen suchten mich, und ich ward wieder in mein Königtum eingesetzt und über die Maßen Größe ward mir hinzugetan.',
        34: 'Nun preise und erhöhe und ehre ich, Nebuchadnezzar, den König der Himmel, Dessen ganzes Tun ist Wahrheit, und Dessen Pfade sind Gericht, und die, so im Übermut dahingehen, vermag Er zu erniedrigen.',
    },
    5: {
        1: 'König Belschazzar machte seinen tausend Großen ein großes Mahl und trank vor den Tausenden Wein.',
        2: 'Belschazzar befahl, als er den Wein geschmeckt, die Gefäße von Gold und von Silber zu bringen, die sein Vater Nebuchadnezzar aus dem Tempel in Jerusalem weggenommen, daß daraus tränken der König und seine Großen, seine Gemahlinnen und seine Kebsen.',
        3: 'Da brachten sie die goldenen Gefäße, die sie aus dem Tempel des Hauses Gottes in Jerusalem hinweggenommen hatten, und der König und seine Großen, seine Gemahlinnen und Kebsen tranken daraus.',
        4: 'Sie tranken den Wein und priesen die Götter von Gold und von Silber, von Erz, von Eisen, von Holz und von Stein.',
        5: 'Zur selben Stunde kamen Finger der Hand eines Menschen hervor und schrieben dem Leuchter gegenüber auf den Kalk der Wand des Palastes des Königs, und der König schaute das Gelenke der Hand, die schrieb.',
        6: 'Da veränderte sich des Königs Farbe und seine Gedanken machten ihn bestürzt, und die Bande seiner Lenden lösten sich und seine Knie schlugen eins ans andere.',
        7: 'Da rief der König mit Macht, man solle die Wahrsager, die Chaldäer und die Sterndeuter hereinbringen; der König hob an und sprach zu den Weisen Babels: Jeder Mensch, der diese Schrift liest und ihre Deutung mir anzeigt, soll in Purpur gekleidet werden, eine Halskette von Gold um den Hals haben und als der Dritte im Königreich schalten.',
        8: 'Da kamen herein alle Weisen des Königs, aber sie vermochten nicht, die Schrift zu lesen, noch deren Deutung dem König kundzutun.',
        9: 'Da ward der König sehr bestürzt, und seine Farbe veränderte sich, und auch seine Großen wurden verwirrt.',
        10: 'Die Königin wegen der Worte des Königs und seiner Großen trat in den Tranksaal, und die Königin hob an und sprach: Der König lebe ewiglich; laß dich deine Gedanken nicht bestürzt machen und dein Gesicht sich nicht verändern.',
        11: 'Es ist ein Mann in deinem Königreich, in dem der Geist der heiligen Götter ist; und in den Tagen deines Vaters ist Erleuchtung und Verstand und Weisheit wie die Weisheit der Götter in ihm erfunden worden, und der König Nebuchadnezzar, dein Vater, hat ihn zum Obersten der Magier, der Wahrsager, der Chaldäer, der Sterndeuter eingesetzt, dein Vater, der König.',
        12: 'Alldieweil ein Geist über die Maßen, und Kenntnis und Verstand, die Deutung von Träumen und das Anzeigen von Rätseln, und die Auflösung knotiger Fragen in ihm ist erfunden worden, in Daniel, dem der König den Namen Beltschazzar beilegte. Nun rufe man Daniel, und er wird die Deutung anzeigen.',
        13: 'Da ward Daniel hereingebracht vor den König. Der König hob an und sprach zu Daniel: Du bist Daniel, von den Söhnen der Verbannung Jehudahs, die mein Vater, der König, aus Jehudah gebracht hat.',
        14: 'Und ich habe von dir gehört, daß der Geist der Götter in dir ist, und Erleuchtung und Verstand und Weisheit über die Maßen in dir ist erfunden worden.',
        15: 'Und nun wurden vor mich geführt die Weisen, die Wahrsager, auf daß sie diese Schrift lesen und deren Deutung mir kundtun, aber sie vermögen nicht die Deutung des Wortes anzuzeigen.',
        16: 'Und ich hörte von dir, daß du Deutungen zu deuten und knotige Fragen aufzulösen vermögest. Wenn du nun vermagst, die Schrift zu lesen und ihre Deutung mir kund zu tun, sollst du dich mit Purpur anziehen und eine Halskette von Gold um deinen Hals haben, und als der Dritte im Königreich schalten.',
        17: 'Da antwortete Daniel und sprach vor dem König: Deine Gaben seien dein und deinen Ehrensold gib einem anderen! Jedoch die Schrift will ich dem König lesen und die Deutung ihm zu wissen tun.',
        18: 'O du König, der höchste Gott hatte Nebuchadnezzar, deinem Vater, das Königreich und die Größe und die Pracht und die Ehre gegeben.',
        19: 'Und vor der Größe, die Er ihm gab, erzitterten alle Völker, Volksstämme und Zungen und scheuten sich vor ihm. Wen er wollte, tötete er, und wen er wollte, ließ er am Leben, und wen er wollte, erhöhte er, und wen er wollte, erniedrigte er.',
        20: 'Und darob erhöhte sich sein Herz, und sein Geist ward stark, so daß er vermessen handelte, und er ward vom Thron seines Königtums hinabgestoßen, und seine Pracht wich von ihm.',
        21: 'Und von den Menschensöhnen ward er verstoßen, und sein Herz machte er gleich mit dem Tier, und mit den wilden Eseln verweilte er und schmeckte Kraut wie die Ochsen, und von dem Tau des Himmels ward sein Leib benetzt, bis daß er erkannte, daß der höchste Gott schaltet über des Menschen Reich, und wen Er will, über sie einsetzt.',
        22: 'Und du, sein Sohn, Belschazzar, hast dein Herz nicht erniedrigt, während du all dies wußtest;',
        23: 'Und hast dich erhöht über den Herrn der Himmel, und die Gefäße Seines Hauses vor dich bringen lassen; und du und deine Großen, deine Gemahlinnen und deine Kebsen haben Wein daraus getrunken, und die Götter aus Silber und Gold, Erz, Eisen, Holz und Stein, die nicht schauen und nicht hören und nichts wissen, gepriesen, und dem Gott, in Dessen Hand dein Odem ist und all deine Pfade sind, Ihn hast du nicht geehrt.',
        24: 'Darum hat Er von Ihm das Gelenk der Hand ausgereckt und diese Schrift gezeichnet.',
        25: 'Und das ist die Schrift, die gezeichnet ist: Mene, mene, tekel, upharsin.',
        26: 'Dies ist die Deutung des Wortes: Mene, Gott hat gezählt dein Königtum und hat es vollendet.',
        27: 'Tekel, du bist in der Waage gewogen und mangelnd erfunden worden!',
        28: 'Peres, zerteilt wird dein Königreich und den Medern und Persern gegeben.',
        29: 'Da befahl Belschazzar, und man zog dem Daniel Purpur an und eine Halskette von Gold um seinen Hals, und riefen aus über ihn, daß er als Dritter schalten solle im Königreich.',
        30: 'In derselben Nacht ward Belschazzar, der König der Chaldäer, getötet.',
    },
    6: {
        1: 'Und Darius, der Meder, empfing das Königreich, da er zweiundsechzig Jahre alt war.',
        2: 'Und es gefiel Darius, daß er über das Königreich hundertzwanzig Satrapen einsetzte, die in dem ganzen Königreich sein sollten;',
        3: 'Und über sie drei Fürsten, von denen einer Daniel war, so daß ihnen diese Satrapen Rechenschaft geben sollten, und der König keinen Schaden hätte.',
        4: 'Da übertraf dieser Daniel die Fürsten und die Satrapen, alldieweil ein Geist über die Maßen in ihm war; und der König gedachte ihn über das ganze Reich einzusetzen.',
        5: 'Deshalb suchten die Fürsten und die Satrapen eine Sache zu finden wider Daniel von seiten des Königreichs; aber sie vermochten keine Sache und keine Verdorbenheit zu finden, denn er war treu und kein Fehler und keine Verdorbenheit ward an ihm gefunden.',
        6: 'Da sprachen diese Männer: Wir werden an diesem Daniel keine Sache finden, wofern wir nicht etwas wider ihn im Gesetze seines Gottes finden.',
        7: 'Da bestürmten diese Fürsten und Satrapen den König und sprachen zu ihm also: Ewiglich lebe der König Darius!',
        8: 'Es sind alle Fürsten des Königreiches, die Landvögte und die Satrapen, die Räte und die Statthalter zu Rate gegangen, daß der König solle eine Satzung aufsetzen und ein Verbot bestärken, daß jeder, der eine Bitte erbittet von irgendeinem Gott oder Menschen, binnen dreißig Tagen, außer von dir, o König, in die Löwengrube hinabgeworfen werde.',
        9: 'Nun solltest du, o König, das Verbot aufsetzen und das Schreiben unterzeichnen, auf daß es nicht geändert werde, als ein Gesetz von Medien und Persien, das nicht vergeht.',
        10: 'Darum unterzeichnete der König Darius denn die Schrift und das Verbot.',
        11: 'Und als Daniel wußte, daß die Schrift unterzeichnet war, ging er in sein Haus; und die Fenster waren offen in seinem Obergemach gegen Jerusalem hin, und dreimal des Tages kniete er auf seine Knie und betete und bekannte vor seinem Gott, gleichwie er vordem getan hatte.',
        12: 'Da stürmten diese Männer herein und fanden Daniel, wie er ersuchte und flehte vor seinem Gott.',
        13: 'Da nahten sie und sprachen vor dem König über das Verbot des Königs: Hast du nicht ein Verbot unterzeichnet, daß jeder Mensch, der von irgendeinem Gott oder Menschen binnen dreißig Tagen außer von dir, o König, etwas ersuche, in die Löwengrube hinabgeworfen werden solle? Der König antwortete und sprach: Fest steht das Wort als Gesetz von Medien und Persien, das nicht vergeht.',
        14: 'Da antworteten sie und sprachen vor dem Könige: Daniel, der einer der Söhne der Verbannung von Jehudah ist, hat nicht Acht auf dich, o König, und auf das Verbot, das du unterzeichnet hast, und dreimal des Tages ersucht er sein Ersuchen.',
        15: 'Als der König dies Wort hörte, ward er sehr betrübt darob, und war besorgt für Daniel, daß er ihn befreite und bestrebte sich bis Sonnenuntergang, daß er ihn errettete.',
        16: 'Da stürmten diese Männer herein zu dem Könige und sprachen zum König: Wisse, o König, daß es ein Gesetz von Medien und Persien ist, daß kein Verbot oder Satzung, vom König aufgesetzt, verändert werde.',
        17: 'Da befahl der König und sie brachten Daniel herbei und warfen ihn hinab in die Löwengrube. Der König hob an und sprach zu Daniel: Dein Gott, Den du unablässig verehrst, befreie dich!',
        18: 'Und es ward ein Stein gebracht, und auf die Öffnung der Grube gelegt, und mit dem Siegelring des Königs und dem Siegelring seiner Großen versiegelt, auf daß sein Wille über Daniel nicht verändert werde.',
        19: 'Da ging der König weg in seinen Palast und brachte die Nacht in Fasten zu, und ließ keine Tänzerinnen vor sich kommen, und sein Schlaf floh weg von ihm.',
        20: 'Dann mit der Morgenröte, mit dem Lichte erhob sich der König und ging in Eile nach der Löwengrube.',
        21: 'Und wie er der Grube nahte, schrie er mit schmerzlicher Stimme zu Daniel. Der König hob an und sprach zu Daniel: Daniel, Knecht des lebendigen Gottes, hat dein Gott, Den du unablässig verehrst, vermocht, dich von den Löwen zu befreien?',
        22: 'Da redete Daniel mit dem Könige: Ewig lebe der König!',
        23: 'Mein Gott hat Seinen Engel gesandt und den Löwen den Rachen verschlossen, daß sie mich nicht schädigten, alldieweil vor Ihm Lauterkeit an mir erfunden worden, und ich auch vor dir keinen Schaden getan habe, o König!',
        24: 'Da ward der König sehr froh über ihn, und befahl, den Daniel aus der Grube heraufzubringen. Und Daniel ward aus der Grube heraufgebracht, und war keine Schädigung an ihm erfunden, weil er an seinen Gott geglaubt.',
        25: 'Und der König befahl, daß man diese Männer bringe, die Daniel angeklagt hatten, und man warf sie, ihre Söhne und ihre Weiber in die Löwengrube hinab, und sie hatten kaum den Boden der Grube erreicht, als die Löwen ihrer mächtig wurden und all ihre Gebeine zermalmten.',
        26: 'Da schrieb König Darius an alle Völker, Volksstämme und Zungen, die auf der ganzen Erde weilen: Euer Friede nehme zu!',
        27: 'Von mir aus ergeht die Weisung, daß man in der ganzen Herrschaft meines Königreichs vor dem Gotte Daniels erzittern und sich scheuen soll: Denn Er ist der lebendige Gott, Der besteht in Ewigkeit, und Sein Reich wird nicht umgestoßen, und bis an das Ende ist Seine Herrschaft.',
        28: 'Er befreit und errettet und tut Zeichen und Wunder am Himmel und auf Erden, Er, Der Daniel aus der Gewalt der Löwen befreit hat. Und dieser Daniel hatte Gedeihen unter der Regierung des Darius und unter der Regierung von Koresch dem Perser.',
    },
    7: {
        1: 'Im ersten Jahre Belschazzars, König von Babel, schaute Daniel einen Traum und Gesichte seines Hauptes auf seinem Lager. Er schrieb dann den Traum nieder; er sagte den Inhalt der Sache.',
        2: 'Daniel hob an und sprach: Ich schaute in meinem Gesichte bei der Nacht, und siehe, die vier Winde des Himmels brachen hervor auf das große Meer.',
        3: 'Und vier große Tiere stiegen herauf aus dem Meer, eines verschieden von dem anderen.',
        4: 'Das erste war wie ein Löwe und hatte Adlersschwingen; und ich schaute, bis seine Schwingen ihm ausgerauft wurden und es sich erhob von der Erde und richtete sich auf auf seine Füße wie ein Mensch, und ein Menschenherz ward ihm gegeben.',
        5: 'Und siehe, ein anderes, zweites Tier glich einem Bären, und richtete sich auf einer Seite auf, und drei Rippen waren in seinem Rachen zwischen seinen Zähnen, und sie sagten ihm also: Stehe auf, friß viel Fleisch!',
        6: 'Hierauf schaute ich, und siehe, ein anderes, wie ein Parder, und es hatte vier Schwingen wie ein Vogel auf seinem Rücken, und das Tier hatte vier Häupter, und ihm ward Herrschaft gegeben.',
        7: 'Nach diesen schaute ich in Gesichten der Nacht und siehe, ein viertes Tier, schauerlich und schrecklich und über die Maßen stark, und es hatte große Zähne von Eisen, es fraß und zermalmte und zertrat, was übrigblieb, mit seinen Füßen, und es war verschieden von allen Tieren vor ihm, und hatte zehn Hörner.',
        8: 'Ich gab acht auf die Hörner; und siehe, ein anderes, kleines Horn kam herauf zwischen ihnen, und vor ihm wurden drei der ersten Hörner ausgerissen, und siehe, Augen wie Menschenaugen waren an diesem Horn, und ein Mund, der Großes redete.',
        9: 'Ich schaute, bis Throne hinabgeworfen wurden, und der Alte der Tage setzte Sich. Sein Gewand war weiß wie Schnee, und das Haar Seines Hauptes wie reine Wolle, Sein Thron Flammen des Feuers, dessen Räder brennendes Feuer.',
        10: 'Ein Strom von Feuer ergoß sich, und ging vor Ihm aus, und tausendmal Tausende dienten Ihm, und zehntausendmal Zehntausende standen vor Ihm. Das Gericht saß, und Bücher wurden geöffnet.',
        11: 'Ich schaute zu wegen der Stimme der großen Worte, die das Horn redete; ich schaute, bis daß das Tier getötet ward und sein Leib zerstört wurde und dem brennenden Feuer übergeben ward.',
        12: 'Und den übrigen Tieren ward ihre Herrschaft genommen, aber des Lebens Länge ward ihnen gegeben, bis auf eine Frist und eine Zeit.',
        13: 'Ich schaute in den Gesichten der Nacht, und siehe, mit den Wolken der Himmel kam wie des Menschen Sohn und gelangte bis zum Alten der Tage, und sie ließen Ihn vor Denselben nahen.',
        14: 'Und Ihm ward gegeben Herrschaft und Pracht und Reich, und alle Völker, Volksstämme und Zungen sollen Ihm dienen. Seine Herrschaft ist eine ewige Herrschaft, die nicht vergeht, und Sein Königtum, das nicht wird umgestoßen.',
        15: 'Und ich, Daniel, ward betrübt in meinem Geiste, inmitten seiner Hülle, und die Gesichte meines Hauptes machten mich bestürzt.',
        16: 'Ich nahte mich einem von denen, die da standen, und ersuchte ihn um Gewisses über all dies; und er sprach mit mir und tat mir die Deutung der Dinge kund:',
        17: 'Diese großen Tiere, deren es vier sind, sind vier Könige, die auf Erden erstehen werden.',
        18: 'Aber die Heiligen des Höchsten werden das Reich empfangen, und das Reich innehaben in Ewigkeit, und in die Ewigkeit der Ewigkeiten.',
        19: 'Dann wollte ich Gewisses über das vierte Tier, das von ihnen allen verschieden war, über die Maßen schauerlich, seine Zähne von Eisen und seine Klauen von Erz, es fraß und zermalmte und zertrat den Überrest mit den Füßen.',
        20: 'Und über die zehn Hörner auf seinem Haupte, und das andere, das heraufkam, und es fielen vor ihm drei; und dieses Horn hatte Augen und einen Mund, der Großes redete, und sein Ansehen war größer denn seiner Gesellen.',
        21: 'Und ich schaute, und dieses Horn geriet in Kampf mit den Heiligen und überwand sie.',
        22: 'Bis daß kam der Alte der Tage und Gericht gab den Heiligen des Höchsten, und es kam die bestimmte Zeit, daß die Heiligen das Reich innehaben sollten.',
        23: 'Er sprach also: Das vierte Tier ist das vierte Königreich, das sein wird auf Erden, das verschieden sein wird von allen Königreichen, und wird fressen die ganze Erde, und sie zerstampfen und zermalmen.',
        24: 'Und was anlangt die zehn Hörner, so werden aus ihm, dem Königreiche, zehn Könige erstehen und ein anderer wird erstehen nach ihnen, und wird verschieden sein von den ersten, und wird drei Könige erniedrigen.',
        25: 'Und er wird Worte reden wider den Höchsten, und verstören die Heiligen des Höchsten, und wird sich unterfangen, Zeiten und Gesetz zu ändern, und sie werden in seine Hand gegeben werden, eine Zeit und Zeiten und eine halbe Zeit.',
        26: 'Und das Gericht wird sitzen und seine Herrschaft wird man wegnehmen, vernichten und zerstören bis zum Ende.',
        27: 'Und das Reich und die Herrschaft und die Größe der Königreiche unter all den Himmeln wird dem Volk der Heiligen des Höchsten gegeben werden; Sein Reich wird sein ein Reich der Ewigkeit, und alle Herrschaften werden Ihn verehren und Ihm gehorchen.',
        28: 'Bis hierher das Ende des Wortes. Ich, Daniel, war sehr bestürzt in meinen Gedanken, und meine Farbe veränderte sich an mir und ich bewahrte das Wort in meinem Herzen.',
    },
    8: {
        1: 'Im dritten Jahre der Regierung Belschazzars, des Königs, erschien mir, Daniel, ein Gesichte nach dem, das mir zu Anbeginn erschienen war.',
        2: 'Und ich sah in dem Gesichte, und es geschah, da ich es sah, da war ich auf der Burg Susan, die in der Landschaft Elam ist, und ich sah in dem Gesichte und war an dem Flusse Ulai.',
        3: 'Und ich hob meine Augen auf und sah, und siehe, ein Widder stand vor dem Flusse und hatte zwei Hörner, und die Hörner waren hoch, und das eine war höher als das zweite, und das höhere wuchs später herauf.',
        4: 'Und ich sah den Widder stoßen dem Meere zu und nach Mitternacht und nach Mittag, und keine Tiere konnten vor ihm bestehen und niemand erretten von seiner Hand, und tat nach seinem Wohlgefallen und machte sich groß.',
        5: 'Und ich betrachtete ihn, und siehe, ein Bock von den Ziegen kam vom Abend über die Oberfläche der ganzen Erde daher und berührte die Erde nicht; und der Bock hatte ein ansehnliches Horn zwischen seinen Augen.',
        6: 'Und er kam zu dem Widder mit den zwei Hörnern, den ich vor dem Flusse stehen sah, und lief auf ihn zu im Grimm seiner Kraft.',
        7: 'Und ich sah, daß er den Widder erreichte und sich gegen ihn erbitterte, und den Widder schlug, und seine zwei Hörner zerbrach, so daß der Widder keine Kraft hatte vor ihm zu stehen, und er ihn zur Erde warf und zerstampfte, und niemand den Widder aus seiner Hand errettete.',
        8: 'Und der Bock von den Ziegen tat sehr groß; da er aber mächtig wurde, zerbrach das große Horn, und es kamen vier ansehnliche anstatt seiner herauf nach den vier Winden der Himmel.',
        9: 'Und aus dem einen von ihnen kam ein kleines Horn hervor, und ward über die Maßen groß gen Mittag und gegen Aufgang und gegen die Zierde.',
        10: 'Und es wurde groß bis zum Heer der Himmel, und fällte zur Erde etliche von dem Heere und von den Sternen, und zerstampfte sie.',
        11: 'Und bis zum Obersten des Heeres machte es sich groß, und nahm Ihm weg das Beständige und warf hinab die Stätte Seiner Heiligkeit.',
        12: 'Und das Heer ward hingegeben samt dem Beständigen zur Übertretung, und man warf die Wahrheit zur Erde, und tat es und es gelang.',
        13: 'Und ich hörte einen Heiligen reden, und ein Heiliger sprach zu einem, der da redete: Wie lange ist dies Gesichte, das Beständige und die verwüstende Übertretung, das Heiligtum hinzugeben und das Herr zum Zerstampfen?',
        14: 'Und Er sprach zu mir bis zum Abend, zum Morgen, zweitausend und dreihundert; so wird das Heilige gerechtfertigt.',
        15: 'Und es geschah, als ich, Daniel, das Gesichte sah, und dessen Verständnis suchte, und siehe, da stand einer mir gegenüber, anzusehen wie ein Mann.',
        16: 'Und ich hörte die Stimme eines Menschen zwischen dem Ulai hervor, und er rief und sprach: Gabriel, laß diesen das Gesichte verstehen.',
        17: 'Und er kam daneben, wo ich stand; und wie er kam, ward ich verstört und fiel auf mein Angesicht. Und er sprach zu mir: Merke auf, Menschensohn, denn das Gesichte ist für die Zeit des Endes.',
        18: 'Und wie er mit mir redete, fiel ich im tiefen Schlaf auf mein Angesicht zur Erde; und er rührte mich an, und ließ mich stehen, daß ich stand.',
        19: 'Und er sprach: Siehe, ich tue dir kund, was geschehen wird auf die Letzte des Unwillens: denn zur bestimmten Zeit ist das Ende.',
        20: 'Der Widder mit den zwei Hörnern, den du gesehen hast, sind die Könige von Medien und Persien.',
        21: 'Und der Bock von den Ziegen ist der König von Griechenland, und das große Horn zwischen seinen Augen, er ist der erste König.',
        22: 'Und daß es zerbrochen ward und vier statt seiner aufstanden, sind vier Königreiche, die aus der Völkerschaft aufstehen, aber nicht mit seiner Kraft.',
        23: 'Und in der Letzte ihres Reiches, wenn die Übertreter ihr Maß erfüllt haben, wird ein König dastehen, frech von Angesicht und der Tücke versteht.',
        24: 'Und gewaltig wird seine Kraft, aber nicht durch seine eigene Kraft, und er wird wunderlich verderben, und es wird ihm gelingen, daß er es tue, und er wird verderben Gewaltige und das Volk der Heiligen.',
        25: 'Und durch seine Klugheit, und weil ihm Trug gelingt unter seiner Hand, und er wird in seinem Herzen groß tun, wird er in ihrer Sicherheit viele verderben, und stehen wider den Obersten der Obersten, und wird ohne Hand zerbrochen.',
        26: 'Und das Gesichte des Abends und des Morgens, wovon gesagt worden ist, das ist Wahrheit; aber du sollst das Gesichte verschließen; denn es ist für viele Tage.',
        27: 'Ich aber, Daniel, war dahin, und war mehrere Tage krank, aber ich stand auf und tat das Geschäft des Königs, und ich erstaunte ob der Erscheinung, und niemand verstand es.',
    },
    9: {
        1: 'Im ersten Jahre von Darius, dem Sohne des Achaschverosch, von dem Samen der Meder, der über der Chaldäer Reich zum König gemacht ward,',
        2: 'Im ersten Jahre seines Königtums vermerkte ich, Daniel, in den Büchern die Zahl der Jahre, davon das Wort Jehovahs zum Propheten Jeremiah geschehen, daß die Verödungen Jerusalems erfüllt würden siebzig Jahre.',
        3: 'Und ich wandte mein Angesicht zum Herrn Gott, zu bitten ein Gebet und ein Flehen, mit Fasten und Sack und Asche.',
        4: 'Und ich betete zu Jehovah, meinem Gott, und bekannte und sprach: Ach Herr, großer und furchtbarer Gott, Der Bund und Barmherzigkeit hält denen, die Ihn lieben und Seine Gebote halten.',
        5: 'Wir haben gesündigt und Missetat begangen, und ungerecht gehandelt, und uns empört, und sind von Deinen Geboten und Rechten abgewichen.',
        6: 'Und haben nicht gehört auf Deine Knechte, die Propheten, die in Deinem Namen zu unseren Königen, unseren Obersten und Vätern und zu allem Volk des Landes geredet haben.',
        7: 'Dein, o Herr, ist Gerechtigkeit, unser aber Scham des Angesichts wie dieses Tages bei dem Mann von Jehudah und bei denen, so in Jerusalem und in ganz Israel wohnen, denen, die nahe und die fern sind in allen Landen, wohin Du sie verstoßen hast ob der Untreue, daß sie von Dir abgefallen sind.',
        8: 'O Herr, unser ist Scham des Angesichts, unseren Königen, unseren Obersten und unseren Vätern, die wir wider Dich gesündigt haben.',
        9: 'Dein, o Herr, unser Gott, ist Erbarmen und Vergebung, denn wir haben uns empört wider Ihn.',
        10: 'Und haben nicht gehört auf die Stimme Jehovahs, unseres Gottes, daß wir gewandelt wären nach Seinen Gesetzen, die Er durch die Hand Seiner Knechte, die Propheten, vor uns gegeben.',
        11: 'Und ganz Israel hat Dein Gesetz übertreten und ist abgewichen und hat nicht auf Deine Stimme gehört; darum ergoß sich über uns die Verwünschung und der Schwur, der geschrieben ist im Gesetze Moses, des Knechts Gottes, weil wir wider Ihn gesündigt haben.',
        12: 'Und Er hat Sein Wort bestätigt, das Er geredet hat über uns und über unsere Richter, die uns richteten, und über uns kommen lassen so großes Übel, desgleichen nicht geschehen unter allen Himmeln, wie es geschehen ist in Jerusalem.',
        13: 'Wie im Gesetze Moses geschrieben ist, ist all dieses Böse über uns gekommen; wir aber flehten nicht an vor Jehovah, unserem Gotte, daß wir von unseren Missetaten umkehrten und merkten auf Deine Wahrheit.',
        14: 'Und der Herr ist wach gewesen mit dem Übel und hat es über uns kommen lassen; denn gerecht ist Jehovah, unser Gott, in allen Seinen Taten, die Er tut, aber wir haben nicht auf Seine Stimme gehört.',
        15: 'Und nun, Herr, unser Gott, Der Du Dein Volk mit starker Hand aus dem Lande Ägypten herausgebracht, und Dir einen Namen gemacht hast, wie er ist an diesem Tage, wir haben gesündigt und ungerecht gehandelt.',
        16: 'Herr, nach all Deiner Gerechtigkeit wende zurück Deinen Zorn und Deinen Grimm von Deiner Stadt Jerusalem, von dem Berge Deiner Heiligkeit! Denn durch unsere Sünden und durch die Missetaten unserer Väter ist Jerusalem und Dein Volk zur Schmach geworden bei allen, die uns umgeben.',
        17: 'Und nun höre, unser Gott, auf das Gebet Deines Knechtes und auf sein Flehen, und laß leuchten Dein Angesicht über Dein Heiligtum, das verwüstete, um des Herrn willen.',
        18: 'Neige, o Gott, Dein Ohr und höre, tue auf Deine Augen und siehe, wie verwüstet sind wir und die Stadt, über der Dein Name genannt wird, denn nicht um unserer Gerechtigkeit willen lassen wir unser Flehen vor Dein Angesicht niederfallen, sondern um Deiner vielen Erbarmungen willen.',
        19: 'O Herr, höre, o Herr, vergib, o Herr, horche und tue es und zögere nicht, um Deiner selbst willen, o mein Gott, denn Dein Name wird über Deiner Stadt und über Deinem Volke genannt.',
        20: 'Und noch redete ich, und betete und bekannte meine Sünde und die Sünde meines Volkes Israel, und ließ mein Flehen fallen vor Jehovah, meinem Gott, für den Berg der Heiligkeit meines Gottes.',
        21: 'Und noch redete ich im Gebet, da flog daher im Flug der Mann Gabriel, den ich zu Anbeginn im Gesichte gesehen, und rührte mich an um die Zeit des Speiseopfers am Abend.',
        22: 'Und er unterrichtete mich und redete mit mir und sprach: Daniel, ich bin nun ausgegangen, dich zu unterrichten in Einsicht.',
        23: 'Zu Anbeginn deines Flehens ging das Wort aus, und ich bin gekommen, dir anzusagen, daß du bist ein Liebling; und merke du auf das Wort und merke auf die Erscheinung.',
        24: 'Siebzig Wochen sind bestimmt über dein Volk und über die Stadt deiner Heiligkeit, zu vollenden die Übertretung und zu besiegeln die Sünden und zu sühnen die Missetat, und hereinzubringen die Gerechtigkeit der Zeitalter und zu besiegeln das Gesetz und den Propheten und zu salben das Heilige des Heiligen.',
        25: 'Und du sollst wissen und merken: Vom Ausgehen des Wortes, daß Jerusalem wieder hergestellt und gebaut werden soll, bis auf den Messias, den Fürsten, sind es sieben Wochen und zweiundsechzig Wochen, da werden die Straße und der Graben wieder hergestellt und gebaut, aber in der Angst der Zeiten.',
        26: 'Und nach den zweiundsechzig Wochen wird der Gesalbte ausgerottet, aber nicht für Sich. Und die Stadt und das Heiligtum wird verderben das Volk eines Fürsten, der da kommt, und sein Ende wird sein mit einer Flut, und bis zum Ende des Streites sind die Verwüstungen entschieden.',
        27: 'Er wird aber vielen den Bund bestärken eine Woche, und in der Hälfte der Woche das Schlachtopfer und Speiseopfer zu Ende bringen, und auf den Vogel der Scheusale die Verwüstung, und bis zur Vollendung und Entscheidung wird es sich ergießen über die Verwüstung.',
    },
    10: {
        1: 'Im dritten Jahre des Koresch, des Königs von Persien, wurde Daniel, den man mit Namen Beltschazzar nannte, ein Wort geoffenbart, und das Wort ist Wahrheit und ein großer Heereszug; und er verstand das Wort, und es ward ihm das Verständnis des Gesichtes.',
        2: 'In selbigen Tagen trauerte ich, Daniel, drei Wochen der Tage,',
        3: 'Ich aß kein leckeres Brot, Fleisch und Wein kam nicht zu meinem Munde, auch salbte ich mich nicht mit Salben, bis die drei Wochen der Tage sich erfüllten.',
        4: 'Und am vierundzwanzigsten Tage des ersten Monats, da war ich am Ufer des großen Flusses, welcher ist der Chiddekel.',
        5: 'Und ich hob meine Augen auf und sah, und siehe, da stand ein Mann, in Linnen gekleidet, und seine Lenden gegürtet mit lauterem Gold aus Uphas.',
        6: 'Und sein Leib war wie ein Tharschisch, und sein Angesicht wie das Ansehen des Blitzes und seine Augen wie Fackeln von Feuer, und seine Arme und seine Füße wie der Anblick des geglätteten Erzes, und die Stimme seiner Worte wie die Stimme einer Volksmenge.',
        7: 'Und ich, Daniel, allein sah die Erscheinung, und die Männer, so mit mir waren, sahen die Erscheinung nicht; aber ein großes Erzittern fiel über sie, und sie entwichen, sich zu verstecken.',
        8: 'Und ich allein verblieb und sah diese große Erscheinung; es verblieb aber keine Kraft in mir und meine Majestät verwandelte sich bis zum Verderben, und ich behielt keine Kraft.',
        9: 'Und ich hörte die Stimme seiner Worte, und wie ich die Stimme seiner Worte gehört, war ich in tiefem Schlaf, auf meinem Angesicht, und mein Angesicht zur Erde.',
        10: 'Und siehe, eine Hand rührte mich an und hob mich auf die Knie und auf die flachen Hände;',
        11: 'Und sprach zu mir: Mann des Wohlgefallens merke auf die Worte, die ich zu dir rede und stehe auf deine Stätte, denn ich bin jetzt zu dir gesandt. Und wie er diese Worte mit mir redete, stand ich mit Beben auf.',
        12: 'Und er sprach zu mir: Fürchte dich nicht, Daniel, denn seit dem ersten Tage, da du dein Herz hingabst, Verständnis zu erlangen und dich zu demütigen vor deinem Gotte, sind deine Worte erhört worden, und ich bin gekommen um deiner Worte willen.',
        13: 'Und der Oberste des Reiches Persiens ist einundzwanzig Tage wider mich gestanden; und siehe, Michael, einer der ersten Obersten, ist gekommen, mir beizustehen, und ich blieb übrig neben den Königen von Persien.',
        14: 'Und ich bin gekommen, dich zu unterrichten, was in den letzten der Tage deinem Volke begegnen wird, denn das Gesichte geht noch auf Tage.',
        15: 'Und wie er so mit mir diese Worte redete, schlug ich mein Angesicht nieder zur Erde und war stumm.',
        16: 'Und siehe, einer, ähnlich wie ein Menschensohn, rührte an meine Lippen, und ich öffnete meinen Mund und redete und sprach zu dem, der mir gegenüber stand: Mein Herr, über der Erscheinung kehren meine Wehen sich wider mich, und ich habe keine Kraft mehr behalten.',
        17: 'Und wie vermag der Knecht dieses meines Herrn zu reden mit diesem meinem Herrn, weil seit der Zeit keine Kraft in mir besteht und kein Odem mehr in mir verblieben ist.',
        18: 'Und es rührte mich wiederum einer an, der das Ansehen eines Menschen hatte, und stärkte mich,',
        19: 'Und sprach: Fürchte dich nicht, Mann des Wohlgefallens, Friede sei mit dir, sei stark, sei stark! Und wie er mit mir redete, erstarkte ich und sagte: Mein Herr, rede, denn du hast mich gestärkt.',
        20: 'Und er sprach: Weißt du, warum ich zu dir gekommen bin? Und jetzt kehre ich zurück, zu streiten mit dem Obersten Persiens, aber wenn ich hinausgehe, siehe, da kommt der Oberste von Griechenland.',
        21: 'Aber ich will dir ansagen, was in der Schrift der Wahrheit verzeichnet ist, und es ist nicht einer, der sich mit mir stärkt wider diesen, als euer Oberster Michael.',
    },
    11: {
        1: 'Und ich stand bei ihm im ersten Jahre des Darius, des Meders, ihn zu halten und ihm zur Stärke.',
        2: 'Und nun will ich dir Wahrheit ansagen: Siehe, noch drei Könige werden in Persien stehen; und der vierte wird mit größerem Reichtum sich bereichern denn alle, und wenn er am stärksten ist durch seinen Reichtum, wird er alles erregen gegen das griechische Reich.',
        3: 'Und ein mächtiger König wird erstehen, und eine große Herrschaft beherrschen und tun nach seinem Wohlgefallen.',
        4: 'Und wenn er so steht, wird sein Reich zerbrechen und sich nach den vier Winden der Himmel zerteilen, und nicht für seine Nachkommen, und nicht mit der Herrschaft, mit der er geherrscht, und sein Reich wird ausgerodet und anderen außer ihnen werden.',
        5: 'Und der König des Mittags und einer seiner Obersten wird stark sein, und wird stark werden wider ihn und herrschen; eine große Herrschaft wird seine Herrschaft sein.',
        6: 'Und am Ende von Jahren werden sie sich verbünden, und die Tochter des Königs von Mittag wird zum König gen Mitternacht kommen, um das Gerade zu tun, aber sie wird die Kraft des Arms nicht behalten und er und sein Arm werden nicht bestehen, und sie wird hingegeben, sie und die sie hergeführt, so wie auch ihr Erzeuger und der, der sie gestärkt hatte in den Zeiten.',
        7: 'Aber es wird ein Reis von ihrer Wurzel an seiner Stelle erstehen und zur Streitmacht kommen, und kommen in die Festung des Königs der Mitternacht, und wider sie tun und siegen,',
        8: 'Und auch ihre Götter mit ihren Guß-bildern samt den kostbaren Gefäßen von Silber und Gold in Gefangenschaft wegführen nach Ägypten, und wird Jahrelang stehen vor dem König von Mitternacht.',
        9: 'Und er wird kommen in das Reich des Königs von Mittag, aber wieder auf seinen Boden zurückkehren.',
        10: 'Und seine Söhne werden Fehden erheben und eine Volksmenge vieler Streitmächte versammeln, und wird kommen und überfluten und daherfahren, und wird zurückkehren und bis zu seinen Festungen befehden.',
        11: 'Und der König vom Mittag wird sich erbittern und ausziehen und streiten mit ihm, mit dem König von Mitternacht, und wird aufstellen viel Volksmenge, aber die Volksmenge wird in seine Hand gegeben.',
        12: 'Und er wird die Volksmenge wegnehmen und sein Herz wird sich erhöhen, und Zehntausende fällen, wird ihn aber nicht überwältigen.',
        13: 'Und der König von Mitternacht wird widerkommen und eine Volksmenge aufstellen, größer denn die vorige, und am Ende der Zeiten der Jahre wird er daherkommen mit großer Streitmacht und mit vieler Habe.',
        14: 'Und in selbigen Zeiten werden viele wider den König von Mittag stehen, und auch die Söhne der Räuber deines Volkes sich erheben, so daß sie das Gesichte bestätigen, und werden straucheln.',
        15: 'Und wird kommen der König von Mitternacht und einen Wall aufschütten und die feste Stadt erobern, und die Arme des Mittags werden nicht bestehen, und sein auserwähltes Volk; und werden keine Kraft haben zum Widerstehen.',
        16: 'Und wer wider ihn kommt, tut nach seinem Wohlgefallen, und wird niemand vor ihm bestehen, und er wird stehen im Land der Zierde, und wird es vollenden durch seine Hand.',
        17: 'Und er wird sein Angesicht richten, daß er mit der Stärke seines ganzen Reiches komme, und wird das Gerade mit ihm tun, und ihm die Tochter der Weiber geben, daß sie ihn verderbe, aber sie wird nicht bestehen, und wird nicht für ihn sein.',
        18: 'Und er wird sein Angesicht zurückwenden wider die Inseln und viele erobern; aber ein Heerführer wird seinem Schmähen ein Ende machen, daß er ihm sein Schmähen zurückgebe.',
        19: 'Und er wird sein Angesicht zurückwenden zu den Festen seines Landes; und er wird straucheln und fallen, und nicht gefunden werden.',
        20: 'Und an seiner Stelle wird einer erstehen, der wird den Erpresser nach des Reiches Ehre umhersenden; aber in einigen Tagen wird er zerbrechen, doch nicht im Zorn und nicht im Streit.',
        21: 'Und an seiner Stelle steht ein Verachteter, und ihm geben sie die Majestät des Königtums nicht; und er kommt unversehens und erfaßt das Reich durch Schmeicheleien.',
        22: 'Und die Arme des Überflutenden werden vor ihm überflutet und zerbrochen werden, und auch der Fürst des Bundes.',
        23: 'Denn nachdem er sich mit ihm verbündet, wird er trüglich handeln und heraufziehen, und mit wenig Völkerschaft ihn besiegen.',
        24: 'Und wird unversehens in die fetten Plätze der Landschaft kommen und tun, was seine Väter und seiner Väter Väter nicht zu tun vermochten, mit Rauben, Beutemachen und dem Verstreuen der Habe unter sie, und wird seine Gedanken denken wider die Festungen und bis auf eine Zeit;',
        25: 'Und wird seine Kraft und sein Herz auferwecken wider den König vom Mittag mit großer Streitmacht. Und der König vom Mittag wird ihn befehden im Streit mit großer und sehr gewaltiger Streitmacht, wird aber nicht bestehen, denn sie werden Anschläge wider ihn ausdenken.',
        26: 'Und die seine leckere Speise essen, werden ihn zerbrechen, und seine Streitmacht wird er überfluten, und viele Erschlagene werden fallen.',
        27: 'Und die beiden, die Könige, ihr Herz wird darauf sein, Böses zu tun, und an einem Tische werden sie Falsches miteinander reden. Es wird ihnen aber nicht gelingen, denn das Ende ist erst zur bestimmten Zeit.',
        28: 'Und er wird zurückkehren in sein Land mit großer Habe und wird sein Herz setzen wider den Bund der Heiligkeit, und wird es tun und in sein Land zurückkehren.',
        29: 'Zur bestimmten Zeit wird er zurückkehren und gen Mittag kommen; aber es wird zuletzt nicht sein wie vormals.',
        30: 'Und es werden Schiffe aus Chitthim wider ihn kommen, und er wird sich betrüben und zurückkehren und unwillig sein wider den Bund der Heiligkeit, und wird es tun; und er wird zurückkehren und sich verständigen mit denen, die den Bund der Heiligkeit verlassen.',
        31: 'Und Arme von ihm werden stehen und das Heiligtum, die Feste, entweihen und das Beständige wegtun und das verwüstende Scheusal aufstellen.',
        32: 'Und er wird die, so ungerecht handeln wider den Bund, mit Schmeicheleien entheiligen; aber das Volk derer, so ihren Gott kennen, werden sich stärken und es tun.',
        33: 'Und die Verständigen des Volkes werden viele zur Einsicht bringen; aber sie werden straucheln ob dem Schwerte und ob der Flamme, ob der Gefangenschaft und dem Raube, einige Tage.',
        34: 'Und wenn sie straucheln, werden sie ihnen mit kleinem Beistande beistehen; aber viele werden ihnen anhangen mit Schmeicheleien.',
        35: 'Und von den Verständigen werden etliche straucheln, um unter ihnen abgetrieben, geläutert und weiß gemacht zu werden auf die Zeit des Endes: denn es ist noch auf die bestimmte Zeit.',
        36: 'Und der König wird tun nach seinem Wohlgefallen und sich erhöhen und groß tun wider jeglichen Gott, und wider den Gott der Götter Wunderliches reden, und wird ihm gelingen, bis vollendet ist der Unwille und die Entscheidung ist gemacht.',
        37: 'Und er wird nicht aufmerken auf die Götter seiner Väter, noch auf die Begierde der Frauen, noch aufmerken auf irgendeinen Gott, sondern groß tun wider alle.',
        38: 'Und er wird den Gott der Befestigungen an seiner Stelle verherrlichen, und den Gott, den seine Väter nicht gekannt, mit Gold und mit Silber, und mit kostbarem Steine und mit Kleinodien verherrlichen.',
        39: 'Und er arbeitet an den Festungen der Festen mit einem ausländischen Gotte. Wer ihn anerkennt, dem mehrt er die Herrlichkeit und läßt ihn herrschen über viele, und den Boden teilt er aus zum Lohne.',
        40: 'Und zur Zeit des Endes wird der König vom Mittag sich mit ihm stoßen, und der König von Mitternacht wird stürmen wider ihn mit Streitwagen und mit Reitern und mit vielen Schiffen, und wird in die Länder kommen und sie überfluten und durchziehen.',
        41: 'Und wird in das Land der Zierde kommen, und viele werden dahinstürzen, aber diese werden entrinnen seiner Hand: Edom und Moab und die Erstlinge der Söhne Ammons.',
        42: 'Und er wird seine Hand in die Länder ausstrecken, und das Land Ägypten wird ihm nicht entkommen.',
        43: 'Und er wird herrschen über die Schätze Goldes und Silbers und über alle Kleinodien Ägyptens, und Libyer und Kuschiten in seinen Schritten.',
        44: 'Und Gerüchte vom Aufgang und von Mitternacht machen ihn bestürzt, und mit großem Grimme zieht er aus, um viele zu vernichten und zu verbannen.',
        45: 'Und er wird seine Palastzelte aufschlagen zwischen den Meeren, an dem Berge der Zierde der Heiligkeit; und er kommt zu seinem Ende und niemand steht ihm bei.',
    },
    12: {
        1: 'Und zur selben Zeit wird dastehen der große Fürst Michael, der da steht für die Söhne deines Volkes, und wird sein eine Zeit der Drangsale, dergleichen nicht gewesen ist, seit Völkerschaften da sind bis auf selbige Zeit, und in jener Zeit wird dein Volk entrinnen, ein jeder, der in dem Buche sich geschrieben findet.',
        2: 'Und viele derer, die im Staub des Bodens schlafen, werden erwachen, etliche zum ewigen Leben und etliche zur Schmach und zu ewiger Abneigung.',
        3: 'Die Verständigen aber werden glänzen wie der Glanz der Himmelsfeste, und die, so viele gerecht gemacht, wie die Sterne in Ewigkeit und immerdar.',
        4: 'Du aber, Daniel, verschließe die Worte und versiegle das Buch bis zur Zeit des Endes; viele werden es dann durchlaufen und die Erkenntnis sich mehren.',
        5: 'Und ich, Daniel, sah, und siehe, zwei andere standen da, der eine auf diesem Ufer des Stromes und der andere auf jenem Ufer des Stromes.',
        6: 'Und er sprach zu dem Manne in Linnen gekleidet, der über den Wassern des Stromes war: Bis wann wird es ein Ende mit den Wundern?',
        7: 'Und ich hörte den Mann, der in Linnen gekleidet war, der über den Wassern des Stromes war, und er erhob seine Rechte und seine Linke zu den Himmeln, und schwur bei Dem, Der da lebt in Ewigkeit: daß es auf eine bestimmte Zeit, bestimmte Zeiten und eine halbe sein soll, und wenn die Zerstreuung der Hand des Volkes der Heiligkeit vollendet ist, wird alles dies vollendet werden.',
        8: 'Und ich hörte es und verstand es nicht, und sprach: Mein Herr, was wird das Letzte davon sein?',
        9: 'Und er sprach: Gehe hin, Daniel, denn die Worte sind verschlossen und versiegelt bis zur Zeit des Endes.',
        10: 'Viele werden sich säubern und weiß machen und läutern, und Ungerechte werden ungerecht handeln, und alle Ungerechten werden nicht aufmerken, aber die Verständigen werden aufmerken.',
        11: 'Und von der Zeit an, wenn das Beständige abgetan und das verwüstende Scheusal eingesetzt wird, sind es tausendzweihundertneunzig Tage.',
        12: 'Selig, der da wartet und erreicht die tausenddreihundertfünfunddreißig Tage.',
        13: 'Und du, gehe zum Ende und ruhe, und stehe zu deinem Lose bis zum Ende der Tage.',
    },
}
