NAME = 'GerTafel: German Tafelbibel (1911)'
BOOK = 'James'

CHAPTERS = {
    1: {
        1: 'Jakobus, ein Knecht Gottes und des Herrn Jesu Christi, entbietet den zwölf Stämmen in der Zerstreuung seinen Gruß.',
        2: 'Achtet es, meine Brüder, für eitel Freude, wenn ihr in mancherlei Anfechtungen fallet,',
        3: 'Und wisset, daß die Prüfung eures Glaubens Standhaftigkeit bewirkt.',
        4: 'Standhaftigkeit aber soll ihr Werk vollkommen machen, auf daß ihr seid vollkommen und vollendet, und es an nichts fehlen lasset.',
        5: 'So aber einem unter euch an Weisheit gebricht, so bitte er Gott darum, Der da einfältig jedem gibt und keinem es aufrückt, so wird sie ihm gegeben werden.',
        6: 'Er bitte aber im Glauben und zweifle nicht; denn der, so da zweifelt, gleicht der Meereswoge, die, vom Winde ergriffen, hinund hergeworfen wird.',
        7: 'Ein solcher Mensch wähne ja nicht, daß er etwas vom Herrn empfangen werde.',
        8: 'Ein wankelmütiger Mensch ist unbeständig auf allen seinen Wegen.',
        9: 'Der niedrige Bruder aber rühme sich seiner Hoheit,',
        10: 'Und der Reiche rühme sich seiner Niedrigkeit; denn wie die Blume des Grases wird er vergehen.',
        11: 'Die Sonne geht auf mit ihrer Glut und dörrt das Gras, und seine Blume fällt ab, und mit ihrer Pracht ist es zu Ende; also vergeht auch der Reiche mitten in seinem Treiben.',
        12: 'Glücklich ist der Mann, der in der Versuchung aushält; denn wenn er sich bewährt, empfängt er den Siegeskranz des Lebens, den der Herr denen, die Ihn lieben, verheißen hat.',
        13: 'Niemand sage, wenn er versucht wird, daß er von Gott versucht werde; denn Gott wird nicht versucht vom Bösen, und versucht auch Selber niemand.',
        14: 'Sondern ein jeglicher wird versucht, wenn er von seiner eigenen Lust fortgerissen und verlockt wird.',
        15: 'Danach, wenn die Lust empfangen hat, gebiert sie die Sünde, die Sünde aber, wenn sie vollendet ist, gebiert den Tod.',
        16: 'Irrt euch nicht, geliebte Brüder!',
        17: 'Alle gute Gabe und alle vollkommene Gabe kommt von oben herab vom Vater der Lichter, bei Dem ist keine Wandlung, noch wechselnde Beschattung.',
        18: 'Aus freiem Ratschluß hat Er uns durch das Wort der Wahrheit geboren, auf daß wir wären Erstlinge Seiner Geschöpfe.',
        19: 'Darum, geliebte Brüder, sei jeder Mensch schnell zum Hören, langsam aber zum Reden, langsam zum Zorn.',
        20: 'Denn des Menschen Zorn tut nicht, was vor Gott recht ist.',
        21: 'Darum legt ab alle Unsauberkeit und allen Auswuchs der Bosheit, und nehmt in Sanftmut auf die euch eingepflanzte Lehre, die eure Seelen retten kann.',
        22: 'Seid aber Täter des Wortes und nicht Hörer allein, womit ihr euch selbst betrügt.',
        23: 'Denn so jemand das Wort hört und nicht tut, gleicht er einem Manne, der sein leiblich Angesicht im Spiegel beschaut.',
        24: 'Denn nachdem er sich beschaut hat, geht er davon, und vergißt alsbald, wie er aussah.',
        25: 'Wer aber in das vollkommene Gesetz der Freiheit hineingeschaut und dabei beharrt hat, und kein vergeßlicher Hörer, sondern ein wirklicher Täter geworden ist, der wird selig durch sein Tun.',
        26: 'So aber einer sich dünkt gottesfürchtig zu sein und hält seine Zunge nicht im Zaum, sondern täuscht sich über sein Herz, dessen Gottesfurcht ist eitel.',
        27: 'Eine reine und unbefleckte Gottesfurcht ist vor Gott dem Vater die, daß man die Waisen und Witwen in ihrer Trübsal heimsucht, und sich unbefleckt von der Welt erhält.',
    },
    2: {
        1: 'Meine Brüder, haltet nicht dafür, daß der Glaube an Jesus Christus, unseren Herrn der Herrlichkeit, Ansehen der Person leide.',
        2: 'Denn so in eure Versammlung ein Mann käme mit goldenem Ring und in prächtigem Kleide, es käme aber auch ein Armer in schlechtem Kleide;',
        3: 'Und ihr sähet auf den, der das prächtige Kleid trägt, und sagtet zu ihm: Mache es dir hier bequem; und sagtet zu dem Armen: Stehe dort hin oder setze dich hier vor meinen Fußschemel;',
        4: 'Machtet ihr da keinen Unterschied bei euch, und würdet Richter argen Sinnes?',
        5: 'Hört, meine geliebten Brüder! Hat Gott nicht die Armen dieser Welt auserwählt, als reich an Glauben und Erben des Reiches, das Er denen, so Ihn lieben, verheißen hat?',
        6: 'Ihr aber hättet dem Armen Unehre angetan. Sind es nicht die Reichen, die euch drükken mit ihrer Gewalt und euch vor die Gerichte ziehen?',
        7: 'Lästern sie nicht den guten Namen, wonach ihr genannt seid?',
        8: 'So ihr vollbringt das königliche Gesetz nach der Schrift: Liebe deinen Nächsten wie dich selbst, so tut ihr wohl.',
        9: 'So ihr aber die Person anseht, begeht ihr eine Sünde und werdet vor dem Gesetz als Übertreter gestraft.',
        10: 'Denn so einer das ganze Gesetz hält, und verstößt an einem, verschuldet er sich an allen.',
        11: 'Denn Der da gesagt hat: Du sollst nicht ehebrechen, hat auch gesagt: Du sollst nicht töten. So du nun nicht ehebrichst, tötest aber, bist du ein Übertreter des Gesetzes.',
        12: 'Also redet und also tut, als die da sollen nach dem Gesetz der Freiheit gerichtet werden.',
        13: 'Denn ein unbarmherzig Gericht ergeht über den, der nicht Barmherzigkeit geübt hat, und Barmherzigkeit rühmt sich wider das Gericht.',
        14: 'Denn was hilft es einem, meine Brüder, so er sagt, er habe Glauben, und hat doch keine Werke; kann der Glaube ihn selig machen?',
        15: 'So aber ein Bruder oder eine Schwester nackt und bloß wäre und an der täglichen Nahrung Mangel litte;',
        16: 'Und einer unter euch zu ihnen spräche: Geht hin im Frieden, wärmt euch und sättigt euch, ihr gäbet ihm aber nicht, was des Leibes Notdurft wäre, was hülfe das?',
        17: 'So ist auch der Glaube, wenn er nicht Werke hat, an und für sich tot.',
        18: 'Aber es sagt vielleicht einer: Du hast den Glauben, und ich habe die Werke - zeige mir deinen Glauben an deinen Werken, so will auch ich dir an meinen Werken meinen Glauben zeigen.',
        19: 'Du glaubst, daß nur ein Gott ist. Du tust wohl daran; die Teufel glauben es auch und zittern.',
        20: 'Willst du aber wissen, du eitler Mensch, daß der Glaube ohne Werke tot ist?',
        21: 'Ist nicht Abraham, unser Vater, durch Werke gerecht geworden, weil er seinen Sohn Isaak auf den Opferaltar dargebracht hat?',
        22: 'Da siehst du, daß der Glaube mit seinen Werken mitwirkte und durch die Werke der Glaube vollkommen ward.',
        23: 'Und so ist die Schrift erfüllt worden, die da sagt: Abraham hat Gott geglaubt, und es ward ihm zur Gerechtigkeit gerechnet, und er ward ein Freund Gottes genannt.',
        24: 'So seht ihr nun, daß der Mensch durch Werke gerecht wird, und nicht durch den Glauben allein.',
        25: 'Gleicherweise die Hure Rahab, ist sie nicht durch die Werke gerecht geworden, weil sie die Boten aufnahm und auf einem anderen Wege wieder entkommen ließ?',
        26: 'Denn gleichwie der Leib ohne den Geist tot ist, also ist auch der Glaube tot ohne die Werke.',
    },
    3: {
        1: 'Es sollten nicht so viele Lehrer sein wollen; ihr wißt ja, daß die Verantwortung um so größer für euch ist.',
        2: 'Denn wir fehlen alle mannigfaltig. Wer aber auch in keinem Worte fehlt, der ist ein vollkommener Mann und ist imstande, auch den ganzen Leib im Zaum zu halten.',
        3: 'Siehe, den Pferden legen wir den Zaum ins Maul, daß sie uns gehorchen, und wir lenken ihren ganzen Leib.',
        4: 'Siehe, die Schiffe, obwohl sie so groß sind und von heftigen Winden umhergetrieben werden, werden doch von dem so kleinen Ruder gelenkt, wohin der Steuermann will.',
        5: 'So ist auch die Zunge ein kleines Glied und richtet Großes an. Siehe, welch einen Wald ein kleines Feuer anzündet!',
        6: 'Auch die Zunge ist ein Feuer, eine Welt der Ungerechtigkeit; sie stellt sich so zu unseren Gliedern, daß sie den ganzen Leib befleckt und von der Geburt an das Lebensrad entzündet und selbst von der Hölle entzündet wird.',
        7: 'Denn jegliches Geschlecht der Tiere, der Vögel, der Kriechtiere und der Seetiere wird gezähmt und ist gezähmt von dem menschlichen Geschlecht.',
        8: 'Die Zunge aber vermag kein Mensch zu zähmen, dies unwiderstehliche Übel voll tödlichen Giftes!',
        9: 'Mit ihr loben wir Gott, den Vater, und mit ihr fluchen wir den Menschen, die nach dem Bilde Gottes geschaffen sind.',
        10: 'Aus einem Munde geht hervor Segen und Fluch. So sollte es nicht sein, meine Brüder.',
        11: 'Quillt wohl die Quelle aus derselben Öffnung Süßes und Bitteres hervor?',
        12: 'Kann wohl, liebe Brüder, ein Feigenbaum Oliven, oder ein Weinstock Feigen tragen? So kann auch eine Quelle nicht salziges und süßes Wasser geben.',
        13: 'Wer ist weise und verständig unter euch? der zeige mit seinem guten Lebenswandel seine Werke in der Sanftmut der Weisheit.',
        14: 'Habt ihr aber bitteren Eifer und Streitsucht in eurem Herzen, so lasset das Rühmen und lügt nicht wider die Wahrheit.',
        15: 'Das ist keine Weisheit, die von oben kommt, sondern eine irdische, natürliche, teuflische.',
        16: 'Denn wo Neid und Streitsucht ist, da ist Unordnung und eitel böses Ding.',
        17: 'Die Weisheit aber, die von oben kommt, ist vor allem rein, sodann friedfertig, sanft, nachgiebig, lenksam, voll Erbarmens und guter Früchte, macht keinen Unterschied und ist ungeheuchelt.',
        18: 'Die Frucht der Gerechtigkeit aber wird gesät in Frieden von denen, die Frieden halten.',
    },
    4: {
        1: 'Woher kommen Streitereien und Kämpfe unter euch? Woher anders als aus euren Lüsten, die da streiten in euren Gliedern wider einander?',
        2: 'Ihr begehrt und könnt es nicht gewinnen, ihr neidet und eifert und könnt es nicht erlangen, ihr kämpft und streitet und habt es nicht, darum, daß ihr nicht bittet.',
        3: 'Ihr bittet und empfangt nicht, weil ihr für euch übel bittet, auf daß ihr es in euren Lüsten vergeuden könnt.',
        4: 'Ihr Ehebrecher und Ehebrecherinnen, wißt ihr nicht, daß der Welt Freundschaft Gottes Feinschaft ist; wer nun der Welt Freund sein will, der wird Gottes Feind.',
        5: 'Oder meint ihr, daß die Schrift umsonst spreche! Eifernd begehrt sie des Geistes, den Er in uns wohnen ließ.',
        6: 'Er gibt aber größere Gnade; darum heißt es: Gott widersteht den Hoffärtigen, aber den Demütigen gibt Er Gnade.',
        7: 'So seid denn Gott untertänig. Widersteht dem Teufel, so flieht er von euch.',
        8: 'Naht euch Gott, so naht Er Sich euch; reinigt die Hände, ihr Sünder, und haltet eure Herzen rein, ihr Wankelmütigen.',
        9: 'Fühlt euer Elend, trauert und weint. Euer Lachen wandle sich in Klage und eure Freude in Betrübnis.',
        10: 'Demütigt euch vor dem Herrn, so wird Er euch erhöhen!',
        11: 'Redet einander nicht Übles nach, Brüder. Wer seinem Bruder Übles nachredet und seinen Bruder richtet, der redet wider das Gesetz und richtet das Gesetz. Wenn du aber das Gesetz richtest, so bist du kein Täter des Gesetzes, sondern Richter.',
        12: 'Es ist nur ein Gesetzgeber, Der lossprechen und verdammen kann. Wer bist du aber, der du den anderen richtest?',
        13: 'Wohlan nun ihr, die ihr sagt: Heute oder morgen wollen wir in die oder die Stadt gehen, wollen daselbst ein Jahr hantieren und gewinnen.',
        14: 'Und ihr wißt doch nicht, wie es morgen steht; denn was ist euer Leben? Ein Dunst ist es, der eine kleine Weile erscheint und dann vergeht.',
        15: 'Ihr solltet vielmehr sagen: So der Herr will und wir am Leben bleiben, wollen wir dies oder das tun.',
        16: 'Nun aber rühmt ihr euch in eurem Übermut. All solches Rühmen aber ist vom Übel.',
        17: 'Wer da weiß Gutes zu tun und tut es nicht, dem ist es Sünde.',
    },
    5: {
        1: 'Wohlan denn ihr Reichen, weint und heult über euer Elend, das über euch kommen wird.',
        2: 'Euer Reichtum verschwindet, eure Gewänder werden von Motten zerfressen.',
        3: 'Euer Gold und Silber ist verrostet, und ihr Rost wird euch zum Zeugnis sein und wird euer Fleisch fressen wie ein Feuer. Ihr habt in den letzten Tagen Schätze gehäuft.',
        4: 'Siehe, der Lohn der Arbeiter, die für euch eure Lande abgemäht, und den ihr verkürzt habt, schreit, und das Schreien der Schnitter ist vor die Ohren des Herrn Zebaoth gekommen.',
        5: 'Ihr ließet euch wohlsein auf Erden und habt geschwelgt, habt euch weidlich gemästet wie am Tag des Schlachtopfers.',
        6: 'Ihr habt den Gerechten verurteilt, gemordet; er widersteht euch nicht.',
        7: 'So haltet denn geduldig aus, liebe Brüder, bis zur Zukunft des Herrn. Siehe, der A-ckersmann wartet auf die köstliche Frucht des Feldes und geduldet sich, bis er Frühregen und Spätregen empfängt.',
        8: 'So geduldet denn auch ihr euch, und festigt eure Herzen; denn die Zukunft des Herrn ist nahe.',
        9: 'Klagt nicht über einander, Brüder, auf daß ihr nicht verdammt werdet; siehe, der Richter steht vor der Tür.',
        10: 'Nehmt euch zum Muster im Leiden und in der Geduld die Propheten, die im Namen des Herrn zu euch geredet haben.',
        11: 'Siehe, wir preisen selig die, so ausharren; von der Standhaftigkeit Hiobs habt ihr gehört, und das Ende des Herrn habt ihr gesehen; denn der Herr ist von großer Gnade und Barmherzigkeit.',
        12: 'Vor allen Dingen aber, meine Brüder, schwört nicht, weder bei dem Himmel, noch bei der Erde, noch einen anderen Schwur. Bei euch aber sei ja: ja, nein: nein, auf daß ihr nicht dem Gericht verfallet.',
        13: 'Leidet jemand unter euch, der bete, ist er wohlgemut, so singe er Psalmen.',
        14: 'Ist jemand krank unter euch, so rufe er zu sich die Ältesten der Gemeinde, und die sollen beten über ihn und ihn salben mit Öl im Namen des Herrn.',
        15: 'Und das Gebet des Glaubens wird dem Kranken helfen und der Herr wird ihn aufrichten, und so er Sünden begangen hat, wird ihm vergeben werden.',
        16: 'Bekennt einander eure Übertretungen und betet füreinander, daß euch Heil widerfahre; das Gebet des Gerechten vermag viel, wenn es ernstlich ist.',
        17: 'Elias war ein Mensch gleich wie wir, und betete ein Gebet, daß es nicht regnen sollte, und es regnete nicht im Lande drei Jahre und sechs Monate.',
        18: 'Und er betete abermals, und der Himmel gab Regen und die Erde brachte ihre Frucht.',
        19: 'Brüder, so einer unter euch von der Wahrheit abirrete, und es brächte ihn jemand zurück,',
        20: 'Der wisse, daß, wer einen Sünder von seinem Irrweg zurückbringt, eine Seele vom Tod errettet und damit eine Menge Sünden bedeckt.',
    },
}
