NAME = 'GerTafel: German Tafelbibel (1911)'
BOOK = 'Jonah'

CHAPTERS = {
    1: {
        1: 'Und es geschah das Wort Jehovahs an Jonah, den Sohn Amitthais, sprechend:',
        2: 'Stehe auf und gehe nach Niniveh, der großen Stadt, und predige wider sie; denn ihre Bosheit ist vor Mich heraufgestiegen.',
        3: 'Und Jonah stand auf, um von dem Angesichte Jehovahs nach Tharschisch zu entweichen; und er ging hinab gen Japho und fand ein Schiff, das nach Tharschisch fuhr, und gab sein Fährgeld und stieg hinab in dasselbe, um mit ihnen nach Tharschisch zu kommen, hinweg vom Angesicht Jehovahs.',
        4: 'Und Jehovah ließ einen großen Wind auf das Meer kommen, und es ward ein großes Wetter auf dem Meere, und das Schiff wollte zerbrechen.',
        5: 'Und die Seeleute fürchteten sich und schrien jeder Mann zu seinem Gott, und warfen die Geräte, die im Schiff waren, in das Meer, daß sie sich leichter machten; Jonah war aber in das Hinterteil des Fahrzeuges hinabgestiegen, und lag da in tiefem Schlaf.',
        6: 'Und es nahte sich ihm der Hauptsteuermann und sprach zu ihm: Was ist dir? Was liegst du im tiefen Schlaf? Stehe auf, rufe zu deinem Gott, vielleicht daß Er es Sich über uns bedenke und wir nicht verloren seien.',
        7: 'Und sie sprachen, der Mann zu seinen Genossen: Kommt, laßt uns Lose werden, daß wir wissen, ob wem uns solch Übel geschieht. Und sie warfen Lose, und das Los fiel auf Jonah.',
        8: 'Und sie sagten zu ihm: Sage uns doch an, um wessen willen uns dieses Übel widerfährt? Was ist dein Geschäft, und von wannen kommst du? Was ist dein Land, und von welchem Volke bist du?',
        9: 'Und er sagte zu ihnen: Ich bin ein Hebräer und fürchte Jehovah, den Gott der Himmel, Der das Meer und das Trockene gemacht hat.',
        10: 'Und die Männer fürchteten sich mit großer Furcht und sagten zu ihm: Warum hast du dies getan? denn die Leute wußten, daß er vor dem Angesichte Jehovahs entwich; denn er hatte es ihnen angesagt.',
        11: 'Und sie sagten zu ihm: Was sollen wir dir tun, auf daß das Meer vor uns zur Ruhe komme? Denn das Meer ward immer stürmischer.',
        12: 'Und er sagte zu ihnen: hebt mich auf und werft mich ins Meer, auf daß das Meer vor euch zur Ruhe komme; denn ich weiß, daß meinetwegen dieses große Wetter über euch ist.',
        13: 'Und die Männer ruderten, daß sie wieder zum trockenen Land zurückkämen und vermochten es nicht; denn das Meer ward immer stürmischer über ihnen.',
        14: 'Und sie riefen Jehovah an und sprachen: Laß uns doch, o Jehovah, nicht verlorengehen ob der Seele dieses Mannes und lege nicht unschuldig Blut auf uns. Denn Du bist Jehovah, wie Du Lust hattest, hast Du getan.',
        15: 'Und sie hoben den Jonah auf und warfen ihn ins Meer; und das Meer stand still von seinem Grollen.',
        16: 'Und die Männer fürchteten Jehovah mit großer Furcht, und sie opferten dem Jehovah Schlachtopfer, und gelobten Gelübde.',
    },
    2: {
        1: 'Und Jehovah verschaffte einen großen Fisch, den Jonah zu verschlingen. Und Jonah war im Leib des Fisches drei Tage und drei Nächte.',
        2: 'Und Jonah betete zu Jehovah, seinem Gotte, aus dem Leib des Fisches,',
        3: 'Und sprach: Ich rief aus meiner Drangsal zu Jehovah, und Er antwortete mir; aus dem Bauche der Hölle habe ich aufgeschrien, Du hörtest meine Stimme.',
        4: 'Und Du warfst mich in den Schlund, in das Herz der Meere, und eine Strömung umgab mich, all Deine Brandungen und deine Wogen gingen über mich hin.',
        5: 'Und ich sprach: Ich bin aus Deinen Augen vertrieben, doch werde ich wiederum den Tempel Deiner Heiligkeit erblicken.',
        6: 'Die Wasser umfingen mich bis an die Seele, mich umgab der Abgrund, Schilf war mir um mein Haupt umgebunden.',
        7: 'Ich sank hinunter zu der Berge Gründe, die Erde - ihre Riegel waren um mich ewiglich. Du aber hast mein Leben aus der Grube heraufgebracht, Jehovah, mein Gott.',
        8: 'Da meine Seele verzagte ob mir, gedachte ich an Jehovah, und mein Gebet kam zu Dir zum Tempel Deiner Heiligkeit.',
        9: 'Die zu der Eitelkeit Nichtigem halten, verlassen ihre Barmherzigkeit.',
        10: 'Ich aber will Dir mit der Stimme des Bekenntnisses opfern. Was ich gelobt habe, will ich entrichten. Das Heil ist bei Jehovah. Und Jehovah sprach zu dem Fisch, und er spie den Jonah aus an das Trockene.',
    },
    3: {
        1: 'Und das Wort Jehovahs geschah an Jonah zum zweitenmal, sprechend:',
        2: 'Stehe auf, gehe nach Niniveh, der großen Stadt und predige die Predigt, die Ich zu dir rede.',
        3: 'Und Jonah stand auf und ging nach Niniveh, nach dem Worte Jehovahs; und Niniveh war eine große Stadt vor Gott, eine Reise von drei Tagen.',
        4: 'Und Jonah fing an, in die Stadt hineinzugehen, eine Reise von einem Tag, und rief und sprach: Noch vierzig Tage, und Niniveh wird umgekehrt.',
        5: 'Und die Männer Ninivehs glaubten an Gott und riefen ein Fasten aus, und kleideten sich in Säcke vom Großen bis zum Kleinen derselben.',
        6: 'Und als das Wort den König Ninivehs erreichte, da stand er auf von seinem Throne und legte seinen Mantel von sich ab, und deckte sich mit einem Sack und saß in Asche.',
        7: 'Und ließ ausschreien und sagen in Niniveh auf Weisung des Königs und seiner Großen und sprechen: Mensch und Vieh, Rind und Kleinvieh sollen nichts schmecken, nicht weiden und kein Wasser trinken.',
        8: 'Und es sollen sich bedecken mit Säcken Mensch und Vieh, und sollen zu Gott rufen kräftiglich und zurückkehren jeder Mann von seinem bösen Weg, und von der Gewalttat, die an ihren Händen ist.',
        9: 'Wer weiß, ob Gott nicht zurückkehrt und es bereut und zurückkehrt von der Entbrennung Seines Zornes, daß wir nicht vergehen.',
        10: 'Und Gott sah ihr Tun, daß sie von ihrem bösen Weg zurückkehrten; und es reute Gott des Bösen, das Er geredet hatte ihnen zu tun, und tat es nicht.',
    },
    4: {
        1: 'Und es war sehr böse vor Jonah, und er entbrannte.',
        2: 'Und er betete zu Jehovah und sprach: Ach Jehovah, war nicht das mein Wort, da ich noch auf meinem Boden war, darum ich wollte zuvorkommen und nach Tharschisch entweichen? Denn ich wußte ja, daß Du ein gnädiger und erbarmungsvoller Gott, langmütig und von großer Barmherzigkeit bist, und Dich des Bösen gereuen läßt.',
        3: 'Und nun, Jehovah, nimm doch meine Seele von mir! Besser ist, ich sterbe, denn daß ich lebe.',
        4: 'Und Jehovah sprach: Ist es gut, daß du entbrennst?',
        5: 'Und Jonah ging hinaus aus der Stadt, und setzte sich gegen Osten von der Stadt, und machte sich allda eine Hütte, und setzte sich darunter in den Schatten, bis daß er sähe, was mit der Stadt würde werden.',
        6: 'Und Jehovah Gott verschaffte einen Wunderbaum, und er stieg auf über Jonah, so daß über seinem Haupte Schatten wäre, so daß er ihn von seinem Bösen errettete; und Jonah ward froh über den Wunderbaum mit großer Fröhlichkeit.',
        7: 'Und Gott verschaffte einen Wurm, als das Morgenrot aufstieg am morgenden Tag, und er stach den Wunderbaum, daß er verdorrte.',
        8: 'Und als die Sonne aufging, geschah, daß Gott einen versengenden Ostwind verschaffte, und die Sonne stach Jonah auf den Kopf, daß er dahinschmachtete; und er erbat seiner Seele, daß er stürbe, und sprach: Besser ist mir, daß ich sterbe, denn daß ich lebe.',
        9: 'Und Gott sprach zu Jonah: Tust du wohl, daß du bei dir entbrennst über den Wunderbaum? Und er sprach: Ich tue wohl, daß ich entbrenne bis zum Tod.',
        10: 'Und Jehovah sprach: Du würdest schonen den Wunderbaum, mit dem du keine Mühe hattest, und den du nicht großgezogen hattest, der in einer Nacht ward und in einer Nacht verging.',
        11: 'Und Ich sollte nicht schonen Niniveh, die große Stadt, in der sind mehr den zwölf Myriaden von Menschen, die nicht wissen den Unterschied zwischen ihrer Rechten und ihrer Linken, und viel Vieh?',
    },
}
