NAME = 'GerGruenewald: 1924 Grünewaldbibel'
BOOK = 'Amos'

CHAPTERS = {
    1: {
        1: 'Die Worte des Amos, der zu Tekoas Viehzüchter gehörte und Gesichte sah zur Zeit des Judakönigs Ozias, sowie zur Zeit des Israelkönigs Jeroboam,',
        2: 'des Joassohns, zwei Jahre vor dem Erdbeben, und der zu sagen pflegte. "Aus Sion brüllt der Herr, und seine Stimme läßt er aus Jerusalem erschallen. Dann stehn der Hirten Anger traurig, und Karmels Gipfel ist beschämt."',
        3: 'So spricht der Herr: "Des Frevels von Damaskus wegen, des drei- und vierfach schändlichen, nehm\' ich es nicht zurück. Sie zogen über Gilead Eisenwalzen.',
        4: "Nun sende ich ein Feuer in das Haus des Asael, und fressen soll's die Schlösser Benhadads.",
        5: 'Die Riegel von Damaskus will ich jetzt zerbrechen. Vertilgen will ich die Bewohner aus dem Sündental, den Zepterträger aus dem Haus der Lust, und wandern soll nach Kir der Aramäer Volk." So spricht der Herr.',
        6: 'So spricht der Herr: "Des Frevels Gazas wegen, des drei- und vierfach schändlichen, nehm\' ich es nicht zurück. Sie haben weggeschleppt in voller Zahl Gefangene und sie an Edom ausgeliefert.',
        7: 'Ich schleudre Feuer in die Mauern Gazas, und fressen soll es seine Burgen.',
        8: 'Aus Asdod tilg ich die Bewohner, aus Askalon, wer dort das Zepter führt, und gegen Akkaron erheb ich wieder meine Hand, und untergehen soll, was von Philistern übrig ist." So spricht der Herr, der Herr.',
        9: 'So spricht der Herr: "Um seines Frevels willen, des drei- und vierfach schändlichen, daß Tyrus das Grenzland Salomos an Syrien ausgeliefert, nehm\' ich es nicht zurück, des Bruderbundes nimmer eingedenk.',
        10: 'Ich sende Feuer gen die Mauern von Tyrus, fressen soll es seine Burgen."',
        11: 'So spricht der Herr, "Des Frevels Edoms wegen, des drei- und vierfach schändlichen, nehm\' ich es nicht zurück, daß dies den Bruder mit dem Schwert verfolgt, sein Mitgefühl erstickt und seinen Zorn für immer festgehalten und ewig hat genährt des Hasses Glut.',
        12: 'Ich sende Feuer wider Teman, es fresse Bosras Burgen."',
        13: 'So spricht der Herr: "Des Frevels Ammons wegen, des drei- und vierfach schändlichen, nehm\' ich es nicht zurück, daß sie das Bergland Gileads eroberten, um ihre Grenzen zu erweitern,',
        14: 'ich sende Feuer gegen Rabatts Mauern, und fressen soll es seine Burgen am Kampftag unter Kriegsgeschrei, im Wettersturm am Tag des Ungewitters.',
        15: 'Fort muß ihr König in Gefangenschaft mit seinen Fürsten insgesamt." So spricht der Herr.',
    },
    2: {
        1: 'So spricht der Herr: "Des Frevels Moabs wegen, des drei- und vierfach schändlichen, nehm\' ich es nicht zurück, daß die Gebeine eines Edomiterkönigs es zu Tüncherkalk verbrannt.',
        2: "Ich sende Feuer wider Moab, und fressen soll's die Burgen Kerijots. Und Moab stirbt im Schlachtgetümmel, bei Kriegsgeschrei und bei Trompetenschall.",
        3: 'Ich tilge ihm den Herrscher aus der Mitte und würge mit ihm alle seine Fürsten." So spricht der Herr. -',
        4: 'So spricht der Herr. "Des Frevels Judas wegen, des drei- und vierfach schändlichen, nehm\' ich es nicht zurück, daß es des Herrn Gesetz verwirft und seine Satzungen nicht hält. Nur ihre Lügen haben sie verführt, die gleichen, denen ihre Väter schon gefolgt.',
        5: 'So sende ich ein Feuer wider Juda, und fressen soll\'s die Burgen von Jerusalem."',
        6: 'So spricht der Herr: "Israels Frevels wegen, des drei- und vierfach schändlichen, nehm\' ich es nicht zurück, daß sie Unschuldige um Geld verkaufen und Arme um ein Paar Sandalen.',
        7: 'Sie, die um Staubes willen nach der Armen Kopfgeld gieren und Dürftiger Steuern höher schrauben, und dabei geht der Mann mit seinem Vater zu üppigem Mahl, um meinen heiligen Namen zu entweihen.',
        8: 'Auf Decken buntgewirkt, so liegen sie zur Seite eines jeglichen Altars und zechen Bier in ihres Gottes Haus.',
        9: 'Und doch vertilgte ich vor ihnen einst den Amoriter, hochgewachsen wie die Zedern, stark wie Eichen. Ich tilgte oben seine Frucht und unten seine Wurzeln.',
        10: 'Ich war es, der euch aus Ägypterland geführt und euch versorgte vierzig Jahre in der Wüste, daß ihr das Amoriterland erobern konntet.',
        11: 'Propheten habe ich für mich erweckt aus euren Söhnen und Nasiräer mir aus euren Jünglingen. Ist dem nicht so, ihr Söhne Israels?" Ein Spruch des Herrn.',
        12: '"Ihr aber gebt den Nasiräern Wein zu trinken, gebietet den Propheten: \'Nimmer dürft ihr prophezeien!\'',
        13: 'Fürwahr so will ich euch zermalmen auf dem Boden, wie volle Garben ein Dreschwagen zermalmt.',
        14: 'Die Flucht vergeht alsdann dem Schnellen. Nicht fühlt der Starke Kraft in sich; der Krieger weiß sich nicht zu retten.',
        15: 'Und selbst der Bogenschütze tritt nicht an; nicht rettet sich der schnelle Läufer, und auch der Reitersmann vermag sein Leben nicht zu retten.',
        16: 'An jenem Tag flieht nackt der Mutigste der Krieger." Ein Spruch des Herrn.',
    },
    3: {
        1: 'Vernehmet diesen Ausspruch, den wider euch der Herr getan, ihr Söhne Israels, und wider alle die Geschlechter, die ich aus dem Ägypterland geführt!',
        2: 'Er lautet so: "Ich lernte euch von allen den Geschlechtern der Erde kennen. Drum strafe ich an euch all eure Missetaten."',
        3: 'Begeben zwei sich zueinander, wenn sie sich nicht zum voraus schon bestellt?',
        4: 'Brüllt denn im Wald der Löwe, eh er seine Beute hat? Läßt denn ein junger Leu aus seinem Lager seine Stimme tönen, bevor er einen Fang gemacht?',
        5: 'Fällt auf den festen Boden wohl ein Vogel, wenn nicht ein Wurfholz für ihn dagewesen? Springt denn vom Boden eine Falle auf, bevor sie wirklich einen Fang gemacht?',
        6: 'Wird die Trompete in der Stadt geblasen, ohne daß die Leute recht erschrecken? Trifft eine Stadt ein Ungemach, das nicht der Herr veranlaßt hat?',
        7: 'Nichts tut der Herr, der Herr, er habe denn zuvor schon sein Geheimnis seinen Dienern, den Propheten, offenbart.',
        8: 'Ein Löwe brüllt. Wer hätte keine Angst? Der Herr, der Herr spricht. Wer prophezeite nicht?',
        9: 'Vermeldet in den Schlössern von Assyrien, in des Ägypterlandes Schlössern und verkündet: Versammelt euch jetzt auf Samarias Bergen und seht das tolle Treiben an in einer Mitte und die Bedrückungen in seinem Innern!',
        10: 'Ja, recht zu tun, verstehn sie nicht", ein Spruch des Herrn, "sie, die in ihren Schlössern Freveltaten häufen und Gewalttat.',
        11: 'Darum", so spricht der Herr, der Herr, "bedrängt ein Feind dies Land. Mit deinem Glanze geht\'s zu Ende jetzt, und deine Schlösser werden ausgeplündert."',
        12: 'So spricht der Herr: "Wie aus des Löwen Rachen ein Paar Beine ein Hirte rettet oder bloß ein Ohrläppchen, so werden auch die Söhne Israels sich retten, die in Samaria wohnen, mit einem Bettgestell und einem Damaszener Deckchen.',
        13: 'Hört! Zeuget wider Jakobs Haus!" Ein Spruch des Herrn, des Herrn, des Gottes der Heerscharen.',
        14: '"Wenn ich die Frevel Israels an ihm bestrafe, dann nehme ich an den Altären Betels Rache, daß des Altares Hörner, abgehauen, zu Boden fallen.',
        15: 'Das Winterhaus zerschlage ich mitsamt dem Sommerhaus, und die mit Elfenbein geschmückten Häuser werden ihrem Untergang verfallen. Große Häuser schwinden gänzlich hin." Ein Spruch des Herrn.',
    },
    4: {
        1: 'Ihr Basanskühe, hört dies Wort, die ihr verweilt auf Samarias Berg, die ihr die Niedrigen bedrücken und die Armen schinden helft, die ihr zu euren Herren sprecht: "Nur immer her, damit wir trinken können!"',
        2: 'Geschworen hat der Herr, der Herr, bei seiner Heiligkeit: "Fürwahr, es kommen Tage über euch, da treibt man euch mit Haken fort, was von euch übrigbleibt mit Stacheln.',
        3: 'Da schleppt man euch hinaus mit Ungestüm, die eine nach der anderen, und wirft euch in den Fluß." Ein Spruch des Herrn.',
        4: '"Nach Betel zieht und sündigt! Nach Gilgal, sündigt dort noch mehr! Bringt morgens eure Opfer dar, am dritten Tage eure Zehnten!',
        5: 'Dankopfer bringt von dem Gesäuerten! Ruft auf zu freiwilligen Opfern! Ihr tut es ja so gern, ihr Söhne Israels." Ein Spruch des Herrn, des Herrn. -',
        6: '"Schon machte ich an allen euren Städten eure Zähne blank und ließ an allen euren Plätzen an Brot es mangeln, und dennoch kamt ihr nicht zu mir zurück." Ein Spruch des Herrn.',
        7: '"Und ich versagte euch den Regen drei Monde vor der Ernte. Ich ließ auf eine Stadt zwar regnen, doch auf die andre nicht. So ward die eine Gegend zwar beregnet; jedoch die andere, auf die kein Regen fiel, verdorrte.',
        8: 'So taumelten die Städte zwei und drei zu einer Stadt, um Wasser dort zu trinken, und wurden nicht gesättigt, und ihr kamet dennoch nicht zu mir zurück." Ein Spruch des Herrn.',
        9: '"Ich schlug mit Kornbrand euch und Meltau, auf schwere Weise eure Gärten, eure Weinberge. Die Heuschrecke fraß Feigen- und Olivenbäume ab, und dennoch kamt ihr nicht zu mir zurtick." Ein Spruch des Herrn.',
        10: '"Ich sandte eine Pest zu euch nach Art und Weise der ägyptischen, schlug mit dem Schwerte eure Jünglinge samt euren besten Pferden. Gestank ließ ich von eurem Lager aus euch in die Nase dringen, und dennoch kamt ihr nicht zu mir zurück." Ein Spruch des Herrn.',
        11: '"Und einen Umsturz bracht\' ich über euch, wie Gott einst Sodom und Gomorrha umgestürzt; ihr gleichet einem Scheit, der Glut entrissen, und dennoch kamt ihr nicht zu nur zurück." Ein Spruch des Herrn.',
        12: '"Drum Israel, will ich mit dir nun so verfahren, und weil ich so mit dir verfahren will, so halte, Israel, dich auch bereit für die Begegnung deines Gottes!"',
        13: 'Ja, sieh! Er ist der Berge Bildner und des Windes Schöpfer. Er kann dem Menschen kundtun, was er selber im geheimen denkt. Er macht zum Morgenrot die Finsternis und wandelt auf der Erde Höhen. "Herr, Gott der Heerscharen", das ist sein Name.',
    },
    5: {
        1: 'Hört dieses Wort, das ich anhebe über euch, ein Trauerlied um das Haus Israel!',
        2: 'Es fällt die Jungfrau Israel, steht nicht mehr auf. Sie liegt auf ihrem eignen Boden hingestreckt, und keiner hilft ihr auf.',
        3: 'Denn also spricht der Herr, der Herr: "Die Stadt, die einst mit tausend ist ins Feld gezogen, behält nur hundert übrig, die hundert einst gestellt, wird zehn nur übrighaben im Hause Israel." -',
        4: 'So spricht der Herr vom Hause Israel: "Kommt, sucht mich auf, daß ihr am Leben bleibet!"',
        5: 'Besucht nicht Betel! Wallfahrt nicht nach Gilgal! Denn Gilgal schwindet; in nichts sinkt Betel."',
        6: 'Den Herrn sucht auf, daß ihr am Leben bleibt! Sonst kommt in Josephs Haus das Feuer und zehrt es auf, und niemand könnte Betels Flammen löschen. -',
        7: 'Weh denen, die das Recht in Wermut wandeln und die Gerechtigkeit zu Boden werfen!',
        8: 'Er ist\'s, der die Plejaden schuf und den Orion, und wie er Finsternis in Morgenlicht verwandelt, dunkelt er den Tag in Nacht. Er ruft des Meeres Wasser her und gießt sie auf die Erde. Sein Name ist "Der Herr".',
        9: 'Vernichtung bringt er starken Plätzen; als Verwüstung kommt er für die Festungen.',
        10: 'Sie hassen den, der vor Gericht Beweise bringt, verabscheun Fürsprecher der Schuldlosen.',
        11: '"Darum, weil ihr auf den Geringen mit Verachtung schaut, doch Kornabgaben von ihm nehmt, drum sollt ihr, mögt ihr auch aus Quadern Häuser bauen, sie dennoch nie bewohnen und, mögt ihr auch die herrlichsten Weingärten pflanzen, dennoch ihren Wein nicht trinken. -',
        12: 'Ja, eure vielen Frevel sind mit wohlbekannt und eurer Missetaten Menge; Schuldlose drücket ihr und nehmt Bestechung an und raubt den Armen vor Gericht ihr Recht."',
        13: 'Deswegen schweigt die Weissagung in jener Zeit; denn eine schlimme Zeit ist es. -',
        14: "Dem Guten strebet nach und nicht dem Bösen, daß ihr am Leben bleibt, damit alsdann der Herr, der Heeresscharen Gott, mit euch so sei, wie ihr's euch wünschet!",
        15: 'Das Böse hasset, liebt das Gute! Verschafft dem Rechte bei Gerichte Geltung! Vielleicht ist dann der Herr der Gott der Heerscharen, dem Reste Josephs gnädig.',
        16: 'Darum spricht so der Herr der Gott der Heerscharen, der Herr: "Auf allen Plätzen Weheklage! In allen Gassen schreit man Wehe, Wehe!\' Zur Trauer ruft man Sänger auf, zur Weheklage, die der Totenlieder kundig.',
        17: 'Auf allen Lagern Traurigkeit, wenn ich durch deine Mitte ziehe", spricht der Herr. -',
        18: 'Weh denen, die den Tag des Herrn sich wünschen! Wozu soll auch der Tag des Herrn nur dienen? Er ist ja Finsternis, nicht Licht.',
        19: 'Wie einer sich vor einem Löwen retten will und stößt auf einen Bären, tritt er ins Haus und stützt sich an die Wand mit seiner Hand, da sticht ihn eine Schlange,',
        20: 'ist nicht geradeso der Tag des Herrn von Unheil schwarz, von keinem Strahl erhellt, nur Dunkel, ohne Morgenstrahl? -',
        21: '"Ich hasse und verwerfe eure Feste und achte nicht auf eure Feiertage.',
        22: "Wenn ihr mir Brand- und Speiseopfer bringt, so hab' ich kein Gefallen daran. Nach euren fetten Bundesopfern mag ich gar nicht blicken.",
        23: 'Hinweg von mir mit dem Gelärme deiner Lieder! Dein Harfenspiel mag ich nicht hören.',
        24: 'Zur Spende werde Recht wie Wasser ausgegossen, Gerechtigkeit wie Ströme Weins!',
        25: 'Habt ihr mir Schlacht- und Speiseopfer dargebracht, Haus Israel, einst in der Wüste vierzig Jahre,',
        26: 'und habt ihr eures Königs Zelt umhergetragen und eures Gottes Sternbildsäule, die ihr euch angefertigt habt?',
        27: 'Darum verschleppe ich euch weiter weg als nach Damaskus." So spricht der Herr; sein Name ist: "Der Gott der Heerscharen".',
    },
    6: {
        1: 'Weh denen, die sich dort auf Sion sicher fühlen und die sich auf Samarias Berg verlassen, die da der Heidenvölker Bestes zur Aus- und Einfuhr nehmen für das Haus von Israel!',
        2: '"Nach Kalne geht und schaut euch um! Und zieht von dort her nach dem großen Hamat! Nach Gat in dem Philisterlande geht, ob ihr wohl tapfrer seid als diese Königreiche, ob ihr Gebiet nicht größer als das eure ist!',
        3: 'Die ihr den Unglückstag fern wissen möchtet und doch den Sabbat der Gewalt herbeiführt!"',
        4: 'Gelagert auf den elfenbeingeschmückten Ruhebetten und hingestreckt auf ihre Ruhelager, verzehren sie der Herde Lämmer, die jungen Rinder aus dem Stall.',
        5: 'Sie gröhlen zu der Zither Klang und musizieren wie verrückt.',
        6: 'Sie trinken von dem feinsten Wein und salben sich mit bestem Öl. Jedoch um Josephs Schaden kümmern sie sich nicht.',
        7: 'Sie ziehen deshalb an der Spitze der Gefangnen fort; zu Ende ist der Schwelger Freudenmahl.',
        8: 'Geschworen hat der Herr, der Herr, bei sich - ein Spruch des Herrn, des Gottes der Heerscharen -: "Ein Abscheu ist mir Jakobs Prunk; zuwider sind mir seine Schlösser. Ich geb die Stadt samt allem, was darinnen, preis.',
        9: 'Und blieben noch in einem einzigen Haus zehn Männer übrig, auch diese sollen sterben."',
        10: 'Wenn dann der Lieblingssohn und Erbe einen forttragen läßt, um die Gebeine aus dem Haus zu schaffen, und fragt er die, die sich im Hintergrund des Hauses hält: "Ist jemand noch bei dir?" dann sagt sie: "Nein!" und sagt dann noch: "Kein Wort mehr weiter!", weil man des Herren Namen nicht mehr nennen darf.',
        11: "Denn so, fürwahr, bestimmt's der Herr: Das große Haus schlägt er in Trümmer; das kleine ganz in Stücke.",
        12: '"Ja, laufen Rosse über Felsen? Kann man mit Stieren Felsen pflügen, daß ihr das Recht in Gift verwandelt, die Früchte der Gerechtigkeit in Wermut?',
        13: "Ihr, die ihr über Lodabar euch freut, ihr, die ihr sagt: 'Ja, haben wir dem nicht durch unsre Kraft Karnajim uns erobert?'",
        14: 'Fürwahr, ich lasse wider euch, du Haus von Israel", ein Spruch des Herrn, des Gottes der Heerscharen, "ein Volk erstehn, das euch bedrängt vom Weg nach Hamat bis zum Weidenbach."',
    },
    7: {
        1: "So ließ der Herr, der Herr, mich's schauen: Er führte junge Heuschrecken herbei zu Anbeginn, da Spätgras wuchs, das Gras, das späte, nach des Königs Mahd.",
        2: 'Und als sie alles Kraut im Lande fressen wollten, sprach ich: "Herr, o Herr, vergib! Wer hilft nur Jakob auf? Gar schwach ist es."',
        3: 'Der Herr erbarmte sich. "Es soll nicht sein!" so sprach der Herr.',
        4: 'Da ließ der Herr, der Herr, mich schauen: Der Herr, der Herr, rief einen Feuerwind herbei; er fraß das große Meer und wollte auch die Flur verzehren.',
        5: 'Da sprach ich: "Herr, ach Herr, hör auf! Wer hilft nur Jakob auf? Gar schwach ist es."',
        6: 'Der Herr erbarmte sich. "Auch dies soll nimmer sein", so sprach der Herr, der Herr.',
        7: 'Dann ließ er dies mich schauen: Da stand der Herr auf einem Haufen Hartgestein und hatte einen harten Stein in seiner Hand.',
        8: 'Da sprach der Herr zu mir: "Was siehst du, Amos?" Ich sagte: "Einen harten Stein." Da sprach der Herr: "Ich lege einen harten Stein ins Innere meines Volkes Israel und will ihm weiter nicht verzeihen.',
        9: 'Verwüstet sollen nunmehr werden Isaaks Höhen, die Heiligtümer Israels zerfallen, und wider des Jeroboam Haus erheb ich mich mit meinem Schwert."',
        10: 'Da ließ Amasias, der Priester Betels, Jeroboam, dem Könige von Israel, vermelden: "Verschwörung stiftet Amos gegen dich im Hause Israels; das Land kann seine Reden nicht mehr fassen;',
        11: 'denn so spricht Amos: \'Jeroboam stirbt durch das Schwert, und Israel wird weggeführt aus seiner Heimat.\'"',
        12: 'Zu Amos aber sprach Amasias: "Auf, Seher, fort! Nach Juda flieh! Dein Brot verdiene dort! Weissage dort!',
        13: 'Zu Betel darfst du doch nicht länger weissagen; denn es ist königliches Heiligtum und Reichstempel."',
        14: 'Darauf gab Amos Antwort und sprach zu Amasias: "Ich bin doch kein Prophet und kein Prophetensohn. Ein Hirte bin ich nur und Maulbeerfeigenzüchter.',
        15: "Mich hat der Herr gerade von der Herde weggeholt, und also sprach der Herr zu mir: 'Auf! Prophezeie gegen mein Volk Israel!'",
        16: "Und nun vernimm das Wort des Herrn! Du hast gesagt: 'Du darfst nicht gegen Israel weissagen, nicht gegen Isaaks Haus so predigen!'",
        17: 'Deshalb spricht so der Herr: \'Dein Weib wird öffentlich entehrt, und deine Söhne mit den Töchtern fallen durch das Schwert. Dein Boden wird durchs Los verteilt. Du selber stirbst auf ungeweihtem Boden, und Israel wird fortgeführt aus seiner Heimat.\'"',
    },
    8: {
        1: 'Dies ließ der Herr, der Herr, mich schauen: Es war ein Korb mit Erntefrüchten.',
        2: 'Er sprach: "Was siehst du, Amos?" Ich sagte: "Einen Korb mit Erntefrüchten." Da sprach der Herr zu mir: "Das Abernten kommt über mein Volk Israel; ich will ihm nicht verzeihen.',
        3: 'Die Glieder werden fürchterlich anschwellen", ein Spruch des Herrn, des Herrn, "an allen Orten wirft man schweigend Leichenhaufen hin."',
        4: 'Vernehmet dies, die ihr den Armen niedertretet, die Niedrigen im Lande unterdrückt',
        5: 'und sprecht: "Wann ist der Neumond um, damit wir Korn verkaufen, der Sabbat, daß wir Korn verhandeln können? Den Scheffel muß man kleiner machen, größer seinen Preis und das Gewicht verfälschen,',
        6: 'um Arme für das Geld zu kaufen und Dürftige um ein Paar Schuhe. - Taubes Korn verhandeln wir."',
        7: 'Der Herr schwört wider Jakobs Adel: "In Ewigkeit vergesse ich nicht ihre Taten." -',
        8: "Soll nicht darob das Land erbeben? Nicht alle trauern, die darinnen wohnen? Wär's gleich dem Euphrat angewachsen, hochgestiegen, so sinkt es dennoch wie Ägyptens Nil.",
        9: '"An jenem Tage wird\'s gescheh\'n", ein Spruch des Herrn, des Herrn, "da lasse ich die Sonne untergehn am Mittag und wandle für die Erde schon am Tag das Licht in Dunkel.',
        10: 'In Trauer ändere ich eure Feste, in Totenklage alle eure Lieder und gürte allen Hüften Bußgewänder um und mache kahlgeschoren jedes Haupt und mach es so wie bei der Trauer um den Einzigen. Und alles endet wie ein bitterer Tag." -',
        11: '"Es kommen Tage", Spruch des Herrn, des Herrn, "da sende ich ins Land den Hunger, doch Hunger nicht nach Brot, nicht Durst nach Wasser, vielmehr danach, das Wort des Herrn zu hören.',
        12: 'Sie wanken dann von Meer zu Meer, von Mitternacht bis Sonnenaufgang hin. So irren sie umher, ein Herrenwort zu suchen, doch sie finden keines. -',
        13: 'An jenem Tage sinken hin die jungen Mädchen, die Jünglinge, vor Durst verschmachtend,',
        14: 'die schwören bei Samarias Sünde, und die sprechen: \'So wahr dein Gott lebt, Dan! So wahr dein Stammgott lebt, Beetseba!\' Sie sinken hin und stehen nicht mehr auf."',
    },
    9: {
        1: 'Ich sah den Herrn an dem Altare stehn; Er sprach: "Wenn an den Säulenknauf du schlägst, dann beben auch die Schwellen. Das Haupt vernicht ich ihnen allen, dann schlag ich ihr Gefolge mit dem Schwerte nieder. Nicht einer soll entrinnen, von ihnen nicht ein einziger sich retten.',
        2: 'Selbst wenn sie in die Unterwelt eindrängen, holte meine Hand sie dort, und stiegen sie zum Himmel auf, dann holte ich sie auch von dort herab.',
        3: 'Versteckten sie sich auf des Karmels Gipfel, dort spähte ich sie aus und holte sie hinweg, und wollten sie vor meinen Augen auf dem Meeresgrunde sich verbergen, so böte ich die Schlangen, sie zu beißen, auf.',
        4: 'Und wanderten gefangen sie vor ihren Feinden her, auch dort geböt\' ich einem Schwerte, sie zu töten. Ich richte meinen Blick auf sie zum Unheil, nicht zum Guten."',
        5: 'Der Herr, der Herr der Heerscharen, der an die Erde rührt, daß sie erbebt, daß alle, die drauf wohnen, trauern und wäre sie dem Euphrat gleich gewachsen, sie wird dem Nil Ägyptens gleich sich wieder senken;',
        6: 'der da im Himmel seinen Söller baut und sein Gewölbe auf der Erde gründet, der dem Meerwasser zuruft und auf die Erde es hingießt; sein Name ist: "Der Herr."',
        7: '"Seid ihr mir nicht geradeso wie die Kuschiten, Söhne Israels?" Ein Spruch des Herrn. "Hab ich nicht aus Ägypterlande Israel geführt? Aus Kreta aber die Philister und aus Kir die Aramäer!" -',
        8: 'Fürwahr, des Herrn, des Herren Augen schauen auf das frevelhafte Reich. "Doch tilge ich durchaus nicht also Jakobs Haus, daß ich es von der Erde tilgte." - Ein Spruch des Herrn.',
        9: '"Fürwahr! Ich gebe Weisung, dann laß ich das Haus Israel bei all den Heiden schütteln, wie man in einer Schütteltrommel schüttelt, daß auf die Erde nicht ein einzig Klümpchen fällt.',
        10: "Dann sterben alle Sünder meines Volkes durch das Schwert, die sprechen: 'So bald kommt nicht das Unglück über uns.'",
        11: 'Dann aber richte ich an jenem Tag die Hütte Davids, die verfallene, auf, vermaure ihre Risse, stelle ihre Trümmer wieder her und baue neu sie auf wie in der Vorzeit fernen Tagen.',
        12: 'Dann nehmen sie den Rest von Edom, wie den von allen andern Völkern die einstens unter seiner Herrschaft standen." Ein Spruch des Herrn, der dies vollführt.',
        13: '"Fürwahr, dann kommen Tage", Spruch des Herrn, "da wird der Pflüger gar den Schnitter und der Traubenkelterer den Sämann treiben, von Wein die Berge triefen und alle Hügel von ihm fließen.',
        14: 'Da wende ich das Schicksal meines Volkes Israel. Sie bauen die zerstörten Städte auf und wohnen drin. Weinberge pflanzen sie und trinken deren Wein. Sie legen Gärten an und essen deren Früchte.',
        15: 'Ich pflanze sie in ihre Heimat ein, daß sie nicht abermals aus ihrem Boden, den ich gab, herausgerissen werden können." So spricht der Herr, dein Gott.',
    },
}
