NAME = 'FrePGR: Bible Perret-Gentil et Rilliet'
BOOK = 'Jonah'

CHAPTERS = {
    1: {
        1: "Et:la parole de l'Éternel fut adressée à Jonas, fils d'Amitthaï, en ces mots:",
        2: "Lève-toi, va à Ninive la grande ville, et prêche-lui, car sa méchanceté est parvenue jusqu'à moi.",
        3: "Mais Jonas se leva pour s'enfuir à Tarsis de devant la face de l'Éternel. Et il descendit à Joppe, et il trouva un navire partant pour Tarsis, et il paya son naulage, et s'embarqua pour aller avec eux à Tarsis, loin de la face de l'Éternel.",
        4: "Mais l'Éternel envoya un grand vent sur la mer, et il s'éleva une grande tempête sur la mer, et le navire risquait de naufrager.",
        5: "Alors les mariniers eurent peur, et ils invoquèrent chacun leur dieu, et ils jetèrent l'attirail qui était sur le vaisseau à la mer, pour l'alléger. Mais Jonas était descendu dans l'intérieur du vaisseau, et s'étant couché il s'était endormi",
        6: "Alors le maître du vaisseau s'approcha, de lui et lui dit: Que fais-tu de dormir? lève-toi! invoque ton Dieu! peut-être Dieu se ressouviendra de nous, et nous ne périrons pas.",
        7: "Et ils se dirent l'un à l'autre: Venez et tirons au sort pour connaître lequel nous attire ce malheur! Et ils tirèrent au sort, et le sort désigna Jonas.",
        8: "Alors ils lui dirent: Dis-nous qui nous attire ce malheur? Quelles sont tes affaires et d'où viens-tu? quel est ton pays et de quelle nation es-tu?",
        9: "Et il leur dit: Je suis hébreu, et c'est l'Éternel, le Dieu des Cieux, que j'adore, Celui qui a fait la mer et la terre ferme.",
        10: "Et ces hommes furent saisis d'une grande crainte, et ils lui dirent: Pourquoi as-tu fait cela? Car ces hommes savaient qu'il fuyait de devant la face de l'Éternel, parce qu'il le leur avait avoué.",
        11: 'Et ils lui dirent: Que te ferons-nous pour que la mer se calme envers nous? Car la mer devenait toujours plus orageuse.',
        12: "Et il leur dit: Prenez-moi, et jetez-moi à la mer, et la mer se calmera envers vous; car je sais que c'est moi qui vous attire cette grande tempête.",
        13: "Et ces hommes ramèrent pour revenir à terre; mais ils ne pouvaient, car la mer allait s'agitant toujours plus contre eux.",
        14: "Alors ils invoquèrent l'Éternel et dirent: Éternel, oh! ne nous fais pas: périr à cause de l'âme de cet homme, et ne nous charge pas du sang innocent; car tu es l'Éternel; ce que tu trouves bon, tu le fais.",
        15: "Et ils prirent Jonas et le jetèrent à la mer, et la mer cessa d'être furieuse.",
        16: "Et ces hommes furent saisis d'une grande crainte envers l'Éternel, et ils sacrifièrent à l'Éternel des victimes, et ils vouèrent des vœux.",
        17: "Et l'Éternel envoya un grand poisson pour engloutir Jonas, et Jonas fut dans le corps du poisson trois jours et trois nuits.",
    },
    2: {
        1: "Alors Jonas fit une prière à l'Éternel son Dieu, dans le corps du poisson, et il dit:",
        2: "Dans mon angoisse j'invoque l'Éternel et Il m'exauce; du sein des Enfers je crie, tu, entends ma voix.",
        3: "Tu me jettes dans l'abîme, au cœur de la mer, et les flots m'environnent, toutes tes vagues et tes ondes passent sur moi.",
        4: 'Mais je dis: Je suis repoussé loin de ton regard! Cependant je reverrai ton saint temple!',
        5: "Les eaux pénètrent jusques à mon âme, l'abîme m'enserre, l'algue s'attache à ma tête.",
        6: "Jusqu'à la base des montagnes je suis descendu, les barrières de la terre se sont fermées derrière moi pour toujours; et tu retires ma vie du tombeau, Éternel, mon Dieu!",
        7: "Quand en moi-même mon âme est défaillante, je me souviens de l'Éternel, et ma, prière parvient jusqu'à toi, jusqu'à ton saint temple.",
        8: 'Les adorateurs des vanités, du néant, abandonnent leur bienfaiteur;',
        9: "mais moi, je veux avec chants de louanges t'offrir des sacrifices et accomplir les vœux que j'ai faits. Le salut vient de l'Éternel!",
        10: "Et l'Éternel commanda au poisson, et il vomit Jonas sur la terre.",
    },
    3: {
        1: "Et la parole de l'Éternel fut adressée pour la seconde fois à Jonas en ces mots:",
        2: 'Lève-toi, va à Ninive la grande ville, et proclames-y la proclamation que je vais te dire.',
        3: "Alors Jonas se leva et alla à Ninive, selon la parole de l'Éternel. Or Ninive était une grande ville devant Dieu, ayant trois jours de marche.",
        4: 'Et Jonas commença à faire dans la ville une journée de marche, et fit la proclamation en ces mots: Encore quarante jours et Ninive est détruite.',
        5: 'Et les gens de Ninive crurent Dieu, et ils publièrent un jeûne, et ils se revêtirent tous du cilice et les grands et les petits.',
        6: "Et lorsque le bruit en parvint au roi de Ninive, il se leva de son trône et déposa son manteau, et se couvrit du cilice, et s'assit sur la cendre.",
        7: "Et il fit crier et dire dans Ninive, de par le roi et ses grands, ces paroles: Que les hommes et les animaux, le bétail et les troupeaux ne goûtent de rien, ne paissent point et ne boivent point d'eau!",
        8: "et que les hommes et les bestiaux soient recouverts du cilice! que l'on crie à Dieu avec force! et que chacun revienne de sa mauvaise voie et de l'injustice de ses mains!",
        9: "Qui sait? Dieu se repentira de nouveau! Il reviendra de l'ardeur de sa colère, et nous ne périrons pas.",
        10: "Et Dieu voyant qu'ils en agissaient ainsi et qu'ils revenaient de leur mauvaise voie, Dieu se repentit du mal qu'il avait parlé de leur faire, et Il ne le leur fit pas.",
    },
    4: {
        1: 'Et cela fut pour Jonas un très grand déplaisir, et il se dépita.',
        2: "Et il pria l'Éternel et dit: Ah! Éternel, n'est-ce pas ce que je disais, quand j'étais encore dans mon pays? Aussi me suis-je hâté de fuir à Tarsis; car je savais que tu es un Dieu clément et miséricordieux, plein de longanimité et d'amour et regrettant de punir.",
        3: 'Et maintenant, Éternel, ôte-moi donc ma vie, car mieux vaut pour moi mourir que de vivre.',
        4: "Mais l'Éternel dit: Fais-tu bien de te dépiter?",
        5: "Alors Jonas sortit de la ville, et s'assit à l'orient de la ville et il se fit là une cabane, et s'y assit à l'ombre, jusqu'à ce qu'il vît ce qui arriverait dans la ville.",
        6: "Alors l'Éternel Dieu fit croître un ricin qui s'éleva au-dessus de Jonas pour qu'il y eût de l'ombre sur sa fête et pour le délivrer de son mal. Et Jonas se réjouit à cause du ricin, et sa joie fut grande.",
        7: "Et Dieu fit venir à l'arrivée de l'aurore le lendemain un ver qui piqua le ricin, de sorte qu'il sécha.",
        8: "Et il arriva au lever du soleil que Dieu fit venir un vent d'orient sourd, et le soleil frappa la tête de Jonas, de sorte qu'il défaillait. Alors il demanda sa mort et il dit: Mieux vaut pour moi mourir que de vivre.",
        9: "Mais Dieu dit à Jonas: Fais-tu bien de te dépiter à cause du ricin? Et il dit: Je fais bien de me dépiter jusqu'à la mort.",
        10: "Et l'Éternel dit: Tu as pitié d'un ricin pour lequel tu n'as pris aucune peine et que tu n'as pas élevé, qui enfant d'une nuit a crû et enfant d'une nuit a péri:",
        11: "et moi je n'aurais point pitié de Ninive la grande ville, dans laquelle il y a plus de cent vingt mille hommes qui ne savent pas distinguer leur droite de leur gauche, et des animaux en grand nombre!",
    },
}
