NAME = 'GerGruenewald: 1924 Grünewaldbibel'
BOOK = 'I John'

CHAPTERS = {
    1: {
        1: 'Was von Anfang an gewesen, was wir gehört, was wir mit eigenen Augen gesehen, was wir geschaut und unsere Hände berührt haben, das künden wir vom Wort des Lebens.',
        2: 'Erschienen ist das Leben- wir haben gesehen und bezeugen und verkünden euch das ewige Leben, das beim Vater war und uns erschienen ist.',
        3: 'Also was wir gesehen und gehört haben, verkünden wir auch euch, damit auch ihr mit uns Gemeinschaft habt. Unsere Gemeinschaft haben wir mit dem Vater und mit seinem Sohne Jesus Christus.',
        4: 'Wir schreiben dies, auf daß ihr euch freut und wir volle Freude hätten.',
        5: 'Das ist die Botschaft, die wir von ihm vernommen haben und die wir euch verkünden: Gott ist Licht. In ihm gibt es keine Finsternis.',
        6: 'Doch wollten wir behaupten, daß wir mit ihm Gemeinschaft hätten, und wollten doch dabei im Finstern wandeln, dann lügen wir und tun nicht die Wahrheit.',
        7: 'Doch wandeln wir im Lichte, wie auch er im Lichte ist, dann leben wir in Gemeinschaft miteinander, und das Blut Jesu, seines Sohnes, macht uns von aller Sünde rein.',
        8: 'Wenn wir aber sagten, wir hätten keine Sünde, dann betrügen wir uns selbst, und die Wahrheit wohnt nicht in uns.',
        9: 'Bekennen wir jedoch unsere Sünden, dann ist er treu und rechtlich, so daß er uns unsere Sünden nachläßt und uns von allem Unrecht reinigt.',
        10: 'Würden wir aber sagen, wir hätten nicht gesündigt, dann würden wir ihn dadurch zum Lügner stempeln, und sein Wort wäre nicht in uns.',
    },
    2: {
        1: 'Meine Kinder, dies schreibe ich euch, damit ihr nicht sündigt. Und wenn einer trotzdem gesündigt hätte, dann ist uns Jesus Christus, der Gerechte, Fürsprecher beim Vater.',
        2: 'Er ist die Sühne für unsere Sünden, und nicht nur für die unsrigen allein, nein, auch für die ganze Welt.',
        3: 'Das ist ja der Beweis, daß wir ihn erkannt haben, wenn wir seine Gebote halten.',
        4: 'Wer sagt: "Ich kenne ihn", doch seine Gebote nicht hält, der ist ein Lügner; in einem solchen ist die Wahrheit nicht.',
        5: 'Doch wer sein Wort hält, in dem ist wahrhaft Gottes Liebe vollendet; dies ist auch das Zeichen, daß wir in ihm sind.',
        6: 'Wer sagt: "Ich bleibe in ihm", dem ist es heilige Pflicht, gerade so zu wandeln, wie auch er gewandelt ist.',
        7: 'Geliebteste! Kein neues Gebot ist es, was ich euch schreibe, sondern ein altes, und ihr hattet es von Anfang an: Das Wort, das ihr vernommen habt, ist dieses alte Gebot.',
        8: 'Und doch ist es auch ein neues Gebot, was ich euch schreibe, wahr in ihm und in euch: Die Finsternis geht vorüber; es leuchtet schon das wahre Licht.',
        9: 'Wer sagt, er sei im Lichte, doch seinen Bruder haßt, der ist noch immer in der Finsternis.',
        10: 'Wer aber seinen Bruder liebt, der bleibt im Licht ohne Anstoß.',
        11: 'Jedoch, wer seinen Bruder haßt, der ist noch immer in der Finsternis; er wandelt in der Finsternis und weiß nicht, wohin er geht; denn die Finsternis hat ihm die Augen verdunkelt.',
        12: 'Ich schreibe euch, ihr Kinder: Euch sind die Sünden nachgelassen um seines Namens willen.',
        13: 'Ich schreibe euch, ihr Väter: Ihr habt ja den erkannt, der von Anfang ist. Ich schreibe euch, ihr Jünglinge: Ihr habt den Bösen überwunden.',
        14: 'Ich habe euch geschrieben, ihr Kinder; denn ihr versteht den Vater. Ich habe euch geschrieben, ihr Väter; denn ihr habt den erkannt, der von Anfang ist. Ich habe euch geschrieben, ihr Jünglinge; denn ihr seid stark, und Gottes Wort wohnt in euch; ihr habt den Bösen überwunden.',
        15: 'Liebt nicht die Welt, noch was sich in der Welt befindet. Wenn jemand die Welt liebt, ist die Liebe des Vaters nicht in ihm.',
        16: 'Denn alles, was in der Welt sich findet: Lust des Fleisches, Lust der Augen, Hoffart des Lebens, kommt nicht vom Vater her, vielmehr kommt es von der Welt.',
        17: 'Allein, die Welt vergeht samt ihrer Lust; wer aber den Willen Gottes tut, bleibt in Ewigkeit.',
        18: 'Kinder, es ist die letzte Stunde: Ihr habt gehört: Es kommt der Antichrist. Jetzt sind schon viele Antichristi aufgestanden. Daran mögen wir erkennen, daß es letzte Stunde ist.',
        19: 'Aus unseren Reihen sind sie ausgegangen; doch sie gehörten nicht zu uns. Denn hätten sie zu uns gehört, so wären sie bei uns geblieben. Allein, es sollte an ihnen sich klar zeigen, daß nicht alle zu uns gehören.',
        20: 'Ihr aber habt die Salbung von dem Heiligen, und ihr alle wisset es.',
        21: 'Ich schreibe euch nicht deshalb, weil ihr die Wahrheit nicht erkennet, sondern weil ihr sie kennet und wisset, daß aus der Wahrheit niemals Lüge kommt.',
        22: 'Wer anders aber ist der Lügner, wenn nicht der, der leugnet, daß Jesus der Christus ist? Das ist der Antichrist, der den Vater samt dem Sohne leugnet.',
        23: 'Denn wer den Sohn leugnet, der hat auch nicht den Vater. Nur wer den Sohn bekennt, hat auch den Vater.',
        24: 'Was ihr von Anfang an vernommen habt, das soll in euch bleiben. Wenn in euch bleibt, was ihr von Anfang an vernommen habt, dann bleibt auch ihr im Sohn und im Vater.',
        25: 'So heißt ja die Verheißung, die er selber uns gegeben hat: das ewige Leben.',
        26: 'Soviel wollte ich euch über jene schreiben, die euch zu verführen suchen.',
        27: 'In euch hingegen bleibt die Stellung, die ihr von ihm empfangen habt; ihr habt nicht nötig, daß euch jemand belehre. Also, wie seine Salbung euch über alles aufgeklärt hat, so ist es wahr, und keine Lüge gibt es. Bleibt so in ihm, wie er es euch gelehrt hat.',
        28: 'Und jetzt, o Kinder, bleibt in ihm! Damit wir, wenn er erscheint, von froher Zuversicht erfüllt sind und bei seiner Ankunft nicht mit Beschämung von ihm zu weichen brauchen.',
        29: 'Ihr wißt, daß er gerecht ist, so wisset ihr auch, daß jeder, der Gerechtigkeit tut, aus ihm geboren ist.',
    },
    3: {
        1: 'Seht, welch große Liebe uns der Vater erwiesen hat: Wir heißen Kinder Gottes und sind es in der Tat. Darum versteht die Welt uns nicht, weil sie ihn nicht verstanden hat.',
        2: 'Geliebteste, jetzt sind wir Kinder Gottes, doch ist es noch nicht offenbar, was wir einst sein werden. Wir wissen aber, wenn er erscheint, werden wir ihm gleich sein, weil wir ihn schauen, wie er ist. -',
        3: 'Jeder, der solche Hoffnung auf ihn hegt, der heiligt sich, so wie auch jener heilig ist.',
        4: 'Jeder, der die Sünde tut, begeht damit auch die Gesetzlosigkeit; die Sünde selber ist die Gesetzlosigkeit.',
        5: 'Nun wisset ihr, daß jener erschienen ist, die Sünden wegzunehmen, und daß keine Sünde in ihm ist.',
        6: 'Jeder, der in ihm bleibt, ist sündenfrei. Doch wer sündigt, hat ihn nicht gesehen noch verstanden.',
        7: 'Kinder! Niemand möge euch verführen. Wer die Gerechtigkeit tut, ist gerecht, wie er gerecht ist.',
        8: 'Doch wer die Sünde tut, stammt aus dem Teufel; denn der Teufel sündigt von Anfang an. Dazu ist der Sohn Gottes erschienen, die Werke des Teufels zu zerstören.',
        9: 'Jeder, der aus Gott geboren ist, sündigt nicht; sein Lebenskeim bleibt ja in ihm. Er kann auch gar nicht sündigen, weil er aus Gott geboren ist.',
        10: 'Die Kinder Gottes und des Teufels sind daran zu erkennen: Wer nicht Gerechtigkeit übt, ist nicht aus Gott, noch auch, wer seinen Bruder nicht liebt.',
        11: 'Denn diese Botschaft habt ihr von Anfang an vernommen: daß wir einander lieben sollen.',
        12: 'Nicht so, wie Kain gehandelt hat, der vom Bösen kam und seinen Bruder mordete. Warum hat er ihn gemordet? Seine Werke waren eben böse, die seines Bruders recht.',
        13: 'Ihr braucht euch nicht zu wundern, Brüder, wenn die Welt euch haßt.',
        14: 'Wir wissen, daß wir aus dem Tode zum Leben gekommen sind, weil wir die Brüder lieben. Wer nicht liebt, bleibt im Tode.',
        15: 'Jeder, der seinen Bruder haßt, ist ein Menschenmörder. Ihr wisset auch: In keines Mörders Innern bleibt das ewige Leben.',
        16: 'Daran erkennen wir die Liebe, daß jener sein Leben für uns hingegeben hat. So sind auch wir verpflichtet, das Leben für die Brüder hinzugeben.',
        17: 'Wenn einer Güter dieser Welt besitzt und seinen Bruder in bitterer Not sieht und doch sein Herz vor ihm verschließt, wie kann in einem solchen noch die Liebe Gottes bleiben?',
        18: 'O Kinder, nicht in Worten laßt uns lieben, nicht mit der Zunge nur, sondern in Tat und Wahrheit.',
        19: 'Daraus werden wir ersehen, daß wir aus der Wahrheit sind, und werden unser Herz vor ihm beruhigen.',
        20: 'Denn mag auch unser Herz uns verdammen, noch größer als unser Herz ist Gott; er weiß ja alles.',
        21: 'Geliebteste, wenn unser Herz uns nicht verdammt, alsdann beseelt uns frohe Zuversicht auf Gott,',
        22: 'und alles, was wir von ihm erbitten, werden wir empfangen, weil wir seine Gebote bewahren und tun, was vor ihm wohlgefällig ist.',
        23: 'Und dies ist sein Gebot: Wir müssen an den Namen seines Sohnes Jesus Christus glauben und einander lieben, wie er es uns geboten hat.',
        24: 'Wer seine Gebote hält, der bleibt in ihm und er in diesem. Daß er in uns verbleibt, das erkennen wir aus dem Geiste, den er uns gegeben hat.',
    },
    4: {
        1: 'Geliebte! Trauet nicht jedem Geiste! Prüft die Geister, ob sie aus Gott sind. Denn viele falsche Propheten sind in die Welt hinausgegangen.',
        2: 'Daran erkennt man den Geist aus Gott: jeder Geist, der bekennt: Jesus Christus ist im Fleische gekommen, ist aus Gott.',
        3: 'Doch jeder Geist, der Jesus nicht bekennt, ist auch nicht aus Gott. Es ist vielmehr der Geist des Antichristen, von dem ihr vernommen habt, daß er kommt; ja, er ist schon in der Welt.',
        4: 'Doch ihr, o Kinder, seid aus Gott, ihr habt jene überwunden; denn er, der in euch ist, ist stärker als jener in der Welt.',
        5: 'Sie sind von der Welt; deshalb reden sie nach Art der Welt; es hört auch die Welt auf sie.',
        6: 'Wir aber sind aus Gott. Wer Gott erkennt, der hört auf uns; nur wer nicht aus Gott ist, der hört auch nicht auf uns. Daran erkennen wir den Geist der Wahrheit und den Geist der Verwirrung.',
        7: 'Geliebte! Lasset uns einander lieben! Die Liebe stammt aus Gott, und jeder, der liebt, ist aus Gott geboren und versteht Gott.',
        8: 'Doch wer nicht liebt, hat Gott nicht verstanden: Gott ist Liebe.',
        9: 'Dadurch hat sich die Liebe Gottes unter uns geoffenbart, daß Gott seinen Eingeborenen Sohn in diese Welt gesandt hat, damit wir durch ihn leben.',
        10: 'Und darin eben liegt die Liebe, nicht, daß wir Gott geliebt haben, sondern daß er uns geliebt und daß er seinen Sohn als Sühne für unsere Sünden gesandt hat.',
        11: 'Geliebte! Wenn uns Gott so sehr geliebt hat, dann sind auch wir verpflichtet, einander zu lieben.',
        12: 'Noch nie hat jemand Gott geschaut, doch wenn wir einander lieben, dann bleibt Gott in uns, und seine Liebe ist in uns vollendet.',
        13: 'Daran mögen wir erkennen, daß wir in ihm bleiben und er in uns verbleibt, daß er von seinem Geist uns gegeben hat.',
        14: 'Wir haben es gesehen und bezeugen es, daß der Vater seinen Sohn als Weltheiland gesandt hat.',
        15: 'Wer nun bekennt: Jesus ist der Sohn Gottes, in dem bleibt Gott und er in Gott.',
        16: 'Und wir haben erkannt und der Liebe geglaubt, die Gott zu uns hat. Gott ist Liebe. Wer in der Liebe bleibt, der bleibt in Gott, und Gott bleibt in ihm.',
        17: 'Darin vollendet sich bei uns die Liebe, daß wir voll Zuversicht für den Tag des Gerichtes verblieben; denn so wie jener sind auch wir in dieser Welt.',
        18: 'Furcht gibt es bei der Liebe nicht; denn ist die Liebe ganz vollendet, dann wird die Furcht verdrängt. Die Furcht hat Strafe in sich, und darum, ist, wer fürchtet, in der Liebe noch nicht vollendet.',
        19: 'Wir lieben, weil er uns zuvor geliebt hat.',
        20: 'Wenn einer sagt: "Ich liebe Gott", doch seinen Bruder haßt, der ist ein Lügner. Wenn einer nämlich seinen Bruder, den er sieht, nicht liebt, der kann auch Gott nicht lieben, den er nicht gesehen hat.',
        21: 'Dieses Gebot haben wir von ihm: Wer Gott liebt, muß auch seinen Bruder lieben.',
    },
    5: {
        1: 'Jeder, der glaubt, daß Jesus der Christus ist, ist aus Gott geboren. Jeder der den Vater liebt, liebt auch dessen Kind.',
        2: 'Daran erkennen wir, daß wir die Kinder Gottes lieben, wenn wir Gott selber lieben und seine Gebote halten.',
        3: 'Denn das ist Liebe zu Gott, daß wir seine Gebote halten.',
        4: 'Seine Gebote sind nicht schwer. Denn alles, was aus Gott geboren ist, hat die Welt überwunden, und unser Glaube ist der Sieg, der die Welt bezwungen hat.',
        5: 'Wer ist es denn, der die Welt besiegt, wenn nicht der, der glaubt, daß Jesus der Sohn Gottes ist?',
        6: 'Er ist es, der gekommen ist durch Wasser, Blut und Geist: Jesus Christus. Nicht allein durch Wasser, sondern durch Wasser und durch Blut. Der Geist ist es, der es bezeugt; der Geist ist Wahrheit.',
        7: 'So sind es denn drei, die Zeugnis geben: im Himmel: der Vater, das Wort und der Heilige Geist, und diese drei sind Eins. Und drei sind es, die Zeugnis geben auf Erden:',
        8: 'Der Geist, das Wasser und das Blut, und diese drei stimmen überein.',
        9: 'Wenn wir dem Zeugnis der Menschen glauben, so steht doch das Zeugnis Gottes höher; denn dies ist das Zeugnis Gottes das höher steht, daß er von seinem Sohne Zeugnis abgelegt hat.',
        10: 'Wer immer an den Sohn Gottes glaubt, der hat das Zeugnis in sich. Wer aber Gott nicht glaubt, macht ihn zum Lügner; er glaubt ja nicht all das Zeugnis, das Gott von seinem Sohn abgelegt hat.',
        11: 'Und dieses Zeugnis lautet: Gott hat uns ewiges Leben gegeben, und dieses Leben ist in seinem Sohne.',
        12: 'Wer den Sohn hat, hat das Leben, wer aber den Sohn Gottes nicht hat, hat auch das Leben nicht.',
        13: 'Dies schreibe ich euch, damit ihr wisset, daß ihr das ewige Leben habt, die ihr an den Namen des Sohnes Gottes glaubt.',
        14: 'Und das ist unsere Zuversicht, die wir zu ihm besitzen, daß er uns hört, wenn wir nach seinem Willen um irgend etwas bitten.',
        15: 'Und wenn wir wissen, daß er uns hört, um was wir immer bitten, so wissen wir auch, daß wir das schon besitzen, was wir mit unseren Bitten erst von ihm erflehen.',
        16: 'Wenn einer sieht, wie sein Bruder eine Sünde tut, die nicht zum Tode führt, der möge beten und dadurch ihm zum Leben verhelfen, wofern er nicht zum Tode gesündigt hat. Es gibt auch eine Sünde, die zum Tode führt; doch nicht für diese, sage ich, soll man beten.',
        17: 'Jede Ungerechtigkeit ist Sünde. Es gibt indes auch eine Sünde, die nicht zum Tode führt.',
        18: 'Wir wissen: Wer aus Gott geboren ist, der sündigt nicht; sondern wer aus Gott geboren ist, der hütet sich, und auch der Böse tastet ihn nicht an.',
        19: 'Wir wissen, daß wir aus Gott stammen und daß die ganze Welt in der Gewalt des Bösen liegt.',
        20: 'Wir wissen aber auch, daß der Sohn Gottes gekommen ist und daß er uns die Einsicht gegeben hat, daß wir den Wahrhaftigen erkennen. Wir sind in dem Wahrhaftigen, in seinem Sohne Jesus Christus. Dies ist der wahre Gott und ewiges Leben.',
        21: 'Kinder, hütet euch vor den Götzen!',
    },
}
