NAME = 'GerGruenewald: 1924 Grünewaldbibel'
BOOK = 'I Thessalonians'

CHAPTERS = {
    1: {
        1: 'Paulus, Silvanus und Timotheus an die Gemeinde der Thessalonicher in Gott, dem Vater, und im Herrn Jesus Christus. Gnade werde euch zuteil und Friede.',
        2: 'Wir danken Gott allezeit für euch alle, sooft wir bei unseren Gebeten euer gedenken.',
        3: 'Vor Gott und unserem Vater denken wir unablässig an euren Glauben, der sich in Werken kundgibt, an eure Liebe, die solche Opfer bringt, an eure feste Hoffnung auf unseren Herrn Jesus Christus.',
        4: 'Wir sind auch überzeugt, von Gott geliebte Brüder, daß ihr erwählt seid.',
        5: 'Denn unser Evangelium ist nicht bloß in Worten zu euch gekommen, sondern auch in Macht und im Heiligen Geiste und mit großer Überzeugungskraft. Ihr wisset ja, wie wir um euretwillen bei euch aufgetreten sind.',
        6: 'Und ihr seid unsere sowie des Herrn Nachahmer geworden, da ihr das Wort, trotz vieler Not, doch mit der Freude des Heiligen Geistes angenommen habt.',
        7: 'Ihr wurdet so ein Vorbild für alle Gläubigen in Mazedonien und in Achaia.',
        8: 'Von euch aus ist das Wort des Herrn erklungen nicht bloß in Mazedonien und Achaia, überall ist euer Glaube an Gott kund geworden. Darüber brauchen wir nichts weiter mehr zu sagen.',
        9: 'Die Leute selbst erzählen es, welch eine Aufnahme wir bei euch gefunden haben und wie ihr euch von den Götzen zu Gott bekehrt habt, um dem lebendigen und wahren Gott zu dienen',
        10: 'und seinen Sohn, den er von den Toten auferweckt hat, vom Himmel zu erwarten, Jesus, der vor dem kommenden Zorngericht uns errettet.',
    },
    2: {
        1: 'Ihr selber wißt ja, meine Brüder, daß unser Auftreten bei euch nicht vergeblich war.',
        2: 'Obgleich wir, wie ihr wisset, schon vorher in Philippi Leiden und Mißhandlungen zu dulden hatten, so haben wir doch im Vertrauen auf unseren Gott den Mut gefunden, euch in heißem Bemühen das Evangelium Gottes zu verkünden.',
        3: 'Unsere Predigt hat ja nichts zu tun mit trügerischer oder mit unlauterer Absicht oder gar mit Arglist;',
        4: 'wir reden vielmehr so, wie wir von Gott gewürdigt wurden, mit dem Evangelium betraut zu werden. Wir reden nicht, um Menschen zu gefallen, vielmehr Gott, der unser Herz durchschaut.',
        5: 'Gar nie, ihr wißt es, sind wir mit Schmeichelreden noch mit versteckter Habsucht aufgetreten - Gott ist unser Zeuge -,',
        6: 'noch suchten wir Ruhm bei den Menschen, bei euch nicht, noch bei anderen.',
        7: 'Wir hätten als Apostel Christi zwar gewichtig auftreten können, doch traten wir in eurer Mitte milde auf wie eine Mutter, die ihre Kinder pflegt.',
        8: 'Ja, so sehr fühlten wir uns zu euch hingezogen und waren gern bereit, nicht bloß das Evangelium Gottes euch zu bringen, sondern auch unsere Lebenskraft für euch zu opfern; so sehr wart ihr uns lieb geworden.',
        9: 'Brüder, ihr erinnert euch an unsere Mühe und Beschwerde. Wir haben Tag und Nacht gearbeitet, um keinem aus euch zur Last zu fallen; so haben wir euch das Evangelium Gottes verkündet.',
        10: 'Ihr und Gott seid dafür Zeugen, wie lauter und gerecht und tadellos wir uns gegen euch, ihr Gläubigen, benommen haben.',
        11: 'Ihr wißt auch, wie wir jeden einzelnen aus euch, gleichwie ein Vater seine Kinder,',
        12: 'ermahnt und aufgemuntert und beschworen haben, ihr möchtet Gottes würdig wandeln, der euch zu seinem Reich und zu seiner Herrlichkeit berufen hat.',
        13: 'Darum danken wir unablässig Gott dafür, daß ihr unsere Predigt vom Worte Gottes aufgenommen habt, nicht als ein Menschenwort etwa habt ihr sie aufgenommen, vielmehr als das, was sie in Wahrheit ist, als Wort Gottes. Dieses ist auch in euch, den Gläubigen, wirksam.',
        14: 'Ihr, meine Brüder, seid ja Nachahmer geworden der Gemeinden Gottes in Judäa, die in Christus Jesus sind. Von euren Volksgenossen hattet ihr die gleichen Leiden zu erdulden, wie jene von den Juden.',
        15: 'Sie haben sogar den Herrn Jesus und die Propheten getötet und uns verfolgt. Sie sind Gott mißfällig Und allen Menschen feind;',
        16: 'sie wollen uns hindern, zu den Heiden zu sprechen, damit auch sie gerettet werden. So machen sie das Maß ihrer Sünden ganz und gar voll. Doch der Zorn hat sich schon völlig an ihnen ausgewirkt.',
        17: 'Brüder! Wir waren fern von euch, äußerlich, nicht aber dem Herzen nach. Da hatten wir lebhaft und voll Sehnsucht das Verlangen, euch wiederum zu sehen.',
        18: 'Deswegen hatten wir uns vorgenommen, zu euch zu kommen, ich, Paulus, sogar wiederholt; doch Satan hat uns daran gehindert.',
        19: 'Denn wer ist unsere Hoffnung, unsere Freude und unser Ruhmeskranz vor unserem Herrn Jesus bei seiner Ankunft, wenn nicht gerade ihr?',
        20: 'Ja, ihr seid unser Ruhm und unsere Freude.',
    },
    3: {
        1: 'Als wir nicht länger uns gedulden konnten, entschlossen wir uns, in Athen allein zurückzubleiben,',
        2: 'und entsandten den Timotheus, unseren Bruder und Diener Gottes für das Evangelium Christi. Er sollte euch im Glauben stärken und ermuntern,',
        3: 'damit niemand im Glauben sich irremachen lasse in den gegenwärtigen Bedrängnissen. Ihr wißt: Dazu sind wir da.',
        4: 'Schon damals, als wir bei euch waren, sagten wir euch zum voraus, daß wir Drangsale erdulden mußten. Ihr wißt jetzt, daß es auch so kam.',
        5: 'Deshalb also, weil ich es länger nicht ertragen konnte, habe ich hingesandt, um zu erfahren, wie es um euren Glauben stehe, ob doch nicht etwa der Versucher euch in Versuchung geführt habe und unsere Arbeit vergeblich gewesen sei.',
        6: 'Jetzt aber ist Timotheus von euch zu uns zurückgekehrt und hat von eurem Glauben und von eurer Liebe uns frohe Kunde gebracht und uns berichtet, daß ihr uns stets in gutem Andenken behaltet voll Sehnsucht, uns noch einmal zu sehen, gleichwie auch wir euch sehen möchten.',
        7: 'Deswegen, Brüder, sind wir voll des Trostes euretwegen durch euren Glauben, all unserer Not und Drangsal zum Trotz.',
        8: 'Wir leben aber jetzt auf, wenn ihr im Herrn feststeht.',
        9: 'Wie könnten wir Gott euretwegen genug für all die Freude danken, die wir von unserem Gott um euch empfinden?',
        10: 'Wir beten Tag und Nacht mit übervollem Herzen um die Gnade, euch zu sehen und das zur Vollendung zu bringen, was noch an eurem Glauben fehlt.',
        11: 'Er selbst aber, unser Gott und Vater, und Jesus, unser Herr, lenke unsern Weg zu euch.',
        12: 'Euch aber lasse der Herr zunehmen und überreich an Liebe werden zueinander und zu allen Menschen, so wie wir euch lieben.',
        13: 'Er möge eure Herzen stärken, daß sie untadelig und heilig vor Gott und unserem Vater seien bei der Ankunft Jesu, unseres Herrn mit allen seinen Heiligen.',
    },
    4: {
        1: 'Im übrigen, meine Brüder, bitten und ermahnen wir euch im Herrn Jesus: Wie ihr es von uns überliefert bekommen habt, wie ihr leben und Gott wohlgefallen sollt, lebt auch wirklich so. Dann werdet ihr immer vollkommener werden.',
        2: 'Ihr wißt ja, welche Vorschriften wir euch in der Kraft des Herrn Jesus gegeben haben.',
        3: 'Denn das ist der Wille Gottes: eure Heiligung. Ihr sollt der Unzucht euch enthalten.',
        4: 'Ein jeglicher aus euch soll es verstehen, in heiliger Zucht und Ehrbarkeit sein Weib sich zu gewinnen',
        5: 'und nicht in leidenschaftlicher Begierde wie die Heiden, die Gott nicht kennen.',
        6: 'Es soll sich keiner einen Übergriff erlauben und seinen Bruder geschäftlich hintergehen; denn alle diese straft der Herr, wie wir ja früher schon es euch gesagt und versichert haben.',
        7: 'Gott hat uns nicht zur Unlauterkeit berufen, vielmehr zur Heiligung.',
        8: 'Wer demnach dies mißachtet, mißachtet nicht Menschen, sondern Gott, der euch seinen Heiligen Geist gegeben hat.',
        9: 'Von brüderlicher Liebe braucht man euch nicht zu schreiben: Ihr habt von Gott selbst es gelernt, einander zu lieben;',
        10: 'ihr tut dies ja in ganz Mazedonien an allen Brüdern. Wir ermahnen euch aber, liebe Brüder, darin immer noch mehr zuzunehmen.',
        11: 'Setzt eure Ehre darein, ein stilles Leben zu führen, eure Angelegenheiten zu besorgen und eurer Hände Arbeit zu verrichten, wie wir euch angewiesen haben.',
        12: 'So wandelt ihr in Ehren vor den Außenstehenden und braucht niemand in Anspruch zu nehmen.',
        13: 'Meine Brüder, wir wollen euch über die Entschlafenen nicht im Ungewissen lassen, damit ihr nicht trauert wie die anderen, die keine Hoffnung haben.',
        14: 'Wenn wir glauben, daß Jesus gestorben und auferstanden ist, so wird Gott ebenso auch die Entschlafenen durch Jesus zugleich mit ihm herbeiführen.',
        15: 'Das sagen wir euch nach einem Worte des Herrn: Wir, die wir noch am Leben sind, die wir noch für die Ankunft des Herrn übrig sind, wir werden vor den Entschlafenen nichts voraus haben.',
        16: 'Der Herr wird ja, wenn der Befehl ergeht, beim Schalle der Stimme des Erzengels und der Posaune Gottes vom Himmel niedersteigen. Zuerst erstehen die in Christus Verstorbenen.',
        17: 'Dann werden wir, die wir noch am Leben und noch übrig sind, vereint mit jenen auf den Wolken in die Luft entrückt werden, dem Herrn entgegen, und werden so immerdar in Gemeinschaft mit dem Herrn sein.',
        18: 'Mit diesen Worten also tröstet einander.',
    },
    5: {
        1: 'Von den Zeiten und von den Fristen, meine Brüder, braucht man euch nicht zu schreiben.',
        2: 'Ihr wißt selbst recht wohl: Der Tag des Herrn kommt wie ein Dieb in der Nacht.',
        3: 'Wenn man noch von Frieden und von Sichersein spricht, bricht plötzlich das Verderben über einen her, gleichwie die Wehen über eine Schwangere; sie werden sicher nicht entrinnen.',
        4: 'Ihr aber, liebe Brüder, bleibt nicht in Finsternis, damit jener Tag euch nicht einem Diebe gleich überrasche.',
        5: 'Ihr alle seid Söhne des Lichtes und Söhne des Tages; wir gehören nicht der Nacht an und nicht der Finsternis.',
        6: 'So laßt uns also nicht schlafen, wie die übrigen; wir wollen vielmehr wachsam sein und nüchtern.',
        7: 'Wer schläft, der schläft bei Nacht, wer trunken ist, der ist bei Nacht betrunken.',
        8: 'Wir aber, die wir dem Tage angehören, wir wollen nüchtern sein, wir wollen mit dem Panzer des Glaubens und der Liebe uns bewaffnen und mit dem Helm der Hoffnung auf das Heil.',
        9: 'Denn Gott hat uns nicht zum Zorne bestimmt, sondern daß wir das Heil erlangen durch unseren Herrn Jesus Christus,',
        10: 'der für uns gestorben ist, damit wir, mögen wir wachen oder entschlafen sein, mit ihm vereinigt leben.',
        11: 'Darum ermahnt und erbaut einander, so wie ihr es ja auch bisher schon tut.',
        12: 'Wir bitten euch, Brüder, zollt denen Anerkennung, die sich bei euch abmühen und eure Vorsteher und Seelsorger im Herrn sind.',
        13: 'Schätzt sie in liebevollem Sinne ganz besonders hoch um ihres Wirkens willen. Lebt im Frieden miteinander.',
        14: 'Liebe Brüder, wir ermahnen euch, weist Unbotmäßige zurecht und tröstet die Kleinmütigen, nehmt euch der Schwachen an und habt Geduld mit allen.',
        15: 'Seht zu, daß keiner Böses mit Bösem vergelte; strebt vielmehr allezeit danach, euch gegenseitig und allen anderen Gutes zu erweisen.',
        16: 'Freut euch allezeit.',
        17: 'Betet ohne Unterlaß. Seid in jeder Lage dankbar.',
        18: 'Denn das will Gott von euch in Christus Jesus.',
        19: 'Löscht den Geist nicht aus.',
        20: 'Weist prophetische Rede nicht verächtlich zurück.',
        21: 'Prüft alles; das, was gut ist, behaltet.',
        22: 'Haltet euch fern jeder schlechten Art.',
        23: 'Er selbst aber, der Gott des Friedens, heilige euch in vollem Maße. Euer Geist und eure Seele und euer Leib bleibe makellos bis zur Ankunft unseres Herrn Jesus Christus.',
        24: 'Getreu ist, der euch berufen hat; er wird es auch vollenden.',
        25: 'Liebe Brüder, betet auch für uns.',
        26: 'Grüßt mit heiligem Kusse alle Brüder!',
        27: 'Ich beschwöre euch beim Herrn: Laßt allen heiligen Brüdern diesen Brief vorlesen.',
        28: 'Die Gnade unseres Herrn Jesus Christus sei mit euch. Amen.',
    },
}
