NAME = 'PorNVA: Bíblia Nova Versão de Acesso Livre'
BOOK = 'I Thessalonians'

CHAPTERS = {
    1: {
        1: 'Paulo, Silvano e Timóteo à igreja de Tessalônica em Deus Pai, e no Senhor Jesus Cristo. Graça e paz a vós.',
        2: 'Nós sempre agradecemos a Deus por todos vós, mencionando-vos em nossas orações.',
        3: 'Lembramos-nos sem cessar, diante de nosso Deus e Pai, da obra da vossa fé, do trabalho do vosso amor e da perseverança da vossa esperança em nosso Senhor Jesus Cristo.',
        4: 'Irmãos amados por Deus, nós sabemos que Ele vos escolheu,',
        5: 'porque o nosso Evangelho não chegou até vós somente em palavra, mas também em poder no Espírito Santo e com toda convicção. Assim, sabeis qual tipo de homens éramos quando estávamos no meio de vós, agindo para o vosso bem.',
        6: 'Vós vos tornastes nossos imitadores e do Senhor, recebendo a Palavra com alegria do Espírito Santo, apesar de grande tribulação.',
        7: 'Por isso vos tornastes exemplos para todos os crentes da Macedônia e Acaia.',
        8: 'Por meio de vós, a Palavra do Senhor tem sido espalhada, não somente na Macedônia e Acaia. Mas, em cada lugar, a vossa fé em Deus tem sido divulgada. Por isso não precisamos dizer nada.',
        9: 'Eles próprios relatam qual tipo de acolhimento nós tivemos convosco e como vos convertestes a Deus, deixando os ídolos para servir ao Deus vivo e verdadeiro,',
        10: 'esperando por Seu Filho, vindo dos céus, que ressurgiu da morte. Esse é Jesus, que nos livra da ira vindoura.',
    },
    2: {
        1: 'Vós mesmos sabeis, irmãos, que a nossa visita a vós não foi em vão.',
        2: 'Sabeis que sofremos e fomos tratados de forma vergonhosa em Filipos. Mesmo assim tivemos confiança em nosso Deus para compartilhar o Seu Evangelho convosco, mesmo em meio a grandes dificuldades.',
        3: 'Pois nossa exortação não procede de erro, nem de impureza, nem de engano.',
        4: 'Mas, assim como fomos aprovados por Deus para que o Evangelho nos fosse confiado, assim falamos, não para agradar a homens, mas para agradar a Deus. Ele é Aquele que examina nossos corações.',
        5: 'Portanto nunca usamos palavras para bajulação, como sabeis, nem com intenção gananciosa. Deus é testemunha disso.',
        6: 'Não buscamos glória de homens, nem de vós nem de outros. Como apóstolos de Cristo, poderíamos ter exigido privilégios.',
        7: 'Em vez disso, fomos gentis entre vós, como uma mãe acalentando seus próprios filhos.',
        8: 'Do mesmo modo, devido ao grande afeto por vós, estávamos contentes por compartilhar convosco não só o Evangelho de Deus, mas também as nossas próprias vidas. Pois vos tornastes muito queridos para nós.',
        9: 'Irmãos, sem dúvida vos lembrais de nosso trabalho e fadiga. Trabalhamos dia e noite para que não fôssemos como um fardo para nenhum de vós. Durante aquele tempo, vos pregávamos o Evangelho de Deus.',
        10: 'Vós sois testemunhas, assim como Deus, de como nos comportamos de forma santa, justa e irrepreensível para convosco, que credes.',
        11: 'Do mesmo modo, sabeis que tratamos cada um de vós como um pai trata seus filhos,',
        12: 'exortando-vos, encorajando-vos e insistindo para viverdes de maneira digna de Deus, que vos chama para o Seu reino e glória.',
        13: 'Por isso nós também agradecemos a Deus constantemente. Pois, quando recebestes de nós a Palavra que ouvistes, não a aceitastes como palavra de homem, mas como ela realmente é, a Palavra de Deus. Essa é a Palavra que também age em vós, que credes.',
        14: 'Porque vós, irmãos, vos tornastes imitadores das igrejas de Deus que estão na Judéia, em Cristo Jesus. Pois também sofrestes as mesmas coisas de seus conterrâneos, assim como eles sofreram dos Judeus.',
        15: 'Foram os Judeus que mataram tanto o Senhor Jesus quanto os profetas. Foram eles que nos expulsaram. Eles não agradam a Deus e são inimigos de todos os homens,',
        16: 'e nos proíbem de falar aos gentios para a salvação deles. Desse modo, só aumentam seus pecados. A ira veio sobre eles de forma definitiva.',
        17: 'Nós, irmãos, separados de vós por um breve período, em presença, não em coração, estamos nos esforçando e com grande desejo de ver-vos novamente.',
        18: 'Porque queremos visitar-vos. Eu, Paulo, tentei visitar-vos mais de uma vez, mas Satanás nos impediu.',
        19: 'Pois, quando nosso Senhor Jesus voltar, quem será nossa esperança, alegria e coroa de glória diante Dele? Por acaso não sois vós assim como os outros?',
        20: 'Pois vós sois nossa glória e alegria.',
    },
    3: {
        1: 'Portanto, quando nós já não podíamos mais suportar, pensamos que seria bom ficarmos sozinhos em Atenas.',
        2: 'Nós enviamos Timóteo, nosso irmão e ministro de Deus no Evangelho de Cristo, para vos fortalecer e confortar em relação à vossa fé.',
        3: 'Nós fizemos isso com o desejo de que ninguém fosse abalado por essas tribulações. Pois vós sabeis que foi para isso que fomos destinados.',
        4: 'Verdadeiramente, quando estávamos convosco, predissemos que haveríamos de sofrer aflição, e isso aconteceu, como vós sabeis.',
        5: 'Por essa razão, quando eu não podia mais suportar, eu o enviei para poder saber acerca da vossa fé, pois talvez o tentador, de alguma maneira, houvesse vos tentado e nosso trabalho tivesse sido em vão.',
        6: 'Mas Timóteo retornou a nós e trouxe boas notícias da vossa fé e amor. Conforme ele nos disse, vós sempre tendes boas lembranças de nós e desejais nos ver, assim como também nós desejamos ver a vós.',
        7: 'Por causa disso, irmãos, nós fomos confortados por causa da vossa fé, em toda a nossa angústia e aflição.',
        8: 'Pois nós agora vivemos, se vós permanecerdes firmes no Senhor.',
        9: 'Pois quantas graças podemos dar a Deus por vós, por toda alegria que nós temos diante de Deus por vossa causa?',
        10: 'Noite e dia nós oramos arduamente para ver vossas faces e prover aquilo que falta à vossa fé.',
        11: 'Que o próprio Deus, nosso Pai, e nosso Senhor Jesus, direcionem nosso caminho até vós.',
        12: 'E que o Senhor vos faça crescer e abundar no amor uns para com os outros e para com todos as pessoas, assim como nós também fazemos para convosco.',
        13: 'Que Ele fortaleça os vossos corações, a fim de que sejam irrepreensíveis em santidade diante do nosso Deus e Pai, na vinda do nosso Senhor Jesus com todos os Seus santos.',
    },
    4: {
        1: 'Finalmente, irmãos, nós vos pedimos e exortamos no Senhor Jesus que, assim como recebestes nossas instruções sobre como deveis andar e satisfazer a Deus, também neste caminho andai, para que façais ainda mais.',
        2: 'Pois sabeis quais instruções vos demos através do Senhor Jesus.',
        3: 'Esta é a vontade de Deus: a vossa santificação, que vos afasteis da imoralidade sexual,',
        4: 'que cada um de vós saiba controlar seu próprio corpo de forma santa e honrosa,',
        5: 'não conduzidos por paixão lasciva, como os gentios que não conhecem a Deus.',
        6: 'E que ninguém desrespeite ou lese a seu irmão nessa questão. Porque o Senhor é o vingador em todas essas coisas, como vos avisamos e testificamos.',
        7: 'Porque Deus não nos chamou para a impureza, mas para a santidade.',
        8: 'Portanto, quem rejeita isso não rejeita a pessoas, mas a Deus, que vos deu o Seu Espírito Santo.',
        9: 'A respeito do amor fraternal, não necessitais que ninguém vos escreva, pois vós mesmos sois ensinados por Deus a amar uns aos outros.',
        10: 'De fato, fazeis isto com todos os irmãos que estão em toda Macedônia. Entretanto, nós vos exortamos, irmãos, a fazer isso ainda mais.',
        11: 'Também vos exortamos a buscar viver pacificamente, cuidar das vossas coisas, e trabalhar com vossas mãos, como vos ordenamos;',
        12: 'assim, andareis corretamente diante daqueles que são de fora, e não necessitareis de coisa nenhuma.',
        13: 'Irmãos, não queremos que ignoreis acerca daqueles que dormem, para que não vos entristeçais como os demais que não têm esperança.',
        14: 'Porque, se acreditamos que Jesus morreu e ressuscitou, também Deus trará com Jesus aqueles que dormiram Nele.',
        15: 'Pois isto vos falamos pela Palavra do Senhor, que nós que estamos vivos, esperando a vinda do Senhor, com certeza não precederemos aqueles que dormem.',
        16: 'Porque o próprio Senhor descerá do céu com grande brado, com a voz do arcanjo, e com a trombeta de Deus, e os mortos em Cristo ressuscitarão primeiro.',
        17: 'Depois, nós, os que estivermos vivos, os que permanecermos, seremos arrebatados juntamente com eles nas nuvens, para nos reunir com o Senhor nos ares. Desse modo, estaremos sempre com o Senhor.',
        18: 'Portanto, consolai uns aos outros com estas palavras.',
    },
    5: {
        1: 'A respeito do tempo e das estações, irmãos, não precisais que algo vos seja escrito.',
        2: 'Sabeis perfeitamente que o dia do Senhor virá como um ladrão de noite.',
        3: 'Quando disserem: "Paz e segurança", a destruição repentina lhes sobrevirá. Será como dores de parto à mulher grávida, e eles não terão como escapar.',
        4: 'Mas vós, irmãos, não estais na escuridão de modo que aquele dia vos alcance como um ladrão.',
        5: 'Vós sois todos filhos da luz e filhos do dia. Nós não somos filhos da noite ou da escuridão.',
        6: 'Logo, não durmamos como os outros fazem, mas continuemos a vigiar, e estejamos sóbrios.',
        7: 'Porque os que dormem, dormem de noite, e aqueles que se embriagam, embriagam-se de noite.',
        8: 'Mas, como somos filhos do dia, fiquemos sóbrios. Coloquemos a couraça da fé e do amor, e a esperança da salvação futura como nosso capacete.',
        9: 'Porque Deus não nos destinou para a ira, mas para obtermos a salvação, por meio de nosso Senhor Jesus Cristo.',
        10: 'Ele que morreu por nós, para que, independentemente de estarmos acordados ou dormindo, possamos viver juntos com Ele.',
        11: 'Portanto, confortemos e edifiquemos uns aos outros como vós já fazeis.',
        12: 'Nós vos pedimos, irmãos, que reconheçais aqueles que trabalham entre vós, que cuidam de vós no Senhor, e que vos admoestam.',
        13: 'Também pedimos que os considereis em alta estima, em amor, por causa do trabalho deles. Vivei em paz.',
        14: 'Nós vos exortamos, irmãos, a advertir os indisciplinados, encorajar os desencorajados, auxiliar os fracos, e ser pacientes para com todos.',
        15: 'Cuidai para que ninguém retribua o mal com o mal, mas esforçai-vos pelo bem uns dos outros e de todos.',
        16: 'Alegrai-vos sempre.',
        17: 'Orai sem cessar.',
        18: 'Em tudo, dai graças. Pois essa é a vontade de Deus, em Cristo Jesus, para convosco.',
        19: 'Não apagueis o Espírito.',
        20: 'Não desprezeis as profecias.',
        21: 'Examinai todas as coisas; retende o que é bom.',
        22: 'Afastai-vos de toda forma de mal.',
        23: 'Que o próprio Deus da paz vos santifique completamente. Que todo seu espírito, alma e corpo sejam preservados irrepreensíveis para a vinda do nosso Senhor Jesus Cristo.',
        24: 'Quem vos chamou é Fiel, e Ele também o fará.',
        25: 'Irmãos, orai também por nós.',
        26: 'Cumprimentai todos os irmãos com um beijo santo.',
        27: 'Eu lhes suplico, pelo Senhor, que esta carta seja lida para todos os irmãos.',
        28: 'Que a graça de nosso Senhor Jesus Cristo esteja convosco.',
    },
}
