NAME = 'NorSMB: Studentmållagsbibelen frå 1921'
BOOK = 'Job'

CHAPTERS = {
    1: {
        1: 'I landet Us budde det ein gong ein mann som heitte Job. Det var ein ærleg og rettvis mann som ottast Gud og heldt seg frå det som vondt var.',
        2: 'Han fekk sju søner og tri døtter,',
        3: 'og han åtte sju tusund sauer, tri tusund kamelar, fem hundrad par uksar og fem hundrad asnor, og dertil ei stor mengd tenarar, so han var den megtigaste av alle austerlendingarne.',
        4: 'Sønerne hans hadde for skikk å halda gilde kvar sin dag heime hjå seg; og dei sende bod og bad dei tri systerne sine, at dei og skulde eta og drikka i lag med deim.',
        5: 'Når so ein umgang med gjestebodsdagar var til endes, sende Job bod etter deim og helga deim tidleg um morgonen ofra han brennoffer, eitt for kvar einskild av deim. For Job tenkte: «Kanskje hev sønerne mine synda og banna Gud i hjarto sine.» Soleis gjorde Job kvar gong.',
        6: 'Men so hende det ein dag at gudssønerne kom og stelte seg fram for Herren; og millom deim var og Satan.',
        7: 'Herren spurde Satan: «Kvar kjem du ifrå?» «Eg hev fare og svive ikring på jordi,» svara Satan.',
        8: 'Då spurde Herren Satan: «Hev du gjeve ans på Job, tenaren min? For liken hans finst ikkje på jordi, slik ein ærleg og rettvis mann som han er, og so som han ottast Gud og held seg frå det som vondt er.»',
        9: 'Men Satan svara Herren: «Skal tru Job ottast Gud for ingen ting?',
        10: 'Du hev då verna um honom og huset hans og alt han eig! Alt hans yrke hev du signa, og buskaparne hans hev breider seg ut i landet.',
        11: 'Men rett ut handi di og rør ved alt det han eig - då skal han so visst banna deg upp i andlitet!»',
        12: 'Då sagde Herren til Satan: «Alt det han eig, er i di magt; men honom sjølv må du ikkje leggja hand på.» So gjekk Satan burt frå Herren.',
        13: 'Ein dag sønerne og døtterne hans heldt måltid og drakk vin i huset hjå den eldste broren,',
        14: 'kom det ein til Job og sagde: «Medan uksarne gjekk for plogen og asnorne beitte ved sida av,',
        15: 'so kom sabæarane og tok deim og hogg ned drengjerne med sverd; berre eg slapp undan, so eg kunde melda det til deg.»',
        16: 'Medan han tala, kom ein annan og sagde: «Guds eld slo ned frå himmelen millom småfeet og hyrdingarne og brende deim upp; berre eg slapp undan, so eg kunde melda det til deg.',
        17: 'Medan han tala, kom den tridje og sagde: «Kaldæarane kom i tri fylkingar og kasta seg yver kamelarne og rana deim; sveinarne hogg dei ned med sverd; berre eg slapp undan, so eg kunde melda det til deg.»',
        18: 'Medan han tala, kom den fjorde og sagde: Medan sønerne og døtterne dine åt og drakk heime hjå den eldste broren;',
        19: 'so kom det ein sterk storm burtanfrå øydemarki og tok fat i alle fire hyrno på huset, so det seig i hop yver ungdomarne og slo deim i hel; berre eg slapp undan, so eg kunde melda det til deg.»',
        20: 'Då stod Job upp og reiv kappa si sund og klypte håret av hovudet og kasta seg å gruve og tilbad',
        21: 'og sagde: «Naken kom eg or moderliv; naken fer eg attende. Herren gav, og Herren tok; Herrens namn vere lova!»',
        22: 'Tråss i alt dette synda ikkje Job, og klaga ikkje på Gud.',
    },
    2: {
        1: 'So hende det ein dag, at gudssønerne kom og stelte seg fram for Herren att, og Satan var millom deim og stelte seg fram for Herren.',
        2: 'Og Herren spurde Satan: «Kvar kjem du ifrå?» «Eg hev fare og svive ikring på jordi,» svara Satan.',
        3: 'Då spurde Herren honom: «Hev du gjeve ans på Job, tenaren min? For liken hans finst ikkje på jordi, slik ein ærleg og rettvis ein mann som han er, og so som han ottast Gud og held seg frå det som vondt er. Han er endå like ærleg, so du hev eggja meg upp til å tyna honom utan grunn.»',
        4: 'Då sagde Satan til Herren: «Hud for hud; ein mann gjev gjerne alt han eig når han berre bergar livet.',
        5: 'Men rett ut handi di og rør ved beini og holdet hans - han skal so visst banna deg upp i andlitet.»',
        6: 'Då sagde Herren til Satan: «Han er i di magt; men spar livet hans!»',
        7: 'So gjekk Satan burt frå Herren; og han slo Job med vonde svullar frå hovud til hæl;',
        8: 'og han tok seg eit skålbrot og skrapa seg med der han sat i oskedungen.',
        9: 'Då sagde kona hans til honom: «Er du endå ulasteleg? Banna Gud, so du kann få døy!»',
        10: 'Men han svara henne: «Du talar som ei fåvis kvinna. Me tek imot av Gud det gode, skal me’kje taka og det vonde?» Tråss i alt dette synda ikkje Job med lipporne sine.',
        11: 'Tri vener til Job fekk høyra um den ulukka som hadde kome yver honom; dei kom kvar frå sin heimstad, Elifaz frå Teman, Bildad frå Suah, og Sofar frå Na’ama, og dei avtala seg imillom at dei skulde ganga til honom for å syna honom samhug og trøysta honom.',
        12: 'Men alt på langt fråstand såg dei at han var heilt ukjenneleg; og dei sette i og gret og reiv sund kapporne sine og kasta mold yver hovudi upp i lufti.',
        13: 'Og dei sat hjå honom på jordi i sju dagar og sju næter; og ingen av deim sagde eit ord til honom, for dei såg at han pintest hardt.',
    },
    3: {
        1: 'Då let Job upp munnen og banna fødedagen sin.',
        2: 'Job tok til ords og sagde:',
        3: '«Burt med den dag då eg vart fødd, den natt som sa: «Ein svein er avla!»',
        4: 'Må denne dag til myrker verta - burtgløymd av Gud i høge himmel - og inkje ljos på honom skina!',
        5: 'Lat svarte myrkret honom eiga og skyer seg kring honom samla! Dagmyrkjingar skal honom skræma',
        6: 'og myrkret gløypa denne natt! Burt med den natt frå årsens dagar, ho kome ei i månads tal!',
        7: 'Ja, aud og tom skal natti verta og ingen fagnad i ho klinga;',
        8: 'Dagbannarar skal henne banna, dei som kann mana upp Livjatan,',
        9: 'Og morgonstjernor skal’kje skina; fåfengt ho venta skal på ljoset - augbrunerne av morgonroden -',
        10: 'av di ho ei livsdøri stengde på mor mi, so eg slapp for kval.',
        11: 'Kvi døydd’ eg ei i moders liv? Ell’ slokna då eg rett var fødd?',
        12: 'Kvi fanst det kne som mot meg tok; og brjost eg kunde suga ved?',
        13: 'So låg eg still og kvilde no, eg sov og hadde ro og fred',
        14: 'hjå kongar og hjå fyrstar, som til gravstad pyramider bygde,',
        15: 'hjå hovdingar som åtte gull og fyllte sine hus med sylv;',
        16: 'ell’ ufødd var eg ikkje til, lik born som aldri ljoset såg.',
        17: 'Der rasar ei dei vonde meir; der kviler dei som trøytte er;',
        18: 'og fangarne er trygge der; dei høyrer ingen drivar meir.',
        19: 'Der stor og liten like er, og trælen fri for herren sin.',
        20: 'Kvi gjev han ljos til den som lid, og liv til deim som gremmer seg,',
        21: 'som fåfengt stundar etter dauden, og søkjer han som løynde skatt,',
        22: 'som gled seg, ja, som jublar høgt, og fegnast når dei finn ei grav -',
        23: 'til mannen som ei finn sin veg, som Gud set fast og stengjer inne?',
        24: 'Min sukk hev vorte daglegt brød, og klaga mi som vatnet strøymar.',
        25: 'Meg råkar det eg ottast fyre; det som eg ræddast, hender meg.',
        26: 'Snaudt fær eg fred, snaudt fær eg ro, snaudt lindring - so kjem uro att.»',
    },
    4: {
        1: 'Då tok Elifaz frå Teman til ords og sagde:',
        2: '«Vert du vel tykkjen um eg talar? Men kven kann halda ordi inne?',
        3: 'På rette veg du førde mange; dei trøytte hender styrkte du;',
        4: 'med ord du hjelpte deim som snåva, og gav dei veike knei kraft.',
        5: 'Men når det gjeld deg sjølv, du klagar; når deg det råkar, ræddast du!',
        6: 'Di von du på di gudstru bygde og sette lit til last-laust liv.',
        7: 'Tenk etter: Når vart skuldlaus tynt? Når gjekk rettvis mann til grunns?',
        8: 'Stødt fann eg: dei som urett pløgde, og sådde naud, dei hausta slikt;',
        9: 'dei stupte for Guds andedrag, gjekk for hans vreidestorm til grunns.',
        10: 'Ja, løva skrik, og villdyr burar; ungløva fær sin tanngard knekt;',
        11: 'og løva døyr av skort på rov; løvinna misser sine ungar.',
        12: 'Ein løynleg tale til meg kom; i øyra mitt det stilt vart kviskra,',
        13: 'som tankar i eit nattsyn kjem, når svevnen tung på folki kviler.',
        14: 'Det kom ei rædsla yver meg, ei skjelving gjenom alle lemer;',
        15: 'ein gust meg yver panna strauk, og på min kropp seg håri reiste;',
        16: 'og noko stogga for mi åsyn; eg kunde ikkje klårt skilja; framfor mitt auga stod eit bilæt’, eg høyrde som ei røyst som kviskra:',
        17: '«Hev menneskjet vel rett for Gud? Er mannen rein framfor sin skapar?',
        18: 'Han sine tenarar ei trur og finn hjå sine englar lyte -',
        19: 'enn meir hjå folk i hus av leir; hjå deim som hev sin grunn i moldi, ein kann deim krasa, som eit mol.',
        20: 'Dei er frå morgon og til kveld; ein krasar deim - kven merkar det? - Og dei vert ikkje funne meir.',
        21: 'Når deira tjeldsnor vert rykt upp, dei døyr og ingen visdom fær.»',
    },
    5: {
        1: 'Rop berre du; kven svarar deg? Kva engel vil du beda til?',
        2: 'Mismod slær fåvis mann i hel og brennhug den som lite veit.',
        3: 'Eg såg ein dåre festa rot, og brått eg laut hans bustad banna.',
        4: 'Hans søner hjelpelaus var, uhjelpte trakka ned i porten.',
        5: 'Hans avling åt dei svoltne upp, dei tok ho tråss i klungergjerde, og snara lurde på hans gods.',
        6: 'Men naudi ei frå dusti kjem; ulukka ei or jordi renn;',
        7: 'nei, mannen vert til møda fødd, som gneistarne lyt fljuga høgt.',
        8: 'Eg vilde venda meg til Gud og leggja saki fram for honom,',
        9: 'som storverk gjer som ei me skynar, fleir’ underverk enn me kann telja,',
        10: 'som sender regnet ned på jord og vatnet yver mark og eng,',
        11: 'som lyfter låg og liten upp og hjelper syrgjande til frelsa,',
        12: 'som spiller planen for dei sløge, so deira hender inkje duger,',
        13: 'som fangar vismann i hans vit, so listig råd forrenner seg.',
        14: 'Um dagen støyter dei på myrker, trivlar ved middag som ved natt.',
        15: 'Frå sverd frelser han frelser fatigmann, frå deira munn, frå yvervald,',
        16: 'so vesalmann fær hava von, men vondskap lata munnen att.',
        17: 'Men sæl den mann som Gud mun refsa; vanvyrd ei tukt frå Allvalds-Gud!',
        18: 'Han sårar, men bind og umkring; han slær men lækjer med si hand.',
        19: 'Seks trengslor bergar han deg or, i sju skal inkje vondt deg nå.',
        20: 'I hunger fri’r han deg frå dauden, i krig du undan sverdet slepp;',
        21: 'for tungesvipa er du berga, og trygg du er i tap og tjon;',
        22: 'du lær åt tjon og hungersnaud og ottast ikkje ville dyr;',
        23: 'du samband hev med stein på marki, og fred med villdyr uti heidi.',
        24: 'Du merkar at ditt tjeld hev fred, og inkje vantar i ditt hus.',
        25: 'Du ser, ditt sæde tallrikt er, ditt avkom rikt som gras på eng.',
        26: 'I mannskraft til di grav du gjeng, lik korn, køyrt inn i rette tid.',
        27: 'Det hev me granska; so det er; so høyr og merka deg det då!»',
    },
    6: {
        1: 'Då tok Job til ords og svara:',
        2: '«Um dei mitt mismod vega vilde og få ulukka mi på vegti,',
        3: 'det tyngjer meir enn havsens sand; difor var ordi mine ville.',
        4: 'For Allvalds pilar sit i meg, mi ånd lyt suga deira gift; Guds rædslor reiser seg til åtak.',
        5: 'Skrik asnet vel i grøne eng? Og rautar uksen ved sitt for?',
        6: 'Kven et det smerne utan salt? Kven finn vel smak i eggjekvite?',
        7: 'Det byd meg mot å røra slikt, det er som min utskjemde mat.',
        8: 'Å, fekk eg uppfyllt bøni mi! Gav Gud meg det eg vonar på!',
        9: 'Ja, vild’ han berre knusa meg, med hand si min livstråd slita!',
        10: 'Då hadde endå eg mi trøyst; trass pina skulde glad eg hoppa! - Den Heilage sitt ord eg held på.',
        11: 'Kva er mi kraft, at eg skuld’ vona? Mi framtid, at eg skulde tola?',
        12: 'Er krafti mi som steinen sterk? Er kanskje kroppen min av kopar?',
        13: 'Mi hjelp hev heilt forlate meg; all kvart stydjepunkt er frå meg teke.',
        14: 'Ein rådlaus treng av venen kjærleik, um enn han ottast Allvald ei.',
        15: 'Som bekken brørne mine sveik, lik bekkjefar som turkar ut.',
        16: 'Fyrst gruggast dei av bråna is, og snø som blandar seg uti,',
        17: 'men minkar so i sumarsoli, og kverv til slutt burt i sumarhiten.',
        18: 'Vegfarande vik av til deim, men kjem til øydemark og døyr.',
        19: 'Kjøpmenn frå Tema skoda dit, flokkar frå Saba vonar trygt;',
        20: 'men svikne vert dei i si von; dei narra vert når dei kjem fram.',
        21: 'So hev de vorte reint til inkjes, de rædsla såg, og rædde vart!',
        22: 'Hev eg då bede dykk um noko? Bad eg dykk løysa meg med gods?',
        23: 'og frelsa meg frå fiendvald og kjøpa meg frå røvarar?',
        24: 'Gjev meg eit svar, so skal eg tegja; seg meg kva eg hev synda med!',
        25: 'Eit rettvis ord er lækjebot; men last frå dykk er inkje verdt.',
        26: 'Du lastar meg for ordi mine; men vonlaus mann so mangt kann segja.',
        27: 'De kastar lut um farlaust barn, og handel driv um dykkar ven.',
        28: 'Vilde de berre sjå på meg! Trur de eg lyg dykk upp i augo?',
        29: 'Vend um, lat ikkje urett skje! Vend um, enn hev eg rett i dette.',
        30: 'Finst det vel fals på tunga mi? Kann ei min gom ulukka smaka?',
    },
    7: {
        1: 'Ja, mannen hev ein strid på jordi; hans dagar gjeng som leigedagar.',
        2: 'Som trælen lengtar etter skugge, og leigekar på løni ventar,',
        3: 'so fekk eg månader av vonbrot og næter fulle utav møda.',
        4: 'Eg segjer når eg gjeng til kvile: «Når skal eg atter standa upp?» Og kvelden vert so lang, so lang: Eg ligg uroleg alt til dagsprett.',
        5: 'Og makk og sår min likam dekkjer, og hudi skorpnar og bryt upp att.',
        6: 'Mi tid fer snøggar’ enn ein skutel, og ho kverv utan nokor von.',
        7: 'Hugs på: mitt liv er som ein pust; mitt auga ser’kje lukka meir.',
        8: 'Snart er eg løynd for alle augo; du fåfengt stirer etter meg.',
        9: 'Som skyi framum fer og kverv, so ingen att frå helheim vender,',
        10: 'snur ei attende til sitt hus; hans heimstad kjenner han’kje meir.',
        11: 'Difor vil’kje munnen stagga, men tala i min djupe hugverk og klaga i mi sjælenaud.',
        12: 'Er eg eit hav, er eg ein drake, med di du vaktar so på meg?',
        13: 'Eg tenkjer: «Lægjet skal meg lindra, og sengi letta suti mi» -',
        14: 'då skræmer du meg upp med draumar, og støkkjer meg med ville syner,',
        15: 'so at eg heller ville kjøvast, ja døy, enn vera slik ei beingrind.',
        16: 'D’er nok! Eg liver ikkje æveleg; Haldt upp! Mitt liv er som ein pust.',
        17: 'Kva er ein mann, at du han vyrder og retter tanken din på honom,',
        18: 'heimsøkjer honom kvar ein morgon, ransakar honom kvar ei stund?',
        19: 'Når tek du frå meg auga ditt? Meg slepper med eg svelgjar råken?',
        20: 'Hev eg gjort synd, kva gjer eg deg, du som på mannen vaktar stødt? Kvi hev du meg til skiva valt? So eg hev vorte meg ei byrd?',
        21: 'Kvi gjev du ikkje syndi til? Kvi ansar du på mine brot? No sig eg snart i moldi ned; og leitar du, so er eg burte.»',
    },
    8: {
        1: 'Då tok Bildad frå Suah til ords og sagde:',
        2: '«Kor lenge vil du tala so og lata ordi storma fram?',
        3: 'Kann Gud vel rengja det som rett er? Kann Allvalds-Gud vel rengja rettferd?',
        4: 'Hev dine søner synda mot han, gav han deim deira synd i vald.',
        5: 'Um du søkja til din Gud, og beda Allvalds-Gud um nåde,',
        6: 'er du då rein og utan svik, då vil han vakna upp for deg og reisa nytt ditt rettferdshus,',
        7: 'Um og di fortid vesall var, so mykje større vert di framtid.',
        8: 'Ja, spør deg for hjå farne ætter, agt på kva federne fann ut.',
        9: '- Me inkje veit, er frå i går; vårt liv ein skugge er på jordi -',
        10: 'dei skal deg læra, gjeva svar med ord ifrå sitt hjartedjup:',
        11: '«Veks sevet vel på turre land? Trivst storren der som vatnet vantar?',
        12: 'Enn stend det grønt, vert ikkje skore, då visnar det fyrr anna gras.»',
        13: 'So gjeng det deim som gløymer Gud; og voni glepp for gudlaus mann.',
        14: 'Hans tillit sunderskori vert, hans tiltru vert til kongurvev;',
        15: 'Det hus han styd seg til, det dett; det som han triv til, stend’kje fast.',
        16: 'Han saftfull veks, med soli skin; hans greiner yver hagen heng,',
        17: 'og roti kring steinrøysar smett, og smyg seg inn imillom steinar.',
        18: 'Men vert han riven frå sin stad, so hugsar staden han ei meir.',
        19: 'Sjå det er gleda på hans veg; or moldi skyt ein annan fram.',
        20: 'Men Gud vanvyrder ei den reine; dei vonde tek han ei i handi.',
        21: 'Han enn din munn med lått skal fylla og lipporne med gledesong;',
        22: 'men skammi klæda skal din fiend’; gudløysetjeld finst ikkje meir.»',
    },
    9: {
        1: 'Då tok Job til ords og sagde:',
        2: '«Eg veit for visst at det er so; kva rett fær mannen imot Gud?',
        3: 'Um han med honom vilde trætta, han kann’kje svara eitt til tusund.',
        4: 'Vis som han er og sterk i velde - kven kann vel strafflaust tråssa honom,',
        5: 'som fjelli flyt, dei veit’kje av det, og velter deim upp i harm,',
        6: 'som ruggar jordi frå sin plass, so pilarne hennar skjelv,',
        7: 'som soli byd so ho ei skin, og set eit segl for stjernorne,',
        8: 'som eine spanar himmeln ut og fram på havsens toppar skrid,',
        9: 'hev skapt Karlsvogni og Orion, Sjustjerna og Sørkamri med?',
        10: 'Som storverk gjer, me ei kann fata, og underverk forutan tal?',
        11: 'Han framum gjeng, eg ser han ikkje; um burt han glid, eg går han ikkje.',
        12: 'Når han tek fat, kven stoggar honom? Kven honom spør: «Kva gjer du der?»',
        13: 'Gud stoggar ikkje vreiden sin; for han seg bøygde Rahabs-fylgjet.',
        14: 'Kor kann vel eg då svara han? Kor skal for han eg ordi leggja?',
        15: 'Um eg hev rett, eg kann’kje svara, men lyt min domar be um nåde.',
        16: 'Og um han svara når eg ropa, eg trudde ei mi røyst han høyrde.',
        17: 'Han som i stormver reiv meg burt og auka grunnlaust såri mine,',
        18: 'han let meg ikkje anda fritt, men metta meg med beiske ting.',
        19: 'Når magt det gjeld, då er han der; men gjeld det rett: kven stemnar honom?',
        20: 'Um eg hev rett, min munn meg dømer; er skuldlaus, han meg domfeller.',
        21: 'Skuldlaus eg er! eg skyner ei meg sjølv, vanvyrder livet mitt.',
        22: 'Det er det same, no eg segjer: Han tyner skuldig og uskuldig.',
        23: 'Når svipa brått gjev ulivssår, med lått han ser den gode lida.',
        24: 'Han jordi gav i nidings hand; på domarar han syni kverver. Er det’kje han, kven er det då?',
        25: 'Mitt liv fer snøggare enn lauparen, dei kverv, men lukka såg det aldri;',
        26: 'Det glid som båtar utav sev, lik ørn som ned på fengdi slær.',
        27: 'Når eg mi plåga gløyma vil og jamna panna mi og smila,',
        28: 'då gruvar eg for pina mi; eg veit du ei frikjenner meg.',
        29: 'For når eg lyt straffskuldig vera, kvifor skal eg då fåfengt stræva?',
        30: 'Um eg i snø meg vilde tvætta og reinsa henderne med lut.',
        31: 'Du ned i grefti straks meg dukka, so mine klæde ved meg stygdest.',
        32: 'Han ikkje er ein mann som eg, kann ei med meg til retten gå;',
        33: 'd’er ingen skilsmann millom oss som handi si kann på oss leggja.',
        34: 'Når berre han tok riset frå meg og ikkje skræmde meg med rædsla,',
        35: 'eg skulde tala utan otte; sjølv dømer eg meg annarleis.',
    },
    10: {
        1: 'Mi sjæl er leid av livet mitt, eg gjev mi klaga lause taumar, vil tala i min såre hugverk.',
        2: 'Til Gud eg segjer: «Døm meg ikkje; seg kvifor du imot meg strider!',
        3: 'Finn du det godt å gjera vald, og øyda upp ditt eige verk, men lysa yver gudlaust råd?',
        4: 'Er auga ditt av kjøt og blod? Ser du som menneskje plar sjå?',
        5: 'Er dine dagar mennesk-dagar? Er dine år lik mannsens år?',
        6: 'Med di mitt brot du leitar upp, og granskar etter syndi mi,',
        7: 'endå du veit eg er uskuldig, og ingen bergar or di hand.',
        8: 'Di hand hev skapt og dana meg fullt ut, og no vil du meg tyna?',
        9: 'Hugs på, du forma meg som leir; no gjer du atter meg til mold!',
        10: 'Som mjølk du let meg renna ut og let meg stivna liksom ost;',
        11: 'Du klædde meg med hud og kjøt, fleitta bein og senar saman.',
        12: 'Du gav meg både liv og miskunn, og verna um mitt andedrag.',
        13: 'Men dette du i hjarta gøymde, eg veit det var i din tanke;',
        14: 'Du vakta på meg um eg synda; du gav meg ikkje til mitt brot;',
        15: 'um eg var skuldig, usæl eg! Um skuldfri, tord’ eg ei meg briska, av skjemsla mett, med naud for augom;',
        16: 'For då du jaga meg som løva og let meg atter under sjå,',
        17: 'du førde nye vitne mot meg og harmast endå meir på meg og sende mot meg her på her.',
        18: 'Kvi drog du meg or morsliv fram? Kvi fekk eg ikkje usedd døy,',
        19: 'lik ein som aldri til hev vore, og vart i grav frå morsliv lagt?',
        20: 'Er ikkje mine dagar få? Haldt upp! Slepp meg, so eg litt glad kann verta,',
        21: 'fyrr eg gjeng burt, og kjem’kje att, til myrkre land med daudeskugge,',
        22: 'eit land so myrkt som svarte natti, med daudeskugge og vanskipnad, der dagsljoset er som myrke natt!»»',
    },
    11: {
        1: 'Då tok Sofar frå Na’ama til ords og sagde:',
        2: '«Skal slik ei svalling ei få svar? Skal slik ein storpratar få rett?',
        3: 'Skal menner for din ordflaum tegja? Skal du få spotta utan skjemsla?',
        4: 'Du segjer: «Rein er læra mi, eg skuldfri er i dine augo.»',
        5: 'Men dersom berre Gud vil tala og opna munnen sin mot deg,',
        6: 'og syna deg sin løynde visdom, kor han eig vit i dobbelt mål! Då skulde du nok skyna at Gud gjev deg noko til av syndi.',
        7: 'Skal tru Guds tankedjup du kjenner? Hev du nått fram til Allvalds grensa?',
        8: 'Høgar’ enn himmelen - kva gjer du? Djupar’ enn helheimen - kva veit du?',
        9: 'Lenger enn jordi strekkjer seg og breidare enn havet sjølv.',
        10: 'Når han skrid fram og legg i lekkjor, stemnar til doms, kven stoggar honom?',
        11: 'Han kjenner deim som talar lygn; han ser den falske utan leiting.',
        12: 'Det tome hovud fær forstand, og asenfolen vert til mann.',
        13: 'Men vil du bu ditt hjarta rett og henderne mot honom breida',
        14: 'og halda svik frå handa di og urett burte frå ditt tjeld,',
        15: 'då kann du lyt’laust hovud lyfta, då stend du fast og ræddast ikkje;',
        16: 'då kann du gløyma all di møda, liksom ei elv som framum rann.',
        17: 'Klårar’ enn dagen stend ditt liv, og myrkret vert til morgongråe;',
        18: 'då er du trygg, då hev du von, du ottelaus til kvile gjeng.',
        19: 'Du ligg, og ingen upp deg skræmer, og mange vil deg gjerne tekkjast.',
        20: 'Men augo veiknar på dei vonde; dei hev’kje nokor tilflugt meir, men ventar på å anda ut.»',
    },
    12: {
        1: 'Då svara Job og sagde:',
        2: '«Ja visst, de er dei rette folk, og visdomen døyr ut med dykk.',
        3: 'Men eg hev vit so vel som de; eg ei til atters stend for dykk; kven kjenner ikkje dette fyrr?',
        4: 'Til spott for venen min vert eg som bad til Gud og bønhøyrd vart. Til spott vert rettvis mann og ærleg.',
        5: 'Vanvyrd ulukka! tenkjer trygg mann, vanvyrdnad ventar deim som vinglar.',
        6: 'Valdsmenn bur roleg i sitt tjeld; trygge er dei som tergar Gud, dei som hev Gud i neven sin.',
        7: 'Spør bølingen, han skal deg læra, og fugl i luft, han segja skal,',
        8: 'og tal til jordi, ho skal læra, og fisk i hav, skal melda deg:',
        9: 'Kven skynar ei på alt i hop, at Herrens hand hev skapa det?',
        10: 'Kvar livand’ sjæl han hev i handi og åndi åt kvart menneskje.',
        11: 'Vert ordi ei med øyra prøvde, som du med gomen maten smakar?',
        12: 'Hjå folk med gråe hår er visdom, og vit hjå deim som liver lenge.',
        13: 'Hjå honom visdom er og kraft, hjå honom råd og dømekraft.',
        14: 'Når han riv ned, kven byggjer upp? Når han set fast, kven løyser ut?',
        15: 'Han stengjer vatnet, turkar det, slepper det, so det jordi øyder.',
        16: 'Hjå honom kraft og klokskap er; han eig båd’ vegvill og vill-leidar;',
        17: 'rådsherrar fører han som fangar, og domarar han gjer til dårar.',
        18: 'Han løyser konge-styring upp, legg reip kring livet på deim sjølve.',
        19: 'Han fører prestar plundra burt og øyder ut eld’-gamle ætter.',
        20: 'Han mælet tek frå øvde talar og vitet frå dei gamle menn,',
        21: 'og yver stormenn skam han øys og løyser beltet på dei sterke.',
        22: 'Han myrkret driv or holor ut og fører dimma fram i dagen.',
        23: 'Han aukar folk og tynar deim; han spreider folk og fører deim;',
        24: 'Han vitet tek frå jordheimsfyrstar og let veglaus heid deim vildra;',
        25: 'dei sviv i myrkret utan ljos, han let dei raga liksom drukne.',
    },
    13: {
        1: 'Ja, allting hev mitt auga set og øyra høyrde og forstod;',
        2: 'alt det de veit, det veit eg og; for dykk eg ei tilbake stend.',
        3: 'Men eg til Allvalds Gud vil tala, med Gud eg vil til retten ganga;',
        4: 'Men de vil dekkja til med lygn, er berre ugagnslækjarar.',
        5: 'Å, gjev de vilde tegja still, so kunde det for visdom gjelda.',
        6: 'Høyr på den skrapa eg vil gjeva, merk når mi lippa åtak gjer!',
        7: 'Vil de forsvara Gud med lygn? Vil de hans sak med urett verja?',
        8: 'Vil de for honom gjera mismun, og spela Guds sakførarar?',
        9: 'Gjeng det dykk vel, når han dykk prøver? Kann de han narra som eit mennesk’?',
        10: 'Han skal so visst dykk straffa strengt, um de slik mismunn gjer i løynd.',
        11: 'Med høgdi si han skræmar dykk, hans rædsla yver dykk skal falla.',
        12: 'Og dykkar kraft-ord vert til oska, og dykkar prov til blaute leir.',
        13: 'Teg stilt, lat meg tala ut, so fær det gå meg som det kann!',
        14: 'Kvi skuld’ eg ta mitt kjøt i tenner? Og halda livet mitt i handi?',
        15: 'Han drep meg, ei eg ventar anna, mi ferd for han lik’vel eg hævdar.',
        16: 'Men ogso det skal hjelpa meg; hjå han fær ingen urein møta.',
        17: 'So høyr då det eg segja vil; lat meg for dykkar øyro tala!',
        18: 'Eg saki hev til rettes lagt; eg skal få rett, det veit eg visst.',
        19: 'Kven er det som med meg kann strida? Eg skulde tegja stilt og døy.',
        20: 'Tvo ting må du spara meg for; då løyner eg meg ikkje for deg:',
        21: 'Di hand lyt burt frå meg du taka, lat ei di rædsla skræma meg!',
        22: 'Stemn meg so inn! eg stend til svars; eller eg talar og du svarar.',
        23: 'Kor mange brot og synder hev eg? Seg meg mi misgjerd og mi synd!',
        24: 'Kvifor vil du di åsyn løyna og for ein fiend’ halda meg?',
        25: 'Vil eit burtblåse blad du skræma? Forfylgja du eit visna strå? -',
        26: 'Når du idømer meg slik straff og let meg erva ungdoms synder',
        27: 'og legg i stokken mine føter, og vaktar alle mine vegar, slær krins um mine foteblad.',
        28: 'Og det mot ein som morkna er, lik klædeplagg som mol et upp.',
    },
    14: {
        1: 'Sjå - menneskjet, av kvinna født, det liver stutt, av uro mett.',
        2: 'Som blom det sprett og visnar burt, ja, lik ein skugge burt det fer.',
        3: 'Men du med honom auga held, og meg du dreg for domen din.',
        4: 'Skal tru det av ein urein kjem ein som er rein? Nei, ikkje ein!',
        5: 'Når dagetalet hans er sett, hans månads-tal sett fast hjå deg, når du for han ei grensa drog som ei han yverskrida kann,',
        6: 'so snu deg frå, lat han få fred og ha sin dag som leigekaren!',
        7: 'For treet er det endå von; um det vert det hogge, sprett det att, på renningar det vantar ikkje.',
        8: 'Når røterne i jordi eldest, og stomnen døyr i turre mold,',
        9: 'ved dåm av vatnet skyt det knupp, fær som ein stikling grøne greiner.',
        10: 'Men døyr ein mann, då ligg han der; han andast, og kvar er han då?',
        11: 'Som vatnet renn ut or ein sjø, som elvi minkar, turkast ut,',
        12: 'so ligg ein mann, ris ikkje upp; til himmeln kverv, dei vaknar ikkje; ein kann’kje vekkja deim or svevnen.',
        13: 'Å, gjev du gøymde meg i helheim, løynde meg, til din vreide gav seg, gav meg ein frest, og so meg hugsa!',
        14: 'Tru mannen døyr og livnar att? I all min strid eg skulde vona og venta til avløysing kom.',
        15: 'Eg skulde svara, når du ropa og lengta mot dine eige verk.',
        16: 'Men no du tel kvart stig eg tek og agtar vel på syndi mi;',
        17: 'mi synd er læst i pungen inn, og på mi skuld du gøymer vel!',
        18: 'Som fjellet fell og smuldrast burt, og berget frå sin stad vert flutt,',
        19: 'Som vatnet holar steinen ut, og flaumen skolar moldi burt, so tek du ifrå mannen voni',
        20: 'og tyngjer honom ned for alltid. Han fer av stad; med åsyn rengd du sender honom burt frå deg.',
        21: 'Han veit’kje um hans born vert heidra; han merkar ikkje um dei armast;',
        22: 'Hans eigen kropp hans liding valdar, og sjæli græt for eigi sorg.»',
    },
    15: {
        1: 'Då tok Elifaz frå Teman til ords og sagde:',
        2: '«Kjem svar i vind og ver frå vismann? Fyller han barmen sin med storm?',
        3: 'Vil han med ugangstale lasta? Med ord som nyttelause er?',
        4: 'Otten for Gud den bryt du ned og skjeplar andakt for Guds åsyn.',
        5: 'For syndi styrer munnen din; du talar som dei falske talar.',
        6: 'Din munn deg dømer, ikkje eg; og dine lippor vitnar mot deg.',
        7: 'Vart fyrst av menneskje du fødd? Vert fyre haugarne du avla?',
        8: 'Var du i Guds rådleggjing med? Og fekk du visdom til deg rana?',
        9: 'Kva veit du som me ikkje veit? Kva skynar du som me ei kjenner?',
        10: 'Gråhærd og gamling er hjå oss; han eldre er enn jamvel far din.',
        11: 'Er trøyst frå Gud det altfor ring? Vanvyrder du eit rolegt ord?',
        12: 'Kvi let du hugen eggja deg? Kvi let du auga rulla vilt?',
        13: 'For imot Gud din harm du snur og let or munnen ordi strøyma.',
        14: 'Kor kann vel mannen vera rein? Og kvinnefødde hava rett?',
        15: 'På sine heilage han lit ei; for honom er’kje himmeln rein,',
        16: 'langt mindre då ein styggeting, ein mann som urett drikk som med vatn.',
        17: 'Eg vil deg læra; høyr på meg! Det som eg såg, vil eg deg melda,',
        18: 'det som vismenner segja kann, og ei hev dult frå sine feder,',
        19: 'dei som åleine landet åtte, og ingen framand kom bland deim.',
        20: 'Den vonde stødt i uro liver, for valdsmann gøymt er fåe år.',
        21: 'I øyro rædsletonar ljomar; fyrr han veit av, kjem tynaren.',
        22: 'Han trur’kje han kann fly frå myrkret; han venta lyt det kvasse sverd.',
        23: 'Han leitar etter brød: Kvar er det? Han veit, ein myrk dag er for hand.',
        24: 'Naud, trengsla skræmer, tyngjer honom, liksom ein konge budd til strid.',
        25: 'For imot Gud han lyfte handi og våga tråssa Allvalds-Gud,',
        26: 'han storma fram med nakken lyft, med vern utav skjold-ryggjer sterke;',
        27: 'han dekte andlitet med feitt og gjorde sine lender feite.',
        28: 'Han budde i bannstøytte byar, i hus som ingen burde bu i, men til grushaugar etla var.',
        29: 'Han vart’kje rik, hans gods kverv burt, hans grøda luter ei mot jordi.',
        30: 'Han kann’kje koma undan myrkret. Hans greiner turkast burt i hiten, og han kjem burt ved hans munns ande.',
        31: 'Trur han på fåfengd, vert han narra, og berre fåfengd haustar han.',
        32: 'Fyrr dagen kjem, då vert det uppfyllt, hans palmegreiner grønkar ikkje.',
        33: 'Lik vinstokk misser han si druva, spiller sin blom som oljetreet.',
        34: 'Ein syndarflokk set ingi frukt, og elden øyder mute- tjeldi.',
        35: 'Dei avlar møda, føder tjon, og svik i fanget sitt dei nører.»',
    },
    16: {
        1: 'Då svara Job og sagde:',
        2: '«Eg hev høyrt nok av dette slag; d’er brysam trøyst de alle gjev.',
        3: 'Vert det’kje slutt på tome ord? Kva er det som til svar deg driv?',
        4: 'Eg skulde tala liksom de, i fall de var i staden min; eg sette ord i hop mot dykk, eg riste hovudet mot dykk;',
        5: 'eg skulde trøysta dykk med munnen og lindra dykk med lippemedynk.',
        6: 'Men tale lindrar ei min verk, og ikkje kverv han um eg tegjer.',
        7: 'Men no hev han meg trøytta ut, du hev øydt ut min heile huslyd.',
        8: 'Du klemde meg, til vitne vart det, mi liding reiste seg imot meg og vitna mot meg beint i syni.',
        9: 'Hans vreide reiv og elte meg; han gnistra tennerne imot meg; fiendar kveste augo på meg',
        10: 'og opna munnen sin imot meg og slo mi kinn med skjemdarslag og stima saman imot meg.',
        11: 'Til farkar Gud meg yverlet og kastar meg i brotsmenns vald.',
        12: 'Midt i min fred han skræmde meg, treiv meg i nakken, krasa meg, til skiva sette han meg upp.',
        13: 'Hans pilar svirrar kringum meg; bønlaust han kløyver mine nyro, mitt gall han tømer ut på jordi.',
        14: 'Han bryt meg sund med brot på brot og stormar mot meg som ei kjempa.',
        15: 'Sekk hev eg sytt um hudi mi og stukke hornet mitt i moldi.',
        16: 'Raudt er mitt andlit utav gråt, og myrkret tyngjer augneloki,',
        17: 'endå mi hand er rein for vald, og bøni mi er fri for svik.',
        18: 'Løyn ikkje blodet mitt, du jord! Legg ikkje klaga mi til kvile!',
        19: 'Alt no mitt vitne er i himmeln, min målsmann i det høge bur.',
        20: 'Når mine vener spottar meg; til Gud eg tårut auga vender.',
        21: 'Han døme millom Gud og mann og millom mannen og hans ven.',
        22: 'Og ikkje mange år det vert fyrr eg gjeng burt og kjem’kje att.',
    },
    17: {
        1: 'Mi ånd er knekt, mitt liv er sløkt, no hev eg berre gravi att.',
        2: 'Eg hæding finn på kvar ein kant, ved deira tråss lyt auga dvelja.',
        3: 'Å, set eit pant for meg hjå deg! Kven elles skal meg handslag gjeva?',
        4: 'Du stengde deira sjæl for skyn; difor vil du ikkje lyfta deim.',
        5: 'Den som gjev vener burt til plundring, hans søner sloknar augo på.',
        6: 'Eg er for folk til ordtak sett, som ein dei sputtar beint i syni.',
        7: 'Mitt auga sjukt av sorger er, og mine lemer er ein skugge.',
        8: 'Dei rettvise støkk yver slikt, og skuldfri harmast på ugudleg.',
        9: 'Men rettvis mann sin veg gjeng fram, og magti veks hjå reinhendt mann.',
        10: 'Men de - kom berre alle att! Eg ingen vismann finn hjå dykk.',
        11: 'Og mine dagar dei kvarv burt; og mine planar slitna sund, dei som mitt hjarta emna på.',
        12: 'Men dei gjer natti um til dag, som ljos var næmare enn myrkrer.',
        13: 'Eit hus i helheim er mi von, i myrkret reider eg mi seng.',
        14: 'Til gravi ropar eg: «Min far!» til makken: «Mor mi! Syster mi!»',
        15: 'Kvar vert det då av voni mi? Mi von, kven augnar henne då?',
        16: 'Til helheims bommar fer ho ned, når eg til kvile gjeng i moldi.»',
    },
    18: {
        1: 'Då tok Bildad frå Suah til ords og sagde:',
        2: '«Kor lenge driv de jagt på ord? Gjev gaum, lat oss so talast ved!',
        3: 'Kvi skal me reknast liksom fe, som ureine i dykkar augo?',
        4: 'Å, du som riv deg sund i sinne, skal jordi øydast for di skuld? Skal fjellet flytjast frå sin stad?',
        5: 'Men sløkt vert ljoset for den vonde, og hans åre-eld skal ikkje skina.',
        6: 'I tjeldet hans vert ljoset myrkt, og lampa sloknar yver han.',
        7: 'Hans sterke stig vert snævra inn; han snåvar yver sine planar.',
        8: 'Hans fot vert fløkt i garnet inn, og upp i netet ferdast han;',
        9: 'og snara triv um hælen hans, og gildra tek på honom fat.',
        10: 'I jordi løynde gildror lurer, og fellor ventar på hans veg.',
        11: 'Og rædslor trugar rundt ikring og skræmer han for kvart eit stig.',
        12: 'Ulukka hungrar etter han, og vondt vil føra han til fall,',
        13: 'vil eta kvar ein led og lem, ja, det vil daudens eldste son.',
        14: 'Hans trygd er rivi frå hans tjeld; du sender han til rædsle-kongen.',
        15: 'I huset hans bur framande, det vert strått svåvel på hans bustad.',
        16: 'Hans rot i grunnen turkar ut; den høge kruna visnar burt.',
        17: 'Hans minne kverv frå jordi burt, og namnlaus vert han vidt og breidt.',
        18: 'Frå ljos til myrker driv dei honom og jagar han frå landi burt.',
        19: 'Han barnlaus vert i eige folk; i heimen hans slepp ingen undan.',
        20: 'Og vestmenn støkk for dagen hans, og austmenn vert av rædsla slegne.',
        21: 'Just soleis gjeng det nidings hus, den heim der ingen kjenner Gud.»',
    },
    19: {
        1: 'Då svara Job og sagde:',
        2: '«Kor lenge vil mi sjel de harma og krasa meg med dykkar ord?',
        3: 'Ti gonger hev de no meg spotta; de skjemmest ei å krenkja meg.',
        4: 'Hev eg i røyndi mistak gjort, dei mistak er mi eigi sak.',
        5: 'Vil de dykk briska imot meg, som um eg lid mi skam med rette?',
        6: 'Hugs på at Gud hev bøygt meg ned og spana kringum meg sitt garn.',
        7: 'Eg ropar: «Vald!» - men eg fær’kje svar; eg ropar: «Hjelp!» men fær’kje rett.',
        8: 'Han stengjer vegen for min fot, og myrker legg han på min stig.',
        9: 'Min heidersklædnad drog han av; han frå mitt hovud kransen tok.',
        10: 'Mi vern han braut, so eg gjekk under, mi von sleit han lik treet upp.',
        11: 'Hans vreide logar meg imot, og for ein fiend’ held han meg.',
        12: 'Hans skarar stemner fram mot meg; dei brøyter seg ein veg mot meg og lægrar seg kring tjeldet mitt.',
        13: 'Han dreiv ifrå meg mine frendar, og kjenningar vart framande.',
        14: 'Skyldfolki held seg burte frå meg, husvenerne hev gløymt meg burt.',
        15: 'For hjon og tenar er eg framand; dei held meg for ein ukjend mann.',
        16: 'Ei svarar drengen på mitt rop. Eg må med munnen tigga honom;',
        17: 'min ande byd imot for kona, eg tevjar ilt for mine sambrør.',
        18: 'Jamvel smågutar spottar meg, når eg stend upp, dei talar mot meg.',
        19: 'Dei styggjest for meg mine vener, og dei eg elska, snur seg mot meg.',
        20: 'Min kropp er berre skin og bein, snaudt hev eg endå tannkjøt att.',
        21: 'Hav medynk, medynk, mine vener! Gud hev meg råka med si hand.',
        22: 'Kvifor skal de som Gud meg jaga, og vert ei mette av mitt kjøt?',
        23: 'Å, gjev at mine ord vart skrivne, og i ei bok vart rita inn,',
        24: 'ja, vart med jarnmeitel og bly for ævleg tid i berget hogne!',
        25: 'Eg veit at min utløysar liver, til sist han yver moldi kjem.',
        26: 'Og når mi hud er øydelagd, ut frå mitt kjøt då ser eg Gud,',
        27: 'eg honom ser som venen min, mitt auga ser det, ingen framand! Å, nyro lengtar i mitt liv!',
        28: 'De segjer: «Me vil jaga honom!» - som um orsaki låg hjå meg!',
        29: 'Men de lyt agta dykk for sverdet; for vreide vert ved sverdet straffa. Og de skal vita: domen kjem.»',
    },
    20: {
        1: 'Då tok Sofar frå Na’ama til ords og sagde:',
        2: '«Difor gjev mine tankar svar, og difor stormar det i meg.',
        3: 'Ei skamleg skrapa fær eg høyra, men kloke svar mi ånd gjev meg.',
        4: 'Veit du’kje at frå ævords tid, frå mannen fyrst på jord vart sett,',
        5: 'ugudlege hev stokkut jubel, vanheilage stuttvarug gleda?',
        6: 'Når modet hans til himmels stig, når hovudet mot sky han lyfter,',
        7: 'han evig gjeng til grunns som skarnet; «Kvar er han?» spør dei, honom såg.',
        8: 'Lik draumen glid han burt og kverv, vert jaga som ei nattesyn.',
        9: 'Han burte er for alle augo, hans stad veit ikkje til han meir.',
        10: 'Hans born lyt hjelpa fatigfolk; hans hender gjev hans gods attende.',
        11: 'Hans bein var full’ av ungdomskraft; men den i moldi ligg med honom.',
        12: 'Er i hans munn det vonde søtt, vil han det under tunga gøyma,',
        13: 'sparer han det og slepper ikkje, held han det under gomen fast,',
        14: 'so vert i kroppen maten hans til orme-eiter i hans buk.',
        15: 'Det gods han gløypte, spyr han ut; Gud driv det ut or magen hans.',
        16: 'Han orme-eiter i seg saug, og ødle-tunga honom drep.',
        17: 'Han fær visst ikkje skoda bekkjer, ei heller flaum av mjølk og honning.',
        18: 'Han rikdom vinn, men nyt han ikkje; han samlar gods, men vert’kje glad.',
        19: 'Han krasa småfolk, let deim liggja, han rana hus som han ei byggjer.',
        20: 'Han kjende ikkje ro inni seg, men med sin skatt han slepp’kje undan.',
        21: 'Hans hækna sparer ingen ting; og difor kverv hans lukka burt.',
        22: 'I all si ovnøgd lid han naud; kvar armings-hand kjem yver honom.',
        23: 'Og til å fylla buken hans han sender vreiden yver honom, let maten sin på honom regna.',
        24: 'Og um han frå jarnvåpen flyr, han såra vert frå koparbogen;',
        25: 'ut gjenom ryggen pili kjem, den blanke odd ut or hans gall, og dauderædslor fell på honom.',
        26: 'Alt myrker gøymt er åt hans skattar, ja, ukveikt eld et honom upp, og øyder all hans eigedom.',
        27: 'Himmelen ter hans brotsverk fram, og jordi reiser seg imot han.',
        28: 'Hans heime-forråd fer sin veg, renn burt på vreidedagen hans.',
        29: 'Slikt etlar Gud til gudlaus mann; det lovar Gud til arv åt honom.»',
    },
    21: {
        1: 'Då svara Job og sagde:',
        2: '«Å høyr då, høyr på mine ord! Gjev i minsto det til trøyst!',
        3: 'Lat meg få lov å tala ut, so kann du spotta etterpå.',
        4: 'Klagar eg vel på menneskje? Og hev eg ikkje grunn til harm?',
        5: 'Vend dykk til meg, og ottast so; legg handi so på dykkar munn.',
        6: 'Eg støkk, når eg det kjem i hug; ei bivring gjenom kroppen gjeng.',
        7: 'Kvifor fær dei gudlause liva, auka i magt som åri gjeng?',
        8: 'Dei ser si ætt stå fast ikring deim, dei hev sitt avkjøme for augo.',
        9: 'I fred stend husi deira trygge, Guds svipa råkar ikkje deim;',
        10: 'med heppa parast deira fe, og kyrne kastar aldri kalv.',
        11: 'Dei slepper borni ut som lamb, og gutarne i leiken hoppar;',
        12: 'Dei syng til trumma og til cither og frygdar seg ved fløyteljod.',
        13: 'I lukka liver dei si tid og fer so brått til helheim ned.',
        14: 'Til Gud dei segjer: «Haldt deg burte!» Me vil’kje kjenna dine vegar!',
        15: 'Kvi skal me tena den Allsterke? Kva gagnar det å be til honom?»',
        16: '«Dei hev’kje lukka si i handi» - Langt burt frå meg med gudlaus råd!',
        17: 'Når sloknar lampa for gudlause? Når kjem ulukka yver deim? Gjev han deim straff i vreidesmod?',
        18: 'Fer dei vel burt som strå for vind, lik agner som i stormen fyk?',
        19: '«Gud gøymer straffi til hans born.» Nei, sjølv skal mannen straffi kjenna!',
        20: 'Lat han få sjå sitt eige fall og drikka harm frå den Allsterke!',
        21: 'Kva bryr han seg vel um sitt hus, når månadstalet hans er fullt?',
        22: 'Vil nokon hjelpa Gud til kunnskap, han som er domar for dei høgste?',
        23: 'Den eine døyr på velmagts høgd, fullkomleg trygg og fredeleg;',
        24: 'hans fat er fulle utav mjølk, og i hans bein er mergen frisk;',
        25: 'den andre døyr so beisk i hug, hev ingenting av lukka smaka.',
        26: 'Dei båe vert i moldi lagde, og deira klednad makkar er.',
        27: 'Sjå kor eg kjennar dykkar tankar, og dykkar meinkrokar mot meg.',
        28: 'De spør: «Kvar er vel stormannshuset? Kvar er det tjeld der gudlause bur?»',
        29: 'Hev de’kje høyrt av ferdafolk - de trur vel det som dei fortel -:',
        30: '«Den vonde frå ulukka slepp; han berga vert på vreidedagen.',
        31: 'Kven lastar honom for hans ferd? Og straffar honom for hans gjerd?',
        32: 'Han vert til gravi båren burt, og ved hans gravhaug held dei vakt.',
        33: 'Søtt søv han under torv i dal, og i hans far all verdi fer, som tallause gjekk fyre honom.',
        34: 'Det trøystar meg med tome ord; av dykkar svar er sviket att.»',
    },
    22: {
        1: 'Då tok Elifaz frå Teman til ords og sagde:',
        2: '«Er mannen vel til gagn for Gud? Nei, vitug mann seg sjølv mun gagna.',
        3: 'Hev Allvald bate av di rettferd? Er det hans vinst, at rett du ferdast?',
        4: 'Er det din gudlegdom han refser, når han med deg held rettargang?',
        5: 'Hev ei din vondskap vore stor og dine syndar utan ende?',
        6: 'Grunnlaust du panta dine brøder; halvnakne drog du klædi av;',
        7: 'den trøytte gav du ikkje vatn, den svoltne negta du ditt brød.',
        8: 'Det er den sterke som eig landet, den stolte hev si bustad der.',
        9: 'Du jaga enkjor burt tomhendt’ burt, slo armen av på faderlause.',
        10: 'Difor ligg snaror kringum deg, og rædsla skræmer deg so brått.',
        11: 'Ell’ vert du ikkje myrkret var, den flaum som fossar yver deg?',
        12: 'Bur ikkje Gud i himmelhøgd, sjå øvste stjernor, høgt dei sit!',
        13: 'Du segjer so: «Kva veit vel Gud? Kann attum skyerne han døma?',
        14: 'For skyer dimmer augo hans; han hev sin gang på himmelkvelven.»',
        15: 'Seg, vil du fylgja fortids-vegen, den stig som illverksmenner gjekk?',
        16: 'Dei som i utid tekne vart - og deira grunn flaut burt i flaum -',
        17: 'som sagde til Gud: «Haldt du deg burte!» Kva skulde Allvald vel deim gjera?',
        18: 'Endå han signa deira hus - langt burt frå meg med gudlaus råd!',
        19: 'Rettvise folk det såg med gleda, og den skuldlause spotta deim:',
        20: '«Fiendarn’ våre gjekk til grunns! Sjå elden øydde det dei leivde!»',
        21: 'Vert ven med honom, og få fred! So skal og lukka timast deg.',
        22: 'Og tak so lærdom av hans munn, og legg deg ordi hans på hjarta!',
        23: 'Vend um til Allvald, då du byggjest og jagar syndi frå ditt tjeld.',
        24: 'Kast gullet ditt i moldi ned - Ofir-gull millom bekkjesteinar.',
        25: 'Allvald skal vera då ditt gull og haugar utav sylv for deg.',
        26: 'Då skal du frygda deg i Allvald, di åsyn lyfta upp til Gud.',
        27: 'Og når du ropar, vil han høyra, so du kann halda det du lovar.',
        28: 'Det du deg etlar, skal du vinna, og ljos skal skina på din veg.',
        29: 'Gjeng vegen ned, du ropar: «Upp!» Han hjelpar den bljug-øygde mann.',
        30: 'Ja, ikkje-skuldfri mann han bergar, frelst vert han ved di reine hand.»',
    },
    23: {
        1: 'Då svara Job og sagde:',
        2: '«Endå gjeld klaga mi for tråss, tungt legg eg handi på min sukk.',
        3: 'Berre eg kunde finna honom og koma til hans bustad fram!',
        4: 'Då la eg fram for han mi sak og fyllte munnen min med prov.',
        5: 'Då høyrde eg kva svar han gav, og merka det han sa til meg.',
        6: 'Vilde med magt han mot meg standa? Nei, lyda på meg vilde han.',
        7: 'Ein skuldfri stod då for han fram; for alltid slapp eg domar min.',
        8: 'Gjeng eg i aust, han er’kje der; mot vest, eg vert han ikkje var;',
        9: 'i nord han verkar, ei eg ser han, han snur mot sud, eg ser han ikkje.',
        10: 'For all den veg eg fer han kjenner; prøvde han meg, eg var som gull.',
        11: 'Min fot hev fylgt i faret hans; hans veg eg gjeng ubrigdeleg,',
        12: 'veik ei frå det hans lippa baud, meir enn mi lov eg lydde hans.',
        13: 'Men ein er han, kven hindrar honom? Det han hev hug til, gjer han og.',
        14: 'Han um min lagnad avgjerd tek, og hev med meg so mangt i emning.',
        15: 'Eg difor ræddast for hans åsyn, når eg det minnest, skjelv eg for han.',
        16: 'Ja, Gud hev brote ned mitt mod, og Allvald hev gjort meg fælen,',
        17: 'ei er det myrkret som meg tyner, og ei mi eigi myrke åsyn.',
    },
    24: {
        1: 'Kvi hev’kje Allvald tider set? Kvi ser hans vener ei hans dagar?',
        2: 'Dei fører deildesteinar burt, stel fe og sender det på beite,',
        3: 'tek asnet frå den faderlause; tek kui enkja eig i pant.',
        4: 'Driv fatigfolk frå vegen burt; alt landsens småfolk kryp i skjol;',
        5: 'Lik ville asen fer dei ut til øydemarki med sitt stræv; og veidefang på ville heid er maten borni deira fær.',
        6: 'Dei haustar mark ved nattetid, og gudlaus manns vinhage plundrar.',
        7: 'Um natti nakne, utan klæde, dei hev for kulden inkje dekkje.',
        8: 'Dei våte vert av regn på fjell, held seg i bergufs utan livd,',
        9: 'Ein farlaus lyt frå moderbarm ein armings klæde gjeng i pant.',
        10: 'Dei nakne gjeng og klædelause, i hunger dei på kornband dreg.',
        11: 'Dei kreistar olje innum murar, dei persar vin og tyrster lel.',
        12: 'Frå byen høyrest styn av menner, og gjenomstungne skrik um hjelp, men Gud ser ei slik meningsløysa.',
        13: 'Det finst og fiendar åt ljoset; dei kjenner ikkje ljossens vegar og held seg ei på ljossens stigar.',
        14: 'Ved dagsprett mordaren stend upp, slær arm og fatig mann i hel, um natti er han so som tjuven.',
        15: 'Horkaren spæjar etter skyming; han tenkjer: «Inkje auga ser meg.» Sitt andlit gøymer han med maska.',
        16: 'I myrkret bryt dei inn i hus, dei som ved dag seg inne stengjer dei seg inne; av ljoset vil dei ikkje vita.',
        17: 'Myrk natt er morgon for deim alle; for natteskræmslorne dei kjenner.',
        18: 'Snøgt fer han yver vatnet burt, bannstøytt vert jordi hans i landet; til vinberg gjeng han ikkje meir.',
        19: 'Som snøvatn kverv for turk og hite, so gløyper helheim deim som synda.',
        20: 'Av moderlivet gløymd han er, og makkar mettar seg på honom; det ingen er som minnest han; so brotsverk brest liksom eit tre.',
        21: 'Han plundra ho som ikkje fødde, som ufør var til barne-eign; mot enkja gjorde han’kje vel.',
        22: 'Men han styd valdsmann med si kraft, og dei fær atter standa upp som hadde mist all von um livet.',
        23: 'Han styd deim so dei liver trygt, hans augo vaktar deira vegar.',
        24: 'Høgt stig dei, brått - dei er’kje meir - dei sig og døyr som alle andre, vert skorne av som aks på strå.',
        25: 'Er det’kje so? Kven legg imot? Kven gjer no mine ord um inkje?»',
    },
    25: {
        1: 'Då tok Bildad frå Suah til ords og sagde:',
        2: '«Hjå honom magt og rædsla finst; han i sin himmel freden skaper.',
        3: 'Kven veit talet på hans herar? Kven yverstrålar ei hans ljos?',
        4: 'Kor kann ein mann ha rett mot Gud? Er vel ein kvinnefødd uskuldig?',
        5: 'Sjå, månen er’kje klår ein gong, og stjernon’ er’kje reine for han.',
        6: 'Enn mannen då, den vesle krypen? Menneskjebarnet, denne makk?»',
    },
    26: {
        1: 'Då svara Job og sagde:',
        2: 'Kvar helst hev du den veike hjelpt? Når studde du den trøytte arm?',
        3: 'Kvar gav du uklok mann ei råd? Kor ovleg visdom hev du synt?',
        4: 'Kven hev du bore melding til? Kva ånd hev tala gjenom deg?',
        5: 'Skuggarne i angest skjelva, vatsdjup og dei som deri bur.',
        6: 'Helheimen open ligg for honom, avgrunnen utan noko dekkje.',
        7: 'Nordheimen han i audni spana, og hengde jordi yver inkje.',
        8: 'Han vatnet inn i skyer bind; og skyi brest ei under det.',
        9: 'Kongsstolen sin han gøymer burt og breider skyer yver honom.',
        10: 'Kring vatni han ei grensa set, der som ljos og myrker byta skal.',
        11: 'Stolparne under himmelen skjelv, og rædde vert dei for hans trugsmål.',
        12: 'Han rører havet upp med velde, og med sit vit han krasar ubeist.',
        13: 'Og himmelen klårnar ved hans ande; hans hand den snøgge ormen drap.',
        14: 'Sjå her utkanten av hans veg; det berre kviskring er me høyrer. Kven skynar, når hans allmagt torar?',
    },
    27: {
        1: 'Job heldt fram med talen sin og sagde:',
        2: '«So sant Gud liver, som meg sveik, og Allvalds som meg volde sorg',
        3: '- for endå eg min ande dreg; i nosi mi er guddomspust -:',
        4: 'Urett ligg ei på mine lippor; mi tunga talar ikkje svik.',
        5: 'D’er langt frå meg å gje’ dykk rett, mi uskyld held eg fast til dauden.',
        6: 'Mi rettferd held eg fast uskjepla, eg ingen dag treng skjemmast ved.',
        7: 'Min fiend’ skal seg syna gudlaus, min motstandar som urettferdig.',
        8: 'Kva von hev en gudlaus att, når Gud vil sjæli or han draga?',
        9: 'Vil Gud vel høyra skriket hans, når trengsla bryt innyver honom?',
        10: 'Kann han i Allvald vel seg gleda? Kann han kvar tid påkalla Gud?',
        11: 'Eg um Guds hand vil læra dykk; kva Allvald vil, det dyl eg ikkje.',
        12: 'Sjå dette hev det alle set; kvi talar de då tome ord?',
        13: 'Den lut fær gudlause av Gud, den arven valdsmann fær av Allvald.',
        14: 'Til sverdet veks hans søner upp; hans avkom mettast ei med brød;',
        15: 'dei siste legst i grav ved pest, og enkjorne held ingi klaga.',
        16: 'Og um han dyngjer sylv som dust og samlar klæde liksom leir:',
        17: 'Den rettvise tek klædi på; skuldlause skifter sylvet hans.',
        18: 'Han byggjer huset sitt som molen, likt hytta vaktmannen set upp.',
        19: 'Rik legg han seg - men aldri meir; han opnar augo - og er burte.',
        20: 'Som vatsflaum rædsla honom tek, ved natt riv stormen honom burt.',
        21: 'Han driv av stad for austanvind, som blæs han frå hans heimstad burt.',
        22: 'Han utan miskunn på han skyt; frå handi hans han røma må.',
        23: 'Med hender klappar dei åt han og pip han frå hans heimstad burt.',
    },
    28: {
        1: 'Sylv hev sin stad, der dei det finn, og gullet, som dei reinsa vinn,',
        2: 'og jarn fram or jordi fær, og kopar ut or steinen bræ’r;',
        3: 'På natteskuggen gjer dei slutt og myrkheims steinar granskar ut.',
        4: 'Djupt under by med annsamt liv i gruvor bergmenn kliv og sviv.',
        5: 'På jordi brødkorn fram dei driv, men inni upp som eld dei riv.',
        6: 'Safiren sit i steinar der, og der seg og gullklumpar ter,',
        7: 'Ei ørnen kjenner denne veg, for haukesyn han løyner seg.',
        8: 'Ei stolte rovdyr vegen fann, og løva aldri gjeng på han.',
        9: 'På harde steinen dei handi legg; då sturtar mang ein bergevegg.',
        10: 'I berget seg gangar grev og skodar mang ein skatt so gjæv.',
        11: 'Dei dytter til for rennand’ å, det løynde fram for ljoset må.',
        12: 'Men visdomen, kvar er han å få? Og kvar skal ein vitet nå?',
        13: 'Slett ingen veit hans verd og vinst; i manneheim han ikkje finst;',
        14: 'Avgrunnen dyn: «Her ei han er!» Og havet segjer: «Ikkje her!»',
        15: 'Du kann’kje kjøpa han for gull, men sylv ei vega prisen full,',
        16: 'og ei for gull ifrå Ofir, ei for onyks, ei for safir.',
        17: 'Ei gull og glas er nok til kaup, og ei til byte fingull-staup.',
        18: 'Korall, krystall gjeld ikkje her. Visdom er meir enn perlor verd.',
        19: 'Topas frå Kus er altfor ring, ja, reinast gull vert ingen ting.',
        20: 'Visdomen, kvar kjem han ifrå? Og kvar skal ein til vitet nå?',
        21: 'Det ingen veit på denne jord; ei fugl det fann, kvar helst han for.',
        22: 'Avgrunn og daude segjer greidt: «Eit gjetord er alt det me veit.»',
        23: 'Men Gud han kjenner denne veg; han veit kvar visdom løyner seg.',
        24: 'Han skodar heilt til heimsens tram, og under himmeln ser han fram.',
        25: 'Då vinden han med vegti vog og sette mål for vatnet og,',
        26: 'då han gav regnet lovi si og ljomet veg å ganga i,',
        27: 'då såg han og synte fram og granska honom umhugsam.',
        28: 'Til menneskja han sagde so: «I Herrens otte visdom sit, og fly det vonde, det er vit.»»',
    },
    29: {
        1: 'Då heldt Job fram med talen sin og sagde:',
        2: '«Å, var eg som i fordums måna’r, som den gong Gud mi verja var,',
        3: 'då yver meg hans lampa skein, som lyste meg i myrkret fram,',
        4: 'slik som eg var i mogne manndom, då Gud var ven i huset mitt,',
        5: 'då Allvald endå med meg var, og mine born eg kring meg såg,',
        6: 'då eg i fløyte foten tvådde, og olje rann av fjellet nær meg,',
        7: 'då eg til porten steig i byen, og sessen min på torget tok!',
        8: 'Ungdomen såg meg, løynde seg; dei gamle reiste seg og stod;',
        9: 'hovdingar stogga midt i talen og lagde handi på sin munn;',
        10: 'og røysti tagna hjå dei gjæve, og tunga seg til gomen kleimde;',
        11: 'dei som meg høyrde, sælka meg, og dei som såg meg, vitna for meg.',
        12: 'Eg berga arming når han ropa, og farlaus som var utan hjelp;',
        13: 'velsigning fekk eg frå forkomne, og enkjor fekk eg til å jubla.',
        14: 'Rettferd var min, eg hennar bunad; rett var mi kappa og mi kruna.',
        15: 'Eg for den blinde auga var, og føter var eg for den halte.',
        16: 'Ein far eg var for fatigfolk; eg for ukjende saki granska.',
        17: 'På brotsmann tennerne eg knekte, reiv fengdi utor gapet hans.',
        18: 'Eg sagde: «I reiret skal eg døy, med dagar talrike som sand.',
        19: 'Til roti mi skal vatnet trengja, dogg bu ved natt på greini mi;',
        20: 'mi æra held seg frisk hjå meg, bogen vert ny handi mi.»',
        21: 'Dei høyrde ventande på meg, og lydde stilt på rådi mi.',
        22: 'Og ikkje la dei mot mitt ord, min tale draup ned yver deim.',
        23: 'På meg dei bia som på regn, ja, som vårregn opna munnen.',
        24: 'Eg smilte til mismodige, mitt andlit fekk dei ikkje myrkt.',
        25: 'Når eg deim vitja, sat eg fremst, sat som ein konge i sin herflokk, lik ein som trøystar syrgjande.',
    },
    30: {
        1: 'Men no er eg til spott for deim som yngre er av år enn eg; eg deira feder ikkje fann verdige plass hjå gjætarhunden.',
        2: 'Magtlause er og deira hender, og deira saft og kraft er burte;',
        3: 'Dei magre er av naud og svolt, dei gneg i turre øydemarki som alt i går var reine audni,',
        4: 'og plukkar melde millom kjørri og hev til føda einerot.',
        5: 'Frå folket vert dei jaga burt, fær tjuvemann slengt etter seg.',
        6: 'Dei gøymer seg i fæle gil, i holor uti jord og fjell;',
        7: 'og millom buskor skrålar dei og samlast under netlerunnar;',
        8: 'ei ætt av dårar og namnlause som ein helst piskar ut or landet.',
        9: 'No er eg slengjestev for deim, eit ordtak hev for deim eg vorte.',
        10: 'Dei styggjest ved meg, held seg burte og sparer ei å sputta på meg.',
        11: 'Utan all blygd dei krenkjer meg, hiv av kvart band framfor mi åsyn.',
        12: 'Eit utjo reiser seg til høgre, dei spenner mine føter burt, og legg ulukke-vegar mot meg.',
        13: 'Og stigen min den bryt dei upp og hjelper til med mi ulukka, dei som er hjelpelause sjølv.',
        14: 'Som gjenom vide murbrot kjem dei, velter seg fram med bråk og brak.',
        15: 'Imot meg vender rædslor seg, mi æra elter dei som stormen, mi velferd kvarv som lette sky.',
        16: 'No jamrar seg mi sjæl i meg; usæle dagar held meg fast.',
        17: 'Natti gneg mine knokar av meg, min verk, mi pina aldri søv.',
        18: 'Ved allmagt vert min klædnad vanstelt, heng tett som skjortekragen kring meg.',
        19: 'Han kasta meg i skarnet ned; og eg ser ut som mold og oska.',
        20: 'Eg skrik til deg, du svarar ikkje, eg stend der, og du stirer på meg.',
        21: 'Hard hev du vorte imot meg, du stri’r mot meg med veldug hand.',
        22: 'Du let meg fara burt i stormen, du let meg tynast i hans brus.',
        23: 'Eg veit du fører meg til dauden, der alt som liver samlast lyt.',
        24: 'Kven kavar ikkje når han søkk? Kven ropar ikkje ut i fåren?',
        25: 'Gret eg’kje sjølv med den fortrykte, og syrgde yver fatigmann?',
        26: 'Eg vona godt, men det kom vondt, eg venta ljos, men myrker kom.',
        27: 'Det kokar allstødt i mitt indre, ulukkedagen møter meg.',
        28: 'Svart gjeng eg kring, men ikkje solbrend, eg ris i flokken, skrik um hjelp.',
        29: 'Bror åt sjakalar hev eg vorte, til strussar eg ein frende er.',
        30: 'Mi hud er svart og flaknar av; det brenn i mine bein av hite.',
        31: 'Min cither hev eg bytt i sorg, og fløyta mi med gråtar-mål.',
    },
    31: {
        1: 'Med augo hev eg gjort ei pakt; eg skal’kje skygna etter møy.',
        2: 'Kva gav meg elles Gud der uppe? Kva arv gav Allvald frå det høge?',
        3: 'Kjem ikkje udådsmann i naud? Og illgjersmenn i ulukka?',
        4: 'Ser ikkje han på mine vegar? Tel ikkje han kvart stig eg gjeng?',
        5: 'Dersom eg fram med fals hev fare, og foten sprunge etter svik',
        6: '- Gud vege meg på rettferds vegt, so han kann sjå eg skuldlaus er! -',
        7: 'Veik mine stig frå vegen av, hev hjarta etter augo gjenge, var det ein flekk på mine hender,',
        8: 'so gjev ein annan et mitt såd, og riv mi planting upp med rot!',
        9: 'Let eg min hug av kvinna dåra, sneik eg til grannens dør meg fram,',
        10: 'so lat mitt viv åt andre mala, og andre yver ho seg bøygje!',
        11: 'For dette er ei skjemdarferd, eit brot som dom og straff fortener,',
        12: 'ein eld som eta vil til avgrunns og øydeleggja all mi eiga.',
        13: 'Vanvyrd’ eg retten åt min træl og trælkvinna i trætta med deim?',
        14: '- Kva gjord’ eg då, når Gud reis upp? Kva svara eg, når han meg klaga?',
        15: 'Dei er som meg i morsliv skapte; ein forma oss i moderfang -',
        16: 'Um eg sagde nei når arming bad, og let enkja gråtande gå burt,',
        17: 'hev eg mitt brød åleine ete, so farlaus inkje fekk ein bit,',
        18: '- nei, far for han eg var frå yngdi, frå morsliv var eg hennar førar -',
        19: 'Såg eg ein stakar utan klæde, ein fatig utan yverplagg,',
        20: 'og so hans lender ei meg signa, og ei mi saueull han vermde,',
        21: 'hev eg mot farlaus handi lyft, av di eg medhald fekk i retten:',
        22: 'Let herdi mi or led då losna, og armen brotna frå sitt bein!',
        23: 'For eg var ovleg rædd Guds straff, eg magtlaus stod framfor hans velde.',
        24: 'Um eg mi lit til gullet sette, og voni til det fine gull,',
        25: 'Gledde eg meg ved auka rikdom, og alt eg vann meg med mi hand,',
        26: 'såg eg på ljoset når det stråla, på månen der han skreid i glans,',
        27: 'vart hjarta mitt i løyndom dåra, so kyss på hand til deim eg sende,',
        28: 'so var det og straffande brot, då neitta eg min Gud der uppe.',
        29: 'Hev eg meg gledt ved uvens uferd, og jubla når han kom i skade,',
        30: '- men eg let ikkje munnen synda og banna honom ifrå livet -',
        31: 'hev ei mitt husfolk stendigt sagt: «Kven gjekk vel svolten frå hans bord?»',
        32: '- Eg let’kje framand natta ute; for ferdamann eg opna døri -',
        33: 'hev eg som Adam dult mi synd, og løynt mi misgjerd i min barm,',
        34: 'di eg var rædd den store hop og ottast spott frå ættefrendar, so stilt eg heldt meg innum dører?',
        35: 'Å, vilde nokon høyra på meg! Sjå her er underskrifti mi, lat berre Allvald svara meg! Fekk eg den skrift min motpart skreiv,',
        36: 'den skulde eg på oksli bera og binda på meg som ein krans',
        37: 'eg melde honom kvart mitt stig, og som ein hovding møta honom.',
        38: 'Dersom min åker klagar meg, og um plogforerne lyt gråta,',
        39: 'åt eg hans grøda ubetalt, tok livet eg av eigarmannen:',
        40: 'Lat då for kveite klunger gro, og ugras der eg sådde bygg!» Her endar Jobs tale.',
    },
    32: {
        1: 'Dei tri mennerne svara ikkje Job meir, av di han heldt seg sjølv for rettferdig.',
        2: 'Men då loga harmen upp hjå Elihu, son åt Barak’el, buziten, av Rams-ætti. Han vart harm på Job, av di han heldt seg sjølv rettferdigare enn Gud.',
        3: 'Han harmast og på dei tri venerne, av di dei ikkje kunde finna noko svar, og endå dømde Job skuldig.',
        4: 'For Elihu hadde venta med å tala til Job, av di dei andre var eldre enn han;',
        5: 'men då Elihu såg at dei tri mennerne ikkje hadde noko å svara, vart han brennande harm.',
        6: 'Og Elihu, son åt Barak’el, buziten, tok til ords og sagde: «Ung er eg etter år å rekna; de derimot er gamle menn. Difor eg blygdest og var rædd å segja til dykk det eg veit.',
        7: 'Eg tenkte: «Åri tala lyt og alderen forkynna visdom.»',
        8: 'Nei, ånd lyt til hjå menneski; og Allvalds ande gjev deim vit.',
        9: 'Dei gamle er’kje alltid vise, kvithærde veit’kje stødt det rette.',
        10: 'Difor eg segjer: Høyr på meg; eg vil og segja det eg veit.',
        11: 'Eg venta hev på dykkar ord og lydde vel på dykkar lærdom, alt med de leita etter ord.',
        12: 'Og eg gav nøgje agt på dykk, men ingen sagde Job imot, ingen av dykk gav honom svar.',
        13: 'Seg ikkje: «Visdom der me fann; Gud slå han ned, folk kann det ikkje.»',
        14: 'Han hev’kje tala imot meg, og ei med dykkar ord eg svarar.',
        15: 'Dei er forstøkte, svarar ikkje, dei vantar ord å føra fram.',
        16: 'Treng eg vel venta når dei tegjer og stend der reint forutan svar?',
        17: 'Eg vil og svara, eg for meg, eg vil og segja det eg veit.',
        18: 'For eg er full av ord til svars; i bringa sprengjer åndi på.',
        19: 'Mitt indre er som innstengd vin, lik nye vinhit vil det sprengjast.',
        20: 'Eg tala vil so eg fær luft, vil opna lipporne og svara.',
        21: 'Eg ikkje tek parti for nokon og smeikjer ei for nokor mann;',
        22: 'å smeikja kann eg ikkje med; min skapar elles burt meg reiv.',
    },
    33: {
        1: 'Men høyr no, Job, på talen min, lyd vel på alle mine ord!',
        2: 'Sjå eg hev opna mine lippor, og tunga talar i min munn.',
        3: 'Frå ærlegt hjarta kjem min tale, rein kunnskap lipporne ber fram.',
        4: 'Guds ånd er det som meg hev skapt, og Allvalds ande gjev meg liv.',
        5: 'Um du det kann, so gjev meg svar! Væpna deg mot meg, og stig fram!',
        6: 'Eg er din likemann for Gud, eg og av leiret forma er.',
        7: 'Du tarv’kje vera rædd for meg, min trykk skal ikkje tyngja deg.',
        8: 'Men du hev sagt for øyro mine - eg høyrde ljoden av ditt ord -:',
        9: '«Eg skuldfri er og utan synd, eg flekkfri er og utan skuld;',
        10: 'men han fører uvensgrunnar mot meg og held meg for sin fiendsmann;',
        11: 'han legg i stokken mine føter og vaktar alle mine vegar.»',
        12: 'Men du hev urett, svarar eg; Gud større er enn menneskja.',
        13: 'Men kvifor vil du klaga på han: Han aldri svarar i sin sak?',
        14: 'På eit vis talar Gud, ja tvo, um enn dei ikkje agtar på det.',
        15: 'I draumar og i syn ved natt, når tunge svevnen fell på folk, når dei på lægjet ligg og blundar,',
        16: 'då let han øyro upp på folk, og innsiglar åtvaring til deim,',
        17: 'for burt frå synd å driva mannen, og rydja ovmod ut or honom',
        18: 'og berga sjæli hans frå gravi og livet hans frå spjotodd-daude.',
        19: 'Han tuktast og med sjukelægje, med stendig uro inn til beini,',
        20: 'hans liv fær mothug imot brød, og sjæli hans mot lostemat.',
        21: 'Hans misser holdet, vert usjåleg, og beini morknar, syner ikkje,',
        22: 'og sjæli ned mot gravi lutar, hans liv mot daude-englarne.',
        23: 'Er det då yver han ein engel, ein millommann, ein utav tusund, som lærer mannen um hans plikt,',
        24: 'Han ynkast yver han og segjer: «Frels honom frå i grav å ganga! Eg hev ei løysepening funne.»',
        25: 'Hans likam skal av helsa bløma, sin ungdom skal han atter få.',
        26: 'Han bed til Gud og nåde fær, so han hans åsyn ser med jubel. Og so fær mannen att si rettferd.',
        27: 'Han syng for folk og segjer so: «Eg synda hev og krenkt det rette, men hev’kje fenge lika for det;',
        28: 'mi sjæl frå gravi berga han, med gleda fær eg ljoset sjå.»',
        29: 'Og sjå: alt dette gjerer Gud tvo gonger, ja tri gong’ mot mannen,',
        30: 'og ber hans sjæl frå gravi burt, so livsens ljos kann lysa for han.',
        31: 'So gjev no gaum og høyr meg, Job, ver tagall du, so eg kann tala!',
        32: 'Um du hev ord, so gjev meg svar! Tala, eg gjev deg gjerne rett.',
        33: 'I anna fall so høyr på meg, teg medan eg deg visdom lærer!»',
    },
    34: {
        1: 'Og Elihu tok til ords og sagde:',
        2: '«Vismenner, høyr på ordi mine! Kunnige folk, lyd no på meg!',
        3: 'For ordi prøver ein med øyro, som ein med gomen maten smakar.',
        4: 'So lat oss no det rette velja og saman finna ut det gode!',
        5: 'For Job hev sagt: «Eg skuldfri er; min rett hev Gud ifrå meg teke;',
        6: 'tråss i min rett, stend eg som ljugar, uskuldig fekk eg ulivssår.»',
        7: 'Finst det vel nokon mann som Job? som gløyper hædings ord som vatn,',
        8: 'som held med illgjerdsmenner lag, hev umgang med gudlause folk?',
        9: 'For han hev sagt: «Kva gagnar det ein mann å vera ven med Gud?»',
        10: 'Difor, de menn med vit, høyr meg! D’er langt frå Gud å vera gudlaus, frå Allvalds-Gud å gjera urett.',
        11: 'Han løner mannen for hans gjerd, fer med han etter all hans ferd.',
        12: 'Nei, urettferdig er’kje Gud, og Allvald krenkjer ikkje retten.',
        13: 'Kven let vel honom styra jordi? Og kven hev grunna jordheims-kringen?',
        14: 'Um han på seg åleine tenkte og drog sin ande til seg att,',
        15: 'då gjekk alt livande til grunns, og menneskja vart atter mold.',
        16: 'Um du er klok, so høyr på dette, og lyd på ljoden av mitt ord!',
        17: 'Kann ein som hatar retten, styra? Fordømer du den allrettvise?',
        18: 'Kann ein til kongen segja: «Niding!» Og til dei megtige: «Du brotsmann?»',
        19: 'Til han som ei gjer skil på fyrstar, og ikkje vyrder rik mot fatig. Av di hans hand hev skapt deim alle?',
        20: 'Dei andast brått og midt um natti, eit folk avjagast og kverv burt, stormenn forgjengst i hjelpeløysa.',
        21: 'Hans augo ser til mannsens ferd, han skodar kvart eit stig han tek;',
        22: 'det finst’kje skugge eller myrker der illgjerdsmenn kann løyna seg.',
        23: 'Han tarv’kje lenge sjå på mannen fyrr han lyt møta Gud til doms.',
        24: 'Han utan forhøyr storfolk krasar og andre set i deira stad.',
        25: 'Han kjennar heile deira verk og gjev um natti deim til tyning.',
        26: 'Han tuktar deim som illgjerdsmenner, ein stad der alle kann det sjå,',
        27: 'dei som hev vike burt frå han og ikkje hev hans vegar fylgt -',
        28: 'so han kann høyra armods klaga og jammerskrik frå undertrykte.',
        29: 'Fær han det stilt, kven vil fordøma? Løyner han seg - kven kann då sjå han? - for folkemugen og for mannen,',
        30: 'so ikkje gudlaus mann skal råda og vera snaror yver folket.',
        31: 'For segjer ein vel so til Gud: «Ovmodigt hev eg bore meg; eg vil ikkje lenger vera vond.',
        32: 'Vis du meg det eg ikkje ser! hev eg gjort synd, vil eg snu um?»',
        33: 'Skal han då straffa som du tykkjer? D’er du som er den misnøgde; so lyt du velja, ikkje eg; og du fær segja det du veit.',
        34: 'Dei kloke folk vil segja til meg, og kvar ein vismann som meg høyrer:',
        35: '«Job talar ikkje med forstand hans ord er utan ettertanke.»',
        36: 'Gjev Job må allstødt verta prøvd for sine svar på nidings vis!',
        37: 'For han legg brotsverk til si synd og ber seg vyrdlaust millom oss, og talar mange ord mot Gud.»',
    },
    35: {
        1: 'Og Elihu tok til ords og sagde:',
        2: '«Seg, trur du vel at slikt er rett, so du meir rettvis er enn Gud,',
        3: 'når djervt du spør: «Kva gagn hev eg, kva løn um eg frå syndi flyr?»',
        4: 'På dette vil eg svara deg og likeins venerne med deg.',
        5: 'Ditt auga du mot himmelen snu, og sjå på skyerne der uppe!',
        6: 'Di synd, kann ho vel skade honom? Lid han, um dine brot er mange?',
        7: 'Er du rettvis, kva gjev du honom? Kva fær han då utav di hand?',
        8: 'Di synd vedkjem ein mann som deg, di rettferd gjeld eit menneskje.',
        9: 'Dei klagar yver urett stor og skrik um hjelp mot valdsmenns arm;',
        10: 'men spør’kje: «Kvar er Gud, min skapar, som let ved natt lovsongar tona,',
        11: 'gjev oss meir vit enn dyr på mark og meir forstand enn fugl i luft?»',
        12: 'Der ropar dei - han svarar ikkje - um hjelp mot ovmod hjå dei vonde.',
        13: 'Gud høyrer ei på tome ord, slikt agtar Allvald ikkje på.',
        14: 'Um enn du segjer du ei ser han, han ser han nok saki, bi på honom!',
        15: 'Og no, når vreiden hans ei refser, tru han ei kjenner dårskapen?',
        16: 'Men Job let upp sin munn til fåfengd, uvitugt talar han so mykje.»',
    },
    36: {
        1: 'Og Elihu heldt fram og sagde:',
        2: '«Vent litt og lat meg tala til deg! For endå hev eg ord for Gud;',
        3: 'eg hentar kunnskap langan leid, skal hjelpa skaparen til rett.',
        4: 'For visst, mitt ord skal ikkje ljuga; framfor deg stend ein full-lærd mann.',
        5: 'Sjå, Gud er sterk, men vander ingen, han som er veldug i forstandskraft.',
        6: 'Han let’kje gudlaus mann få liva; men armingarne gjev han rett.',
        7: 'Han snur’kje augo frå rettvise; hjå kongar på sin konungsstol han let deim ævleg sitja høgt.',
        8: 'Um dei i lekkjor bundne vart og i ulukkesnaror fanga,',
        9: 'so synar han deim deira ferd og brot - at dei ovmoda seg -',
        10: 'til refsing opnar øyro deira og byd deim venda um frå syndi.',
        11: 'Um dei då høyrer vil og lyda, so liver dei sitt liv i lukka og sine år i herlegdom;',
        12: 'um ikkje, fær dei styng av spjotet, og i sin dårskap andast dei.',
        13: 'Men vreiden trivst i vonde hjarto; dei bed’kje, um dei bundne vert;',
        14: 'i ungdomstidi skal dei døy, forgangast som utukt-sveinar.',
        15: 'Han frelser arming ved hans naud, opnar hans øyro gjenom trengsla.',
        16: 'Deg og han lokkar ut or trengsla, fritt fær du det og ikkje trongt, ditt bord er fullt av feite retter.',
        17: 'Men fær du straff som syndug mann, i fall hans domsord held deg fast.',
        18: 'Lat ikkje tukti avla vreide, den tunge bot deg leida vilt!',
        19: 'Kann klaga hjelpa deg or naud, kor mykje enn du stræva vil?',
        20: 'Du må’kje lengta etter natti då folk vert rykte frå sin stad!',
        21: 'Gjev agt, so ei til synd du vender, for det du heller vil enn lida.',
        22: 'Sjå, Gud er upphøgd i sitt velde; kven er ein lærar slik som han?',
        23: 'Kven hev vel vegen lagt for honom? Kven sagde vel: «Du hev urett gjort?»',
        24: 'Hugs på å prisa høgt hans verk, som menneski hev sunge um!',
        25: 'Kvart menneskje med lyst det ser, mann-ætti ser det langan leid.',
        26: 'Upphøgd, uskynande er Gud, hans liveår kann ingen telja,',
        27: 'for han dreg vatsdroparne, so det vert regn av skodde-eim.',
        28: 'Og ifrå skyerne det fløymer og dryp ned yver mange folk.',
        29: 'Kven skynar vel skyhoparne og torebraket frå hans hytta?',
        30: 'Han breider ljoset sitt ikring seg og let det hylja havsens røter.',
        31: 'Soleis han dømer folkeslag og skiftar brød i ovmengd ut.',
        32: 'Han sveiper henderne i ljos og sender det mot fienden.',
        33: 'Hans tora meldar um hans koma, ja, feet varslar når han kjem.',
    },
    37: {
        1: 'For dette bivrar hjarta mitt og lyfter seg frå staden sin.',
        2: 'Å, høyr på harmen i hans røyst, den dun som dundrar or hans munn!',
        3: 'Det fer burt under himmelkvelv, men elden skin til heimsens endar.',
        4: 'So burar røysti etterpå, han torar med sitt stolte mod, og ljoni held han ikkje att når røysti si han ljoma let.',
        5: 'Gud torar underfullt med røysti, gjer storverk som me ei kann skyna.',
        6: 'Han snøen byd: «Fall ned til jord!» Til regnet og, sitt sterke silregn.',
        7: 'Han stengjer av for mannehand, so all hans skapning læra må.',
        8: 'Villdyri gjeng til sine hi og kvilar på sin legestad.',
        9: 'Or inste kammer kjem det storm, og kulde ut av vindarne.',
        10: 'Utav Guds ande gustar frost, dei vide vatni kjem i tvang.',
        11: 'Han lastar skyi og med væta og breider sine elding-skyer,',
        12: 'og hit og dit dei hastar fram, og skifter leid som han det vil og set i verk det som han byd, utyver vide jordheims-kringen;',
        13: 'anten til ris, når jordi treng det, ell’ og med nåde lyt dei råka.',
        14: 'Job, lyd på dette, statt no still, gjev gaum på undri Gud hev gjort!',
        15: 'Veit du når Gud deim segjer fyre, og let sitt ljos or skyi skina?',
        16: 'Veit du vel korleis skyi sviv, um underi åt den Allvise?',
        17: 'Du som i heite klæde styn, når jordi brenn i sunnanvind?',
        18: 'Gjer du med honom himmelkvelven, som er so fast som støypte spegel?',
        19: 'Lær oss, kva me skal segja honom! Me tegja lyt for berre myrker.',
        20: 'Skal han få melding at eg talar? Vil nokon ynskja seg å tynast?',
        21: 'No kann ein ikkje ljoset sjå, um enn det klårt på himmeln skin, men vinden sopar skyi burt.',
        22: 'Langt nordanfrå kjem gullet hit, ein fælsleg glans ligg yver Gud.',
        23: 'Til Allvald kann me ikkje nå, til han som er so stor i magt; men rett og rettferd ei han krenkjer.',
        24: 'Difor ber folket age for han, han ansar ingen sjølvklok mann.»',
    },
    38: {
        1: 'Og Herren svara Job or stormen og sagde:',
        2: '«Kven er det som gjer rådgjerd myrk med ord som reint er utan skyn?',
        3: 'Spenn som ein mann ditt belte på, gjev meg på mine spursmål svar.',
        4: 'Kvar var du då eg grunna jordi? Seg fram, i fall du greida hev!',
        5: 'Kven sette måli - veit du det? - Og spana målsnor yver henne?',
        6: 'Kvar vart pelaran’ sette ned? Kven la vel hennar hyrnestein,',
        7: 'med alle morgonstjernor kvad, gudssønerne av gleda song?',
        8: 'Kven stengde havet inn med dører, då det braut ut or moderfang?',
        9: 'Då eg det skyer gav til klæde og myrkeskodd til sveip åt det',
        10: 'då eg for det ei grensa sette og trygga ho med port og bom',
        11: 'og sagde: «Hit og ikkje lenger! Di byrge bylgja stogge her!»',
        12: 'Baud du vel dagsprett nokon gong? Gav du morgonroden stad,',
        13: 'so femner kringum ytste jordi, so syndaran’ vart riste av?',
        14: 'Då tek ho form som leir for segl, og all stend greinlegt som ein klædnad.',
        15: 'Då misser gudlause sitt ljos, den arm som lyfte seg, vert knekt.',
        16: 'Kom du til havsens kjeldor fram, hev du på avgrunns-botnen gjenge?',
        17: 'Hev daude-portarn’ vist seg for deg? Ja, såg du daudeskuggens portar?',
        18: 'Og hev du vel jordviddi set? Kjenner du alt i hop, seg fram!',
        19: 'Kvar finn ein veg dit ljoset bur? Og kvar hev myrkret heimen sin?',
        20: 'So du kann henta deim til grensa og vita veg til deira hus.',
        21: 'Du veit det, du vart fødd den gong, og dagetalet ditt er stort.',
        22: 'Kom du dit snøen uppspard ligg? Og såg du forrådshus for haglet,',
        23: 'som eg til trengsle-tidi gøymer, til dagarne med kamp og krig?',
        24: 'Kva veg tru ljoset deiler seg, austanvinden spreider seg på jordi?',
        25: 'Kven laga renna vel for regnet og brøytte veg for torestrålen,',
        26: 'so væta kjem til aude land, til øydemark der ingen bur,',
        27: 'til kveikjing for den nakne heid, so gras kann gro der fyrr var bert?',
        28: 'Skal tru um regnet hev ein far? Kven avlar vel doggdroparne?',
        29: 'Kva moderliv kom isen or? Kven avla rim i himmelrømd,',
        30: 'når vatnet hardnar liksom stein, når havflata stivnar til?',
        31: 'Bind du vel bandet um Sjustjerna? Løyser du lekkjet av Orion?',
        32: 'Set du rett tid for dyreringen? Og driv du Bjørnen og hans ungar?',
        33: 'Kjenner du himmelleverne? Gav du han yver jordi magt?',
        34: 'Kann røysti di til skyi nå, so vatnet fløymer yver deg?',
        35: 'Byd du vel ljoni fara ut, so dei deg svarar: «Her er me?»',
        36: 'Kven la i myrke skyer visdom? Kven gav forstand til hildringi?',
        37: 'Kven tel med visdom skyerne? Kven tømer himmelfati ut,',
        38: 'når turre mold vert samanrend, jordklumpar kleimer seg i hop?',
    },
    39: {
        1: 'Gjeng du for løva etter rov og gjev ungløvor deira mette,',
        2: 'medan dei gøymer seg i holor og ligg på lur i busk og kjørr?',
        3: 'Kven yter ramnen føda hans, når upp til Gud hans ungar ropar og flakkar kringum utan mat?',
        4: 'Steingeiti, veit du når ho kidar? Vaktar du riderne åt hindi?',
        5: 'Tel måna’rne dei gjeng med unge, og kjenner du deira fødetid?',
        6: 'Dei bøygjer seg, fø’r sine ungar, so er det slutt med deira rider.',
        7: 'På marki kidi veks seg store, spring burt og kjem’kje att til deim.',
        8: 'Kven let villasnet renna fritt, tok bandet av det skjerre dyr,',
        9: 'som eg gav øydemark til heim, den salte steppa til ein bustad?',
        10: 'Det lær åt byen med sitt ståk, slepp høyra skjenn frå drivaren.',
        11: 'Det finn seg beite millom fjell, og leitar upp kvart grøne strå.',
        12: 'Skal tru villuksen vil deg tena, og natta yver ved di krubba?',
        13: 'Kann du til fori honom tøyma, horvar han dalar etter deg?',
        14: 'Lit du på honom for hans styrke? Og yverlet du han ditt arbeid?',
        15: 'Trur du han til å føra grøda heim og draga henne inn i løda?',
        16: 'Struss-hoa flaksar kåt med vengen, men viser fjør og veng morskjærleik?',
        17: 'Nei, ho legg sine egg på jordi, og let so sanden verma deim;',
        18: 'ho gløymer at ein fot kann treda og villdyr trakka deim i kras.',
        19: 'Hardt fer ho åt med sine ungar, som var dei ikkje hennar eigne; for fåfengt stræv ho ikkje ræddast.',
        20: 'For Gud let henne gløyma visdom, han ei tiletla henne vit.',
        21: 'Men når ho baskar seg i veg, ho lær åt både hest og mann.',
        22: 'Skal tru um du gjev hesten kraft og klæder halsen hans med mån?',
        23: 'Let du han som grashoppen springa alt med han frøser skræmeleg.',
        24: 'Glad i si kraft han marki skrapar og fer so fram mot væpna flokk.',
        25: 'Han urædd er og lær åt rædsla, for sverdet ei han vender um,',
        26: 'det skranglar pilhus yver honom, det blenkjer spjot til styng og skot.',
        27: 'Med ståk og bråk han slukar jordi, ustyrleg når stridsluren gjeng.',
        28: 'Han kneggjar: «Hui!» når luren læt, han verar striden langan leid, med skrik frå hovdingar og herrop!',
        29: 'Flyg hauken upp ved ditt forstand og spilar vengjerne mot sud?',
        30: 'Stig ørnen høgt av di du byd, og byggjer reiret sitt i høgdi? Han bur på berg og held seg der, på kvasse tind og høge nut. Derfrå han spæjar etter mat, hans augo yver viddi skodar. Hans ungar gløypar i seg blod; der det finst lik, der er han og.» Og Herren svara Job og sagde: «Vil klandraren med Allvald trætta? Lat han som lastar Gud då svara!» Då svara Job Herren og sagde: «For ring eg er; kva skal eg svara? Eg handi legg på munnen min. Ein gong eg tala, no eg tegjer, tvo gong’ - eg gjer det ikkje meir.»',
    },
    40: {
        1: 'Og Herren svara Job or stormen og sagde:',
        2: '«Spenn som mann ditt beltet på, gjev meg på mine spursmål svar:',
        3: 'Vil du forspille meg min rett, fordøma meg, so du fær rett?',
        4: 'Hev du vel slik ein arm som Gud? Kann du som han med røysti dundra?',
        5: 'Pryd deg med høgd og herredom, klæd deg i glans og herlegdom,',
        6: 'Lat so din vreide strøyma fram, sjå kvar ein stolt og audmyk han!',
        7: 'Så kvar ein stolt og bøyg han ned, og slå til jord dei gudlause!',
        8: 'Og gøym deim alle under jordi, bitt deira andlit fast i løynd!',
        9: 'So skal eg og lovprisa deg, som siger med di høgre vann.',
        10: 'Sjå elvhesten! Eg hev skapt han liksom deg; som ein ukse et han gras.',
        11: 'Sjå då krafti i hans lender, i bukmusklarne hans styrke!',
        12: 'Halen gjer han stiv som ceder, fast bogsenarne er tvinna.',
        13: 'Knokarne er koparrøyrer, beini som jarnstenger er.',
        14: 'Av Guds verk er han det fyrste, av sin skapar fekk han sverd.',
        15: 'Bergi ber åt honom for, alle villdyr leikar der.',
        16: 'Under lotusbusk han kviler, løyner seg i røyr og sev.',
        17: 'Lotusbusk gjev honom skugge, piletre umkransar honom.',
        18: 'Strid gjeng elvi, ei han ottast; trygg er han um so sjølve Jordan fossar imot hans gap.',
        19: 'Kann ein tak han so han ser det, draga snara gjenom snuten?',
        20: 'Kann du fiska krokodillen, binda tunga hans med taum,',
        21: 'Draga snor i gjenom nosi, hogga krok i kjaken hans?',
        22: 'Vil han tigga um nåde, tala mjuke ord til deg?',
        23: 'Tru han vil gjera samband med deg og din træl for alltid verta?',
        24: 'Kann du han som leikfugl halda for smågjentorne i band? Handlar fiskarlag med honom, skiftar ut til kræmarar? Kann hans hud med spjot du fylla, og hans hovud med harpunar? Berre prøv - du skal det minnast; enn ein gong du gjer det ikkje! Kvar og ein vil missa voni, verta feld ved syni av han.',
    },
    41: {
        1: 'Ingen torer eggja honom; kven kann då mot meg reisa?',
        2: 'Kven gav meg, so eg gjev att? Under himmeln alt eg eig.',
        3: 'Ei eg tegjer um hans lemer, um hans sterke, væne bygnad.',
        4: 'Kven hev drege brynja av han, Gjenge inn i duble tanngard?',
        5: 'Kven hev opna kjakeporten? Rædsla kring hans tenner ligg.',
        6: 'Sterke er hans skjolde-rader, feste med ei fast forsigling.',
        7: 'Tett dei ligg innåt kvarandre, ingi luft slepp millom deim.',
        8: 'Eine skjolden i den andre heng i hop, skilst ikkje åt.',
        9: 'Ljos ifrå hans njosing strålar, augo skin som morgonroden.',
        10: 'Or hans gap skyt brandar fram, gneistar sprutar derifrå.',
        11: 'Or hans nasar stig det røyk, liksom eim or kjel som kokar.',
        12: 'Anden hans set eld på kol, logen ut or gapet stend.',
        13: 'I hans nakke styrken bur, rædsla spring framfor hans åsyn.',
        14: 'Tette sit kjøtvalkarne, støypte fast urikkelg.',
        15: 'Hjarta hans er hardt som stein, fast som understein i kverni.',
        16: 'Kjempor ræddast når han ris, misser både mod og hugs;',
        17: 'Sverd vil ikkje bita på, ikkje skot med spjot og pil.',
        18: 'Jarn agtar han liksom strå, kopar nett som fauskeved.',
        19: 'Ei han vik for bogesonen; stein frå slyngja vert som halm,',
        20: 'og stridsklubba vert som strå, og han lær åt spjot som susar.',
        21: 'Under han er kvasse broddar, spor dei set som treskjeslede.',
        22: 'Djupet kokar som ei gryta, sjøen som ein salvekjel.',
        23: 'Vegen lyser etter honom, djupet skin som sylverhår.',
        24: 'Liken hans på jord ei finst, denne skapning utan ræddhug.',
        25: 'Han ser ned på alt som høgt er, konge yver alle kaute.»',
    },
    42: {
        1: 'Då svara Job Herren og sagde:',
        2: '«Eg skynar at du allting kann; for deg er ingen plan umogleg.',
        3: 'Kven vil uvitug myrkja rådgjerd? Eg tala som ein fåvis mann um under som eg ikkje fata.',
        4: 'Å høyr no, lat meg få tala! Eg vil deg spyrja, lær du meg!',
        5: 'Fyrr høyrd’ eg berre gjete deg, no ser eg deg med eigne augo.',
        6: 'Difor eg tek det i meg att og tregar djupt i mold og oska.»',
        7: 'Då no Herren hadde tala desse ordi til Job, sagde han til Elifaz frå Teman: «Eg er harm på deg og dei tvo venerne dine, av di de hev ikkje tala rett um meg soleis som Job, tenaren min.',
        8: 'Tak difor sju uksar og sju verar, og gakk til Job, tenaren min, og ofra brennoffer for dykk; og lat Job, tenaren min, beda for dykk! For berre honom vil eg taka til nåde, so eg ikkje gjer ulukka på dykk, for de ikkje hev tala rett um meg soleis som Job, tenaren min.»',
        9: 'Og Elifaz frå Teman og Bildad frå Suah og Sofar frå Na’ama gjekk av stad og gjorde so som Herren hadde sagt til deim, og Herren høyrde Jobs bøn.',
        10: 'No vende Herren lagnaden for Job, då han bad for venerne sine; og alt det Job hadde ått, fekk han tvifald att.',
        11: 'Og alle brørne og systerne hans kom til honom, og like eins alle dei kjenningar han fyrr hadde havt, og dei åt og drakk med honom i huset hans. Og synte honom medynk og trøysta honom for all den ulukka som Herren ført yver honom, og kvar av deim gav honom ein gullpening og ein gullring.',
        12: 'Og Herren velsigna den siste livetidi åt Job meir enn den fyrste; han fekk fjortan tusund sauer og seks tusund kamelar og tusund par uksar og tusund asnor.',
        13: 'Og han fekk sju søner og tri døtter;',
        14: 'den eine av deim kalla han Jemima, den andre Kesia og den tridje Keren-Happuk.',
        15: 'Det fanst ikkje so væne kvinnor i heile landet som døtterne åt Job, og far deira let deim erva til liks med brørne deira.',
        16: 'Etter dette livde Job hundrad og fyrti år, og såg born og barneborn, fire ættleder.',
        17: 'Og Job døydde gamall og mett av dagar.',
    },
}
