NAME = 'NorSMB: Studentmållagsbibelen frå 1921'
BOOK = 'Revelation of John'

CHAPTERS = {
    1: {
        1: 'Jesu Kristi openberring, som Gud gav honom til å visa tenarane sine det som snart skal hendast; og han sende bod ved engelen sin og synte det i teikn for tenaren sin Johannes,',
        2: 'som hev vitna um Guds ord og Jesu Kristi vitnemål, alt det han såg.',
        3: 'Sæl er den som les og dei som høyrer det profetiske ord og gøymer det som stend skrive der; for tidi er nær!',
        4: 'Johannes til dei sju kyrkjelydarne i Asia: Nåde vere med dykk og fred frå honom som er og som var og som kjem, og frå dei sju ånder som er framfor hans kongsstol,',
        5: 'og frå Jesus Kristus, det truverdige vitnet, den fyrstefødde av dei daude og herren yver kongarne på jordi! Honom som elskar oss og hev fria oss frå synderne våre med sitt blod,',
        6: 'og som hev gjort oss til eit kongerike, til prestar for Gud og sin Fader, honom tilhøyrer æra og magti i all æva! Amen.',
        7: 'Sjå, han kjem med skyerne, og kvart auga skal sjå honom, ogso dei som hev gjenomstunge honom, og alle ætter på jordi skal gråta sårt for honom. Ja, Amen!',
        8: 'Eg er A og Å, segjer Herren Gud, han som er og som var og som kjem, den Allmegtige.',
        9: 'Eg, Johannes, som er dykkar bror og luthavande i trengsla og i riket og i tolmodet i Jesus, eg var på den øyi som heiter Patmos, for Guds ord og Jesu vitnemål skuld.',
        10: 'Eg var burtrykt i Anden på Herrens dag, og eg høyrde attanfor meg ei sterk røyst som av ein basun, som sagde:',
        11: '«Det du ser, skriv det upp i ei bok og send det til dei sju kyrkjelydarne, til Efesus og til Smyrna og til Pergamum og til Tyatira og til Sardes og til Filadelfia og til Laodikea!»',
        12: 'Og eg snudde meg, so eg kunde sjå røysti som tala med meg, og då eg snudde meg, såg eg sju ljosestakar av gull,',
        13: 'og midt imillom dei sju ljosestakarne ein som var lik ein menneskjeson, klædd i ein fotsid kjole og umbunden under bringa med eit gullbelte,',
        14: 'og hovudet og håret hans var kvitt som kvit ull, som snø, og augo hans som eldsloge,',
        15: 'og føterne hans var liksom skinande kopar, som dei var glødde i ein omn, og røysti hans var som ljod av mange vatn.',
        16: 'Og han hadde sju stjernor i si høgre hand, og eit tvieggja kvast sverd gjekk ut or munnen hans, og hans åsyn var som soli når ho skin i si kraft.',
        17: 'Og då eg såg honom, fall eg ned for føterne hans som ein daud; og han lagde si høgre hand på meg og sagde:',
        18: '«Ottast ikkje! eg er den fyrste og den siste og den livande; og eg var daud, og sjå, eg er livande i all æva! Og eg hev lyklarne til dauden og til helheimen.',
        19: 'Skriv då det du såg, både det som er, og det som skal henda heretter,',
        20: 'løyndomen med dei sju stjernorne som du såg i mi høgre hand, og dei sju gull-ljosestakarne! Dei sju stjernorne er englar for dei sju kyrkjelydarne, og dei sju ljosestakarne er dei sju kyrkjelydarne.»',
    },
    2: {
        1: '«Skriv til engelen for kyrkjelyden i Efesus: Dette segjer han som held dei sju stjernorne i si høgre hand, han som gjeng midt imillom dei sju gull-ljosestakarne:',
        2: 'Eg veit um gjerningarne dine, og arbeidet ditt, og tolmodet ditt, og at du ikkje kann lida dei vonde, og du hev prøvt deim som segjer dei er apostlar, og ikkje er det, og hev funne at dei er ljugarar;',
        3: 'og du hev tolmod og hev havt mykje å bera for mitt namn skuld, og du hev ikkje vorte trøytt.',
        4: 'Men eg hev imot deg at du hev uppgjeve din fyrste kjærleik.',
        5: 'Kom difor i hug kvar du er fallen ifrå, og vend um og gjer dei fyrste gjerningarne! elles kjem eg snart yver deg og vil flytja ljosestaken din frå sin stad, um du ikkje umvender deg.',
        6: 'Men dette hev du, at du hatar gjerningarne åt nikolaitarne, som eg og hatar.',
        7: 'Den som hev øyra, han høyre kva Anden segjer til kyrkjelydarne: Den som sigrar, honom vil eg gjeva å eta av livsens tre, som er i Guds Paradis.',
        8: 'Og skriv til engelen for kyrkjelyden i Smyrna: Dette segjer den fyrste og den siste, han som var daud, og vart livande:',
        9: 'Eg veit um trengsla di og fatigdomen din - men du er rik - og spotti frå deim som segjer at dei er jødar, og ikkje er det, men er Satans synagoga.',
        10: 'Ottast ikkje for det du skal lida! Sjå, djevelen skal kasta nokre av dykk i fengsel, so de skal verta freista, og de skal hava trengsla i ti dagar. Ver tru til dauden, so skal eg gjeva deg livsens kruna!',
        11: 'Den som hev øyra, han høyre kva Anden segjer til kyrkjelydarne: Den som sigrar, han skal slett ikkje lida mein av den andre dauden!',
        12: 'Og skriv til engelen for kyrkjelyden i Pergamum: Dette segjer han som hev det tvieggja kvasse sverdet:',
        13: 'Eg veit kvar du bur: der som Satans kongsstol er, og du held fast ved mitt namn, og du forneitta ikkje mi tru, endå i dei dagar då Antipas var mitt true vitne, han som vart ihelslegen hjå dykk, der Satan bur.',
        14: 'Men eg hev nokre få ting imot deg: at du hev sume der som held fast ved Bileams læra, han som lærde Balak å leggja støyt for Israels born, å eta avgudsoffer og gjera hor.',
        15: 'Soleis hev du og sume som held fast ved læra åt nikolaitarne.',
        16: 'Vend um! men um du ikkje det gjer, kjem eg snart yver deg og vil strida mot deim ved min munns sverd.',
        17: 'Den som hev øyra, han høyre kva Anden segjer til kyrkjelydarne: Den som sigrar, honom vil eg gjeva å eta av det løynde manna, og eg vil gjeva honom ein kvit stein og eit nytt namn skrive på steinen, som ingen kjenner, utan den som fær det!',
        18: 'Og skriv til engelen for kyrkjelyden i Tyatira: Dette segjer Guds son, han som hev augo som eldsloge og føter som skinande kopar:',
        19: 'Eg veit um dine gjerningar og din kjærleik og di tenesta og di tru og tolmodet ditt og dei siste gjerningarne dine, som er fleire enn dei fyrste.',
        20: 'Men eg hev imot deg at du let kvinna Jezabel råda, ho som segjer at ho er ei profetkvinna, og ho lærer og dårar mine tenarar til å driva hor og eta avgudsoffer.',
        21: 'Og eg gav henne tid til å venda um, men ho vil ikkje venda um frå sin hordom.',
        22: 'Sjå, eg kastar henne på sjukelægje, og deim som driv hor med henne, i stor trengsla, dersom dei ikkje vender um frå sine gjerningar.',
        23: 'Og borni hennar vil eg rykkja burt ved daude, og alle kyrkjelydarne skal sanna at eg er den som ransakar nyro og hjarto, og eg vil gjeva dykk kvar etter dykkar gjerningar.',
        24: 'Men eg segjer dykk andre i Tyatira, alle som ikkje hev denne læra, og som ikkje kjenner Satans dypter - som dei segjer -: Eg vil ikkje leggja nokor onnor byrd på dykk.',
        25: 'Berre haldt fast ved det de hev, til dess eg kjem!',
        26: 'Og den som sigrar og tek vare på mine gjerningar alt til enden, honom vil eg gjeva magt yver heidningarne,',
        27: 'og han skal styra deim med jarnstav, liksom ein knasar kruskjerald, so som eg og hev fenge det av min Fader;',
        28: 'og eg vil gjeva honom morgonstjerna.',
        29: 'Den som hev øyra, han høyre kva Anden segjer til kyrkjelydarne!»',
    },
    3: {
        1: '«Og skriv til engelen for kyrkjelyden i Sardes: Dette segjer han som hev dei sju Guds ånder og dei sju stjernorne: Eg veit um gjerningarne dine, at du hev namn av å liva, og du er daud!',
        2: 'Vert vaken og styrk det andre, som var på veg til å døy! for eg hev ikkje funne gjerningarne dine fullkomne for min Gud.',
        3: 'Kom difor i hug korleis du hev lært og høyrt, og tak vare på det og vend um! Dersom du då ikkje vaker, skal eg koma som ein tjuv, og du skal ikkje vita kva stund eg kjem yver deg.',
        4: 'Men du hev nokre få namn i Sardes som ikkje hev flekka klædi sine, og dei skal ganga med meg i kvite klæde; for dei er det verde.',
        5: 'Den som sigrar, han skal verta klædd soleis i kvite klæde, og eg skal ikkje strjuka hans namn ut or livsens bok, og eg vil kjennast ved hans namn for min Fader og for hans englar.',
        6: 'Den som hev øyra, han høyre kva Anden segjer til kyrkjelydarne!',
        7: 'Og skriv til engelen for kyrkjelyden i Filadelfia: Dette segjer den Heilage, den Sannordige, han som hev Davids lykel, han som let upp, og ingen let att, og let att, og ingen let upp:',
        8: 'Eg veit um dine gjerningar. Sjå, eg hev sett framfyre deg ei opna dør, og ingen kann lata henne att; for du hev liti kraft, og hev like vel halde mitt ord og ikkje forneitta mitt namn.',
        9: 'Sjå, eg let nokre av Satans synagoga koma, som segjer dei er jødar, og ikkje er det, men lyg; sjå, eg vil gjera so at dei skal koma og falla ned for føterne dine og kjenna at eg hev elska deg.',
        10: 'Sidan du hev teke vare på mitt ord um tolmod, so vil eg og halda deg fri frå den freistings stund som skal koma yver all heimen til å freista deim som bur på jordi.',
        11: 'Eg kjem snart; haldt fast på det du hev, so ingen skal taka kruna di!',
        12: 'Den som sigrar, honom vil eg gjera til ein pilar i min Guds tempel, og han skal aldri meir ganga ut derifrå, og eg vil skriva på honom min Guds namn og namnet på min Guds by, det nye Jerusalem, det som kjem ned frå himmelen frå min Gud, og mitt namn det nye.',
        13: 'Den som hev øyra, han høyre kva Anden segjer til kyrkjelydarne!',
        14: 'Og skriv til engelen for kyrkjelyden i Laodikea: Dette segjer han som er amen, det truverdige og sannordige vitnet, upphavet til Guds skapning:',
        15: 'Eg veit um dine gjerningar, at du er korkje kald eller varm. Gjev du var kald eller varm!',
        16: 'Men so, då du er lunka og korkje kald eller varm, vil eg spy deg ut or munnen min.',
        17: 'Sidan du segjer: «Eg er rik og hev ovnøgd og treng ingen ting», og du veit ikkje at du er arm og ynkeleg og fatig og blind og naken,',
        18: 'so råder eg deg til å kjøpa av meg gull som er glødt i eld, so du kann verta rik, og kvite klæde, so du kann klæda deg med deim, og skammi av din nakenskap ikkje skal verta synberr, og salva augo dine med augnesalve, so du kann sjå!',
        19: 'Alle deim som eg elskar, deim refser og tuktar eg. Ver difor ihuga og vend um!',
        20: 'Sjå, eg stend for døri og bankar på; dersom nokon høyrer mi røyst og let upp døri, so vil eg ganga inn til honom og halda nattverd med honom, og han med meg.',
        21: 'Den som sigrar, honom vil eg gjeva å sitja med meg på min kongsstol, liksom og eg hev sigra og sett meg med min Fader på hans kongsstol.',
        22: 'Den som hev øyra, han høyre kva Anden segjer til kyrkjelydarne!»',
    },
    4: {
        1: 'Deretter såg eg, og sjå, det var ei dør opna i himmelen, og den fyrste røysti som eg hadde høyrt liksom ein basun som tala med meg, sagde: «Stig upp her, so skal eg syna deg det som skal hendast heretter!»',
        2: 'Straks var eg burtrykt i Anden, og sjå, ein kongsstol stod i himmelen, og det sat ein på stolen.',
        3: 'Og han som sat der, var sjåande til liksom jaspis og sarderstein, og det var ein regnboge rundt um stolen, å sjå til liksom smaragd.',
        4: 'Og rundt ikring stolen var det fire og tjuge stolar, og på stolarne såg eg fire og tjuge eldste sitjande, klædde i kvite klæde, og dei hadde gullkrunor på hovudi sine.',
        5: 'Og frå stolen for det ut ljoneldar og røyster og toredunar, og framfor stolen brann sju eldkyndlar, som er dei sju Guds ånder.',
        6: 'Og framfor stolen var det eit glashav likt krystall, og midt fyre stolen og rundt um stolen er det fire livende, uppfyllte med augo framantil og attantil.',
        7: 'Og den fyrste livendet er likt ei løva, og det andre livendet er likt ein ukse, og det tridje livendet hev åsyn som eit menneskje, og det fjorde livendet er likt ei fljugande ørn.',
        8: 'Og dei fire livendi hadde, kvart for seg, seks vengjer; rundt ikring og innantil var dei uppfyllte med augo, og dei held ikkje upp dag eller natt med å segja: «Heilag, heilag, heilag er Herren, Gud den allmegtige, han som var og som er og som kjem!»',
        9: 'Og når dei fire livendi gjev æra og pris og takk åt honom som sit på stolen, og som liver i all æva,',
        10: 'so fell dei fire og tjuge eldste ned for honom som sit på stolen, og tilbed honom som liver i all æva, og kastar krunorne sine ned for stolen og segjer:',
        11: '«Verdig er du, Herre, til å få æra og pris og magt! for du skapte alle ting, og for din vilje skuld var dei til og vart dei skapte!»',
    },
    5: {
        1: 'Og eg såg i den høgre handi hans som sat på stolen ei bok med skrift på innsida og utsida og forsigla med sju innsigle.',
        2: 'Og eg såg ein veldug engel, som ropa ut med høg røyst: «Kven er verdig til å opna boki og brjota hennar innsigle?»',
        3: 'Og ingen i himmelen eller på jordi eller under jordi kunde opna boki eller sjå i henne.',
        4: 'Då gret eg sårt, av di ingen vart funnen verdig til å opna boki eller sjå i henne.',
        5: 'Og ein av dei eldste segjer til meg: «Gråt ikkje! sjå, løva som er av Juda ætt, Davids rotrenning, hev sigra og kann opna boki og brjota hennar sju innsigle.»',
        6: 'Og eg såg at midt imillom stolen og dei fire livendi og midt imillom dei eldste stod eit lamb, liksom slagta, og det hadde sju horn og sju augo, det er dei sju Guds ånder som er utsende yver all jordi.',
        7: 'Og det kom og tok boki or den høgre handi hans som sat på stolen.',
        8: 'Og då det tok boki, fall dei fire livendi og dei fire og tjuge eldste ned for Lambet, og dei hadde kvar si harpa og gullskåler fulle med røykjelse, som er bønerne frå dei heilage.',
        9: 'Og dei syng ein ny song og segjer: «Du er verdig til å taka boki og opna hennar innsigle, av di du vart slagta og med ditt blod kjøpte oss åt Gud av alle ætter og tungemål og folk og landslydar.',
        10: 'Og du gjorde deim til eit kongerike og til prestar for vår Gud, og dei skal vera kongar på jordi!»',
        11: 'Og eg såg, og eg høyrde ei røyst av mange englar ikring stolen og dei fire livendi og dei eldste; og talet på deim var ti tusund gonger ti tusund og tusund gonger tusund.',
        12: 'Og dei sagde med høg røyst: «Lambet som er slagta, er verdigt til å få magt og rikdom og visdom og styrke og pris og æra og velsigning!»',
        13: 'Og kvar skapning som er i himmelen og på jordi og under jordi og på havet, og alt det som er i deim, høyrde eg segja: «Honom som sit på stolen, og Lambet tilhøyrer velsigning og pris og æra og magt i all æva!»',
        14: 'Og dei fire livendi sagde: «Amen!» Og dei fire og tjuge eldste fall ned og tilbad.',
    },
    6: {
        1: 'Og eg såg då Lambet opna eit av dei sju innsigli, og eg høyrde eit av dei fire livendi segja som med torerøyst: «Kom!»',
        2: 'Og eg såg, og sjå, ein kvit hest; og han som sat på honom, hadde ein boge, og det vart gjeve honom ei kruna, og han drog ut med siger og til siger.',
        3: 'Og då det opna det andre innsiglet, høyrde eg det andre livendet segja: «Kom!»',
        4: 'Og det kom ut ein annan hest, som var raud, og honom som sat på honom, vart det gjeve å taka freden burt frå jordi, og at dei skulde slagta kvarandre; og det var gjeve honom eit stort sverd.',
        5: 'Og då det opna det tridje innsiglet, høyrde eg det tridje livendet segja; «Kom!» Og eg såg, og sjå, ein svart hest; og han som sat på honom, hadde ei vegt i handi.',
        6: 'Og eg høyrde liksom ei røyst midt imillom dei fire livendi, som sagde: «Eit mål kveite for ein pening, og tri mål bygg for ein pening; men oljen og vinen skal du ikkje skada.»',
        7: 'Og då det opna det fjorde innsiglet, høyrde eg røysti av det fjorde livendet, som sagde: «Kom!»',
        8: 'Og eg såg, og sjå, ein gul hest; og han som sat på honom, hans namn var Dauden, og helheimen fylgde med honom: og det vart gjeve deim magt yver fjordeparten av jordi til å drepa med sverd og med svolt og med sott og ved villdyri på jordi.',
        9: 'Og då det opna det femte innsiglet, såg eg under altaret deira sjæler som var myrde for Guds ord og det vitnemål skuld som dei hadde.',
        10: 'Og dei ropa med høg røyst og sagde: «Herre, du heilage og sannordige, kor lenge drygjer du fyrr du held dom og hemner blodet vårt på deim som bur på jordi?»',
        11: 'Og det vart gjeve deim kvar ein lang, kvit kjole, og det vart sagt deim at dei skulde slå seg til ro endå ei liti stund, til dess talet vart fullt på deira medtenarar og brør som skulde verta ihelslegne liksom dei.',
        12: 'Og eg såg då det opna det sette innsiglet, og sjå, det vart ein stor jordskjelv, og soli vart svart som ein hårsekk, og månen vart som blod.',
        13: 'Og stjernorne på himmelen fall ned på jordi, liksom eit fiketre kastar sine umogne fikor ned når det vert rist av sterk vind.',
        14: 'Og himmelen kvarv i hop som ein bokrull som vert samanrulla, og kvart fjell og kvar øy vart flutt frå sin stad.',
        15: 'Og kongarne på jordi og stormennerne og herhovdingarne og dei rike og dei velduge og kvar træl og kvar fri mann gøymde seg i holor og i berghamrar.',
        16: 'Og dei segjer til fjelli og hamrarne: «Fall yver oss og gøym oss for hans åsyn som sit på kongsstolen og for vreiden til Lambet!',
        17: 'For deira store vreide-dag er komen, og kven kann standa seg?»',
    },
    7: {
        1: 'Deretter såg eg fire englar som stod på dei fire hyrno av jordi og heldt dei fire vindarne på jordi, so ingen vind skulde blåsa yver jordi eller yver havet eller på noko tre.',
        2: 'Og eg såg ein annan engel, som steig upp frå solovringi og hadde den livande Guds innsigle; og han ropa med høg røyst til dei fire englar som det var gjeve å skada jordi og havet,',
        3: 'og sagde: «Skad ikkje jordi eller havet eller trei, fyrr me fær sett innsigle på vår Guds tenarar i deira pannor!»',
        4: 'Og eg høyrde talet på deim som hadde fenge innsigle: eit hundrad og fire og fyrti tusund med innsigle utav alle ætter av Israels born:',
        5: 'av Juda-ætti tolv tusund med innsigle, av Ruben-ætti tolv tusund, av Gads-ætti tolv tusund,',
        6: 'av Assers-ætti tolv tusund, av Naftali-ætti tolv tusund, av Manasse-ætti tolv tusund,',
        7: 'av Simeons-ætti tolv tusund, av Levi-ætti tolv tusund, av Issakars-ætti tolv tusund,',
        8: 'av Sebulons-ætti tolv tusund, av Josefs-ætti tolv tusund, og av Benjamins-ætti tolv tusund med innsigle.',
        9: 'Deretter såg eg, og sjå: ein stor skare som ingen kunde telja, av alle folk og ætter og landslydar og tungemål, som stod framfor kongsstolen og Lambet, klædde i lange kvite klæde og med palmegreiner i henderne,',
        10: 'og dei ropa med høg røyst og sagde: «Frelsa høyrer til vår Gud, som sit på kongsstolen, og Lambet.»',
        11: 'Og alle englarne stod rundt um stolen og um dei eldste og dei fire livendi, og dei fall ned for stolen på sitt andlit og tilbad Gud',
        12: 'og sagde: «Amen! Velsigning og æra og visdom og takk og pris og magt og styrke høyrer til vår Gud i all æva! Amen.»',
        13: 'Og ein av dei eldste tok til ords og sagde til meg: «Desse som er klædde i dei lange kvite kjolarne, kven er dei, og kvar er dei komne ifrå?»',
        14: 'Eg sagde til honom: «Herre, du veit det.» Og han sagde til meg: «Dette er dei som kjem ut or den store trengsla, og dei hev tvege kjolarne sine og gjort deim kvite i blodet av Lambet.',
        15: 'Difor er dei for Guds kongsstol og tener honom dag og natt i hans tempel; og han som sit på stolen, skal reisa sin bustad yver deim.',
        16: 'Dei skal ikkje lenger hungra og ikkje lenger tyrsta; ikkje heller skal soli falla på deim eller nokon hite;',
        17: 'for Lambet som er midt framfor kongsstolen, skal vakta deim og leida deim til livsens vatskjeldor, og Gud skal turka kvar tåra frå augo deira.»',
    },
    8: {
        1: 'Og då det opna det sjuande innsiglet, vart det stilt i himmelen umkring ein halv time.',
        2: 'Og eg såg dei sju englarne som stend for Guds åsyn, og det vart gjeve deim sju basunar.',
        3: 'Og ein annan engel kom og stod ved altaret, og han hadde eit røykjefat av gull, og det vart gjeve honom mykje røykjelse, som han skulde leggja til bønerne frå alle dei heilage på det gullaltaret som var framfor stolen.',
        4: 'Og røyken av røykjelsen steig frå engelens hand upp for Gud med bønerne frå dei heilage.',
        5: 'Og engelen tok røykjefatet og fyllte det med eld frå altaret og kasta det på jordi; og det kom toredunar og røyster og ljoneldar og jordskjelv.',
        6: 'Og dei sju englarne som hadde dei sju basunarne, gjorde seg ferdige til å blåsa i deim.',
        7: 'Og den fyrste engelen bles. Og det kom hagl og eld, blanda med blod, og vart kasta ned på jordi; og tridjeparten av jordi vart uppbrend, og tridjeparten av trei vart uppbrend, og alt grønt gras vart uppbrend.',
        8: 'Og den andre engelen bles. Og det vart liksom eit stort fjell, brennande i eld, kasta i havet; og tridjeparten av havet vart til blod.',
        9: 'Og so døydde tridjeparten av dei skapningar i havet som hadde liv, og tridjeparten av skipi gjekk under.',
        10: 'Og den tridje engelen bles. Og frå himmelen fall ei stor stjerna, brennande som ein kyndel, og ho fall på tridjeparten av elvarne og på vatskjeldorne.',
        11: 'Og namnet på stjerna var malurt, og tridjeparten av vatnet vart til malurt, og mange menneskje døydde av vatnet, då det hadde vorte beiskt.',
        12: 'Og den fjorde engelen bles. Og tridjeparten av soli vart slegen, og tridjeparten av månen og tridjeparten av stjernorne, so tridjeparten av deim skulde verta formyrkt, og tridjeparten av dagen missa ljoset sitt, og natti like eins.',
        13: 'Og eg såg, og eg høyrde ein ørn som flaug under det høgste av himmelen og sagde med høg røyst: «Usæle, usæle, usæle dei som bur på jordi, for dei andre basunrøyster av dei tri englar som endå skal blåsa!»',
    },
    9: {
        1: 'Og den femte engelen bles. Og eg såg eg ei stjerna som hadde falle frå himmelen ned på jordi, og ho fekk lykelen til avgrunnsbrunnen.',
        2: 'Og ho opna avgrunnsbrunnen, og ein røyk steig upp or brunnen, lik røyken av ein stor omn, og soli og lufti vart myrkte av røyken frå brunnen.',
        3: 'Og or røyken kom grashoppar ut på jordi, og det vart gjeve deim magt, slik som skorpionarne på jordi hev,',
        4: 'og det vart sagt deim at dei ikkje måtte skada graset på jordi eller noko grønt eller noko tre, men berre dei menneskje som ikkje hadde Guds innsigle på pannorne.',
        5: 'Og det vart gjeve deim at dei ikkje skulde drepa deim, men pina deim i fem månader; og pinsla av deim var som pinsla av ein skorpion når han sting eit menneskje.',
        6: 'Og i dei dagar skal folk søkja dauden og ikkje finna honom, og stunda etter å døy, og dauden skal fly frå deim.',
        7: 'Og grashopparne såg ut som hestar, tilbudde til strid; og på hovudi deira var det liksom krunor av gull, og andliti deira var som menneskjeandlit.',
        8: 'Og dei hadde hår som kvendehår, og tennerne deira var som løvetenner.',
        9: 'Og dei hadde brynjor liksom jarnbrynjor, og ljoden av vengjerne deira var som ljod av vogner når mange hestar renner til strid.',
        10: 'Og dei hadde stertar liksom skorpionar, og det var broddar i stertarne deira, og dei hadde magt til å skada menneski fem månader.',
        11: 'Til konge yver seg hev dei avgrunnsengelen, hans namn er på hebraisk Abaddon, og på gresk hev han namnet Apollyon.',
        12: 'Det fyrste usæle er yverstade; sjå, det kjem tvo usæle etter dette!',
        13: 'Og den sette engelen bles. Og eg høyrde ei røyst frå dei fire horni på det gullaltaret som stod framfor Gud,',
        14: 'og ho sagde til den sette engelen, som hadde basunen: «Løys dei fire englarne som er bundne ved den store elvi Eufrat!»',
        15: 'Og dei fire englarne vart løyste, dei som hadde vore ferdige på timen og dagen og månaden og året til å drepa tridjeparten av menneski.',
        16: 'Og talet på herarne av hestfolk var tvo gonger ti tusund gonger ti tusund; eg høyrde talet på deim.',
        17: 'Og soleis såg eg i syni hestarne og deim som sat på deim: dei hadde eldraude og myrkraude og svåvelgule brynjor; og hovudi på hestarne var som løvehovud, og or munnarne deira fer det ut eld og røyk og svåvel.',
        18: 'Av desse tri: elden og røyken og svåvelet, som for ut or munnarne deira, vart tridjeparten av menneski drepen.',
        19: 'For magti åt hestarne ligg i munnen deira og halen deira, for halarne deira er som ormar og hev hovud, og med deim gjer dei skade.',
        20: 'Og dei andre menneskje, som ikkje vart drepne i desse plågorne, vende ikkje um frå dei verki deira hender hadde gjort, so dei heldt upp med å tilbeda dei vonde ånder og avgudarne av gull og av sylv og av kopar og av stein og av tre, som korkje kann sjå eller høyra eller ganga.',
        21: 'Og dei vende ikkje um frå mordgjerningarne sine eller frå trolldomskunsterne sine eller frå hordomen sin eller frå tjuvskapen sin.',
    },
    10: {
        1: 'Og eg såg ein annan veldug engel stiga ned frå himmelen, sveipt i ei sky, og regnbogen var yver hovudet hans, og hans åsyn var som soli, og føterne hans som eldstolpar.',
        2: 'Og han hadde i handi ei liti opna bok, og han sette sin høgre fot på havet og den vinstre på jordi.',
        3: 'Og han ropa med høg røyst, som ei løva burar, og då han hadde ropa, tala dei sju toredunar med sine røyster.',
        4: 'Og då dei sju toredunar hadde tala med sine røyster, vilde eg til å skriva; og eg høyrde ei røyst frå himmelen som sagde til meg: «Set innsigle for det som dei sju toredunar tala, og skriv det ikkje upp!»',
        5: 'Og engelen, som eg såg standa på havet og på jordi, lyfte handi upp mot himmelen,',
        6: 'og svor ved honom som liver i all æva, som skapte himmelen og det som er i honom, og jordi og det som er på henne, og havet og det som er i det, at det ikkje lenger skal vera nokor tid.',
        7: 'Men i dei dagar då røysti av den sjuande engelen vert høyrd, når han skal blåsa, då skal og Guds løyndom vera fullenda, so som han forkynte for tenarane sine, profetarne.',
        8: 'Og den røysti som eg hadde høyrt frå himmelen, tala atter med meg og sagde: «Gakk og tak den litle opne boki i handi på den engelen som stend på havet og på jordi!»',
        9: 'Og eg gjekk burt til engelen og sagde til honom: «Gjev meg den litle boki!» Og han sagde til meg: «Tak og et henne, og ho skal svida i magen din; men i munnen din skal ho vera søt som honning.»',
        10: 'Og eg tok den litle boki or handi på engelen og åt henne, og ho var søt som honning i munnen min, men då eg hadde ete henne, sveid det i magen min.',
        11: 'Og dei segjer til meg: «Du skal atter spå um mange landslydar og folk og tungemål og kongar.»',
    },
    11: {
        1: 'Og det vart gjeve meg ei røyr liksom ein stav, med dei ordi: «Statt upp og mæl Guds tempel og altaret og deim som tilbed der!',
        2: 'Men fyregarden utanfor templet, lat honom vera og mæl honom ikkje! for han er gjeven åt heidningarne, og dei skal trøda ned den heilage byen i tvo og fyrti månader.',
        3: 'Og eg vil gjeva mine tvo vitne, at dei skal vera profetar i tusund og tvo hundrad og seksti dagar, klædde i sekk.',
        4: 'Dette er dei tvo oljetrei og dei tvo ljosestakarne som stend framfor Herren yver jordi.',
        5: 'Og dersom nokon vil gjera deim skade, so gjeng det eld ut or munnen deira og fortærer fiendarne deira; ja, dersom nokon vil gjera deim skade, skal han soleis verta drepen.',
        6: 'Desse hev magt til å lata att himmelen, so de ikkje skal falla regn i dei dagar dei er profetar; og dei hev magt yver vatni til å umskapa deim til blod og til å slå jordi med allslag plåga, so ofte dei vil.',
        7: 'Og når dei hev fullført sitt vitnemål, skal det dyret som stig upp or avgrunnen, føra strid med deim og vinna på deim og drepa deim.',
        8: 'Og liki deira skal liggja på gatorne i den store byen, den som i åndeleg tyding vert kalla Sodoma og Egyptarland, der som og deira herre vart krossfest.',
        9: 'Og nokre av landslydarne og ætterne og tungemåli og folki skal sjå liki deira tri dagar og ein halv og ikkje lata liki deira verta lagde i grav.',
        10: 'Og dei som bur på jordi, skal gleda seg yver deim og fagna seg og senda kvarandre gåvor, av di desse tvo profetarne var til plåga for deim som bur på jordi.»',
        11: 'Og etter dei tri dagar og ein halv kom det livs-ande frå Gud i deim, og dei stod på føterne, og ein stor otte fall på deim som såg deim.',
        12: 'Og dei høyrde ei høg røyst frå himmelen som sagde til deim: «Stig upp her!» Og dei steig upp til himmelen i skyi, og fiendarne deira såg deim.',
        13: 'Og i same stundi kom det ein stor jordskjelv, og tiandeparten av byen fall, og sju tusund mann vart drepne i jordskjelven; og dei andre vart forfærde og gav Gud i himmelen æra.',
        14: 'Det andre usæle er yverstade; sjå, det tridje usæle kjem snart.',
        15: 'Og den sjuande engelen bles. Og det vart høyrt høge røyster i himmelen, som sagde: «Kongedømet yver verdi er tilfalle vår Herre og den han salva, og han skal vera konge i all æva.»',
        16: 'Og dei fire og tjuge eldste, som sit framfor Gud på stolarne sine, fall ned på sitt andlit og tilbad Gud',
        17: 'og sagde: «Me takkar deg, Herre Gud, du allmegtige, du som er og som var, at du hev teke di store magt og vorte konge.',
        18: 'Og heidningarne hev vorte vreide, og din vreide er komen, og den tid då dei daude skal dømast, og då du skal løna dine tenarar, profetarne og dei heilage og deim som ottast ditt namn, dei små og dei store, og då du skal øyda deim som øyder jordi.»',
        19: 'Og Guds tempel i himmelen vart upplate, og hans sambandskista vart sedd i templet hans; og det kom ljoneldar og røyster og toredunar og jordskjelv og stort hagl.',
    },
    12: {
        1: 'Og eit stort teikn vart set i himmelen: ei kvinna klædd med soli, og med månen under føterne, og på hovudet hadde ho ei kruna av tolv stjernor.',
        2: 'Og ho var med barn og skreik i barnsnaud og i harde føderider.',
        3: 'Og eit anna teikn vart set i himmelen, og sjå: ein stor eldraud drake, som hadde sju hovud og ti horn og på hovudi sine sju krunor.',
        4: 'Og sterten hans drog tridjeparten av stjernorne på himmelen med seg og kasta deim ned på jordi; og draken stod framfor kvinna som skulde føda, so han kunde gløypa barnet hennar når ho hadde født det.',
        5: 'Og ho fødde eit gutebarn, som skal styra alle heidningarne med jarnstav, og barnet hennar vart upprykt til Gud og til hans kongsstol.',
        6: 'Og kvinna flydde ut i øydemarki, der ho hev ein stad som Gud hev laga til åt henne, for at dei skal næra henne der i tusund tvo hundrad og seksti dagar.',
        7: 'Og det vart ein strid i himmelen: Mikael og hans englar stridde med draken, og draken stridde, og hans englar.',
        8: 'Og dei vann ikkje, og deira stad vart ikkje heller meir funnen i himmelen.',
        9: 'Og den store draken vart kasta ned, den gamle ormen, han som vert kalla djevelen og Satan, han som dårar heile verdi; han vart kasta ned på jordi, og englarne hans vart kasta ned med honom.',
        10: 'Og eg høyrde ei høg røyst i himmelen, som sagde: «Frå no eig vår Gud frelsa og krafti og riket, og den han salva, hev magti; for klagaren mot brørne våre er kasta ned, han som klaga deim for vår Gud dag og natt.',
        11: 'Og dei hev vunne yver honom i kraft av blodet av Lambet og det ordet dei vitna; og dei hadde ikkje livet sitt kjært, alt til dauden.',
        12: 'Difor fagna dykk, de himlar, og de som bur i deim! Usæle jordi og havet! for djevelen hev fare ned til dykk i stor vreide, då han veit at han berre hev ei liti tid.»',
        13: 'Og då draken såg at han var nedkasta til jordi, forfylgde han kvinna som hadde født guten.',
        14: 'Og dei tvo vengjerne på den store ørnen vart gjevne til kvinna, so ho skulde fljuga ut i øydemarki til sin stad, der ho fær si føda ei tid og tider og ei halv tid, langt ifrå augo på ormen.',
        15: 'Og ormen spruta or gapet sitt vatn som ei elv etter kvinna, for å riva henne burt med elvi.',
        16: 'Men jordi kom kvinna til hjelp, og jordi opna sin munn og svelgde elvi som draken spruta ut or gapet sitt.',
        17: 'Og draken vart arg på kvinna og gjekk burt og skulde strida med dei andre av hennar ætt, dei som held Guds bod og hev Jesu vitnemål. Og eg stod på sanden ved havet.',
    },
    13: {
        1: 'Og eg såg eit dyr stiga upp or havet, det hadde ti horn og sju hovud, og på horni sine ti krunor, og på hovudi sine spottings namn.',
        2: 'Og dyret som eg såg, var likt ein leopard, og føterne på det var som på ein bjørn, og gapet som eit løvegap. Og draken gav det si kraft og sin kongsstol og stor magt.',
        3: 'Og eg såg eit av hovudi på det liksom såra til ulivs; og ulivssåret vart lækt, og all jordi undrast og fylgde etter dyret;',
        4: 'og dei tilbad draken for di han hadde gjeve dyret magt, og dei tilbad dyret og sagde: «Kven er lik dyret, og kven kann strida mot det?»',
        5: 'Og det vart gjeve det ein munn som tala store og spottande ord, og det vart gjeve det magt til å halda på i tvo og fyrti månader.',
        6: 'Og det opna munnen sin til spottingar mot Gud, til å spotta hans namn og hans bustad, deim som bur i himmelen.',
        7: 'Og det vart det gjeve å føra strid mot dei heilage og vinna på deim, og det vart gjeve det magt yver kvar ætt og kvar landslyd og kvart tungemål og kvart folk.',
        8: 'Og alle som bur på jordi, skal tilbeda det, kvar den som ikkje frå verdi vart grunnlagd, hev fenge namnet sitt skrive i livsens bok hjå Lambet som er slagta.',
        9: 'Dersom nokon hev øyra, so høyre han!',
        10: 'Um nokon fører i fengsel, han skal i fengsel. Um nokon drep med sverd, han skal drepast med sverd. Her er tolmodet og trui til dei heilage.',
        11: 'Og eg såg eit anna dyr stiga upp or jordi, og det hadde tvo horn liksom eit lamb, og tala liksom ein drake.',
        12: 'Og det brukar heile magti åt det fyrste dyret for augo på det, og gjer at jordi og dei som bur på henne, tilbed det fyrste dyret, som ulivssåret vart lækt på.',
        13: 'Og det gjer store teikn, so det endå fær eld til å falla ned frå himmelen på jordi for augo på menneski.',
        14: 'Og det dårar deim som bur på jordi, for dei teikn skuld som det hev fenge magt til å gjera for augo på dyret, med di det segjer til deim som bur på jordi, at dei skal gjera eit bilæte åt det dyret som hev såret av sverdet og vart i live.',
        15: 'Og det fekk magt til å gjeva dyrebilætet livs-ande, so dyrebilætet jamvel kunde tala, og gjera so, at alle dei som ikkje vilde tilbeda dyrebilætet, skulde drepast.',
        16: 'Og det gjer at alle, både små og store, rike og fatige, frie og trælar, fær eit merke på si høgre hand eller på panna si,',
        17: 'og at ingen kann kjøpa eller selja, utan den som hev merket, namnet på dyret eller talet for dette namnet.',
        18: 'Her er det visdomen! Den som hev vit, han rekne ut talet til dyret; for det er talet for eit menneskje, og talet for det er seks hundrad og seks og seksti.',
    },
    14: {
        1: 'Og eg såg, og sjå: Lambet stod på Sionsfjellet og med det hundrad og fire og fyrti tusund, som hadde dess namn og dess Faders namn skrive på panna.',
        2: 'Og eg høyrde ei røyst frå himmelen liksom ljoden av mange vatn og som ljoden av sterk tora, og eg høyrde ljod av harpespelarar som spela på harporne sine.',
        3: 'Og dei song ein ny song framfor kongsstolen og for dei fire livendi og dei eldste; og ingen kunde læra songen, utan dei hundrad og fire og fyrti tusund, dei som er kjøpte frå jordi.',
        4: 'Desse er dei som ikkje hev gjort seg ureine med kvende; for dei er som møyar. Desse er dei som fylgjer Lambet kvar helst det gjeng. Desse er kjøpte frå menneski til ei fyrstegrøda for Gud og Lambet,',
        5: 'og i deira munn er ikkje funne svik; for dei er utan lyte.',
        6: 'Og eg såg ein annan engel fljuga under det høgste av himmelen; han hadde eit ævelegt evangelium å forkynna deim som bur på jordi og alle folk og ætter og tungemål og landslydar,',
        7: 'og han sagde med høg røyst: «Ottast Gud og gjev honom æra! for timen til hans dom er komen; og tilbed honom som gjorde himmelen og jordi og havet og vatskjeldorne!»',
        8: 'Og endå ein annan engel fylgde etter og sagde: «Falli, falli er Babylon, den store, ho som hev skjenkt alle folki av sin hordoms vreide-vin.»',
        9: 'Og endå ein tridje engel fylgde etter deim og sagde med høg røyst: «Dersom nokon tilbed dyret og bilætet av det og tek merket på panna si eller på handi si,',
        10: 'so skal han og drikka av Guds vreide-vin, som er skjenkt ublanda i hans harms skål, og han skal verta pint med eld og svåvel for augo på dei heilage englar og Lambet.',
        11: 'Og røyken av pinsla deira stig upp i all æva, og dei hev ikkje kvila dag eller natt, dei som tilbed dyret og bilætet av det, og kvar ein som tek namnemerket til det.»',
        12: 'Her er tolmodet til dei heilage, dei som held Guds bod og trui på Jesus.',
        13: 'Og eg høyrde ei røyst frå himmelen som sagde: «Skriv: Sæle er dei daude som døyr i Herren heretter! Ja, segjer Anden, dei skal kvila frå arbeidet sitt, for gjerningarne deira fylgjer med deim.»',
        14: 'Og eg såg, og sjå: ei kvit sky, og på skyi sat ein som var lik ein menneskjeson, og han hadde ei gullkruna på hovudet og ein kvass sigd i handi.',
        15: 'Og ein annan engel kom ut or templet og ropa med høg røyst til honom som sat på skyi: «Send ut sigden din og skjer! for timen til skurden er komen; for jordi er mogi til skurd.»',
        16: 'Og han som sat på skyi, let sigden sin fara yver jordi, og jordi vart skori.',
        17: 'Og ein annan engel kom ut or templet i himmelen, og han hadde ein kvass sigd, han og.',
        18: 'Og endå ein annan engel kom ut frå altaret, og han hadde magt yver elden og ropa med høg røyst til honom som hadde den kvasse sigden: «Send ut den kvasse sigden din og skjer druvorne av vintreet på jordi; for beri på det er mogne!»',
        19: 'Og engelen let sigden sin fara yver jordi og skar frukti av vintreet på jordi og kasta henne i den store vinpersa til Guds vreide.',
        20: 'Og vinpersa vart trødd utanfor byen, og det gjekk blod ut frå persa heilt upp til beisli på hestarne, so langt som tusund og seks hundrad stadier.',
    },
    15: {
        1: 'Og eg såg eit anna teikn i himmelen, stort og underlegt: sju englar, som hadde dei sju siste plågorne; for med deim er Guds vreide fullenda.',
        2: 'Og eg såg liksom eit glashav, blanda med eld, og deim som hadde vunne siger yver dyret og yver bilætet av det og yver namnetalet på det, såg eg standa ved glashavet og halda Guds harpor.',
        3: 'Og dei song songen åt Moses, Guds tenar, og songen åt Lambet og sagde: «Store og underlege er dine gjerningar, Herre Gud, du allmegtige! Rettferdige og sanne er dine vegar, du konge yver folki!',
        4: 'Kven skulde ikkje ottast, Herre, og æra ditt namn? for einast du er heilag; for alle folki skal koma og tilbeda for di åsyn, for dine rettferdige domar hev vorte openberre!»',
        5: 'Og deretter såg eg, og sjå: Templet med vitnemålstjeldet i himmelen vart opna,',
        6: 'og dei sju englarne som hadde dei sju plågorne, kom ut or templet, klædde i reint og skinande linty og umbundne um bringa med gullbelte.',
        7: 'Og eit av dei fire livendi gav dei sju englarne sju gullskåler, fyllte med Guds vreide, hans som liver i all æva.',
        8: 'Og templet var fyllt med røyk av Guds herlegdom og av hans magt, og ingen kunde ganga inn i templet fyrr dei sju plågorne frå dei sju englarne var fullenda.',
    },
    16: {
        1: 'Og eg høyrde ei høg røyst frå templet, som sagde til dei sju englarne: «Gakk og tøm dei sju skålerne med Guds vreide ut på jordi!»',
        2: 'Og den fyrste gjekk og tømde si skål på jordi; og det kom ein vond og våleg svoll på dei menneskje som hadde merket åt dyret, og som tilbad bilætet av det.',
        3: 'Og den andre engelen tømde si skål i havet, og det vart til blod som av ein daud mann, og kvar livande sjæl i havet døydde.',
        4: 'Og den tridje engelen tømde si skål i elvarne og vatskjeldorne, og det vart til blod.',
        5: 'Og eg høyrde engelen yver vatni segja: «Rettferdig er du som er og som var, du heilage, at du hev halde slik dom.',
        6: 'For blod av heilage og av profetar rende dei ut, og blod gav du deim å drikka; for dei er det verde.»',
        7: 'Og eg høyrde altaret segja: «Ja, Herre Gud, du allmegtige! Sanne og rettferdige er dine domar!»',
        8: 'Og den fjorde engelen tømde si skål på soli, og ho fekk magt til å brenna menneski med eld.',
        9: 'Og menneski vart brende av stor hite, og dei spotta Guds namn, hans som hev magt yver desse plågorne, og dei vende ikkje um, so dei gav honom æra.',
        10: 'Og den femte engelen tømde si skål yver kongsstolen til dyret; og riket til det vart formyrkt, og dei togg tungorne sine av pinsla,',
        11: 'og dei spotta Gud i himmelen for pinslorne sine og svollarne sine, og vende ikkje um frå sine gjerningar.',
        12: 'Og den sette engelen tømde si skål i den store elvi Eufrat, og vatnet hennar turka upp, so vegen skulde verta rudd for kongarne frå Austerland.',
        13: 'Og eg såg at det or munnen på draken og or munnen på dyret og or munnen på den falske profeten kom ut tri ureine ånder liksom paddor.',
        14: 'For dei er djevle-ånder som gjer teikn, og dei gjeng ut til kongarne i heile mannheimen til å sanka deim saman til striden på den store dagen åt Gud den allmegtige.',
        15: 'Sjå, eg kjem som ein tjuv! Sæl er den som vaker og vaktar klædi sine, so han ikkje skal ganga naken, og dei skal sjå hans skam!',
        16: 'Og han førde deim saman til den stad som heiter på hebraisk Harmageddon.',
        17: 'Og den sjuande engelen tømde si skål i lufti, og ei høg røyst kom ut frå templet i himmelen, frå kongsstolen, og sagde: «Det er gjort!»',
        18: 'Og der kom ljoneldar og røyster og toredunar, og det vart ein stor jordskjelv, ein slik at det, alt sidan menneskja vart til på jordi, ikkje hev vore ein sovoren jordskjelv, so stor.',
        19: 'Og den store byen vart kløyvd i tri partar, og byarne åt folki fall, og Babylon, den store, vart ihugkomi for Gud, at han skulde gjeva henne skåli med vinen av sin strenge vreide.',
        20: 'Og kvar øy kvarv burt, og fjell vart ikkje funne.',
        21: 'Og stort hagl, som hundrad pund tungt, fall ned frå himmelen på menneski, og menneski spotta Gud for plåga av haglet; for den plåga var ovleg stor.',
    },
    17: {
        1: 'Og ein av dei sju englarne som hadde dei sju skålerne, kom og tala med meg og sagde: «Kom, eg skal visa deg domen yver den store skjøkja, som sit ved dei mange vatni,',
        2: 'henne som kongarne på jordi hev hora med, og dei som bur på jordi, vart drukne av hennar hordoms vin.»',
        3: 'Og han førde meg i åndi burt i ei øydemark, og eg såg ei kvinna sitja på eit skarlakraudt dyr, som var fullt med spottings namn og hadde sju hovud og ti horn.',
        4: 'Og kvinna var klædd i purpur og skarlak og lyste av gull og dyre steinar og perlor; ho hadde i handi ei gullskål full med styggedom og med ureinska av hordomen hennar.',
        5: 'Og på panna hennar var skrive eit namn, ein løyndom: Babylon, den store, mor åt skjøkjorne og styggedomarne på jordi.',
        6: 'Og eg såg kvinna fullskjenkt med blodet av dei heilage og med blodet av Jesu vitne, og eg undra meg storleg då eg såg henne.',
        7: 'Og engelen sagde til meg: «Kvi undra du deg? Eg vil segja deg løyndomen med kvinna og med dyret som ber henne, og som hev dei sju hovudi og ti horni.',
        8: 'Det dyret du såg, det var og er ikkje, og det skal stiga upp or avgrunnen og fara burt til undergang; og dei som bur på jordi, som ikkje hev namni sine skrivne i livsens bok frå verdi vart grunnlagd, dei skal undra seg når dei ser at dyret var og ikkje er og skal koma att.',
        9: 'Her spørst det um vitet som hev visdom! Dei sju hovudi er sju fjell, som kvinna sit på,',
        10: 'og dei er sju kongar; dei fem er falne, den eine er til, den andre er ikkje komen endå; og når han kjem, skal han berre halda seg ei stutt tid.',
        11: 'Og dyret som var og ikkje er, det er sjølv den åttande og er og ein av dei sju og fer burt til undergang.',
        12: 'Og dei ti horni som du såg, er ti kongar som ikkje endå hev fenge rike, men dei fær magt som kongar ein time saman med dyret.',
        13: 'Desse hev same tanken, og si kraft og magt gjev dei til dyret.',
        14: 'Desse skal strida mot Lambet, og Lambet skal vinna yver deim, for det er herren yver herrar og kongen yver kongar, og dei som er med det, dei som er kalla og utvalde og trufaste.»',
        15: 'Og han sagde til meg: «Dei vatni som du såg der skjøkja sit, er landslydar og flokkar og folk og tungemål.',
        16: 'Og dei ti horni som du såg, og dyret, desse skal hata skjøkja og gjera henne aud og naki, og kjøtet hennar skal dei eta, og henne sjølv skal dei brenna upp med eld.',
        17: 'For Gud gav deim i hjarta å fullføra hans tanke og fullføra den eine og same tanken og gjeva dyret sitt rike, til dess Guds ord er fullførde.',
        18: 'Og kvinna som du såg, er den store byen som hev kongeveldet yver kongarne på jordi.»',
    },
    18: {
        1: 'Deretter såg eg ein annan engel stiga ned frå himmelen; han hadde stor magt, og jordi vart upplyst av hans herlegdom.',
        2: 'Og han ropa med sterk røyst og sagde: «Falli, falli er Babylon, den store, og ho hev vorte bustad for vonde ånder, eit fangebol for alle ureine ånder, og eit fangebol for alle ureine og styggjelege fuglar.',
        3: 'For av hennar hordoms vreide-vin hev alle folki drukke, og kongarne på jordi hev drive hor med henne, og kjøpmennerne på jordi hev vorte rike av hennar ovlivnads fylla.»',
        4: 'Og eg høyrde ei onnor røyst frå himmelen, som sagde: «Gakk ut frå henne, de mitt folk, so de ikkje skal verta medskuldige i synderne hennar og ikkje få noko av plågorne hennar!',
        5: 'For synderne hennar når heilt upp til himmelen, og Gud hev kome hennar urettferdige gjerningar i hug.',
        6: 'Gjev henne att som ho hev gjeve, og gjev henne tvifaldt etter hennar gjerningar! Skjenk henne tvifaldt i den skåli som ho hev skjenkt i!',
        7: 'So mykje som ho hev æra seg sjølv og livt i ovlivnad, so mykje pinsla og sorg gjeve de henne! For ho segjer i sitt hjarta: «Eg sit som dronning og er ikkje enkja, og sorg skal eg ikkje sjå.»',
        8: 'Difor skal plågorne hennar koma på ein dag: daude og sorg og svolt, og ho skal verta uppbrend med eld; for sterk er Herren Gud, som dømde henne.',
        9: 'Og kongarne på jordi som hev drive hor og ovlivnad med henne, skal gråta og barma seg yver henne, når dei ser røyken av hennar brand,',
        10: 'medan dei stend langt undan av otte for pinsla hennar og segjer: «Usæl, usæl du store by Babylon, du sterke by! at domen din er komen i ein time!»',
        11: 'Og kjøpmennerne på jordi græt og syrgjer yver henne, av di ingen lenger kjøper varorne deira:',
        12: 'varor av gull og sylv og dyre steinar og perlor og kostelegt linty og purpur og silke og skarlak og allslag angande tre og allslag kjerald av filsbein og allslag kjerald av dyrverdigt tre og kopar og jarn og marmor',
        13: 'og kanel og hårsalve og røykjelse og myrra og røykjeverk og vin og olje og fint mjøl og kveite og storfe og sauer og hestar og vogner og trælar og menneskje-sjæler.',
        14: 'Og den frukt som di sjæl hadde lyst til, er komi burt frå deg, og alt det feite og glimande er kome burt frå deg, og aldri skal nokon finna det meir.',
        15: 'Dei som handlar med desse ting, som hev vorte rike ved henne, skal standa langt undan av otte for pinsla hennar og gråta og syrgja',
        16: 'og segja: «Usæl, usæl den store byen, som var klædd i kostelegt linty og purpur og skarlak, og lyste av gull og dyre steinar og perlor; at so stor ein rikdom er øydd i ein time!»',
        17: 'Og kvar styremann og kvar skipsførar og alle sjøfolk og alle dei som fer på havet, stod langt undan',
        18: 'og ropa då dei såg røyken av hennar brand, og sagde: «Kven er lik den store byen?»',
        19: 'Og dei kasta dust på hovudi sine og ropa med gråt og sorg og sagde: «Usæl, usæl den store byen, der alle som hadde skip på havet, vart rike av hennar eignaluter, at ho vart lagd i øyde i ein time!»',
        20: 'Fagna deg yver henne, du himmel, og de apostlar og profetar, av di Gud hev halde dom for dykk yver henne!»',
        21: 'Og ein veldug engel lyfte ein stein som ein stor kvernstein og kasta honom i havet og sagde: «So skal Babylon, den store byen, med hast verta nedkasta og ikkje meir verta funnen.',
        22: 'Og ingen ljod av harpespelarar og songarar og fløytelåtarar og lurblåsarar skal lenger verta høyrd i deg, og ingen som driv nokor kunst, skal lenger verta funnen i deg, og ingen ljod av kvern lenger verta høyrd i deg.',
        23: 'Og ljos av lampa skal ikkje lenger skina i deg, og røyst av brudgom og brur ikkje lenger verta høyrd i deg; for dine kjøpmenner var storkararne på jordi, av di alle folk vart dåra ved din trolldom.',
        24: 'Og i henne vart det funne blod av profetar og heilage og av alle deim som er myrde på jordi.»',
    },
    19: {
        1: 'Deretter høyrde eg liksom ei høg røyst av ein stor skare i himmelen, som sagde: «Halleluja! Frelsa og æra og magti tilhøyrer vår Gud!',
        2: 'For sanne og rettferdige er hans domar; for han hev dømt den store skjøkja, ho som øydelagde jordi med sin hordom, og han hev kravt blodet av sine tenarar ut or hennar hand!»',
        3: 'Og dei sagde ein gong til: «Halleluja! Og røyken av henne stig upp i all æva.»',
        4: 'Og dei fire og tjuge eldste og dei fire livendi fall ned og tilbad Gud, som sat på kongsstolen, og sagde: «Amen! halleluja!»',
        5: 'Og det kom ei røyst ut frå kongsstolen og sagde: «Lova vår Gud, alle hans tenarar, og de som ottast honom, både små og store!»',
        6: 'Og eg høyrde liksom ei røyst av ein stor skare, og som ein ljod av mange vatn, og som ein ljod av sterke toredunar, som sagde: «Halleluja! for Herren, Gud den allmegtige, hev vorte konge!',
        7: 'Lat oss gleda og fagna oss og gjeva honom æra, for brudlaupet åt Lambet er kome, og bruri hans hev butt seg til!',
        8: 'Og det er henne gjeve å klæda seg i reint og skinande fint linty; for det fine lintyet er dei rettferdige gjerningar av dei heilage.»',
        9: 'Og han segjer til meg: «Skriv: Sæle er dei som er bedne til brudlaups-nattverden åt Lambet!» Og han segjer til meg: «Dette er Guds sanne ord.»',
        10: 'Og eg fall ned for føterne hans og vilde tilbeda honom, og han segjer til meg: «Sjå til du ikkje gjer det! eg er medtenar til deg og brørne dine, som hev Jesu vitnemål. Tilbed Gud! For Jesus vitnemål er anden med profetordet.»',
        11: 'Og eg såg himmelen opna, og sjå: ein kvit hest; og den som sat på honom, heiter «Trufast og sannordig», og han dømer og strider med rettferd.',
        12: 'Augo hans er som eldsloge, og på hovudet hans er det mange krunor; han hev eit namn skrive som ingen kjenner, utan han sjølv.',
        13: 'Og han er klædd i ein klædnad, duppa i blod, og hans namn er kalla: «Guds ord».',
        14: 'Og herarne i himmelen fylgde honom på kvite hestar og klædde i kvitt og reint fint linty.',
        15: 'Og or munnen hans gjeng det ut eit kvast sverd til å slå heidningarne med, og han skal styra deim med jarnstav, og han trøder persa med den strenge vreide-vin frå Gud, den allmegtige.',
        16: 'Og han hev på sin klædnad og på si lend eit namn skrive: «Kongen yver kongar og herren yver herrar.»',
        17: 'Og eg såg ein engel som stod i soli, og han ropa med høg røyst og sagde til alle fuglar som flyg under det høgste av himmelen: «Kom og sanka dykk til Guds store matmål:',
        18: 'til å eta kjøt av kongar og kjøt av herhovdingar og kjøt av velduge og kjøt av hestar og kjøt av deim som sat på deim, og kjøt av alle, frie og trælar, små og store!»',
        19: 'Og eg såg dyret og kongarne på jordi og herarne deira samankomne til å føra strid mot honom som sat på hesten, og mot hans her.',
        20: 'Og dyret vart gripe, og saman med det den falske profeten, han som for augo på det hadde gjort dei teikni han hadde dåra deim med som tok merket åt dyret og tilbad bilætet av det. Desse tvo vart kasta livande i eldsjøen som brenn med svåvel.',
        21: 'Og dei andre vart drepne med sverdet hans som sat på hesten, det som gjekk ut or munnen hans. Og alle fuglarne vart metta av kjøtet deira.',
    },
    20: {
        1: 'Og eg såg ein engel stige ned frå himmelen, som hadde lykelen til avgrunnen og ei stor lekkja i handi si.',
        2: 'Og han greip draken, den gamle ormen, som er djevelen og Satan, og batt honom for tusund år',
        3: 'og kasta honom i avgrunnen og læste honom inne og sette innsigle yver honom, so han ikkje lenger skulde dåra folki, til dess dei tusund år var fullenda. Og etter den tid skal han verta løyst ei liti stund.',
        4: 'Og eg såg stolar, og dei sette seg på deim, og det vart gjeve deim magt til å halda dom; og eg såg deira sjæler som var halshogne for Jesu vitnemål og Guds ord skuld, og deim som ikkje hadde tilbede dyret eller bilætet av det, og ikkje teke merket på panna si og på handi si; og dei vart livande og rådde saman med Kristus i tusund år.',
        5: 'Men dei andre daude vart ikkje livande att, fyrr dei tusund år var fullenda. Dette er den fyrste uppstoda.',
        6: 'Sæl og heilag er den som hev lut i den fyrste uppstoda; yver deim hev den andre dauden ingi magt, men dei skal vera Guds og Kristi prestar og råda saman med honom i tusund år.',
        7: 'Og når dei tusund åri er fullenda, skal Satan verta løyst ut or sitt fengsel,',
        8: 'og han skal ganga ut og dåra folki ved dei fire jordhyrno, Gog og Magog, og føra deim saman til strid, og talet på deim er som havsens sand.',
        9: 'Og dei drog upp på den vide jordflata og kringsette lægret åt dei heilage og den byen som Gud elska. Og det fall eld ned ifrå himmelen frå Gud og øydde deim.',
        10: 'Og djevelen, som hadde dåra deim, vart kasta i sjøen med eld og svåvel, der dyret og den falske profeten var; og dei skal verta pinte dag og natt i all æva.',
        11: 'Og eg såg ein stor kvit kongsstol, og honom som sat derpå; og jordi og himmelen flydde frå hans åsyn, og det fanst ikkje nokon stad for deim.',
        12: 'Og eg såg dei daude, små og store, standa framfor Gud, og bøker vart opna, og ei onnor bok vart opna, det er livsens bok. Og dei daude vart dømde etter det som var skrive i bøkerne, etter gjerningarne sine.',
        13: 'Og havet gav att dei daude som var i det, og dauden og helheimen gav att dei daude som var i deim, og dei vart dømde kvar etter sine gjerningar.',
        14: 'Og dauden og helheimen vart kasta i eldsjøen. Dette er den andre dauden: eldsjøen.',
        15: 'Og dersom nokon ikkje vart funnen uppskriven i livsens bok, so vart han kasta i eldsjøen.',
    },
    21: {
        1: 'Og eg såg ein ny himmel og ei ny jord; for den fyrste himmelen og den fyrste jordi hadde kvorve burt, og havet er ikkje meir.',
        2: 'Og eg såg den heilage byen, det nye Jerusalem, stiga ned ifrå himmelen frå Gud, budd som ei brur som er prydd for brudgomen sin.',
        3: 'Og eg høyrde ei høg røyst frå kongsstolen, som sagde: «Sjå, Guds bustad er hjå menneski, og han skal bu hjå deim; og dei skal vera hans folk, og Gud sjølv skal vera hjå deim og vera deira Gud.',
        4: 'Og han skal turka kvar tåra av augo deira, og dauden skal ikkje meir vera til, og ikkje sorg og ikkje skrik og ikkje pinsla skal meir vera til; for dei fyrste ting er burtfarne.»',
        5: 'Og han som sat på kongsstolen, sagde: «Sjå, eg gjer alle ting nye!» Og han segjer til meg: «Skriv! for desse ordi er truverdige og sanne.»',
        6: 'Og han sagde til meg: «Det er gjort. Eg er A og Å, upphavet og enden. Eg vil gjeva den tyrste av kjelda med livsens vatn for inkje.',
        7: 'Den som sigrar, skal erva alle ting, og eg vil vera hans Gud, og han skal vera min son.',
        8: 'Men dei som er ræddhuga og vantruande og styggjelege og manndråparar og horkarar og trollmenner og avgudsdyrkarar og alle ljugarar, deira lut skal vera i sjøen som brenn med eld og svåvel; det er den andre dauden.»',
        9: 'Og ein av dei sju englarne som hadde dei sju skålerne, fyllte med dei sju siste plågorne, kom til meg og tala med meg og sagde: «Kom, eg skal visa deg bruri, vivet til Lambet!»',
        10: 'Og han førde meg i åndi burt på eit stort og høgt fjell og viste meg den heilage byen Jerusalem, som steig ned frå himmelen frå Gud.',
        11: 'Han hadde Guds herlegdom, og hans ljos var som av den kostelegaste stein, som krystallblank jaspis.',
        12: 'Og han hadde ein stor og høg mur, han hadde tolv portar, og på portarne tolv englar og innskrivne namn, som er namni på dei tolv ætter av Israels born:',
        13: 'mot aust tri portar, mot nord tri portar, mot sud tri portar, mot vest tri portar.',
        14: 'Og muren um byen hadde tolv grunnsteinar, og på deim namni på dei tolv apostlar åt Lambet.',
        15: 'Og han som tala med meg, hadde ei gullrøyr til å mæla byen og portarne og muren hans.',
        16: 'Og byen ligg i ein firkant, og lengdi på honom er so stor som breiddi. Og han mælte byen med røyri: tolv tusund stadier; lengd og breidd og høgd på honom er like.',
        17: 'Og han mælte muren um honom: eit hundrad og fire og fyrti alner, etter eit menneskjemål, som og er engle-mål.',
        18: 'Og muren var bygd av jaspis, og byen var av reint gull, lik reint glas.',
        19: 'Og grunnsteinarne i bymuren var prydde med allslag dyre steinar: den fyrste grunnsteinen var jaspis, den andre safir, den tridje kalcedon, den fjorde smaragd,',
        20: 'den femte sardonyx, den sette sarder, den sjuande krysolit, den åttande beryll, den niande topas, den tiande krysopras, den ellevte hyacint, den tolvte ametyst.',
        21: 'Og dei tolv portarne var tolv perlor; kvar ein av portarne var av ei perla, og gata i byen var reint gull som klårt glas.',
        22: 'Og eg såg ikkje noko tempel i honom; for hans tempel er Herren, Gud den allmegtige, og Lambet.',
        23: 'Og byen treng ikkje soli eller månen til å skina åt seg; for Guds herlegdom upplyser honom, og Lambet er hans ljos.',
        24: 'Og folki skal ferdast i hans ljos, og kongarne på jordi ber sin herlegdom til honom.',
        25: 'Og hans portar skal aldri verta stengde um dagen; for natt skal ikkje vera der.',
        26: 'Og dei skal bera herlegdomen og æra frå folki til honom.',
        27: 'Og inkje ureint skal koma inn i honom, og ingen som fer med styggedom og lygn; berre dei som er innskrivne i livsens bok hjå Lambet.',
    },
    22: {
        1: 'Og han viste meg ei elv med livsens vatn, som rann klår som krystall ut frå kongsstolen åt Gud og Lambet.',
        2: 'Midt imillom bygata og elvi, på båe sidor, stod livsens tre, som bar tolv gonger frukt og gav kvar månad si frukt. Og lauvet på treet var til helsebot for folki.',
        3: 'Og ingi bannstøyting skal vera meir, og kongsstolen åt Gud og Lambet skal vera der, og hans tenarar skal tena honom.',
        4: 'Og dei skal sjå hans åsyn, og hans namn skal vera på panna deira.',
        5: 'Og natt skal det ikkje vera meir, og dei treng ikkje til ljos av lampa og ljos av sol, for Gud Herren skal lysa yver deim; og dei skal råda i all æva.',
        6: 'Og han sagde til meg: «Desse ord er truverdige og sanne; og Herren, den Gud som skifter ut sin Ande til profetarne, hev sendt sin engel til å syna tenarane sine det som snart skal henda.',
        7: 'Sjå, eg kjem snart! Sæl er den som tek vare på dei profetiske ord i denne boki.»',
        8: 'Og eg, Johannes, er den som såg og høyrde dette. Og då eg hadde høyrt og set, fall eg ned og vilde tilbeda for føterne til den engelen som synte meg dette.',
        9: 'Og han segjer til meg: «Sjå til du ikkje gjer det; for eg er medtenar til deg og brørne dine, profetarne, og til deim som tek vare på ordi i denne boki. Tilbed Gud!»',
        10: 'Og han segjer til meg: «Du skal ikkje setja innsigle på dei profetiske ord i denne boki! for tidi er nær.',
        11: 'Lat den som gjer urett gjera urett framleides, og den ureine verta urein framleides, og den rettferdige gjera rettferd framleides, og den heilage verta helga framleides!',
        12: 'Sjå, eg kjem snart, og mi løn er med meg, til å gjeva kvar attergjeld, etter som hans gjerning er.',
        13: 'Eg er A og Å, upphavet og enden, den fyrste og den siste.',
        14: 'Sæle er dei som tvær kjolarne sine, so dei må få rett til livsens tre og koma inn i byen gjenom portarne.',
        15: 'Men utanfor er hundarne og trollmennerne og horkararne og manndråparane og avgudsdyrkarane og kvar som elskar og talar lygn.',
        16: 'Eg, Jesus, hev sendt min engel til å vitna dette for dykk um kyrkjelydarne. Eg er Davids rotrenning og ætt, den klåre morgonstjerna.',
        17: 'Og Anden og bruri segjer: «Kom!» Og den som høyrer det, segje: «Kom!» Og den som er tyrst, han kome, og den som vil, han take livsens vatn for inkje!»',
        18: 'Eg vitnar for kvar som høyrer dei profetiske ordi i denne boki: Dersom nokon legg noko til dette, so skal Gud leggja på honom dei plågor som er skrivne i denne boki.',
        19: 'Og dersom nokon tek noko burt frå ordi i denne profetiske boki, so skal Gud taka hans lut burt frå livsens tre og frå den heilage byen som det stend skrive um i denne boki.',
        20: 'Han som vitnar dette, segjer: «Ja, eg kjem snart.» Amen, ja kom, Herre Jesus!',
        21: 'Vår Herre Jesu Kristi nåde vere med dykk alle! Amen.',
    },
}
