NAME = 'GerMenge: Menge-Bibel (1939)'
BOOK = 'Nahum'

CHAPTERS = {
    1: {
        1: '(Dies ist) der Gottesspruch über Ninive, das Buch des Gesichts Nahums, des Elkositers.',
        2: 'Ein eifernder und rächender Gott ist der HERR, ja ein Rächer ist der HERR und voller Zornesglut; Rache übt der HERR an seinen Widersachern und trägt seinen Feinden (ihre Verschuldungen) nach.',
        3: 'Der HERR ist wohl langsam zum Zorn und groß an Gnade, läßt aber (den Schuldigen) keineswegs ungestraft. Durch Sturm und Ungewitter geht der Weg des HERRN, und Gewölk ist der Staub seiner Füße.',
        4: 'Er schilt das Meer und legt es trocken und läßt alle Ströme versiegen; Basan und der Karmel verdorren, und die Blüte des Libanons verwelkt.',
        5: 'Die Berge erbeben vor ihm, und die Hügel zerschmelzen; die Erde hebt sich bei seinem Anblick empor, der Erdkreis samt allen, die darauf wohnen.',
        6: 'Wer kann vor seinem Groll bestehen und wer standhalten bei der Glut seines Zornes? Sein Grimm wirkt sich wie Feuer aus, und die Felsen zerspringen vor ihm.',
        7: 'Doch gütig ist der HERR (gegen die auf ihn Hoffenden), eine feste Burg am Tage der Drangsal, und er kennt die, welche bei ihm Zuflucht suchen;',
        8: 'aber mit überschwemmender Flut vernichtet er seine Widersacher, und Finsternis verfolgt seine Feinde.',
        9: 'Was ersinnt ihr Anschläge gegen den HERRN? Vernichtung wird er herbeiführen: nicht zum zweitenmal braucht die Drangsal sich zu erheben.',
        10: 'Denn wären sie gar wie Dornen dicht verflochten und wie von ihrem Trank durchtränkt, sollen sie doch völlig verzehrt werden wie dürre Stoppeln! –',
        11: 'Von dir (Ninive) ist der ausgegangen, der Böses gegen den HERRN ersann, der nichtswürdige Ränkeschmied.',
        12: 'So hat der HERR gesprochen: »Wenn sie auch wohlgemut und noch so zahlreich sind, sollen sie doch abgemäht werden und dahinfahren! Und habe ich dich (Juda) auch gedemütigt, so will ich dich doch fortan nicht mehr demütigen,',
        13: 'sondern will nunmehr sein Joch, das auf dir lastet, zerbrechen und deine Stricke zerreißen.«',
        14: 'Über dich aber (Assyrien) hat der HERR bestimmt, daß von deinem Namen fernerhin kein Same kommen soll. »Aus dem Hause deines Gottes will ich Schnitzbild und Gußbild ausrotten, will dir dein Grab herrichten; denn zu leicht bist du erfunden worden.«',
    },
    2: {
        1: 'Sehet da: auf den Bergen die Schritte eines Freudenboten, der Heil verkündigt! Feiere, Juda, deine Feste, erfülle deine Gelübde! Denn hinfort wird der Nichtswürdige dich nicht mehr durchziehen: er ist völlig vernichtet.',
        2: 'Es rückt gegen dich (Ninive) der Zerstörer heran: wahre die Festung, überwache die Straße, lege dir den Gurt fest um die Hüften, nimm alle Kraft zusammen!',
        3: 'Denn der HERR stellt den Weinstock Jakobs wieder her gleichwie den Weinstock Israels; denn Verwüster haben sie verwüstet und ihre Ranken vernichtet.',
        4: 'Die Schilde seiner Krieger sind rot gefärbt, die Mannen in Scharlach gekleidet; es funkelt der Stahl an den Kriegswagen, sooft er sie zurüstet, und die Lanzen werden geschwungen.',
        5: 'Auf den Straßen rasen die Wagen einher, jagen auf den freien Plätzen dahin; wie Fackeln sind sie anzusehen, wie Blitze fahren sie hin und her.',
        6: 'Er bietet seine Edlen auf: strauchelnd kommen sie auf ihren Bahnen herbei; sie eilen hin zur Mauer der Stadt, doch schon ist das Schutzdach aufgestellt.',
        7: 'Die Tore an den Strömen werden erbrochen: da verzagt der Palast.',
        8: 'Die Königin wird entkleidet und weggeführt, während ihre Mägde wie girrende Tauben schluchzen und sich auf den Busen schlagen.',
        9: 'Ninive ist wie ein Teich, dessen Wasser entweichen. (Wohl ruft man:) »Halt, halt!«, doch niemand wendet sich um.',
        10: '»Raubt Silber, raubt Gold!« Denn unermeßlich ist der Vorrat, die Fülle von Kostbarkeiten jeder Art.',
        11: 'O Öde, Verödung und Verheerung! Verzagte Herzen und schlotternde Knie, Zittern in allen Lenden und Totenblässe in allen Gesichtern!',
        12: 'Wo ist nun die Behausung der Löwen und die Lagerstätte der jungen Leuen, wo der Löwe, die Löwin umherstreifte und das Löwenjunge, von niemand aufgeschreckt?',
        13: 'Der Löwe raubte, bis seine Jungen genug hatten, und mordete für seine Löwinnen; er füllte seine Höhlen mit Raub an und seine Schlupfwinkel mit zerrissenen (Beutetieren).',
        14: '»Nunmehr will ich an dich« – so lautet der Ausspruch des HERRN der Heerscharen – »und will deine Kriegswagen in Rauch aufgehen lassen; deine jungen Leuen soll das Schwert fressen, und ich will deinem Rauben auf der Erde ein Ende machen, und die Stimme deiner Sendlinge soll man fortan nicht mehr vernehmen!«',
    },
    3: {
        1: 'Wehe der blutbefleckten Stadt, die ganz angefüllt ist mit Trug und Gewalttat und die kein Ende des Raubens findet!',
        2: 'Horch Peitschenknall, horch Rädergerassel! Jagende Rosse und rollende Wagen,',
        3: 'heransprengende Reiter, funkelnde Schwerter und blitzende Speere! Durchbohrte in Menge, Haufen von Toten und zahllose Leichen – man strauchelt über die Leichen!',
        4: 'Und (das alles) wegen der vielen Buhlereien der holdseligen, verführerischen Buhlerin, die ganze Völker mit ihrer Buhlerei berückte und Völkerschaften mit ihren Zauberkünsten (umgarnte).',
        5: '»Nunmehr will ich an dich« – so lautet der Ausspruch des HERRN der Heerscharen – »und will deine Schleppe dir übers Gesicht ziehen und den Völkern deine Blöße zeigen und den Königreichen deine Scham.',
        6: 'Ich will dich mit Unrat bewerfen und dich dadurch entehren und dich zu einem Schauspiel machen,',
        7: 'daß alle, die dich erblicken, vor dir fliehen und ausrufen: ›Zerstört ist Ninive! Wer möchte ihm Beileid bezeigen? Wo soll ich Tröster für dich ausfindig machen?‹«',
        8: 'Bist du etwa besser als No Ammon, die an den Nilarmen thronte, rings von Wasser umgeben? die Stadt, deren Außenwerk der Nilstrom bildete und deren Mauer aus Wasser bestand?',
        9: 'Äthiopier waren ihre Stärke und Ägypter ohne Zahl; Put und die Libyer standen ihr zu Gebot.',
        10: 'Doch auch sie ist der Verbannung verfallen, ist in die Gefangenschaft gewandert, auch ihre Kinder sind an allen Straßenecken zerschmettert worden; über ihre Edlen warf man das Los, und alle ihre Großen wurden mit Ketten gefesselt.',
        11: 'So sollst auch du, Ninive, trunken werden, sollst umnachtet daliegen; auch du sollst Zuflucht vor dem Feinde suchen müssen!',
        12: 'Alle deine Festungen sind wie Feigenbäume mit Frühfeigen: werden sie geschüttelt, fallen sie dem, der essen will, in den Mund.',
        13: 'Wisse wohl: dein Kriegsvolk ist zu Weibern in deiner Mitte geworden; deinen Feinden stehen die Tore deines Landes weit offen, Feuer verzehrt deine Riegel.',
        14: 'Schöpfe dir Wasser für die (Zeit der) Belagerung, mache deine Festungswerke stärker! tritt in den Lehm und stampfe Ton, nimm die Ziegelform zur Hand!',
        15: 'Trotzdem wird das Feuer dich fressen, wird das Schwert dich vertilgen, dich verzehren wie die Freßgrillen verzehren. Magst du auch zahlreich sein wie ein Freßgrillenschwarm, zahllos wie ein Heuschreckenvolk,',
        16: 'magst du auch mehr Krämer haben, als Sterne am Himmel sind: – die Freßgrillen häuten sich und fliegen davon!',
        17: 'Deine Fürsten gleichen den Heuschrecken und deine Hofleute den Grillenschwärmen, die sich bei kaltem Wetter an den Mauern lagern; geht aber die Sonne auf, so fliegen sie davon, und niemand weiß, wo sie geblieben sind.',
        18: 'Entschlafen sind deine Hirten, König von Assyrien, entschlummert deine Großen! Dein Kriegsvolk hat sich auf den Bergen zerstreut, und niemand ist da, der es sammelt!',
        19: 'Keine Linderung gibt es für deine Wunde, unheilbar ist der Schlag, der dich getroffen! Alle, welche die Kunde von dir vernehmen, klatschen über dich in die Hände; denn über wen wäre nicht deine Bosheit ohne Unterlaß dahingegangen?',
    },
}
