NAME = 'GerLeoNA28: Leonberger Bibel, NT (NA28)'
BOOK = 'II Timothy'

CHAPTERS = {
    1: {
        1: 'Paulus, ein Apostel von Christus Jesus durch den Willen Gottes gemäß der Verheißung des Lebens, das in Christus Jesus [ist]. /',
        2: 'An Timotheus, [mein] geliebtes Kind: /Gnade, Barmherzigkeit, Frieden von Gott dem Vater und Christus Jesus, unserem Herrn!',
        3: 'Ich danke Gott, dem ich – ‹wie schon meine Vorfahren› – mit einem reinen Gewissen diene, während ich in meinen Fürbitten ununterbrochen die Erinnerung an dich aufrechterhalte, bei Nacht und bei Tag,',
        4: 'weil ich mich danach sehne, dich zu sehen – wobei ich mich an deine Tränen erinnert habe –, damit ich von Freude erfüllt werde,',
        5: 'da ich an den ungeheuchelten Glauben in dir ‹erinnert wurde›, welcher zuerst in deiner Großmutter Lois und deiner Mutter Eunike wohnte, und ich bin überzeugt: auch in dir.',
        6: 'Aus diesem Grund erinnere ich dich daran, die Gnadengabe Gottes anzufachen, die in dir ist durch Auflegung meiner Hände.',
        7: 'Gott hat uns nämlich nicht einen Geist der Feigheit gegeben, sondern der Kraft und der Liebe und der Besonnenheit.',
        8: 'Schäme dich also weder für das Zeugnis unseres Herrn noch für mich, seinen Gefangenen, sondern ertrage Schlechtes zugunsten der guten Nachricht entsprechend der Kraft Gottes,',
        9: 'der uns gerettet und mit einer heiligen Berufung berufen hat, nicht nach unseren Werken, sondern nach seiner Absicht und Gnade, die uns in Christus Jesus gegeben wurde vor ewigen Zeiten,',
        10: 'jetzt aber erschienen ist durch die Erscheinung unseres Herrn Christus Jesus, der einerseits den Tod vernichtet hat, andererseits Leben und Unvergänglichkeit durch die gute Nachricht ans Licht gebracht hat,',
        11: 'für die ich als Prediger und Apostel und Lehrer bestimmt wurde.',
        12: 'Aus diesem Grund erleide ich auch diese [Dinge]; doch ich schäme mich nicht, denn ich weiß, wem ich vertraut habe, und ich bin überzeugt, dass er fähig ist, meine Anzahlung bis zu jenem Tag aufzubewahren.',
        13: 'Beherzige die gesunden Worte, die du von mir gehört hast, in dem Glauben und der Liebe, die in Christus Jesus [sind].',
        14: 'Bewahre die gute Anzahlung durch den heiligen Geist, der in uns wohnt.',
        15: 'Du weißt Folgendes: dass alle, die in Asia [leben], sich von mir abgewandt haben; zu denen gehören Phygelus und Hermogenes.',
        16: 'Der Herr gebe dem Haus von Onesiphorus Erbarmen, weil er mich oft erfrischt und er sich für meine Gefangenschaft nicht geschämt hat,',
        17: 'sondern mich schnell gesucht und gefunden hat, als ich in Rom angekommen war –',
        18: 'der Herr möge es ihm schenken, an jenem Tag beim Herrn Erbarmen zu finden – und wie viel er in Ephesus diente, weißt du besser [als ich].',
    },
    2: {
        1: 'Du nun, mein Kind: Bekleide dich mit der Gnade, die in Christus Jesus [ist],',
        2: 'und was du von mir in Gegenwart vieler Zeugen gehört hast, das vertraue gläubigen Menschen an, welche imstande sein werden, auch andere zu lehren.',
        3: 'Ertrage Schlechtes mit als ein guter Soldat von Christus Jesus.',
        4: 'Niemand, der als Soldat kämpft, verwickelt sich in den Beschäftigungen des Alltags, sodass er dem gefällt, der ihn als Soldat angeworben hat.',
        5: 'Und wenn jemand auch an einem Wettkampf teilnimmt, dann wird er nicht [mit dem Siegeskranz] gekrönt, außer er hat regelkonform am Wettkampf teilgenommen.',
        6: 'Der Bauer, der sich abmüht, muss zuerst die Erträge einholen.',
        7: 'Bedenke, was ich sage; denn der Herr wird dir Verständnis in allen [Dingen] geben.',
        8: 'Denk an Jesus Christus, auferweckt von den Toten, aus der Nachkommenschaft Davids, gemäß meiner guten Nachricht,',
        9: 'in dem ich Übel erleide, bis hin zu Fesseln wie ein Übeltäter, doch das Wort Gottes ist nicht gefesselt!',
        10: 'Deshalb erdulde ich alles um der Erwählten willen, damit auch sie die Rettung, die in Christus Jesus [ist], mit ewiger Herrlichkeit erlangen.',
        11: 'Das Wort [ist] zuverlässig: Wenn wir nämlich mitgestorben sind, werden wir auch mitleben; /',
        12: 'wenn wir erdulden, werden wir auch mitregieren; /wenn wir verleugnen sollten, wird auch jener uns verleugnen; /',
        13: 'wenn wir untreu sind, bleibt jener treu. Er kann sich selbst nämlich nicht verleugnen.',
        14: 'Erinnere daran, indem du vor Gott bezeugst, keine Wortgefechte zu führen, was zu nichts nütze [ist], [außer] zum Untergang der Zuhörer.',
        15: 'Setze alles daran, dich selbst Gott als ein bewährter und vertrauenswürdiger Arbeiter zur Verfügung zu stellen, der das Wort der Wahrheit richtig behandelt.',
        16: 'Aber den gottlosen Floskeln geh aus dem Weg, denn sie werden zu mehr Gottlosigkeit fortschreiten,',
        17: 'und ihr Wort wird wie ein Geschwür wuchern. Zu denen gehören Hymenäus und Philetus,',
        18: 'die hinsichtlich der Wahrheit abgeirrt sind, indem sie sagen, die Auferstehung sei bereits geschehen, und den Glauben von einigen umkrempeln.',
        19: 'Das feste Fundament Gottes steht jedoch und trägt folgendes Siegel: „Der Herr kennt diejenigen, die ihm gehören“, und: „Es soll sich jeder fernhalten von Ungerechtigkeit, der den Namen des Herrn benennt.“',
        20: 'Aber in einem großen Haus sind nicht nur goldene und silberne Gefäße, sondern auch hölzerne und tonerdene, und zwar die einen zur Ehre, die anderen zur Unehre.',
        21: 'Wenn sich also jemand von diesen reinigt, wird er ein Gefäß zur Ehre sein, geheiligt, dem Hausherrn nützlich, zu jedem guten Werk vorbereitet.',
        22: 'Den jugendlichen Begierden entfliehe nun, strebe aber nach Gerechtigkeit, Treue, Liebe, Frieden mit denen, die den Herrn anrufen aus reinem Herzen.',
        23: 'Und die törichten und ungelehrten Streitfragen meide, weil du weißt, dass sie [nur] Streitigkeiten erzeugen.',
        24: 'Aber ein Knecht des Herrn soll nicht streiten, sondern gegenüber allen gutmütig sein, belehrbar, gelassen,',
        25: 'indem er mit Sanftmut diejenigen unterweist, die widersprechen, falls Gott ihnen Buße zur Erkenntnis der Wahrheit gibt',
        26: 'und sie aus der Falle des Teufels wieder ernüchtern, nachdem sie von ihm für seinen Willen eingespannt worden sind.',
    },
    3: {
        1: 'Folgendes aber sollst du wissen: In den letzten Tagen werden schwere Zeiten eintreten,',
        2: 'denn die Menschen werden selbstverliebt sein, geldverliebt, prahlerisch, hochmütig, Lästerer, den Eltern ungehorsam, undankbar, unheilig,',
        3: 'lieblos, unversöhnlich, Verleumder, unenthaltsam, grausam, nicht das Gute liebend,',
        4: 'Verräter, gedankenlos, aufgeblasen, mehr Freunde des Vergnügens als Freunde Gottes;',
        5: 'sie besitzen eine Form der Frömmigkeit, aber deren Kraft verleugnen sie. Und diese [Leute] meide!',
        6: 'Denn von diesen stammen diejenigen, die sich in die Häuser einschleichen und schwache Frauen verführen, die beladen sind mit Sünden [und] sich leiten lassen von verschiedenen Begierden,',
        7: 'die ständig lernen und niemals zur Erkenntnis der Wahrheit kommen können.',
        8: 'Aber in der Weise, wie Jannes und Jambres Mose widerstanden, so widerstehen auch diese der Wahrheit – Menschen, die im Verstand verdorben und hinsichtlich des Glaubens unbewährt [sind] –,',
        9: 'doch sie werden nicht zu Größerem fortschreiten; denn ihr Unverstand wird allen offensichtlich sein, wie es auch der [Unverstand] von jenen war.',
        10: 'Du aber bist mir unmittelbar gefolgt: in der Lehre, dem Lebensstil, der Hingabe, der Treue, der Geduld, der Liebe, der Ausdauer,',
        11: 'den Verfolgungen, den Leiden, die mir in Antiochia, in Ikonia, in Lystra passiert sind. Diese Verfolgungen habe ich ertragen, und aus allem hat mich der Herr gerettet.',
        12: 'Aber auch alle, die in Christus Jesus fromm leben wollen, werden verfolgt werden.',
        13: 'Böse Menschen und Schwindler aber werden zu [noch] Schlimmerem voranschreiten, indem sie irreführen und irregeführt werden.',
        14: 'Du aber bleibe bei dem, was du gelernt hast und wovon du überzeugt bist, weil du weißt, von wem du es gelernt hast,',
        15: 'und weil du von klein auf die heiligen Schriften kennst, die dich weise machen können zur Rettung durch Glauben, der in Christus Jesus [ist].',
        16: 'Alle Schrift [ist] gottgehaucht und nützlich zur Lehre, zur Überführung, zur Korrektur, zur Unterweisung in Gerechtigkeit,',
        17: 'damit der Mensch Gottes gerüstet ist, zu jedem guten Werk ausgerüstet.',
    },
    4: {
        1: 'Ich bezeuge vor Gott und Christus Jesus, der im Begriff steht, Lebende und Tote zu richten, und seiner Erscheinung und seinem Königreich:',
        2: 'Predige das Wort, sei zu passender oder unpassender Zeit bereit, überführe, weise zurecht, ermahne, mit aller Geduld und Lehre!',
        3: 'Es wird nämlich eine Zeit geben, wo sie die gesunde Lehre nicht ertragen werden, sondern sich selbst nach den eigenen Wünschen Lehrer anhäufen werden, damit das Gehör gekitzelt wird.',
        4: 'Und sie werden das Gehör von der Wahrheit abwenden und es den Fabeln zuwenden.',
        5: 'Du aber sei nüchtern in allem, ertrage Schlechtes, tu das Werk eines Evangelisten, erfülle deinen Dienst!',
        6: 'Denn ich werde schon als Trankopfer versprengt und die Zeit meines Abschieds ist da.',
        7: 'Ich habe den guten Kampf gekämpft, ich habe den Lauf vollendet, ich habe den Glauben bewahrt.',
        8: 'Fortan liegt mir der Siegeskranz der Gerechtigkeit bereit, den mir der Herr, der gerechte Richter, an jenem Tag verleihen wird – aber nicht nur mir, sondern auch allen, die sein Erscheinen lieb gewonnen haben.',
        9: 'Beeile dich, bald zu mir zu kommen!',
        10: 'Denn Demas hat mich verlassen, weil er das jetzige Zeitalter lieb gewonnen hat; und zwar ist er nach Thessalonich gegangen, Kreszenz nach Galatien, Titus nach Dalmatien.',
        11: 'Nur Lukas ist bei mir. Nimm Markus und bring ihn mit dir, denn er ist mir nützlich zum Dienst.',
        12: 'Tychikus wiederum habe ich nach Ephesus gesandt.',
        13: 'Wenn du kommst, bring den Mantel, den ich in Troas bei Karpus zurückließ, und die Bücher, besonders die Pergamente.',
        14: 'Alexander der Schmied hat mir viel Schlechtes erwiesen (der Herr wird ihm nach seinen Werken vergelten).',
        15: 'Vor ihm hüte auch du dich, denn er hat unseren Worten vehement widerstanden.',
        16: 'Bei meiner ersten Verteidigung stand mir niemand bei, sondern alle haben mich verlassen – es möge ihnen nicht zugerechnet werden!',
        17: 'Der Herr aber stand mir bei und hat mich gestärkt, damit die Predigt durch mich erfüllt wird und alle Nationen sie hören und aus dem Rachen des Löwen gerettet werden.',
        18: 'Der Herr wird mich von jedem bösen Werk erlösen und mich in sein himmlisches Reich retten. Ihm [sei] die Herrlichkeit ‹für immer und ewig›! Amen.',
        19: 'Grüß Priska und Aquila und das Haus von Onesiphorus!',
        20: 'Erastus ist in Korinth geblieben, Trophimus wiederum habe ich in Milet gelassen, weil er krank war.',
        21: 'Beeile dich, vor dem Winter zu kommen! Es grüßen dich Eubulus und Pudens und Linus und Klaudia sowie alle [anderen] Geschwister.',
        22: 'Der Herr [sei] mit deinem Geist! Die Gnade [sei] mit euch!',
    },
}
