NAME = 'GerMenge: Menge-Bibel (1939)'
BOOK = 'Colossians'

CHAPTERS = {
    1: {
        1: 'Ich, Paulus, ein Apostel Christi Jesu durch Gottes Willen, und der Bruder Timotheus',
        2: 'senden unsern Gruß den in Kolossä lebenden heiligen und gläubigen Brüdern in Christus Jesus: Gnade sei mit euch und Friede von Gott, unserm Vater!',
        3: 'Wir danken Gott, dem Vater unsers Herrn Jesus Christus, allezeit in unsern Gebeten für euch,',
        4: 'da wir von eurem Glaubensstand in Christus Jesus und von der Liebe, die ihr zu allen Heiligen hegt, gehört haben,',
        5: '(und zwar danken wir Gott) um des Hoffnungsgutes willen, das für euch im Himmel aufbewahrt liegt. Von diesem habt ihr schon im voraus Kunde erhalten durch das Wort der Wahrheit, nämlich der Heilsbotschaft,',
        6: 'die bei euch Eingang gefunden hat, wie sie ja auch in der ganzen Welt (verbreitet) ist und ebenso Frucht bringt und wächst wie auch bei euch seit dem Tage, an dem ihr sie vernommen und die Gnade Gottes in Wahrheit erkannt habt.',
        7: 'Ihr habt ja die betreffende Unterweisung von unserm geliebten Mitknecht Epaphras empfangen, der als unser Vertreter ein treuer Diener Christi ist',
        8: 'und uns auch von eurer durch den Geist gewirkten Liebe berichtet hat.',
        9: 'Deshalb hören auch wir seit dem Tage, an dem wir es vernommen haben, nicht auf, für euch zu beten und (Gott) zu bitten, daß ihr mit der Erkenntnis seines Willens in aller geistgewirkten Weisheit und Einsicht erfüllt werden möchtet,',
        10: 'damit ihr so, wie es des Herrn würdig ist, zu seinem völligen Wohlgefallen wandelt. Ja, möchtet ihr in jedem guten Werke Frucht bringen und in der Erkenntnis Gottes wachsen!',
        11: 'Möchtet ihr mit aller Kraft, wie es der Macht seiner Herrlichkeit entspricht, zu aller Standhaftigkeit und Ausdauer ausgerüstet werden',
        12: 'und mit Freuden dem Vater Dank sagen, der uns zur Teilnahme am Erbe der Heiligen im Licht tüchtig gemacht hat!',
        13: 'Er hat uns ja aus der Gewalt der Finsternis gerettet und uns in das Reich des Sohnes seiner Liebe versetzt.',
        14: 'In diesem haben wir die Erlösung, nämlich die Vergebung der Sünden;',
        15: 'er ist ja das Ebenbild des unsichtbaren Gottes, der Erstgeborene aller Schöpfung;',
        16: 'denn in ihm ist alles geschaffen worden, was im Himmel und auf der Erde ist, das Sichtbare wie das Unsichtbare, mögen es Throne oder Herrschaften, Mächte oder Gewalten sein: alles ist durch ihn und für ihn geschaffen worden,',
        17: 'und er ist vor allem, und alles hat in ihm seinen Bestand.',
        18: 'Ferner ist er das Haupt des Leibes, nämlich der Gemeinde: er ist der Anfang, der Erstgeborene aus den Toten, er, der in allen Beziehungen den Vorrang haben sollte.',
        19: 'Denn es war (Gottes) Ratschluß, in ihm die ganze Fülle wohnen zu lassen',
        20: 'und durch ihn alles mit sich zu versöhnen – nachdem er durch sein am Kreuz vergossenes Blut Frieden gestiftet hat –, durch ihn (zu versöhnen) sowohl das, was auf der Erde, als auch das, was in den Himmeln ist.',
        21: 'Auch euch, die ihr einst (gott)entfremdet und feindlichen Sinnes in euren bösen Werken waret, –',
        22: 'jetzt aber hat er euch in seinem Fleischesleibe durch seinen Tod versöhnt, um euch als heilig, untadelig und unanklagbar vor ihm darzustellen,',
        23: 'wofern ihr im Glauben fest gegründet und unerschütterlich beharrt und euch nicht von der Hoffnung abbringen laßt, die in der Heilsbotschaft beschlossen liegt. Diese (Botschaft) habt ihr vernommen: sie ist ja in der ganzen Schöpfung unter dem Himmel verkündigt worden, und ich, Paulus, bin ihr Diener geworden.',
        24: 'Jetzt freue ich mich der Leiden, die ich für euch zu erdulden habe, und ergänze das, was an den Trübsalen Christi noch fehlt, in meinem Fleisch für seinen Leib, das heißt für die Gemeinde,',
        25: 'deren Diener ich infolge des Haushalteramts geworden bin, das mir von Gott im Hinblick auf euch übertragen worden ist, um das Wort Gottes vollkommen auszurichten,',
        26: 'nämlich das Geheimnis, das, seitdem es Weltzeiten und Menschengeschlechter gibt, verborgen gewesen, jetzt aber seinen Heiligen geoffenbart worden ist.',
        27: 'Denn ihnen hat Gott kundtun wollen, welche Fülle von Herrlichkeit dieses Geheimnis (gerade) unter den Heidenvölkern in sich berge. Dieser Reichtum besteht darin, daß Christus in euch ist, als die Hoffnung auf die (künftige) Herrlichkeit.',
        28: 'Und er ist es, den wir verkündigen, indem wir jedermann ermahnen und jedermann in aller Weisheit unterweisen, um einem jeden zur Vollkommenheit in Christus zu verhelfen.',
        29: 'Um dieses zu erreichen, arbeite ich auch angestrengt und kämpfe vermöge seiner Kraft, die sich machtvoll in mir wirksam erweist.',
    },
    2: {
        1: 'Ich will euch nämlich wissen lassen, welch schweren Kampf ich für euch und die (Brüder) in Laodizea sowie (überhaupt) für alle, denen ich bis jetzt persönlich noch unbekannt geblieben bin, zu bestehen habe.',
        2: 'Ihre Herzen sollen dadurch ermutigt werden, nachdem sie sich in Liebe fest zusammengeschlossen haben und in den ganzen Reichtum des vollen Verständnisses (eingeführt werden), zur Erkenntnis des Geheimnisses Gottes.',
        3: 'Dieses (Geheimnis) ist Christus, in welchem alle Schätze der Weisheit und Erkenntnis verborgen liegen.',
        4: 'Ich sage dies aber, damit niemand euch durch Überredungskünste täusche.',
        5: 'Denn wenn ich auch leiblich abwesend bin, so bin ich doch dem Geist nach bei euch gegenwärtig und sehe mit Freuden eure festgeschlossene Kampfstellung und das gesicherte Bollwerk eures Glaubens an Christus.',
        6: 'Wie ihr nun den Herrn Christus Jesus angenommen habt, so wandelt nun auch in ihm:',
        7: 'bleibt in ihm festgewurzelt und baut euch in ihm auf und werdet fest im Glauben, wie ihr unterwiesen worden seid, und laßt es an reichlicher Danksagung nicht fehlen.',
        8: 'Gebt wohl acht, daß niemand euch einfängt durch die Philosophie und eitle Täuschung, die sich auf menschliche Überlieferung, auf die Elemente der Welt, gründet und mit Christus nichts zu tun hat.',
        9: 'Denn in ihm wohnt die ganze Fülle der Gottheit leibhaftig,',
        10: 'und ihr besitzt die ganze Fülle in ihm, der das Haupt jeder Herrschaft und Gewalt ist.',
        11: 'In ihm habt ihr auch die Beschneidung empfangen, nämlich eine solche, die nicht mit Händen vollzogen ist, nein, die in der Ablegung des Fleischesleibes besteht: die Beschneidung Christi,',
        12: 'da ihr in der Taufe mit ihm zusammen begraben worden seid. In ihm seid ihr auch mitauferweckt worden durch den Glauben an die Kraftwirkung Gottes, der ihn aus den Toten auferweckt hat.',
        13: 'Auch euch, die ihr durch eure Übertretungen und den unbeschnittenen Zustand eures Fleisches (einst) tot waret, auch euch hat Gott zusammen mit ihm lebendig gemacht, indem er uns alle Übertretungen aus Gnaden vergeben hat,',
        14: 'dadurch, daß er den durch seine Satzungen gegen uns lautenden Schuldschein, der für unser Heil ein Hindernis bildete, ausgelöscht und ihn weggeschafft hat, indem er ihn ans Kreuz heftete.',
        15: 'Nachdem er dann die Mächte und die Gewalten völlig entwaffnet hatte, stellte er sie öffentlich zur Schau und triumphierte in ihm über sie.',
        16: 'Darum soll niemand um Speisen und Getränke willen oder in bezug auf Fest- oder Neumondsfeier oder Sabbate absprechende Urteile über euch abgeben;',
        17: 'diese Dinge sind ja doch nur der Schatten von dem in der Zukunft Kommenden; das leibhaftige Wesen dagegen gehört Christus an.',
        18: 'Niemand soll euch verurteilen, indem er sich in demutsvollem Wesen und in Verehrung der Engel gefällt, sich mit Gesichten brüstet, ohne Grund von seinem fleischlichen Sinn aufgeblasen ist',
        19: 'und sich nicht an das Haupt hält, von dem aus der ganze Leib durch die Gelenke und Bänder unterstützt und zusammengehalten wird und so ein gottgeordnetes Wachstum vollzieht.',
        20: 'Wenn ihr mit Christus gestorben seid, los von den Elementen der Welt, was laßt ihr euch da, als ob ihr noch in der Welt lebtet, Satzungen aufbürden,',
        21: 'z.B.: »Das darfst du nicht anfassen und das nicht essen und das nicht anrühren«? –',
        22: 'Alles Derartige ist doch dazu bestimmt, durch den Verbrauch der Vernichtung anheimzufallen, und stellt (nur) Menschengebote und Menschenlehren dar,',
        23: 'die zwar im Ruf besonderer Weisheit infolge einer selbsterwählten Frömmigkeit und Demut und schonungsloser Härte gegen den Körper stehen, aber ohne wirklichen Wert sind, indem sie nur zur Befriedigung des Fleisches dienen.',
    },
    3: {
        1: 'Seid ihr also mit Christus auferweckt worden, so suchet das, was droben ist, dort, wo Christus weilt, indem er zur Rechten Gottes thront!',
        2: 'Trachtet nach dem, was droben ist, nicht nach dem, was auf Erden ist;',
        3: 'ihr seid ja doch gestorben, und euer Leben ist zusammen mit Christus in Gott verborgen.',
        4: 'Wenn Christus, unser Leben, offenbar werden wird, dann werdet auch ihr zusammen mit ihm offenbar werden in Herrlichkeit.',
        5: 'So ertötet denn eure Glieder, die an der Erde (haften), (in denen) Unzucht, Unsittlichkeit, Leidenschaft, böse Begierde (wohnen) und die Habsucht, die nichts anderes als Götzendienst ist;',
        6: 'um dieser (Sünden) willen ergeht das Zorngericht Gottes über die Söhne des Ungehorsams.',
        7: 'In diesen (Sünden) seid auch ihr einst gewandelt, als ihr noch in ihnen lebtet.',
        8: 'Jetzt aber legt auch ihr alles derartige ab: Zorn, Erbitterung, Bosheit, Schimpfworte und unanständige Reden eures Mundes!',
        9: 'Belügt euch nicht gegenseitig! Ihr habt ja doch den alten Menschen samt seinem ganzen Tun ausgezogen',
        10: 'und den neuen Menschen angezogen, der zur Erkenntnis nach dem Bilde seines Schöpfers erneuert wird,',
        11: 'wo keine Rede mehr ist von Griechen und Juden, von Beschnittenen und Unbeschnittenen, von Barbaren und Skythen, Sklaven und Freien, sondern alles und in allen (allein) Christus.',
        12: 'So ziehet nun als von Gott Auserwählte, als Heilige und Geliebte, herzliches Erbarmen, Gütigkeit, Demut, Sanftmut und Geduld an;',
        13: 'ertragt einander und vergebt euch gegenseitig, wenn jemand dem andern etwas vorzuwerfen hat; wie der Herr euch vergeben hat, so tut auch ihr es.',
        14: 'Zu dem allem aber (ziehet) die Liebe (an), die das Band der Vollkommenheit ist.',
        15: 'Und der Friede Christi regiere in euren Herzen – zu diesem seid ihr ja auch berufen worden als ein Leib –, und erweiset euch dankbar (dafür)!',
        16: 'Laßt das Wort Christi reichlich unter euch wohnen; belehrt und ermahnt einander in aller Weisheit, und singet Gott mit Psalmen, Lobgesängen und geistlichen Liedern, voller Dankbarkeit in euren Herzen.',
        17: 'Und alles, was ihr mit Worten oder Werken tun mögt, das tut alles im Namen des Herrn Jesus, indem ihr eure Dankgebete durch seine Vermittlung vor Gott den Vater bringt.',
        18: 'Ihr Frauen, seid euren Männern untertan, wie es sich im Herrn gebührt! –',
        19: 'Ihr Männer, habt eure Frauen lieb und laßt euch nicht erbittern gegen sie! –',
        20: 'Ihr Kinder, seid euren Eltern in allen Stücken gehorsam, denn das ist wohlgefällig im Herrn. –',
        21: 'Ihr Väter, reizt eure Kinder nicht, damit sie nicht verdrossen werden! –',
        22: 'Ihr Knechte, seid euren leiblichen Herren in allen Stücken gehorsam, nicht mit Augendienerei als solche, die Menschen zu gefallen suchen, sondern in Aufrichtigkeit des Herzens als solche, die den (himmlischen) Herrn fürchten.',
        23: 'Alles, was ihr zu tun habt, das leistet mit willigem Herzen, als gälte es dem Herrn und nicht den Menschen;',
        24: 'ihr wißt ja, daß ihr vom Herrn das (himmlische) Erbe als Lohn empfangen werdet: ihr dient ja dem Herrn Christus als Knechte.',
        25: 'Wer dagegen unrecht tut, wird den Lohn für das, was er Unrechtes getan hat, empfangen; da gibt es kein Ansehen der Person. –',
    },
    4: {
        1: 'Ihr Herren, gewährt euren Knechten das, was recht und billig ist; ihr wißt ja, daß auch ihr einen Herrn im Himmel habt.',
        2: 'Haltet an am Gebet und seid wachsam dabei mit Danksagung.',
        3: 'Betet zugleich auch für uns, Gott möge uns die Möglichkeit zur Predigt des Wortes geben, damit wir das Geheimnis Christi, um dessen willen ich auch in Ketten gefesselt bin, verkündigen können',
        4: 'und ich es so kundtue, wie meine Pflicht es erfordert.',
        5: 'Benehmt euch mit Weisheit im Verkehr mit denen, die draußen sind, und kauft die Zeit aus.',
        6: 'Eure Rede sei allezeit herzgewinnend, mit Salz gewürzt; ihr müßt wissen, wie ihr einem jeden zu antworten habt.',
        7: 'Über meine persönliche Lage wird euch der geliebte Bruder Tychikus berichten, mein treuer Gehilfe und Mitarbeiter im Herrn.',
        8: 'Ich habe ihn eben deswegen zu euch gesandt, damit ihr erfahrt, wie es um uns steht, und damit er eure Herzen ermutige.',
        9: 'In seiner Begleitung befindet sich Onesimus, der treue und geliebte Bruder, euer Landsmann; diese (beiden) werden euch berichten, wie hier alles steht.',
        10: 'Grüße sendet euch mein Mitgefangener Aristarchus, ebenso Markus, der Vetter des Barnabas, in betreff dessen ihr bereits (die erforderlichen) Aufträge erhalten habt – wenn er zu euch kommt, so nehmt ihn freundlich auf! –,',
        11: 'ferner Jesus, der den Beinamen Justus führt; diese drei sind die einzigen, die aus dem Judentum stammen und als meine Mitarbeiter am Reiche Gottes sich betätigen; sie sind mir ein rechter Trost geworden.',
        12: 'Es grüßt euch euer Landsmann Epaphras, ein Knecht Christi Jesu, der allezeit in seinen Gebeten für euch ringt, damit ihr in allem, was dem Willen Gottes entspricht, als Vollkommene und völlig Überzeugte dastehen möget.',
        13: 'Ja, ich muß ihm das Zeugnis geben, daß er sich um euch und um die (Brüder) in Laodizea und in Hierapolis viel Mühe gibt.',
        14: 'Es grüßt euch unser geliebter Lukas, der Arzt, und Demas.',
        15: 'Grüßet ihr die Brüder in Laodizea, auch Nymphas sowie die Gemeinde in ihrem Haus;',
        16: 'und wenn dieser Brief bei euch (vor)gelesen ist, so sorgt dafür, daß er auch in der Gemeinde von Laodizea zur Verlesung gelange und daß auch ihr den von Laodizea zu lesen bekommt.',
        17: 'Bestellt ferner dem Archippus: »Sei darauf bedacht, daß du den Dienst, den du im Herrn übernommen hast, gehörig ausrichtest!«',
        18: 'Hier mein, des Paulus, eigenhändig geschriebener Gruß! Gedenket meiner Fesseln! Die Gnade sei mit euch!',
    },
}
