NAME = 'GerMenge: Menge-Bibel (1939)'
BOOK = 'Micah'

CHAPTERS = {
    1: {
        1: '(Dies ist) das Wort des HERRN, das an Micha aus Moreseth in den Tagen der judäischen Könige Jotham, Ahas und Hiskia ergangen ist und das er über Samaria und Jerusalem geschaut hat.',
        2: 'Höret, ihr Völker allesamt; merke auf, o Erde und alles, was sie erfüllt! Und es sei Gott der HERR Zeuge gegen euch, der Allherr von seinem heiligen Tempel aus!',
        3: 'Denn sehet: der HERR verläßt seine Wohnstätte, er steigt herab und schreitet dahin über die Höhen der Erde.',
        4: 'Da zerfließen die Berge unter seinen Schritten, und die Täler spalten sich – wie Wachs vor dem Feuer, wie Wasser an einem Abhang hinabstürzt.',
        5: 'Dies alles (geschieht) wegen der Untreue Jakobs und wegen der Sünden des Hauses Israel! Wer ist es aber, der die Untreue Jakobs verübt? Doch wohl Samaria! Und wer vollführt die Sünde des Höhendienstes Judas? Doch wohl Jerusalem!',
        6: '»So will ich denn Samaria zu einem Steinhaufen im Felde machen, zum Gelände für Weinberge; ich will die Steine der Stadt ins Tal hinabstürzen und ihre Grundmauern bloßlegen.',
        7: 'Alle ihre Schnitzbilder sollen zerschlagen und alle ihre buhlerischen Weihegaben im Feuer verbrannt werden, und alle ihre Götzenbilder will ich der Vernichtung preisgeben; denn vom Buhlerlohn sind sie zusammengebracht: so sollen sie auch wieder zu Buhlerlohn werden!«',
        8: 'Darüber will ich wehklagen und jammern, will barfuß und ohne Obergewand einhergehen! Ich will eine Wehklage anstimmen wie die Schakale und ein Trauerlied wie die Strauße!',
        9: 'Denn unheilbar ist der Schlag (der Samaria getroffen hat): er dringt bis nach Juda, reicht bis an die Tore meines Volkes, bis nach Jerusalem.',
        10: 'In Gath tut es nicht kund! In Akko veranstaltet kein Weinen! In Beth-Leophra wälzt euch im Staube!',
        11: 'Mache dich auf den Weg, Einwohnerschaft von Saphir, in schimpflicher Entblößung! Die Bevölkerung von Zaanan zieht nicht mehr aus! Die Trauer Beth-Haezels nimmt euch die Lust, dort zu rasten.',
        12: 'Ach, es zittert um ihr Heil die Bevölkerung von Maroth, denn Unheil fährt vom HERRN her an die Tore Jerusalems herab!',
        13: 'Schirre die Renner an den Wagen, Einwohnerschaft von Lachis! Dort ist der Anfang der Versündigung für die Tochter Zion gewesen; denn bei dir (zuerst) haben sich die Missetaten Israels vorgefunden.',
        14: 'Darum mußt du das Entlassungsgeschenk geben an Moreseth-Gath. Die Häuser von Achsib werden für die Könige von Israel trüglich werden.',
        15: 'Einen neuen Besitzer bringe ich dir, Bewohnerschaft von Maresa. Auf ewig geht Adullam zugrunde (wie) die Herrlichkeit Israels.',
        16: 'Mache dir das Haupt kahl und schere dir den Bart ab um deine geliebten Kinder! Mache dir die Glatze so breit wie die eines Geiers! Denn sie müssen fort von dir (in die Gefangenschaft) wandern!',
    },
    2: {
        1: 'Wehe denen, die auf Frevel sinnen und Böses planen auf ihren Lagern und die es beim nächsten Morgenlicht ausführen, weil die Macht dazu in ihrer Hand liegt!',
        2: 'Gelüstet es sie nach Äckern, so bemächtigen sie sich ihrer mit Gewalt, oder nach Häusern, so nehmen sie sie weg: sie verüben Gewalttat an dem Besitzer und seinem Hause, an dem Eigentümer und seinem Erbgut.',
        3: 'Darum hat der HERR so gesprochen: »Wisset wohl: (auch) ich habe gegen dieses Geschlecht Unheil im Sinn, aus dem ihr eure Hälse nicht herausziehen und worin ihr nicht mehr aufrecht einhergehen könnt; denn es soll eine schlimme Zeit sein!«',
        4: 'An jenem Tage wird man ein Spottlied auf euch anheben und ein Klagelied anstimmen, das so lautet: »Es ist aus! Völlig vernichtet sind wir! Das Erbteil meines Volkes gibt er in fremde Hände: ach, wie entzieht er es mir! An Abtrünnige teilt er unsere Felder aus!«',
        5: 'Darum wirst du niemand haben, der dir die Meßschnur über ein Ackerlos wirft in der Gemeinde des HERRN.',
        6: '»Laßt das prophetische Predigen!« predigen sie; »derartige Dinge predigt man nicht! Nicht wird Schande uns alle treffen!',
        7: 'Ist das Haus Jakobs etwa verflucht? Ist der HERR etwa zornmütig, oder ist sein Tun von dieser Art? Meinen seine Worte es nicht gut mit dem, der rechtschaffen wandelt?«',
        8: 'Aber ihr seid es, die feindselig gegen mein Volk auftreten! Vom Rock herunter reißt ihr den Mantel denen ab, die arglos vorüberziehen, die von Streit nichts wissen wollen.',
        9: 'Die Frauen meines Volkes vertreibt ihr aus ihrem beglückenden Heim und raubt ihren kleinen Kindern meinen Ehrenschmuck auf immer.',
        10: '»Packt euch!« (so sagt ihr) und »hinweg mit euch, denn hier ist eures Bleibens nicht!« Um einer geringen Kleinigkeit willen vollzieht ihr grausam Pfändung.',
        11: 'Ja, wenn jemand käme, der dem Winde nachliefe und euch Lug und Trug vortrüge: »Ich will dir von Wein und Würztrank predigen!« – der wäre ein Prediger für dieses Volk!',
        12: '»Sammeln, ja sammeln will ich dich, Jakob, insgesamt; zusammenbringen, ja zusammenbringen will ich, was von Israel noch übrig ist! Vereinigen will ich sie wie Schafe in der Hürde, wie eine Herde auf der Trift, so daß sie eine von Menschen wimmelnde Menge bilden.«',
        13: 'An ihrer Spitze zieht dann der leitende Widder dahin, sie brechen durch, ziehen durch das Tor und gehen hinaus: ihr König schreitet vor ihnen her und der HERR selber an ihrer Spitze.',
    },
    3: {
        1: 'Da sagte ich: »Höret doch, ihr Häupter Jakobs und ihr Obersten des Hauses Israel! Kommt es euch nicht zu, das Recht zu kennen?',
        2: 'Und doch haßt ihr das Gute und liebt das Böse; ihr reißt den Leuten die Haut vom Leibe und das Fleisch von den Knochen;',
        3: 'ihr haßt das Fleisch meines Volkes, zieht ihnen die Haut vom Leibe ab und zerschlagt ihnen die Knochen, ihr zerlegt sie wie (einen Braten) im Kochtopf und wie Fleischstücke im Kessel.«',
        4: 'Dereinst werden sie zum HERRN schreien, doch er wird sie nicht erhören, sondern sein Angesicht zu jener Zeit vor ihnen verbergen, wie sie es mit ihrem bösen Tun verdient haben.',
        5: 'So hat der HERR gegen die Propheten gesprochen, die mein Volk irreführen, die, solange ihre Zähne etwas zu beißen haben, Frieden verkünden, aber dem, der ihnen nichts in den Mund steckt, den Krieg erklären.',
        6: '»Darum soll es Nacht für euch werden, so daß ihr keine Gesichte schaut, und Finsternis für euch eintreten, so daß keine Weissagung stattfindet; da soll die Sonne für die Propheten untergehen und der Tag über ihnen zu finsterer Nacht werden;',
        7: 'dann werden die Seher beschämt dastehen und die Wahrsager erröten müssen; und sie werden sich alle den Bart verhüllen, weil keine Antwort von Gott mehr erfolgt.«',
        8: 'Ich dagegen bin mit Kraft erfüllt, mit dem Geist des HERRN und mit Rechtsgefühl und Mut, um Jakob seine Treulosigkeit vorzuhalten und Israel seine Sünde.',
        9: 'Höret doch dieses, ihr Häupter des Hauses Jakob und ihr Obersten des Hauses Israel, die ihr das Recht verabscheut und alles Gerade krumm macht,',
        10: 'die ihr Zion mit Blutvergießen aufbaut und Jerusalem mit Unrecht!',
        11: 'Seine Häupter sprechen Recht für Geschenke, seine Priester erteilen Rechtsbescheide für Bezahlung, und seine Propheten wahrsagen für Geld; und dabei verlassen sie sich auf den HERRN, daß sie sagen: »Ist nicht der HERR in unserer Mitte? Uns kann kein Unglück widerfahren!«',
        12: 'Darum wird um euretwillen Zion zu Ackerland umgepflügt und Jerusalem zu einer Trümmerstätte werden und der Tempelberg zu einer bewaldeten Höhe!',
    },
    4: {
        1: 'Am Ende der Tage aber wird es geschehen, daß der Tempelberg des HERRN festgegründet dasteht an der Spitze der Berge und über die anderen Höhen erhaben; dann werden die Völker zu ihm strömen',
        2: 'und zahlreiche Völkerschaften sich aufmachen und sagen: »Kommt, laßt uns zum Berge des HERRN hinaufziehen und zum Hause des Gottes Jakobs, damit er uns über seine Wege belehre und wir auf seinen Pfaden wandeln!« Denn von Zion wird Belehrung ausgehen und das Wort des HERRN von Jerusalem.',
        3: 'Dann wird er zwischen vielen Völkern richten und mächtigen Völkerschaften Recht sprechen bis in weite Ferne. Da werden sie ihre Schwerter zu Pflugscharen umschmieden und ihre Lanzenspitzen zu Winzermessern. Kein Volk wird noch das Schwert gegen ein anderes Volk erheben, noch sich hinfort auf den Krieg einüben;',
        4: 'sie werden ein jeder unter seinem Weinstock und unter seinem Feigenbaum sitzen, ohne daß jemand sie aufschreckt; denn der Mund des HERRN der Heerscharen hat es verheißen.',
        5: 'Mögen alle Völker ein jedes im Namen seines Gottes wandeln – wir wollen im Namen des HERRN, unsers Gottes, wandeln immer und ewig!',
        6: '»An jenem Tage« – so lautet der Ausspruch des HERRN –, »da will ich sammeln, was hinkt, und zusammenbringen, was zerstreut ist, und alle, denen ich Unheil zugefügt habe.',
        7: 'Und ich will die Hinkenden zu einem Überrest machen und das Weitentfernte zu einem starken Volke; und als König wird der HERR über sie herrschen auf dem Berge Zion von nun an bis in Ewigkeit.«',
        8: 'Du aber, Herdenturm, du Hügel der Tochter Zion, an dich wird gelangen und zu dir zurückkehren die vormalige Herrschaft, das Königtum der Tochter Jerusalem.',
        9: 'Nun aber, warum erhebst du ein solches Jammergeschrei? Darüber, daß es keinen König in dir gibt? Oder ist dein Berater umgekommen, daß Wehen dich ergriffen haben wie ein Weib in Kindesnöten?',
        10: 'Ja, winde dich in Wehen und brich in Geschrei aus, Tochter Zion, wie ein Weib in Kindesnöten! Du mußt ja nun aus der Stadt hinausziehen, mußt auf freiem Felde lagern und bis Babylon wandern! Dort aber wirst du Rettung finden, dort wird der HERR dich aus der Hand deiner Feinde erlösen!',
        11: 'Jetzt freilich haben sich viele Völker gegen dich versammelt und rufen: »(Zion) soll entweiht werden, auf daß unser Auge sich an seinem Schicksal weide!«',
        12: 'Aber sie kennen die Gedanken des HERRN nicht und wissen nichts von seinem Ratschluß, daß er sie nämlich zusammengebracht hat wie Garben auf der Tenne.',
        13: 'Steh auf, Tochter Zion, und drisch! Denn ich will dein Horn zu Eisen und deine Hufe zu Erz machen, auf daß du viele Völker zermalmst und ihren Raub dem HERRN weihst und ihren Reichtum dem Herrn der ganzen Erde.',
        14: 'Und nun laß dich zusammendrängen, Tochter der Bedrängnis! Einen Belagerungswall haben sie gegen uns aufgeworfen, und mit dem Stock schlagen sie den Richter Israels ins Gesicht.',
    },
    5: {
        1: 'Du aber, Bethlehem-Ephrath, bist zwar zu klein, als daß du zu den Gaustädten Judas gehörtest, aber aus dir wird mir der hervorgehen, der in Israel Herrscher sein soll und dessen Herkunft der Vergangenheit, den Tagen der Urzeit, angehört.',
        2: 'Darum wird er sie preisgeben bis zu der Zeit, wo sie, die gebären soll, geboren hat und der Rest seiner Volksgenossen zu den Kindern Israel zurückkehrt.',
        3: 'Dann wird er auftreten und (seine Herde) weiden in der Kraft des HERRN, im hoheitsvollen Namen des HERRN, seines Gottes, so daß sie sicher wohnen; denn nunmehr wird er groß dastehen bis an die Enden der Erde.',
        4: 'Und folgender Art wird der Friede (mit den Assyrern) sein: Wenn Assyrien in unser Land einrückt und unser Gebiet betritt, dann werden wir sieben Hirten und acht fürstliche Männer gegen sie aufstellen;',
        5: 'die werden das Land der Assyrer mit dem Schwert abweiden, das Land Nimrods mit der blanken Klinge. So wird er uns vor den Assyrern erretten, wenn sie in unser Land einrücken und unser Gebiet betreten.',
        6: 'Dann wird der Überrest Jakobs (unter den Heiden) inmitten der Völkermenge sein wie der Tau vom HERRN, wie Regenschauer auf Wiesengras, die auf Menschen nicht warten und auf Menschenkinder nicht harren.',
        7: 'Dann wird der Überrest Jakobs unter den Heiden inmitten der Völkermenge sein wie ein Löwe unter den Tieren des Waldes, wie ein junger Leu unter Schafherden, der, wenn er hindurchgeht, niedertritt und rettungslos zerreißt. –',
        8: 'Hoch erhoben soll dein Arm über deine Bedränger sein, und alle deine Feinde sollen ausgerottet werden!',
        9: '»Und dann, an jenem Tage« – so lautet der Ausspruch des HERRN –, »da werde ich deine Rosse aus deiner Mitte vertilgen und deine Kriegswagen vernichten;',
        10: 'da werde ich die Städte deines Landes zerstören und alle deine Festungen niederreißen;',
        11: 'da werde ich auch die Zaubermittel aus deiner Hand vernichten, und Beschwörer soll es bei dir nicht mehr geben;',
        12: 'da werde ich auch deine Götzenbilder vernichten und deine Malsteine aus deiner Mitte, damit du dich vor dem Machwerk deiner Hände nicht mehr niederwirfst;',
        13: 'da werde ich deine Götzenbäume aus deiner Mitte ausreißen und deine Haine vernichten',
        14: 'und werde in Zorn und Ingrimm Rache an den Völkern nehmen, die nicht haben gehorchen wollen.«',
    },
    6: {
        1: 'Höret doch, was der HERR gesprochen hat: »Auf! Erhebe die Anklage angesichts der Berge und laß die Anhöhen deine Stimme vernehmen!«',
        2: 'Höret, ihr Berge, die Anklage des HERRN und merkt auf, ihr Grundfesten der Erde! Denn einen Rechtsstreit hat der HERR mit seinem Volke, und mit Israel will er sich auseinandersetzen:',
        3: '»Mein Volk, was habe ich dir zuleide getan und womit dich gekränkt? Lege Zeugnis gegen mich ab!',
        4: 'Ich habe dich doch aus dem Lande Ägypten hergeführt und dich aus dem Diensthause freigemacht, ich habe Mose, Aaron und Mirjam (als Führer) vor dir hergehen lassen.',
        5: 'Mein Volk, denke doch daran, was Balak, der Moabiterkönig, im Sinn gehabt und was Bileam, der Sohn Beors, ihm geantwortet hat, und an die Ereignisse auf dem Zuge von Sittim bis Gilgal, damit du die Gnadenerweise des HERRN erkennst!«',
        6: '»Womit soll ich vor den HERRN treten, mich beugen vor dem Gott der Höhe? Soll ich mit Brandopfertieren vor ihn treten, mit einjährigen Kälbern?',
        7: 'Hat der HERR Wohlgefallen an Tausenden von Widdern, an Zehntausenden von Bächen Öls? Oder soll ich meinen Erstgeborenen als Schuldopfer für mich hingeben, die Frucht meines Leibes als Sündopfer für mein Leben?«',
        8: 'Er hat dir kundgetan, o Mensch, was gut ist; und was fordert der HERR anderes von dir, als Gerechtigkeit zu üben und dich der Liebe zu befleißigen und demütig zu wandeln mit deinem Gott?',
        9: 'Horch! Der HERR ruft der Stadt zu – und Weisheit ist es, deinen Namen zu fürchten –; vernehmt (Landvolk und Stadtgemeinde) die Zuchtrute und den, der sie bestellt hat!',
        10: '»Ist immer noch unrecht erworbenes Gut im Hause des Gottlosen und das fluchwürdige, schwindsüchtige Getreidemaß?',
        11: 'Kann ich Straflosigkeit üben bei unrichtiger Waage und bei einem Beutel mit falschen Gewichtstücken?',
        12: 'Die Reichen in der Stadt sind voll von Gewalttätigkeit, ihre Bewohner reden Lügen, und ihre Zunge ist Trug in ihrem Munde.',
        13: 'So will denn auch ich dir unheilbar tiefe Wunden schlagen, dich vernichten um deiner Sünden willen:',
        14: 'du sollst essen, aber nicht satt werden, so daß dein Hunger ungestillt bleibt; schaffst du etwas beiseite, so sollst du es doch nicht retten, und was du gerettet hast, das will ich dem Schwerte preisgeben.',
        15: 'Du wirst säen, aber nicht ernten, wirst Oliven pressen, aber mit Öl dich nicht salben, und Trauben keltern, aber keinen Wein davon trinken.',
        16: 'Denn du hast die Lehren Omris befolgt und das ganze Treiben des Hauses Ahabs; und ihr seid nach ihren Ratschlägen gewandelt, damit ich dich zum abschreckenden Beispiel mache und deine Bewohnerschaft zum Gespött, und damit ihr den Hohn der Völker tragt!«',
    },
    7: {
        1: 'Wehe mir! Denn es ergeht mir wie bei der Obstlese, wie bei der Nachlese in der Weinernte: nicht eine Traube ist mehr da zum Essen, nicht eine Frühfeige, nach der mein Herz verlangt!',
        2: 'Ausgestorben sind die Frommen im Lande, und es gibt keinen Ehrlichen mehr unter den Menschen; allesamt liegen sie auf der Lauer nach Bluttaten, jeder macht Jagd auf den andern mit dem Fangnetz.',
        3: 'Auf das Böse sind ihre Hände gerichtet, um es eifrig auszuführen: der Fürst fordert, und der Richter steht ihm gegen Bezahlung zu Diensten; der Mächtige spricht das aus, wonach ihn in seiner Gier gelüstet, und dann flechten sie es ineinander.',
        4: 'Der Beste unter ihnen ist wie ein Dornstrauch, der Rechtschaffenste noch schlimmer als eine Dornhecke. Aber der Tag, den deine Späher angekündigt haben, dein Strafgericht, kommt heran: da wird die Bestürzung bei ihnen anheben.',
        5: 'Trauet keinem Genossen mehr, verlaßt euch nicht auf den Freund! Vor dem Weibe, das an deiner Brust liegt, hüte die Pforten deines Mundes!',
        6: 'Denn der Sohn mißachtet den Vater, die Tochter lehnt sich gegen ihre Mutter auf, die Schwiegertochter gegen ihre Schwiegermutter, und eines jeden Feinde sind die eigenen Hausgenossen. –',
        7: 'Ich aber will nach dem HERRN ausschauen, will harren auf den Gott, der mir hilft: mein Gott wird mich erhören!',
        8: 'Freue dich nicht über mich, meine Feindin! Denn bin ich auch gefallen, so stehe ich doch wieder auf, und sitze ich auch in Finsternis, so ist doch der HERR mein Licht.',
        9: 'Den Zorn des HERRN will ich tragen – denn ich habe gegen ihn gesündigt –, bis er meine Sache in die Hand nimmt und mir Recht schafft: er wird mich ans Licht herausführen, daß ich seine Gerechtigkeit mit Freuden schaue.',
        10: 'Auch meine Feindin wird es sehen, und Beschämung wird sie bedecken, sie, die zu mir gesagt hat: »Wo ist nun der HERR, dein Gott?« Meine Augen werden sich an ihrem Anblick weiden, wenn sie alsdann zertreten wird wie Kot auf der Straße. –',
        11: '»Ein Tag kommt, wo deine Mauern wieder aufgebaut, der Tag, wo deine Grenzen hinausgerückt werden.',
        12: 'An jenem Tage wird man zu dir kommen von Assyrien bis Ägypten und von Ägypten bis zum Euphratstrom, von einem Meer bis zum anderen und von einem Gebirge bis zum anderen.',
        13: 'Die Erde aber wird zur Wüste werden um ihrer Bewohner willen, zur Strafe für ihre Taten.«',
        14: 'Weide dein Volk mit deinem Hirtenstabe, die Herde deines Erbteils, die da abgesondert für sich das Waldland bewohnt auf dem Karmel! Laß sie auch wieder in Basan und Gilead weiden wie in den Tagen der Vorzeit!',
        15: '»Wie einst in den Tagen, als du aus Ägyptenland zogest, will ich sie wieder Wundertaten schauen lassen.',
        16: 'Die Heidenvölker werden es sehen und beschämt werden trotz all ihrer Macht; sie werden die Hand auf den Mund legen, und ihre Ohren werden taub sein;',
        17: 'sie werden Staub lecken wie die Schlangen, wie das Gewürm am Erdboden; zitternd werden sie aus ihren Burgen hervorkommen, bebend dem HERRN, unserm Gott, sich nahen und vor dir sich fürchten.«',
        18: 'Wer ist ein Gott wie du, der Sündenschuld vergibt und an den Missetaten des Überrestes seines Eigentumsvolkes vorübergeht? Der nicht ewiglich an seinem Zorn festhält, sondern Freude an der Gnade hat?',
        19: 'Er wird sich unser aufs neue erbarmen, wird unsere Verschuldungen niedertreten und alle unsere Missetaten in die Tiefen des Meeres versenken.',
        20: 'Du wirst an Jakob Treue, an Abraham Gnade erweisen, die du unsern Vätern zugeschworen hast in den Tagen der Vorzeit.',
    },
}
