NAME = 'FinSTLK2017: Pyhä Raamattu (STLK 2017)'
BOOK = 'Esther'

CHAPTERS = {
    1: {
        1: 'Ahasveroksen aikana – sen Ahasveroksen, joka hallitsi Intiasta Kuusin maahan saakka, sataa kahtakymmentä seitsemää maakuntaa – siihen aikaan,',
        2: 'kun kuningas Ahasveros istui kuninkaallisella valtaistuimellaan, joka oli Suusanin linnassa, tapahtui tämä.',
        3: 'Kolmantena hallitusvuotenaan hän laittoi pidot kaikille ruhtinailleen ja palvelijoilleen. Persian ja Meedian hallitseva voima, ylimykset ja maaherrat olivat hänen luonaan,',
        4: 'ja hän näytti heille kuninkaallisen kunniansa rikkautta ja suuruutensa loistavaa komeutta monta päivää, sata kahdeksankymmentä päivää.',
        5: 'Kun ne päivät olivat kuluneet, kuningas laittoi kaikelle Suusanin linnan väelle, niin pienille kuin suurillekin, kuninkaan palatsin puutarhan esipihaan seitsemän päivän pidot.',
        6: 'Pellava-, puuvilla- ja sinipunaverhoja oli kiinnitetty valkoisilla pellavanauhoilla ja purppuranpunaisilla nauhoilla hopeatankoihin ja valkoisiin marmoripylväisiin. Kultaisia ja hopeisia lepovuoteita oli pihalla, joka oli päällystetty vihreällä ja valkoisella marmorilla, helmiäisellä ja kirjavalla marmorilla.',
        7: 'Juotavaa tarjottiin kulta-astioissa, ja astiat olivat erimuotoisia. Kuninkaan viiniä oli runsaasti kuninkaalliseen tapaan.',
        8: 'Juomisessa oli lakina, ettei saanut olla mitään pakkoa, sillä niin kuningas oli käskenyt kaikkia hovimestareitaan, että oli tehtävä kunkin oman halun mukaan.',
        9: 'Kuningatar Vastikin laittoi naisille pidot kuningas Ahasveroksen kuninkaalliseen palatsiin.',
        10: 'Seitsemäntenä päivänä, kun kuninkaan sydän oli viinistä iloinen, hän käski Mehumanin, Bistan, Harbonan, Bigtan, Abagtan, Seetarin ja Karkaan, niiden seitsemän hoviherran, jotka toimittivat palvelusta kuningas Ahasveroksen luona,',
        11: 'tuoda kuningatar Vastin kuninkaallinen kruunu päässä kuninkaan eteen, että hän saisi näyttää kansoille ja ruhtinaille hänen kauneutensa, sillä hän oli ulkonäöltään ihana.',
        12: 'Mutta kuningatar Vasti kieltäytyi tulemasta, vaikka kuningas hoviherrojen välityksellä oli käskenyt. Kuningas suuttui kovin, ja hänessä syttyi viha.',
        13: 'Kuningas puhui viisaille, jotka tunsivat ajat – sillä näin oli tapana esittää kuninkaan sana kaikille lain ja oikeuden tuntijoille,',
        14: 'ja hänen lähimpänsä olivat Karsena, Seetar, Admata, Tarsis, Meres, Marsena ja Memukan, seitsemän Persian ja Meedian ruhtinasta, jotka näkivät kuninkaan kasvot ja istuivat valtakunnan ensimmäisinä –:',
        15: '"Mitä lain mukaan on tehtävä kuningatar Vastille, koska hän ei ole noudattanut käskyä, jonka kuningas Ahasveros on antanut hoviherrojen kautta?"',
        16: 'Memukan sanoi kuninkaan ja ruhtinaiden edessä: "Kuningatar Vasti ei ole rikkonut ainoastaan kuningasta vastaan, vaan myös kaikkia ruhtinaita vastaan ja kaikkia kansoja vastaan kuningas Ahasveroksen kaikissa maakunnissa.',
        17: "Kun kuningattaren teko tulee kaikkien vaimojen tietoon, se saattaa heidät halveksimaan aviomiehiään, he kun voivat sanoa: 'Kuningas Ahasveros käski tuoda kuningatar Vastin eteensä, mutta tämä ei tullut.'",
        18: 'Jo tänä päivänä voivat Persian ja Meedian ruhtinattaret, jotka kuulevat kuningattaren teon, puhua siitä kaikille kuninkaan ruhtinaille, ja siitä tulee halveksimista ja suuttumusta riittämiin asti.',
        19: 'Jos kuningas hyväksi näkee, julkaistakoon kuninkaallinen käsky ja kirjoitettakoon muuttumattomana Persian ja Meedian lakeihin, ettei Vasti enää saa tulla kuningas Ahasveroksen eteen ja että kuningas antaa hänen kuninkaallisen arvonsa toiselle, häntä paremmalle.',
        20: 'Kuninkaan antama säädös tulee tunnetuksi koko hänen valtakunnassaan, vaikka se onkin suuri, ja kaikki vaimot, sekä suuret että pienet, antavat kunnian aviomiehilleen."',
        21: 'Tämä puhe miellytti kuningasta ja ruhtinaita, ja kuningas teki Memukanin sanan mukaan.',
        22: 'Hän lähetti kaikkiin kuninkaan maakuntiin – kuhunkin maakuntaan sen omalla kirjoituksella ja kullekin kansalle sen omalla kielellä – kirjeet, että jokainen mies olkoon herra talossaan ja saakoon puhua oman kansansa kieltä.',
    },
    2: {
        1: 'Näiden tapausten jälkeen, kun kuningas Ahasveroksen viha oli asettunut, hän muisti Vastia ja mitä tämä oli tehnyt ja mitä hänestä oli päätetty.',
        2: 'Kuninkaan palvelijat, jotka toimittivat hänelle palvelusta, sanoivat: "Etsittäköön kuninkaalle nuoria neitsyitä, ihania näöltään.',
        3: 'Asettakoon kuningas kaikkiin valtakuntansa maakuntiin käskyläiset keräämään kaikki nuoret neitsyet, näöltään ihanat, Suusanin linnaan, vaimojen taloon, Heegain, kuninkaan hoviherran ja vaimojen vartijan, huostaan, ja annettakoon heille heidän kauneudenhoitonsa.',
        4: 'Neitsyt, johon kuningas mieltyy, tulkoon kuningattareksi Vastin sijaan." Tämä puhe miellytti kuningasta, ja hän teki niin.',
        5: 'Suusanin linnassa oli juutalainen mies, nimeltä Mordokai, Jaairin poika, joka oli Siimein poika, joka Kiisin poika, benjaminilainen,',
        6: 'joka oli viety Jerusalemista karkotukseen niiden karkotettujen joukossa, jotka vietiin samalla kuin Jekonja, Juudan kuningas, jonka Nebukadnessar, Baabelin kuningas, vei karkotukseen.',
        7: 'Hän [Mordokai] oli setänsä tyttären Hadassan, se on Esterin, kasvatusisä, sillä tämä oli isätön ja äiditön. Tyttö oli vartaloltaan kaunis ja näöltään ihana, ja hänen isänsä ja äitinsä kuoltua Mordokai oli ottanut hänet tyttärekseen.',
        8: 'Kun kuninkaan käsky ja laki tuli tunnetuksi ja kun kerättiin paljon tyttöjä Suusanin linnaan Heegain huostaan, otettiin Esterkin kuninkaan palatsiin Heegain, vaimojen vartijan, huostaan.',
        9: 'Tyttö miellytti häntä ja sai armon hänen edessään, ja hän antoi hänelle joutuin hänen kauneudenhoitonsa ja määrätyn ravinto-osansa sekä seitsemän valiopalvelijatarta kuninkaan palatsista ja siirsi hänet palvelijattarineen vaimojen taloon parhaaseen paikkaan.',
        10: 'Ester ei ilmaissut kansaansa eikä syntyperäänsä, sillä Mordokai oli häntä kieltänyt sitä ilmaisemasta.',
        11: 'Mutta Mordokai kuljeskeli joka päivä vaimojen talon esipihan edustalla saadakseen tietää, voiko Ester hyvin ja mitä hänelle on tapahtunut.',
        12: 'Kun jonkun tytön vuoro tuli mennä kuningas Ahasveroksen luo, sitten kun hänelle oli kaksitoista kuukautta tehty, niin kuin vaimoista oli määrätty – sillä niin pitkä aika kului heidän kauneudenhoitoonsa: kuusi kuukautta mirhaöljyllä, toiset kuusi kuukautta hajuaineilla sekä muilla naisten kauneudenhoitokeinoilla – meni tyttö kuninkaan luo.',
        13: 'Kaikki, mitä hän pyysi, annettiin hänelle mukaan vaimojen talosta kuninkaan palatsiin.',
        14: 'Illalla hän meni, ja aamulla hän palasi toiseen vaimojen taloon kuninkaan hoviherran Saasgan, sivuvaimojen vartijan, huostaan. Hän ei enää mennyt kuninkaan luo, paitsi jos kuningas oli häneen mieltynyt ja häntä kutsuttiin nimellä.',
        15: 'Kun Esterille, Mordokain sedän Abihailin tyttärelle, jonka Mordokai oli ottanut tyttärekseen, tuli vuoro mennä kuninkaan luo, hän ei halunnut mukaansa muuta, kuin mitä Heegai, kuninkaan hoviherra, vaimojen vartija, neuvoi. Ester sai armon kaikkien niiden edessä, jotka näkivät hänet.',
        16: 'Ester vietiin kuningas Ahasveroksen luo hänen kuninkaalliseen palatsiinsa kymmenennessä kuussa, se on teebet-kuussa, hänen seitsemäntenä hallitusvuotenaan.',
        17: 'Ester tuli kuninkaalle kaikkia muita naisia rakkaammaksi ja sai hänen edessään armon ja suosion ennen kaikkia muita neitsyitä, niin että tämä pani kuninkaallisen kruunun hänen päähänsä ja teki hänet kuningattareksi Vastin sijaan.',
        18: 'Kuningas laittoi suuret pidot kaikille ruhtinailleen ja palvelijoilleen, pidot Esterin kunniaksi, ja myönsi maakunnille verohuojennusta ja jakeli lahjoja, kuninkaalliseen tapaan.',
        19: 'Kun neitsyitä koottiin toinen kerta ja Mordokai istuskeli kuninkaan portissa',
        20: '– eikä Ester ollut ilmaissut syntyperäänsä eikä kansaansa, sillä Mordokai oli häntä siitä kieltänyt. Ester näet teki, mitä Mordokai käski, samoin kuin ollessaan hänen kasvattinaan –',
        21: 'niin siihen aikaan Mordokain istuskellessa kuninkaan portissa Bigtan ja Teres, kaksi kuninkaan hoviherraa, ovenvartijoita, suuttuivat ja etsivät tilaisuutta käydäkseen käsiksi kuningas Ahasverokseen.',
        22: 'Mutta se tuli Mordokain tietoon, ja hän ilmaisi sen kuningatar Esterille, ja Ester sanoi sen Mordokain nimessä kuninkaalle.',
        23: 'Asia tutkittiin, ja kun se havaittiin todeksi, ripustettiin heidät molemmat hirsipuuhun. Se kirjoitettiin aikakirjaan kuningasta varten.',
    },
    3: {
        1: 'Näiden tapausten jälkeen kuningas Ahasveros korotti agagilaisen Haamanin, Hammedatan pojan, ylensi hänet ja antoi hänelle ylimmän sijan kaikkien ruhtinaiden joukossa, jotka olivat hänen luonaan.',
        2: 'Kaikki kuninkaan palvelijat, jotka olivat kuninkaan portissa, polvistuivat ja heittäytyivät maahan Haamanin edessä, sillä niin oli kuningas käskenyt häntä kohdella. Mutta Mordokai ei polvistunut eikä heittäytynyt maahan.',
        3: 'Kuninkaan palvelijat, jotka olivat kuninkaan portissa, sanoivat Mordokaille: "Miksi sinä rikot kuninkaan käskyn?"',
        4: 'Kun he joka päivä sanoivat hänelle näin, mutta hän ei totellut heitä, he ilmoittivat tämän Haamanille nähdäkseen oliko Mordokain sanoma syy pätevä, sillä hän oli ilmoittanut heille olevansa juutalainen.',
        5: 'Kun Haaman näki, ettei Mordokai polvistunut eikä heittäytynyt maahan hänen edessään, Haaman tuli kiukkua täyteen.',
        6: 'Kun hänelle ilmoitettiin, mitä kansaa Mordokai oli, hän väheksyi käydä käsiksi yksinomaan Mordokaihin: Haaman etsi tilaisuutta hävittääkseen koko Ahasveroksen valtakunnasta kaikki juutalaiset, Mordokain kansan.',
        7: 'Ensimmäisessä kuussa, se on niisan-kuussa, kuningas Ahasveroksen kahdentenatoista vuotena, heitettiin Haamanin edessä puuria, se on arpaa, jokaisesta päivästä ja jokaisesta kuukaudesta, kahdenteentoista kuukauteen, se on adar-kuuhun, asti.',
        8: 'Haaman sanoi kuningas Ahasverokselle: "Eräs kansa on hajallaan ja erillään muiden kansojen seassa valtakuntasi kaikissa maakunnissa. Heidän lakinsa ovat toisenlaiset kuin kaikkien muiden kansojen. He eivät noudata kuninkaan lakeja, eikä kuninkaan sovi jättää heitä rauhaan.',
        9: 'Jos kuningas näkee hyväksi, kirjoitettakoon määräys, että heidät on tuhottava. Minä punnitsen kymmenentuhatta talenttia hopeaa virkamiehille vietäväksi kuninkaan aarrekammioihin."',
        10: 'Kuningas otti kädestään sinettisormuksensa ja antoi sen agagilaiselle Haamanille, Hammedatan pojalle, juutalaisten vastustajalle.',
        11: 'Kuningas sanoi Haamanille: "Hopea olkoon annettu sinulle, ja samoin se kansa, tehdäksesi sille, mitä hyväksi näet."',
        12: 'Kutsuttiin kuninkaan kirjurit ensimmäisessä kuussa, sen kolmantenatoista päivänä, ja kirjoitettiin, aivan kuten Haaman käski, määräys kuninkaan satraapeille ja jokaisen maakunnan käskynhaltijoille ja jokaisen kansan ruhtinaille, kuhunkin maakuntaan sen omalla kirjoituksella ja kullekin kansalle sen omalla kielellä. Kuningas Ahasveroksen nimessä se kirjoitettiin ja sinetöitiin kuninkaan sinettisormuksella.',
        13: 'Juoksijoiden mukana lähetettiin kaikkiin kuninkaan maakuntiin kirjeet, että oli hävitettävä, tapettava ja tuhottava kaikki juutalaiset, nuoret ja vanhat, lapset ja naiset, samana päivänä, kahdennentoista kuun, se on adar-kuun, kolmantenatoista päivänä, ja että oli ryöstettävä, mitä heiltä oli saalista saatavana.',
        14: 'Kirjeen jäljennös oli julkaistava lakina jokaisessa maakunnassa tiedoksi kaikille kansoille, että olisivat valmiit tuona päivänä.',
        15: 'Juoksijat lähtivät kuninkaan käskystä kiireisesti matkaan heti, kun laki oli annettu Suusanin linnassa. Kuningas ja Haaman istuivat juomaan, mutta Suusanin kaupunki oli hämmästyksissään.',
    },
    4: {
        1: 'Kun Mordokai sai tietää kaiken, mitä oli tapahtunut, Mordokai repäisi vaatteensa, pukeutui säkkiin ja tuhkaan ja meni keskelle kaupunkia ja huuteli kovia ja katkeria valitushuutoja.',
        2: 'Hän meni kuninkaan portin edustalle asti, sillä sisälle kuninkaan porttiin ei saanut mennä säkkiin puettuna.',
        3: 'Jokaisessa maakunnassa, joka paikassa, mihin kuninkaan käsky ja hänen lakinsa tuli, syntyi juutalaisten keskuudessa suuri suru: paastottiin, itkettiin ja valitettiin. Monet levittivät alleen säkin ja tuhkaa.',
        4: 'Kun Esterin palvelijattaret ja hänen hoviherransa tulivat ja kertoivat hänelle tämän, kuningatar joutui suureen tuskaan, ja hän lähetti vaatteita, että Mordokai puettaisiin niihin ja että hän riisuisi säkin yltään, mutta hän ei ottanut niitä vastaan.',
        5: 'Ester kutsui Hatakin, joka oli kuninkaan hoviherroja ja jonka tämä oli asettanut häntä palvelemaan, ja käski hänet Mordokain luo saadakseen tietää, mitä ja mistä syystä tämä kaikki oli.',
        6: 'Hatak meni Mordokain luo kaupungin torille, joka on kuninkaan portin edustalla,',
        7: 'ja Mordokai ilmoitti hänelle kaikki, mitä hänelle oli tapahtunut, ja myös tarkasti, kuinka paljon hopeaa Haaman oli luvannut punnita kuninkaan aarrekammioihin juutalaisten tuhoamisesta.',
        8: 'Myös jäljennöksen sen lain sanamuodosta, joka Suusanissa oli annettu heidän hävittämisekseen, hän antoi hänelle, että hän näyttäisi sen Esterille ja ilmoittaisi tälle asian sekä velvoittaisi häntä menemään kuninkaan luo anomaan armoa ja rukoilemaan häntä kansansa puolesta.',
        9: 'Hatak meni ja kertoi Esterille Mordokain sanat.',
        10: 'Ester puhui Hatakille ja käski hänen sanoa Mordokaille:',
        11: '"Kaikki kuninkaan palvelijat ja kuninkaan maakuntien kansa tietävät, että kuka ikinä, mies tai nainen, kutsumatta menee kuninkaan luo sisimpään esipihaan, on laki sama jokaiselle: hänet surmataan. Vain se, jota kohti kuningas ojentaa kultavaltikkansa, jää eloon. Mutta minua ei ole kolmeenkymmeneen päivään kutsuttu tulemaan kuninkaan luo."',
        12: 'Kun Mordokaille kerrottiin Esterin sanat,',
        13: 'Mordokai käski vastata Esterille: "Älä luulekaan, että sinä, kun olet kuninkaan linnassa, pelastut yksin kaikista juutalaisista.',
        14: 'Jos sinä tänä aikana olet vaiti, tulee apu ja pelastus juutalaisille muualta, mutta sinä ja sinun isäsi perhe tuhoudutte. Kuka tietää, etkö sinä juuri tällaista aikaa varten ole päässyt kuninkaalliseen arvoon?"',
        15: 'Ester käski vastata Mordokaille:',
        16: '"Mene ja kokoa kaikki Suusanin juutalaiset, ja paastotkaa puolestani. Olkaa syömättä ja juomatta kolme vuorokautta yötä päivää. Myös minä palvelijattarineni paastoan samoin. Sitten minä menen kuninkaan luo, vaikka se on vastoin lakia. Jos tuhoudun, niin tuhoudun."',
        17: 'Niin Mordokai meni ja teki, aivan kuten Ester oli häntä käskenyt.',
    },
    5: {
        1: 'Kolmantena päivänä Ester pukeutui kuninkaallisesti ja astui kuninkaan linnan sisimpään esipihaan vastapäätä kuninkaan linnaa. Kuningas istui kuninkaallisella valtaistuimellaan kuninkaallisessa linnassa vastapäätä linnan ovea.',
        2: 'Kun kuningas näki kuningatar Esterin seisovan esipihassa, tämä sai armon hänen silmiensä edessä, ja kuningas ojensi Esteriä kohti kultavaltikan, joka hänellä oli kädessä. Ester astui esiin ja kosketti valtikan päätä.',
        3: 'Kuningas sanoi hänelle: "Mikä sinun on, kuningatar Ester, ja mitä pyydät? Se sinulle annetaan, olkoon vaikka puoli valtakuntaa."',
        4: 'Ester vastasi: "Jos kuningas hyväksi näkee, tulkoon kuningas ja myös Haaman tänä päivänä pitoihin, jotka olen hänelle laittanut."',
        5: 'Kuningas sanoi: "Noutakaa kiireesti Haaman tehdäksemme Esterin toivomuksen mukaan." Kun kuningas ja Haaman olivat tulleet pitoihin, jotka Ester oli laittanut,',
        6: 'kuningas kysyi viinin juonnin aikana Esteriltä: "Mitä pyydät? Se sinulle annetaan, ja mitä haluat, se täytetään, olkoon vaikka puoli valtakuntaa."',
        7: 'Ester vastasi sanoen: "Tätä minä pyydän ja haluan:',
        8: 'jos olen saanut armon kuninkaan silmien edessä ja jos kuningas näkee hyväksi antaa minulle, mitä pyydän, ja täyttää, mitä haluan, niin tulkoot kuningas ja Haaman vielä pitoihin, jotka heille laitan. Huomenna teen kuninkaan toivomuksen mukaan."',
        9: 'Haaman lähti sieltä sinä päivänä iloisena ja hyvillä mielin. Kun Haaman näki Mordokain kuninkaan portissa eikä tämä noussut ylös eikä näyttänyt pelkäävän häntä, täytti viha Mordokaita kohtaan Haamanin.',
        10: 'Mutta Haaman hillitsi itsensä ja meni kotiinsa. Sitten hän lähetti noutamaan ystävänsä ja vaimonsa Sereksen.',
        11: 'Haaman kehuskeli heille rikkautensa loistoa ja poikiensa paljoutta, ja kuinka kuningas kaikessa oli korottanut hänet ja ylentänyt hänet ylemmäksi ruhtinaita ja kuninkaan palvelijoita.',
        12: 'Haaman sanoi: "Eipä kuningatar Esterkään antanut laittamiinsa pitoihin kuninkaan kanssa tulla kenenkään muun kuin minun. Huomiseksikin olen kuninkaan kanssa kutsuttu hänen luokseen.',
        13: 'Mutta tämä kaikki ei minua tyydytä, niin kauan kuin minä näen juutalaisen Mordokain istuvan kuninkaan portissa."',
        14: 'Hänen vaimonsa Seres ja kaikki hänen ystävänsä sanoivat hänelle: "Tehtäköön hirsipuu viisikymmentä kyynärää korkea, ja pyydä huomenaamulla kuninkaalta, että Mordokai ripustetaan siihen, niin voit mennä kuninkaan kanssa pitoihin iloisena." Tämä puhe miellytti Haamania, ja hän teetti hirsipuun.',
    },
    6: {
        1: 'Sinä yönä uni pakeni kuningasta. Hän käski tuoda muistettavien tapahtumien kirjan, aikakirjan.',
        2: 'Kun sitä luettiin kuninkaalle, huomattiin kirjoitetun, kuinka Mordokai oli ilmaissut, että Bigtan ja Teres, kaksi kuninkaan hoviherraa, ovenvartijoita, oli etsinyt tilaisuutta käydäkseen käsiksi kuningas Ahasverokseen.',
        3: 'Kuningas kysyi: "Mitä kunniaa ja korotusta Mordokai on tästä saanut?" Kuninkaan palvelijat, jotka toimittivat hänelle palvelusta, vastasivat: "Ei hän ole saanut mitään."',
        4: 'Kuningas kysyi: "Kuka on esipihassa?" Mutta Haaman oli tullut kuninkaan palatsin ulompaan esipihaan pyytämään kuninkaalta, että Mordokai ripustettaisiin hirsipuuhun, jonka hän oli pystyttänyt Mordokaita varten.',
        5: 'Kuninkaan palvelijat vastasivat hänelle: "Katso, esipihassa seisoo Haaman."',
        6: 'Kuningas sanoi: "Tulkoon sisään." Kun Haaman oli tullut, kuningas kysyi häneltä: "Mitä on tehtävä miehelle, jota kuningas tahtoo kunnioittaa?" Niin Haaman ajatteli sydämessään: "Kenellepä muulle kuningas tahtoisi osoittaa kunniaa kuin minulle?"',
        7: 'Haaman vastasi kuninkaalle: "Miehelle, jota kuningas tahtoo kunnioittaa,',
        8: 'tuotakoon kuninkaallinen puku, johon kuningas on ollut puettuna, ja hevonen, jolla kuningas on ratsastanut ja jonka päähän on pantu kuninkaallinen kruunu.',
        9: 'Puku ja hevonen annettakoon jollekin kuninkaan ruhtinaista, ylimyksistä. Puettakoon siihen mies, jota kuningas tahtoo kunnioittaa, ja kuljetettakoon häntä sen hevosen selässä kaupungin torilla ja huudettakoon hänen edellään: \'Näin tehdään miehelle, jota kuningas tahtoo kunnioittaa.\'"',
        10: 'Kuningas sanoi Haamanille: "Hae joutuin puku ja hevonen, kuten sanoit, ja tee näin juutalaiselle Mordokaille, joka istuu kuninkaan portissa. Älä jätä tekemättä mitään kaikesta, mitä olet puhunut."',
        11: 'Haaman otti puvun ja hevosen, puki Mordokain ja kuljetti häntä hevosen selässä kaupungin torilla ja huusi hänen edellään: "Näin tehdään miehelle, jota kuningas tahtoo kunnioittaa."',
        12: 'Sitten Mordokai palasi takaisin kuninkaan porttiin, mutta Haaman kiiruhti kotiinsa murehtien ja pää peitettynä.',
        13: 'Kun Haaman kertoi vaimolleen Serekselle ja kaikille ystävilleen kaiken, mitä hänelle oli tapahtunut, sanoivat hänen viisaansa ja hänen vaimonsa Seres hänelle: "Jos Mordokai, jonka edessä olet alkanut kaatua, on syntyjään juutalainen, et sinä voi hänelle mitään, vaan kaadut hänen eteensä maahan asti."',
        14: 'Heidän vielä puhuessaan hänen kanssaan tulivat kuninkaan hoviherrat ja veivät Haamanin kiireen vilkkaa pitoihin, jotka Ester oli laittanut.',
    },
    7: {
        1: 'Kuningas ja Haaman olivat saapuneet kuningatar Esterin kanssa juomaan.',
        2: 'Kuningas sanoi myös viinin juonnin toisena päivänä Esterille: "Mitä pyydät, kuningatar Ester? Se sinulle annetaan, ja mitä haluat? Se täytetään, olkoon vaikka puoli valtakuntaa."',
        3: 'Kuningatar Ester vastasi ja sanoi: "Jos olen saanut armon silmiesi edessä, kuningas, ja jos kuningas hyväksi näkee, annettakoon minulle oma henkeni, kun sitä pyydän, ja kansani, kun sitä haluan.',
        4: 'Sillä meidät on myyty, minut ja kansani, hävitettäviksi, tapettaviksi ja tuhottaviksi. Jos meidät olisi myyty vain orjiksi ja orjattariksi, olisin siitä vaiti, sillä sen vaivan takia ei kannattaisi kuningasta vaivata."',
        5: 'Kuningas Ahasveros sanoi ja kysyi kuningatar Esteriltä: "Kuka se on, ja missä se on, joka on rohjennut tehdä sellaista?"',
        6: 'Ester vastasi: "Se vastustaja ja vihamies on tuo paha Haaman." Silloin Haaman pelästyi kuningasta ja kuningatarta.',
        7: 'Kuningas nousi vihoissaan juomasta viiniä ja meni linnan puutarhaan, mutta Haaman jäi siihen pyytääkseen henkeänsä kuningatar Esteriltä, sillä hän näki, että kuninkaalla oli paha mielessä häntä vastaan.',
        8: 'Kun kuningas tuli linnan puutarhasta takaisin linnaan, jossa viiniä juotiin, Haaman oli juuri heittäytymässä lepovuoteelle, jolla kuningatar Ester lepäsi. Kuningas sanoi: "Vai tekee hän vielä väkivaltaa kuningattarelle linnassa läsnä ollessani!" Tuskin tämä sana oli päässyt kuninkaan suusta, kun jo Haamanin kasvot peitettiin.',
        9: 'Silloin Harbona, yksi kuningasta palvelevista hoviherroista, sanoi: "Katso, seisoohan Haamanin talon edessä hirsipuu viisikymmentä kyynärää korkea, se, minkä Haaman on teettänyt Mordokaita varten, jonka puhe kerran koitui kuninkaan hyväksi." Kuningas sanoi: "Ripustakaa hänet siihen."',
        10: 'Haaman ripustettiin hirsipuuhun, jonka hän oli pystyttänyt Mordokain varalle. Kuninkaan viha asettui.',
    },
    8: {
        1: 'Sinä päivänä kuningas Ahasveros lahjoitti kuningatar Esterille Haamanin, juutalaisten vastustajan, talon. Mordokai pääsi kuninkaan eteen, sillä Ester oli ilmoittanut, mikä Mordokai oli hänelle.',
        2: 'Kuningas otti kädestään sinettisormuksensa, jonka hän oli otattanut pois Haamanilta, ja antoi sen Mordokaille, ja Ester pani Mordokain Haamanin talon hoitajaksi.',
        3: 'Mutta Ester puhui vielä kuninkaan edessä ja lankesi hänen jalkojensa juureen, itki ja rukoili häntä torjumaan agagilaisen Haamanin pahuuden ja sen juonen, jonka tämä oli punonut juutalaisia vastaan.',
        4: 'Kuningas ojensi Esteriä kohti kultavaltikan, ja Ester nousi ja seisoi kuninkaan edessä.',
        5: 'Hän sanoi: "Jos kuningas hyväksi näkee ja jos minä olen löytänyt armon hänen edessään ja kuningas katsoo sen soveliaaksi ja minä olen hänen silmissään otollinen, kirjoitettakoon määräys ja peruutettakoon agagilaisen Haamanin, Hammedatan pojan, juoni, ne kirjeet, jotka hän kirjoitutti tuhotakseen juutalaiset kaikissa kuninkaan maakunnissa.',
        6: 'Sillä kuinka jaksaisin nähdä kansaani kohtaavan onnettomuuden, kuinka jaksaisin nähdä sukuni surman!"',
        7: 'Kuningas Ahasveros sanoi kuningatar Esterille ja juutalaiselle Mordokaille: "Katso, Haamanin talon olen lahjoittanut Esterille, ja hänet itsensä on ripustettu hirsipuuhun, koska hän oli käynyt käsiksi juutalaisiin.',
        8: 'Mutta nyt kirjoittakaa kuninkaan nimessä sellainen juutalaisia koskeva määräys, kuin hyväksi näette, ja sinetöikää se kuninkaan sinettisormuksella. Sillä kirjelmä, joka on kirjoitettu kuninkaan nimessä ja sinetöity kuninkaan sinettisormuksella, on peruuttamaton."',
        9: 'Niin kutsuttiin kuninkaan kirjurit silloin kolmannessa kuussa, se on siivan-kuussa, sen kahdentenakymmenentenä kolmantena päivänä, ja kirjoitettiin, aivan niin kuin Mordokai käski, määräys juutalaisille sekä satraapeille, käskynhaltijoille ja maaherroille sataan kahteenkymmeneen seitsemään maakuntaan, Intiasta Kuusin maahan saakka, kuhunkin maakuntaan sen omalla kirjoituksella ja kullekin kansalle sen omalla kielellä, myös juutalaisille heidän kirjoituksellaan ja kielellään.',
        10: 'Hän kirjoitutti kuningas Ahasveroksen nimessä ja sinetöi kuninkaan sinettisormuksella. Hän lähetti ratsulähettien mukana, jotka ratsastivat tammatarhoissa kasvatetuilla hovin hevosilla, kirjeet:',
        11: '"Kuningas sallii juutalaisten jokaisessa kaupungissa, missä heitä onkin, kokoontua puolustamaan henkeään hävittämällä, tappamalla ja tuhoamalla kansan ja maakunnan kaiken aseväen, joka heitä ahdistaa, sekä myös lapset ja naiset, ja ryöstämään, mitä heiltä on saatavana saalista,',
        12: 'samana päivänä kaikissa kuningas Ahasveroksen maakunnissa, kahdennentoista kuun, se on adar-kuun, kolmantenatoista päivänä."',
        13: 'Kirjeen jäljennös oli julkaistava lakina jokaisessa maakunnassa tiedoksi kaikille kansoille, ja että juutalaiset olisivat valmiit sinä päivänä kostamaan vihollisilleen.',
        14: 'Hovin hevosilla ratsastavat lähetit lähtivät kuninkaan käskystä kiireen vilkkaa ja nopeasti matkaan kohta, kun laki oli annettu Suusanin linnassa.',
        15: 'Mutta Mordokai lähti kuninkaan luota puettuna kuninkaalliseen sinipunaiseen purppuraan ja pellavapukuun, ja hänellä oli suuri kultakruunu ja viitta, tehty valkoisesta pellavakankaasta ja purppuranpunaisesta kankaasta. Silloin Suusanin kaupunki riemuitsi ja oli iloissaan.',
        16: 'Juutalaisille oli tullut onni, ilo, riemu ja kunnia,',
        17: 'ja jokaisessa maakunnassa ja kaupungissa, joka paikassa, mihin kuninkaan käsky ja hänen lakinsa tuli, oli juutalaisilla ilo ja riemu, pidot ja juhlat. Paljon oli maan kansoista niitä, jotka kääntyivät juutalaisiksi, sillä kauhu juutalaisia kohtaan oli vallannut heidät.',
    },
    9: {
        1: 'Kahdennessatoista kuussa, se on adar-kuussa, sen kolmantenatoista päivänä, jona kuninkaan käsky ja hänen lakinsa oli toimeenpantava, sinä päivänä, jona juutalaisten viholliset olivat toivoneet saavansa heidät valtaansa, mutta jona päinvastoin juutalaiset saivat valtaansa vihamiehensä,',
        2: 'kokoontuivat juutalaiset kaupungeissaan kaikissa kuningas Ahasveroksen maakunnissa käydäkseen käsiksi niihin, jotka olivat hankkineet heille onnettomuutta, eikä kukaan kestänyt heidän edessään, sillä kauhu heitä kohtaan oli vallannut kaikki kansat.',
        3: 'Silloin kaikki maaherrat, satraapit ja käskynhaltijat ja kuninkaan virkamiehet auttoivat juutalaisia, sillä kauhu Mordokaita kohtaan oli vallannut heidät.',
        4: 'Sillä Mordokai oli mahtava kuninkaan palatsissa, ja hänen maineensa levisi kaikkiin maakuntiin, sillä tämä mies, Mordokai, tuli yhä mahtavammaksi.',
        5: 'Juutalaiset voittivat kaikki vihollisensa lyöden miekoilla, surmaten ja tuhoten, ja tekivät vihamiehilleen, mitä tahtoivat.',
        6: 'Suusanin linnassa juutalaiset tappoivat ja tuhosivat viisisataa miestä.',
        7: 'Parsandatan, Dalfonin, Aspatan,',
        8: 'Pooratan, Adaljan, Aridatan,',
        9: 'Parmastan, Arisain, Aridain ja Vaisatan,',
        10: 'kymmenen Haamanin, Hammedatan pojan, juutalaisten vastustajan, poikaa, he tappoivat, mutta saaliiseen he eivät käyneet käsiksi.',
        11: 'Sinä päivänä tuli Suusanin linnassa tapettujen luku kuninkaan tietoon.',
        12: 'Niin kuningas sanoi kuningatar Esterille: "Suusanin linnassa juutalaiset ovat tappaneet ja tuhonneet viisisataa miestä ja Haamanin kymmenen poikaa, muissa kuninkaan maakunnissa mitä lienevätkään tehneet! Mitä nyt pyydät? Se sinulle annetaan, ja mitä vielä haluat? Se täytetään."',
        13: 'Niin Ester sanoi: "Jos kuningas hyväksi näkee, sallittakoon Suusanin juutalaisten huomennakin tehdä saman lain mukaan kuin tänä päivänä. Ripustettakoon Haamanin kymmenen poikaa hirsipuuhun."',
        14: 'Kuningas käski tehdä niin. Sitten siitä annettiin laki Suusanissa, ja Haamanin kymmenen poikaa ripustettiin.',
        15: 'Suusanin juutalaiset kokoontuivat myös adar-kuun neljäntenätoista päivänä ja tappoivat Suusanissa kolmesataa miestä, mutta saaliiseen he eivät käyneet käsiksi.',
        16: 'Myös muut juutalaiset, jotka olivat kuninkaan maakunnissa, olivat kokoontuneet puolustamaan henkeään ja päässeet rauhaan vihollisistaan tapettuaan vihamiehiään seitsemänkymmentäviisi tuhatta – käymättä käsiksi saaliiseen –',
        17: 'adar-kuun kolmantenatoista päivänä. He lepäsivät sen kuun neljännentoista päivän viettäen sen pito- ja ilopäivänä.',
        18: 'Mutta Suusanin juutalaiset olivat kokoontuneet sen kuun kolmantenatoista ja neljäntenätoista päivänä, ja he lepäsivät sen kuun viidennentoista päivän viettäen sen pito- ja ilopäivänä.',
        19: 'Sen tähden maaseudun juutalaiset, jotka asuvat maaseutukaupungeissa, viettävät adar-kuun neljännentoista päivän ilo-, pito- ja juhlapäivänä ja lähettävät toisilleen maistiaisia.',
        20: 'Mordokai pani kirjaan nämä tapaukset. Hän lähetti kirjeet kaikille juutalaisille kuningas Ahasveroksen kaikkiin maakuntiin, lähellä ja kaukana oleville,',
        21: 'säätäen heille, että heidän oli vietettävä adar-kuun neljättätoista päivää ja saman kuun viidettätoista päivää joka vuosi,',
        22: 'koska juutalaiset niinä päivinä olivat päässeet rauhaan vihollisistaan ja siinä kuussa murhe oli kääntynyt heille iloksi ja suru juhlaksi – että heidän oli vietettävä ne päivät pito- ja ilopäivinä ja lähetettävä toisilleen maistiaisia ja köyhille lahjoja.',
        23: 'Juutalaiset ottivat pysyväksi tavaksi, mitä jo olivat alkaneet tehdä ja mitä Mordokai oli heille kirjoittanut.',
        24: 'Koska agagilainen Haaman, Hammedatan poika, kaikkien juutalaisten vastustaja, oli punonut juonen juutalaisia vastaan tuhotakseen heidät ja oli heittänyt puurin, se on arvan, hävittääkseen ja tuhotakseen heidät,',
        25: 'ja koska sen tultua kuninkaan tietoon tämä oli kirjeellisesti määrännyt, että Haamanin pahan juonen, jonka hän oli punonut juutalaisia vastaan, tuli kääntyä hänen omaan päähänsä ja että hänet ja hänen poikansa oli ripustettava hirsipuuhun,',
        26: 'sen tähden antoivat he näille päiville nimeksi puurim, puur-sanan mukaan. Sen tähden, tuon käskykirjeen koko sisällyksen johdosta ja sen johdosta, mitä he itse olivat näin nähneet ja mitä heille oli tapahtunut,',
        27: 'juutalaiset säätivät ja ottivat itselleen ja jälkeläisilleen ja kaikille heihin liittyville muuttumattomaksi ja pysyväksi tavaksi, että näitä kahta päivää oli vietettävä määräyksen mukaisesti ja määräaikana joka vuosi',
        28: 'ja että jokaisen sukupolven ja suvun oli näitä päiviä muistettava ja vietettävä joka maakunnassa ja kaupungissa sekä että näiden puurim-päivien tuli säilyä muuttumattomina juutalaisten keskuudessa eikä niiden muisto saanut hävitä heidän jälkeläisiltään.',
        29: 'Kuningatar Ester, Abihailin tytär, ja juutalainen Mordokai kirjoittivat kaiken valtansa nojalla kirjoituksia saattaakseen säädöksenä voimaan tämän toisen puurim-käskykirjeen.',
        30: 'Mordokai lähetti kirjeet, ystävällisin ja vilpittömin sanoin, kaikille juutalaisille Ahasveroksen valtakunnan sataan kahteenkymmeneen seitsemään maakuntaan',
        31: 'saattaakseen säädöksenä voimaan nämä puurim-päivät niiden määräaikoina, kuten juutalainen Mordokai ja kuningatar Ester olivat niistä säätäneet ja niin kuin juutalaiset itse olivat säätäneet itselleen ja jälkeläisilleen määräykset niihin kuuluvista paastoista ja valitushuudoista.',
        32: 'Näin säädettiin Esterin käskystä nämä puurim-määräykset ja kirjoitettiin kirjaan.',
    },
    10: {
        1: 'Kuningas Ahasveros saattoi työveron alaiseksi sekä mannermaan että merensaaret.',
        2: 'Kaikki hänen valta- ja urotyönsä ja kertomus Mordokain suuruudesta, johon kuningas hänet korotti, ovat kirjoitettuina Meedian ja Persian kuningasten aikakirjassa.',
        3: 'Sillä juutalainen Mordokai oli kuningas Ahasveroksen lähin mies ja oli suuri juutalaisten keskuudessa ja rakas lukuisille veljilleen, koska hän toimi kansansa parhaaksi ja puhui koko heimonsa onnen puolesta.',
    },
}
