NAME = 'SloKJV: Slovenian translation of Holy Bible King James Version (1769)'
BOOK = 'Esther'

CHAPTERS = {
    1: {
        1: 'Pripetilo se je torej v dneh kralja Ahasvérja (to je Ahasvérja, ki je kraljeval od Indije celo do Etiopije, nad sto sedemindvajsetimi provincami),',
        2: 'da je v tistih dneh, ko je Kralj Ahasvér sedel na prestolu svojega kraljestva, ki je bilo v palači Suze,',
        3: 'v tretjem letu njegovega kraljevanja, priredil gostijo vsem svojim princem in svojim služabnikom; moči Perzije in Medije, plemičem in princem provinc, ki so bili pred njim,',
        4: 'ko jim je mnogo dni kazal bogastva svojega veličastnega kraljestva in čast svojega odličnega veličanstva, celó sto osemdeset dni.',
        5: 'Ko so ti dnevi minili, je kralj priredil gostijo vsemu ljudstvu, ki je bilo prisotno v palači Suze, tako velikim kakor malim, sedem dni na dvoru vrta kraljeve palače,',
        6: 'kjer so bile bele, zelene in modre tanke preproge, pritrjene z vrvicami iz tankega lanenega platna in vijolične, k srebrnim obročem in stebrom iz marmorja. Postelje so bile iz zlata in srebra, na tlaku iz rdečega, modrega, belega in črnega marmorja.',
        7: 'Dajali so jim piti iz zlatih posod (posode so bile različne ena od druge) in kraljevega vina v obilju, glede na kraljevo razkošje.',
        8: 'Pitje je bilo glede na postavo. Nihče ni silil, kajti tako je kralj določil vsem častnikom njegove hiše, da naj storijo glede na užitek vsakega človeka.',
        9: 'Prav tako je kraljica Vaští pripravila gostijo za ženske v kraljevi hiši, ki je pripadala Kralju Ahasvérju.',
        10: 'Na sedmi dan, ko je bilo kraljevo srce veselo od vina, je ukazal Mehumánu, Bizetáju, Harbonáju, Bigtáju, Abagtáju, Zetárju in Karkásu, sedmim glavnim dvornim upraviteljem, ki so služili v prisotnosti Kralja Ahasvérja,',
        11: 'da privedejo kraljico Vaští s kraljevo krono pred kralja, da ljudstvu in princem pokaže njeno lepoto, kajti bila je lepa na pogled.',
        12: 'Toda kraljica Vaští je odklonila, da pride na kraljevo zapoved po njegovih glavnih dvornih upraviteljih. Zato je bil kralj zelo ogorčen in njegova jeza je gorela v njem.',
        13: 'Potem je kralj rekel modrim možem, ki so poznali čase (Kajti tak je bil kraljev običaj do vseh teh, ki so poznali postavo in sodbo',
        14: 'in takoj poleg njega so bili Karšenáj, Šetár, Admát, Taršíš, Meres, Marsenáj in Memuhán, sedem princev iz Perzije in Medije, ki so videli kraljevo obličje in ki so prvi sedeli v kraljestvu.)',
        15: '»Kaj naj storimo kraljici Vaští, glede na postavo, ker po glavnih dvornih upraviteljih ni izpolnila zapovedi Kralja Ahasvérja?«',
        16: 'Memuhán je pred kraljem in princi odgovoril: »Kraljica Vaští ni storila narobe samo kralju, temveč tudi vsem princem in vsemu ljudstvu, ki so po vseh provincah Kralja Ahasvérja.',
        17: 'Kajti to dejanje kraljice bo prišlo povsod do vseh žensk, tako da bodo v svojih očeh prezirale svoje soproge, ko bo to sporočeno: ›Kralj Ahasvér je zapovedal kraljici Vaští, da bi bila privedena predenj, toda ni prišla.‹',
        18: 'Podobno bodo gospe iz Perzije in Medije, ki so slišale o kraljičinem dejanju, ta dan rekle vsem kraljevim princem. Tako bo vstalo preveč zaničevanja in besa.',
        19: 'Če to ugaja kralju, naj gre od njega kraljeva zapoved in naj bo ta zapisana med postave Perzijcev in Medijcev, da ta ne bo predrugačena: ›Da Vaští ne pride več pred Kralja Ahasvérja. Kralj pa naj njen kraljevi stan izroči drugi, ki je boljša kakor ona.‹',
        20: 'Ko bo kraljevi odlok, ki ga bo izdal, razglašen po vsem njegovem kraljestvu (kajti to je veliko), bodo vse žene dale svojim soprogom spoštovanje, tako malim, kakor velikim.«',
        21: 'Govor je ugajal kralju in princem in kralj je storil glede na Memuhánovo besedo.',
        22: 'Kajti poslal je pisma v vse kraljeve province, v vsako provinco glede na njeno pisavo in vsakemu ljudstvu glede na njihov jezik, da bi vsak mož vladal v svoji lastni hiši in da bi bilo to razglašeno glede na jezik vsakega ljudstva.',
    },
    2: {
        1: 'Po teh stvareh, ko je bil bes Kralja Ahasvérja pomirjen, se je spomnil Vaští in kar je storila in kaj je bilo odrejeno zoper njo.',
        2: 'Potem so mu kraljevi služabniki, ki so mu služili, rekli: »Naj bodo za kralja poiskane lepe mlade device.',
        3: 'Kralj naj določi častnike po vseh provincah svojega kraljestva, da lahko zberejo skupaj vse lepe mlade device v palačo Suze, v žensko hišo, pod oskrbo Hege, kraljevega glavnega upravitelja, čuvaja žensk in naj jim bodo dane njihove stvari za očiščevanje',
        4: 'in naj bo dekle, ki ugaja kralju, kraljica namesto Vaští.« Stvar je kralju ugajala in tako je storil.',
        5: 'Torej v palači Suze je bil nek Jud, katerega ime je bilo Mordohaj, sin Jaíra, sinú Šimíja, sinú Kiša, Benjaminovec,',
        6: 'ki je bil iz Jeruzalema odveden z ujetništvom, ki so bili odvedeni z Jehoníjem, Judovim kraljem, ki ga je babilonski kralj Nebukadnezar odvedel proč.',
        7: 'Vzgajal je Hadáso, to je Estero, hčer svojega strica, kajti ni imela niti očeta niti matere, deklica pa je bila lepa in krasna, ki si jo je Mordohaj, ko sta bila njen oče in mati mrtva, vzel za svojo lastno hčer.',
        8: 'Tako se je pripetilo, ko se je slišala kraljeva zapoved in njegov odlok in ko je bilo mnogo deklet skupaj zbranih v palači Suze, k oskrbi Hegája, da je bila tudi Estera privedena v kraljevo hišo, v oskrbo Hegája, čuvaja žensk.',
        9: 'Dekle mu je ugajalo in od njega doseglo naklonjenost. Naglo ji je dal njene stvari za očiščenje, s takšnimi stvarmi, kakor so ji pripadale in sedem služabnic, ki so bile primerne, da so ji bile izročene iz kraljeve hiše, ter njo in njene deklice privedel v najboljši prostor ženske hiše.',
        10: 'Estera pa ni prikazala svojega ljudstva niti svojega sorodstva, kajti Mordohaj ji je naročil, da naj tega ne prikaže.',
        11: 'Mordohaj pa je vsak dan hodil pred dvor ženske hiše, da izve, kako se Estera počuti in kaj bo postalo iz nje.',
        12: 'Torej, ko je prišla za vsako deklico vrsta, da gre h Kralju Ahasvérju, potem ko je bila dvanajst mesecev, glede na določen način za ženske (kajti tako so bili dnevi njihovih očiščevanj dovršeni, namreč šest mesecev z oljem iz mire in šest mesecev s prijetnimi dišavami in z drugimi stvarmi za očiščevanje žensk),',
        13: 'potem je vsako dekle tako prišlo h kralju. Karkoli si je želela, ji je bilo dano, da gre z njo iz ženske hiše v kraljevo hišo.',
        14: 'Zvečer je odšla, naslednji dan pa se je vrnila v drugo žensko hišo, k oskrbi Šaašgáza, kraljevega glavnega upravitelja, ki je čuval priležnice. Ni več prišla h kralju, razen če se je kralj razveseljeval v njej in da je bila poklicana po imenu.',
        15: 'Torej ko je bila vrsta na Esteri, hčeri Abihájila, Mordohajevega strica, ki si jo je vzel za svojo hčer, je prišla, da gre noter h kralju. Ničesar ni zahtevala, razen kar je Hegáj, kraljevi glavni upravitelj, čuvaj žensk, določil. In Estera je dosegla naklonjenost v očeh vseh tistih, ki so pogledali nanjo.',
        16: 'Tako je bila Estera odpeljana h Kralju Ahasvérju, v njegovo kraljevo hišo, v desetem mesecu, ki je mesec tébet, v sedmem letu njegovega vladanja.',
        17: 'Kralj pa je ljubil Estero nad vsemi ženskami in dosegla je milost in naklonjenost v njegovem pogledu, bolj kot vse device, tako da je kraljevo krono postavil na njeno glavo in jo naredil kraljico namesto Vaští.',
        18: 'Takrat je kralj naredil veliko praznovanje vsem svojim princem in svojim služabnikom, celó Esterin praznik. Provincam je naredil razbremenitev in dal darove glede na kraljevo razkošje.',
        19: 'Ko so drugič zbirali device skupaj, takrat je Mordohaj sedel pri kraljevih velikih vratih.',
        20: 'Estera še ni prikazala svojega sorodstva niti svojega ljudstva, kakor ji je Mordohaj naročil, kajti Estera je izvršila Mordohajevo zapoved, podobno kakor, ko je bila vzgajana pri njem.',
        21: 'V tistih dneh, medtem ko je Mordohaj sedel pri kraljevih velikih vratih, sta bila dva izmed glavnih dvornih upraviteljev, Bigtáj in Tereš, izmed tistih, ki sta varovala vrata, ogorčena in iskala, da položita roko na Kralja Ahasvérja.',
        22: 'Stvar pa je bila odkrita Mordohaju, ki je to povedal kraljici Esteri in Estera je v Mordohajevem imenu o tem potrdila kralju.',
        23: 'Ko je bilo o tej zadevi opravljeno zasliševanje, je bilo to razkrito, zato sta bila oba obešena na drevo. To je bilo pred kraljem zapisano v kroniško knjigo.',
    },
    3: {
        1: 'Po teh stvareh je Kralj Ahasvér povišal Hamána, Hamedátovega sina, Agágovca in ga napredoval in njegov sedež postavil nad vse prince, ki so bili z njim.',
        2: 'Vsi kraljevi služabniki, ki so bili pri kraljevih velikih vratih, so se priklonili in častili Hamána, kajti kralj je glede njega tako zapovedal. Mordohaj pa se ni priklonil niti ga ni častil.',
        3: 'Potem so kraljevi služabniki, ki so bili pri kraljevih velikih vratih, Mordohaju rekli: »Zakaj prestopaš kraljevo zapoved?«',
        4: 'Pripetilo se je torej, ko so mu dnevno govorili in jim ni prisluhnil, da so povedali Hamánu, da vidijo, ali bodo Mordohajeve zadeve obstale, kajti povedal jim je, da je bil Jud.',
        5: 'Ko je Hamán videl, da se Mordohaj ni priklonil niti ga ni častil, potem je bil Hamán poln besa.',
        6: 'Zdelo se mu je v posmeh, da položi roke samo na Mordohaja, kajti pokazali so mu Mordohajevo ljudstvo. Zato je Hamán iskal, da uniči vse Jude, ki so bili po celotnem Ahasvérjevem kraljestvu, torej Mordohajevo ljudstvo.',
        7: 'V prvem mesecu, ki je mesec nisán, v dvanajstem letu kralja Ahasvérja, so metali pur, kar je žreb, pred Hamánom iz dneva v dan in iz meseca v mesec, do dvanajstega meseca, ki je mesec adár.',
        8: 'Hamán je rekel Kralju Ahasvérju: »Tam je neko ljudstvo, razkropljeno naokoli in razpršeno med ljudstvom po vseh provincah tvojega kraljestva. Njihove postave so različne od vsega ljudstva niti se ne držijo kraljevih postav. Zatorej to ni za kraljevo korist, da jih trpi.',
        9: 'Če to ugaja kralju, naj bo to zapisano, da bodo lahko uničeni, jaz pa bom plačal deset tisoč talentov srebra rokam tistih, ki so zadolženi za to delo, da to prinesejo v kraljeve zakladnice.«',
        10: 'Kralj je iz svoje roke snel svoj prstan ter ga dal Hamedátovemu sinu Hamánu, Agágovcu, sovražniku Judov.',
        11: 'Kralj je rekel Hamánu: »Srebro ti je dano, tudi ljudstvo, da storiš z njimi, kakor se ti zdi dobro.«',
        12: 'Potem so bili na trinajsti dan prvega meseca poklicani kraljevi pisarji in bilo je napisano glede na vse, kar je Hamán ukazal kraljevim poročnikom in voditeljem, ki so bili nad vsako provinco in vladarjem vsakega ljudstva vsake province, glede na njihovo pisavo in vsakemu ljudstvu glede na njihov jezik. V imenu kralja Ahasvérja je bilo napisano in zapečateno s kraljevim prstanom.',
        13: 'Pisma so bila po slih poslana v vse kraljeve province, da uničijo, ubijejo in pogubijo vse Jude, tako mlade kakor stare, majhne otroke in ženske, na en dan, torej na trinajsti dan dvanajstega meseca, ki je mesec adár in da si njihov dobiček vzamejo za plen.',
        14: 'Prepis pisanja za zapoved, ki naj bo predana v vsako provinco, je bilo razglašeno vsem ljudstvom, da bodo pripravljeni za ta dan.',
        15: 'Sli so odšli ven, podvizani s kraljevo zapovedjo in odlok je bil izdan v palači Suze. Kralj in Hamán pa sta se usedla, da pijeta, mesto Suze pa je bilo zbegano.',
    },
    4: {
        1: 'Ko je Mordohaj zaznal vse, kar je bilo storjeno, je Mordohaj raztrgal svoja oblačila in si nadel vrečevino s pepelom in odšel ven v sredo mesta ter vpil z glasnim in grenkim glasom.',
        2: 'Prišel je celo pred kraljeva velika vrata, kajti nihče ne more vstopiti v kraljeva velika vrata, oblečen z vrečevino.',
        3: 'V vsaki provinci, kamor sta prišla kraljeva zapoved in njegov odlok, je bilo med Judi veliko žalovanje, post, jokanje in tarnanje in mnogi so ležali v vrečevini in pepelu.',
        4: 'Tako so Esterine služabnice in njeni glavni dvorni upravitelji prišli in ji to povedali. Potem je bila kraljica silno užaloščena. Poslala je oblačilo, da obleče Mordohaja in da odstrani njegovo vrečevino proč iz njega, toda on tega ni sprejel.',
        5: 'Potem je Estera poklicala po Hatáha, enega izmed kraljevih glavnih dvornih upraviteljev, ki je bil določen, da ji služi in mu dala zapoved za Mordohaja, da izve kaj je bilo to in zakaj je bilo to.',
        6: 'Tako je Hatáh odšel k Mordohaju, na mestno ulico, ki je bila pred kraljevimi velikimi vrati.',
        7: 'Mordohaj mu je povedal o vsem, kar se mu je zgodilo in o vsoti denarja, ki ga je Hamán obljubil plačati v kraljeve zakladnice za Jude, da jih uniči.',
        8: 'Dal mu je tudi kopijo pisanja odloka, ki je bil izdan v [mestu] Suze, da jih uniči, da ga pokaže Esteri in da ji to oznani in da jo zadolži, da naj bi šla h kralju, da mu izroči ponižno prošnjo in da pred njim sporoči zahtevo za svoje ljudstvo.',
        9: 'Hatáh je prišel in Esteri povedal Mordohajeve besede.',
        10: 'Estera je Hatáhu ponovno spregovorila in mu dala zapoved za Mordohaja:',
        11: '»Vsi kraljevi služabniki in ljudstvo kraljevih provinc vedo, da kdorkoli, ki ni poklican, bodisi moški ali ženska, pride h kralju na notranji dvor, je zanj ena postava, da ga usmrté, razen tistega, proti kateremu bo kralj iztegnil zlato žezlo, da bo lahko živel. Toda jaz nisem bila poklicana, da pridem h kralju teh trideset dni.«',
        12: 'Esterine besede so povedali Mordohaju.',
        13: 'Potem je Mordohaj zapovedal odgovoriti Esteri: »Ne misli si, da boš ti v kraljevi hiši ušla bolj kakor vsi Judje.',
        14: 'Kajti če ob tem času povsem ohranjaš svoj mir, potem bo povečanje in osvoboditev vstalo k Judom iz drugega kraja, toda ti in hiša tvojega očeta boste uničeni. Kdo ve, ali nisi prišla do kraljestva zaradi tega časa, kakor je ta?«',
        15: 'Potem jim je Estera zaukazala vrniti Mordohaju ta odgovor:',
        16: '»Pojdi, zberi skupaj vse Jude, ki so prisotni v [mestu] Suze in se postite zame in tri dni niti ne jejte niti ne pijte, ne ponoči ne podnevi. Tudi jaz in moje dekle se bomo prav tako postile in tako bom šla noter h kralju, kar ni glede na postavo, in če umrem, umrem.«',
        17: 'Tako je Mordohaj odšel svojo pot in storil glede na vse to, kar mu je Estera zapovedala.',
    },
    5: {
        1: 'Pripetilo se je torej na tretji dan, da si je Estera nadela svojo kraljevsko obleko in stopila na notranji dvor kraljeve hiše, nasproti kraljevi hiši in kralj je sedel na svojem kraljevem prestolu, v kraljevi hiši, nasproti velikim vratom hiše.',
        2: 'In bilo je tako, da ko je kralj zagledal kraljico Estero stati na dvoru, je ta dosegla naklonjenost v njegovem pogledu. Kralj je proti Esteri iztegnil zlato žezlo, ki je bilo v njegovi roki. Tako se je Estera približala in se dotaknila vrha žezla.',
        3: 'Potem ji je kralj rekel: »Kaj hočeš, kraljica Estera? Kakšna je tvoja prošnja? Dano ti bo celo do polovice kraljestva.«',
        4: 'Estera je odgovorila: »Če se to zdi kralju dobro, naj kralj in Hamán prideta danes na gostijo, ki sem jo pripravila zanj.«',
        5: 'Potem je kralj rekel: »Pripravite Hamána, da se podviza, da bo lahko storil, kakor je rekla Estera.« Tako sta kralj in Hamán prišla na gostijo, ki jo je pripravila Estera.',
        6: 'Kralj je pri vinski gostiji Esteri rekel: »Kaj je tvoja prošnja? Ta ti bo zagotovljena. Kaj je tvoja zahteva? Celo do polovice kraljestva ti bo izpolnjena.«',
        7: 'Potem je Estera odgovorila in rekla: »Moja prošnja in moja zahteva je,',
        8: 'če sem našla naklonjenost v kraljevih očeh in če to ugaja kralju, da zagotovi mojo prošnjo in da izvede mojo zahtevo, naj kralj in Hamán prideta na gostijo, ki jo bom pripravila zanju, jutri pa bom storila, kakor je rekel kralj.«',
        9: 'Potem je Hamán tega dne odšel radosten in z veselim srcem. Toda, ko je Hamán pri kraljevih velikih vratih zagledal Mordohaja, ki ni vstal niti se zaradi njega ni premaknil, je bil poln ogorčenja zoper Mordohaja.',
        10: 'Vendar se je Hamán zadržal. Ko pa je prišel domov, je poslal in dal poklicati po svoje prijatelje in svojo ženo Zêrešo.',
        11: 'Hamán jim je govoril o slavi svojih bogastev in množici svojih otrok in vseh stvareh, s katerimi ga je kralj povišal in kako ga je napredoval nad prince in kraljeve služabnike.',
        12: 'Poleg tega je Hamán rekel: »Da, kraljica Estera nobenemu drugemu ni dovolila vstopiti s kraljem na gostijo, ki jo je pripravila, razen meni in tudi jutri sem s kraljem povabljen k njej.',
        13: 'Vendar mi vse to nič ne koristi, dokler vidim Juda Mordohaja sedeti pri kraljevih velikih vratih.«',
        14: 'Potem so mu njegova žena Zêreša in vsi njegovi prijatelji rekli: »Naj bodo narejene petdeset komolcev visoke vislice in jutri spregovori kralju, da bo Mordohaj lahko obešen nanje. Potem pojdi vesel s kraljem na gostijo.« Stvar je ugajala Hamánu in velel je, da se naredijo vislice.',
    },
    6: {
        1: 'To noč kralj ni mogel spati in zapovedal je, da prinesejo knjigo kroniških zapisov in brani so bili pred kraljem.',
        2: 'Najdeno je bilo zapisano, da je Mordohaj povedal o Bigtánu in Terešu, o dveh izmed glavnih dvornih upraviteljev, čuvajema vrat, ki sta iskala, da položita roko na Kralja Ahasvérja.',
        3: 'Kralj je rekel: »Kakšna čast in dostojanstvo sta bila zaradi tega storjena Mordohaju?« Potem so kraljevi služabniki, ki so mu služili, rekli: »Nič ni bilo storjeno zanj.«',
        4: 'Kralj je rekel: »Kdo je na dvoru?« Torej Hamán je prišel na zunanji dvor kraljeve hiše, da spregovori kralju, da Mordohaja obesi na vislice, ki jih je pripravil zanj.',
        5: 'Kraljevi služabniki pa so mu rekli: »Glej, Hamán stoji na dvoru.« Kralj je rekel: »Naj vstopi.«',
        6: 'Tako je Hamán vstopil. Kralj mu je rekel: »Kaj naj bo storjeno človeku, ki se ga kralj razveseljuje, da ga počasti?« Torej Hamán je v svojem srcu mislil: ›Koga bi se kralj veselil, da ga počasti, bolj kakor mene?‹',
        7: 'Hamán je odgovoril kralju: »Za človeka, ki se ga kralj razveseljuje, da ga počasti,',
        8: 'naj bo prinesena kraljevska obleka, ki jo kralj uporablja za nošnjo in konj, na katerem jaha kralj in kraljeva krona, ki je postavljena na njegovi glavi.',
        9: 'Ta obleka in konj naj bosta izročena roki enega izmed kraljevih najplemenitejših princev, da bodo lahko s tem oblekli človeka, ki se ga kralj razveseljuje počastiti in naj ga na konjskem hrbtu povedejo po mestni ulici in pred njim razglašajo: ›Tako bo to storjeno človeku, ki se ga kralj razveseljuje, da ga počasti.‹«',
        10: 'Potem je kralj rekel Hamánu: »Podvizaj se in vzemi obleko in konja, kakor si rekel in celo tako stori Judu Mordohaju, ki sedi pri kraljevih velikih vratih. Naj ničesar ne manjka od vsega, kar si govoril.«',
        11: 'Potem je Hamán vzel obleko in konja ter oblekel Mordohaja in ga na konjskem hrbtu povedel po mestni ulici in pred njim razglašal: »Tako bo storjeno človeku, ki se ga kralj razveseljuje, da ga počasti.«',
        12: 'In Mordohaj je ponovno prišel h kraljevim velikim vratom. Hamán pa je žalujoč hitel k svoji hiši in svojo glavo je imel zakrito.',
        13: 'Hamán je povedal svoji ženi Zêreši in vsem svojim prijateljem, vsako stvar, ki ga je doletela. Potem so mu njegovi modri možje in njegova žena Zêreša rekli: »Če je Mordohaj iz rodu Judov, pred katerim si začel padati, ne boš prevladal zoper njega, temveč boš zagotovo padel pred njim.«',
        14: 'Medtem ko so še govorili z njim, so prišli kraljevi glavni dvorni upravitelji in hiteli, da Hamána privedejo na gostijo, ki jo je pripravila Estera.',
    },
    7: {
        1: 'Tako sta kralj in Hamán prišla na gostijo s kraljico Estero.',
        2: 'Kralj je drugi dan na vinski gostiji Esteri ponovno rekel: »Kaj je tvoja prošnja, kraljica Estera? Ta ti bo zagotovljena. Kaj je tvoja zahteva? Ta bo izpolnjena, celó do polovice kraljestva.«',
        3: 'Takrat je kraljica Estera odgovorila in rekla: »Če sem našla naklonjenost v tvojem pogledu, oh kralj in če to ugaja kralju, naj mi bo na mojo prošnjo dano moje življenje in moje ljudstvo na mojo zahtevo.',
        4: 'Kajti prodani smo, jaz in moje ljudstvo, da bi bili uničeni, da bi bili umorjeni in da umremo. Če pa bi bili prodani za sužnje in sužnjice, bi zadržala svoj jezik, čeprav sovražnik ne bi mogel izravnati kraljeve škode.«',
        5: 'Potem je Kralj Ahasvér odgovoril in kraljici Esteri rekel: »Kdo je tisti in kje je, da si v svojem srcu drzne dovoliti, da tako stori?«',
        6: 'Estera pa je rekla: »Nasprotnik in sovražnik je ta zlobni Hamán.« Potem je bil Hamán prestrašen pred kraljem in kraljico.',
        7: 'Kralj je vstal od vinske gostije in v svojem besu odšel v vrt palače. Hamán pa je vstal, da bi pri kraljici Esteri zaprosil za svoje življenje, kajti videl je, da je bilo pri kralju zoper njega določeno zlo.',
        8: 'Potem se je kralj z vrta palače vrnil v prostor vinske gostije, Hamán pa je bil zrušen na postelji, na kateri je bila Estera. Potem je kralj rekel: »Ali bo tudi v hiši, pred menoj, posilil kraljico?« Brž ko je beseda odšla iz kraljevih ust, so pokrili Hamánov obraz.',
        9: 'Harbonáj, eden izmed glavnih dvornih upraviteljev je pred kraljem rekel: »Glej, tudi vislice, petdeset komolcev visoke, ki jih je Hamán pripravil za Mordohaja, ki je dobro govoril za kralja, stojijo v Hamánovi hiši.« Potem je kralj rekel: »Obesite ga nanje.«',
        10: 'Tako so Hamána obesili na vislice, ki jih je pripravil za Mordohaja. Potem je bil kraljev bes pomirjen.',
    },
    8: {
        1: 'Na ta dan je dal Kralj Ahasvér hišo Hamána, sovražnika Judov, kraljici Esteri. Mordohaj pa je prišel pred kralja, kajti Estera je povedala, kaj ji je bil.',
        2: 'Kralj je snel svoj prstan, ki ga je vzel od Hamána in ga dal Mordohaju. Estera pa je Mordohaja postavila nad Hamánovo hišo.',
        3: 'Estera je ponovno spregovorila pred kraljem in padla dol pri njegovih stopalih in ga s solzami rotila, da odstrani vragolijo Hamána, Agágovca in njegov naklep, ki ga je zasnoval zoper Jude.',
        4: 'Potem je kralj proti Esteri iztegnil zlato žezlo. Tako je Estera vstala in stala pred kraljem',
        5: 'in rekla: »Če kralju ugaja in če sem našla naklonjenost v njegovem pogledu in se zdi stvar pravilna pred kraljem in sem prijetna v njegovih očeh, naj bo zapisano, da se razveljavijo pisma, ki jih je zasnoval Hamán, Hamedátov sin, Agágovec, katera je napisal, da uničijo Jude, ki so po vseh kraljevih provincah.',
        6: 'Kajti kako lahko prenašam gledanje zla, ki bo prišlo k mojemu ljudstvu? Ali kako lahko prenašam gledanje uničenja mojega sorodstva?«',
        7: 'Tedaj je kralj Ahasvér rekel kraljici Esteri in Judu Mordohaju: »Glejta, Esteri sem dal hišo Hamána, njega pa so obesili na vislice, ker je svojo roko položil na Jude.',
        8: 'Tudi za Jude napišita, kakor vama to ugaja, v kraljevem imenu in to zapečatita s kraljevim prstanom, kajti pisanja, ki je napisano v kraljevem imenu in zapečateno s kraljevim pečatom, noben človek ne more razveljaviti.«',
        9: 'Potem so bili poklicani kraljevi pisarji, ob tistem času, v tretjem mesecu, ki je mesec siván, na njegov triindvajseti dan in to je bilo napisano glede na vse, kar je Mordohaj zapovedal Judom, poročnikom, namestnikom in vladarjem provinc, ki so od Indije do Etiopije, sto sedemindvajsetim provincam, vsaki provinci glede na njihovo pisanje in vsakemu ljudstvu glede na njihov jezik in Judom glede na njihovo pisanje in glede na njihov jezik.',
        10: 'Napisal je v imenu Kralja Ahasvérja in to zapečatil s kraljevim prstanom in pisma poslal po slih na konjskem hrbtu in jahačih na mulah, kamelah in mladih [enogrbih] velblodih.',
        11: 'V teh je kralj zagotovil Judom, ki so bili v vsakem mestu, da se zberejo skupaj in da stojijo za svoje življenje, da uničijo, da ubijejo in da povzročijo, da umre vsa moč ljudstva in province, ki bi jih hotela napasti, tako malčke kakor ženske in da njihov dobiček vzamejo za plen,',
        12: 'na en dan po vseh provincah Kralja Ahasvérja, namreč na trinajsti dan dvanajstega meseca, ki je mesec adár.',
        13: 'Kopija pisanja za zapoved, ki naj bi bila dana v vsako provinco, je bila razglašena vsemu ljudstvu in da naj bodo Judje pripravljeni za ta dan, da se maščujejo na svojih sovražnikih.',
        14: 'Tako so sli, ki so jahali na mulah in kamelah, odšli ven, podvizani in pritisnjeni s kraljevo zapovedjo. In odlok je bil izdan pri palači Suze.',
        15: 'Mordohaj je odšel izpred prisotnosti kralja v kraljevski obleki iz modre in bele in z veliko krono iz zlata in z obleko iz tankega lanenega platna in vijolične, mesto Suze pa se je veselilo in bilo veselo.',
        16: 'Judje so imeli svetlobo, veselje, radost in čast.',
        17: 'V vsaki provinci in v vsakem mestu, kamor sta prišla kraljeva zapoved in njegov odlok, so imeli Judje radost in veselje, praznovanje in dober dan. In mnogi izmed ljudstva dežele so postali Judje, kajti strah pred Judi je padel nanje.',
    },
    9: {
        1: 'Torej v dvanajstem mesecu, ki je mesec adár, na trinajsti dan istega, ko sta se kraljeva zapoved in njegov odlok približala izvršitvi, na dan, ko so sovražniki Judov upali, da bodo imeli oblast nad njimi (čeprav je bilo to obrnjeno ravno nasprotno, da so Judje vladali nad tistimi, ki so jih sovražili),',
        2: 'so se Judje zbrali skupaj v svojih mestih, po vseh provincah kralja Ahasvérja, da položijo roko na tiste, ki so iskali njihovo bolečino in noben človek se jim ni mogel zoperstaviti, kajti strah pred njimi je padel na vse ljudstvo.',
        3: 'Vsi vladarji provinc, poročniki, namestniki in kraljevi častniki, so pomagali Judom, ker je nanje padel strah pred Mordohajem.',
        4: 'Kajti Mordohaj je bil velik v kraljevi hiši in njegova slava je šla po vseh provincah, kajti ta mož Mordohaj je postajal večji in večji.',
        5: 'Tako so Judje vse svoje sovražnike udarili z udarcem meča, pokolom in uničenjem. Tistim pa, ki so jih sovražili, so storili, kar so hoteli.',
        6: 'V palači Suze so Judje usmrtili in uničili petsto mož.',
        7: 'Paršandáta, Dalfóna, Aspáta,',
        8: 'Poráta, Adaljája, Aridáta,',
        9: 'Parmášta, Arisája, Aridája, Jezáta,',
        10: 'deset sinov Hamedátovega sina Hamána, sovražnika Judov, so usmrtili, toda na plen niso položili svojih rok.',
        11: 'Na ta dan je bilo število tistih, ki so bili umorjeni v palači Suze, privedeno pred kralja.',
        12: 'Kralj je kraljici Esteri rekel: »Judje so umorili in uničili petsto mož v palači Suze in deset Hamánovih sinov. Kaj so storili v preostalih kraljevih provincah? Torej kaj je tvoja prošnja? In ta ti bo zagotovljena. Ali kaj je tvoja nadaljnja zahteva? In ta bo storjena.«',
        13: 'Potem je Estera rekla: »Če to ugaja kralju, naj bo to zagotovljeno Judom, ki so v [mestu] Suze, da prav tako storijo jutri, glede na odlok današnjega dne in naj bo Hamánovih deset sinov obešenih na vislice.«',
        14: 'Kralj je zapovedal, da naj bo tako storjeno. Odlok je bil izdan v [mestu] Suze in obesili so Hamánovih deset sinov.',
        15: 'Kajti Judje, ki so bili v [mestu] Suze, so se zbrali skupaj tudi na štirinajsti dan meseca adárja in v [mestu] Suze usmrtili tristo mož. Toda na plen niso položili svojih rok.',
        16: 'Tudi drugi Judje, ki so bili v kraljevih provincah, so se zbrali skupaj in stali za svoja življenja in imeli počitek pred svojimi nasprotniki in jih izmed svojih sovražnikov usmrtili petinsedemdeset tisoč, toda svojih rok niso položili na plen.',
        17: 'Na trinajsti dan meseca adárja in na štirinajsti dan istega so počivali in to naredili za dan praznovanja in veselja.',
        18: 'Toda Judje, ki so bili v [mestu] Suze zbrani skupaj na njegov trinajsti dan in na njegov štirinajsti in na petnajsti dan istega, so počivali in to naredili za dan praznovanja in veselja.',
        19: 'Zato so Judje po vaseh, ki prebivajo v mestih brez obzidja, naredili štirinajsti dan meseca adárja za dan veselja in praznovanja in dober dan in pošiljanja deležev drug drugemu.',
        20: 'Mordohaj je napisal te stvari in poslal pisma vsem Judom, ki so bili po vseh provincah Kralja Ahasvérja, tako bližnjim kakor daljnim,',
        21: 'da to utrdi med njimi, da naj letno ohranjajo štirinajsti dan meseca adárja in petnajsti dan istega,',
        22: 'kakor dneva, na katera so Judje počivali pred svojimi sovražniki in mesec, ki je bil obrnjen k njim, od bridkosti v radost in od žalovanja v dober dan, da si bodo lahko pripravili dneve praznovanja in radosti in pošiljanja deležev drug drugemu in daril ubogim.',
        23: 'Judje so se lotili, da storijo, kakor so začeli in kakor jim je Mordohaj zapisal,',
        24: 'ker je Hamán, Hamedátov sin, Agágovec, sovražnik vseh Judov, zoper Jude zasnoval, da jih uniči in vrgel pur, to je žreb, da jih ugonobi in da jih uniči,',
        25: 'toda ko je Estera prišla pred kralja, je ta s pismi zapovedal, da naj se njegov zlobni naklep, ki ga je zasnoval zoper Jude, vrne na njegovo lastno glavo in da naj bodo on in njegovi sinovi obešeni na vislice.',
        26: 'Zato so ta dneva imenovali purim, po imenu pur. Zato so – po vseh besedah tega pisma in od tega, kar so videli glede te zadeve in kar je prišlo k njim –',
        27: 'Judje odredili in vzeli nase in na svoje potomstvo in na vse tiste, ki so se jim pridružili, tako da to ne bi prešlo, da bodo vsako leto ta dva dneva ohranjali glede na njihovo pisanje in glede na njihov določeni čas.',
        28: 'In da se bodo teh [dveh] dni spominjali in držali skozi vse rodove, vsaka družina, vsaka provinca in vsako mesto in da ta dneva purima med Judi ne bi prešla niti spomin nanju ne izgine od njihovega potomstva.',
        29: 'Potem je kraljica Estera, hči Abihájila in Juda Mordohaja, z vso oblastjo napisala, da potrjuje to drugo pismo o purimu.',
        30: 'In poslal je pisma vsem Judom, v sto sedemindvajset provinc Ahasvérjevega kraljestva, z besedami miru in resnice,',
        31: 'da potrdi ta [dva] dneva purima, na njun določeni čas, glede na to, kakor sta jima Jud Mordohaj in kraljica Estera predpisala in kakor so odredili zase in za svoje potomstvo zadeve posta in njihovega joka.',
        32: 'Esterin odlok je potrdil te stvari o purimu in to je bilo zapisano v knjigo.',
    },
    10: {
        1: 'Kralj Ahasvér je naložil davek deželi in morskim otokom.',
        2: 'Vsa dejanja njegove oblasti, njegove moči in razglas Mordohajeve veličine, kamor ga je kralj napredoval, mar niso zapisana v kroniški knjigi kraljev Medije in Perzije?',
        3: 'Kajti Jud Mordohaj je bil drugi za kraljem Ahasvérjem in velik med Judi in sprejet od množice svojih bratov, prizadevajoč si za blagostanje svojega ljudstva in govoril je mir vsemu svojemu semenu.',
    },
}
