NAME = 'GerAlbrecht: German Albrecht Neues Testament und Psalmen'
BOOK = 'II Corinthians'

CHAPTERS = {
    1: {
        1: 'Paulus, durch Gottes Willen ein Apostel Christi Jesu, und der Bruder Timotheus entbieten ihren Gruß der Gemeinde Gottes in Korinth samt allen Heiligen in ganz Achaja.',
        2: 'Gnade sei mit euch und Friede von Gott, unserem Vater, und dem Herrn Jesus Christus!',
        3: 'Gepriesen sein der Gott und Vater unseres Herrn Jesus Christus — der Vater voll Barmherzigkeit und der Gott, der in jeder Weise tröstet!',
        4: 'Er tröstet uns in all unserer Trübsal, damit wir dann auch andere in ihren Trübsalen trösten können mit dem Trost, der uns von Gott zuteil wird.',
        5: 'Denn wie Christi Leiden reichlich über uns kommen, so wird uns auch durch Christus reichlich Trost geschenkt.',
        6: 'Und beides dient zu euerm Besten. Denn leiden wir Trübsal, so können wir euch auch (in eurer Trübsal) trösten und dadurch euerm Heil dienen. Und werden wir (von Gott) getröstet, so können wir euch auch Trost spenden, und der zeigt seine Kraft darin, daß ihr dieselben Leiden, die auch uns treffen, mit Standhaftigkeit ertragt.',
        7: 'Daß ihr solchen Trost erfahrt, ist unsere feste Hoffnung. Denn wir wissen, daß ihr nicht nur an unseren Leiden, sondern auch an unserem Trost Anteil habt.',
        8: 'Wir wollen euch, liebe Brüder, nicht in Unkenntnis lassen über die Trübsal, die uns in Asien widerfahren ist: sie hat uns so gewaltig und unerträglich gedrückt, daß wir sogar am Leben verzweifelten.',
        9: 'Ja wir glaubten eine sichere Beute des Todes zu sein. Denn wir sollten lernen, unser Vertrauen nicht auf uns selbst zu setzen, sondern auf Gott, der die Toten auferweckt.',
        10: 'Der hat uns denn auch aus des Todes Rachen errettet und rettet uns noch fort und fort. Ja, zu ihm steht unsere Hoffnung, daß er uns auch ferner retten wird.',
        11: 'In dieser Hoffnung stärkt uns die Gewißheit, daß auch ihr fürbittend für uns einsteht. So soll nun auch aus vielen Herzen ein Dankgebet aufsteigen für die gnädige Errettung, die so viele für uns (von Gott) erfleht haben.',
        12: 'Und dürfen wir uns nicht rühmen (eurer Teilname wert zu sein)? Unser Gewissen gibt uns ja das gute Zeugnis, daß wir in Heiligkeit und Lauterkeit, wie Gott sie wirkt, nicht in fleischlicher Weisheit, sondern von Gottes Gnade geleitet, unseren Wandel in der Welt und ganz besonders im Verkehr mit euch geführt haben.',
        13: "Denn unsere Briefe an euch sind frei von allen Hintergedanken: sie sagen nichts anderes, als was ihr darin lest und wahrnehmt. Ich hoffe auch, ihr werdet es schließlich verstehen — wie ihr's zum Teil bereits verstanden habt —,",
        14: 'daß, ebenso wie wir uns euer rühmen dürfen, ihr euch auch unser an dem Tag unseres Herrn Jesus rühmen könnt.',
        15: 'In dieser Zuversicht war ich willens, euch zuerst zu besuchen, um euch eine doppelte Freude zu machen:',
        16: 'ich wollte über Korinth nach Mazedonien reisen und dann wieder von Mazedonien zu euch zurückkehren, um mir von euch das Geleit nach Judäa geben zu lassen.',
        17: 'Habe ich nun etwa leichtsinnig gehandelt, als ich diesen Plan faßte? Oder lasse ich mich bei meinen Entschlüssen von menschlichen Launen leiten, so daß ich heute ja und morgen nein sage?',
        18: 'Bei der Wahrhaftigkeit Gottes erkläre ich: unser Wort an euch ist nicht heute Ja und morgen Nein.',
        19: 'Denn der Sohn Gottes, Jesus Christus, den wir — ich, Silvanus und Timotheus — unter euch verkündigt haben, der ist auch nicht Ja und Nein zugleich gewesen, sondern ihm ist nur Ja.',
        20: 'Alle Verheißungen Gottes finden in ihm ihr Ja. Darum sprechen wir auch durch ihn zur Ehre Gottes das Amen aus.',
        21: "Gott ist's, der uns und euch in Christi Gemeinschaft befestigt und uns gesalbt hat:",
        22: 'er hat uns auch sein Siegel aufgedrückt und seinen Geist als Angeld in unser Herz gegeben.',
        23: 'Ich rufe Gott zum Zeugen an für meine Seele: ich bin deshalb noch nicht wieder nach Korinth gekommen, weil ich zunehmend gegen euch verfahren wollte.',
        24: 'Damit will ich aber sagen, daß wir Herren sind über euern Glauben; nein, wir wollen nur eure Freude mehren. Denn im Glauben steht ihr fest.',
    },
    2: {
        1: 'Ich habe mir vorgenommen, euch bei einem neuen Besuch nicht wieder Betrübnis zu bereiten.',
        2: 'Denn wenn ich euch betrübe, wer soll mich dann erfreuen? Das könnte doch nur der, der von mir Betrübnis erfährt.',
        3: 'Deshalb habe ich mich auch brieflich an euch gewandt, um nicht bei meinem Besuch von denen, die mir Freude machen sollten, Betrübnis zu erfahren. Ich darf doch wohl zu euch allen das Vertrauen haben, daß meine Freude euer aller Freude ist.',
        4: 'Denn aus großer innerer Not und Herzensangst und unter vielen Tränen habe ich euch geschrieben, nicht um euch Betrübnis zu bereiten, sondern um euch die Liebe sehen zu lassen, die ich ganz besonders zu euch habe.',
        5: 'Hat jemand Kränkungen verursacht, der hat nicht mich gekränkt, sondern mehr oder weniger — um nicht zuviel zu sagen — euch alle.',
        6: 'Für diesen Mann genügt die Rüge, die ihm die Mehrzahl von euch erteilt habt.',
        7: 'Darum solltet ihr ihm jetzt verzeihen und Trost zusprechen, damit der Ärmste nicht etwa von den Fluten der Traurigkeit verschlungen wird.',
        8: 'So fordere ich euch denn auf: laßt Liebe gegen ihn walten!',
        9: 'Der Zweck meines letzten Briefes ist ja erreicht: ich wollte sehen, ob sich euer Gehorsam wirklich in allen Stücken bewährt.',
        10: 'Wenn ihr ihm nun verzeiht, so verzeihe ich ihm auch. Ja vor dem Angesicht Christi habe ich ihm um euretwillen bereits verziehen, wenn überhaupt noch etwas zu verzeihen war.',
        11: 'Denn der Satan soll keinen Vorteil über uns gewinnen. Solche Schliche kennen wir nur zu gut.',
        12: 'Ich kam nach Troas, um die Frohe Botschaft Christi zu verkündigen. Dort fand ich einen großen Wirkungskreis im Dienst des Herrn.',
        13: 'Trotzdem hatte ich keine Ruhe in meinem Geist, weil ich meinen Bruder Titus nicht antraf. Darum nahm ich Abschied von ihnen und zog nach Mazedonien.',
        14: 'Gott sei Dank, der uns im Dienst Christi fortwährend Siege feiern läßt und den Duft seiner Erkenntnis überall durch uns verbreitet!',
        15: 'Denn wir sind ein Gott angenehmer Wohlgeruch, den Christus wirkt — bei denen, die gerettet werden, und bei denen, die verlorengehen.',
        16: 'Für diese sind wir ein Geruch, der aus dem Tod kommt und zum Tod führt, für jene aber ein Geruch, der aus dem Leben kommt und zum Leben führt. Und wer ist zu solchem Dienst tüchtig?',
        17: 'Wir: denn wir treiben nicht wie so viele mit dem Wort Gottes Schacher; sondern wie Männer, die das Tageslicht nicht scheuen, ja, wie Männer, die von Gott gesandt sind und, eins mit Christus, vor Gottes Antlitz stehen, — so und nicht anders reden wir.',
    },
    3: {
        1: 'Fangen wir schon wieder an, uns selbst zu "empfehlen"? Oder bedürfen wir gar wie gewisse Leute Empfehlungsbriefe an euch oder von euch?',
        2: 'Unser Empfehlungsbrief seid ihr. Der ist in unser Herz geschrieben, der wird von aller Welt erkannt und auch gelesen.',
        3: 'Es ist ja klar zu sehen, daß ihr ein Brief Christi seid, den wir als seine Diener ausgefertigt haben: ein Brief, nicht mit Tinte geschrieben, sondern mit dem Geist des lebendigen Gottes; ein Brief, der nicht auf steinernen Tafeln steht, sondern auf fleischernen Herzenstafeln.',
        4: 'Diese Zuversicht können wir nur durch Christus vor Gott zum Ausdruck bringen.',
        5: 'Nicht durch eigene Kraft können wir aus uns selbst Gedanken schöpfen; nein, unsere Tüchtigkeit kommt von Gott.',
        6: 'Er hat uns tüchtig gemacht, Diener eines neuen Bundes zu sein: nicht Buchstabendiener, sondern Geistesdiener. Denn der Buchstabe (des Gesetzes) tötet, der Geist (des Herrn) macht lebendig.',
        7: 'Wenn aber schon der Dienst, der den Tod verkündigt — dessen Urkunde in Buchstaben auf Stein gegraben war — so herrlich gewesen ist, daß die Kinder Israel das Antlitz Moses wegen des Glanzes auf seinem Angesicht — der doch verschwand — nicht unverwandt ansehen konnten:',
        8: 'wie sollte da der Dienst, der den Geist mitteilt, nicht noch viel herrlicher sein?',
        9: 'Denn wenn der Dienst, der die Verurteilung ausspricht, herrlich gewesen ist: so ist der Dienst, der die Rechtfertigung schenkt, ganz unvergleichlich herrlicher.',
        10: 'Ja, man kann sagen: Jener Herrlichkeitsglanz (des ersten Dienstes) verblaßt hier völlig vor der überwältigenden Herrlichkeit (des anderen Dienstes).',
        11: 'Denn ist schon das Vergängliche herrlich, wieviel herrlicher ist da erst das Bleibende!',
        12: 'In dieser Hoffnung (auf die bleibende Herrlichkeit unseres Dienstes) reden wir nun frei und offen.',
        13: 'Wir machen es nicht wie Mose, der eine Decke auf sein Antlitz legte, weil die Kinder Israel nicht sehen sollten, daß der vergängliche Glanz ein Ende nahm.',
        14: 'Doch trotzdem ist ihr Sinn verstockt. Denn bis auf den heutigen Tag ist noch immer dieselbe Decke da, wenn ihnen die Schriften des Alten Bundes vorgelesen werden: es ist ihnen verborgen, daß der Alte Bund in Christus ein Ende hat.',
        15: 'Also bis heute liegt eine Decke auf ihrem Herzen, sooft Mose vorgelesen wird.',
        16: 'Wenn sich aber Israel dereinst zum Herrn bekehrt, dann soll diese Decke weggenommen werden.',
        17: 'Mit "dem Herrn" ist hier der Geist gemeint. Denn wo der Geist des Herrn ist, da ist Freiheit.',
        18: 'Und wir alle, die wir mit unverhülltem Angesicht die Herrlichkeit des Herrn wie in einem Spiegel schauen, wir werden in dasselbe Bild verwandelt, so daß seine Herrlichkeit die unsere wird. Das kann nicht anders sein, weil der Herr, das heißt der Geist, hier wirksam ist.',
    },
    4: {
        1: 'Weil wir nun diesen Dienst durch Gottes Erbarmen ausrichten dürfen, so sind wir nicht feige.',
        2: 'Nein, wir meiden alle "schändlichen Schleichwege"; wir gehen auch nicht mit "Arglist" um, noch "verfälschen" wir Gottes Wort; sondern wir machen offen die Wahrheit kund. So suchen wir uns vor Gottes Angesicht dem unbefangenen Bewußtsein aller Menschen zu empfehlen.',
        3: '"Liegt nun trotzdem über unserer Heilsbotschaft eine Decke", so ist das nur der Fall bei denen, die verloren gehen.',
        4: 'Ihnen hat der Gott dieser Weltzeit wegen ihres Unglaubens den Sinn verblendet, damit ihnen nicht leuchte der Glanz der Frohen Botschaft von der Herrlichkeit Christi, der da ist das Ebenbild Gottes.',
        5: 'Denn wir verkündigen nicht "uns selbst", sondern Christus Jesus: er ist der Herr, und wir sind um Jesu willen eure Knechte.',
        6: 'Denn Gott, der einst gesprochen hat: "Das Lichte leuchte aus der Finsternis", der hat auch in unseren Herzen das Licht aufgehen lassen, damit (durch uns auch anderen) leuchte jene Erkenntnis der Herrlichkeit Gottes, die da strahlt auf Christi Angesicht.',
        7: 'Diesen (köstlichen) Schatz tragen wir aber in (zerbrechlichen) Tongefäßen — denn es soll sich zeigen, daß die überschwengliche Fülle der Kraft (die in diesem Schatz liegt) von Gott stammt, nicht von uns —.',
        8: 'Wir werden von allen Seiten bedrängt, doch nicht erdrückt; wir zagen wohl, doch wir verzagen nicht.',
        9: 'Wir werden verfolgt, aber nicht (von Gott) verlassen; wir werden zu Boden geworfen, doch nicht getötet.',
        10: 'Auf Schritt und Tritt tragen wir das Sterben Jesu an unserem Leib umher, damit sich auch das Leben Jesu an unserem Leib offenbare.',
        11: 'Denn im Dienst Jesu geraten wir mitten im Leben beständig in des Todes Rachen, damit sich auch das Leben Jesu an unserem sterblichen Fleisch offenbare.',
        12: 'So wirkt in uns der Tod, in euch jedoch das Leben.',
        13: 'Trotzdem erfüllt uns derselbe Glaubensgeist, der in dem Schriftwort zum Ausdruck kommt: Ich glaube, darum rede ich. Wir glauben auch, und darum reden wir auch.',
        14: 'Denn wir haben die Gewißheit, daß er, der den Herrn Jesus auferweckt hat, auch uns, die wir mit Jesus eins sind, auferwecken und uns zugleich mit euch darstellen wird (vor seinem Angesicht).',
        15: 'Dies alles erfahren wir um euretwillen. Denn je reicher der Strom der Gnade fließt, desto mehr Herzen sollen auch zur Ehre Gottes überströmen von Dank.',
        16: 'Deshalb sind wir auch nicht feige. Mag unser äußerer Mensch auch aufgerieben werden, unser innerer Mensch gewinnt dafür von Tag zu Tag stets neue Kraft.',
        17: 'Denn ein kurzer Augenblick leichter Trübsal bringt uns in überschwenglich reichem Maß eine ewige Fülle der Herrlichkeit,',
        18: 'wenn wir nicht schauen auf das Sichtbare, sondern auf das Unsichtbare. Denn das Sichtbare ist vergänglich, das Unsichtbare ist ewig.',
    },
    5: {
        1: 'Wir wissen ja: Wenn unser Zelt — das Haus, worin wir hier auf Erden wohnen — (im Tode) abgebrochen wird, so haben wir einen Bau, von Gott bereitet, ein himmlisches Haus, das nicht mit Händen gemacht ist, sondern ewig bleiben soll.',
        2: 'Solange wir in diesem Zelt wohnen, haben wir zu seufzen, weil wir voll Sehnsucht darauf warten, mit unserer himmlischen Behausung überkleidet zu werden.',
        3: 'Denn haben wir diese angezogen, dann werden wir nicht unbekleidet dastehen.',
        4: 'Solange wir also noch in diesem Zelt wohnen, haben wir zu seufzen unter einem schweren Druck. Denn wir möchten nicht entkleidet, sondern überkleidet werden, damit das Sterbliche verschlungen werde von dem Leben.',
        5: "Gott ist's, der uns hierzu befähigt hat: er hat uns auch den Geist als Angeld darauf gegeben.",
        6: 'Darum sind wir allezeit getrost, obwohl wir wissen: Solange dieser Leib noch unsere Heimat ist, sind wir noch fern von der Heimat,',
        7: 'fern vom Herrn — denn unser Lebensweg führt uns hier durch Glauben, nicht durch Schauen —.',
        8: 'Trotzdem sind wir getrost und möchten sogar lieber diesen Leib verlassen und daheim sein bei dem Herrn.',
        9: 'Deshalb setzen wir auch alles daran, ihm (bei seinem Kommen) wohlgefällig zu sein — ganz einerlei, ob wir dann in diesem Leib wohnen oder ihn verlassen haben.',
        10: 'Denn wir alle müssen offenbar werden vor dem Richterstuhl Christi, damit ein jeder seinen Lohn empfange für sein Tun in diesem Leibesleben, es sei gut oder böse.',
        11: 'Weil wir nun wissen, wie sehr der Herr (als Richter) zu fürchten ist, könnten wir uns da bei den Menschen "einschmeicheln" wollen? Gott kennt uns genau. Ich hoffe, auch ihr seid innerlich von unserer Aufrichtigkeit überzeugt.',
        12: 'Damit wollen wir uns aber nicht wieder einmal bei euch "empfehlen". Nein, wir wollen euch nur Anlaß geben, eure gute Meinung von uns auch jenen Prahlern gegenüber zu vertreten, deren Herz ganz anders ist als ihr frommes Gesicht.',
        13: 'Sind wir nun wirklich "von Sinnen gekommen", so ist das im Dienst Gottes geschehen: sind wir aber bei gesundem Verstand, so ist das euch zum Segen.',
        14: 'Was uns ganz und gar gefangennimmt, das ist die Liebe, die Christus uns bewiesen hat. wir denken nämlich so: Einer ist für alle gestorben, folglich sind alle gestorben.',
        15: 'Und er ist darum für alle gestorben, damit die, die da leben, nicht mehr sich selbst leben, sondern dem, der zu ihrem Heil gestorben und auferstanden ist.',
        16: 'Darum beurteilen wir jetzt niemand mehr nach dem äußeren Augenschein. Und haben wir früher sogar Christus nur nach seiner äußeren Erscheinung im Fleisch beurteilt, so denken wir jetzt ganz anders von ihm.',
        17: 'Wer also mit Christus in Gemeinschaft steht, der ist ein neues Geschöpf. Das Alte ist (bei ihm) vergangen: ein Neues ist offenbar geworden.',
        18: 'Dies alles aber ist Gottes Werk: Er hat uns durch Christus mit sich versöhnt und uns den Dienst übertragen, die Versöhnung zu verkündigen.',
        19: 'Denn Gott war es, der in Christus die Welt mit sich versöhnte: er rechnet den Menschen ihre Übertretungen nicht zu, und er hat uns den Auftrag gegeben, die Versöhnung kundzumachen.',
        20: 'So treten wir in Christi Namen als Gesandte auf, ja, Gottes Stimme tönt durch unseren Mahnruf. Wir bitten in Christi Namen: "Laßt euch mit Gott versöhnen!"',
        21: 'Ihn, der die Sünde nicht gekannt, hat er für uns zur Sünde gemacht, damit wir in ihm Gottes Gerechtigkeit würden.',
    },
    6: {
        1: 'Als (Gottes) Mitarbeiter ermahnen wir euch auch: Laßt Gottes Gnade, die ihr empfangen habt, nicht ohne Wirkung bei euch bleiben!',
        2: 'Gott spricht ja: Zu willkommener Zeit habe ich dich erhört, am Tage des Heils habe ich dir geholfen. Jetzt ist die hochwillkommene Zeit, jetzt ist der Tag des Heils!',
        3: 'Wir geben euch in keiner Weise Anstoß, damit auf unseren Dienst kein Tadel falle.',
        4: "Sondern in jeder Hinsicht beweisen wir uns, wie sich's für Gottes Diener ziemt: Voll Ausdauer sind wir in Trübsal, Nöten und Ängsten,",
        5: 'bei Schlägen und in Gefängnissen, bei Aufruhr und Mühsal, in Nachtwachen und Fasten.',
        6: 'Wir bewähren uns durch Reinheit des Lebens, durch Erkenntnis, Langmut und freundliches Wesen, durch Wirken im Heiligen Geist und ungeheuchelte Liebe,',
        7: 'durch Verkündigen der Wahrheit und Erweisung der Gotteskraft, indem wir die Waffen führe, die die Gerechtigkeit verleiht, zu Trutz und Schutz.',
        8: 'Wir bleiben fest, mag unser Weg durch Ehre oder Schande führen, mag man uns schmähen oder rühmen: Man schilt uns als Betrüger, und doch sind wir wahrhaftig.',
        9: 'Man hält uns für unbekannt, aber wir sind wohlbekannt. Man sagt, wir lägen im Sterben, und siehe da: wir leben! Man meint, Gott züchtige uns, und trotzdem werden wir nicht getötet.',
        10: 'Man denkt, wir müßten traurig sein, und wir sind immer fröhlich. Man hält uns für Bettler, aber wir machen viele reich. Es scheint, wir hätten nichts, und wir besitzen alles!',
        11: 'Wir haben offen zu euch geredet, o Korinther; unser Herz hat sich (in Liebe zu euch) weit aufgetan.',
        12: 'Es ist viel Raum für euch in unserem Herzen; doch in euern Herzen ist nur wenig Raum für uns.',
        13: 'Habt uns doch auch lieb — ich rede zu euch als zu meinen Kindern —: macht auch eure Herzen weit für uns!',
        14: '- Habt nicht vertrauten Umgang mit den Heiden! Denn was hat die Gerechtigkeit zu schaffen mit der Gesetzlosigkeit? Oder welche Gemeinschaft haben Licht und Finsternis?',
        15: 'Wie stimmt Christus mit Beliar? Oder was hat der Gläubige zu tun mit dem Ungläubigen?',
        16: 'Wie verträgt sich der Tempel Gottes mit den Götzen? Und wir sind der Tempel des lebendigen Gottes. Denn Gott hat gesagt: Ich will unter ihnen wohnen und wandeln, ich will ihr Gott sein, und sie sollen mein Volk sein.',
        17: 'Darum: Geht aus von ihnen und sondert euch ab, spricht der Herr, und rührt nichts Unreines an! Denn ich will euch annehmen',
        18: 'und euer Vater sein, und ihr sollt meine Söhne und Töchter sein, spricht der allmächtige Herr.',
    },
    7: {
        1: 'Weil wir so köstliche Verheißungen haben, Geliebte, wollen wir uns reinigen von allem, was Fleisch und Geist befleckt, und ein heiliges Leben führen in Gottesfurcht! —',
        2: 'Gebt uns Raum (in euern Herzen)! Wir haben doch keinem von euch Unrecht getan, wir haben niemand betrogen.',
        3: 'Diese Worte sollen kein Vorwurf für euch sein: Wir wollen euch ja, wie ich eben erst gesagt, in Tod und Leben nicht aus unserem Herzen lassen.',
        4: 'Ich habe großes Vertrauen zu euch, ich habe viel an euch zu rühmen; ich habe Trost in Fülle und bin bei all unserer Trübsal überreich an Freude.',
        5: 'Auch nach unserer Ankunft in Mazedonien haben wir keinen ruhigen Augenblick gehabt, sondern überall gab es Widerwärtigkeit: von außen Kämpfe, im Herzen Angst.',
        6: 'Gott, der Tröster der Betrübten, hat uns aber durch die Ankunft des Titus Trost geschenkt,',
        7: 'das heißt nicht nur durch seine Ankunft, sondern vor allem durch die Erquickung, die er bei euch gefunden hat. Er hat uns erzählt, wie ihr euch sehnt (mich wiederzusehen), wie tief betrübt ihr seid, wie sehr ihr an mir hängt. Das alles hat meine Freude noch vermehrt.',
        8: 'Habe ich euch nun auch durch meinen Brief betrübt, so tut mir das jetzt nicht mehr leid. Früher hat es mir wohl leid getan — denn ich sehe, daß euch jener Brief, wenn auch nur vorübergehend, betrübt hat —.',
        9: 'Jetzt aber freue ich mich, freilich nicht darüber, daß ihr in Traurigkeit gekommen seid, aber daß euch diese Traurigkeit zur Sinnesänderung geführt hat. Eure Traurigkeit ist Gott wohlgefällig gewesen, und darum haben wir euch in keiner Weise Schaden zugefügt.',
        10: 'Denn die Traurigkeit, die Gott gefällt, wirkt eine Reue, die zum Heil führt, und solche Reue bereut man nie. Die Traurigkeit dagegen, die die Welt empfindet, wirkt den Tod.',
        11: 'Seht doch, welche Wandlung gerade diese gottgefällige Traurigkeit bei euch hervorgebracht hat! Ihr seid ernst geworden, ja noch mehr: ihr habt euch entschuldigt, ihr habt euerm Unwillen Ausdruck gegeben, ihr habt Furcht, ihr sehnt euch nach mir, ihr wollt streng vorgehen, ihr wollt strafen. So habt ihr deutlich bewiesen, daß ihr selbst in dieser Sache ohne jede Schuld seid.',
        12: 'Meinen Brief habe ich euch nicht deshalb geschrieben, um den Beleidiger zu strafen oder dem Beleidigten Genugtuung zu verschaffen, sondern vor Gottes Angesicht sollte es offenbar werden, wie sehr ihr uns gewogen seid.',
        13: 'Und da dies erreicht ist, so sind wir auch getröstet. Außer diesem Trost haben wir aber noch eine besondere Freude erlebt, als wir sahen, wie sehr sich Titus darüber freute, daß ihr alle seinen Geist so reich erquickt habt.',
        14: 'Denn wenn ich euch ihm gegenüber früher manchmal gerühmt habe, so bin ich nun nicht damit zuschanden geworden. Sondern wie alles, was wir zu euch geredet haben, die lautere Wahrheit ist, so hat sich auch unser Rühmen dem Titus gegenüber als Wahrheit erwiesen.',
        15: 'Und sein Herz schlägt jetzt noch mehr für euch als früher, wenn er daran denkt, wie gehorsam ihr alle gewesen seid, und mit welcher Scheu und Ehrfurcht ihr ihn aufgenommen habt.',
        16: 'Wie freue ich mich, daß ich nun in jeder Hinsicht Vertrauen zu euch haben kann!',
    },
    8: {
        1: 'Wir wollen euch nun auch mitteilen, liebe Brüder, wie reich sich die Gnade Gottes in den Gemeinden Mazedoniens erwiesen hat.',
        2: 'Trotz ihrer bedrängten Lage haben sie große Freudigkeit gezeigt, und trotz ihrer tiefen Armut haben sie eine überreiche Freigebigkeit an den Tag gelegt.',
        3: 'Denn nach Kräften — das muß ich ihnen bezeugen —, ja über ihre Kräfte haben sie freiwillig beigesteuert.',
        4: 'Sie haben uns dringend angefleht um die Gunst, an dem Liebeswerk für die Heiligen (in Jerusalem) teilnehmen zu dürfen.',
        5: 'Auch ist ihre Gabe viel reicher gewesen, als wir erwarten konnten: im Gehorsam gegen Gottes Willen haben sie sich selbst (und ihre Gaben) zunächst dem Herrn und dann auch uns zur Verfügung gestellt.',
        6: 'Dieser Erfolg hat uns nun ermutigt, dem Titus zuzureden, auch bei euch die schon früher begonnene Sammlung zu vollenden.',
        7: 'Wie ihr euch sonst überall hervortut: durch Glauben, Einsicht und Erkenntnis, durch regen Eifer und zumal durch innige Liebe zu mir, so tut euch auch bei diesem Liebeswerk hervor!',
        8: 'Ich will euch hier nichts befehlen, ich halte euch nur den Eifer anderer vor, um zu prüfen, ob auch eure Liebe echt ist.',
        9: '- Ihr kennt ja die Gnade unseres Herrn Jesus Christus: er war reich, und trotzdem ist er arm geworden um euretwillen, um euch durch seine Armut reich zu machen —.',
        10: 'Ich gebe euch hier nur einen Rat. Den der kann euch nur nützlich sein. Im vorigen Jahr habt ihr schon mit der Sammlung begonnen: ihr habt sie also nicht nur zuerst ins Werk gesetzt, ihr habt sie auch zuerst beschlossen.',
        11: 'Führt nun das angefangene Werk jetzt auch zu Ende, damit dem freudigen Entschluß auch die Tat entspreche, soweit euch eure Mittel das erlauben!',
        12: 'Denn wer mit freudigem Herzen nach seinem Vermögen gibt, der ist Gott angenehm. Gott verlangt nicht, was man selbst nicht hat.',
        13: 'Ihr sollt also andere nicht so unterstützen, daß ihre Not gelindert wird, während ihr selbst in Not geratet. Nein, es handelt sich hier nur um einen Ausgleich:',
        14: 'Diesmal soll euer Überfluß ihrem Mangel abhelfen, damit ein andermal ihr Überfluß euerm Mangel zugute komme. Auf diese Weise soll ein Ausgleich stattfinden,',
        15: 'wie geschrieben steht: Wer viel (Manna) sammelte, der hatte keinen Überfluß; und wer nur wenig sammelte, der litt keinen Mangel.',
        16: 'Gott sei Dank, daß er Titus denselben Eifer um euch ins Herz gegeben hat (der uns erfüllt)!',
        17: 'Denn er ist unserer Aufforderung (euch zu besuchen) nachgekommen. Bei seinem Eifer hätte es aber gar keiner Aufforderung bedurft: er kommt ganz aus eigenem Antrieb zu euch.',
        18: 'Und mit ihm senden wir jenen Bruder, der als Diener der Heilsbotschaft in allen Gemeinden geschätzt wird,',
        19: 'und der außerdem auch zur Ehre des Herrn und auf unseren ausdrücklichen Wunsch von den Gemeinden (Mazedoniens) zu unserem Reisegefährten erwählt worden ist, um diese Liebesgabe, die wir jetzt einsammeln, mit uns (nach Jerusalem) zu bringen.',
        20: 'So vermeiden wir die Gefahr, daß man uns bei dieser reichen Gabe, die wir sammeln irgendeinen Vorwurf mache.',
        21: 'Den unsere Sorge ist, daß alles redlich zugehe nicht nur vor Gott, sondern auch vor Menschen.',
        22: 'Mit beiden senden wir noch einen dritten Bruder: sein Eifer, den wir schon bei vielen Gelegenheiten erprobt haben, ist gerade jetzt besonders groß, da er das vollste Vertrauen zu euch hat.',
        23: 'Für Titus rede ich, weil er mein Gehilfe und mein besonderer Mitarbeiter bei euch ist. Was die beiden anderen Brüder angeht, so sind sie Abgesandte der Gemeinden und Diener, die zur Ehre Christi wirken.',
        24: 'Wenn ihr nun diesen Männern Liebe beweist und das, was wir von euch gerühmt haben, durch euer Verhalten gegen sie rechtfertigt, so (steht ihr auch) vor den (anderen) Gemeinden (in gutem Licht da).',
    },
    9: {
        1: 'Über die Liebesgabe selbst, die für die Heiligen bestimmt ist, brauche ich euch nicht weiter zu schreiben.',
        2: 'Denn eure Opferwilligkeit ist mir wohlbekannt. Ich rühme sie auch den Mazedoniern gegenüber, indem ich ihnen vorhalte: "Achaja ist schon seit Jahresfrist bereit, die gesammelten Gelder abzuliefern." So hat euer Eifer die Mehrzahl (der Mazedonier) angespornt.',
        3: 'Trotzdem sende ich euch die erwähnten Brüder: das Lob, das wir euch in diesem Stück erteilt, soll nicht hinfällig werden, sondern ihr sollt wirklich, wie ich behauptet habe, mit der Sammlung fertig sein.',
        4: 'Denn was wäre die Folge, wenn mich Brüder aus Mazedonien zu euch begleiten und fänden, ihr wärt noch nicht fertig? Dann müßten wir — um nicht zu sagen ihr — in dieser Sache beschämt dastehen.',
        5: "Darum habe ich's für nötig erachtet, die Brüder aufzufordern, mir nach Korinth vorauszureisen und die von euch versprochene Liebesgabe ganz einzusammeln, damit sie bei meiner Ankunft bereitliege, und zwar als reiche Liebesgabe, nicht als karge.",
        6: 'Ich meine: Wer kärglich sät, der wird auch kärglich ernten; und wer reichlich sät, der wird auch reichlich ernten.',
        7: "Jeder gebe, wie er sich's in seinem Herzen vorgenommen hat, ohne Unlust, ohne Zwang. Denn einen fröhlichen Geber hat Gott lieb.",
        8: 'Gott aber ist mächtig genug, euch mit (irdischem) Segen so zu überschütten, daß ihr nicht nur stets völlig euer Auskommen findet, sondern auch noch reichlich Mittel habt zu allerlei Liebeswerken.',
        9: 'Steht doch geschrieben: Er hat ausgestreut, er hat den Armen gegeben, seine Gerechtigkeit bleibt ewig.',
        10: 'Der nun dem Sämann Samen gibt und ihm Brot zur Speise reicht, der wird auch euch (bei eurer Wohltätigkeit) reichlich Mittel schenken und die Früchte eurer Gerechtigkeit wachsen lassen.',
        11: 'Ja ihr sollt an irdischen Gütern solchen Überfluß haben, daß ihr nach Herzenswunsch beisteuern könnt zu unserer Liebesgabe, wofür die Empfänger Gott danken werden.',
        12: 'Denn diese gleichsam priesterliche Opfergabe, die durch unseren Dienst dargebracht wird, hilft nicht nur dem Mangel der Heiligen (in Jerusalem) ab. Sie wirkt noch mehr. Einmal wird sie viele dazu treiben, Gott (für seine Hilfe) zu danken',
        13: 'und im Blick auf die Bewährung (eures Glaubens), die sich durch diese Liebesgabe kundgibt, ihn dafür zu preisen, daß ihr dem Bekenntnis zu Christi Froher Botschaft so treu ergeben seid und die brüderliche Gemeinschaft mit ihnen und allen Gläubigen so aufrichtig festhaltet.',
        14: 'Dann aber werden sie auch für euch beten und sich in Liebe nach euch sehnen, weil sich Gottes Gnade so überschwenglich reich an euch beweist.',
        15: 'Ja, Gott sei Dank für seine unaussprechlich herrliche Gabe!',
    },
    10: {
        1: 'Nun habe ich, Paulus, — mit dem Hinweis auf Christi Freundlichkeit und Milde — noch ein besonderes Wort der Ermahnung an euch zu richten. Ich bin ja (nach den Worten meiner Gegner) feige, wenn ich euch Aug in Aug gegenüberstehe, doch mutig, wenn ich aus der Ferne zu euch rede.',
        2: 'Bitte, zwingt mich nicht, wenn ich bei euch bin, mutig aufzutreten mit jener zuversichtlichen Kühnheit, die ich gewissen Leuten gegenüber zeigen will, die da meinen, wir lassen uns von fleischlichen Rücksichten leiten.',
        3: 'Wohl leben wir noch im (sterblichen) Fleisch, doch kämpfen wir nicht fleischlich.',
        4: 'Denn die Waffen, womit wir kämpfen, sind nicht fleischlich. Gott macht sie stark, Bollwerke zu zerstören.',
        5: 'Wir vernichten damit (dem Glauben feindliche) Anschläge und jede stolze Festung, die sich gegen die Erkenntnis Gottes erhebt, und nehmen jeden Gedanken gefangen für den Gehorsam, wie ihn Christus bewiesen.',
        6: 'Jeden Ungehorsam aber sind wir entschlossen zu strafen, wenn ihr (als Gemeinde) unseren Weisungen erst völlig gehorsam geworden seid..',
        7: 'Seht auf das, was klar vor Augen liegt! Trotzt einer darauf, Christi Diener zu sein, der sage sich, daß wir ebenso gut Christus dienen wie er.',
        8: 'Und sollte ich mich der uns vom Herrn verliehenen Vollmacht — euch zu erbauen, nicht euch zu zerstören — auch noch viel lauter rühmen, so würde ich nicht damit zuschanden.',
        9: 'Ich will aber nicht den Schein erwecken, als suchte ich euch durch meine Briefe einzuschüchtern.',
        10: '"Seine Briefe" — so sagt man ja — "sind wuchtig und entschieden; seine äußere Erscheinung aber macht keinen Eindruck, und reden kann er gar nicht."',
        11: 'Wer so spricht, der lasse sich gesagt sein: Wie wir aus der Ferne in unseren Briefen reden, so werden wir auch nach unserer Ankunft handeln.',
        12: 'Allerdings haben wir nicht den "Mut", uns mit gewissen Leuten, die sich selbst empfehlen, auf eine Stufe zu stellen und uns mit ihnen zu vergleichen. Diese Leute messen sich in ihrem Unverstand an sich selbst und spiegeln sich in ihrem eigenen Bild.',
        13: 'Wir dagegen wollen uns nicht maßlos rühmen, sondern uns mit unserem Rühmen auf das Arbeitsfeld beschränken, das Gott uns abgemessen hat, und das auch euch umfaßt.',
        14: 'Wir dehnen unseren Wirkungskreis nicht eigenmächtig aus, sondern ihr gehört mit dazu. Denn wir sind ja mit Christi Froher Botschaft wirklich bis zu euch gekommen und haben sie euch zuerst verkündigt.',
        15: 'Wir schreiben uns also nicht in maßlosem Ruhmesdünkel die Früchte fremder Arbeit zu. Wohl aber hoffen wir: wenn euer Glaube wächst, so können wir später — doch stets innerhalb der Grenzen des uns angewiesenen Arbeitsfeldes — von euch aus einen größeren Wirkungskreis aufsuchen',
        16: 'und auch in jenen Gegenden, die über Korinth hinaus (weiter westwärts) liegen, die Heilsbotschaft verkündigen. Dabei wollen wir aber nie in ein fremdes Arbeitsfeld eindringen noch uns der durch andere errungenen Erfolge rühmen. Nein:',
        17: 'Wer sich rühmt, der rühme sich des Herrn!',
        18: 'Denn nicht der ist bewährt (als Gottes Diener), der sich selbst empfiehlt, sondern der, den der Herr empfiehlt.',
    },
    11: {
        1: 'Daß ihr euch doch ein klein wenig "Torheit" von mir gefallen ließet! Und nicht wahr, das tut ihr auch.',
        2: 'Denn ich liebe euch ja mit einer Eifersucht, wie sie Gott empfindet, und ich habe euch für einen Mann geworben, um euch als eine Jungfrau Christus zuzuführen.',
        3: 'Ich fürchte aber: wie Eva durch die List der Schlage verführt worden ist, so können vielleicht auch eure Gedanken betört und abgezogen werden von der Aufrichtigkeit und Lauterkeit, die ihr Christus schuldet.',
        4: 'Kommt nämlich einer zu euch und verkündigt euch einen anderen Jesus, den wir nicht verkündigt haben, oder empfangt ihr einen Geist verschieden von dem, den ihr (durch meinen Dienst) empfangen habt, oder hört ihr eine Heilsbotschaft, die der, die ihr vernommen, widerspricht, — so laßt ihr euch das gern gefallen.',
        5: 'Ich glaube doch in keinem Stück hinter den "unvergleichlich hohen Aposteln" zurückzustehen.',
        6: 'Denn bin ich auch ein Stümper in der Redekunst, so bin ich es doch nicht in der Erkenntnis, die haben wir stets in jeder Hinsicht in bezug auf euch bewiesen.',
        7: 'Oder ist es etwa eine Sünde, daß ich mich selbst erniedrigt habe, um euch zu erhöhen? Ich rede hier davon, daß ich euch Gottes Heilsbotschaft umsonst verkündigt habe.',
        8: 'Andere Gemeinden habe ich ausgeplündert und Bezahlung von ihnen genommen, um euch zu dienen.',
        9: 'Und als ich bei euch war und Mangel litt, bin ich doch keinem zur Last gefallen. Denn was ich nötig hatte, das haben mir die Brüder aus Mazedonien mitgebracht. Ich habe mich stets gehütet, euch zur Last zu fallen, und das will ich auch in Zukunft tun.',
        10: 'Bei Christi Wahrhaftigkeit, die in mir wohnt, versichere ich: daß ich mich so rühme, dem soll in dem Gebiet von Achaja kein Riegel vorgeschoben werden.',
        11: 'Warum? Etwa weil ich euch nicht liebhabe? Das weiß Gott!',
        12: 'Doch wie ich jetzt handle, so will ich auch in Zukunft handeln, um denen, die ihre Freude daran finden (mich zu schmähen), jeden Vorwand dafür abzuschneiden und sie zu zwingen, wenn sie sich rühmen wollen, sich ebenso zu zeigen wie wir. (Aber so zeigen sie sich nicht.)',
        13: 'Denn diese Leute sind falsche Apostel, Arbeiter, die mit Lug und Trug umgehen, die sich in Apostel Christi verkleiden.',
        14: 'Und das ist gar kein Wunder. Denn auch der Satan, ihr Meister, verkleidet sich in einen Engel des Lichts.',
        15: 'Da kann es nicht befremden, wenn auch seine Diener äußerlich als Diener der Gerechtigkeit auftreten. Sie werden aber ein Ende nehmen, wie ihre Werke verdienen.',
        16: 'Noch einmal sage ich: Niemand denke, ich sei ein "Tor". Haltet ihr mich aber doch dafür, nun, dann kann ich auch warten, daß ihr mich mit meiner Torheit anhört und auch mir erlaubt, einen kleinen Augenblick zu prahlen.',
        17: 'Was ich jetzt rede, das rede ich also nicht im Sinne des Herrn, das rede ich wie ein Tor; denn jetzt soll doch einmal geprahlt werden.',
        18: 'Weil so viele mit äußeren Vorzügen prahlen, darum will ich auch einmal so prahlen.',
        19: 'Ihr klugen Leute habt ja die Toren so gern.',
        20: 'Ja ihr habt es gern, wenn man euch mit List einfängt, wenn man hochfahrend auftritt, wenn man euch ins Antlitz schlägt.',
        21: 'Zu meiner Schande muß ich gestehen: das haben wir nicht fertiggebracht. Womit aber sonst gewisse Leute prahlen — ich rede töricht —, damit kann ich auch prahlen:',
        22: 'Sie sind Hebräer? Ich auch. Sie sind Israeliten? Ich auch. Sie sind Nachkommen Abrahams? Ich auch.',
        23: 'Sie sind Christi Diener? Das bin ich noch viel mehr — dies sage ich freilich im Wahnwitz —. Ich habe viel mehr Mühsal erduldet, bin häufiger im Gefängnis gewesen, bin übermäßig geschlagen worden, habe oft dem Tod ins Auge geschaut.',
        24: 'Von den Juden habe ich fünfmal vierzig Streiche weniger einen erhalten.',
        25: 'Dreimal bin ich mit Ruten gepeitscht und einmal gesteinigt worden. Dreimal habe ich Schiffbruch gelitten, vierundzwanzig Stunden bin ich ein Spielball der Meereswogen gewesen.',
        26: 'Dann die vielen Reisen und Gefahren aller Art: Gefahren auf Flüssen, Gefahren von den Heiden, Gefahren von meinem eigenen Volk, Gefahren in der Wüste, Gefahren auf der See, Gefahren unter falschen Brüdern.',
        27: 'Dazu: Mühe und Drangsal, viele schlaflose Nächte, Hunger und Durst, viel Fasten, Kälte und Blöße.',
        28: 'Endlich — von allem anderen hier zu schweigen — die tägliche Arbeit, die auf mir liegt: die Sorge für alle Gemeinden.',
        29: 'Ist einer schwach, bin ich dann nicht mit ihm schwach? Fällt einer in Sünde, bin ich da nicht (von Schmerz) entbrannt?',
        30: 'Bin ich gezwungen, mich zu rühmen, so will ich mich meiner Schwachheit rühmen.',
        31: 'Der Gott und Vater des Herrn Jesus — der gepriesen sei in Ewigkeit — der weiß, daß ich nicht lüge:',
        32: 'In Damaskus ließ der Statthalter des Königs Aretas die Stadt bewachen, um mich gefangenzunehmen.',
        33: 'Da wurde ich durch ein Fenster in einem Korb die Mauer hinabgelassen, und so entging ich seinen Händen.',
    },
    12: {
        1: 'Ich muß mich rühmen — es taugt zwar nicht —, und so will ich nun auf die Gesichte und Offenbarungen eingehen, die mir der Herr geschenkt hat.',
        2: 'Ich kenne einen Jünger Christi, der vor vierzehn Jahren — ob im Leib oder außerhalb des Leibes, das weiß ich nicht, Gott weiß es — bis in den dritten Himmel entrückt wurde.',
        3: 'Und von demselben Menschen ist mir bekannt, daß er — ob im Leib oder ohne seinen Leib, das weiß ich nicht, Gott weiß es —',
        4: 'bis in das Paradies entrückt worden ist und (dort) geheimnisvolle Dinge vernommen hat, von denen man nicht reden darf.',
        5: 'Wenn ich aber an mich selbst denke, so will ich mich nur meiner Schwachheit rühmen.',
        6: 'Wollte ich mich jedoch rühmen, so wäre ich deshalb kein "Tor": denn ich würde ja die Wahrheit sagen. Ich verzichte aber darauf (mich zu rühmen), damit mich niemand überschätze, sondern jeder mich nur nach dem beurteile, was er an mir sieht und hört.',
        7: 'Damit ich jedoch wegen der außerordentlichen Offenbarungen nicht hochmütig werde, ist mir ein Stachel ins Fleisch gegeben worden: ein Satansengel, der mich mit Fäusten schlagen muß, damit ich nicht hochmütig werde.',
        8: 'Dreimal habe ich den Herrn angefleht, daß dieser Satansengel von mir weiche.',
        9: 'Doch der Herr hat mir geantwortet: "Es genügt dir meine Gnade; denn die Kraft zeigt sich am herrlichsten in der Schwachheit." So will ich mich denn am liebsten gerade meiner Schwachheiten rühmen, damit Christi Kraft bei mir einkehre.',
        10: 'Darum habe ich meine Freude an den Schwachheiten, Schmähungen, Nöten, Verfolgungen und Drangsalen, die ich um Christi willen leide. Denn wenn ich schwach bin, dann bin ich stark.',
        11: 'Ich habe mich (mit meinem Rühmen) wirklich töricht gezeigt. Ihr habt mich aber dazu gezwungen. Denn ich hätte von euch empfohlen werden sollen (und nicht meine Gegner). Ich bin ja in keiner Weise hinter den "unvergleichlich hohen Aposteln" zurückgeblieben, wenn ich auch "nichts bin".',
        12: 'Fürwahr, die Beweise für mein Apostelamt habe ich durch Zeichen, Wunder und Taten übernatürlicher Kraft in unermüdlicher Ausdauer unter euch erbracht.',
        13: 'Denn worin steht ihr hinter den anderen Gemeinden zurück? Doch nur darin, daß ich euch nicht zur Last gefallen bin. Verzeiht mir dieses Unrecht!',
        14: 'Jetzt will ich euch zum drittenmal besuchen, und auch da will ich euch nicht zur Last fallen. Denn ich suche nicht euer Hab und Gut, sondern euch selbst. Es sollen ja auch nicht die Kinder den Eltern Schätze sammeln, sondern umgekehrt, die Eltern den Kindern.',
        15: 'Ich aber will nicht nur mein Hab und Gut, sondern sogar mein Leben mit Freuden für eure Seelen opfern. Soll ich denn, je mehr ich euch liebe, nur desto weniger Gegenliebe von euch erfahren?',
        16: 'Doch gut: Ich bin euch nicht zur Last gefallen. Aber "ich bin durchtrieben und habe euch mit Kost um das Eure gebracht".',
        17: 'Habe ich euch denn durch einen meiner Mitarbeiter ausbeuten lassen?',
        18: 'Ich habe Titus veranlaßt, euch zu besuchen, und habe mit ihm den bekannten Bruder gesandt. Hat euch etwa Titus ausgebeutet? Haben wir nicht beide in demselben Geist gehandelt? Sind wir nicht in denselben Fußstapfen gewandelt?',
        19: 'Schon längst denkt ihr wohl, wir wollten uns vor euch verteidigen. Nein, wir reden vor Gottes Angesicht als solche, die mit Christus in Gemeinschaft stehen. Alle unsere Worte, Geliebte, sollen nur zu eurer Förderung dienen.',
        20: 'Ich fürchte nämlich, daß ich euch bei meiner Ankunft nicht so finde, wie ich möchte, und daß auch ihr mich nicht nach euerm Wunsch findet. Ich fürchte, Zank und Neid, Leidenschaft und Selbstsucht, Verleumdung und Ohrenbläserei, Aufgeblasenheit und Unordnung bei euch anzutreffen.',
        21: 'Ja mir ist bange, daß mich mein Gott, wenn ich nun komme, aufs neue bei euch demütige und ich über viele trauern müsse, die noch in ihren alten Sünden stecken und sich nicht bekehrt haben von ihrer Unreinigkeit, Hurerei und Ausschweifung, in die sie gefallen sind.',
    },
    13: {
        1: 'Zum drittenmal will ich jetzt zu euch kommen. Durch die Aussage zweier oder dreier Zeugen soll jede Sache entschieden werden.',
        2: 'Was ich bei meiner zweiten Anwesenheit denen, die noch in ihren alten Sünden stecken, und allen anderen (Widerspenstigen) erklärt habe, das wiederhole ich jetzt in meiner Abwesenheit: Bei meiner Rückkehr will ich keine Schonung üben.',
        3: 'Ihr wünscht ja zu erfahren, daß Christus durch mich redet: er zeigt sich gegen euch nicht schwach; nein, er ist mächtig unter euch.',
        4: 'Denn ist er auch in (menschlicher) Schwachheit gekreuzigt worden, so lebt er nun durch Gottes Kraft. Wir sind auch schwach wie er; doch in seiner Gemeinschaft werden wir durch Gottes Kraft voll Leben sein, und das sollt ihr erfahren!',
        5: 'Seht zu, ob ihr im Glauben steht; prüft euch selbst! Oder merkt ihr nicht, daß Jesus Christus in euch wohnt? Ihr wärt sonst nicht echt (im Glauben).',
        6: 'Daß wir echt sind und die Probe bestehen, das sollt ihr hoffentlich erfahren.',
        7: 'Wir beten aber zu Gott, er möge euch vor allem Bösen bewahren. Uns liegt ja nicht daran, daß wir erprobt erscheinen, sondern daß ihr das Gute tut, — dann wollen wir gern als solche gelten, die die Probe nicht bestehen.',
        8: 'Denn wir vermögen nichts gegen die Wahrheit, wir wollen nur die Wahrheit fördern.',
        9: 'Ja wir freuen uns, wenn wir schwach sind und ihr stark seid. Und daß ihr euch wieder zurechtbringen laßt —, das ist es ja, was wir (von Gott) erflehen.',
        10: 'Gerade deshalb schreibe ich euch diesen Brief aus der Ferne, damit ich bei meiner Anwesenheit nicht mit Strenge aufzutreten brauche in der Ausübung der Macht, die mir der Herr verliehen hat zur Erbauung und nicht zur Zerstörung.',
        11: 'Im übrigen, Brüder, freut euch, laßt euch wieder zurechtbringen, nehmt Ermahnung an, seid einträchtig und lebt in Frieden! Dann wird der Gott der Liebe und des Friedens mit euch sein.',
        12: 'Grüßt einander mit dem heiligen Kuß! Es grüßen euch alle Heiligen.',
        14: 'Die Gnade des Herrn Jesus Christus, die Liebe Gottes und die Gemeinschaft des Heiligen Geistes sei mit euch allen!',
    },
}
