NAME = 'Twenty: Twentieth Century New Testament'
BOOK = 'I John'

CHAPTERS = {
    1: {
        1: 'It is of what has been in existence from the Beginning, of what we have heard, of what we have seen with our eyes, of what we watched reverently and touched with our hands — it is about the Word who is the Life that we are now writing.',
        2: 'That Life was made visible, and we have seen it, and now bear our testimony to it, and tell you of that Immortal Life, which was with the Father and was made visible to us.',
        3: 'It is of what we have seen and heard that we now tell you, so that you may have communion with us. And our communion is with the Father and with his Son, Jesus Christ.',
        4: 'And we are writing all this to you that our joy may be complete.',
        5: 'These, then, are the Tidings that we have heard from him and now tell you — ‘God is Light, and Darkness has no place at all in him.’',
        6: 'If we say that we have communion with him, and yet continue to live in the Darkness, we lie, and are not living the Truth.',
        7: 'But, if our lives are lived in the Light, as God himself is in the Light, we have communion with one another, and the Blood of Jesus, his Son, purifies us from all sin.',
        8: 'If we say that there is no sin in us, we are deceiving ourselves, and the Truth has no place in us.',
        9: 'If we confess our sins, God may be trusted, in his righteousness, to forgive us our sins and purify us from all wickedness.',
        10: 'If we say that we have not sinned, we are making God a liar, and his Message has no place in us.',
    },
    2: {
        1: 'My children, I am writing to you to keep you from sinning; but if any one should sin, we have one who can plead for us with the Father — Jesus Christ, the Righteous —',
        2: 'and he is the atoning sacrifice for our sins, and not for ours only, but for those of the whole world besides.',
        3: 'And by this we know that we have learned to know him — by our laying his commands to heart.',
        4: 'The man who says ‘I know Jesus,’ but does not lay his commands to heart, is a liar, and the Truth has no place in him;',
        5: 'but, whenever a man lays his Message to heart, in that man the love of God has indeed reached its perfection. By this we know that we are in union with God —',
        6: 'He who professes to maintain union with God is himself bound to live as Christ lived.',
        7: 'Dear friends, it is no new command that I am writing to you, but an old command, which you have had from the first. That old command is the Message to which you listened.',
        8: 'Yet, again, it is a new Command that I am writing to you — manifest in Christ’s life and in your own — for the Darkness is passing away and the true Light is already shining.',
        9: 'He who says that he is in the Light, and yet hates his Brother, is in the Darkness even now.',
        10: 'He who loves his Brother is always in the Light, and there is nothing within him to cause him to stumble;',
        11: 'while he who hates his Brother is in the Darkness, and is living in the Darkness, and does not know where he is going, because the Darkness prevents his seeing.',
        12: 'I am writing, Children, to you, because your sins have been forgiven you for Christ’s sake.',
        13: 'I am writing, Fathers, to you, because you have learned to know him who has been from the Beginning. I am writing, Young Men, to you, because you have conquered the Evil One. I write, Children, to you, because you have learned to know the Father.',
        14: 'I write, Fathers, to you, because you have learned to know him who has been from the Beginning. I write, Young Men, to you, because you are strong, and God’s Message is always in your hearts, and you have conquered the Evil One.',
        15: 'Do not love the world or what the world can offer. When any one loves the world, there is no love for the Father in him;',
        16: 'for all that the world can offer — the gratification of the earthly nature, the gratification of the eye, the pretentious life — belongs, not to the Father, but to the world.',
        17: 'And the world, and all that it gratifies, is passing away, but he who does God’s will remains for ever.',
        18: 'My Children, these are the last days. You were told that an Anti-Christ was coming; and many Anti-Christs have already arisen. By that we know that these are the last days.',
        19: 'From us, it is true, they went out, but they had never belonged to us; for, if they had belonged to us, they would have remained among us. They left us that it might be made clear that they do not, any of them, belong to us.',
        20: 'You, however, have received consecration from the Holy One.',
        21: 'You all know — But I am not writing to you because you do not know the Truth, but because you do know it, and because nothing false can come from the Truth.',
        22: 'Who is a liar, if not the man who rejects the truth that Jesus is the Christ? He is the Anti-Christ — The man who rejects the Father and the Son.',
        23: 'No one who rejects the Son has found the Father; he who acknowledges the Son has found the Father also.',
        24: 'As for you, let what you were told at the first be always in your thoughts. If, then, what you were told at the first is always in your thoughts, you yourselves will maintain your union both with the Son and with the Father.',
        25: 'And this is what he himself promised us — The Immortal Life!',
        26: 'In writing thus to you, I have in mind those who are trying to mislead you.',
        27: 'But you — you still retain in your hearts that consecration which you received from the Christ, and are not in need of any one to teach you; but, since his consecration of you teaches you about everything, and since it is a real consecration, and no lie, then, as it has taught you, maintain your union with him.',
        28: 'Yes, my Children, maintain your union with Christ, so that, whenever he appears, our confidence may not fail us, and we may not be ashamed to meet him at his coming.',
        29: 'Knowing him to be righteous, you realise that every one who lives righteously has received the new Life from him.',
    },
    3: {
        1: 'Think what love the Father has shown us in allowing us to be called ‘Children of God’; as indeed we are. The reason why the world does not know us is that it has not learned to know him.',
        2: 'Dear friends, we are God’s Children now; what we shall be has not yet been revealed. What we do know is that, when it is revealed, we shall be like Christ; because we shall see him as he is.',
        3: 'And every one who has this hope with regard to Christ tries to make himself pure — as Christ is pure.',
        4: 'Every one who lives sinfully is living in violation of Law. Sin is violation of Law.',
        5: 'And you know that Christ appeared to take away our sins; and in him Sin has no place.',
        6: 'No one who maintains union with him lives in sin; no one who lives in sin has ever really seen him or learned to know him.',
        7: 'My Children, do not let any one mislead you. He who lives righteously is righteous — as Christ is righteous.',
        8: 'He who lives sinfully belongs to the Devil, for the Devil has sinned from the first. It was for this that the Son of God appeared, that he might undo the Devil’s work.',
        9: 'No one who has received the new Life from God lives sinfully, because the very nature of God dwells within him; and he cannot live in sin, because he has received the new Life from God.',
        10: 'By this the Children of God are distinguished from the Children of the Devil — No one who lives unrighteously comes from God, and especially the man who does not love his Brother.',
        11: 'For these are the Tidings that we heard from the first — that we are to love one another.',
        12: 'We must not be like Cain, who belonged to the Evil One and killed his brother. And why did he kill him? It was because his life was bad while his brother’s was good.',
        13: 'Do not wonder, Brothers, if the world hates you.',
        14: 'We know that we have passed out of Death into Life, because we love our Brothers. The man who does not love remains in a state of Death.',
        15: 'Every one who hates his Brother is a murderer; and you know that no murderer has Immortal Life within him.',
        16: 'We have learned to know what love is from this — that Christ laid down his life on our behalf. Therefore we also ought to lay down our lives on behalf of our Brothers.',
        17: 'But, if any one has worldly possessions, and yet looks on while his Brother is in want, and steels his heart against him, how can it be said that the love of God is within him?',
        18: 'My children, do not let our love be mere words, or end in talk; let it be true and show itself in acts.',
        19: 'By that we shall know that we are on the side of the Truth; and we shall satisfy ourselves in God’s sight,',
        20: 'that if our conscience condemns us, yet God is greater than our conscience and knows everything.',
        21: 'Dear friends, if our conscience does not condemn us, then we approach God with confidence,',
        22: 'and we receive from him whatever we ask, because we are laying his commands to heart, and are doing what is pleasing in his sight.',
        23: 'His Command is this — that we should put our trust in the Name of his Son, Jesus Christ, and love one another, in accordance with the Command that he gave us.',
        24: 'And he who lays his commands to heart maintains union with Christ, and Christ with him. And by this we know that Christ maintains union with us — by our possession of the Spirit which he gave us.',
    },
    4: {
        1: 'Dear friends, do not trust every inspiration, but test each inspiration, to see whether it proceeds from God; because many false Prophets have gone out into the world.',
        2: 'This is the way by which to know the inspiration of God — All inspiration that acknowledges Jesus Christ as come in our human nature is from God;',
        3: 'while all inspiration that does not acknowledge Jesus is not inspiration from God. It is the inspiration of the Anti-Christ; you have heard that it was to come, and it is now already in the world.',
        4: 'You, my Children, come from God, and you have successfully resisted such men as these, because he who is in you is greater than he who is in the world.',
        5: 'Those men belong to the world; and therefore they speak as the world speaks, and the world listens to them.',
        6: 'We come from God. He who knows God listens to us; the man who does not come from God does not listen to us. By that we may know the true inspiration from the false.',
        7: 'Dear friends, let us love one another, because Love comes from God; and every one who loves has received the new Life from God and knows God.',
        8: 'He who does not love has not learned to know God; for God is Love.',
        9: 'The love of God was revealed to us by his sending his only Son into the world, that we might find Life through him.',
        10: 'His love is seen in this — not in our having loved God, but in his loving us and sending his Son to be an atoning sacrifice for our sins.',
        11: 'Dear friends, since God loved us thus, we, surely, ought to love one another.',
        12: 'No human eyes have ever seen God, yet, if we love one another, God remains in union with us, and his love attains its perfection in us.',
        13: 'We know that we remain in union with him, and he with us, by this — by his having given us some measure of his Spirit.',
        14: 'Moreover, our eyes have seen — and we are testifying to the fact — that the Father has sent the Son to be the Saviour of the world.',
        15: 'Whoever acknowledges that Jesus Christ is the Son of God — God remains in union with that man, and he with God.',
        16: 'And, moreover, we have learned to know, and have accepted as a fact, the love which God has for us. God is Love; and he who lives in love lives in God, and God in him.',
        17: 'It is through this that love has attained its perfection in us, so that we may have confidence on the Day of Judgment, because what Christ is that we also are in this world.',
        18: 'There is no fear in love. No! Love, when perfect, drives out fear, for fear implies punishment, and the man who feels fear has not attained to perfect love.',
        19: 'We love, because God first loved us.',
        20: 'If a man says ‘I love God,’ and yet hates his Brother, he is a liar; for the man who does not love his Brother, whom he has seen, cannot love God, whom he has not seen.',
        21: 'Indeed, we have this Command from God — ‘He who loves God must also love his Brother.’',
    },
    5: {
        1: 'Every one who believes that Jesus is the Christ has received the new Life from God; and every one who loves him who gave that Life loves him who has received it.',
        2: 'By this we know that we love God’s Children — when we love God and carry out his commands.',
        3: 'For to love God is to lay his commands to heart; and his commands are not burdensome,',
        4: 'because all that has received the new Life from God conquers the world. And this is the power that has conquered the world — our faith!',
        5: 'Who is he that conquers the world but the man who believes that Jesus is the Son of God?',
        6: 'He it is whose Coming was attested by means of Water and Blood — Jesus Christ himself; not by Water only, but by Water and by Blood. And there is the Spirit also to bear testimony, and the Spirit is Truth itself.',
        7: 'It is a three-fold testimony —',
        8: 'that of the Spirit, the Water, and the Blood — and these three are at one.',
        9: 'We accept the testimony of men, but God’s testimony is still stronger; and there is the testimony of God — the fact that he has already borne testimony about his Son.',
        10: 'He who believes in the Son of God has that testimony within him. He who does not believe God has made God a liar, by refusing to believe in that testimony which he has borne about his Son.',
        11: 'And that testimony is that God gave us Immortal Life, and that this Life is in his Son.',
        12: 'He who finds the Son finds Life; he who does not find the Son of God does not find Life.',
        13: 'I write this to you, that you may realise that you have found Immortal Life — you who believe in the Name of the Son of God.',
        14: 'And this is the confidence with which we approach him, that whenever we ask anything that is in accordance with his will, he listens to us.',
        15: 'And if we realise that he listens to us — whatever we ask — we realise that we have what we have asked from him.',
        16: 'If any one sees his Brother committing some sin that is not a deadly sin, he will ask, and so be the means of giving Life to him — to any whose sin is not deadly. There is such a thing as deadly sin; about that I do not say that a man should pray.',
        17: 'Every wrong action is sin, and there is sin that is not deadly.',
        18: 'We know that no one who has received the new Life from God lives in sin. No, he who has received the new Life from God keeps the thought of God in his heart, and then the Evil One does not touch him.',
        19: 'We realise that we come from God, while all the world is under the influence of the Evil One.',
        20: 'We realise, too, that the Son of God has come among us, and has given us the discernment to know the True God; and we are in union with the True God by our union with his Son, Jesus Christ. He is the True God and he is Immortal Life.',
        21: 'My Children, guard yourselves against false ideas of God.',
    },
}
