NAME = 'FreLXXGiguet: Traduction de la LXX par Pierre GIGUET et autres traducteurs, 1872.'
BOOK = 'Habakkuk'

CHAPTERS = {
    1: {
        1: 'Vision d’Habacuc le prophète.',
        2: 'Jusques à quand, Seigneur, crierai-je sans que vous m’écoutiez? jusques à quand vous crierai-je que l’on me fait violence? Ne me sauverez-vous pas?',
        3: 'Pourquoi m’avez-vous affligé et m’avez-vous donné la douleur de voir la misère et l’impiété? Je suis en procès, et le juge reçoit des présents.',
        4: 'À cause de cela, la loi a été déchirée, et le jugement n’arrivera pas à bonne fin, parce que l’impie opprime le juste, et la sentence sera torturée.',
        5: 'Voyez, contempteurs de la loi, regardez et admirez ces merveilles, et soyez anéantis: car, de vos jours, je vais faire une œuvre que vous ne croirez pas, quoiqu’on vous l’annonce.',
        6: 'Voilà que je vais susciter les Chaldéens, nation cruelle et rapide, qui marche sur les plaines de la terre, pour prendre possession de tentes qui ne sont point les siennes.',
        7: 'Redoutable et fameuse, c’est d’elle que le jugement procédera; tout son butin proviendra d’elle-même.',
        8: 'Et ses chevaux s’élanceront plus agiles que le léopard; ils courront plus rapides que les loups de l’Arabie. Et ses cavaliers sortiront à cheval, et ils prendront de loin leur élan, et ils se déploieront comme l’aigle ardent à dévorer sa proie.',
        9: 'La perdition tombera sur les impies qui leur feront face, et leur tiendront tête; et l’envahisseur emmènera des captifs aussi nombreux que les grains de sable.',
        10: 'Et il se raillera des rois, et les tyrans seront pour lui des jouets, et il rira de chaque forteresse, et il l’entourera de levées de terre, et il la prendra de force.',
        11: 'Alors son esprit changera, et il se transformera, et il fera pitié; telle est la force de mon Dieu.',
        12: 'Seigneur, mon Dieu et mon Saint, n’êtes-vous pas dès le commencement? Est-ce que nous mourrons? Vous avez établi ces choses pour le jugement, et vous m’avez formé, Seigneur, pour annoncer votre châtiment.',
        13: 'L’œil du Seigneur est trop pur pour regarder le mal et s’arrêter sur les labeurs de l’affliction. Pourquoi, Seigneur, considérez-vous ceux qui vous méprisent? Pourquoi gardez-vous le silence quand l’impie dévore le juste?',
        14: 'Traiterez-vous les hommes comme les poissons de la mer, ou comme les reptiles qui n’ont point de guide?',
        15: 'Il a pris toute l’espèce à l’hameçon; il en a',
        16: 'À cause de cela, il sacrifiera à sa nasse, il encensera son filet, parce qu’avec leur aide il aura engraissé sa part, et recueilli des aliments de choix.',
        17: 'Et, à cause de cela, il jettera encore son filet, et ne se fera jamais faute de tuer les nations.',
    },
    2: {
        1: 'Je me tiendrai en garde, et je monterai sur une roche, et je veillerai pour savoir ce qu’on dira contre moi, et ce que je répondrai quand je serai repris.',
        2: 'Et le Seigneur me parla, et il me dit: Écris ta vision, écris - la clairement sur une tablette, afin qu’on la lise couramment.',
        3: 'Car ta vision est véritable; elle se réalisera au temps marqué; elle ne sera point vaine. S’il ne vient pas encore, attends-le; car sûrement il viendra et ne tardera point.',
        4: 'Celui qui se retire de moi, mon âme ne se complaira pas avec lui; le juste vivra de sa foi en moi.',
        5: 'L’homme présomptueux, méprisant, imposteur, n’arrivera point à ses fins; celui qui a rendu son âme vaste comme l’enfer est aussi insatiable que la mort; il réunira sous lui toutes les nations, et il recevra sous lui tous les peuples.',
        6: 'Mais toutes ces choses ne feront-elles pas de lui un sujet d’histoires et de récits qu’on se répétera? On dira Malheur à l’homme qui, sans se lasser, accumule les biens d’autrui, et fait cruellement sentir le poids de son collier!',
        7: 'Car soudain s’élèveront contre toi des gens qui te mordront, et autour de toi veilleront des assassins, et tu seras pour eux une proie.',
        8: 'Parce que tu as pillé une multitude de nations, les peuples qui restent encore te pilleront à leur tour, à cause du sang des hommes, à cause de tes impiétés contre la terre, contre la ville et ses habitants.',
        9: 'Malheur à celui qui, en sa maison, a de mauvaises convoitises, qui veut placer haut son nid, pour se délivrer de la main du malheur!',
        10: 'Tu as médité la honte de ta maison, tu as épuisé beaucoup de peuples, et ton âme a péché.',
        11: 'Aussi la pierre des murailles criera-t-elle contre toi, et l’escarbot du haut des solives lui fera écho.',
        12: 'Malheur à celui qui bâtit une ville avec le sang, et qui la fonde avec l’iniquité!',
        13: 'Ces choses ne sont-elles pas du Seigneur tout-puissant? maints peuples forts ont été épuisés par le feu, et maintes nations ont défailli,',
        14: 'Pour que la terre soit remplie de la connaissance de la gloire du Seigneur, qui la couvrira comme l’eau.',
        15: 'Malheur à celui qui donne à boire à son ami de la lie de vin, et l’enivre pour voir dans ses cavernes!',
        16: 'Toi aussi, bois, au lieu de gloire, la plénitude de la honte; que ton cœur s’agite et tremble: te voilà',
        17: 'Car l’impiété du Liban te couvrira, et les ravages des bêtes fauves te feront trembler, à cause du sang des hommes et de tes impiétés contre la terre, contre la ville et tous ses habitants.',
        18: 'À quoi peut servir une statue qu’eux-mêmes ont sculptée? on l’a jetée en fonte, apparence mensongère, et, pour faire une idole muette, l’artiste a eu foi en l’œuvre qu’il a façonnée.',
        19: 'Malheur à celui qui dit au bois: Sors de ton assoupissement, réveille-toi; et à la pierre: Lève-toi; car ce n’est qu’une image; c’est de l’or ou de l’argent battus au marteau, et il n’y a en cette œuvre aucun esprit.',
        20: 'Mais le Seigneur réside en son saint temple; que toute la terre révère son visage!',
    },
    3: {
        1: 'Seigneur, j’ai entendu votre voix, et j’ai eu crainte.',
        2: 'J’ai considéré vos œuvres, et je me suis extasié. Entre deux animaux vous vous manifesterez; quand les années seront proches, on vous connaîtra; quand les temps seront venus, vous apparaîtrez; quand mon âme est troublée de votre colère, souvenez-vous de votre miséricorde.',
        3: 'Dieu viendra de Théman, et le Saint de la montagne ténébreuse de Pharan. Sa vertu est le vêtement des cieux, et la terre est pleine de sa louange.',
        4: 'Sa splendeur sera comme la lumière; il a dans sa main des cornes (de puissance), et de la force il a fait un puissant amour.',
        5: 'Devant sa face ira une parole; elle cheminera dans les plaines; sur ses pieds',
        6: 'Il s’est dressé, et la terre en a tremblé; il a regardé, et les nations se sont évanouies. Les montagnes ont été violemment agitées; les collines se sont fondues, sous les pas de sa marche éternelle.',
        7: 'À cause des troubles, j’ai vu les tentes des Éthiopiens renversées; les tentes de la terre de Madian seront aussi frappées d’épouvante.',
        8: 'Seigneur, est-ce contre les fleuves que vous êtes irrité? Est-ce que votre colère s’en prend aux fleuves? Attaquerez-vous la mer? car vous êtes monté sur votre char, et vos chevaux amènent le salut.',
        9: 'Tu as fortement tendu ton arc contre les sceptres, dit le Seigneur. Le cours des fleuves sera déchiré.',
        10: 'Les peuples vous verront, Seigneur, et ils auront des douleurs comme celles de l’enfantement. Quand vous détruisiez la voie par une inondation, l’abîme a fait entendre sa voix, et il a élevé ses vagues vers vous.',
        11: 'Le soleil s’est levé; la lune s’est tenue au lieu qui lui est prescrit: vos rayons s’avanceront dans la lumière, à la lueur des éclairs qui jaillissent de vos armes.',
        12: 'Par vos menaces, vous abaisserez la terre, et dans votre courroux vous abattrez les nations.',
        13: 'Vous êtes venu pour le salut de votre peuple, pour sauver votre Christ; vous enverrez la mort sur la tête des impies; vous les avez chargés de chaînes jusqu’au cou.',
        14: 'Vous avez frappé de stupeur les bêtes des puissants; ils en trembleront; ils laisseront voir leur frein en ouvrant la bouche, comme un pauvre qui mange en se cachant.',
        15: 'Et, monté sur vos chevaux, vous êtes entré dans la mer, et ils en ont troublé l’eau profonde.',
        16: 'J’ai veillé, et mes entrailles ont frémi au son de la prière de mes lèvres, et l’effroi est entré dans mes os, et tout mon être a été bouleversé. Je me reposerai au jour de l’affliction, et je monterai chez le peuple où je suis passager.',
        17: 'Car alors le figuier ne portera pas de fruits; il n’y aura pas de raisin à la vigne; l’œuvre de l’olivier sera trompeuse, et les champs ne produiront pas de nourriture. Les brebis manqueront de fourrage, et il n’y aura pas de bœufs à la crèche.',
        18: 'Pour moi, je tressaillirai dans le Seigneur; je mettrai ma joie en Dieu, mon sauveur.',
        19: 'Le Seigneur mon Dieu est ma force; il placera mes pieds sur une base inébranlable; il m’a fait monter sur les hautes cimes, pour chanter en son honneur un chant de triomphe.',
    },
}
