NAME = 'FreSynodale1921: Le Nouveau Testament Version Synodale 1921 et le livre des Psaumes'
BOOK = 'II Thessalonians'

CHAPTERS = {
    1: {
        1: "Paul, Silvain et Timothée, à l'Église des Thessaloniciens, qui est en Dieu, notre Père, et en Jésus-Christ, le Seigneur.",
        2: 'Que la grâce et la paix vous soient données de la part de Dieu, notre Père, et du Seigneur Jésus-Christ!',
        3: "Nous devons, frères, rendre sans cesse grâces à Dieu à votre sujet; et cela est bien juste, puisque votre foi fait de grands progrès, et que l'amour que vous avez tous les uns pour les autres augmente de plus en plus.",
        4: 'Aussi, nous nous glorifions à votre sujet auprès des Eglises de Dieu, à cause de votre patience et de votre foi dans toutes les persécutions et les afflictions que vous endurez.',
        5: 'Il y a là une preuve du juste jugement de Dieu, qui veut vous rendre dignes de son royaume, pour lequel vous souffrez.',
        6: "N'est-il pas, en effet, conforme à la justice de Dieu, de rendre l'affliction à ceux qui vous affligent,",
        7: 'et de vous donner, à vous qui êtes affligés, du repos avec nous,',
        8: "lorsque le Seigneur Jésus apparaîtra, venant du ciel, avec les anges de sa puissance, au milieu des flammes de feu, pour faire justice de ceux qui ne connaissent point Dieu et qui n'obéissent pas à l'Évangile de notre Seigneur Jésus-Christ?",
        9: "Ils seront punis d'une perdition éternelle, loin de la face du Seigneur et de la gloire de sa puissance,",
        10: 'quand il viendra, en ce jour-là, pour être glorifié dans ses saints et admiré dans tous ceux qui auront cru; car vous avez cru au témoignage que nous avons rendu devant vous.',
        11: "C'est pourquoi, nous prions sans cesse pour vous, afin que notre Dieu vous rende dignes de l'appel qu'il vous a adressé, et qu'il accomplisse en vous, avec puissance, tous les miséricordieux desseins de sa bonté et l'oeuvre de la foi;",
        12: 'en sorte que le nom de notre Seigneur Jésus soit glorifié en vous, et vous en lui, selon la grâce de notre Dieu et du Seigneur Jésus-Christ.',
    },
    2: {
        1: "En ce qui concerne l'avènement de notre Seigneur-Jésus-Christ et notre réunion avec lui, nous vous en prions, frères,",
        2: "ne vous laissez pas si promptement troubler l'esprit, ni alarmer par une prétendue inspiration, par quelque parole ou quelque lettre qui nous serait attribuée, comme si le jour du Seigneur était proche.",
        3: "Que personne ne vous séduise en aucune manière. Car il faut qu'auparavant l'apostasie soit arrivée, et qu'on ait vu paraître l'homme de l'iniquité, le fils de la perdition,",
        4: "l'adversaire qui, s'élevant au-dessus de tout ce qu'on appelle Dieu ou qu'on adore, va jusqu'à s'asseoir dans le temple de Dieu, se faisant passer lui-même pour Dieu.",
        5: "Ne vous souvient-il pas que je vous disais ces choses, lorsque j'étais encore auprès de vous?",
        6: "Et maintenant, vous savez bien ce qui lui fait obstacle, pour qu'il ne soit manifesté qu'en son temps.",
        7: "Car déjà le mystère de l'iniquité est à l'oeuvre; seulement, il faut que celui qui lui fait encore obstacle soit écarté.",
        8: "Et alors sera manifesté l'impie, que le Seigneur Jésus détruira par le souffle de sa bouche, et qu'il anéantira par l'éclat de son avènement.",
        9: 'Cet impie apparaîtra avec la puissance de Satan, opérant toutes sortes de miracles, de signes et de prodiges menteurs,',
        10: "et recourant à toutes les séductions de l'injustice pour la perte de ceux qui périssent, parce qu'ils n'ont pas ouvert leur coeur à l'amour de la vérité, qui les aurait sauvés.",
        11: "C'est pour cela que Dieu leur envoie une puissance d'égarement qui les fait croire au mensonge,",
        12: "afin que tous ceux qui n'ont pas cru à la vérité, mais qui ont pris plaisir à l'injustice, soient soumis à son jugement.",
        13: "Quant à nous, frères aimés du Seigneur, nous devons sans cesse rendre grâces à Dieu à votre sujet, parce qu'il vous a choisis, dès le commencement, pour vous donner le salut, par la sanctification de l'Esprit et par la foi en la vérité.",
        14: "C'est à cela aussi qu'il vous a appelés par notre Évangile, pour que vous possédiez la gloire de notre Seigneur Jésus-Christ.",
        15: 'Ainsi donc, frères, demeurez fermes, et retenez les enseignements que nous vous avons transmis, soit de vive voix, soit par notre lettre.',
        16: 'Que notre Seigneur Jésus-Christ lui-même, et Dieu, notre Père, qui nous a aimés et nous a donnés par sa grâce une consolation éternelle et une bonne espérance,',
        17: 'consolent vos coeurs et vous affermissent en toute bonne oeuvre et en toute bonne parole!',
    },
    3: {
        1: "Au reste, frères, priez pour nous, afin que la parole du Seigneur se répande librement, qu'elle soit glorifiée partout, comme elle l'est parmi vous,",
        2: "et que nous soyons délivrés des hommes fâcheux et méchants; car tous n'ont pas la foi.",
        3: 'Le Seigneur est fidèle; il vous affermira et vous gardera du Malin.',
        4: 'Nous avons à votre égard cette confiance dans le Seigneur, que vous faites et que vous ferez les choses que nous vous recommandons.',
        5: 'Que le Seigneur dispose vos coeurs à aimer Dieu et à attendre patiemment Jésus-Christ!',
        6: "Frères, nous vous recommandons, au nom de notre Seigneur Jésus-Christ, de vous tenir à l'écart de tout frère qui ne sait pas régler sa conduite, et qui ne suit pas les enseignements que vous avez reçus de nous.",
        7: "Vous savez vous-mêmes ce que vous devez faire pour nous imiter; car c'est une vie bien réglée que nous avons menée parmi vous,",
        8: "et nous n'avons mangé gratuitement le pain de personne, mais nous avons travaillé nuit et jour, dans la fatigue et dans la peine, pour n'être à charge à aucun de vous.",
        9: "Non pas que nous n'en eussions le droit, mais nous avons voulu nous donner à vous en exemple, afin que vous nous imitiez.",
        10: "Aussi bien, lorsque nous étions auprès de vous, nous vous le déclarions expressément: si quelqu'un ne veut pas travailler, il ne doit pas non plus manger.",
        11: "Nous apprenons, en effet, que certains d'entre vous ont une conduite irrégulière et qu'au lieu de travailler, ils se mêlent de choses qui ne les regardent pas.",
        12: "Nous invitons ces gens-là et nous les exhortons, au nom du Seigneur Jésus-Christ, à travailler paisiblement, afin de manger le pain qu'ils ont eux-mêmes gagné.",
        13: 'Pour vous, frères, ne vous lassez pas de faire le bien.',
        14: "Et si quelqu'un n'obéit pas à ce que nous vous disons dans cette lettre, notez-le, et n'ayez aucune relation avec lui, afin qu'il en ait de la confusion.",
        15: 'Toutefois, ne le regardez pas comme un ennemi, mais avertissez-le comme un frère.',
        16: 'Que le Seigneur de la paix vous donne lui-même la paix en tout temps, de toute manière! Que le Seigneur soit avec vous tous!',
        17: "La salutation est de ma main, à moi, Paul. C'est là ma signature dans toutes mes lettres: c'est ainsi que j'écris.",
        18: 'Que la grâce de notre Seigneur Jésus-Christ soit avec vous tous!',
    },
}
