NAME = 'SloKJV: Slovenian translation of Holy Bible King James Version (1769)'
BOOK = 'II Thessalonians'

CHAPTERS = {
    1: {
        1: 'Pavel in Silván ter Timótej, cerkvi Tesaloníčanov v Bogu, našem Očetu in Gospodu Jezusu Kristusu:',
        2: '›Milost vam in mir od Boga, našega Očeta in Gospoda Jezusa Kristusa.‹',
        3: 'Dolžni smo, da se vedno zahvaljujemo Bogu za vas, bratje, kakor se spodobi, zato ker ta vaša vera silno raste in je ljubezen vsakogar izmed vas vseh do drug drugega obilna,',
        4: 'tako, da se mi sami ponašamo z vami po Božjih cerkvah, zaradi vaše potrpežljivosti in vere, v vseh vaših preganjanjih in stiskah, ki jih prenašate;',
        5: 'kar je razpoznaven simbol pravične Božje sodbe, da boste lahko šteti vredne Božjega kraljestva, za katerega tudi trpite.',
        6: 'Čeprav je pri Bogu pravična stvar, da poplača stisko tem, ki vas stiskajo;',
        7: 'vam pa, ki ste stiskani, počitek z nami, ko se bo Gospod Jezus, razodet iz nebes, s svojimi mogočnimi angeli,',
        8: 'v plamenečem ognju maščeval na teh, ki ne poznajo Boga in ne ubogajo evangelija našega Gospoda Jezusa Kristusa;',
        9: 'ki bodo kaznovani z večnim uničenjem proč od Gospodove prisotnosti in proč od slave njegove moči;',
        10: '§ ko bo prišel, da bo proslavljen v svojih svetih in da bo občudovan v vseh teh, ki verujejo (ker so verovali našemu pričevanju med vami) na tisti dan.',
        11: 'Zatorej tudi vedno molimo za vas, da vas bo naš Bog imel za vredne te poklicanosti in izpolnite vso dobro voljo njegove dobrote ter delo vere v môči;',
        12: 'da bo v vas lahko proslavljeno ime našega Gospoda Jezusa Kristusa in vi v njem, glede na milost našega Boga in Gospoda Jezusa Kristusa.',
    },
    2: {
        1: 'Torej vas rotimo, bratje, pri prihodu našega Gospoda Jezusa Kristusa in pri našem zbiranju k njemu,',
        2: 'da ne boste kmalu pretreseni v mišljenju ali bili vznemirjeni, niti po duhu, niti z besedo, niti s pismom kot od nas, kakor da je blizu Kristusov dan.',
        3: 'Nobenemu človeku ne pustite, da vas na kakršenkoli način zavede, kajti ta dan ne bo prišel, razen če ne bo najprej prišlo odpadanje in da se razodene grešen človek, sin pogube,',
        4: 'ki nasprotuje in se povišuje nad vse, kar se imenuje Bog ali kar se obožuje, tako da se le-ta kakor Bog usede v Božji tempelj in se razkazuje, da je Bog.',
        5: 'Se ne spomnite, da ko sem bil še z vami, sem vam te stvari povedal?',
        6: 'Sedaj poznate, kaj ga zadržuje, da bi se lahko razodel ob svojem času.',
        7: 'Kajti skrivnost krivičnosti že deluje. Samo tisti, ki sedaj ovira, bo oviral, dokler ne bo umaknjen s poti.',
        8: 'In takrat bo razodet ta Zlobni, ki ga bo Gospod pokončal z dihom svojih ust in uničil s sijajem svojega prihoda.',
        9: 'Torej njega, katerega prihod je po Satanovem delovanju z vso močjo in znamenji ter lažnimi čudeži',
        10: 'in z vso varljivostjo nepravičnosti v teh, ki umirajo, zato ker niso sprejeli ljubezni do resnice, da bi bili lahko rešeni.',
        11: 'In zaradi tega razloga jim bo Bog poslal močno zablodo, da bi verjeli laži;',
        12: 'da bodo lahko obsojeni vsi, ki niso verjeli resnici, temveč so uživali v nepravičnosti.',
        13: 'Toda mi smo dolžni, da se nenehno zahvaljujemo Bogu za vas, od Gospoda ljubljeni bratje, ker vas je Bog od začetka izbral za rešitev duše s posvečenjem Duha in prepričanjem v resnico;',
        14: 'kamor vas je poklical po našem evangeliju, k doseganju slave našega Gospoda Jezusa Kristusa.',
        15: 'Torej bratje, stojte trdno in držite se izročil, o katerih ste bili poučeni, bodisi z besedo ali našo poslanico.',
        16: 'Torej sam naš Gospod Jezus Kristus in Bog, celó naš Oče, ki nas je ljubil in nam je po milosti dal večno tolažbo ter dobro upanje,',
        17: '[naj] tolaži vaša srca ter vas utrdi v vsaki dobri besedi in delu.',
    },
    3: {
        1: 'Končno, bratje, molíte za nas, da bi Gospodova beseda imela prosto pot in bi bila proslavljena, tako kakor je pri vas,',
        2: 'in da bi bili mi lahko rešeni pred nerazumnimi in zlobneži, kajti vsi ljudje nimajo vere.',
        3: 'Toda Gospod je zvest, ki vas bo utrdil in vas varoval pred zlom.',
        4: 'Glede vas pa imamo zaupanje v Gospodu, da tako delate, kakor boste delali stvari, ki vam jih zapovedujemo.',
        5: 'In Gospod naj vodi vaša srca v Božjo ljubezen in v potrpežljivo čakanje na Kristusa.',
        6: 'Torej vam naročamo, bratje, v imenu našega Gospoda Jezusa Kristusa, da se oddaljite od vsakega brata, ki živi neredno in ne po izročilu, ki ga je prejel od nas.',
        7: 'Kajti vi sami veste, kako nas morate posnemati, kajti med vami se nismo vedli neredno',
        8: 'niti nismo zastonj jedli kruha kateregakoli človeka, temveč smo noč in dan delali z muko in garanjem, da ne bi bili nikomur izmed vas v breme.',
        9: 'Ne, ker ne bi imeli avtoritete, temveč da sebe naredimo za zgled vam, da bi nas posnemali.',
        10: 'Kajti celó, ko smo bili z vami, smo vam zapovedali to, da če kdorkoli noče delati, naj tudi ne bi jedel.',
        11: 'Kajti slišimo, da so med vami nekateri, ki živijo neredno, ki sploh ne delajo, temveč so vtikljivci.',
        12: 'Torej tem, ki so takšni, velevamo in jih spodbujamo pri našem Gospodu Jezusu Kristusu, da v spokojnosti delajo in jedo svoj lastni kruh.',
        13: 'Toda vi, bratje, ne bodite izmučeni v počenjanju dobrega.',
        14: 'In če kdorkoli ni poslušen naši besedi v tej poslanici, tega človeka si zaznamujte in se ne družite z njim, da bo osramočen.',
        15: 'Vendar ga ne imejte za sovražnika, ampak ga opominjajte kakor brata.',
        16: 'Torej sam Gospod miru [naj] vam vsekakor vedno daje mir. Gospod bodi z vami vsemi.',
        17: 'Pozdrav od Pavla z mojo lastno roko, kar je simbol v vsaki poslanici. Tako pišem.',
        18: '§ Milost našega Gospoda Jezusa Kristusa bodi z vami vsemi. Amen. [Druga poslanica Tesaloníčanom je bila napisana iz Aten.]',
    },
}
